#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

DIR=$(dirname $0)

. "$DIR/common"

# KMS_WEBUI_PORT from impala config
export KMS_HTTP_PORT=$KMS_WEBUI_PORT

# Path to the file where the catalina server writes the PID
export CATALINA_PID=$PID_DIR/kms

# Versions of OpenJDK starting at 8u171 will fail unless
# this Java property is set. See https://issues.apache.org/jira/browse/HDFS-13494
# Note that this omits some of the JDK defaults, because KMS only
# uses this one.
export HADOOP_OPTS="${HADOOP_OPTS:-} -Djceks.key.serialFilter=org.apache.hadoop.crypto.key.JavaKeyStoreProvider*"

function start {

  if [[ -e "$CATALINA_PID" ]]; then
    rm "$CATALINA_PID"
  fi

  do_start $HADOOP_HOME/bin/hadoop kms &> "$LOG_DIR/$(basename $0).out"
}

$1
