#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


# This script runs the Impala shell. Python is required.
#
# This script assumes that the supporting library files for the Impala shell are
# rooted in either the same directory that this script is in, or in a directory
# in the environment variable ${IMPALA_SHELL_HOME}.
#
# The required directories are:
# gen-py/ -- containing the Python thrift stubs for connecting to Impalad
# lib/ -- containing the Hive Beeswax libraries; note this directory exists only in the
#         shell tarball, not the Impala repository, see make_shell_tarball.sh for details
# ext-py${VERSION}/ -- containing all the eggs for the modules packaged with the shell.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SHELL_HOME=${IMPALA_SHELL_HOME:-${SCRIPT_DIR}}

# Set the envrionment's locale settings to allow for utf-8 compatibility
export LC_CTYPE=${LC_CTYPE:-en_US.UTF-8}

# User can configure EGG_CACHE by setting PYTHON_EGG_CACHE.
# By default it is set to a per-user temporary location,
# which follows what hue does.
PYTHON_EGG_CACHE=${PYTHON_EGG_CACHE:-/tmp/impala-shell-python-egg-cache-${USER}}

if [ ! -d ${PYTHON_EGG_CACHE} ]; then
  mkdir ${PYTHON_EGG_CACHE}
fi

# Select python version; prefer 2, use 3 if 2's absent. Allow override with envvar
PYTHON_EXE="${IMPALA_PYTHON_EXECUTABLE:-python}"
if ! command -v "${PYTHON_EXE}" > /dev/null; then
  PYTHON_EXE=python3
fi

# External module eggs are located in /ext-py, append them to the PYTHONPATH
# Loads eggs based on Python version
PYTHON_VERSION=$("${PYTHON_EXE}" -c 'import sys; print(sys.version_info[0])')
EGG_PATH=''
for EGG in $(ls ${SHELL_HOME}/ext-py${PYTHON_VERSION}/*.egg); do
   EGG_PATH="${EGG}:${EGG_PATH}"
done

PYTHONPATH="${EGG_PATH}${SHELL_HOME}/gen-py:${SHELL_HOME}/lib:${PYTHONPATH}" \
  PYTHONIOENCODING='utf-8' exec ${PYTHON_EXE} ${SHELL_HOME}/impala_shell.py "$@"
