#!/bin/bash

set -e

DIR=$(dirname $0)

. "$DIR/common"
. "$DIR/kudu-common"   # Sets KUDU_COMMON_ARGS

function start {
  do_start "$KUDU_BIN_DIR"/kudu-master \
      -flagfile "$NODE_DIR"/etc/kudu/master.conf \
      "${KUDU_COMMON_ARGS[@]}"
}

$1
