#!/bin/bash

set -e

DIR=$(dirname $0)

. "$DIR/common"
. "$DIR/kudu-common"   # Sets KUDU_BIN_DIR

function start {
  # Add a dummy flag with value IBelongToTheMiniCluster so the process is easily
  # identifiable in case the pid file is removed.
  do_start "$KUDU_BIN_DIR"/kudu-master \
      -flagfile "$NODE_DIR"/etc/kudu/master.conf \
      -vmodule IBelongToTheMiniCluster
}

$1
