# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import base64
import datetime
import os
import uuid
import xml.etree.ElementTree as ET
import zlib

try:
  from urllib.parse import parse_qs, urlparse
  from urllib.request import HTTPErrorProcessor, build_opener, Request
except ImportError:
  from urllib2 import HTTPErrorProcessor, build_opener, Request
  from urlparse import parse_qs, urlparse

from tests.common.custom_cluster_test_suite import CustomClusterTestSuite


class NoRedirection(HTTPErrorProcessor):
  """Allows inspecting http redirection responses. """

  def http_response(self, request, response):  # noqa: U100
    return response


def format_time(time):
  """ Converts datetimes to the format expected in SAML2 XMLs. """
  return time.strftime("%Y-%m-%dT%H:%M:%SZ")


def encode_if_needed(value):
  """ Encodes the value to bytes if needed, depending on the python version. """
  return value if isinstance(value, bytes) else value.encode('utf-8')


class TestSamlBase(CustomClusterTestSuite):
  """Base class for SAML SSO tests containing common functionality."""

  CERT_DIR = "%s/testdata/authentication" % os.environ['IMPALA_HOME']
  IDP_URL = "https://localhost:8443/simplesaml/saml2/idp/SSOService.php"
  ASSERTATION_ERROR_MESSAGE = \
      "SAML assertion could not be validated. Check server logs for more details."

  # Metric names for SAML authentication
  HS2_SAML_SUCCESS_METRIC = \
      "impala.thrift-server.hiveserver2-http-frontend.total-saml-auth-success"
  HS2_SAML_FAILURE_METRIC = \
      "impala.thrift-server.hiveserver2-http-frontend.total-saml-auth-failure"
  WS_SAML_SUCCESS_METRIC = "impala.webserver.total-saml-auth-success"
  WS_SAML_FAILURE_METRIC = "impala.webserver.total-saml-auth-failure"

  # Common SAML configuration arguments (keystore and entity settings)
  SSO_ARGS_COMMON = ("--saml2_keystore_path=%s/saml2_sso.jks "
                     "--saml2_keystore_password_cmd=\"echo -n storepass\" "
                     "--saml2_private_key_password_cmd=\"echo -n keypass\" "
                     "--saml2_sp_entity_id=org.apache.impala "
                     "--saml2_want_assertations_signed=false "
                     "--saml2_allow_without_tls_debug_only=true "
                     "--cookie_require_secure=false "
                     "--saml2_ee_test_mode=true"
                     % CERT_DIR)

  # A sample 'AttributeStatement' part of authn response (generated by simplesaml php).
  # Note: ATTRIBUTE_STATEMENT is set at the end of the file after templates are defined
  ATTRIBUTE_STATEMENT = None

  @classmethod
  def hs2_http_port(cls):
    return cls.pytest_config().option.impalad_hs2_http_port

  def _parse_authn_request(self, saml_req_xml):
    """Parse SAML AuthnRequest XML and extract request ID."""
    root = ET.fromstring(saml_req_xml)
    assert root.tag == "{urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest"
    return root.attrib["ID"]

  def _parse_redirection_response_common(self, response):
    """Parse common parts of redirection response."""
    assert response.getcode() == 302
    new_url = response.info()["location"]
    assert new_url.startswith(TestSamlBase.IDP_URL)
    query_part = urlparse(new_url).query
    query = parse_qs(query_part)
    assert "RelayState" in query, query
    relay_state = query["RelayState"][0]
    assert relay_state is not None
    saml_req = query["SAMLRequest"][0]
    assert saml_req is not None
    saml_req_xml = zlib.decompress(base64.urlsafe_b64decode(saml_req), -15)
    return relay_state, saml_req_xml

  @staticmethod
  def _generate_authn_response(request_id, attributes_xml, destination, recipient,
                               not_before=None, not_on_or_after=None, issuer=None):
    """Generate SAML AuthnResponse with given parameters.

    Args:
      request_id: The ID from the AuthnRequest to respond to
      attributes_xml: XML string containing attribute statements
      destination: The destination URL
      recipient: The recipient URL
      not_before: Optional override for notBefore timestamp (for testing invalid times)
      not_on_or_after: Optional override for notOnOrAfter timestamp (for testing expired)
      issuer: Optional override for issuer (for testing untrusted IDP)
    """
    now = datetime.datetime.utcnow()
    if not_before is None:
      not_before = format_time(now)
    if not_on_or_after is None:
      not_on_or_after = format_time(now + datetime.timedelta(hours=2))
    if issuer is None:
      issuer = "https://localhost:8443/simplesaml/saml2/idp/metadata.php"

    return SAML_RESPONSE_TEMPLATE.format(request_id=request_id,
                                         not_on_or_after=not_on_or_after,
                                         not_before=not_before,
                                         issue_instant=format_time(now),
                                         attribute_statement=attributes_xml,
                                         msg_id=str(uuid.uuid4()),
                                         assertation_id=str(uuid.uuid4()),
                                         destination=destination,
                                         recipient=recipient,
                                         issuer=issuer)

  def _test_common_protocol_checks(self):
    """Common protocol checks for both test classes."""
    # Test the SAML workflow with different attributes
    self._test_saml2_browser_workflow("", True)

    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    self._test_saml2_browser_workflow(attributes_xml, True)

    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="bad_group")
    self._test_saml2_browser_workflow(attributes_xml, True)

  def _test_common_group_filter_checks(self):
    """Common group filter checks for both test classes."""
    # Test the SAML workflow with different attributes
    self._test_saml2_browser_workflow("", False)

    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    self._test_saml2_browser_workflow(attributes_xml, True)

    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="bad_group")
    self._test_saml2_browser_workflow(attributes_xml, False)

  # HS2-specific workflow methods
  def _hs2_request_resource(self, host_port, client_port, sp_callback_url):  # noqa: U100
    """Initial POST request to hs2-http port, response should be redirected
       to IDP and contain the authnrequest."""
    opener = build_opener(NoRedirection)
    payload = encode_if_needed(" ")
    req = Request("http://localhost:%s" % host_port, payload)
    req.add_header('X-Hive-Token-Response-Port', client_port)
    response = opener.open(req)
    client_id = response.info().get("X-Hive-Client-Identifier", None)
    assert client_id is not None
    relay_state, saml_req_xml = self._parse_redirection_response_common(response)
    request_id = self._parse_authn_request(saml_req_xml)
    return relay_state, client_id, request_id

  def _hs2_send_authn_response(self, sp_callback_url, request_id, relay_state,
                                attributes_xml, expect_success):
    """Send an authnresponse to Impala - normally the IDP would do this, but in
       this test we generate it from an xml template.
       Impala should answer with a form that submits to CLIENT_PORT and contains
       the bearer token as a hidden state."""
    destination = sp_callback_url + "?client_name=ImpalaSamlClientHS2"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))
    opener = build_opener(NoRedirection)
    req = Request(sp_callback_url, encode_if_needed(body))
    response = opener.open(req)
    bearer_token = self._hs2_parse_xhtml_form(response, expect_success)
    return bearer_token

  def _hs2_parse_xhtml_form(self, response, expect_success):
    """Parse XHTML form response to extract bearer token or error message."""
    assert response.getcode() == 200
    content = response.read()
    root = ET.fromstring(content)
    assert root.tag == "html"
    assert root[0].tag == "body"
    assert root[0][0].tag == "form"
    token = ""
    message = ""
    for input in root[0][0]:
      assert input.tag == "input"
      if input.attrib["name"] == "token":
        token = input.attrib["value"]
      elif input.attrib["name"] == "message":
        message = input.attrib["value"]

    if expect_success:
      assert token.startswith("u=user1"), str(content)
    else:
      assert message == TestSamlBase.ASSERTATION_ERROR_MESSAGE
    return token

  def _hs2_request_resource_with_bearer(self, host_port, client_id, bearer_token,
                                        manipulate_bearer_token=False, repeated=False):
    """Send POST request to hs2-http port again, this time with bearer token.
       The response should contain a security cookie if the validation succeeded.
       'manipulate_bearer_token': if true, the token is tampered to simulate a forged
                          token, which must be rejected by the token signature check.
       'repeated': if true, a previously used valid token is replayed, which must be
                          rejected as a bearer token can only be used once."""
    payload = encode_if_needed(" ")
    req = Request("http://localhost:%s" % host_port, payload)
    req.add_header('X-Hive-Client-Identifier', client_id)
    if manipulate_bearer_token:
      bearer_token = bearer_token.replace("user1", "user2")
    req.add_header('Authorization', "Bearer " + bearer_token)
    opener = build_opener(NoRedirection)
    response = opener.open(req)
    # saml2_ee_test_mode=true leads to returning 401 unauthorized - otherwise the
    # call would hang if there is no Thrift message.
    assert response.getcode() == 401
    cookies = response.info()['Set-Cookie']
    if manipulate_bearer_token:
      assert not cookies, "Auth should fail with forged bearer token"
    elif repeated:
      assert not cookies, "Auth should fail with repeated bearer token"
    else:
      assert cookies
      assert cookies.startswith("impala.auth=")

  # WS-specific workflow methods
  def _ws_request_resource(self, ws_port):
    """Initial GET request to webserver port, response should be redirected
       to IDP and contain the authnrequest."""
    opener = build_opener(NoRedirection)
    req = Request("http://localhost:%s" % ws_port)
    response = opener.open(req)
    relay_state, saml_req_xml = self._parse_redirection_response_common(response)
    request_id = self._parse_authn_request(saml_req_xml)
    return relay_state, request_id

  def _ws_send_authn_response(self, sp_callback_url, request_id, relay_state,
                               attributes_xml, expect_success):
    """Send an authnresponse to Impala - normally the IDP would do this, but in
       this test we generate it from an xml template.
       Impala should answer with a redirect with cookies"""
    destination = sp_callback_url + "?client_name=ImpalaSamlClientWS"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))
    opener = build_opener(NoRedirection)
    req = Request(sp_callback_url, encode_if_needed(body))
    response = opener.open(req)
    if expect_success:
      assert response.getcode() == 302
      cookies = response.info()['Set-Cookie']
      assert cookies.startswith("impala.auth=")
    else:
      assert response.getcode() == 401
      assert response.read().decode('utf-8') == TestSamlBase.ASSERTATION_ERROR_MESSAGE


class TestHS2Saml(TestSamlBase):
  """ Tests for a client using SAML2 browser profile.

      Most tests simulate the SAML2 browser profile workflow by sending 3 http requests
      to Impala's hs2-http port:
      1. a POST request with header X-Hive-Token-Response-Port set
         - Normally the client should listen on the port above, but this is not needed
           during the tests
         - Impala responds with a redirection to the SSO service ('IDP_URL') with
           encoded SAMLRequest and RelayState parameters.
         - SAML2 browser profile is designed for web pages that are already opened in the
           browser, which would do the redirection automatically. As in our case the
           workflow is expected to be executed from a client like JDBC, the client should
           normally open a browser tab with the the location in the redirection. During
           the tests the browser is not involved.
         - Implemented by _request_resource() in the tests.
      2. a POST request with the same path as configured in flag saml2_sp_callback_url
         containing an encoded AuthNResponse and the RelayState as content
         - Normally this comes from the browser.
         - Impala validates the AuthNResponse end responds with an HTML form that submits
           to localhost:{X-Hive-Token-Response-Port} and contains a bearer token.
         - Implemented by _send_authn_response() in the tests.
      3. a POST request with the bearer token as auth header
         - Impala validates the token and returns an auth cookie.
         - Implemented by _request_resource_with_bearer() in the tests.

      After getting the auth cookie the client should send "normal" hs2-http Thrift
      requests, but this is not included in the tests as currently there is no client
      that supports SAML auth. IMPALA-10496 tracks adding SAML support to Impyla.
  """

  SP_CALLBACK_URL = "http://localhost:28000/SAML2/SSO/POST"
  CLIENT_PORT = 12345

  SSO_ARGS = ((TestSamlBase.SSO_ARGS_COMMON
               + " --saml2_idp_metadata=%s/saml2_sso_metadata.xml"
               + " --saml2_sp_callback_url=%s")
              % (TestSamlBase.CERT_DIR, SP_CALLBACK_URL))

  SSO_ARGS_WITH_GROUP_FILTER = (
      "{} --saml2_group_filter=group1,group2 "
      "--saml2_group_attribute_name=eduPersonAffiliation").format(SSO_ARGS)

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_browser_profile_no_group_filter(self):
    self._test_common_protocol_checks()
    # A forged bearer token (tampered user) must be rejected by the signature check.
    self._test_saml2_browser_workflow("", True, manipulate_bearer_token=True)

  @CustomClusterTestSuite.with_args(
      impalad_args=SSO_ARGS_WITH_GROUP_FILTER, cluster_size=1)
  def test_saml2_browser_profile_with_group_filter(self):
      self._test_common_group_filter_checks()

  def _test_saml2_browser_workflow(self, attributes_xml, expect_success,
                                   manipulate_bearer_token=False):
    """ Sends the 3 SAML related requests to Impala and parses/validates
        their response.
        'attributes_xml': contains the attributes part of authn response
        'expect_success': if false, then the workflow is expected to fail when
                          Impala validates the assertions in authn response
        'manipulate_bearer_token': if true, the bearer token sent in the 3rd step is
                          tampered to simulate a forged token, which must be rejected """
    relay_state, client_id, request_id = self._hs2_request_resource(
        TestSamlBase.hs2_http_port(), TestHS2Saml.CLIENT_PORT,
        TestHS2Saml.SP_CALLBACK_URL)
    bearer_token = self._hs2_send_authn_response(
        TestHS2Saml.SP_CALLBACK_URL, request_id, relay_state, attributes_xml,
        expect_success)
    if not expect_success:
      return

    # Get initial success metric value before step 3
    impalad = self.cluster.impalads[0]
    initial_success = impalad.service.get_metric_value(
        TestSamlBase.HS2_SAML_SUCCESS_METRIC)

    self._hs2_request_resource_with_bearer(
        TestSamlBase.hs2_http_port(), client_id, bearer_token,
        manipulate_bearer_token=manipulate_bearer_token)
    # A valid bearer token must not be accepted a second time (replay protection).
    self._hs2_request_resource_with_bearer(
        TestSamlBase.hs2_http_port(), client_id, bearer_token,
        manipulate_bearer_token=manipulate_bearer_token, repeated=True)

    # Verify success metric behaviour
    final_success = impalad.service.get_metric_value(
        TestSamlBase.HS2_SAML_SUCCESS_METRIC)
    if manipulate_bearer_token:
      assert final_success == initial_success, \
          "Success metric should not change with forged bearer token"
    else:
      assert final_success > initial_success, \
          "Success metric should increment on successful auth"

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_untrusted_idp(self):
    """Test that SAML response from an untrusted IDP is rejected."""
    self._test_saml2_invalid_response_workflow(issuer="https://unknown.com/idp")

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_expired_assertion(self):
    """Test that SAML response with expired assertion is rejected."""
    past_time = format_time(datetime.datetime.utcnow() - datetime.timedelta(hours=1))
    self._test_saml2_invalid_response_workflow(not_on_or_after=past_time)

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_not_yet_valid_assertion(self):
    """Test that SAML response with not-yet-valid assertion is rejected."""
    future_time = format_time(datetime.datetime.utcnow() + datetime.timedelta(hours=1))
    self._test_saml2_invalid_response_workflow(not_before=future_time)

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_invalid_request_id(self):
    """Test that SAML response with invalid InResponseTo is rejected."""
    self._test_saml2_invalid_response_workflow(request_id="invalid_request_id")

    # Verify the specific error in the logs
    self.assert_impalad_log_contains("INFO",
        "SAMLInResponseToMismatchException: InResponseToField of the Response "
        "doesn't correspond to sent message invalid_request_id", 1)

  def _test_saml2_invalid_response_workflow(self, request_id=None, issuer=None,
                                            not_before=None, not_on_or_after=None):
    """Test workflow with an invalid SAML response that should be rejected."""
    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    relay_state, client_id, actual_request_id = self._hs2_request_resource(
        TestSamlBase.hs2_http_port(), TestHS2Saml.CLIENT_PORT,
        TestHS2Saml.SP_CALLBACK_URL)

    # Use provided request_id or the actual one from the request
    request_id_to_use = request_id if request_id is not None else actual_request_id

    # Send authn response with invalid parameters - should fail
    destination = TestHS2Saml.SP_CALLBACK_URL + "?client_name=ImpalaSamlClientHS2"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id_to_use, attributes_xml, destination, recipient,
        not_before=not_before, not_on_or_after=not_on_or_after, issuer=issuer)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))
    opener = build_opener(NoRedirection)
    req = Request(TestHS2Saml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    # Should get error message in the form
    self._hs2_parse_xhtml_form(response, expect_success=False)

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_response_replay_attack(self):
    """Test that replaying the exact same SAML response is rejected.

    This tests pac4j's MessageReplaySecurityHandler which checks the SAML Response
    msg_id (not the request_id/InResponseTo). When the entire response is replayed,
    the msg_id is the same, and pac4j detects this as a replay attack.

    A realistic replay attack intercepts and reuses the SAML response at step 2,
    without completing step 3 (bearer token validation).
    """
    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    relay_state, client_id, request_id = self._hs2_request_resource(
        TestSamlBase.hs2_http_port(), TestHS2Saml.CLIENT_PORT,
        TestHS2Saml.SP_CALLBACK_URL)

    # Generate the SAML response
    destination = TestHS2Saml.SP_CALLBACK_URL + "?client_name=ImpalaSamlClientHS2"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))

    # First SAML response submission - should succeed
    opener = build_opener(NoRedirection)
    req = Request(TestHS2Saml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    bearer_token = self._hs2_parse_xhtml_form(response, True)
    assert bearer_token.startswith("u=user1"), "First auth should succeed"

    # Now replay the exact same SAML response - should be rejected
    # pac4j's MessageReplaySecurityHandler tracks msg_id and detects the replay
    req = Request(TestHS2Saml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    # pac4j's replay detection for HS2 returns 200 but without a valid bearer token
    assert response.getcode() == 200, \
        f"Expected 200 on HS2 replay, got: {response.getcode()}"
    # Verify replay was rejected (should not contain a valid bearer token)
    content = response.read()
    content_str = content.decode('utf-8') if isinstance(content, bytes) else content
    # A valid token starts with "u=user1", replayed response should not have this
    assert "u=user1" not in content_str, \
        f"Expected no valid token in replayed response, but got: {content_str[:200]}"
    # Verify the replay was detected in the server logs
    self.assert_impalad_log_contains("INFO", "Replay detected of message")

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_request_id_replay_attack(self):
    """Test that reusing the same request_id (InResponseTo) is rejected.

    This tests InResponseTo validation using our ImpalaSAMLMessageStore. When a
    new response is generated with a DIFFERENT msg_id but the SAME request_id
    (InResponseTo), it should be rejected because the request_id has already been
    consumed.
    """
    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    relay_state, client_id, request_id = self._hs2_request_resource(
        TestSamlBase.hs2_http_port(), TestHS2Saml.CLIENT_PORT,
        TestHS2Saml.SP_CALLBACK_URL)

    # Generate first SAML response with this request_id
    destination = TestHS2Saml.SP_CALLBACK_URL + "?client_name=ImpalaSamlClientHS2"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))

    # First authentication - should succeed
    opener = build_opener(NoRedirection)
    req = Request(TestHS2Saml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    bearer_token = self._hs2_parse_xhtml_form(response, True)
    assert bearer_token.startswith("u=user1"), "First auth should succeed"

    # Now generate a NEW response with DIFFERENT msg_id but SAME request_id
    # This simulates an attacker creating a new response for an already-used request
    authn_resp_2 = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp_2 = base64.urlsafe_b64encode(authn_resp_2.encode('utf-8'))
    body_2 = (b"SAMLResponse=" + encoded_authn_resp_2 + b"&RelayState="
              + encode_if_needed(relay_state))

    # This should be rejected because the request_id has been consumed
    req = Request(TestHS2Saml.SP_CALLBACK_URL, encode_if_needed(body_2))
    response = opener.open(req)
    assert response.getcode() == 200, \
        f"Expected 200 on HS2 request_id reuse, got: {response.getcode()}"
    # Verify replay was rejected (should not contain a valid bearer token)
    content = response.read()
    content_str = content.decode('utf-8') if isinstance(content, bytes) else content
    # A valid token starts with "u=user1", replayed response should not have this
    assert "u=user1" not in content_str, \
        f"Expected no valid token in replayed response, but got: {content_str[:200]}"
    # Verify the specific error in the logs
    self.assert_impalad_log_contains("INFO",
        "SAMLInResponseToMismatchException: InResponseToField of the Response "
        "doesn't correspond to sent message", 1)


class TestWebserverSaml(TestSamlBase):
  """
  Tests for a client using SAML2 browser profile against the Impala webserver.

  These tests simulate the SAML2 browser profile workflow by sending HTTP requests
  to Impala's webserver port (default 25000):

  1. A GET request to the webserver port.
     - The test client sends a GET request to the webserver.
     - Impala responds with a 302 redirect to the SSO service (IDP_URL), including
       encoded SAMLRequest and RelayState parameters.
     - This simulates the browser being redirected to the identity provider.

  2. A POST request to the SAML2 callback URL (SP_CALLBACK_URL) containing an encoded
     AuthNResponse and the RelayState as content.
     - Normally, this would come from the browser after authentication at the IDP.
     - Impala validates the AuthNResponse and responds with a 302 redirect and a
       Set-Cookie header containing the authentication cookie.

  3. (Not implemented here) After obtaining the auth cookie, a real client would send
     authenticated requests to the webserver. These tests focus on the SAML2
     authentication flow only.
  """

  SP_CALLBACK_URL = "http://localhost:25000/SAML2/SSO/POST"
  WS_PORT = 25000

  SSO_ARGS = ((TestSamlBase.SSO_ARGS_COMMON
               + " --webserver_saml2_idp_metadata=%s/saml2_sso_metadata.xml"
               + " --webserver_saml2_sp_callback_url=%s")
              % (TestSamlBase.CERT_DIR, SP_CALLBACK_URL))

  SSO_ARGS_WITH_GROUP_FILTER = (
      "{} --saml2_group_filter=group1,group2 "
      "--saml2_group_attribute_name=eduPersonAffiliation").format(SSO_ARGS)

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_browser_profile_no_group_filter(self):
      self._test_common_protocol_checks()

  @CustomClusterTestSuite.with_args(
      impalad_args=SSO_ARGS_WITH_GROUP_FILTER, cluster_size=1)
  def test_saml2_browser_profile_with_group_filter(self):
      self._test_common_group_filter_checks()

  def _test_saml2_browser_workflow(self, attributes_xml, expect_success):
    """Execute the complete SAML browser workflow for webserver authentication."""
    # Get initial metric values
    impalad = self.cluster.impalads[0]
    initial_success = impalad.service.get_metric_value(
        TestSamlBase.WS_SAML_SUCCESS_METRIC)
    initial_failure = impalad.service.get_metric_value(
        TestSamlBase.WS_SAML_FAILURE_METRIC)

    relay_state, request_id = self._ws_request_resource(TestWebserverSaml.WS_PORT)
    self._ws_send_authn_response(
        TestWebserverSaml.SP_CALLBACK_URL, request_id, relay_state, attributes_xml,
        expect_success)

    # Verify metrics were updated correctly
    final_success = impalad.service.get_metric_value(
        TestSamlBase.WS_SAML_SUCCESS_METRIC)
    final_failure = impalad.service.get_metric_value(
        TestSamlBase.WS_SAML_FAILURE_METRIC)
    if expect_success:
      assert final_success == initial_success + 1, \
          "Success metric should increment on successful auth"
      assert final_failure == initial_failure, \
          "Failure metric should not change on successful auth"
    else:
      assert final_success == initial_success, \
          "Success metric should not change on failed auth"
      assert final_failure == initial_failure + 1, \
          "Failure metric should increment on failed auth"

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_untrusted_idp(self):
    """Test that SAML response from an untrusted IDP is rejected."""
    self._test_saml2_invalid_response_workflow(issuer="https://unknown.com/idp")

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_expired_assertion(self):
    """Test that SAML response with expired assertion is rejected."""
    past_time = format_time(datetime.datetime.utcnow() - datetime.timedelta(hours=1))
    self._test_saml2_invalid_response_workflow(not_on_or_after=past_time)

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_not_yet_valid_assertion(self):
    """Test that SAML response with not-yet-valid assertion is rejected."""
    future_time = format_time(datetime.datetime.utcnow() + datetime.timedelta(hours=1))
    self._test_saml2_invalid_response_workflow(not_before=future_time)

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_invalid_request_id(self):
    """Test that SAML response with invalid InResponseTo is rejected."""
    self._test_saml2_invalid_response_workflow(request_id="invalid_request_id")

    # Verify the specific error in the logs
    self.assert_impalad_log_contains("INFO",
        "SAMLInResponseToMismatchException: InResponseToField of the Response "
        "doesn't correspond to sent message invalid_request_id", 1)

  def _test_saml2_invalid_response_workflow(self, request_id=None, issuer=None,
                                            not_before=None, not_on_or_after=None):
    """Test workflow with an invalid SAML response that should be rejected."""
    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    relay_state, actual_request_id = self._ws_request_resource(TestWebserverSaml.WS_PORT)

    # Use provided request_id or the actual one from the request
    request_id_to_use = request_id if request_id is not None else actual_request_id

    # Send authn response with invalid parameters - should fail
    destination = TestWebserverSaml.SP_CALLBACK_URL + "?client_name=ImpalaSamlClientWS"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id_to_use, attributes_xml, destination, recipient,
        not_before=not_before, not_on_or_after=not_on_or_after, issuer=issuer)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))
    opener = build_opener(NoRedirection)
    req = Request(TestWebserverSaml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    # Should get 401 with error message
    assert response.getcode() == 401
    assert response.read().decode('utf-8') == TestSamlBase.ASSERTATION_ERROR_MESSAGE

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_response_replay_attack(self):
    """Test that replaying the exact same SAML response is rejected.

    This tests pac4j's MessageReplaySecurityHandler which checks the SAML Response
    msg_id (not the request_id/InResponseTo). When the entire response is replayed,
    the msg_id is the same, and pac4j detects this as a replay attack.

    A realistic replay attack intercepts and reuses the SAML response at step 2.
    """
    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    relay_state, request_id = self._ws_request_resource(TestWebserverSaml.WS_PORT)

    # Generate the SAML response (with unique msg_id and assertion_id)
    destination = TestWebserverSaml.SP_CALLBACK_URL + "?client_name=ImpalaSamlClientWS"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))

    # First SAML response submission - should succeed
    opener = build_opener(NoRedirection)
    req = Request(TestWebserverSaml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    assert response.getcode() == 302, "First auth should succeed with redirect"
    cookies = response.info()['Set-Cookie']
    assert cookies.startswith("impala.auth="), "Should receive auth cookie"

    # Now replay the exact same SAML response (same msg_id, same assertion_id)
    # pac4j's MessageReplaySecurityHandler tracks msg_id and detects the replay
    req = Request(TestWebserverSaml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    assert response.getcode() == 401, \
        f"Expected 401 on response replay, got: {response.getcode()}"

    # In case of Webserver the responce validation is the last saml step, after which the
    # RelayState gets invalidated. Thus repeating it leads to 'Invalidated RelayState'
    # error, not even reaching the Replay protection

    # Verify the replay was detected in the server logs
    self.assert_impalad_log_contains("ERROR", "Invalid relay state")

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_saml2_request_id_replay_attack(self):
    """Test that reusing the same request_id (InResponseTo) is rejected.

    This tests InResponseTo validation using our ImpalaSAMLMessageStore. When a
    new response is generated with a DIFFERENT msg_id but the SAME request_id
    (InResponseTo), it should be rejected because the request_id has already been
    consumed.
    """
    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    relay_state, request_id = self._ws_request_resource(TestWebserverSaml.WS_PORT)

    # Generate first SAML response with this request_id
    destination = TestWebserverSaml.SP_CALLBACK_URL + "?client_name=ImpalaSamlClientWS"
    recipient = destination
    authn_resp = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp = base64.urlsafe_b64encode(authn_resp.encode('utf-8'))
    body = (b"SAMLResponse=" + encoded_authn_resp + b"&RelayState="
            + encode_if_needed(relay_state))

    # First authentication - should succeed
    opener = build_opener(NoRedirection)
    req = Request(TestWebserverSaml.SP_CALLBACK_URL, encode_if_needed(body))
    response = opener.open(req)
    assert response.getcode() == 302
    cookies = response.info()['Set-Cookie']
    assert cookies.startswith("impala.auth=")

    # Now generate a NEW response with DIFFERENT msg_id but SAME request_id
    # This simulates an attacker creating a new response for an already-used request
    authn_resp_2 = TestSamlBase._generate_authn_response(
        request_id, attributes_xml, destination, recipient)
    encoded_authn_resp_2 = base64.urlsafe_b64encode(authn_resp_2.encode('utf-8'))
    body_2 = (b"SAMLResponse=" + encoded_authn_resp_2 + b"&RelayState="
              + encode_if_needed(relay_state))

    # This should be rejected because the request_id has been consumed
    req = Request(TestWebserverSaml.SP_CALLBACK_URL, encode_if_needed(body_2))
    response = opener.open(req)
    assert response.getcode() == 401, \
        f"Expected 401 on request_id reuse, got: {response.getcode()}"

    # In case of Webserver the responce validation is the last saml step, after which the
    # RelayState gets invalidated. Thus repeating it leads to 'Invalid relay state' error,
    # not even reaching the Replay protection.

    # Verify the replay was detected in the server logs
    self.assert_impalad_log_contains("ERROR", "Invalid relay state")


class TestCombinedSaml(TestSamlBase):
  """
  Tests for both HS2 and webserver SAML running simultaneously on the same impalad.

  This test class verifies that both SAML services can be configured and work
  independently on the same Impala instance:
  - HS2 SAML protects hs2-http port (28000)
  - Webserver SAML protects webserver port (25000)

  Uses single inheritance from TestSamlBase and calls protocol-specific methods directly.
  """

  SSO_ARGS = ((TestSamlBase.SSO_ARGS_COMMON
               + " --saml2_idp_metadata=%s/saml2_sso_metadata.xml"
               + " --saml2_sp_callback_url=%s"
               + " --webserver_saml2_idp_metadata=%s/saml2_sso_metadata.xml"
               + " --webserver_saml2_sp_callback_url=%s")
              % (TestSamlBase.CERT_DIR, TestHS2Saml.SP_CALLBACK_URL,
                 TestSamlBase.CERT_DIR, TestWebserverSaml.SP_CALLBACK_URL))

  @CustomClusterTestSuite.with_args(impalad_args=SSO_ARGS, cluster_size=1)
  def test_both_saml_services_work_independently(self):
    """Test that both HS2 and webserver SAML work on the same impalad."""
    impalad = self.cluster.impalads[0]

    # Test HS2 SAML workflow using base class methods
    attributes_xml = TestSamlBase.ATTRIBUTE_STATEMENT.format(group_name="group1")
    relay_state, client_id, request_id = self._hs2_request_resource(
        TestSamlBase.hs2_http_port(), TestHS2Saml.CLIENT_PORT,
        TestHS2Saml.SP_CALLBACK_URL)
    bearer_token = self._hs2_send_authn_response(
        TestHS2Saml.SP_CALLBACK_URL, request_id, relay_state, attributes_xml, True)

    # Get initial HS2 success metric before step 3
    initial_hs2_success = impalad.service.get_metric_value(
        TestSamlBase.HS2_SAML_SUCCESS_METRIC)

    self._hs2_request_resource_with_bearer(TestSamlBase.hs2_http_port(), client_id,
                                           bearer_token)

    # Verify HS2 SAML success metric incremented
    final_hs2_success = impalad.service.get_metric_value(
        TestSamlBase.HS2_SAML_SUCCESS_METRIC)
    assert final_hs2_success > initial_hs2_success, \
        "HS2 SAML success metric should increment"

    # Get initial webserver success metric before webserver SAML workflow
    initial_ws_success = impalad.service.get_metric_value(
        TestSamlBase.WS_SAML_SUCCESS_METRIC)

    # Test webserver SAML workflow using base class methods
    relay_state, request_id = self._ws_request_resource(TestWebserverSaml.WS_PORT)
    self._ws_send_authn_response(
        TestWebserverSaml.SP_CALLBACK_URL, request_id, relay_state, attributes_xml, True)

    # Verify webserver SAML success metric incremented
    final_ws_success = impalad.service.get_metric_value(
        TestSamlBase.WS_SAML_SUCCESS_METRIC)
    assert final_ws_success > initial_ws_success, \
        "Webserver SAML success metric should increment"


# Sample 'AttributeStatement' part of authn response (generated by simplesaml php)
SAML_ATTRIBUTE_STATEMENT_TEMPLATE = """
    <saml:AttributeStatement>
      <saml:Attribute Name="uid"
          NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">1</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="eduPersonAffiliation"
          NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">{group_name}</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="email"
          NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">user1@example.com</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>"""

# Complete SAML Response template for authentication responses
SAML_RESPONSE_TEMPLATE = """
    <samlp:Response
        xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
        xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
        ID="{msg_id}"
        Version="2.0" IssueInstant="{issue_instant}"
        Destination="{destination}"
        InResponseTo="{request_id}">
      <saml:Issuer>
        {issuer}
      </saml:Issuer>
      <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
      </samlp:Status>
      <saml:Assertion
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xs="http://www.w3.org/2001/XMLSchema"
          ID="{assertation_id}"
          Version="2.0"
          IssueInstant="{issue_instant}">
        <saml:Issuer>
            https://localhost:8443/simplesaml/saml2/idp/metadata.php
        </saml:Issuer>
        <saml:Subject>
          <saml:NameID
              SPNameQualifier="org.apache.impala"
              Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">
            user1
          </saml:NameID>
          <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
          <saml:SubjectConfirmationData
              NotOnOrAfter="{not_on_or_after}"
              Recipient="{recipient}"
              InResponseTo="{request_id}"/>
          </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="{not_before}" NotOnOrAfter="{not_on_or_after}">
          <saml:AudienceRestriction>
            <saml:Audience>org.apache.impala</saml:Audience>
          </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement
            AuthnInstant="{issue_instant}"
            SessionNotOnOrAfter="{not_on_or_after}"
            SessionIndex="_b7ac1881122cb9e24fbdef7ed40c0aafeeef1313cf">
          <saml:AuthnContext>
            <saml:AuthnContextClassRef>
                urn:oasis:names:tc:SAML:2.0:ac:classes:Password
            </saml:AuthnContextClassRef>
          </saml:AuthnContext>
        </saml:AuthnStatement>
        {attribute_statement}
      </saml:Assertion>
    </samlp:Response>"""

# Initialize class attributes after templates are defined
TestSamlBase.ATTRIBUTE_STATEMENT = SAML_ATTRIBUTE_STATEMENT_TEMPLATE
