// Copyright (c) 2011 Cloudera, Inc. All rights reserved.

#ifndef IMPALA_EXEC_HDFS_TEXT_TABLE_SINK_H
#define IMPALA_EXEC_HDFS_TEXT_TABLE_SINK_H

#include "exec/data-sink.h"

#include <hdfs.h>
#include <boost/scoped_ptr.hpp>
#include <boost/unordered_map.hpp>

// needed for scoped_ptr to work on ObjectPool
#include "common/object-pool.h"
#include "runtime/descriptors.h"

namespace impala {

class Expr;
class TupleDescriptor;
class TupleRow;
class RuntimeState;
class OutputPartition;

// TODO: HdfsTextScanNode and this class have a lot in common.
// At some point, we might want to factor out the common parts.

// The sink consumes all row batches of its child execution tree,
// and writes the evaluated select_list_exprs
// as delimited text into Hdfs files.
// This sink supports static and dynamic partition inserts (Hive terminology),
// as well as inserting into unpartitioned tables,
// and optional overwriting of partitions/tables.
//
// Files and partitions:
// This sink writes a single Hdfs file per output partition,
// corresponding to an Hdfs directory.
// The Hdfs file name is the queryId, and therefore,
// we rely on the uniqueness of queryIds.
// For each row, its target partition is computed based on the
// partition_key_exprs from tsink.
// A map of opened Hdfs files (corresponding to partitions) is maintained.
//
// Failure behavior:
// In Exec() all data is written to Hdfs files in a temporary directory.
// In Close() all temporary Hdfs files are moved to their final locations,
// while also removing the original files if overwrite was specified, as follows:
// 1. We move all temporary files to their final destinations.
// 2. After all tmp files have been moved,
//    we delete the original files if overwrite was specified.
// There is a possibility of data inconsistency,
// e.g., if a failure occurs while moving the Hdfs files.
// The temporary directory is <table base dir>/<query_id.hi>-<query_id.lo>_data
// such that an external tool can easily clean up incomplete inserts.
// This is consistent with Hive's behavior.
class HdfsTextTableSink : public DataSink {
 public:
  HdfsTextTableSink(const RowDescriptor& row_desc, const TUniqueId& query_id,
      const std::vector<TExpr>& select_list_texprs, const TDataSink& tsink);

  // Prepares select_list_exprs and partition_key_exprs. Sets delimiters.
  // Also, connects to Hdfs, and prepares the single output partition for static inserts.
  virtual Status Init(RuntimeState* state);

  // Append all rows in batch to the temporary Hdfs files corresponding to partitions.
  virtual Status Send(RuntimeState* state, RowBatch* batch);

  // Move temporary Hdfs files to final locations.
  // Remove original Hdfs files if overwrite was specified.
  virtual Status Close(RuntimeState* state);

  virtual std::string DebugString() const;

 private:
  // Key is the concatenation of the evaluated
  // dynamic_partition_key_exprs_ generated by GetHashTblKey().
  // Maps to an OutputPartition, which are owned by the object pool.
  typedef boost::unordered_map<std::string, OutputPartition* > HashTable;

  static const char DELIM_INIT = -1;

  // Generates string key for hash_tbl_ as a concatenation
  // of all dynamic_partition_key_exprs_.
  // The generated string is much shorter than the full Hdfs file name.
  void GetHashTblKey(std::string* key);

  // Initialise and prepare select and partition key expressions
  Status PrepareExprs(RuntimeState* state);

  // Sets hdfs_file_name and tmp_hdfs_file_name of given output partition.
  // The Hdfs directory is created from the target table's base Hdfs dir,
  // the partition_key_names_ and the evaluated partition_key_exprs_.
  // The Hdfs file name is the query_id_.
  void BuildHdfsFileNames(OutputPartition* output);

  // Initialises the filenames of a given output partition, and opens the temporary file.
  Status InitOutputPartition(OutputPartition* output);

  // Appends delimited string representation of current_row_ to output partition.
  Status AppendCurrentRow(OutputPartition* output);

  // Move tmp Hdfs files from output partitions to their final destinations.
  // If overwrite is true, we move the tmp Hdfs directories,
  // otherwise we move the tmp Hdfs files.
  // Also deletes the tmp directory,
  // and optionally the original Hdfs files if overwrite_ is true.
  Status MoveTmpHdfsFiles();

  // Move the tmp Hdfs file of a single output partition to its final destination.
  Status MoveTmpHdfsFile(OutputPartition* output);

  // Deletes all files in the Hdfs directory of the given OutputPartition,
  // except output->hdfs_file_name which was just created.
  Status DeleteOriginalFiles(OutputPartition* output);

  // Updates runtime stats of HDFS files created and rows written, then closes the file
  // associated with the partition
  Status FinalizePartition(RuntimeState* state, OutputPartition* partition);

  // Row descriptor of row batches passed in Send(). Set in c'tor.
  const RowDescriptor& row_desc_;

  // Table id resolved in Prepare() to set tuple_desc_;
  TableId table_id_;

  // Descriptor of target table. Set in Prepare().
  const HdfsTableDescriptor* table_desc_;

  // Thrift representation of select list exprs, saved in the constructor
  // to be used to initialise select_list_exprs_ in Init
  const std::vector<TExpr>& select_list_texprs_;

  // Thrift representation of partition keys, saved in the constructor
  // to be used to initialise partition_key_exprs_ in Init
  const std::vector<TExpr>& partition_key_texprs_;

  // Exprs of partition keys.
  std::vector<Expr*> partition_key_exprs_;

  // Exprs that materialize output values
  std::vector<Expr*> select_list_exprs_;

  // Indicates whether the existing partitions should be overwritten.
  bool overwrite_;

  // string representation of query_id_. Used for per-partition Hdfs file names,
  // and for tmp Hdfs directories. Set in Prepare();
  std::string query_id_str_;

  // Current row from the current RowBatch to output
  TupleRow* current_row_;

  // Character delimiting tuples.
  char tuple_delim_;

  // Character delimiting fields (to become slots).
  char field_delim_;

  // Escape character. TODO: Escape output.
  char escape_char_;

  // Special value for NULL partition keys to be compatible with Hive.
  std::string null_partition_key_value_;

  // Hash table of generated output partitions.
  // Maps from a string representation of the dynamic_partition_key_exprs_
  // generated by GetHashTblKey() to its corresponding OutputPartition.
  HashTable partition_keys_to_output_partitions_;

  // Subset of partition_key_exprs_ which are not constant. Set in Prepare().
  // Used for generating the string key of hash_tbl_.
  std::vector<Expr*> dynamic_partition_key_exprs_;

  // Static output partition used if dynamic_partition_exprs_ are empty.
  // Initialized in Prepare().
  boost::scoped_ptr<OutputPartition> static_partition_;

  // Connection to hdfs, established in Open() and closed in Close().
  hdfsFS hdfs_connection_;
};

}
#endif
