# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

apiVersion: impala.apache.org/v1alpha1
kind: ImpalaCluster
metadata:
  name: impala-demo
  namespace: impala
spec:
  impalaReleaseName: impala
  ldapReleaseName: impala-ldap
  ldapEnabled: false
  kuduEnabled: false
  rangerEnabled: false
  rangerAuthEnabled: false
  storageClassName: ""
  config:
    impalad:
      flags:
        num_reactor_threads: "0"
      queryDefaults:
        mt_dop: "4"
        default_file_format: "parquet"
  set:
    service.impalad.type: ClusterIP
