Impala: be/src/exprs/agg-fn-evaluator.cc File Reference
agg-fn-evaluator.cc File Reference
#include "exprs/agg-fn-evaluator.h"
#include <sstream>
#include "codegen/llvm-codegen.h"
#include "common/logging.h"
#include "exec/aggregation-node.h"
#include "exprs/aggregate-functions.h"
#include "exprs/expr-context.h"
#include "exprs/anyval-util.h"
#include "runtime/lib-cache.h"
#include "runtime/runtime-state.h"
#include "udf/udf-internal.h"
#include "util/debug-util.h"
#include <thrift/protocol/TDebugProtocol.h>
#include "common/names.h"
Typedefs
typedef void(* InitFn)(FunctionContext *, AnyVal *)
typedef void(* UpdateFn0)(FunctionContext *, AnyVal *)
typedef void(* UpdateFn1)(FunctionContext *, const AnyVal &, AnyVal *)
typedef void(* UpdateFn2)(FunctionContext *, const AnyVal &, const AnyVal &, AnyVal *)
typedef void(* UpdateFn3)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
typedef void(* UpdateFn4)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
typedef void(* UpdateFn5)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
typedef void(* UpdateFn6)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
typedef void(* UpdateFn7)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
typedef void(* UpdateFn8)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
typedef StringVal(* SerializeFn)(FunctionContext *, const StringVal &)
typedef AnyVal(* GetValueFn)(FunctionContext *, const AnyVal &)
typedef AnyVal(* FinalizeFn)(FunctionContext *, const AnyVal &)
Functions
static void SetAnyVal (const SlotDescriptor *desc, Tuple *tuple, AnyVal *dst)
Typedef Documentation
typedef AnyVal(* FinalizeFn)(FunctionContext *, const AnyVal &)
Definition at line 62 of file agg-fn-evaluator.cc.
typedef AnyVal(* GetValueFn)(FunctionContext *, const AnyVal &)
Definition at line 61 of file agg-fn-evaluator.cc.
typedef void(* InitFn)(FunctionContext *, AnyVal *)
Definition at line 43 of file agg-fn-evaluator.cc.
typedef StringVal(* SerializeFn)(FunctionContext *, const StringVal &)
Definition at line 60 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn0)(FunctionContext *, AnyVal *)
Definition at line 44 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn1)(FunctionContext *, const AnyVal &, AnyVal *)
Definition at line 45 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn2)(FunctionContext *, const AnyVal &, const AnyVal &, AnyVal *)
Definition at line 46 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn3)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
Definition at line 47 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn4)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
Definition at line 49 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn5)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
Definition at line 51 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn6)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
Definition at line 53 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn7)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
Definition at line 55 of file agg-fn-evaluator.cc.
typedef void(* UpdateFn8)(FunctionContext *, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, const AnyVal &, AnyVal *)
Definition at line 57 of file agg-fn-evaluator.cc.
Function Documentation
static void SetAnyVal (const SlotDescriptor * desc, Tuple * tuple, AnyVal * dst) static
Definition at line 332 of file agg-fn-evaluator.cc.
References impala::Tuple::GetSlot(), impala::Tuple::IsNull(), impala::SlotDescriptor::null_indicator_offset(), impala::AnyValUtil::SetAnyVal(), impala::SlotDescriptor::tuple_offset(), and impala::SlotDescriptor::type().
Referenced by impala::AggFnEvaluator::Merge(), and impala::AggFnEvaluator::Update().