Impala: be/src/exprs/aggregate-functions-test.cc File Reference
aggregate-functions-test.cc File Reference
#include <iostream>
#include <gtest/gtest.h>
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/foreach.hpp>
#include <boost/accumulators/accumulators.hpp>
#include <boost/accumulators/statistics/stats.hpp>
#include <boost/accumulators/statistics/variance.hpp>
#include "common/logging.h"
#include "exprs/aggregate-functions.h"
#include "runtime/multi-precision.h"
#include "udf/udf.h"
#include "udf/uda-test-harness.h"
#include "util/decimal-util.h"
#include "common/names.h"
Functions
template<int RANGE_START, int RANGE_END>
bool CheckAppxMedian (const IntVal &actual, const IntVal &expected)
bool CheckHistogramDistribution (const StringVal &actual, const StringVal &max_expected_stdev)
TEST (HistogramTest, TestInt)
TEST (HistogramTest, TestDecimal)
TEST (HistogramTest, TestString)
int main (int argc, char **argv)
Function Documentation
template<int RANGE_START, int RANGE_END> bool CheckAppxMedian (const IntVal & actual, const IntVal & expected)
Definition at line 43 of file aggregate-functions-test.cc.
References impala_udf::IntVal::val.
bool CheckHistogramDistribution (const StringVal & actual, const StringVal & max_expected_stdev)
Definition at line 47 of file aggregate-functions-test.cc.
References impala_udf::StringVal::len, and impala_udf::StringVal::ptr.
Referenced by TEST().
int main (int argc, char ** argv)
Definition at line 165 of file aggregate-functions-test.cc.
References impala::InitGoogleLoggingSafe(), and impala::DecimalUtil::InitMaxUnscaledDecimal().
TEST (HistogramTest , TestInt)
Definition at line 68 of file aggregate-functions-test.cc.
References CheckHistogramDistribution(), impala_udf::UdaTestHarness< RESULT, INTERMEDIATE, INPUT >::Execute(), impala_udf::UdaTestHarnessBase< RESULT, INTERMEDIATE >::GetErrorMsg(), impala::NUM_BUCKETS, and impala_udf::UdaTestHarnessBase< RESULT, INTERMEDIATE >::SetResultComparator().
TEST (HistogramTest , TestDecimal)
Definition at line 113 of file aggregate-functions-test.cc.
References CheckHistogramDistribution(), impala_udf::UdaTestHarness< RESULT, INTERMEDIATE, INPUT >::Execute(), impala_udf::UdaTestHarnessBase< RESULT, INTERMEDIATE >::GetErrorMsg(), impala::DecimalUtil::MAX_UNSCALED_DECIMAL, impala::NUM_BUCKETS, and impala_udf::UdaTestHarnessBase< RESULT, INTERMEDIATE >::SetResultComparator().
TEST (HistogramTest , TestString)
Definition at line 145 of file aggregate-functions-test.cc.
References impala_udf::UdaTestHarness< RESULT, INTERMEDIATE, INPUT >::Execute(), impala_udf::UdaTestHarnessBase< RESULT, INTERMEDIATE >::GetErrorMsg(), and impala::NUM_BUCKETS.