Impala: be/src/runtime/buffered-tuple-stream-test.cc File Reference
buffered-tuple-stream-test.cc File Reference
#include <boost/scoped_ptr.hpp>
#include <boost/bind.hpp>
#include <boost/filesystem.hpp>
#include <gtest/gtest.h>
#include <string>
#include <limits>
#include "codegen/llvm-codegen.h"
#include "common/init.h"
#include "runtime/buffered-tuple-stream.inline.h"
#include "runtime/row-batch.h"
#include "runtime/tmp-file-mgr.h"
#include "runtime/string-value.h"
#include "service/fe-support.h"
#include "testutil/desc-tbl-builder.h"
#include "util/test-info.h"
#include "gen-cpp/Types_types.h"
#include "gen-cpp/ImpalaInternalService_types.h"
#include "common/names.h"
Classes
class impala::SimpleTupleStreamTest
class impala::SimpleNullStreamTest
class impala::MultiTupleStreamTest
class impala::MultiNullableTupleStreamTest
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Functions
impala::TEST_F (SimpleTupleStreamTest, Basic)
impala::TEST_F (SimpleTupleStreamTest, OneBufferSpill)
impala::TEST_F (SimpleTupleStreamTest, ManyBufferSpill)
impala::TEST_F (SimpleTupleStreamTest, UnpinPin)
impala::TEST_F (SimpleTupleStreamTest, SmallBuffers)
impala::TEST_F (SimpleNullStreamTest, Basic)
impala::TEST_F (MultiTupleStreamTest, MultiTupleOneBufferSpill)
impala::TEST_F (MultiTupleStreamTest, MultiTupleManyBufferSpill)
impala::TEST_F (MultiNullableTupleStreamTest, MultiNullableTupleOneBufferSpill)
impala::TEST_F (MultiNullableTupleStreamTest, MultiNullableTupleManyBufferSpill)
int main (int argc, char **argv)
Variables
const int BATCH_SIZE = 250
static const StringValue impala::STRINGS []
static const int impala::NUM_STRINGS = sizeof(STRINGS) / sizeof(StringValue)
Function Documentation
int main (int argc, char ** argv)
Definition at line 703 of file buffered-tuple-stream-test.cc.
References impala::TestInfo::BE_TEST, impala::TmpFileMgr::Init(), impala::InitCommonRuntime(), impala::InitFeSupport(), and impala::LlvmCodeGen::InitializeLlvm().
Variable Documentation
const int BATCH_SIZE = 250
Definition at line 39 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::ReadValues(), impala::ChildQuery::SetQueryOptions(), impala::TEST_F(), impala::SimpleTupleStreamTest::TestIntValuesInterleaved(), and impala::SimpleTupleStreamTest::TestValues().