Impala: be/src/runtime/buffered-tuple-stream.cc File Reference
buffered-tuple-stream.cc File Reference
#include "runtime/buffered-tuple-stream.h"
#include <boost/bind.hpp>
#include <gutil/strings/substitute.h>
#include "runtime/descriptors.h"
#include "runtime/row-batch.h"
#include "runtime/tuple-row.h"
#include "util/bit-util.h"
#include "util/debug-util.h"
#include "common/names.h"
Functions
int NumPinned (const list< BufferedBlockMgr::Block * > &blocks)
Variables
static const int64_t INITIAL_BLOCK_SIZES []
static const int NUM_SMALL_BLOCKS = sizeof(INITIAL_BLOCK_SIZES) / sizeof(int64_t)
Function Documentation
int NumPinned (const list< BufferedBlockMgr::Block * > & blocks)
Definition at line 84 of file buffered-tuple-stream.cc.
Referenced by impala::BufferedTupleStream::Close(), impala::BufferedTupleStream::NewBlockForWrite(), impala::BufferedTupleStream::NextBlockForRead(), impala::BufferedTupleStream::PinStream(), impala::BufferedTupleStream::PrepareForRead(), and impala::BufferedTupleStream::UnpinBlock().
Variable Documentation
const int64_t INITIAL_BLOCK_SIZES[] static
Initial value:
=
    { 64 * 1024, 512 * 1024 }
Definition at line 33 of file buffered-tuple-stream.cc.
Referenced by impala::BufferedTupleStream::Init(), and impala::BufferedTupleStream::NewBlockForWrite().
const int NUM_SMALL_BLOCKS = sizeof(INITIAL_BLOCK_SIZES) / sizeof(int64_t) static
Definition at line 35 of file buffered-tuple-stream.cc.
Referenced by impala::BufferedTupleStream::NewBlockForWrite().