Impala: be/src/runtime/buffered-block-mgr-test.cc File Reference
buffered-block-mgr-test.cc File Reference
#include <boost/scoped_ptr.hpp>
#include <boost/bind.hpp>
#include <boost/thread/thread.hpp>
#include <boost/filesystem.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <gtest/gtest.h>
#include "common/init.h"
#include "codegen/llvm-codegen.h"
#include "runtime/disk-io-mgr.h"
#include "runtime/buffered-block-mgr.h"
#include "runtime/exec-env.h"
#include "runtime/mem-tracker.h"
#include "runtime/runtime-state.h"
#include "runtime/tmp-file-mgr.h"
#include "service/fe-support.h"
#include "util/disk-info.h"
#include "util/cpu-info.h"
#include "util/promise.h"
#include "util/test-info.h"
#include "util/time.h"
#include "gen-cpp/Types_types.h"
#include "gen-cpp/ImpalaInternalService_types.h"
#include "common/names.h"
Classes
class impala::BufferedBlockMgrTest
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Functions
DECLARE_bool (disk_spill_encryption)
impala::TEST_F (BufferedBlockMgrTest, GetNewBlock)
impala::TEST_F (BufferedBlockMgrTest, GetNewBlockSmallBlocks)
impala::TEST_F (BufferedBlockMgrTest, Pin)
impala::TEST_F (BufferedBlockMgrTest, Eviction)
impala::TEST_F (BufferedBlockMgrTest, Deletion)
impala::TEST_F (BufferedBlockMgrTest, Close)
impala::TEST_F (BufferedBlockMgrTest, WriteError)
impala::TEST_F (BufferedBlockMgrTest, MultipleClients)
impala::TEST_F (BufferedBlockMgrTest, MultipleClientsExtraBuffers)
impala::TEST_F (BufferedBlockMgrTest, ClientOversubscription)
impala::TEST_F (BufferedBlockMgrTest, SingleRandom_plain)
impala::TEST_F (BufferedBlockMgrTest, Multi2Random_plain)
impala::TEST_F (BufferedBlockMgrTest, Multi4Random_plain)
impala::TEST_F (BufferedBlockMgrTest, SingleRandom_encryption)
impala::TEST_F (BufferedBlockMgrTest, Multi2Random_encryption)
impala::TEST_F (BufferedBlockMgrTest, Multi4Random_encryption)
int main (int argc, char **argv)
Variables
const string SCRATCH_DIR = "/tmp/impala-scratch"
Function Documentation
DECLARE_bool (disk_spill_encryption)
int main (int argc, char ** argv)
Definition at line 868 of file buffered-block-mgr-test.cc.
References impala::TestInfo::BE_TEST, impala::TmpFileMgr::Init(), impala::InitCommonRuntime(), impala::InitFeSupport(), and impala::LlvmCodeGen::InitializeLlvm().
Variable Documentation
const string SCRATCH_DIR = "/tmp/impala-scratch"
Definition at line 47 of file buffered-block-mgr-test.cc.
Referenced by impala::TEST_F().