Impala: impala::BaseSequenceScanner Class Reference
impala::BaseSequenceScanner Class Reference abstract
#include <base-sequence-scanner.h>
Classes
struct FileHeader
Public Member Functions
virtual Status Prepare (ScannerContext *context)
One-time initialisation of state that is constant across scan ranges.
virtual void Close ()
virtual Status ProcessSplit ()
virtual ~BaseSequenceScanner ()
Static Public Member Functions
static Status IssueInitialRanges (HdfsScanNode *scan_node, const std::vector< HdfsFileDesc * > &files)
Issue the initial ranges for all sequence container files.
Static Public Attributes
static const int FILE_BLOCK_SIZE = 4096
static const char * LLVM_CLASS_NAME = "class.impala::HdfsScanner"
Protected Types
typedef int(* WriteTuplesFn)(HdfsScanner *, MemPool *, TupleRow *, int, FieldLocation *, int, int, int, int)
Protected Member Functions
virtual FileHeader * AllocateFileHeader ()=0
virtual Status ReadFileHeader ()=0
virtual Status ProcessRange ()=0
virtual THdfsFileFormat::type file_format () const =0
Returns type of scanner: e.g. rcfile, seqfile.
BaseSequenceScanner (HdfsScanNode *, RuntimeState *)
Status ReadSync ()
Status SkipToSync (const uint8_t *sync, int sync_size)
bool finished ()
Status InitializeWriteTuplesFn (HdfsPartitionDescriptor *partition, THdfsFileFormat::type type, const std::string &scanner_name)
void StartNewRowBatch ()
Set batch_ to a new row batch and update tuple_mem_ accordingly.
virtual Status InitNewRange ()=0
Reset internal state for a new scan range.
int GetMemory (MemPool **pool, Tuple **tuple_mem, TupleRow **tuple_row_mem)
Status CommitRows (int num_rows)
void AddFinalRowBatch ()
void AttachPool (MemPool *pool, bool commit_batch)
bool IR_ALWAYS_INLINE EvalConjuncts (TupleRow *row)
int WriteEmptyTuples (RowBatch *row_batch, int num_tuples)
int WriteEmptyTuples (ScannerContext *context, TupleRow *tuple_row, int num_tuples)
Write empty tuples and commit them to the context object.
int WriteAlignedTuples (MemPool *pool, TupleRow *tuple_row_mem, int row_size, FieldLocation *fields, int num_tuples, int max_added_tuples, int slots_per_tuple, int row_start_indx)
Status UpdateDecompressor (const THdfsCompression::type &compression)
Status UpdateDecompressor (const std::string &codec)
bool ReportTupleParseError (FieldLocation *fields, uint8_t *errors, int row_idx)
virtual void LogRowParseError (int row_idx, std::stringstream *)
bool WriteCompleteTuple (MemPool *pool, FieldLocation *fields, Tuple *tuple, TupleRow *tuple_row, Tuple *template_tuple, uint8_t *error_fields, uint8_t *error_in_row)
void ReportColumnParseError (const SlotDescriptor *desc, const char *data, int len)
void InitTuple (Tuple *template_tuple, Tuple *tuple)
Tuple * next_tuple (Tuple *t) const
TupleRow * next_row (TupleRow *r) const
ExprContext * GetConjunctCtx (int idx) const
Static Protected Member Functions
static llvm::Function * CodegenWriteCompleteTuple (HdfsScanNode *, LlvmCodeGen *, const std::vector< ExprContext * > &conjunct_ctxs)
static llvm::Function * CodegenWriteAlignedTuples (HdfsScanNode *, LlvmCodeGen *, llvm::Function *write_tuple_fn)
Protected Attributes
FileHeader * header_
File header for this scan range. This is not owned by the parent scan node.
bool only_parsing_header_
If true, this scanner object is only for processing the header.
HdfsScanNode * scan_node_
The scan node that started this scanner.
RuntimeState * state_
RuntimeState for error reporting.
ScannerContext * context_
Context for this scanner.
ScannerContext::Stream * stream_
The first stream for context_.
std::vector< ExprContext * > conjunct_ctxs_
Tuple * template_tuple_
int tuple_byte_size_
Fixed size of each tuple, in bytes.
Tuple * tuple_
Current tuple pointer into tuple_mem_.
RowBatch * batch_
uint8_t * tuple_mem_
The tuple memory of batch_.
int num_errors_in_file_
number of errors in current file
boost::scoped_ptr< TextConverter > text_converter_
Helper class for converting text to other types;.
int32_t num_null_bytes_
Number of null bytes in the tuple.
Status parse_status_
boost::scoped_ptr< Codec > decompressor_
Decompressor class to use, if any.
THdfsCompression::type decompression_type_
The most recently used decompression type.
boost::scoped_ptr< MemPool > data_buffer_pool_
RuntimeProfile::Counter * decompress_timer_
Time spent decompressing bytes.
WriteTuplesFn write_tuples_fn_
Jitted write tuples function pointer. Null if codegen is disabled.
Static Protected Attributes
static const int SYNC_HASH_SIZE = 16
Size of the sync hash field.
static const int HEADER_SIZE = 1024
static const int SYNC_MARKER = -1
Sync indicator.
Private Member Functions
int ReadPastSize (int64_t file_offset)
int FindSyncBlock (const uint8_t *buffer, int buffer_len, const uint8_t *sync, int sync_len)
void CloseFileRanges (const char *file)
Private Attributes
bool finished_
finished_ is set by ReadSync() and SkipToSync().
int64_t block_start_
int total_block_size_
int num_syncs_
The number of syncs seen by this scanner so far.
RuntimeProfile::Counter * bytes_skipped_counter_
Number of bytes skipped when advancing to next sync on error.
Detailed Description
Superclass for all sequence container based file formats: e.g. SequenceFile, RCFile, Avro Sequence container formats have sync markers periodically in the file. This class is will skip to the start of sync markers for errors and hdfs splits.
Definition at line 35 of file base-sequence-scanner.h.
Member Typedef Documentation
typedef int(* impala::HdfsScanner::WriteTuplesFn)(HdfsScanner *, MemPool *, TupleRow *, int, FieldLocation *, int, int, int, int) protected inherited
Matching typedef for WriteAlignedTuples for codegen. Refer to comments for that function.
Definition at line 212 of file hdfs-scanner.h.
Constructor & Destructor Documentation
BaseSequenceScanner::~BaseSequenceScanner () virtual
Definition at line 71 of file base-sequence-scanner.cc.
BaseSequenceScanner::BaseSequenceScanner (HdfsScanNode * node, RuntimeState * state) protected
Definition at line 63 of file base-sequence-scanner.cc.
Member Function Documentation
void HdfsScanner::AddFinalRowBatch () protected inherited
Attach all remaining resources from context_ to batch_ and send batch_ to the scan node. This must be called after all rows have been committed and no further resources are needed from context_ (in practice this will happen in each scanner subclass's Close() implementation).
Definition at line 145 of file hdfs-scanner.cc.
References impala::HdfsScanNode::AddMaterializedRowBatch(), impala::HdfsScanner::batch_, impala::HdfsScanner::context_, impala::ScannerContext::ReleaseCompletedResources(), and impala::HdfsScanner::scan_node_.
Referenced by impala::HdfsTextScanner::Close(), Close(), and impala::HdfsParquetScanner::Close().
virtual FileHeader* impala::BaseSequenceScanner::AllocateFileHeader () protected pure virtual
Subclasses must implement these functions. The order for calls will be
AllocateFileHeader() - called once per file
ReadFileHeader() - called once per file
InitNewRange()
ProcessRange() In the normal case, 3 and 4 are called for each scan range once. In the case of errors and skipped bytes, 4 is repeatedly called, each time starting right after the sync marker. Allocate a file header object for this scanner. If the scanner needs additional header information, it should subclass FileHeader. The allocated object will be placed in the scan node's pool.
Implemented in impala::HdfsRCFileScanner, impala::HdfsSequenceScanner, and impala::HdfsAvroScanner.
Referenced by ProcessSplit().
void impala::HdfsScanner::AttachPool (MemPool * pool, bool commit_batch) inline protected inherited
Release all memory in 'pool' to batch_. If commit_batch is true, the row batch will be committed. commit_batch should be true if the attached pool is expected to be non-trivial (i.e. a decompression buffer) to minimize scanner mem usage.
Definition at line 256 of file hdfs-scanner.h.
References impala::MemPool::AcquireData(), impala::HdfsScanner::batch_, impala::HdfsScanner::CommitRows(), and impala::RowBatch::tuple_data_pool().
Referenced by impala::HdfsTextScanner::Close(), Close(), impala::HdfsParquetScanner::Close(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ReadCompressedBlock(), impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage(), and impala::HdfsRCFileScanner::ResetRowGroup().
void BaseSequenceScanner::Close () virtual
Release all resources the scanner has allocated. This is the last chance for the scanner to attach any resources to the ScannerContext object.
Reimplemented from impala::HdfsScanner.
Definition at line 82 of file base-sequence-scanner.cc.
References impala::HdfsScanner::AddFinalRowBatch(), impala::HdfsScanner::AttachPool(), impala::ScannerContext::Stream::bytes_left(), impala::HdfsScanner::Close(), impala::BaseSequenceScanner::FileHeader::compression_type, impala::HdfsScanner::data_buffer_pool_, impala::HdfsScanner::decompressor_, file_format(), header_, num_syncs_, only_parsing_header_, impala::HdfsScanNode::RangeComplete(), impala::HdfsScanner::scan_node_, impala::HdfsScanner::stream_, total_block_size_, and VLOG_FILE.
void BaseSequenceScanner::CloseFileRanges (const char * file) private
Close skipped ranges for 'file'. This is only called when processing the header range and the header had an issue.
Definition at line 274 of file base-sequence-scanner.cc.
References bytes_skipped_counter_, COUNTER_ADD, file_format(), impala::HdfsScanNode::GetFileDesc(), only_parsing_header_, impala::HdfsScanNode::RangeComplete(), impala::HdfsScanner::scan_node_, and impala::HdfsFileDesc::splits.
Referenced by ProcessSplit().
Function * HdfsScanner::CodegenWriteAlignedTuples (HdfsScanNode * , LlvmCodeGen * , llvm::Function * write_tuple_fn) static protected inherited
Codegen function to replace WriteAlignedTuples. WriteAlignedTuples is cross compiled to IR. This function loads the precompiled IR function, modifies it and returns the resulting function.
Definition at line 495 of file hdfs-scanner.cc.
References impala::LlvmCodeGen::codegen_timer(), impala::LlvmCodeGen::FinalizeFunction(), impala::LlvmCodeGen::GetFunction(), impala::LlvmCodeGen::ReplaceCallSites(), and SCOPED_TIMER.
Referenced by impala::HdfsTextScanner::Codegen(), and impala::HdfsSequenceScanner::Codegen().
Function * HdfsScanner::CodegenWriteCompleteTuple (HdfsScanNode * , LlvmCodeGen * , const std::vector< ExprContext * > & conjunct_ctxs) static protected inherited
Codegen function to replace WriteCompleteTuple. Should behave identically to WriteCompleteTuple.
Definition at line 296 of file hdfs-scanner.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::TupleDescriptor::byte_size(), impala::LlvmCodeGen::codegen_timer(), impala::LlvmCodeGen::CodegenMemcpy(), impala::TextConverter::CodegenWriteSlot(), impala::HdfsScanNode::ComputeSlotMaterializationOrder(), impala::LlvmCodeGen::context(), impala::CodegenAnyVal::CreateCallWrapped(), impala::LlvmCodeGen::false_value(), impala::LlvmCodeGen::FinalizeFunction(), impala::TupleDescriptor::GenerateLlvmStruct(), impala::Status::GetDetail(), impala::LlvmCodeGen::GetFunction(), impala::LlvmCodeGen::GetIntConstant(), impala::LlvmCodeGen::GetType(), impala::CodegenAnyVal::GetVal(), impala::HdfsScanNode::hdfs_table(), impala::FieldLocation::LLVM_CLASS_NAME, impala::TupleRow::LLVM_CLASS_NAME, impala::Tuple::LLVM_CLASS_NAME, impala::HdfsScanner::LLVM_CLASS_NAME, impala::MemPool::LLVM_CLASS_NAME, impala::HdfsScanNode::materialized_slots(), impala::HdfsTableDescriptor::null_column_value(), impala::HdfsScanNode::num_materialized_partition_keys(), impala::TupleDescriptor::num_null_bytes(), impala::Status::ok(), impala::LlvmCodeGen::OptimizeFunctionWithExprs(), impala::HdfsScanNode::runtime_state(), SCOPED_TIMER, impala::LlvmCodeGen::true_value(), impala::HdfsScanNode::tuple_desc(), impala::HdfsScanNode::tuple_idx(), impala::ColumnType::type, impala::SlotDescriptor::type(), impala::TYPE_BOOLEAN, impala::TYPE_DECIMAL, impala::TYPE_INT, impala::TYPE_TIMESTAMP, and impala::TYPE_TINYINT.
Referenced by impala::HdfsTextScanner::Codegen(), and impala::HdfsSequenceScanner::Codegen().
Status HdfsScanner::CommitRows (int num_rows) protected inherited
Commit num_rows to the current row batch. If this completes, the row batch is enqueued with the scan node and StartNewRowBatch() is called. Returns Status::OK if the query is not cancelled and hasn't exceeded any mem limits. Scanner can call this with 0 rows to flush any pending resources (attached pools and io buffers) to minimize memory consumption.
Definition at line 124 of file hdfs-scanner.cc.
References impala::HdfsScanNode::AddMaterializedRowBatch(), impala::RowBatch::AtCapacity(), impala::HdfsScanner::batch_, impala::TupleDescriptor::byte_size(), impala::Status::CANCELLED, impala::ScannerContext::cancelled(), impala::RowBatch::capacity(), impala::RuntimeState::CheckQueryState(), impala::RowBatch::CommitRows(), impala::HdfsScanner::conjunct_ctxs_, impala::HdfsScanner::context_, impala::ExprContext::FreeLocalAllocations(), impala::ScannerContext::num_completed_io_buffers(), impala::RowBatch::num_rows(), impala::Status::OK, impala::ScannerContext::ReleaseCompletedResources(), RETURN_IF_ERROR, impala::HdfsScanner::scan_node_, impala::HdfsScanner::StartNewRowBatch(), impala::HdfsScanner::state_, impala::HdfsScanNode::tuple_desc(), and impala::HdfsScanner::tuple_mem_.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsScanner::AttachPool(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), and impala::HdfsParquetScanner::ProcessSplit().
bool IR_ALWAYS_INLINE impala::HdfsScanner::EvalConjuncts (TupleRow * row) inline protected inherited
Convenience function for evaluating conjuncts using this scanner's ExprContexts. This must always be inlined so we can correctly replace the call to ExecNode::EvalConjuncts() during codegen.
Definition at line 266 of file hdfs-scanner.h.
References impala::HdfsScanner::conjunct_ctxs_, and impala::ExecNode::EvalConjuncts().
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsAvroScanner::DecodeAvroData(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsScanner::WriteCompleteTuple(), impala::HdfsScanner::WriteEmptyTuples(), and impala::HdfsTextScanner::WriteFields().
virtual THdfsFileFormat::type impala::BaseSequenceScanner::file_format () const protected pure virtual
Returns type of scanner: e.g. rcfile, seqfile.
Implemented in impala::HdfsRCFileScanner, impala::HdfsSequenceScanner, and impala::HdfsAvroScanner.
Referenced by Close(), and CloseFileRanges().
int BaseSequenceScanner::FindSyncBlock (const uint8_t * buffer, int buffer_len, const uint8_t * sync, int sync_len) private
Utility function to look for 'sync' in buffer. Returns the offset into buffer of the end of sync if it is found, otherwise, returns -1.
Definition at line 194 of file base-sequence-scanner.cc.
References offset, and impala::StringSearch::Search().
Referenced by SkipToSync().
bool impala::BaseSequenceScanner::finished () inline protected
Definition at line 117 of file base-sequence-scanner.h.
References finished_.
Referenced by impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsRCFileScanner::ProcessRange().
ExprContext * HdfsScanner::GetConjunctCtx (int idx) const protected inherited
Simple wrapper around conjunct_ctxs_. Used in the codegen'd version of WriteCompleteTuple() because it's easier than writing IR to access conjunct_ctxs_.
Definition at line 79 of file hdfs-scanner-ir.cc.
References impala::HdfsScanner::conjunct_ctxs_, and gen_ir_descriptions::idx.
int HdfsScanner::GetMemory (MemPool ** pool, Tuple ** tuple_mem, TupleRow ** tuple_row_mem) protected inherited
Gets memory for outputting tuples into batch_. *pool is the mem pool that should be used for memory allocated for those tuples. *tuple_mem should be the location to output tuples, and *tuple_row_mem for outputting tuple rows. Returns the maximum number of tuples/tuple rows that can be output (before the current row batch is complete and a new one is allocated). Memory returned from this call is invalidated after calling CommitRows. Callers must call GetMemory again after calling this function.
Definition at line 115 of file hdfs-scanner.cc.
References impala::RowBatch::AddRow(), impala::HdfsScanner::batch_, impala::RowBatch::capacity(), impala::RowBatch::GetRow(), impala::RowBatch::num_rows(), impala::RowBatch::tuple_data_pool(), and impala::HdfsScanner::tuple_mem_.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsRCFileScanner::ProcessRange().
Status HdfsScanner::InitializeWriteTuplesFn (HdfsPartitionDescriptor * partition, THdfsFileFormat::type type, const std::string & scanner_name) protected inherited
Initializes write_tuples_fn_ to the jitted function if codegen is possible.
partition - partition descriptor for this scanner/scan range
type - type for this scanner
scanner_name - debug string name for this scanner (e.g. HdfsTextScanner)
Definition at line 87 of file hdfs-scanner.cc.
References impala::HdfsPartitionDescriptor::escape_char(), impala::HdfsScanNode::GetCodegenFn(), impala::ExecNode::id(), impala::HdfsScanNode::IncNumScannersCodegenDisabled(), impala::HdfsScanNode::IncNumScannersCodegenEnabled(), impala::Status::OK, impala::HdfsScanner::scan_node_, impala::TupleDescriptor::string_slots(), impala::HdfsScanNode::tuple_desc(), and impala::HdfsScanner::write_tuples_fn_.
Referenced by impala::HdfsSequenceScanner::InitNewRange(), and impala::HdfsTextScanner::ResetScanner().
virtual Status impala::HdfsScanner::InitNewRange () protected pure virtual inherited
Reset internal state for a new scan range.
Implemented in impala::HdfsRCFileScanner, impala::HdfsParquetScanner, impala::HdfsSequenceScanner, impala::HdfsAvroScanner, and impala::HdfsTextScanner.
Referenced by ProcessSplit().
void impala::HdfsScanner::InitTuple (Tuple * template_tuple, Tuple * tuple) inline protected inherited
Initialize a tuple. TODO: only copy over non-null slots. TODO: InitTuple is called frequently, avoid the if, perhaps via templatization.
Definition at line 355 of file hdfs-scanner.h.
References impala::HdfsScanner::num_null_bytes_, and impala::HdfsScanner::tuple_byte_size_.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsAvroScanner::DecodeAvroData(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsScanner::WriteCompleteTuple(), and impala::HdfsTextScanner::WriteFields().
Status BaseSequenceScanner::IssueInitialRanges (HdfsScanNode * scan_node, const std::vector< HdfsFileDesc * > & files) static
Issue the initial ranges for all sequence container files.
Definition at line 40 of file base-sequence-scanner.cc.
References impala::HdfsScanNode::AddDiskIoRanges(), impala::HdfsScanNode::AllocateScanRange(), HEADER_SIZE, impala::Status::OK, impala::ScanRangeMetadata::partition_id, and RETURN_IF_ERROR.
Referenced by impala::HdfsScanNode::GetNext().
void HdfsScanner::LogRowParseError (int row_idx, std::stringstream *) protected virtual inherited
Utility function to append an error message for an invalid row. This is called from ReportTupleParseError() row_idx is the index of the row in the current batch. Subclasses should override this function (i.e. text needs to join boundary rows). Since this is only in the error path, vtable overhead is acceptable.
Reimplemented in impala::HdfsSequenceScanner, and impala::HdfsTextScanner.
Definition at line 572 of file hdfs-scanner.cc.
Referenced by impala::HdfsScanner::ReportTupleParseError().
TupleRow* impala::HdfsScanner::next_row (TupleRow * r) const inline protected inherited
Definition at line 368 of file hdfs-scanner.h.
References impala::HdfsScanner::batch_, and impala::RowBatch::row_byte_size().
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsAvroScanner::DecodeAvroData(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsScanner::WriteEmptyTuples(), and impala::HdfsTextScanner::WriteFields().
Tuple* impala::HdfsScanner::next_tuple (Tuple * t) const inline protected inherited
Definition at line 363 of file hdfs-scanner.h.
References impala::HdfsScanner::tuple_byte_size_.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsAvroScanner::DecodeAvroData(), impala::HdfsRCFileScanner::ProcessRange(), and impala::HdfsTextScanner::WriteFields().
Status BaseSequenceScanner::Prepare (ScannerContext * context) virtual
One-time initialisation of state that is constant across scan ranges.
Reimplemented from impala::HdfsScanner.
Reimplemented in impala::HdfsRCFileScanner, and impala::HdfsSequenceScanner.
Definition at line 74 of file base-sequence-scanner.cc.
References ADD_COUNTER, bytes_skipped_counter_, impala::Status::OK, impala::HdfsScanner::Prepare(), ReadPastSize(), RETURN_IF_ERROR, impala::ExecNode::runtime_profile(), impala::HdfsScanner::scan_node_, impala::ScannerContext::Stream::set_read_past_size_cb(), and impala::HdfsScanner::stream_.
Referenced by impala::HdfsSequenceScanner::Prepare(), and impala::HdfsRCFileScanner::Prepare().
virtual Status impala::BaseSequenceScanner::ProcessRange () protected pure virtual
Process the current range until the end or an error occurred. Note this might be called multiple times if we skip over bad data. This function should read from the underlying ScannerContext materializing tuples to the context. When this function is called, it is guaranteed to be at the start of a data block (i.e. right after the sync marker).
Implemented in impala::HdfsRCFileScanner, impala::HdfsSequenceScanner, and impala::HdfsAvroScanner.
Referenced by ProcessSplit().
Status BaseSequenceScanner::ProcessSplit () virtual
Process an entire split, reading bytes from the context's streams. Context is initialized with the split data (e.g. template tuple, partition descriptor, etc). This function should only return on error or end of scan range.
Implements impala::HdfsScanner.
Definition at line 100 of file base-sequence-scanner.cc.
References impala::RuntimeState::abort_on_error(), impala::ObjectPool::Add(), impala::HdfsScanNode::AddDiskIoRanges(), AllocateFileHeader(), bytes_skipped_counter_, CloseFileRanges(), COUNTER_ADD, impala::ScannerContext::Stream::eof(), impala::ScannerContext::Stream::file_offset(), impala::ScannerContext::Stream::filename(), finished_, impala::HdfsScanNode::GetFileDesc(), impala::HdfsScanNode::GetFileMetadata(), header_, impala::BaseSequenceScanner::FileHeader::header_size, impala::HdfsScanner::InitNewRange(), impala::BaseSequenceScanner::FileHeader::is_compressed, impala::Status::IsCancelled(), impala::Status::IsMemLimitExceeded(), impala::RuntimeState::LogError(), impala::Status::msg(), impala::RuntimeState::obj_pool(), impala::Status::OK, impala::Status::ok(), only_parsing_header_, impala::HdfsScanner::parse_status_, ProcessRange(), ReadFileHeader(), RETURN_IF_ERROR, RETURN_IF_FALSE, impala::HdfsScanner::scan_node_, impala::ScannerContext::Stream::set_contains_tuple_data(), impala::HdfsScanNode::SetFileMetadata(), impala::ScannerContext::Stream::SkipBytes(), SkipToSync(), impala::HdfsScanner::state_, impala::HdfsScanner::stream_, impala::BaseSequenceScanner::FileHeader::sync, and SYNC_HASH_SIZE.
virtual Status impala::BaseSequenceScanner::ReadFileHeader () protected pure virtual
Read the file header. The underlying ScannerContext is at the start of the file header. This function must read the file header (which advances context_ past it) and initialize header_.
Implemented in impala::HdfsRCFileScanner, impala::HdfsSequenceScanner, and impala::HdfsAvroScanner.
Referenced by ProcessSplit().
int BaseSequenceScanner::ReadPastSize (int64_t file_offset) private
Callback for stream_ to compute how much to read past the scan range. Returns the average number of bytes per block minus how far 'file_offset' is into the current block.
Definition at line 284 of file base-sequence-scanner.cc.
References BLOCK_SIZE_PADDING_PERCENT, block_start_, impala::RuntimeState::io_mgr(), impala::DiskIoMgr::max_read_buffer_size(), MIN_SYNC_READ_SIZE, num_syncs_, REMAINING_BLOCK_SIZE_GUESS, impala::HdfsScanner::state_, and total_block_size_.
Referenced by Prepare().
Status BaseSequenceScanner::ReadSync () protected
Read and validate sync marker against header_->sync. Returns non-ok if the sync marker did not match. Scanners should always use this function to read sync markers, otherwise finished() might not be updated correctly. If finished() returns true after calling this function, scanners must not process any more records.
Definition at line 170 of file base-sequence-scanner.cc.
References block_start_, impala::ScannerContext::Stream::eof(), impala::ScannerContext::Stream::eosr(), impala::ScannerContext::Stream::file_offset(), finished_, impala::ScannerContext::Stream::GetBytes(), impala::hash, header_, impala::ReadWriteUtil::HexDump(), num_syncs_, impala::Status::OK, impala::HdfsScanner::parse_status_, RETURN_IF_FALSE, impala::HdfsScanner::stream_, impala::BaseSequenceScanner::FileHeader::sync, SYNC_HASH_SIZE, and total_block_size_.
Referenced by impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsRCFileScanner::ProcessRange().
void HdfsScanner::ReportColumnParseError (const SlotDescriptor * desc, const char * data, int len) protected inherited
Report parse error for column @ desc. If abort_on_error is true, sets parse_status_ to the error message.
Definition at line 577 of file hdfs-scanner.cc.
References impala::RuntimeState::abort_on_error(), impala::SlotDescriptor::col_pos(), impala::RuntimeState::LogError(), impala::RuntimeState::LogHasSpace(), impala::HdfsScanNode::num_partition_keys(), impala::Status::ok(), impala::HdfsScanner::parse_status_, impala::HdfsScanner::scan_node_, impala::HdfsScanner::state_, and impala::SlotDescriptor::type().
Referenced by impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsScanner::ReportTupleParseError(), and impala::HdfsTextScanner::WritePartialTuple().
bool HdfsScanner::ReportTupleParseError (FieldLocation * fields, uint8_t * errors, int row_idx) protected inherited
Utility function to report parse errors for each field. If errors[i] is nonzero, fields[i] had a parse error. row_idx is the idx of the row in the current batch that had the parse error Returns false if parsing should be aborted. In this case parse_status_ is set to the error. This is called from WriteAlignedTuples.
Definition at line 546 of file hdfs-scanner.cc.
References impala::RuntimeState::abort_on_error(), impala::ScannerContext::Stream::filename(), impala::RuntimeState::LogError(), impala::RuntimeState::LogHasSpace(), impala::HdfsScanner::LogRowParseError(), impala::HdfsScanNode::materialized_slots(), impala::HdfsScanner::num_errors_in_file_, impala::Status::ok(), impala::HdfsScanner::parse_status_, impala::HdfsScanner::ReportColumnParseError(), impala::RuntimeState::ReportFileErrors(), impala::HdfsScanner::scan_node_, impala::HdfsScanner::state_, and impala::HdfsScanner::stream_.
Referenced by impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsScanner::WriteAlignedTuples().
Status BaseSequenceScanner::SkipToSync (const uint8_t * sync, int sync_size) protected
Utility function to advance past the next sync marker, reading bytes from stream_. If no sync is found in the scan range, return Status::OK and sets finished_ to true. It is safe to call this function past eosr.
sync: sync marker to search for (does not include 0xFFFFFFFF prefix)
sync_size: number of bytes for sync
Definition at line 212 of file base-sequence-scanner.cc.
References block_start_, impala::ScannerContext::Stream::bytes_left(), impala::ScannerContext::Stream::eof(), impala::ScannerContext::Stream::eosr(), impala::ScannerContext::Stream::file_offset(), impala::ScannerContext::Stream::filename(), FindSyncBlock(), finished_, impala::ScannerContext::Stream::GetBuffer(), impala::ScannerContext::Stream::GetBytes(), num_syncs_, offset, impala::Status::OK, impala::HdfsScanner::parse_status_, RETURN_IF_ERROR, RETURN_IF_FALSE, impala::ScannerContext::Stream::SkipBytes(), impala::HdfsScanner::stream_, and VLOG_FILE.
Referenced by ProcessSplit().
void HdfsScanner::StartNewRowBatch () protected inherited
Set batch_ to a new row batch and update tuple_mem_ accordingly.
Definition at line 108 of file hdfs-scanner.cc.
References impala::MemPool::Allocate(), impala::HdfsScanner::batch_, impala::RuntimeState::batch_size(), impala::ExecNode::mem_tracker(), impala::ExecNode::row_desc(), impala::HdfsScanner::scan_node_, impala::HdfsScanner::state_, impala::HdfsScanner::tuple_byte_size_, impala::RowBatch::tuple_data_pool(), and impala::HdfsScanner::tuple_mem_.
Referenced by impala::HdfsScanner::CommitRows(), and impala::HdfsScanner::Prepare().
Status HdfsScanner::UpdateDecompressor (const THdfsCompression::type & compression) protected inherited
Update the decompressor_ object given a compression type or codec name. Depending on the old compression type and the new one, it may close the old decompressor and/or create a new one of different type.
Definition at line 513 of file hdfs-scanner.cc.
References impala::Codec::CreateDecompressor(), impala::HdfsScanner::data_buffer_pool_, impala::HdfsScanner::decompression_type_, impala::HdfsScanner::decompressor_, impala::Status::OK, RETURN_IF_ERROR, impala::HdfsScanner::scan_node_, impala::TupleDescriptor::string_slots(), and impala::HdfsScanNode::tuple_desc().
Referenced by impala::HdfsAvroScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), and impala::HdfsTextScanner::ProcessSplit().
Status impala::HdfsScanner::UpdateDecompressor (const std::string & codec) protected inherited
int HdfsScanner::WriteAlignedTuples (MemPool * pool, TupleRow * tuple_row_mem, int row_size, FieldLocation * fields, int num_tuples, int max_added_tuples, int slots_per_tuple, int row_start_indx) protected inherited
Processes batches of fields and writes them out to tuple_row_mem.
'pool' mempool to allocate from for auxiliary tuple memory
'tuple_row_mem' preallocated tuple_row memory this function must use.
'fields' must start at the beginning of a tuple.
'num_tuples' number of tuples to process
'max_added_tuples' the maximum number of tuples that should be added to the batch.
'row_start_index' is the number of rows that have already been processed as part of WritePartialTuple. Returns the number of tuples added to the row batch. This can be less than num_tuples/tuples_till_limit because of failed conjuncts. Returns -1 if parsing should be aborted due to parse errors.
Definition at line 33 of file hdfs-scanner-ir.cc.
References impala::HdfsScanner::ReportTupleParseError(), impala::HdfsScanner::template_tuple_, impala::HdfsScanner::tuple_, impala::HdfsScanner::tuple_byte_size_, UNLIKELY, and impala::HdfsScanner::WriteCompleteTuple().
Referenced by impala::HdfsSequenceScanner::ProcessDecompressedBlock(), and impala::HdfsTextScanner::WriteFields().
bool HdfsScanner::WriteCompleteTuple (MemPool * pool, FieldLocation * fields, Tuple * tuple, TupleRow * tuple_row, Tuple * template_tuple, uint8_t * error_fields, uint8_t * error_in_row) protected inherited
Writes out all slots for 'tuple' from 'fields'. 'fields' must be aligned to the start of the tuple (e.g. fields[0] maps to slots[0]). After writing the tuple, it will be evaluated against the conjuncts.
error_fields is an out array. error_fields[i] will be set to true if the ith field had a parse error
error_in_row is an out bool. It is set to true if any field had parse errors Returns whether the resulting tuplerow passed the conjuncts. The parsing of the fields and evaluating against conjuncts is combined in this function. This is done so it can be possible to evaluate conjuncts as slots are materialized (on partial tuples). This function is replaced by a codegen'd function at runtime. This is the reason that the out error parameters are typed uint8_t instead of bool. We need to be able to match this function's signature identically for the codegen'd function. Bool's as out parameters can get converted to bytes by the compiler and rather than implicitly depending on that to happen, we will explicitly type them to bytes. TODO: revisit this
Definition at line 217 of file hdfs-scanner.cc.
References impala::HdfsScanner::EvalConjuncts(), impala::HdfsScanner::InitTuple(), impala::FieldLocation::len, impala::HdfsScanNode::materialized_slots(), impala::HdfsScanner::scan_node_, impala::TupleRow::SetTuple(), impala::HdfsScanner::text_converter_, impala::HdfsScanNode::tuple_idx(), and UNLIKELY.
Referenced by impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsScanner::WriteAlignedTuples().
int HdfsScanner::WriteEmptyTuples (RowBatch * row_batch, int num_tuples) protected inherited
Utility method to write out tuples when there are no materialized fields (e.g. select count(*) or only partition keys). num_tuples - Total number of tuples to write out. Returns the number of tuples added to the row batch.
Definition at line 157 of file hdfs-scanner.cc.
References impala::RowBatch::AddRow(), impala::RowBatch::AddRows(), impala::RowBatch::AtCapacity(), impala::RowBatch::capacity(), impala::RowBatch::CommitLastRow(), impala::RowBatch::CommitRows(), impala::HdfsScanner::EvalConjuncts(), impala::RowBatch::GetRow(), impala::RowBatch::INVALID_ROW_INDEX, impala::RowBatch::num_rows(), impala::HdfsScanner::scan_node_, impala::TupleRow::SetTuple(), impala::HdfsScanner::template_tuple_, and impala::HdfsScanNode::tuple_idx().
Referenced by impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsRCFileScanner::ProcessRange().
int HdfsScanner::WriteEmptyTuples (ScannerContext * context, TupleRow * tuple_row, int num_tuples) protected inherited
Write empty tuples and commit them to the context object.
Definition at line 195 of file hdfs-scanner.cc.
References impala::HdfsScanner::EvalConjuncts(), impala::HdfsScanner::next_row(), impala::HdfsScanner::scan_node_, impala::TupleRow::SetTuple(), impala::HdfsScanner::template_tuple_, and impala::HdfsScanNode::tuple_idx().
Member Data Documentation
RowBatch* impala::HdfsScanner::batch_ protected inherited
The current row batch being populated. Creating new row batches, attaching context resources, and handing off to the scan node is handled by this class in CommitRows(), but AttachPool() must be called by scanner subclasses to attach any memory allocated by that subclass. All row batches created by this class are transferred to the scan node (i.e., all batches are ultimately owned by the scan node).
Definition at line 177 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::AddFinalRowBatch(), impala::HdfsScanner::AttachPool(), impala::HdfsScanner::CommitRows(), impala::HdfsScanner::GetMemory(), impala::HdfsScanner::next_row(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessSplit(), impala::HdfsScanner::StartNewRowBatch(), impala::HdfsTextScanner::WriteFields(), and impala::HdfsScanner::~HdfsScanner().
int64_t impala::BaseSequenceScanner::block_start_ private
Byte offset from the start of the file for the current block. Note that block refers to all the data between two syncs.
Definition at line 150 of file base-sequence-scanner.h.
Referenced by ReadPastSize(), ReadSync(), and SkipToSync().
RuntimeProfile::Counter* impala::BaseSequenceScanner::bytes_skipped_counter_ private
Number of bytes skipped when advancing to next sync on error.
Definition at line 174 of file base-sequence-scanner.h.
Referenced by CloseFileRanges(), Prepare(), and ProcessSplit().
std::vector<ExprContext*> impala::HdfsScanner::conjunct_ctxs_ protected inherited
ExprContext for each conjunct. Each scanner has its own ExprContexts so the conjuncts can be safely evaluated in parallel.
Definition at line 154 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::Close(), impala::HdfsScanner::CommitRows(), impala::HdfsScanner::EvalConjuncts(), impala::HdfsScanner::GetConjunctCtx(), and impala::HdfsScanner::Prepare().
ScannerContext* impala::HdfsScanner::context_ protected inherited
Context for this scanner.
Definition at line 147 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::AddFinalRowBatch(), impala::HdfsParquetScanner::AssembleRows(), impala::HdfsScanner::CommitRows(), impala::HdfsTextScanner::FillByteBufferCompressedFile(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsParquetScanner::InitColumns(), impala::HdfsTextScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsScanner::Prepare(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsParquetScanner::ProcessSplit(), and impala::HdfsTextScanner::ResetScanner().
boost::scoped_ptr<MemPool> impala::HdfsScanner::data_buffer_pool_ protected inherited
Pool to allocate per data block memory. This should be used with the decompressor and any other per data block allocations.
Definition at line 205 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::Close(), Close(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ReadCompressedBlock(), impala::HdfsRCFileScanner::ReadRowGroup(), impala::HdfsRCFileScanner::ResetRowGroup(), impala::HdfsScanner::UpdateDecompressor(), and impala::HdfsTextScanner::WritePartialTuple().
RuntimeProfile::Counter* impala::HdfsScanner::decompress_timer_ protected inherited
Time spent decompressing bytes.
Definition at line 208 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::FillByteBufferCompressedFile(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsSequenceScanner::GetRecord(), impala::HdfsScanner::Prepare(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsRCFileScanner::ReadColumnBuffers(), impala::HdfsSequenceScanner::ReadCompressedBlock(), impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage(), and impala::HdfsRCFileScanner::ReadKeyBuffers().
THdfsCompression::type impala::HdfsScanner::decompression_type_ protected inherited
The most recently used decompression type.
Definition at line 201 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::FillByteBuffer(), impala::HdfsTextScanner::FillByteBufferCompressedFile(), and impala::HdfsScanner::UpdateDecompressor().
boost::scoped_ptr<Codec> impala::HdfsScanner::decompressor_ protected inherited
Decompressor class to use, if any.
Definition at line 198 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::Close(), Close(), impala::HdfsScanner::Close(), impala::HdfsTextScanner::FillByteBuffer(), impala::HdfsTextScanner::FillByteBufferCompressedFile(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsSequenceScanner::GetRecord(), impala::HdfsRCFileScanner::InitNewRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsRCFileScanner::ReadColumnBuffers(), impala::HdfsSequenceScanner::ReadCompressedBlock(), impala::HdfsRCFileScanner::ReadKeyBuffers(), and impala::HdfsScanner::UpdateDecompressor().
const int impala::HdfsScanner::FILE_BLOCK_SIZE = 4096 static inherited
Assumed size of an OS file block. Used mostly when reading file format headers, etc. This probably ought to be a derived number from the environment.
Definition at line 95 of file hdfs-scanner.h.
bool impala::BaseSequenceScanner::finished_ private
finished_ is set by ReadSync() and SkipToSync().
Set to true when this scanner has processed all the bytes it is responsible for, i.e., when it reads a sync occurring completely in the next scan range, as this is the first sync that the next scan range will be able to locate. (Each scan range is responsible for the first complete sync in the range through the first complete sync in the next range.) We need this variable because checking context_->eosr() after reading each sync is insufficient. If a sync marker spans two scan ranges, the first scan range must process the following block since the second scan range cannot find the incomplete sync. context_->eosr() will not alert us to this situation, causing the block to be skipped.
Definition at line 146 of file base-sequence-scanner.h.
Referenced by finished(), ProcessSplit(), ReadSync(), and SkipToSync().
FileHeader* impala::BaseSequenceScanner::header_ protected
File header for this scan range. This is not owned by the parent scan node.
Definition at line 127 of file base-sequence-scanner.h.
Referenced by Close(), impala::HdfsSequenceScanner::GetRecord(), impala::HdfsAvroScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsRCFileScanner::InitNewRange(), impala::HdfsAvroScanner::ParseMetadata(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), ProcessSplit(), impala::HdfsRCFileScanner::ReadColumnBuffers(), impala::HdfsAvroScanner::ReadFileHeader(), impala::HdfsSequenceScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadKeyBuffers(), impala::HdfsRCFileScanner::ReadNumColumnsMetadata(), and ReadSync().
const int BaseSequenceScanner::HEADER_SIZE = 1024 static protected
Estimate of header size in bytes. This is initial number of bytes to issue per file. If the estimate is too low, more bytes will be read as necessary.
Definition at line 121 of file base-sequence-scanner.h.
Referenced by IssueInitialRanges().
const char * HdfsScanner::LLVM_CLASS_NAME = "class.impala::HdfsScanner" static inherited
Scanner subclasses must implement these static functions as well. Unfortunately, c++ does not allow static virtual functions. Issue the initial ranges for 'files'. HdfsFileDesc groups all the splits assigned to this scan node by file. This is called before any of the scanner subclasses are created to process splits in 'files'. The strategy on how to parse the scan ranges depends on the file format.
For simple text files, all the splits are simply issued to the io mgr and one split == one scan range.
For formats with a header, the metadata is first parsed, and then the ranges are issued to the io mgr. There is one scan range for the header and one range for each split.
For columnar formats, the header is parsed and only the relevant byte ranges should be issued to the io mgr. This is one range for the metadata and one range for each column, for each split. This function is how scanners can pick their strategy. void IssueInitialRanges(HdfsScanNode* scan_node, const std::vector<HdfsFileDesc*>& files); Codegen all functions for this scanner. The codegen'd function is specific to the scanner subclass but not specific to each scanner object. We don't want to codegen the functions for each scanner object. llvm::Function* Codegen(HdfsScanNode* scan_node);
Definition at line 137 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::CodegenWriteCompleteTuple().
int impala::HdfsScanner::num_errors_in_file_ protected inherited
number of errors in current file
Definition at line 183 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::ReportTupleParseError().
int32_t impala::HdfsScanner::num_null_bytes_ protected inherited
Number of null bytes in the tuple.
Definition at line 189 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::InitTuple().
int impala::BaseSequenceScanner::num_syncs_ private
The number of syncs seen by this scanner so far.
Definition at line 157 of file base-sequence-scanner.h.
Referenced by Close(), ReadPastSize(), ReadSync(), and SkipToSync().
bool impala::BaseSequenceScanner::only_parsing_header_ protected
If true, this scanner object is only for processing the header.
Definition at line 130 of file base-sequence-scanner.h.
Referenced by Close(), CloseFileRanges(), impala::HdfsAvroScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsRCFileScanner::InitNewRange(), and ProcessSplit().
Status impala::HdfsScanner::parse_status_ protected inherited
Contains current parse status to minimize the number of Status objects returned. This significantly minimizes the cross compile dependencies for llvm since status objects inline a bunch of string functions. Also, status objects aren't extremely cheap to create and destroy.
Definition at line 195 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsSequenceScanner::GetRecord(), impala::HdfsAvroScanner::ParseMetadata(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), ProcessSplit(), impala::HdfsSequenceScanner::ReadBlockHeader(), impala::HdfsRCFileScanner::ReadColumnBuffers(), impala::HdfsSequenceScanner::ReadCompressedBlock(), impala::HdfsAvroScanner::ReadFileHeader(), impala::HdfsSequenceScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadKeyBuffers(), impala::HdfsRCFileScanner::ReadNumColumnsMetadata(), impala::HdfsRCFileScanner::ReadRowGroupHeader(), ReadSync(), impala::HdfsScanner::ReportColumnParseError(), impala::HdfsScanner::ReportTupleParseError(), SkipToSync(), and impala::HdfsTextScanner::WriteFields().
HdfsScanNode* impala::HdfsScanner::scan_node_ protected inherited
The scan node that started this scanner.
Definition at line 141 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::AddFinalRowBatch(), impala::HdfsParquetScanner::AssembleRows(), impala::HdfsParquetScanner::BaseColumnReader::BaseColumnReader(), impala::HdfsTextScanner::Close(), Close(), impala::HdfsParquetScanner::Close(), CloseFileRanges(), impala::HdfsScanner::CommitRows(), impala::HdfsParquetScanner::CreateColumnReaders(), impala::HdfsParquetScanner::CreateReader(), impala::HdfsRCFileScanner::DebugString(), impala::HdfsAvroScanner::DecodeAvroData(), impala::HdfsTextScanner::FillByteBufferCompressedFile(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsParquetScanner::InitColumns(), impala::HdfsScanner::InitializeWriteTuplesFn(), impala::HdfsTextScanner::InitNewRange(), impala::HdfsAvroScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsRCFileScanner::InitNewRange(), impala::HdfsAvroScanner::ParseMetadata(), impala::HdfsTextScanner::Prepare(), Prepare(), impala::HdfsParquetScanner::Prepare(), impala::HdfsScanner::Prepare(), impala::HdfsSequenceScanner::Prepare(), impala::HdfsRCFileScanner::Prepare(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), ProcessSplit(), impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage(), impala::HdfsRCFileScanner::ReadRowGroup(), impala::HdfsScanner::ReportColumnParseError(), impala::HdfsScanner::ReportTupleParseError(), impala::HdfsTextScanner::ResetScanner(), impala::HdfsAvroScanner::ResolveSchemas(), impala::HdfsScanner::StartNewRowBatch(), impala::HdfsScanner::UpdateDecompressor(), impala::HdfsAvroScanner::VerifyTypesMatch(), impala::HdfsScanner::WriteCompleteTuple(), impala::HdfsScanner::WriteEmptyTuples(), impala::HdfsTextScanner::WriteFields(), and impala::HdfsTextScanner::WritePartialTuple().
RuntimeState* impala::HdfsScanner::state_ protected inherited
RuntimeState for error reporting.
Definition at line 144 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::Close(), impala::HdfsScanner::CommitRows(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsTextScanner::Prepare(), impala::HdfsScanner::Prepare(), impala::HdfsSequenceScanner::Prepare(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsRCFileScanner::ProcessRange(), ProcessSplit(), impala::HdfsSequenceScanner::ReadCompressedBlock(), ReadPastSize(), impala::HdfsRCFileScanner::ReadRowGroup(), impala::HdfsScanner::ReportColumnParseError(), impala::HdfsScanner::ReportTupleParseError(), impala::HdfsAvroScanner::ResolveSchemas(), impala::HdfsScanner::StartNewRowBatch(), impala::HdfsParquetScanner::ValidateColumn(), and impala::HdfsTextScanner::WriteFields().
ScannerContext::Stream* impala::HdfsScanner::stream_ protected inherited
The first stream for context_.
Definition at line 150 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::Close(), Close(), impala::HdfsParquetScanner::CreateColumnReaders(), impala::HdfsRCFileScanner::DebugString(), impala::HdfsTextScanner::FillByteBuffer(), impala::HdfsTextScanner::FillByteBufferCompressedFile(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsTextScanner::FindFirstTuple(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsSequenceScanner::GetRecord(), impala::HdfsTextScanner::InitNewRange(), impala::HdfsRCFileScanner::InitNewRange(), impala::HdfsRCFileScanner::NextField(), impala::HdfsAvroScanner::ParseMetadata(), Prepare(), impala::HdfsScanner::Prepare(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsTextScanner::ProcessSplit(), ProcessSplit(), impala::HdfsParquetScanner::ProcessSplit(), impala::HdfsSequenceScanner::ReadBlockHeader(), impala::HdfsRCFileScanner::ReadColumnBuffers(), impala::HdfsSequenceScanner::ReadCompressedBlock(), impala::HdfsAvroScanner::ReadFileHeader(), impala::HdfsSequenceScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadKeyBuffers(), impala::HdfsRCFileScanner::ReadNumColumnsMetadata(), impala::HdfsRCFileScanner::ReadRowGroupHeader(), ReadSync(), impala::HdfsScanner::ReportTupleParseError(), SkipToSync(), impala::HdfsParquetScanner::ValidateFileMetadata(), impala::HdfsAvroScanner::VerifyTypesMatch(), and impala::HdfsTextScanner::WriteFields().
const int impala::BaseSequenceScanner::SYNC_HASH_SIZE = 16 static protected
Size of the sync hash field.
Definition at line 49 of file base-sequence-scanner.h.
Referenced by ProcessSplit(), impala::HdfsAvroScanner::ReadFileHeader(), impala::HdfsSequenceScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadFileHeader(), and ReadSync().
const int BaseSequenceScanner::SYNC_MARKER = -1 static protected
Sync indicator.
Definition at line 124 of file base-sequence-scanner.h.
Referenced by impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsRCFileScanner::ProcessRange().
Tuple* impala::HdfsScanner::template_tuple_ protected inherited
A partially materialized tuple with only partition key slots set. The non-partition key slots are set to NULL. The template tuple must be copied into tuple_ before any of the other slots are materialized. Pointer is NULL if there are no partition key slots. This template tuple is computed once for each file and valid for the duration of that file. It is owned by the HDFS scan node.
Definition at line 164 of file hdfs-scanner.h.
Referenced by impala::HdfsAvroScanner::AllocateFileHeader(), impala::HdfsParquetScanner::AssembleRows(), impala::HdfsParquetScanner::CreateColumnReaders(), impala::HdfsAvroScanner::DecodeAvroData(), impala::HdfsAvroScanner::InitNewRange(), impala::HdfsScanner::Prepare(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsAvroScanner::ResolveSchemas(), impala::HdfsScanner::WriteAlignedTuples(), impala::HdfsScanner::WriteEmptyTuples(), and impala::HdfsTextScanner::WriteFields().
boost::scoped_ptr<TextConverter> impala::HdfsScanner::text_converter_ protected inherited
Helper class for converting text to other types;.
Definition at line 186 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsRCFileScanner::Prepare(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsScanner::WriteCompleteTuple(), and impala::HdfsTextScanner::WritePartialTuple().
int impala::BaseSequenceScanner::total_block_size_ private
The total number of bytes in all blocks this scan range has processed (updated in SkipToSync(), so only includes blocks that were completely processed).
Definition at line 154 of file base-sequence-scanner.h.
Referenced by Close(), ReadPastSize(), and ReadSync().
Tuple* impala::HdfsScanner::tuple_ protected inherited
Current tuple pointer into tuple_mem_.
Definition at line 170 of file hdfs-scanner.h.
Referenced by impala::HdfsTextScanner::FinishScanRange(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsScanner::WriteAlignedTuples(), and impala::HdfsTextScanner::WriteFields().
int impala::HdfsScanner::tuple_byte_size_ protected inherited
Fixed size of each tuple, in bytes.
Definition at line 167 of file hdfs-scanner.h.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsScanner::InitTuple(), impala::HdfsScanner::next_tuple(), impala::HdfsScanner::StartNewRowBatch(), and impala::HdfsScanner::WriteAlignedTuples().
uint8_t* impala::HdfsScanner::tuple_mem_ protected inherited
The tuple memory of batch_.
Definition at line 180 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::CommitRows(), impala::HdfsScanner::GetMemory(), and impala::HdfsScanner::StartNewRowBatch().
WriteTuplesFn impala::HdfsScanner::write_tuples_fn_ protected inherited
Jitted write tuples function pointer. Null if codegen is disabled.
Definition at line 215 of file hdfs-scanner.h.
Referenced by impala::HdfsScanner::InitializeWriteTuplesFn(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), and impala::HdfsTextScanner::WriteFields().
The documentation for this class was generated from the following files:
be/src/exec/base-sequence-scanner.h
be/src/exec/base-sequence-scanner.cc