Impala: com.cloudera.impala.authorization.AuthorizationChecker Class Reference
com.cloudera.impala.authorization.AuthorizationChecker Class Reference
Public Member Functions
AuthorizationChecker (AuthorizationConfig config, AuthorizationPolicy policy)
AuthorizationConfig getConfig ()
Set< String > getUserGroups (User user)
void checkAccess (User user, PrivilegeRequest privilegeRequest) throws AuthorizationException
boolean hasAccess (User user, PrivilegeRequest request)
Static Private Member Functions
static
ResourceAuthorizationProvider createProvider (AuthorizationConfig config, AuthorizationPolicy policy)
Private Attributes
final ResourceAuthorizationProvider provider_
final AuthorizationConfig config_
final AuthorizeableServer server_
Detailed Description
Definition at line 41 of file AuthorizationChecker.java.
Constructor & Destructor Documentation
com.cloudera.impala.authorization.AuthorizationChecker.AuthorizationChecker (AuthorizationConfig config, AuthorizationPolicy policy) inline
Definition at line 49 of file AuthorizationChecker.java.
References com.cloudera.impala.authorization.AuthorizationChecker.config_, com.cloudera.impala.authorization.AuthorizationChecker.createProvider(), com.cloudera.impala.authorization.AuthorizationConfig.getServerName(), com.cloudera.impala.authorization.AuthorizationConfig.isEnabled(), com.cloudera.impala.authorization.AuthorizationChecker.provider_, and com.cloudera.impala.authorization.AuthorizationChecker.server_.
Member Function Documentation
void com.cloudera.impala.authorization.AuthorizationChecker.checkAccess (User user, PrivilegeRequest privilegeRequest) throws AuthorizationException inline
Authorizes the PrivilegeRequest, throwing an Authorization exception if the user does not have sufficient privileges.
Definition at line 119 of file AuthorizationChecker.java.
References com.cloudera.impala.authorization.Privilege.ALL, com.cloudera.impala.authorization.Privilege.ANY, com.cloudera.impala.authorization.AuthorizationChecker.hasAccess(), and com.cloudera.impala.authorization.Privilege.VIEW_METADATA.
static ResourceAuthorizationProvider com.cloudera.impala.authorization.AuthorizationChecker.createProvider (AuthorizationConfig config, AuthorizationPolicy policy) inline static private
Definition at line 65 of file AuthorizationChecker.java.
References com.cloudera.impala.authorization.AuthorizationConfig.getPolicyFile(), com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig(), com.cloudera.impala.authorization.AuthorizationConfig.getServerName(), and com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.AuthorizationChecker().
AuthorizationConfig com.cloudera.impala.authorization.AuthorizationChecker.getConfig () inline
Definition at line 104 of file AuthorizationChecker.java.
References com.cloudera.impala.authorization.AuthorizationChecker.config_.
Set<String> com.cloudera.impala.authorization.AuthorizationChecker.getUserGroups (User user) inline
Returns the set of groups this user belongs to. Uses the GroupMappingService that is in the AuthorizationProvider to properly resolve Hadoop groups or local group mappings.
Definition at line 111 of file AuthorizationChecker.java.
References com.cloudera.impala.authorization.User.getShortName().
boolean com.cloudera.impala.authorization.AuthorizationChecker.hasAccess (User user, PrivilegeRequest request) inline
Definition at line 148 of file AuthorizationChecker.java.
References impala_udf.ALL, com.cloudera.impala.authorization.AuthorizationChecker.config_, com.cloudera.impala.authorization.PrivilegeRequest.getAuthorizeable(), com.cloudera.impala.authorization.PrivilegeRequest.getPrivilege(), com.cloudera.impala.authorization.User.getShortName(), com.cloudera.impala.authorization.AuthorizationConfig.isEnabled(), and com.cloudera.impala.authorization.AuthorizationChecker.provider_.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.checkAccess().
Member Data Documentation
final AuthorizationConfig com.cloudera.impala.authorization.AuthorizationChecker.config_ private
Definition at line 43 of file AuthorizationChecker.java.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.AuthorizationChecker(), com.cloudera.impala.authorization.AuthorizationChecker.getConfig(), and com.cloudera.impala.authorization.AuthorizationChecker.hasAccess().
final ResourceAuthorizationProvider com.cloudera.impala.authorization.AuthorizationChecker.provider_ private
Definition at line 42 of file AuthorizationChecker.java.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.AuthorizationChecker(), and com.cloudera.impala.authorization.AuthorizationChecker.hasAccess().
final AuthorizeableServer com.cloudera.impala.authorization.AuthorizationChecker.server_ private
Definition at line 44 of file AuthorizationChecker.java.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.AuthorizationChecker().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/authorization/AuthorizationChecker.java