Impala: impala::StringFunctions Class Reference
impala::StringFunctions Class Reference
#include <string-functions.h>
Static Public Member Functions
static StringVal Substring (FunctionContext *, const StringVal &str, const BigIntVal &pos, const BigIntVal &len)
static StringVal Substring (FunctionContext *, const StringVal &str, const BigIntVal &pos)
static StringVal Left (FunctionContext *, const StringVal &str, const BigIntVal &len)
static StringVal Right (FunctionContext *, const StringVal &str, const BigIntVal &len)
static StringVal Space (FunctionContext *, const BigIntVal &len)
static StringVal Repeat (FunctionContext *, const StringVal &str, const BigIntVal &n)
static StringVal Lpad (FunctionContext *, const StringVal &str, const BigIntVal &len, const StringVal &pad)
static StringVal Rpad (FunctionContext *, const StringVal &str, const BigIntVal &, const StringVal &pad)
static IntVal Length (FunctionContext *, const StringVal &str)
static IntVal CharLength (FunctionContext *, const StringVal &str)
static StringVal Lower (FunctionContext *, const StringVal &str)
static StringVal Upper (FunctionContext *, const StringVal &str)
static StringVal InitCap (FunctionContext *, const StringVal &str)
static StringVal Reverse (FunctionContext *, const StringVal &str)
static StringVal Translate (FunctionContext *, const StringVal &str, const StringVal &src, const StringVal &dst)
static StringVal Trim (FunctionContext *, const StringVal &str)
static StringVal Ltrim (FunctionContext *, const StringVal &str)
static StringVal Rtrim (FunctionContext *, const StringVal &str)
static IntVal Ascii (FunctionContext *, const StringVal &str)
static IntVal Instr (FunctionContext *, const StringVal &str, const StringVal &substr)
static IntVal Locate (FunctionContext *, const StringVal &substr, const StringVal &str)
static IntVal LocatePos (FunctionContext *, const StringVal &substr, const StringVal &str, const BigIntVal &start_pos)
static void RegexpPrepare (FunctionContext *, FunctionContext::FunctionStateScope)
static void RegexpClose (FunctionContext *, FunctionContext::FunctionStateScope)
static StringVal RegexpExtract (FunctionContext *, const StringVal &str, const StringVal &pattern, const BigIntVal &index)
static StringVal RegexpReplace (FunctionContext *, const StringVal &str, const StringVal &pattern, const StringVal &replace)
static StringVal Concat (FunctionContext *, int num_children, const StringVal *strs)
static StringVal ConcatWs (FunctionContext *, const StringVal &sep, int num_children, const StringVal *strs)
static IntVal FindInSet (FunctionContext *, const StringVal &str, const StringVal &str_set)
static void ParseUrlPrepare (FunctionContext *, FunctionContext::FunctionStateScope)
static StringVal ParseUrl (FunctionContext *, const StringVal &url, const StringVal &part)
static StringVal ParseUrlKey (FunctionContext *, const StringVal &url, const StringVal &key, const StringVal &part)
static void ParseUrlClose (FunctionContext *, FunctionContext::FunctionStateScope)
Detailed Description
Definition at line 30 of file string-functions.h.
Member Function Documentation
IntVal impala::StringFunctions::Ascii (FunctionContext * context, const StringVal & str) static
Definition at line 265 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::IntVal::null(), and impala_udf::StringVal::ptr.
IntVal impala::StringFunctions::CharLength (FunctionContext * context, const StringVal & str) static
Definition at line 148 of file string-functions.cc.
References impala_udf::FunctionContext::GetArgType(), impala_udf::AnyVal::is_null, impala_udf::FunctionContext::TypeDesc::len, impala_udf::IntVal::null(), impala_udf::StringVal::ptr, impala_udf::FunctionContext::TypeDesc::type, and impala_udf::FunctionContext::TYPE_FIXED_BUFFER.
StringVal impala::StringFunctions::Concat (FunctionContext * context, int num_children, const StringVal * strs) static
Definition at line 409 of file string-functions.cc.
StringVal impala::StringFunctions::ConcatWs (FunctionContext * context, const StringVal & sep, int num_children, const StringVal * strs) static
Definition at line 414 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
IntVal impala::StringFunctions::FindInSet (FunctionContext * context, const StringVal & str, const StringVal & str_set) static
Definition at line 445 of file string-functions.cc.
References impala::StringValue::Eq(), impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::IntVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::InitCap (FunctionContext * context, const StringVal & str) static
Definition at line 177 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
IntVal impala::StringFunctions::Instr (FunctionContext * context, const StringVal & str, const StringVal & substr) static
Definition at line 271 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::IntVal::null(), and impala::StringSearch::Search().
StringVal impala::StringFunctions::Left (FunctionContext * context, const StringVal & str, const BigIntVal & len) static
Definition at line 60 of file string-functions.cc.
IntVal impala::StringFunctions::Length (FunctionContext * context, const StringVal & str) static
Definition at line 143 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, and impala_udf::IntVal::null().
Referenced by impala::Expr::InitBuiltinsDummy().
IntVal impala::StringFunctions::Locate (FunctionContext * context, const StringVal & substr, const StringVal & str) static
Definition at line 281 of file string-functions.cc.
IntVal impala::StringFunctions::LocatePos (FunctionContext * context, const StringVal & substr, const StringVal & str, const BigIntVal & start_pos) static
Definition at line 286 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::IntVal::null(), impala_udf::StringVal::ptr, impala::StringSearch::Search(), and impala_udf::BigIntVal::val.
StringVal impala::StringFunctions::Lower (FunctionContext * context, const StringVal & str) static
Definition at line 155 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::Lpad (FunctionContext * context, const StringVal & str, const BigIntVal & len, const StringVal & pad) static
Definition at line 94 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), impala_udf::StringVal::ptr, and impala_udf::BigIntVal::val.
StringVal impala::StringFunctions::Ltrim (FunctionContext * context, const StringVal & str) static
Definition at line 243 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::ParseUrl (FunctionContext * ctx, const StringVal & url, const StringVal & part) static
Definition at line 491 of file string-functions.cc.
References impala_udf::FunctionContext::AddWarning(), impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetFunctionState(), impala_udf::AnyVal::is_null, impala_udf::FunctionContext::IsArgConstant(), impala_udf::StringVal::null(), and impala::StringValue::ToStringVal().
void impala::StringFunctions::ParseUrlClose (FunctionContext * ctx, FunctionContext::FunctionStateScope scope) static
Definition at line 522 of file string-functions.cc.
References impala_udf::FunctionContext::FRAGMENT_LOCAL, and impala_udf::FunctionContext::GetFunctionState().
StringVal impala::StringFunctions::ParseUrlKey (FunctionContext * ctx, const StringVal & url, const StringVal & key, const StringVal & part) static
Definition at line 531 of file string-functions.cc.
References impala_udf::FunctionContext::AddWarning(), impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetFunctionState(), impala_udf::AnyVal::is_null, impala_udf::FunctionContext::IsArgConstant(), impala_udf::StringVal::null(), and impala::StringValue::ToStringVal().
void impala::StringFunctions::ParseUrlPrepare (FunctionContext * ctx, FunctionContext::FunctionStateScope scope) static
Definition at line 471 of file string-functions.cc.
References impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetArgType(), impala_udf::FunctionContext::GetConstantArg(), impala_udf::FunctionContext::IsArgConstant(), impala_udf::FunctionContext::SetError(), impala_udf::FunctionContext::SetFunctionState(), impala_udf::FunctionContext::TypeDesc::type, and impala_udf::FunctionContext::TYPE_STRING.
void impala::StringFunctions::RegexpClose (FunctionContext * context, FunctionContext::FunctionStateScope scope) static
Definition at line 344 of file string-functions.cc.
References impala_udf::FunctionContext::FRAGMENT_LOCAL, and impala_udf::FunctionContext::GetFunctionState().
StringVal impala::StringFunctions::RegexpExtract (FunctionContext * context, const StringVal & str, const StringVal & pattern, const BigIntVal & index) static
Definition at line 351 of file string-functions.cc.
References impala_udf::FunctionContext::AddWarning(), impala::CompileRegex(), impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetFunctionState(), impala_udf::AnyVal::is_null, impala_udf::FunctionContext::IsArgConstant(), impala_udf::StringVal::len, impala_udf::StringVal::null(), impala_udf::StringVal::ptr, and impala_udf::BigIntVal::val.
void impala::StringFunctions::RegexpPrepare (FunctionContext * context, FunctionContext::FunctionStateScope scope) static
Definition at line 327 of file string-functions.cc.
References impala::CompileRegex(), impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetArgType(), impala_udf::FunctionContext::GetConstantArg(), impala_udf::FunctionContext::IsArgConstant(), impala_udf::FunctionContext::SetError(), impala_udf::FunctionContext::SetFunctionState(), impala_udf::FunctionContext::TypeDesc::type, and impala_udf::FunctionContext::TYPE_STRING.
StringVal impala::StringFunctions::RegexpReplace (FunctionContext * context, const StringVal & str, const StringVal & pattern, const StringVal & replace) static
Definition at line 384 of file string-functions.cc.
References impala_udf::FunctionContext::AddWarning(), impala::CompileRegex(), impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetFunctionState(), impala_udf::AnyVal::is_null, impala_udf::FunctionContext::IsArgConstant(), impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::Repeat (FunctionContext * context, const StringVal & str, const BigIntVal & n) static
Definition at line 81 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), impala_udf::StringVal::ptr, and impala_udf::BigIntVal::val.
StringVal impala::StringFunctions::Reverse (FunctionContext * context, const StringVal & str) static
Definition at line 194 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::Right (FunctionContext * context, const StringVal & str, const BigIntVal & len) static
Definition at line 66 of file string-functions.cc.
References impala_udf::StringVal::len, and impala_udf::BigIntVal::val.
StringVal impala::StringFunctions::Rpad (FunctionContext * context, const StringVal & str, const BigIntVal & len, const StringVal & pad) static
Definition at line 119 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), impala_udf::StringVal::ptr, and impala_udf::BigIntVal::val.
StringVal impala::StringFunctions::Rtrim (FunctionContext * context, const StringVal & str) static
Definition at line 253 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::Space (FunctionContext * context, const BigIntVal & len) static
Definition at line 73 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::null(), impala_udf::StringVal::ptr, and impala_udf::BigIntVal::val.
StringVal impala::StringFunctions::Substring (FunctionContext * context, const StringVal & str, const BigIntVal & pos, const BigIntVal & len) static
Definition at line 39 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), impala_udf::StringVal::ptr, and impala_udf::BigIntVal::val.
StringVal impala::StringFunctions::Substring (FunctionContext * context, const StringVal & str, const BigIntVal & pos) static
Definition at line 53 of file string-functions.cc.
StringVal impala::StringFunctions::Translate (FunctionContext * context, const StringVal & str, const StringVal & src, const StringVal & dst) static
Definition at line 201 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::Trim (FunctionContext * context, const StringVal & str) static
Definition at line 228 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
StringVal impala::StringFunctions::Upper (FunctionContext * context, const StringVal & str) static
Definition at line 164 of file string-functions.cc.
References impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::null(), and impala_udf::StringVal::ptr.
The documentation for this class was generated from the following files:
be/src/exprs/string-functions.h
be/src/exprs/string-functions.cc