Impala: impala::DescriptorTbl Class Reference
impala::DescriptorTbl Class Reference
#include <descriptors.h>
Public Member Functions
TableDescriptor * GetTableDescriptor (TableId id) const
TupleDescriptor * GetTupleDescriptor (TupleId id) const
SlotDescriptor * GetSlotDescriptor (SlotId id) const
void GetTupleDescs (std::vector< TupleDescriptor * > *descs) const
return all registered tuple descriptors
std::string DebugString () const
Static Public Member Functions
static Status Create (ObjectPool *pool, const TDescriptorTable &thrift_tbl, DescriptorTbl **tbl)
Private Types
typedef
std::tr1::unordered_map
< TableId, TableDescriptor * > TableDescriptorMap
typedef
std::tr1::unordered_map
< TupleId, TupleDescriptor * > TupleDescriptorMap
typedef
std::tr1::unordered_map
< SlotId, SlotDescriptor * > SlotDescriptorMap
Private Member Functions
DescriptorTbl ()
Private Attributes
TableDescriptorMap tbl_desc_map_
TupleDescriptorMap tuple_desc_map_
SlotDescriptorMap slot_desc_map_
Detailed Description
Definition at line 338 of file descriptors.h.
Member Typedef Documentation
typedef std::tr1::unordered_map<SlotId, SlotDescriptor*> impala::DescriptorTbl::SlotDescriptorMap private
Definition at line 357 of file descriptors.h.
typedef std::tr1::unordered_map<TableId, TableDescriptor*> impala::DescriptorTbl::TableDescriptorMap private
Definition at line 355 of file descriptors.h.
typedef std::tr1::unordered_map<TupleId, TupleDescriptor*> impala::DescriptorTbl::TupleDescriptorMap private
Definition at line 356 of file descriptors.h.
Constructor & Destructor Documentation
impala::DescriptorTbl::DescriptorTbl () inline private
Definition at line 363 of file descriptors.h.
Referenced by Create().
Member Function Documentation
Status impala::DescriptorTbl::Create (ObjectPool * pool, const TDescriptorTable & thrift_tbl, DescriptorTbl ** tbl) static
Creates a descriptor tbl within 'pool' from thrift_tbl and returns it via 'tbl'. Returns OK on success, otherwise error (in which case 'tbl' will be unset).
Definition at line 378 of file descriptors.cc.
References impala::ObjectPool::Add(), DescriptorTbl(), impala::Status::OK, and impala::TupleDescriptor::table_desc_.
Referenced by impala::DescriptorTblBuilder::Build(), impala::DataStreamTest::CreateRowDesc(), and impala::PlanFragmentExecutor::Prepare().
string impala::DescriptorTbl::DebugString () const
Definition at line 608 of file descriptors.cc.
References tuple_desc_map_.
Referenced by impala::PlanFragmentExecutor::Prepare().
SlotDescriptor * impala::DescriptorTbl::GetSlotDescriptor (SlotId id) const
Definition at line 447 of file descriptors.cc.
References slot_desc_map_.
Referenced by impala::HdfsScanNode::ComputeSlotMaterializationOrder(), and impala::SlotRef::Prepare().
TableDescriptor * impala::DescriptorTbl::GetTableDescriptor (TableId id) const
Definition at line 427 of file descriptors.cc.
References tbl_desc_map_.
Referenced by impala::HBaseTableSink::Prepare(), and impala::HdfsTableSink::Prepare().
TupleDescriptor * impala::DescriptorTbl::GetTupleDescriptor (TupleId id) const
Definition at line 437 of file descriptors.cc.
References tuple_desc_map_.
Referenced by impala::AnalyticEvalNode::AnalyticEvalNode(), impala::SlotRef::Prepare(), impala::HBaseScanNode::Prepare(), impala::UnionNode::Prepare(), impala::DataSourceScanNode::Prepare(), impala::AggregationNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), and impala::HdfsScanNode::Prepare().
void impala::DescriptorTbl::GetTupleDescs (std::vector< TupleDescriptor * > * descs) const
return all registered tuple descriptors
Definition at line 458 of file descriptors.cc.
References tuple_desc_map_.
Member Data Documentation
SlotDescriptorMap impala::DescriptorTbl::slot_desc_map_ private
Definition at line 361 of file descriptors.h.
Referenced by GetSlotDescriptor().
TableDescriptorMap impala::DescriptorTbl::tbl_desc_map_ private
Definition at line 359 of file descriptors.h.
Referenced by GetTableDescriptor().
TupleDescriptorMap impala::DescriptorTbl::tuple_desc_map_ private
Definition at line 360 of file descriptors.h.
Referenced by DebugString(), GetTupleDescriptor(), and GetTupleDescs().
The documentation for this class was generated from the following files:
be/src/runtime/descriptors.h
be/src/runtime/descriptors.cc