Impala: impala::ThreadMgr Class Reference
impala::ThreadMgr Class Reference
Classes
class ThreadDescriptor
Public Member Functions
ThreadMgr ()
Status StartInstrumentation (MetricGroup *metrics, Webserver *webserver)
void AddThread (const thread::id &thread, const string &name, const string &category, int64_t tid)
void RemoveThread (const thread::id &boost_id, const string &category)
Private Types
typedef map< const thread::id,
ThreadDescriptor > ThreadCategory
typedef map< string,
ThreadCategory > ThreadCategoryMap
Private Member Functions
void ThreadGroupUrlCallback (const Webserver::ArgumentMap &args, Document *output)
void ThreadOverviewUrlCallback (const Webserver::ArgumentMap &args, Document *document)
Private Attributes
mutex lock_
ThreadCategoryMap thread_categories_
bool metrics_enabled_
IntGauge * total_threads_metric_
IntGauge * current_num_threads_metric_
Detailed Description
Definition at line 54 of file thread.cc.
Member Typedef Documentation
typedef map<const thread::id, ThreadDescriptor> impala::ThreadMgr::ThreadCategory private
Definition at line 94 of file thread.cc.
typedef map<string, ThreadCategory> impala::ThreadMgr::ThreadCategoryMap private
Definition at line 97 of file thread.cc.
Constructor & Destructor Documentation
impala::ThreadMgr::ThreadMgr () inline
Definition at line 56 of file thread.cc.
Member Function Documentation
void impala::ThreadMgr::AddThread (const thread::id & thread, const string & name, const string & category, int64_t tid)
Definition at line 178 of file thread.cc.
References lock_.
void impala::ThreadMgr::RemoveThread (const thread::id & boost_id, const string & category)
Definition at line 188 of file thread.cc.
References lock_.
Status impala::ThreadMgr::StartInstrumentation (MetricGroup * metrics, Webserver * webserver)
Definition at line 155 of file thread.cc.
References impala::MetricGroup::AddGauge(), lock_, impala::OK, impala::Webserver::RegisterUrlCallback(), impala::THREADS_TEMPLATE, and impala::THREADS_WEB_PAGE.
void impala::ThreadMgr::ThreadGroupUrlCallback (const Webserver::ArgumentMap & args, Document * output) private
Definition at line 214 of file thread.cc.
References impala::Status::GetDetail(), impala::GetThreadStats(), impala::ThreadStats::iowait_ns, impala::ThreadStats::kernel_ns, lock_, impala::Status::ok(), and impala::ThreadStats::user_ns.
void impala::ThreadMgr::ThreadOverviewUrlCallback (const Webserver::ArgumentMap & args, Document * document) private
Definition at line 196 of file thread.cc.
References lock_.
Member Data Documentation
IntGauge* impala::ThreadMgr::current_num_threads_metric_ private
Definition at line 111 of file thread.cc.
mutex impala::ThreadMgr::lock_ private
Definition at line 100 of file thread.cc.
bool impala::ThreadMgr::metrics_enabled_ private
Definition at line 106 of file thread.cc.
ThreadCategoryMap impala::ThreadMgr::thread_categories_ private
Definition at line 103 of file thread.cc.
IntGauge* impala::ThreadMgr::total_threads_metric_ private
Definition at line 110 of file thread.cc.
The documentation for this class was generated from the following file:
be/src/util/thread.cc