Impala: com.cloudera.impala.catalog.PartitionStatsUtil Class Reference
com.cloudera.impala.catalog.PartitionStatsUtil Class Reference
Static Public Member Functions
static TPartitionStats partStatsFromParameters (Map< String, String > hmsParameters) throws ImpalaException
static void partStatsToParameters (TPartitionStats partStats, HdfsPartition partition)
static void deletePartStats (HdfsPartition partition)
Static Public Attributes
static final String INTERMEDIATE_STATS_NUM_CHUNKS
static final String INTERMEDIATE_STATS_CHUNK_PREFIX
Static Private Member Functions
static List< String > chunkStringForHms (String data, int chunkLen)
Static Private Attributes
static final int HMS_MAX_CHUNKLEN = 4000
static final Logger LOG = LoggerFactory.getLogger(PartitionStatsUtil.class)
Detailed Description
Handles serialising and deserialising intermediate statistics from the Hive MetaStore via the parameters map attached to every Hive partition object.
Definition at line 39 of file PartitionStatsUtil.java.
Member Function Documentation
static List<String> com.cloudera.impala.catalog.PartitionStatsUtil.chunkStringForHms (String data, int chunkLen) inline static private
Definition at line 128 of file PartitionStatsUtil.java.
References gen_ir_descriptions.idx.
Referenced by com.cloudera.impala.catalog.PartitionStatsUtil.partStatsToParameters().
static void com.cloudera.impala.catalog.PartitionStatsUtil.deletePartStats (HdfsPartition partition) inline static
Definition at line 118 of file PartitionStatsUtil.java.
References com.cloudera.impala.catalog.HdfsPartition.getParameters(), com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_CHUNK_PREFIX, and com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_NUM_CHUNKS.
Referenced by com.cloudera.impala.catalog.PartitionStatsUtil.partStatsToParameters().
static TPartitionStats com.cloudera.impala.catalog.PartitionStatsUtil.partStatsFromParameters (Map< String, String > hmsParameters) throws ImpalaException inline static
Reconstructs a TPartitionStats object from its serialised form in the given parameter map. Returns null if no stats are serialised, and throws an exception if there was an error during deserialisation.
Definition at line 56 of file PartitionStatsUtil.java.
References com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_CHUNK_PREFIX, and com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_NUM_CHUNKS.
static void com.cloudera.impala.catalog.PartitionStatsUtil.partStatsToParameters (TPartitionStats partStats, HdfsPartition partition) inline static
Serialises a TPartitionStats object to a partition.
Definition at line 84 of file PartitionStatsUtil.java.
References com.cloudera.impala.catalog.PartitionStatsUtil.chunkStringForHms(), com.cloudera.impala.catalog.PartitionStatsUtil.deletePartStats(), com.cloudera.impala.catalog.PartitionStatsUtil.HMS_MAX_CHUNKLEN, com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_CHUNK_PREFIX, and com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_NUM_CHUNKS.
Member Data Documentation
final int com.cloudera.impala.catalog.PartitionStatsUtil.HMS_MAX_CHUNKLEN = 4000 static private
Definition at line 47 of file PartitionStatsUtil.java.
Referenced by com.cloudera.impala.catalog.PartitionStatsUtil.partStatsToParameters().
final String com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_CHUNK_PREFIX static
Initial value:
=
      "impala_intermediate_stats_chunk"
Definition at line 43 of file PartitionStatsUtil.java.
Referenced by com.cloudera.impala.catalog.PartitionStatsUtil.deletePartStats(), com.cloudera.impala.catalog.PartitionStatsUtil.partStatsFromParameters(), and com.cloudera.impala.catalog.PartitionStatsUtil.partStatsToParameters().
final String com.cloudera.impala.catalog.PartitionStatsUtil.INTERMEDIATE_STATS_NUM_CHUNKS static
Initial value:
=
      "impala_intermediate_stats_num_chunks"
Definition at line 40 of file PartitionStatsUtil.java.
Referenced by com.cloudera.impala.catalog.PartitionStatsUtil.deletePartStats(), com.cloudera.impala.catalog.PartitionStatsUtil.partStatsFromParameters(), and com.cloudera.impala.catalog.PartitionStatsUtil.partStatsToParameters().
final Logger com.cloudera.impala.catalog.PartitionStatsUtil.LOG = LoggerFactory.getLogger(PartitionStatsUtil.class) static private
Definition at line 49 of file PartitionStatsUtil.java.
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/PartitionStatsUtil.java