Impala: com.cloudera.impala.hive.executor.UdfExecutorTest Class Reference
com.cloudera.impala.hive.executor.UdfExecutorTest Class Reference
Public Member Functions
void HiveMathTest () throws ImpalaRuntimeException, MalformedURLException
void HiveStringsTest () throws ImpalaRuntimeException, MalformedURLException
void BasicTest () throws ImpalaRuntimeException, MalformedURLException
Package Functions
long allocate (int byteSize)
long createStringValue (String v)
void freeAllocations ()
Writable createObject (PrimitiveType t, Object o)
Writable createBoolean (boolean v)
Writable createTinyInt (int v)
Writable createSmallInt (int v)
Writable createInt (int v)
Writable createBigInt (long v)
Writable createFloat (float v)
Writable createDouble (double v)
Writable createBytes (String v)
Writable createText (String v)
Type getType (Object w)
void TestUdfImpl (String jar, Class<?> c, Object expectedValue, Type expectedType, boolean validate, Object...args) throws MalformedURLException, ImpalaRuntimeException
void TestUdf (String jar, Class<?> c, Writable expectedValue, Object...args) throws MalformedURLException, ImpalaRuntimeException
void TestUdf (String jar, Class<?> c, String expectedValue, Object...args) throws MalformedURLException, ImpalaRuntimeException
void TestHiveUdf (Class<?> c, Writable expectedValue, Object...args) throws MalformedURLException, ImpalaRuntimeException
void TestHiveUdfNoValidate (Class<?> c, Writable expectedValue, Object...args) throws MalformedURLException, ImpalaRuntimeException
Package Attributes
ArrayList< Long > allocations_ = Lists.newArrayList()
Private Attributes
final String HIVE_BUILTIN_JAR
Detailed Description
Definition at line 67 of file UdfExecutorTest.java.
Member Function Documentation
long com.cloudera.impala.hive.executor.UdfExecutorTest.allocate (int byteSize) inline package
Definition at line 76 of file UdfExecutorTest.java.
void com.cloudera.impala.hive.executor.UdfExecutorTest.BasicTest () throws ImpalaRuntimeException, MalformedURLException inline
Definition at line 350 of file UdfExecutorTest.java.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createBigInt (long v) inline package
Definition at line 147 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.BIGINT.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createBoolean (boolean v) inline package
Definition at line 143 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.BOOLEAN.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createBytes (String v) inline package
Definition at line 150 of file UdfExecutorTest.java.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createDouble (double v) inline package
Definition at line 149 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.DOUBLE.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createFloat (float v) inline package
Definition at line 148 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.FLOAT.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createInt (int v) inline package
Definition at line 146 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.INT.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createObject (PrimitiveType t, Object o) inline package
Definition at line 101 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.getSlotSize().
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createSmallInt (int v) inline package
Definition at line 145 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.SMALLINT.
long com.cloudera.impala.hive.executor.UdfExecutorTest.createStringValue (String v) inline package
Definition at line 83 of file UdfExecutorTest.java.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createText (String v) inline package
Definition at line 155 of file UdfExecutorTest.java.
Writable com.cloudera.impala.hive.executor.UdfExecutorTest.createTinyInt (int v) inline package
Definition at line 144 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.PrimitiveType.TINYINT.
void com.cloudera.impala.hive.executor.UdfExecutorTest.freeAllocations () inline package
Definition at line 93 of file UdfExecutorTest.java.
Type com.cloudera.impala.hive.executor.UdfExecutorTest.getType (Object w) inline package
Definition at line 161 of file UdfExecutorTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.INVALID, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.STRING, and com.cloudera.impala.catalog.Type.TINYINT.
void com.cloudera.impala.hive.executor.UdfExecutorTest.HiveMathTest () throws ImpalaRuntimeException, MalformedURLException inline
Definition at line 296 of file UdfExecutorTest.java.
void com.cloudera.impala.hive.executor.UdfExecutorTest.HiveStringsTest () throws ImpalaRuntimeException, MalformedURLException inline
Definition at line 336 of file UdfExecutorTest.java.
void com.cloudera.impala.hive.executor.UdfExecutorTest.TestHiveUdf (Class<?> c, Writable expectedValue, Object... args) throws MalformedURLException, ImpalaRuntimeException inline package
Definition at line 282 of file UdfExecutorTest.java.
void com.cloudera.impala.hive.executor.UdfExecutorTest.TestHiveUdfNoValidate (Class<?> c, Writable expectedValue, Object... args) throws MalformedURLException, ImpalaRuntimeException inline package
Definition at line 287 of file UdfExecutorTest.java.
void com.cloudera.impala.hive.executor.UdfExecutorTest.TestUdf (String jar, Class<?> c, Writable expectedValue, Object... args) throws MalformedURLException, ImpalaRuntimeException inline package
Definition at line 272 of file UdfExecutorTest.java.
void com.cloudera.impala.hive.executor.UdfExecutorTest.TestUdf (String jar, Class<?> c, String expectedValue, Object... args) throws MalformedURLException, ImpalaRuntimeException inline package
Definition at line 277 of file UdfExecutorTest.java.
void com.cloudera.impala.hive.executor.UdfExecutorTest.TestUdfImpl (String jar, Class<?> c, Object expectedValue, Type expectedType, boolean validate, Object... args) throws MalformedURLException, ImpalaRuntimeException inline package
Definition at line 186 of file UdfExecutorTest.java.
References com.cloudera.impala.hive.executor.ImpalaStringWritable.getBytes(), com.cloudera.impala.catalog.Type.getPrimitiveType(), and com.cloudera.impala.util.UnsafeUtil.UNSAFE.
Member Data Documentation
ArrayList<Long> com.cloudera.impala.hive.executor.UdfExecutorTest.allocations_ = Lists.newArrayList() package
Definition at line 72 of file UdfExecutorTest.java.
final String com.cloudera.impala.hive.executor.UdfExecutorTest.HIVE_BUILTIN_JAR private
Initial value:
= System.getenv("HIVE_HOME") + "/" +
      "lib/hive-exec-" + System.getenv("IMPALA_HIVE_VERSION") + ".jar"
Definition at line 68 of file UdfExecutorTest.java.
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/hive/executor/UdfExecutorTest.java