Impala: com.cloudera.impala.analysis.ExprTest Class Reference
com.cloudera.impala.analysis.ExprTest Class Reference
Public Member Functions
void TestLiteralExpr ()
Private Member Functions
void testLiteralExprPositive (String value, Type type)
void testLiteralExprNegative (String value, Type type)
Detailed Description
Definition at line 25 of file ExprTest.java.
Member Function Documentation
void com.cloudera.impala.analysis.ExprTest.TestLiteralExpr () inline
Definition at line 28 of file ExprTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.Type.DATE, com.cloudera.impala.catalog.Type.DATETIME, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.INVALID, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.analysis.ExprTest.testLiteralExprNegative(), com.cloudera.impala.analysis.ExprTest.testLiteralExprPositive(), com.cloudera.impala.catalog.Type.TIMESTAMP, and com.cloudera.impala.catalog.Type.TINYINT.
void com.cloudera.impala.analysis.ExprTest.testLiteralExprNegative (String value, Type type) inline private
Definition at line 72 of file ExprTest.java.
Referenced by com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
void com.cloudera.impala.analysis.ExprTest.testLiteralExprPositive (String value, Type type) inline private
Definition at line 59 of file ExprTest.java.
Referenced by com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/analysis/ExprTest.java