Impala: com.cloudera.impala.catalog.HdfsPartition.FileBlock Class Reference
com.cloudera.impala.catalog.HdfsPartition.FileBlock Class Reference
Public Member Functions
FileBlock (long offset, long blockLength, List< BlockReplica > replicaHostIdxs)
long getOffset ()
long getLength ()
boolean isCached ()
List< Integer > getReplicaHostIdxs ()
int getDiskId (int hostIndex)
boolean isCached (int hostIndex)
THdfsFileBlock toThrift ()
String toString ()
Static Public Member Functions
static void setDiskIds (int[] diskIds, THdfsFileBlock fileBlock)
static FileBlock fromThrift (THdfsFileBlock thriftFileBlock)
Private Member Functions
FileBlock (THdfsFileBlock fileBlock)
Private Attributes
final THdfsFileBlock fileBlock_
boolean isCached_
Detailed Description
File Block metadata
Definition at line 157 of file HdfsPartition.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.HdfsPartition.FileBlock.FileBlock (THdfsFileBlock fileBlock) inline private
Definition at line 161 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileBlock.fileBlock_, com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached(), and com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached_.
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileBlock.fromThrift().
com.cloudera.impala.catalog.HdfsPartition.FileBlock.FileBlock (long offset, long blockLength, List< BlockReplica > replicaHostIdxs) inline
Construct a FileBlock given the start offset (in bytes) of the file associated with this block, the length of the block (in bytes), and a list of BlockReplicas. Does not fill diskIds.
Definition at line 174 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileBlock.fileBlock_, com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached_, and offset.
Member Function Documentation
static FileBlock com.cloudera.impala.catalog.HdfsPartition.FileBlock.fromThrift (THdfsFileBlock thriftFileBlock) inline static
Definition at line 225 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileBlock.FileBlock().
int com.cloudera.impala.catalog.HdfsPartition.FileBlock.getDiskId (int hostIndex) inline
Return the disk id of the block in BlockLocation.getNames()[hostIndex]; -1 if disk id is not supported.
Definition at line 214 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileBlock.fileBlock_.
long com.cloudera.impala.catalog.HdfsPartition.FileBlock.getLength () inline
Definition at line 192 of file HdfsPartition.java.
long com.cloudera.impala.catalog.HdfsPartition.FileBlock.getOffset () inline
Definition at line 191 of file HdfsPartition.java.
List<Integer> com.cloudera.impala.catalog.HdfsPartition.FileBlock.getReplicaHostIdxs () inline
Definition at line 195 of file HdfsPartition.java.
boolean com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached () inline
Definition at line 194 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached_.
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileBlock.FileBlock().
boolean com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached (int hostIndex) inline
Definition at line 219 of file HdfsPartition.java.
static void com.cloudera.impala.catalog.HdfsPartition.FileBlock.setDiskIds (int[] diskIds, THdfsFileBlock fileBlock) inline static
Populates the given THdfsFileBlock's list of disk ids with the given disk id values. The number of disk ids must match the number of network addresses set in the file block.
Definition at line 204 of file HdfsPartition.java.
String com.cloudera.impala.catalog.HdfsPartition.FileBlock.toString () inline
Definition at line 230 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileBlock.fileBlock_.
THdfsFileBlock com.cloudera.impala.catalog.HdfsPartition.FileBlock.toThrift () inline
Definition at line 223 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileBlock.fileBlock_.
Member Data Documentation
final THdfsFileBlock com.cloudera.impala.catalog.HdfsPartition.FileBlock.fileBlock_ private
Definition at line 158 of file HdfsPartition.java.
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileBlock.FileBlock(), com.cloudera.impala.catalog.HdfsPartition.FileBlock.getDiskId(), com.cloudera.impala.catalog.HdfsPartition.FileBlock.toString(), and com.cloudera.impala.catalog.HdfsPartition.FileBlock.toThrift().
boolean com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached_ private
Definition at line 159 of file HdfsPartition.java.
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileBlock.FileBlock(), and com.cloudera.impala.catalog.HdfsPartition.FileBlock.isCached().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HdfsPartition.java