Impala: com.cloudera.impala.analysis.AnalyticExpr Class Reference
com.cloudera.impala.analysis.AnalyticExpr Class Reference
Public Member Functions
AnalyticExpr (FunctionCallExpr fnCall, List< Expr > partitionExprs, List< OrderByElement > orderByElements, AnalyticWindow window)
FunctionCallExpr getFnCall ()
List< Expr > getPartitionExprs ()
List< OrderByElement > getOrderByElements ()
AnalyticWindow getWindow ()
boolean equals (Object obj)
boolean isConstant ()
Expr clone ()
String toSqlImpl ()
String debugString ()
void analyze (Analyzer analyzer) throws AnalysisException
ExprId getId ()
Type getType ()
double getSelectivity ()
long getNumDistinctValues ()
void setPrintSqlInParens (boolean b)
boolean isWhereClauseConjunct ()
void setIsWhereClauseConjunct ()
boolean isAuxExpr ()
boolean isRegisteredPredicate ()
void setIsAuxExpr ()
Function getFn ()
void analyzeNoThrow (Analyzer analyzer)
void castChildCharsToStrings (Analyzer analyzer) throws AnalysisException
String toSql ()
TExpr treeToThrift ()
boolean isAggregate ()
List< String > childrenToSql ()
int hashCode ()
List< Expr > getConjuncts ()
Expr trySubstitute (ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootType) throws AnalysisException
Expr substitute (ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootType)
Expr reset ()
boolean isBound (TupleId tid)
boolean isBound (SlotId slotId)
boolean isBoundByTupleIds (List< TupleId > tids)
boolean isBoundBySlotIds (List< SlotId > slotIds)
void getIds (List< TupleId > tupleIds, List< SlotId > slotIds)
boolean isLiteral ()
boolean isNullLiteral ()
boolean isScalarSubquery ()
void checkReturnsBool (String name, boolean printExpr) throws AnalysisException
final Expr castTo (Type targetType) throws AnalysisException
void castChild (Type targetType, int childIndex) throws AnalysisException
Expr ignoreImplicitCast ()
boolean isImplicitCast ()
String toString ()
SlotRef unwrapSlotRef (boolean implicitOnly)
Expr negate ()
Subquery getSubquery ()
void foldConstantChildren (Analyzer analyzer) throws AnalysisException
Static Public Member Functions
static boolean isAnalyticFn (Function fn)
static boolean isAggregateFn (Function fn)
static long getNumDistinctValues (List< Expr > exprs)
static void analyze (List<?extends Expr > exprs, Analyzer analyzer) throws AnalysisException
static String toSql (List<?extends Expr > exprs)
static List< TExpr > treesToThrift (List<?extends Expr > exprs)
static
com.google.common.base.Predicate
< Expr > isAggregatePredicate ()
static String debugString (List<?extends Expr > exprs)
static< CextendsExpr > boolean equalLists (List< C > l1, List< C > l2)
static< CextendsExpr > boolean equalSets (List< C > l1, List< C > l2)
static< CextendsExpr > boolean isSubset (List< C > l1, List< C > l2)
static< CextendsExpr > List< C > intersect (List< C > l1, List< C > l2)
static void intersect (Analyzer analyzer, List< Expr > l1, List< Expr > l2, ExprSubstitutionMap smap, List< Expr > i1, List< Expr > i2)
static ArrayList< Expr > trySubstituteList (Iterable<?extends Expr > exprs, ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootTypes) throws AnalysisException
static ArrayList< Expr > substituteList (Iterable<?extends Expr > exprs, ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootTypes)
static ArrayList< Expr > resetList (ArrayList< Expr > l)
static< CextendsExpr >
ArrayList< C > cloneList (Iterable< C > l)
static< CextendsExpr > void removeDuplicates (List< C > l)
static< CextendsExpr > void removeConstants (List< C > l)
static boolean isBound (List<?extends Expr > exprs, List< TupleId > tids)
static< CextendsExpr > void getIds (List<?extends Expr > exprs, List< TupleId > tupleIds, List< SlotId > slotIds)
static Expr pushNegationToOperands (Expr root)
Static Public Attributes
static String FIRST_VALUE_REWRITE = "first_value_rewrite"
static final int EXPR_CHILDREN_LIMIT = 10000
static final int EXPR_DEPTH_LIMIT = 1000
static final
com.google.common.base.Predicate
< Expr > IS_NOT_PREDICATE
static final
com.google.common.base.Predicate
< Expr > IS_OR_PREDICATE
static final
com.google.common.base.Predicate
< Expr > IS_SCALAR_SUBQUERY
static final
com.google.common.base.Predicate
< Expr > NON_NULL_EMPTY_AGG
static final
com.google.common.base.Predicate
< Expr > IS_BUILTIN_AGG_FN
static final
com.google.common.base.Predicate
< Expr > IS_TRUE_LITERAL
Protected Member Functions
AnalyticExpr (AnalyticExpr other)
void toThrift (TExprNode msg)
void resetAnalysisState ()
Expr substituteImpl (ExprSubstitutionMap smap, Analyzer analyzer) throws AnalysisException
void setId (ExprId id)
void computeNumDistinctValues ()
Type[] collectChildReturnTypes ()
Function getBuiltinFunction (Analyzer analyzer, String name, Type[] argTypes, CompareMode mode) throws AnalysisException
void castForFunctionCall (boolean ignoreWildcardDecimals) throws AnalysisException
void convertNumericLiteralsFromDecimal (Analyzer analyzer) throws AnalysisException
void treeToThriftHelper (TExpr container)
void getIdsHelper (Set< TupleId > tupleIds, Set< SlotId > slotIds)
Expr uncheckedCastTo (Type targetType) throws AnalysisException
void uncheckedCastChild (Type targetType, int childIndex) throws AnalysisException
Protected Attributes
ExprId id_
Type type_
boolean isAnalyzed_
boolean isWhereClauseConjunct_
boolean printSqlInParens_ = false
double selectivity_
long numDistinctValues_
Function fn_
Static Protected Attributes
static double DEFAULT_SELECTIVITY = 0.1
Package Functions
void checkOffset (Analyzer analyzer) throws AnalysisException
Type getResolvedWildCardType () throws AnalysisException
Private Member Functions
void checkRangeOffsetBoundaryExpr (AnalyticWindow.Boundary boundary) throws AnalysisException
void standardize (Analyzer analyzer)
Expr getOffsetExpr (FunctionCallExpr offsetFnCall)
void syncWithChildren ()
void setChildren ()
Static Private Member Functions
static boolean isOffsetFn (Function fn)
static boolean isMinMax (Function fn)
static boolean isRankingFn (Function fn)
Private Attributes
FunctionCallExpr fnCall_
final List< Expr > partitionExprs_
List< OrderByElement > orderByElements_ = Lists.newArrayList()
AnalyticWindow window_
boolean resetWindow_ = false
String sqlString_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(AnalyticExpr.class)
static String LEAD = "lead"
static String LAG = "lag"
static String FIRSTVALUE = "first_value"
static String LASTVALUE = "last_value"
static String RANK = "rank"
static String DENSERANK = "dense_rank"
static String ROWNUMBER = "row_number"
static String MIN = "min"
static String MAX = "max"
Detailed Description
Representation of an analytic function call with OVER clause. All "subexpressions" (such as the actual function call parameters as well as the partition/ordering exprs, etc.) are embedded as children in order to allow expr substitution: function call params: child 0 .. #params partition exprs: children #params + 1 .. #params + #partition-exprs ordering exprs: children #params + #partition-exprs + 1 .. #params + #partition-exprs + #order-by-elements exprs in windowing clause: remaining children
Note that it's wrong to embed the FunctionCallExpr itself as a child, because in 'COUNT(..) OVER (..)' the 'COUNT(..)' is not part of a standard aggregate computation and must not be substituted as such. However, the parameters of the analytic function call might reference the output of an aggregate computation and need to be substituted as such; example: COUNT(COUNT(..)) OVER (..)
Definition at line 60 of file AnalyticExpr.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr (FunctionCallExpr fnCall, List< Expr > partitionExprs, List< OrderByElement > orderByElements, AnalyticWindow window) inline
Definition at line 92 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.fnCall_, com.cloudera.impala.analysis.AnalyticExpr.partitionExprs_, com.cloudera.impala.analysis.AnalyticExpr.setChildren(), and com.cloudera.impala.analysis.AnalyticExpr.window_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.clone(), com.cloudera.impala.analysis.AnalyticExpr.equals(), and com.cloudera.impala.analysis.AnalyticExpr.substituteImpl().
com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr (AnalyticExpr other) inline protected
clone() c'tor
Definition at line 105 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.FunctionCallExpr.clone(), com.cloudera.impala.analysis.AnalyticExpr.fnCall_, com.cloudera.impala.analysis.AnalyticExpr.orderByElements_, com.cloudera.impala.analysis.AnalyticExpr.partitionExprs_, com.cloudera.impala.analysis.AnalyticExpr.resetWindow_, com.cloudera.impala.analysis.AnalyticExpr.setChildren(), com.cloudera.impala.analysis.AnalyticExpr.sqlString_, and com.cloudera.impala.analysis.AnalyticExpr.window_.
Member Function Documentation
void com.cloudera.impala.analysis.AnalyticExpr.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 261 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.checkOffset(), com.cloudera.impala.analysis.AnalyticExpr.checkRangeOffsetBoundaryExpr(), com.cloudera.impala.analysis.AnalyticExpr.getFnCall(), com.cloudera.impala.analysis.AnalyticWindow.getLeftBoundary(), com.cloudera.impala.analysis.AnalyticWindow.getRightBoundary(), com.cloudera.impala.analysis.Expr.getType(), com.cloudera.impala.analysis.AnalyticExpr.isAggregateFn(), com.cloudera.impala.analysis.AnalyticExpr.isAnalyticFn(), com.cloudera.impala.analysis.Expr.isAnalyzed_, com.cloudera.impala.analysis.AnalyticExpr.isConstant(), com.cloudera.impala.analysis.AnalyticExpr.isMinMax(), com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn(), com.cloudera.impala.analysis.AnalyticExpr.isRankingFn(), com.cloudera.impala.analysis.AnalyticExpr.orderByElements_, com.cloudera.impala.analysis.AnalyticExpr.partitionExprs_, com.cloudera.impala.analysis.AnalyticExpr.setChildren(), com.cloudera.impala.analysis.AnalyticExpr.sqlString_, com.cloudera.impala.analysis.AnalyticExpr.standardize(), com.cloudera.impala.analysis.Expr.toSql(), com.cloudera.impala.analysis.Expr.type_, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_PRECEDING, and com.cloudera.impala.analysis.AnalyticExpr.window_.
static void com.cloudera.impala.analysis.Expr.analyze (List<?extends Expr > exprs, Analyzer analyzer) throws AnalysisException inline static inherited
Helper function: analyze list of exprs
Definition at line 440 of file Expr.java.
void com.cloudera.impala.analysis.Expr.analyzeNoThrow (Analyzer analyzer) inline inherited
Helper function to analyze this expr and assert that the analysis was successful. TODO: This function could be used in many more places to clean up. Consider adding an IAnalyzable interface or similar to and move this helper into Analyzer such that non-Expr things can use the helper also.
Definition at line 238 of file Expr.java.
References com.cloudera.impala.analysis.Expr.analyze().
void com.cloudera.impala.analysis.Expr.castChild (Type targetType, int childIndex) throws AnalysisException inline inherited
Add a cast expression above child. If child is a literal expression, we attempt to convert the value of the child directly, and not insert a cast node.
Parameters
targetType type to be cast to
childIndex index of child to be cast
Definition at line 1008 of file Expr.java.
Referenced by com.cloudera.impala.analysis.CaseExpr.analyze(), and com.cloudera.impala.analysis.Expr.castForFunctionCall().
void com.cloudera.impala.analysis.Expr.castChildCharsToStrings (Analyzer analyzer) throws AnalysisException inline inherited
Casts any child which is CHAR to a STRING.
Definition at line 277 of file Expr.java.
References com.cloudera.impala.analysis.Expr.analyze(), com.cloudera.impala.analysis.Expr.castTo(), com.cloudera.impala.catalog.PrimitiveType.CHAR, and com.cloudera.impala.catalog.Type.STRING.
Referenced by com.cloudera.impala.analysis.CaseExpr.analyze().
void com.cloudera.impala.analysis.Expr.castForFunctionCall (boolean ignoreWildcardDecimals) throws AnalysisException inline protected inherited
Generates the necessary casts for the children of this expr to call fn_. child(0) is cast to the function's first argument, child(1) to the second etc. This does not do any validation and the casts are assumed to be safe.
If ignoreWildcardDecimals is true, the function will not cast arguments that are wildcard decimals. This is used for builtins where the cast is done within the BE function. Otherwise, if the function signature contains wildcard decimals, each wildcard child argument will be cast to the highest resolution that can contain all of the child wildcard arguments. e.g. fn(decimal(*), decimal(*)) called with fn(decimal(10,2), decimal(5,3)) both children will be cast to (11, 3).
Definition at line 312 of file Expr.java.
References com.cloudera.impala.analysis.Expr.castChild(), com.cloudera.impala.analysis.Expr.fn_, and com.cloudera.impala.analysis.Expr.getResolvedWildCardType().
Referenced by com.cloudera.impala.analysis.LikePredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.CompoundPredicate.analyze(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), and com.cloudera.impala.analysis.FunctionCallExpr.analyze().
final Expr com.cloudera.impala.analysis.Expr.castTo (Type targetType) throws AnalysisException inline inherited
Casts this expr to a specific target type. It checks the validity of the cast and calls uncheckedCastTo().
Parameters
targetType type to be cast to
Returns
cast expression, or converted literal, should never return null
Exceptions
AnalysisException when an invalid cast is asked for, for example, failure to convert a string literal to a date literal
Definition at line 967 of file Expr.java.
References com.cloudera.impala.analysis.Expr.type_, and com.cloudera.impala.analysis.Expr.uncheckedCastTo().
Referenced by com.cloudera.impala.analysis.Expr.castChildCharsToStrings().
void com.cloudera.impala.analysis.AnalyticExpr.checkOffset (Analyzer analyzer) throws AnalysisException inline package
Checks offset of lag()/lead().
Definition at line 236 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.Expr.getFn(), com.cloudera.impala.analysis.AnalyticExpr.getFnCall(), com.cloudera.impala.util.TColumnValueUtil.getNumericVal(), com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn(), offset, and com.cloudera.impala.analysis.Expr.toSql().
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze().
void com.cloudera.impala.analysis.AnalyticExpr.checkRangeOffsetBoundaryExpr (AnalyticWindow.Boundary boundary) throws AnalysisException inline private
Checks that the value expr of an offset boundary of a RANGE window is compatible with orderingExprs (and that there's only a single ordering expr).
Definition at line 215 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.Expr.getType(), com.cloudera.impala.catalog.Type.isImplicitlyCastable(), com.cloudera.impala.analysis.AnalyticExpr.orderByElements_, and com.cloudera.impala.analysis.Expr.toSql().
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze().
void com.cloudera.impala.analysis.Expr.checkReturnsBool (String name, boolean printExpr) throws AnalysisException inline inherited
Checks whether this expr returns a boolean type or NULL type. If not, throws an AnalysisException with an appropriate error message using 'name' as a prefix. For example, 'name' could be "WHERE clause". The error message only contains this.toSql() if printExpr is true.
Definition at line 947 of file Expr.java.
References com.cloudera.impala.catalog.Type.isBoolean(), impala.name, com.cloudera.impala.analysis.Expr.toSql(), and com.cloudera.impala.analysis.Expr.type_.
List<String> com.cloudera.impala.analysis.Expr.childrenToSql () inline inherited
Definition at line 531 of file Expr.java.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.toSqlImpl().
Expr com.cloudera.impala.analysis.AnalyticExpr.clone () inline
Definition at line 142 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr().
static <CextendsExpr> ArrayList<C> com.cloudera.impala.analysis.Expr.cloneList (Iterable< C > l) inline static inherited
Create a deep copy of 'l'. The elements of the returned list are of the same type as the input list.
Definition at line 798 of file Expr.java.
Referenced by com.cloudera.impala.planner.DistributedPlanner.createHashJoinFragment().
Type [] com.cloudera.impala.analysis.Expr.collectChildReturnTypes () inline protected inherited
Collects the returns types of the child nodes in an array.
Definition at line 266 of file Expr.java.
References com.cloudera.impala.analysis.Expr.type_.
Referenced by com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.LikePredicate.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.CompoundPredicate.analyze(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), and com.cloudera.impala.analysis.FunctionCallExpr.analyze().
void com.cloudera.impala.analysis.Expr.computeNumDistinctValues () inline protected inherited
Definition at line 246 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isConstant(), and com.cloudera.impala.analysis.Expr.numDistinctValues_.
Referenced by com.cloudera.impala.analysis.Expr.analyze(), and com.cloudera.impala.analysis.CastExpr.CastExpr().
void com.cloudera.impala.analysis.Expr.convertNumericLiteralsFromDecimal (Analyzer analyzer) throws AnalysisException inline protected inherited
Converts numeric literal in the expr tree rooted at this expr to return floating point types instead of decimals, if possible.
Decimal has a higher processing cost than floating point and we should not pay the cost if the user does not require the accuracy. For example: "select float_col + 1.1" would start out with 1.1 as a decimal(2,1) and the float_col would be promoted to a high accuracy decimal. This function will identify this case and treat 1.1 as a float. In the case of "decimal_col + 1.1", 1.1 would remain a decimal. In the case of "float_col + cast(1.1 as decimal(2,1))", the result would be a decimal.
Another way to think about it is that DecimalLiterals are analyzed as returning decimals (of the narrowest precision/scale) and we later convert them to a floating point type when it is consistent with the user's intent.
TODO: another option is to do constant folding in the FE and then apply this rule.
Definition at line 413 of file Expr.java.
References com.cloudera.impala.analysis.Expr.convertNumericLiteralsToFloat(), com.cloudera.impala.catalog.Type.isDecimal(), and com.cloudera.impala.analysis.Expr.isExplicitCastToDecimal().
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), and com.cloudera.impala.analysis.BinaryPredicate.analyze().
String com.cloudera.impala.analysis.AnalyticExpr.debugString () inline
Definition at line 172 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.getFnCall(), and com.cloudera.impala.analysis.AnalyticExpr.window_.
static String com.cloudera.impala.analysis.Expr.debugString (List<?extends Expr > exprs) inline static inherited
Definition at line 543 of file Expr.java.
static <CextendsExpr> boolean com.cloudera.impala.analysis.Expr.equalLists (List< C > l1, List< C > l2) inline static inherited
Return true if l1[i].equals(l2[i]) for all i.
Definition at line 584 of file Expr.java.
Referenced by com.cloudera.impala.analysis.AggregateInfo.createDistinctAggInfo().
boolean com.cloudera.impala.analysis.AnalyticExpr.equals (Object obj) inline
Definition at line 124 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), com.cloudera.impala.analysis.FunctionCallExpr.equals(), com.cloudera.impala.analysis.AnalyticWindow.equals(), com.cloudera.impala.analysis.AnalyticExpr.fnCall_, com.cloudera.impala.analysis.AnalyticExpr.getFnCall(), and com.cloudera.impala.analysis.AnalyticExpr.window_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isMinMax(), com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn(), and com.cloudera.impala.analysis.AnalyticExpr.isRankingFn().
static <CextendsExpr> boolean com.cloudera.impala.analysis.Expr.equalSets (List< C > l1, List< C > l2) inline static inherited
Return true if l1 equals l2 when both lists are interpreted as sets. TODO: come up with something better than O(n^2)?
Definition at line 598 of file Expr.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.WindowGroup.isCompatible(), and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf().
void com.cloudera.impala.analysis.Expr.foldConstantChildren (Analyzer analyzer) throws AnalysisException inline inherited
Evaluate in the BE the children of 'this' that are constant expressions and substitute them with the evaluation result as LiteralExprs. Modifies 'this' in place and does not re-analyze it. Hence, it is not safe to evaluate the modified expr in the BE as the resolved fn_ may be incorrect given the new arguments.
Throws an AnalysisException if the evaluation fails in the BE.
TODO: Used only during partition pruning. Convert it to a generic constant expression folding function to be used during the analysis.
Definition at line 1134 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isAnalyzed_, and com.cloudera.impala.analysis.Expr.isLiteral().
Function com.cloudera.impala.analysis.Expr.getBuiltinFunction (Analyzer analyzer, String name, Type[] argTypes, CompareMode mode) throws AnalysisException inline protected inherited
Looks up in the catalog the builtin for 'name' and 'argTypes'. Returns null if the function is not found.
Definition at line 290 of file Expr.java.
References com.cloudera.impala.catalog.Catalog.BUILTINS_DB, com.cloudera.impala.catalog.Type.INVALID, and impala.name.
Referenced by com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.LikePredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.CompoundPredicate.analyze(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), and com.cloudera.impala.analysis.CaseExpr.analyze().
List<Expr> com.cloudera.impala.analysis.Expr.getConjuncts () inline inherited
Gather conjuncts from this expr and return them in a list. A conjunct is an expr that returns a boolean, e.g., Predicates, function calls, SlotRefs, etc. Hence, this method is placed here and not in Predicate.
Definition at line 662 of file Expr.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.StmtRewriter.canEliminate(), com.cloudera.impala.analysis.StmtRewriter.mergeExpr(), com.cloudera.impala.analysis.Analyzer.registerConjuncts(), com.cloudera.impala.analysis.Analyzer.registerOnClauseConjuncts(), and com.cloudera.impala.analysis.StmtRewriter.rewriteWhereClauseSubqueries().
Function com.cloudera.impala.analysis.Expr.getFn () inline inherited
Definition at line 197 of file Expr.java.
References com.cloudera.impala.analysis.Expr.fn_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.checkOffset(), com.cloudera.impala.analysis.AnalyticExpr.getOffsetExpr(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
FunctionCallExpr com.cloudera.impala.analysis.AnalyticExpr.getFnCall () inline
Definition at line 118 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.fnCall_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.checkOffset(), com.cloudera.impala.analysis.AnalyticExpr.debugString(), com.cloudera.impala.analysis.AnalyticExpr.equals(), com.cloudera.impala.analysis.AnalyticExpr.getOffsetExpr(), com.cloudera.impala.analysis.ColumnLineageGraph.getProjectionDeps(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
ExprId com.cloudera.impala.analysis.Expr.getId () inline inherited
Definition at line 186 of file Expr.java.
References com.cloudera.impala.analysis.Expr.id_.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate(), com.cloudera.impala.analysis.Analyzer.getBoundPredicates(), com.cloudera.impala.analysis.SlotRef.getIdsHelper(), com.cloudera.impala.analysis.Analyzer.registerConjunct(), com.cloudera.impala.analysis.SlotRef.toString(), and com.cloudera.impala.analysis.SlotRef.toThrift().
void com.cloudera.impala.analysis.Expr.getIds (List< TupleId > tupleIds, List< SlotId > slotIds) inline inherited
Definition at line 883 of file Expr.java.
References com.cloudera.impala.analysis.Expr.getIdsHelper().
static <CextendsExpr> void com.cloudera.impala.analysis.Expr.getIds (List<?extends Expr > exprs, List< TupleId > tupleIds, List< SlotId > slotIds) inline static inherited
Definition at line 897 of file Expr.java.
void com.cloudera.impala.analysis.Expr.getIdsHelper (Set< TupleId > tupleIds, Set< SlotId > slotIds) inline protected inherited
Definition at line 891 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.getIds().
long com.cloudera.impala.analysis.Expr.getNumDistinctValues () inline inherited
Definition at line 190 of file Expr.java.
References com.cloudera.impala.analysis.Expr.numDistinctValues_.
Referenced by com.cloudera.impala.analysis.SlotRef.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), and com.cloudera.impala.analysis.SlotRef.SlotRef().
static long com.cloudera.impala.analysis.Expr.getNumDistinctValues (List< Expr > exprs) inline static inherited
Returns the product of the given exprs' number of distinct values or -1 if any of the exprs have an invalid number of distinct values.
Definition at line 502 of file Expr.java.
Expr com.cloudera.impala.analysis.AnalyticExpr.getOffsetExpr (FunctionCallExpr offsetFnCall) inline private
Returns the explicit or implicit offset of an analytic function call.
Definition at line 542 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.Expr.getFn(), com.cloudera.impala.analysis.AnalyticExpr.getFnCall(), and com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn().
Referenced by com.cloudera.impala.analysis.AnalyticExpr.standardize().
List<OrderByElement> com.cloudera.impala.analysis.AnalyticExpr.getOrderByElements () inline
Definition at line 120 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.orderByElements_.
Referenced by com.cloudera.impala.analysis.ColumnLineageGraph.getPredicateDeps(), and com.cloudera.impala.planner.AnalyticPlanner.WindowGroup.isCompatible().
List<Expr> com.cloudera.impala.analysis.AnalyticExpr.getPartitionExprs () inline
Definition at line 119 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.partitionExprs_.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.WindowGroup.isCompatible().
Type com.cloudera.impala.analysis.Expr.getResolvedWildCardType () throws AnalysisException inline package inherited
Returns the max resolution type of all the wild card decimal types. Returns null if there are no wild card types.
Definition at line 336 of file Expr.java.
References com.cloudera.impala.catalog.Type.isNull(), com.cloudera.impala.catalog.Type.isWildcardDecimal(), and com.cloudera.impala.analysis.Expr.type_.
Referenced by com.cloudera.impala.analysis.Expr.castForFunctionCall().
double com.cloudera.impala.analysis.Expr.getSelectivity () inline inherited
Definition at line 189 of file Expr.java.
References com.cloudera.impala.analysis.Expr.selectivity_.
Subquery com.cloudera.impala.analysis.Expr.getSubquery () inline inherited
Returns the subquery of an expr. Returns null if this expr does not contain a subquery.
TODO: Support predicates with more that one subqueries when we implement the independent subquery evaluation.
Definition at line 1114 of file Expr.java.
Type com.cloudera.impala.analysis.Expr.getType () inline inherited
Definition at line 188 of file Expr.java.
References com.cloudera.impala.analysis.Expr.type_.
Referenced by com.cloudera.impala.analysis.Subquery.analyze(), com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.LimitElement.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.AnalyzeExprsTest.checkCasts(), com.cloudera.impala.analysis.AnalyticInfo.checkConsistency(), com.cloudera.impala.analysis.AggregateInfo.checkConsistency(), com.cloudera.impala.analysis.AnalyticWindow.checkOffsetBoundaries(), com.cloudera.impala.analysis.AnalyticExpr.checkRangeOffsetBoundaryExpr(), com.cloudera.impala.analysis.Subquery.createStructTypeFromExprList(), com.cloudera.impala.analysis.InlineViewRef.createTupleDescriptor(), com.cloudera.impala.catalog.ColumnStats.fromExpr(), com.cloudera.impala.planner.DataSourceScanNode.getDisjunctsHelper(), com.cloudera.impala.analysis.Expr.isExplicitCastToDecimal(), com.cloudera.impala.analysis.Expr.isScalarSubquery(), com.cloudera.impala.planner.DataSourceScanNode.literalToColumnValue(), com.cloudera.impala.analysis.Subquery.returnsScalarColumn(), com.cloudera.impala.analysis.QueryStmt.substituteOrdinals(), com.cloudera.impala.analysis.Expr.trySubstitute(), and com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest().
AnalyticWindow com.cloudera.impala.analysis.AnalyticExpr.getWindow () inline
Definition at line 121 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.window_.
int com.cloudera.impala.analysis.Expr.hashCode () inline inherited
Definition at line 649 of file Expr.java.
References com.cloudera.impala.analysis.Expr.id_.
Expr com.cloudera.impala.analysis.Expr.ignoreImplicitCast () inline inherited
Returns child expr if this expr is an implicit cast, otherwise returns 'this'.
Definition at line 1034 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isImplicitCast().
static <CextendsExpr> List<C> com.cloudera.impala.analysis.Expr.intersect (List< C > l1, List< C > l2) inline static inherited
Return the intersection of l1 and l2.599
Definition at line 614 of file Expr.java.
static void com.cloudera.impala.analysis.Expr.intersect (Analyzer analyzer, List< Expr > l1, List< Expr > l2, ExprSubstitutionMap smap, List< Expr > i1, List< Expr > i2) inline static inherited
Compute the intersection of l1 and l2, given the smap, and return the intersecting l1 elements in i1 and the intersecting l2 elements in i2.
Definition at line 626 of file Expr.java.
References com.cloudera.impala.analysis.Expr.equals().
boolean com.cloudera.impala.analysis.Expr.isAggregate () inline inherited
Definition at line 527 of file Expr.java.
static boolean com.cloudera.impala.analysis.AnalyticExpr.isAggregateFn (Function fn) inline static
Definition at line 189 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze().
static com.google.common.base.Predicate<Expr> com.cloudera.impala.analysis.Expr.isAggregatePredicate () inline static inherited
Definition at line 523 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isAggregatePredicate_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), and com.cloudera.impala.analysis.TableRef.analyzeJoin().
static boolean com.cloudera.impala.analysis.AnalyticExpr.isAnalyticFn (Function fn) inline static
Definition at line 184 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.isMinMax(), com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn(), and com.cloudera.impala.analysis.AnalyticExpr.isRankingFn().
boolean com.cloudera.impala.analysis.Expr.isAuxExpr () inline inherited
Definition at line 194 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isAuxExpr_.
Referenced by com.cloudera.impala.analysis.Analyzer.hasUnassignedConjuncts().
boolean com.cloudera.impala.analysis.Expr.isBound (TupleId tid) inline inherited
Returns true if expr is fully bound by tid, otherwise false.
Definition at line 845 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isBoundByTupleIds().
Referenced by com.cloudera.impala.analysis.SelectStmt.analyzeAggregation().
boolean com.cloudera.impala.analysis.Expr.isBound (SlotId slotId) inline inherited
Returns true if expr is fully bound by slotId, otherwise false.
Definition at line 862 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isBoundBySlotIds().
static boolean com.cloudera.impala.analysis.Expr.isBound (List<?extends Expr > exprs, List< TupleId > tids) inline static inherited
Definition at line 876 of file Expr.java.
boolean com.cloudera.impala.analysis.Expr.isBoundBySlotIds (List< SlotId > slotIds) inline inherited
Returns true if expr is fully bound by slotIds, otherwise false.
Definition at line 869 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.isBound(), and com.cloudera.impala.planner.HdfsScanNode.prunePartitions().
boolean com.cloudera.impala.analysis.Expr.isBoundByTupleIds (List< TupleId > tids) inline inherited
Returns true if expr is fully bound by tids, otherwise false.
Definition at line 852 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate(), com.cloudera.impala.planner.AnalyticPlanner.createSortInfo(), com.cloudera.impala.analysis.Expr.isBound(), and com.cloudera.impala.analysis.StmtRewriter.mergeExpr().
boolean com.cloudera.impala.analysis.AnalyticExpr.isConstant () inline
Analytic exprs cannot be constant.
Definition at line 139 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze().
boolean com.cloudera.impala.analysis.Expr.isImplicitCast () inline inherited
Returns true if 'this' is an implicit cast expr.
Definition at line 1042 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.ignoreImplicitCast(), com.cloudera.impala.analysis.Expr.reset(), and com.cloudera.impala.analysis.Expr.substituteImpl().
boolean com.cloudera.impala.analysis.Expr.isLiteral () inline inherited
Returns
true if this is an instance of LiteralExpr
Definition at line 908 of file Expr.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.canEvalUsingPartitionMd(), com.cloudera.impala.analysis.CaseExpr.CaseExpr(), and com.cloudera.impala.analysis.Expr.foldConstantChildren().
static boolean com.cloudera.impala.analysis.AnalyticExpr.isMinMax (Function fn) inline static private
Definition at line 199 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.equals(), com.cloudera.impala.analysis.AnalyticExpr.isAnalyticFn(), com.cloudera.impala.analysis.AnalyticExpr.MAX, and com.cloudera.impala.analysis.AnalyticExpr.MIN.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze().
boolean com.cloudera.impala.analysis.Expr.isNullLiteral () inline inherited
Returns
true if this expr is either a null literal or a cast from a null literal.
Definition at line 926 of file Expr.java.
Referenced by com.cloudera.impala.analysis.CaseExpr.CaseExpr().
static boolean com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn (Function fn) inline static private
Definition at line 194 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.equals(), com.cloudera.impala.analysis.AnalyticExpr.isAnalyticFn(), com.cloudera.impala.analysis.AnalyticExpr.LAG, and com.cloudera.impala.analysis.AnalyticExpr.LEAD.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.checkOffset(), com.cloudera.impala.analysis.AnalyticExpr.getOffsetExpr(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
static boolean com.cloudera.impala.analysis.AnalyticExpr.isRankingFn (Function fn) inline static private
Definition at line 204 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.DENSERANK, com.cloudera.impala.analysis.AnalyticExpr.equals(), com.cloudera.impala.analysis.AnalyticExpr.isAnalyticFn(), com.cloudera.impala.analysis.AnalyticExpr.RANK, and com.cloudera.impala.analysis.AnalyticExpr.ROWNUMBER.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze().
boolean com.cloudera.impala.analysis.Expr.isRegisteredPredicate () inline inherited
Definition at line 195 of file Expr.java.
References com.cloudera.impala.analysis.Expr.id_.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.migrateConjunctsToInlineView().
boolean com.cloudera.impala.analysis.Expr.isScalarSubquery () inline inherited
Return true if this expr is a scalar subquery.
Definition at line 936 of file Expr.java.
References com.cloudera.impala.analysis.Expr.getType(), and com.cloudera.impala.analysis.Expr.isAnalyzed_.
Referenced by com.cloudera.impala.analysis.StmtRewriter.createJoinConjunct().
static <CextendsExpr> boolean com.cloudera.impala.analysis.Expr.isSubset (List< C > l1, List< C > l2) inline static inherited
Return true if l1 is a subset of l2.
Definition at line 606 of file Expr.java.
Referenced by com.cloudera.impala.planner.DistributedPlanner.createInsertFragment().
boolean com.cloudera.impala.analysis.Expr.isWhereClauseConjunct () inline inherited
Definition at line 192 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isWhereClauseConjunct_.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate(), and com.cloudera.impala.analysis.Analyzer.evalByJoin().
Expr com.cloudera.impala.analysis.Expr.negate () inline inherited
Negates a boolean Expr.
Definition at line 1102 of file Expr.java.
References com.cloudera.impala.catalog.PrimitiveType.BOOLEAN.
static Expr com.cloudera.impala.analysis.Expr.pushNegationToOperands (Expr root) inline static inherited
Pushes negation to the individual operands of a predicate tree rooted at 'root'.
Definition at line 1076 of file Expr.java.
References com.cloudera.impala.analysis.Expr.IS_NOT_PREDICATE, and com.cloudera.impala.analysis.Expr.NEGATE_FN.
static <CextendsExpr> void com.cloudera.impala.analysis.Expr.removeConstants (List< C > l) inline static inherited
Removes constant exprs
Definition at line 833 of file Expr.java.
static <CextendsExpr> void com.cloudera.impala.analysis.Expr.removeDuplicates (List< C > l) inline static inherited
Removes duplicate exprs (according to equals()).
Definition at line 810 of file Expr.java.
Expr com.cloudera.impala.analysis.Expr.reset () inline inherited
Resets the internal analysis state of this expr tree. Removes implicit casts.
Definition at line 771 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isImplicitCast(), and com.cloudera.impala.analysis.Expr.resetAnalysisState().
Referenced by com.cloudera.impala.analysis.Expr.resetList().
void com.cloudera.impala.analysis.AnalyticExpr.resetAnalysisState () inline protected
Definition at line 588 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.resetWindow_, com.cloudera.impala.analysis.AnalyticExpr.syncWithChildren(), and com.cloudera.impala.analysis.AnalyticExpr.window_.
static ArrayList<Expr> com.cloudera.impala.analysis.Expr.resetList (ArrayList< Expr > l) inline static inherited
Definition at line 780 of file Expr.java.
References com.cloudera.impala.analysis.Expr.reset().
void com.cloudera.impala.analysis.AnalyticExpr.setChildren () inline private
Populate children_ from fnCall_, partitionExprs_, orderByElements_
Definition at line 569 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.fnCall_, com.cloudera.impala.analysis.AnalyticWindow.getLeftBoundary(), com.cloudera.impala.analysis.AnalyticWindow.getRightBoundary(), com.cloudera.impala.analysis.AnalyticExpr.orderByElements_, com.cloudera.impala.analysis.AnalyticExpr.partitionExprs_, and com.cloudera.impala.analysis.AnalyticExpr.window_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), and com.cloudera.impala.analysis.AnalyticExpr.analyze().
void com.cloudera.impala.analysis.Expr.setId (ExprId id) inline protected inherited
Definition at line 187 of file Expr.java.
void com.cloudera.impala.analysis.Expr.setIsAuxExpr () inline inherited
Definition at line 196 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isAuxExpr_.
void com.cloudera.impala.analysis.Expr.setIsWhereClauseConjunct () inline inherited
Definition at line 193 of file Expr.java.
References com.cloudera.impala.analysis.Expr.isWhereClauseConjunct_.
void com.cloudera.impala.analysis.Expr.setPrintSqlInParens (boolean b) inline inherited
Definition at line 191 of file Expr.java.
References com.cloudera.impala.analysis.Expr.printSqlInParens_.
void com.cloudera.impala.analysis.AnalyticExpr.standardize (Analyzer analyzer) inline private
If necessary, rewrites the analytic function, window, and/or order-by elements into a standard format for the purpose of simpler backend execution, as follows:
row_number(): Set a window from UNBOUNDED PRECEDING to CURRENT_ROW.
lead()/lag(): Explicitly set the default arguments to for BE simplicity. Set a window for lead(): UNBOUNDED PRECEDING to OFFSET FOLLOWING. Set a window for lag(): UNBOUNDED PRECEDING to OFFSET PRECEDING.
UNBOUNDED FOLLOWING windows: Reverse the ordering and window if the start bound is not UNBOUNDED PRECEDING. Flip first_value() and last_value().
first_value(): Set the upper boundary to CURRENT_ROW if the lower boundary is UNBOUNDED_PRECEDING.
Explicitly set the default window if no window was given but there are order-by elements.
FIRST_VALUE without UNBOUNDED PRECEDING gets rewritten to use a different window and change the function to return the last value. We either set the fn to be 'last_value' or 'first_value_rewrite', which simply wraps the 'last_value' implementation but allows us to handle the first rows in a partition in a special way in the backend. There are a few cases: a) Start bound is X FOLLOWING or CURRENT ROW (X=0): Use 'last_value' with a window where both bounds are X FOLLOWING (or CURRENT ROW). Setting the start bound to X following is necessary because the X rows at the end of a partition have no rows in their window. Note that X FOLLOWING could be rewritten as lead(X) but that would not work for CURRENT ROW. b) Start bound is X PRECEDING and end bound is CURRENT ROW or FOLLOWING: Use 'first_value_rewrite' and a window with an end bound X PRECEDING. An extra parameter '-1' is added to indicate to the backend that NULLs should not be added for the first X rows. c) Start bound is X PRECEDING and end bound is Y PRECEDING: Use 'first_value_rewrite' and a window with an end bound X PRECEDING. The first Y rows in a partition have empty windows and should be NULL. An extra parameter with the integer constant Y is added to indicate to the backend that NULLs should be added for the first Y rows.
Definition at line 404 of file AnalyticExpr.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.CURRENT_ROW, com.cloudera.impala.analysis.AnalyticWindow.DEFAULT_WINDOW, com.cloudera.impala.analysis.AnalyticExpr.FIRSTVALUE, com.cloudera.impala.analysis.AnalyticExpr.fnCall_, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.FOLLOWING, com.cloudera.impala.analysis.Expr.getFn(), com.cloudera.impala.analysis.AnalyticExpr.getFnCall(), com.cloudera.impala.analysis.FunctionName.getFunction(), com.cloudera.impala.analysis.AnalyticWindow.getLeftBoundary(), com.cloudera.impala.analysis.AnalyticExpr.getOffsetExpr(), com.cloudera.impala.analysis.AnalyticWindow.getRightBoundary(), com.cloudera.impala.analysis.AnalyticWindow.getType(), com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn(), com.cloudera.impala.analysis.AnalyticExpr.LAG, com.cloudera.impala.analysis.AnalyticExpr.LASTVALUE, com.cloudera.impala.analysis.AnalyticExpr.orderByElements_, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.PRECEDING, com.cloudera.impala.analysis.AnalyticExpr.resetWindow_, com.cloudera.impala.analysis.AnalyticExpr.ROWNUMBER, com.cloudera.impala.analysis.Expr.type_, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_FOLLOWING, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_PRECEDING, and com.cloudera.impala.analysis.AnalyticExpr.window_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze().
Expr com.cloudera.impala.analysis.Expr.substitute (ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootType) inline inherited
Returns an analyzed clone of 'this' with exprs substituted according to smap. Removes implicit casts and analysis state while cloning/substituting exprs within this tree, such that the returned result has minimal implicit casts and types. Expects the analysis of the post-substitution expr to succeed. If smap is null, this function is equivalent to clone(). If preserveRootType is true, the resulting expr tree will be cast if necessary to the type of 'this'.
Definition at line 710 of file Expr.java.
References com.cloudera.impala.analysis.Expr.trySubstitute().
Referenced by com.cloudera.impala.planner.HashJoinNode.init().
Expr com.cloudera.impala.analysis.AnalyticExpr.substituteImpl (ExprSubstitutionMap smap, Analyzer analyzer) throws AnalysisException inline protected
Definition at line 598 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr().
static ArrayList<Expr> com.cloudera.impala.analysis.Expr.substituteList (Iterable<?extends Expr > exprs, ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootTypes) inline static inherited
Definition at line 730 of file Expr.java.
References com.cloudera.impala.analysis.Expr.trySubstituteList().
Referenced by com.cloudera.impala.planner.AnalyticPlanner.createSortGroupPlan(), and com.cloudera.impala.planner.AnalyticPlanner.createSortInfo().
void com.cloudera.impala.analysis.AnalyticExpr.syncWithChildren () inline private
Keep fnCall_, partitionExprs_ and orderByElements_ in sync with children_.
Definition at line 552 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.resetAnalysisState().
String com.cloudera.impala.analysis.Expr.toSql () inline inherited
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 449 of file Expr.java.
References com.cloudera.impala.analysis.Expr.printSqlInParens_, and com.cloudera.impala.analysis.Expr.toSqlImpl().
Referenced by com.cloudera.impala.analysis.ExtractFromExpr.analyze(), com.cloudera.impala.analysis.Subquery.analyze(), com.cloudera.impala.analysis.SlotRef.analyze(), com.cloudera.impala.analysis.LimitElement.analyze(), com.cloudera.impala.analysis.LikePredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.CompoundPredicate.analyze(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.Expr.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.analysis.AnalyticExpr.checkOffset(), com.cloudera.impala.analysis.AnalyticExpr.checkRangeOffsetBoundaryExpr(), com.cloudera.impala.analysis.Expr.checkReturnsBool(), com.cloudera.impala.analysis.LiteralExpr.create(), com.cloudera.impala.analysis.StmtRewriter.createJoinConjunct(), com.cloudera.impala.analysis.QueryStmt.createSortInfo(), com.cloudera.impala.analysis.ExtractFromExpr.getFunctionNotFoundError(), com.cloudera.impala.analysis.FunctionCallExpr.getFunctionNotFoundError(), com.cloudera.impala.analysis.Analyzer.registerConjunct(), com.cloudera.impala.analysis.QueryStmt.substituteOrdinals(), com.cloudera.impala.analysis.CaseExpr.toCaseSql(), com.cloudera.impala.analysis.TableRef.toSql(), com.cloudera.impala.analysis.BetweenPredicate.toSqlImpl(), and com.cloudera.impala.analysis.AnalyticExpr.toSqlImpl().
static String com.cloudera.impala.analysis.Expr.toSql (List<?extends Expr > exprs) inline static inherited
Definition at line 552 of file Expr.java.
String com.cloudera.impala.analysis.AnalyticExpr.toSqlImpl () inline
Definition at line 145 of file AnalyticExpr.java.
References com.cloudera.impala.analysis.AnalyticExpr.orderByElements_, com.cloudera.impala.analysis.AnalyticExpr.partitionExprs_, com.cloudera.impala.analysis.AnalyticExpr.sqlString_, com.cloudera.impala.analysis.Expr.toSql(), and com.cloudera.impala.analysis.AnalyticExpr.window_.
String com.cloudera.impala.analysis.Expr.toString () inline inherited
Definition at line 1047 of file Expr.java.
References com.cloudera.impala.analysis.Expr.id_, com.cloudera.impala.analysis.Expr.numDistinctValues_, com.cloudera.impala.analysis.Expr.selectivity_, and com.cloudera.impala.analysis.Expr.type_.
Referenced by com.cloudera.impala.analysis.ExtractFromExpr.analyze(), com.cloudera.impala.analysis.NullLiteral.debugString(), com.cloudera.impala.analysis.NumericLiteral.debugString(), com.cloudera.impala.analysis.CastExpr.debugString(), com.cloudera.impala.analysis.CastExpr.getFnName(), and com.cloudera.impala.analysis.InPredicate.initBuiltins().
void com.cloudera.impala.analysis.AnalyticExpr.toThrift (TExprNode msg) inline protected
Definition at line 181 of file AnalyticExpr.java.
static List<TExpr> com.cloudera.impala.analysis.Expr.treesToThrift (List<?extends Expr > exprs) inline static inherited
Definition at line 515 of file Expr.java.
Referenced by com.cloudera.impala.planner.HdfsTableSink.toThrift(), com.cloudera.impala.planner.SortNode.toThrift(), and com.cloudera.impala.planner.ExchangeNode.toThrift().
TExpr com.cloudera.impala.analysis.Expr.treeToThrift () inline inherited
Definition at line 460 of file Expr.java.
References com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.Type.isNull(), com.cloudera.impala.analysis.Expr.treeToThriftHelper(), and com.cloudera.impala.analysis.Expr.type_.
void com.cloudera.impala.analysis.Expr.treeToThriftHelper (TExpr container) inline protected inherited
Definition at line 474 of file Expr.java.
References com.cloudera.impala.analysis.Expr.fn_, com.cloudera.impala.catalog.Function.getNumArgs(), com.cloudera.impala.catalog.Function.hasVarArgs(), com.cloudera.impala.analysis.Expr.isAnalyzed_, and com.cloudera.impala.analysis.Expr.toThrift().
Referenced by com.cloudera.impala.analysis.Expr.treeToThrift().
Expr com.cloudera.impala.analysis.Expr.trySubstitute (ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootType) throws AnalysisException inline inherited
Returns an analyzed clone of 'this' with exprs substituted according to smap. Removes implicit casts and analysis state while cloning/substituting exprs within this tree, such that the returned result has minimal implicit casts and types. Throws if analyzing the post-substitution expr tree failed. If smap is null, this function is equivalent to clone(). If preserveRootType is true, the resulting expr tree will be cast if necessary to the type of 'this'.
Definition at line 689 of file Expr.java.
References com.cloudera.impala.analysis.Expr.clone(), com.cloudera.impala.analysis.Expr.getType(), and com.cloudera.impala.analysis.Expr.type_.
Referenced by com.cloudera.impala.analysis.Expr.substitute().
static ArrayList<Expr> com.cloudera.impala.analysis.Expr.trySubstituteList (Iterable<?extends Expr > exprs, ExprSubstitutionMap smap, Analyzer analyzer, boolean preserveRootTypes) throws AnalysisException inline static inherited
Definition at line 719 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.substituteList().
void com.cloudera.impala.analysis.Expr.uncheckedCastChild (Type targetType, int childIndex) throws AnalysisException inline protected inherited
Convert child to to targetType, possibly by inserting an implicit cast, or by returning an altogether new expression, or by returning 'this' with a modified return type'.
Parameters
targetType type to be cast to
childIndex index of child to be cast
Definition at line 1024 of file Expr.java.
Referenced by com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), and com.cloudera.impala.analysis.FunctionCallExpr.analyze().
Expr com.cloudera.impala.analysis.Expr.uncheckedCastTo (Type targetType) throws AnalysisException inline protected inherited
Create an expression equivalent to 'this' but returning targetType; possibly by inserting an implicit cast, or by returning an altogether new expression or by returning 'this' with a modified return type'.
Parameters
targetType type to be cast to
Returns
cast expression, or converted literal, should never return null
Exceptions
AnalysisException when an invalid cast is asked for, for example, failure to convert a string literal to a date literal
Definition at line 995 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.castTo().
SlotRef com.cloudera.impala.analysis.Expr.unwrapSlotRef (boolean implicitOnly) inline inherited
If 'this' is a SlotRef or a Cast that wraps a SlotRef, returns that SlotRef. Otherwise returns null.
Definition at line 1060 of file Expr.java.
Member Data Documentation
double com.cloudera.impala.analysis.Expr.DEFAULT_SELECTIVITY = 0.1 static protected inherited
Definition at line 63 of file Expr.java.
Referenced by com.cloudera.impala.analysis.BetweenPredicate.analyze(), com.cloudera.impala.analysis.SlotRef.analyze(), com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), and com.cloudera.impala.analysis.BinaryPredicate.analyze().
String com.cloudera.impala.analysis.AnalyticExpr.DENSERANK = "dense_rank" static private
Definition at line 83 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isRankingFn().
final int com.cloudera.impala.analysis.Expr.EXPR_CHILDREN_LIMIT = 10000 static inherited
Definition at line 54 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.analyze(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprChildLimit().
final int com.cloudera.impala.analysis.Expr.EXPR_DEPTH_LIMIT = 1000 static inherited
Definition at line 56 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.analyze(), com.cloudera.impala.analysis.AnalyzeExprsTest.testFuncExprDepthLimit(), and com.cloudera.impala.analysis.AnalyzeExprsTest.testInfixExprDepthLimit().
String com.cloudera.impala.analysis.AnalyticExpr.FIRST_VALUE_REWRITE = "first_value_rewrite" static
Definition at line 90 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.WindowGroup.requiresIndependentEval().
String com.cloudera.impala.analysis.AnalyticExpr.FIRSTVALUE = "first_value" static private
Definition at line 80 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.standardize().
Function com.cloudera.impala.analysis.Expr.fn_ protected inherited
Definition at line 161 of file Expr.java.
Referenced by com.cloudera.impala.analysis.BetweenPredicate.analyze(), com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.LikePredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.CompoundPredicate.analyze(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.Expr.castForFunctionCall(), com.cloudera.impala.analysis.Expr.equals(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.Expr.getFn(), com.cloudera.impala.analysis.FunctionCallExpr.getReturnType(), com.cloudera.impala.analysis.FunctionCallExpr.isAggregateFunction(), com.cloudera.impala.analysis.FunctionCallExpr.isConstant(), com.cloudera.impala.analysis.FunctionCallExpr.isScalarFunction(), com.cloudera.impala.analysis.FunctionCallExpr.resetAnalysisState(), com.cloudera.impala.analysis.FunctionCallExpr.returnsNonNullOnEmpty(), and com.cloudera.impala.analysis.Expr.treeToThriftHelper().
FunctionCallExpr com.cloudera.impala.analysis.AnalyticExpr.fnCall_ private
Definition at line 63 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), com.cloudera.impala.analysis.AnalyticExpr.equals(), com.cloudera.impala.analysis.AnalyticExpr.getFnCall(), com.cloudera.impala.analysis.AnalyticExpr.setChildren(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
ExprId com.cloudera.impala.analysis.Expr.id_ protected inherited
Definition at line 135 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.debugString(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.Expr.getId(), com.cloudera.impala.analysis.Expr.hashCode(), com.cloudera.impala.analysis.Expr.isRegisteredPredicate(), and com.cloudera.impala.analysis.Expr.toString().
final com.google.common.base.Predicate<Expr> com.cloudera.impala.analysis.Expr.IS_BUILTIN_AGG_FN static inherited
Initial value:
=
      new com.google.common.base.Predicate<Expr>() {
        @Override
        public boolean apply(Expr arg) {
          return arg instanceof FunctionCallExpr &&
              ((FunctionCallExpr)arg).getFnName().isBuiltin();
        }
      }
Definition at line 115 of file Expr.java.
Referenced by com.cloudera.impala.analysis.StmtRewriter.createJoinConjunct().
final com.google.common.base.Predicate<Expr> com.cloudera.impala.analysis.Expr.IS_NOT_PREDICATE static inherited
Initial value:
=
      new com.google.common.base.Predicate<Expr>() {
        @Override
        public boolean apply(Expr arg) {
          return arg instanceof CompoundPredicate &&
              ((CompoundPredicate)arg).getOp() == CompoundPredicate.Operator.NOT;
        }
      }
Definition at line 75 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.pushNegationToOperands().
final com.google.common.base.Predicate<Expr> com.cloudera.impala.analysis.Expr.IS_OR_PREDICATE static inherited
Initial value:
=
      new com.google.common.base.Predicate<Expr>() {
        @Override
        public boolean apply(Expr arg) {
          return arg instanceof CompoundPredicate &&
              ((CompoundPredicate)arg).getOp() == CompoundPredicate.Operator.OR;
        }
      }
Definition at line 85 of file Expr.java.
Referenced by com.cloudera.impala.analysis.StmtRewriter.canExtractCorrelatedPredicates(), and com.cloudera.impala.analysis.StmtRewriter.hasSubqueryInDisjunction().
final com.google.common.base.Predicate<Expr> com.cloudera.impala.analysis.Expr.IS_SCALAR_SUBQUERY static inherited
Initial value:
=
      new com.google.common.base.Predicate<Expr>() {
        @Override
        public boolean apply(Expr arg) {
          return arg.isScalarSubquery();
        }
      }
Definition at line 95 of file Expr.java.
Referenced by com.cloudera.impala.analysis.IsNullPredicate.analyze(), and com.cloudera.impala.analysis.StmtRewriter.rewriteWhereClauseSubqueries().
final com.google.common.base.Predicate<Expr> com.cloudera.impala.analysis.Expr.IS_TRUE_LITERAL static inherited
Initial value:
=
      new com.google.common.base.Predicate<Expr>() {
        @Override
        public boolean apply(Expr arg) {
          return arg instanceof BoolLiteral && ((BoolLiteral)arg).getValue();
        }
      }
Definition at line 124 of file Expr.java.
Referenced by com.cloudera.impala.analysis.StmtRewriter.canEliminate().
boolean com.cloudera.impala.analysis.Expr.isAnalyzed_ protected inherited
Definition at line 143 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Predicate< com.cloudera.impala.analysis.Expr >.analyze(), com.cloudera.impala.analysis.ExistsPredicate.analyze(), com.cloudera.impala.analysis.TupleIsNullPredicate.analyze(), com.cloudera.impala.analysis.ExtractFromExpr.analyze(), com.cloudera.impala.analysis.BetweenPredicate.analyze(), com.cloudera.impala.analysis.Subquery.analyze(), com.cloudera.impala.analysis.SlotRef.analyze(), com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.LikePredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.CompoundPredicate.analyze(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.Expr.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.CastExpr.CastExpr(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.Expr.foldConstantChildren(), com.cloudera.impala.analysis.SlotRef.getDesc(), com.cloudera.impala.analysis.SlotRef.getResolvedPath(), com.cloudera.impala.analysis.BetweenPredicate.getRewrittenPredicate(), com.cloudera.impala.analysis.SlotRef.getSlotId(), com.cloudera.impala.analysis.NumericLiteral.init(), com.cloudera.impala.analysis.SlotRef.isBoundBySlotIds(), com.cloudera.impala.analysis.Expr.isScalarSubquery(), com.cloudera.impala.analysis.NumericLiteral.NumericLiteral(), com.cloudera.impala.analysis.FunctionCallExpr.resetAnalysisState(), com.cloudera.impala.analysis.Expr.resetAnalysisState(), com.cloudera.impala.analysis.SlotRef.SlotRef(), com.cloudera.impala.analysis.Subquery.Subquery(), com.cloudera.impala.analysis.Expr.treeToThriftHelper(), and com.cloudera.impala.analysis.NumericLiteral.uncheckedCastTo().
boolean com.cloudera.impala.analysis.Expr.isWhereClauseConjunct_ protected inherited
Definition at line 144 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.Analyzer.getBoundPredicates(), com.cloudera.impala.analysis.Expr.isWhereClauseConjunct(), and com.cloudera.impala.analysis.Expr.setIsWhereClauseConjunct().
String com.cloudera.impala.analysis.AnalyticExpr.LAG = "lag" static private
Definition at line 79 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
String com.cloudera.impala.analysis.AnalyticExpr.LASTVALUE = "last_value" static private
Definition at line 81 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.standardize().
String com.cloudera.impala.analysis.AnalyticExpr.LEAD = "lead" static private
Definition at line 78 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isOffsetFn().
final Logger com.cloudera.impala.analysis.AnalyticExpr.LOG = LoggerFactory.getLogger(AnalyticExpr.class) static private
Definition at line 61 of file AnalyticExpr.java.
String com.cloudera.impala.analysis.AnalyticExpr.MAX = "max" static private
Definition at line 86 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isMinMax().
String com.cloudera.impala.analysis.AnalyticExpr.MIN = "min" static private
Definition at line 85 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isMinMax().
final com.google.common.base.Predicate<Expr> com.cloudera.impala.analysis.Expr.NON_NULL_EMPTY_AGG static inherited
Initial value:
= new com.google.common.base.Predicate<Expr>() {
        @Override
        public boolean apply(Expr arg) {
          return arg instanceof FunctionCallExpr &&
              ((FunctionCallExpr)arg).returnsNonNullOnEmpty();
        }
      }
Definition at line 106 of file Expr.java.
Referenced by com.cloudera.impala.analysis.StmtRewriter.createJoinConjunct(), and com.cloudera.impala.analysis.StmtRewriter.mergeExpr().
long com.cloudera.impala.analysis.Expr.numDistinctValues_ protected inherited
Definition at line 157 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Predicate< com.cloudera.impala.analysis.Expr >.analyze(), com.cloudera.impala.analysis.SlotRef.analyze(), com.cloudera.impala.analysis.Expr.computeNumDistinctValues(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.Expr.getNumDistinctValues(), com.cloudera.impala.analysis.LiteralExpr.LiteralExpr(), com.cloudera.impala.analysis.SlotRef.SlotRef(), and com.cloudera.impala.analysis.Expr.toString().
List<OrderByElement> com.cloudera.impala.analysis.AnalyticExpr.orderByElements_ = Lists.newArrayList() private
Definition at line 67 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.checkRangeOffsetBoundaryExpr(), com.cloudera.impala.analysis.AnalyticExpr.getOrderByElements(), com.cloudera.impala.analysis.AnalyticExpr.setChildren(), com.cloudera.impala.analysis.AnalyticExpr.standardize(), and com.cloudera.impala.analysis.AnalyticExpr.toSqlImpl().
final List<Expr> com.cloudera.impala.analysis.AnalyticExpr.partitionExprs_ private
Definition at line 64 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.getPartitionExprs(), com.cloudera.impala.analysis.AnalyticExpr.setChildren(), and com.cloudera.impala.analysis.AnalyticExpr.toSqlImpl().
boolean com.cloudera.impala.analysis.Expr.printSqlInParens_ = false protected inherited
Definition at line 148 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.Expr.setPrintSqlInParens(), and com.cloudera.impala.analysis.Expr.toSql().
String com.cloudera.impala.analysis.AnalyticExpr.RANK = "rank" static private
Definition at line 82 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isRankingFn().
boolean com.cloudera.impala.analysis.AnalyticExpr.resetWindow_ = false private
Definition at line 73 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), com.cloudera.impala.analysis.AnalyticExpr.resetAnalysisState(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
String com.cloudera.impala.analysis.AnalyticExpr.ROWNUMBER = "row_number" static private
Definition at line 84 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.isRankingFn(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
double com.cloudera.impala.analysis.Expr.selectivity_ protected inherited
Definition at line 153 of file Expr.java.
Referenced by com.cloudera.impala.analysis.BetweenPredicate.analyze(), com.cloudera.impala.analysis.SlotRef.analyze(), com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.CompoundPredicate.analyze(), com.cloudera.impala.analysis.BinaryPredicate.analyze(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.Expr.getSelectivity(), com.cloudera.impala.analysis.LikePredicate.LikePredicate(), and com.cloudera.impala.analysis.Expr.toString().
String com.cloudera.impala.analysis.AnalyticExpr.sqlString_ private
Definition at line 76 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), and com.cloudera.impala.analysis.AnalyticExpr.toSqlImpl().
Type com.cloudera.impala.analysis.Expr.type_ protected inherited
Definition at line 142 of file Expr.java.
Referenced by com.cloudera.impala.analysis.Predicate< com.cloudera.impala.analysis.Expr >.analyze(), com.cloudera.impala.analysis.Subquery.analyze(), com.cloudera.impala.analysis.SlotRef.analyze(), com.cloudera.impala.analysis.TimestampArithmeticExpr.analyze(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.BoolLiteral.BoolLiteral(), com.cloudera.impala.analysis.CastExpr.CastExpr(), com.cloudera.impala.analysis.Expr.castTo(), com.cloudera.impala.analysis.Expr.checkReturnsBool(), com.cloudera.impala.analysis.Expr.collectChildReturnTypes(), com.cloudera.impala.analysis.NumericLiteral.debugString(), com.cloudera.impala.analysis.CastExpr.debugString(), com.cloudera.impala.analysis.NumericLiteral.explicitlyCastToFloat(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.analysis.ExtractFromExpr.ExtractFromExpr(), com.cloudera.impala.analysis.Expr.getResolvedWildCardType(), com.cloudera.impala.analysis.Expr.getType(), com.cloudera.impala.analysis.NumericLiteral.getUnscaledValue(), com.cloudera.impala.analysis.NullLiteral.NullLiteral(), com.cloudera.impala.analysis.NumericLiteral.NumericLiteral(), com.cloudera.impala.analysis.NullLiteral.resetAnalysisState(), com.cloudera.impala.analysis.SlotRef.SlotRef(), com.cloudera.impala.analysis.AnalyticExpr.standardize(), com.cloudera.impala.analysis.StringLiteral.StringLiteral(), com.cloudera.impala.analysis.Expr.toString(), com.cloudera.impala.analysis.NumericLiteral.toThrift(), com.cloudera.impala.analysis.Expr.treeToThrift(), com.cloudera.impala.analysis.Expr.trySubstitute(), com.cloudera.impala.analysis.NullLiteral.uncheckedCastTo(), com.cloudera.impala.analysis.StringLiteral.uncheckedCastTo(), com.cloudera.impala.analysis.NumericLiteral.uncheckedCastTo(), and com.cloudera.impala.analysis.SlotRef.uncheckedCastTo().
AnalyticWindow com.cloudera.impala.analysis.AnalyticExpr.window_ private
Definition at line 68 of file AnalyticExpr.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.AnalyticExpr(), com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.debugString(), com.cloudera.impala.analysis.AnalyticExpr.equals(), com.cloudera.impala.analysis.AnalyticExpr.getWindow(), com.cloudera.impala.analysis.AnalyticExpr.resetAnalysisState(), com.cloudera.impala.analysis.AnalyticExpr.setChildren(), com.cloudera.impala.analysis.AnalyticExpr.standardize(), and com.cloudera.impala.analysis.AnalyticExpr.toSqlImpl().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AnalyticExpr.java