Impala: com.cloudera.impala.util.GlogAppender Class Reference
com.cloudera.impala.util.GlogAppender Class Reference
Public Member Functions
boolean requiresLayout ()
void ActivateOptions ()
void close ()
void append (LoggingEvent event)
Static Public Member Functions
static void Install (TLogLevel impalaLogLevel, TLogLevel otherLogLevel) throws InternalException
Private Member Functions
TLogLevel levelToSeverity (Level level)
Static Private Member Functions
static String log4jLevelForTLogLevel (TLogLevel logLevel) throws InternalException
Detailed Description
log4j appender which calls into C++ code to log messages at their correct severities via glog.
Definition at line 34 of file GlogAppender.java.
Member Function Documentation
void com.cloudera.impala.util.GlogAppender.ActivateOptions () inline
Definition at line 39 of file GlogAppender.java.
void com.cloudera.impala.util.GlogAppender.append (LoggingEvent event) inline
Definition at line 60 of file GlogAppender.java.
References com.cloudera.impala.util.GlogAppender.levelToSeverity().
void com.cloudera.impala.util.GlogAppender.close () inline
Definition at line 42 of file GlogAppender.java.
static void com.cloudera.impala.util.GlogAppender.Install (TLogLevel impalaLogLevel, TLogLevel otherLogLevel) throws InternalException inline static
Manually override Log4j root logger configuration. Any values in log4j.properties not overridden (that is, anything but the root logger and its default level) will continue to have effect.
impalaLogLevel - the maximum log level for com.cloudera.impala.* classes
otherLogLevel - the maximum log level for all other classes
Definition at line 99 of file GlogAppender.java.
References com.cloudera.impala.util.GlogAppender.log4jLevelForTLogLevel().
TLogLevel com.cloudera.impala.util.GlogAppender.levelToSeverity (Level level) inline private
Definition at line 44 of file GlogAppender.java.
Referenced by com.cloudera.impala.util.GlogAppender.append().
static String com.cloudera.impala.util.GlogAppender.log4jLevelForTLogLevel (TLogLevel logLevel) throws InternalException inline static private
Returns a log4j level string corresponding to the Glog log level
Definition at line 78 of file GlogAppender.java.
Referenced by com.cloudera.impala.util.GlogAppender.Install().
boolean com.cloudera.impala.util.GlogAppender.requiresLayout () inline
Definition at line 36 of file GlogAppender.java.
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/util/GlogAppender.java