Impala: impala::ScopedTimer< T > Class Template Reference
impala::ScopedTimer< T > Class Template Reference
#include <runtime-profile.h>
Public Member Functions
ScopedTimer (RuntimeProfile::Counter *counter)
void Stop ()
void Start ()
void UpdateCounter ()
void ReleaseCounter ()
Updates the underlying counter for the final time and clears the pointer to it.
~ScopedTimer ()
Update counter when object is destroyed.
Private Member Functions
ScopedTimer (const ScopedTimer &timer)
Disable copy constructor and assignment.
ScopedTimer & operator= (const ScopedTimer &timer)
Private Attributes
T sw_
RuntimeProfile::Counter * counter_
Detailed Description
template<class T>
class impala::ScopedTimer< T >
Utility class to update time elapsed when the object goes out of scope. 'T' must implement the StopWatch "interface" (Start,Stop,ElapsedTime) but we use templates not to pay for virtual function overhead.
Definition at line 705 of file runtime-profile.h.
Constructor & Destructor Documentation
template<class T> impala::ScopedTimer< T >::ScopedTimer (RuntimeProfile::Counter * counter) inline
Definition at line 707 of file runtime-profile.h.
template<class T> impala::ScopedTimer< T >::~ScopedTimer () inline
Update counter when object is destroyed.
Definition at line 730 of file runtime-profile.h.
template<class T> impala::ScopedTimer< T >::ScopedTimer (const ScopedTimer< T > & timer) private
Disable copy constructor and assignment.
Member Function Documentation
template<class T> ScopedTimer& impala::ScopedTimer< T >::operator= (const ScopedTimer< T > & timer) private
template<class T> void impala::ScopedTimer< T >::ReleaseCounter () inline
Updates the underlying counter for the final time and clears the pointer to it.
Definition at line 724 of file runtime-profile.h.
template<class T> void impala::ScopedTimer< T >::Start () inline
Definition at line 715 of file runtime-profile.h.
Referenced by impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), and impala::HashJoinNode::LeftJoinGetNext().
template<class T> void impala::ScopedTimer< T >::Stop () inline
Definition at line 714 of file runtime-profile.h.
Referenced by impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), and impala::HashJoinNode::LeftJoinGetNext().
template<class T> void impala::ScopedTimer< T >::UpdateCounter () inline
Definition at line 717 of file runtime-profile.h.
Referenced by impala::ScopedTimer< impala::MonotonicStopWatch >::ReleaseCounter(), and impala::ScopedTimer< impala::MonotonicStopWatch >::~ScopedTimer().
Member Data Documentation
template<class T> RuntimeProfile::Counter* impala::ScopedTimer< T >::counter_ private
Definition at line 741 of file runtime-profile.h.
Referenced by impala::ScopedTimer< impala::MonotonicStopWatch >::ReleaseCounter(), and impala::ScopedTimer< impala::MonotonicStopWatch >::UpdateCounter().
template<class T> T impala::ScopedTimer< T >::sw_ private
Definition at line 740 of file runtime-profile.h.
Referenced by impala::ScopedTimer< impala::MonotonicStopWatch >::ScopedTimer(), impala::ScopedTimer< impala::MonotonicStopWatch >::Start(), impala::ScopedTimer< impala::MonotonicStopWatch >::Stop(), impala::ScopedTimer< impala::MonotonicStopWatch >::UpdateCounter(), and impala::ScopedTimer< impala::MonotonicStopWatch >::~ScopedTimer().
The documentation for this class was generated from the following file:
be/src/util/runtime-profile.h