Impala: impala::JniLocalFrame Class Reference
impala::JniLocalFrame Class Reference
#include <jni-util.h>
Public Member Functions
JniLocalFrame ()
~JniLocalFrame ()
Status push (JNIEnv *env, int max_local_ref=10)
Private Attributes
JNIEnv * env_
Detailed Description
Utility class to push/pop a single JNI frame. "push" will push a JNI frame and the d'tor will pop the JNI frame. Frames establish a scope for local references. Local references go out of scope when their frame is popped, which enables the GC to clean up the corresponding objects.
Definition at line 133 of file jni-util.h.
Constructor & Destructor Documentation
impala::JniLocalFrame::JniLocalFrame () inline
Definition at line 135 of file jni-util.h.
impala::JniLocalFrame::~JniLocalFrame () inline
Definition at line 136 of file jni-util.h.
References env_.
Member Function Documentation
Status impala::JniLocalFrame::push (JNIEnv * env, int max_local_ref = 10)
Pushes a new JNI local frame. The frame can support max_local_ref local references. The number of local references created inside the frame might exceed max_local_ref, but there is no guarantee that memory will be available. Push should be called at most once.
Definition at line 34 of file jni-util.cc.
References env_, and impala::Status::OK.
Referenced by CallJniMethod(), impala::JniUtil::CallJniMethod(), Planner::GeneratePlan(), impala::Catalog::GetAllCatalogObjects(), impala::Catalog::GetCatalogVersion(), impala::HBaseTableScanner::GetCurrentValue(), impala::HBaseTableScanner::HandleResultScannerTimeout(), impala::HBaseTable::Init(), impala::ExternalDataSourceExecutor::Init(), impala::HBaseTableScanner::InitScanRange(), Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs(), impala::HBaseTableScanner::Next(), impala::HiveUdfCall::Open(), impala::HBaseTableScanner::ScanSetup(), impala::Frontend::SetCatalogInitialized(), and impala::Frontend::ValidateSettings().
Member Data Documentation
JNIEnv* impala::JniLocalFrame::env_ private
Definition at line 145 of file jni-util.h.
Referenced by push(), and ~JniLocalFrame().
The documentation for this class was generated from the following files:
be/src/util/jni-util.h
be/src/util/jni-util.cc