Impala: impala::TestInfo Class Reference
impala::TestInfo Class Reference
#include <test-info.h>
Public Types
enum Mode { NON_TEST, BE_TEST, FE_TEST }
Static Public Member Functions
static void Init (Mode mode)
Called in InitCommonRuntime().
static bool is_fe_test ()
static bool is_test ()
Static Private Attributes
static Mode mode_ = TestInfo::NON_TEST
Detailed Description
Provides global access to whether this binary is running as part of the tests (i.e., without a full BE).
Definition at line 22 of file test-info.h.
Member Enumeration Documentation
enum impala::TestInfo::Mode
Enumerator
NON_TEST
BE_TEST
FE_TEST
Definition at line 24 of file test-info.h.
Member Function Documentation
static void impala::TestInfo::Init (Mode mode) inline static
Called in InitCommonRuntime().
Definition at line 31 of file test-info.h.
References mode_.
static bool impala::TestInfo::is_fe_test () inline static
Definition at line 33 of file test-info.h.
References FE_TEST, and mode_.
Referenced by impala::DynamicOpen(), and impala::LibCache::InitInternal().
static bool impala::TestInfo::is_test () inline static
Definition at line 34 of file test-info.h.
References BE_TEST, FE_TEST, and mode_.
Referenced by MaintenanceThread().
Member Data Documentation
TestInfo::Mode TestInfo::mode_ = TestInfo::NON_TEST static private
Definition at line 37 of file test-info.h.
Referenced by Init(), is_fe_test(), and is_test().
The documentation for this class was generated from the following files:
be/src/util/test-info.h
be/src/util/test-info.cc