Impala: com.cloudera.impala.planner.S3PlannerTest Class Reference
com.cloudera.impala.planner.S3PlannerTest Class Reference
Public Member Functions
void setUpTest ()
void testS3ScanRanges ()
Static Public Member Functions
static void setUp () throws Exception
static void cleanUp ()
Protected Member Functions
Path cleanseFilePath (Path path)
void runPlannerTestFile (String testFile, TQueryOptions options)
void runPlannerTestFile (String testFile)
void runPlannerTestFile (String testFile, String dbName)
Private Attributes
final Configuration CONF = new Configuration()
Path fsName
Static Private Attributes
static final String TEST_FS_S3A_NAME = "test.fs.s3a.name"
static final Path S3A_CANONICAL_BUCKET = new Path("s3a://bucket")
Detailed Description
Definition at line 32 of file S3PlannerTest.java.
Member Function Documentation
Path com.cloudera.impala.planner.S3PlannerTest.cleanseFilePath (Path path) inline protected
Remove any non-constant components of the given file path. For S3, the actual bucket name, which will be unique to the tester's setup, needs to be replaced with a fixed bucket name.
Definition at line 64 of file S3PlannerTest.java.
References com.cloudera.impala.planner.S3PlannerTest.fsName, path(), and com.cloudera.impala.planner.S3PlannerTest.S3A_CANONICAL_BUCKET.
static void com.cloudera.impala.planner.PlannerTestBase.cleanUp () inline static inherited
Definition at line 99 of file PlannerTestBase.java.
void com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile (String testFile, TQueryOptions options) inline protected inherited
Definition at line 606 of file PlannerTestBase.java.
Referenced by com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile(), com.cloudera.impala.planner.PlannerTest.testAggregation(), com.cloudera.impala.planner.PlannerTest.testAnalyticFns(), com.cloudera.impala.planner.PlannerTest.testConstant(), com.cloudera.impala.planner.PlannerTest.testDataSourceTables(), com.cloudera.impala.planner.PlannerTest.testDdl(), com.cloudera.impala.planner.PlannerTest.testDistinct(), com.cloudera.impala.planner.PlannerTest.testDistinctEstimate(), com.cloudera.impala.planner.PlannerTest.testEmpty(), com.cloudera.impala.planner.PlannerTest.testHbase(), com.cloudera.impala.planner.PlannerTest.testHdfs(), com.cloudera.impala.planner.PlannerTest.testImplicitJoins(), com.cloudera.impala.planner.PlannerTest.testInlineView(), com.cloudera.impala.planner.PlannerTest.testInlineViewLimit(), com.cloudera.impala.planner.PlannerTest.testInsert(), com.cloudera.impala.planner.PlannerTest.testJoinOrder(), com.cloudera.impala.planner.PlannerTest.testJoins(), com.cloudera.impala.planner.PlannerTest.testLineage(), com.cloudera.impala.planner.PlannerTest.testNestedCollections(), com.cloudera.impala.planner.PlannerTest.testOrder(), com.cloudera.impala.planner.PlannerTest.testOuterJoins(), com.cloudera.impala.planner.PlannerTest.testPredicatePropagation(), com.cloudera.impala.planner.S3PlannerTest.testS3ScanRanges(), com.cloudera.impala.planner.PlannerTest.testSmallQueryOptimization(), com.cloudera.impala.planner.PlannerTest.testSubqueryRewrite(), com.cloudera.impala.planner.PlannerTest.testTopN(), com.cloudera.impala.planner.PlannerTest.testTpcds(), com.cloudera.impala.planner.PlannerTest.testTpch(), com.cloudera.impala.planner.PlannerTest.testUnion(), com.cloudera.impala.planner.PlannerTest.testValues(), com.cloudera.impala.planner.PlannerTest.testViews(), and com.cloudera.impala.planner.PlannerTest.testWithClause().
void com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile (String testFile) inline protected inherited
Definition at line 647 of file PlannerTestBase.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile (String testFile, String dbName) inline protected inherited
Definition at line 651 of file PlannerTestBase.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
static void com.cloudera.impala.planner.PlannerTestBase.setUp () throws Exception inline static inherited
Definition at line 91 of file PlannerTestBase.java.
void com.cloudera.impala.planner.S3PlannerTest.setUpTest () inline
Config property test.fs.s3a.name must be set to the S3 scheme and bucket when running on S3, and otherwise unset. If it is not set, then skip this test. Also remember the scheme://bucket for later.
Definition at line 51 of file S3PlannerTest.java.
References com.cloudera.impala.planner.S3PlannerTest.fsName, and com.cloudera.impala.planner.S3PlannerTest.TEST_FS_S3A_NAME.
void com.cloudera.impala.planner.S3PlannerTest.testS3ScanRanges () inline
Verify that S3 scan ranges are generated correctly.
Definition at line 78 of file S3PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
Member Data Documentation
final Configuration com.cloudera.impala.planner.S3PlannerTest.CONF = new Configuration() private
Definition at line 40 of file S3PlannerTest.java.
Path com.cloudera.impala.planner.S3PlannerTest.fsName private
Definition at line 43 of file S3PlannerTest.java.
Referenced by com.cloudera.impala.planner.S3PlannerTest.cleanseFilePath(), and com.cloudera.impala.planner.S3PlannerTest.setUpTest().
final Path com.cloudera.impala.planner.S3PlannerTest.S3A_CANONICAL_BUCKET = new Path("s3a://bucket") static private
Definition at line 37 of file S3PlannerTest.java.
Referenced by com.cloudera.impala.planner.S3PlannerTest.cleanseFilePath().
final String com.cloudera.impala.planner.S3PlannerTest.TEST_FS_S3A_NAME = "test.fs.s3a.name" static private
Definition at line 34 of file S3PlannerTest.java.
Referenced by com.cloudera.impala.planner.S3PlannerTest.setUpTest().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/planner/S3PlannerTest.java