Impala: impala::NotifiedCounter Class Reference
impala::NotifiedCounter Class Reference
Public Member Functions
NotifiedCounter ()
void Notify (ThreadResourceMgr::ResourcePool *consumer)
int counter () const
Private Attributes
int counter_
Detailed Description
Definition at line 26 of file thread-resource-mgr-test.cc.
Constructor & Destructor Documentation
impala::NotifiedCounter::NotifiedCounter () inline
Definition at line 28 of file thread-resource-mgr-test.cc.
Member Function Documentation
int impala::NotifiedCounter::counter () const inline
Definition at line 37 of file thread-resource-mgr-test.cc.
References counter_.
Referenced by impala::TEST().
void impala::NotifiedCounter::Notify (ThreadResourceMgr::ResourcePool * consumer) inline
Definition at line 31 of file thread-resource-mgr-test.cc.
References counter_, impala::ThreadResourceMgr::ResourcePool::num_threads(), and impala::ThreadResourceMgr::ResourcePool::quota().
Referenced by impala::TEST().
Member Data Documentation
int impala::NotifiedCounter::counter_ private
Definition at line 40 of file thread-resource-mgr-test.cc.
Referenced by counter(), and Notify().
The documentation for this class was generated from the following file:
be/src/runtime/thread-resource-mgr-test.cc