Impala: com.cloudera.impala.service.JniCatalog Class Reference
com.cloudera.impala.service.JniCatalog Class Reference
Public Member Functions
JniCatalog (boolean loadInBackground, int numMetadataLoadingThreads, String sentryServiceConfig, int impalaLogLevel, int otherLogLevel) throws InternalException
byte[] getCatalogObjects (long from_version) throws ImpalaException, TException
long getCatalogVersion ()
byte[] execDdl (byte[] thriftDdlExecReq) throws ImpalaException
byte[] resetMetadata (byte[] thriftResetMetadataReq) throws ImpalaException, TException
byte[] getDbNames (byte[] thriftGetTablesParams) throws ImpalaException, TException
byte[] getTableNames (byte[] thriftGetTablesParams) throws ImpalaException, TException
byte[] getCatalogObject (byte[] thriftParams) throws ImpalaException, TException
byte[] getFunctions (byte[] thriftParams) throws ImpalaException, TException
void prioritizeLoad (byte[] thriftLoadReq) throws ImpalaException, TException
void checkUserSentryAdmin (byte[] thriftReq) throws ImpalaException, TException
byte[] updateCatalog (byte[] thriftUpdateCatalog) throws ImpalaException, TException
Static Public Member Functions
static TUniqueId getServiceId ()
Static Private Member Functions
static TUniqueId generateId ()
Private Attributes
final CatalogServiceCatalog catalog_
final CatalogOpExecutor catalogOpExecutor_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(JniCatalog.class)
static final
TBinaryProtocol.Factory protocolFactory_
static final TUniqueId catalogServiceId_ = generateId()
Detailed Description
JNI-callable interface for the CatalogService. The main point is to serialize and de-serialize thrift structures between C and Java parts of the CatalogService.
Definition at line 59 of file JniCatalog.java.
Constructor & Destructor Documentation
com.cloudera.impala.service.JniCatalog.JniCatalog (boolean loadInBackground, int numMetadataLoadingThreads, String sentryServiceConfig, int impalaLogLevel, int otherLogLevel) throws InternalException inline
Definition at line 74 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.catalog_, com.cloudera.impala.service.JniCatalog.catalogOpExecutor_, and com.cloudera.impala.service.JniCatalog.getServiceId().
Member Function Documentation
void com.cloudera.impala.service.JniCatalog.checkUserSentryAdmin (byte[] thriftReq) throws ImpalaException, TException inline
Verifies whether the user is configured as an admin on the Sentry Service. Throws an AuthorizationException if the user does not have admin privileges or if there were errors communicating with the Sentry Service.
Definition at line 223 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
byte [] com.cloudera.impala.service.JniCatalog.execDdl (byte[] thriftDdlExecReq) throws ImpalaException inline
Executes the given DDL request and returns the result.
Definition at line 123 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
static TUniqueId com.cloudera.impala.service.JniCatalog.generateId () inline static private
Definition at line 69 of file JniCatalog.java.
byte [] com.cloudera.impala.service.JniCatalog.getCatalogObject (byte[] thriftParams) throws ImpalaException, TException inline
Gets the thrift representation of a catalog object.
Definition at line 179 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
byte [] com.cloudera.impala.service.JniCatalog.getCatalogObjects (long from_version) throws ImpalaException, TException inline
Gets all catalog objects
Definition at line 106 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
long com.cloudera.impala.service.JniCatalog.getCatalogVersion () inline
Gets the current catalog version.
Definition at line 116 of file JniCatalog.java.
byte [] com.cloudera.impala.service.JniCatalog.getDbNames (byte[] thriftGetTablesParams) throws ImpalaException, TException inline
Returns a list of table names matching an optional pattern. The argument is a serialized TGetTablesParams object. The return type is a serialized TGetTablesResult object.
Definition at line 150 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
byte [] com.cloudera.impala.service.JniCatalog.getFunctions (byte[] thriftParams) throws ImpalaException, TException inline
See comment in CatalogServiceCatalog.
Definition at line 190 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
static TUniqueId com.cloudera.impala.service.JniCatalog.getServiceId () inline static
Definition at line 101 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.catalogServiceId_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.execDdlRequest(), com.cloudera.impala.service.CatalogOpExecutor.execResetMetadata(), com.cloudera.impala.service.JniCatalog.JniCatalog(), and com.cloudera.impala.service.CatalogOpExecutor.updateCatalog().
byte [] com.cloudera.impala.service.JniCatalog.getTableNames (byte[] thriftGetTablesParams) throws ImpalaException, TException inline
Returns a list of table names matching an optional pattern. The argument is a serialized TGetTablesParams object. The return type is a serialized TGetTablesResult object.
Definition at line 165 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
void com.cloudera.impala.service.JniCatalog.prioritizeLoad (byte[] thriftLoadReq) throws ImpalaException, TException inline
Definition at line 211 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
byte [] com.cloudera.impala.service.JniCatalog.resetMetadata (byte[] thriftResetMetadataReq) throws ImpalaException, TException inline
Execute a reset metadata statement. See comment in CatalogOpExecutor.java.
Definition at line 137 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
byte [] com.cloudera.impala.service.JniCatalog.updateCatalog (byte[] thriftUpdateCatalog) throws ImpalaException, TException inline
Process any updates to the metastore required after a query executes. The argument is a serialized TCatalogUpdate.
Definition at line 235 of file JniCatalog.java.
References com.cloudera.impala.service.JniCatalog.protocolFactory_.
Member Data Documentation
final CatalogServiceCatalog com.cloudera.impala.service.JniCatalog.catalog_ private
Definition at line 63 of file JniCatalog.java.
Referenced by com.cloudera.impala.service.JniCatalog.JniCatalog().
final CatalogOpExecutor com.cloudera.impala.service.JniCatalog.catalogOpExecutor_ private
Definition at line 64 of file JniCatalog.java.
Referenced by com.cloudera.impala.service.JniCatalog.JniCatalog().
final TUniqueId com.cloudera.impala.service.JniCatalog.catalogServiceId_ = generateId() static private
Definition at line 67 of file JniCatalog.java.
Referenced by com.cloudera.impala.service.JniCatalog.getServiceId().
final Logger com.cloudera.impala.service.JniCatalog.LOG = LoggerFactory.getLogger(JniCatalog.class) static private
Definition at line 60 of file JniCatalog.java.
final TBinaryProtocol.Factory com.cloudera.impala.service.JniCatalog.protocolFactory_ static private
Initial value:
=
      new TBinaryProtocol.Factory()
Definition at line 61 of file JniCatalog.java.
Referenced by com.cloudera.impala.service.JniCatalog.checkUserSentryAdmin(), com.cloudera.impala.service.JniCatalog.execDdl(), com.cloudera.impala.service.JniCatalog.getCatalogObject(), com.cloudera.impala.service.JniCatalog.getCatalogObjects(), com.cloudera.impala.service.JniCatalog.getDbNames(), com.cloudera.impala.service.JniCatalog.getFunctions(), com.cloudera.impala.service.JniCatalog.getTableNames(), com.cloudera.impala.service.JniCatalog.prioritizeLoad(), com.cloudera.impala.service.JniCatalog.resetMetadata(), and com.cloudera.impala.service.JniCatalog.updateCatalog().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/service/JniCatalog.java