Impala: impala::DiskIoMgr::RequestRange Class Reference
impala::DiskIoMgr::RequestRange Class Reference
#include <disk-io-mgr.h>
Public Member Functions
hdfsFS fs () const
const char * file () const
int64_t offset () const
int64_t len () const
int disk_id () const
RequestType::type request_type () const
T * Next () const
Returns the Next/Prev node or NULL if this is the end/front.
T * Prev () const
Protected Attributes
hdfsFS fs_
Hadoop filesystem that contains file_, or set to NULL for local filesystem.
std::string file_
Path to file being read or written.
int64_t offset_
Offset within file_ being read or written.
int64_t len_
Length of data read or written.
int disk_id_
Id of disk containing file_;.
RequestType::type request_type_
The type of IO request, READ or WRITE.
Detailed Description
Represents a contiguous sequence of bytes in a single file. This is the common base class for read and write IO requests - ScanRange and WriteRange. Each disk thread processes exactly one RequestRange at a time.
Definition at line 263 of file disk-io-mgr.h.
Member Function Documentation
int impala::DiskIoMgr::RequestRange::disk_id () const inline
Definition at line 269 of file disk-io-mgr.h.
References disk_id_.
Referenced by impala::DiskIoMgr::RequestContext::AddRequestRange(), impala::HdfsParquetScanner::InitColumns(), impala::HdfsTextScanner::IssueInitialRanges(), impala::HdfsParquetScanner::IssueInitialRanges(), impala::BufferedBlockMgr::PinBlock(), impala::HdfsParquetScanner::ProcessFooter(), and impala::DiskIoMgr::RequestContext::ScheduleScanRange().
const char* impala::DiskIoMgr::RequestRange::file () const inline
Definition at line 266 of file disk-io-mgr.h.
References file_.
Referenced by impala::ScannerContext::Stream::filename(), impala::HdfsParquetScanner::InitColumns(), impala::BufferedBlockMgr::PinBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsScanNode::ScannerThread(), impala::HdfsParquetScanner::ValidateColumn(), and impala::DiskIoMgr::Write().
hdfsFS impala::DiskIoMgr::RequestRange::fs () const inline
Definition at line 265 of file disk-io-mgr.h.
References fs_.
Referenced by impala::HdfsParquetScanner::InitColumns(), and impala::HdfsParquetScanner::ProcessFooter().
int64_t impala::DiskIoMgr::RequestRange::len () const inline
Definition at line 268 of file disk-io-mgr.h.
References len_.
Referenced by impala::DiskIoMgr::AddWriteRange(), impala::ScannerContext::Stream::bytes_left(), impala::ScannerContext::Stream::eosr(), impala::BufferedBlockMgr::PinBlock(), impala::DiskIoMgr::Read(), impala::HdfsScanNode::ScannerThread(), and impala::DiskIoMgrTest::ValidateSyncRead().
template<typename T> T* impala::InternalQueue< T >::Node::Next () const inline inherited
Returns the Next/Prev node or NULL if this is the end/front.
Definition at line 48 of file internal-queue.h.
References impala::InternalQueue< T >::lock_, impala::InternalQueue< T >::Node::next, and impala::InternalQueue< T >::Node::parent_queue.
Referenced by impala::TEST(), and impala::BufferedBlockMgr::Validate().
int64_t impala::DiskIoMgr::RequestRange::offset () const inline
Definition at line 267 of file disk-io-mgr.h.
References offset_.
Referenced by impala::DiskIoMgrStress::ClientThread(), impala::ScannerContext::Stream::file_offset(), impala::HdfsTextScanner::FindFirstTuple(), impala::HdfsTextScanner::IssueInitialRanges(), impala::HdfsParquetScanner::IssueInitialRanges(), impala::BufferedBlockMgr::PinBlock(), impala::HdfsScanNode::ScannerThread(), impala::TEST_F(), impala::DiskIoMgrTest::ValidateScanRange(), and impala::DiskIoMgr::WriteRangeHelper().
template<typename T> T* impala::InternalQueue< T >::Node::Prev () const inline inherited
Definition at line 52 of file internal-queue.h.
References impala::InternalQueue< T >::lock_, impala::InternalQueue< T >::Node::parent_queue, and impala::InternalQueue< T >::Node::prev.
Referenced by impala::TEST().
RequestType::type impala::DiskIoMgr::RequestRange::request_type () const inline
Definition at line 270 of file disk-io-mgr.h.
References request_type_.
Referenced by impala::DiskIoMgr::RequestContext::AddRequestRange(), impala::DiskIoMgr::RequestContext::Cancel(), and impala::DiskIoMgr::WorkLoop().
Member Data Documentation
int impala::DiskIoMgr::RequestRange::disk_id_ protected
Id of disk containing file_;.
Definition at line 286 of file disk-io-mgr.h.
Referenced by disk_id(), impala::DiskIoMgr::HandleWriteFinished(), and impala::DiskIoMgr::ValidateScanRange().
std::string impala::DiskIoMgr::RequestRange::file_ protected
Path to file being read or written.
Definition at line 277 of file disk-io-mgr.h.
Referenced by file(), impala::DiskIoMgr::Write(), and impala::DiskIoMgr::WriteRangeHelper().
hdfsFS impala::DiskIoMgr::RequestRange::fs_ protected
Hadoop filesystem that contains file_, or set to NULL for local filesystem.
Definition at line 274 of file disk-io-mgr.h.
Referenced by fs().
int64_t impala::DiskIoMgr::RequestRange::len_ protected
Length of data read or written.
Definition at line 283 of file disk-io-mgr.h.
Referenced by len(), impala::DiskIoMgr::ReadRange(), and impala::DiskIoMgr::WriteRangeHelper().
int64_t impala::DiskIoMgr::RequestRange::offset_ protected
Offset within file_ being read or written.
Definition at line 280 of file disk-io-mgr.h.
Referenced by offset().
RequestType::type impala::DiskIoMgr::RequestRange::request_type_ protected
The type of IO request, READ or WRITE.
Definition at line 289 of file disk-io-mgr.h.
Referenced by request_type(), and impala::DiskIoMgr::ScanRange::ScanRange().
The documentation for this class was generated from the following file:
be/src/runtime/disk-io-mgr.h