Impala: impala::GrowingTest Class Reference
impala::GrowingTest Class Reference
Static Public Member Functions
template<int buffer_size>
static uint64_t AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static void SanityCheck (const HashStore< buffer_size > &hs, uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static uint64_t NextTestCase (int build_tuples, uint64_t prev, int num_tables)
template<int buffer_size>
static void Test ()
template<int buffer_size>
static uint64_t AggregateTest (uint64_t num_probe_tuples, int num_tables)
template<int buffer_size>
static void SanityCheck (const HashStore< buffer_size > &hs, uint64_t num_probe_tuples, int num_tables)
template<int buffer_size>
static uint64_t NextTestCase (uint64_t prev, int num_tables)
template<int buffer_size>
static void Test ()
template<int buffer_size>
static uint64_t AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static void SanityCheck (const HashStore< buffer_size > &hs, uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static uint64_t NextTestCase (int build_tuples, uint64_t prev, int num_tables)
template<int buffer_size>
static void Test ()
template<int buffer_size>
static uint64_t AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static void SanityCheck (const HashStore< buffer_size > &hs, uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static uint64_t NextTestCase (int build_tuples, uint64_t prev, int num_tables)
template<int buffer_size>
static void Test ()
template<int buffer_size>
static uint64_t AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static void SanityCheck (const HashStore< buffer_size > &hs, uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size>
static uint64_t NextTestCase (int build_tuples, uint64_t prev, int num_tables)
template<int buffer_size>
static void Test ()
template<int buffer_size, int streaming_lines>
static uint64_t AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size, int streaming_lines>
static void SanityCheck (const HashStore< buffer_size, streaming_lines > &hs, uint64_t num_probe_tuples, int max_id, int num_tables)
template<int buffer_size, int streaming_lines>
static uint64_t NextTestCase (int build_tuples, uint64_t prev, int num_tables)
template<int buffer_size, int streaming_lines>
static void Test ()
Static Public Attributes
static const uint64_t NUM_PROBE_TUPLES = 100000000
static const int TUPLES_IN_TABLE = (StandardHashTable::NODES / 10) * 8
Detailed Description
Definition at line 18 of file growing-test.cc.
Member Function Documentation
template<int buffer_size> static uint64_t impala::GrowingTest::AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 22 of file growing-test.cc.
References impala::StopWatch::Start(), impala::StopWatch::Stop(), and tuples.
template<int buffer_size> static uint64_t impala::GrowingTest::AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 22 of file growing-test.cc.
References impala::StopWatch::Start(), impala::StopWatch::Stop(), and tuples.
template<int buffer_size> static uint64_t impala::GrowingTest::AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 23 of file growing-test.cc.
References impala::StopWatch::ElapsedTime(), impala::StopWatch::Start(), impala::StopWatch::Stop(), and tuples.
template<int buffer_size, int streaming_lines> static uint64_t impala::GrowingTest::AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 23 of file growing-test.cc.
References impala::StopWatch::ElapsedTime(), impala::StopWatch::Start(), impala::StopWatch::Stop(), and tuples.
template<int buffer_size> static uint64_t impala::GrowingTest::AggregateTest (uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 23 of file growing-test.cc.
References impala::StopWatch::ElapsedTime(), impala::StopWatch::Start(), impala::StopWatch::Stop(), and tuples.
template<int buffer_size> static uint64_t impala::GrowingTest::AggregateTest (uint64_t num_probe_tuples, int num_tables) inline static
Definition at line 33 of file growing-test.cc.
References impala::StopWatch::ElapsedTime(), impala::StopWatch::Start(), impala::StopWatch::Stop(), tuples, and TUPLES_IN_TABLE.
template<int buffer_size> static uint64_t impala::GrowingTest::NextTestCase (int build_tuples, uint64_t prev, int num_tables) inline static
Definition at line 58 of file growing-test.cc.
References NUM_PROBE_TUPLES, and impala::PrettyPrinter::Print().
template<int buffer_size> static uint64_t impala::GrowingTest::NextTestCase (int build_tuples, uint64_t prev, int num_tables) inline static
Definition at line 59 of file growing-test.cc.
References NUM_PROBE_TUPLES, and impala::PrettyPrinter::Print().
template<int buffer_size> static uint64_t impala::GrowingTest::NextTestCase (int build_tuples, uint64_t prev, int num_tables) inline static
Definition at line 59 of file growing-test.cc.
References NUM_PROBE_TUPLES, and impala::PrettyPrinter::Print().
template<int buffer_size, int streaming_lines> static uint64_t impala::GrowingTest::NextTestCase (int build_tuples, uint64_t prev, int num_tables) inline static
Definition at line 60 of file growing-test.cc.
References NUM_PROBE_TUPLES, and impala::PrettyPrinter::Print().
template<int buffer_size> static uint64_t impala::GrowingTest::NextTestCase (int build_tuples, uint64_t prev, int num_tables) inline static
Definition at line 60 of file growing-test.cc.
References NUM_PROBE_TUPLES, and impala::PrettyPrinter::Print().
template<int buffer_size> static uint64_t impala::GrowingTest::NextTestCase (uint64_t prev, int num_tables) inline static
Definition at line 73 of file growing-test.cc.
References NUM_PROBE_TUPLES, impala::PrettyPrinter::Print(), and TUPLES_IN_TABLE.
template<int buffer_size> static void impala::GrowingTest::SanityCheck (const HashStore< buffer_size > & hs, uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 38 of file growing-test.cc.
References Buffer().
template<int buffer_size> static void impala::GrowingTest::SanityCheck (const HashStore< buffer_size > & hs, uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 38 of file growing-test.cc.
References Buffer().
template<int buffer_size, int streaming_lines> static void impala::GrowingTest::SanityCheck (const HashStore< buffer_size, streaming_lines > & hs, uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 39 of file growing-test.cc.
References Buffer().
template<int buffer_size> static void impala::GrowingTest::SanityCheck (const HashStore< buffer_size > & hs, uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 39 of file growing-test.cc.
References Buffer().
template<int buffer_size> static void impala::GrowingTest::SanityCheck (const HashStore< buffer_size > & hs, uint64_t num_probe_tuples, int max_id, int num_tables) inline static
Definition at line 39 of file growing-test.cc.
References Buffer().
template<int buffer_size> static void impala::GrowingTest::SanityCheck (const HashStore< buffer_size > & hs, uint64_t num_probe_tuples, int num_tables) inline static
Definition at line 49 of file growing-test.cc.
References Buffer(), and TUPLES_IN_TABLE.
template<int buffer_size> static void impala::GrowingTest::Test () inline static
Definition at line 78 of file growing-test.cc.
References BUFFER_SIZE, and impala::PrettyPrinter::Print().
template<int buffer_size> static void impala::GrowingTest::Test () inline static
Definition at line 79 of file growing-test.cc.
References BUFFER_SIZE, and impala::PrettyPrinter::Print().
template<int buffer_size> static void impala::GrowingTest::Test () inline static
Definition at line 79 of file growing-test.cc.
References BUFFER_SIZE, and impala::PrettyPrinter::Print().
template<int buffer_size> static void impala::GrowingTest::Test () inline static
Definition at line 80 of file growing-test.cc.
References BUFFER_SIZE, and impala::PrettyPrinter::Print().
template<int buffer_size, int streaming_lines> static void impala::GrowingTest::Test () inline static
Definition at line 80 of file growing-test.cc.
References BUFFER_SIZE, and impala::PrettyPrinter::Print().
template<int buffer_size> static void impala::GrowingTest::Test () inline static
Definition at line 93 of file growing-test.cc.
References BUFFER_SIZE, and impala::PrettyPrinter::Print().
Member Data Documentation
static const uint64_t impala::GrowingTest::NUM_PROBE_TUPLES = 100000000 static
Definition at line 20 of file growing-test.cc.
Referenced by main(), and NextTestCase().
const int impala::GrowingTest::TUPLES_IN_TABLE = (StandardHashTable::NODES / 10) * 8 static
Definition at line 29 of file growing-test.cc.
Referenced by AggregateTest(), NextTestCase(), and SanityCheck().
The documentation for this class was generated from the following file:
be/src/experiments/hashing/growing-test.cc