Impala: CatalogServiceThriftIf Class Reference
CatalogServiceThriftIf Class Reference
Public Member Functions
CatalogServiceThriftIf (CatalogServer *catalog_server)
virtual void ExecDdl (TDdlExecResponse &resp, const TDdlExecRequest &req)
virtual void ResetMetadata (TResetMetadataResponse &resp, const TResetMetadataRequest &req)
virtual void UpdateCatalog (TUpdateCatalogResponse &resp, const TUpdateCatalogRequest &req)
virtual void GetFunctions (TGetFunctionsResponse &resp, const TGetFunctionsRequest &req)
virtual void GetCatalogObject (TGetCatalogObjectResponse &resp, const TGetCatalogObjectRequest &req)
virtual void PrioritizeLoad (TPrioritizeLoadResponse &resp, const TPrioritizeLoadRequest &req)
virtual void SentryAdminCheck (TSentryAdminCheckResponse &resp, const TSentryAdminCheckRequest &req)
Private Attributes
CatalogServer * catalog_server_
Detailed Description
Definition at line 54 of file catalog-server.cc.
Constructor & Destructor Documentation
CatalogServiceThriftIf::CatalogServiceThriftIf (CatalogServer * catalog_server) inline
Definition at line 56 of file catalog-server.cc.
Member Function Documentation
virtual void CatalogServiceThriftIf::ExecDdl (TDdlExecResponse & resp, const TDdlExecRequest & req) inline virtual
Definition at line 61 of file catalog-server.cc.
References impala::Status::GetDetail(), impala::Status::ok(), impala::Status::ToThrift(), and VLOG_RPC.
virtual void CatalogServiceThriftIf::GetCatalogObject (TGetCatalogObjectResponse & resp, const TGetCatalogObjectRequest & req) inline virtual
Definition at line 110 of file catalog-server.cc.
References impala::Status::GetDetail(), impala::Status::ok(), and VLOG_RPC.
virtual void CatalogServiceThriftIf::GetFunctions (TGetFunctionsResponse & resp, const TGetFunctionsRequest & req) inline virtual
Definition at line 98 of file catalog-server.cc.
References impala::Status::GetDetail(), impala::Status::ok(), impala::Status::ToThrift(), and VLOG_RPC.
virtual void CatalogServiceThriftIf::PrioritizeLoad (TPrioritizeLoadResponse & resp, const TPrioritizeLoadRequest & req) inline virtual
Definition at line 122 of file catalog-server.cc.
References impala::Status::GetDetail(), impala::Status::ok(), impala::Status::ToThrift(), and VLOG_RPC.
virtual void CatalogServiceThriftIf::ResetMetadata (TResetMetadataResponse & resp, const TResetMetadataRequest & req) inline virtual
Definition at line 72 of file catalog-server.cc.
References impala::Status::GetDetail(), impala::Status::ok(), impala::Status::ToThrift(), and VLOG_RPC.
virtual void CatalogServiceThriftIf::SentryAdminCheck (TSentryAdminCheckResponse & resp, const TSentryAdminCheckRequest & req) inline virtual
Definition at line 133 of file catalog-server.cc.
References impala::Status::GetDetail(), impala::Status::ok(), impala::Status::ToThrift(), and VLOG_RPC.
virtual void CatalogServiceThriftIf::UpdateCatalog (TUpdateCatalogResponse & resp, const TUpdateCatalogRequest & req) inline virtual
Definition at line 85 of file catalog-server.cc.
References impala::Status::GetDetail(), impala::Status::ok(), impala::Status::ToThrift(), and VLOG_RPC.
Member Data Documentation
CatalogServer* CatalogServiceThriftIf::catalog_server_ private
Definition at line 145 of file catalog-server.cc.
The documentation for this class was generated from the following file:
be/src/catalog/catalog-server.cc