Impala: com.cloudera.impala.analysis.ParserTest Class Reference
com.cloudera.impala.analysis.ParserTest Class Reference
Public Member Functions
Object ParsesOk (String stmt)
void ParserError (String stmt, String expectedErrorString)
void ParserError (String stmt)
void TestNoFromClause ()
void TestSelect ()
void TestAlias ()
void TestStar ()
void TestMultilineComment ()
void TestSinglelineComment ()
void TestPlanHints ()
void TestFromClause ()
void TestWhereClause ()
void TestGroupBy ()
void TestOrderBy ()
void TestHaving ()
void TestLimit ()
void TestOffset ()
void TestUnion ()
void TestValuesStmt () throws AnalysisException
void TestWithClause () throws AnalysisException
void TestNumericLiteralMinMaxValues ()
void TestIdentQuoting ()
void TestLiteralExprs ()
void TestFunctionCallExprs ()
void TestArithmeticExprs ()
void TestTimestampArithmeticExprs ()
void TestCaseExprs ()
void TestCastExprs ()
void TestConditionalExprs ()
void TestAggregateExprs ()
void TestAnalyticExprs ()
void TestPredicates ()
void TestCompoundPredicates ()
void TestBetweenPredicate ()
void TestInPredicate ()
void TestSlotRef ()
void TestInsert ()
void TestUse ()
void TestShow ()
void TestShowCreateTable ()
void TestDescribe ()
void TestCreateDatabase ()
void TestCreateFunction ()
void TestVariadicCreateFunctions ()
void TestCreateAggregate ()
void TestAlterTableAddReplaceColumns ()
void TestAlterTableAddPartition ()
void TestAlterTableDropColumn ()
void TestAlterTableDropPartition ()
void TestAlterTableChangeColumn ()
void TestAlterTableSet ()
void TestAlterTableOrViewRename ()
void TestCreateTable ()
void TestCreateDataSource ()
void TestDropDataSource ()
void TestCreateView ()
void TestAlterView ()
void TestCreateTableAsSelect ()
void TestDrop ()
void TestLoadData ()
void TestTypes ()
void TestResetMetadata ()
void TestComputeDropStats ()
void TestGetErrorMsg ()
void TestExplain ()
void TestSubqueries ()
void TestSet ()
void TestCreateDropRole ()
void TestGrantRevokeRole ()
void TestGrantRevokePrivilege ()
void TestShowRoles ()
void TestShowGrantRole ()
void TestComputeStats ()
void TestComputeStatsIncremental ()
void TestSemiColon ()
Package Functions
public< C extends Expr > Object ParsesOk (String selectStmtSql, Class< C > cl)
Private Member Functions
void TestJoinHints (String stmt, String...expectedHints)
void TestSelectListHints (String stmt, String...expectedHints)
void TestInsertHints (String stmt, String...expectedHints)
void testStringLiteral (String s)
void testCompoundPredicates (String andStr, String orStr, String notStr)
void testLiteralTruthValues (String andStr, String orStr, String notStr)
void testInsert ()
void TypeDefsParseOk (String...typeDefs)
void TypeDefsError (String...typeDefs)
Static Private Attributes
static final String[] operands_
Detailed Description
Definition at line 34 of file ParserTest.java.
Member Function Documentation
void com.cloudera.impala.analysis.ParserTest.ParserError (String stmt, String expectedErrorString) inline
Asserts if stmt parses fine or the error string doesn't match and it is non-null.
Definition at line 81 of file ParserTest.java.
References gen_ir_descriptions.parser.
Referenced by com.cloudera.impala.analysis.ParserTest.ParserError(), com.cloudera.impala.analysis.ParserTest.TestAlias(), com.cloudera.impala.analysis.ParserTest.TestAlterTableAddPartition(), com.cloudera.impala.analysis.ParserTest.TestAlterTableAddReplaceColumns(), com.cloudera.impala.analysis.ParserTest.TestAlterTableChangeColumn(), com.cloudera.impala.analysis.ParserTest.TestAlterTableDropColumn(), com.cloudera.impala.analysis.ParserTest.TestAlterTableDropPartition(), com.cloudera.impala.analysis.ParserTest.TestAlterTableOrViewRename(), com.cloudera.impala.analysis.ParserTest.TestAlterTableSet(), com.cloudera.impala.analysis.ParserTest.TestAlterView(), com.cloudera.impala.analysis.ParserTest.TestAnalyticExprs(), com.cloudera.impala.analysis.ParserTest.TestArithmeticExprs(), com.cloudera.impala.analysis.ParserTest.TestBetweenPredicate(), com.cloudera.impala.analysis.ParserTest.TestCaseExprs(), com.cloudera.impala.analysis.ParserTest.TestCastExprs(), com.cloudera.impala.analysis.ParserTest.testCompoundPredicates(), com.cloudera.impala.analysis.ParserTest.TestComputeDropStats(), com.cloudera.impala.analysis.ParserTest.TestComputeStats(), com.cloudera.impala.analysis.ParserTest.TestComputeStatsIncremental(), com.cloudera.impala.analysis.ParserTest.TestConditionalExprs(), com.cloudera.impala.analysis.ParserTest.TestCreateAggregate(), com.cloudera.impala.analysis.ParserTest.TestCreateDatabase(), com.cloudera.impala.analysis.ParserTest.TestCreateDataSource(), com.cloudera.impala.analysis.ParserTest.TestCreateDropRole(), com.cloudera.impala.analysis.ParserTest.TestCreateFunction(), com.cloudera.impala.analysis.ParserTest.TestCreateTable(), com.cloudera.impala.analysis.ParserTest.TestCreateTableAsSelect(), com.cloudera.impala.analysis.ParserTest.TestCreateView(), com.cloudera.impala.analysis.ParserTest.TestDescribe(), com.cloudera.impala.analysis.ParserTest.TestDrop(), com.cloudera.impala.analysis.ParserTest.TestDropDataSource(), com.cloudera.impala.analysis.ParserTest.TestExplain(), com.cloudera.impala.analysis.ParserTest.TestFromClause(), com.cloudera.impala.analysis.ParserTest.TestFunctionCallExprs(), com.cloudera.impala.analysis.ParserTest.TestGetErrorMsg(), com.cloudera.impala.analysis.ParserTest.TestGrantRevokePrivilege(), com.cloudera.impala.analysis.ParserTest.TestGrantRevokeRole(), com.cloudera.impala.analysis.ParserTest.TestGroupBy(), com.cloudera.impala.analysis.ParserTest.TestHaving(), com.cloudera.impala.analysis.ParserTest.TestIdentQuoting(), com.cloudera.impala.analysis.ParserTest.TestInPredicate(), com.cloudera.impala.analysis.ParserTest.testInsert(), com.cloudera.impala.analysis.ParserTest.TestInsert(), com.cloudera.impala.analysis.ParserTest.TestLimit(), com.cloudera.impala.analysis.ParserTest.TestLiteralExprs(), com.cloudera.impala.analysis.ParserTest.TestLoadData(), com.cloudera.impala.analysis.ParserTest.TestMultilineComment(), com.cloudera.impala.analysis.ParserTest.TestNoFromClause(), com.cloudera.impala.analysis.ParserTest.TestOffset(), com.cloudera.impala.analysis.ParserTest.TestOrderBy(), com.cloudera.impala.analysis.ParserTest.TestPlanHints(), com.cloudera.impala.analysis.ParserTest.TestResetMetadata(), com.cloudera.impala.analysis.ParserTest.TestSelect(), com.cloudera.impala.analysis.ParserTest.TestSemiColon(), com.cloudera.impala.analysis.ParserTest.TestSet(), com.cloudera.impala.analysis.ParserTest.TestShow(), com.cloudera.impala.analysis.ParserTest.TestShowCreateTable(), com.cloudera.impala.analysis.ParserTest.TestShowGrantRole(), com.cloudera.impala.analysis.ParserTest.TestShowRoles(), com.cloudera.impala.analysis.ParserTest.TestSinglelineComment(), com.cloudera.impala.analysis.ParserTest.TestStar(), com.cloudera.impala.analysis.ParserTest.TestSubqueries(), com.cloudera.impala.analysis.ParserTest.TestTimestampArithmeticExprs(), com.cloudera.impala.analysis.ParserTest.TestUnion(), com.cloudera.impala.analysis.ParserTest.TestUse(), com.cloudera.impala.analysis.ParserTest.TestValuesStmt(), com.cloudera.impala.analysis.ParserTest.TestVariadicCreateFunctions(), com.cloudera.impala.analysis.ParserTest.TestWhereClause(), com.cloudera.impala.analysis.ParserTest.TestWithClause(), and com.cloudera.impala.analysis.ParserTest.TypeDefsError().
void com.cloudera.impala.analysis.ParserTest.ParserError (String stmt) inline
Asserts if stmt parses fine.
Parameters
stmt
Definition at line 101 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError().
Object com.cloudera.impala.analysis.ParserTest.ParsesOk (String stmt) inline
Asserts in case of parser error.
Definition at line 43 of file ParserTest.java.
References gen_ir_descriptions.parser.
Referenced by com.cloudera.impala.analysis.ParserTest.ParsesOk(), com.cloudera.impala.analysis.ParserTest.TestAggregateExprs(), com.cloudera.impala.analysis.ParserTest.TestAlias(), com.cloudera.impala.analysis.ParserTest.TestAlterTableAddPartition(), com.cloudera.impala.analysis.ParserTest.TestAlterTableAddReplaceColumns(), com.cloudera.impala.analysis.ParserTest.TestAlterTableChangeColumn(), com.cloudera.impala.analysis.ParserTest.TestAlterTableDropColumn(), com.cloudera.impala.analysis.ParserTest.TestAlterTableDropPartition(), com.cloudera.impala.analysis.ParserTest.TestAlterTableOrViewRename(), com.cloudera.impala.analysis.ParserTest.TestAlterTableSet(), com.cloudera.impala.analysis.ParserTest.TestAlterView(), com.cloudera.impala.analysis.ParserTest.TestAnalyticExprs(), com.cloudera.impala.analysis.ParserTest.TestArithmeticExprs(), com.cloudera.impala.analysis.ParserTest.TestBetweenPredicate(), com.cloudera.impala.analysis.ParserTest.TestCaseExprs(), com.cloudera.impala.analysis.ParserTest.TestCastExprs(), com.cloudera.impala.analysis.ParserTest.testCompoundPredicates(), com.cloudera.impala.analysis.ParserTest.TestCompoundPredicates(), com.cloudera.impala.analysis.ParserTest.TestComputeDropStats(), com.cloudera.impala.analysis.ParserTest.TestComputeStats(), com.cloudera.impala.analysis.ParserTest.TestComputeStatsIncremental(), com.cloudera.impala.analysis.ParserTest.TestConditionalExprs(), com.cloudera.impala.analysis.ParserTest.TestCreateAggregate(), com.cloudera.impala.analysis.ParserTest.TestCreateDatabase(), com.cloudera.impala.analysis.ParserTest.TestCreateDataSource(), com.cloudera.impala.analysis.ParserTest.TestCreateDropRole(), com.cloudera.impala.analysis.ParserTest.TestCreateFunction(), com.cloudera.impala.analysis.ParserTest.TestCreateTable(), com.cloudera.impala.analysis.ParserTest.TestCreateTableAsSelect(), com.cloudera.impala.analysis.ParserTest.TestCreateView(), com.cloudera.impala.analysis.ParserTest.TestDescribe(), com.cloudera.impala.analysis.ParserTest.TestDrop(), com.cloudera.impala.analysis.ParserTest.TestDropDataSource(), com.cloudera.impala.analysis.ParserTest.TestExplain(), com.cloudera.impala.analysis.ParserTest.TestFromClause(), com.cloudera.impala.analysis.ParserTest.TestFunctionCallExprs(), com.cloudera.impala.analysis.ParserTest.TestGrantRevokePrivilege(), com.cloudera.impala.analysis.ParserTest.TestGrantRevokeRole(), com.cloudera.impala.analysis.ParserTest.TestGroupBy(), com.cloudera.impala.analysis.ParserTest.TestHaving(), com.cloudera.impala.analysis.ParserTest.TestIdentQuoting(), com.cloudera.impala.analysis.ParserTest.TestInPredicate(), com.cloudera.impala.analysis.ParserTest.testInsert(), com.cloudera.impala.analysis.ParserTest.TestInsertHints(), com.cloudera.impala.analysis.ParserTest.TestJoinHints(), com.cloudera.impala.analysis.ParserTest.TestLimit(), com.cloudera.impala.analysis.ParserTest.TestLiteralExprs(), com.cloudera.impala.analysis.ParserTest.testLiteralTruthValues(), com.cloudera.impala.analysis.ParserTest.TestLoadData(), com.cloudera.impala.analysis.ParserTest.TestMultilineComment(), com.cloudera.impala.analysis.ParserTest.TestNoFromClause(), com.cloudera.impala.analysis.ParserTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.analysis.ParserTest.TestOffset(), com.cloudera.impala.analysis.ParserTest.TestOrderBy(), com.cloudera.impala.analysis.ParserTest.TestPredicates(), com.cloudera.impala.analysis.ParserTest.TestResetMetadata(), com.cloudera.impala.analysis.ParserTest.TestSelect(), com.cloudera.impala.analysis.ParserTest.TestSelectListHints(), com.cloudera.impala.analysis.ParserTest.TestSemiColon(), com.cloudera.impala.analysis.ParserTest.TestSet(), com.cloudera.impala.analysis.ParserTest.TestShow(), com.cloudera.impala.analysis.ParserTest.TestShowCreateTable(), com.cloudera.impala.analysis.ParserTest.TestShowGrantRole(), com.cloudera.impala.analysis.ParserTest.TestShowRoles(), com.cloudera.impala.analysis.ParserTest.TestSinglelineComment(), com.cloudera.impala.analysis.ParserTest.TestSlotRef(), com.cloudera.impala.analysis.ParserTest.TestStar(), com.cloudera.impala.analysis.ParserTest.testStringLiteral(), com.cloudera.impala.analysis.ParserTest.TestSubqueries(), com.cloudera.impala.analysis.ParserTest.TestTimestampArithmeticExprs(), com.cloudera.impala.analysis.ParserTest.TestUnion(), com.cloudera.impala.analysis.ParserTest.TestUse(), com.cloudera.impala.analysis.ParserTest.TestValuesStmt(), com.cloudera.impala.analysis.ParserTest.TestVariadicCreateFunctions(), com.cloudera.impala.analysis.ParserTest.TestWhereClause(), com.cloudera.impala.analysis.ParserTest.TestWithClause(), and com.cloudera.impala.analysis.ParserTest.TypeDefsParseOk().
public<C extends Expr> Object com.cloudera.impala.analysis.ParserTest.ParsesOk (String selectStmtSql, Class< C > cl) inline package
Attempts to parse the given select statement, and asserts in case of parser error. Also asserts that the first select-list expression is of given class.
Definition at line 62 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAggregateExprs () inline
Definition at line 1166 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlias () inline
Tests table and column aliases which can specified as identifiers (quoted or unquoted) or string literals (single or double quoted).
Definition at line 132 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterTableAddPartition () inline
Definition at line 1758 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterTableAddReplaceColumns () inline
Definition at line 1728 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterTableChangeColumn () inline
Definition at line 1844 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterTableDropColumn () inline
Definition at line 1803 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterTableDropPartition () inline
Definition at line 1821 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterTableOrViewRename () inline
Definition at line 1925 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterTableSet () inline
Definition at line 1861 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAlterView () inline
Definition at line 2231 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestAnalyticExprs () inline
Definition at line 1186 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestArithmeticExprs () inline
Definition at line 1044 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.operands_, com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestBetweenPredicate () inline
Definition at line 1316 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCaseExprs () inline
Definition at line 1127 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCastExprs () inline
Definition at line 1148 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.testCompoundPredicates (String andStr, String orStr, String notStr) inline private
Definition at line 1240 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestCompoundPredicates().
void com.cloudera.impala.analysis.ParserTest.TestCompoundPredicates () inline
Definition at line 1286 of file ParserTest.java.
References com.cloudera.impala.analysis.CompoundPredicate.getOp(), com.cloudera.impala.analysis.ParserTest.ParsesOk(), com.cloudera.impala.analysis.ParserTest.testCompoundPredicates(), and com.cloudera.impala.analysis.ParserTest.testLiteralTruthValues().
void com.cloudera.impala.analysis.ParserTest.TestComputeDropStats () inline
Definition at line 2443 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestComputeStats () inline
Definition at line 2869 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestComputeStatsIncremental () inline
Definition at line 2877 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestConditionalExprs () inline
Definition at line 1156 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateAggregate () inline
Definition at line 1690 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateDatabase () inline
Definition at line 1591 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateDataSource () inline
Definition at line 2136 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateDropRole () inline
Definition at line 2749 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateFunction () inline
Definition at line 1626 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateTable () inline
Definition at line 1940 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateTableAsSelect () inline
Definition at line 2260 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestCreateView () inline
Definition at line 2185 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestDescribe () inline
Definition at line 1576 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestDrop () inline
Definition at line 2287 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestDropDataSource () inline
Definition at line 2175 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestExplain () inline
Definition at line 2612 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestFromClause () inline
Definition at line 434 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestFunctionCallExprs () inline
Definition at line 1032 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestGetErrorMsg () inline
Definition at line 2464 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError().
void com.cloudera.impala.analysis.ParserTest.TestGrantRevokePrivilege () inline
Definition at line 2775 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestGrantRevokeRole () inline
Definition at line 2762 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestGroupBy () inline
Definition at line 522 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestHaving () inline
Definition at line 564 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestIdentQuoting () inline
Definition at line 843 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestInPredicate () inline
Definition at line 1345 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.testInsert () inline private
Run positive tests for INSERT INTO/OVERWRITE.
Definition at line 1375 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestInsert().
void com.cloudera.impala.analysis.ParserTest.TestInsert () inline
Definition at line 1452 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.testInsert().
void com.cloudera.impala.analysis.ParserTest.TestInsertHints (String stmt, String... expectedHints) inline private
Parses stmt and checks that the insert hints stmt are the expected hints.
Definition at line 276 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestPlanHints().
void com.cloudera.impala.analysis.ParserTest.TestJoinHints (String stmt, String... expectedHints) inline private
Parses stmt and checks that the all table refs in stmt have the expected join hints. The expectedHints contains the hints of all table refs from left to right (starting with the second tableRef because the first one cannot have hints).
Definition at line 249 of file ParserTest.java.
References com.cloudera.impala.analysis.SelectStmt.getTableRefs(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestPlanHints().
void com.cloudera.impala.analysis.ParserTest.TestLimit () inline
Definition at line 580 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestLiteralExprs () inline
Definition at line 908 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), com.cloudera.impala.analysis.ParserTest.ParsesOk(), and com.cloudera.impala.analysis.ParserTest.testStringLiteral().
void com.cloudera.impala.analysis.ParserTest.testLiteralTruthValues (String andStr, String orStr, String notStr) inline private
Definition at line 1271 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestCompoundPredicates().
void com.cloudera.impala.analysis.ParserTest.TestLoadData () inline
Definition at line 2335 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestMultilineComment () inline
Various test cases for (multiline) C-style comments.
Definition at line 183 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestNoFromClause () inline
Definition at line 106 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestNumericLiteralMinMaxValues () inline
Definition at line 804 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestOffset () inline
Definition at line 596 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestOrderBy () inline
Definition at line 533 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestPlanHints () inline
Definition at line 284 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), com.cloudera.impala.analysis.ParserTest.TestInsertHints(), com.cloudera.impala.analysis.ParserTest.TestJoinHints(), and com.cloudera.impala.analysis.ParserTest.TestSelectListHints().
void com.cloudera.impala.analysis.ParserTest.TestPredicates () inline
Definition at line 1217 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.operands_, and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestResetMetadata () inline
Definition at line 2429 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestSelect () inline
Definition at line 117 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestSelectListHints (String stmt, String... expectedHints) inline private
Parses stmt and checks that the select-list plan hints in stmt are the expected hints.
Definition at line 266 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestPlanHints().
void com.cloudera.impala.analysis.ParserTest.TestSemiColon () inline
Definition at line 2894 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestSet () inline
Definition at line 2727 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestShow () inline
Definition at line 1498 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestShowCreateTable () inline
Definition at line 1568 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestShowGrantRole () inline
Definition at line 2850 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestShowRoles () inline
Definition at line 2838 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestSinglelineComment () inline
Various test cases for one line comment style (starts with –).
Definition at line 228 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestSlotRef () inline
Definition at line 1365 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestStar () inline
Definition at line 164 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.testStringLiteral (String s) inline private
Definition at line 1024 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestLiteralExprs().
void com.cloudera.impala.analysis.ParserTest.TestSubqueries () inline
Definition at line 2623 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestTimestampArithmeticExprs () inline
We have three variants of timestamp arithmetic exprs, as in MySQL: http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html (section #function_date-add)
Non-function-call like version, e.g., 'a + interval b timeunit'
Beginning with an interval (only for '+'), e.g., 'interval b timeunit + a'
Function-call like version, e.g., date_add(a, interval b timeunit)
Definition at line 1080 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestTypes () inline
Definition at line 2378 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.TypeDefsError(), and com.cloudera.impala.analysis.ParserTest.TypeDefsParseOk().
void com.cloudera.impala.analysis.ParserTest.TestUnion () inline
Definition at line 611 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestUse () inline
Definition at line 1491 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestValuesStmt () throws AnalysisException inline
Definition at line 713 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestVariadicCreateFunctions () inline
Definition at line 1674 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestWhereClause () inline
Definition at line 504 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TestWithClause () throws AnalysisException inline
Definition at line 751 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError(), and com.cloudera.impala.analysis.ParserTest.ParsesOk().
void com.cloudera.impala.analysis.ParserTest.TypeDefsError (String... typeDefs) inline private
Asserts that the given typeDefs fail to parse.
Definition at line 2370 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParserError().
Referenced by com.cloudera.impala.analysis.ParserTest.TestTypes().
void com.cloudera.impala.analysis.ParserTest.TypeDefsParseOk (String... typeDefs) inline private
Wraps the given typeDefs in a CREATE TABLE and CAST and runs ParsesOk(). Also tests that the type is parsed correctly in ARRAY, MAP, and STRUCT types.
Definition at line 2356 of file ParserTest.java.
References com.cloudera.impala.analysis.ParserTest.ParsesOk().
Referenced by com.cloudera.impala.analysis.ParserTest.TestTypes().
Member Data Documentation
final String [] com.cloudera.impala.analysis.ParserTest.operands_ static private
Initial value:
=
      new String[] {"i", "5", "true", "NULL", "'a'", "(1.5 * 8)" }
Definition at line 37 of file ParserTest.java.
Referenced by com.cloudera.impala.analysis.ParserTest.TestArithmeticExprs(), and com.cloudera.impala.analysis.ParserTest.TestPredicates().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/analysis/ParserTest.java