Impala: impala::BufferBuilder Class Reference
impala::BufferBuilder Class Reference
Utility class to build an in-memory buffer.
#include <buffer-builder.h>
Public Member Functions
BufferBuilder (uint8_t *dst_buffer, int dst_len)
BufferBuilder (char *dst_buffer, int dst_len)
void Append (const void *buffer, int len)
template<typename T >
void Append (const T &v)
int capacity () const
int size () const
Private Attributes
uint8_t * buffer_
int capacity_
int size_
Detailed Description
Utility class to build an in-memory buffer.
Definition at line 25 of file buffer-builder.h.
Constructor & Destructor Documentation
impala::BufferBuilder::BufferBuilder (uint8_t * dst_buffer, int dst_len) inline
Definition at line 27 of file buffer-builder.h.
impala::BufferBuilder::BufferBuilder (char * dst_buffer, int dst_len) inline
Definition at line 31 of file buffer-builder.h.
Member Function Documentation
void impala::BufferBuilder::Append (const void * buffer, int len) inline
Definition at line 36 of file buffer-builder.h.
References buffer_, capacity_, and size_.
Referenced by Append(), and impala::HdfsParquetTableWriter::BaseColumnWriter::FinalizeCurrentPage().
template<typename T > void impala::BufferBuilder::Append (const T & v) inline
Definition at line 43 of file buffer-builder.h.
References Append().
int impala::BufferBuilder::capacity () const inline
Definition at line 47 of file buffer-builder.h.
References capacity_.
Referenced by impala::HdfsParquetTableWriter::BaseColumnWriter::FinalizeCurrentPage().
int impala::BufferBuilder::size () const inline
Definition at line 48 of file buffer-builder.h.
References size_.
Referenced by impala::HdfsParquetTableWriter::BaseColumnWriter::FinalizeCurrentPage().
Member Data Documentation
uint8_t* impala::BufferBuilder::buffer_ private
Definition at line 51 of file buffer-builder.h.
Referenced by Append().
int impala::BufferBuilder::capacity_ private
Definition at line 52 of file buffer-builder.h.
Referenced by Append(), and capacity().
int impala::BufferBuilder::size_ private
Definition at line 53 of file buffer-builder.h.
Referenced by Append(), and size().
The documentation for this class was generated from the following file:
be/src/util/buffer-builder.h