Impala: com.cloudera.impala.planner.SortNode Class Reference
com.cloudera.impala.planner.SortNode Class Reference
Public Member Functions
SortNode (PlanNodeId id, PlanNode input, SortInfo info, boolean useTopN, long offset)
long getOffset ()
void setOffset (long offset)
boolean hasOffset ()
boolean useTopN ()
SortInfo getSortInfo ()
void setInputPartition (DataPartition inputPartition)
DataPartition getInputPartition ()
boolean isAnalyticSort ()
void setIsAnalyticSort (boolean v)
boolean isBlockingNode ()
void init (Analyzer analyzer) throws InternalException
void computeCosts (TQueryOptions queryOptions)
PlanNodeId getId ()
void setId (PlanNodeId id)
long getLimit ()
boolean hasLimit ()
long getPerHostMemCost ()
long getCardinality ()
int getNumNodes ()
float getAvgRowSize ()
void setFragment (PlanFragment fragment)
PlanFragment getFragment ()
List< Expr > getConjuncts ()
ExprSubstitutionMap getOutputSmap ()
void setOutputSmap (ExprSubstitutionMap smap)
Set< ExprId > getAssignedConjuncts ()
void setAssignedConjuncts (Set< ExprId > conjuncts)
void setLimit (long limit)
void unsetLimit ()
ArrayList< TupleId > getTupleIds ()
ArrayList< TupleId > getTblRefIds ()
void setTblRefIds (ArrayList< TupleId > ids)
Set< TupleId > getNullableTupleIds ()
void addConjuncts (List< Expr > conjuncts)
void transferConjuncts (PlanNode recipient)
String getExplainString ()
TPlan treeToThrift ()
long getInputCardinality ()
Static Public Member Functions
static long addCardinalities (long a, long b)
static long multiplyCardinalities (long a, long b)
Protected Member Functions
void computeStats (Analyzer analyzer)
String debugString ()
void toThrift (TPlanNode msg)
String getNodeExplainString (String prefix, String detailPrefix, TExplainLevel detailLevel)
String getOffsetExplainString (String prefix)
final String getExplainString (String rootPrefix, String prefix, TExplainLevel detailLevel)
String getExplainString (List<?extends Expr > exprs)
void setDisplayName (String s)
final String getDisplayLabel ()
String getDisplayLabelDetail ()
void assignConjuncts (Analyzer analyzer)
ExprSubstitutionMap getCombinedChildSmap ()
void createDefaultSmap (Analyzer analyzer)
long capAtLimit (long cardinality)
void markSlotsMaterialized (Analyzer analyzer, List< Expr > exprs)
void computeMemLayout (Analyzer analyzer)
double computeSelectivity ()
boolean hasValidStats ()
Protected Attributes
long offset_
String displayName_
PlanNodeId id_
long limit_
ArrayList< TupleId > tupleIds_
ArrayList< TupleId > tblRefIds_
Set< TupleId > nullableTupleIds_ = Sets.newHashSet()
List< Expr > conjuncts_ = Lists.newArrayList()
PlanFragment fragment_
ExprSubstitutionMap outputSmap_
Set< ExprId > assignedConjuncts_
long cardinality_
int numNodes_
float avgRowSize_
long perHostMemCost_ = -1
Static Protected Attributes
static final int DEFAULT_BATCH_SIZE = 1024
Private Member Functions
String getNodeExplainDetail (TExplainLevel detailLevel)
Static Private Member Functions
static String getDisplayName (boolean isTopN, boolean isMergeOnly)
Private Attributes
final SortInfo info_
DataPartition inputPartition_
boolean isAnalyticSort_
List< Expr > resolvedTupleExprs_
final boolean useTopN_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(SortNode.class)
Detailed Description
Node that implements a sort with or without a limit. useTopN_ is true for sorts with limits that are implemented by a TopNNode in the backend. SortNode is used otherwise. Will always materialize the new tuple info_.sortTupleDesc_.
Definition at line 47 of file SortNode.java.
Constructor & Destructor Documentation
com.cloudera.impala.planner.SortNode.SortNode (PlanNodeId id, PlanNode input, SortInfo info, boolean useTopN, long offset) inline
Definition at line 65 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.getDisplayName(), com.cloudera.impala.analysis.SortInfo.getSortTupleDescriptor(), com.cloudera.impala.planner.SortNode.info_, offset, com.cloudera.impala.planner.SortNode.offset_, com.cloudera.impala.planner.SortNode.useTopN(), and com.cloudera.impala.planner.SortNode.useTopN_.
Member Function Documentation
static long com.cloudera.impala.planner.PlanNode.addCardinalities (long a, long b) inline static inherited
Computes and returns the sum of two cardinalities. If an overflow occurs, the maximum Long value is returned (Long.MAX_VALUE).
Definition at line 528 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), and com.cloudera.impala.planner.PlanNode.getInputCardinality().
void com.cloudera.impala.planner.PlanNode.addConjuncts (List< Expr > conjuncts) inline inherited
Definition at line 209 of file PlanNode.java.
void com.cloudera.impala.planner.PlanNode.assignConjuncts (Analyzer analyzer) inline protected inherited
Assign remaining unassigned conjuncts.
Definition at line 401 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.init().
long com.cloudera.impala.planner.PlanNode.capAtLimit (long cardinality) inline protected inherited
Definition at line 450 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.hasLimit(), and com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.SortNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), and com.cloudera.impala.planner.HdfsScanNode.computeStats().
void com.cloudera.impala.planner.SortNode.computeCosts (TQueryOptions queryOptions) inline
Definition at line 199 of file SortNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_, com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.analysis.SortInfo.getSortTupleDescriptor(), com.cloudera.impala.planner.PlanNode.hasValidStats(), com.cloudera.impala.planner.SortNode.info_, com.cloudera.impala.planner.SortNode.offset_, com.cloudera.impala.planner.PlanNode.perHostMemCost_, and com.cloudera.impala.planner.SortNode.useTopN_.
void com.cloudera.impala.planner.PlanNode.computeMemLayout (Analyzer analyzer) inline protected inherited
Call computeMemLayout() for all materialized tuples.
Definition at line 475 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tupleIds_.
Referenced by com.cloudera.impala.planner.EmptySetNode.init(), com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), and com.cloudera.impala.planner.UnionNode.init().
double com.cloudera.impala.planner.PlanNode.computeSelectivity () inline protected inherited
Compute the product of the selectivies of all conjuncts.
Definition at line 484 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
Referenced by com.cloudera.impala.planner.SelectNode.computeStats(), com.cloudera.impala.planner.CrossJoinNode.computeStats(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), and com.cloudera.impala.planner.HdfsScanNode.computeStats().
void com.cloudera.impala.planner.SortNode.computeStats (Analyzer analyzer) inline protected
Definition at line 127 of file SortNode.java.
References com.cloudera.impala.planner.PlanNode.capAtLimit(), and com.cloudera.impala.planner.PlanNode.cardinality_.
Referenced by com.cloudera.impala.planner.SortNode.init().
void com.cloudera.impala.planner.PlanNode.createDefaultSmap (Analyzer analyzer) inline protected inherited
Sets outputSmap_ to compose(existing smap, combined child smap). Also substitutes conjuncts_ using the combined child smap.
Definition at line 425 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_, com.cloudera.impala.planner.PlanNode.getCombinedChildSmap(), and com.cloudera.impala.planner.PlanNode.outputSmap_.
Referenced by com.cloudera.impala.planner.SelectNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.init().
String com.cloudera.impala.planner.SortNode.debugString () inline protected
Definition at line 134 of file SortNode.java.
References com.cloudera.impala.analysis.Expr.debugString(), com.cloudera.impala.analysis.SortInfo.getIsAscOrder(), com.cloudera.impala.analysis.SortInfo.getOrderingExprs(), com.cloudera.impala.planner.SortNode.info_, and com.cloudera.impala.planner.SortNode.offset_.
Set<ExprId> com.cloudera.impala.planner.PlanNode.getAssignedConjuncts () inline inherited
Definition at line 180 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.assignedConjuncts_.
float com.cloudera.impala.planner.PlanNode.getAvgRowSize () inline inherited
Definition at line 174 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), and com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan().
long com.cloudera.impala.planner.PlanNode.getCardinality () inline inherited
Definition at line 172 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan(), and com.cloudera.impala.planner.SingleNodePlanner.createJoinPlan().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.getCombinedChildSmap () inline protected inherited
Returns an smap that combines the childrens' smaps.
Definition at line 410 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.HashJoinNode.init().
List<Expr> com.cloudera.impala.planner.PlanNode.getConjuncts () inline inherited
Definition at line 177 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
Referenced by com.cloudera.impala.planner.ScanNode.getInputCardinality().
final String com.cloudera.impala.planner.PlanNode.getDisplayLabel () inline protected inherited
Definition at line 225 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.displayName_.
Referenced by com.cloudera.impala.planner.ExchangeNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
String com.cloudera.impala.planner.PlanNode.getDisplayLabelDetail () inline protected inherited
Subclasses can override to provide a node specific detail string that is displayed to the user. e.g. scan can return the table name.
Definition at line 234 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
static String com.cloudera.impala.planner.SortNode.getDisplayName (boolean isTopN, boolean isMergeOnly) inline static private
Definition at line 230 of file SortNode.java.
Referenced by com.cloudera.impala.planner.SortNode.SortNode().
String com.cloudera.impala.planner.PlanNode.getExplainString () inline inherited
Definition at line 219 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.getDisplayLabelDetail(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), and com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString().
final String com.cloudera.impala.planner.PlanNode.getExplainString (String rootPrefix, String prefix, TExplainLevel detailLevel) inline protected inherited
Generate the explain plan tree. The plan will be in the form of:
root | |-—child 3 | limit:1 | |-—child 2 | limit:2 | child 1
The root node header line will be prefixed by rootPrefix and the remaining plan output will be prefixed by prefix.
Definition at line 252 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_, com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getNodeExplainString(), com.cloudera.impala.planner.PlanNode.getOffsetExplainString(), com.cloudera.impala.planner.PlanNode.limit_, com.cloudera.impala.planner.PlanNode.numNodes_, com.cloudera.impala.planner.PlanNode.perHostMemCost_, and com.cloudera.impala.planner.PlanNode.tupleIds_.
String com.cloudera.impala.planner.PlanNode.getExplainString (List<?extends Expr > exprs) inline protected inherited
Definition at line 506 of file PlanNode.java.
PlanFragment com.cloudera.impala.planner.PlanNode.getFragment () inline inherited
Definition at line 176 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.fragment_.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), and com.cloudera.impala.planner.PipelinedPlanNodeSet.computePlanNodeSets().
PlanNodeId com.cloudera.impala.planner.PlanNode.getId () inline inherited
Definition at line 164 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.id_.
Referenced by com.cloudera.impala.planner.DataStreamSink.getExplainString(), com.cloudera.impala.planner.AggregationNode.init(), and com.cloudera.impala.planner.DataStreamSink.toThrift().
long com.cloudera.impala.planner.PlanNode.getInputCardinality () inline inherited
The input cardinality is the sum of output cardinalities of its children. For scan nodes the input cardinality is the expected number of rows scanned.
Definition at line 570 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.addCardinalities().
DataPartition com.cloudera.impala.planner.SortNode.getInputPartition () inline
Definition at line 83 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.inputPartition_.
Referenced by com.cloudera.impala.planner.DistributedPlanner.createAnalyticFragment().
long com.cloudera.impala.planner.PlanNode.getLimit () inline inherited
Definition at line 169 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.ScanNode.getInputCardinality().
String com.cloudera.impala.planner.SortNode.getNodeExplainDetail (TExplainLevel detailLevel) inline private
Definition at line 184 of file SortNode.java.
References com.cloudera.impala.planner.PlanNode.hasLimit(), com.cloudera.impala.planner.SortNode.hasOffset(), com.cloudera.impala.planner.PlanNode.limit_, and com.cloudera.impala.planner.SortNode.offset_.
Referenced by com.cloudera.impala.planner.SortNode.getNodeExplainString().
String com.cloudera.impala.planner.SortNode.getNodeExplainString (String prefix, String detailPrefix, TExplainLevel detailLevel) inline protected
Definition at line 162 of file SortNode.java.
References com.cloudera.impala.planner.PlanNode.displayName_, and com.cloudera.impala.planner.SortNode.getNodeExplainDetail().
Set<TupleId> com.cloudera.impala.planner.PlanNode.getNullableTupleIds () inline inherited
Definition at line 204 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.nullableTupleIds_.
int com.cloudera.impala.planner.PlanNode.getNumNodes () inline inherited
Definition at line 173 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.numNodes_.
Referenced by com.cloudera.impala.planner.PipelinedPlanNodeSet.computeResourceEstimates(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), and com.cloudera.impala.planner.DataSourceScanNode.computeStats().
long com.cloudera.impala.planner.SortNode.getOffset () inline
Definition at line 75 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.offset_.
String com.cloudera.impala.planner.SortNode.getOffsetExplainString (String prefix) inline protected
Definition at line 194 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.offset_.
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.getOutputSmap () inline inherited
Definition at line 178 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.outputSmap_.
long com.cloudera.impala.planner.PlanNode.getPerHostMemCost () inline inherited
Definition at line 171 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.perHostMemCost_.
Referenced by com.cloudera.impala.planner.PipelinedPlanNodeSet.computeResourceEstimates().
SortInfo com.cloudera.impala.planner.SortNode.getSortInfo () inline
Definition at line 79 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.info_.
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.getTblRefIds () inline inherited
Definition at line 201 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tblRefIds_.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.getTupleIds () inline inherited
Definition at line 196 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tupleIds_.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.SingleNodePlanner.createInlineViewPlan(), com.cloudera.impala.planner.AnalyticPlanner.createSortInfo(), and com.cloudera.impala.planner.SelectNode.SelectNode().
boolean com.cloudera.impala.planner.PlanNode.hasLimit () inline inherited
Definition at line 170 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.PlanNode.capAtLimit(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.ScanNode.getInputCardinality(), and com.cloudera.impala.planner.SortNode.getNodeExplainDetail().
boolean com.cloudera.impala.planner.SortNode.hasOffset () inline
Definition at line 77 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.offset_.
Referenced by com.cloudera.impala.planner.SortNode.getNodeExplainDetail().
boolean com.cloudera.impala.planner.PlanNode.hasValidStats () inline protected inherited
Returns true if stats-related variables are valid.
Definition at line 519 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_, and com.cloudera.impala.planner.PlanNode.numNodes_.
Referenced by com.cloudera.impala.planner.SortNode.computeCosts(), and com.cloudera.impala.planner.HashJoinNode.computeStats().
void com.cloudera.impala.planner.SortNode.init (Analyzer analyzer) throws InternalException inline
Definition at line 91 of file SortNode.java.
References com.cloudera.impala.planner.PlanNode.assignConjuncts(), com.cloudera.impala.planner.PlanNode.computeMemLayout(), com.cloudera.impala.planner.SortNode.computeStats(), com.cloudera.impala.planner.PlanNode.getCombinedChildSmap(), com.cloudera.impala.planner.PlanNode.outputSmap_, and com.cloudera.impala.planner.SortNode.resolvedTupleExprs_.
boolean com.cloudera.impala.planner.SortNode.isAnalyticSort () inline
Definition at line 84 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.isAnalyticSort_.
boolean com.cloudera.impala.planner.SortNode.isBlockingNode () inline
Definition at line 88 of file SortNode.java.
void com.cloudera.impala.planner.PlanNode.markSlotsMaterialized (Analyzer analyzer, List< Expr > exprs) inline protected inherited
Marks all slots referenced in exprs as materialized.
Definition at line 464 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.init().
static long com.cloudera.impala.planner.PlanNode.multiplyCardinalities (long a, long b) inline static inherited
Computes and returns the product of two cardinalities. If an overflow occurs, the maximum Long value is returned (Long.MAX_VALUE).
Definition at line 541 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeStats(), and com.cloudera.impala.planner.HashJoinNode.getJoinCardinality().
void com.cloudera.impala.planner.PlanNode.setAssignedConjuncts (Set< ExprId > conjuncts) inline inherited
Definition at line 181 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.assignedConjuncts_.
void com.cloudera.impala.planner.PlanNode.setDisplayName (String s) inline protected inherited
Definition at line 223 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.displayName_.
void com.cloudera.impala.planner.PlanNode.setFragment (PlanFragment fragment) inline inherited
Definition at line 175 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.fragment_.
void com.cloudera.impala.planner.PlanNode.setId (PlanNodeId id) inline inherited
Definition at line 165 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.id_.
void com.cloudera.impala.planner.SortNode.setInputPartition (DataPartition inputPartition) inline
Definition at line 80 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.inputPartition_.
void com.cloudera.impala.planner.SortNode.setIsAnalyticSort (boolean v) inline
Definition at line 85 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.isAnalyticSort_.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.createSortGroupPlan().
void com.cloudera.impala.planner.PlanNode.setLimit (long limit) inline inherited
Set the limit_ to the given limit_ only if the limit_ hasn't been set, or the new limit_ is lower.
Parameters
limit_
Definition at line 190 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
void com.cloudera.impala.planner.SortNode.setOffset (long offset) inline
Definition at line 76 of file SortNode.java.
References offset, and com.cloudera.impala.planner.SortNode.offset_.
void com.cloudera.impala.planner.PlanNode.setOutputSmap (ExprSubstitutionMap smap) inline inherited
Definition at line 179 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.outputSmap_.
void com.cloudera.impala.planner.PlanNode.setTblRefIds (ArrayList< TupleId > ids) inline inherited
Definition at line 202 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tblRefIds_.
void com.cloudera.impala.planner.SortNode.toThrift (TPlanNode msg) inline protected
Definition at line 149 of file SortNode.java.
References com.cloudera.impala.analysis.SortInfo.getIsAscOrder(), com.cloudera.impala.analysis.SortInfo.getOrderingExprs(), com.cloudera.impala.planner.SortNode.info_, com.cloudera.impala.planner.SortNode.offset_, com.cloudera.impala.planner.SortNode.resolvedTupleExprs_, com.cloudera.impala.analysis.Expr.treesToThrift(), and com.cloudera.impala.planner.SortNode.useTopN_.
void com.cloudera.impala.planner.PlanNode.transferConjuncts (PlanNode recipient) inline inherited
Definition at line 214 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
TPlan com.cloudera.impala.planner.PlanNode.treeToThrift () inline inherited
Definition at line 341 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
void com.cloudera.impala.planner.PlanNode.unsetLimit () inline inherited
Definition at line 194 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
boolean com.cloudera.impala.planner.SortNode.useTopN () inline
Definition at line 78 of file SortNode.java.
References com.cloudera.impala.planner.SortNode.useTopN_.
Referenced by com.cloudera.impala.planner.SortNode.SortNode().
Member Data Documentation
Set<ExprId> com.cloudera.impala.planner.PlanNode.assignedConjuncts_ protected inherited
Definition at line 99 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getAssignedConjuncts(), com.cloudera.impala.planner.CrossJoinNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.setAssignedConjuncts().
float com.cloudera.impala.planner.PlanNode.avgRowSize_ protected inherited
Definition at line 110 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getAvgRowSize(), and com.cloudera.impala.planner.PlanNode.getExplainString().
long com.cloudera.impala.planner.PlanNode.cardinality_ protected inherited
Definition at line 103 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.SelectNode.computeStats(), com.cloudera.impala.planner.CrossJoinNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.SortNode.computeStats(), com.cloudera.impala.planner.AnalyticEvalNode.computeStats(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getCardinality(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.HashJoinNode.getJoinCardinality(), com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality(), com.cloudera.impala.planner.PlanNode.hasValidStats(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
List<Expr> com.cloudera.impala.planner.PlanNode.conjuncts_ = Lists.newArrayList() protected inherited
Definition at line 86 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.computeSelectivity(), com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.HBaseScanNode.createHBaseFilters(), com.cloudera.impala.planner.PlanNode.debugString(), com.cloudera.impala.planner.PlanNode.getConjuncts(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.planner.SelectNode.init(), com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.transferConjuncts(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
final int com.cloudera.impala.planner.PlanNode.DEFAULT_BATCH_SIZE = 1024 static protected inherited
Definition at line 63 of file PlanNode.java.
String com.cloudera.impala.planner.PlanNode.displayName_ protected inherited
Definition at line 66 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getDisplayLabel(), com.cloudera.impala.planner.EmptySetNode.getNodeExplainString(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.SortNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.setDisplayName(), and com.cloudera.impala.planner.ExchangeNode.setMergeInfo().
PlanFragment com.cloudera.impala.planner.PlanNode.fragment_ protected inherited
Definition at line 90 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.ExchangeNode.getDisplayLabelDetail(), com.cloudera.impala.planner.PlanNode.getFragment(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.reorderOperands(), and com.cloudera.impala.planner.PlanNode.setFragment().
PlanNodeId com.cloudera.impala.planner.PlanNode.id_ protected inherited
Definition at line 69 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getId(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.setId().
final SortInfo com.cloudera.impala.planner.SortNode.info_ private
Definition at line 50 of file SortNode.java.
Referenced by com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.SortNode.debugString(), com.cloudera.impala.planner.SortNode.getSortInfo(), com.cloudera.impala.planner.SortNode.SortNode(), and com.cloudera.impala.planner.SortNode.toThrift().
DataPartition com.cloudera.impala.planner.SortNode.inputPartition_ private
Definition at line 53 of file SortNode.java.
Referenced by com.cloudera.impala.planner.SortNode.getInputPartition(), and com.cloudera.impala.planner.SortNode.setInputPartition().
boolean com.cloudera.impala.planner.SortNode.isAnalyticSort_ private
Definition at line 56 of file SortNode.java.
Referenced by com.cloudera.impala.planner.SortNode.isAnalyticSort(), and com.cloudera.impala.planner.SortNode.setIsAnalyticSort().
long com.cloudera.impala.planner.PlanNode.limit_ protected inherited
Definition at line 71 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.PlanNode.capAtLimit(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.PlanNode.debugString(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getLimit(), com.cloudera.impala.planner.SortNode.getNodeExplainDetail(), com.cloudera.impala.planner.PlanNode.hasLimit(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.setLimit(), com.cloudera.impala.planner.PlanNode.treeToThriftHelper(), and com.cloudera.impala.planner.PlanNode.unsetLimit().
final Logger com.cloudera.impala.planner.SortNode.LOG = LoggerFactory.getLogger(SortNode.class) static private
Definition at line 48 of file SortNode.java.
Set<TupleId> com.cloudera.impala.planner.PlanNode.nullableTupleIds_ = Sets.newHashSet() protected inherited
Definition at line 84 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.PlanNode.getNullableTupleIds(), and com.cloudera.impala.planner.PlanNode.PlanNode().
int com.cloudera.impala.planner.PlanNode.numNodes_ protected inherited
Definition at line 107 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.HdfsScanNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getNumNodes(), com.cloudera.impala.planner.PlanNode.hasValidStats(), and com.cloudera.impala.planner.PlanNode.PlanNode().
long com.cloudera.impala.planner.SortNode.offset_ protected
Definition at line 63 of file SortNode.java.
Referenced by com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.SortNode.debugString(), com.cloudera.impala.planner.SortNode.getNodeExplainDetail(), com.cloudera.impala.planner.SortNode.getOffset(), com.cloudera.impala.planner.SortNode.getOffsetExplainString(), com.cloudera.impala.planner.SortNode.hasOffset(), com.cloudera.impala.planner.SortNode.setOffset(), com.cloudera.impala.planner.SortNode.SortNode(), and com.cloudera.impala.planner.SortNode.toThrift().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.outputSmap_ protected inherited
Definition at line 93 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.PlanNode.getOutputSmap(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.PlanNode.setOutputSmap().
long com.cloudera.impala.planner.PlanNode.perHostMemCost_ = -1 protected inherited
Definition at line 114 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AnalyticEvalNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.DataSourceScanNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.HBaseScanNode.computeCosts(), com.cloudera.impala.planner.PlanNode.computeCosts(), com.cloudera.impala.planner.HdfsScanNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getPerHostMemCost(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
List<Expr> com.cloudera.impala.planner.SortNode.resolvedTupleExprs_ private
Definition at line 60 of file SortNode.java.
Referenced by com.cloudera.impala.planner.SortNode.init(), and com.cloudera.impala.planner.SortNode.toThrift().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.tblRefIds_ protected inherited
Definition at line 79 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getTblRefIds(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.setTblRefIds().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.tupleIds_ protected inherited
Definition at line 74 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.UnionNode.addChild(), com.cloudera.impala.planner.PlanNode.computeMemLayout(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getTupleIds(), com.cloudera.impala.planner.EmptySetNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.HdfsScanNode.prunePartitions(), com.cloudera.impala.planner.ExchangeNode.toThrift(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
final boolean com.cloudera.impala.planner.SortNode.useTopN_ private
Definition at line 61 of file SortNode.java.
Referenced by com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.SortNode.SortNode(), com.cloudera.impala.planner.SortNode.toThrift(), and com.cloudera.impala.planner.SortNode.useTopN().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/planner/SortNode.java