Impala: com.cloudera.impala.catalog.HdfsCachePool Class Reference
com.cloudera.impala.catalog.HdfsCachePool Class Reference
Public Member Functions
HdfsCachePool (CachePoolInfo cachePoolInfo)
HdfsCachePool (THdfsCachePool cachePool)
TCatalogObjectType getCatalogObjectType ()
THdfsCachePool toThrift ()
String getName ()
long getCatalogVersion ()
void setCatalogVersion (long newVersion)
boolean isLoaded ()
Static Public Member Functions
static HdfsCachePool fromThrift (THdfsCachePool cachePool)
Private Attributes
long catalogVersion_
final THdfsCachePool cachePool_
Detailed Description
Represents an HDFS cache pool (CachePoolInfo class). Currently, the only metadata we care about for cache pools is the cache pool name. In the future it may be desirable to track additional metadata such as the owner, size, and current usage of the pool.
Definition at line 28 of file HdfsCachePool.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.HdfsCachePool.HdfsCachePool (CachePoolInfo cachePoolInfo) inline
Definition at line 32 of file HdfsCachePool.java.
References com.cloudera.impala.catalog.HdfsCachePool.cachePool_.
Referenced by com.cloudera.impala.catalog.HdfsCachePool.fromThrift().
com.cloudera.impala.catalog.HdfsCachePool.HdfsCachePool (THdfsCachePool cachePool) inline
Definition at line 36 of file HdfsCachePool.java.
References com.cloudera.impala.catalog.HdfsCachePool.cachePool_.
Member Function Documentation
static HdfsCachePool com.cloudera.impala.catalog.HdfsCachePool.fromThrift (THdfsCachePool cachePool) inline static
Definition at line 50 of file HdfsCachePool.java.
References com.cloudera.impala.catalog.HdfsCachePool.HdfsCachePool().
TCatalogObjectType com.cloudera.impala.catalog.HdfsCachePool.getCatalogObjectType () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 42 of file HdfsCachePool.java.
long com.cloudera.impala.catalog.HdfsCachePool.getCatalogVersion () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 57 of file HdfsCachePool.java.
References com.cloudera.impala.catalog.HdfsCachePool.catalogVersion_.
Referenced by com.cloudera.impala.catalog.ImpaladCatalog.removeCatalogObject().
String com.cloudera.impala.catalog.HdfsCachePool.getName () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 55 of file HdfsCachePool.java.
boolean com.cloudera.impala.catalog.HdfsCachePool.isLoaded () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 61 of file HdfsCachePool.java.
void com.cloudera.impala.catalog.HdfsCachePool.setCatalogVersion (long newVersion) inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 59 of file HdfsCachePool.java.
References com.cloudera.impala.catalog.HdfsCachePool.catalogVersion_.
THdfsCachePool com.cloudera.impala.catalog.HdfsCachePool.toThrift () inline
Definition at line 46 of file HdfsCachePool.java.
References com.cloudera.impala.catalog.HdfsCachePool.cachePool_.
Member Data Documentation
final THdfsCachePool com.cloudera.impala.catalog.HdfsCachePool.cachePool_ private
Definition at line 30 of file HdfsCachePool.java.
Referenced by com.cloudera.impala.catalog.HdfsCachePool.HdfsCachePool(), and com.cloudera.impala.catalog.HdfsCachePool.toThrift().
long com.cloudera.impala.catalog.HdfsCachePool.catalogVersion_ private
Definition at line 29 of file HdfsCachePool.java.
Referenced by com.cloudera.impala.catalog.HdfsCachePool.getCatalogVersion(), and com.cloudera.impala.catalog.HdfsCachePool.setCatalogVersion().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HdfsCachePool.java