Impala: com.cloudera.impala.authorization.AuthorizationConfig Class Reference
com.cloudera.impala.authorization.AuthorizationConfig Class Reference
Public Member Functions
AuthorizationConfig (String serverName, String policyFile, String sentryConfigFile, String policyProviderClassName)
void validateConfig () throws IllegalArgumentException
boolean isEnabled ()
boolean isFileBasedPolicy ()
String getServerName ()
String getPolicyFile ()
SentryConfig getSentryConfig ()
String getPolicyProviderClassName ()
Static Public Member Functions
static AuthorizationConfig createAuthDisabledConfig ()
static AuthorizationConfig createHadoopGroupAuthConfig (String serverName, String policyFile, String sentryConfigFile)
Private Attributes
final String serverName_
final String policyFile_
final SentryConfig sentryConfig_
final String policyProviderClassName_
Detailed Description
Definition at line 27 of file AuthorizationConfig.java.
Constructor & Destructor Documentation
com.cloudera.impala.authorization.AuthorizationConfig.AuthorizationConfig (String serverName, String policyFile, String sentryConfigFile, String policyProviderClassName) inline
Creates a new authorization configuration object.
Parameters
serverName - The name of this Impala server.
policyFile - The path to the authorization policy file or null if the policy engine is not file based.
sentryConfigFile - Absolute path and file name of the sentry service.
policyProviderClassName - Class name of the policy provider to use.
Definition at line 42 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.policyFile_, com.cloudera.impala.authorization.AuthorizationConfig.policyProviderClassName_, com.cloudera.impala.authorization.AuthorizationConfig.sentryConfig_, and com.cloudera.impala.authorization.AuthorizationConfig.serverName_.
Referenced by com.cloudera.impala.authorization.AuthorizationConfig.createAuthDisabledConfig(), and com.cloudera.impala.authorization.AuthorizationConfig.createHadoopGroupAuthConfig().
Member Function Documentation
static AuthorizationConfig com.cloudera.impala.authorization.AuthorizationConfig.createAuthDisabledConfig () inline static
Returns an AuthorizationConfig object that has authorization disabled.
Definition at line 56 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.AuthorizationConfig().
Referenced by com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.ToSqlTest.analyze(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.createAuthDisabledAnalyzer(), and com.cloudera.impala.service.FrontendTest.TestCatalogNotReady().
static AuthorizationConfig com.cloudera.impala.authorization.AuthorizationConfig.createHadoopGroupAuthConfig (String serverName, String policyFile, String sentryConfigFile) inline static
Returns an AuthorizationConfig object configured to use Hadoop user->group mappings for the authorization provider.
Definition at line 64 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.AuthorizationConfig().
Referenced by com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeGrantRevokePriv(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.createAnalyzer(), com.cloudera.impala.analysis.AuthorizationTest.TestNoPermissionsWhenPolicyFileDoesNotExist(), and com.cloudera.impala.analysis.AuthorizationTest.TestServerNameAuthorized().
String com.cloudera.impala.authorization.AuthorizationConfig.getPolicyFile () inline
The policy file path.
Definition at line 138 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.policyFile_.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.createProvider().
String com.cloudera.impala.authorization.AuthorizationConfig.getPolicyProviderClassName () inline
Definition at line 144 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.policyProviderClassName_.
SentryConfig com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig () inline
The Sentry configuration.
Definition at line 143 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.sentryConfig_.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.createProvider(), com.cloudera.impala.analysis.AuthorizationTest.createSentryService(), com.cloudera.impala.analysis.AuthorizationTest.setup(), com.cloudera.impala.analysis.AuthorizationTest.TestCreateDatabase(), com.cloudera.impala.analysis.AuthorizationTest.TestFunction(), and com.cloudera.impala.analysis.AuthorizationTest.TestSentryService().
String com.cloudera.impala.authorization.AuthorizationConfig.getServerName () inline
The server name to secure.
Definition at line 133 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.serverName_.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.AuthorizationChecker(), and com.cloudera.impala.authorization.AuthorizationChecker.createProvider().
boolean com.cloudera.impala.authorization.AuthorizationConfig.isEnabled () inline
Returns true if authorization is enabled. If either serverName, policyFile, or sentryServiceConfig_ file is set (not null or empty), authorization is considered enabled.
Definition at line 118 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.policyFile_, and com.cloudera.impala.authorization.AuthorizationConfig.serverName_.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.AuthorizationChecker(), com.cloudera.impala.service.Frontend.Frontend(), com.cloudera.impala.service.Frontend.getDbNames(), com.cloudera.impala.service.Frontend.getTableNames(), com.cloudera.impala.authorization.AuthorizationChecker.hasAccess(), and com.cloudera.impala.authorization.AuthorizationConfig.validateConfig().
boolean com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy () inline
Returns true if using an authorization policy from a file in HDFS. If false, uses an authorization policy based on cached metadata sent from the catalog server via the statestore.
Definition at line 128 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.AuthorizationConfig.policyFile_.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.createProvider(), com.cloudera.impala.analysis.AuthorizationTest.TestCreateDatabase(), com.cloudera.impala.analysis.AuthorizationTest.TestFunction(), com.cloudera.impala.analysis.AuthorizationTest.TestLocalGroupPolicyProvider(), com.cloudera.impala.analysis.AuthorizationTest.TestNoPermissionsWhenPolicyFileDoesNotExist(), com.cloudera.impala.analysis.AuthorizationTest.TestResetMetadata(), and com.cloudera.impala.analysis.AuthorizationTest.TestServerNameAuthorized().
void com.cloudera.impala.authorization.AuthorizationConfig.validateConfig () throws IllegalArgumentException inline
Definition at line 74 of file AuthorizationConfig.java.
References com.cloudera.impala.authorization.SentryConfig.getConfigFile(), com.cloudera.impala.authorization.AuthorizationConfig.isEnabled(), com.cloudera.impala.authorization.AuthorizationConfig.policyProviderClassName_, com.cloudera.impala.authorization.AuthorizationConfig.sentryConfig_, and com.cloudera.impala.authorization.AuthorizationConfig.serverName_.
Member Data Documentation
final String com.cloudera.impala.authorization.AuthorizationConfig.policyFile_ private
Definition at line 30 of file AuthorizationConfig.java.
Referenced by com.cloudera.impala.authorization.AuthorizationConfig.AuthorizationConfig(), com.cloudera.impala.authorization.AuthorizationConfig.getPolicyFile(), com.cloudera.impala.authorization.AuthorizationConfig.isEnabled(), and com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
final String com.cloudera.impala.authorization.AuthorizationConfig.policyProviderClassName_ private
Definition at line 32 of file AuthorizationConfig.java.
Referenced by com.cloudera.impala.authorization.AuthorizationConfig.AuthorizationConfig(), com.cloudera.impala.authorization.AuthorizationConfig.getPolicyProviderClassName(), and com.cloudera.impala.authorization.AuthorizationConfig.validateConfig().
final SentryConfig com.cloudera.impala.authorization.AuthorizationConfig.sentryConfig_ private
Definition at line 31 of file AuthorizationConfig.java.
Referenced by com.cloudera.impala.authorization.AuthorizationConfig.AuthorizationConfig(), com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig(), and com.cloudera.impala.authorization.AuthorizationConfig.validateConfig().
final String com.cloudera.impala.authorization.AuthorizationConfig.serverName_ private
Definition at line 28 of file AuthorizationConfig.java.
Referenced by com.cloudera.impala.authorization.AuthorizationConfig.AuthorizationConfig(), com.cloudera.impala.authorization.AuthorizationConfig.getServerName(), com.cloudera.impala.authorization.AuthorizationConfig.isEnabled(), and com.cloudera.impala.authorization.AuthorizationConfig.validateConfig().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/authorization/AuthorizationConfig.java