Impala: impala::RowBatchList Class Reference
impala::RowBatchList Class Reference
#include <row-batch-list.h>
Classes
class TupleRowIterator
A simple iterator used to scan over all the rows stored in the list.
Public Member Functions
RowBatchList ()
void AddRowBatch (RowBatch *row_batch)
void Reset ()
Resets the list.
std::string DebugString (const RowDescriptor &desc)
Outputs a debug string containing the contents of the list.
int64_t total_num_rows ()
Returns the total number of rows in all row batches.
TupleRowIterator Iterator ()
Returns a new iterator over all the tuple rows.
Private Attributes
std::vector< RowBatch * > row_batches_
int64_t total_num_rows_
Total number of rows.
Friends
class TupleRowIterator
Detailed Description
A simple list structure for RowBatches that provides an interface for iterating over the TupleRows.
Definition at line 34 of file row-batch-list.h.
Constructor & Destructor Documentation
impala::RowBatchList::RowBatchList () inline
Definition at line 36 of file row-batch-list.h.
Member Function Documentation
void impala::RowBatchList::AddRowBatch (RowBatch * row_batch) inline
Add the 'row_batch' to the list. The RowBatch* and all of its resources are owned by the caller.
Definition at line 81 of file row-batch-list.h.
References impala::RowBatch::num_rows(), row_batches_, and total_num_rows_.
Referenced by impala::CrossJoinNode::ConstructBuildSide(), and impala::TEST_F().
std::string impala::RowBatchList::DebugString (const RowDescriptor & desc) inline
Outputs a debug string containing the contents of the list.
Definition at line 94 of file row-batch-list.h.
References impala::RowBatchList::TupleRowIterator::AtEnd(), impala::RowBatchList::TupleRowIterator::GetRow(), Iterator(), impala::RowBatchList::TupleRowIterator::Next(), impala::PrintRow(), and total_num_rows_.
Referenced by impala::CrossJoinNode::BuildListDebugString().
TupleRowIterator impala::RowBatchList::Iterator () inline
Returns a new iterator over all the tuple rows.
Definition at line 111 of file row-batch-list.h.
References TupleRowIterator.
Referenced by DebugString(), impala::RowBatchListTest::FullScan(), impala::CrossJoinNode::InitGetNext(), impala::CrossJoinNode::ProcessLeftChildBatch(), and impala::TEST_F().
void impala::RowBatchList::Reset () inline
Resets the list.
Definition at line 88 of file row-batch-list.h.
References row_batches_, and total_num_rows_.
Referenced by impala::CrossJoinNode::Close(), and impala::CrossJoinNode::Reset().
int64_t impala::RowBatchList::total_num_rows () inline
Returns the total number of rows in all row batches.
Definition at line 108 of file row-batch-list.h.
References total_num_rows_.
Referenced by impala::CrossJoinNode::ConstructBuildSide(), and impala::TEST_F().
Friends And Related Function Documentation
friend class TupleRowIterator friend
Definition at line 116 of file row-batch-list.h.
Referenced by Iterator().
Member Data Documentation
std::vector<RowBatch*> impala::RowBatchList::row_batches_ private
Definition at line 118 of file row-batch-list.h.
Referenced by AddRowBatch(), impala::RowBatchList::TupleRowIterator::AtEnd(), impala::RowBatchList::TupleRowIterator::Next(), and Reset().
int64_t impala::RowBatchList::total_num_rows_ private
Total number of rows.
Definition at line 121 of file row-batch-list.h.
Referenced by AddRowBatch(), DebugString(), Reset(), and total_num_rows().
The documentation for this class was generated from the following file:
be/src/exec/row-batch-list.h