Impala: com.cloudera.impala.analysis.FunctionArgs Class Reference
com.cloudera.impala.analysis.FunctionArgs Class Reference
Public Member Functions
FunctionArgs ()
FunctionArgs (ArrayList< TypeDef > argTypeDefs, boolean varArgs)
void setHasVarArgs (boolean b)
void analyze (Analyzer analyzer) throws AnalysisException
ArrayList< TypeDef > getArgTypeDefs ()
ArrayList< Type > getArgTypes ()
boolean hasVarArgs ()
String toSql ()
Private Attributes
final ArrayList< TypeDef > argTypeDefs_
boolean hasVarArgs_
ArrayList< Type > argTypes_
Detailed Description
Definition at line 25 of file FunctionArgs.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.FunctionArgs.FunctionArgs () inline
Definition at line 32 of file FunctionArgs.java.
References com.cloudera.impala.analysis.FunctionArgs.argTypeDefs_, and com.cloudera.impala.analysis.FunctionArgs.hasVarArgs_.
com.cloudera.impala.analysis.FunctionArgs.FunctionArgs (ArrayList< TypeDef > argTypeDefs, boolean varArgs) inline
Definition at line 37 of file FunctionArgs.java.
References com.cloudera.impala.analysis.FunctionArgs.argTypeDefs_, and com.cloudera.impala.analysis.FunctionArgs.hasVarArgs_.
Member Function Documentation
void com.cloudera.impala.analysis.FunctionArgs.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 49 of file FunctionArgs.java.
References com.cloudera.impala.analysis.FunctionArgs.argTypeDefs_, and com.cloudera.impala.analysis.FunctionArgs.argTypes_.
ArrayList<TypeDef> com.cloudera.impala.analysis.FunctionArgs.getArgTypeDefs () inline
Definition at line 58 of file FunctionArgs.java.
References com.cloudera.impala.analysis.FunctionArgs.argTypeDefs_.
ArrayList<Type> com.cloudera.impala.analysis.FunctionArgs.getArgTypes () inline
Definition at line 59 of file FunctionArgs.java.
References com.cloudera.impala.analysis.FunctionArgs.argTypes_.
Referenced by com.cloudera.impala.analysis.DropFunctionStmt.analyze(), com.cloudera.impala.analysis.CreateFunctionStmtBase.analyze(), and com.cloudera.impala.analysis.CreateUdaStmt.createFunction().
boolean com.cloudera.impala.analysis.FunctionArgs.hasVarArgs () inline
Definition at line 60 of file FunctionArgs.java.
References com.cloudera.impala.analysis.FunctionArgs.hasVarArgs_.
Referenced by com.cloudera.impala.analysis.CreateFunctionStmtBase.analyze(), and com.cloudera.impala.analysis.CreateUdaStmt.createFunction().
void com.cloudera.impala.analysis.FunctionArgs.setHasVarArgs (boolean b) inline
Definition at line 43 of file FunctionArgs.java.
References com.cloudera.impala.analysis.FunctionArgs.hasVarArgs_.
String com.cloudera.impala.analysis.FunctionArgs.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 63 of file FunctionArgs.java.
Member Data Documentation
final ArrayList<TypeDef> com.cloudera.impala.analysis.FunctionArgs.argTypeDefs_ private
Definition at line 26 of file FunctionArgs.java.
Referenced by com.cloudera.impala.analysis.FunctionArgs.analyze(), com.cloudera.impala.analysis.FunctionArgs.FunctionArgs(), and com.cloudera.impala.analysis.FunctionArgs.getArgTypeDefs().
ArrayList<Type> com.cloudera.impala.analysis.FunctionArgs.argTypes_ private
Definition at line 30 of file FunctionArgs.java.
Referenced by com.cloudera.impala.analysis.FunctionArgs.analyze(), and com.cloudera.impala.analysis.FunctionArgs.getArgTypes().
boolean com.cloudera.impala.analysis.FunctionArgs.hasVarArgs_ private
Definition at line 27 of file FunctionArgs.java.
Referenced by com.cloudera.impala.analysis.FunctionArgs.FunctionArgs(), com.cloudera.impala.analysis.FunctionArgs.hasVarArgs(), and com.cloudera.impala.analysis.FunctionArgs.setHasVarArgs().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/FunctionArgs.java