Impala: com.cloudera.impala.planner.PlannerContext Class Reference
com.cloudera.impala.planner.PlannerContext Class Reference
Public Member Functions
PlannerContext (AnalysisContext.AnalysisResult analysisResult, TQueryCtx queryCtx)
QueryStmt getQueryStmt ()
TQueryCtx getQueryCtx ()
TQueryOptions getQueryOptions ()
AnalysisContext.AnalysisResult getAnalysisResult ()
Analyzer getRootAnalyzer ()
boolean isSingleNodeExec ()
PlanNodeId getNextNodeId ()
PlanFragmentId getNextFragmentId ()
boolean isInsertOrCtas ()
Static Public Attributes
static final double HASH_TBL_SPACE_OVERHEAD = 1.1
static final double SORT_MEM_MAX_FRACTION = 0.80
Private Attributes
final IdGenerator< PlanNodeId > nodeIdGenerator_ = PlanNodeId.createGenerator()
final IdGenerator< PlanFragmentId > fragmentIdGenerator_
final TQueryCtx queryCtx_
final
AnalysisContext.AnalysisResult analysisResult_
final QueryStmt queryStmt_
Detailed Description
Contains the analysis result of a query as well as planning-specific parameters and state such as plan-node and plan-fragment id generators.
Definition at line 28 of file PlannerContext.java.
Constructor & Destructor Documentation
com.cloudera.impala.planner.PlannerContext.PlannerContext (AnalysisContext.AnalysisResult analysisResult, TQueryCtx queryCtx) inline
Definition at line 44 of file PlannerContext.java.
References com.cloudera.impala.planner.PlannerContext.analysisResult_, com.cloudera.impala.planner.PlannerContext.getQueryStmt(), com.cloudera.impala.planner.PlannerContext.isInsertOrCtas(), com.cloudera.impala.planner.PlannerContext.queryCtx_, and com.cloudera.impala.planner.PlannerContext.queryStmt_.
Member Function Documentation
AnalysisContext.AnalysisResult com.cloudera.impala.planner.PlannerContext.getAnalysisResult () inline
Definition at line 60 of file PlannerContext.java.
References com.cloudera.impala.planner.PlannerContext.analysisResult_.
PlanFragmentId com.cloudera.impala.planner.PlannerContext.getNextFragmentId () inline
Definition at line 64 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.DistributedPlanner.createHashJoinFragment(), com.cloudera.impala.planner.DistributedPlanner.createInsertFragment(), com.cloudera.impala.planner.DistributedPlanner.createMergeFragment(), com.cloudera.impala.planner.DistributedPlanner.createParentFragment(), com.cloudera.impala.planner.Planner.createPlan(), com.cloudera.impala.planner.DistributedPlanner.createPlanFragments(), com.cloudera.impala.planner.DistributedPlanner.createScanFragment(), and com.cloudera.impala.planner.DistributedPlanner.createUnionNodeFragment().
PlanNodeId com.cloudera.impala.planner.PlannerContext.getNextNodeId () inline
Definition at line 63 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.addUnassignedConjuncts(), com.cloudera.impala.planner.DistributedPlanner.connectChildFragment(), com.cloudera.impala.planner.DistributedPlanner.createAggregationFragment(), com.cloudera.impala.planner.SingleNodePlanner.createAggregationPlan(), com.cloudera.impala.planner.SingleNodePlanner.createConstantSelectPlan(), com.cloudera.impala.planner.SingleNodePlanner.createEmptyNode(), com.cloudera.impala.planner.DistributedPlanner.createHashJoinFragment(), com.cloudera.impala.planner.SingleNodePlanner.createInlineViewPlan(), com.cloudera.impala.planner.DistributedPlanner.createInsertFragment(), com.cloudera.impala.planner.DistributedPlanner.createMergeFragment(), com.cloudera.impala.planner.DistributedPlanner.createParentFragment(), com.cloudera.impala.planner.SingleNodePlanner.createQueryPlan(), com.cloudera.impala.planner.SingleNodePlanner.createScanNode(), com.cloudera.impala.planner.SingleNodePlanner.createSelectPlan(), com.cloudera.impala.planner.AnalyticPlanner.createSortGroupPlan(), and com.cloudera.impala.planner.SingleNodePlanner.createUnionPlan().
TQueryCtx com.cloudera.impala.planner.PlannerContext.getQueryCtx () inline
Definition at line 56 of file PlannerContext.java.
References com.cloudera.impala.planner.PlannerContext.queryCtx_.
TQueryOptions com.cloudera.impala.planner.PlannerContext.getQueryOptions () inline
Definition at line 57 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.Planner.computeResourceReqs(), com.cloudera.impala.planner.Planner.createPlan(), com.cloudera.impala.planner.SingleNodePlanner.createSingleNodePlan(), and com.cloudera.impala.planner.PlannerContext.isSingleNodeExec().
QueryStmt com.cloudera.impala.planner.PlannerContext.getQueryStmt () inline
Definition at line 55 of file PlannerContext.java.
References com.cloudera.impala.planner.PlannerContext.queryStmt_.
Referenced by com.cloudera.impala.planner.PlannerContext.PlannerContext().
Analyzer com.cloudera.impala.planner.PlannerContext.getRootAnalyzer () inline
Definition at line 61 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.DistributedPlanner.createAggregationFragment(), and com.cloudera.impala.planner.DistributedPlanner.createAnalyticFragment().
boolean com.cloudera.impala.planner.PlannerContext.isInsertOrCtas () inline
Definition at line 65 of file PlannerContext.java.
References com.cloudera.impala.planner.PlannerContext.analysisResult_.
Referenced by com.cloudera.impala.planner.Planner.createPlan(), and com.cloudera.impala.planner.PlannerContext.PlannerContext().
boolean com.cloudera.impala.planner.PlannerContext.isSingleNodeExec () inline
Definition at line 62 of file PlannerContext.java.
References com.cloudera.impala.planner.PlannerContext.getQueryOptions().
Referenced by com.cloudera.impala.planner.Planner.createPlan().
Member Data Documentation
final AnalysisContext.AnalysisResult com.cloudera.impala.planner.PlannerContext.analysisResult_ private
Definition at line 41 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.PlannerContext.getAnalysisResult(), com.cloudera.impala.planner.PlannerContext.isInsertOrCtas(), and com.cloudera.impala.planner.PlannerContext.PlannerContext().
final IdGenerator<PlanFragmentId> com.cloudera.impala.planner.PlannerContext.fragmentIdGenerator_ private
Initial value:
=
      PlanFragmentId.createGenerator()
Definition at line 37 of file PlannerContext.java.
final double com.cloudera.impala.planner.PlannerContext.HASH_TBL_SPACE_OVERHEAD = 1.1 static
Definition at line 31 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), and com.cloudera.impala.planner.DistributedPlanner.createHashJoinFragment().
final IdGenerator<PlanNodeId> com.cloudera.impala.planner.PlannerContext.nodeIdGenerator_ = PlanNodeId.createGenerator() private
Definition at line 36 of file PlannerContext.java.
final TQueryCtx com.cloudera.impala.planner.PlannerContext.queryCtx_ private
Definition at line 40 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.PlannerContext.getQueryCtx(), and com.cloudera.impala.planner.PlannerContext.PlannerContext().
final QueryStmt com.cloudera.impala.planner.PlannerContext.queryStmt_ private
Definition at line 42 of file PlannerContext.java.
Referenced by com.cloudera.impala.planner.PlannerContext.getQueryStmt(), and com.cloudera.impala.planner.PlannerContext.PlannerContext().
final double com.cloudera.impala.planner.PlannerContext.SORT_MEM_MAX_FRACTION = 0.80 static
Definition at line 34 of file PlannerContext.java.
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/planner/PlannerContext.java