Impala: impala::PartitioningThroughputTest Class Reference
impala::PartitioningThroughputTest Class Reference
Classes
struct Buffer
struct BufferBuffer
Public Member Functions
struct
impala::PartitioningThroughputTest::Buffer __attribute__ ((__packed__)) __attribute__((aligned(64)))
struct
impala::PartitioningThroughputTest::BufferBuffer __attribute__ ((__packed__)) __attribute__((aligned(64)))
void TestThroughput ()
void TestRawThroughput ()
Public Attributes
Buffer * buffers_
BufferBuffer * buffer_buffers_
Static Public Attributes
static const uint64_t FANOUT_BITS = 6
static const uint64_t NUM_BUFFERS = 1<<FANOUT_BITS
static const uint64_t DATA_BYTES = 1<<30
static const uint64_t DATA_TUPLES = DATA_BYTES / sizeof(ProbeTuple)
static const uint64_t BUFFER_BYTES = DATA_BYTES / NUM_BUFFERS * 2
static const uint64_t BUFFER_TUPLES = BUFFER_BYTES / sizeof(ProbeTuple)
static const int STREAMING_BUFFER_TUPLES = 8 * 4
Detailed Description
Definition at line 20 of file partitioning-throughput-test.cc.
Member Function Documentation
struct impala::PartitioningThroughputTest::Buffer impala::PartitioningThroughputTest::__attribute__ ((__packed__))
struct impala::PartitioningThroughputTest::BufferBuffer impala::PartitioningThroughputTest::__attribute__ ((__packed__))
void impala::PartitioningThroughputTest::TestRawThroughput () inline
Definition at line 110 of file partitioning-throughput-test.cc.
References impala::PrettyPrinter::Print(), impala::StopWatch::Start(), and impala::StopWatch::Stop().
Referenced by main().
void impala::PartitioningThroughputTest::TestThroughput () inline
Definition at line 78 of file partitioning-throughput-test.cc.
References Buffer(), buffer_buffers_, BUFFER_TUPLES, BufferBuffer(), buffers_, DATA_TUPLES, NUM_BUFFERS, impala::PrettyPrinter::Print(), impala::StopWatch::Start(), impala::StopWatch::Stop(), and tuples.
Member Data Documentation
BufferBuffer* impala::PartitioningThroughputTest::buffer_buffers_
Definition at line 126 of file partitioning-throughput-test.cc.
Referenced by TestThroughput().
const uint64_t impala::PartitioningThroughputTest::BUFFER_BYTES = DATA_BYTES / NUM_BUFFERS * 2 static
Definition at line 30 of file partitioning-throughput-test.cc.
const uint64_t impala::PartitioningThroughputTest::BUFFER_TUPLES = BUFFER_BYTES / sizeof(ProbeTuple) static
Definition at line 31 of file partitioning-throughput-test.cc.
Referenced by TestThroughput().
Buffer* impala::PartitioningThroughputTest::buffers_
Definition at line 125 of file partitioning-throughput-test.cc.
Referenced by TestThroughput().
const uint64_t impala::PartitioningThroughputTest::DATA_BYTES = 1<<30 static
Definition at line 26 of file partitioning-throughput-test.cc.
const uint64_t impala::PartitioningThroughputTest::DATA_TUPLES = DATA_BYTES / sizeof(ProbeTuple) static
Definition at line 27 of file partitioning-throughput-test.cc.
Referenced by TestThroughput().
const uint64_t impala::PartitioningThroughputTest::FANOUT_BITS = 6 static
Definition at line 23 of file partitioning-throughput-test.cc.
const uint64_t impala::PartitioningThroughputTest::NUM_BUFFERS = 1<<FANOUT_BITS static
Definition at line 24 of file partitioning-throughput-test.cc.
Referenced by TestThroughput().
const int impala::PartitioningThroughputTest::STREAMING_BUFFER_TUPLES = 8 * 4 static
Definition at line 33 of file partitioning-throughput-test.cc.
The documentation for this class was generated from the following file:
be/src/experiments/hashing/split-benchmarks/partitioning-throughput-test.cc