Impala: com.cloudera.impala.authorization.PrivilegeRequestBuilder Class Reference
com.cloudera.impala.authorization.PrivilegeRequestBuilder Class Reference
Public Member Functions
PrivilegeRequestBuilder onTable (String dbName, String tableName)
PrivilegeRequestBuilder onDb (String dbName)
PrivilegeRequestBuilder onURI (String uriName)
PrivilegeRequestBuilder onAnyTable (String dbName)
PrivilegeRequestBuilder allOf (Privilege privilege)
PrivilegeRequestBuilder all ()
PrivilegeRequestBuilder any ()
PrivilegeRequest toRequest ()
Package Attributes
Authorizeable authorizeable_
Privilege privilege_
Detailed Description
Class that helps build PrivilegeRequest objects. For example: PrivilegeRequestBuilder builder = new PrivilegeRequestBuilder(); PrivilegeRequest = builder.allOf(Privilege.SELECT).onTable("db", "tbl").toRequest();
TODO: In the future, this class could be extended to provide the option to specify multiple permissions. For example: builder.allOf(SELECT, INSERT).onTable(..); It could also be extended to support an "anyOf" to check if the user has any of the permissions specified: builder.anyOf(SELECT, INSERT).onTable(...);
Definition at line 32 of file PrivilegeRequestBuilder.java.
Member Function Documentation
PrivilegeRequestBuilder com.cloudera.impala.authorization.PrivilegeRequestBuilder.all () inline
Specifies the user needs "ALL" privileges
Definition at line 78 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.Privilege.ALL, and com.cloudera.impala.authorization.PrivilegeRequestBuilder.privilege_.
PrivilegeRequestBuilder com.cloudera.impala.authorization.PrivilegeRequestBuilder.allOf (Privilege privilege) inline
Specifies the privilege the user needs to have.
Definition at line 70 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.PrivilegeRequestBuilder.privilege_.
Referenced by com.cloudera.impala.analysis.Analyzer.getDb().
PrivilegeRequestBuilder com.cloudera.impala.authorization.PrivilegeRequestBuilder.any () inline
Specifies that any privileges are sufficient.
Definition at line 86 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.Privilege.ANY, and com.cloudera.impala.authorization.PrivilegeRequestBuilder.privilege_.
Referenced by com.cloudera.impala.analysis.Analyzer.getDb().
PrivilegeRequestBuilder com.cloudera.impala.authorization.PrivilegeRequestBuilder.onAnyTable (String dbName) inline
Specifies that permissions on any table in the given database.
Definition at line 63 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.AuthorizeableTable.ANY_TABLE_NAME, and com.cloudera.impala.authorization.PrivilegeRequestBuilder.onTable().
PrivilegeRequestBuilder com.cloudera.impala.authorization.PrivilegeRequestBuilder.onDb (String dbName) inline
Sets the authorizeable object to be a database.
Definition at line 47 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.PrivilegeRequestBuilder.authorizeable_.
PrivilegeRequestBuilder com.cloudera.impala.authorization.PrivilegeRequestBuilder.onTable (String dbName, String tableName) inline
Sets the authorizeable object to be a table.
Definition at line 39 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.PrivilegeRequestBuilder.authorizeable_.
Referenced by com.cloudera.impala.authorization.PrivilegeRequestBuilder.onAnyTable().
PrivilegeRequestBuilder com.cloudera.impala.authorization.PrivilegeRequestBuilder.onURI (String uriName) inline
Sets the authorizeable object to be a URI.
Definition at line 55 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.PrivilegeRequestBuilder.authorizeable_.
PrivilegeRequest com.cloudera.impala.authorization.PrivilegeRequestBuilder.toRequest () inline
Builds a PrivilegeRequest object based on the current Authorizeable object and privilege settings.
Definition at line 95 of file PrivilegeRequestBuilder.java.
References com.cloudera.impala.authorization.PrivilegeRequestBuilder.authorizeable_, and com.cloudera.impala.authorization.PrivilegeRequestBuilder.privilege_.
Member Data Documentation
Authorizeable com.cloudera.impala.authorization.PrivilegeRequestBuilder.authorizeable_ package
Definition at line 33 of file PrivilegeRequestBuilder.java.
Referenced by com.cloudera.impala.authorization.PrivilegeRequestBuilder.onDb(), com.cloudera.impala.authorization.PrivilegeRequestBuilder.onTable(), com.cloudera.impala.authorization.PrivilegeRequestBuilder.onURI(), and com.cloudera.impala.authorization.PrivilegeRequestBuilder.toRequest().
Privilege com.cloudera.impala.authorization.PrivilegeRequestBuilder.privilege_ package
Definition at line 34 of file PrivilegeRequestBuilder.java.
Referenced by com.cloudera.impala.authorization.PrivilegeRequestBuilder.all(), com.cloudera.impala.authorization.PrivilegeRequestBuilder.allOf(), com.cloudera.impala.authorization.PrivilegeRequestBuilder.any(), and com.cloudera.impala.authorization.PrivilegeRequestBuilder.toRequest().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/authorization/PrivilegeRequestBuilder.java