Impala: com.cloudera.impala.util.FsPermissionChecker.Permissions Class Reference
com.cloudera.impala.util.FsPermissionChecker.Permissions Class Reference
Public Member Functions
boolean checkPermissions (FsAction action)
boolean canRead ()
boolean canWrite ()
boolean canReadAndWrite ()
Protected Member Functions
Permissions (FileStatus fileStatus, AclStatus aclStatus)
Private Member Functions
boolean shouldApplyMask (AclEntry acl)
boolean isApplicableAcl (AclEntry e)
Boolean checkAcls (FsAction action)
List< AclEntry > getAclFromPermAndEntries (FsPermission perm, List< AclEntry > entries)
Private Attributes
final FileStatus fileStatus_
final FsPermission permissions_
final AclStatus aclStatus_
Map< AclEntryType, List
< AclEntry > > entriesByTypes_ = Maps.newHashMap()
AclEntry mask_
Detailed Description
Allows checking different access permissions of a file without repeatedly accessing the underlying filesystem by caching the results of a status call at construction.
Definition at line 80 of file FsPermissionChecker.java.
Constructor & Destructor Documentation
com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions (FileStatus fileStatus, AclStatus aclStatus) inline protected
If aclStatus is null, ACL permissions are not checked.
Definition at line 90 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.ACL_TYPE_PRIORITY, com.cloudera.impala.util.FsPermissionChecker.Permissions.aclStatus_, com.cloudera.impala.util.FsPermissionChecker.Permissions.fileStatus_, com.cloudera.impala.util.FsPermissionChecker.Permissions.getAclFromPermAndEntries(), com.cloudera.impala.util.FsPermissionChecker.Permissions.isApplicableAcl(), com.cloudera.impala.util.FsPermissionChecker.Permissions.mask_, and com.cloudera.impala.util.FsPermissionChecker.Permissions.permissions_.
Member Function Documentation
boolean com.cloudera.impala.util.FsPermissionChecker.Permissions.canRead () inline
Definition at line 219 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.Permissions.checkPermissions().
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.canReadAndWrite().
boolean com.cloudera.impala.util.FsPermissionChecker.Permissions.canReadAndWrite () inline
Definition at line 221 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.Permissions.canRead(), and com.cloudera.impala.util.FsPermissionChecker.Permissions.canWrite().
boolean com.cloudera.impala.util.FsPermissionChecker.Permissions.canWrite () inline
Definition at line 220 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.Permissions.checkPermissions().
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.canReadAndWrite().
Boolean com.cloudera.impala.util.FsPermissionChecker.Permissions.checkAcls (FsAction action) inline private
Returns true if ACLs allow 'action', false if they explicitly disallow 'action', and 'null' if no ACLs are available. See http://users.suse.com/~agruen/acl/linux-acls/online for more details about acl access check algorithm.
Definition at line 162 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.ACL_TYPE_PRIORITY, com.cloudera.impala.util.FsPermissionChecker.Permissions.aclStatus_, com.cloudera.impala.util.FsPermissionChecker.Permissions.entriesByTypes_, com.cloudera.impala.util.FsPermissionChecker.Permissions.mask_, and com.cloudera.impala.util.FsPermissionChecker.Permissions.shouldApplyMask().
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkPermissions().
boolean com.cloudera.impala.util.FsPermissionChecker.Permissions.checkPermissions (FsAction action) inline
Returns true if the current user can perform the given action given these permissions.
Definition at line 200 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.Permissions.checkAcls(), com.cloudera.impala.util.FsPermissionChecker.Permissions.fileStatus_, com.cloudera.impala.util.FsPermissionChecker.groups_, and com.cloudera.impala.util.FsPermissionChecker.user_.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.canRead(), and com.cloudera.impala.util.FsPermissionChecker.Permissions.canWrite().
List<AclEntry> com.cloudera.impala.util.FsPermissionChecker.Permissions.getAclFromPermAndEntries (FsPermission perm, List< AclEntry > entries) inline private
Definition at line 227 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions().
boolean com.cloudera.impala.util.FsPermissionChecker.Permissions.isApplicableAcl (AclEntry e) inline private
Returns true if this ACL applies to the current user and / or group
Definition at line 134 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.Permissions.aclStatus_.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions().
boolean com.cloudera.impala.util.FsPermissionChecker.Permissions.shouldApplyMask (AclEntry acl) inline private
Returns true if the mask should apply. The mask ACL applies only to unnamed user ACLs (e.g. user::r-x), and all group ACLs.
Definition at line 119 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.Permissions.mask_.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkAcls().
Member Data Documentation
final AclStatus com.cloudera.impala.util.FsPermissionChecker.Permissions.aclStatus_ private
Definition at line 83 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkAcls(), com.cloudera.impala.util.FsPermissionChecker.Permissions.isApplicableAcl(), and com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions().
Map<AclEntryType, List<AclEntry> > com.cloudera.impala.util.FsPermissionChecker.Permissions.entriesByTypes_ = Maps.newHashMap() private
Definition at line 84 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkAcls().
final FileStatus com.cloudera.impala.util.FsPermissionChecker.Permissions.fileStatus_ private
Definition at line 81 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkPermissions(), and com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions().
AclEntry com.cloudera.impala.util.FsPermissionChecker.Permissions.mask_ private
Definition at line 85 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkAcls(), com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions(), and com.cloudera.impala.util.FsPermissionChecker.Permissions.shouldApplyMask().
final FsPermission com.cloudera.impala.util.FsPermissionChecker.Permissions.permissions_ private
Definition at line 82 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/util/FsPermissionChecker.java