Impala: com.cloudera.impala.analysis.AnalyzeExprsTest Class Reference
com.cloudera.impala.analysis.AnalyzeExprsTest Class Reference
Public Member Functions
void TestNumericLiteralMinMaxValues ()
void TestTimestampValueExprs () throws AnalysisException
void TestBooleanValueExprs () throws AnalysisException
void TestBinaryPredicates () throws AnalysisException
void TestDecimalCasts () throws AnalysisException
void TestStringCasts () throws AnalysisException
void TestNullCasts () throws AnalysisException
void TestComplexTypeCasts () throws AnalysisException
void TestLikePredicates () throws AnalysisException
void TestCompoundPredicates () throws AnalysisException
void TestIsNullPredicates () throws AnalysisException
void TestBetweenPredicates () throws AnalysisException
void TestInPredicates () throws AnalysisException
void TestAnalyticExprs () throws AnalysisException
void TestArithmeticTypeCasts () throws AnalysisException
void TestComparisonTypeCasts () throws AnalysisException
void TestNumericLiteralTypeResolution () throws AnalysisException
void DoNotTestStringLiteralToDateCasts () throws AnalysisException
void TestFixedPointArithmeticOps () throws AnalysisException
void TestTimestampArithmeticExpressions ()
void TestFunctionCallExpr () throws AnalysisException
void TestVarArgFunctions () throws AnalysisException
void TestNullFunctionArguments ()
void TestCaseExpr () throws AnalysisException
void TestDecodeExpr () throws AnalysisException
void TestConditionalExprs ()
void TestUdfs ()
void TestExprChildLimit ()
void TestExprDepthLimit ()
void TestDecimalArithmetic ()
void TestDecimalOperators () throws AnalysisException
void TestDecimalCast () throws AnalysisException
void TestDecimalFunctions () throws AnalysisException
void TestAppxCountDistinctOption () throws AnalysisException, CatalogException
void tearDown ()
ParseNode ParsesOk (String stmt)
ParseNode AnalyzesOk (String stmt)
ParseNode AnalyzesOk (String stmt, String expectedWarning)
ParseNode AnalyzesOk (String stmt, Analyzer analyzer, String expectedWarning)
ParseNode AnalyzesOk (String stmt, Analyzer analyzer)
void AnalysisError (String stmt)
void AnalysisError (String stmt, String expectedErrorString)
void AnalysisError (String stmt, Analyzer analyzer, String expectedErrorString)
void TestCompressedText () throws AnalysisException
void TestMemLayout () throws AnalysisException
void TestUnsupportedTypes ()
void TestBinaryHBaseTable ()
void TestUnsupportedSerde ()
void TestResetMetadata ()
void TestExplain ()
void TestLimitAndOffset ()
void TestAnalyzeShowCreateTable ()
void TestFunctionMatching ()
Protected Member Functions
Analyzer createAnalyzer (String defaultDb)
Analyzer createAnalyzer (TQueryOptions queryOptions)
Analyzer createAnalyzerUsingHiveColLabels ()
Function addTestFunction (String name, ArrayList< ScalarType > args, boolean varArgs)
Function addTestFunction (String name, ScalarType arg, boolean varArgs)
Function addTestFunction (String db, String fnName, ArrayList< ScalarType > args, boolean varArgs)
void addTestUda (String name, Type retType, Type...argTypes)
Db addTestDb (String dbName)
void clearTestDbs ()
Table addTestTable (String createTableSql)
void clearTestTables ()
void checkSelectToThrift (SelectStmt node)
void TblsAnalyzeOk (String query, TableName tbl)
void TblsAnalysisError (String query, TableName tbl, String expectedError)
void checkExprType (String query, Type type)
Protected Attributes
final List< Db > testDbs_ = Lists.newArrayList()
final List< Table > testTables_ = Lists.newArrayList()
Analyzer analyzer_
Static Protected Attributes
static final Logger LOG = LoggerFactory.getLogger(AnalyzerTest.class)
static ImpaladCatalog catalog_ = new ImpaladTestCatalog()
static Map< ScalarType, String > typeToLiteralValue_
Package Functions
void assertCaseEquivalence (String caseSql, String decodeSql) throws AnalysisException
Static Package Functions
[static initializer]
Private Member Functions
void testNumericLiteral (String literal, Type expectedType)
void testExprCast (String literal, Type expectedType)
void typeCastTest (Type type1, Type type2, boolean op1IsLiteral, ArithmeticExpr.Operator arithmeticOp, BinaryPredicate.Operator cmpOp, Type opType) throws AnalysisException
void checkReturnType (String stmt, Type resultType)
void checkCasts (Expr expr)
void testDecimalExpr (String expr, Type expectedType)
void testInfixExprDepthLimit (String prefix, String repeatSuffix)
void testFuncExprDepthLimit (String openFunc, String baseArg, String closeFunc)
String getNestedFuncExpr (String openFunc, String baseArg, String closeFunc, int numFuncs)
Detailed Description
Definition at line 46 of file AnalyzeExprsTest.java.
Member Function Documentation
com.cloudera.impala.analysis.AnalyzerTest.[static initializer] () inline static package inherited
Db com.cloudera.impala.analysis.AnalyzerTest.addTestDb (String dbName) inline protected inherited
Add a new dummy database with the given name to the catalog. Returns the new dummy database. The database is registered in testDbs_ and removed in the method.
Definition at line 140 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.catalog_.
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.TestImplicitAndExplicitPaths(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSlotRefPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStarPathAmbiguity(), and com.cloudera.impala.analysis.AnalyzeStmtsTest.TestTableRefPathAmbiguity().
Function com.cloudera.impala.analysis.AnalyzerTest.addTestFunction (String name, ArrayList< ScalarType > args, boolean varArgs) inline protected inherited
Definition at line 108 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.addTestFunction(), and com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf().
Function com.cloudera.impala.analysis.AnalyzerTest.addTestFunction (String name, ScalarType arg, boolean varArgs) inline protected inherited
Definition at line 113 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.addTestFunction().
Function com.cloudera.impala.analysis.AnalyzerTest.addTestFunction (String db, String fnName, ArrayList< ScalarType > args, boolean varArgs) inline protected inherited
Definition at line 118 of file AnalyzerTest.java.
References com.cloudera.impala.catalog.Type.INT.
Table com.cloudera.impala.analysis.AnalyzerTest.addTestTable (String createTableSql) inline protected inherited
Add a new dummy table to the catalog based on the given CREATE TABLE sql. The dummy table only has the column definitions and no other metadata. Returns the new dummy table. The test tables are registered in testTables_ and removed in the method.
Definition at line 161 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.ColumnDef.getColName(), and com.cloudera.impala.analysis.CreateTableStmt.getTbl().
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.TestImplicitAndExplicitPaths(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSlotRefPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStarPathAmbiguity(), and com.cloudera.impala.analysis.AnalyzeStmtsTest.TestTableRefPathAmbiguity().
void com.cloudera.impala.analysis.AnalyzerTest.addTestUda (String name, Type retType, Type... argTypes) inline protected inherited
Definition at line 129 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), and com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestAggregateSubqueries().
void com.cloudera.impala.analysis.AnalyzerTest.AnalysisError (String stmt) inline inherited
Asserts if stmt passes analysis.
Definition at line 304 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeCreateDropRole(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeGrantRevokePriv(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeGrantRevokeRole(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeShowGrantRole(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeShowRoles(), com.cloudera.impala.analysis.AnalyzeExprsTest.DoNotTestStringLiteralToDateCasts(), com.cloudera.impala.analysis.AnalyzerTest.TblsAnalysisError(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestAggregateSubqueries(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableAddDropPartition(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableAddReplaceColumns(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableChangeColumn(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableDropColumn(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableRename(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableSet(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableSetCached(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterView(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterViewRename(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestAnalyticExprs(), com.cloudera.impala.analysis.AnalyzerTest.TestAnalyzeShowCreateTable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestAppxCountDistinctOption(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestBetweenPredicates(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestBinaryPredicates(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestCaseExpr(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestCatalogTableRefs(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testCollectionTableRefs(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestCollectionTableRefs(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComplexTypeCasts(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestComplexTypesInSelectList(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestCompoundPredicates(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestComputeIncrementalStats(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestComputeStats(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestConditionalExprs(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateAvroTest(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateDataSource(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateDb(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTableAsSelect(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTableLike(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTableLikeFile(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateView(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalArithmetic(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCast(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCasts(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalFunctions(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalOperators(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecodeExpr(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDescribe(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestDistinct(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestDistinctInlineView(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDrop(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDropIncrementalStats(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDropStats(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestExistsSubqueries(), com.cloudera.impala.analysis.AnalyzerTest.TestExplain(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprChildLimit(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestFixedPointArithmeticOps(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestFromClause(), com.cloudera.impala.analysis.AnalyzeExprsTest.testFuncExprDepthLimit(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestFunctionCallExpr(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestFunctions(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestGroupBy(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestImplicitAndExplicitPaths(), com.cloudera.impala.analysis.AnalyzeExprsTest.testInfixExprDepthLimit(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestInlineView(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestInPredicates(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestInsert(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertDynamic(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestInsertHints(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertStatic(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertUnpartitioned(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertWithPermutation(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestInSubqueries(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestJoinHints(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestLikePredicates(), com.cloudera.impala.analysis.AnalyzerTest.TestLimitAndOffset(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestLoadData(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestNoFromClause(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullFunctionArguments(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestOnClause(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestOrderBy(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestOrdinals(), com.cloudera.impala.analysis.AnalyzerTest.TestResetMetadata(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSemiJoins(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShow(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShowFiles(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShowPartitions(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShowStats(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSlotRefPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStar(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStarPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStructFields(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestSubqueries(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestTableRefPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestTimestampArithmeticExpressions(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUda(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestUnion(), com.cloudera.impala.analysis.AnalyzerTest.TestUnsupportedSerde(), com.cloudera.impala.analysis.AnalyzerTest.TestUnsupportedTypes(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUseDb(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestUsingClause(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestValuesStmt(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestVarArgFunctions(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestViews(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestWhereClause(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestWithClause(), and com.cloudera.impala.analysis.AnalyzeDDLTest.TypeDefAnalysisError().
void com.cloudera.impala.analysis.AnalyzerTest.AnalysisError (String stmt, String expectedErrorString) inline inherited
Asserts if stmt passes analysis or the error string doesn't match and it is non-null.
Definition at line 319 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), and com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
void com.cloudera.impala.analysis.AnalyzerTest.AnalysisError (String stmt, Analyzer analyzer, String expectedErrorString) inline inherited
Asserts if stmt passes analysis or the error string doesn't match and it is non-null.
Definition at line 327 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.catalog_, com.cloudera.impala.authorization.AuthorizationConfig.createAuthDisabledConfig(), com.cloudera.impala.testutil.TestUtils.createQueryContext(), and com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
ParseNode com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk (String stmt) inline inherited
Analyze 'stmt', expecting it to pass. Asserts in case of analysis error.
Definition at line 252 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), and com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.addTestTable(), com.cloudera.impala.analysis.AuditingTest.AnalyzeAccessEvents(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeCreateDropRole(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeGrantRevokePriv(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeGrantRevokeRole(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeShowGrantRole(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeShowRoles(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.AnalyzeExprsTest.assertCaseEquivalence(), com.cloudera.impala.analysis.AnalyzeDDLTest.checkComputeStatsStmt(), com.cloudera.impala.analysis.AnalyzerTest.checkExprType(), com.cloudera.impala.analysis.AnalyzeExprsTest.checkReturnType(), com.cloudera.impala.analysis.AnalyzerTest.TblsAnalyzeOk(), com.cloudera.impala.analysis.ToSqlTest.TblsTestToSql(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestAggregateSubqueries(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testAllTableAliases(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableAddDropPartition(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableAddReplaceColumns(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableChangeColumn(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableDropColumn(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableRename(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableSet(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterTableSetCached(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterView(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestAlterViewRename(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestAnalyticExprs(), com.cloudera.impala.analysis.AnalyzerTest.TestAnalyzeShowCreateTable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestAppxCountDistinctOption(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestBetweenPredicates(), com.cloudera.impala.analysis.AnalyzerTest.TestBinaryHBaseTable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestBinaryPredicates(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestBooleanValueExprs(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestCaseExpr(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestCatalogTableRefs(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestCollectionTableRefs(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestCompoundPredicates(), com.cloudera.impala.analysis.AnalyzerTest.TestCompressedText(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestComputeStats(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestConditionalExprs(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateAvroTest(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateDataSource(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateDb(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTableAsSelect(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTableLike(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTableLikeFile(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateView(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalArithmetic(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCast(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCasts(), com.cloudera.impala.analysis.AnalyzeExprsTest.testDecimalExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalFunctions(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalOperators(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecodeExpr(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDescribe(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestDistinct(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestDistinctInlineView(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDrop(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDropIncrementalStats(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestDropStats(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestExistsSubqueries(), com.cloudera.impala.analysis.AnalyzerTest.TestExplain(), com.cloudera.impala.analysis.AnalyzeExprsTest.testExprCast(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprChildLimit(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestFromClause(), com.cloudera.impala.analysis.AnalyzeExprsTest.testFuncExprDepthLimit(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestFunctionCallExpr(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestFunctions(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestGroupBy(), com.cloudera.impala.analysis.AnalyzeExprsTest.testInfixExprDepthLimit(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestInlineView(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestInPredicates(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestInsert(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertDynamic(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestInsertHints(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertStatic(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertUnpartitioned(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testInsertWithPermutation(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestInSubqueries(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestIsNullPredicates(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestJoinHints(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestLikePredicates(), com.cloudera.impala.analysis.AnalyzerTest.TestLimitAndOffset(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestLoadData(), com.cloudera.impala.analysis.AnalyzerTest.testMixedNullable(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestNoFromClause(), com.cloudera.impala.analysis.AnalyzerTest.testNonMaterializedSlots(), com.cloudera.impala.analysis.AnalyzerTest.testNonNullable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullFunctionArguments(), com.cloudera.impala.analysis.AnalyzeExprsTest.testNumericLiteral(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestOnClause(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestOrderBy(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestOrdinals(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestPermissionValidation(), com.cloudera.impala.analysis.AnalyzerTest.TestResetMetadata(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSelectListHints(), com.cloudera.impala.analysis.AnalyzerTest.testSelectStar(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSemiJoins(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSetQueryOption(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShow(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShowFiles(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShowPartitions(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestShowStats(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testSlotRefPath(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestSlotRefPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStar(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testStarPath(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStarPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestSubqueries(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testTableRefPath(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestTableRefPathAmbiguity(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestTimestampArithmeticExpressions(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestTimestampValueExprs(), com.cloudera.impala.analysis.ToSqlTest.testToSql(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUda(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestUnion(), com.cloudera.impala.analysis.AnalyzerTest.TestUnsupportedTypes(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUseDb(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUseStatement(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestUsingClause(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestValuesStmt(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestVarArgFunctions(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestViews(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestWhereClause(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestWithClause(), com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest(), and com.cloudera.impala.analysis.AnalyzeDDLTest.TypeDefsAnalyzeOk().
ParseNode com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk (String stmt, String expectedWarning) inline inherited
Analyze 'stmt', expecting it to pass. Asserts in case of analysis error. If 'expectedWarning' is not null, asserts that a warning is produced.
Definition at line 260 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), and com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
ParseNode com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk (String stmt, Analyzer analyzer, String expectedWarning) inline inherited
Analyze 'stmt', expecting it to pass. Asserts in case of analysis error. If 'expectedWarning' is not null, asserts that a warning is produced.
Definition at line 268 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.analyzer_, com.cloudera.impala.analysis.AnalyzerTest.catalog_, com.cloudera.impala.authorization.AuthorizationConfig.createAuthDisabledConfig(), com.cloudera.impala.testutil.TestUtils.createQueryContext(), and com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
ParseNode com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk (String stmt, Analyzer analyzer) inline inherited
Analyze 'stmt', expecting it to pass. Asserts in case of analysis error.
Definition at line 311 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.assertCaseEquivalence (String caseSql, String decodeSql) throws AnalysisException inline package
Assert that the caseSql and decodeSql have the same underlying child expr and thrift representation.
Definition at line 1616 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), and com.cloudera.impala.analysis.SelectStmt.getSelectList().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecodeExpr().
void com.cloudera.impala.analysis.AnalyzeExprsTest.checkCasts (Expr expr) inline private
Check that:
we don't implicitly cast literals (we should have simply converted the literal to the target type)
we don't do redundant casts (ie, we don't cast a bigint expr to a bigint)
Definition at line 1201 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.Expr.getType(), and com.cloudera.impala.analysis.CastExpr.isImplicit().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest().
void com.cloudera.impala.analysis.AnalyzerTest.checkExprType (String query, Type type) inline protected inherited
Definition at line 532 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts().
void com.cloudera.impala.analysis.AnalyzeExprsTest.checkReturnType (String stmt, Type resultType) inline private
Definition at line 1124 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution().
void com.cloudera.impala.analysis.AnalyzerTest.checkSelectToThrift (SelectStmt node) inline protected inherited
Check whether SelectStmt components can be converted to thrift.
Definition at line 194 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.checkBinaryExprs(), com.cloudera.impala.analysis.AggregateInfoBase.getAggregateExprs(), com.cloudera.impala.analysis.AggregateInfoBase.getGroupingExprs(), com.cloudera.impala.analysis.SelectStmt.getHavingPred(), and com.cloudera.impala.analysis.SelectStmt.getWhereClause().
void com.cloudera.impala.analysis.AnalyzerTest.clearTestDbs () inline protected inherited
Definition at line 149 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.testDbs_.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.tearDown().
void com.cloudera.impala.analysis.AnalyzerTest.clearTestTables () inline protected inherited
Definition at line 179 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.testTables_.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.tearDown().
Analyzer com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer (String defaultDb) inline protected inherited
Definition at line 85 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.catalog_, and com.cloudera.impala.authorization.AuthorizationConfig.createAuthDisabledConfig().
Referenced by com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AuditingTest.AnalyzeAccessEvents(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.AnalyzerTest.createAnalyzerUsingHiveColLabels(), com.cloudera.impala.analysis.AnalyzerTest.TblsAnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.TblsAnalyzeOk(), com.cloudera.impala.analysis.ToSqlTest.TblsTestToSql(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestAppxCountDistinctOption(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestCatalogTableRefs(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testCollectionTableRefs(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestTableRefPathAmbiguity(), com.cloudera.impala.analysis.ToSqlTest.testToSql(), and com.cloudera.impala.analysis.AnalyzeStmtsTest.TestWithClause().
Analyzer com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer (TQueryOptions queryOptions) inline protected inherited
Definition at line 92 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.catalog_, and com.cloudera.impala.authorization.AuthorizationConfig.createAuthDisabledConfig().
Analyzer com.cloudera.impala.analysis.AnalyzerTest.createAnalyzerUsingHiveColLabels () inline protected inherited
Definition at line 99 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), and com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.TestInlineView().
void com.cloudera.impala.analysis.AnalyzeExprsTest.DoNotTestStringLiteralToDateCasts () throws AnalysisException inline
Definition at line 1217 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError().
String com.cloudera.impala.analysis.AnalyzeExprsTest.getNestedFuncExpr (String openFunc, String baseArg, String closeFunc, int numFuncs) inline private
Generates a string: openFunc* baseArg closeFunc*, where * repetition of exactly numFuncs times.
Definition at line 2099 of file AnalyzeExprsTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.testFuncExprDepthLimit().
ParseNode com.cloudera.impala.analysis.AnalyzerTest.ParsesOk (String stmt) inline inherited
Parse 'stmt' and return the root ParseNode.
Definition at line 235 of file AnalyzerTest.java.
References gen_ir_descriptions.parser.
Referenced by com.cloudera.impala.analysis.AuditingTest.TestAccessEventsOnAuthFailure().
void com.cloudera.impala.analysis.AnalyzerTest.TblsAnalysisError (String query, TableName tbl, String expectedError) inline protected inherited
Same as TblsAnalyzeOk(), except that analysis of all variants is expected to fail with the given error message.
Definition at line 373 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), and com.cloudera.impala.analysis.TableName.getDb().
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.testAllTableAliases(), and com.cloudera.impala.analysis.AnalyzeStmtsTest.testCollectionTableRefs().
void com.cloudera.impala.analysis.AnalyzerTest.TblsAnalyzeOk (String query, TableName tbl) inline protected inherited
Generates and analyzes two variants of the given query by replacing all occurrences of "$TBL" in the query string with the unqualified and fully-qualified version of the given table name. The unqualified variant is analyzed using an analyzer that has tbl's db set as the default database. Example: query = "select id from $TBL, $TBL" tbl = "functional.alltypes" Variants generated and analyzed: select id from alltypes, alltypes (default db is "functional") select id from functional.alltypes, functional.alltypes (default db is "default")
Definition at line 360 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), and com.cloudera.impala.analysis.TableName.getDb().
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.testAllTableAliases(), and com.cloudera.impala.analysis.AnalyzeStmtsTest.testCollectionTableRefs().
void com.cloudera.impala.analysis.AnalyzerTest.tearDown () inline inherited
Definition at line 186 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.clearTestDbs(), and com.cloudera.impala.analysis.AnalyzerTest.clearTestTables().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestAnalyticExprs () throws AnalysisException inline
Definition at line 603 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzerTest.TestAnalyzeShowCreateTable () inline inherited
Definition at line 689 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestAppxCountDistinctOption () throws AnalysisException, CatalogException inline
Definition at line 2113 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), and com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts () throws AnalysisException inline
Test of all arithmetic type casts.
Definition at line 971 of file AnalyzeExprsTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.NULL, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.TINYINT, and com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestBetweenPredicates () throws AnalysisException inline
Definition at line 496 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzerTest.TestBinaryHBaseTable () inline inherited
Definition at line 572 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestBinaryPredicates () throws AnalysisException inline
Definition at line 158 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestBooleanValueExprs () throws AnalysisException inline
Definition at line 132 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestCaseExpr () throws AnalysisException inline
Definition at line 1502 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts () throws AnalysisException inline
Test of all type casts in comparisons following mysql's casting policy.
Definition at line 1049 of file AnalyzeExprsTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.TINYINT, and com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestComplexTypeCasts () throws AnalysisException inline
Tests that casts to complex types fail with an appropriate error message.
Definition at line 393 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestCompoundPredicates () throws AnalysisException inline
Definition at line 430 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzerTest.TestCompressedText () throws AnalysisException inline inherited
Definition at line 401 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestConditionalExprs () inline
Definition at line 1643 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalArithmetic () inline
Definition at line 1819 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.catalog.ScalarType.createDecimalType(), and com.cloudera.impala.analysis.AnalyzeExprsTest.testDecimalExpr().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCast () throws AnalysisException inline
Definition at line 1974 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCasts () throws AnalysisException inline
Definition at line 216 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.Type.getSupportedTypes(), com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, and com.cloudera.impala.catalog.Type.toSql().
void com.cloudera.impala.analysis.AnalyzeExprsTest.testDecimalExpr (String expr, Type expectedType) inline private
Definition at line 1809 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalArithmetic(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalFunctions().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalFunctions () throws AnalysisException inline
Definition at line 1992 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.catalog.ScalarType.createDecimalType(), and com.cloudera.impala.analysis.AnalyzeExprsTest.testDecimalExpr().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalOperators () throws AnalysisException inline
Definition at line 1945 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecodeExpr () throws AnalysisException inline
Definition at line 1573 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), and com.cloudera.impala.analysis.AnalyzeExprsTest.assertCaseEquivalence().
void com.cloudera.impala.analysis.AnalyzerTest.TestExplain () inline inherited
Definition at line 604 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.testExprCast (String literal, Type expectedType) inline private
Asserts that an expression can be cast as the specified type
Definition at line 251 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), and com.cloudera.impala.catalog.Type.toSql().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprChildLimit () inline
Definition at line 1750 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), and com.cloudera.impala.analysis.Expr.EXPR_CHILDREN_LIMIT.
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprDepthLimit () inline
Definition at line 1778 of file AnalyzeExprsTest.java.
References com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.analysis.AnalyzeExprsTest.testFuncExprDepthLimit(), and com.cloudera.impala.analysis.AnalyzeExprsTest.testInfixExprDepthLimit().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestFixedPointArithmeticOps () throws AnalysisException inline
Definition at line 1238 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError().
void com.cloudera.impala.analysis.AnalyzeExprsTest.testFuncExprDepthLimit (String openFunc, String baseArg, String closeFunc) inline private
Test expr depth limit of function-like operations, e.g., f(a). Generates test exprs using the pattern: openFunc* baseArg closeFunc*
Definition at line 2080 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.Expr.EXPR_DEPTH_LIMIT, and com.cloudera.impala.analysis.AnalyzeExprsTest.getNestedFuncExpr().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprDepthLimit().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestFunctionCallExpr () throws AnalysisException inline
Definition at line 1403 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching () inline inherited
Definition at line 705 of file AnalyzerTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.analysis.AnalyzerTest.createFunction(), com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.STRING, and com.cloudera.impala.catalog.Type.TINYINT.
void com.cloudera.impala.analysis.AnalyzeExprsTest.testInfixExprDepthLimit (String prefix, String repeatSuffix) inline private
Test expr depth limit of operators in infix notation, e.g., 1 + 1. Generates test exprs using the pattern: prefix + repeatSuffix*
Definition at line 2056 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), and com.cloudera.impala.analysis.Expr.EXPR_DEPTH_LIMIT.
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprDepthLimit().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestInPredicates () throws AnalysisException inline
Definition at line 553 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestIsNullPredicates () throws AnalysisException inline
Definition at line 488 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestLikePredicates () throws AnalysisException inline
Definition at line 403 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzerTest.TestLimitAndOffset () inline inherited
Definition at line 630 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzerTest.TestMemLayout () throws AnalysisException inline inherited
Definition at line 411 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.testMixedNullable(), com.cloudera.impala.analysis.AnalyzerTest.testNonMaterializedSlots(), com.cloudera.impala.analysis.AnalyzerTest.testNonNullable(), and com.cloudera.impala.analysis.AnalyzerTest.testSelectStar().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts () throws AnalysisException inline
Tests that cast(null to type) returns type for all types.
Definition at line 374 of file AnalyzeExprsTest.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.analysis.AnalyzerTest.checkExprType(), com.cloudera.impala.catalog.Type.DEFAULT_DECIMAL, com.cloudera.impala.catalog.Type.getSupportedTypes(), and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullFunctionArguments () inline
Tests that functions with NULL arguments get resolved properly, and that proper errors are reported when the non-null arguments cannot be cast to match a signature.
Definition at line 1473 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.testNumericLiteral (String literal, Type expectedType) inline private
Asserts that "select literal" analyzes ok and that the expectedType matches the actual type.
Definition at line 117 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues () inline
Definition at line 49 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.analysis.AnalyzeExprsTest.testNumericLiteral(), and com.cloudera.impala.catalog.Type.TINYINT.
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution () throws AnalysisException inline
Definition at line 1136 of file AnalyzeExprsTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.analysis.AnalyzeExprsTest.checkReturnType(), com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.Type.DOUBLE, and com.cloudera.impala.catalog.Type.TINYINT.
void com.cloudera.impala.analysis.AnalyzerTest.TestResetMetadata () inline inherited
Definition at line 583 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts () throws AnalysisException inline
Definition at line 260 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.catalog.ScalarType.createCharType(), com.cloudera.impala.catalog.ScalarType.createVarcharType(), com.cloudera.impala.catalog.Type.STRING, and com.cloudera.impala.analysis.AnalyzeExprsTest.testExprCast().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestTimestampArithmeticExpressions () inline
We have three variants of timestamp arithmetic exprs, as in MySQL: http://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html (section #function_date-add)
Non-function-call like version, e.g., 'a + interval b timeunit'
Beginning with an interval (only for '+'), e.g., 'interval b timeunit + a'
Function-call like version, e.g., date_add(a, interval b timeunit)
Definition at line 1262 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestTimestampValueExprs () throws AnalysisException inline
Definition at line 125 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs () inline
Definition at line 1690 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.INT, and com.cloudera.impala.catalog.Type.STRING.
void com.cloudera.impala.analysis.AnalyzerTest.TestUnsupportedSerde () inline inherited
Definition at line 577 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError().
void com.cloudera.impala.analysis.AnalyzerTest.TestUnsupportedTypes () inline inherited
We distinguish between three classes of unsupported types:
Complex types, e.g., map For tables with such types we prevent loading the table metadata.
Primitive types For tables with unsupported primitive types (e.g., binary) we can run queries as long as the unsupported columns are not referenced. We fail analysis if a query references an unsupported primitive column.
Partition-column types We do not support table partitioning on timestamp columns
Definition at line 549 of file AnalyzerTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.TestVarArgFunctions () throws AnalysisException inline
Definition at line 1447 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
void com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest (Type type1, Type type2, boolean op1IsLiteral, ArithmeticExpr.Operator arithmeticOp, BinaryPredicate.Operator cmpOp, Type opType) throws AnalysisException inline private
Generate an expr of the form "<type1> <arithmeticOp | cmpOp> <type2>" and make sure that the expr has the correct type (opType for arithmetic ops or bool for comparisons) and that both operands are of type 'opType'.
Definition at line 1073 of file AnalyzeExprsTest.java.
References com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.analysis.AnalyzeExprsTest.checkCasts(), com.cloudera.impala.analysis.Expr.getType(), and com.cloudera.impala.catalog.Type.isNull().
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts().
Member Data Documentation
Analyzer com.cloudera.impala.analysis.AnalyzerTest.analyzer_ protected inherited
Definition at line 64 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeAuthStmtsTest(), and com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk().
ImpaladCatalog com.cloudera.impala.analysis.AnalyzerTest.catalog_ = new ImpaladTestCatalog() static protected inherited
Definition at line 58 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.addTestDb(), com.cloudera.impala.analysis.AnalyzerTest.AnalysisError(), com.cloudera.impala.analysis.ToSqlTest.analyze(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.AnalyzeGrantRevokePriv(), com.cloudera.impala.analysis.AnalyzerTest.AnalyzesOk(), com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.createAnalyzer(), com.cloudera.impala.analysis.AnalyzerTest.createAnalyzer(), and com.cloudera.impala.analysis.AnalyzeAuthStmtsTest.createAuthDisabledAnalyzer().
final Logger com.cloudera.impala.analysis.AnalyzerTest.LOG = LoggerFactory.getLogger(AnalyzerTest.class) static protected inherited
Definition at line 57 of file AnalyzerTest.java.
final List<Db> com.cloudera.impala.analysis.AnalyzerTest.testDbs_ = Lists.newArrayList() protected inherited
Definition at line 61 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.clearTestDbs().
final List<Table> com.cloudera.impala.analysis.AnalyzerTest.testTables_ = Lists.newArrayList() protected inherited
Definition at line 62 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.clearTestTables().
Map<ScalarType, String> com.cloudera.impala.analysis.AnalyzerTest.typeToLiteralValue_ static protected inherited
Initial value:
=
      new HashMap<ScalarType, String>()
Definition at line 67 of file AnalyzerTest.java.
Referenced by com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/analysis/AnalyzeExprsTest.java