Impala: impala::Sorter::TupleSorter::TupleIterator Class Reference
impala::Sorter::TupleSorter::TupleIterator Class Reference
Public Member Functions
TupleIterator (TupleSorter *parent, int64_t index)
void Next ()
void Prev ()
Private Attributes
TupleSorter * parent_
int64_t index_
uint8_t * current_tuple_
uint8_t * buffer_start_
int block_index_
Friends
class TupleSorter
Detailed Description
Definition at line 220 of file sorter.cc.
Constructor & Destructor Documentation
impala::Sorter::TupleSorter::TupleIterator::TupleIterator (TupleSorter * parent, int64_t index) inline
Definition at line 222 of file sorter.cc.
References impala::Sorter::TupleSorter::block_capacity_, impala::Sorter::Run::fixed_len_blocks_, impala::Sorter::TupleSorter::run_, impala::Sorter::TupleSorter::tuple_size_, and UNLIKELY.
Member Function Documentation
void impala::Sorter::TupleSorter::TupleIterator::Next () inline
Definition at line 247 of file sorter.cc.
References UNLIKELY.
Referenced by impala::Sorter::TupleSorter::InsertionSort(), and impala::Sorter::TupleSorter::Partition().
void impala::Sorter::TupleSorter::TupleIterator::Prev () inline
Definition at line 262 of file sorter.cc.
References UNLIKELY.
Referenced by impala::Sorter::TupleSorter::InsertionSort(), and impala::Sorter::TupleSorter::Partition().
Friends And Related Function Documentation
friend class TupleSorter friend
Definition at line 274 of file sorter.cc.
Member Data Documentation
int impala::Sorter::TupleSorter::TupleIterator::block_index_ private
Definition at line 289 of file sorter.cc.
uint8_t* impala::Sorter::TupleSorter::TupleIterator::buffer_start_ private
Definition at line 286 of file sorter.cc.
uint8_t* impala::Sorter::TupleSorter::TupleIterator::current_tuple_ private
Definition at line 283 of file sorter.cc.
Referenced by impala::Sorter::TupleSorter::InsertionSort(), impala::Sorter::TupleSorter::Partition(), and impala::Sorter::TupleSorter::SortHelper().
int64_t impala::Sorter::TupleSorter::TupleIterator::index_ private
Definition at line 280 of file sorter.cc.
Referenced by impala::Sorter::TupleSorter::InsertionSort(), impala::Sorter::TupleSorter::Partition(), and impala::Sorter::TupleSorter::SortHelper().
TupleSorter* impala::Sorter::TupleSorter::TupleIterator::parent_ private
Definition at line 277 of file sorter.cc.
The documentation for this class was generated from the following file:
be/src/runtime/sorter.cc