Impala: com.cloudera.impala.analysis.FunctionParams Class Reference
com.cloudera.impala.analysis.FunctionParams Class Reference
Public Member Functions
FunctionParams (boolean isDistinct, List< Expr > exprs)
FunctionParams (List< Expr > exprs)
boolean isStar ()
boolean isDistinct ()
List< Expr > exprs ()
void setIsDistinct (boolean v)
int size ()
Static Public Member Functions
static FunctionParams createStarParam ()
Private Member Functions
FunctionParams ()
Private Attributes
final boolean isStar_
boolean isDistinct_
final List< Expr > exprs_
Detailed Description
Return value of the grammar production that parses function parameters. These parameters can be for scalar or aggregate functions.
Definition at line 23 of file FunctionParams.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.FunctionParams.FunctionParams (boolean isDistinct, List< Expr > exprs) inline
Definition at line 29 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.exprs(), com.cloudera.impala.analysis.FunctionParams.isDistinct(), and com.cloudera.impala.analysis.FunctionParams.isStar_.
com.cloudera.impala.analysis.FunctionParams.FunctionParams (List< Expr > exprs) inline
Definition at line 36 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.exprs().
com.cloudera.impala.analysis.FunctionParams.FunctionParams () inline private
Definition at line 51 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.exprs_, com.cloudera.impala.analysis.FunctionParams.isDistinct_, and com.cloudera.impala.analysis.FunctionParams.isStar_.
Referenced by com.cloudera.impala.analysis.FunctionParams.createStarParam().
Member Function Documentation
static FunctionParams com.cloudera.impala.analysis.FunctionParams.createStarParam () inline static
Definition at line 40 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.FunctionParams().
List<Expr> com.cloudera.impala.analysis.FunctionParams.exprs () inline
Definition at line 46 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.exprs_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.FunctionCallExpr(), and com.cloudera.impala.analysis.FunctionParams.FunctionParams().
boolean com.cloudera.impala.analysis.FunctionParams.isDistinct () inline
Definition at line 45 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.isDistinct_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.equals(), com.cloudera.impala.analysis.FunctionParams.FunctionParams(), com.cloudera.impala.analysis.FunctionCallExpr.getFunctionNotFoundError(), and com.cloudera.impala.analysis.FunctionCallExpr.toSqlImpl().
boolean com.cloudera.impala.analysis.FunctionParams.isStar () inline
Definition at line 44 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.isStar_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.equals(), com.cloudera.impala.analysis.FunctionCallExpr.getFunctionNotFoundError(), and com.cloudera.impala.analysis.FunctionCallExpr.toSqlImpl().
void com.cloudera.impala.analysis.FunctionParams.setIsDistinct (boolean v) inline
Definition at line 47 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.isDistinct_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.analyze().
int com.cloudera.impala.analysis.FunctionParams.size () inline
Definition at line 48 of file FunctionParams.java.
References com.cloudera.impala.analysis.FunctionParams.exprs_.
Member Data Documentation
final List<Expr> com.cloudera.impala.analysis.FunctionParams.exprs_ private
Definition at line 26 of file FunctionParams.java.
Referenced by com.cloudera.impala.analysis.FunctionParams.exprs(), com.cloudera.impala.analysis.FunctionParams.FunctionParams(), and com.cloudera.impala.analysis.FunctionParams.size().
boolean com.cloudera.impala.analysis.FunctionParams.isDistinct_ private
Definition at line 25 of file FunctionParams.java.
Referenced by com.cloudera.impala.analysis.FunctionParams.FunctionParams(), com.cloudera.impala.analysis.FunctionParams.isDistinct(), and com.cloudera.impala.analysis.FunctionParams.setIsDistinct().
final boolean com.cloudera.impala.analysis.FunctionParams.isStar_ private
Definition at line 24 of file FunctionParams.java.
Referenced by com.cloudera.impala.analysis.FunctionParams.FunctionParams(), and com.cloudera.impala.analysis.FunctionParams.isStar().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/FunctionParams.java