Impala: impala::DataStreamSender::Channel Class Reference
impala::DataStreamSender::Channel Class Reference
Public Member Functions
Channel (DataStreamSender *parent, const RowDescriptor &row_desc, const TNetworkAddress &destination, const TUniqueId &fragment_instance_id, PlanNodeId dest_node_id, int buffer_size)
Status Init (RuntimeState *state)
Status AddRow (TupleRow *row)
Status SendBatch (TRowBatch *batch)
Status GetSendStatus ()
void WaitForRpc ()
void Close (RuntimeState *state)
int64_t num_data_bytes_sent () const
TRowBatch * thrift_batch ()
Private Member Functions
Status SendCurrentBatch ()
void TransmitData (int thread_id, const TRowBatch *)
void TransmitDataHelper (const TRowBatch *)
Status CloseInternal ()
Private Attributes
DataStreamSender * parent_
int buffer_size_
ImpalaInternalServiceClientCache * client_cache_
const RowDescriptor & row_desc_
TNetworkAddress address_
TUniqueId fragment_instance_id_
PlanNodeId dest_node_id_
int64_t num_data_bytes_sent_
scoped_ptr< RowBatch > batch_
TRowBatch thrift_batch_
ThreadPool< TRowBatch * > rpc_thread_
condition_variable rpc_done_cv_
mutex rpc_thread_lock_
bool rpc_in_flight_
Status rpc_status_
Detailed Description
Definition at line 57 of file data-stream-sender.cc.
Constructor & Destructor Documentation
impala::DataStreamSender::Channel::Channel (DataStreamSender * parent, const RowDescriptor & row_desc, const TNetworkAddress & destination, const TUniqueId & fragment_instance_id, PlanNodeId dest_node_id, int buffer_size) inline
Definition at line 63 of file data-stream-sender.cc.
Member Function Documentation
Status impala::DataStreamSender::Channel::AddRow (TupleRow * row)
Definition at line 227 of file data-stream-sender.cc.
References impala::Tuple::DeepCopy(), impala::TupleRow::GetTuple(), impala::OK, RETURN_IF_ERROR, impala::row_desc_, impala::TupleRow::SetTuple(), impala::RowDescriptor::tuple_descriptors(), and UNLIKELY.
void impala::DataStreamSender::Channel::Close (RuntimeState * state)
Definition at line 303 of file data-stream-sender.cc.
References impala::RuntimeState::LogError(), impala::Status::msg(), and impala::Status::ok().
Status impala::DataStreamSender::Channel::CloseInternal () private
Definition at line 270 of file data-stream-sender.cc.
References impala::ClientConnection< T >::DoRpc(), impala::ErrorMsg::msg(), impala::Status::msg(), impala::Status::ok(), RETURN_IF_ERROR, and VLOG_RPC.
Status impala::DataStreamSender::Channel::GetSendStatus ()
Definition at line 262 of file data-stream-sender.cc.
Status impala::DataStreamSender::Channel::Init (RuntimeState * state)
Definition at line 151 of file data-stream-sender.cc.
References impala::RowDescriptor::GetRowSize(), impala::RuntimeState::impalad_client_cache(), impala::OK, and impala::row_desc_.
int64_t impala::DataStreamSender::Channel::num_data_bytes_sent () const inline
Definition at line 104 of file data-stream-sender.cc.
Status impala::DataStreamSender::Channel::SendBatch (TRowBatch * batch)
Definition at line 159 of file data-stream-sender.cc.
References impala::OK, RETURN_IF_ERROR, and VLOG_ROW.
Referenced by impala::DataStreamSender::Send().
Status impala::DataStreamSender::Channel::SendCurrentBatch () private
Definition at line 252 of file data-stream-sender.cc.
References impala::OK, and RETURN_IF_ERROR.
TRowBatch* impala::DataStreamSender::Channel::thrift_batch () inline
Definition at line 105 of file data-stream-sender.cc.
Referenced by impala::DataStreamSender::Send().
void impala::DataStreamSender::Channel::TransmitData (int thread_id, const TRowBatch * batch) private
Definition at line 175 of file data-stream-sender.cc.
void impala::DataStreamSender::Channel::TransmitDataHelper (const TRowBatch * batch) private
Definition at line 186 of file data-stream-sender.cc.
References impala::ClientConnection< T >::DoRpc(), impala::OK, SCOPED_TIMER, and VLOG_ROW.
void impala::DataStreamSender::Channel::WaitForRpc ()
Definition at line 219 of file data-stream-sender.cc.
References SCOPED_TIMER.
Referenced by impala::DataStreamSender::Send().
Member Data Documentation
TNetworkAddress impala::DataStreamSender::Channel::address_ private
Definition at line 114 of file data-stream-sender.cc.
scoped_ptr<RowBatch> impala::DataStreamSender::Channel::batch_ private
Definition at line 122 of file data-stream-sender.cc.
int impala::DataStreamSender::Channel::buffer_size_ private
Definition at line 109 of file data-stream-sender.cc.
ImpalaInternalServiceClientCache* impala::DataStreamSender::Channel::client_cache_ private
Definition at line 111 of file data-stream-sender.cc.
PlanNodeId impala::DataStreamSender::Channel::dest_node_id_ private
Definition at line 116 of file data-stream-sender.cc.
TUniqueId impala::DataStreamSender::Channel::fragment_instance_id_ private
Definition at line 115 of file data-stream-sender.cc.
int64_t impala::DataStreamSender::Channel::num_data_bytes_sent_ private
Definition at line 119 of file data-stream-sender.cc.
DataStreamSender* impala::DataStreamSender::Channel::parent_ private
Definition at line 108 of file data-stream-sender.cc.
const RowDescriptor& impala::DataStreamSender::Channel::row_desc_ private
Definition at line 113 of file data-stream-sender.cc.
condition_variable impala::DataStreamSender::Channel::rpc_done_cv_ private
Definition at line 132 of file data-stream-sender.cc.
bool impala::DataStreamSender::Channel::rpc_in_flight_ private
Definition at line 134 of file data-stream-sender.cc.
Status impala::DataStreamSender::Channel::rpc_status_ private
Definition at line 136 of file data-stream-sender.cc.
ThreadPool<TRowBatch*> impala::DataStreamSender::Channel::rpc_thread_ private
Definition at line 131 of file data-stream-sender.cc.
mutex impala::DataStreamSender::Channel::rpc_thread_lock_ private
Definition at line 133 of file data-stream-sender.cc.
TRowBatch impala::DataStreamSender::Channel::thrift_batch_ private
Definition at line 123 of file data-stream-sender.cc.
The documentation for this class was generated from the following file:
be/src/runtime/data-stream-sender.cc