Impala: com.cloudera.impala.catalog.CatalogTest Class Reference
com.cloudera.impala.catalog.CatalogTest Class Reference
Public Member Functions
void TestColSchema () throws CatalogException
void TestPartitions () throws CatalogException
void testStats () throws TableLoadingException
void testColStatsColTypeMismatch () throws Exception
void testInternalHBaseTable () throws CatalogException
void testDatabaseDoesNotExist ()
void testCreateTableMetadata () throws CatalogException
void testLoadingUnsupportedTableTypes () throws CatalogException
void TestTableWithBadEscapeChar () throws CatalogException
void TestUdf () throws CatalogException
Private Member Functions
void checkTableCols (Db db, String tblName, int numClusteringCols, String[] colNames, Type[] colTypes) throws TableLoadingException
void checkHBaseTableCols (Db db, String hiveTableName, String hbaseTableName, String[] hiveColNames, String[] colFamilies, String[] colQualifiers, Type[] colTypes) throws TableLoadingException
void assertStatsUnknown (Column column)
List< String > getFunctionSignatures (String db) throws DatabaseNotFoundException
Static Private Attributes
static CatalogServiceCatalog catalog_
Detailed Description
Definition at line 29 of file CatalogTest.java.
Member Function Documentation
void com.cloudera.impala.catalog.CatalogTest.assertStatsUnknown (Column column) inline private
Definition at line 436 of file CatalogTest.java.
References com.cloudera.impala.catalog.Column.getStats().
Referenced by com.cloudera.impala.catalog.CatalogTest.testColStatsColTypeMismatch().
void com.cloudera.impala.catalog.CatalogTest.checkHBaseTableCols (Db db, String hiveTableName, String hbaseTableName, String[] hiveColNames, String[] colFamilies, String[] colQualifiers, Type[] colTypes) throws TableLoadingException inline private
Definition at line 51 of file CatalogTest.java.
References com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.catalog.HBaseColumn.getColumnFamily(), com.cloudera.impala.catalog.HBaseColumn.getColumnQualifier(), and com.cloudera.impala.catalog.HBaseTable.getHBaseTableName().
Referenced by com.cloudera.impala.catalog.CatalogTest.TestColSchema().
void com.cloudera.impala.catalog.CatalogTest.checkTableCols (Db db, String tblName, int numClusteringCols, String[] colNames, Type[] colTypes) throws TableLoadingException inline private
Definition at line 33 of file CatalogTest.java.
References com.cloudera.impala.catalog.Column.getName(), com.cloudera.impala.catalog.Table.getName(), com.cloudera.impala.catalog.Table.getNumClusteringCols(), and com.cloudera.impala.catalog.Column.getType().
Referenced by com.cloudera.impala.catalog.CatalogTest.checkHBaseTableCols(), and com.cloudera.impala.catalog.CatalogTest.TestColSchema().
List<String> com.cloudera.impala.catalog.CatalogTest.getFunctionSignatures (String db) throws DatabaseNotFoundException inline private
Definition at line 517 of file CatalogTest.java.
Referenced by com.cloudera.impala.catalog.CatalogTest.TestUdf().
void com.cloudera.impala.catalog.CatalogTest.TestColSchema () throws CatalogException inline
Definition at line 71 of file CatalogTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.CatalogTest.catalog_, com.cloudera.impala.catalog.CatalogTest.checkHBaseTableCols(), com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.Db.getName(), com.cloudera.impala.catalog.CatalogServiceCatalog.getOrLoadTable(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.Type.TIMESTAMP, and com.cloudera.impala.catalog.Type.TINYINT.
void com.cloudera.impala.catalog.CatalogTest.testColStatsColTypeMismatch () throws Exception inline
Verifies that updating column stats data for a type that isn't compatible with the column type results in the stats being set to "unknown". This is a regression test for IMPALA-588, where this used to result in a Preconditions failure.
Definition at line 395 of file CatalogTest.java.
References com.cloudera.impala.catalog.CatalogTest.assertStatsUnknown(), com.cloudera.impala.catalog.CatalogTest.catalog_, com.cloudera.impala.catalog.Table.getColumn(), and com.cloudera.impala.catalog.CatalogServiceCatalog.getOrLoadTable().
void com.cloudera.impala.catalog.CatalogTest.testCreateTableMetadata () throws CatalogException inline
Definition at line 461 of file CatalogTest.java.
void com.cloudera.impala.catalog.CatalogTest.testDatabaseDoesNotExist () inline
Definition at line 455 of file CatalogTest.java.
void com.cloudera.impala.catalog.CatalogTest.testInternalHBaseTable () throws CatalogException inline
Definition at line 447 of file CatalogTest.java.
References com.cloudera.impala.catalog.CatalogTest.catalog_, and com.cloudera.impala.catalog.CatalogServiceCatalog.getOrLoadTable().
void com.cloudera.impala.catalog.CatalogTest.testLoadingUnsupportedTableTypes () throws CatalogException inline
Definition at line 476 of file CatalogTest.java.
References com.cloudera.impala.catalog.IncompleteTable.getCause().
void com.cloudera.impala.catalog.CatalogTest.TestPartitions () throws CatalogException inline
Definition at line 268 of file CatalogTest.java.
References com.cloudera.impala.catalog.CatalogTest.catalog_, and com.cloudera.impala.catalog.CatalogServiceCatalog.getOrLoadTable().
void com.cloudera.impala.catalog.CatalogTest.testStats () throws TableLoadingException inline
Definition at line 305 of file CatalogTest.java.
References com.cloudera.impala.catalog.PrimitiveType.BIGINT, com.cloudera.impala.catalog.PrimitiveType.BOOLEAN, com.cloudera.impala.catalog.CatalogTest.catalog_, com.cloudera.impala.catalog.PrimitiveType.DOUBLE, com.cloudera.impala.catalog.PrimitiveType.FLOAT, com.cloudera.impala.catalog.Catalog.getDb(), com.cloudera.impala.catalog.Column.getStats(), com.cloudera.impala.catalog.PrimitiveType.INT, com.cloudera.impala.catalog.PrimitiveType.SMALLINT, com.cloudera.impala.catalog.PrimitiveType.STRING, com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP, and com.cloudera.impala.catalog.PrimitiveType.TINYINT.
void com.cloudera.impala.catalog.CatalogTest.TestTableWithBadEscapeChar () throws CatalogException inline
Definition at line 507 of file CatalogTest.java.
References com.cloudera.impala.catalog.CatalogTest.catalog_, com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_ESCAPE_CHAR, com.cloudera.impala.catalog.HdfsStorageDescriptor.getEscapeChar(), and com.cloudera.impala.catalog.CatalogServiceCatalog.getOrLoadTable().
void com.cloudera.impala.catalog.CatalogTest.TestUdf () throws CatalogException inline
Definition at line 527 of file CatalogTest.java.
References com.cloudera.impala.catalog.CatalogTest.getFunctionSignatures(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.INVALID, and com.cloudera.impala.catalog.Type.TINYINT.
Member Data Documentation
CatalogServiceCatalog com.cloudera.impala.catalog.CatalogTest.catalog_ static private
Initial value:
=
      CatalogServiceTestCatalog.create()
Definition at line 30 of file CatalogTest.java.
Referenced by com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.catalog.CatalogTest.testColStatsColTypeMismatch(), com.cloudera.impala.catalog.CatalogTest.testInternalHBaseTable(), com.cloudera.impala.catalog.CatalogTest.TestPartitions(), com.cloudera.impala.catalog.CatalogTest.testStats(), and com.cloudera.impala.catalog.CatalogTest.TestTableWithBadEscapeChar().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/catalog/CatalogTest.java