Impala: impala::ScanNode Class Reference
impala::ScanNode Class Reference abstract
Abstract base class of all scan nodes; introduces SetScanRange().
#include <scan-node.h>
Public Member Functions
ScanNode (ObjectPool *pool, const TPlanNode &tnode, const DescriptorTbl &descs)
virtual Status Prepare (RuntimeState *state)
void SetScanRanges (const std::vector< TScanRangeParams > &scan_range_params)
virtual bool IsScanNode () const
RuntimeProfile::Counter * bytes_read_counter () const
RuntimeProfile::Counter * rows_read_counter () const
RuntimeProfile::Counter * read_timer () const
RuntimeProfile::Counter * total_throughput_counter () const
RuntimeProfile::Counter * per_read_thread_throughput_counter () const
RuntimeProfile::Counter * materialize_tuple_timer () const
RuntimeProfile::Counter * scan_ranges_complete_counter () const
RuntimeProfile::ThreadCounters * scanner_thread_counters () const
RuntimeProfile::Counter & active_scanner_thread_counter ()
RuntimeProfile::Counter * average_scanner_thread_concurrency () const
virtual Status Init (const TPlanNode &tnode)
virtual Status Open (RuntimeState *state)
virtual Status GetNext (RuntimeState *state, RowBatch *row_batch, bool *eos)=0
virtual Status Reset (RuntimeState *state)
virtual void Close (RuntimeState *state)
void CollectNodes (TPlanNodeType::type node_type, std::vector< ExecNode * > *nodes)
void CollectScanNodes (std::vector< ExecNode * > *nodes)
Collect all scan node types.
std::string DebugString () const
Returns a string representation in DFS order of the plan rooted at this.
virtual void DebugString (int indentation_level, std::stringstream *out) const
const std::vector< ExprContext * > & conjunct_ctxs () const
int id () const
TPlanNodeType::type type () const
const RowDescriptor & row_desc () const
int64_t rows_returned () const
int64_t limit () const
bool ReachedLimit ()
RuntimeProfile * runtime_profile ()
MemTracker * mem_tracker ()
MemTracker * expr_mem_tracker ()
Static Public Member Functions
static Status CreateTree (ObjectPool *pool, const TPlan &plan, const DescriptorTbl &descs, ExecNode **root)
static void SetDebugOptions (int node_id, TExecNodePhase::type phase, TDebugAction::type action, ExecNode *tree)
Set debug action for node with given id in 'tree'.
static bool EvalConjuncts (ExprContext *const *ctxs, int num_ctxs, TupleRow *row)
static llvm::Function * CodegenEvalConjuncts (RuntimeState *state, const std::vector< ExprContext * > &conjunct_ctxs, const char *name="EvalConjuncts")
static int GetNodeIdFromProfile (RuntimeProfile *p)
Extract node id from p->name().
Static Public Attributes
static const std::string BYTES_READ_COUNTER = "BytesRead"
names of ScanNode common counters
static const std::string ROWS_READ_COUNTER = "RowsRead"
static const std::string TOTAL_HDFS_READ_TIMER = "TotalRawHdfsReadTime(*)"
static const std::string TOTAL_HBASE_READ_TIMER = "TotalRawHBaseReadTime(*)"
static const std::string TOTAL_THROUGHPUT_COUNTER = "TotalReadThroughput"
static const std::string PER_READ_THREAD_THROUGHPUT_COUNTER
static const std::string NUM_DISKS_ACCESSED_COUNTER = "NumDisksAccessed"
static const std::string MATERIALIZE_TUPLE_TIMER = "MaterializeTupleTime(*)"
static const std::string SCAN_RANGES_COMPLETE_COUNTER = "ScanRangesComplete"
static const std::string SCANNER_THREAD_COUNTERS_PREFIX = "ScannerThreads"
static const std::string SCANNER_THREAD_TOTAL_WALLCLOCK_TIME
static const std::string AVERAGE_SCANNER_THREAD_CONCURRENCY
static const std::string AVERAGE_HDFS_READ_THREAD_CONCURRENCY
static const std::string NUM_SCANNER_THREADS_STARTED
static const std::string ROW_THROUGHPUT_COUNTER = "RowsReturnedRate"
Names of counters shared by all exec nodes.
Protected Member Functions
ExecNode * child (int i)
bool is_closed ()
void InitRuntimeProfile (const std::string &name)
Status ExecDebugAction (TExecNodePhase::type phase, RuntimeState *state)
void AddRuntimeExecOption (const std::string &option)
Appends option to 'runtime_exec_options_'.
virtual Status QueryMaintenance (RuntimeState *state)
void AddExprCtxToFree (ExprContext *ctx)
void AddExprCtxsToFree (const std::vector< ExprContext * > &ctxs)
void AddExprCtxsToFree (const SortExecExprs &sort_exec_exprs)
Static Protected Member Functions
static Status CreateNode (ObjectPool *pool, const TPlanNode &tnode, const DescriptorTbl &descs, ExecNode **node)
Create a single exec node derived from thrift node; place exec node in 'pool'.
static Status CreateTreeHelper (ObjectPool *pool, const std::vector< TPlanNode > &tnodes, const DescriptorTbl &descs, ExecNode *parent, int *node_idx, ExecNode **root)
Protected Attributes
const std::vector
< TScanRangeParams > * scan_range_params_
The scan ranges this scan node is responsible for. Not owned.
RuntimeProfile::Counter * bytes_read_counter_
RuntimeProfile::TimeSeriesCounter * bytes_read_timeseries_counter_
Time series of the bytes_read_counter_.
RuntimeProfile::Counter * rows_read_counter_
rows/tuples read from the scanner (including those discarded by EvalConjucts())
RuntimeProfile::Counter * read_timer_
RuntimeProfile::Counter * total_throughput_counter_
Wall based aggregate read throughput [bytes/sec].
RuntimeProfile::Counter * per_read_thread_throughput_counter_
Per thread read throughput [bytes/sec].
RuntimeProfile::Counter * num_disks_accessed_counter_
RuntimeProfile::Counter * materialize_tuple_timer_
RuntimeProfile::Counter * scan_ranges_complete_counter_
RuntimeProfile::ThreadCounters * scanner_thread_counters_
Aggregated scanner thread counters.
RuntimeProfile::Counter active_scanner_thread_counter_
The number of active scanner threads that are not blocked by IO.
RuntimeProfile::Counter * average_scanner_thread_concurrency_
RuntimeProfile::Counter active_hdfs_read_thread_counter_
The number of active hdfs reading threads reading for this node.
RuntimeProfile::Counter * average_hdfs_read_thread_concurrency_
RuntimeProfile::Counter * num_scanner_threads_started_counter_
std::vector
< RuntimeProfile::Counter * > hdfs_read_thread_concurrency_bucket_
int id_
TPlanNodeType::type type_
ObjectPool * pool_
std::vector< ExprContext * > conjunct_ctxs_
std::vector< ExecNode * > children_
RowDescriptor row_descriptor_
TExecNodePhase::type debug_phase_
TDebugAction::type debug_action_
int64_t limit_
int64_t num_rows_returned_
boost::scoped_ptr< RuntimeProfile > runtime_profile_
RuntimeProfile::Counter * rows_returned_counter_
RuntimeProfile::Counter * rows_returned_rate_
boost::scoped_ptr< MemTracker > mem_tracker_
Account for peak memory used by this node.
boost::scoped_ptr< MemTracker > expr_mem_tracker_
MemTracker that should be used for ExprContexts.
boost::mutex exec_options_lock_
std::string runtime_exec_options_
Detailed Description
Abstract base class of all scan nodes; introduces SetScanRange().
Includes ScanNode common counters: BytesRead - total bytes read by this scan node. Provided as a counter as well as a time series that samples the counter. TotalRawReadTime - it measures the total time spent in underlying reads. For HDFS files, this is the time in the disk-io-mgr's reading threads for this node. For example, if we have 3 reading threads and each spent 1 sec, this counter will report 3 sec. For HBase, this is the time spent in the region server. TotalReadThroughput - BytesRead divided by the total time spent in this node (from Open to Close). For IO bounded queries, this should be very close to the total throughput of all the disks. PerDiskRawHdfsThroughput - the read throughput for each disk. If all the data reside on disk, this should be the read throughput the disk, regardless of whether the query is IO bounded or not. NumDisksAccessed - number of disks accessed. AverageScannerThreadConcurrency - the average number of active scanner threads. A scanner thread is considered active if it is not blocked by IO. This number would be low (less than 1) for IO-bound queries. For cpu-bound queries, this number would be close to the max scanner threads allowed. AverageHdfsReadThreadConcurrency - the average number of active hdfs reading threads reading for this scan node. For IO bound queries, this should be close to the number of disk. Hdfs Read Thread Concurrency Bucket - the bucket counting (%) of hdfs read thread concurrency. NumScannerThreadsStarted - the number of scanner threads started for the duration of the ScanNode. This is at most the number of scan ranges but should be much less since a single scanner thread will likely process multiple scan ranges. ScanRangesComplete - number of scan ranges completed MaterializeTupleTime - time spent in creating in-memory tuple format ScannerThreadsTotalWallClockTime - total time spent in all scanner threads. ScannerThreadsUserTime, ScannerThreadsSysTime, ScannerThreadsVoluntaryContextSwitches, ScannerThreadsInvoluntaryContextSwitches - these are aggregated counters across all scanner threads of this scan node. They are taken from getrusage. See RuntimeProfile::ThreadCounters for details.
Definition at line 77 of file scan-node.h.
Constructor & Destructor Documentation
impala::ScanNode::ScanNode (ObjectPool * pool, const TPlanNode & tnode, const DescriptorTbl & descs) inline
Definition at line 79 of file scan-node.h.
Member Function Documentation
RuntimeProfile::Counter& impala::ScanNode::active_scanner_thread_counter () inline
Definition at line 113 of file scan-node.h.
References active_scanner_thread_counter_.
void impala::ExecNode::AddExprCtxsToFree (const std::vector< ExprContext * > & ctxs) protected inherited
Referenced by impala::ExecNode::AddExprCtxsToFree(), impala::UnionNode::Prepare(), impala::SortNode::Prepare(), impala::TopNNode::Prepare(), impala::ExchangeNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), and impala::HdfsScanNode::Prepare().
void impala::ExecNode::AddExprCtxsToFree (const SortExecExprs & sort_exec_exprs) protected inherited
Definition at line 410 of file exec-node.cc.
References impala::ExecNode::AddExprCtxsToFree(), impala::SortExecExprs::lhs_ordering_expr_ctxs(), impala::SortExecExprs::rhs_ordering_expr_ctxs(), and impala::SortExecExprs::sort_tuple_slot_expr_ctxs().
void impala::ExecNode::AddExprCtxToFree (ExprContext * ctx) inline protected inherited
Add an ExprContext to have its local allocations freed by QueryMaintenance(). Exprs that are evaluated in the main execution thread should be added. Exprs evaluated in a separate thread are generally not safe to add, since a local allocation may be freed while it's being used. Rather than using this mechanism, threads should call FreeLocalAllocations() on local ExprContexts periodically.
Definition at line 276 of file exec-node.h.
References impala::ExecNode::expr_ctxs_to_free_.
Referenced by impala::AnalyticEvalNode::Prepare().
void impala::ExecNode::AddRuntimeExecOption (const std::string & option) protected inherited
Appends option to 'runtime_exec_options_'.
Definition at line 188 of file exec-node.cc.
References impala::RuntimeProfile::AddInfoString(), impala::ExecNode::exec_options_lock_, impala::ExecNode::runtime_exec_options_, and impala::ExecNode::runtime_profile().
Referenced by impala::PartitionedHashJoinNode::AttachProbeFilters(), impala::HashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::Open(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), and impala::HdfsScanNode::StopAndFinalizeCounters().
RuntimeProfile::Counter* impala::ScanNode::average_scanner_thread_concurrency () const inline
Definition at line 116 of file scan-node.h.
References average_scanner_thread_concurrency_.
RuntimeProfile::Counter* impala::ScanNode::bytes_read_counter () const inline
Definition at line 95 of file scan-node.h.
References bytes_read_counter_.
Referenced by impala::HBaseTableScanner::GetFamily(), impala::HBaseTableScanner::GetQualifier(), impala::HBaseTableScanner::GetRowKey(), impala::HBaseTableScanner::GetValue(), impala::HdfsScanNode::Open(), and impala::HdfsScanNode::StopAndFinalizeCounters().
ExecNode* impala::ExecNode::child (int i) inline protected inherited
Definition at line 241 of file exec-node.h.
References impala::ExecNode::children_.
Referenced by impala::CrossJoinNode::BuildListDebugString(), impala::BlockingJoinNode::BuildSideThread(), impala::HashJoinNode::CodegenCreateOutputRow(), impala::PartitionedHashJoinNode::CodegenCreateOutputRow(), impala::CrossJoinNode::ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::PartitionedHashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::GetLeftChildRowString(), impala::SelectNode::GetNext(), impala::UnionNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::PartitionedAggregationNode::Partition::InitStreams(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::SelectNode::Open(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::SelectNode::Prepare(), impala::SortNode::Prepare(), impala::UnionNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::AnalyticEvalNode::ProcessChildBatches(), and impala::SortNode::SortInput().
void impala::ExecNode::Close (RuntimeState * state) virtual inherited
Close() will get called for every exec node, regardless of what else is called and the status of these calls (i.e. Prepare() may never have been called, or Prepare()/Open()/GetNext() returned with an error). Close() releases all resources that were allocated in Open()/GetNext(), even if the latter ended with an error. Close() can be called if the node has been prepared or the node is closed. The default implementation updates runtime profile counters and calls Close() on the children. Subclasses should check if the node has already been closed (is_closed()), then close themselves, then call the base Close(). Nodes that are using tuples returned by a child may call Close() on their children before their own Close() if the child node has returned eos. It is only safe to call Close() on the child node while the parent node is still returning rows if the parent node fully materializes the child's input.
Reimplemented in impala::HdfsScanNode, impala::PartitionedAggregationNode, impala::AnalyticEvalNode, impala::PartitionedHashJoinNode, impala::BlockingJoinNode, impala::AggregationNode, impala::DataSourceScanNode, impala::HashJoinNode, impala::CrossJoinNode, impala::HBaseScanNode, impala::ExchangeNode, impala::TopNNode, impala::SortNode, impala::UnionNode, and impala::SelectNode.
Definition at line 166 of file exec-node.cc.
References impala::ExecNode::children_, impala::Expr::Close(), impala::ExecNode::conjunct_ctxs_, COUNTER_SET, impala::RuntimeState::instance_mem_tracker(), impala::ExecNode::is_closed_, impala::MemTracker::LogUsage(), impala::ExecNode::mem_tracker(), impala::ExecNode::num_rows_returned_, impala::RuntimeState::query_id(), and impala::ExecNode::rows_returned_counter_.
Referenced by impala::BlockingJoinNode::BuildSideThread(), impala::SelectNode::Close(), impala::UnionNode::Close(), impala::SortNode::Close(), impala::TopNNode::Close(), impala::ExchangeNode::Close(), impala::HBaseScanNode::Close(), impala::AggregationNode::Close(), impala::BlockingJoinNode::Close(), impala::AnalyticEvalNode::Close(), impala::PartitionedAggregationNode::Close(), impala::PlanFragmentExecutor::Close(), impala::HdfsScanNode::Close(), impala::UnionNode::GetNext(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::AggregationNode::Open(), and impala::PartitionedAggregationNode::Open().
Function * impala::ExecNode::CodegenEvalConjuncts (RuntimeState * state, const std::vector< ExprContext * > & conjunct_ctxs, const char * name = "EvalConjuncts") static inherited
Returns a codegen'd version of EvalConjuncts(), or NULL if the function couldn't be codegen'd. The codegen'd version uses inlined, codegen'd GetBooleanVal() functions.
Definition at line 452 of file exec-node.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::LlvmCodeGen::context(), impala::CodegenAnyVal::CreateCallWrapped(), impala::LlvmCodeGen::false_value(), impala::LlvmCodeGen::FinalizeFunction(), impala::RuntimeState::GetCodegen(), impala::Status::GetDetail(), impala::CodegenAnyVal::GetIsNull(), impala::LlvmCodeGen::GetType(), impala::CodegenAnyVal::GetVal(), impala::TupleRow::LLVM_CLASS_NAME, impala::ExprContext::LLVM_CLASS_NAME, impala::Status::ok(), impala::LlvmCodeGen::true_value(), impala::ExecNode::type(), impala::TYPE_BOOLEAN, impala::TYPE_INT, and VLOG_QUERY.
Referenced by impala::HdfsAvroScanner::CodegenDecodeAvroData(), impala::HashJoinNode::CodegenProcessProbeBatch(), and impala::PartitionedHashJoinNode::CodegenProcessProbeBatch().
void impala::ExecNode::CollectNodes (TPlanNodeType::type node_type, std::vector< ExecNode * > * nodes) inherited
Collect all nodes of given 'node_type' that are part of this subtree, and return in 'nodes'.
Definition at line 359 of file exec-node.cc.
References impala::ExecNode::children_, and impala::ExecNode::type_.
Referenced by impala::ExecNode::CollectScanNodes(), and impala::PlanFragmentExecutor::Prepare().
void impala::ExecNode::CollectScanNodes (std::vector< ExecNode * > * nodes) inherited
Collect all scan node types.
Definition at line 366 of file exec-node.cc.
References impala::ExecNode::CollectNodes().
Referenced by impala::PlanFragmentExecutor::Prepare().
const std::vector<ExprContext*>& impala::ExecNode::conjunct_ctxs () const inline inherited
Definition at line 152 of file exec-node.h.
References impala::ExecNode::conjunct_ctxs_.
Referenced by impala::HdfsScanNode::ComputeSlotMaterializationOrder(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HashJoinNode::GetNext(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
Status impala::ExecNode::CreateNode (ObjectPool * pool, const TPlanNode & tnode, const DescriptorTbl & descs, ExecNode ** node) static protected inherited
Create a single exec node derived from thrift node; place exec node in 'pool'.
Definition at line 260 of file exec-node.cc.
References impala::ObjectPool::Add(), impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::ExecNode::CreateTreeHelper().
Status impala::ExecNode::CreateTree (ObjectPool * pool, const TPlan & plan, const DescriptorTbl & descs, ExecNode ** root) static inherited
Creates exec node tree from list of nodes contained in plan via depth-first traversal. All nodes are placed in pool. Returns error if 'plan' is corrupted, otherwise success.
Definition at line 199 of file exec-node.cc.
References impala::ExecNode::CreateTreeHelper(), impala::Status::OK, and impala::Status::ok().
Referenced by impala::PlanFragmentExecutor::Prepare().
Status impala::ExecNode::CreateTreeHelper (ObjectPool * pool, const std::vector< TPlanNode > & tnodes, const DescriptorTbl & descs, ExecNode * parent, int * node_idx, ExecNode ** root) static protected inherited
Definition at line 218 of file exec-node.cc.
References impala::RuntimeProfile::AddChild(), impala::ExecNode::children_, impala::ExecNode::CreateNode(), impala::Status::OK, RETURN_IF_ERROR, and impala::ExecNode::runtime_profile().
Referenced by impala::ExecNode::CreateTree().
string impala::ExecNode::DebugString () const inherited
Returns a string representation in DFS order of the plan rooted at this.
Definition at line 345 of file exec-node.cc.
Referenced by impala::SortNode::DebugString(), impala::TopNNode::DebugString(), impala::ExchangeNode::DebugString(), impala::AggregationNode::DebugString(), impala::AnalyticEvalNode::DebugString(), impala::PartitionedAggregationNode::DebugString(), impala::BlockingJoinNode::DebugString(), and impala::PlanFragmentExecutor::Prepare().
virtual void impala::ExecNode::DebugString (int indentation_level, std::stringstream * out) const virtual inherited
Recursive helper method for generating a string for DebugString(). Implementations should call DebugString(int, std::stringstream) on their children. Input parameters: indentation_level: Current level in plan tree. Output parameters: out: Stream to accumulate debug string.
Reimplemented in impala::BlockingJoinNode, impala::PartitionedAggregationNode, impala::AnalyticEvalNode, impala::AggregationNode, impala::DataSourceScanNode, impala::ExchangeNode, impala::HBaseScanNode, impala::TopNNode, and impala::SortNode.
bool impala::ExecNode::EvalConjuncts (ExprContext *const * ctxs, int num_ctxs, TupleRow * row) static inherited
Evaluate ExprContexts over row. Returns true if all exprs return true. TODO: This doesn't use the vector<Expr*> signature because I haven't figured out how to deal with declaring a templated std:vector type in IR
Definition at line 393 of file exec-node.cc.
References impala::ExprContext::GetBooleanVal(), impala_udf::AnyVal::is_null, and impala_udf::BooleanVal::val.
Referenced by impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HdfsScanner::EvalConjuncts(), EvalOtherJoinConjuncts(), EvalOtherJoinConjuncts2(), impala::PartitionedHashJoinNode::EvaluateNullProbe(), impala::HBaseScanNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::PartitionedHashJoinNode::OutputNullAwareProbeRows(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), impala::CrossJoinNode::ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
Status impala::ExecNode::ExecDebugAction (TExecNodePhase::type phase, RuntimeState * state) protected inherited
Executes debug_action_ if phase matches debug_phase_. 'phase' must not be INVALID.
Definition at line 378 of file exec-node.cc.
References impala::Status::CANCELLED, impala::ExecNode::debug_action_, impala::ExecNode::debug_phase_, impala::RuntimeState::is_cancelled(), and impala::Status::OK.
Referenced by impala::SelectNode::GetNext(), impala::SortNode::GetNext(), impala::UnionNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExecNode::Open(), and impala::ExecNode::Prepare().
MemTracker* impala::ExecNode::expr_mem_tracker () inline inherited
Definition at line 163 of file exec-node.h.
References impala::ExecNode::expr_mem_tracker_.
Referenced by impala::PartitionedAggregationNode::Partition::InitStreams(), impala::SortNode::Prepare(), impala::UnionNode::Prepare(), impala::TopNNode::Prepare(), impala::ExchangeNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), and impala::HdfsScanNode::Prepare().
virtual Status impala::ExecNode::GetNext (RuntimeState * state, RowBatch * row_batch, bool * eos) pure virtual inherited
Retrieves rows and returns them via row_batch. Sets eos to true if subsequent calls will not retrieve any more rows. Data referenced by any tuples returned in row_batch must not be overwritten by the callee until Close() is called. The memory holding that data can be returned via row_batch's tuple_data_pool (in which case it may be deleted by the caller) or held on to by the callee. The row_batch, including its tuple_data_pool, will be destroyed by the caller at some point prior to the final Close() call. In other words, if the memory holding the tuple data will be referenced by the callee in subsequent GetNext() calls, it must not be attached to the row_batch's tuple_data_pool. Caller must not be holding any io buffers. This will cause deadlock. TODO: AggregationNode and HashJoinNode cannot be "re-opened" yet.
Implemented in impala::HdfsScanNode, impala::PartitionedAggregationNode, impala::AnalyticEvalNode, impala::PartitionedHashJoinNode, impala::AggregationNode, impala::HashJoinNode, impala::DataSourceScanNode, impala::CrossJoinNode, impala::ExchangeNode, impala::TopNNode, impala::HBaseScanNode, impala::SortNode, impala::UnionNode, impala::SelectNode, and impala::EmptySetNode.
Referenced by impala::PlanFragmentExecutor::GetNextInternal(), and impala::BlockingJoinNode::Open().
int impala::ExecNode::GetNodeIdFromProfile (RuntimeProfile * p) static inherited
Extract node id from p->name().
Definition at line 62 of file exec-node.cc.
References impala::RuntimeProfile::metadata().
int impala::ExecNode::id () const inline inherited
Definition at line 154 of file exec-node.h.
References impala::ExecNode::id_.
Referenced by impala::AnalyticEvalNode::AddResultTuple(), impala::AnalyticEvalNode::AddRow(), impala::AnalyticEvalNode::AnalyticEvalNode(), impala::AnalyticEvalNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::HdfsScanner::InitializeWriteTuplesFn(), impala::HdfsAvroScanner::InitNewRange(), impala::AnalyticEvalNode::InitNextPartition(), impala::PartitionedAggregationNode::MoveHashPartitions(), impala::PartitionedHashJoinNode::NodeDebugString(), impala::AnalyticEvalNode::Open(), impala::HdfsScanNode::Open(), impala::PlanFragmentExecutor::Prepare(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::AnalyticEvalNode::ProcessChildBatch(), impala::HdfsScanNode::ScannerThread(), impala::AnalyticEvalNode::TryAddRemainingResults(), impala::AnalyticEvalNode::TryAddResultTupleForCurrRow(), impala::AnalyticEvalNode::TryAddResultTupleForPrevRow(), and impala::AnalyticEvalNode::TryRemoveRowsBeforeWindow().
Status impala::ExecNode::Init (const TPlanNode & tnode) virtual inherited
Initializes this object from the thrift tnode desc. The subclass should do any initialization that can fail in Init() rather than the ctor. If overridden in subclass, must first call superclass's Init().
Reimplemented in impala::PartitionedAggregationNode, impala::AnalyticEvalNode, impala::PartitionedHashJoinNode, impala::AggregationNode, impala::HashJoinNode, impala::BlockingJoinNode, impala::ExchangeNode, impala::TopNNode, impala::SortNode, and impala::UnionNode.
Definition at line 124 of file exec-node.cc.
References impala::ExecNode::conjunct_ctxs_, impala::Expr::CreateExprTrees(), impala::Status::OK, impala::ExecNode::pool_, and RETURN_IF_ERROR.
Referenced by impala::SortNode::Init(), impala::UnionNode::Init(), impala::TopNNode::Init(), impala::ExchangeNode::Init(), impala::BlockingJoinNode::Init(), impala::AggregationNode::Init(), impala::AnalyticEvalNode::Init(), and impala::PartitionedAggregationNode::Init().
void impala::ExecNode::InitRuntimeProfile (const std::string & name) protected inherited
Definition at line 371 of file exec-node.cc.
References impala::ExecNode::id_, impala::ExecNode::pool_, and impala::ExecNode::runtime_profile_.
Referenced by impala::ExecNode::ExecNode().
bool impala::ExecNode::is_closed () inline protected inherited
Definition at line 242 of file exec-node.h.
References impala::ExecNode::is_closed_.
Referenced by impala::SelectNode::Close(), impala::SortNode::Close(), impala::UnionNode::Close(), impala::TopNNode::Close(), impala::ExchangeNode::Close(), impala::HBaseScanNode::Close(), impala::CrossJoinNode::Close(), impala::HashJoinNode::Close(), impala::AggregationNode::Close(), impala::BlockingJoinNode::Close(), impala::AnalyticEvalNode::Close(), impala::PartitionedHashJoinNode::Close(), impala::PartitionedAggregationNode::Close(), impala::HdfsScanNode::Close(), impala::PartitionedAggregationNode::Partition::Close(), impala::PartitionedHashJoinNode::Partition::Close(), impala::PartitionedHashJoinNode::ReserveTupleStreamBlocks(), impala::PartitionedHashJoinNode::SpillPartition(), impala::PartitionedAggregationNode::SpillPartition(), and impala::PartitionedHashJoinNode::Partition::~Partition().
virtual bool impala::ScanNode::IsScanNode () const inline virtual
Reimplemented from impala::ExecNode.
Definition at line 93 of file scan-node.h.
int64_t impala::ExecNode::limit () const inline inherited
Definition at line 158 of file exec-node.h.
References impala::ExecNode::limit_.
Referenced by impala::CrossJoinNode::GetNext(), and impala::HashJoinNode::LeftJoinGetNext().
RuntimeProfile::Counter* impala::ScanNode::materialize_tuple_timer () const inline
Definition at line 104 of file scan-node.h.
References materialize_tuple_timer_.
Referenced by impala::HBaseScanNode::GetNext(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), and impala::HdfsTextScanner::WriteFields().
MemTracker* impala::ExecNode::mem_tracker () inline inherited
Definition at line 162 of file exec-node.h.
References impala::ExecNode::mem_tracker_.
Referenced by impala::ExecNode::Close(), impala::CrossJoinNode::ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::HdfsScanNode::EnoughMemoryForScannerThread(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::HdfsScanNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::SelectNode::Prepare(), impala::HBaseScanNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::PartitionedHashJoinNode::PrepareNextPartition(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::PartitionedAggregationNode::ProcessStream(), impala::HdfsRCFileScanner::ReadRowGroup(), impala::HdfsAvroScanner::ResolveSchemas(), impala::SortNode::SortInput(), and impala::HdfsScanner::StartNewRowBatch().
Status impala::ExecNode::Open (RuntimeState * state) virtual inherited
Performs any preparatory work prior to calling GetNext(). Caller must not be holding any io buffers. This will cause deadlock. If overridden in subclass, must first call superclass's Open(). If a parent exec node adds slot filters (see RuntimeState::AddBitmapFilter()), they need to be added before calling Open() on the child that will consume them.
Reimplemented in impala::HdfsScanNode, impala::PartitionedAggregationNode, impala::AnalyticEvalNode, impala::AggregationNode, impala::BlockingJoinNode, impala::DataSourceScanNode, impala::ExchangeNode, impala::TopNNode, impala::SortNode, impala::UnionNode, impala::HBaseScanNode, and impala::SelectNode.
Definition at line 154 of file exec-node.cc.
References impala::ExecNode::conjunct_ctxs_, impala::ExecNode::ExecDebugAction(), impala::Expr::Open(), and RETURN_IF_ERROR.
Referenced by impala::SelectNode::Open(), impala::HBaseScanNode::Open(), impala::SortNode::Open(), impala::UnionNode::Open(), impala::TopNNode::Open(), impala::ExchangeNode::Open(), impala::DataSourceScanNode::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::HdfsScanNode::Open(), and impala::PlanFragmentExecutor::OpenInternal().
RuntimeProfile::Counter* impala::ScanNode::per_read_thread_throughput_counter () const inline
Definition at line 101 of file scan-node.h.
References per_read_thread_throughput_counter_.
Status impala::ScanNode::Prepare (RuntimeState * state) virtual
Sets up internal structures, etc., without doing any actual work. Must be called prior to Open(). Will only be called once in this node's lifetime. All code generation (adding functions to the LlvmCodeGen object) must happen in Prepare(). Retrieving the jit compiled function pointer must happen in Open(). If overridden in subclass, must first call superclass's Prepare().
Reimplemented from impala::ExecNode.
Reimplemented in impala::HdfsScanNode, impala::DataSourceScanNode, and impala::HBaseScanNode.
Definition at line 44 of file scan-node.cc.
References ADD_CHILD_TIMER, ADD_COUNTER, ADD_THREAD_COUNTERS, ADD_TIME_SERIES_COUNTER, impala::RuntimeProfile::AddRateCounter(), BYTES_READ_COUNTER, bytes_read_counter_, bytes_read_timeseries_counter_, MATERIALIZE_TUPLE_TIMER, materialize_tuple_timer_, impala::Status::OK, impala::ExecNode::Prepare(), RETURN_IF_ERROR, ROWS_READ_COUNTER, rows_read_counter_, impala::ExecNode::runtime_profile(), impala::ExecNode::runtime_profile_, scanner_thread_counters_, SCANNER_THREAD_COUNTERS_PREFIX, SCANNER_THREAD_TOTAL_WALLCLOCK_TIME, SCOPED_TIMER, TOTAL_THROUGHPUT_COUNTER, and total_throughput_counter_.
Referenced by impala::HBaseScanNode::Prepare(), impala::DataSourceScanNode::Prepare(), and impala::HdfsScanNode::Prepare().
Status impala::ExecNode::QueryMaintenance (RuntimeState * state) protected virtual inherited
Frees any local allocations made by expr_ctxs_to_free_ and returns the result of state->CheckQueryState(). Nodes should call this periodically, e.g. once per input row batch. This should not be called outside the main execution thread. Nodes may override this to add extra periodic cleanup, e.g. freeing other local allocations. ExecNodes overriding this function should return ExecNode::QueryMaintenance().
Reimplemented in impala::PartitionedAggregationNode, and impala::AnalyticEvalNode.
Definition at line 401 of file exec-node.cc.
References impala::RuntimeState::CheckQueryState(), impala::ExecNode::expr_ctxs_to_free_, and impala::ExprContext::FreeLocalAllocations().
Referenced by impala::CrossJoinNode::ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::SelectNode::GetNext(), impala::SortNode::GetNext(), impala::UnionNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::HBaseScanNode::Open(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::AnalyticEvalNode::QueryMaintenance(), impala::PartitionedAggregationNode::QueryMaintenance(), and impala::SortNode::SortInput().
bool impala::ExecNode::ReachedLimit () inline inherited
Definition at line 159 of file exec-node.h.
References impala::ExecNode::limit_, and impala::ExecNode::num_rows_returned_.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HdfsTextScanner::FinishScanRange(), impala::SelectNode::GetNext(), impala::UnionNode::GetNext(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::ExchangeNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::HashJoinNode::LeftJoinGetNext(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), and impala::PlanFragmentExecutor::ReachedLimit().
RuntimeProfile::Counter* impala::ScanNode::read_timer () const inline
Definition at line 97 of file scan-node.h.
References read_timer_.
Referenced by impala::HBaseTableScanner::Next(), and impala::HdfsScanNode::Open().
Status impala::ExecNode::Reset (RuntimeState * state) virtual inherited
Resets all data-specific state, returning this node to the state it was in after calling Prepare() and before calling Open(). Prepare() must have already been called before calling Reset(). Open() and GetNext() may have optionally been called. Close() must not have been called. If overridden in a subclass, must call superclass's Reset() at the end. The default implementation calls Reset() on children. Note that this function may be called many times, so should be fast. For example, accumulated memory does not need to be freed on every call if it's expensive.
Reimplemented in impala::HdfsScanNode, impala::PartitionedAggregationNode, impala::AnalyticEvalNode, impala::PartitionedHashJoinNode, impala::AggregationNode, impala::BlockingJoinNode, impala::HashJoinNode, impala::DataSourceScanNode, impala::CrossJoinNode, impala::ExchangeNode, impala::HBaseScanNode, impala::TopNNode, impala::SortNode, impala::UnionNode, and impala::SelectNode.
Definition at line 159 of file exec-node.cc.
References impala::ExecNode::children_, impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::BlockingJoinNode::Reset().
const RowDescriptor& impala::ExecNode::row_desc () const inline inherited
Definition at line 156 of file exec-node.h.
References impala::ExecNode::row_descriptor_.
Referenced by impala::CrossJoinNode::BuildListDebugString(), impala::HashJoinNode::CodegenCreateOutputRow(), impala::PartitionedHashJoinNode::CodegenCreateOutputRow(), impala::CrossJoinNode::ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::GetLeftChildRowString(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::PartitionedAggregationNode::Partition::InitStreams(), impala::TopNNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::SelectNode::Prepare(), impala::SortNode::Prepare(), impala::UnionNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::PlanFragmentExecutor::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::PartitionedAggregationNode::ProcessStream(), impala::PlanFragmentExecutor::row_desc(), impala::SortNode::SortInput(), and impala::HdfsScanner::StartNewRowBatch().
RuntimeProfile::Counter* impala::ScanNode::rows_read_counter () const inline
Definition at line 96 of file scan-node.h.
References rows_read_counter_.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), and impala::HdfsRCFileScanner::ProcessRange().
int64_t impala::ExecNode::rows_returned () const inline inherited
Definition at line 157 of file exec-node.h.
References impala::ExecNode::num_rows_returned_.
Referenced by impala::CrossJoinNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedAggregationNode::Open(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::CrossJoinNode::ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), and impala::HdfsTextScanner::WriteFields().
RuntimeProfile* impala::ExecNode::runtime_profile () inline inherited
Definition at line 161 of file exec-node.h.
References impala::ExecNode::runtime_profile_.
Referenced by impala::ExecNode::AddRuntimeExecOption(), impala::BlockingJoinNode::BuildSideThread(), impala::ExecNode::CreateTreeHelper(), impala::PartitionedAggregationNode::Partition::InitStreams(), impala::SortNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::HdfsScanNode::Open(), impala::HdfsTextScanner::Prepare(), impala::HBaseScanNode::Prepare(), impala::BaseSequenceScanner::Prepare(), impala::ExchangeNode::Prepare(), impala::HdfsParquetScanner::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), Prepare(), impala::PlanFragmentExecutor::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanner::Prepare(), impala::HdfsScanNode::Prepare(), and impala::PartitionedHashJoinNode::ProcessBuildInput().
RuntimeProfile::Counter* impala::ScanNode::scan_ranges_complete_counter () const inline
Definition at line 107 of file scan-node.h.
References scan_ranges_complete_counter_.
RuntimeProfile::ThreadCounters* impala::ScanNode::scanner_thread_counters () const inline
Definition at line 110 of file scan-node.h.
References scanner_thread_counters_.
Referenced by impala::HBaseScanNode::GetNext(), and impala::HdfsScanNode::ScannerThread().
void impala::ExecNode::SetDebugOptions (int node_id, TExecNodePhase::type phase, TDebugAction::type action, ExecNode * tree) static inherited
Set debug action for node with given id in 'tree'.
Definition at line 332 of file exec-node.cc.
References impala::ExecNode::children_, impala::ExecNode::debug_action_, impala::ExecNode::debug_phase_, and impala::ExecNode::id_.
Referenced by impala::PlanFragmentExecutor::Prepare().
void impala::ScanNode::SetScanRanges (const std::vector< TScanRangeParams > & scan_range_params) inline
This should be called before Prepare(), and the argument must be not destroyed until after Prepare().
Definition at line 89 of file scan-node.h.
References scan_range_params_.
Referenced by impala::PlanFragmentExecutor::Prepare().
RuntimeProfile::Counter* impala::ScanNode::total_throughput_counter () const inline
Definition at line 98 of file scan-node.h.
References total_throughput_counter_.
Referenced by impala::HBaseScanNode::Close(), and impala::HdfsScanNode::StopAndFinalizeCounters().
TPlanNodeType::type impala::ExecNode::type () const inline inherited
Definition at line 155 of file exec-node.h.
References impala::ExecNode::type_.
Referenced by impala::ExecNode::CodegenEvalConjuncts(), impala::PartitionedAggregationNode::CodegenUpdateTuple(), and impala::PlanFragmentExecutor::Prepare().
Member Data Documentation
RuntimeProfile::Counter impala::ScanNode::active_hdfs_read_thread_counter_ protected
The number of active hdfs reading threads reading for this node.
Definition at line 164 of file scan-node.h.
Referenced by impala::HdfsScanNode::Close(), and impala::HdfsScanNode::Open().
RuntimeProfile::Counter impala::ScanNode::active_scanner_thread_counter_ protected
The number of active scanner threads that are not blocked by IO.
Definition at line 157 of file scan-node.h.
Referenced by active_scanner_thread_counter(), impala::HdfsScanNode::Close(), impala::HdfsScanNode::EnoughMemoryForScannerThread(), impala::HdfsScanNode::Open(), impala::HdfsScanNode::ScannerThread(), and impala::HdfsScanNode::ThreadTokenAvailableCb().
const string impala::ScanNode::AVERAGE_HDFS_READ_THREAD_CONCURRENCY static
Initial value:
=
    "AverageHdfsReadThreadConcurrency"
Definition at line 133 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open().
RuntimeProfile::Counter* impala::ScanNode::average_hdfs_read_thread_concurrency_ protected
Average number of active hdfs reading threads This should be created in Open and stopped when all the scanner threads are done.
Definition at line 168 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open(), and impala::HdfsScanNode::StopAndFinalizeCounters().
const string impala::ScanNode::AVERAGE_SCANNER_THREAD_CONCURRENCY static
Initial value:
=
    "AverageScannerThreadConcurrency"
Definition at line 132 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open().
RuntimeProfile::Counter* impala::ScanNode::average_scanner_thread_concurrency_ protected
Average number of active scanner threads This should be created in Open and stopped when all the scanner threads are done.
Definition at line 161 of file scan-node.h.
Referenced by average_scanner_thread_concurrency(), impala::HdfsScanNode::Open(), and impala::HdfsScanNode::StopAndFinalizeCounters().
const string impala::ScanNode::BYTES_READ_COUNTER = "BytesRead" static
names of ScanNode common counters
Definition at line 121 of file scan-node.h.
Referenced by Prepare().
RuntimeProfile::Counter* impala::ScanNode::bytes_read_counter_ protected
Definition at line 140 of file scan-node.h.
Referenced by bytes_read_counter(), impala::HdfsScanNode::Open(), and Prepare().
RuntimeProfile::TimeSeriesCounter* impala::ScanNode::bytes_read_timeseries_counter_ protected
Time series of the bytes_read_counter_.
Definition at line 142 of file scan-node.h.
Referenced by impala::HBaseScanNode::Close(), Prepare(), and impala::HdfsScanNode::StopAndFinalizeCounters().
std::vector<ExecNode*> impala::ExecNode::children_ protected inherited
Definition at line 214 of file exec-node.h.
Referenced by impala::ExecNode::child(), impala::ExecNode::Close(), impala::ExecNode::CollectNodes(), impala::ExecNode::CreateTreeHelper(), impala::HBaseScanNode::DebugString(), impala::UnionNode::GetNext(), impala::UnionNode::Open(), impala::AggregationNode::Open(), impala::PartitionedAggregationNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::ExecNode::Prepare(), impala::PartitionedAggregationNode::ProcessStream(), impala::ExecNode::Reset(), and impala::ExecNode::SetDebugOptions().
std::vector<ExprContext*> impala::ExecNode::conjunct_ctxs_ protected inherited
Definition at line 212 of file exec-node.h.
Referenced by impala::ExecNode::Close(), impala::HashJoinNode::CodegenProcessProbeBatch(), impala::PartitionedHashJoinNode::CodegenProcessProbeBatch(), impala::ExecNode::conjunct_ctxs(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HBaseScanNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::TopNNode::Init(), impala::ExecNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::ExecNode::Open(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), impala::ExecNode::Prepare(), impala::CrossJoinNode::ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
TDebugAction::type impala::ExecNode::debug_action_ protected inherited
Definition at line 220 of file exec-node.h.
Referenced by impala::ExecNode::ExecDebugAction(), and impala::ExecNode::SetDebugOptions().
TExecNodePhase::type impala::ExecNode::debug_phase_ protected inherited
debug-only: if debug_action_ is not INVALID, node will perform action in debug_phase_
Definition at line 219 of file exec-node.h.
Referenced by impala::ExecNode::ExecDebugAction(), and impala::ExecNode::SetDebugOptions().
boost::mutex impala::ExecNode::exec_options_lock_ protected inherited
Execution options that are determined at runtime. This is added to the runtime profile at Close(). Examples for options logged here would be "Codegen Enabled"
Definition at line 238 of file exec-node.h.
Referenced by impala::ExecNode::AddRuntimeExecOption().
boost::scoped_ptr<MemTracker> impala::ExecNode::expr_mem_tracker_ protected inherited
MemTracker that should be used for ExprContexts.
Definition at line 233 of file exec-node.h.
Referenced by impala::ExecNode::expr_mem_tracker(), and impala::ExecNode::Prepare().
std::vector<RuntimeProfile::Counter*> impala::ScanNode::hdfs_read_thread_concurrency_bucket_ protected
HDFS read thread concurrency bucket: bucket[i] refers to the number of sample taken where there are i concurrent hdfs read thread running
Definition at line 174 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open(), and impala::HdfsScanNode::StopAndFinalizeCounters().
int impala::ExecNode::id_ protected inherited
Definition at line 209 of file exec-node.h.
Referenced by impala::PartitionedAggregationNode::CreateHashPartitions(), impala::ExecNode::id(), impala::ExecNode::InitRuntimeProfile(), impala::PartitionedAggregationNode::NextPartition(), impala::ExchangeNode::Prepare(), impala::PartitionedHashJoinNode::PrepareNextPartition(), impala::PartitionedHashJoinNode::ProcessBuildInput(), and impala::ExecNode::SetDebugOptions().
int64_t impala::ExecNode::limit_ protected inherited
Definition at line 222 of file exec-node.h.
Referenced by impala::SortNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::TopNNode::InsertTupleRow(), impala::HdfsScanNode::limit(), impala::ExecNode::limit(), impala::TopNNode::Open(), and impala::ExecNode::ReachedLimit().
const string impala::ScanNode::MATERIALIZE_TUPLE_TIMER = "MaterializeTupleTime(*)" static
Definition at line 128 of file scan-node.h.
Referenced by Prepare().
RuntimeProfile::Counter* impala::ScanNode::materialize_tuple_timer_ protected
Definition at line 151 of file scan-node.h.
Referenced by materialize_tuple_timer(), and Prepare().
boost::scoped_ptr<MemTracker> impala::ExecNode::mem_tracker_ protected inherited
Account for peak memory used by this node.
Definition at line 230 of file exec-node.h.
Referenced by impala::ExecNode::mem_tracker(), and impala::ExecNode::Prepare().
const string impala::ScanNode::NUM_DISKS_ACCESSED_COUNTER = "NumDisksAccessed" static
Definition at line 127 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open().
RuntimeProfile::Counter* impala::ScanNode::num_disks_accessed_counter_ protected
Definition at line 150 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open(), and impala::HdfsScanNode::StopAndFinalizeCounters().
int64_t impala::ExecNode::num_rows_returned_ protected inherited
Definition at line 223 of file exec-node.h.
Referenced by impala::ExecNode::Close(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), impala::ExecNode::ReachedLimit(), and impala::ExecNode::rows_returned().
const string impala::ScanNode::NUM_SCANNER_THREADS_STARTED static
Initial value:
=
    "NumScannerThreadsStarted"
Definition at line 134 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open().
RuntimeProfile::Counter* impala::ScanNode::num_scanner_threads_started_counter_ protected
Definition at line 170 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open(), and impala::HdfsScanNode::ThreadTokenAvailableCb().
const string impala::ScanNode::PER_READ_THREAD_THROUGHPUT_COUNTER static
Initial value:
=
    "PerReadThreadRawHdfsThroughput"
Definition at line 126 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open().
RuntimeProfile::Counter* impala::ScanNode::per_read_thread_throughput_counter_ protected
Per thread read throughput [bytes/sec].
Definition at line 149 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open(), and per_read_thread_throughput_counter().
ObjectPool* impala::ExecNode::pool_ protected inherited
Definition at line 211 of file exec-node.h.
Referenced by impala::SortNode::Init(), impala::UnionNode::Init(), impala::TopNNode::Init(), impala::ExchangeNode::Init(), impala::HashJoinNode::Init(), impala::AggregationNode::Init(), impala::ExecNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::AnalyticEvalNode::Init(), impala::PartitionedAggregationNode::Init(), impala::ExecNode::InitRuntimeProfile(), impala::HdfsScanNode::Open(), impala::PartitionedHashJoinNode::Prepare(), and impala::PartitionedHashJoinNode::ProcessBuildInput().
RuntimeProfile::Counter* impala::ScanNode::read_timer_ protected
Definition at line 145 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open(), impala::HBaseScanNode::Prepare(), and read_timer().
RowDescriptor impala::ExecNode::row_descriptor_ protected inherited
Definition at line 215 of file exec-node.h.
Referenced by impala::SortNode::Open(), impala::SortNode::Prepare(), impala::TopNNode::Prepare(), impala::ExchangeNode::Prepare(), and impala::ExecNode::row_desc().
const string impala::ExecNode::ROW_THROUGHPUT_COUNTER = "RowsReturnedRate" static inherited
Names of counters shared by all exec nodes.
Definition at line 169 of file exec-node.h.
Referenced by impala::ExecNode::Prepare().
const string impala::ScanNode::ROWS_READ_COUNTER = "RowsRead" static
Definition at line 122 of file scan-node.h.
Referenced by Prepare().
RuntimeProfile::Counter* impala::ScanNode::rows_read_counter_ protected
rows/tuples read from the scanner (including those discarded by EvalConjucts())
Definition at line 144 of file scan-node.h.
Referenced by impala::HBaseScanNode::GetNext(), Prepare(), and rows_read_counter().
RuntimeProfile::Counter* impala::ExecNode::rows_returned_counter_ protected inherited
Definition at line 226 of file exec-node.h.
Referenced by impala::ExecNode::Close(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), and impala::ExecNode::Prepare().
RuntimeProfile::Counter* impala::ExecNode::rows_returned_rate_ protected inherited
Definition at line 227 of file exec-node.h.
Referenced by impala::ExecNode::Prepare().
std::string impala::ExecNode::runtime_exec_options_ protected inherited
Definition at line 239 of file exec-node.h.
Referenced by impala::ExecNode::AddRuntimeExecOption().
boost::scoped_ptr<RuntimeProfile> impala::ExecNode::runtime_profile_ protected inherited
Definition at line 225 of file exec-node.h.
Referenced by impala::HBaseScanNode::Close(), impala::SelectNode::GetNext(), impala::UnionNode::GetNext(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNext(), impala::ExecNode::InitRuntimeProfile(), impala::SelectNode::Open(), impala::HBaseScanNode::Open(), impala::UnionNode::Open(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::ExchangeNode::Open(), impala::DataSourceScanNode::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::SelectNode::Prepare(), impala::UnionNode::Prepare(), impala::SortNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::ExecNode::runtime_profile(), and impala::HdfsScanNode::StopAndFinalizeCounters().
const std::vector<TScanRangeParams>* impala::ScanNode::scan_range_params_ protected
The scan ranges this scan node is responsible for. Not owned.
Definition at line 138 of file scan-node.h.
Referenced by impala::HBaseScanNode::Prepare(), impala::HdfsScanNode::Prepare(), and SetScanRanges().
const string impala::ScanNode::SCAN_RANGES_COMPLETE_COUNTER = "ScanRangesComplete" static
Definition at line 129 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open().
RuntimeProfile::Counter* impala::ScanNode::scan_ranges_complete_counter_ protected
Definition at line 152 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open(), and scan_ranges_complete_counter().
RuntimeProfile::ThreadCounters* impala::ScanNode::scanner_thread_counters_ protected
Aggregated scanner thread counters.
Definition at line 154 of file scan-node.h.
Referenced by Prepare(), and scanner_thread_counters().
const string impala::ScanNode::SCANNER_THREAD_COUNTERS_PREFIX = "ScannerThreads" static
Definition at line 130 of file scan-node.h.
Referenced by Prepare().
const string impala::ScanNode::SCANNER_THREAD_TOTAL_WALLCLOCK_TIME static
Initial value:
=
    "ScannerThreadsTotalWallClockTime"
Definition at line 131 of file scan-node.h.
Referenced by impala::HdfsTextScanner::Prepare(), and Prepare().
const string impala::ScanNode::TOTAL_HBASE_READ_TIMER = "TotalRawHBaseReadTime(*)" static
Definition at line 124 of file scan-node.h.
Referenced by impala::HBaseScanNode::Prepare().
const string impala::ScanNode::TOTAL_HDFS_READ_TIMER = "TotalRawHdfsReadTime(*)" static
Definition at line 123 of file scan-node.h.
Referenced by impala::HdfsScanNode::Open().
const string impala::ScanNode::TOTAL_THROUGHPUT_COUNTER = "TotalReadThroughput" static
Definition at line 125 of file scan-node.h.
Referenced by Prepare().
RuntimeProfile::Counter* impala::ScanNode::total_throughput_counter_ protected
Wall based aggregate read throughput [bytes/sec].
Definition at line 147 of file scan-node.h.
Referenced by Prepare(), and total_throughput_counter().
TPlanNodeType::type impala::ExecNode::type_ protected inherited
Definition at line 210 of file exec-node.h.
Referenced by impala::ExecNode::CollectNodes(), and impala::ExecNode::type().
The documentation for this class was generated from the following files:
be/src/exec/scan-node.h
be/src/exec/scan-node.cc