Impala: impala::DecimalOperators Class Reference
impala::DecimalOperators Class Reference
#include <decimal-operators.h>
Public Types
enum DecimalRoundOp { TRUNCATE, FLOOR, CEIL, ROUND }
Static Public Member Functions
static DecimalVal CastToDecimalVal (FunctionContext *, const DecimalVal &)
static DecimalVal CastToDecimalVal (FunctionContext *, const TinyIntVal &)
static DecimalVal CastToDecimalVal (FunctionContext *, const SmallIntVal &)
static DecimalVal CastToDecimalVal (FunctionContext *, const IntVal &)
static DecimalVal CastToDecimalVal (FunctionContext *, const BigIntVal &)
static DecimalVal CastToDecimalVal (FunctionContext *, const FloatVal &)
static DecimalVal CastToDecimalVal (FunctionContext *, const DoubleVal &)
static DecimalVal CastToDecimalVal (FunctionContext *, const StringVal &)
static BooleanVal CastToBooleanVal (FunctionContext *, const DecimalVal &)
static TinyIntVal CastToTinyIntVal (FunctionContext *, const DecimalVal &)
static SmallIntVal CastToSmallIntVal (FunctionContext *, const DecimalVal &)
static IntVal CastToIntVal (FunctionContext *, const DecimalVal &)
static BigIntVal CastToBigIntVal (FunctionContext *, const DecimalVal &)
static FloatVal CastToFloatVal (FunctionContext *, const DecimalVal &)
static DoubleVal CastToDoubleVal (FunctionContext *, const DecimalVal &)
static StringVal CastToStringVal (FunctionContext *, const DecimalVal &)
static TimestampVal CastToTimestampVal (FunctionContext *, const DecimalVal &)
static DecimalVal Add_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static DecimalVal Subtract_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static DecimalVal Multiply_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static DecimalVal Divide_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static DecimalVal Mod_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static BooleanVal Eq_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static BooleanVal Ne_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static BooleanVal Ge_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static BooleanVal Gt_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static BooleanVal Le_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static BooleanVal Lt_DecimalVal_DecimalVal (FunctionContext *, const DecimalVal &, const DecimalVal &)
static DecimalVal RoundDecimal (FunctionContext *context, const DecimalVal &val, const ColumnType &val_type, const ColumnType &output_type, const DecimalRoundOp &op)
static DecimalVal RoundDecimal (FunctionContext *context, const DecimalVal &val, const DecimalRoundOp &op)
static DecimalVal RoundDecimalNegativeScale (FunctionContext *context, const DecimalVal &val, const ColumnType &val_type, const ColumnType &output_type, const DecimalRoundOp &op, int64_t rounding_scale)
Static Private Member Functions
static DecimalVal IntToDecimalVal (FunctionContext *context, const ColumnType &type, int64_t val)
Converts 'val' to a DecimalVal according to 'type'. 'type' must be a decimal type.
static DecimalVal FloatToDecimalVal (FunctionContext *context, const ColumnType &type, double val)
static DecimalVal ScaleDecimalValue (FunctionContext *context, const Decimal4Value &val, const ColumnType &val_type, const ColumnType &output_type)
Returns the value of 'val' scaled to 'output_type'.
static DecimalVal ScaleDecimalValue (FunctionContext *context, const Decimal8Value &val, const ColumnType &val_type, const ColumnType &output_type)
static DecimalVal ScaleDecimalValue (FunctionContext *context, const Decimal16Value &val, const ColumnType &val_type, const ColumnType &output_type)
template<typename T >
static T RoundDelta (const DecimalValue< T > &v, int src_scale, int target_scale, const DecimalRoundOp &op)
Detailed Description
Implementation of the decimal operators. These include the cast, arithmetic and binary operators.
Definition at line 33 of file decimal-operators.h.
Member Enumeration Documentation
enum impala::DecimalOperators::DecimalRoundOp
The rounding rule when converting decimals. These only apply going from a higher scale to a lower one.
Enumerator
TRUNCATE
Additional digits are dropped.
FLOOR
Returns largest value not greater than the value. (digits are dropped for positive values and rounded away from zero for negative values)
CEIL
Returns smallest value not smaller than the value. (rounded away from zero for positive values and extra digits dropped for negative values)
ROUND
Rounded towards zero if the extra digits are less than .5 and away from zero otherwise.
Definition at line 81 of file decimal-operators.h.
Member Function Documentation
static DecimalVal impala::DecimalOperators::Add_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
static BigIntVal impala::DecimalOperators::CastToBigIntVal (FunctionContext * , const DecimalVal &) static
BooleanVal impala::DecimalOperators::CastToBooleanVal (FunctionContext * context, const DecimalVal & val) static
Definition at line 534 of file decimal-operators.cc.
References impala_udf::FunctionContext::GetArgType(), impala::ColumnType::GetByteSize(), impala_udf::AnyVal::is_null, impala::ColumnType::type, impala::TYPE_DECIMAL, impala::AnyValUtil::TypeDescToColumnType(), impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * context, const DecimalVal & val) static
Definition at line 435 of file decimal-operators.cc.
References RoundDecimal(), and TRUNCATE.
Referenced by impala::Expr::InitBuiltinsDummy().
static DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * , const TinyIntVal &) static
static DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * , const SmallIntVal &) static
static DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * , const IntVal &) static
static DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * , const BigIntVal &) static
static DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * , const FloatVal &) static
static DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * , const DoubleVal &) static
DecimalVal impala::DecimalOperators::CastToDecimalVal (FunctionContext * context, const StringVal & val) static
Definition at line 440 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), impala_udf::FunctionContext::GetReturnType(), impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala::StringParser::PARSE_SUCCESS, impala::StringParser::PARSE_UNDERFLOW, impala_udf::StringVal::ptr, impala::AnyValUtil::TypeDescToColumnType(), and impala::DecimalValue< T >::value().
static DoubleVal impala::DecimalOperators::CastToDoubleVal (FunctionContext * , const DecimalVal &) static
static FloatVal impala::DecimalOperators::CastToFloatVal (FunctionContext * , const DecimalVal &) static
static IntVal impala::DecimalOperators::CastToIntVal (FunctionContext * , const DecimalVal &) static
static SmallIntVal impala::DecimalOperators::CastToSmallIntVal (FunctionContext * , const DecimalVal &) static
StringVal impala::DecimalOperators::CastToStringVal (FunctionContext * context, const DecimalVal & val) static
Definition at line 478 of file decimal-operators.cc.
References impala_udf::FunctionContext::GetArgType(), impala::ColumnType::GetByteSize(), impala_udf::AnyVal::is_null, impala::DecimalValue< T >::ToString(), impala::AnyValUtil::TypeDescToColumnType(), impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
TimestampVal impala::DecimalOperators::CastToTimestampVal (FunctionContext * context, const DecimalVal & val) static
Definition at line 502 of file decimal-operators.cc.
References impala_udf::FunctionContext::GetArgType(), impala::ColumnType::GetByteSize(), impala_udf::AnyVal::is_null, impala::DecimalValue< T >::ToDouble(), impala::TimestampValue::ToTimestampVal(), impala::ColumnType::type, impala::TYPE_DECIMAL, impala::AnyValUtil::TypeDescToColumnType(), impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
static TinyIntVal impala::DecimalOperators::CastToTinyIntVal (FunctionContext * , const DecimalVal &) static
static DecimalVal impala::DecimalOperators::Divide_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
static BooleanVal impala::DecimalOperators::Eq_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
DecimalVal impala::DecimalOperators::FloatToDecimalVal (FunctionContext * context, const ColumnType & type, double val) inline static private
Definition at line 66 of file decimal-operators.cc.
References impala::DecimalValue< int32_t >::FromDouble(), impala::DecimalValue< int128_t >::FromDouble(), impala::DecimalValue< int64_t >::FromDouble(), impala::ColumnType::GetByteSize(), RETURN_IF_OVERFLOW, impala::ColumnType::type, impala::TYPE_DECIMAL, and impala::DecimalValue< T >::value().
static BooleanVal impala::DecimalOperators::Ge_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
static BooleanVal impala::DecimalOperators::Gt_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
DecimalVal impala::DecimalOperators::IntToDecimalVal (FunctionContext * context, const ColumnType & type, int64_t val) inline static private
Converts 'val' to a DecimalVal according to 'type'. 'type' must be a decimal type.
Definition at line 40 of file decimal-operators.cc.
References impala::DecimalValue< int32_t >::FromInt(), impala::DecimalValue< int128_t >::FromInt(), impala::DecimalValue< int64_t >::FromInt(), impala::ColumnType::GetByteSize(), RETURN_IF_OVERFLOW, impala::ColumnType::type, impala::TYPE_DECIMAL, and impala::DecimalValue< T >::value().
static BooleanVal impala::DecimalOperators::Le_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
static BooleanVal impala::DecimalOperators::Lt_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
static DecimalVal impala::DecimalOperators::Mod_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
static DecimalVal impala::DecimalOperators::Multiply_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
static BooleanVal impala::DecimalOperators::Ne_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
DecimalVal impala::DecimalOperators::RoundDecimal (FunctionContext * context, const DecimalVal & val, const ColumnType & val_type, const ColumnType & output_type, const DecimalRoundOp & op) static
Evaluates a round from 'val' and returns the result, using the rounding rule of 'type'.
Definition at line 377 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), impala_udf::AnyVal::is_null, RoundDelta(), impala::ColumnType::scale, ScaleDecimalValue(), impala::ColumnType::type, impala::TYPE_DECIMAL, impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
Referenced by CastToDecimalVal(), impala::DecimalFunctions::Ceil(), impala::DecimalFunctions::Floor(), impala::DecimalFunctions::Round(), RoundDecimal(), impala::DecimalFunctions::RoundTo(), and impala::DecimalFunctions::Truncate().
DecimalVal impala::DecimalOperators::RoundDecimal (FunctionContext * context, const DecimalVal & val, const DecimalRoundOp & op) static
Same as above but infers 'val_type' from the first argument type and 'output_type' from the return type according to 'context'.
Definition at line 425 of file decimal-operators.cc.
References impala_udf::FunctionContext::GetArgType(), impala_udf::FunctionContext::GetReturnType(), RoundDecimal(), and impala::AnyValUtil::TypeDescToColumnType().
DecimalVal impala::DecimalOperators::RoundDecimalNegativeScale (FunctionContext * context, const DecimalVal & val, const ColumnType & val_type, const ColumnType & output_type, const DecimalRoundOp & op, int64_t rounding_scale) static
Handles the case of rounding to a negative scale. This means rounding to a digit before the decimal point. rounding_scale is the number of digits before the decimal to round to. TODO: can this code be reorganized to combine the two version of RoundDecimal()? The implementation is similar but not quite the same. This code is, in general, harder to read because there are multiple input/output types to handle and all combinations are valid. Another option might be to use templates to generate each pair: Decimal4Value Round(const Decimal4Value&); Decimal8Value Round(const Decimal4Value&); Decimal4Value Round(const Decimal8Value&); etc.
Definition at line 306 of file decimal-operators.cc.
References impala::abs(), impala_udf::AnyVal::is_null, impala::DecimalUtil::MAX_UNSCALED_DECIMAL, impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, impala_udf::DecimalVal::val8, and impala::DecimalValue< T >::value().
Referenced by impala::DecimalFunctions::RoundTo().
template<typename T > static T impala::DecimalOperators::RoundDelta (const DecimalValue< T > & v, int src_scale, int target_scale, const DecimalRoundOp & op) inline static private
Returns the delta that needs to be added when the source decimal is rounded to target scale. Returns 0, if no rounding is necessary, or -1/1 if rounding is required.
Definition at line 147 of file decimal-operators.h.
References impala::abs(), and impala::DecimalValue< T >::value().
Referenced by RoundDecimal().
DecimalVal impala::DecimalOperators::ScaleDecimalValue (FunctionContext * context, const Decimal4Value & val, const ColumnType & val_type, const ColumnType & output_type) inline static private
Returns the value of 'val' scaled to 'output_type'.
Definition at line 99 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), RETURN_IF_OVERFLOW, impala::DecimalValue< T >::ScaleTo(), impala::ToDecimal16(), impala::ToDecimal8(), impala::ColumnType::type, impala::TYPE_DECIMAL, and impala::DecimalValue< T >::value().
Referenced by RoundDecimal().
DecimalVal impala::DecimalOperators::ScaleDecimalValue (FunctionContext * context, const Decimal8Value & val, const ColumnType & val_type, const ColumnType & output_type) inline static private
Definition at line 129 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), RETURN_IF_OVERFLOW, impala::DecimalValue< T >::ScaleTo(), impala::ToDecimal16(), impala::ToDecimal4(), impala::ColumnType::type, impala::TYPE_DECIMAL, and impala::DecimalValue< T >::value().
DecimalVal impala::DecimalOperators::ScaleDecimalValue (FunctionContext * context, const Decimal16Value & val, const ColumnType & val_type, const ColumnType & output_type) inline static private
Definition at line 159 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), RETURN_IF_OVERFLOW, impala::DecimalValue< T >::ScaleTo(), impala::ToDecimal4(), impala::ToDecimal8(), impala::ColumnType::type, impala::TYPE_DECIMAL, and impala::DecimalValue< T >::value().
static DecimalVal impala::DecimalOperators::Subtract_DecimalVal_DecimalVal (FunctionContext * , const DecimalVal & , const DecimalVal &) static
The documentation for this class was generated from the following files:
be/src/exprs/decimal-operators.h
be/src/exprs/decimal-operators.cc