Impala: com.cloudera.impala.analysis.SelectList Class Reference
com.cloudera.impala.analysis.SelectList Class Reference
Public Member Functions
SelectList (List< SelectListItem > items)
SelectList ()
SelectList (List< SelectListItem > items, boolean isDistinct, List< String > planHints)
SelectList (SelectList other)
List< SelectListItem > getItems ()
void setPlanHints (List< String > planHints)
List< String > getPlanHints ()
boolean isDistinct ()
void setIsDistinct (boolean value)
boolean isStraightJoin ()
boolean hasPlanHints ()
void analyzePlanHints (Analyzer analyzer)
SelectList clone ()
Private Attributes
List< String > planHints_
final List< SelectListItem > items_
boolean isDistinct_
boolean isStraightJoin_
Detailed Description
Select list items plus optional distinct clause and optional plan hints.
Definition at line 24 of file SelectList.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.SelectList.SelectList (List< SelectListItem > items) inline
Definition at line 32 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isDistinct_, com.cloudera.impala.analysis.SelectList.isStraightJoin_, and com.cloudera.impala.analysis.SelectList.items_.
com.cloudera.impala.analysis.SelectList.SelectList () inline
Definition at line 38 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isDistinct_, com.cloudera.impala.analysis.SelectList.isStraightJoin_, and com.cloudera.impala.analysis.SelectList.items_.
Referenced by com.cloudera.impala.analysis.SelectList.clone().
com.cloudera.impala.analysis.SelectList.SelectList (List< SelectListItem > items, boolean isDistinct, List< String > planHints) inline
Definition at line 44 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isDistinct(), com.cloudera.impala.analysis.SelectList.isDistinct_, com.cloudera.impala.analysis.SelectList.isStraightJoin_, com.cloudera.impala.analysis.SelectList.items_, and com.cloudera.impala.analysis.SelectList.planHints_.
com.cloudera.impala.analysis.SelectList.SelectList (SelectList other) inline
C'tor for cloning.
Definition at line 55 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isDistinct_, com.cloudera.impala.analysis.SelectList.isStraightJoin_, com.cloudera.impala.analysis.SelectList.items_, and com.cloudera.impala.analysis.SelectList.planHints_.
Member Function Documentation
void com.cloudera.impala.analysis.SelectList.analyzePlanHints (Analyzer analyzer) inline
Definition at line 74 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isStraightJoin_, and com.cloudera.impala.analysis.SelectList.planHints_.
SelectList com.cloudera.impala.analysis.SelectList.clone () inline
Definition at line 86 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.SelectList().
Referenced by com.cloudera.impala.analysis.SelectStmt.clone().
List<SelectListItem> com.cloudera.impala.analysis.SelectList.getItems () inline
Definition at line 66 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.items_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyzeAggregation().
List<String> com.cloudera.impala.analysis.SelectList.getPlanHints () inline
Definition at line 68 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.planHints_.
Referenced by com.cloudera.impala.analysis.StmtRewriter.replaceUnqualifiedStarItems(), and com.cloudera.impala.analysis.StmtRewriter.updateInlineView().
boolean com.cloudera.impala.analysis.SelectList.hasPlanHints () inline
Definition at line 72 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.planHints_.
Referenced by com.cloudera.impala.analysis.SelectStmt.toSql().
boolean com.cloudera.impala.analysis.SelectList.isDistinct () inline
Definition at line 69 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isDistinct_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.analysis.SelectStmt.createAggInfo(), com.cloudera.impala.analysis.SelectList.SelectList(), and com.cloudera.impala.analysis.SelectStmt.toSql().
boolean com.cloudera.impala.analysis.SelectList.isStraightJoin () inline
Definition at line 71 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isStraightJoin_.
void com.cloudera.impala.analysis.SelectList.setIsDistinct (boolean value) inline
Definition at line 70 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.isDistinct_.
void com.cloudera.impala.analysis.SelectList.setPlanHints (List< String > planHints) inline
Definition at line 67 of file SelectList.java.
References com.cloudera.impala.analysis.SelectList.planHints_.
Member Data Documentation
boolean com.cloudera.impala.analysis.SelectList.isDistinct_ private
Definition at line 27 of file SelectList.java.
Referenced by com.cloudera.impala.analysis.SelectList.isDistinct(), com.cloudera.impala.analysis.SelectList.SelectList(), and com.cloudera.impala.analysis.SelectList.setIsDistinct().
boolean com.cloudera.impala.analysis.SelectList.isStraightJoin_ private
Definition at line 30 of file SelectList.java.
Referenced by com.cloudera.impala.analysis.SelectList.analyzePlanHints(), com.cloudera.impala.analysis.SelectList.isStraightJoin(), and com.cloudera.impala.analysis.SelectList.SelectList().
final List<SelectListItem> com.cloudera.impala.analysis.SelectList.items_ private
Definition at line 26 of file SelectList.java.
Referenced by com.cloudera.impala.analysis.SelectList.getItems(), and com.cloudera.impala.analysis.SelectList.SelectList().
List<String> com.cloudera.impala.analysis.SelectList.planHints_ private
Definition at line 25 of file SelectList.java.
Referenced by com.cloudera.impala.analysis.SelectList.analyzePlanHints(), com.cloudera.impala.analysis.SelectList.getPlanHints(), com.cloudera.impala.analysis.SelectList.hasPlanHints(), com.cloudera.impala.analysis.SelectList.SelectList(), and com.cloudera.impala.analysis.SelectList.setPlanHints().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/SelectList.java