Impala: com.cloudera.impala.analysis.AnalyticWindow Class Reference
com.cloudera.impala.analysis.AnalyticWindow Class Reference
Classes
class Boundary
enum BoundaryType
enum Type
Public Member Functions
Type getType ()
Boundary getLeftBoundary ()
Boundary getRightBoundary ()
Boundary setRightBoundary (Boundary b)
AnalyticWindow (Type type, Boundary b)
AnalyticWindow (Type type, Boundary l, Boundary r)
AnalyticWindow reverse ()
String toSql ()
TAnalyticWindow toThrift ()
boolean equals (Object obj)
AnalyticWindow clone ()
void analyze (Analyzer analyzer) throws AnalysisException
Static Public Attributes
static final AnalyticWindow DEFAULT_WINDOW
Private Member Functions
AnalyticWindow (AnalyticWindow other)
void checkOffsetExpr (Analyzer analyzer, Boundary boundary) throws AnalysisException
void checkOffsetBoundaries (Analyzer analyzer, Boundary b1, Boundary b2) throws AnalysisException
Private Attributes
final Type type_
final Boundary leftBoundary_
Boundary rightBoundary_
String toSqlString_
Detailed Description
Windowing clause of an analytic expr Both left and right boundaries are always non-null after analyze().
Definition at line 35 of file AnalyticWindow.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow (Type type, Boundary b) inline
Definition at line 193 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_, com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, and com.cloudera.impala.analysis.AnalyticWindow.type_.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.clone(), com.cloudera.impala.analysis.AnalyticWindow.equals(), and com.cloudera.impala.analysis.AnalyticWindow.reverse().
com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow (Type type, Boundary l, Boundary r) inline
Definition at line 200 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_, com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, and com.cloudera.impala.analysis.AnalyticWindow.type_.
com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow (AnalyticWindow other) inline private
Clone c'tor
Definition at line 211 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_, com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, com.cloudera.impala.analysis.AnalyticWindow.toSqlString_, and com.cloudera.impala.analysis.AnalyticWindow.type_.
Member Function Documentation
void com.cloudera.impala.analysis.AnalyticWindow.analyze (Analyzer analyzer) throws AnalysisException inline
Definition at line 344 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.checkOffsetBoundaries(), com.cloudera.impala.analysis.AnalyticWindow.checkOffsetExpr(), com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.CURRENT_ROW, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.FOLLOWING, com.cloudera.impala.analysis.AnalyticWindow.Boundary.getType(), com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.isOffset(), com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.PRECEDING, com.cloudera.impala.analysis.AnalyticWindow.Type.RANGE, com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, com.cloudera.impala.analysis.AnalyticWindow.toSql(), com.cloudera.impala.analysis.AnalyticWindow.toSqlString_, com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_, com.cloudera.impala.analysis.AnalyticWindow.type_, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_FOLLOWING, and com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_PRECEDING.
void com.cloudera.impala.analysis.AnalyticWindow.checkOffsetBoundaries (Analyzer analyzer, Boundary b1, Boundary b2) throws AnalysisException inline private
Check that b1 <= b2.
Definition at line 317 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.Expr.getType(), and com.cloudera.impala.analysis.AnalyticWindow.toSql().
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze().
void com.cloudera.impala.analysis.AnalyticWindow.checkOffsetExpr (Analyzer analyzer, Boundary boundary) throws AnalysisException inline private
Semantic analysis for expr of a PRECEDING/FOLLOWING clause.
Definition at line 278 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Type.ROWS, and com.cloudera.impala.analysis.AnalyticWindow.type_.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze().
AnalyticWindow com.cloudera.impala.analysis.AnalyticWindow.clone () inline
Definition at line 273 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow().
boolean com.cloudera.impala.analysis.AnalyticWindow.equals (Object obj) inline
Definition at line 258 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow(), com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, and com.cloudera.impala.analysis.AnalyticWindow.type_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.equals().
Boundary com.cloudera.impala.analysis.AnalyticWindow.getLeftBoundary () inline
Definition at line 189 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.setChildren(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
Boundary com.cloudera.impala.analysis.AnalyticWindow.getRightBoundary () inline
Definition at line 190 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.setChildren(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
Type com.cloudera.impala.analysis.AnalyticWindow.getType () inline
Definition at line 188 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.type_.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.standardize().
AnalyticWindow com.cloudera.impala.analysis.AnalyticWindow.reverse () inline
Definition at line 221 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.getType(), com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_, com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, and com.cloudera.impala.analysis.AnalyticWindow.type_.
Boundary com.cloudera.impala.analysis.AnalyticWindow.setRightBoundary (Boundary b) inline
Definition at line 191 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_.
String com.cloudera.impala.analysis.AnalyticWindow.toSql () inline
Definition at line 232 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_, com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, com.cloudera.impala.analysis.AnalyticWindow.Boundary.toSql(), and com.cloudera.impala.analysis.AnalyticWindow.toSqlString_.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), and com.cloudera.impala.analysis.AnalyticWindow.checkOffsetBoundaries().
TAnalyticWindow com.cloudera.impala.analysis.AnalyticWindow.toThrift () inline
Definition at line 245 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.getType(), com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_, com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_, com.cloudera.impala.analysis.AnalyticWindow.Type.toThrift(), com.cloudera.impala.analysis.AnalyticWindow.type_, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_FOLLOWING, and com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_PRECEDING.
Member Data Documentation
final AnalyticWindow com.cloudera.impala.analysis.AnalyticWindow.DEFAULT_WINDOW static
Initial value:
= new AnalyticWindow(Type.RANGE,
      new Boundary(BoundaryType.UNBOUNDED_PRECEDING, null),
      new Boundary(BoundaryType.CURRENT_ROW, null))
Definition at line 37 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.standardize().
final Boundary com.cloudera.impala.analysis.AnalyticWindow.leftBoundary_ private
Definition at line 184 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow(), com.cloudera.impala.analysis.AnalyticWindow.analyze(), com.cloudera.impala.analysis.AnalyticWindow.getLeftBoundary(), com.cloudera.impala.analysis.AnalyticWindow.reverse(), com.cloudera.impala.analysis.AnalyticWindow.toSql(), and com.cloudera.impala.analysis.AnalyticWindow.toThrift().
Boundary com.cloudera.impala.analysis.AnalyticWindow.rightBoundary_ private
Definition at line 185 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow(), com.cloudera.impala.analysis.AnalyticWindow.analyze(), com.cloudera.impala.analysis.AnalyticWindow.equals(), com.cloudera.impala.analysis.AnalyticWindow.getRightBoundary(), com.cloudera.impala.analysis.AnalyticWindow.reverse(), com.cloudera.impala.analysis.AnalyticWindow.setRightBoundary(), com.cloudera.impala.analysis.AnalyticWindow.toSql(), and com.cloudera.impala.analysis.AnalyticWindow.toThrift().
String com.cloudera.impala.analysis.AnalyticWindow.toSqlString_ private
Definition at line 186 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow(), com.cloudera.impala.analysis.AnalyticWindow.analyze(), and com.cloudera.impala.analysis.AnalyticWindow.toSql().
final Type com.cloudera.impala.analysis.AnalyticWindow.type_ private
Definition at line 183 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.AnalyticWindow(), com.cloudera.impala.analysis.AnalyticWindow.analyze(), com.cloudera.impala.analysis.AnalyticWindow.checkOffsetExpr(), com.cloudera.impala.analysis.AnalyticWindow.equals(), com.cloudera.impala.analysis.AnalyticWindow.getType(), com.cloudera.impala.analysis.AnalyticWindow.reverse(), and com.cloudera.impala.analysis.AnalyticWindow.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AnalyticWindow.java