Impala: impala::CastFunctions Class Reference
impala::CastFunctions Class Reference
#include <cast-functions.h>
Static Public Member Functions
static BooleanVal CastToBooleanVal (FunctionContext *context, const TinyIntVal &val)
static BooleanVal CastToBooleanVal (FunctionContext *context, const SmallIntVal &val)
static BooleanVal CastToBooleanVal (FunctionContext *context, const IntVal &val)
static BooleanVal CastToBooleanVal (FunctionContext *context, const BigIntVal &val)
static BooleanVal CastToBooleanVal (FunctionContext *context, const FloatVal &val)
static BooleanVal CastToBooleanVal (FunctionContext *context, const DoubleVal &val)
static BooleanVal CastToBooleanVal (FunctionContext *context, const TimestampVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const BooleanVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const SmallIntVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const IntVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const BigIntVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const FloatVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const DoubleVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const StringVal &val)
static TinyIntVal CastToTinyIntVal (FunctionContext *context, const TimestampVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const BooleanVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const TinyIntVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const IntVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const BigIntVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const FloatVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const DoubleVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const StringVal &val)
static SmallIntVal CastToSmallIntVal (FunctionContext *context, const TimestampVal &val)
static IntVal CastToIntVal (FunctionContext *context, const BooleanVal &val)
static IntVal CastToIntVal (FunctionContext *context, const TinyIntVal &val)
static IntVal CastToIntVal (FunctionContext *context, const SmallIntVal &val)
static IntVal CastToIntVal (FunctionContext *context, const BigIntVal &val)
static IntVal CastToIntVal (FunctionContext *context, const FloatVal &val)
static IntVal CastToIntVal (FunctionContext *context, const DoubleVal &val)
static IntVal CastToIntVal (FunctionContext *context, const StringVal &val)
static IntVal CastToIntVal (FunctionContext *context, const TimestampVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const BooleanVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const TinyIntVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const SmallIntVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const IntVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const FloatVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const DoubleVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const StringVal &val)
static BigIntVal CastToBigIntVal (FunctionContext *context, const TimestampVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const BooleanVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const TinyIntVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const SmallIntVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const IntVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const BigIntVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const DoubleVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const StringVal &val)
static FloatVal CastToFloatVal (FunctionContext *context, const TimestampVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const BooleanVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const TinyIntVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const SmallIntVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const IntVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const BigIntVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const FloatVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const StringVal &val)
static DoubleVal CastToDoubleVal (FunctionContext *context, const TimestampVal &val)
static StringVal CastToStringVal (FunctionContext *context, const BooleanVal &val)
static StringVal CastToStringVal (FunctionContext *context, const TinyIntVal &val)
static StringVal CastToStringVal (FunctionContext *context, const SmallIntVal &val)
static StringVal CastToStringVal (FunctionContext *context, const IntVal &val)
static StringVal CastToStringVal (FunctionContext *context, const BigIntVal &val)
static StringVal CastToStringVal (FunctionContext *context, const FloatVal &val)
static StringVal CastToStringVal (FunctionContext *context, const DoubleVal &val)
static StringVal CastToStringVal (FunctionContext *context, const TimestampVal &val)
static StringVal CastToStringVal (FunctionContext *context, const StringVal &val)
static StringVal CastToChar (FunctionContext *context, const StringVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const BooleanVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const TinyIntVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const SmallIntVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const IntVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const BigIntVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const FloatVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const DoubleVal &val)
static TimestampVal CastToTimestampVal (FunctionContext *context, const StringVal &val)
Detailed Description
Definition at line 25 of file cast-functions.h.
Member Function Documentation
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const BooleanVal & val) static
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const TinyIntVal & val) static
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const SmallIntVal & val) static
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const IntVal & val) static
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const FloatVal & val) static
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const DoubleVal & val) static
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const StringVal & val) static
static BigIntVal impala::CastFunctions::CastToBigIntVal (FunctionContext * context, const TimestampVal & val) static
static BooleanVal impala::CastFunctions::CastToBooleanVal (FunctionContext * context, const TinyIntVal & val) static
Referenced by impala::Expr::InitBuiltinsDummy().
static BooleanVal impala::CastFunctions::CastToBooleanVal (FunctionContext * context, const SmallIntVal & val) static
static BooleanVal impala::CastFunctions::CastToBooleanVal (FunctionContext * context, const IntVal & val) static
static BooleanVal impala::CastFunctions::CastToBooleanVal (FunctionContext * context, const BigIntVal & val) static
static BooleanVal impala::CastFunctions::CastToBooleanVal (FunctionContext * context, const FloatVal & val) static
static BooleanVal impala::CastFunctions::CastToBooleanVal (FunctionContext * context, const DoubleVal & val) static
static BooleanVal impala::CastFunctions::CastToBooleanVal (FunctionContext * context, const TimestampVal & val) static
StringVal CastFunctions::CastToChar (FunctionContext * context, const StringVal & val) static
Definition at line 173 of file cast-functions.cc.
References impala::FunctionContextImpl::AllocateLocal(), impala_udf::FunctionContext::GetReturnType(), impala_udf::FunctionContext::impl(), impala_udf::AnyVal::is_null, impala::ColumnType::len, impala_udf::StringVal::len, impala::StringValue::PadWithSpaces(), impala_udf::StringVal::ptr, impala::ColumnType::type, impala::TYPE_CHAR, and impala::AnyValUtil::TypeDescToColumnType().
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const BooleanVal & val) static
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const TinyIntVal & val) static
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const SmallIntVal & val) static
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const IntVal & val) static
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const BigIntVal & val) static
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const FloatVal & val) static
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const StringVal & val) static
static DoubleVal impala::CastFunctions::CastToDoubleVal (FunctionContext * context, const TimestampVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const BooleanVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const TinyIntVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const SmallIntVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const IntVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const BigIntVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const DoubleVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const StringVal & val) static
static FloatVal impala::CastFunctions::CastToFloatVal (FunctionContext * context, const TimestampVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const BooleanVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const TinyIntVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const SmallIntVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const BigIntVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const FloatVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const DoubleVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const StringVal & val) static
static IntVal impala::CastFunctions::CastToIntVal (FunctionContext * context, const TimestampVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const BooleanVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const TinyIntVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const IntVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const BigIntVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const FloatVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const DoubleVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const StringVal & val) static
static SmallIntVal impala::CastFunctions::CastToSmallIntVal (FunctionContext * context, const TimestampVal & val) static
static StringVal impala::CastFunctions::CastToStringVal (FunctionContext * context, const BooleanVal & val) static
StringVal CastFunctions::CastToStringVal (FunctionContext * context, const TinyIntVal & val) static
Definition at line 145 of file cast-functions.cc.
References impala::AnyValUtil::FromString(), impala_udf::FunctionContext::GetReturnType(), impala_udf::AnyVal::is_null, impala::AnyValUtil::TruncateIfNecessary(), impala::AnyValUtil::TypeDescToColumnType(), and impala_udf::TinyIntVal::val.
static StringVal impala::CastFunctions::CastToStringVal (FunctionContext * context, const SmallIntVal & val) static
static StringVal impala::CastFunctions::CastToStringVal (FunctionContext * context, const IntVal & val) static
static StringVal impala::CastFunctions::CastToStringVal (FunctionContext * context, const BigIntVal & val) static
static StringVal impala::CastFunctions::CastToStringVal (FunctionContext * context, const FloatVal & val) static
static StringVal impala::CastFunctions::CastToStringVal (FunctionContext * context, const DoubleVal & val) static
StringVal CastFunctions::CastToStringVal (FunctionContext * context, const TimestampVal & val) static
Definition at line 154 of file cast-functions.cc.
References impala::AnyValUtil::FromString(), impala::TimestampValue::FromTimestampVal(), impala_udf::FunctionContext::GetReturnType(), impala_udf::AnyVal::is_null, impala::AnyValUtil::TruncateIfNecessary(), and impala::AnyValUtil::TypeDescToColumnType().
StringVal CastFunctions::CastToStringVal (FunctionContext * context, const StringVal & val) static
Definition at line 163 of file cast-functions.cc.
References impala_udf::FunctionContext::GetReturnType(), impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::ptr, impala::AnyValUtil::TruncateIfNecessary(), and impala::AnyValUtil::TypeDescToColumnType().
static TimestampVal impala::CastFunctions::CastToTimestampVal (FunctionContext * context, const BooleanVal & val) static
static TimestampVal impala::CastFunctions::CastToTimestampVal (FunctionContext * context, const TinyIntVal & val) static
static TimestampVal impala::CastFunctions::CastToTimestampVal (FunctionContext * context, const SmallIntVal & val) static
static TimestampVal impala::CastFunctions::CastToTimestampVal (FunctionContext * context, const IntVal & val) static
static TimestampVal impala::CastFunctions::CastToTimestampVal (FunctionContext * context, const BigIntVal & val) static
static TimestampVal impala::CastFunctions::CastToTimestampVal (FunctionContext * context, const FloatVal & val) static
static TimestampVal impala::CastFunctions::CastToTimestampVal (FunctionContext * context, const DoubleVal & val) static
TimestampVal CastFunctions::CastToTimestampVal (FunctionContext * context, const StringVal & val) static
Definition at line 239 of file cast-functions.cc.
References impala::TimestampValue::HasDateOrTime(), impala_udf::AnyVal::is_null, impala_udf::StringVal::len, impala_udf::StringVal::ptr, and impala::TimestampValue::ToTimestampVal().
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const BooleanVal & val) static
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const SmallIntVal & val) static
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const IntVal & val) static
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const BigIntVal & val) static
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const FloatVal & val) static
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const DoubleVal & val) static
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const StringVal & val) static
static TinyIntVal impala::CastFunctions::CastToTinyIntVal (FunctionContext * context, const TimestampVal & val) static
The documentation for this class was generated from the following files:
be/src/exprs/cast-functions.h
be/src/exprs/cast-functions.cc