Impala: apache::thrift::transport::TSaslServerTransport::Factory Class Reference
apache::thrift::transport::TSaslServerTransport::Factory Class Reference
#include <TSaslServerTransport.h>
Public Member Functions
Factory ()
Factory (const std::string &mechanism, const std::string &protocol, const std::string &serverName, const std::string &realm, unsigned flags, std::map< std::string, std::string > props, std::vector< struct sasl_callback > callbacks)
virtual ~Factory ()
virtual boost::shared_ptr
< TTransport > getTransport (boost::shared_ptr< TTransport > trans)
void addServerDefinition (const std::string &mechanism, const std::string &protocol, const std::string &serverName, const std::string &realm, unsigned int flags, std::map< std::string, std::string > props, std::vector< struct sasl_callback > callbacks)
Private Attributes
std::map< std::string,
TSaslServerDefinition * > serverDefinitionMap_
std::map< boost::shared_ptr
< TTransport >
, boost::shared_ptr
< TBufferedTransport > > transportMap_
boost::mutex transportMap_mutex_
Detailed Description
Factory to ensure that a given underlying TTransport instance receives the same TSaslServerTransport for both send and receive.
Definition at line 133 of file TSaslServerTransport.h.
Constructor & Destructor Documentation
apache::thrift::transport::TSaslServerTransport::Factory::Factory () inline
Definition at line 135 of file TSaslServerTransport.h.
apache::thrift::transport::TSaslServerTransport::Factory::Factory (const std::string & mechanism, const std::string & protocol, const std::string & serverName, const std::string & realm, unsigned flags, std::map< std::string, std::string > props, std::vector< struct sasl_callback > callbacks) inline
Create a new Factor for a server definition. Provides a single definition for the server, others may be added.
Definition at line 141 of file TSaslServerTransport.h.
References addServerDefinition().
virtual apache::thrift::transport::TSaslServerTransport::Factory::~Factory () inline virtual
Definition at line 150 of file TSaslServerTransport.h.
Member Function Documentation
void apache::thrift::transport::TSaslServerTransport::Factory::addServerDefinition (const std::string & mechanism, const std::string & protocol, const std::string & serverName, const std::string & realm, unsigned int flags, std::map< std::string, std::string > props, std::vector< struct sasl_callback > callbacks) inline
Definition at line 159 of file TSaslServerTransport.h.
References serverDefinitionMap_.
Referenced by Factory(), and impala::SaslAuthProvider::GetServerTransportFactory().
shared_ptr< TTransport > apache::thrift::transport::TSaslServerTransport::Factory::getTransport (boost::shared_ptr< TTransport > trans) virtual
Wraps the transport with the Sasl protocol.
Definition at line 114 of file TSaslServerTransport.cpp.
References serverDefinitionMap_, transportMap_, transportMap_mutex_, and apache::thrift::transport::TSaslServerTransport::TSaslServerTransport().
Member Data Documentation
std::map<std::string, TSaslServerDefinition*> apache::thrift::transport::TSaslServerTransport::Factory::serverDefinitionMap_ private
Definition at line 173 of file TSaslServerTransport.h.
Referenced by addServerDefinition(), and getTransport().
std::map<boost::shared_ptr<TTransport>, boost::shared_ptr<TBufferedTransport> > apache::thrift::transport::TSaslServerTransport::Factory::transportMap_ private
Definition at line 177 of file TSaslServerTransport.h.
Referenced by getTransport().
boost::mutex apache::thrift::transport::TSaslServerTransport::Factory::transportMap_mutex_ private
Definition at line 180 of file TSaslServerTransport.h.
Referenced by getTransport().
The documentation for this class was generated from the following files:
be/src/transport/TSaslServerTransport.h
be/src/transport/TSaslServerTransport.cpp