Impala: com.cloudera.impala.planner.AnalyticPlanner.SortGroup Class Reference
com.cloudera.impala.planner.AnalyticPlanner.SortGroup Class Reference
Classes
class SizeLt
Public Member Functions
SortGroup (WindowGroup windowGroup)
boolean isCompatible (WindowGroup windowGroup)
void add (WindowGroup windowGroup)
boolean isPrefixOf (SortGroup other)
void absorb (SortGroup other)
void init ()
void orderWindowGroups ()
Public Attributes
List< Expr > partitionByExprs
List< OrderByElement > orderByElements
List< WindowGroup > windowGroups = Lists.newArrayList()
int totalOutputTupleSize = -1
Static Package Functions
[static initializer]
Static Private Attributes
static final SizeLt SIZE_LT
Detailed Description
Collection of WindowGroups that share the same partition-by/order-by specification.
Definition at line 636 of file AnalyticPlanner.java.
Constructor & Destructor Documentation
com.cloudera.impala.planner.AnalyticPlanner.SortGroup.SortGroup (WindowGroup windowGroup) inline
Definition at line 644 of file AnalyticPlanner.java.
References com.cloudera.impala.planner.AnalyticPlanner.SortGroup.orderByElements, and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.partitionByExprs.
Member Function Documentation
com.cloudera.impala.planner.AnalyticPlanner.SortGroup.[static initializer] () inline static package
void com.cloudera.impala.planner.AnalyticPlanner.SortGroup.absorb (SortGroup other) inline
Adds other's window groups to ours, assuming that we're a prefix of other.
Definition at line 685 of file AnalyticPlanner.java.
References com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf().
void com.cloudera.impala.planner.AnalyticPlanner.SortGroup.add (WindowGroup windowGroup) inline
Definition at line 658 of file AnalyticPlanner.java.
References com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isCompatible().
void com.cloudera.impala.planner.AnalyticPlanner.SortGroup.init () inline
Compute totalOutputTupleSize.
Definition at line 693 of file AnalyticPlanner.java.
References com.cloudera.impala.planner.AnalyticPlanner.SortGroup.totalOutputTupleSize, and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.windowGroups.
boolean com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isCompatible (WindowGroup windowGroup) inline
True if the partition and ordering exprs of windowGroup match ours.
Definition at line 653 of file AnalyticPlanner.java.
References com.cloudera.impala.planner.AnalyticPlanner.WindowGroup.orderByElements, com.cloudera.impala.planner.AnalyticPlanner.SortGroup.orderByElements, and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.partitionByExprs.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.add().
boolean com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf (SortGroup other) inline
Return true if 'this' and other have compatible partition exprs and our orderByElements are a prefix of other's.
Definition at line 667 of file AnalyticPlanner.java.
References com.cloudera.impala.analysis.Expr.equalSets(), com.cloudera.impala.analysis.OrderByElement.getExpr(), com.cloudera.impala.analysis.OrderByElement.isAsc(), com.cloudera.impala.analysis.OrderByElement.nullsFirst(), com.cloudera.impala.planner.AnalyticPlanner.SortGroup.orderByElements, and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.partitionByExprs.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.absorb().
void com.cloudera.impala.planner.AnalyticPlanner.SortGroup.orderWindowGroups () inline
Order window groups by increasing size of the output tuple. This minimizes the total volume of data that needs to be buffered.
Definition at line 724 of file AnalyticPlanner.java.
References com.cloudera.impala.planner.AnalyticPlanner.SortGroup.SIZE_LT, and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.windowGroups.
Member Data Documentation
List<OrderByElement> com.cloudera.impala.planner.AnalyticPlanner.SortGroup.orderByElements
Definition at line 638 of file AnalyticPlanner.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isCompatible(), com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf(), and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.SortGroup().
List<Expr> com.cloudera.impala.planner.AnalyticPlanner.SortGroup.partitionByExprs
Definition at line 637 of file AnalyticPlanner.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isCompatible(), com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf(), and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.SortGroup().
final SizeLt com.cloudera.impala.planner.AnalyticPlanner.SortGroup.SIZE_LT static private
Definition at line 715 of file AnalyticPlanner.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.orderWindowGroups().
int com.cloudera.impala.planner.AnalyticPlanner.SortGroup.totalOutputTupleSize = -1
Definition at line 642 of file AnalyticPlanner.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.init().
List<WindowGroup> com.cloudera.impala.planner.AnalyticPlanner.SortGroup.windowGroups = Lists.newArrayList()
Definition at line 639 of file AnalyticPlanner.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.init(), and com.cloudera.impala.planner.AnalyticPlanner.SortGroup.orderWindowGroups().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/planner/AnalyticPlanner.java