Impala: com.cloudera.impala.analysis.OrderByElement Class Reference
com.cloudera.impala.analysis.OrderByElement Class Reference
Public Member Functions
OrderByElement (Expr expr, boolean isAsc, Boolean nullsFirstParam)
Expr getExpr ()
void setExpr (Expr e)
boolean isAsc ()
Boolean getNullsFirstParam ()
boolean nullsFirst ()
String toSql ()
boolean equals (Object obj)
OrderByElement clone ()
Static Public Member Functions
static boolean nullsFirst (Boolean nullsFirstParam, boolean isAsc)
static List< OrderByElement > substitute (List< OrderByElement > src, ExprSubstitutionMap smap, Analyzer analyzer)
static List< Expr > getOrderByExprs (List< OrderByElement > src)
static List< OrderByElement > reverse (List< OrderByElement > src)
Private Attributes
Expr expr_
final boolean isAsc_
final Boolean nullsFirstParam_
Detailed Description
Combination of expr, ASC/DESC, and nulls ordering.
Definition at line 25 of file OrderByElement.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.OrderByElement.OrderByElement (Expr expr, boolean isAsc, Boolean nullsFirstParam) inline
Constructs the OrderByElement.
'nullsFirstParam' should be true if "NULLS FIRST", false if "NULLS LAST", or null if the NULLs order was not specified.
Definition at line 38 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.isAsc().
Referenced by com.cloudera.impala.analysis.OrderByElement.clone(), com.cloudera.impala.analysis.OrderByElement.equals(), com.cloudera.impala.analysis.OrderByElement.reverse(), and com.cloudera.impala.analysis.OrderByElement.substitute().
Member Function Documentation
OrderByElement com.cloudera.impala.analysis.OrderByElement.clone () inline
Definition at line 85 of file OrderByElement.java.
References com.cloudera.impala.analysis.Expr.clone(), com.cloudera.impala.analysis.OrderByElement.expr_, com.cloudera.impala.analysis.OrderByElement.isAsc_, com.cloudera.impala.analysis.OrderByElement.nullsFirstParam_, and com.cloudera.impala.analysis.OrderByElement.OrderByElement().
boolean com.cloudera.impala.analysis.OrderByElement.equals (Object obj) inline
Definition at line 72 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.isAsc_, com.cloudera.impala.analysis.OrderByElement.nullsFirstParam_, and com.cloudera.impala.analysis.OrderByElement.OrderByElement().
Expr com.cloudera.impala.analysis.OrderByElement.getExpr () inline
Definition at line 45 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.expr_.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf(), and com.cloudera.impala.analysis.OrderByElement.reverse().
Boolean com.cloudera.impala.analysis.OrderByElement.getNullsFirstParam () inline
Definition at line 48 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.nullsFirstParam_.
static List<Expr> com.cloudera.impala.analysis.OrderByElement.getOrderByExprs (List< OrderByElement > src) inline static
Extracts the order-by exprs from the list of order-by elements and returns them.
Definition at line 123 of file OrderByElement.java.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.createSortGroupPlan().
boolean com.cloudera.impala.analysis.OrderByElement.isAsc () inline
Definition at line 47 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.isAsc_.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf(), and com.cloudera.impala.analysis.OrderByElement.OrderByElement().
boolean com.cloudera.impala.analysis.OrderByElement.nullsFirst () inline
Definition at line 49 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.isAsc_, com.cloudera.impala.analysis.OrderByElement.nullsFirst(), and com.cloudera.impala.analysis.OrderByElement.nullsFirstParam_.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.SortGroup.isPrefixOf(), com.cloudera.impala.analysis.OrderByElement.nullsFirst(), and com.cloudera.impala.analysis.OrderByElement.reverse().
static boolean com.cloudera.impala.analysis.OrderByElement.nullsFirst (Boolean nullsFirstParam, boolean isAsc) inline static
Compute nullsFirst.
Parameters
nullsFirstParam True if "NULLS FIRST", false if "NULLS LAST", or null if the NULLs order was not specified.
isAsc
Returns
Returns true if nulls are ordered first or false if nulls are ordered last. Independent of isAsc.
Definition at line 102 of file OrderByElement.java.
static List<OrderByElement> com.cloudera.impala.analysis.OrderByElement.reverse (List< OrderByElement > src) inline static
Returns a new list of OrderByElements with the same (cloned) expressions but the ordering direction reversed (asc becomes desc, nulls first becomes nulls last, etc.)
Definition at line 135 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.getExpr(), com.cloudera.impala.analysis.OrderByElement.isAsc_, com.cloudera.impala.analysis.OrderByElement.nullsFirst(), com.cloudera.impala.analysis.OrderByElement.nullsFirstParam_, and com.cloudera.impala.analysis.OrderByElement.OrderByElement().
void com.cloudera.impala.analysis.OrderByElement.setExpr (Expr e) inline
Definition at line 46 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.expr_.
static List<OrderByElement> com.cloudera.impala.analysis.OrderByElement.substitute (List< OrderByElement > src, ExprSubstitutionMap smap, Analyzer analyzer) inline static
Returns a new list of order-by elements with the order by exprs of src substituted according to smap. Preserves the other sort params from src.
Definition at line 110 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.OrderByElement().
Referenced by com.cloudera.impala.planner.AnalyticPlanner.createSortGroupPlan().
String com.cloudera.impala.analysis.OrderByElement.toSql () inline
Definition at line 51 of file OrderByElement.java.
References com.cloudera.impala.analysis.OrderByElement.isAsc_, and com.cloudera.impala.analysis.OrderByElement.nullsFirstParam_.
Member Data Documentation
Expr com.cloudera.impala.analysis.OrderByElement.expr_ private
Definition at line 26 of file OrderByElement.java.
Referenced by com.cloudera.impala.analysis.OrderByElement.clone(), com.cloudera.impala.analysis.OrderByElement.getExpr(), and com.cloudera.impala.analysis.OrderByElement.setExpr().
final boolean com.cloudera.impala.analysis.OrderByElement.isAsc_ private
Definition at line 27 of file OrderByElement.java.
Referenced by com.cloudera.impala.analysis.OrderByElement.clone(), com.cloudera.impala.analysis.OrderByElement.equals(), com.cloudera.impala.analysis.OrderByElement.isAsc(), com.cloudera.impala.analysis.OrderByElement.nullsFirst(), com.cloudera.impala.analysis.OrderByElement.reverse(), and com.cloudera.impala.analysis.OrderByElement.toSql().
final Boolean com.cloudera.impala.analysis.OrderByElement.nullsFirstParam_ private
Definition at line 30 of file OrderByElement.java.
Referenced by com.cloudera.impala.analysis.OrderByElement.clone(), com.cloudera.impala.analysis.OrderByElement.equals(), com.cloudera.impala.analysis.OrderByElement.getNullsFirstParam(), com.cloudera.impala.analysis.OrderByElement.nullsFirst(), com.cloudera.impala.analysis.OrderByElement.reverse(), and com.cloudera.impala.analysis.OrderByElement.toSql().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/OrderByElement.java