Impala: com.cloudera.impala.analysis.UnionStmt.UnionOperand Class Reference
com.cloudera.impala.analysis.UnionStmt.UnionOperand Class Reference
Public Member Functions
UnionOperand (QueryStmt queryStmt, Qualifier qualifier)
void analyze (Analyzer parent) throws AnalysisException
QueryStmt getQueryStmt ()
Qualifier getQualifier ()
void setQualifier (Qualifier qualifier)
Analyzer getAnalyzer ()
ExprSubstitutionMap getSmap ()
void drop ()
boolean isDropped ()
UnionOperand clone ()
boolean hasAnalyticExprs ()
Private Attributes
final QueryStmt queryStmt_
Qualifier qualifier_
Analyzer analyzer_
final ExprSubstitutionMap smap_ = new ExprSubstitutionMap()
boolean isDropped_ = false
Detailed Description
Represents an operand to a union, created by the parser. Contains a query statement and the all/distinct qualifier of the union operator (null for the first queryStmt).
Definition at line 50 of file UnionStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.UnionStmt.UnionOperand.UnionOperand (QueryStmt queryStmt, Qualifier qualifier) inline
Definition at line 66 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.UnionOperand.clone().
Member Function Documentation
void com.cloudera.impala.analysis.UnionStmt.UnionOperand.analyze (Analyzer parent) throws AnalysisException inline
Definition at line 71 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.analyzer_.
UnionOperand com.cloudera.impala.analysis.UnionStmt.UnionOperand.clone () inline
Definition at line 86 of file UnionStmt.java.
References com.cloudera.impala.analysis.QueryStmt.clone(), com.cloudera.impala.analysis.UnionStmt.UnionOperand.qualifier_, com.cloudera.impala.analysis.UnionStmt.UnionOperand.queryStmt_, and com.cloudera.impala.analysis.UnionStmt.UnionOperand.UnionOperand().
void com.cloudera.impala.analysis.UnionStmt.UnionOperand.drop () inline
Definition at line 82 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.isDropped_.
Analyzer com.cloudera.impala.analysis.UnionStmt.UnionOperand.getAnalyzer () inline
Definition at line 80 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.analyzer_.
Qualifier com.cloudera.impala.analysis.UnionStmt.UnionOperand.getQualifier () inline
Definition at line 77 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.qualifier_.
Referenced by com.cloudera.impala.analysis.UnionStmt.propagateDistinct(), and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
QueryStmt com.cloudera.impala.analysis.UnionStmt.UnionOperand.getQueryStmt () inline
Definition at line 76 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.queryStmt_.
ExprSubstitutionMap com.cloudera.impala.analysis.UnionStmt.UnionOperand.getSmap () inline
Definition at line 81 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.smap_.
boolean com.cloudera.impala.analysis.UnionStmt.UnionOperand.hasAnalyticExprs () inline
Definition at line 90 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.queryStmt_, and com.cloudera.impala.analysis.UnionStmt.UnionStmt().
boolean com.cloudera.impala.analysis.UnionStmt.UnionOperand.isDropped () inline
Definition at line 83 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.UnionOperand.isDropped_.
void com.cloudera.impala.analysis.UnionStmt.UnionOperand.setQualifier (Qualifier qualifier) inline
Definition at line 79 of file UnionStmt.java.
Member Data Documentation
Analyzer com.cloudera.impala.analysis.UnionStmt.UnionOperand.analyzer_ private
Definition at line 57 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.UnionOperand.analyze(), and com.cloudera.impala.analysis.UnionStmt.UnionOperand.getAnalyzer().
boolean com.cloudera.impala.analysis.UnionStmt.UnionOperand.isDropped_ = false private
Definition at line 64 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.UnionOperand.drop(), and com.cloudera.impala.analysis.UnionStmt.UnionOperand.isDropped().
Qualifier com.cloudera.impala.analysis.UnionStmt.UnionOperand.qualifier_ private
Definition at line 53 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.UnionOperand.clone(), and com.cloudera.impala.analysis.UnionStmt.UnionOperand.getQualifier().
final QueryStmt com.cloudera.impala.analysis.UnionStmt.UnionOperand.queryStmt_ private
Definition at line 51 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.UnionOperand.clone(), com.cloudera.impala.analysis.UnionStmt.UnionOperand.getQueryStmt(), and com.cloudera.impala.analysis.UnionStmt.UnionOperand.hasAnalyticExprs().
final ExprSubstitutionMap com.cloudera.impala.analysis.UnionStmt.UnionOperand.smap_ = new ExprSubstitutionMap() private
Definition at line 60 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.UnionOperand.getSmap().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/UnionStmt.java