Impala: impala::BufferedBlockMgrTest Class Reference
impala::BufferedBlockMgrTest Class Reference
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
shared_ptr< BufferedBlockMgr > CreateMgr (int max_buffers)
void AllocateBlocks (BufferedBlockMgr *block_mgr, BufferedBlockMgr::Client *client, int num_blocks, vector< BufferedBlockMgr::Block * > *blocks)
void TestRandomInternalImpl (BufferedBlockMgr *block_mgr, int num_buffers, int tid)
void TestRandomInternalSingle ()
void TestRandomInternalMulti (int num_threads)
Static Protected Member Functions
static void GetFreeBlock (BufferedBlockMgr *block_mgr, BufferedBlockMgr::Client *client, BufferedBlockMgr::Block **new_block, Promise< bool > *promise)
static void ValidateBlock (BufferedBlockMgr::Block *block, int32_t data)
static int32_t * MakeRandomSizeData (BufferedBlockMgr::Block *block)
static void ValidateRandomSizeData (BufferedBlockMgr::Block *block, int32_t size)
Protected Attributes
scoped_ptr< ExecEnv > exec_env_
scoped_ptr< RuntimeState > runtime_state_
scoped_ptr< MemTracker > block_mgr_parent_tracker_
scoped_ptr< MemTracker > io_mgr_tracker_
Static Protected Attributes
static const int block_size_ = 1024
static const int SINGLE_THREADED_TID = -1
Detailed Description
Definition at line 53 of file buffered-block-mgr-test.cc.
Member Function Documentation
void impala::BufferedBlockMgrTest::AllocateBlocks (BufferedBlockMgr * block_mgr, BufferedBlockMgr::Client * client, int num_blocks, vector< BufferedBlockMgr::Block * > * blocks) inline protected
Definition at line 124 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Block::Allocate(), impala::BufferedBlockMgr::GetNewBlock(), and impala::Status::ok().
shared_ptr<BufferedBlockMgr> impala::BufferedBlockMgrTest::CreateMgr (int max_buffers) inline protected
Definition at line 114 of file buffered-block-mgr-test.cc.
References block_mgr_parent_tracker_, block_size_, impala::BufferedBlockMgr::Create(), and runtime_state_.
Referenced by TestRandomInternalMulti(), and TestRandomInternalSingle().
static void impala::BufferedBlockMgrTest::GetFreeBlock (BufferedBlockMgr * block_mgr, BufferedBlockMgr::Client * client, BufferedBlockMgr::Block ** new_block, Promise< bool > * promise) inline static protected
Definition at line 74 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::GetNewBlock(), and impala::Promise< T >::Set().
static int32_t* impala::BufferedBlockMgrTest::MakeRandomSizeData (BufferedBlockMgr::Block * block) inline static protected
Definition at line 85 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Block::Allocate().
Referenced by TestRandomInternalImpl().
virtual void impala::BufferedBlockMgrTest::SetUp () inline protected virtual
Definition at line 57 of file buffered-block-mgr-test.cc.
References block_mgr_parent_tracker_, exec_env_, io_mgr_tracker_, and runtime_state_.
virtual void impala::BufferedBlockMgrTest::TearDown () inline protected virtual
Definition at line 67 of file buffered-block-mgr-test.cc.
References block_mgr_parent_tracker_, exec_env_, io_mgr_tracker_, and runtime_state_.
void impala::BufferedBlockMgrTest::TestRandomInternalImpl (BufferedBlockMgr * block_mgr, int num_buffers, int tid) inline protected
Definition at line 144 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Cancel(), impala::BufferedBlockMgr::GetNewBlock(), impala::Status::IsCancelled(), MakeRandomSizeData(), impala::Status::ok(), impala::BufferedBlockMgr::RegisterClient(), runtime_state_, SINGLE_THREADED_TID, and ValidateRandomSizeData().
Referenced by TestRandomInternalMulti(), and TestRandomInternalSingle().
void impala::BufferedBlockMgrTest::TestRandomInternalMulti (int num_threads) inline protected
Definition at line 276 of file buffered-block-mgr-test.cc.
References block_mgr_parent_tracker_, CreateMgr(), and TestRandomInternalImpl().
void impala::BufferedBlockMgrTest::TestRandomInternalSingle () inline protected
Definition at line 267 of file buffered-block-mgr-test.cc.
References block_mgr_parent_tracker_, CreateMgr(), SINGLE_THREADED_TID, and TestRandomInternalImpl().
static void impala::BufferedBlockMgrTest::ValidateBlock (BufferedBlockMgr::Block * block, int32_t data) inline static protected
Definition at line 80 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Block::buffer(), and impala::BufferedBlockMgr::Block::valid_data_len().
static void impala::BufferedBlockMgrTest::ValidateRandomSizeData (BufferedBlockMgr::Block * block, int32_t size) inline static protected
Definition at line 100 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Block::buffer(), and impala::BufferedBlockMgr::Block::valid_data_len().
Referenced by TestRandomInternalImpl().
Member Data Documentation
scoped_ptr<MemTracker> impala::BufferedBlockMgrTest::block_mgr_parent_tracker_ protected
Definition at line 293 of file buffered-block-mgr-test.cc.
Referenced by CreateMgr(), SetUp(), TearDown(), TestRandomInternalMulti(), and TestRandomInternalSingle().
const int impala::BufferedBlockMgrTest::block_size_ = 1024 static protected
Definition at line 55 of file buffered-block-mgr-test.cc.
Referenced by CreateMgr().
scoped_ptr<ExecEnv> impala::BufferedBlockMgrTest::exec_env_ protected
Definition at line 291 of file buffered-block-mgr-test.cc.
Referenced by SetUp(), and TearDown().
scoped_ptr<MemTracker> impala::BufferedBlockMgrTest::io_mgr_tracker_ protected
Definition at line 294 of file buffered-block-mgr-test.cc.
Referenced by SetUp(), and TearDown().
scoped_ptr<RuntimeState> impala::BufferedBlockMgrTest::runtime_state_ protected
Definition at line 292 of file buffered-block-mgr-test.cc.
Referenced by CreateMgr(), SetUp(), TearDown(), and TestRandomInternalImpl().
const int impala::BufferedBlockMgrTest::SINGLE_THREADED_TID = -1 static protected
Definition at line 143 of file buffered-block-mgr-test.cc.
Referenced by TestRandomInternalImpl(), and TestRandomInternalSingle().
The documentation for this class was generated from the following file:
be/src/runtime/buffered-block-mgr-test.cc