Impala: impala::RuntimeProfile::TimeSeriesCounter Class Reference
impala::RuntimeProfile::TimeSeriesCounter Class Reference
#include <runtime-profile.h>
Public Member Functions
std::string DebugString () const
void AddSample (int ms_elapsed)
Private Member Functions
TimeSeriesCounter (const std::string &name, TUnit::type unit, DerivedCounterFunction fn)
TimeSeriesCounter (const std::string &name, TUnit::type unit, int period, const std::vector< int64_t > &values)
void ToThrift (TTimeSeriesCounter *counter)
Private Attributes
std::string name_
TUnit::type unit_
DerivedCounterFunction sample_fn_
StreamingCounterSampler samples_
Friends
class RuntimeProfile
Detailed Description
Definition at line 321 of file runtime-profile.h.
Constructor & Destructor Documentation
impala::RuntimeProfile::TimeSeriesCounter::TimeSeriesCounter (const std::string & name, TUnit::type unit, DerivedCounterFunction fn) inline private
Definition at line 333 of file runtime-profile.h.
impala::RuntimeProfile::TimeSeriesCounter::TimeSeriesCounter (const std::string & name, TUnit::type unit, int period, const std::vector< int64_t > & values) inline private
Construct a time series object from existing sample data. This counter is then read-only (i.e. there is no sample function).
Definition at line 340 of file runtime-profile.h.
Member Function Documentation
void impala::RuntimeProfile::TimeSeriesCounter::AddSample (int ms_elapsed) inline
Definition at line 325 of file runtime-profile.h.
References impala::StreamingSampler< T, MAX_SAMPLES >::AddSample(), sample_fn_, and samples_.
string impala::RuntimeProfile::TimeSeriesCounter::DebugString () const
Definition at line 881 of file runtime-profile.cc.
References impala::RuntimeProfile::name_.
void impala::RuntimeProfile::TimeSeriesCounter::ToThrift (TTimeSeriesCounter * counter) private
Definition at line 868 of file runtime-profile.cc.
References impala::StreamingSampler< T, MAX_SAMPLES >::GetSamples(), name_, samples_, unit_, and impala::SpinLock::unlock().
Friends And Related Function Documentation
friend class RuntimeProfile friend
Definition at line 331 of file runtime-profile.h.
Member Data Documentation
std::string impala::RuntimeProfile::TimeSeriesCounter::name_ private
Definition at line 347 of file runtime-profile.h.
Referenced by ToThrift().
DerivedCounterFunction impala::RuntimeProfile::TimeSeriesCounter::sample_fn_ private
Definition at line 349 of file runtime-profile.h.
Referenced by AddSample().
StreamingCounterSampler impala::RuntimeProfile::TimeSeriesCounter::samples_ private
Definition at line 350 of file runtime-profile.h.
Referenced by AddSample(), and ToThrift().
TUnit::type impala::RuntimeProfile::TimeSeriesCounter::unit_ private
Definition at line 348 of file runtime-profile.h.
Referenced by ToThrift().
The documentation for this class was generated from the following files:
be/src/util/runtime-profile.h
be/src/util/runtime-profile.cc