Impala: impala::DecompressorTest Class Reference
impala::DecompressorTest Class Reference
Protected Member Functions
DecompressorTest ()
~DecompressorTest ()
void RunTest (THdfsCompression::type format)
void RunTestStreaming (THdfsCompression::type format)
void CompressAndDecompress (Codec *compressor, Codec *decompressor, int64_t input_len, uint8_t *input)
void CompressAndStreamingDecompress (Codec *compressor, Codec *decompressor, int64_t input_len, uint8_t *input)
void CompressAndDecompressNoOutputAllocated (Codec *compressor, Codec *decompressor, int64_t input_len, uint8_t *input)
Protected Attributes
uint8_t input_ [2 *26 *1024]
uint8_t input_streaming_ [32 *1024 *1024+1]
MemTracker mem_tracker_
MemPool mem_pool_
Detailed Description
Definition at line 30 of file decompress-test.cc.
Constructor & Destructor Documentation
impala::DecompressorTest::DecompressorTest () inline protected
Definition at line 32 of file decompress-test.cc.
References input_, and input_streaming_.
impala::DecompressorTest::~DecompressorTest () inline protected
Definition at line 51 of file decompress-test.cc.
References impala::MemPool::FreeAll(), and mem_pool_.
Member Function Documentation
void impala::DecompressorTest::CompressAndDecompress (Codec * compressor, Codec * decompressor, int64_t input_len, uint8_t * input) inline protected
Definition at line 102 of file decompress-test.cc.
References impala::MemPool::Allocate(), impala::Codec::MaxOutputLen(), mem_pool_, impala::Status::ok(), and impala::Codec::ProcessBlock().
Referenced by RunTest().
void impala::DecompressorTest::CompressAndDecompressNoOutputAllocated (Codec * compressor, Codec * decompressor, int64_t input_len, uint8_t * input) inline protected
Definition at line 170 of file decompress-test.cc.
References impala::MemPool::Allocate(), impala::Codec::MaxOutputLen(), mem_pool_, impala::Status::ok(), and impala::Codec::ProcessBlock().
Referenced by RunTest().
void impala::DecompressorTest::CompressAndStreamingDecompress (Codec * compressor, Codec * decompressor, int64_t input_len, uint8_t * input) inline protected
Definition at line 142 of file decompress-test.cc.
References impala::Status::ok(), impala::Codec::ProcessBlock(), and impala::Codec::ProcessBlockStreaming().
Referenced by RunTestStreaming().
void impala::DecompressorTest::RunTest (THdfsCompression::type format) inline protected
Definition at line 55 of file decompress-test.cc.
References CompressAndDecompress(), CompressAndDecompressNoOutputAllocated(), impala::Codec::CreateCompressor(), impala::Codec::CreateDecompressor(), input_, and mem_pool_.
void impala::DecompressorTest::RunTestStreaming (THdfsCompression::type format) inline protected
Definition at line 85 of file decompress-test.cc.
References CompressAndStreamingDecompress(), impala::Codec::CreateCompressor(), impala::Codec::CreateDecompressor(), input_streaming_, and mem_pool_.
Member Data Documentation
uint8_t impala::DecompressorTest::input_[2 *26 *1024] protected
Definition at line 192 of file decompress-test.cc.
Referenced by DecompressorTest(), and RunTest().
uint8_t impala::DecompressorTest::input_streaming_[32 *1024 *1024+1] protected
Definition at line 198 of file decompress-test.cc.
Referenced by DecompressorTest(), and RunTestStreaming().
MemPool impala::DecompressorTest::mem_pool_ protected
Definition at line 201 of file decompress-test.cc.
Referenced by CompressAndDecompress(), CompressAndDecompressNoOutputAllocated(), RunTest(), RunTestStreaming(), and ~DecompressorTest().
MemTracker impala::DecompressorTest::mem_tracker_ protected
Definition at line 200 of file decompress-test.cc.
The documentation for this class was generated from the following file:
be/src/util/decompress-test.cc