Impala: impala::Status Class Reference
impala::Status Class Reference
#include <status.h>
Public Types
typedef
strings::internal::SubstituteArg ArgType
Public Member Functions
Status ()
Status (const Status &status)
copy c'tor makes copy of error detail so Status can be returned by value
Status (TErrorCode::type code)
Status (TErrorCode::type error, const ArgType &arg0)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2, const ArgType &arg3)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2, const ArgType &arg3, const ArgType &arg4)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2, const ArgType &arg3, const ArgType &arg4, const ArgType &arg5)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2, const ArgType &arg3, const ArgType &arg4, const ArgType &arg5, const ArgType &arg6)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2, const ArgType &arg3, const ArgType &arg4, const ArgType &arg5, const ArgType &arg6, const ArgType &arg7)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2, const ArgType &arg3, const ArgType &arg4, const ArgType &arg5, const ArgType &arg6, const ArgType &arg7, const ArgType &arg8)
Status (TErrorCode::type error, const ArgType &arg0, const ArgType &arg1, const ArgType &arg2, const ArgType &arg3, const ArgType &arg4, const ArgType &arg5, const ArgType &arg6, const ArgType &arg7, const ArgType &arg8, const ArgType &arg9)
Status (const ErrorMsg &e)
Status (const std::string &error_msg)
~Status ()
Status & operator= (const Status &status)
same as copy c'tor
Status (const TStatus &status)
Status & operator= (const TStatus &status)
Status (const apache::hive::service::cli::thrift::TStatus &hs2_status)
Status & operator= (const apache::hive::service::cli::thrift::TStatus &hs2_status)
bool ok () const
bool IsCancelled () const
bool IsMemLimitExceeded () const
bool IsRecoverableError () const
const ErrorMsg & msg () const
Returns the error message associated with a non-successful status.
void SetErrorMsg (const ErrorMsg &m)
void AddDetail (const std::string &msg)
Add a detail string. Calling this method is only defined on a non-OK message.
void MergeStatus (const Status &status)
template<typename T >
void SetTStatus (T *status_container) const
void ToThrift (TStatus *status) const
Convert into TStatus.
const std::string GetDetail () const
TErrorCode::type code () const
Static Public Member Functions
static Status Expected (const std::string &error_msg)
Create a status instance that represents an expected error and will not be logged.
Static Public Attributes
static const Status OK
static const Status CANCELLED
static const Status MEM_LIMIT_EXCEEDED
static const Status DEPRECATED_RPC
Private Member Functions
Status (const std::string &error_msg, bool silent)
Private Attributes
ErrorMsg * msg_
Detailed Description
Status is used as a function return type to indicate success, failure or cancellation of the function. In case of successful completion, it only occupies sizeof(void*) statically allocated memory and therefore no more members should be added to this class. A Status may either be OK (represented by the singleton Status::OK), or it may represent an error condition. In the latter case, a Status has both an error code, which belongs to the TErrorCode enum, and an error string, which may be presented to clients or logged to disk. An error Status may also have one or more optional 'detail' strings which provide further context. These strings are intended for internal consumption only - and therefore will not be sent to clients. The state associated with an error Status is encapsulated in an ErrorMsg instance to ensure that the size of Status is kept very small, as it is passed around on the stack as a return value. See ErrorMsg for more details on how error strings are constructed. Example Usage: Status fnB(int x) { // Status as return value Status status = fnA(x); if (!status.ok()) { status.AddDetail("fnA(x) went wrong"); return status; } int r = Read(fid); // Attaches an ErrorMsg with type GENERAL to the status if (r == -1) return Status("String Constructor"); int x = MoreRead(x); if (x == 4711) { // Specific error messages with one param Status s = Status(ERROR_4711_HAS_NO_BLOCKS, x); // Optional detail s.AddDetail("rotation-disk-broken due to weather"); } return Status::OK; } TODO: macros: RETURN_IF_ERROR(status) << "msg" MAKE_ERROR() << "msg"
Definition at line 81 of file status.h.
Member Typedef Documentation
typedef strings::internal::SubstituteArg impala::Status::ArgType
Definition at line 83 of file status.h.
Constructor & Destructor Documentation
impala::Status::Status () inline
Definition at line 85 of file status.h.
Referenced by Expected().
impala::Status::Status (const Status & status) inline
copy c'tor makes copy of error detail so Status can be returned by value
Definition at line 93 of file status.h.
impala::Status::Status (TErrorCode::type code)
Status using only the error code as a parameter. This can be used for error messages that don't take format parameters.
Definition at line 39 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0)
These constructors are used if the caller wants to indicate a non-successful execution and supply a client-facing error message. This is the preferred way of instantiating a non-successful Status.
Definition at line 44 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1)
Definition at line 49 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2)
Definition at line 54 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2, const ArgType & arg3)
Definition at line 59 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2, const ArgType & arg3, const ArgType & arg4)
Definition at line 65 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2, const ArgType & arg3, const ArgType & arg4, const ArgType & arg5)
Definition at line 71 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2, const ArgType & arg3, const ArgType & arg4, const ArgType & arg5, const ArgType & arg6)
Definition at line 78 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2, const ArgType & arg3, const ArgType & arg4, const ArgType & arg5, const ArgType & arg6, const ArgType & arg7)
Definition at line 85 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2, const ArgType & arg3, const ArgType & arg4, const ArgType & arg5, const ArgType & arg6, const ArgType & arg7, const ArgType & arg8)
Definition at line 93 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (TErrorCode::type error, const ArgType & arg0, const ArgType & arg1, const ArgType & arg2, const ArgType & arg3, const ArgType & arg4, const ArgType & arg5, const ArgType & arg6, const ArgType & arg7, const ArgType & arg8, const ArgType & arg9)
Definition at line 102 of file status.cc.
References impala::GetStackTrace(), impala::ErrorMsg::msg(), and msg_.
impala::Status::Status (const ErrorMsg & e)
Used when the ErrorMsg is created as an intermediate value that is either passed to the Status or to the RuntimeState.
Definition at line 123 of file status.cc.
impala::Status::Status (const std::string & error_msg)
This constructor creates a Status with a default error code of GENERAL and is not intended for statuses that might be client-visible. TODO: deprecate
impala::Status::~Status () inline
Definition at line 141 of file status.h.
References msg_.
impala::Status::Status (const TStatus & status)
"Copy" c'tor from TStatus. Retains the TErrorCode value and the message
Definition at line 126 of file status.cc.
impala::Status::Status (const apache::hive::service::cli::thrift::TStatus & hs2_status)
"Copy c'tor from HS2 TStatus. Retains the TErrorCode value and the message
Definition at line 140 of file status.cc.
impala::Status::Status (const std::string & error_msg, bool silent) private
Silent general error, this cannot be used with typed error messages as it would defy the cause of a useful error message.
Member Function Documentation
void impala::Status::AddDetail (const std::string & msg)
Add a detail string. Calling this method is only defined on a non-OK message.
Definition at line 166 of file status.cc.
References impala::ErrorMsg::AddDetail(), msg(), and msg_.
Referenced by impala::BufferedBlockMgr::FindBufferForBlock(), impala::ScalarFnCall::GetUdf(), impala::SimpleScheduler::Init(), impala::AdmissionController::Init(), impala::HdfsLzoTextScanner::IssueInitialRanges(), impala::BufferedBlockMgr::MemLimitTooLowError(), impala::PartitionedAggregationNode::NextPartition(), impala::PartitionedHashJoinNode::PrepareNextPartition(), impala::Sorter::Run::PrepareRead(), impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage(), impala::PartitionedHashJoinNode::ReserveTupleStreamBlocks(), impala::SimpleScheduler::Schedule(), impala::PartitionedAggregationNode::SpillPartition(), and impala::ExecEnv::StartServices().
TErrorCode::type impala::Status::code () const inline
Definition at line 226 of file status.h.
References impala::ErrorMsg::error(), msg_, and impala::OK.
Referenced by impala::Statestore::DoSubscriberUpdate(), impala::DiskIoMgrTest::ScanRangeThread(), impala::TEST_F(), impala::DiskIoMgrTest::ValidateScanRange(), and impala::DiskIoMgrTest::WriteValidateCallback().
Status impala::Status::Expected (const std::string & error_msg) static
Create a status instance that represents an expected error and will not be logged.
Definition at line 162 of file status.cc.
References Status().
Referenced by impala::AdmissionController::CanAdmitRequest(), and impala::DynamicLookup().
const string impala::Status::GetDetail () const
Returns the formatted message of the error message and the individual details of the additional messages as a single string. This should only be called internally and not to report an error back to the client.
Definition at line 184 of file status.cc.
References impala::ErrorMsg::GetFullMessageDetails(), and msg_.
Referenced by impala::QueryResourceMgr::AcquireVcoreResources(), impala::AdmissionController::AddPoolUpdates(), impala::AdmissionController::AdmitQuery(), impala::ImpalaServer::ArchiveQuery(), impala::HdfsParquetScanner::AssembleRows(), impala::ImpalaServer::AuditEventLoggerFlushThread(), impala::CatalogServer::BuildTopicUpdates(), impala::ImpalaServer::CancelFromThreadPool(), impala::ImpalaServer::CancelQueryUrlCallback(), impala::CatalogServer::CatalogObjectsUrlCallback(), impala::ImpalaServer::CatalogObjectsUrlCallback(), impala::ImpalaServer::CatalogUpdateCallback(), impala::CatalogServer::CatalogUrlCallback(), impala::ImpalaServer::CatalogUrlCallback(), impala::HBaseTableWriter::Close(), impala::HiveUdfCall::Close(), impala::ImpalaServer::CloseInsert(), impala::HashTableCtx::CodegenEquals(), impala::OldHashTable::CodegenEquals(), impala::ExecNode::CodegenEvalConjuncts(), impala::HashTableCtx::CodegenEvalRow(), impala::OldHashTable::CodegenEvalTupleRow(), impala::AggregationNode::CodegenUpdateSlot(), impala::PartitionedAggregationNode::CodegenUpdateSlot(), impala::HdfsScanner::CodegenWriteCompleteTuple(), impala::ImpalaServer::ConnectionEnd(), impala::Expr::CreateExprTree(), impala::AdmissionController::DequeueLoop(), impala::ImpalaServer::QueryExecState::Done(), impala::Statestore::DoSubscriberUpdate(), impala::HiveUdfCall::Evaluate(), CatalogServiceThriftIf::ExecDdl(), impala::ImpalaServer::executeAndWait(), impala::ImpalaServer::ExecuteInternal(), impala::ImpalaServer::ExecuteMetadataOp(), impala::ImpalaServer::ExecuteStatement(), impala::MemTracker::ExpandRmReservation(), impala::ImpalaServer::fetch(), impala::ImpalaServer::FetchResults(), impala::HdfsTextScanner::FinishScanRange(), impala::CatalogServer::GatherCatalogUpdatesThread(), CatalogServiceThriftIf::GetCatalogObject(), impala::ImpalaServer::GetExecSummary(), CatalogServiceThriftIf::GetFunctions(), impala::ExprTest::GetValue(), impala::StatestoreSubscriber::Heartbeat(), impala::ImpalaServer::ImpalaServer(), impala::SimpleScheduler::Init(), impala::ImpalaServer::InitializeConfigVariables(), impala::Frontend::IsAuthorizationError(), Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad(), impala::ImpalaServer::LineageLoggerFlushThread(), impala::ImpalaServer::LogAuditRecord(), main(), impala::PlanFragmentExecutor::OptimizeLlvmModule(), impala::ScalarFnCall::Prepare(), CatalogServiceThriftIf::PrioritizeLoad(), impala::ImpalaServer::ProcessCatalogUpdateResult(), impala::HdfsParquetScanner::ProcessFooter(), impala::ImpalaServer::query(), impala::ImpalaServer::QueryProfileEncodedUrlCallback(), impala::ImpalaServer::QueryProfileUrlCallback(), impala::ImpalaServer::QuerySummaryCallback(), impala::StatestoreSubscriber::RecoveryModeChecker(), impala::ResourceBroker::RegisterWithLlama(), CatalogServiceThriftIf::ResetMetadata(), ResolveSymbolLookup(), impala::RowBatch::RowBatch(), CatalogServiceThriftIf::SentryAdminCheck(), impala::RowBatch::Serialize(), impala::StatestoreSubscriber::Start(), impala::SimpleTupleStreamTest::TestValues(), impala::ThreadMgr::ThreadGroupUrlCallback(), CatalogServiceThriftIf::UpdateCatalog(), impala::SimpleScheduler::UpdateMembership(), and impala::ImpalaServer::QueryExecState::UpdateQueryStatus().
bool impala::Status::IsCancelled () const inline
Definition at line 174 of file status.h.
References impala::ErrorMsg::error(), and msg_.
Referenced by impala::DiskIoMgrStress::ClientThread(), impala::ExchangeNode::FillInputRowBatch(), impala::HdfsTextScanner::FinishScanRange(), impala::PlanFragmentExecutor::Open(), impala::BaseSequenceScanner::ProcessSplit(), impala::DataStreamTest::ReadStream(), impala::DataStreamTest::ReadStreamMerging(), impala::HdfsScanNode::ScannerThread(), impala::TEST_F(), impala::BufferedBlockMgrTest::TestRandomInternalImpl(), and impala::DiskIoMgrTest::WriteValidateCallback().
bool impala::Status::IsMemLimitExceeded () const inline
Definition at line 178 of file status.h.
References impala::ErrorMsg::error(), and msg_.
Referenced by impala::HdfsScanNode::GetNext(), impala::PlanFragmentExecutor::Open(), impala::BaseSequenceScanner::ProcessSplit(), impala::HdfsScanNode::ScannerThread(), impala::RuntimeState::SetMemLimitExceeded(), impala::TEST_F(), and impala::PlanFragmentExecutor::UpdateStatus().
bool impala::Status::IsRecoverableError () const inline
Definition at line 183 of file status.h.
References impala::ErrorMsg::error(), and msg_.
Referenced by impala::ImpalaServer::FetchResults().
void impala::Status::MergeStatus (const Status & status)
Does nothing if status.ok(). Otherwise: if 'this' is an error status, adds the error msg from 'status'; otherwise assigns 'status'.
Definition at line 172 of file status.cc.
References impala::ErrorMsg::AddDetail(), impala::ErrorMsg::details(), impala::ErrorMsg::msg(), msg(), msg_, and ok().
Referenced by impala::ExternalDataSourceExecutor::Close(), and Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad().
const ErrorMsg& impala::Status::msg () const inline
Returns the error message associated with a non-successful status.
Definition at line 189 of file status.h.
References msg_.
Referenced by AddDetail(), impala::HBaseTable::Close(), impala::DataSourceScanNode::Close(), impala::DataStreamSender::Channel::Close(), impala::DataStreamSender::Channel::CloseInternal(), impala::BufferedBlockMgr::ConsumeMemory(), MergeStatus(), impala::BlockingJoinNode::Open(), impala::PlanFragmentExecutor::Open(), impala::BaseSequenceScanner::ProcessSplit(), and impala::BufferedBlockMgr::WriteComplete().
bool impala::Status::ok () const inline
Definition at line 172 of file status.h.
References msg_.
Referenced by impala::QueryResourceMgr::AcquireVcoreResources(), impala::AdmissionController::AddPoolUpdates(), impala::BufferedTupleStream::AddRow(), impala::DiskIoMgr::AddScanRanges(), impala::DiskIoMgr::AddWriteRange(), impala::AdmissionController::AdmitQuery(), impala::BufferedBlockMgrTest::AllocateBlocks(), impala::BufferedTupleStream::AllocateRow(), impala::PartitionedHashJoinNode::AppendRowStreamFull(), impala::ImpalaServer::ArchiveQuery(), impala::HdfsParquetScanner::AssembleRows(), impala::ImpalaServer::AuditEventLoggerFlushThread(), impala::DescriptorTblBuilder::Build(), impala::BlockingJoinNode::BuildSideThread(), impala::CatalogServer::BuildTopicUpdates(), impala::DiskIoMgr::RequestContext::Cancel(), impala::DiskIoMgr::ScanRange::Cancel(), impala::ImpalaServer::CancelFromThreadPool(), impala::ImpalaServer::CancelQueryUrlCallback(), impala::CatalogServer::CatalogObjectsUrlCallback(), impala::ImpalaServer::CatalogObjectsUrlCallback(), impala::ImpalaServer::CatalogUpdateCallback(), impala::CatalogServer::CatalogUrlCallback(), impala::ImpalaServer::CatalogUrlCallback(), impala::DataStreamTest::CheckReceivers(), impala::ClientConnection< T >::ClientConnection(), impala::DiskIoMgrStress::ClientThread(), impala::HBaseTable::Close(), impala::HBaseTableWriter::Close(), impala::DataSourceScanNode::Close(), impala::HiveUdfCall::Close(), impala::DataStreamSender::Channel::Close(), impala::ImpalaServer::CloseInsert(), impala::DataStreamSender::Channel::CloseInternal(), impala::HdfsTextScanner::Codegen(), impala::HdfsAvroScanner::Codegen(), impala::HdfsSequenceScanner::Codegen(), impala::HdfsAvroScanner::CodegenDecodeAvroData(), impala::HashTableCtx::CodegenEquals(), impala::OldHashTable::CodegenEquals(), impala::ExecNode::CodegenEvalConjuncts(), impala::HashTableCtx::CodegenEvalRow(), impala::OldHashTable::CodegenEvalTupleRow(), impala::HashTableCtx::CodegenHashCurrentRow(), impala::OldHashTable::CodegenHashCurrentRow(), impala::PartitionedAggregationNode::CodegenProcessBatch(), impala::HashJoinNode::CodegenProcessBuildBatch(), impala::PartitionedHashJoinNode::CodegenProcessBuildBatch(), impala::HashJoinNode::CodegenProcessProbeBatch(), impala::PartitionedHashJoinNode::CodegenProcessProbeBatch(), impala::AggregationNode::CodegenProcessRowBatch(), impala::AggregationNode::CodegenUpdateSlot(), impala::PartitionedAggregationNode::CodegenUpdateSlot(), impala::AggregationNode::CodegenUpdateTuple(), impala::PartitionedAggregationNode::CodegenUpdateTuple(), impala::HdfsScanner::CodegenWriteCompleteTuple(), impala::DecompressorTest::CompressAndDecompress(), impala::DecompressorTest::CompressAndDecompressNoOutputAllocated(), impala::DecompressorTest::CompressAndStreamingDecompress(), impala::ImpalaServer::ConnectionEnd(), impala::BufferedBlockMgr::ConsumeMemory(), impala::ClientCacheHelper::CreateClient(), impala::LlvmCodeGenTest::CreateCodegen(), impala::Expr::CreateExprTree(), impala::SimpleTupleStreamTest::CreateMgr(), impala::HdfsTableSink::CreateNewTmpFile(), impala::ExecNode::CreateTree(), impala::DataStreamSender::DataStreamSender(), impala::AdmissionController::DequeueLoop(), impala::DiskIoMgrStress::DiskIoMgrStress(), impala::Statestore::DoSubscriberUpdate(), impala::HiveUdfCall::Evaluate(), impala::CatalogOpExecutor::Exec(), impala::ChildQuery::ExecAndFetch(), CatalogServiceThriftIf::ExecDdl(), impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest(), impala::ImpalaServer::Execute(), impala::ImpalaServer::executeAndWait(), impala::ImpalaServer::ExecuteInternal(), impala::ImpalaServer::ExecuteMetadataOp(), impala::ImpalaServer::ExecuteStatement(), impala::ResourceBroker::Expand(), impala::MemTracker::ExpandRmReservation(), impala::ImpalaServer::fetch(), impala::ImpalaServer::QueryExecState::FetchNextBatch(), impala::ImpalaServer::FetchResults(), impala::HdfsTextScanner::FinishScanRange(), impala::CatalogServer::GatherCatalogUpdatesThread(), impala::ScannerContext::Stream::GetBytes(), impala::LibCache::GetCacheEntry(), impala::LibCache::GetCacheEntryInternal(), CatalogServiceThriftIf::GetCatalogObject(), impala::ImpalaServer::GetExecSummary(), CatalogServiceThriftIf::GetFunctions(), impala::PartitionedHashJoinNode::GetNext(), impala::HdfsScanNode::GetNext(), impala::DiskIoMgr::ScanRange::GetNext(), impala::DiskIoMgr::GetNextRange(), impala::HdfsTableSink::GetOutputPartition(), impala::ScalarFnCall::GetUdf(), impala::ExprTest::GetValue(), impala::HashTable::GrowNodeArray(), impala::ImpalaServer::HadoopVarzUrlCallback(), impala::CatalogOpExecutor::HandleDropDataSource(), impala::CatalogOpExecutor::HandleDropFunction(), impala::DiskIoMgr::HandleReadFinished(), HandleSend(), impala::AdmissionController::HandleTopicUpdates(), impala::HdfsPartitionDescriptor::HdfsPartitionDescriptor(), impala::StatestoreSubscriber::Heartbeat(), impala::ImpalaServer::ImpalaServer(), impala::TmpFileMgr::Init(), impala::SimpleScheduler::Init(), impala::ImpalaServer::InitializeConfigVariables(), impala::Frontend::IsAuthorizationError(), impala::HdfsLzoTextScanner::IssueInitialRanges(), Java_com_cloudera_impala_service_FeSupport_NativeCacheJar(), Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad(), impala::LlvmCodeGenTest::LifetimeTest(), impala::ImpalaServer::LineageLoggerFlushThread(), impala::ResourceBroker::LlamaRpc(), impala::ImpalaServer::LogAuditRecord(), impala::ImpalaServer::LogQueryEvents(), main(), impala::ImpalaServer::MembershipCallback(), MergeStatus(), impala::DiskIoMgrStress::NewClient(), impala::BlockingJoinNode::Open(), impala::PlanFragmentExecutor::Open(), impala::ThriftClientImpl::OpenWithRetry(), impala::PlanFragmentExecutor::OptimizeLlvmModule(), impala::ScalarFnCall::Prepare(), CatalogServiceThriftIf::PrioritizeLoad(), impala::PartitionedAggregationNode::ProcessBatch(), impala::ImpalaServer::ProcessCatalogUpdateResult(), impala::HdfsParquetScanner::ProcessFooter(), impala::BaseSequenceScanner::ProcessSplit(), impala::ImpalaServer::query(), impala::ImpalaServer::QueryProfileEncodedUrlCallback(), impala::ImpalaServer::QueryProfileUrlCallback(), impala::ImpalaServer::QuerySummaryCallback(), impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage(), impala::DiskIoMgr::ScanRange::ReadFromCache(), impala::DiskIoMgr::ReadRange(), impala::SimpleTupleStreamTest::ReadValues(), impala::StatestoreSubscriber::RecoveryModeChecker(), impala::ResourceBroker::RegisterWithLlama(), impala::ClientCacheHelper::ReopenClient(), impala::HdfsScanner::ReportColumnParseError(), impala::FragmentMgr::FragmentExecState::ReportStatusCb(), impala::HdfsScanner::ReportTupleParseError(), impala::ResourceBroker::Reserve(), CatalogServiceThriftIf::ResetMetadata(), ResolveSymbolLookup(), impala::DiskIoMgr::ReturnBuffer(), impala::RowBatch::RowBatch(), impala::HdfsScanNode::ScannerThread(), impala::DiskIoMgrTest::ScanRangeThread(), impala::SimpleScheduler::Schedule(), impala::DataStreamTest::Sender(), impala::PlanFragmentExecutor::SendReport(), CatalogServiceThriftIf::SentryAdminCheck(), impala::RowBatch::Serialize(), impala::RuntimeState::set_query_status(), impala::RuntimeState::SetMemLimitExceeded(), impala::OldHashTableTest::SetUp(), impala::HashTableTest::SetUp(), impala::StateStore2Test::SetUp(), impala::PartitionedAggregationNode::Partition::Spill(), impala::StatestoreSubscriber::Start(), impala::ExecEnv::StartServices(), impala::StateStore2Test::StartStateStoreSubscriber(), impala::TEST(), TEST(), impala::TEST_F(), TestDeserialize(), impala::ExprTest::TestNonOkStatus(), impala::BufferedBlockMgrTest::TestRandomInternalImpl(), impala::TestSingleLiteralConstruction(), impala::ThreadMgr::ThreadGroupUrlCallback(), impala::BufferedBlockMgr::TransferBuffer(), impala::ImpalaServer::TransmitData(), CatalogServiceThriftIf::UpdateCatalog(), impala::SimpleScheduler::UpdateMembership(), impala::ImpalaServer::QueryExecState::UpdateQueryStatus(), impala::FragmentMgr::FragmentExecState::UpdateStatus(), impala::PlanFragmentExecutor::UpdateStatus(), impala::DiskIoMgrTest::ValidateScanRange(), impala::DiskIoMgrTest::ValidateSyncRead(), impala::ImpalaServer::QueryExecState::Wait(), impala::ParallelExecutor::Worker(), impala::BufferedBlockMgr::WriteComplete(), impala::DiskIoMgrTest::WriteCompleteCallback(), impala::HdfsTextScanner::WriteFields(), and impala::DiskIoMgrTest::WriteValidateCallback().
Status& impala::Status::operator= (const Status & status) inline
same as copy c'tor
Definition at line 146 of file status.h.
References LIKELY, and msg_.
Status & impala::Status::operator= (const TStatus & status)
same as previous c'tor Retains the TErrorCode value and the message
Definition at line 130 of file status.cc.
References msg_, and impala::OK.
Status & impala::Status::operator= (const apache::hive::service::cli::thrift::TStatus & hs2_status)
same as previous c'tor Retains the TErrorCode value and the message
Definition at line 149 of file status.cc.
References msg_.
void impala::Status::SetErrorMsg (const ErrorMsg & m) inline
Sets the ErrorMessage on the detail of the status. Calling this method is only valid if an error was reported. TODO: deprecate, error should be immutable
Definition at line 197 of file status.h.
References msg_.
Referenced by impala::PartitionedAggregationNode::CreateHashPartitions(), impala::Statestore::DoSubscriberUpdate(), impala::ScalarFnCall::Prepare(), and impala::PartitionedHashJoinNode::ProcessBuildInput().
template<typename T > void impala::Status::SetTStatus (T * status_container) const inline
Convert into TStatus. Call this if 'status_container' contains an optional TStatus field named 'status'. This also sets status_container->__isset.status.
Definition at line 213 of file status.h.
References ToThrift().
Referenced by impala::FragmentMgr::CancelPlanFragment(), impala::FragmentMgr::FragmentExecState::ReportStatusCb(), and impala::ImpalaServer::TransmitData().
void impala::Status::ToThrift (TStatus * status) const
Convert into TStatus.
Definition at line 188 of file status.cc.
References impala::ErrorMsg::details(), impala::ErrorMsg::error(), impala::ErrorMsg::msg(), msg_, and impala::OK.
Referenced by CatalogServiceThriftIf::ExecDdl(), CatalogServiceThriftIf::GetFunctions(), Java_com_cloudera_impala_service_FeSupport_NativeCacheJar(), Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad(), CatalogServiceThriftIf::PrioritizeLoad(), StatestoreThriftIf::RegisterSubscriber(), CatalogServiceThriftIf::ResetMetadata(), CatalogServiceThriftIf::SentryAdminCheck(), SetTStatus(), and CatalogServiceThriftIf::UpdateCatalog().
Member Data Documentation
const Status impala::Status::CANCELLED static
Definition at line 88 of file status.h.
Referenced by impala::DiskIoMgr::CancelContext(), impala::HdfsScanner::CommitRows(), impala::BufferedBlockMgr::DeleteBlock(), impala::BufferedBlockMgr::DeleteOrUnpinBlock(), impala::ExecNode::ExecDebugAction(), impala::BufferedBlockMgr::FindBuffer(), impala::BufferedBlockMgr::FindBufferForBlock(), impala::DataStreamRecvr::SenderQueue::GetBatch(), impala::ScannerContext::Stream::GetBuffer(), impala::ScannerContext::Stream::GetBytesInternal(), impala::BufferedBlockMgr::GetNewBlock(), impala::ScannerContext::Stream::GetNextBuffer(), impala::ChildQuery::IsCancelled(), impala::DiskIoMgr::ScanRange::Open(), impala::DiskIoMgr::ScanRange::Read(), impala::DiskIoMgr::ScanRange::ReadFromCache(), impala::ScannerContext::Stream::ReleaseCompletedResources(), impala::TEST_F(), impala::BufferedBlockMgr::TransferBuffer(), and impala::BufferedBlockMgr::UnpinBlock().
const Status impala::Status::DEPRECATED_RPC static
Definition at line 90 of file status.h.
const Status impala::Status::MEM_LIMIT_EXCEEDED static
Definition at line 89 of file status.h.
Referenced by impala::PartitionedAggregationNode::CreateHashPartitions(), impala::BufferedBlockMgr::FindBufferForBlock(), impala::DiskIoMgr::GetNextRequestRange(), impala::BufferedBlockMgr::MemLimitTooLowError(), impala::PartitionedAggregationNode::NextPartition(), impala::PartitionedHashJoinNode::PrepareNextPartition(), impala::Sorter::Run::PrepareRead(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::PartitionedHashJoinNode::ReserveTupleStreamBlocks(), impala::RuntimeState::SetMemLimitExceeded(), impala::PartitionedAggregationNode::SpillPartition(), and impala::TEST_F().
ErrorMsg* impala::Status::msg_ private
Status uses a naked pointer to ensure the size of an instance on the stack is only the sizeof(ErrorMsg*). Every Status owns its ErrorMsg instance.
Definition at line 238 of file status.h.
Referenced by AddDetail(), code(), GetDetail(), IsCancelled(), IsMemLimitExceeded(), IsRecoverableError(), MergeStatus(), msg(), ok(), operator=(), SetErrorMsg(), Status(), ToThrift(), and ~Status().
const Status impala::Status::OK static
Definition at line 87 of file status.h.
Referenced by impala::Sorter::Run::AddBatch(), impala::Sorter::AddBatch(), impala::HdfsScanNode::AddDiskIoRanges(), impala::AnalyticEvalNode::AddRow(), impala::HdfsParquetTableWriter::AddRowGroup(), impala::DiskIoMgr::AddScanRanges(), impala::StatestoreSubscriber::AddTopic(), impala::DiskIoMgr::AddWriteRange(), impala::AdmissionController::AdmitQuery(), impala::TmpFileMgr::File::AllocateSpace(), impala::SimpleLogger::AppendEntry(), impala::HdfsParquetTableWriter::BaseColumnWriter::AppendRow(), impala::HBaseTableWriter::AppendRowBatch(), impala::HdfsSequenceTableWriter::AppendRowBatch(), impala::HdfsTextTableWriter::AppendRowBatch(), impala::HdfsParquetTableWriter::AppendRowBatch(), impala::HdfsAvroTableWriter::AppendRowBatch(), impala::CgroupsMgr::AssignThreadToCgroup(), impala::ImpalaServer::AuthorizeProxyUser(), impala::PartitionedHashJoinNode::Partition::BuildHashTableInternal(), impala::PartitionedHashJoinNode::BuildHashTables(), CallJniMethod(), impala::JniUtil::CallJniMethod(), impala::AdmissionController::CanAdmitRequest(), impala::ImpalaServer::CancelInternal(), impala::StatestoreSubscriber::CheckRegistrationId(), impala::JniUtil::Cleanup(), impala::PartitionedHashJoinNode::CleanUpHashPartitions(), impala::HBaseTableWriter::CleanUpJni(), impala::Expr::Clone(), impala::ImpaladQueryExecutor::Close(), impala::ImpalaServer::CloseSessionInternal(), impala::CompoundPredicate::CodegenComputeFn(), impala::HdfsScanner::CommitRows(), impala::GzipCompressor::Compress(), impala::CrossJoinNode::ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::PartitionedHashJoinNode::ConstructBuildSide(), impala::BufferedBlockMgr::ConsumeMemory(), impala::HdfsSequenceTableWriter::ConsumeRow(), impala::CopyHdfsFile(), impala::AggFnEvaluator::Create(), impala::BufferedBlockMgr::Create(), impala::DescriptorTbl::Create(), impala::RuntimeState::CreateBlockMgr(), impala::HBaseTableWriter::CreateByteArray(), impala::HBaseTableScanner::CreateByteArray(), impala::CgroupsMgr::CreateCgroup(), impala::RuntimeState::CreateCodegen(), impala::HdfsParquetScanner::CreateColumnReaders(), impala::DataSink::CreateDataSink(), impala::QueryResourceMgr::CreateExpansionRequest(), impala::Expr::CreateExpr(), impala::Expr::CreateExprTree(), impala::Expr::CreateExprTrees(), impala::PartitionedAggregationNode::CreateHashPartitions(), impala::CreateImpalaServer(), impala::DataStreamRecvr::CreateMerger(), impala::Sorter::CreateMerger(), impala::ExecNode::CreateNode(), impala::HBaseTableWriter::CreatePut(), impala::HBaseTableWriter::CreatePutList(), impala::HdfsParquetTableWriter::CreateSchema(), impala::ThriftServer::CreateSocket(), impala::ExecNode::CreateTree(), impala::Expr::CreateTreeFromThrift(), impala::ExecNode::CreateTreeHelper(), impala::BufferedBlockMgr::Decrypt(), impala::BufferedBlockMgr::DeleteBlock(), impala::BufferedBlockMgr::DeleteOrUnpinBlock(), impala::DeserializeThriftMsg(), impala::ClientConnection< T >::DoRpc(), impala::CgroupsMgr::DropCgroup(), impala::DynamicLookup(), impala::DynamicOpen(), impala::ThriftServer::EnableSsl(), impala::BufferedBlockMgr::Encrypt(), impala::PartitionedHashJoinNode::EvaluateNullProbe(), impala::ImpaladQueryExecutor::Exec(), impala::ImpalaServer::QueryExecState::Exec(), impala::CatalogOpExecutor::ExecComputeStats(), impala::ImpalaServer::QueryExecState::ExecDdlRequest(), impala::ExecNode::ExecDebugAction(), impala::ImpalaServer::QueryExecState::ExecLocalCatalogOp(), impala::FragmentMgr::ExecPlanFragment(), impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest(), impala::ImpalaServer::ExecuteInternal(), impala::ResourceBroker::Expand(), impala::ImpaladQueryExecutor::Explain(), impala::ImpalaServer::QueryExecState::FetchNextBatch(), impala::ImpaladQueryExecutor::FetchResult(), impala::ImpalaServer::QueryExecState::FetchRowsInternal(), impala::HdfsTextScanner::FillByteBufferCompressedFile(), impala::HdfsTextScanner::FillByteBufferGzip(), impala::HdfsParquetTableWriter::Finalize(), impala::LlvmCodeGen::FinalizeModule(), impala::HdfsTableSink::FinalizePartitionFile(), impala::BufferedBlockMgr::FindBuffer(), impala::BufferedBlockMgr::FindBufferForBlock(), impala::HdfsTextScanner::FindFirstTuple(), impala::HdfsTextScanner::FinishScanRange(), impala::HdfsTextTableWriter::Flush(), impala::HdfsSequenceTableWriter::Flush(), impala::HdfsAvroTableWriter::Flush(), impala::HdfsParquetTableWriter::BaseColumnWriter::Flush(), impala::HdfsParquetTableWriter::FlushCurrentRowGroup(), impala::SimpleLogger::FlushInternal(), impala::Catalog::GetAllCatalogObjects(), impala::DataStreamRecvr::SenderQueue::GetBatch(), impala::ScannerContext::Stream::GetBuffer(), impala::ScannerContext::Stream::GetBytesInternal(), impala::CatalogOpExecutor::GetCatalogObject(), impala::Catalog::GetCatalogVersion(), impala::CgroupsMgr::GetCgroupPaths(), impala::RuntimeState::GetCodegen(), impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::Expr::GetCodegendComputeFnWrapper(), impala::HBaseTableScanner::GetCurrentValue(), impala::ImpalaServer::GetExecSummary(), impala::HdfsTableSink::GetFileBlockSize(), impala::GetFileSize(), impala::ScalarFnCall::GetFunction(), impala::JniUtil::GetGlobalClassRef(), impala::Codec::GetHadoopCodecClassName(), impala::GetHostname(), impala::JniUtil::GetJniExceptionMsg(), impala::GetLastModificationTime(), impala::BufferedBlockMgr::GetNewBlock(), impala::EmptySetNode::GetNext(), impala::SelectNode::GetNext(), impala::UnionNode::GetNext(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), impala::CrossJoinNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::SortedRunMerger::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::Sorter::Run::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::Sorter::GetNext(), impala::DiskIoMgr::ScanRange::GetNext(), impala::Sorter::Run::GetNextBatch(), impala::ScannerContext::Stream::GetNextBuffer(), impala::DataSourceScanNode::GetNextInputBatch(), impala::PlanFragmentExecutor::GetNextInternal(), impala::BufferedTupleStream::GetNextInternal(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::DiskIoMgr::GetNextRange(), impala::HdfsTableSink::GetOutputPartition(), impala::RequestPoolService::GetPoolConfig(), impala::HdfsSequenceScanner::GetRecord(), impala::HBaseTable::GetResultScanner(), impala::HBaseTableScanner::GetRowKey(), impala::BufferedTupleStream::GetRows(), impala::ImpalaServer::QueryExecState::GetRowValue(), impala::ImpalaServer::GetRuntimeProfileStr(), impala::ImpalaServer::GetSessionState(), impala::HBaseTableFactory::GetTable(), impala::GetThreadStats(), impala::ScalarFnCall::GetUdf(), impala::HBaseTableScanner::HandleResultScannerTimeout(), impala::HostnameToIpAddrs(), HttpGet(), impala::SimpleLogger::Init(), impala::HBaseTable::Init(), impala::SortNode::Init(), impala::UnionNode::Init(), impala::HBaseTableFactory::Init(), impala::ExternalDataSourceExecutor::Init(), impala::GzipDecompressor::Init(), impala::TopNNode::Init(), impala::ExchangeNode::Init(), impala::SortedRunMerger::BatchedRowSupplier::Init(), impala::BlockingJoinNode::Init(), impala::HdfsSequenceTableWriter::Init(), impala::HdfsTextTableWriter::Init(), impala::GzipCompressor::Init(), impala::ResourceBroker::Init(), impala::HashJoinNode::Init(), impala::HBaseTableWriter::Init(), impala::AggregationNode::Init(), impala::ExecNode::Init(), impala::Sorter::Run::Init(), impala::HdfsParquetTableWriter::Init(), impala::AnalyticEvalNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::HdfsAvroTableWriter::Init(), impala::BzipDecompressor::Init(), impala::HBaseTableScanner::Init(), impala::BzipCompressor::Init(), impala::SnappyDecompressor::Init(), impala::CgroupsMgr::Init(), impala::SnappyBlockCompressor::Init(), impala::PartitionedAggregationNode::Init(), impala::Sorter::Init(), impala::Lz4Decompressor::Init(), impala::SnappyCompressor::Init(), impala::SnappyBlockDecompressor::Init(), impala::Lz4Compressor::Init(), impala::BufferedTupleStream::Init(), impala::JniUtil::Init(), impala::MetricGroup::Init(), impala::RuntimeState::Init(), impala::LlvmCodeGen::Init(), impala::DiskIoMgr::Init(), impala::ImpalaServer::InitAuditEventLogging(), impala::HdfsParquetScanner::InitColumns(), impala::HdfsParquetScanner::ColumnReader< T >::InitDataPage(), impala::HdfsParquetScanner::BoolColumnReader::InitDataPage(), impala::ExecEnv::InitForFeTests(), impala::CrossJoinNode::InitGetNext(), impala::HashJoinNode::InitGetNext(), impala::PartitionedHashJoinNode::InitGetNext(), impala::HdfsScanner::InitializeWriteTuplesFn(), impala::LibCache::InitInternal(), impala::HBaseTable::InitJNI(), impala::HBaseTableWriter::InitJNI(), impala::ImpalaServer::InitLineageLogging(), InitLoggingDir(), impala::JvmMetric::InitMetrics(), impala::HdfsTextTableWriter::InitNewFile(), impala::HdfsParquetTableWriter::InitNewFile(), impala::HdfsTextScanner::InitNewRange(), impala::HdfsAvroScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsParquetScanner::InitNewRange(), impala::HdfsRCFileScanner::InitNewRange(), impala::HdfsTableSink::InitOutputPartition(), impala::ImpalaServer::InitProfileLogging(), impala::HBaseTableScanner::InitScanRange(), impala::PartitionedAggregationNode::Partition::InitStreams(), impala::BufferedBlockMgr::InitTmpFiles(), impala::Sorter::InputDone(), impala::ChildQuery::IsCancelled(), impala::BaseSequenceScanner::IssueInitialRanges(), impala::HdfsTextScanner::IssueInitialRanges(), impala::HdfsParquetScanner::IssueInitialRanges(), impala::InProcessImpalaServer::Join(), impala::HashJoinNode::LeftJoinGetNext(), impala::LlvmCodeGen::LinkModule(), impala::ResourceBroker::LlamaRpc(), llama::LlamaStatusToImpalaStatus(), impala::LlvmCodeGen::LoadImpalaIR(), impala::LlvmCodeGen::LoadIntrinsics(), impala::JniUtil::LoadJniMethod(), impala::HdfsLzoTextScanner::LoadLzoLibrary(), impala::LlvmCodeGen::LoadModule(), impala::JniUtil::LocalToGlobalRef(), impala::ImpalaServer::LogLineageRecord(), impala::Statestore::MainLoop(), impala::Sorter::MergeIntermediateRuns(), impala::PartitionedAggregationNode::MoveHashPartitions(), impala::BufferedTupleStream::NewBlockForWrite(), impala::SortedRunMerger::BatchedRowSupplier::Next(), impala::HBaseTableScanner::Next(), impala::BufferedTupleStream::NextBlockForRead(), impala::HdfsRCFileScanner::NextField(), impala::PartitionedAggregationNode::NextPartition(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::HdfsRCFileScanner::NextRow(), impala::PartitionedHashJoinNode::NextSpilledProbeRowBatch(), impala::Statestore::OfferUpdate(), impala::SelectNode::Open(), impala::HBaseScanNode::Open(), impala::UnionNode::Open(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::SortExecExprs::Open(), impala::ExchangeNode::Open(), impala::CaseExpr::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::AggFnEvaluator::Open(), impala::HdfsScanNode::Open(), impala::HdfsTableSink::Open(), impala::Expr::Open(), impala::DiskIoMgr::ScanRange::Open(), impala::UnionNode::OpenCurrentChild(), impala::HdfsPartitionDescriptor::OpenExprs(), impala::PlanFragmentExecutor::OpenInternal(), impala::PartitionedHashJoinNode::OutputNullAwareNullProbe(), impala::PartitionedHashJoinNode::OutputNullAwareProbeRows(), impala::DelimitedTextParser::ParseFieldLocations(), ParseMemValue(), impala::HdfsAvroScanner::ParseMetadata(), impala::BufferedBlockMgr::PinBlock(), impala::BufferedTupleStream::PinStream(), impala::SlotRef::Prepare(), impala::TupleIsNullPredicate::Prepare(), impala::HdfsTextScanner::Prepare(), impala::SelectNode::Prepare(), impala::HBaseScanNode::Prepare(), impala::SortNode::Prepare(), impala::UnionNode::Prepare(), impala::BaseSequenceScanner::Prepare(), impala::SortExecExprs::Prepare(), impala::TopNNode::Prepare(), impala::ExchangeNode::Prepare(), impala::DataSourceScanNode::Prepare(), impala::DataSink::Prepare(), impala::CrossJoinNode::Prepare(), impala::HdfsParquetScanner::Prepare(), impala::BlockingJoinNode::Prepare(), impala::CaseExpr::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::SortedRunMerger::Prepare(), impala::ScalarFnCall::Prepare(), impala::HiveUdfCall::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::DataStreamSender::Prepare(), impala::ExecNode::Prepare(), impala::ScanNode::Prepare(), impala::PlanFragmentExecutor::Prepare(), impala::AggFnEvaluator::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanner::Prepare(), impala::HdfsScanNode::Prepare(), impala::HdfsTableSink::Prepare(), impala::HdfsSequenceScanner::Prepare(), impala::HdfsRCFileScanner::Prepare(), impala::Expr::Prepare(), impala::HdfsTableSink::PrepareExprs(), impala::HdfsPartitionDescriptor::PrepareExprs(), impala::BufferedTupleStream::PrepareForRead(), impala::PartitionedHashJoinNode::PrepareNextPartition(), impala::PartitionedHashJoinNode::PrepareNullAwareNullProbe(), impala::PartitionedHashJoinNode::PrepareNullAwarePartition(), impala::Sorter::Run::PrepareRead(), impala::CatalogOpExecutor::PrioritizeLoad(), impala::PartitionedAggregationNode::ProcessBatch(), impala::PartitionedAggregationNode::ProcessBatchNoGrouping(), impala::GzipDecompressor::ProcessBlock(), impala::GzipCompressor::ProcessBlock(), impala::BzipDecompressor::ProcessBlock(), impala::BzipCompressor::ProcessBlock(), impala::SnappyDecompressor::ProcessBlock(), impala::SnappyBlockCompressor::ProcessBlock(), impala::Lz4Decompressor::ProcessBlock(), impala::SnappyCompressor::ProcessBlock(), impala::SnappyBlockDecompressor::ProcessBlock(), impala::Lz4Compressor::ProcessBlock(), impala::Codec::ProcessBlock32(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::GzipDecompressor::ProcessBlockStreaming(), impala::PartitionedHashJoinNode::ProcessBuildBatch(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::ImpalaServer::ProcessCatalogUpdateResult(), impala::AnalyticEvalNode::ProcessChildBatch(), impala::AnalyticEvalNode::ProcessChildBatches(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), impala::HdfsTextScanner::ProcessSplit(), impala::BaseSequenceScanner::ProcessSplit(), impala::HdfsParquetScanner::ProcessSplit(), impala::PartitionedAggregationNode::ProcessStream(), impala::JniLocalFrame::push(), impala::HBaseTable::Put(), impala::DiskIoMgr::ScanRange::Read(), impala::DiskIoMgr::Read(), impala::HdfsSequenceScanner::ReadBlockHeader(), impala::HdfsRCFileScanner::ReadColumnBuffers(), impala::HdfsSequenceScanner::ReadCompressedBlock(), impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage(), impala::HdfsAvroScanner::ReadFileHeader(), impala::HdfsSequenceScanner::ReadFileHeader(), impala::HdfsRCFileScanner::ReadFileHeader(), impala::DiskIoMgr::ScanRange::ReadFromCache(), impala::HdfsRCFileScanner::ReadKeyBuffers(), impala::HdfsRCFileScanner::ReadNumColumnsMetadata(), impala::HdfsRCFileScanner::ReadRowGroup(), impala::HdfsRCFileScanner::ReadRowGroupHeader(), impala::BaseSequenceScanner::ReadSync(), impala::ResourceBroker::RefreshLlamaNodes(), impala::BufferedBlockMgr::RegisterClient(), impala::DiskIoMgr::RegisterContext(), impala::CgroupsMgr::RegisterFragment(), impala::RegisterMemoryMetrics(), impala::ImpalaServer::RegisterQuery(), impala::Statestore::RegisterSubscriber(), impala::ResourceBroker::RegisterWithLlama(), impala::AdmissionController::RejectRequest(), impala::ResourceBroker::Release(), impala::AdmissionController::ReleaseQuery(), impala::CgroupsMgr::RelocateThreads(), impala::TmpFileMgr::File::Remove(), impala::ResourceBroker::Reserve(), impala::PartitionedHashJoinNode::ReserveTupleStreamBlocks(), impala::ExecNode::Reset(), impala::DiskIoMgr::RequestContext::Reset(), impala::HdfsParquetScanner::BaseColumnReader::Reset(), impala::DiskIoMgr::BufferDescriptor::Reset(), impala::HdfsTextScanner::ResetScanner(), impala::RequestPoolService::ResolveRequestPool(), impala::HdfsAvroScanner::ResolveSchemas(), impala::ImpalaServer::QueryExecState::RestartFetch(), impala::HBaseTableScanner::ScanSetup(), impala::DataStreamSender::Send(), impala::HdfsTableSink::Send(), impala::Statestore::SendHeartbeat(), impala::Statestore::SendTopicUpdate(), impala::ThriftSerializer::Serialize(), impala::SerializeThriftMsg(), impala::Frontend::SetCatalogInitialized(), impala::CgroupsMgr::SetCpuShares(), impala::SetDecimalVal(), impala::ImpalaServer::SetQueryInflight(), impala::ImpalaServer::QueryExecState::SetResultCache(), impala::ImpaladQueryExecutor::Setup(), impala::BaseSequenceScanner::SkipToSync(), SnappyBlockDecompress(), impala::SortNode::SortInput(), impala::Sorter::SortRun(), impala::PartitionedAggregationNode::Partition::Spill(), impala::PartitionedHashJoinNode::Partition::Spill(), impala::PartitionedHashJoinNode::SpillPartition(), impala::PartitionedAggregationNode::SpillPartition(), impala::Webserver::Start(), impala::CatalogServer::Start(), impala::ThriftServer::Start(), impala::NoAuthProvider::Start(), impala::InProcessImpalaServer::StartAsBackendOnly(), impala::ExecEnv::StartServices(), impala::InProcessImpalaServer::StartWithClientServers(), impala::BufferedTupleStream::SwitchToIoBuffers(), impala::TCatalogObjectFromObjectName(), impala::TEST_F(), impala::ImpalaServer::THandleIdentifierToTUniqueId(), impala::BufferedBlockMgr::TransferBuffer(), impala::Sorter::Run::TryAddBlock(), impala::Sorter::Run::UnpinAllBlocks(), impala::BufferedTupleStream::UnpinBlock(), impala::BufferedBlockMgr::UnpinBlock(), impala::BufferedTupleStream::UnpinStream(), impala::CgroupsMgr::UnregisterFragment(), impala::ImpalaServer::UnregisterQuery(), impala::ImpalaServer::QueryExecState::UpdateCatalog(), impala::ImpalaServer::UpdateCatalogMetrics(), impala::HdfsScanner::UpdateDecompressor(), impala::ParallelExecutorTest::UpdateFunction(), impala::StatestoreSubscriber::UpdateState(), impala::ImpalaServer::QueryExecState::UpdateTableAndColumnStats(), impala::HdfsParquetScanner::ValidateColumn(), impala::HdfsParquetScanner::ValidateFileMetadata(), impala::QuerySchedule::ValidateReservation(), impala::DataSourceScanNode::ValidateRowBatchSize(), impala::DiskIoMgr::ValidateScanRange(), impala::Frontend::ValidateSettings(), impala::BufferedBlockMgr::VerifyHash(), impala::HdfsAvroScanner::VerifyTypesMatch(), impala::ImpalaServer::QueryExecState::WaitForChildQueries(), impala::WaitForServer(), impala::ImpalaServer::QueryExecState::WaitInternal(), impala::ImpalaServer::ScopedSessionState::WithSession(), impala::HdfsTableWriter::Write(), impala::BufferedBlockMgr::WriteComplete(), impala::HdfsSequenceTableWriter::WriteCompressedBlock(), impala::HdfsParquetTableWriter::WriteFileFooter(), impala::HdfsSequenceTableWriter::WriteFileHeader(), impala::HdfsAvroTableWriter::WriteFileHeader(), impala::HdfsParquetTableWriter::WriteFileHeader(), impala::DiskIoMgr::WriteRangeHelper(), impala::BufferedBlockMgr::WriteUnpinnedBlock(), and impala::BufferedBlockMgr::WriteUnpinnedBlocks().
The documentation for this class was generated from the following files:
be/src/common/status.h
be/src/common/status.cc