Impala: com.cloudera.impala.analysis.ColumnDef Class Reference
com.cloudera.impala.analysis.ColumnDef Class Reference
Public Member Functions
ColumnDef (String colName, TypeDef typeDef, String comment)
void setType (Type type)
Type getType ()
TypeDef getTypeDef ()
String getColName ()
String getComment ()
void analyze () throws AnalysisException
String toString ()
TColumn toThrift ()
Private Attributes
final String colName_
final String comment_
final TypeDef typeDef_
Type type_
Detailed Description
Represents a column definition in a CREATE/ALTER TABLE/VIEW statement. Column definitions in CREATE/ALTER TABLE statements require a column type, whereas column definitions in CREATE/ALTER VIEW statements infer the column type from the corresponding view definition. All column definitions have an optional comment. Since a column definition refers a column stored in the Metastore, the column name must be valid according to the Metastore's rules (see).
Definition at line 32 of file ColumnDef.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.ColumnDef.ColumnDef (String colName, TypeDef typeDef, String comment) inline
Definition at line 41 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.colName_, com.cloudera.impala.analysis.ColumnDef.comment_, and com.cloudera.impala.analysis.ColumnDef.typeDef_.
Member Function Documentation
void com.cloudera.impala.analysis.ColumnDef.analyze () throws AnalysisException inline
Definition at line 53 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.colName_, com.cloudera.impala.analysis.ColumnDef.type_, and com.cloudera.impala.analysis.ColumnDef.typeDef_.
String com.cloudera.impala.analysis.ColumnDef.getColName () inline
Definition at line 50 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.colName_.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.addTestTable(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.CreateTableStmt.analyzeAvroSchema(), and com.cloudera.impala.analysis.ColumnDef.toThrift().
String com.cloudera.impala.analysis.ColumnDef.getComment () inline
Definition at line 51 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.comment_.
Referenced by com.cloudera.impala.analysis.ColumnDef.toThrift().
Type com.cloudera.impala.analysis.ColumnDef.getType () inline
Definition at line 48 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.type_.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.analyzeAvroSchema().
TypeDef com.cloudera.impala.analysis.ColumnDef.getTypeDef () inline
Definition at line 49 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.typeDef_.
void com.cloudera.impala.analysis.ColumnDef.setType (Type type) inline
Definition at line 47 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.type_.
String com.cloudera.impala.analysis.ColumnDef.toString () inline
Definition at line 67 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.colName_, com.cloudera.impala.analysis.ColumnDef.comment_, and com.cloudera.impala.analysis.ColumnDef.type_.
TColumn com.cloudera.impala.analysis.ColumnDef.toThrift () inline
Definition at line 78 of file ColumnDef.java.
References com.cloudera.impala.analysis.ColumnDef.getColName(), com.cloudera.impala.analysis.ColumnDef.getComment(), com.cloudera.impala.catalog.Type.toThrift(), and com.cloudera.impala.analysis.ColumnDef.type_.
Member Data Documentation
final String com.cloudera.impala.analysis.ColumnDef.colName_ private
Definition at line 33 of file ColumnDef.java.
Referenced by com.cloudera.impala.analysis.ColumnDef.analyze(), com.cloudera.impala.analysis.ColumnDef.ColumnDef(), com.cloudera.impala.analysis.ColumnDef.getColName(), and com.cloudera.impala.analysis.ColumnDef.toString().
final String com.cloudera.impala.analysis.ColumnDef.comment_ private
Definition at line 34 of file ColumnDef.java.
Referenced by com.cloudera.impala.analysis.ColumnDef.ColumnDef(), com.cloudera.impala.analysis.ColumnDef.getComment(), and com.cloudera.impala.analysis.ColumnDef.toString().
Type com.cloudera.impala.analysis.ColumnDef.type_ private
Definition at line 39 of file ColumnDef.java.
Referenced by com.cloudera.impala.analysis.ColumnDef.analyze(), com.cloudera.impala.analysis.ColumnDef.getType(), com.cloudera.impala.analysis.ColumnDef.setType(), com.cloudera.impala.analysis.ColumnDef.toString(), and com.cloudera.impala.analysis.ColumnDef.toThrift().
final TypeDef com.cloudera.impala.analysis.ColumnDef.typeDef_ private
Definition at line 38 of file ColumnDef.java.
Referenced by com.cloudera.impala.analysis.ColumnDef.analyze(), com.cloudera.impala.analysis.ColumnDef.ColumnDef(), and com.cloudera.impala.analysis.ColumnDef.getTypeDef().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/ColumnDef.java