Impala: impala::AtomicInt< T > Class Template Reference
impala::AtomicInt< T > Class Template Reference
#include <atomic.h>
Public Member Functions
AtomicInt (T initial=0)
operator T () const
AtomicInt & operator= (T val)
AtomicInt & operator= (const AtomicInt< T > &val)
AtomicInt & operator+= (T delta)
AtomicInt & operator-= (T delta)
AtomicInt & operator|= (T v)
AtomicInt & operator&= (T v)
AtomicInt & operator++ ()
These define the preincrement (i.e. –value) operators.
AtomicInt & operator-- ()
AtomicInt< T > operator++ (int)
This is post increment, which needs to return a new object.
AtomicInt< T > operator-- (int)
T Read ()
Safe read of the value.
T UpdateAndFetch (T delta)
Increments by delta (i.e. += delta) and returns the new val.
T FetchAndUpdate (T delta)
Increment by delta and returns the old val.
void UpdateMax (T value)
Updates the int to 'value' if value is larger.
void UpdateMin (T value)
bool CompareAndSwap (T old_val, T new_val)
Returns true if the atomic compare-and-swap was successful.
T CompareAndSwapVal (T old_val, T new_val)
T Swap (const T &new_val)
Atomically updates value_ with new_val. Returns the old value_.
Private Attributes
T value_
Detailed Description
template<typename T>
class impala::AtomicInt< T >
Wrapper for atomic integers. This should be switched to c++ 11 when we can switch. This class overloads operators to behave like a regular integer type but all operators and functions are thread safe.
Definition at line 46 of file atomic.h.
Constructor & Destructor Documentation
template<typename T> impala::AtomicInt< T >::AtomicInt (T initial = 0) inline
Definition at line 48 of file atomic.h.
Member Function Documentation
template<typename T> bool impala::AtomicInt< T >::CompareAndSwap (T old_val, T new_val) inline
Returns true if the atomic compare-and-swap was successful.
Definition at line 131 of file atomic.h.
Referenced by impala::CASDecrementThread(), impala::CASIncrementThread(), impala::PlanFragmentExecutor::FragmentComplete(), impala::TEST(), impala::RuntimeProfile::HighWaterMarkCounter::TryAdd(), impala::AtomicInt< int >::UpdateMax(), impala::AtomicInt< int >::UpdateMin(), and impala::PlanFragmentExecutor::UpdateStatus().
template<typename T> T impala::AtomicInt< T >::CompareAndSwapVal (T old_val, T new_val) inline
Returns the content of value_ before the operation. If returnValue == old_val, then the atomic compare-and-swap was successful.
Definition at line 137 of file atomic.h.
Referenced by impala::TEST().
template<typename T> T impala::AtomicInt< T >::FetchAndUpdate (T delta) inline
Increment by delta and returns the old val.
Definition at line 110 of file atomic.h.
Referenced by impala::TEST().
template<typename T> impala::AtomicInt< T >::operator T () const inline
Definition at line 50 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator&= (T v) inline
Definition at line 74 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator++ () inline
These define the preincrement (i.e. –value) operators.
Definition at line 80 of file atomic.h.
template<typename T> AtomicInt<T> impala::AtomicInt< T >::operator++ (int) inline
This is post increment, which needs to return a new object.
Definition at line 90 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator+= (T delta) inline
Definition at line 61 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator-- () inline
Definition at line 84 of file atomic.h.
template<typename T> AtomicInt<T> impala::AtomicInt< T >::operator-- (int) inline
Definition at line 94 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator-= (T delta) inline
Definition at line 65 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator= (T val) inline
Definition at line 52 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator= (const AtomicInt< T > & val) inline
Definition at line 56 of file atomic.h.
template<typename T> AtomicInt& impala::AtomicInt< T >::operator|= (T v) inline
Definition at line 70 of file atomic.h.
template<typename T> T impala::AtomicInt< T >::Read () inline
Safe read of the value.
Definition at line 100 of file atomic.h.
Referenced by impala::CASDecrementThread(), impala::CASIncrementThread(), impala::PlanFragmentExecutor::ReportProfile(), and impala::PeriodicCounterUpdater::UpdateLoop().
template<typename T> T impala::AtomicInt< T >::Swap (const T & new_val) inline
Atomically updates value_ with new_val. Returns the old value_.
Definition at line 142 of file atomic.h.
Referenced by impala::TEST(), and impala::PeriodicCounterUpdater::~PeriodicCounterUpdater().
template<typename T> T impala::AtomicInt< T >::UpdateAndFetch (T delta) inline
Increments by delta (i.e. += delta) and returns the new val.
Definition at line 105 of file atomic.h.
Referenced by impala::RuntimeProfile::HighWaterMarkCounter::Add(), impala::HdfsOperationSet::MarkOneOpDone(), impala::MemTracker::Release(), and impala::TEST().
template<typename T> void impala::AtomicInt< T >::UpdateMax (T value) inline
Updates the int to 'value' if value is larger.
Definition at line 115 of file atomic.h.
Referenced by impala::RuntimeProfile::HighWaterMarkCounter::Add(), impala::RuntimeProfile::HighWaterMarkCounter::Set(), impala::TEST(), and impala::RuntimeProfile::HighWaterMarkCounter::TryAdd().
template<typename T> void impala::AtomicInt< T >::UpdateMin (T value) inline
Definition at line 122 of file atomic.h.
Referenced by impala::TEST().
Member Data Documentation
template<typename T> T impala::AtomicInt< T >::value_ private
Definition at line 147 of file atomic.h.
Referenced by impala::AtomicInt< int >::CompareAndSwap(), impala::AtomicInt< int >::CompareAndSwapVal(), impala::AtomicInt< int >::FetchAndUpdate(), impala::AtomicInt< uint32_t >::operator uint32_t(), impala::AtomicInt< int >::operator&=(), impala::AtomicInt< int >::operator++(), impala::AtomicInt< int >::operator+=(), impala::AtomicInt< int >::operator--(), impala::AtomicInt< int >::operator-=(), impala::AtomicInt< int >::operator=(), impala::AtomicInt< int >::operator|=(), impala::AtomicInt< int >::Read(), impala::AtomicInt< int >::Swap(), impala::AtomicInt< int >::UpdateAndFetch(), impala::AtomicInt< int >::UpdateMax(), and impala::AtomicInt< int >::UpdateMin().
The documentation for this class was generated from the following file:
be/src/common/atomic.h