Impala: impala::InPredicateBenchmark Class Reference
impala::InPredicateBenchmark Class Reference
Classes
struct TestData
Static Public Member Functions
template<typename T , typename SetType >
static TestData< T, SetType > CreateTestData (int num_values, const FunctionContext::TypeDesc &type, int num_search_vals=100)
template<typename T , typename SetType >
static void TestSetLookup (int batch_size, void *d)
template<typename T , typename SetType >
static void TestIterate (int batch_size, void *d)
static void RunIntBenchmark (int n)
static void RunStringBenchmark (int n)
static void RunDecimalBenchmark (int n)
Static Private Member Functions
static FunctionContext * CreateContext (int num_args, const FunctionContext::TypeDesc &type)
Detailed Description
Definition at line 186 of file in-predicate-benchmark.cc.
Member Function Documentation
static FunctionContext* impala::InPredicateBenchmark::CreateContext (int num_args, const FunctionContext::TypeDesc & type) inline static private
Definition at line 304 of file in-predicate-benchmark.cc.
template<typename T , typename SetType > static TestData<T, SetType> impala::InPredicateBenchmark::CreateTestData (int num_values, const FunctionContext::TypeDesc & type, int num_search_vals = 100) inline static
Definition at line 203 of file in-predicate-benchmark.cc.
References impala::InPredicateBenchmark::TestData< T, SetType >::anyval_ptrs, impala::InPredicateBenchmark::TestData< T, SetType >::anyvals, impala::InPredicateBenchmark::TestData< T, SetType >::search_vals, impala::InPredicateBenchmark::TestData< T, SetType >::state, impala::InPredicateBenchmark::TestData< T, SetType >::total_found_iter, impala::InPredicateBenchmark::TestData< T, SetType >::total_found_set, impala::InPredicateBenchmark::TestData< T, SetType >::total_iter, and impala::InPredicateBenchmark::TestData< T, SetType >::total_set.
static void impala::InPredicateBenchmark::RunDecimalBenchmark (int n) inline static
Definition at line 288 of file in-predicate-benchmark.cc.
References impala::Benchmark::AddBenchmark(), impala::Benchmark::Measure(), impala_udf::FunctionContext::TypeDesc::precision, impala_udf::FunctionContext::TypeDesc::scale, impala_udf::FunctionContext::TypeDesc::type, and impala::TYPE_DECIMAL.
Referenced by main().
static void impala::InPredicateBenchmark::RunIntBenchmark (int n) inline static
Definition at line 258 of file in-predicate-benchmark.cc.
References impala::Benchmark::AddBenchmark(), impala::Benchmark::Measure(), impala_udf::FunctionContext::TypeDesc::type, and impala::TYPE_INT.
Referenced by main().
static void impala::InPredicateBenchmark::RunStringBenchmark (int n) inline static
Definition at line 273 of file in-predicate-benchmark.cc.
References impala::Benchmark::AddBenchmark(), impala::Benchmark::Measure(), impala_udf::FunctionContext::TypeDesc::type, and impala::TYPE_STRING.
Referenced by main().
template<typename T , typename SetType > static void impala::InPredicateBenchmark::TestIterate (int batch_size, void * d) inline static
Definition at line 246 of file in-predicate-benchmark.cc.
References impala::InPredicateBenchmark::TestData< T, SetType >::anyvals, impala::InPredicate::Iterate(), impala::InPredicateBenchmark::TestData< T, SetType >::search_vals, impala::InPredicateBenchmark::TestData< T, SetType >::state, impala::InPredicateBenchmark::TestData< T, SetType >::total_found_iter, impala::InPredicateBenchmark::TestData< T, SetType >::total_iter, and impala_udf::BooleanVal::val.
template<typename T , typename SetType > static void impala::InPredicateBenchmark::TestSetLookup (int batch_size, void * d) inline static
Definition at line 234 of file in-predicate-benchmark.cc.
References impala::InPredicateBenchmark::TestData< T, SetType >::search_vals, impala::InPredicate::SetLookup(), impala::InPredicateBenchmark::TestData< T, SetType >::state, impala::InPredicateBenchmark::TestData< T, SetType >::total_found_set, impala::InPredicateBenchmark::TestData< T, SetType >::total_set, and impala_udf::BooleanVal::val.
The documentation for this class was generated from the following file:
be/src/exprs/in-predicate-benchmark.cc