Impala: impala::RuntimeProfile::HighWaterMarkCounter Class Reference
impala::RuntimeProfile::HighWaterMarkCounter Class Reference
#include <runtime-profile.h>
Public Member Functions
HighWaterMarkCounter (TUnit::type unit)
virtual void Add (int64_t delta)
bool TryAdd (int64_t delta, int64_t max)
virtual void Set (int64_t v)
int64_t current_value () const
void BitOr (int64_t delta)
Use this to update if the counter is a bitmap.
virtual void Set (double value)
virtual int64_t value () const
virtual double double_value () const
TUnit::type unit () const
Protected Attributes
AtomicInt< int64_t > value_
TUnit::type unit_
Private Attributes
AtomicInt< int64_t > current_value_
Detailed Description
A counter that keeps track of the highest value seen (reporting that as value()) and the current value.
Definition at line 125 of file runtime-profile.h.
Constructor & Destructor Documentation
impala::RuntimeProfile::HighWaterMarkCounter::HighWaterMarkCounter (TUnit::type unit) inline
Definition at line 127 of file runtime-profile.h.
Member Function Documentation
virtual void impala::RuntimeProfile::HighWaterMarkCounter::Add (int64_t delta) inline virtual
Reimplemented from impala::RuntimeProfile::Counter.
Definition at line 129 of file runtime-profile.h.
References current_value_, impala::AtomicInt< T >::UpdateAndFetch(), impala::AtomicInt< T >::UpdateMax(), and impala::RuntimeProfile::Counter::value_.
Referenced by impala::MemTracker::TryConsume().
void impala::RuntimeProfile::Counter::BitOr (int64_t delta) inline inherited
Use this to update if the counter is a bitmap.
Definition at line 98 of file runtime-profile.h.
References impala::RuntimeProfile::Counter::value_.
Referenced by impala::DiskIoMgr::ReadRange().
int64_t impala::RuntimeProfile::HighWaterMarkCounter::current_value () const inline
Definition at line 153 of file runtime-profile.h.
References current_value_.
Referenced by impala::MemTracker::consumption(), and impala::MemTracker::ExpandRmReservation().
virtual double impala::RuntimeProfile::Counter::double_value () const inline virtual inherited
Definition at line 110 of file runtime-profile.h.
References impala::RuntimeProfile::Counter::value_.
Referenced by impala::TEST(), and impala::RuntimeProfile::AveragedCounter::UpdateCounter().
virtual void impala::RuntimeProfile::Counter::Set (double value) inline virtual inherited
Reimplemented in impala::RuntimeProfile::AveragedCounter.
Definition at line 104 of file runtime-profile.h.
References impala::RuntimeProfile::Counter::value(), and impala::RuntimeProfile::Counter::value_.
virtual void impala::RuntimeProfile::HighWaterMarkCounter::Set (int64_t v) inline virtual
Reimplemented from impala::RuntimeProfile::Counter.
Definition at line 148 of file runtime-profile.h.
References current_value_, impala::AtomicInt< T >::UpdateMax(), and impala::RuntimeProfile::Counter::value_.
Referenced by impala::MemTracker::Consume(), impala::MemTracker::GcMemory(), impala::HdfsTextScanner::IssueInitialRanges(), impala::MemTracker::Release(), and impala::MemTracker::TryConsume().
bool impala::RuntimeProfile::HighWaterMarkCounter::TryAdd (int64_t delta, int64_t max) inline
Tries to increase the current value by delta. If current_value() + delta exceeds max, return false and current_value is not changed.
Definition at line 136 of file runtime-profile.h.
References impala::AtomicInt< T >::CompareAndSwap(), current_value_, LIKELY, impala::AtomicInt< T >::UpdateMax(), and impala::RuntimeProfile::Counter::value_.
Referenced by impala::MemTracker::TryConsume().
TUnit::type impala::RuntimeProfile::Counter::unit () const inline inherited
Definition at line 114 of file runtime-profile.h.
References impala::RuntimeProfile::Counter::unit_.
Referenced by impala::ScopedTimer< impala::MonotonicStopWatch >::ScopedTimer(), impala::TEST(), and impala::RuntimeProfile::UnitsPerSecond().
virtual int64_t impala::RuntimeProfile::Counter::value () const inline virtual inherited
Reimplemented in impala::RuntimeProfile::DerivedCounter.
Definition at line 108 of file runtime-profile.h.
References impala::RuntimeProfile::Counter::value_.
Referenced by impala::HdfsScanNode::Close(), impala::RuntimeProfile::ComputeTimeInProfile(), impala::BufferedBlockMgr::DebugInternal(), impala::HdfsScanNode::EnoughMemoryForScannerThread(), impala::Coordinator::BackendExecState::GetNodeThroughput(), impala::Coordinator::BackendExecState::GetNumScanRangesCompleted(), impala::MemTracker::peak_consumption(), impala::HdfsScanNode::ScannerThread(), impala::RuntimeProfile::Counter::Set(), impala::HdfsScanNode::StopAndFinalizeCounters(), impala::PeriodicCounterUpdater::StopBucketingCounters(), impala::TEST(), impala::TEST_F(), impala::HdfsScanNode::ThreadTokenAvailableCb(), impala::RuntimeProfile::UnitsPerSecond(), impala::RuntimeProfile::AveragedCounter::UpdateCounter(), and impala::ValidateCounter().
Member Data Documentation
AtomicInt<int64_t> impala::RuntimeProfile::HighWaterMarkCounter::current_value_ private
The current value of the counter. value_ in the super class represents the high water mark.
Definition at line 158 of file runtime-profile.h.
Referenced by Add(), current_value(), Set(), and TryAdd().
TUnit::type impala::RuntimeProfile::Counter::unit_ protected inherited
Definition at line 120 of file runtime-profile.h.
Referenced by impala::RuntimeProfile::Counter::unit(), and impala::RuntimeProfile::AveragedCounter::UpdateCounter().
AtomicInt<int64_t> impala::RuntimeProfile::Counter::value_ protected inherited
Definition at line 119 of file runtime-profile.h.
Referenced by impala::RuntimeProfile::Counter::Add(), Add(), impala::RuntimeProfile::Counter::BitOr(), impala::RuntimeProfile::Counter::double_value(), impala::RuntimeProfile::Counter::Set(), Set(), TryAdd(), impala::RuntimeProfile::AveragedCounter::UpdateCounter(), and impala::RuntimeProfile::Counter::value().
The documentation for this class was generated from the following file:
be/src/util/runtime-profile.h