Impala: com.cloudera.impala.analysis.CreateTableLikeStmt Class Reference
com.cloudera.impala.analysis.CreateTableLikeStmt Class Reference
Public Member Functions
CreateTableLikeStmt (TableName tableName, TableName srcTableName, boolean isExternal, String comment, THdfsFileFormat fileFormat, HdfsUri location, boolean ifNotExists)
String getTbl ()
String getSrcTbl ()
boolean isExternal ()
boolean getIfNotExists ()
String getComment ()
THdfsFileFormat getFileFormat ()
HdfsUri getLocation ()
String getDb ()
String getSrcDb ()
String getOwner ()
String toSql ()
TCreateTableLikeParams toThrift ()
void analyze (Analyzer analyzer) throws AnalysisException
void setIsExplain ()
boolean isExplain ()
Protected Attributes
boolean isExplain_ = false
Private Attributes
final TableName tableName_
final TableName srcTableName_
final boolean isExternal_
final String comment_
final THdfsFileFormat fileFormat_
final HdfsUri location_
final boolean ifNotExists_
String dbName_
String srcDbName_
String owner_
Detailed Description
Represents a CREATE TABLE LIKE statement which creates a new table based on a copy of an existing table definition.
Definition at line 32 of file CreateTableLikeStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.CreateTableLikeStmt.CreateTableLikeStmt (TableName tableName, TableName srcTableName, boolean isExternal, String comment, THdfsFileFormat fileFormat, HdfsUri location, boolean ifNotExists) inline
Builds a CREATE TABLE LIKE statement
Parameters
tableName - Name of the new table
srcTableName - Name of the source table (table to copy)
isExternal - If true, the table's data will be preserved if dropped.
comment - Comment to attach to the table
fileFormat - File format of the table
location - The HDFS location of where the table data will stored.
ifNotExists - If true, no errors are thrown if the table already exists
Definition at line 56 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.isExternal().
Member Function Documentation
void com.cloudera.impala.analysis.CreateTableLikeStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 131 of file CreateTableLikeStmt.java.
References com.cloudera.impala.authorization.Privilege.ALL, com.cloudera.impala.authorization.Privilege.CREATE, com.cloudera.impala.analysis.CreateTableLikeStmt.dbName_, com.cloudera.impala.analysis.CreateTableLikeStmt.getDb(), com.cloudera.impala.analysis.TableName.getTbl(), com.cloudera.impala.analysis.CreateTableLikeStmt.getTbl(), com.cloudera.impala.analysis.CreateTableLikeStmt.ifNotExists_, com.cloudera.impala.analysis.CreateTableLikeStmt.location_, com.cloudera.impala.analysis.CreateTableLikeStmt.owner_, com.cloudera.impala.analysis.CreateTableLikeStmt.srcDbName_, com.cloudera.impala.analysis.CreateTableLikeStmt.srcTableName_, com.cloudera.impala.analysis.CreateTableLikeStmt.tableName_, com.cloudera.impala.analysis.Analyzer.TBL_ALREADY_EXISTS_ERROR_MSG, and com.cloudera.impala.authorization.Privilege.VIEW_METADATA.
String com.cloudera.impala.analysis.CreateTableLikeStmt.getComment () inline
Definition at line 74 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.comment_.
String com.cloudera.impala.analysis.CreateTableLikeStmt.getDb () inline
Can only be called after analysis, returns the name of the database the table will be created within.
Definition at line 82 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.dbName_.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
THdfsFileFormat com.cloudera.impala.analysis.CreateTableLikeStmt.getFileFormat () inline
Definition at line 75 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.fileFormat_.
boolean com.cloudera.impala.analysis.CreateTableLikeStmt.getIfNotExists () inline
Definition at line 73 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.ifNotExists_.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
HdfsUri com.cloudera.impala.analysis.CreateTableLikeStmt.getLocation () inline
Definition at line 76 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.location_.
String com.cloudera.impala.analysis.CreateTableLikeStmt.getOwner () inline
Definition at line 96 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.owner_.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
String com.cloudera.impala.analysis.CreateTableLikeStmt.getSrcDb () inline
Can only be called after analysis, returns the name of the database the table will be created within.
Definition at line 91 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.srcDbName_.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
String com.cloudera.impala.analysis.CreateTableLikeStmt.getSrcTbl () inline
Definition at line 71 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
String com.cloudera.impala.analysis.CreateTableLikeStmt.getTbl () inline
Definition at line 70 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
boolean com.cloudera.impala.analysis.CreateTableLikeStmt.isExternal () inline
Definition at line 72 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.isExternal_.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.CreateTableLikeStmt(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.CreateTableLikeStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 102 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.comment_, com.cloudera.impala.analysis.CreateTableLikeStmt.fileFormat_, com.cloudera.impala.analysis.TableName.getDb(), com.cloudera.impala.analysis.CreateTableLikeStmt.ifNotExists_, com.cloudera.impala.analysis.CreateTableLikeStmt.isExternal_, com.cloudera.impala.analysis.CreateTableLikeStmt.location_, com.cloudera.impala.analysis.CreateTableLikeStmt.srcTableName_, and com.cloudera.impala.analysis.CreateTableLikeStmt.tableName_.
TCreateTableLikeParams com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift () inline
Definition at line 117 of file CreateTableLikeStmt.java.
References com.cloudera.impala.analysis.CreateTableLikeStmt.comment_, com.cloudera.impala.analysis.CreateTableLikeStmt.fileFormat_, com.cloudera.impala.analysis.CreateTableLikeStmt.getDb(), com.cloudera.impala.analysis.CreateTableLikeStmt.getIfNotExists(), com.cloudera.impala.analysis.CreateTableLikeStmt.getOwner(), com.cloudera.impala.analysis.CreateTableLikeStmt.getSrcDb(), com.cloudera.impala.analysis.CreateTableLikeStmt.getSrcTbl(), com.cloudera.impala.analysis.CreateTableLikeStmt.getTbl(), com.cloudera.impala.analysis.CreateTableLikeStmt.isExternal(), and com.cloudera.impala.analysis.CreateTableLikeStmt.location_.
Member Data Documentation
final String com.cloudera.impala.analysis.CreateTableLikeStmt.comment_ private
Definition at line 36 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.getComment(), com.cloudera.impala.analysis.CreateTableLikeStmt.toSql(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
String com.cloudera.impala.analysis.CreateTableLikeStmt.dbName_ private
Definition at line 42 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeStmt.getDb().
final THdfsFileFormat com.cloudera.impala.analysis.CreateTableLikeStmt.fileFormat_ private
Definition at line 37 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.getFileFormat(), com.cloudera.impala.analysis.CreateTableLikeStmt.toSql(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
final boolean com.cloudera.impala.analysis.CreateTableLikeStmt.ifNotExists_ private
Definition at line 39 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), com.cloudera.impala.analysis.CreateTableLikeStmt.getIfNotExists(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toSql().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final boolean com.cloudera.impala.analysis.CreateTableLikeStmt.isExternal_ private
Definition at line 35 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.isExternal(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toSql().
final HdfsUri com.cloudera.impala.analysis.CreateTableLikeStmt.location_ private
Definition at line 38 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), com.cloudera.impala.analysis.CreateTableLikeStmt.getLocation(), com.cloudera.impala.analysis.CreateTableLikeStmt.toSql(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toThrift().
String com.cloudera.impala.analysis.CreateTableLikeStmt.owner_ private
Definition at line 44 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeStmt.getOwner().
String com.cloudera.impala.analysis.CreateTableLikeStmt.srcDbName_ private
Definition at line 43 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeStmt.getSrcDb().
final TableName com.cloudera.impala.analysis.CreateTableLikeStmt.srcTableName_ private
Definition at line 34 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toSql().
final TableName com.cloudera.impala.analysis.CreateTableLikeStmt.tableName_ private
Definition at line 33 of file CreateTableLikeStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeStmt.toSql().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/CreateTableLikeStmt.java