Impala: com.cloudera.impala.analysis.Analyzer.GlobalState Class Reference
com.cloudera.impala.analysis.Analyzer.GlobalState Class Reference
Public Member Functions
GlobalState (ImpaladCatalog catalog, TQueryCtx queryCtx, AuthorizationConfig authzConfig)
Public Attributes
final ImpaladCatalog catalog
final TQueryCtx queryCtx
final AuthorizationConfig authzConfig
final DescriptorTable descTbl = new DescriptorTable()
final IdGenerator< ExprId > conjunctIdGenerator = ExprId.createGenerator()
final ColumnLineageGraph lineageGraph
boolean isExplain
boolean hasPlanHints = false
boolean containsSubquery = false
boolean useHiveColLabels = false
final Map< ExprId, Expr > conjuncts = Maps.newHashMap()
final ArrayList< ExprId > singleTidConjuncts = Lists.newArrayList()
final Map< TupleId, List
< ExprId > > eqJoinConjuncts = Maps.newHashMap()
Set< ExprId > assignedConjuncts
final Map< TupleId, TableRef > outerJoinedTupleIds = Maps.newHashMap()
final Map< ExprId, TableRef > fullOuterJoinedConjuncts = Maps.newHashMap()
final Map< TupleId, TableRef > fullOuterJoinedTupleIds = Maps.newHashMap()
final Map< TupleId, TableRef > semiJoinedTupleIds = Maps.newHashMap()
final Map< TableRef, List
< ExprId > > conjunctsByOjClause = Maps.newHashMap()
final Map< ExprId, TableRef > ojClauseByConjunct = Maps.newHashMap()
final Map< ExprId, TableRef > sjClauseByConjunct = Maps.newHashMap()
final Map< SlotId, Analyzer > blockBySlot = Maps.newHashMap()
Set< TAccessEvent > accessEvents = Sets.newHashSet()
final LinkedHashMap< String,
Integer > warnings
final IdGenerator
< EquivalenceClassId > equivClassIdGenerator
Private Attributes
final List< PrivilegeRequest > privilegeReqs = Lists.newArrayList()
final List< Pair
< PrivilegeRequest, String > > maskedPrivilegeReqs
final Map< EquivalenceClassId,
ArrayList< SlotId > > equivClassMembers
final Map< SlotId,
EquivalenceClassId > equivClassBySlotId = Maps.newHashMap()
final ExprSubstitutionMap equivClassSmap = new ExprSubstitutionMap()
ValueTransferGraph valueTransferGraph
final List< Pair< SlotId,
SlotId > > registeredValueTransfers
final ListMap< TNetworkAddress > hostIndex = new ListMap<TNetworkAddress>()
final EventSequence timeline = new EventSequence("Planner Timeline")
Detailed Description
Definition at line 160 of file Analyzer.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.Analyzer.GlobalState.GlobalState (ImpaladCatalog catalog, TQueryCtx queryCtx, AuthorizationConfig authzConfig) inline
Definition at line 281 of file Analyzer.java.
References com.cloudera.impala.analysis.Analyzer.GlobalState.authzConfig, com.cloudera.impala.analysis.Analyzer.GlobalState.catalog, and com.cloudera.impala.analysis.Analyzer.GlobalState.queryCtx.
Member Data Documentation
Set<TAccessEvent> com.cloudera.impala.analysis.Analyzer.GlobalState.accessEvents = Sets.newHashSet()
Definition at line 244 of file Analyzer.java.
Set<ExprId> com.cloudera.impala.analysis.Analyzer.GlobalState.assignedConjuncts
Initial value:
=
        Collections.newSetFromMap(new IdentityHashMap<ExprId, Boolean>())
Definition at line 198 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.getUnassignedConjuncts(), com.cloudera.impala.analysis.Analyzer.getUnassignedOjConjuncts(), and com.cloudera.impala.analysis.Analyzer.hasUnassignedConjuncts().
final AuthorizationConfig com.cloudera.impala.analysis.Analyzer.GlobalState.authzConfig
Definition at line 165 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.GlobalState.GlobalState().
final Map<SlotId, Analyzer> com.cloudera.impala.analysis.Analyzer.GlobalState.blockBySlot = Maps.newHashMap()
Definition at line 231 of file Analyzer.java.
final ImpaladCatalog com.cloudera.impala.analysis.Analyzer.GlobalState.catalog
Definition at line 163 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.createWithNewGlobalState(), com.cloudera.impala.analysis.Analyzer.getCatalog(), and com.cloudera.impala.analysis.Analyzer.GlobalState.GlobalState().
final IdGenerator<ExprId> com.cloudera.impala.analysis.Analyzer.GlobalState.conjunctIdGenerator = ExprId.createGenerator()
Definition at line 167 of file Analyzer.java.
final Map<ExprId, Expr> com.cloudera.impala.analysis.Analyzer.GlobalState.conjuncts = Maps.newHashMap()
Definition at line 184 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.getUnassignedConjuncts(), com.cloudera.impala.analysis.Analyzer.hasUnassignedConjuncts(), and com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.partitionValueTransfers().
final Map<TableRef, List<ExprId> > com.cloudera.impala.analysis.Analyzer.GlobalState.conjunctsByOjClause = Maps.newHashMap()
Definition at line 219 of file Analyzer.java.
boolean com.cloudera.impala.analysis.Analyzer.GlobalState.containsSubquery = false
Definition at line 178 of file Analyzer.java.
final DescriptorTable com.cloudera.impala.analysis.Analyzer.GlobalState.descTbl = new DescriptorTable()
Definition at line 166 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.createEqPredicate(), com.cloudera.impala.analysis.Analyzer.getBoundPredicates(), and com.cloudera.impala.analysis.Analyzer.getEquivSlots().
final Map<TupleId, List<ExprId> > com.cloudera.impala.analysis.Analyzer.GlobalState.eqJoinConjuncts = Maps.newHashMap()
Definition at line 195 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.registerConjunct().
final Map<SlotId, EquivalenceClassId> com.cloudera.impala.analysis.Analyzer.GlobalState.equivClassBySlotId = Maps.newHashMap() private
Definition at line 262 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.createIdentityEquivClasses(), and com.cloudera.impala.analysis.Analyzer.getBoundPredicates().
final IdGenerator<EquivalenceClassId> com.cloudera.impala.analysis.Analyzer.GlobalState.equivClassIdGenerator
Initial value:
=
        EquivalenceClassId.createGenerator()
Definition at line 253 of file Analyzer.java.
final Map<EquivalenceClassId, ArrayList<SlotId> > com.cloudera.impala.analysis.Analyzer.GlobalState.equivClassMembers private
Initial value:
=
        Maps.newHashMap()
Definition at line 257 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.computeEquivClasses(), com.cloudera.impala.analysis.Analyzer.getEquivClasses(), and com.cloudera.impala.analysis.Analyzer.getEquivSlots().
final ExprSubstitutionMap com.cloudera.impala.analysis.Analyzer.GlobalState.equivClassSmap = new ExprSubstitutionMap() private
Definition at line 265 of file Analyzer.java.
final Map<ExprId, TableRef> com.cloudera.impala.analysis.Analyzer.GlobalState.fullOuterJoinedConjuncts = Maps.newHashMap()
Definition at line 207 of file Analyzer.java.
final Map<TupleId, TableRef> com.cloudera.impala.analysis.Analyzer.GlobalState.fullOuterJoinedTupleIds = Maps.newHashMap()
Definition at line 210 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.registerFullOuterJoinedConjunct().
boolean com.cloudera.impala.analysis.Analyzer.GlobalState.hasPlanHints = false
Definition at line 175 of file Analyzer.java.
final ListMap<TNetworkAddress> com.cloudera.impala.analysis.Analyzer.GlobalState.hostIndex = new ListMap<TNetworkAddress>() private
Definition at line 275 of file Analyzer.java.
boolean com.cloudera.impala.analysis.Analyzer.GlobalState.isExplain
Definition at line 172 of file Analyzer.java.
final ColumnLineageGraph com.cloudera.impala.analysis.Analyzer.GlobalState.lineageGraph
Definition at line 168 of file Analyzer.java.
final List<Pair<PrivilegeRequest, String> > com.cloudera.impala.analysis.Analyzer.GlobalState.maskedPrivilegeReqs private
Initial value:
=
        Lists.newArrayList()
Definition at line 239 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.authorize().
final Map<ExprId, TableRef> com.cloudera.impala.analysis.Analyzer.GlobalState.ojClauseByConjunct = Maps.newHashMap()
Definition at line 224 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate(), com.cloudera.impala.analysis.Analyzer.getBoundPredicates(), and com.cloudera.impala.analysis.Analyzer.getUnassignedConjuncts().
final Map<TupleId, TableRef> com.cloudera.impala.analysis.Analyzer.GlobalState.outerJoinedTupleIds = Maps.newHashMap()
Definition at line 203 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate(), com.cloudera.impala.analysis.Analyzer.getBoundPredicates(), and com.cloudera.impala.analysis.Analyzer.invertOuterJoinState().
final List<PrivilegeRequest> com.cloudera.impala.analysis.Analyzer.GlobalState.privilegeReqs = Lists.newArrayList() private
Definition at line 234 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.authorize().
final TQueryCtx com.cloudera.impala.analysis.Analyzer.GlobalState.queryCtx
Definition at line 164 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.GlobalState.GlobalState(), and com.cloudera.impala.analysis.Analyzer.markConstantConjunct().
final List<Pair<SlotId, SlotId> > com.cloudera.impala.analysis.Analyzer.GlobalState.registeredValueTransfers private
Initial value:
=
        Lists.newArrayList()
Definition at line 270 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.computeValueTransfers(), and com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.validate().
final Map<TupleId, TableRef> com.cloudera.impala.analysis.Analyzer.GlobalState.semiJoinedTupleIds = Maps.newHashMap()
Definition at line 215 of file Analyzer.java.
final ArrayList<ExprId> com.cloudera.impala.analysis.Analyzer.GlobalState.singleTidConjuncts = Lists.newArrayList()
Definition at line 187 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.getBoundPredicates(), and com.cloudera.impala.analysis.Analyzer.registerConjunct().
final Map<ExprId, TableRef> com.cloudera.impala.analysis.Analyzer.GlobalState.sjClauseByConjunct = Maps.newHashMap()
Definition at line 228 of file Analyzer.java.
final EventSequence com.cloudera.impala.analysis.Analyzer.GlobalState.timeline = new EventSequence("Planner Timeline") private
Definition at line 279 of file Analyzer.java.
boolean com.cloudera.impala.analysis.Analyzer.GlobalState.useHiveColLabels = false
Definition at line 181 of file Analyzer.java.
ValueTransferGraph com.cloudera.impala.analysis.Analyzer.GlobalState.valueTransferGraph private
Definition at line 268 of file Analyzer.java.
final LinkedHashMap<String, Integer> com.cloudera.impala.analysis.Analyzer.GlobalState.warnings
Initial value:
=
        new LinkedHashMap<String, Integer>()
Definition at line 250 of file Analyzer.java.
Referenced by com.cloudera.impala.analysis.Analyzer.getWarnings().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/Analyzer.java