Impala: com.cloudera.impala.analysis.PartitionKeyValue Class Reference
com.cloudera.impala.analysis.PartitionKeyValue Class Reference
Public Member Functions
PartitionKeyValue (String colName, Expr value)
void analyze (Analyzer analyzer) throws AnalysisException
String getColName ()
Expr getValue ()
LiteralExpr getLiteralValue ()
boolean isDynamic ()
boolean isStatic ()
String toString ()
String toPredicateSql ()
Static Public Member Functions
static String getPartitionKeyValueString (LiteralExpr literalValue, String nullPartitionKeyValue)
Private Attributes
final String colName_
final Expr value_
LiteralExpr literalValue_
Detailed Description
Representation of a single column:value element in the PARTITION (...) clause of an insert or alter table statement.
Definition at line 24 of file PartitionKeyValue.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.PartitionKeyValue.PartitionKeyValue (String colName, Expr value) inline
Definition at line 32 of file PartitionKeyValue.java.
Member Function Documentation
void com.cloudera.impala.analysis.PartitionKeyValue.analyze (Analyzer analyzer) throws AnalysisException inline
Definition at line 37 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.Expr.isConstant(), com.cloudera.impala.analysis.PartitionKeyValue.isStatic(), com.cloudera.impala.analysis.PartitionKeyValue.literalValue_, com.cloudera.impala.analysis.PartitionKeyValue.toString(), and com.cloudera.impala.analysis.PartitionKeyValue.value_.
String com.cloudera.impala.analysis.PartitionKeyValue.getColName () inline
Definition at line 48 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.PartitionKeyValue.colName_.
LiteralExpr com.cloudera.impala.analysis.PartitionKeyValue.getLiteralValue () inline
Definition at line 50 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.PartitionKeyValue.literalValue_.
static String com.cloudera.impala.analysis.PartitionKeyValue.getPartitionKeyValueString (LiteralExpr literalValue, String nullPartitionKeyValue) inline static
Utility method that returns the string value for the given partition key. For NULL values (a NullLiteral type) or empty literal values this will return the given null partition key value.
Definition at line 77 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.LiteralExpr.getStringValue().
Expr com.cloudera.impala.analysis.PartitionKeyValue.getValue () inline
Definition at line 49 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.PartitionKeyValue.value_.
boolean com.cloudera.impala.analysis.PartitionKeyValue.isDynamic () inline
Definition at line 51 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.PartitionKeyValue.value_.
Referenced by com.cloudera.impala.analysis.PartitionKeyValue.isStatic().
boolean com.cloudera.impala.analysis.PartitionKeyValue.isStatic () inline
Definition at line 52 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.PartitionKeyValue.isDynamic().
Referenced by com.cloudera.impala.analysis.PartitionKeyValue.analyze(), com.cloudera.impala.analysis.PartitionKeyValue.toPredicateSql(), and com.cloudera.impala.analysis.PartitionKeyValue.toString().
String com.cloudera.impala.analysis.PartitionKeyValue.toPredicateSql () inline
Returns a binary predicate as a SQL string which matches the column and value of this PartitionKeyValue. If the value is null, correctly substitutes 'IS' as the operator.
Definition at line 63 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.PartitionKeyValue.colName_, com.cloudera.impala.analysis.LiteralExpr.getStringValue(), com.cloudera.impala.analysis.PartitionKeyValue.isStatic(), and com.cloudera.impala.analysis.PartitionKeyValue.literalValue_.
String com.cloudera.impala.analysis.PartitionKeyValue.toString () inline
Definition at line 55 of file PartitionKeyValue.java.
References com.cloudera.impala.analysis.PartitionKeyValue.colName_, and com.cloudera.impala.analysis.PartitionKeyValue.isStatic().
Referenced by com.cloudera.impala.analysis.PartitionKeyValue.analyze().
Member Data Documentation
final String com.cloudera.impala.analysis.PartitionKeyValue.colName_ private
Definition at line 26 of file PartitionKeyValue.java.
Referenced by com.cloudera.impala.analysis.PartitionKeyValue.getColName(), com.cloudera.impala.analysis.PartitionKeyValue.toPredicateSql(), and com.cloudera.impala.analysis.PartitionKeyValue.toString().
LiteralExpr com.cloudera.impala.analysis.PartitionKeyValue.literalValue_ private
Definition at line 30 of file PartitionKeyValue.java.
Referenced by com.cloudera.impala.analysis.PartitionKeyValue.analyze(), com.cloudera.impala.analysis.PartitionKeyValue.getLiteralValue(), and com.cloudera.impala.analysis.PartitionKeyValue.toPredicateSql().
final Expr com.cloudera.impala.analysis.PartitionKeyValue.value_ private
Definition at line 28 of file PartitionKeyValue.java.
Referenced by com.cloudera.impala.analysis.PartitionKeyValue.analyze(), com.cloudera.impala.analysis.PartitionKeyValue.getValue(), and com.cloudera.impala.analysis.PartitionKeyValue.isDynamic().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/PartitionKeyValue.java