Impala: com.cloudera.impala.analysis.CreateOrAlterViewStmtBase Class Reference
com.cloudera.impala.analysis.CreateOrAlterViewStmtBase Class Reference abstract
Public Member Functions
CreateOrAlterViewStmtBase (boolean ifNotExists, TableName tableName, ArrayList< ColumnDef > columnDefs, String comment, QueryStmt viewDefStmt)
TCreateOrAlterViewParams toThrift ()
String getDb ()
String getOwner ()
List< ColumnDef > getColumnDescs ()
String getComment ()
boolean getIfNotExists ()
String getOriginalViewDef ()
String getInlineViewDef ()
String getTbl ()
void analyze (Analyzer analyzer) throws AnalysisException
String toSql ()
void setIsExplain ()
boolean isExplain ()
Protected Member Functions
void createColumnAndViewDefs (Analyzer analyzer) throws AnalysisException
void computeLineageGraph (Analyzer analyzer)
Protected Attributes
final boolean ifNotExists_
final TableName tableName_
final ArrayList< ColumnDef > columnDefs_
final String comment_
final QueryStmt viewDefStmt_
String dbName_
String owner_
String originalViewDef_
String inlineViewDef_
ArrayList< ColumnDef > finalColDefs_
boolean isExplain_ = false
Static Private Attributes
static final Logger LOG
Detailed Description
Base class for CREATE VIEW and ALTER VIEW AS SELECT statements.
Definition at line 34 of file CreateOrAlterViewStmtBase.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.CreateOrAlterViewStmtBase (boolean ifNotExists, TableName tableName, ArrayList< ColumnDef > columnDefs, String comment, QueryStmt viewDefStmt) inline
Definition at line 69 of file CreateOrAlterViewStmtBase.java.
Member Function Documentation
void com.cloudera.impala.analysis.StatementBase.analyze (Analyzer analyzer) throws AnalysisException inline inherited
Analyzes the statement and throws an AnalysisException if analysis fails. A failure could be due to a problem with the statement or because one or more tables/views were missing from the catalog. It is up to the analysis() implementation to ensure the maximum number of missing tables/views get collected in the Analyzer before failing analyze().
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 33 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.computeLineageGraph (Analyzer analyzer) inline protected
Computes the column lineage graph for a create/alter view statetement.
Definition at line 158 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.dbName_, com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.finalColDefs_, and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getTbl().
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), and com.cloudera.impala.analysis.CreateViewStmt.analyze().
void com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs (Analyzer analyzer) throws AnalysisException inline protected
Sets the originalViewDef and the expanded inlineViewDef based on viewDefStmt. If columnDefs were given, checks that they do not contain duplicate column names and throws an exception if they do.
Definition at line 85 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.columnDefs_, com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.dbName_, com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.finalColDefs_, com.cloudera.impala.analysis.QueryStmt.getBaseTblResultExprs(), com.cloudera.impala.analysis.QueryStmt.getColLabels(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.inlineViewDef_, com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.originalViewDef_, com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.owner_, and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.viewDefStmt_.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), and com.cloudera.impala.analysis.CreateViewStmt.analyze().
List<ColumnDef> com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getColumnDescs () inline
Definition at line 200 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.columnDefs_.
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getComment () inline
Definition at line 201 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.comment_.
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getDb () inline
Can only be called after analysis, returns the name of the database the table will be created within.
Definition at line 187 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.dbName_.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
boolean com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getIfNotExists () inline
Definition at line 202 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.ifNotExists_.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getInlineViewDef () inline
Definition at line 204 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.inlineViewDef_.
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getOriginalViewDef () inline
Definition at line 203 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.originalViewDef_.
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getOwner () inline
Can only be called after analysis, returns the owner of the view to be created.
Definition at line 195 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.owner_.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getTbl () inline
Definition at line 205 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.computeLineageGraph(), and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.StatementBase.toSql () inline inherited
Print SQL syntax corresponding to this node.
See Also
com.cloudera.impala.parser.ParseNode::toSql()
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 41 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.CreateUdaStmt.analyze(), and com.cloudera.impala.analysis.QueryStmt.createSortInfo().
TCreateOrAlterViewParams com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift () inline
Definition at line 169 of file CreateOrAlterViewStmtBase.java.
References com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.comment_, com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.finalColDefs_, com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getDb(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getIfNotExists(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getOwner(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getTbl(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.inlineViewDef_, and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.originalViewDef_.
Member Data Documentation
final ArrayList<ColumnDef> com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.columnDefs_ protected
Definition at line 40 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getColumnDescs(), and com.cloudera.impala.analysis.CreateViewStmt.toSql().
final String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.comment_ protected
Definition at line 41 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getComment(), and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.dbName_ protected
Definition at line 45 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), com.cloudera.impala.analysis.CreateViewStmt.analyze(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.computeLineageGraph(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs(), and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getDb().
ArrayList<ColumnDef> com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.finalColDefs_ protected
Definition at line 67 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.computeLineageGraph(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs(), and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
final boolean com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.ifNotExists_ protected
Definition at line 38 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.CreateViewStmt.analyze(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getIfNotExists(), and com.cloudera.impala.analysis.CreateViewStmt.toSql().
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.inlineViewDef_ protected
Definition at line 63 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getInlineViewDef(), and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final Logger com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.LOG static private
Initial value:
=
      LoggerFactory.getLogger(CreateOrAlterViewStmtBase.class)
Definition at line 35 of file CreateOrAlterViewStmtBase.java.
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.originalViewDef_ protected
Definition at line 50 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getOriginalViewDef(), and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.toThrift().
String com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.owner_ protected
Definition at line 46 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), com.cloudera.impala.analysis.CreateViewStmt.analyze(), com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs(), and com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.getOwner().
final TableName com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.tableName_ protected
Definition at line 39 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), com.cloudera.impala.analysis.CreateViewStmt.analyze(), com.cloudera.impala.analysis.AlterViewStmt.toSql(), and com.cloudera.impala.analysis.CreateViewStmt.toSql().
final QueryStmt com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.viewDefStmt_ protected
Definition at line 42 of file CreateOrAlterViewStmtBase.java.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/CreateOrAlterViewStmtBase.java