Impala: com.cloudera.impala.analysis.DropDbStmt Class Reference
com.cloudera.impala.analysis.DropDbStmt Class Reference
Public Member Functions
DropDbStmt (String dbName, boolean ifExists)
String getDb ()
boolean getIfExists ()
String toSql ()
TDropDbParams toThrift ()
void analyze (Analyzer analyzer) throws AnalysisException
void setIsExplain ()
boolean isExplain ()
Protected Attributes
boolean isExplain_ = false
Private Attributes
final String dbName_
final boolean ifExists_
Detailed Description
Represents a DROP [IF EXISTS] DATABASE statement
Definition at line 25 of file DropDbStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.DropDbStmt.DropDbStmt (String dbName, boolean ifExists) inline
Constructor for building the drop statement. If ifExists is true, an error will not be thrown if the database does not exist.
Definition at line 33 of file DropDbStmt.java.
Member Function Documentation
void com.cloudera.impala.analysis.DropDbStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 59 of file DropDbStmt.java.
References com.cloudera.impala.analysis.Analyzer.DB_DOES_NOT_EXIST_ERROR_MSG, com.cloudera.impala.analysis.DropDbStmt.dbName_, com.cloudera.impala.authorization.Privilege.DROP, com.cloudera.impala.analysis.DropDbStmt.ifExists_, and com.cloudera.impala.catalog.Db.numFunctions().
String com.cloudera.impala.analysis.DropDbStmt.getDb () inline
Definition at line 38 of file DropDbStmt.java.
References com.cloudera.impala.analysis.DropDbStmt.dbName_.
Referenced by com.cloudera.impala.analysis.DropDbStmt.toSql(), and com.cloudera.impala.analysis.DropDbStmt.toThrift().
boolean com.cloudera.impala.analysis.DropDbStmt.getIfExists () inline
Definition at line 39 of file DropDbStmt.java.
References com.cloudera.impala.analysis.DropDbStmt.ifExists_.
Referenced by com.cloudera.impala.analysis.DropDbStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.DropDbStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 42 of file DropDbStmt.java.
References com.cloudera.impala.analysis.DropDbStmt.getDb(), and com.cloudera.impala.analysis.DropDbStmt.ifExists_.
TDropDbParams com.cloudera.impala.analysis.DropDbStmt.toThrift () inline
Definition at line 51 of file DropDbStmt.java.
References com.cloudera.impala.analysis.DropDbStmt.getDb(), and com.cloudera.impala.analysis.DropDbStmt.getIfExists().
Member Data Documentation
final String com.cloudera.impala.analysis.DropDbStmt.dbName_ private
Definition at line 26 of file DropDbStmt.java.
Referenced by com.cloudera.impala.analysis.DropDbStmt.analyze(), and com.cloudera.impala.analysis.DropDbStmt.getDb().
final boolean com.cloudera.impala.analysis.DropDbStmt.ifExists_ private
Definition at line 27 of file DropDbStmt.java.
Referenced by com.cloudera.impala.analysis.DropDbStmt.analyze(), com.cloudera.impala.analysis.DropDbStmt.getIfExists(), and com.cloudera.impala.analysis.DropDbStmt.toSql().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/DropDbStmt.java