Impala: com.cloudera.impala.analysis.CreateTableAsSelectStmt Class Reference
com.cloudera.impala.analysis.CreateTableAsSelectStmt Class Reference
Public Member Functions
CreateTableAsSelectStmt (CreateTableStmt createStmt, QueryStmt queryStmt)
QueryStmt getQueryStmt ()
InsertStmt getInsertStmt ()
CreateTableStmt getCreateStmt ()
String toSql ()
void analyze (Analyzer analyzer) throws AnalysisException
void setIsExplain ()
boolean isExplain ()
Protected Attributes
boolean isExplain_ = false
Private Attributes
final CreateTableStmt createStmt_
final InsertStmt insertStmt_
Static Private Attributes
static final EnumSet
< THdfsFileFormat > SUPPORTED_INSERT_FORMATS
Detailed Description
Represents a CREATE TABLE AS SELECT (CTAS) statement
Definition at line 34 of file CreateTableAsSelectStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.CreateTableAsSelectStmt.CreateTableAsSelectStmt (CreateTableStmt createStmt, QueryStmt queryStmt) inline
Builds a CREATE TABLE AS SELECT statement
Definition at line 43 of file CreateTableAsSelectStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.getTblName().
Member Function Documentation
void com.cloudera.impala.analysis.CreateTableAsSelectStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 58 of file CreateTableAsSelectStmt.java.
References com.cloudera.impala.authorization.Privilege.ANY, com.cloudera.impala.analysis.CreateTableAsSelectStmt.createStmt_, com.cloudera.impala.analysis.Analyzer.DB_DOES_NOT_EXIST_ERROR_MSG, com.cloudera.impala.analysis.CreateTableStmt.getDb(), com.cloudera.impala.analysis.CreateTableStmt.getFileFormat(), com.cloudera.impala.analysis.CreateTableStmt.getLocation(), and com.cloudera.impala.analysis.CreateTableAsSelectStmt.SUPPORTED_INSERT_FORMATS.
CreateTableStmt com.cloudera.impala.analysis.CreateTableAsSelectStmt.getCreateStmt () inline
Definition at line 53 of file CreateTableAsSelectStmt.java.
References com.cloudera.impala.analysis.CreateTableAsSelectStmt.createStmt_.
InsertStmt com.cloudera.impala.analysis.CreateTableAsSelectStmt.getInsertStmt () inline
Definition at line 52 of file CreateTableAsSelectStmt.java.
References com.cloudera.impala.analysis.CreateTableAsSelectStmt.insertStmt_.
QueryStmt com.cloudera.impala.analysis.CreateTableAsSelectStmt.getQueryStmt () inline
Definition at line 51 of file CreateTableAsSelectStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.toSql().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.CreateTableAsSelectStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 55 of file CreateTableAsSelectStmt.java.
References com.cloudera.impala.analysis.CreateTableAsSelectStmt.getQueryStmt().
Member Data Documentation
final CreateTableStmt com.cloudera.impala.analysis.CreateTableAsSelectStmt.createStmt_ private
Definition at line 35 of file CreateTableAsSelectStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.analyze(), and com.cloudera.impala.analysis.CreateTableAsSelectStmt.getCreateStmt().
final InsertStmt com.cloudera.impala.analysis.CreateTableAsSelectStmt.insertStmt_ private
Definition at line 36 of file CreateTableAsSelectStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.getInsertStmt().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final EnumSet<THdfsFileFormat> com.cloudera.impala.analysis.CreateTableAsSelectStmt.SUPPORTED_INSERT_FORMATS static private
Initial value:
=
      EnumSet.of(THdfsFileFormat.PARQUET, THdfsFileFormat.TEXT)
Definition at line 37 of file CreateTableAsSelectStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.analyze().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/CreateTableAsSelectStmt.java