Impala: com.cloudera.impala.catalog.HdfsTable.FsKey Class Reference
com.cloudera.impala.catalog.HdfsTable.FsKey Class Reference
Public Member Functions
FsKey (FileSystem fs)
int hashCode ()
boolean equals (Object o)
String toString ()
Package Attributes
FileSystem filesystem
Detailed Description
Definition at line 194 of file HdfsTable.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.HdfsTable.FsKey.FsKey (FileSystem fs) inline
Definition at line 197 of file HdfsTable.java.
References com.cloudera.impala.catalog.HdfsTable.FsKey.filesystem.
Referenced by com.cloudera.impala.catalog.HdfsTable.FsKey.equals().
Member Function Documentation
boolean com.cloudera.impala.catalog.HdfsTable.FsKey.equals (Object o) inline
Definition at line 203 of file HdfsTable.java.
References com.cloudera.impala.catalog.HdfsTable.FsKey.FsKey().
int com.cloudera.impala.catalog.HdfsTable.FsKey.hashCode () inline
Definition at line 200 of file HdfsTable.java.
References com.cloudera.impala.catalog.HdfsTable.FsKey.hashCode().
Referenced by com.cloudera.impala.catalog.HdfsTable.FsKey.hashCode().
String com.cloudera.impala.catalog.HdfsTable.FsKey.toString () inline
Definition at line 214 of file HdfsTable.java.
References com.cloudera.impala.catalog.HdfsTable.FsKey.toString().
Referenced by com.cloudera.impala.catalog.HdfsTable.FsKey.toString().
Member Data Documentation
FileSystem com.cloudera.impala.catalog.HdfsTable.FsKey.filesystem package
Definition at line 195 of file HdfsTable.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.FsKey.FsKey().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HdfsTable.java