Impala: com.cloudera.impala.analysis.UnionStmt Class Reference
com.cloudera.impala.analysis.UnionStmt Class Reference
Classes
enum Qualifier
class UnionOperand
Public Member Functions
UnionStmt (List< UnionOperand > operands, ArrayList< OrderByElement > orderByElements, LimitElement limitElement)
List< UnionOperand > getOperands ()
List< UnionOperand > getDistinctOperands ()
boolean hasDistinctOps ()
List< UnionOperand > getAllOperands ()
boolean hasAllOps ()
AggregateInfo getDistinctAggInfo ()
boolean hasAnalyticExprs ()
void removeAllOperands ()
void analyze (Analyzer analyzer) throws AnalysisException
void materializeRequiredSlots (Analyzer analyzer) throws InternalException
TupleId getTupleId ()
void getMaterializedTupleIds (ArrayList< TupleId > tupleIdList)
String toSql ()
ArrayList< String > getColLabels ()
QueryStmt clone ()
Analyzer getAnalyzer ()
void setWithClause (WithClause withClause)
boolean hasWithClause ()
WithClause getWithClause ()
boolean hasOrderByClause ()
boolean hasLimit ()
long getLimit ()
boolean hasOffset ()
long getOffset ()
SortInfo getSortInfo ()
boolean evaluateOrderBy ()
ArrayList< Expr > getResultExprs ()
ArrayList< Expr > getBaseTblResultExprs ()
void setLimit (long limit) throws AnalysisException
ArrayList< OrderByElement > cloneOrderByElements ()
WithClause cloneWithClause ()
void setIsExplain ()
boolean isExplain ()
Protected Member Functions
String queryStmtToSql (QueryStmt queryStmt)
void createSortInfo (Analyzer analyzer) throws AnalysisException
void createSortTupleInfo (Analyzer analyzer)
Expr getFirstAmbiguousAlias (List< Expr > exprs)
void substituteOrdinals (List< Expr > exprs, String errorPrefix, Analyzer analyzer) throws AnalysisException
void materializeSlots (Analyzer analyzer, List< Expr > exprs)
Protected Attributes
final List< UnionOperand > operands_
final List< UnionOperand > distinctOperands_ = Lists.newArrayList()
final List< UnionOperand > allOperands_ = Lists.newArrayList()
AggregateInfo distinctAggInfo_
TupleId tupleId_
String toSqlString_ = null
WithClause withClause_
ArrayList< OrderByElement > orderByElements_
LimitElement limitElement_
ArrayList< Expr > resultExprs_ = Lists.newArrayList()
ArrayList< Expr > baseTblResultExprs_ = Lists.newArrayList()
final ExprSubstitutionMap aliasSmap_ = new ExprSubstitutionMap()
final ArrayList< Expr > ambiguousAliasList_ = Lists.newArrayList()
SortInfo sortInfo_
boolean evaluateOrderBy_
Analyzer analyzer_
boolean isExplain_ = false
Private Member Functions
void unnestOperands (Analyzer analyzer) throws AnalysisException
void setOperandSmap (UnionOperand operand, Analyzer analyzer)
void unnestOperand (List< UnionOperand > target, Qualifier targetQualifier, UnionOperand operand)
void propagateDistinct ()
void createMetadata (Analyzer analyzer) throws AnalysisException
Private Attributes
boolean hasAnalyticExprs_ = false
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(UnionStmt.class)
Detailed Description
Representation of a union with its list of operands, and optional order by and limit. A union materializes its results, and its resultExprs are slotrefs into the materialized tuple. During analysis, the operands are normalized (separated into a single sequence of DISTINCT followed by a single sequence of ALL operands) and unnested to the extent possible. This also creates the AggregationInfo for DISTINCT operands.
Definition at line 37 of file UnionStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.UnionStmt.UnionStmt (List< UnionOperand > operands, ArrayList< OrderByElement > orderByElements, LimitElement limitElement) inline
Definition at line 125 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.clone(), com.cloudera.impala.analysis.UnionStmt.UnionOperand.hasAnalyticExprs(), and com.cloudera.impala.analysis.UnionStmt.unnestOperand().
Member Function Documentation
void com.cloudera.impala.analysis.UnionStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Propagates DISTINCT from left to right, and checks that all union operands are union compatible, adding implicit casts if necessary.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 149 of file UnionStmt.java.
References com.cloudera.impala.analysis.QueryStmt.baseTblResultExprs_, com.cloudera.impala.analysis.UnionStmt.createMetadata(), com.cloudera.impala.analysis.QueryStmt.createSortInfo(), com.cloudera.impala.analysis.QueryStmt.createSortTupleInfo(), com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy_, com.cloudera.impala.analysis.UnionStmt.hasAnalyticExprs_, com.cloudera.impala.analysis.UnionStmt.operands_, com.cloudera.impala.analysis.UnionStmt.propagateDistinct(), com.cloudera.impala.analysis.UnionStmt.queryStmtToSql(), com.cloudera.impala.analysis.QueryStmt.resultExprs_, com.cloudera.impala.analysis.UnionStmt.toSql(), com.cloudera.impala.analysis.UnionStmt.toSqlString_, and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
QueryStmt com.cloudera.impala.analysis.UnionStmt.clone () inline
Definition at line 529 of file UnionStmt.java.
References com.cloudera.impala.analysis.LimitElement.clone(), com.cloudera.impala.analysis.QueryStmt.cloneOrderByElements(), com.cloudera.impala.analysis.QueryStmt.cloneWithClause(), com.cloudera.impala.analysis.UnionStmt.hasAnalyticExprs_, com.cloudera.impala.analysis.QueryStmt.limitElement_, com.cloudera.impala.analysis.UnionStmt.operands_, and com.cloudera.impala.analysis.UnionStmt.UnionStmt().
Referenced by com.cloudera.impala.analysis.UnionStmt.setOperandSmap().
ArrayList<OrderByElement> com.cloudera.impala.analysis.QueryStmt.cloneOrderByElements () inline inherited
Definition at line 311 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.orderByElements_.
Referenced by com.cloudera.impala.analysis.ValuesStmt.clone(), com.cloudera.impala.analysis.UnionStmt.clone(), and com.cloudera.impala.analysis.SelectStmt.clone().
WithClause com.cloudera.impala.analysis.QueryStmt.cloneWithClause () inline inherited
Definition at line 315 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.withClause_.
Referenced by com.cloudera.impala.analysis.ValuesStmt.clone(), com.cloudera.impala.analysis.UnionStmt.clone(), and com.cloudera.impala.analysis.SelectStmt.clone().
void com.cloudera.impala.analysis.UnionStmt.createMetadata (Analyzer analyzer) throws AnalysisException inline private
Create a descriptor for the tuple materialized by the union. Set resultExprs to be slot refs into that tuple. Also fills the substitution map, such that "order by" can properly resolve column references from the result of the union.
Definition at line 399 of file UnionStmt.java.
References com.cloudera.impala.analysis.QueryStmt.aliasSmap_, com.cloudera.impala.analysis.QueryStmt.baseTblResultExprs_, com.cloudera.impala.analysis.ExprSubstitutionMap.containsMappingFor(), com.cloudera.impala.analysis.QueryStmt.getBaseTblResultExprs(), com.cloudera.impala.analysis.UnionStmt.getColLabels(), com.cloudera.impala.analysis.SlotRef.getSlotId(), com.cloudera.impala.analysis.UnionStmt.operands_, com.cloudera.impala.analysis.QueryStmt.orderByElements_, com.cloudera.impala.analysis.QueryStmt.resultExprs_, and com.cloudera.impala.analysis.UnionStmt.tupleId_.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze().
void com.cloudera.impala.analysis.QueryStmt.createSortInfo (Analyzer analyzer) throws AnalysisException inline protected inherited
Creates sortInfo by resolving aliases and ordinals in the orderingExprs. If the query stmt is an inline view/union operand, then order-by with no limit with offset is not allowed, since that requires a sort and merging-exchange, and subsequent query execution would occur on a single machine. Sets evaluateOrderBy_ to false for ignored order-by w/o limit/offset in nested queries.
Definition at line 115 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.aliasSmap_, com.cloudera.impala.analysis.QueryStmt.clone(), com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy_, com.cloudera.impala.analysis.QueryStmt.getFirstAmbiguousAlias(), com.cloudera.impala.analysis.QueryStmt.hasLimit(), com.cloudera.impala.analysis.QueryStmt.hasOffset(), com.cloudera.impala.analysis.QueryStmt.orderByElements_, com.cloudera.impala.analysis.QueryStmt.sortInfo_, com.cloudera.impala.analysis.QueryStmt.substituteOrdinals(), com.cloudera.impala.analysis.StatementBase.toSql(), and com.cloudera.impala.analysis.Expr.toSql().
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), and com.cloudera.impala.analysis.UnionStmt.analyze().
void com.cloudera.impala.analysis.QueryStmt.createSortTupleInfo (Analyzer analyzer) inline protected inherited
Create a tuple descriptor for the single tuple that is materialized, sorted and output by the exec node implementing the sort. Done by materializing slot refs in the order-by and result expressions. Those SlotRefs in the ordering and result exprs are substituted with SlotRefs into the new tuple. This simplifies sorting logic for total (no limit) sorts. Done after analyzeAggregation() since ordering and result exprs may refer to the outputs of aggregation. Invoked for UnionStmt as well since TODO: We could do something more sophisticated than simply copying input slotrefs - e.g. compute some order-by expressions.
Definition at line 185 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy_, and com.cloudera.impala.analysis.QueryStmt.resultExprs_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), and com.cloudera.impala.analysis.UnionStmt.analyze().
boolean com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy () inline inherited
Definition at line 278 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy_.
List<UnionOperand> com.cloudera.impala.analysis.UnionStmt.getAllOperands () inline
Definition at line 134 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.allOperands_.
Analyzer com.cloudera.impala.analysis.QueryStmt.getAnalyzer () inline inherited
Definition at line 83 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.analyzer_.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.createInlineViewPlan(), and com.cloudera.impala.analysis.StmtRewriter.rewrite().
ArrayList<Expr> com.cloudera.impala.analysis.QueryStmt.getBaseTblResultExprs () inline inherited
Definition at line 280 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.baseTblResultExprs_.
Referenced by com.cloudera.impala.analysis.CreateOrAlterViewStmtBase.createColumnAndViewDefs(), com.cloudera.impala.analysis.UnionStmt.createMetadata(), com.cloudera.impala.planner.SingleNodePlanner.createSingleNodePlan(), and com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots().
ArrayList<String> com.cloudera.impala.analysis.UnionStmt.getColLabels () inline
Definition at line 523 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.createMetadata().
AggregateInfo com.cloudera.impala.analysis.UnionStmt.getDistinctAggInfo () inline
Definition at line 136 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.distinctAggInfo_.
List<UnionOperand> com.cloudera.impala.analysis.UnionStmt.getDistinctOperands () inline
Definition at line 132 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.distinctOperands_.
Expr com.cloudera.impala.analysis.QueryStmt.getFirstAmbiguousAlias (List< Expr > exprs) inline protected inherited
Return the first expr in exprs that is a non-unique alias. Return null if none of exprs is an ambiguous alias.
Definition at line 219 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.ambiguousAliasList_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), and com.cloudera.impala.analysis.QueryStmt.createSortInfo().
long com.cloudera.impala.analysis.QueryStmt.getLimit () inline inherited
Definition at line 274 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.QueryStmt.setLimit().
void com.cloudera.impala.analysis.UnionStmt.getMaterializedTupleIds (ArrayList< TupleId > tupleIdList) inline
Definition at line 462 of file UnionStmt.java.
References com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy_, and com.cloudera.impala.analysis.UnionStmt.tupleId_.
long com.cloudera.impala.analysis.QueryStmt.getOffset () inline inherited
Definition at line 276 of file QueryStmt.java.
List<UnionOperand> com.cloudera.impala.analysis.UnionStmt.getOperands () inline
Definition at line 131 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.operands_.
ArrayList<Expr> com.cloudera.impala.analysis.QueryStmt.getResultExprs () inline inherited
Definition at line 279 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.resultExprs_.
Referenced by com.cloudera.impala.analysis.UnionStmt.setOperandSmap(), com.cloudera.impala.analysis.AnalyzeStmtsTest.testSlotRefPath(), and com.cloudera.impala.analysis.AnalyzeStmtsTest.TestStar().
SortInfo com.cloudera.impala.analysis.QueryStmt.getSortInfo () inline inherited
Definition at line 277 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.sortInfo_.
TupleId com.cloudera.impala.analysis.UnionStmt.getTupleId () inline
Definition at line 459 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.tupleId_.
WithClause com.cloudera.impala.analysis.QueryStmt.getWithClause () inline inherited
Definition at line 271 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.withClause_.
boolean com.cloudera.impala.analysis.UnionStmt.hasAllOps () inline
Definition at line 135 of file UnionStmt.java.
boolean com.cloudera.impala.analysis.UnionStmt.hasAnalyticExprs () inline
Definition at line 137 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.hasAnalyticExprs_.
boolean com.cloudera.impala.analysis.UnionStmt.hasDistinctOps () inline
Definition at line 133 of file UnionStmt.java.
boolean com.cloudera.impala.analysis.QueryStmt.hasLimit () inline inherited
Definition at line 273 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), com.cloudera.impala.analysis.StmtRewriter.canRewriteCorrelatedSubquery(), com.cloudera.impala.analysis.QueryStmt.createSortInfo(), com.cloudera.impala.analysis.QueryStmt.setLimit(), and com.cloudera.impala.analysis.UnionStmt.toSql().
boolean com.cloudera.impala.analysis.QueryStmt.hasOffset () inline inherited
Definition at line 275 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.QueryStmt.createSortInfo(), and com.cloudera.impala.analysis.UnionStmt.toSql().
boolean com.cloudera.impala.analysis.QueryStmt.hasOrderByClause () inline inherited
Definition at line 272 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.orderByElements_.
Referenced by com.cloudera.impala.analysis.QueryStmt.analyzeLimit(), and com.cloudera.impala.analysis.UnionStmt.toSql().
boolean com.cloudera.impala.analysis.QueryStmt.hasWithClause () inline inherited
Definition at line 270 of file QueryStmt.java.
References com.cloudera.impala.analysis.QueryStmt.withClause_.
Referenced by com.cloudera.impala.analysis.QueryStmt.analyze().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots (Analyzer analyzer) throws InternalException inline
Marks the baseTblResultExprs of its operands as materialized, based on which of the output slots have been marked. Calls materializeRequiredSlots() on the operands themselves.
Definition at line 221 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.distinctAggInfo_, com.cloudera.impala.analysis.UnionStmt.distinctOperands_, com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy_, com.cloudera.impala.analysis.QueryStmt.getBaseTblResultExprs(), com.cloudera.impala.analysis.TupleDescriptor.getSlots(), com.cloudera.impala.analysis.SlotDescriptor.isMaterialized(), com.cloudera.impala.analysis.QueryStmt.materializeSlots(), com.cloudera.impala.analysis.UnionStmt.operands_, and com.cloudera.impala.analysis.UnionStmt.tupleId_.
void com.cloudera.impala.analysis.QueryStmt.materializeSlots (Analyzer analyzer, List< Expr > exprs) inline protected inherited
Mark slots referenced in exprs as materialized.
Definition at line 303 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots(), and com.cloudera.impala.analysis.SelectStmt.materializeRequiredSlots().
void com.cloudera.impala.analysis.UnionStmt.propagateDistinct () inline private
Propagates DISTINCT (if present) from right to left. Implied associativity: A UNION ALL B UNION DISTINCT C = (A UNION ALL B) UNION DISTINCT C = A UNION DISTINCT B UNION DISTINCT C
Definition at line 380 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.Qualifier.DISTINCT, com.cloudera.impala.analysis.UnionStmt.UnionOperand.getQualifier(), and com.cloudera.impala.analysis.UnionStmt.operands_.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze().
String com.cloudera.impala.analysis.UnionStmt.queryStmtToSql (QueryStmt queryStmt) inline protected
String representation of queryStmt used in reporting errors. Allow subclasses to override this.
Definition at line 370 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze().
void com.cloudera.impala.analysis.UnionStmt.removeAllOperands () inline
Definition at line 139 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.allOperands_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.QueryStmt.setLimit (long limit) throws AnalysisException inline inherited
Definition at line 281 of file QueryStmt.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.analysis.QueryStmt.getLimit(), com.cloudera.impala.analysis.QueryStmt.hasLimit(), and com.cloudera.impala.analysis.QueryStmt.limitElement_.
Referenced by com.cloudera.impala.analysis.StmtRewriter.mergeExpr().
void com.cloudera.impala.analysis.UnionStmt.setOperandSmap (UnionOperand operand, Analyzer analyzer) inline private
Sets the smap for the given operand. It maps from the output slots this union's tuple to the corresponding base table exprs of the operand.
Definition at line 322 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.clone(), com.cloudera.impala.analysis.QueryStmt.getResultExprs(), and com.cloudera.impala.analysis.UnionStmt.tupleId_.
Referenced by com.cloudera.impala.analysis.UnionStmt.unnestOperands().
void com.cloudera.impala.analysis.QueryStmt.setWithClause (WithClause withClause) inline inherited
Definition at line 269 of file QueryStmt.java.
void com.cloudera.impala.analysis.QueryStmt.substituteOrdinals (List< Expr > exprs, String errorPrefix, Analyzer analyzer) throws AnalysisException inline protected inherited
Substitute exprs of the form "<number>" with the corresponding expressions.
Definition at line 230 of file QueryStmt.java.
References com.cloudera.impala.analysis.Expr.getType(), com.cloudera.impala.analysis.QueryStmt.resultExprs_, and com.cloudera.impala.analysis.Expr.toSql().
Referenced by com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), and com.cloudera.impala.analysis.QueryStmt.createSortInfo().
String com.cloudera.impala.analysis.UnionStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 472 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.Qualifier.ALL, com.cloudera.impala.analysis.QueryStmt.hasLimit(), com.cloudera.impala.analysis.QueryStmt.hasOffset(), com.cloudera.impala.analysis.QueryStmt.hasOrderByClause(), com.cloudera.impala.analysis.UnionStmt.operands_, com.cloudera.impala.analysis.UnionStmt.toSqlString_, and com.cloudera.impala.analysis.QueryStmt.withClause_.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze().
void com.cloudera.impala.analysis.UnionStmt.unnestOperand (List< UnionOperand > target, Qualifier targetQualifier, UnionOperand operand) inline private
Add a single operand to the target list; if the operand itself is a UnionStmt, apply unnesting to the extent possible (possibly modifying 'operand' in the process).
Definition at line 339 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.Qualifier.DISTINCT, and com.cloudera.impala.analysis.UnionStmt.UnionStmt().
Referenced by com.cloudera.impala.analysis.UnionStmt.unnestOperands().
void com.cloudera.impala.analysis.UnionStmt.unnestOperands (Analyzer analyzer) throws AnalysisException inline private
Fill distinct-/allOperands and performs possible unnesting of UnionStmt operands in the process.
Definition at line 261 of file UnionStmt.java.
References com.cloudera.impala.analysis.UnionStmt.Qualifier.ALL, com.cloudera.impala.analysis.UnionStmt.allOperands_, com.cloudera.impala.analysis.UnionStmt.Qualifier.DISTINCT, com.cloudera.impala.analysis.UnionStmt.distinctAggInfo_, com.cloudera.impala.analysis.UnionStmt.distinctOperands_, com.cloudera.impala.analysis.UnionStmt.UnionOperand.getQualifier(), com.cloudera.impala.analysis.UnionStmt.operands_, com.cloudera.impala.analysis.QueryStmt.resultExprs_, com.cloudera.impala.analysis.UnionStmt.setOperandSmap(), com.cloudera.impala.analysis.UnionStmt.tupleId_, and com.cloudera.impala.analysis.UnionStmt.unnestOperand().
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze().
Member Data Documentation
final ExprSubstitutionMap com.cloudera.impala.analysis.QueryStmt.aliasSmap_ = new ExprSubstitutionMap() protected inherited
Map of expression substitutions for replacing aliases in "order by" or "group by" clauses with their corresponding result expr.
Definition at line 62 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.analysis.UnionStmt.createMetadata(), and com.cloudera.impala.analysis.QueryStmt.createSortInfo().
final List<UnionOperand> com.cloudera.impala.analysis.UnionStmt.allOperands_ = Lists.newArrayList() protected
Definition at line 112 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.getAllOperands(), com.cloudera.impala.analysis.UnionStmt.removeAllOperands(), and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
final ArrayList<Expr> com.cloudera.impala.analysis.QueryStmt.ambiguousAliasList_ = Lists.newArrayList() protected inherited
Select list item alias does not have to be unique. This list contains all the non-unique aliases. For example, select int_col a, string_col a from alltypessmall; Both columns are using the same alias "a".
Definition at line 70 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.QueryStmt.getFirstAmbiguousAlias().
Analyzer com.cloudera.impala.analysis.QueryStmt.analyzer_ protected inherited
Definition at line 81 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.QueryStmt.getAnalyzer(), and com.cloudera.impala.analysis.SelectStmt.getTableAliasGenerator().
ArrayList<Expr> com.cloudera.impala.analysis.QueryStmt.baseTblResultExprs_ = Lists.newArrayList() protected inherited
Definition at line 56 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze(), com.cloudera.impala.analysis.UnionStmt.createMetadata(), com.cloudera.impala.analysis.QueryStmt.getBaseTblResultExprs(), and com.cloudera.impala.analysis.SelectStmt.resolveInlineViewRefs().
AggregateInfo com.cloudera.impala.analysis.UnionStmt.distinctAggInfo_ protected
Definition at line 114 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.getDistinctAggInfo(), com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots(), and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
final List<UnionOperand> com.cloudera.impala.analysis.UnionStmt.distinctOperands_ = Lists.newArrayList() protected
Definition at line 107 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.getDistinctOperands(), com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots(), and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
boolean com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy_ protected inherited
Definition at line 78 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), com.cloudera.impala.analysis.UnionStmt.analyze(), com.cloudera.impala.analysis.QueryStmt.createSortInfo(), com.cloudera.impala.analysis.QueryStmt.createSortTupleInfo(), com.cloudera.impala.analysis.QueryStmt.evaluateOrderBy(), com.cloudera.impala.analysis.UnionStmt.getMaterializedTupleIds(), com.cloudera.impala.analysis.SelectStmt.getMaterializedTupleIds(), com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots(), and com.cloudera.impala.analysis.SelectStmt.materializeRequiredSlots().
boolean com.cloudera.impala.analysis.UnionStmt.hasAnalyticExprs_ = false private
Definition at line 123 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze(), com.cloudera.impala.analysis.UnionStmt.clone(), and com.cloudera.impala.analysis.UnionStmt.hasAnalyticExprs().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
LimitElement com.cloudera.impala.analysis.QueryStmt.limitElement_ protected inherited
Definition at line 45 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.QueryStmt.analyzeLimit(), com.cloudera.impala.analysis.ValuesStmt.clone(), com.cloudera.impala.analysis.UnionStmt.clone(), com.cloudera.impala.analysis.SelectStmt.clone(), com.cloudera.impala.analysis.QueryStmt.QueryStmt(), com.cloudera.impala.analysis.SelectStmt.returnsSingleRow(), and com.cloudera.impala.analysis.QueryStmt.setLimit().
final Logger com.cloudera.impala.analysis.UnionStmt.LOG = LoggerFactory.getLogger(UnionStmt.class) static private
Definition at line 38 of file UnionStmt.java.
final List<UnionOperand> com.cloudera.impala.analysis.UnionStmt.operands_ protected
Definition at line 103 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze(), com.cloudera.impala.analysis.ValuesStmt.clone(), com.cloudera.impala.analysis.UnionStmt.clone(), com.cloudera.impala.analysis.UnionStmt.createMetadata(), com.cloudera.impala.analysis.UnionStmt.getOperands(), com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots(), com.cloudera.impala.analysis.UnionStmt.propagateDistinct(), com.cloudera.impala.analysis.ValuesStmt.toSql(), com.cloudera.impala.analysis.UnionStmt.toSql(), and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
ArrayList<OrderByElement> com.cloudera.impala.analysis.QueryStmt.orderByElements_ protected inherited
Definition at line 44 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.analysis.QueryStmt.cloneOrderByElements(), com.cloudera.impala.analysis.UnionStmt.createMetadata(), com.cloudera.impala.analysis.QueryStmt.createSortInfo(), com.cloudera.impala.analysis.QueryStmt.hasOrderByClause(), com.cloudera.impala.analysis.QueryStmt.QueryStmt(), and com.cloudera.impala.analysis.SelectStmt.toSql().
ArrayList<Expr> com.cloudera.impala.analysis.QueryStmt.resultExprs_ = Lists.newArrayList() protected inherited
Definition at line 52 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), com.cloudera.impala.analysis.UnionStmt.analyze(), com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.analysis.SelectStmt.analyzeAnalytics(), com.cloudera.impala.analysis.SelectStmt.createAggInfo(), com.cloudera.impala.analysis.UnionStmt.createMetadata(), com.cloudera.impala.analysis.QueryStmt.createSortTupleInfo(), com.cloudera.impala.analysis.QueryStmt.getResultExprs(), com.cloudera.impala.analysis.SelectStmt.resolveInlineViewRefs(), com.cloudera.impala.analysis.QueryStmt.substituteOrdinals(), and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
SortInfo com.cloudera.impala.analysis.QueryStmt.sortInfo_ protected inherited
Definition at line 72 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.analysis.SelectStmt.analyzeAnalytics(), com.cloudera.impala.analysis.QueryStmt.createSortInfo(), com.cloudera.impala.analysis.QueryStmt.getSortInfo(), and com.cloudera.impala.analysis.QueryStmt.QueryStmt().
String com.cloudera.impala.analysis.UnionStmt.toSqlString_ = null protected
Definition at line 120 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.analyze(), and com.cloudera.impala.analysis.UnionStmt.toSql().
TupleId com.cloudera.impala.analysis.UnionStmt.tupleId_ protected
Definition at line 117 of file UnionStmt.java.
Referenced by com.cloudera.impala.analysis.UnionStmt.createMetadata(), com.cloudera.impala.analysis.UnionStmt.getMaterializedTupleIds(), com.cloudera.impala.analysis.UnionStmt.getTupleId(), com.cloudera.impala.analysis.UnionStmt.materializeRequiredSlots(), com.cloudera.impala.analysis.UnionStmt.setOperandSmap(), and com.cloudera.impala.analysis.UnionStmt.unnestOperands().
WithClause com.cloudera.impala.analysis.QueryStmt.withClause_ protected inherited
Definition at line 42 of file QueryStmt.java.
Referenced by com.cloudera.impala.analysis.QueryStmt.cloneWithClause(), com.cloudera.impala.analysis.QueryStmt.getWithClause(), com.cloudera.impala.analysis.QueryStmt.hasWithClause(), com.cloudera.impala.analysis.ValuesStmt.toSql(), com.cloudera.impala.analysis.UnionStmt.toSql(), and com.cloudera.impala.analysis.SelectStmt.toSql().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/UnionStmt.java