Impala: com.cloudera.impala.testutil.ImpalaJdbcClient Class Reference
com.cloudera.impala.testutil.ImpalaJdbcClient Class Reference
Classes
class ClientExecOptions
Public Member Functions
void connect () throws ClassNotFoundException, SQLException
void close () throws SQLException
ResultSet execQuery (String query) throws SQLException
void changeDatabase (String db_name) throws SQLException
Connection getConnection ()
Statement getStatement ()
Static Public Member Functions
static ImpalaJdbcClient createClientUsingHiveJdbcDriver ()
static ImpalaJdbcClient createClientUsingHiveJdbcDriver (String connString)
static void main (String[] args) throws SQLException, ClassNotFoundException, ParseException
Private Member Functions
ImpalaJdbcClient (String driverName, String connString)
void validateConnection () throws SQLException
Static Private Member Functions
static ClientExecOptions parseOptions (String[] args) throws ParseException
static String formatColumnValue (String colVal, String columnType) throws NumberFormatException
static void execQuery (ImpalaJdbcClient client, String queryString) throws SQLException, NumberFormatException
Private Attributes
final String driverName_
final String connString_
Connection conn_
Statement stmt_
Static Private Attributes
static final Logger LOG = Logger.getLogger(ImpalaJdbcClient.class)
static final String HIVE_SERVER2_DRIVER_NAME
static final String SASL_AUTH_SPEC = ";auth=none"
static final String NOSASL_AUTH_SPEC = ";auth=noSasl"
static final String DEFAULT_CONNECTION_STRING
Detailed Description
Basic tool for executing queries and and displaying results using Impala over JDBC.
Definition at line 42 of file ImpalaJdbcClient.java.
Constructor & Destructor Documentation
com.cloudera.impala.testutil.ImpalaJdbcClient.ImpalaJdbcClient (String driverName, String connString) inline private
Definition at line 68 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.createClientUsingHiveJdbcDriver().
Member Function Documentation
void com.cloudera.impala.testutil.ImpalaJdbcClient.changeDatabase (String db_name) throws SQLException inline
Definition at line 122 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.validateConnection().
void com.cloudera.impala.testutil.ImpalaJdbcClient.close () throws SQLException inline
Definition at line 102 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.conn_, and com.cloudera.impala.testutil.ImpalaJdbcClient.stmt_.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.execQuery().
void com.cloudera.impala.testutil.ImpalaJdbcClient.connect () throws ClassNotFoundException, SQLException inline
Definition at line 87 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.conn_, com.cloudera.impala.testutil.ImpalaJdbcClient.connString_, com.cloudera.impala.testutil.ImpalaJdbcClient.driverName_, and com.cloudera.impala.testutil.ImpalaJdbcClient.stmt_.
static ImpalaJdbcClient com.cloudera.impala.testutil.ImpalaJdbcClient.createClientUsingHiveJdbcDriver () inline static
Definition at line 136 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.DEFAULT_CONNECTION_STRING, com.cloudera.impala.testutil.ImpalaJdbcClient.HIVE_SERVER2_DRIVER_NAME, com.cloudera.impala.testutil.ImpalaJdbcClient.ImpalaJdbcClient(), and com.cloudera.impala.testutil.ImpalaJdbcClient.NOSASL_AUTH_SPEC.
static ImpalaJdbcClient com.cloudera.impala.testutil.ImpalaJdbcClient.createClientUsingHiveJdbcDriver (String connString) inline static
Definition at line 141 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.HIVE_SERVER2_DRIVER_NAME, and com.cloudera.impala.testutil.ImpalaJdbcClient.ImpalaJdbcClient().
ResultSet com.cloudera.impala.testutil.ImpalaJdbcClient.execQuery (String query) throws SQLException inline
Definition at line 116 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.validateConnection().
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.main().
static void com.cloudera.impala.testutil.ImpalaJdbcClient.execQuery (ImpalaJdbcClient client, String queryString) throws SQLException, NumberFormatException inline static private
Executes one or more queries using the given ImpalaJdbcClient. Multiple queries should be seperated using semi-colons.
Exceptions
SQLException
Definition at line 245 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.close(), and com.cloudera.impala.testutil.ImpalaJdbcClient.formatColumnValue().
static String com.cloudera.impala.testutil.ImpalaJdbcClient.formatColumnValue (String colVal, String columnType) throws NumberFormatException inline static private
Definition at line 221 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.execQuery().
Connection com.cloudera.impala.testutil.ImpalaJdbcClient.getConnection () inline
Definition at line 128 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.conn_.
Statement com.cloudera.impala.testutil.ImpalaJdbcClient.getStatement () inline
Definition at line 132 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.stmt_.
static void com.cloudera.impala.testutil.ImpalaJdbcClient.main (String[] args) throws SQLException, ClassNotFoundException, ParseException inline static
Executes a query over JDBC. Multiple queries can be passed in if they are semi-colon separated.
Definition at line 294 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.execQuery(), and com.cloudera.impala.testutil.ImpalaJdbcClient.parseOptions().
static ClientExecOptions com.cloudera.impala.testutil.ImpalaJdbcClient.parseOptions (String[] args) throws ParseException inline static private
Parses command line options
Definition at line 169 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.NOSASL_AUTH_SPEC, and com.cloudera.impala.testutil.ImpalaJdbcClient.SASL_AUTH_SPEC.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.main().
void com.cloudera.impala.testutil.ImpalaJdbcClient.validateConnection () throws SQLException inline private
Definition at line 73 of file ImpalaJdbcClient.java.
References com.cloudera.impala.testutil.ImpalaJdbcClient.conn_, and com.cloudera.impala.testutil.ImpalaJdbcClient.stmt_.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.changeDatabase(), and com.cloudera.impala.testutil.ImpalaJdbcClient.execQuery().
Member Data Documentation
Connection com.cloudera.impala.testutil.ImpalaJdbcClient.conn_ private
Definition at line 65 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.close(), com.cloudera.impala.testutil.ImpalaJdbcClient.connect(), com.cloudera.impala.testutil.ImpalaJdbcClient.getConnection(), and com.cloudera.impala.testutil.ImpalaJdbcClient.validateConnection().
final String com.cloudera.impala.testutil.ImpalaJdbcClient.connString_ private
Definition at line 64 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.connect().
final String com.cloudera.impala.testutil.ImpalaJdbcClient.DEFAULT_CONNECTION_STRING static private
Initial value:
=
      "jdbc:hive2://localhost:21050/default"
Definition at line 60 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.createClientUsingHiveJdbcDriver().
final String com.cloudera.impala.testutil.ImpalaJdbcClient.driverName_ private
Definition at line 63 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.connect().
final String com.cloudera.impala.testutil.ImpalaJdbcClient.HIVE_SERVER2_DRIVER_NAME static private
Initial value:
=
      "org.apache.hive.jdbc.HiveDriver"
Definition at line 48 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.createClientUsingHiveJdbcDriver().
final Logger com.cloudera.impala.testutil.ImpalaJdbcClient.LOG = Logger.getLogger(ImpalaJdbcClient.class) static private
Definition at line 43 of file ImpalaJdbcClient.java.
final String com.cloudera.impala.testutil.ImpalaJdbcClient.NOSASL_AUTH_SPEC = ";auth=noSasl" static private
Definition at line 56 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.createClientUsingHiveJdbcDriver(), and com.cloudera.impala.testutil.ImpalaJdbcClient.parseOptions().
final String com.cloudera.impala.testutil.ImpalaJdbcClient.SASL_AUTH_SPEC = ";auth=none" static private
Definition at line 53 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.parseOptions().
Statement com.cloudera.impala.testutil.ImpalaJdbcClient.stmt_ private
Definition at line 66 of file ImpalaJdbcClient.java.
Referenced by com.cloudera.impala.testutil.ImpalaJdbcClient.close(), com.cloudera.impala.testutil.ImpalaJdbcClient.connect(), com.cloudera.impala.testutil.ImpalaJdbcClient.getStatement(), and com.cloudera.impala.testutil.ImpalaJdbcClient.validateConnection().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/testutil/ImpalaJdbcClient.java