Impala: com.cloudera.impala.catalog.Db Class Reference
com.cloudera.impala.catalog.Db Class Reference
Public Member Functions
Db (String name, Catalog catalog)
void setIsSystemDb (boolean b)
boolean isSystemDb ()
TDatabase toThrift ()
String getName ()
TCatalogObjectType getCatalogObjectType ()
void addTable (Table table)
List< String > getAllTableNames ()
boolean containsTable (String tableName)
Table getTable (String tblName)
Table removeTable (String tableName)
int numFunctions ()
boolean containsFunction (String name)
Function getFunction (Function desc, Function.CompareMode mode)
Function getFunction (String signatureString)
boolean addFunction (Function fn)
Function removeFunction (Function desc)
Function removeFunction (String signatureStr)
void addScalarBuiltin (String fnName, String symbol, boolean varArgs, Type retType, Type...args)
void addScalarBuiltin (String fnName, String symbol, String prepareFnSymbol, String closeFnSymbol, boolean varArgs, Type retType, Type...args)
void addBuiltin (Function fn)
List< Function > getFunctions (TFunctionCategory category, PatternMatcher fnPattern)
long getCatalogVersion ()
void setCatalogVersion (long newVersion)
Catalog getParentCatalog ()
boolean isLoaded ()
Static Public Member Functions
static Db fromTDatabase (TDatabase db, Catalog parentCatalog)
Protected Member Functions
HashMap< String, List< Function > > getAllFunctions ()
Private Attributes
final Catalog parentCatalog_
final TDatabase thriftDb_
long catalogVersion_ = Catalog.INITIAL_CATALOG_VERSION
final CatalogObjectCache< Table > tableCache_
final HashMap< String, List
< Function > > functions_
boolean isSystemDb_ = false
Static Private Attributes
static final Logger LOG = Logger.getLogger(Db.class)
Detailed Description
Internal representation of db-related metadata. Owned by Catalog instance. Not thread safe.
The static initialisation method loadDb is the only way to construct a Db object.
Tables are stored in a map from the table name to the table object. They may be loaded 'eagerly' at construction or 'lazily' on first reference. Tables are accessed via getTable which may trigger a metadata read in two cases:
if the table has never been loaded
if the table loading failed on the previous attempt
Definition at line 44 of file Db.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.Db.Db (String name, Catalog catalog) inline
Definition at line 63 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, com.cloudera.impala.catalog.Db.parentCatalog_, com.cloudera.impala.catalog.Db.tableCache_, and com.cloudera.impala.catalog.Db.thriftDb_.
Referenced by com.cloudera.impala.catalog.Db.fromTDatabase().
Member Function Documentation
void com.cloudera.impala.catalog.Db.addBuiltin (Function fn) inline
Adds a builtin to this database. The function must not already exist.
Definition at line 247 of file Db.java.
References com.cloudera.impala.catalog.Db.addFunction(), com.cloudera.impala.catalog.Db.getFunction(), com.cloudera.impala.catalog.Function.CompareMode.IS_IDENTICAL, and com.cloudera.impala.catalog.Db.isSystemDb().
Referenced by com.cloudera.impala.catalog.Db.addScalarBuiltin().
boolean com.cloudera.impala.catalog.Db.addFunction (Function fn) inline
See comment in Catalog.
Definition at line 179 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, com.cloudera.impala.catalog.Db.getFunction(), and com.cloudera.impala.catalog.Db.getName().
Referenced by com.cloudera.impala.catalog.Db.addBuiltin(), and com.cloudera.impala.catalog.CatalogServiceCatalog.addFunction().
void com.cloudera.impala.catalog.Db.addScalarBuiltin (String fnName, String symbol, boolean varArgs, Type retType, Type... args) inline
Add a builtin with the specified name and signatures to this db. This defaults to not using a Prepare/Close function.
Definition at line 228 of file Db.java.
void com.cloudera.impala.catalog.Db.addScalarBuiltin (String fnName, String symbol, String prepareFnSymbol, String closeFnSymbol, boolean varArgs, Type retType, Type... args) inline
Add a builtin with the specified name and signatures to this db.
Definition at line 236 of file Db.java.
References com.cloudera.impala.catalog.Db.addBuiltin(), com.cloudera.impala.catalog.ScalarFunction.createBuiltin(), and com.cloudera.impala.catalog.Db.isSystemDb().
void com.cloudera.impala.catalog.Db.addTable (Table table) inline
Adds a table to the table cache.
Definition at line 89 of file Db.java.
boolean com.cloudera.impala.catalog.Db.containsFunction (String name) inline
See comment in Catalog.
Definition at line 131 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, and impala.name.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze(), and com.cloudera.impala.analysis.FunctionCallExpr.analyze().
boolean com.cloudera.impala.catalog.Db.containsTable (String tableName) inline
Definition at line 100 of file Db.java.
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.invalidateTable().
static Db com.cloudera.impala.catalog.Db.fromTDatabase (TDatabase db, Catalog parentCatalog) inline static
Creates a Db object with no tables based on the given TDatabase thrift struct.
Definition at line 75 of file Db.java.
References com.cloudera.impala.catalog.Db.Db().
HashMap<String, List<Function> > com.cloudera.impala.catalog.Db.getAllFunctions () inline protected
Returns a map of functionNames to list of (overloaded) functions with that name. This is not thread safe so a higher level lock must be taken while iterating over the returned functions.
Definition at line 259 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
List<String> com.cloudera.impala.catalog.Db.getAllTableNames () inline
Gets all table names in the table cache.
Definition at line 96 of file Db.java.
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects(), and com.cloudera.impala.testutil.BlockIdGenerator.main().
TCatalogObjectType com.cloudera.impala.catalog.Db.getCatalogObjectType () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 82 of file Db.java.
long com.cloudera.impala.catalog.Db.getCatalogVersion () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 292 of file Db.java.
References com.cloudera.impala.catalog.Db.catalogVersion_.
Referenced by com.cloudera.impala.catalog.ImpaladCatalog.addDb(), com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects(), and com.cloudera.impala.catalog.ImpaladCatalog.removeDb().
Function com.cloudera.impala.catalog.Db.getFunction (Function desc, Function.CompareMode mode) inline
Definition at line 140 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
Referenced by com.cloudera.impala.catalog.Db.addBuiltin(), com.cloudera.impala.catalog.Db.addFunction(), and com.cloudera.impala.catalog.Db.removeFunction().
Function com.cloudera.impala.catalog.Db.getFunction (String signatureString) inline
Definition at line 165 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
List<Function> com.cloudera.impala.catalog.Db.getFunctions (TFunctionCategory category, PatternMatcher fnPattern) inline
Returns all functions that match 'fnPattern'.
Definition at line 266 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, and com.cloudera.impala.util.PatternMatcher.matches().
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects().
String com.cloudera.impala.catalog.Db.getName () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 81 of file Db.java.
Referenced by com.cloudera.impala.catalog.Catalog.addDb(), com.cloudera.impala.catalog.Db.addFunction(), com.cloudera.impala.catalog.AggregateFunction.createAnalyticBuiltin(), com.cloudera.impala.catalog.AggregateFunction.createBuiltin(), com.cloudera.impala.service.CatalogOpExecutor.dropDatabase(), com.cloudera.impala.service.MetadataOp.getDbsMetadata(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Table.getTableName(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.TableLoader.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.ImpaladCatalog.removeDb(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.catalog.IncompleteTable.toThrift(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
Catalog com.cloudera.impala.catalog.Db.getParentCatalog () inline
Definition at line 295 of file Db.java.
References com.cloudera.impala.catalog.Db.parentCatalog_.
Table com.cloudera.impala.catalog.Db.getTable (String tblName) inline
Returns the Table with the given name if present in the table cache or null if the table does not exist in the cache.
Definition at line 108 of file Db.java.
boolean com.cloudera.impala.catalog.Db.isLoaded () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 298 of file Db.java.
boolean com.cloudera.impala.catalog.Db.isSystemDb () inline
Definition at line 79 of file Db.java.
References com.cloudera.impala.catalog.Db.isSystemDb_.
Referenced by com.cloudera.impala.catalog.Db.addBuiltin(), com.cloudera.impala.catalog.Db.addScalarBuiltin(), and com.cloudera.impala.analysis.Analyzer.checkSystemDbAccess().
int com.cloudera.impala.catalog.Db.numFunctions () inline
Returns the number of functions in this database.
Definition at line 122 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
Referenced by com.cloudera.impala.analysis.DropDbStmt.analyze(), and com.cloudera.impala.service.CatalogOpExecutor.dropDatabase().
Function com.cloudera.impala.catalog.Db.removeFunction (Function desc) inline
See comment in Catalog.
Definition at line 198 of file Db.java.
References com.cloudera.impala.catalog.Function.functionName(), com.cloudera.impala.catalog.Db.functions_, and com.cloudera.impala.catalog.Db.getFunction().
Referenced by com.cloudera.impala.catalog.Db.removeFunction().
Function com.cloudera.impala.catalog.Db.removeFunction (String signatureStr) inline
Removes a Function with the matching signature string. Returns the removed Function if a Function was removed as a result of this call, null otherwise. TODO: Move away from using signature strings and instead use Function IDs.
Definition at line 216 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, com.cloudera.impala.catalog.Db.getFunction(), and com.cloudera.impala.catalog.Db.removeFunction().
Table com.cloudera.impala.catalog.Db.removeTable (String tableName) inline
Removes the table name and any cached metadata from the Table cache.
Definition at line 115 of file Db.java.
void com.cloudera.impala.catalog.Db.setCatalogVersion (long newVersion) inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 294 of file Db.java.
References com.cloudera.impala.catalog.Db.catalogVersion_.
void com.cloudera.impala.catalog.Db.setIsSystemDb (boolean b) inline
Definition at line 70 of file Db.java.
References com.cloudera.impala.catalog.Db.isSystemDb_.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.BuiltinsDb().
TDatabase com.cloudera.impala.catalog.Db.toThrift () inline
Definition at line 80 of file Db.java.
References com.cloudera.impala.catalog.Db.thriftDb_.
Member Data Documentation
long com.cloudera.impala.catalog.Db.catalogVersion_ = Catalog.INITIAL_CATALOG_VERSION private
Definition at line 48 of file Db.java.
Referenced by com.cloudera.impala.catalog.Db.getCatalogVersion(), and com.cloudera.impala.catalog.Db.setCatalogVersion().
final HashMap<String, List<Function> > com.cloudera.impala.catalog.Db.functions_ private
Definition at line 57 of file Db.java.
Referenced by com.cloudera.impala.catalog.Db.addFunction(), com.cloudera.impala.catalog.Db.containsFunction(), com.cloudera.impala.catalog.Db.Db(), com.cloudera.impala.catalog.Db.getAllFunctions(), com.cloudera.impala.catalog.Db.getFunction(), com.cloudera.impala.catalog.Db.getFunctions(), com.cloudera.impala.catalog.Db.numFunctions(), and com.cloudera.impala.catalog.Db.removeFunction().
boolean com.cloudera.impala.catalog.Db.isSystemDb_ = false private
Definition at line 61 of file Db.java.
Referenced by com.cloudera.impala.catalog.Db.isSystemDb(), and com.cloudera.impala.catalog.Db.setIsSystemDb().
final Logger com.cloudera.impala.catalog.Db.LOG = Logger.getLogger(Db.class) static private
Definition at line 45 of file Db.java.
final Catalog com.cloudera.impala.catalog.Db.parentCatalog_ private
Definition at line 46 of file Db.java.
Referenced by com.cloudera.impala.catalog.Db.Db(), and com.cloudera.impala.catalog.Db.getParentCatalog().
final CatalogObjectCache<Table> com.cloudera.impala.catalog.Db.tableCache_ private
Definition at line 51 of file Db.java.
Referenced by com.cloudera.impala.catalog.Db.Db().
final TDatabase com.cloudera.impala.catalog.Db.thriftDb_ private
Definition at line 47 of file Db.java.
Referenced by com.cloudera.impala.catalog.Db.Db(), and com.cloudera.impala.catalog.Db.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/Db.java