Impala: com.cloudera.impala.analysis.TableName Class Reference
com.cloudera.impala.analysis.TableName Class Reference
Public Member Functions
TableName (String db, String tbl)
String getDb ()
String getTbl ()
boolean isEmpty ()
void analyze () throws AnalysisException
boolean isFullyQualified ()
String toSql ()
String toString ()
List< String > toPath ()
TTableName toThrift ()
boolean equals (Object anObject)
int hashCode ()
Static Public Member Functions
static TableName fromThrift (TTableName tableName)
Private Attributes
final String db_
final String tbl_
Detailed Description
Represents a table/view name that optionally includes its database (a fully qualified table name). Analysis of this table name checks for validity of the database and table name according to the Metastore's policy (see). According to that definition, we can still use "invalid" table names for tables/views that are not stored in the Metastore, e.g., for Inline Views or WITH-clause views.
Definition at line 33 of file TableName.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.TableName.TableName (String db, String tbl) inline
Definition at line 37 of file TableName.java.
Referenced by com.cloudera.impala.analysis.TableName.fromThrift().
Member Function Documentation
void com.cloudera.impala.analysis.TableName.analyze () throws AnalysisException inline
Checks whether the db and table name meet the Metastore's requirements.
Definition at line 52 of file TableName.java.
References com.cloudera.impala.analysis.TableName.db_, and com.cloudera.impala.analysis.TableName.tbl_.
boolean com.cloudera.impala.analysis.TableName.equals (Object anObject) inline
Returns true of the table names are considered equals. To check for equality, a case-insensitive comparison of the database and table name is performed.
Definition at line 109 of file TableName.java.
References com.cloudera.impala.analysis.TableName.toString().
static TableName com.cloudera.impala.analysis.TableName.fromThrift (TTableName tableName) inline static
Definition at line 98 of file TableName.java.
References com.cloudera.impala.analysis.TableName.TableName().
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTable().
String com.cloudera.impala.analysis.TableName.getDb () inline
Definition at line 45 of file TableName.java.
References com.cloudera.impala.analysis.TableName.db_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.createTableLike(), com.cloudera.impala.service.CatalogOpExecutor.createView(), com.cloudera.impala.service.CatalogOpExecutor.dropTableOrView(), com.cloudera.impala.analysis.Analyzer.getTargetDbName(), com.cloudera.impala.analysis.AnalyzerTest.TblsAnalysisError(), com.cloudera.impala.analysis.AnalyzerTest.TblsAnalyzeOk(), com.cloudera.impala.analysis.ToSqlTest.TblsTestToSql(), com.cloudera.impala.analysis.DropTableOrViewStmt.toSql(), com.cloudera.impala.analysis.DropStatsStmt.toSql(), com.cloudera.impala.analysis.AlterViewStmt.toSql(), com.cloudera.impala.analysis.CreateViewStmt.toSql(), com.cloudera.impala.analysis.CreateTableLikeStmt.toSql(), com.cloudera.impala.analysis.ShowFilesStmt.toThrift(), com.cloudera.impala.analysis.ResetMetadataStmt.toThrift(), and com.cloudera.impala.service.CatalogOpExecutor.updateCatalog().
String com.cloudera.impala.analysis.TableName.getTbl () inline
Definition at line 46 of file TableName.java.
References com.cloudera.impala.analysis.TableName.tbl_.
Referenced by com.cloudera.impala.analysis.CreateViewStmt.analyze(), com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze(), com.cloudera.impala.analysis.PrivilegeSpec.analyze(), com.cloudera.impala.analysis.TableRef.analyze(), com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), com.cloudera.impala.analysis.CreateTableStmt.analyze(), com.cloudera.impala.service.CatalogOpExecutor.dropTableOrView(), com.cloudera.impala.analysis.Analyzer.getFqTableName(), and com.cloudera.impala.service.Frontend.loadTableData().
int com.cloudera.impala.analysis.TableName.hashCode () inline
Definition at line 117 of file TableName.java.
References com.cloudera.impala.analysis.TableName.toString().
boolean com.cloudera.impala.analysis.TableName.isEmpty () inline
Definition at line 47 of file TableName.java.
boolean com.cloudera.impala.analysis.TableName.isFullyQualified () inline
Returns true if this name has a non-empty database field and a non-empty table name.
Definition at line 68 of file TableName.java.
References com.cloudera.impala.analysis.TableName.db_, and com.cloudera.impala.analysis.TableName.tbl_.
Referenced by com.cloudera.impala.analysis.ShowCreateTableStmt.analyze(), com.cloudera.impala.analysis.DescribeStmt.analyze(), com.cloudera.impala.analysis.ShowFilesStmt.analyze(), com.cloudera.impala.analysis.Analyzer.getFqTableName(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
List<String> com.cloudera.impala.analysis.TableName.toPath () inline
Definition at line 91 of file TableName.java.
References com.cloudera.impala.analysis.TableName.db_, and com.cloudera.impala.analysis.TableName.tbl_.
String com.cloudera.impala.analysis.TableName.toSql () inline
Definition at line 72 of file TableName.java.
References com.cloudera.impala.analysis.TableName.db_, com.cloudera.impala.analysis.ToSqlUtils.getIdentSql(), and com.cloudera.impala.analysis.TableName.tbl_.
Referenced by com.cloudera.impala.analysis.InsertStmt.checkTypeCompatibility().
String com.cloudera.impala.analysis.TableName.toString () inline
Definition at line 83 of file TableName.java.
References com.cloudera.impala.analysis.TableName.db_, and com.cloudera.impala.analysis.TableName.tbl_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterView(), com.cloudera.impala.analysis.TableName.equals(), and com.cloudera.impala.analysis.TableName.hashCode().
TTableName com.cloudera.impala.analysis.TableName.toThrift () inline
Definition at line 102 of file TableName.java.
References com.cloudera.impala.analysis.TableName.db_, and com.cloudera.impala.analysis.TableName.tbl_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.updateCatalog().
Member Data Documentation
final String com.cloudera.impala.analysis.TableName.db_ private
Definition at line 34 of file TableName.java.
Referenced by com.cloudera.impala.analysis.TableName.analyze(), com.cloudera.impala.analysis.TableName.getDb(), com.cloudera.impala.analysis.TableName.isFullyQualified(), com.cloudera.impala.analysis.TableName.toPath(), com.cloudera.impala.analysis.TableName.toSql(), com.cloudera.impala.analysis.TableName.toString(), and com.cloudera.impala.analysis.TableName.toThrift().
final String com.cloudera.impala.analysis.TableName.tbl_ private
Definition at line 35 of file TableName.java.
Referenced by com.cloudera.impala.analysis.TableName.analyze(), com.cloudera.impala.analysis.TableName.getTbl(), com.cloudera.impala.analysis.TableName.isFullyQualified(), com.cloudera.impala.analysis.TableName.toPath(), com.cloudera.impala.analysis.TableName.toSql(), com.cloudera.impala.analysis.TableName.toString(), and com.cloudera.impala.analysis.TableName.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/TableName.java