Impala: com.cloudera.impala.testutil.TestFileParser Class Reference
com.cloudera.impala.testutil.TestFileParser Class Reference
Classes
enum Section
class TestCase
Public Member Functions
TestFileParser (String fileName)
List< TestCase > getTestCases ()
String getTestFileName ()
boolean hasSetupSection ()
void parseFile ()
void parseFile (String table)
Private Member Functions
void open (String table)
TestCase parseOneTestCase ()
void close ()
Private Attributes
final List< TestCase > testCases = Lists.newArrayList()
int lineNum = 0
final String fileName
BufferedReader reader
Scanner scanner
boolean hasSetupSection = false
Static Private Attributes
static final Logger LOG = Logger.getLogger(TestCase.class)
static final ArrayList< Section > defaultSectionOrder
Detailed Description
Parses a file containing one or more test case descriptions into a list of TestCase objects. A test file has the following format:
<QUERY string>=""> -— <SECTION NAME 1> <EXPECTED CONTENTS 1> -— <SECTION NAME 2> <EXPECTED CONTENTS 2> -— <SECTION NAME 3>
<EXPECTED CONTENTS 3>
<QUERY string>=""> -— <SECTION NAME 1> <EXPECTED CONTENTS 1> -— <SECTION NAME 2> <EXPECTED CONTENTS 2> -— <SECTION NAME 3>
<EXPECTED CONTENTS 3>
Acceptable section names are ONLY those contained in TestFileParser.Section.
Lines beginning with # or // are comments. Clients can retrieve sections with or without these lines included.
Note that <QUERY string>=""> and <EXPECTED contents>=""> sections can consist of multiple lines.
Definition at line 51 of file TestFileParser.java.
Constructor & Destructor Documentation
com.cloudera.impala.testutil.TestFileParser.TestFileParser (String fileName) inline
Definition at line 201 of file TestFileParser.java.
References com.cloudera.impala.testutil.TestFileParser.fileName.
Member Function Documentation
void com.cloudera.impala.testutil.TestFileParser.close () inline private
Definition at line 318 of file TestFileParser.java.
References com.cloudera.impala.testutil.TestFileParser.reader, and com.cloudera.impala.testutil.TestFileParser.scanner.
Referenced by com.cloudera.impala.testutil.TestFileParser.parseFile().
List<TestCase> com.cloudera.impala.testutil.TestFileParser.getTestCases () inline
Definition at line 205 of file TestFileParser.java.
References com.cloudera.impala.testutil.TestFileParser.testCases.
Referenced by com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
String com.cloudera.impala.testutil.TestFileParser.getTestFileName () inline
Definition at line 209 of file TestFileParser.java.
References com.cloudera.impala.testutil.TestFileParser.fileName.
boolean com.cloudera.impala.testutil.TestFileParser.hasSetupSection () inline
Definition at line 213 of file TestFileParser.java.
Referenced by com.cloudera.impala.testutil.TestFileParser.parseOneTestCase().
void com.cloudera.impala.testutil.TestFileParser.open (String table) inline private
Initializes the scanner and the input stream corresponding to the test file name
Definition at line 220 of file TestFileParser.java.
References com.cloudera.impala.testutil.TestFileParser.fileName, com.cloudera.impala.testutil.TestFileParser.reader, and com.cloudera.impala.testutil.TestFileParser.scanner.
Referenced by com.cloudera.impala.testutil.TestFileParser.parseFile().
void com.cloudera.impala.testutil.TestFileParser.parseFile () inline
Parses a test file in its entirety and constructs a list of TestCases.
Definition at line 302 of file TestFileParser.java.
void com.cloudera.impala.testutil.TestFileParser.parseFile (String table) inline
Definition at line 306 of file TestFileParser.java.
References com.cloudera.impala.testutil.TestFileParser.close(), com.cloudera.impala.testutil.TestFileParser.open(), com.cloudera.impala.testutil.TestFileParser.parseOneTestCase(), and com.cloudera.impala.testutil.TestFileParser.scanner.
TestCase com.cloudera.impala.testutil.TestFileParser.parseOneTestCase () inline private
Consumes input from the test file until a single test case has been parsed.
Definition at line 235 of file TestFileParser.java.
References com.cloudera.impala.testutil.TestFileParser.defaultSectionOrder, com.cloudera.impala.testutil.TestFileParser.hasSetupSection(), com.cloudera.impala.testutil.TestFileParser.lineNum, com.cloudera.impala.testutil.TestFileParser.Section.QUERY, com.cloudera.impala.testutil.TestFileParser.scanner, and com.cloudera.impala.testutil.TestFileParser.Section.SETUP.
Referenced by com.cloudera.impala.testutil.TestFileParser.parseFile().
Member Data Documentation
final ArrayList<Section> com.cloudera.impala.testutil.TestFileParser.defaultSectionOrder static private
Initial value:
=
    Lists.newArrayList(Section.QUERY, Section.TYPES, Section.RESULTS)
For backwards compatibility, if no title is found this is the order in which sections are labeled.
Definition at line 198 of file TestFileParser.java.
Referenced by com.cloudera.impala.testutil.TestFileParser.parseOneTestCase().
final String com.cloudera.impala.testutil.TestFileParser.fileName private
Definition at line 189 of file TestFileParser.java.
Referenced by com.cloudera.impala.testutil.TestFileParser.getTestFileName(), com.cloudera.impala.testutil.TestFileParser.open(), and com.cloudera.impala.testutil.TestFileParser.TestFileParser().
boolean com.cloudera.impala.testutil.TestFileParser.hasSetupSection = false private
Definition at line 192 of file TestFileParser.java.
int com.cloudera.impala.testutil.TestFileParser.lineNum = 0 private
Definition at line 188 of file TestFileParser.java.
Referenced by com.cloudera.impala.testutil.TestFileParser.parseOneTestCase(), and com.cloudera.impala.testutil.TestFileParser.TestCase.TestCase().
final Logger com.cloudera.impala.testutil.TestFileParser.LOG = Logger.getLogger(TestCase.class) static private
Definition at line 52 of file TestFileParser.java.
BufferedReader com.cloudera.impala.testutil.TestFileParser.reader private
Definition at line 190 of file TestFileParser.java.
Referenced by com.cloudera.impala.testutil.TestFileParser.close(), and com.cloudera.impala.testutil.TestFileParser.open().
Scanner com.cloudera.impala.testutil.TestFileParser.scanner private
Definition at line 191 of file TestFileParser.java.
Referenced by com.cloudera.impala.testutil.TestFileParser.close(), com.cloudera.impala.testutil.TestFileParser.open(), com.cloudera.impala.testutil.TestFileParser.parseFile(), and com.cloudera.impala.testutil.TestFileParser.parseOneTestCase().
final List<TestCase> com.cloudera.impala.testutil.TestFileParser.testCases = Lists.newArrayList() private
Definition at line 186 of file TestFileParser.java.
Referenced by com.cloudera.impala.testutil.TestFileParser.getTestCases().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/testutil/TestFileParser.java