Impala: com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt Class Reference
com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt Class Reference
Public Member Functions
AlterTableAddReplaceColsStmt (TableName tableName, List< ColumnDef > columnDefs, boolean replaceExistingCols)
List< ColumnDef > getColumnDescs ()
boolean getReplaceExistingCols ()
TAlterTableParams toThrift ()
void analyze (Analyzer analyzer) throws AnalysisException
String getTbl ()
String getDb ()
String toSql ()
void setIsExplain ()
boolean isExplain ()
Protected Member Functions
Table getTargetTable ()
Protected Attributes
final TableName tableName_
Table table_
boolean isExplain_ = false
Private Attributes
final List< ColumnDef > columnDefs_
final boolean replaceExistingCols_
Detailed Description
Represents an ALTER TABLE ADD|REPLACE COLUMNS (colDef1, colDef2, ...) statement.
Definition at line 36 of file AlterTableAddReplaceColsStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.AlterTableAddReplaceColsStmt (TableName tableName, List< ColumnDef > columnDefs, boolean replaceExistingCols) inline
Definition at line 40 of file AlterTableAddReplaceColsStmt.java.
References com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.columnDefs_, and com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.replaceExistingCols_.
Member Function Documentation
void com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 69 of file AlterTableAddReplaceColsStmt.java.
References com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.columnDefs_, com.cloudera.impala.analysis.AlterTableStmt.getTargetTable(), and com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.replaceExistingCols_.
List<ColumnDef> com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.getColumnDescs () inline
Definition at line 48 of file AlterTableAddReplaceColsStmt.java.
References com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.columnDefs_.
Referenced by com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.toThrift().
String com.cloudera.impala.analysis.AlterTableStmt.getDb () inline inherited
Can only be called after analysis, returns the parent database name of the target table for this ALTER TABLE statement.
Definition at line 47 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
boolean com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.getReplaceExistingCols () inline
Definition at line 51 of file AlterTableAddReplaceColsStmt.java.
References com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.replaceExistingCols_.
Table com.cloudera.impala.analysis.AlterTableStmt.getTargetTable () inline protected inherited
Can only be called after analysis, returns the Table object of the target of this ALTER TABLE statement.
Definition at line 55 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.table_.
Referenced by com.cloudera.impala.analysis.AlterTableSetStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetCachedStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetLocationStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getDb().
String com.cloudera.impala.analysis.AlterTableStmt.getTbl () inline inherited
Definition at line 41 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toSql(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.StatementBase.toSql () inline inherited
Print SQL syntax corresponding to this node.
See Also
com.cloudera.impala.parser.ParseNode::toSql()
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 41 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.CreateUdaStmt.analyze(), and com.cloudera.impala.analysis.QueryStmt.createSortInfo().
TAlterTableParams com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.toThrift () inline
Definition at line 56 of file AlterTableAddReplaceColsStmt.java.
References com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.getColumnDescs(), and com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.replaceExistingCols_.
Member Data Documentation
final List<ColumnDef> com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.columnDefs_ private
Definition at line 37 of file AlterTableAddReplaceColsStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.AlterTableAddReplaceColsStmt(), com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.analyze(), and com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.getColumnDescs().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final boolean com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.replaceExistingCols_ private
Definition at line 38 of file AlterTableAddReplaceColsStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.AlterTableAddReplaceColsStmt(), com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.getReplaceExistingCols(), and com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.toThrift().
Table com.cloudera.impala.analysis.AlterTableStmt.table_ protected inherited
Definition at line 33 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
final TableName com.cloudera.impala.analysis.AlterTableStmt.tableName_ protected inherited
Definition at line 30 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), and com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AlterTableAddReplaceColsStmt.java