Impala: impala::CrossJoinNode Class Reference
impala::CrossJoinNode Class Reference
#include <cross-join-node.h>
Public Member Functions
CrossJoinNode (ObjectPool *pool, const TPlanNode &tnode, const DescriptorTbl &descs)
virtual Status Prepare (RuntimeState *state)
virtual Status GetNext (RuntimeState *state, RowBatch *row_batch, bool *eos)
virtual Status Reset (RuntimeState *state)
virtual void Close (RuntimeState *state)
virtual Status Init (const TPlanNode &tnode)
virtual Status Open (RuntimeState *state)
std::string DebugString () const
Returns a string representation in DFS order of the plan rooted at this.
void CollectNodes (TPlanNodeType::type node_type, std::vector< ExecNode * > *nodes)
void CollectScanNodes (std::vector< ExecNode * > *nodes)
Collect all scan node types.
const std::vector< ExprContext * > & conjunct_ctxs () const
int id () const
TPlanNodeType::type type () const
const RowDescriptor & row_desc () const
int64_t rows_returned () const
int64_t limit () const
bool ReachedLimit ()
RuntimeProfile * runtime_profile ()
MemTracker * mem_tracker ()
MemTracker * expr_mem_tracker ()
Static Public Member Functions
static Status CreateTree (ObjectPool *pool, const TPlan &plan, const DescriptorTbl &descs, ExecNode **root)
static void SetDebugOptions (int node_id, TExecNodePhase::type phase, TDebugAction::type action, ExecNode *tree)
Set debug action for node with given id in 'tree'.
static bool EvalConjuncts (ExprContext *const *ctxs, int num_ctxs, TupleRow *row)
static llvm::Function * CodegenEvalConjuncts (RuntimeState *state, const std::vector< ExprContext * > &conjunct_ctxs, const char *name="EvalConjuncts")
static int GetNodeIdFromProfile (RuntimeProfile *p)
Extract node id from p->name().
Static Public Attributes
static const char * LLVM_CLASS_NAME = "class.impala::BlockingJoinNode"
static const std::string ROW_THROUGHPUT_COUNTER = "RowsReturnedRate"
Names of counters shared by all exec nodes.
Protected Member Functions
virtual Status InitGetNext (TupleRow *first_left_row)
virtual Status ConstructBuildSide (RuntimeState *state)
virtual void AddToDebugString (int indentation_level, std::stringstream *out) const
virtual void DebugString (int indentation_level, std::stringstream *out) const
Subclasses should not override, use AddToDebugString() to add to the result.
std::string GetLeftChildRowString (TupleRow *row)
void CreateOutputRow (TupleRow *out_row, TupleRow *probe_row, TupleRow *build_row)
ExecNode * child (int i)
bool is_closed ()
virtual bool IsScanNode () const
void InitRuntimeProfile (const std::string &name)
Status ExecDebugAction (TExecNodePhase::type phase, RuntimeState *state)
void AddRuntimeExecOption (const std::string &option)
Appends option to 'runtime_exec_options_'.
virtual Status QueryMaintenance (RuntimeState *state)
void AddExprCtxToFree (ExprContext *ctx)
void AddExprCtxsToFree (const std::vector< ExprContext * > &ctxs)
void AddExprCtxsToFree (const SortExecExprs &sort_exec_exprs)
Static Protected Member Functions
static Status CreateNode (ObjectPool *pool, const TPlanNode &tnode, const DescriptorTbl &descs, ExecNode **node)
Create a single exec node derived from thrift node; place exec node in 'pool'.
static Status CreateTreeHelper (ObjectPool *pool, const std::vector< TPlanNode > &tnodes, const DescriptorTbl &descs, ExecNode *parent, int *node_idx, ExecNode **root)
Protected Attributes
const std::string node_name_
TJoinOp::type join_op_
bool eos_
boost::scoped_ptr< MemPool > build_pool_
boost::scoped_ptr< RowBatch > probe_batch_
bool probe_side_eos_
int probe_batch_pos_
TupleRow * current_probe_row_
bool matched_probe_
int probe_tuple_row_size_
int build_tuple_row_size_
TupleRow * semi_join_staging_row_
bool can_add_probe_filters_
RuntimeProfile::Counter * build_timer_
RuntimeProfile::Counter * probe_timer_
RuntimeProfile::Counter * build_row_counter_
RuntimeProfile::Counter * probe_row_counter_
int id_
TPlanNodeType::type type_
ObjectPool * pool_
std::vector< ExprContext * > conjunct_ctxs_
std::vector< ExecNode * > children_
RowDescriptor row_descriptor_
TExecNodePhase::type debug_phase_
TDebugAction::type debug_action_
int64_t limit_
int64_t num_rows_returned_
boost::scoped_ptr< RuntimeProfile > runtime_profile_
RuntimeProfile::Counter * rows_returned_counter_
RuntimeProfile::Counter * rows_returned_rate_
boost::scoped_ptr< MemTracker > mem_tracker_
Account for peak memory used by this node.
boost::scoped_ptr< MemTracker > expr_mem_tracker_
MemTracker that should be used for ExprContexts.
boost::mutex exec_options_lock_
std::string runtime_exec_options_
Private Member Functions
int ProcessLeftChildBatch (RowBatch *output_batch, RowBatch *batch, int max_added_rows)
std::string BuildListDebugString ()
Private Attributes
boost::scoped_ptr< ObjectPool > build_batch_pool_
Object pool for build RowBatches, stores all BuildBatches in build_rows_.
RowBatchList build_batches_
List of build batches, constructed in Prepare()
RowBatchList::TupleRowIterator current_build_row_
Detailed Description
Node for cross joins. Iterates over the left child rows and then the right child rows and, for each combination, writes the output row if the conjuncts are satisfied. The build batches are kept in a list that is fully constructed from the right child in ConstructBuildSide() (called by BlockingJoinNode::Open()) while rows are fetched from the left child as necessary in GetNext().
Definition at line 44 of file cross-join-node.h.
Constructor & Destructor Documentation
CrossJoinNode::CrossJoinNode (ObjectPool * pool, const TPlanNode & tnode, const DescriptorTbl & descs)
Definition at line 33 of file cross-join-node.cc.
Member Function Documentation
void impala::ExecNode::AddExprCtxsToFree (const std::vector< ExprContext * > & ctxs) protected inherited
Referenced by impala::ExecNode::AddExprCtxsToFree(), impala::UnionNode::Prepare(), impala::SortNode::Prepare(), impala::TopNNode::Prepare(), impala::ExchangeNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), and impala::HdfsScanNode::Prepare().
void impala::ExecNode::AddExprCtxsToFree (const SortExecExprs & sort_exec_exprs) protected inherited
Definition at line 410 of file exec-node.cc.
References impala::ExecNode::AddExprCtxsToFree(), impala::SortExecExprs::lhs_ordering_expr_ctxs(), impala::SortExecExprs::rhs_ordering_expr_ctxs(), and impala::SortExecExprs::sort_tuple_slot_expr_ctxs().
void impala::ExecNode::AddExprCtxToFree (ExprContext * ctx) inline protected inherited
Add an ExprContext to have its local allocations freed by QueryMaintenance(). Exprs that are evaluated in the main execution thread should be added. Exprs evaluated in a separate thread are generally not safe to add, since a local allocation may be freed while it's being used. Rather than using this mechanism, threads should call FreeLocalAllocations() on local ExprContexts periodically.
Definition at line 276 of file exec-node.h.
References impala::ExecNode::expr_ctxs_to_free_.
Referenced by impala::AnalyticEvalNode::Prepare().
void impala::ExecNode::AddRuntimeExecOption (const std::string & option) protected inherited
Appends option to 'runtime_exec_options_'.
Definition at line 188 of file exec-node.cc.
References impala::RuntimeProfile::AddInfoString(), impala::ExecNode::exec_options_lock_, impala::ExecNode::runtime_exec_options_, and impala::ExecNode::runtime_profile().
Referenced by impala::PartitionedHashJoinNode::AttachProbeFilters(), impala::HashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::Open(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), and impala::HdfsScanNode::StopAndFinalizeCounters().
virtual void impala::BlockingJoinNode::AddToDebugString (int indentation_level, std::stringstream * out) const inline protected virtual inherited
Gives subclasses an opportunity to add debug output to the debug string printed by DebugString().
Reimplemented in impala::PartitionedHashJoinNode, and impala::HashJoinNode.
Definition at line 117 of file blocking-join-node.h.
Referenced by impala::BlockingJoinNode::DebugString().
string CrossJoinNode::BuildListDebugString () private
Returns a debug string for build_rows_. This is used for debugging during the build list construction and before doing the join.
Definition at line 133 of file cross-join-node.cc.
References build_batches_, impala::ExecNode::child(), impala::RowBatchList::DebugString(), and impala::ExecNode::row_desc().
Referenced by ConstructBuildSide().
ExecNode* impala::ExecNode::child (int i) inline protected inherited
Definition at line 241 of file exec-node.h.
References impala::ExecNode::children_.
Referenced by BuildListDebugString(), impala::BlockingJoinNode::BuildSideThread(), impala::HashJoinNode::CodegenCreateOutputRow(), impala::PartitionedHashJoinNode::CodegenCreateOutputRow(), ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::PartitionedHashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::GetLeftChildRowString(), impala::SelectNode::GetNext(), impala::UnionNode::GetNext(), GetNext(), impala::HashJoinNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::PartitionedAggregationNode::Partition::InitStreams(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::SelectNode::Open(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::SelectNode::Prepare(), impala::SortNode::Prepare(), impala::UnionNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::AnalyticEvalNode::ProcessChildBatches(), and impala::SortNode::SortInput().
void CrossJoinNode::Close (RuntimeState * state) virtual
Subclasses should close any other structures and then call BlockingJoinNode::Close().
Reimplemented from impala::BlockingJoinNode.
Definition at line 52 of file cross-join-node.cc.
References build_batch_pool_, build_batches_, impala::BlockingJoinNode::Close(), impala::ExecNode::is_closed(), and impala::RowBatchList::Reset().
Function * impala::ExecNode::CodegenEvalConjuncts (RuntimeState * state, const std::vector< ExprContext * > & conjunct_ctxs, const char * name = "EvalConjuncts") static inherited
Returns a codegen'd version of EvalConjuncts(), or NULL if the function couldn't be codegen'd. The codegen'd version uses inlined, codegen'd GetBooleanVal() functions.
Definition at line 452 of file exec-node.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::LlvmCodeGen::context(), impala::CodegenAnyVal::CreateCallWrapped(), impala::LlvmCodeGen::false_value(), impala::LlvmCodeGen::FinalizeFunction(), impala::RuntimeState::GetCodegen(), impala::Status::GetDetail(), impala::CodegenAnyVal::GetIsNull(), impala::LlvmCodeGen::GetType(), impala::CodegenAnyVal::GetVal(), impala::TupleRow::LLVM_CLASS_NAME, impala::ExprContext::LLVM_CLASS_NAME, impala::Status::ok(), impala::LlvmCodeGen::true_value(), impala::ExecNode::type(), impala::TYPE_BOOLEAN, impala::TYPE_INT, and VLOG_QUERY.
Referenced by impala::HdfsAvroScanner::CodegenDecodeAvroData(), impala::HashJoinNode::CodegenProcessProbeBatch(), and impala::PartitionedHashJoinNode::CodegenProcessProbeBatch().
void impala::ExecNode::CollectNodes (TPlanNodeType::type node_type, std::vector< ExecNode * > * nodes) inherited
Collect all nodes of given 'node_type' that are part of this subtree, and return in 'nodes'.
Definition at line 359 of file exec-node.cc.
References impala::ExecNode::children_, and impala::ExecNode::type_.
Referenced by impala::ExecNode::CollectScanNodes(), and impala::PlanFragmentExecutor::Prepare().
void impala::ExecNode::CollectScanNodes (std::vector< ExecNode * > * nodes) inherited
Collect all scan node types.
Definition at line 366 of file exec-node.cc.
References impala::ExecNode::CollectNodes().
Referenced by impala::PlanFragmentExecutor::Prepare().
const std::vector<ExprContext*>& impala::ExecNode::conjunct_ctxs () const inline inherited
Definition at line 152 of file exec-node.h.
References impala::ExecNode::conjunct_ctxs_.
Referenced by impala::HdfsScanNode::ComputeSlotMaterializationOrder(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HashJoinNode::GetNext(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
Status CrossJoinNode::ConstructBuildSide (RuntimeState * state) protected virtual
We parallelize building the build-side with Open'ing the left child. If, for example, the left child is another join node, it can start to build its own build-side at the same time.
Implements impala::BlockingJoinNode.
Definition at line 59 of file cross-join-node.cc.
References impala::RowBatchList::AddRowBatch(), impala::RuntimeState::batch_size(), build_batch_pool_, build_batches_, impala::BlockingJoinNode::build_row_counter_, impala::BlockingJoinNode::build_timer_, BuildListDebugString(), impala::ExecNode::child(), COUNTER_SET, GetNext(), impala::ExecNode::mem_tracker(), impala::RowBatch::num_io_buffers(), impala::Status::OK, impala::BlockingJoinNode::Open(), impala::ExecNode::QueryMaintenance(), RETURN_IF_CANCELLED, RETURN_IF_ERROR, impala::ExecNode::row_desc(), SCOPED_TIMER, impala::RowBatchList::total_num_rows(), and VLOG_ROW.
Status impala::ExecNode::CreateNode (ObjectPool * pool, const TPlanNode & tnode, const DescriptorTbl & descs, ExecNode ** node) static protected inherited
Create a single exec node derived from thrift node; place exec node in 'pool'.
Definition at line 260 of file exec-node.cc.
References impala::ObjectPool::Add(), impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::ExecNode::CreateTreeHelper().
void BlockingJoinNode::CreateOutputRow (TupleRow * out_row, TupleRow * probe_row, TupleRow * build_row) protected inherited
Write combined row, consisting of the left child's 'probe_row' and right child's 'build_row' to 'out_row'. This is replaced by codegen.
Definition at line 240 of file blocking-join-node.cc.
References impala::BlockingJoinNode::build_tuple_row_size_, and impala::BlockingJoinNode::probe_tuple_row_size_.
Referenced by impala::PartitionedHashJoinNode::EvaluateNullProbe(), impala::HashJoinNode::GetNext(), impala::PartitionedHashJoinNode::OutputNullAwareProbeRows(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
Status impala::ExecNode::CreateTree (ObjectPool * pool, const TPlan & plan, const DescriptorTbl & descs, ExecNode ** root) static inherited
Creates exec node tree from list of nodes contained in plan via depth-first traversal. All nodes are placed in pool. Returns error if 'plan' is corrupted, otherwise success.
Definition at line 199 of file exec-node.cc.
References impala::ExecNode::CreateTreeHelper(), impala::Status::OK, and impala::Status::ok().
Referenced by impala::PlanFragmentExecutor::Prepare().
Status impala::ExecNode::CreateTreeHelper (ObjectPool * pool, const std::vector< TPlanNode > & tnodes, const DescriptorTbl & descs, ExecNode * parent, int * node_idx, ExecNode ** root) static protected inherited
Definition at line 218 of file exec-node.cc.
References impala::RuntimeProfile::AddChild(), impala::ExecNode::children_, impala::ExecNode::CreateNode(), impala::Status::OK, RETURN_IF_ERROR, and impala::ExecNode::runtime_profile().
Referenced by impala::ExecNode::CreateTree().
void BlockingJoinNode::DebugString (int indentation_level, std::stringstream * out) const protected virtual inherited
Subclasses should not override, use AddToDebugString() to add to the result.
Reimplemented from impala::ExecNode.
Definition at line 212 of file blocking-join-node.cc.
References impala::BlockingJoinNode::AddToDebugString(), impala::ExecNode::DebugString(), impala::BlockingJoinNode::eos_, impala::BlockingJoinNode::node_name_, and impala::BlockingJoinNode::probe_batch_pos_.
string impala::ExecNode::DebugString () const inherited
Returns a string representation in DFS order of the plan rooted at this.
Definition at line 345 of file exec-node.cc.
Referenced by impala::SortNode::DebugString(), impala::TopNNode::DebugString(), impala::ExchangeNode::DebugString(), impala::AggregationNode::DebugString(), impala::AnalyticEvalNode::DebugString(), impala::PartitionedAggregationNode::DebugString(), impala::BlockingJoinNode::DebugString(), and impala::PlanFragmentExecutor::Prepare().
bool impala::ExecNode::EvalConjuncts (ExprContext *const * ctxs, int num_ctxs, TupleRow * row) static inherited
Evaluate ExprContexts over row. Returns true if all exprs return true. TODO: This doesn't use the vector<Expr*> signature because I haven't figured out how to deal with declaring a templated std:vector type in IR
Definition at line 393 of file exec-node.cc.
References impala::ExprContext::GetBooleanVal(), impala_udf::AnyVal::is_null, and impala_udf::BooleanVal::val.
Referenced by impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HdfsScanner::EvalConjuncts(), EvalOtherJoinConjuncts(), EvalOtherJoinConjuncts2(), impala::PartitionedHashJoinNode::EvaluateNullProbe(), impala::HBaseScanNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::PartitionedHashJoinNode::OutputNullAwareProbeRows(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
Status impala::ExecNode::ExecDebugAction (TExecNodePhase::type phase, RuntimeState * state) protected inherited
Executes debug_action_ if phase matches debug_phase_. 'phase' must not be INVALID.
Definition at line 378 of file exec-node.cc.
References impala::Status::CANCELLED, impala::ExecNode::debug_action_, impala::ExecNode::debug_phase_, impala::RuntimeState::is_cancelled(), and impala::Status::OK.
Referenced by impala::SelectNode::GetNext(), impala::SortNode::GetNext(), impala::UnionNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExecNode::Open(), and impala::ExecNode::Prepare().
MemTracker* impala::ExecNode::expr_mem_tracker () inline inherited
Definition at line 163 of file exec-node.h.
References impala::ExecNode::expr_mem_tracker_.
Referenced by impala::PartitionedAggregationNode::Partition::InitStreams(), impala::SortNode::Prepare(), impala::UnionNode::Prepare(), impala::TopNNode::Prepare(), impala::ExchangeNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), and impala::HdfsScanNode::Prepare().
string BlockingJoinNode::GetLeftChildRowString (TupleRow * row) protected inherited
Returns a debug string for the left child's 'row'. They have tuple ptrs that are uninitialized; the left child only populates the tuple ptrs it is responsible for. This function outputs just the row values and leaves the build side values as NULL. This is only used for debugging and outputting the left child rows before doing the join.
Definition at line 222 of file blocking-join-node.cc.
References impala::ExecNode::child(), impala::TupleRow::GetTuple(), impala::PrintTuple(), impala::ExecNode::row_desc(), and impala::RowDescriptor::tuple_descriptors().
Referenced by impala::HashJoinNode::GetNext().
Status CrossJoinNode::GetNext (RuntimeState * state, RowBatch * row_batch, bool * eos) virtual
Retrieves rows and returns them via row_batch. Sets eos to true if subsequent calls will not retrieve any more rows. Data referenced by any tuples returned in row_batch must not be overwritten by the callee until Close() is called. The memory holding that data can be returned via row_batch's tuple_data_pool (in which case it may be deleted by the caller) or held on to by the callee. The row_batch, including its tuple_data_pool, will be destroyed by the caller at some point prior to the final Close() call. In other words, if the memory holding the tuple data will be referenced by the callee in subsequent GetNext() calls, it must not be attached to the row_batch's tuple_data_pool. Caller must not be holding any io buffers. This will cause deadlock. TODO: AggregationNode and HashJoinNode cannot be "re-opened" yet.
Implements impala::ExecNode.
Definition at line 85 of file cross-join-node.cc.
References impala::RowBatch::AtCapacity(), impala::RowBatchList::TupleRowIterator::AtEnd(), impala::RowBatch::capacity(), impala::ExecNode::child(), COUNTER_ADD, COUNTER_SET, current_build_row_, impala::BlockingJoinNode::eos_, impala::ExecNode::ExecDebugAction(), impala::ExecNode::limit(), impala::RowBatch::num_rows(), impala::ExecNode::num_rows_returned_, impala::Status::OK, impala::BlockingJoinNode::probe_batch_, impala::BlockingJoinNode::probe_batch_pos_, impala::BlockingJoinNode::probe_row_counter_, impala::BlockingJoinNode::probe_side_eos_, impala::BlockingJoinNode::probe_timer_, ProcessLeftChildBatch(), impala::ExecNode::QueryMaintenance(), impala::ExecNode::ReachedLimit(), RETURN_IF_CANCELLED, RETURN_IF_ERROR, impala::ExecNode::rows_returned(), impala::ExecNode::rows_returned_counter_, impala::ExecNode::runtime_profile_, SCOPED_TIMER, impala::ScopedTimer< T >::Start(), and impala::ScopedTimer< T >::Stop().
Referenced by ConstructBuildSide().
int impala::ExecNode::GetNodeIdFromProfile (RuntimeProfile * p) static inherited
Extract node id from p->name().
Definition at line 62 of file exec-node.cc.
References impala::RuntimeProfile::metadata().
int impala::ExecNode::id () const inline inherited
Definition at line 154 of file exec-node.h.
References impala::ExecNode::id_.
Referenced by impala::AnalyticEvalNode::AddResultTuple(), impala::AnalyticEvalNode::AddRow(), impala::AnalyticEvalNode::AnalyticEvalNode(), impala::AnalyticEvalNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::HdfsScanner::InitializeWriteTuplesFn(), impala::HdfsAvroScanner::InitNewRange(), impala::AnalyticEvalNode::InitNextPartition(), impala::PartitionedAggregationNode::MoveHashPartitions(), impala::PartitionedHashJoinNode::NodeDebugString(), impala::AnalyticEvalNode::Open(), impala::HdfsScanNode::Open(), impala::PlanFragmentExecutor::Prepare(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::AnalyticEvalNode::ProcessChildBatch(), impala::HdfsScanNode::ScannerThread(), impala::AnalyticEvalNode::TryAddRemainingResults(), impala::AnalyticEvalNode::TryAddResultTupleForCurrRow(), impala::AnalyticEvalNode::TryAddResultTupleForPrevRow(), and impala::AnalyticEvalNode::TryRemoveRowsBeforeWindow().
Status BlockingJoinNode::Init (const TPlanNode & tnode) virtual inherited
Subclasses should call BlockingJoinNode::Init() and then perform any other Init() work, e.g. creating expr trees.
Reimplemented from impala::ExecNode.
Reimplemented in impala::PartitionedHashJoinNode, and impala::HashJoinNode.
Definition at line 45 of file blocking-join-node.cc.
References impala::ExecNode::Init(), impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::HashJoinNode::Init(), and impala::PartitionedHashJoinNode::Init().
Status CrossJoinNode::InitGetNext (TupleRow * first_left_child_row) protected virtual
Init the build-side state for a new left child row (e.g. hash table iterator or list iterator) given the first row. Used in Open() to prepare for GetNext(). A NULL ptr for first_left_child_row indicates the left child eos.
Implements impala::BlockingJoinNode.
Definition at line 80 of file cross-join-node.cc.
References build_batches_, current_build_row_, impala::RowBatchList::Iterator(), and impala::Status::OK.
void impala::ExecNode::InitRuntimeProfile (const std::string & name) protected inherited
Definition at line 371 of file exec-node.cc.
References impala::ExecNode::id_, impala::ExecNode::pool_, and impala::ExecNode::runtime_profile_.
Referenced by impala::ExecNode::ExecNode().
bool impala::ExecNode::is_closed () inline protected inherited
Definition at line 242 of file exec-node.h.
References impala::ExecNode::is_closed_.
Referenced by impala::SelectNode::Close(), impala::SortNode::Close(), impala::UnionNode::Close(), impala::TopNNode::Close(), impala::ExchangeNode::Close(), impala::HBaseScanNode::Close(), Close(), impala::HashJoinNode::Close(), impala::AggregationNode::Close(), impala::BlockingJoinNode::Close(), impala::AnalyticEvalNode::Close(), impala::PartitionedHashJoinNode::Close(), impala::PartitionedAggregationNode::Close(), impala::HdfsScanNode::Close(), impala::PartitionedAggregationNode::Partition::Close(), impala::PartitionedHashJoinNode::Partition::Close(), impala::PartitionedHashJoinNode::ReserveTupleStreamBlocks(), impala::PartitionedHashJoinNode::SpillPartition(), impala::PartitionedAggregationNode::SpillPartition(), and impala::PartitionedHashJoinNode::Partition::~Partition().
virtual bool impala::ExecNode::IsScanNode () const inline protected virtual inherited
Reimplemented in impala::ScanNode.
Definition at line 251 of file exec-node.h.
int64_t impala::ExecNode::limit () const inline inherited
Definition at line 158 of file exec-node.h.
References impala::ExecNode::limit_.
Referenced by GetNext(), and impala::HashJoinNode::LeftJoinGetNext().
MemTracker* impala::ExecNode::mem_tracker () inline inherited
Definition at line 162 of file exec-node.h.
References impala::ExecNode::mem_tracker_.
Referenced by impala::ExecNode::Close(), ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::HdfsScanNode::EnoughMemoryForScannerThread(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::HdfsScanNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::SelectNode::Prepare(), impala::HBaseScanNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::PartitionedHashJoinNode::PrepareNextPartition(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::PartitionedAggregationNode::ProcessStream(), impala::HdfsRCFileScanner::ReadRowGroup(), impala::HdfsAvroScanner::ResolveSchemas(), impala::SortNode::SortInput(), and impala::HdfsScanner::StartNewRowBatch().
Status BlockingJoinNode::Open (RuntimeState * state) virtual inherited
Open prepares the build side structures (subclasses should implement ConstructBuildSide()) and then prepares for GetNext with the first left child row (subclasses should implement InitGetNext()).
Reimplemented from impala::ExecNode.
Definition at line 156 of file blocking-join-node.cc.
References impala::ExecNode::AddRuntimeExecOption(), impala::CgroupsMgr::AssignThreadToCgroup(), impala::BlockingJoinNode::BuildSideThread(), impala::RuntimeState::cgroup(), impala::ExecEnv::cgroups_mgr(), impala::ExecNode::child(), impala::BlockingJoinNode::ConstructBuildSide(), COUNTER_ADD, impala::BlockingJoinNode::current_probe_row_, impala::BlockingJoinNode::eos_, impala::RuntimeState::exec_env(), impala::Promise< T >::Get(), impala::ExecNode::GetNext(), impala::BlockingJoinNode::InitGetNext(), impala::RuntimeState::LogError(), impala::Status::msg(), impala::BlockingJoinNode::node_name_, impala::Status::OK, impala::Status::ok(), impala::ExecNode::Open(), impala::BlockingJoinNode::probe_batch_, impala::BlockingJoinNode::probe_batch_pos_, impala::BlockingJoinNode::probe_row_counter_, impala::BlockingJoinNode::probe_side_eos_, impala::ExecNode::QueryMaintenance(), impala::RuntimeState::resource_pool(), RETURN_IF_CANCELLED, RETURN_IF_ERROR, impala::ExecNode::runtime_profile_, SCOPED_TIMER, and impala::ThreadResourceMgr::ResourcePool::TryAcquireThreadToken().
Referenced by ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), and impala::PartitionedHashJoinNode::ConstructBuildSide().
Status CrossJoinNode::Prepare (RuntimeState * state) virtual
Subclasses should call BlockingJoinNode::Prepare() and then perform any other Prepare() work, e.g. codegen.
Reimplemented from impala::BlockingJoinNode.
Definition at line 38 of file cross-join-node.cc.
References build_batch_pool_, impala::BlockingJoinNode::join_op_, impala::Status::OK, impala::BlockingJoinNode::Prepare(), and RETURN_IF_ERROR.
int CrossJoinNode::ProcessLeftChildBatch (RowBatch * output_batch, RowBatch * batch, int max_added_rows) private
Processes a batch from the left child. output_batch: the batch for resulting tuple rows batch: the batch from the left child to process. This function can be called to continue processing a batch in the middle max_added_rows: maximum rows that can be added to output_batch return the number of rows added to output_batch
Definition at line 142 of file cross-join-node.cc.
References impala::RowBatch::AddRows(), impala::RowBatchList::TupleRowIterator::AtEnd(), build_batches_, impala::RowBatch::CommitRows(), impala::ExecNode::conjunct_ctxs_, impala::BlockingJoinNode::CreateOutputRow(), current_build_row_, impala::BlockingJoinNode::current_probe_row_, impala::ExecNode::EvalConjuncts(), impala::RowBatchList::TupleRowIterator::GetRow(), impala::RowBatch::GetRow(), impala::RowBatch::INVALID_ROW_INDEX, impala::RowBatchList::Iterator(), impala::RowBatchList::TupleRowIterator::Next(), impala::RowBatch::num_rows(), impala::BlockingJoinNode::probe_batch_pos_, impala::RowBatch::row_byte_size(), impala::ExecNode::rows_returned(), and UNLIKELY.
Referenced by GetNext().
Status impala::ExecNode::QueryMaintenance (RuntimeState * state) protected virtual inherited
Frees any local allocations made by expr_ctxs_to_free_ and returns the result of state->CheckQueryState(). Nodes should call this periodically, e.g. once per input row batch. This should not be called outside the main execution thread. Nodes may override this to add extra periodic cleanup, e.g. freeing other local allocations. ExecNodes overriding this function should return ExecNode::QueryMaintenance().
Reimplemented in impala::PartitionedAggregationNode, and impala::AnalyticEvalNode.
Definition at line 401 of file exec-node.cc.
References impala::RuntimeState::CheckQueryState(), impala::ExecNode::expr_ctxs_to_free_, and impala::ExprContext::FreeLocalAllocations().
Referenced by ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::SelectNode::GetNext(), impala::SortNode::GetNext(), impala::UnionNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::HBaseScanNode::Open(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::AnalyticEvalNode::QueryMaintenance(), impala::PartitionedAggregationNode::QueryMaintenance(), and impala::SortNode::SortInput().
bool impala::ExecNode::ReachedLimit () inline inherited
Definition at line 159 of file exec-node.h.
References impala::ExecNode::limit_, and impala::ExecNode::num_rows_returned_.
Referenced by impala::HdfsParquetScanner::AssembleRows(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HdfsTextScanner::FinishScanRange(), impala::SelectNode::GetNext(), impala::UnionNode::GetNext(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::ExchangeNode::GetNext(), GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::HashJoinNode::LeftJoinGetNext(), impala::HdfsSequenceScanner::ProcessBlockCompressedScanRange(), impala::HdfsTextScanner::ProcessRange(), impala::HdfsAvroScanner::ProcessRange(), impala::HdfsSequenceScanner::ProcessRange(), impala::HdfsRCFileScanner::ProcessRange(), and impala::PlanFragmentExecutor::ReachedLimit().
Status CrossJoinNode::Reset (RuntimeState * state) virtual
Subclasses should reset any state modified in Open() and GetNext() and then call BlockingJoinNode::Reset().
Reimplemented from impala::BlockingJoinNode.
Definition at line 45 of file cross-join-node.cc.
References build_batch_pool_, build_batches_, impala::BlockingJoinNode::Reset(), and impala::RowBatchList::Reset().
const RowDescriptor& impala::ExecNode::row_desc () const inline inherited
Definition at line 156 of file exec-node.h.
References impala::ExecNode::row_descriptor_.
Referenced by BuildListDebugString(), impala::HashJoinNode::CodegenCreateOutputRow(), impala::PartitionedHashJoinNode::CodegenCreateOutputRow(), ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::GetLeftChildRowString(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::PartitionedAggregationNode::Partition::InitStreams(), impala::TopNNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::SelectNode::Prepare(), impala::SortNode::Prepare(), impala::UnionNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::PlanFragmentExecutor::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::PartitionedHashJoinNode::ProcessBuildInput(), impala::PartitionedAggregationNode::ProcessStream(), impala::PlanFragmentExecutor::row_desc(), impala::SortNode::SortInput(), and impala::HdfsScanner::StartNewRowBatch().
int64_t impala::ExecNode::rows_returned () const inline inherited
Definition at line 157 of file exec-node.h.
References impala::ExecNode::num_rows_returned_.
Referenced by GetNext(), impala::AnalyticEvalNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedAggregationNode::Open(), impala::HdfsSequenceScanner::ProcessDecompressedBlock(), ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), and impala::HdfsTextScanner::WriteFields().
RuntimeProfile* impala::ExecNode::runtime_profile () inline inherited
Definition at line 161 of file exec-node.h.
References impala::ExecNode::runtime_profile_.
Referenced by impala::ExecNode::AddRuntimeExecOption(), impala::BlockingJoinNode::BuildSideThread(), impala::ExecNode::CreateTreeHelper(), impala::PartitionedAggregationNode::Partition::InitStreams(), impala::SortNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::HdfsScanNode::Open(), impala::HdfsTextScanner::Prepare(), impala::HBaseScanNode::Prepare(), impala::BaseSequenceScanner::Prepare(), impala::ExchangeNode::Prepare(), impala::HdfsParquetScanner::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::ScanNode::Prepare(), impala::PlanFragmentExecutor::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanner::Prepare(), impala::HdfsScanNode::Prepare(), and impala::PartitionedHashJoinNode::ProcessBuildInput().
void impala::ExecNode::SetDebugOptions (int node_id, TExecNodePhase::type phase, TDebugAction::type action, ExecNode * tree) static inherited
Set debug action for node with given id in 'tree'.
Definition at line 332 of file exec-node.cc.
References impala::ExecNode::children_, impala::ExecNode::debug_action_, impala::ExecNode::debug_phase_, and impala::ExecNode::id_.
Referenced by impala::PlanFragmentExecutor::Prepare().
TPlanNodeType::type impala::ExecNode::type () const inline inherited
Definition at line 155 of file exec-node.h.
References impala::ExecNode::type_.
Referenced by impala::ExecNode::CodegenEvalConjuncts(), impala::PartitionedAggregationNode::CodegenUpdateTuple(), and impala::PlanFragmentExecutor::Prepare().
Member Data Documentation
boost::scoped_ptr<ObjectPool> impala::CrossJoinNode::build_batch_pool_ private
Object pool for build RowBatches, stores all BuildBatches in build_rows_.
Definition at line 59 of file cross-join-node.h.
Referenced by Close(), ConstructBuildSide(), Prepare(), and Reset().
RowBatchList impala::CrossJoinNode::build_batches_ private
List of build batches, constructed in Prepare()
Definition at line 61 of file cross-join-node.h.
Referenced by BuildListDebugString(), Close(), ConstructBuildSide(), InitGetNext(), ProcessLeftChildBatch(), and Reset().
boost::scoped_ptr<MemPool> impala::BlockingJoinNode::build_pool_ protected inherited
Definition at line 70 of file blocking-join-node.h.
Referenced by impala::BlockingJoinNode::Close(), impala::HashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::Prepare(), and impala::BlockingJoinNode::Reset().
RuntimeProfile::Counter* impala::BlockingJoinNode::build_row_counter_ protected inherited
Definition at line 102 of file blocking-join-node.h.
Referenced by ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), impala::BlockingJoinNode::Prepare(), and impala::PartitionedHashJoinNode::ProcessBuildInput().
RuntimeProfile::Counter* impala::BlockingJoinNode::build_timer_ protected inherited
Definition at line 100 of file blocking-join-node.h.
Referenced by ConstructBuildSide(), impala::HashJoinNode::ConstructBuildSide(), and impala::BlockingJoinNode::Prepare().
int impala::BlockingJoinNode::build_tuple_row_size_ protected inherited
Definition at line 89 of file blocking-join-node.h.
Referenced by impala::HashJoinNode::CodegenCreateOutputRow(), impala::PartitionedHashJoinNode::CodegenCreateOutputRow(), impala::BlockingJoinNode::CreateOutputRow(), and impala::BlockingJoinNode::Prepare().
bool impala::BlockingJoinNode::can_add_probe_filters_ protected inherited
If true, this node can add filters to the probe (left child) node after processing the entire build side.
Definition at line 98 of file blocking-join-node.h.
Referenced by impala::PartitionedHashJoinNode::AllocateProbeFilters(), impala::PartitionedHashJoinNode::AttachProbeFilters(), impala::PartitionedHashJoinNode::BuildHashTables(), impala::HashJoinNode::ConstructBuildSide(), impala::HashJoinNode::HashJoinNode(), and impala::PartitionedHashJoinNode::PartitionedHashJoinNode().
std::vector<ExecNode*> impala::ExecNode::children_ protected inherited
Definition at line 214 of file exec-node.h.
Referenced by impala::ExecNode::child(), impala::ExecNode::Close(), impala::ExecNode::CollectNodes(), impala::ExecNode::CreateTreeHelper(), impala::HBaseScanNode::DebugString(), impala::UnionNode::GetNext(), impala::UnionNode::Open(), impala::AggregationNode::Open(), impala::PartitionedAggregationNode::Open(), impala::UnionNode::OpenCurrentChild(), impala::ExecNode::Prepare(), impala::PartitionedAggregationNode::ProcessStream(), impala::ExecNode::Reset(), and impala::ExecNode::SetDebugOptions().
std::vector<ExprContext*> impala::ExecNode::conjunct_ctxs_ protected inherited
Definition at line 212 of file exec-node.h.
Referenced by impala::ExecNode::Close(), impala::HashJoinNode::CodegenProcessProbeBatch(), impala::PartitionedHashJoinNode::CodegenProcessProbeBatch(), impala::ExecNode::conjunct_ctxs(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::HBaseScanNode::GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::TopNNode::Init(), impala::ExecNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::ExecNode::Open(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), impala::ExecNode::Prepare(), ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
RowBatchList::TupleRowIterator impala::CrossJoinNode::current_build_row_ private
Definition at line 62 of file cross-join-node.h.
Referenced by GetNext(), InitGetNext(), and ProcessLeftChildBatch().
TupleRow* impala::BlockingJoinNode::current_probe_row_ protected inherited
Definition at line 82 of file blocking-join-node.h.
Referenced by impala::HashJoinNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::PartitionedHashJoinNode::NextSpilledProbeRowBatch(), impala::BlockingJoinNode::Open(), ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), impala::PartitionedHashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ResetForProbe().
TDebugAction::type impala::ExecNode::debug_action_ protected inherited
Definition at line 220 of file exec-node.h.
Referenced by impala::ExecNode::ExecDebugAction(), and impala::ExecNode::SetDebugOptions().
TExecNodePhase::type impala::ExecNode::debug_phase_ protected inherited
debug-only: if debug_action_ is not INVALID, node will perform action in debug_phase_
Definition at line 219 of file exec-node.h.
Referenced by impala::ExecNode::ExecDebugAction(), and impala::ExecNode::SetDebugOptions().
bool impala::BlockingJoinNode::eos_ protected inherited
Definition at line 69 of file blocking-join-node.h.
Referenced by impala::BlockingJoinNode::DebugString(), GetNext(), impala::HashJoinNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::BlockingJoinNode::Open(), and impala::BlockingJoinNode::Reset().
boost::mutex impala::ExecNode::exec_options_lock_ protected inherited
Execution options that are determined at runtime. This is added to the runtime profile at Close(). Examples for options logged here would be "Codegen Enabled"
Definition at line 238 of file exec-node.h.
Referenced by impala::ExecNode::AddRuntimeExecOption().
boost::scoped_ptr<MemTracker> impala::ExecNode::expr_mem_tracker_ protected inherited
MemTracker that should be used for ExprContexts.
Definition at line 233 of file exec-node.h.
Referenced by impala::ExecNode::expr_mem_tracker(), and impala::ExecNode::Prepare().
int impala::ExecNode::id_ protected inherited
Definition at line 209 of file exec-node.h.
Referenced by impala::PartitionedAggregationNode::CreateHashPartitions(), impala::ExecNode::id(), impala::ExecNode::InitRuntimeProfile(), impala::PartitionedAggregationNode::NextPartition(), impala::ExchangeNode::Prepare(), impala::PartitionedHashJoinNode::PrepareNextPartition(), impala::PartitionedHashJoinNode::ProcessBuildInput(), and impala::ExecNode::SetDebugOptions().
TJoinOp::type impala::BlockingJoinNode::join_op_ protected inherited
Definition at line 68 of file blocking-join-node.h.
Referenced by impala::PartitionedHashJoinNode::CleanUpHashPartitions(), impala::PartitionedHashJoinNode::CodegenCreateOutputRow(), impala::PartitionedHashJoinNode::CodegenProcessProbeBatch(), impala::PartitionedHashJoinNode::GetNext(), impala::HashJoinNode::HashJoinNode(), impala::PartitionedHashJoinNode::Init(), impala::PartitionedHashJoinNode::MinRequiredBuffers(), impala::PartitionedHashJoinNode::NextSpilledProbeRowBatch(), impala::PartitionedHashJoinNode::NodeDebugString(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), and impala::HashJoinNode::ProcessProbeBatch().
int64_t impala::ExecNode::limit_ protected inherited
Definition at line 222 of file exec-node.h.
Referenced by impala::SortNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::TopNNode::InsertTupleRow(), impala::HdfsScanNode::limit(), impala::ExecNode::limit(), impala::TopNNode::Open(), and impala::ExecNode::ReachedLimit().
const char * BlockingJoinNode::LLVM_CLASS_NAME = "class.impala::BlockingJoinNode" static inherited
Definition at line 64 of file blocking-join-node.h.
Referenced by impala::HashJoinNode::CodegenCreateOutputRow(), and impala::PartitionedHashJoinNode::CodegenCreateOutputRow().
bool impala::BlockingJoinNode::matched_probe_ protected inherited
Definition at line 83 of file blocking-join-node.h.
Referenced by impala::HashJoinNode::GetNext(), impala::HashJoinNode::InitGetNext(), impala::HashJoinNode::ProcessProbeBatch(), impala::PartitionedHashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ResetForProbe().
boost::scoped_ptr<MemTracker> impala::ExecNode::mem_tracker_ protected inherited
Account for peak memory used by this node.
Definition at line 230 of file exec-node.h.
Referenced by impala::ExecNode::mem_tracker(), and impala::ExecNode::Prepare().
const std::string impala::BlockingJoinNode::node_name_ protected inherited
Definition at line 67 of file blocking-join-node.h.
Referenced by impala::BlockingJoinNode::DebugString(), and impala::BlockingJoinNode::Open().
int64_t impala::ExecNode::num_rows_returned_ protected inherited
Definition at line 223 of file exec-node.h.
Referenced by impala::ExecNode::Close(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::AnalyticEvalNode::GetNextOutputBatch(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), impala::ExecNode::ReachedLimit(), and impala::ExecNode::rows_returned().
ObjectPool* impala::ExecNode::pool_ protected inherited
Definition at line 211 of file exec-node.h.
Referenced by impala::SortNode::Init(), impala::UnionNode::Init(), impala::TopNNode::Init(), impala::ExchangeNode::Init(), impala::HashJoinNode::Init(), impala::AggregationNode::Init(), impala::ExecNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::AnalyticEvalNode::Init(), impala::PartitionedAggregationNode::Init(), impala::ExecNode::InitRuntimeProfile(), impala::HdfsScanNode::Open(), impala::PartitionedHashJoinNode::Prepare(), and impala::PartitionedHashJoinNode::ProcessBuildInput().
boost::scoped_ptr<RowBatch> impala::BlockingJoinNode::probe_batch_ protected inherited
probe_batch_ must be cleared before calling GetNext(). The child node does not initialize all tuple ptrs in the row, only the ones that it is responsible for.
Definition at line 75 of file blocking-join-node.h.
Referenced by impala::BlockingJoinNode::Close(), GetNext(), impala::HashJoinNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::PartitionedHashJoinNode::NextSpilledProbeRowBatch(), impala::BlockingJoinNode::Open(), impala::PartitionedHashJoinNode::OutputNullAwareNullProbe(), impala::PartitionedHashJoinNode::OutputNullAwareProbeRows(), impala::BlockingJoinNode::Prepare(), impala::PartitionedHashJoinNode::PrepareNullAwareNullProbe(), impala::PartitionedHashJoinNode::PrepareNullAwarePartition(), impala::PartitionedHashJoinNode::ProcessProbeBatch(), impala::BlockingJoinNode::Reset(), and impala::BlockingJoinNode::~BlockingJoinNode().
int impala::BlockingJoinNode::probe_batch_pos_ protected inherited
TODO: These variables should move to a join control block struct, which is local to each probing thread.
Definition at line 81 of file blocking-join-node.h.
Referenced by impala::PartitionedHashJoinNode::CleanUpHashPartitions(), impala::BlockingJoinNode::DebugString(), GetNext(), impala::HashJoinNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::PartitionedHashJoinNode::NextSpilledProbeRowBatch(), impala::BlockingJoinNode::Open(), impala::PartitionedHashJoinNode::OutputNullAwareNullProbe(), impala::PartitionedHashJoinNode::OutputNullAwareProbeRows(), impala::PartitionedHashJoinNode::PrepareNullAwareNullProbe(), impala::PartitionedHashJoinNode::PrepareNullAwarePartition(), ProcessLeftChildBatch(), impala::HashJoinNode::ProcessProbeBatch(), impala::PartitionedHashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ResetForProbe().
RuntimeProfile::Counter* impala::BlockingJoinNode::probe_row_counter_ protected inherited
Definition at line 103 of file blocking-join-node.h.
Referenced by GetNext(), impala::HashJoinNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::BlockingJoinNode::Open(), and impala::BlockingJoinNode::Prepare().
bool impala::BlockingJoinNode::probe_side_eos_ protected inherited
Definition at line 77 of file blocking-join-node.h.
Referenced by GetNext(), impala::HashJoinNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::NextProbeRowBatch(), impala::BlockingJoinNode::Open(), and impala::BlockingJoinNode::Reset().
RuntimeProfile::Counter* impala::BlockingJoinNode::probe_timer_ protected inherited
Definition at line 101 of file blocking-join-node.h.
Referenced by GetNext(), impala::HashJoinNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), and impala::BlockingJoinNode::Prepare().
int impala::BlockingJoinNode::probe_tuple_row_size_ protected inherited
Size of the TupleRow (just the Tuple ptrs) from the build (right) and probe (left) sides. Set to zero if the build/probe tuples are not returned, e.g., for semi joins. Cached because it is used in the hot path.
Definition at line 88 of file blocking-join-node.h.
Referenced by impala::HashJoinNode::CodegenCreateOutputRow(), impala::PartitionedHashJoinNode::CodegenCreateOutputRow(), impala::BlockingJoinNode::CreateOutputRow(), and impala::BlockingJoinNode::Prepare().
RowDescriptor impala::ExecNode::row_descriptor_ protected inherited
Definition at line 215 of file exec-node.h.
Referenced by impala::SortNode::Open(), impala::SortNode::Prepare(), impala::TopNNode::Prepare(), impala::ExchangeNode::Prepare(), and impala::ExecNode::row_desc().
const string impala::ExecNode::ROW_THROUGHPUT_COUNTER = "RowsReturnedRate" static inherited
Names of counters shared by all exec nodes.
Definition at line 169 of file exec-node.h.
Referenced by impala::ExecNode::Prepare().
RuntimeProfile::Counter* impala::ExecNode::rows_returned_counter_ protected inherited
Definition at line 226 of file exec-node.h.
Referenced by impala::ExecNode::Close(), impala::SelectNode::CopyRows(), impala::UnionNode::EvalAndMaterializeExprs(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNextInternal(), impala::ExchangeNode::GetNextMerging(), impala::HashJoinNode::LeftJoinGetNext(), impala::PartitionedHashJoinNode::OutputUnmatchedBuild(), and impala::ExecNode::Prepare().
RuntimeProfile::Counter* impala::ExecNode::rows_returned_rate_ protected inherited
Definition at line 227 of file exec-node.h.
Referenced by impala::ExecNode::Prepare().
std::string impala::ExecNode::runtime_exec_options_ protected inherited
Definition at line 239 of file exec-node.h.
Referenced by impala::ExecNode::AddRuntimeExecOption().
boost::scoped_ptr<RuntimeProfile> impala::ExecNode::runtime_profile_ protected inherited
Definition at line 225 of file exec-node.h.
Referenced by impala::HBaseScanNode::Close(), impala::SelectNode::GetNext(), impala::UnionNode::GetNext(), impala::SortNode::GetNext(), impala::HBaseScanNode::GetNext(), impala::TopNNode::GetNext(), impala::ExchangeNode::GetNext(), GetNext(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AnalyticEvalNode::GetNext(), impala::PartitionedHashJoinNode::GetNext(), impala::PartitionedAggregationNode::GetNext(), impala::HdfsScanNode::GetNext(), impala::ExecNode::InitRuntimeProfile(), impala::SelectNode::Open(), impala::HBaseScanNode::Open(), impala::UnionNode::Open(), impala::SortNode::Open(), impala::TopNNode::Open(), impala::ExchangeNode::Open(), impala::DataSourceScanNode::Open(), impala::BlockingJoinNode::Open(), impala::AggregationNode::Open(), impala::AnalyticEvalNode::Open(), impala::PartitionedAggregationNode::Open(), impala::SelectNode::Prepare(), impala::UnionNode::Prepare(), impala::SortNode::Prepare(), impala::TopNNode::Prepare(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::AnalyticEvalNode::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::ExecNode::Prepare(), impala::ScanNode::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::ExecNode::runtime_profile(), and impala::HdfsScanNode::StopAndFinalizeCounters().
TupleRow* impala::BlockingJoinNode::semi_join_staging_row_ protected inherited
Row assembled from all lhs and rhs tuples used for evaluating the non-equi-join conjuncts for semi joins. Semi joins only return the lhs or rhs output tuples, so this tuple is temporarily assembled for evaluating the conjuncts.
Definition at line 94 of file blocking-join-node.h.
Referenced by impala::BlockingJoinNode::Close(), impala::PartitionedHashJoinNode::EvaluateNullProbe(), impala::PartitionedHashJoinNode::OutputNullAwareProbeRows(), impala::BlockingJoinNode::Prepare(), impala::HashJoinNode::ProcessProbeBatch(), and impala::PartitionedHashJoinNode::ProcessProbeBatch().
TPlanNodeType::type impala::ExecNode::type_ protected inherited
Definition at line 210 of file exec-node.h.
Referenced by impala::ExecNode::CollectNodes(), and impala::ExecNode::type().
The documentation for this class was generated from the following files:
be/src/exec/cross-join-node.h
be/src/exec/cross-join-node.cc