Impala: impala::LlvmCodeGenTest Class Reference
impala::LlvmCodeGenTest Class Reference
Static Protected Member Functions
static void LifetimeTest ()
static Status LoadFromFile (ObjectPool *pool, const string &filename, scoped_ptr< LlvmCodeGen > *codegen)
static LlvmCodeGen * CreateCodegen (ObjectPool *pool)
static void ClearHashFns (LlvmCodeGen *codegen)
static void * JitFunction (LlvmCodeGen *codegen, Function *function)
Detailed Description
Definition at line 32 of file llvm-codegen-test.cc.
Member Function Documentation
static void impala::LlvmCodeGenTest::ClearHashFns (LlvmCodeGen * codegen) inline static protected
Definition at line 68 of file llvm-codegen-test.cc.
References impala::LlvmCodeGen::ClearHashFns().
static LlvmCodeGen* impala::LlvmCodeGenTest::CreateCodegen (ObjectPool * pool) inline static protected
Definition at line 59 of file llvm-codegen-test.cc.
References impala::ObjectPool::Add(), impala::LlvmCodeGen::Init(), and impala::Status::ok().
static void* impala::LlvmCodeGenTest::JitFunction (LlvmCodeGen * codegen, Function * function) inline static protected
Definition at line 72 of file llvm-codegen-test.cc.
References impala::LlvmCodeGen::JitFunction().
static void impala::LlvmCodeGenTest::LifetimeTest () inline static protected
Definition at line 34 of file llvm-codegen-test.cc.
References impala::LlvmCodeGen::Init(), impala::Status::ok(), and pool.
static Status impala::LlvmCodeGenTest::LoadFromFile (ObjectPool * pool, const string & filename, scoped_ptr< LlvmCodeGen > * codegen) inline static protected
Definition at line 54 of file llvm-codegen-test.cc.
The documentation for this class was generated from the following file:
be/src/codegen/llvm-codegen-test.cc