Impala: com.cloudera.impala.authorization.ImpalaInternalAdminUser Class Reference
com.cloudera.impala.authorization.ImpalaInternalAdminUser Class Reference
Public Member Functions
String getName ()
String getShortName ()
Static Public Member Functions
static ImpalaInternalAdminUser getInstance ()
Private Member Functions
ImpalaInternalAdminUser ()
Static Private Attributes
static final
ImpalaInternalAdminUser instance_ = new ImpalaInternalAdminUser()
Detailed Description
Definition at line 22 of file ImpalaInternalAdminUser.java.
Constructor & Destructor Documentation
com.cloudera.impala.authorization.ImpalaInternalAdminUser.ImpalaInternalAdminUser () inline private
Definition at line 25 of file ImpalaInternalAdminUser.java.
Member Function Documentation
static ImpalaInternalAdminUser com.cloudera.impala.authorization.ImpalaInternalAdminUser.getInstance () inline static
Definition at line 32 of file ImpalaInternalAdminUser.java.
References com.cloudera.impala.authorization.ImpalaInternalAdminUser.instance_.
Referenced by com.cloudera.impala.service.Frontend.execHiveServer2MetadataOp().
String com.cloudera.impala.authorization.User.getName () inline inherited
Definition at line 30 of file User.java.
References com.cloudera.impala.authorization.User.name_.
Referenced by com.cloudera.impala.analysis.AuthorizationTest.createSessionState(), com.cloudera.impala.util.SentryProxy.PolicyReader.run(), com.cloudera.impala.analysis.AuthorizationTest.TestFunction(), com.cloudera.impala.analysis.AuthorizationTest.TestLocalGroupPolicyProvider(), and com.cloudera.impala.analysis.AuthorizationTest.TestShortUsernameUsed().
String com.cloudera.impala.authorization.User.getShortName () inline inherited
Definition at line 37 of file User.java.
References gen_ir_descriptions.idx, and com.cloudera.impala.authorization.User.name_.
Referenced by com.cloudera.impala.authorization.AuthorizationChecker.getUserGroups(), and com.cloudera.impala.authorization.AuthorizationChecker.hasAccess().
Member Data Documentation
final ImpalaInternalAdminUser com.cloudera.impala.authorization.ImpalaInternalAdminUser.instance_ = new ImpalaInternalAdminUser() static private
Definition at line 23 of file ImpalaInternalAdminUser.java.
Referenced by com.cloudera.impala.authorization.ImpalaInternalAdminUser.getInstance().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/authorization/ImpalaInternalAdminUser.java