Impala: impala::HashTableTest Class Reference
impala::HashTableTest Class Reference
Classes
struct ProbeTestData
Public Member Functions
HashTableTest ()
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
TupleRow * CreateTupleRow (int32_t val)
void ResizeTable (HashTable *table, int64_t new_size, HashTableCtx *ht_ctx)
void FullScan (HashTable *table, HashTableCtx *ht_ctx, int min, int max, bool all_unique, TupleRow **results, TupleRow **expected)
void ValidateMatch (TupleRow *probe_row, TupleRow *build_row)
void ProbeTest (HashTable *table, HashTableCtx *ht_ctx, ProbeTestData *data, int num_data, bool scan)
void SetupTest (bool quadratic, int table_size)
void BasicTest (bool quadratic, int table_size)
void ScanTest (bool quadratic, int initial_size, int rows_to_insert, int additional_rows)
void GrowTableTest (bool quadratic)
void InsertFullTest (bool quadratic, int table_size)
Protected Attributes
ObjectPool pool_
MemTracker tracker_
MemPool mem_pool_
vector< ExprContext * > build_expr_ctxs_
vector< ExprContext * > probe_expr_ctxs_
Detailed Description
Definition at line 38 of file hash-table-test.cc.
Constructor & Destructor Documentation
impala::HashTableTest::HashTableTest () inline
Definition at line 40 of file hash-table-test.cc.
Member Function Documentation
void impala::HashTableTest::BasicTest (bool quadratic, int table_size) inline protected
Definition at line 190 of file hash-table-test.cc.
References build_expr_ctxs_, impala::HashTable::CheckAndResize(), impala::HashTable::Close(), CreateTupleRow(), impala::HashTableCtx::EvalAndHashBuild(), impala::HashTableTest::ProbeTestData::expected_build_rows, impala::MemPool::FreeAll(), FullScan(), impala::hash, impala::HashTable::Insert(), mem_pool_, impala::HashTable::num_buckets(), probe_expr_ctxs_, impala::HashTableTest::ProbeTestData::probe_row, ProbeTest(), ResizeTable(), and impala::HashTable::size().
TupleRow* impala::HashTableTest::CreateTupleRow (int32_t val) inline protected
Definition at line 76 of file hash-table-test.cc.
References impala::MemPool::Allocate(), impala::Tuple::Create(), mem_pool_, and impala::TupleRow::SetTuple().
Referenced by BasicTest(), GrowTableTest(), InsertFullTest(), ScanTest(), and SetupTest().
void impala::HashTableTest::FullScan (HashTable * table, HashTableCtx * ht_ctx, int min, int max, bool all_unique, TupleRow ** results, TupleRow ** expected) inline protected
Definition at line 95 of file hash-table-test.cc.
References impala::HashTable::Iterator::AtEnd(), impala::HashTable::Begin(), build_expr_ctxs_, impala::HashTable::Iterator::GetRow(), impala::TupleRow::GetTuple(), and impala::HashTable::Iterator::Next().
Referenced by BasicTest().
void impala::HashTableTest::GrowTableTest (bool quadratic) inline protected
Definition at line 298 of file hash-table-test.cc.
References impala::HashTable::Iterator::AtEnd(), build_expr_ctxs_, impala::HashTable::CheckAndResize(), impala::HashTable::Close(), CreateTupleRow(), impala::HashTableCtx::EvalAndHashBuild(), impala::HashTableCtx::EvalAndHashProbe(), impala::HashTable::Find(), impala::MemPool::FreeAll(), impala::HashTable::Iterator::GetRow(), impala::TupleRow::GetTuple(), impala::hash, impala::HashTable::Insert(), impala::MemTracker::LimitExceeded(), mem_pool_, pool, probe_expr_ctxs_, impala::HashTable::size(), tracker, and ValidateMatch().
void impala::HashTableTest::InsertFullTest (bool quadratic, int table_size) inline protected
Definition at line 352 of file hash-table-test.cc.
References impala::HashTable::Iterator::AtEnd(), build_expr_ctxs_, impala::HashTable::Close(), CreateTupleRow(), impala::HashTable::EmptyBuckets(), impala::HashTableCtx::EvalAndHashBuild(), impala::HashTableCtx::EvalAndHashProbe(), impala::HashTable::Find(), impala::MemPool::FreeAll(), impala::TupleRow::GetTuple(), impala::hash, impala::HashTable::Insert(), mem_pool_, pool, probe_expr_ctxs_, and tracker.
void impala::HashTableTest::ProbeTest (HashTable * table, HashTableCtx * ht_ctx, ProbeTestData * data, int num_data, bool scan) inline protected
Definition at line 126 of file hash-table-test.cc.
References impala::HashTable::Iterator::AtEnd(), impala::HashTableCtx::EvalAndHashProbe(), impala::HashTableTest::ProbeTestData::expected_build_rows, impala::HashTable::Find(), impala::HashTable::Iterator::GetRow(), impala::TupleRow::GetTuple(), impala::hash, impala::HashTable::Iterator::Next(), impala::HashTableTest::ProbeTestData::probe_row, and ValidateMatch().
Referenced by BasicTest(), and ScanTest().
void impala::HashTableTest::ResizeTable (HashTable * table, int64_t new_size, HashTableCtx * ht_ctx) inline protected
Definition at line 87 of file hash-table-test.cc.
References impala::HashTable::ResizeBuckets().
Referenced by BasicTest(), and ScanTest().
void impala::HashTableTest::ScanTest (bool quadratic, int initial_size, int rows_to_insert, int additional_rows) inline protected
Definition at line 247 of file hash-table-test.cc.
References build_expr_ctxs_, impala::HashTable::CheckAndResize(), impala::HashTable::Close(), CreateTupleRow(), impala::HashTableCtx::EvalAndHashBuild(), impala::HashTableTest::ProbeTestData::expected_build_rows, impala::MemPool::FreeAll(), impala::TupleRow::GetTuple(), impala::hash, impala::HashTable::Insert(), mem_pool_, impala::BitUtil::NextPowerOfTwo(), impala::HashTable::num_buckets(), probe_expr_ctxs_, impala::HashTableTest::ProbeTestData::probe_row, ProbeTest(), and ResizeTable().
virtual void impala::HashTableTest::SetUp () inline protected virtual
Definition at line 49 of file hash-table-test.cc.
References impala::ObjectPool::Add(), build_expr_ctxs_, impala::Status::ok(), impala::Expr::Open(), pool_, impala::Expr::Prepare(), probe_expr_ctxs_, tracker_, and impala::TYPE_INT.
void impala::HashTableTest::SetupTest (bool quadratic, int table_size) inline protected
Definition at line 161 of file hash-table-test.cc.
References build_expr_ctxs_, impala::HashTable::Close(), CreateTupleRow(), impala::MemPool::FreeAll(), mem_pool_, and probe_expr_ctxs_.
virtual void impala::HashTableTest::TearDown () inline protected virtual
Definition at line 71 of file hash-table-test.cc.
References build_expr_ctxs_, impala::Expr::Close(), and probe_expr_ctxs_.
void impala::HashTableTest::ValidateMatch (TupleRow * probe_row, TupleRow * build_row) inline protected
Definition at line 112 of file hash-table-test.cc.
References build_expr_ctxs_, and probe_expr_ctxs_.
Referenced by GrowTableTest(), and ProbeTest().
Member Data Documentation
vector<ExprContext*> impala::HashTableTest::build_expr_ctxs_ protected
Definition at line 46 of file hash-table-test.cc.
Referenced by BasicTest(), FullScan(), GrowTableTest(), InsertFullTest(), ScanTest(), SetUp(), SetupTest(), TearDown(), and ValidateMatch().
MemPool impala::HashTableTest::mem_pool_ protected
Definition at line 45 of file hash-table-test.cc.
Referenced by BasicTest(), CreateTupleRow(), GrowTableTest(), InsertFullTest(), ScanTest(), and SetupTest().
ObjectPool impala::HashTableTest::pool_ protected
Definition at line 43 of file hash-table-test.cc.
Referenced by SetUp().
vector<ExprContext*> impala::HashTableTest::probe_expr_ctxs_ protected
Definition at line 47 of file hash-table-test.cc.
Referenced by BasicTest(), GrowTableTest(), InsertFullTest(), ScanTest(), SetUp(), SetupTest(), TearDown(), and ValidateMatch().
MemTracker impala::HashTableTest::tracker_ protected
Definition at line 44 of file hash-table-test.cc.
Referenced by SetUp().
The documentation for this class was generated from the following file:
be/src/exec/hash-table-test.cc