Impala: impala::HdfsParquetTableWriter::BoolColumnWriter Class Reference
impala::HdfsParquetTableWriter::BoolColumnWriter Class Reference
Public Member Functions
BoolColumnWriter (HdfsParquetTableWriter *parent, ExprContext *ctx, const THdfsCompression::type &codec)
Status AppendRow (TupleRow *row)
Status Flush (int64_t *file_pos, int64_t *first_data_page, int64_t *first_dictionary_page)
virtual void Reset ()
void Close ()
const ColumnType & type () const
uint64_t num_values () const
uint64_t total_compressed_size () const
uint64_t total_uncompressed_size () const
parquet::CompressionCodec::type codec () const
Protected Member Functions
virtual bool EncodeValue (void *value, int64_t *bytes_needed)
virtual void FinalizeCurrentPage ()
void NewPage ()
void WriteDictDataPage ()
Protected Attributes
HdfsParquetTableWriter * parent_
ExprContext * expr_ctx_
THdfsCompression::type codec_
scoped_ptr< Codec > compressor_
vector< DataPage > pages_
int num_data_pages_
int64_t page_size_
DataPage * current_page_
int64_t num_values_
int64_t total_compressed_byte_size_
int64_t total_uncompressed_byte_size_
Encoding::type current_encoding_
DictEncoderBase * dict_encoder_base_
RleEncoder * def_levels_
uint8_t * values_buffer_
int values_buffer_len_
Private Attributes
BitWriter * bool_values_
Detailed Description
Definition at line 334 of file hdfs-parquet-table-writer.cc.
Constructor & Destructor Documentation
impala::HdfsParquetTableWriter::BoolColumnWriter::BoolColumnWriter (HdfsParquetTableWriter * parent, ExprContext * ctx, const THdfsCompression::type & codec) inline
Definition at line 337 of file hdfs-parquet-table-writer.cc.
References impala::PLAIN, impala::ExprContext::root(), impala::ColumnType::type, impala::Expr::type(), and impala::TYPE_BOOLEAN.
Member Function Documentation
Status HdfsParquetTableWriter::BaseColumnWriter::AppendRow (TupleRow * row) inline inherited
Definition at line 371 of file hdfs-parquet-table-writer.cc.
References impala::Status::OK, impala::PrettyPrinter::Print(), and UNLIKELY.
void impala::HdfsParquetTableWriter::BaseColumnWriter::Close () inline inherited
Definition at line 140 of file hdfs-parquet-table-writer.cc.
parquet::CompressionCodec::type impala::HdfsParquetTableWriter::BaseColumnWriter::codec () const inline inherited
Definition at line 149 of file hdfs-parquet-table-writer.cc.
References impala::IMPALA_TO_PARQUET_CODEC.
virtual bool impala::HdfsParquetTableWriter::BoolColumnWriter::EncodeValue (void * value, int64_t * bytes_needed) inline protected virtual
Implements impala::HdfsParquetTableWriter::BaseColumnWriter.
Definition at line 349 of file hdfs-parquet-table-writer.cc.
virtual void impala::HdfsParquetTableWriter::BoolColumnWriter::FinalizeCurrentPage () inline protected virtual
Reimplemented from impala::HdfsParquetTableWriter::BaseColumnWriter.
Definition at line 353 of file hdfs-parquet-table-writer.cc.
Status HdfsParquetTableWriter::BaseColumnWriter::Flush (int64_t * file_pos, int64_t * first_data_page, int64_t * first_dictionary_page) inherited
Definition at line 432 of file hdfs-parquet-table-writer.cc.
References impala::HdfsParquetTableWriter::BaseColumnWriter::DataPage::data, impala::HdfsParquetTableWriter::BaseColumnWriter::DataPage::header, impala::Status::OK, RETURN_IF_ERROR, and SCOPED_TIMER.
void HdfsParquetTableWriter::BaseColumnWriter::NewPage () protected inherited
Definition at line 597 of file hdfs-parquet-table-writer.cc.
uint64_t impala::HdfsParquetTableWriter::BaseColumnWriter::num_values () const inline inherited
Definition at line 146 of file hdfs-parquet-table-writer.cc.
virtual void impala::HdfsParquetTableWriter::BaseColumnWriter::Reset () inline virtual inherited
Reimplemented in impala::HdfsParquetTableWriter::ColumnWriter< T >.
Definition at line 130 of file hdfs-parquet-table-writer.cc.
References impala::PLAIN.
uint64_t impala::HdfsParquetTableWriter::BaseColumnWriter::total_compressed_size () const inline inherited
Definition at line 147 of file hdfs-parquet-table-writer.cc.
uint64_t impala::HdfsParquetTableWriter::BaseColumnWriter::total_uncompressed_size () const inline inherited
Definition at line 148 of file hdfs-parquet-table-writer.cc.
const ColumnType& impala::HdfsParquetTableWriter::BaseColumnWriter::type () const inline inherited
Definition at line 145 of file hdfs-parquet-table-writer.cc.
References impala::ColumnType::type.
Referenced by impala::HdfsParquetTableWriter::Init().
void HdfsParquetTableWriter::BaseColumnWriter::WriteDictDataPage () inline protected inherited
Definition at line 416 of file hdfs-parquet-table-writer.cc.
References UNLIKELY.
Member Data Documentation
BitWriter* impala::HdfsParquetTableWriter::BoolColumnWriter::bool_values_ private
Definition at line 366 of file hdfs-parquet-table-writer.cc.
THdfsCompression::type impala::HdfsParquetTableWriter::BaseColumnWriter::codec_ protected inherited
Definition at line 196 of file hdfs-parquet-table-writer.cc.
scoped_ptr<Codec> impala::HdfsParquetTableWriter::BaseColumnWriter::compressor_ protected inherited
Definition at line 199 of file hdfs-parquet-table-writer.cc.
Encoding::type impala::HdfsParquetTableWriter::BaseColumnWriter::current_encoding_ protected inherited
Definition at line 218 of file hdfs-parquet-table-writer.cc.
DataPage* impala::HdfsParquetTableWriter::BaseColumnWriter::current_page_ protected inherited
Definition at line 214 of file hdfs-parquet-table-writer.cc.
RleEncoder* impala::HdfsParquetTableWriter::BaseColumnWriter::def_levels_ protected inherited
Definition at line 227 of file hdfs-parquet-table-writer.cc.
DictEncoderBase* impala::HdfsParquetTableWriter::BaseColumnWriter::dict_encoder_base_ protected inherited
Definition at line 221 of file hdfs-parquet-table-writer.cc.
ExprContext* impala::HdfsParquetTableWriter::BaseColumnWriter::expr_ctx_ protected inherited
Definition at line 194 of file hdfs-parquet-table-writer.cc.
int impala::HdfsParquetTableWriter::BaseColumnWriter::num_data_pages_ protected inherited
Definition at line 205 of file hdfs-parquet-table-writer.cc.
int64_t impala::HdfsParquetTableWriter::BaseColumnWriter::num_values_ protected inherited
Definition at line 215 of file hdfs-parquet-table-writer.cc.
int64_t impala::HdfsParquetTableWriter::BaseColumnWriter::page_size_ protected inherited
Definition at line 212 of file hdfs-parquet-table-writer.cc.
vector<DataPage> impala::HdfsParquetTableWriter::BaseColumnWriter::pages_ protected inherited
Definition at line 201 of file hdfs-parquet-table-writer.cc.
HdfsParquetTableWriter* impala::HdfsParquetTableWriter::BaseColumnWriter::parent_ protected inherited
Definition at line 193 of file hdfs-parquet-table-writer.cc.
int64_t impala::HdfsParquetTableWriter::BaseColumnWriter::total_compressed_byte_size_ protected inherited
Definition at line 216 of file hdfs-parquet-table-writer.cc.
int64_t impala::HdfsParquetTableWriter::BaseColumnWriter::total_uncompressed_byte_size_ protected inherited
Definition at line 217 of file hdfs-parquet-table-writer.cc.
uint8_t* impala::HdfsParquetTableWriter::BaseColumnWriter::values_buffer_ protected inherited
Definition at line 230 of file hdfs-parquet-table-writer.cc.
int impala::HdfsParquetTableWriter::BaseColumnWriter::values_buffer_len_ protected inherited
Definition at line 232 of file hdfs-parquet-table-writer.cc.
The documentation for this class was generated from the following file:
be/src/exec/hdfs-parquet-table-writer.cc