Impala: com.cloudera.impala.analysis.AlterTableDropPartitionStmt Class Reference
com.cloudera.impala.analysis.AlterTableDropPartitionStmt Class Reference
Public Member Functions
AlterTableDropPartitionStmt (TableName tableName, PartitionSpec partitionSpec, boolean ifExists)
boolean getIfNotExists ()
String toSql ()
TAlterTableParams toThrift ()
void analyze (Analyzer analyzer) throws AnalysisException
String getTbl ()
String getDb ()
void setIsExplain ()
boolean isExplain ()
Protected Member Functions
Table getTargetTable ()
Protected Attributes
final TableName tableName_
Table table_
boolean isExplain_ = false
Private Attributes
final boolean ifExists_
final PartitionSpec partitionSpec_
Detailed Description
Represents an ALTER TABLE DROP PARTITION statement.
Definition at line 27 of file AlterTableDropPartitionStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AlterTableDropPartitionStmt.AlterTableDropPartitionStmt (TableName tableName, PartitionSpec partitionSpec, boolean ifExists) inline
Definition at line 31 of file AlterTableDropPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableDropPartitionStmt.ifExists_, and com.cloudera.impala.analysis.AlterTableDropPartitionStmt.partitionSpec_.
Member Function Documentation
void com.cloudera.impala.analysis.AlterTableDropPartitionStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 63 of file AlterTableDropPartitionStmt.java.
References com.cloudera.impala.authorization.Privilege.ALTER, and com.cloudera.impala.analysis.AlterTableDropPartitionStmt.ifExists_.
String com.cloudera.impala.analysis.AlterTableStmt.getDb () inline inherited
Can only be called after analysis, returns the parent database name of the target table for this ALTER TABLE statement.
Definition at line 47 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
boolean com.cloudera.impala.analysis.AlterTableDropPartitionStmt.getIfNotExists () inline
Definition at line 40 of file AlterTableDropPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableDropPartitionStmt.ifExists_.
Table com.cloudera.impala.analysis.AlterTableStmt.getTargetTable () inline protected inherited
Can only be called after analysis, returns the Table object of the target of this ALTER TABLE statement.
Definition at line 55 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.table_.
Referenced by com.cloudera.impala.analysis.AlterTableSetStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetCachedStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetLocationStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getDb().
String com.cloudera.impala.analysis.AlterTableStmt.getTbl () inline inherited
Definition at line 41 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toSql(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 43 of file AlterTableDropPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.getTbl(), and com.cloudera.impala.analysis.AlterTableDropPartitionStmt.ifExists_.
TAlterTableParams com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toThrift () inline
Definition at line 52 of file AlterTableDropPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableDropPartitionStmt.ifExists_.
Member Data Documentation
final boolean com.cloudera.impala.analysis.AlterTableDropPartitionStmt.ifExists_ private
Definition at line 28 of file AlterTableDropPartitionStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableDropPartitionStmt.AlterTableDropPartitionStmt(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.getIfNotExists(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final PartitionSpec com.cloudera.impala.analysis.AlterTableDropPartitionStmt.partitionSpec_ private
Definition at line 29 of file AlterTableDropPartitionStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableDropPartitionStmt.AlterTableDropPartitionStmt().
Table com.cloudera.impala.analysis.AlterTableStmt.table_ protected inherited
Definition at line 33 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
final TableName com.cloudera.impala.analysis.AlterTableStmt.tableName_ protected inherited
Definition at line 30 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), and com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AlterTableDropPartitionStmt.java