Impala: com.cloudera.impala.catalog.HiveStorageDescriptorFactory Class Reference
com.cloudera.impala.catalog.HiveStorageDescriptorFactory Class Reference
Static Public Member Functions
static StorageDescriptor createSd (THdfsFileFormat fileFormat, RowFormat rowFormat)
Static Private Member Functions
static StorageDescriptor createParquetFileSd ()
static StorageDescriptor createTextSd ()
static StorageDescriptor createSequenceFileSd ()
static StorageDescriptor createRcFileSd ()
static StorageDescriptor createAvroSd ()
static StorageDescriptor createGenericSd ()
Detailed Description
Definition at line 24 of file HiveStorageDescriptorFactory.java.
Member Function Documentation
static StorageDescriptor com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createAvroSd () inline static private
Definition at line 98 of file HiveStorageDescriptorFactory.java.
References com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createGenericSd().
Referenced by com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd().
static StorageDescriptor com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createGenericSd () inline static private
Creates a new StorageDescriptor with options common to all storage formats.
Definition at line 115 of file HiveStorageDescriptorFactory.java.
Referenced by com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createAvroSd(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createParquetFileSd(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createRcFileSd(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSequenceFileSd(), and com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createTextSd().
static StorageDescriptor com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createParquetFileSd () inline static private
Definition at line 60 of file HiveStorageDescriptorFactory.java.
References com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createGenericSd().
Referenced by com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd().
static StorageDescriptor com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createRcFileSd () inline static private
Definition at line 89 of file HiveStorageDescriptorFactory.java.
References com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createGenericSd().
Referenced by com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd().
static StorageDescriptor com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd (THdfsFileFormat fileFormat, RowFormat rowFormat) inline static
Creates and returns a Hive StoreDescriptor for the given FileFormat and RowFormat. Currently supports creating StorageDescriptors for Parquet, Text, Sequence, and RC file. TODO: Add support for HBase
Definition at line 31 of file HiveStorageDescriptorFactory.java.
References com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createAvroSd(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createParquetFileSd(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createRcFileSd(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSequenceFileSd(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createTextSd(), com.cloudera.impala.catalog.RowFormat.getEscapeChar(), com.cloudera.impala.catalog.RowFormat.getFieldDelimiter(), and com.cloudera.impala.catalog.RowFormat.getLineDelimiter().
static StorageDescriptor com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSequenceFileSd () inline static private
Definition at line 79 of file HiveStorageDescriptorFactory.java.
References com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createGenericSd().
Referenced by com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd().
static StorageDescriptor com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createTextSd () inline static private
Definition at line 69 of file HiveStorageDescriptorFactory.java.
References com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createGenericSd().
Referenced by com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HiveStorageDescriptorFactory.java