Impala: com.cloudera.impala.analysis.LimitElement Class Reference
com.cloudera.impala.analysis.LimitElement Class Reference
Public Member Functions
LimitElement (Expr limitExpr, Expr offsetExpr)
Expr getLimitExpr ()
Expr getOffsetExpr ()
long getLimit ()
boolean hasLimit ()
long getOffset ()
String toSql ()
void analyze (Analyzer analyzer) throws AnalysisException
LimitElement clone ()
Protected Member Functions
LimitElement (LimitElement other)
Static Private Member Functions
static long evalIntegerExpr (Analyzer analyzer, Expr expr, String name) throws AnalysisException
Private Attributes
final Expr limitExpr_
final Expr offsetExpr_
long limit_
long offset_
boolean isAnalyzed_
Detailed Description
Combination of limit and offset expressions.
Definition at line 26 of file LimitElement.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.LimitElement.LimitElement (Expr limitExpr, Expr offsetExpr) inline
Constructs the LimitElement.
Parameters
limitExpr The limit expression. May be null if there is no LIMIT clause.
offsetExpr The offset expression. May be null if there is no OFFSET clause.
Definition at line 38 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.isAnalyzed_, com.cloudera.impala.analysis.LimitElement.limit_, and com.cloudera.impala.analysis.LimitElement.offset_.
Referenced by com.cloudera.impala.analysis.LimitElement.clone().
com.cloudera.impala.analysis.LimitElement.LimitElement (LimitElement other) inline protected
Copy c'tor used in clone().
Definition at line 49 of file LimitElement.java.
References com.cloudera.impala.analysis.Expr.clone(), com.cloudera.impala.analysis.LimitElement.isAnalyzed_, com.cloudera.impala.analysis.LimitElement.limit_, com.cloudera.impala.analysis.LimitElement.limitExpr_, com.cloudera.impala.analysis.LimitElement.offset_, and com.cloudera.impala.analysis.LimitElement.offsetExpr_.
Member Function Documentation
void com.cloudera.impala.analysis.LimitElement.analyze (Analyzer analyzer) throws AnalysisException inline
Definition at line 98 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.evalIntegerExpr(), com.cloudera.impala.analysis.Expr.getType(), com.cloudera.impala.analysis.LimitElement.isAnalyzed_, com.cloudera.impala.analysis.Expr.isConstant(), com.cloudera.impala.analysis.LimitElement.limit_, com.cloudera.impala.analysis.LimitElement.limitExpr_, com.cloudera.impala.analysis.LimitElement.offset_, com.cloudera.impala.analysis.LimitElement.offsetExpr_, and com.cloudera.impala.analysis.Expr.toSql().
LimitElement com.cloudera.impala.analysis.LimitElement.clone () inline
Definition at line 165 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.LimitElement().
Referenced by com.cloudera.impala.analysis.ValuesStmt.clone(), com.cloudera.impala.analysis.UnionStmt.clone(), and com.cloudera.impala.analysis.SelectStmt.clone().
static long com.cloudera.impala.analysis.LimitElement.evalIntegerExpr (Analyzer analyzer, Expr expr, String name) throws AnalysisException inline static private
Evaluations an expression to a non-zero integral value, returned as a long. Throws if the expression cannot be evaluated, if the value evaluates to null, or if the result is negative. The 'name' parameter is used in exception messages, e.g. "LIMIT expression evaluates to NULL".
Definition at line 136 of file LimitElement.java.
References impala.name.
Referenced by com.cloudera.impala.analysis.LimitElement.analyze().
long com.cloudera.impala.analysis.LimitElement.getLimit () inline
Returns the integer limit, evaluated from the limit expression. Must call analyze() first. If no limit was set, then -1 is returned.
Definition at line 64 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.isAnalyzed_, and com.cloudera.impala.analysis.LimitElement.limit_.
Referenced by com.cloudera.impala.analysis.SelectStmt.returnsSingleRow().
Expr com.cloudera.impala.analysis.LimitElement.getLimitExpr () inline
Definition at line 57 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.limitExpr_.
long com.cloudera.impala.analysis.LimitElement.getOffset () inline
Returns the integer offset, evaluated from the offset expression. Must call analyze() first. If no offsetExpr exists, then 0 (the default offset) is returned.
Definition at line 78 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.isAnalyzed_, and com.cloudera.impala.analysis.LimitElement.offset_.
Expr com.cloudera.impala.analysis.LimitElement.getOffsetExpr () inline
Definition at line 58 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.offsetExpr_.
Referenced by com.cloudera.impala.analysis.QueryStmt.analyzeLimit().
boolean com.cloudera.impala.analysis.LimitElement.hasLimit () inline
Definition at line 69 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.isAnalyzed_, and com.cloudera.impala.analysis.LimitElement.limit_.
String com.cloudera.impala.analysis.LimitElement.toSql () inline
Definition at line 83 of file LimitElement.java.
References com.cloudera.impala.analysis.LimitElement.isAnalyzed_, com.cloudera.impala.analysis.LimitElement.limitExpr_, com.cloudera.impala.analysis.LimitElement.offset_, and com.cloudera.impala.analysis.LimitElement.offsetExpr_.
Referenced by com.cloudera.impala.analysis.QueryStmt.analyzeLimit().
Member Data Documentation
boolean com.cloudera.impala.analysis.LimitElement.isAnalyzed_ private
Definition at line 31 of file LimitElement.java.
Referenced by com.cloudera.impala.analysis.LimitElement.analyze(), com.cloudera.impala.analysis.LimitElement.getLimit(), com.cloudera.impala.analysis.LimitElement.getOffset(), com.cloudera.impala.analysis.LimitElement.hasLimit(), com.cloudera.impala.analysis.LimitElement.LimitElement(), and com.cloudera.impala.analysis.LimitElement.toSql().
long com.cloudera.impala.analysis.LimitElement.limit_ private
Definition at line 29 of file LimitElement.java.
Referenced by com.cloudera.impala.analysis.LimitElement.analyze(), com.cloudera.impala.analysis.LimitElement.getLimit(), com.cloudera.impala.analysis.LimitElement.hasLimit(), and com.cloudera.impala.analysis.LimitElement.LimitElement().
final Expr com.cloudera.impala.analysis.LimitElement.limitExpr_ private
Definition at line 27 of file LimitElement.java.
Referenced by com.cloudera.impala.analysis.LimitElement.analyze(), com.cloudera.impala.analysis.LimitElement.getLimitExpr(), com.cloudera.impala.analysis.LimitElement.LimitElement(), and com.cloudera.impala.analysis.LimitElement.toSql().
long com.cloudera.impala.analysis.LimitElement.offset_ private
Definition at line 30 of file LimitElement.java.
Referenced by com.cloudera.impala.analysis.LimitElement.analyze(), com.cloudera.impala.analysis.LimitElement.getOffset(), com.cloudera.impala.analysis.LimitElement.LimitElement(), and com.cloudera.impala.analysis.LimitElement.toSql().
final Expr com.cloudera.impala.analysis.LimitElement.offsetExpr_ private
Definition at line 28 of file LimitElement.java.
Referenced by com.cloudera.impala.analysis.LimitElement.analyze(), com.cloudera.impala.analysis.LimitElement.getOffsetExpr(), com.cloudera.impala.analysis.LimitElement.LimitElement(), and com.cloudera.impala.analysis.LimitElement.toSql().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/LimitElement.java