Impala: impala::RowBatchList::TupleRowIterator Class Reference
impala::RowBatchList::TupleRowIterator Class Reference
A simple iterator used to scan over all the rows stored in the list.
#include <row-batch-list.h>
Public Member Functions
TupleRowIterator ()
Dummy constructor.
bool AtEnd ()
Returns true if this iterator is at the end, i.e. GetRow() cannot be called.
TupleRow * GetRow ()
void Next ()
Increments the iterator. No-op if the iterator is at the end.
Private Member Functions
TupleRowIterator (RowBatchList *list)
Private Attributes
RowBatchList * list_
std::vector< RowBatch * >::iterator batch_it_
int64_t row_idx_
Friends
class RowBatchList
Detailed Description
A simple iterator used to scan over all the rows stored in the list.
Definition at line 39 of file row-batch-list.h.
Constructor & Destructor Documentation
impala::RowBatchList::TupleRowIterator::TupleRowIterator () inline
Dummy constructor.
Definition at line 42 of file row-batch-list.h.
impala::RowBatchList::TupleRowIterator::TupleRowIterator (RowBatchList * list) inline private
Definition at line 68 of file row-batch-list.h.
Member Function Documentation
bool impala::RowBatchList::TupleRowIterator::AtEnd () inline
Returns true if this iterator is at the end, i.e. GetRow() cannot be called.
Definition at line 45 of file row-batch-list.h.
References batch_it_, list_, and impala::RowBatchList::row_batches_.
Referenced by impala::RowBatchList::DebugString(), impala::RowBatchListTest::FullScan(), impala::CrossJoinNode::GetNext(), GetRow(), and impala::CrossJoinNode::ProcessLeftChildBatch().
TupleRow* impala::RowBatchList::TupleRowIterator::GetRow () inline
Returns the current row. Callers must check the iterator is not AtEnd() before calling GetRow().
Definition at line 51 of file row-batch-list.h.
References AtEnd(), and row_idx_.
Referenced by impala::RowBatchList::DebugString(), impala::RowBatchListTest::FullScan(), and impala::CrossJoinNode::ProcessLeftChildBatch().
void impala::RowBatchList::TupleRowIterator::Next () inline
Increments the iterator. No-op if the iterator is at the end.
Definition at line 57 of file row-batch-list.h.
References batch_it_, list_, impala::RowBatchList::row_batches_, and row_idx_.
Referenced by impala::RowBatchList::DebugString(), impala::RowBatchListTest::FullScan(), and impala::CrossJoinNode::ProcessLeftChildBatch().
Friends And Related Function Documentation
friend class RowBatchList friend
Definition at line 66 of file row-batch-list.h.
Member Data Documentation
std::vector<RowBatch*>::iterator impala::RowBatchList::TupleRowIterator::batch_it_ private
Definition at line 75 of file row-batch-list.h.
Referenced by AtEnd(), and Next().
RowBatchList* impala::RowBatchList::TupleRowIterator::list_ private
Definition at line 74 of file row-batch-list.h.
Referenced by AtEnd(), and Next().
int64_t impala::RowBatchList::TupleRowIterator::row_idx_ private
Definition at line 76 of file row-batch-list.h.
Referenced by GetRow(), and Next().
The documentation for this class was generated from the following file:
be/src/exec/row-batch-list.h