Impala: impala::ConditionalFunctions Class Reference
impala::ConditionalFunctions Class Reference
Conditional functions that can be expressed as UDFs.
#include <conditional-functions.h>
Static Public Member Functions
static TinyIntVal NullIfZero (FunctionContext *context, const TinyIntVal &val)
static SmallIntVal NullIfZero (FunctionContext *context, const SmallIntVal &val)
static IntVal NullIfZero (FunctionContext *context, const IntVal &val)
static BigIntVal NullIfZero (FunctionContext *context, const BigIntVal &val)
static FloatVal NullIfZero (FunctionContext *context, const FloatVal &val)
static DoubleVal NullIfZero (FunctionContext *context, const DoubleVal &val)
static DecimalVal NullIfZero (FunctionContext *context, const DecimalVal &val)
static TinyIntVal ZeroIfNull (FunctionContext *context, const TinyIntVal &val)
static SmallIntVal ZeroIfNull (FunctionContext *context, const SmallIntVal &val)
static IntVal ZeroIfNull (FunctionContext *context, const IntVal &val)
static BigIntVal ZeroIfNull (FunctionContext *context, const BigIntVal &val)
static FloatVal ZeroIfNull (FunctionContext *context, const FloatVal &val)
static DoubleVal ZeroIfNull (FunctionContext *context, const DoubleVal &val)
static DecimalVal ZeroIfNull (FunctionContext *context, const DecimalVal &val)
static BooleanVal IsFalse (FunctionContext *ctx, const BooleanVal &val)
static BooleanVal IsNotFalse (FunctionContext *ctx, const BooleanVal &val)
static BooleanVal IsTrue (FunctionContext *ctx, const BooleanVal &val)
static BooleanVal IsNotTrue (FunctionContext *ctx, const BooleanVal &val)
Detailed Description
Conditional functions that can be expressed as UDFs.
Definition at line 31 of file conditional-functions.h.
Member Function Documentation
BooleanVal ConditionalFunctions::IsFalse (FunctionContext * ctx, const BooleanVal & val) static
Functions IsFalse and IsTrue return false when the input is NULL. Functions IsNotFalse and IsNotTrue return true when the input is NULL.
Definition at line 34 of file conditional-functions.cc.
References impala_udf::AnyVal::is_null, and impala_udf::BooleanVal::val.
BooleanVal ConditionalFunctions::IsNotFalse (FunctionContext * ctx, const BooleanVal & val) static
Definition at line 39 of file conditional-functions.cc.
References impala_udf::AnyVal::is_null, and impala_udf::BooleanVal::val.
BooleanVal ConditionalFunctions::IsNotTrue (FunctionContext * ctx, const BooleanVal & val) static
Definition at line 49 of file conditional-functions.cc.
References impala_udf::AnyVal::is_null, and impala_udf::BooleanVal::val.
BooleanVal ConditionalFunctions::IsTrue (FunctionContext * ctx, const BooleanVal & val) static
Definition at line 44 of file conditional-functions.cc.
References impala_udf::AnyVal::is_null, and impala_udf::BooleanVal::val.
static TinyIntVal impala::ConditionalFunctions::NullIfZero (FunctionContext * context, const TinyIntVal & val) static
Referenced by impala::Expr::InitBuiltinsDummy().
static SmallIntVal impala::ConditionalFunctions::NullIfZero (FunctionContext * context, const SmallIntVal & val) static
static IntVal impala::ConditionalFunctions::NullIfZero (FunctionContext * context, const IntVal & val) static
static BigIntVal impala::ConditionalFunctions::NullIfZero (FunctionContext * context, const BigIntVal & val) static
static FloatVal impala::ConditionalFunctions::NullIfZero (FunctionContext * context, const FloatVal & val) static
static DoubleVal impala::ConditionalFunctions::NullIfZero (FunctionContext * context, const DoubleVal & val) static
DecimalVal ConditionalFunctions::NullIfZero (FunctionContext * context, const DecimalVal & val) static
Definition at line 72 of file conditional-functions-ir.cc.
References impala::ColumnType::GetByteSize(), impala_udf::FunctionContext::GetReturnType(), impala_udf::AnyVal::is_null, impala::AnyValUtil::TypeDescToColumnType(), impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
static TinyIntVal impala::ConditionalFunctions::ZeroIfNull (FunctionContext * context, const TinyIntVal & val) static
static SmallIntVal impala::ConditionalFunctions::ZeroIfNull (FunctionContext * context, const SmallIntVal & val) static
static IntVal impala::ConditionalFunctions::ZeroIfNull (FunctionContext * context, const IntVal & val) static
static BigIntVal impala::ConditionalFunctions::ZeroIfNull (FunctionContext * context, const BigIntVal & val) static
static FloatVal impala::ConditionalFunctions::ZeroIfNull (FunctionContext * context, const FloatVal & val) static
static DoubleVal impala::ConditionalFunctions::ZeroIfNull (FunctionContext * context, const DoubleVal & val) static
static DecimalVal impala::ConditionalFunctions::ZeroIfNull (FunctionContext * context, const DecimalVal & val) static
The documentation for this class was generated from the following files:
be/src/exprs/conditional-functions.h
be/src/exprs/conditional-functions-ir.cc
be/src/exprs/conditional-functions.cc