Impala: impala::ClientConnection< T > Class Template Reference
impala::ClientConnection< T > Class Template Reference
#include <client-cache.h>
Public Member Functions
ClientConnection (ClientCache< T > *client_cache, TNetworkAddress address, Status *status)
~ClientConnection ()
Status Reopen ()
T * operator-> () const
template<class F , class Request , class Response >
Status DoRpc (const F &f, const Request &request, Response *response)
Private Attributes
ClientCache< T > * client_cache_
T * client_
Detailed Description
template<class T>
class impala::ClientConnection< T >
A scoped client connection to help manage clients from a client cache. Clients of this class should use DoRpc() to actually make RPC calls.
Definition at line 192 of file client-cache.h.
Constructor & Destructor Documentation
template<class T> impala::ClientConnection< T >::ClientConnection (ClientCache< T > * client_cache, TNetworkAddress address, Status * status) inline
Definition at line 194 of file client-cache.h.
References impala::ClientConnection< T >::client_, impala::ClientConnection< T >::client_cache_, and impala::Status::ok().
template<class T> impala::ClientConnection< T >::~ClientConnection () inline
Definition at line 200 of file client-cache.h.
References impala::ClientConnection< T >::client_, and impala::ClientConnection< T >::client_cache_.
Member Function Documentation
template<class T> template<class F , class Request , class Response > Status impala::ClientConnection< T >::DoRpc (const F & f, const Request & request, Response * response) inline
Perform an RPC call f(request, response), with some failure handling in case the TCP connection underpinning this client has been closed unexpectedly. Note that this can lead to f() being called twice, as this method may retry f() once, depending on the error received from the first attempt. TODO: Detect already-closed cnxns and only retry in that case. Returns RPC_TIMEOUT if a timeout occurred, and RPC_GENERAL_ERROR if the RPC could not be completed for any other reason (except for an unexpectedly closed cnxn, see TODO). Application-level failures should be signalled through the response type. TODO: Use TTransportException::TTransportExceptionType to distinguish between failure modes.
Definition at line 225 of file client-cache.h.
References impala::ClientConnection< T >::client_, impala::IsTimeoutTException(), impala::Status::OK, impala::ClientConnection< T >::Reopen(), and RETURN_IF_ERROR.
Referenced by impala::DataStreamSender::Channel::CloseInternal(), impala::FragmentMgr::FragmentExecState::ReportStatusCb(), and impala::DataStreamSender::Channel::TransmitDataHelper().
template<class T> T* impala::ClientConnection< T >::operator-> () const inline
Definition at line 210 of file client-cache.h.
References impala::ClientConnection< T >::client_.
template<class T> Status impala::ClientConnection< T >::Reopen () inline
Definition at line 206 of file client-cache.h.
References impala::ClientConnection< T >::client_, and impala::ClientConnection< T >::client_cache_.
Referenced by impala::ClientConnection< T >::DoRpc().
Member Data Documentation
template<class T> T* impala::ClientConnection< T >::client_ private
Definition at line 247 of file client-cache.h.
Referenced by impala::ClientConnection< T >::ClientConnection(), impala::ClientConnection< T >::DoRpc(), impala::ClientConnection< T >::operator->(), impala::ClientConnection< T >::Reopen(), and impala::ClientConnection< T >::~ClientConnection().
template<class T> ClientCache<T>* impala::ClientConnection< T >::client_cache_ private
Definition at line 246 of file client-cache.h.
Referenced by impala::ClientConnection< T >::ClientConnection(), impala::ClientConnection< T >::Reopen(), and impala::ClientConnection< T >::~ClientConnection().
The documentation for this class was generated from the following file:
be/src/runtime/client-cache.h