Impala: com.cloudera.impala.analysis.BaseTableRef Class Reference
com.cloudera.impala.analysis.BaseTableRef Class Reference
Public Member Functions
BaseTableRef (TableRef tableRef, Path resolvedPath)
void analyze (Analyzer analyzer) throws AnalysisException
String debugString ()
TableRef clone ()
TupleDescriptor createTupleDescriptor (Analyzer analyzer) throws AnalysisException
JoinOperator getJoinOp ()
boolean isChildRef ()
List< String > getPath ()
Path getResolvedPath ()
String[] getAliases ()
String getUniqueAlias ()
boolean hasExplicitAlias ()
String getExplicitAlias ()
Table getTable ()
ArrayList< String > getJoinHints ()
Expr getOnClause ()
List< String > getUsingClause ()
void setJoinOp (JoinOperator op)
void setOnClause (Expr e)
void setUsingClause (List< String > colNames)
TableRef getLeftTblRef ()
void setLeftTblRef (TableRef leftTblRef)
void setJoinHints (ArrayList< String > hints)
boolean isBroadcastJoin ()
boolean isPartitionedJoin ()
List< TupleId > getOnClauseTupleIds ()
boolean isResolved ()
TupleDescriptor getDesc ()
TupleId getId ()
List< TupleId > getMaterializedTupleIds ()
List< TupleId > getAllMaterializedTupleIds ()
List< TupleId > getAllTupleIds ()
void analyzeJoin (Analyzer analyzer) throws AnalysisException
void invertJoin (List< Pair< TableRef, PlanNode >> refPlans, Analyzer analyzer)
String toSql ()
Privilege getPrivilegeRequirement ()
Protected Member Functions
String tableRefToSql ()
void setJoinAttrs (TableRef other)
Protected Attributes
List< String > rawPath_
Path resolvedPath_
String[] aliases_
boolean hasExplicitAlias_
JoinOperator joinOp_
ArrayList< String > joinHints_
Expr onClause_
List< String > usingColNames_
TableRef leftTblRef_
boolean isAnalyzed_
List< TupleId > onClauseTupleIds_ = Lists.newArrayList()
TupleDescriptor desc_
Private Member Functions
BaseTableRef (BaseTableRef other)
Detailed Description
Represents a reference to an actual table, such as an Hdfs or HBase table. BaseTableRefs are instantiated as a result of table resolution during analysis of a SelectStmt.
Definition at line 25 of file BaseTableRef.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.BaseTableRef.BaseTableRef (TableRef tableRef, Path resolvedPath) inline
Definition at line 26 of file BaseTableRef.java.
References com.cloudera.impala.analysis.TableRef.aliases_, com.cloudera.impala.analysis.TableRef.getTable(), com.cloudera.impala.analysis.TableRef.hasExplicitAlias(), and com.cloudera.impala.analysis.TableRef.resolvedPath_.
Referenced by com.cloudera.impala.analysis.BaseTableRef.clone().
com.cloudera.impala.analysis.BaseTableRef.BaseTableRef (BaseTableRef other) inline private
C'tor for cloning.
Definition at line 41 of file BaseTableRef.java.
Member Function Documentation
void com.cloudera.impala.analysis.BaseTableRef.analyze (Analyzer analyzer) throws AnalysisException inline
Register this table ref and then analyze the Join clause.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 49 of file BaseTableRef.java.
References com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.desc_, com.cloudera.impala.analysis.TableRef.getPrivilegeRequirement(), and com.cloudera.impala.analysis.TableRef.isAnalyzed_.
void com.cloudera.impala.analysis.TableRef.analyzeJoin (Analyzer analyzer) throws AnalysisException inline inherited
Analyze the join clause. The join clause can only be analyzed after the left table has been analyzed and the TupleDescriptor (desc) of this table has been created.
Definition at line 339 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), com.cloudera.impala.analysis.Path.createRawPath(), com.cloudera.impala.analysis.JoinOperator.CROSS_JOIN, com.cloudera.impala.analysis.TableRef.desc_, com.cloudera.impala.analysis.JoinOperator.FULL_OUTER_JOIN, com.cloudera.impala.analysis.Expr.getConjuncts(), com.cloudera.impala.analysis.TableRef.getDesc(), com.cloudera.impala.analysis.TableRef.getId(), com.cloudera.impala.analysis.TableRef.getJoinOp(), com.cloudera.impala.analysis.TableRef.getUniqueAlias(), com.cloudera.impala.analysis.Expr.isAggregatePredicate(), com.cloudera.impala.analysis.TableRef.isBroadcastJoin_, com.cloudera.impala.analysis.TableRef.isChildRef(), com.cloudera.impala.analysis.TableRef.joinOp_, com.cloudera.impala.analysis.JoinOperator.LEFT_ANTI_JOIN, com.cloudera.impala.analysis.JoinOperator.LEFT_OUTER_JOIN, com.cloudera.impala.analysis.JoinOperator.LEFT_SEMI_JOIN, com.cloudera.impala.analysis.TableRef.leftTblRef_, com.cloudera.impala.analysis.JoinOperator.NULL_AWARE_LEFT_ANTI_JOIN, com.cloudera.impala.analysis.TableRef.onClause_, com.cloudera.impala.analysis.Path.resolve(), com.cloudera.impala.analysis.JoinOperator.RIGHT_ANTI_JOIN, com.cloudera.impala.analysis.JoinOperator.RIGHT_OUTER_JOIN, com.cloudera.impala.analysis.JoinOperator.RIGHT_SEMI_JOIN, com.cloudera.impala.analysis.TableRef.toSql(), com.cloudera.impala.analysis.JoinOperator.toString(), and com.cloudera.impala.analysis.TableRef.usingColNames_.
Referenced by com.cloudera.impala.analysis.BaseTableRef.analyze(), com.cloudera.impala.analysis.CollectionTableRef.analyze(), and com.cloudera.impala.analysis.InlineViewRef.analyze().
TableRef com.cloudera.impala.analysis.BaseTableRef.clone () inline
Definition at line 69 of file BaseTableRef.java.
References com.cloudera.impala.analysis.BaseTableRef.BaseTableRef().
TupleDescriptor com.cloudera.impala.analysis.TableRef.createTupleDescriptor (Analyzer analyzer) throws AnalysisException inline inherited
Creates and returns a empty TupleDescriptor registered with the analyzer based on the resolvedPath_. This method is called from the analyzer when registering this table reference.
Definition at line 169 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.getUniqueAlias(), and com.cloudera.impala.analysis.TableRef.resolvedPath_.
String com.cloudera.impala.analysis.BaseTableRef.debugString () inline
Definition at line 67 of file BaseTableRef.java.
References com.cloudera.impala.analysis.BaseTableRef.tableRefToSql().
String [] com.cloudera.impala.analysis.TableRef.getAliases () inline inherited
Returns all legal aliases of this table ref.
Definition at line 205 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.aliases_.
List<TupleId> com.cloudera.impala.analysis.TableRef.getAllMaterializedTupleIds () inline inherited
Return the list of tuple ids materialized by the full sequence of table refs up to this one.
Definition at line 278 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.getMaterializedTupleIds(), and com.cloudera.impala.analysis.TableRef.leftTblRef_.
List<TupleId> com.cloudera.impala.analysis.TableRef.getAllTupleIds () inline inherited
Return the list of tuple ids of the full sequence of table refs up to this one.
Definition at line 292 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.isAnalyzed_, and com.cloudera.impala.analysis.TableRef.leftTblRef_.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate().
TupleDescriptor com.cloudera.impala.analysis.TableRef.getDesc () inline inherited
This method should only be called after the TableRef has been analyzed.
Definition at line 250 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.desc_, and com.cloudera.impala.analysis.TableRef.isAnalyzed_.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.planner.SingleNodePlanner.getHashLookupJoinConjuncts(), and com.cloudera.impala.analysis.StmtRewriter.mergeExpr().
String com.cloudera.impala.analysis.TableRef.getExplicitAlias () inline inherited
Returns the explicit alias if this table ref has one, null otherwise.
Definition at line 224 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.getUniqueAlias(), and com.cloudera.impala.analysis.TableRef.hasExplicitAlias().
Referenced by com.cloudera.impala.analysis.InlineViewRef.InlineViewRef(), com.cloudera.impala.analysis.BaseTableRef.tableRefToSql(), com.cloudera.impala.analysis.InlineViewRef.tableRefToSql(), and com.cloudera.impala.analysis.TableRef.tableRefToSql().
TupleId com.cloudera.impala.analysis.TableRef.getId () inline inherited
This method should only be called after the TableRef has been analyzed.
Definition at line 260 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.desc_, and com.cloudera.impala.analysis.TableRef.isAnalyzed_.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.planner.SingleNodePlanner.migrateConjunctsToInlineView(), and com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.partitionValueTransfers().
ArrayList<String> com.cloudera.impala.analysis.TableRef.getJoinHints () inline inherited
Definition at line 233 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.joinHints_.
JoinOperator com.cloudera.impala.analysis.TableRef.getJoinOp () inline inherited
Definition at line 188 of file TableRef.java.
References com.cloudera.impala.analysis.JoinOperator.INNER_JOIN, and com.cloudera.impala.analysis.TableRef.joinOp_.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.Analyzer.canEvalPredicate(), com.cloudera.impala.planner.SingleNodePlanner.createJoinPlan(), com.cloudera.impala.analysis.Analyzer.getAntiJoinRef(), com.cloudera.impala.analysis.Analyzer.getBoundPredicates(), com.cloudera.impala.analysis.Analyzer.getEqJoinConjuncts(), com.cloudera.impala.analysis.TableRef.invertJoin(), com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.partitionValueTransfers(), com.cloudera.impala.analysis.Analyzer.registerOnClauseConjuncts(), and com.cloudera.impala.analysis.StmtRewriter.replaceUnqualifiedStarItems().
TableRef com.cloudera.impala.analysis.TableRef.getLeftTblRef () inline inherited
Definition at line 239 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.leftTblRef_.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.createJoinPlan().
List<TupleId> com.cloudera.impala.analysis.TableRef.getMaterializedTupleIds () inline inherited
Definition at line 267 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.desc_, and com.cloudera.impala.analysis.TableRef.isAnalyzed_.
Referenced by com.cloudera.impala.analysis.TableRef.getAllMaterializedTupleIds().
Expr com.cloudera.impala.analysis.TableRef.getOnClause () inline inherited
Definition at line 234 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.onClause_.
List<TupleId> com.cloudera.impala.analysis.TableRef.getOnClauseTupleIds () inline inherited
Definition at line 244 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.onClauseTupleIds_.
List<String> com.cloudera.impala.analysis.TableRef.getPath () inline inherited
Definition at line 199 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.rawPath_.
Privilege com.cloudera.impala.analysis.TableRef.getPrivilegeRequirement () inline inherited
Gets the privilege requirement. This is always SELECT for TableRefs.
Definition at line 499 of file TableRef.java.
References com.cloudera.impala.authorization.Privilege.SELECT.
Referenced by com.cloudera.impala.analysis.BaseTableRef.analyze(), com.cloudera.impala.analysis.CollectionTableRef.analyze(), and com.cloudera.impala.analysis.TableRef.analyze().
Path com.cloudera.impala.analysis.TableRef.getResolvedPath () inline inherited
Definition at line 200 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.resolvedPath_.
Table com.cloudera.impala.analysis.TableRef.getTable () inline inherited
Definition at line 229 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.resolvedPath_.
Referenced by com.cloudera.impala.analysis.BaseTableRef.BaseTableRef(), and com.cloudera.impala.analysis.BaseTableRef.tableRefToSql().
String com.cloudera.impala.analysis.TableRef.getUniqueAlias () inline inherited
Returns the explicit alias or the fully-qualified implicit alias. The returned alias is guaranteed to be unique (i.e., column/field references against the alias cannot be ambiguous).
Definition at line 212 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.aliases_.
Referenced by com.cloudera.impala.analysis.InlineViewRef.analyze(), com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.planner.SingleNodePlanner.createJoinPlan(), com.cloudera.impala.analysis.TableRef.createTupleDescriptor(), com.cloudera.impala.analysis.InlineViewRef.createTupleDescriptor(), and com.cloudera.impala.analysis.TableRef.getExplicitAlias().
List<String> com.cloudera.impala.analysis.TableRef.getUsingClause () inline inherited
Definition at line 235 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.usingColNames_.
boolean com.cloudera.impala.analysis.TableRef.hasExplicitAlias () inline inherited
Returns true if this table ref has an explicit alias. Note that getAliases().length() == 1 does not imply an explicit alias because nested collection refs have only a single implicit alias.
Definition at line 219 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.hasExplicitAlias_.
Referenced by com.cloudera.impala.analysis.BaseTableRef.BaseTableRef(), com.cloudera.impala.analysis.CollectionTableRef.CollectionTableRef(), com.cloudera.impala.analysis.TableRef.getExplicitAlias(), and com.cloudera.impala.analysis.InlineViewRef.InlineViewRef().
void com.cloudera.impala.analysis.TableRef.invertJoin (List< Pair< TableRef, PlanNode >> refPlans, Analyzer analyzer) inline inherited
Inverts the join whose rhs is represented by this table ref. If necessary, this function modifies the registered analysis state associated with this table ref, as well as the chain of left table references in refPlans as appropriate. Requires that this is the very first join in a series of joins.
Definition at line 447 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.getJoinOp(), com.cloudera.impala.analysis.Analyzer.invertOuterJoinState(), com.cloudera.impala.analysis.JoinOperator.isOuterJoin(), com.cloudera.impala.analysis.TableRef.joinOp_, com.cloudera.impala.analysis.TableRef.leftTblRef_, and com.cloudera.impala.analysis.TableRef.onClause_.
boolean com.cloudera.impala.analysis.TableRef.isBroadcastJoin () inline inherited
Definition at line 242 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.isBroadcastJoin_.
boolean com.cloudera.impala.analysis.TableRef.isChildRef () inline inherited
Returns true if the path of this table ref is is rooted at a registered parent ref.
Definition at line 197 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin().
boolean com.cloudera.impala.analysis.TableRef.isPartitionedJoin () inline inherited
Definition at line 243 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.isPartitionedJoin_.
boolean com.cloudera.impala.analysis.TableRef.isResolved () inline inherited
Definition at line 245 of file TableRef.java.
void com.cloudera.impala.analysis.TableRef.setJoinAttrs (TableRef other) inline protected inherited
Set this table's context-dependent join attributes from the given table. Does not clone the attributes.
Definition at line 181 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.InlineViewRef.InlineViewRef().
void com.cloudera.impala.analysis.TableRef.setJoinHints (ArrayList< String > hints) inline inherited
Definition at line 241 of file TableRef.java.
void com.cloudera.impala.analysis.TableRef.setJoinOp (JoinOperator op) inline inherited
Definition at line 236 of file TableRef.java.
void com.cloudera.impala.analysis.TableRef.setLeftTblRef (TableRef leftTblRef) inline inherited
Definition at line 240 of file TableRef.java.
void com.cloudera.impala.analysis.TableRef.setOnClause (Expr e) inline inherited
Definition at line 237 of file TableRef.java.
void com.cloudera.impala.analysis.TableRef.setUsingClause (List< String > colNames) inline inherited
Definition at line 238 of file TableRef.java.
String com.cloudera.impala.analysis.BaseTableRef.tableRefToSql () inline protected
Definition at line 57 of file BaseTableRef.java.
References com.cloudera.impala.analysis.TableRef.getExplicitAlias(), com.cloudera.impala.analysis.TableRef.getTable(), and com.cloudera.impala.analysis.TableRef.toSql().
Referenced by com.cloudera.impala.analysis.BaseTableRef.debugString().
String com.cloudera.impala.analysis.TableRef.toSql () inline inherited
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 478 of file TableRef.java.
References com.cloudera.impala.analysis.TableRef.joinHints_, com.cloudera.impala.analysis.TableRef.joinOp_, com.cloudera.impala.analysis.TableRef.leftTblRef_, com.cloudera.impala.analysis.TableRef.onClause_, com.cloudera.impala.analysis.TableRef.tableRefToSql(), com.cloudera.impala.analysis.Expr.toSql(), com.cloudera.impala.analysis.JoinOperator.toString(), and com.cloudera.impala.analysis.TableRef.usingColNames_.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.BaseTableRef.tableRefToSql(), and com.cloudera.impala.analysis.InlineViewRef.tableRefToSql().
Member Data Documentation
String [] com.cloudera.impala.analysis.TableRef.aliases_ protected inherited
Definition at line 58 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.BaseTableRef.BaseTableRef(), com.cloudera.impala.analysis.CollectionTableRef.CollectionTableRef(), com.cloudera.impala.analysis.TableRef.getAliases(), com.cloudera.impala.analysis.TableRef.getUniqueAlias(), com.cloudera.impala.analysis.InlineViewRef.InlineViewRef(), and com.cloudera.impala.analysis.TableRef.TableRef().
TupleDescriptor com.cloudera.impala.analysis.TableRef.desc_ protected inherited
Definition at line 83 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.BaseTableRef.analyze(), com.cloudera.impala.analysis.CollectionTableRef.analyze(), com.cloudera.impala.analysis.InlineViewRef.analyze(), com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.getDesc(), com.cloudera.impala.analysis.TableRef.getId(), and com.cloudera.impala.analysis.TableRef.getMaterializedTupleIds().
boolean com.cloudera.impala.analysis.TableRef.hasExplicitAlias_ protected inherited
Definition at line 61 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.hasExplicitAlias(), and com.cloudera.impala.analysis.TableRef.TableRef().
boolean com.cloudera.impala.analysis.TableRef.isAnalyzed_ protected inherited
Definition at line 77 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.BaseTableRef.analyze(), com.cloudera.impala.analysis.CollectionTableRef.analyze(), com.cloudera.impala.analysis.InlineViewRef.analyze(), com.cloudera.impala.analysis.TableRef.getAllTupleIds(), com.cloudera.impala.analysis.InlineViewRef.getAnalyzer(), com.cloudera.impala.analysis.InlineViewRef.getBaseTblSmap(), com.cloudera.impala.analysis.TableRef.getDesc(), com.cloudera.impala.analysis.TableRef.getId(), com.cloudera.impala.analysis.InlineViewRef.getMaterializedTupleIds(), com.cloudera.impala.analysis.TableRef.getMaterializedTupleIds(), com.cloudera.impala.analysis.InlineViewRef.getSmap(), and com.cloudera.impala.analysis.TableRef.TableRef().
ArrayList<String> com.cloudera.impala.analysis.TableRef.joinHints_ protected inherited
Definition at line 64 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), com.cloudera.impala.analysis.TableRef.getJoinHints(), com.cloudera.impala.analysis.TableRef.TableRef(), and com.cloudera.impala.analysis.TableRef.toSql().
JoinOperator com.cloudera.impala.analysis.TableRef.joinOp_ protected inherited
Definition at line 63 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), com.cloudera.impala.analysis.TableRef.getJoinOp(), com.cloudera.impala.analysis.TableRef.invertJoin(), and com.cloudera.impala.analysis.TableRef.toSql().
TableRef com.cloudera.impala.analysis.TableRef.leftTblRef_ protected inherited
Definition at line 73 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.getAllMaterializedTupleIds(), com.cloudera.impala.analysis.TableRef.getAllTupleIds(), com.cloudera.impala.analysis.TableRef.getLeftTblRef(), com.cloudera.impala.analysis.TableRef.invertJoin(), and com.cloudera.impala.analysis.TableRef.toSql().
Expr com.cloudera.impala.analysis.TableRef.onClause_ protected inherited
Definition at line 65 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.getOnClause(), com.cloudera.impala.analysis.TableRef.invertJoin(), com.cloudera.impala.analysis.TableRef.TableRef(), and com.cloudera.impala.analysis.TableRef.toSql().
List<TupleId> com.cloudera.impala.analysis.TableRef.onClauseTupleIds_ = Lists.newArrayList() protected inherited
Definition at line 80 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.getOnClauseTupleIds().
List<String> com.cloudera.impala.analysis.TableRef.rawPath_ protected inherited
Definition at line 47 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyze(), com.cloudera.impala.analysis.TableRef.getPath(), com.cloudera.impala.analysis.TableRef.TableRef(), and com.cloudera.impala.analysis.TableRef.tableRefToSql().
Path com.cloudera.impala.analysis.TableRef.resolvedPath_ protected inherited
Definition at line 50 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.CollectionTableRef.analyze(), com.cloudera.impala.analysis.TableRef.analyze(), com.cloudera.impala.analysis.BaseTableRef.BaseTableRef(), com.cloudera.impala.analysis.CollectionTableRef.CollectionTableRef(), com.cloudera.impala.analysis.TableRef.createTupleDescriptor(), com.cloudera.impala.analysis.TableRef.getResolvedPath(), com.cloudera.impala.analysis.TableRef.getTable(), com.cloudera.impala.analysis.CollectionTableRef.isChildRef(), and com.cloudera.impala.analysis.TableRef.tableRefToSql().
List<String> com.cloudera.impala.analysis.TableRef.usingColNames_ protected inherited
Definition at line 66 of file TableRef.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.getUsingClause(), com.cloudera.impala.analysis.TableRef.TableRef(), and com.cloudera.impala.analysis.TableRef.toSql().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/BaseTableRef.java