Impala: impala::Coordinator::BackendExecState Class Reference
impala::Coordinator::BackendExecState Class Reference
Public Member Functions
BackendExecState (QuerySchedule &schedule, Coordinator *coord, const TNetworkAddress &coord_address, int backend_num, const TPlanFragment &fragment, int fragment_idx, const FragmentExecParams &params, int instance_idx, DebugOptions *debug_options, ObjectPool *obj_pool)
void ComputeTotalSplitSize ()
int64_t GetNodeThroughput (int plan_node_id)
int64_t GetNumScanRangesCompleted (int plan_node_id)
int64_t UpdateNumScanRangesCompleted ()
Public Attributes
TUniqueId fragment_instance_id
MonotonicStopWatch stopwatch
const TNetworkAddress backend_address
int64_t total_split_size
TExecPlanFragmentParams rpc_params
int fragment_idx
int instance_idx
boost::mutex lock
Status status
bool initiated
bool done
bool profile_created
RuntimeProfile * profile
ErrorLogMap error_log
int64_t total_ranges_complete
FragmentInstanceCounters aggregate_counters
Detailed Description
Definition at line 104 of file coordinator.cc.
Constructor & Destructor Documentation
impala::Coordinator::BackendExecState::BackendExecState (QuerySchedule & schedule, Coordinator * coord, const TNetworkAddress & coord_address, int backend_num, const TPlanFragment & fragment, int fragment_idx, const FragmentExecParams & params, int instance_idx, DebugOptions * debug_options, ObjectPool * obj_pool) inline
Definition at line 141 of file coordinator.cc.
References impala::DebugOptions::action, impala::ObjectPool::Add(), impala::DebugOptions::node_id, impala::DebugOptions::phase, and impala::PrintId().
Member Function Documentation
void impala::Coordinator::BackendExecState::ComputeTotalSplitSize ()
Definition at line 189 of file coordinator.cc.
int64_t impala::Coordinator::BackendExecState::GetNodeThroughput (int plan_node_id)
Definition at line 200 of file coordinator.cc.
References impala::RuntimeProfile::Counter::value().
int64_t impala::Coordinator::BackendExecState::GetNumScanRangesCompleted (int plan_node_id)
Definition at line 214 of file coordinator.cc.
References impala::RuntimeProfile::Counter::value().
int64_t impala::Coordinator::BackendExecState::UpdateNumScanRangesCompleted ()
Definition at line 228 of file coordinator.cc.
Member Data Documentation
FragmentInstanceCounters impala::Coordinator::BackendExecState::aggregate_counters
Definition at line 139 of file coordinator.cc.
const TNetworkAddress impala::Coordinator::BackendExecState::backend_address
Definition at line 108 of file coordinator.cc.
bool impala::Coordinator::BackendExecState::done
Definition at line 131 of file coordinator.cc.
ErrorLogMap impala::Coordinator::BackendExecState::error_log
Definition at line 134 of file coordinator.cc.
int impala::Coordinator::BackendExecState::fragment_idx
Definition at line 115 of file coordinator.cc.
TUniqueId impala::Coordinator::BackendExecState::fragment_instance_id
Definition at line 106 of file coordinator.cc.
bool impala::Coordinator::BackendExecState::initiated
Definition at line 130 of file coordinator.cc.
int impala::Coordinator::BackendExecState::instance_idx
Definition at line 118 of file coordinator.cc.
boost::mutex impala::Coordinator::BackendExecState::lock
Definition at line 123 of file coordinator.cc.
RuntimeProfile* impala::Coordinator::BackendExecState::profile
Definition at line 133 of file coordinator.cc.
bool impala::Coordinator::BackendExecState::profile_created
Definition at line 132 of file coordinator.cc.
TExecPlanFragmentParams impala::Coordinator::BackendExecState::rpc_params
Definition at line 112 of file coordinator.cc.
Status impala::Coordinator::BackendExecState::status
Definition at line 128 of file coordinator.cc.
MonotonicStopWatch impala::Coordinator::BackendExecState::stopwatch
Definition at line 107 of file coordinator.cc.
int64_t impala::Coordinator::BackendExecState::total_ranges_complete
Definition at line 137 of file coordinator.cc.
int64_t impala::Coordinator::BackendExecState::total_split_size
Definition at line 109 of file coordinator.cc.
The documentation for this class was generated from the following file:
be/src/runtime/coordinator.cc