Impala: impala::SimpleNullStreamTest Class Reference
impala::SimpleNullStreamTest Class Reference
Protected Member Functions
virtual void CreateDescriptors ()
virtual void SetUp ()
virtual void TearDown ()
void CreateMgr (int64_t limit, int block_size)
virtual RowBatch * CreateIntBatch (int start_val, int num_rows, bool gen_null)
virtual RowBatch * CreateStringBatch (int string_idx, int num_rows, bool gen_null)
void AppendRowTuples (TupleRow *row, vector< int > *results)
void AppendRowTuples (TupleRow *row, vector< StringValue > *results)
void AppendValue (Tuple *t, vector< int > *results)
void AppendValue (Tuple *t, vector< StringValue > *results)
template<typename T >
void ReadValues (BufferedTupleStream *stream, RowDescriptor *desc, vector< T > *results, int num_batches=-1)
virtual void VerifyResults (const vector< int > &results, int exp_rows, bool gen_null)
virtual void VerifyResults (const vector< StringValue > &results, int exp_rows, bool gen_null)
template<typename T >
void TestValues (int num_batches, RowDescriptor *desc, bool gen_null)
void TestIntValuesInterleaved (int num_batches, int num_batches_before_read)
Protected Attributes
scoped_ptr< ExecEnv > exec_env_
scoped_ptr< RuntimeState > runtime_state_
scoped_ptr< MemTracker > block_mgr_parent_tracker_
shared_ptr< BufferedBlockMgr > block_mgr_
BufferedBlockMgr::Client * client_
MemTracker tracker_
ObjectPool pool_
RowDescriptor * int_desc_
RowDescriptor * string_desc_
scoped_ptr< MemPool > mem_pool_
Detailed Description
Definition at line 403 of file buffered-tuple-stream-test.cc.
Member Function Documentation
void impala::SimpleTupleStreamTest::AppendRowTuples (TupleRow * row, vector< int > * results) inline protected inherited
Definition at line 176 of file buffered-tuple-stream-test.cc.
References impala::SimpleTupleStreamTest::AppendValue(), impala::TupleRow::GetTuple(), impala::SimpleTupleStreamTest::int_desc_, and impala::RowDescriptor::tuple_descriptors().
Referenced by impala::SimpleTupleStreamTest::ReadValues().
void impala::SimpleTupleStreamTest::AppendRowTuples (TupleRow * row, vector< StringValue > * results) inline protected inherited
Definition at line 184 of file buffered-tuple-stream-test.cc.
References impala::SimpleTupleStreamTest::AppendValue(), impala::TupleRow::GetTuple(), impala::SimpleTupleStreamTest::string_desc_, and impala::RowDescriptor::tuple_descriptors().
void impala::SimpleTupleStreamTest::AppendValue (Tuple * t, vector< int > * results) inline protected inherited
Definition at line 192 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::AppendRowTuples().
void impala::SimpleTupleStreamTest::AppendValue (Tuple * t, vector< StringValue > * results) inline protected inherited
Definition at line 201 of file buffered-tuple-stream-test.cc.
References impala::StringValue::len, impala::SimpleTupleStreamTest::mem_pool_, and impala::StringValue::ptr.
virtual void impala::SimpleNullStreamTest::CreateDescriptors () inline protected virtual
Reimplemented from impala::SimpleTupleStreamTest.
Definition at line 405 of file buffered-tuple-stream-test.cc.
References impala::ObjectPool::Add(), impala::DescriptorTblBuilder::Build(), impala::DescriptorTblBuilder::DeclareTuple(), impala::SimpleTupleStreamTest::int_desc_, impala::SimpleTupleStreamTest::pool_, impala::SimpleTupleStreamTest::string_desc_, impala::TYPE_INT, and impala::TYPE_STRING.
virtual RowBatch* impala::SimpleTupleStreamTest::CreateIntBatch (int start_val, int num_rows, bool gen_null) inline protected virtual inherited
Definition at line 101 of file buffered-tuple-stream-test.cc.
References impala::ObjectPool::Add(), impala::RowBatch::AddRow(), impala::MemPool::Allocate(), impala::RowBatch::CommitLastRow(), impala::RowBatch::GetRow(), gen_ir_descriptions::idx, impala::SimpleTupleStreamTest::int_desc_, impala::SimpleTupleStreamTest::pool_, impala::TupleRow::SetTuple(), impala::SimpleTupleStreamTest::tracker_, impala::RowBatch::tuple_data_pool(), and impala::RowDescriptor::tuple_descriptors().
Referenced by impala::SimpleTupleStreamTest::TestIntValuesInterleaved(), and impala::SimpleTupleStreamTest::TestValues().
void impala::SimpleTupleStreamTest::CreateMgr (int64_t limit, int block_size) inline protected inherited
Definition at line 93 of file buffered-tuple-stream-test.cc.
References impala::SimpleTupleStreamTest::block_mgr_, impala::SimpleTupleStreamTest::client_, impala::BufferedBlockMgr::Create(), impala::Status::ok(), impala::SimpleTupleStreamTest::runtime_state_, and impala::SimpleTupleStreamTest::tracker_.
virtual RowBatch* impala::SimpleTupleStreamTest::CreateStringBatch (int string_idx, int num_rows, bool gen_null) inline protected virtual inherited
Definition at line 136 of file buffered-tuple-stream-test.cc.
References impala::ObjectPool::Add(), impala::RowBatch::AddRow(), impala::MemPool::Allocate(), impala::RowBatch::CommitLastRow(), impala::RowBatch::GetRow(), impala::NUM_STRINGS, impala::SimpleTupleStreamTest::pool_, impala::TupleRow::SetTuple(), impala::SimpleTupleStreamTest::string_desc_, impala::STRINGS, impala::SimpleTupleStreamTest::tracker_, impala::RowBatch::tuple_data_pool(), and impala::RowDescriptor::tuple_descriptors().
Referenced by impala::SimpleTupleStreamTest::TestValues().
template<typename T > void impala::SimpleTupleStreamTest::ReadValues (BufferedTupleStream * stream, RowDescriptor * desc, vector< T > * results, int num_batches = -1) inline protected inherited
Definition at line 215 of file buffered-tuple-stream-test.cc.
References impala::SimpleTupleStreamTest::AppendRowTuples(), BATCH_SIZE, impala::BufferedTupleStream::GetNext(), impala::RowBatch::GetRow(), impala::RowBatch::num_rows(), impala::Status::ok(), impala::RowBatch::Reset(), and impala::SimpleTupleStreamTest::tracker_.
Referenced by impala::SimpleTupleStreamTest::TestIntValuesInterleaved(), and impala::SimpleTupleStreamTest::TestValues().
virtual void impala::SimpleTupleStreamTest::SetUp () inline protected virtual inherited
Definition at line 59 of file buffered-tuple-stream-test.cc.
References impala::SimpleTupleStreamTest::CreateDescriptors(), impala::SimpleTupleStreamTest::exec_env_, impala::SimpleTupleStreamTest::mem_pool_, impala::SimpleTupleStreamTest::runtime_state_, and impala::SimpleTupleStreamTest::tracker_.
virtual void impala::SimpleTupleStreamTest::TearDown () inline protected virtual inherited
Definition at line 85 of file buffered-tuple-stream-test.cc.
References impala::SimpleTupleStreamTest::block_mgr_, impala::SimpleTupleStreamTest::block_mgr_parent_tracker_, impala::SimpleTupleStreamTest::exec_env_, impala::SimpleTupleStreamTest::mem_pool_, and impala::SimpleTupleStreamTest::runtime_state_.
void impala::SimpleTupleStreamTest::TestIntValuesInterleaved (int num_batches, int num_batches_before_read) inline protected inherited
Definition at line 347 of file buffered-tuple-stream-test.cc.
References BATCH_SIZE, impala::SimpleTupleStreamTest::block_mgr_, impala::SimpleTupleStreamTest::client_, impala::SimpleTupleStreamTest::CreateIntBatch(), impala::RowBatch::GetRow(), impala::SimpleTupleStreamTest::int_desc_, impala::RowBatch::num_rows(), impala::SimpleTupleStreamTest::ReadValues(), impala::RowBatch::Reset(), impala::SimpleTupleStreamTest::runtime_state_, and impala::RowDescriptor::tuple_descriptors().
template<typename T > void impala::SimpleTupleStreamTest::TestValues (int num_batches, RowDescriptor * desc, bool gen_null) inline protected inherited
Definition at line 299 of file buffered-tuple-stream-test.cc.
References BATCH_SIZE, impala::SimpleTupleStreamTest::block_mgr_, impala::SimpleTupleStreamTest::client_, impala::SimpleTupleStreamTest::CreateIntBatch(), impala::SimpleTupleStreamTest::CreateStringBatch(), impala::Status::GetDetail(), impala::RowBatch::GetRow(), impala::RowBatch::num_rows(), offset, impala::SimpleTupleStreamTest::ReadValues(), impala::RowBatch::Reset(), impala::SimpleTupleStreamTest::runtime_state_, and impala::SimpleTupleStreamTest::VerifyResults().
virtual void impala::SimpleTupleStreamTest::VerifyResults (const vector< int > & results, int exp_rows, bool gen_null) inline protected virtual inherited
Definition at line 231 of file buffered-tuple-stream-test.cc.
References impala::SimpleTupleStreamTest::int_desc_, and impala::RowDescriptor::tuple_descriptors().
Referenced by impala::SimpleTupleStreamTest::TestValues().
virtual void impala::SimpleTupleStreamTest::VerifyResults (const vector< StringValue > & results, int exp_rows, bool gen_null) inline protected virtual inherited
Definition at line 263 of file buffered-tuple-stream-test.cc.
References gen_ir_descriptions::idx, impala::NUM_STRINGS, impala::SimpleTupleStreamTest::string_desc_, impala::STRINGS, and impala::RowDescriptor::tuple_descriptors().
Member Data Documentation
shared_ptr<BufferedBlockMgr> impala::SimpleTupleStreamTest::block_mgr_ protected inherited
Definition at line 391 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::CreateMgr(), impala::SimpleTupleStreamTest::TearDown(), impala::SimpleTupleStreamTest::TestIntValuesInterleaved(), and impala::SimpleTupleStreamTest::TestValues().
scoped_ptr<MemTracker> impala::SimpleTupleStreamTest::block_mgr_parent_tracker_ protected inherited
Definition at line 389 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::TearDown().
BufferedBlockMgr::Client* impala::SimpleTupleStreamTest::client_ protected inherited
Definition at line 392 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::CreateMgr(), impala::SimpleTupleStreamTest::TestIntValuesInterleaved(), and impala::SimpleTupleStreamTest::TestValues().
scoped_ptr<ExecEnv> impala::SimpleTupleStreamTest::exec_env_ protected inherited
Definition at line 387 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::SetUp(), and impala::SimpleTupleStreamTest::TearDown().
RowDescriptor* impala::SimpleTupleStreamTest::int_desc_ protected inherited
Definition at line 396 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::AppendRowTuples(), impala::SimpleTupleStreamTest::CreateDescriptors(), CreateDescriptors(), impala::MultiTupleStreamTest::CreateDescriptors(), impala::MultiNullableTupleStreamTest::CreateDescriptors(), impala::SimpleTupleStreamTest::CreateIntBatch(), impala::SimpleTupleStreamTest::TestIntValuesInterleaved(), and impala::SimpleTupleStreamTest::VerifyResults().
scoped_ptr<MemPool> impala::SimpleTupleStreamTest::mem_pool_ protected inherited
Definition at line 398 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::AppendValue(), impala::SimpleTupleStreamTest::SetUp(), and impala::SimpleTupleStreamTest::TearDown().
ObjectPool impala::SimpleTupleStreamTest::pool_ protected inherited
Definition at line 395 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::CreateDescriptors(), CreateDescriptors(), impala::MultiTupleStreamTest::CreateDescriptors(), impala::MultiNullableTupleStreamTest::CreateDescriptors(), impala::SimpleTupleStreamTest::CreateIntBatch(), and impala::SimpleTupleStreamTest::CreateStringBatch().
scoped_ptr<RuntimeState> impala::SimpleTupleStreamTest::runtime_state_ protected inherited
Definition at line 388 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::CreateMgr(), impala::SimpleTupleStreamTest::SetUp(), impala::SimpleTupleStreamTest::TearDown(), impala::SimpleTupleStreamTest::TestIntValuesInterleaved(), and impala::SimpleTupleStreamTest::TestValues().
RowDescriptor* impala::SimpleTupleStreamTest::string_desc_ protected inherited
Definition at line 397 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::AppendRowTuples(), impala::SimpleTupleStreamTest::CreateDescriptors(), CreateDescriptors(), impala::MultiTupleStreamTest::CreateDescriptors(), impala::MultiNullableTupleStreamTest::CreateDescriptors(), impala::SimpleTupleStreamTest::CreateStringBatch(), and impala::SimpleTupleStreamTest::VerifyResults().
MemTracker impala::SimpleTupleStreamTest::tracker_ protected inherited
Definition at line 394 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::CreateIntBatch(), impala::SimpleTupleStreamTest::CreateMgr(), impala::SimpleTupleStreamTest::CreateStringBatch(), impala::SimpleTupleStreamTest::ReadValues(), and impala::SimpleTupleStreamTest::SetUp().
The documentation for this class was generated from the following file:
be/src/runtime/buffered-tuple-stream-test.cc