Impala: impala::HBaseTableDescriptor Class Reference
impala::HBaseTableDescriptor Class Reference
#include <descriptors.h>
Classes
struct HBaseColumnDescriptor
Public Member Functions
HBaseTableDescriptor (const TTableDescriptor &tdesc)
virtual std::string DebugString () const
const std::string table_name () const
const std::vector
< HBaseColumnDescriptor > & cols () const
int num_cols () const
int num_clustering_cols () const
bool IsClusteringCol (const SlotDescriptor *slot_desc) const
const std::string & name () const
const std::string & database () const
const std::vector< std::string > & col_names () const
Protected Attributes
std::string table_name_
native name of hbase table
std::vector
< HBaseColumnDescriptor > cols_
List of family/qualifier pairs.
std::string name_
std::string database_
TableId id_
int num_cols_
int num_clustering_cols_
std::vector< std::string > col_names_
Detailed Description
Definition at line 263 of file descriptors.h.
Constructor & Destructor Documentation
impala::HBaseTableDescriptor::HBaseTableDescriptor (const TTableDescriptor & tdesc)
Definition at line 209 of file descriptors.cc.
References cols_.
Member Function Documentation
const std::vector<std::string>& impala::TableDescriptor::col_names () const inline inherited
Definition at line 165 of file descriptors.h.
References impala::TableDescriptor::col_names_.
Referenced by impala::HdfsParquetTableWriter::AddRowGroup(), impala::HdfsParquetTableWriter::CreateSchema(), impala::HdfsParquetTableWriter::FlushCurrentRowGroup(), impala::HdfsTableSink::InitOutputPartition(), impala::DataSourceScanNode::Open(), impala::HdfsTableSink::PrepareExprs(), and impala::HdfsAvroScanner::VerifyTypesMatch().
const std::vector<HBaseColumnDescriptor>& impala::HBaseTableDescriptor::cols () const inline
Definition at line 281 of file descriptors.h.
References cols_.
Referenced by impala::HBaseTableWriter::AppendRowBatch(), and impala::HBaseTableWriter::Init().
const std::string& impala::TableDescriptor::database () const inline inherited
Definition at line 164 of file descriptors.h.
References impala::TableDescriptor::database_.
Referenced by impala::HdfsScanNode::StopAndFinalizeCounters().
string impala::HBaseTableDescriptor::DebugString () const virtual
Reimplemented from impala::TableDescriptor.
Definition at line 220 of file descriptors.cc.
References cols_, impala::TableDescriptor::DebugString(), and table_name_.
bool impala::TableDescriptor::IsClusteringCol (const SlotDescriptor * slot_desc) const inline inherited
The first num_clustering_cols_ columns by position are clustering columns.
Definition at line 158 of file descriptors.h.
References impala::SlotDescriptor::col_path(), and impala::TableDescriptor::num_clustering_cols_.
const std::string& impala::TableDescriptor::name () const inline inherited
Definition at line 163 of file descriptors.h.
References impala::TableDescriptor::name_.
Referenced by impala::HBaseTableWriter::Init(), impala::DataSourceScanNode::Open(), and impala::HdfsScanNode::StopAndFinalizeCounters().
int impala::TableDescriptor::num_clustering_cols () const inline inherited
Definition at line 153 of file descriptors.h.
References impala::TableDescriptor::num_clustering_cols_.
Referenced by impala::HdfsParquetTableWriter::AddRowGroup(), impala::HdfsSequenceTableWriter::AppendRowBatch(), impala::HdfsTextTableWriter::AppendRowBatch(), impala::HdfsAvroTableWriter::ConsumeRow(), impala::HdfsParquetTableWriter::CreateSchema(), impala::HdfsSequenceTableWriter::EncodeRow(), impala::HdfsParquetTableWriter::FlushCurrentRowGroup(), impala::HdfsTableWriter::HdfsTableWriter(), impala::HdfsParquetTableWriter::Init(), impala::HdfsScanNode::num_partition_keys(), and impala::HdfsTableSink::PrepareExprs().
int impala::TableDescriptor::num_cols () const inline inherited
Definition at line 152 of file descriptors.h.
References impala::TableDescriptor::num_cols_.
Referenced by impala::HBaseTableWriter::AppendRowBatch(), impala::HdfsSequenceTableWriter::AppendRowBatch(), impala::HdfsTextTableWriter::AppendRowBatch(), impala::HdfsAvroTableWriter::ConsumeRow(), impala::HdfsSequenceTableWriter::EncodeRow(), impala::HdfsTableWriter::HdfsTableWriter(), impala::HBaseTableWriter::Init(), impala::HdfsParquetTableWriter::Init(), impala::HdfsTextScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsRCFileScanner::InitNewRange(), impala::HdfsTableSink::PrepareExprs(), and impala::HdfsAvroScanner::ResolveSchemas().
const std::string impala::HBaseTableDescriptor::table_name () const inline
Definition at line 267 of file descriptors.h.
References table_name_.
Referenced by impala::HBaseScanNode::GetNext().
Member Data Documentation
std::vector<std::string> impala::TableDescriptor::col_names_ protected inherited
Definition at line 173 of file descriptors.h.
Referenced by impala::TableDescriptor::col_names(), and impala::TableDescriptor::DebugString().
std::vector<HBaseColumnDescriptor> impala::HBaseTableDescriptor::cols_ protected
List of family/qualifier pairs.
Definition at line 288 of file descriptors.h.
Referenced by cols(), DebugString(), and HBaseTableDescriptor().
std::string impala::TableDescriptor::database_ protected inherited
Definition at line 169 of file descriptors.h.
Referenced by impala::TableDescriptor::database().
TableId impala::TableDescriptor::id_ protected inherited
Definition at line 170 of file descriptors.h.
std::string impala::TableDescriptor::name_ protected inherited
Definition at line 168 of file descriptors.h.
Referenced by impala::TableDescriptor::name().
int impala::TableDescriptor::num_clustering_cols_ protected inherited
Definition at line 172 of file descriptors.h.
Referenced by impala::TableDescriptor::DebugString(), impala::TableDescriptor::IsClusteringCol(), and impala::TableDescriptor::num_clustering_cols().
int impala::TableDescriptor::num_cols_ protected inherited
Definition at line 171 of file descriptors.h.
Referenced by impala::TableDescriptor::DebugString(), and impala::TableDescriptor::num_cols().
std::string impala::HBaseTableDescriptor::table_name_ protected
native name of hbase table
Definition at line 285 of file descriptors.h.
Referenced by DebugString(), and table_name().
The documentation for this class was generated from the following files:
be/src/runtime/descriptors.h
be/src/runtime/descriptors.cc