Impala: com.cloudera.impala.catalog.RowFormat Class Reference
com.cloudera.impala.catalog.RowFormat Class Reference
Public Member Functions
RowFormat (String fieldDelimiter, String lineDelimiter, String escapeChar)
String getFieldDelimiter ()
String getLineDelimiter ()
String getEscapeChar ()
boolean isDefault ()
TTableRowFormat toThrift ()
Static Public Member Functions
static RowFormat fromThrift (TTableRowFormat tableRowFormat)
static RowFormat fromStorageDescriptor (StorageDescriptor sd)
Static Public Attributes
static final RowFormat DEFAULT_ROW_FORMAT = new RowFormat(null, null, null)
Private Member Functions
RowFormat (String fieldDelimiter, String lineDelimiter, String escapeChar, boolean unescape)
Static Private Member Functions
static String getUnescapedValueOrNull (String value)
Private Attributes
final String fieldDelimiter_
final String lineDelimiter_
final String escapeChar_
Detailed Description
Defines the physical (on-disk) format for a table's data. This is used when creating a new table to specify how to interpret the fields (columns) and lines (rows) in a a data file.
Definition at line 30 of file RowFormat.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.RowFormat.RowFormat (String fieldDelimiter, String lineDelimiter, String escapeChar, boolean unescape) inline private
Definition at line 38 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.escapeChar_, com.cloudera.impala.catalog.RowFormat.fieldDelimiter_, com.cloudera.impala.catalog.RowFormat.getUnescapedValueOrNull(), and com.cloudera.impala.catalog.RowFormat.lineDelimiter_.
Referenced by com.cloudera.impala.catalog.RowFormat.fromStorageDescriptor(), and com.cloudera.impala.catalog.RowFormat.fromThrift().
com.cloudera.impala.catalog.RowFormat.RowFormat (String fieldDelimiter, String lineDelimiter, String escapeChar) inline
Creates a new instance of the RowFormat class, unescaping the values of field delimiter, line delimiter, and escape char.
Definition at line 55 of file RowFormat.java.
Member Function Documentation
static RowFormat com.cloudera.impala.catalog.RowFormat.fromStorageDescriptor (StorageDescriptor sd) inline static
Returns the RowFormat for the storage descriptor.
Definition at line 100 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.RowFormat().
static RowFormat com.cloudera.impala.catalog.RowFormat.fromThrift (TTableRowFormat tableRowFormat) inline static
Definition at line 87 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.DEFAULT_ROW_FORMAT, and com.cloudera.impala.catalog.RowFormat.RowFormat().
Referenced by com.cloudera.impala.service.CatalogOpExecutor.createMetaStoreTable().
String com.cloudera.impala.catalog.RowFormat.getEscapeChar () inline
Definition at line 67 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.escapeChar_.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.analyze(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd(), com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.catalog.RowFormat.toThrift().
String com.cloudera.impala.catalog.RowFormat.getFieldDelimiter () inline
Definition at line 59 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.fieldDelimiter_.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.analyze(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd(), com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.catalog.RowFormat.toThrift().
String com.cloudera.impala.catalog.RowFormat.getLineDelimiter () inline
Definition at line 63 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.lineDelimiter_.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.analyze(), com.cloudera.impala.catalog.HiveStorageDescriptorFactory.createSd(), com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.catalog.RowFormat.toThrift().
static String com.cloudera.impala.catalog.RowFormat.getUnescapedValueOrNull (String value) inline static private
Definition at line 75 of file RowFormat.java.
Referenced by com.cloudera.impala.catalog.RowFormat.RowFormat().
boolean com.cloudera.impala.catalog.RowFormat.isDefault () inline
Definition at line 71 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.escapeChar_, com.cloudera.impala.catalog.RowFormat.fieldDelimiter_, and com.cloudera.impala.catalog.RowFormat.lineDelimiter_.
Referenced by com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql().
TTableRowFormat com.cloudera.impala.catalog.RowFormat.toThrift () inline
Definition at line 79 of file RowFormat.java.
References com.cloudera.impala.catalog.RowFormat.getEscapeChar(), com.cloudera.impala.catalog.RowFormat.getFieldDelimiter(), and com.cloudera.impala.catalog.RowFormat.getLineDelimiter().
Member Data Documentation
final RowFormat com.cloudera.impala.catalog.RowFormat.DEFAULT_ROW_FORMAT = new RowFormat(null, null, null) static
Definition at line 32 of file RowFormat.java.
Referenced by com.cloudera.impala.analysis.CreateTableDataSrcStmt.CreateTableDataSrcStmt(), com.cloudera.impala.catalog.RowFormat.fromThrift(), com.cloudera.impala.service.CatalogOpExecutor.setStorageDescriptorFileFormat(), and com.cloudera.impala.catalog.HdfsStorageDescriptorTest.testDelimiters().
final String com.cloudera.impala.catalog.RowFormat.escapeChar_ private
Definition at line 36 of file RowFormat.java.
Referenced by com.cloudera.impala.catalog.RowFormat.getEscapeChar(), com.cloudera.impala.catalog.RowFormat.isDefault(), and com.cloudera.impala.catalog.RowFormat.RowFormat().
final String com.cloudera.impala.catalog.RowFormat.fieldDelimiter_ private
Definition at line 34 of file RowFormat.java.
Referenced by com.cloudera.impala.catalog.RowFormat.getFieldDelimiter(), com.cloudera.impala.catalog.RowFormat.isDefault(), and com.cloudera.impala.catalog.RowFormat.RowFormat().
final String com.cloudera.impala.catalog.RowFormat.lineDelimiter_ private
Definition at line 35 of file RowFormat.java.
Referenced by com.cloudera.impala.catalog.RowFormat.getLineDelimiter(), com.cloudera.impala.catalog.RowFormat.isDefault(), and com.cloudera.impala.catalog.RowFormat.RowFormat().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/RowFormat.java