Impala: com.cloudera.impala.catalog.DataSourceTable Class Reference
com.cloudera.impala.catalog.DataSourceTable Class Reference
Public Member Functions
TDataSource getDataSource ()
String getInitString ()
int getNumNodes ()
TCatalogObjectType getCatalogObjectType ()
void load (Table oldValue, HiveMetaStoreClient client, org.apache.hadoop.hive.metastore.api.Table msTbl) throws TableLoadingException
TResultSet getTableStats ()
TTableDescriptor toThriftDescriptor (Set< Long > referencedPartitions)
TTable toThrift ()
void addColumn (Column col)
void clearColumns ()
void updateLastDdlTime (long ddlTime)
void validate () throws TableLoadingException
TCatalogObject toTCatalogObject ()
Db getDb ()
String getName ()
String getFullName ()
TableName getTableName ()
String getOwner ()
ArrayList< Column > getColumns ()
List< String > getColumnNames ()
String getStorageHandlerClassName ()
ArrayList< Column > getColumnsInHiveOrder ()
List< Column > getNonClusteringColumns ()
Column getColumn (String name)
org.apache.hadoop.hive.metastore.api.Table getMetaStoreTable ()
int getNumClusteringCols ()
TableId getId ()
long getNumRows ()
ArrayType getType ()
long getCatalogVersion ()
void setCatalogVersion (long catalogVersion)
boolean isLoaded ()
Static Public Member Functions
static boolean isSupportedColumnType (Type colType)
static boolean isSupportedPrimitiveType (PrimitiveType primitiveType)
static boolean isDataSourceTable (org.apache.hadoop.hive.metastore.api.Table msTbl)
static Table fromMetastoreTable (TableId id, Db db, org.apache.hadoop.hive.metastore.api.Table msTbl)
static Table fromThrift (Db parentDb, TTable thriftTable) throws TableLoadingException
Static Public Attributes
static final String TBL_PROP_DATA_SRC_NAME = "__IMPALA_DATA_SOURCE_NAME"
static final String TBL_PROP_INIT_STRING = "__IMPALA_DATA_SOURCE_INIT_STRING"
static final String TBL_PROP_LOCATION = "__IMPALA_DATA_SOURCE_LOCATION"
static final String TBL_PROP_CLASS = "__IMPALA_DATA_SOURCE_CLASS"
static final String TBL_PROP_API_VER = "__IMPALA_DATA_SOURCE_API_VERSION"
Protected Member Functions
DataSourceTable (TableId id, org.apache.hadoop.hive.metastore.api.Table msTable, Db db, String name, String owner)
void loadFromThrift (TTable thriftTable) throws TableLoadingException
List< String > getColumnNamesWithHmsStats ()
void loadAllColumnStats (HiveMetaStoreClient client)
Type parseColumnType (FieldSchema fs) throws TableLoadingException
Static Protected Member Functions
static long getRowCount (Map< String, String > parameters)
Protected Attributes
final
org.apache.hadoop.hive.metastore.api.Table msTable_
final TableId id_
final Db db_
final String name_
final String owner_
TTableDescriptor tableDesc_
List< FieldSchema > fields_
TAccessLevel accessLevel_ = TAccessLevel.READ_WRITE
int numClusteringCols_
long numRows_ = -1
final ArrayType type_ = new ArrayType(new StructType())
long lastDdlTime_
Static Protected Attributes
static EnumSet< TableType > SUPPORTED_TABLE_TYPES
Private Member Functions
void loadColumns (List< FieldSchema > fieldSchemas, HiveMetaStoreClient client) throws TableLoadingException
String getRequiredTableProperty (org.apache.hadoop.hive.metastore.api.Table msTbl, String key, String dataSourceName) throws TableLoadingException
TDataSourceTable getDataSourceTable ()
Private Attributes
String initString_
TDataSource dataSource_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(DataSourceTable.class)
Detailed Description
Represents a table backed by an external data source. All data source properties are stored as table properties (persisted in the metastore) because the DataSource catalog object is not persisted so the DataSource catalog object will not exist if the catalog server is restarted, but the table does not need the DataSource catalog object in order to scan the table. Tables that contain the TBL_PROP_DATA_SRC_NAME table parameter are assumed to be backed by an external data source.
Definition at line 46 of file DataSourceTable.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.DataSourceTable.DataSourceTable (TableId id, org.apache.hadoop.hive.metastore.api.Table msTable, Db db, String name, String owner) inline protected
Definition at line 77 of file DataSourceTable.java.
Member Function Documentation
void com.cloudera.impala.catalog.Table.addColumn (Column col) inline inherited
Definition at line 114 of file Table.java.
References com.cloudera.impala.catalog.ArrayType.getItemType(), and com.cloudera.impala.catalog.Table.type_.
Referenced by com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.DataSourceTable.loadColumns(), and com.cloudera.impala.catalog.HdfsTable.loadColumns().
void com.cloudera.impala.catalog.Table.clearColumns () inline inherited
Definition at line 121 of file Table.java.
References com.cloudera.impala.catalog.ArrayType.getItemType(), and com.cloudera.impala.catalog.Table.type_.
Referenced by com.cloudera.impala.catalog.HBaseTable.load().
static Table com.cloudera.impala.catalog.Table.fromMetastoreTable (TableId id, Db db, org.apache.hadoop.hive.metastore.api.Table msTbl) inline static inherited
Creates a table of the appropriate type based on the given hive.metastore.api.Table object.
Definition at line 207 of file Table.java.
References com.cloudera.impala.catalog.DataSourceTable.isDataSourceTable(), com.cloudera.impala.catalog.HBaseTable.isHBaseTable(), and com.cloudera.impala.catalog.HdfsFileFormat.isHdfsFormatClass().
static Table com.cloudera.impala.catalog.Table.fromThrift (Db parentDb, TTable thriftTable) throws TableLoadingException inline static inherited
Factory method that creates a new Table from its Thrift representation. Determines the type of table to create based on the Thrift table provided.
Definition at line 231 of file Table.java.
TCatalogObjectType com.cloudera.impala.catalog.DataSourceTable.getCatalogObjectType () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 97 of file DataSourceTable.java.
long com.cloudera.impala.catalog.Table.getCatalogVersion () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 408 of file Table.java.
References com.cloudera.impala.catalog.Table.catalogVersion_.
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.dropPartition(), com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects(), com.cloudera.impala.catalog.ImpaladCatalog.removeTable(), com.cloudera.impala.catalog.CatalogServiceCatalog.replaceTableIfUnchanged(), and com.cloudera.impala.catalog.Table.toTCatalogObject().
Column com.cloudera.impala.catalog.Table.getColumn (String name) inline inherited
Case-insensitive lookup.
Definition at line 392 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.loadAllColumnStats(), and com.cloudera.impala.catalog.CatalogTest.testColStatsColTypeMismatch().
List<String> com.cloudera.impala.catalog.Table.getColumnNames () inline inherited
Returns a list of the column names ordered by position.
Definition at line 354 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByPos_.
Referenced by com.cloudera.impala.analysis.ColumnLineageGraph.addTargetColumnLabels(), com.cloudera.impala.catalog.HdfsTable.getTHdfsTable(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
List<String> com.cloudera.impala.catalog.Table.getColumnNamesWithHmsStats () inline protected inherited
Definition at line 144 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByName_, and impala.name.
Referenced by com.cloudera.impala.catalog.Table.loadAllColumnStats().
ArrayList<Column> com.cloudera.impala.catalog.Table.getColumns () inline inherited
Definition at line 349 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByPos_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableOrViewRename(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.catalog.HdfsTable.createPartition(), com.cloudera.impala.catalog.HdfsTable.dropPartition(), com.cloudera.impala.catalog.HdfsTable.getColumnNamesWithHmsStats(), com.cloudera.impala.catalog.HBaseTable.getColumnsInHiveOrder(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.HBaseTable.getTHBaseTable(), com.cloudera.impala.analysis.InsertStmt.prepareExpressions(), com.cloudera.impala.catalog.HdfsTable.resetPartitionMd(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.updatePartitionMdAndColStats().
ArrayList<Column> com.cloudera.impala.catalog.Table.getColumnsInHiveOrder () inline inherited
Returns the list of all columns, but with partition columns at the end of the list rather than the beginning. This is equivalent to the order in which Hive enumerates columns.
Definition at line 373 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByPos_, com.cloudera.impala.catalog.Table.getNonClusteringColumns(), and com.cloudera.impala.catalog.Table.numClusteringCols_.
Referenced by com.cloudera.impala.service.DescribeResultFactory.describeTableMinimal(), com.cloudera.impala.service.Frontend.getColumnStats(), and com.cloudera.impala.analysis.InsertStmt.prepareExpressions().
TDataSource com.cloudera.impala.catalog.DataSourceTable.getDataSource () inline
Gets the the data source.
Definition at line 86 of file DataSourceTable.java.
References com.cloudera.impala.catalog.DataSourceTable.dataSource_.
Referenced by com.cloudera.impala.planner.DataSourceScanNode.prepareDataSource(), and com.cloudera.impala.planner.DataSourceScanNode.toThrift().
TDataSourceTable com.cloudera.impala.catalog.DataSourceTable.getDataSourceTable () inline private
Returns a thrift TDataSourceTable structure for the data source table.
Definition at line 243 of file DataSourceTable.java.
References com.cloudera.impala.catalog.DataSourceTable.dataSource_, and com.cloudera.impala.catalog.DataSourceTable.initString_.
Referenced by com.cloudera.impala.catalog.DataSourceTable.toThrift(), and com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor().
Db com.cloudera.impala.catalog.Table.getDb () inline inherited
Definition at line 341 of file Table.java.
References com.cloudera.impala.catalog.Table.db_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableUpdateStats(), com.cloudera.impala.service.CatalogOpExecutor.createHiveColStats(), com.cloudera.impala.analysis.Analyzer.getTable(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), com.cloudera.impala.analysis.ShowStatsStmt.toThrift(), com.cloudera.impala.analysis.ComputeStatsStmt.toThrift(), and com.cloudera.impala.service.CatalogOpExecutor.updateCatalog().
String com.cloudera.impala.catalog.Table.getFullName () inline inherited
Definition at line 343 of file Table.java.
References com.cloudera.impala.catalog.Table.db_, com.cloudera.impala.catalog.Db.getName(), and com.cloudera.impala.catalog.Table.name_.
Referenced by com.cloudera.impala.analysis.ShowPartitionsStmt.analyze(), com.cloudera.impala.analysis.ShowStatsStmt.analyze(), com.cloudera.impala.analysis.ShowFilesStmt.analyze(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), com.cloudera.impala.analysis.TableRef.analyze(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.analysis.Analyzer.getTable(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.loadAllColumnStats(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), com.cloudera.impala.catalog.HdfsTable.loadDiskIds(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
TableId com.cloudera.impala.catalog.Table.getId () inline inherited
Definition at line 403 of file Table.java.
References com.cloudera.impala.catalog.Table.id_.
Referenced by com.cloudera.impala.planner.HBaseTableSink.toThrift(), and com.cloudera.impala.planner.HdfsTableSink.toThrift().
String com.cloudera.impala.catalog.DataSourceTable.getInitString () inline
Gets the table init string passed to the data source.
Definition at line 91 of file DataSourceTable.java.
References com.cloudera.impala.catalog.DataSourceTable.initString_.
Referenced by com.cloudera.impala.planner.DataSourceScanNode.debugString().
org.apache.hadoop.hive.metastore.api.Table com.cloudera.impala.catalog.Table.getMetaStoreTable () inline inherited
Returns the metastore.api.Table object this Table was created from. Returns null if the derived Table object was not created from a metastore Table (ex. InlineViews).
Definition at line 398 of file Table.java.
References com.cloudera.impala.catalog.Table.msTable_.
Referenced by com.cloudera.impala.catalog.HdfsTable.getFirstLocationWithoutWriteAccess(), com.cloudera.impala.catalog.HdfsTable.getPartitionFromThriftPartitionSpec(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.HBaseTable.loadFromThrift(), com.cloudera.impala.catalog.HdfsTable.loadFromThrift(), and com.cloudera.impala.catalog.Table.toThrift().
String com.cloudera.impala.catalog.Table.getName () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 342 of file Table.java.
References com.cloudera.impala.catalog.Table.name_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableUpdateStats(), com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.service.CatalogOpExecutor.createHiveColStats(), com.cloudera.impala.catalog.HdfsTable.createPartition(), com.cloudera.impala.catalog.HdfsPartition.fromThrift(), com.cloudera.impala.analysis.Analyzer.getTable(), com.cloudera.impala.analysis.InlineViewRef.InlineViewRef(), com.cloudera.impala.catalog.Table.parseColumnType(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), com.cloudera.impala.analysis.ShowStatsStmt.toThrift(), com.cloudera.impala.analysis.ComputeStatsStmt.toThrift(), com.cloudera.impala.service.CatalogOpExecutor.updateCatalog(), and com.cloudera.impala.analysis.WithClause.WithClause().
List<Column> com.cloudera.impala.catalog.Table.getNonClusteringColumns () inline inherited
Returns the list of all columns excluding any partition columns.
Definition at line 385 of file Table.java.
References com.cloudera.impala.catalog.Table.numClusteringCols_.
Referenced by com.cloudera.impala.analysis.ComputeStatsStmt.analyze(), and com.cloudera.impala.catalog.Table.getColumnsInHiveOrder().
int com.cloudera.impala.catalog.Table.getNumClusteringCols () inline inherited
Definition at line 402 of file Table.java.
References com.cloudera.impala.catalog.Table.numClusteringCols_.
Referenced by com.cloudera.impala.analysis.ShowPartitionsStmt.analyze(), com.cloudera.impala.analysis.ComputeStatsStmt.analyze(), com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.service.CatalogOpExecutor.dropTableOrView(), com.cloudera.impala.analysis.ComputeStatsStmt.getBaseColumnStatsQuerySelectList(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.catalog.HdfsTable.getNonPartitionFieldSchemas(), com.cloudera.impala.planner.HdfsScanNode.prunePartitions(), and com.cloudera.impala.service.CatalogOpExecutor.updateCatalog().
int com.cloudera.impala.catalog.DataSourceTable.getNumNodes () inline
Definition at line 94 of file DataSourceTable.java.
long com.cloudera.impala.catalog.Table.getNumRows () inline inherited
Definition at line 404 of file Table.java.
References com.cloudera.impala.catalog.Table.numRows_.
Referenced by com.cloudera.impala.analysis.IsNullPredicate.analyze().
String com.cloudera.impala.catalog.Table.getOwner () inline inherited
Definition at line 348 of file Table.java.
References com.cloudera.impala.catalog.Table.owner_.
String com.cloudera.impala.catalog.DataSourceTable.getRequiredTableProperty (org.apache.hadoop.hive.metastore.api.Table msTbl, String key, String dataSourceName) throws TableLoadingException inline private
Definition at line 191 of file DataSourceTable.java.
References com.cloudera.impala.catalog.Table.name_.
Referenced by com.cloudera.impala.catalog.DataSourceTable.load().
static long com.cloudera.impala.catalog.Table.getRowCount (Map< String, String > parameters) inline static protected inherited
Returns the value of the ROW_COUNT constant, or -1 if not found.
Definition at line 191 of file Table.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), and com.cloudera.impala.catalog.HdfsTable.loadPartitions().
String com.cloudera.impala.catalog.Table.getStorageHandlerClassName () inline inherited
Subclasses should override this if they provide a storage handler class. Currently only HBase tables need to provide a storage handler.
Definition at line 366 of file Table.java.
TableName com.cloudera.impala.catalog.Table.getTableName () inline inherited
Definition at line 344 of file Table.java.
References com.cloudera.impala.catalog.Table.db_, com.cloudera.impala.catalog.Db.getName(), and com.cloudera.impala.catalog.Table.name_.
Referenced by com.cloudera.impala.analysis.ComputeStatsStmt.analyze(), com.cloudera.impala.service.CatalogOpExecutor.dropStats(), and com.cloudera.impala.analysis.InlineViewRef.InlineViewRef().
TResultSet com.cloudera.impala.catalog.DataSourceTable.getTableStats () inline
Returns statistics on this table as a tabular result set. Used for the SHOW TABLE STATS statement. The schema of the returned TResultSet is set inside this method.
Definition at line 208 of file DataSourceTable.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Table.numRows_, and com.cloudera.impala.catalog.ScalarType.toThrift().
ArrayType com.cloudera.impala.catalog.Table.getType () inline inherited
Definition at line 405 of file Table.java.
References com.cloudera.impala.catalog.Table.type_.
Referenced by com.cloudera.impala.catalog.HdfsTable.load().
static boolean com.cloudera.impala.catalog.DataSourceTable.isDataSourceTable (org.apache.hadoop.hive.metastore.api.Table msTbl) inline static
True if the Hive org.apache.hadoop.hive.metastore.api.Table is a data source table by checking for the existance of the TBL_PROP_DATA_SRC_NAME table property.
Definition at line 252 of file DataSourceTable.java.
References com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_DATA_SRC_NAME.
Referenced by com.cloudera.impala.catalog.Table.fromMetastoreTable().
boolean com.cloudera.impala.catalog.Table.isLoaded () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 416 of file Table.java.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.getExistingTable(), com.cloudera.impala.service.Frontend.getMissingTbls(), com.cloudera.impala.catalog.CatalogServiceCatalog.getOrLoadTable(), com.cloudera.impala.testutil.ImpaladTestCatalog.getTable(), com.cloudera.impala.catalog.ImpaladCatalog.getTable(), and com.cloudera.impala.analysis.Analyzer.getTable().
static boolean com.cloudera.impala.catalog.DataSourceTable.isSupportedColumnType (Type colType) inline static
Returns true if the column type is supported.
Definition at line 102 of file DataSourceTable.java.
References com.cloudera.impala.catalog.Type.getPrimitiveType(), and com.cloudera.impala.catalog.DataSourceTable.isSupportedPrimitiveType().
Referenced by com.cloudera.impala.analysis.CreateTableDataSrcStmt.analyze(), and com.cloudera.impala.catalog.DataSourceTable.loadColumns().
static boolean com.cloudera.impala.catalog.DataSourceTable.isSupportedPrimitiveType (PrimitiveType primitiveType) inline static
Returns true if the primitive type is supported.
Definition at line 110 of file DataSourceTable.java.
References impala.INVALID_TYPE.
Referenced by com.cloudera.impala.catalog.DataSourceTable.isSupportedColumnType(), and com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable().
void com.cloudera.impala.catalog.DataSourceTable.load (Table oldValue, HiveMetaStoreClient client, org.apache.hadoop.hive.metastore.api.Table msTbl) throws TableLoadingException inline
Definition at line 160 of file DataSourceTable.java.
References com.cloudera.impala.catalog.DataSourceTable.dataSource_, com.cloudera.impala.catalog.Table.getMetaStoreTable(), com.cloudera.impala.catalog.DataSourceTable.getRequiredTableProperty(), com.cloudera.impala.catalog.Table.getRowCount(), com.cloudera.impala.catalog.DataSourceTable.initString_, com.cloudera.impala.catalog.DataSourceTable.loadColumns(), com.cloudera.impala.catalog.Table.name_, com.cloudera.impala.catalog.Table.numClusteringCols_, com.cloudera.impala.catalog.Table.numRows_, com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_API_VER, com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_CLASS, com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_DATA_SRC_NAME, com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_INIT_STRING, and com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_LOCATION.
void com.cloudera.impala.catalog.Table.loadAllColumnStats (HiveMetaStoreClient client) inline protected inherited
Loads column statistics for all columns in this table from the Hive metastore. Any errors are logged and ignored, since the absence of column stats is not critical to the correctness of the system.
Definition at line 155 of file Table.java.
References com.cloudera.impala.catalog.Table.getColumn(), com.cloudera.impala.catalog.Table.getColumnNamesWithHmsStats(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Column.getType(), com.cloudera.impala.catalog.ColumnStats.isSupportedColType(), com.cloudera.impala.catalog.Table.name_, and com.cloudera.impala.catalog.Column.updateStats().
Referenced by com.cloudera.impala.catalog.HBaseTable.load(), and com.cloudera.impala.catalog.HdfsTable.loadColumns().
void com.cloudera.impala.catalog.DataSourceTable.loadColumns (List< FieldSchema > fieldSchemas, HiveMetaStoreClient client) throws TableLoadingException inline private
Create columns corresponding to fieldSchemas. Throws a TableLoadingException if the metadata is incompatible with what we support.
Definition at line 140 of file DataSourceTable.java.
References com.cloudera.impala.catalog.Table.addColumn(), com.cloudera.impala.catalog.Column.getType(), com.cloudera.impala.catalog.DataSourceTable.isSupportedColumnType(), and com.cloudera.impala.catalog.Table.parseColumnType().
Referenced by com.cloudera.impala.catalog.DataSourceTable.load().
void com.cloudera.impala.catalog.DataSourceTable.loadFromThrift (TTable thriftTable) throws TableLoadingException inline protected
Definition at line 152 of file DataSourceTable.java.
References com.cloudera.impala.catalog.DataSourceTable.dataSource_, and com.cloudera.impala.catalog.DataSourceTable.initString_.
Type com.cloudera.impala.catalog.Table.parseColumnType (FieldSchema fs) throws TableLoadingException inline protected inherited
Gets the ColumnType from the given FieldSchema by using Impala's SqlParser. Throws a TableLoadingException if the FieldSchema could not be parsed. The type can either be:
Supported by Impala, in which case the type is returned.
A type Impala understands but is not yet implemented (e.g. date), the type is returned but type.IsSupported() returns false.
A type Impala can't understand at all, and a TableLoadingException is thrown.
Definition at line 331 of file Table.java.
References com.cloudera.impala.catalog.Table.getName().
Referenced by com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.DataSourceTable.loadColumns(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), and com.cloudera.impala.catalog.HBaseTable.supportsBinaryEncoding().
void com.cloudera.impala.catalog.Table.setCatalogVersion (long catalogVersion) inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 411 of file Table.java.
References com.cloudera.impala.catalog.Table.catalogVersion_.
TCatalogObject com.cloudera.impala.catalog.Table.toTCatalogObject () inline inherited
Definition at line 314 of file Table.java.
References com.cloudera.impala.catalog.Table.getCatalogObjectType(), com.cloudera.impala.catalog.Table.getCatalogVersion(), and com.cloudera.impala.catalog.Table.toThrift().
TTable com.cloudera.impala.catalog.DataSourceTable.toThrift () inline
Returns a thrift structure representing the table.
Definition at line 233 of file DataSourceTable.java.
References com.cloudera.impala.catalog.DataSourceTable.getDataSourceTable().
TTableDescriptor com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor (Set< Long > referencedPartitions) inline
Definition at line 220 of file DataSourceTable.java.
References com.cloudera.impala.catalog.Table.db_, com.cloudera.impala.catalog.Table.getColumnNames(), com.cloudera.impala.catalog.Table.getColumns(), com.cloudera.impala.catalog.DataSourceTable.getDataSourceTable(), com.cloudera.impala.catalog.Db.getName(), com.cloudera.impala.catalog.Table.id_, com.cloudera.impala.catalog.Table.name_, and com.cloudera.impala.catalog.Table.numClusteringCols_.
void com.cloudera.impala.catalog.Table.updateLastDdlTime (long ddlTime) inline inherited
Updates the lastDdlTime for this Table, if the new value is greater than the existing value. Does nothing if the new value is less than or equal to the existing value.
Definition at line 132 of file Table.java.
References com.cloudera.impala.catalog.Table.lastDdlTime_.
void com.cloudera.impala.catalog.Table.validate () throws TableLoadingException inline inherited
Checks preconditions for this table to function as expected. Currently only checks that all entries in colsByName_ use lower case keys.
Definition at line 279 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByName_.
Member Data Documentation
TAccessLevel com.cloudera.impala.catalog.Table.accessLevel_ = TAccessLevel.READ_WRITE protected inherited
Definition at line 66 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.getFirstLocationWithoutWriteAccess(), com.cloudera.impala.catalog.HdfsTable.hasWriteAccess(), com.cloudera.impala.catalog.Table.loadFromThrift(), com.cloudera.impala.catalog.HdfsTable.loadPartitions(), and com.cloudera.impala.catalog.Table.toThrift().
TDataSource com.cloudera.impala.catalog.DataSourceTable.dataSource_ private
Definition at line 75 of file DataSourceTable.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.getDataSource(), com.cloudera.impala.catalog.DataSourceTable.getDataSourceTable(), com.cloudera.impala.catalog.DataSourceTable.load(), and com.cloudera.impala.catalog.DataSourceTable.loadFromThrift().
final Db com.cloudera.impala.catalog.Table.db_ protected inherited
Definition at line 61 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getDb(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Table.getTableName(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.Table(), com.cloudera.impala.catalog.IncompleteTable.toThrift(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
List<FieldSchema> com.cloudera.impala.catalog.Table.fields_ protected inherited
Definition at line 65 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.getFieldSchemas(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), and com.cloudera.impala.catalog.Table.loadFromThrift().
final TableId com.cloudera.impala.catalog.Table.id_ protected inherited
Definition at line 60 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getId(), com.cloudera.impala.catalog.Table.Table(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
String com.cloudera.impala.catalog.DataSourceTable.initString_ private
Definition at line 74 of file DataSourceTable.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.getDataSourceTable(), com.cloudera.impala.catalog.DataSourceTable.getInitString(), com.cloudera.impala.catalog.DataSourceTable.load(), and com.cloudera.impala.catalog.DataSourceTable.loadFromThrift().
long com.cloudera.impala.catalog.Table.lastDdlTime_ protected inherited
Definition at line 85 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.Table(), and com.cloudera.impala.catalog.Table.updateLastDdlTime().
final Logger com.cloudera.impala.catalog.DataSourceTable.LOG = LoggerFactory.getLogger(DataSourceTable.class) static private
Definition at line 47 of file DataSourceTable.java.
final org.apache.hadoop.hive.metastore.api.Table com.cloudera.impala.catalog.Table.msTable_ protected inherited
Definition at line 58 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getMetaStoreTable(), and com.cloudera.impala.catalog.Table.Table().
final String com.cloudera.impala.catalog.Table.name_ protected inherited
Definition at line 62 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Table.getName(), com.cloudera.impala.catalog.DataSourceTable.getRequiredTableProperty(), com.cloudera.impala.catalog.Table.getTableName(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.loadAllColumnStats(), com.cloudera.impala.catalog.HdfsTable.loadBlockMetadata(), com.cloudera.impala.catalog.HBaseTable.loadFromThrift(), com.cloudera.impala.catalog.Table.Table(), com.cloudera.impala.catalog.IncompleteTable.toThrift(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
int com.cloudera.impala.catalog.Table.numClusteringCols_ protected inherited
Definition at line 69 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.dropPartition(), com.cloudera.impala.catalog.HdfsTable.getColumnNamesWithHmsStats(), com.cloudera.impala.catalog.Table.getColumnsInHiveOrder(), com.cloudera.impala.catalog.Table.getNonClusteringColumns(), com.cloudera.impala.catalog.Table.getNumClusteringCols(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), com.cloudera.impala.catalog.Table.loadFromThrift(), com.cloudera.impala.catalog.HdfsTable.resetPartitionMd(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.updatePartitionMdAndColStats().
long com.cloudera.impala.catalog.Table.numRows_ = -1 protected inherited
Definition at line 72 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getNumRows(), com.cloudera.impala.catalog.DataSourceTable.getTableStats(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.loadFromThrift(), com.cloudera.impala.catalog.CatalogObjectToFromThriftTest.TestPartitionedTable(), and com.cloudera.impala.catalog.Table.toThrift().
final String com.cloudera.impala.catalog.Table.owner_ protected inherited
Definition at line 63 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getOwner(), and com.cloudera.impala.catalog.Table.Table().
EnumSet<TableType> com.cloudera.impala.catalog.Table.SUPPORTED_TABLE_TYPES static protected inherited
Initial value:
= EnumSet.of(
      TableType.EXTERNAL_TABLE, TableType.MANAGED_TABLE, TableType.VIRTUAL_VIEW)
Definition at line 88 of file Table.java.
TTableDescriptor com.cloudera.impala.catalog.Table.tableDesc_ protected inherited
Definition at line 64 of file Table.java.
final String com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_API_VER = "__IMPALA_DATA_SOURCE_API_VERSION" static
Table property key for the API version implemented by the data source.
Definition at line 72 of file DataSourceTable.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.load().
final String com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_CLASS = "__IMPALA_DATA_SOURCE_CLASS" static
Table property key for the class implementing ExternalDataSource.
Definition at line 67 of file DataSourceTable.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.load().
final String com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_DATA_SRC_NAME = "__IMPALA_DATA_SOURCE_NAME" static
Table property key for the data source name.
Definition at line 52 of file DataSourceTable.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.isDataSourceTable(), and com.cloudera.impala.catalog.DataSourceTable.load().
final String com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_INIT_STRING = "__IMPALA_DATA_SOURCE_INIT_STRING" static
Table property key for the table init string.
Definition at line 57 of file DataSourceTable.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.load().
final String com.cloudera.impala.catalog.DataSourceTable.TBL_PROP_LOCATION = "__IMPALA_DATA_SOURCE_LOCATION" static
Table property key for the data source library HDFS path.
Definition at line 62 of file DataSourceTable.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.load().
final ArrayType com.cloudera.impala.catalog.Table.type_ = new ArrayType(new StructType()) protected inherited
Definition at line 82 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.addColumn(), com.cloudera.impala.catalog.Table.clearColumns(), com.cloudera.impala.catalog.Table.getType(), and com.cloudera.impala.catalog.Table.loadFromThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/DataSourceTable.java