Impala: com.cloudera.impala.analysis.TypeDef Class Reference
com.cloudera.impala.analysis.TypeDef Class Reference
Public Member Functions
TypeDef (Type parsedType)
void analyze (Analyzer analyzer) throws AnalysisException
Type getType ()
String toString ()
String toSql ()
Private Member Functions
void analyze (Type type, Analyzer analyzer) throws AnalysisException
void analyzeScalarType (ScalarType scalarType, Analyzer analyzer) throws AnalysisException
void analyzeStructType (StructType structType, Analyzer analyzer) throws AnalysisException
void analyzeMapType (MapType mapType, Analyzer analyzer) throws AnalysisException
Private Attributes
boolean isAnalyzed_
final Type parsedType_
Detailed Description
Represents an anonymous type definition, e.g., used in DDL and CASTs.
Definition at line 35 of file TypeDef.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.TypeDef.TypeDef (Type parsedType) inline
Definition at line 39 of file TypeDef.java.
References com.cloudera.impala.analysis.TypeDef.parsedType_.
Member Function Documentation
void com.cloudera.impala.analysis.TypeDef.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 44 of file TypeDef.java.
References com.cloudera.impala.analysis.TypeDef.isAnalyzed_, and com.cloudera.impala.analysis.TypeDef.parsedType_.
Referenced by com.cloudera.impala.analysis.TypeDef.analyze(), com.cloudera.impala.analysis.TypeDef.analyzeMapType(), and com.cloudera.impala.analysis.TypeDef.analyzeStructType().
void com.cloudera.impala.analysis.TypeDef.analyze (Type type, Analyzer analyzer) throws AnalysisException inline private
Definition at line 50 of file TypeDef.java.
References com.cloudera.impala.analysis.TypeDef.analyze(), com.cloudera.impala.analysis.TypeDef.analyzeMapType(), com.cloudera.impala.analysis.TypeDef.analyzeScalarType(), com.cloudera.impala.analysis.TypeDef.analyzeStructType(), and com.cloudera.impala.catalog.ArrayType.getItemType().
void com.cloudera.impala.analysis.TypeDef.analyzeMapType (MapType mapType, Analyzer analyzer) throws AnalysisException inline private
Definition at line 129 of file TypeDef.java.
References com.cloudera.impala.analysis.TypeDef.analyze().
Referenced by com.cloudera.impala.analysis.TypeDef.analyze().
void com.cloudera.impala.analysis.TypeDef.analyzeScalarType (ScalarType scalarType, Analyzer analyzer) throws AnalysisException inline private
Definition at line 64 of file TypeDef.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.ScalarType.MAX_CHAR_LENGTH, com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, com.cloudera.impala.catalog.ScalarType.MAX_VARCHAR_LENGTH, impala.name, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
Referenced by com.cloudera.impala.analysis.TypeDef.analyze().
void com.cloudera.impala.analysis.TypeDef.analyzeStructType (StructType structType, Analyzer analyzer) throws AnalysisException inline private
Definition at line 111 of file TypeDef.java.
References com.cloudera.impala.analysis.TypeDef.analyze(), and com.cloudera.impala.analysis.TypeDef.toSql().
Referenced by com.cloudera.impala.analysis.TypeDef.analyze().
Type com.cloudera.impala.analysis.TypeDef.getType () inline
Definition at line 139 of file TypeDef.java.
References com.cloudera.impala.analysis.TypeDef.parsedType_.
String com.cloudera.impala.analysis.TypeDef.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 145 of file TypeDef.java.
Referenced by com.cloudera.impala.analysis.TypeDef.analyzeStructType().
String com.cloudera.impala.analysis.TypeDef.toString () inline
Definition at line 142 of file TypeDef.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeFileStmt.extractParquetSchema(), and com.cloudera.impala.analysis.CastExpr.toSqlImpl().
Member Data Documentation
boolean com.cloudera.impala.analysis.TypeDef.isAnalyzed_ private
Definition at line 36 of file TypeDef.java.
Referenced by com.cloudera.impala.analysis.TypeDef.analyze().
final Type com.cloudera.impala.analysis.TypeDef.parsedType_ private
Definition at line 37 of file TypeDef.java.
Referenced by com.cloudera.impala.analysis.TypeDef.analyze(), com.cloudera.impala.analysis.TypeDef.getType(), and com.cloudera.impala.analysis.TypeDef.TypeDef().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/TypeDef.java