Impala: com.cloudera.impala.analysis.LoadDataStmt Class Reference
com.cloudera.impala.analysis.LoadDataStmt Class Reference
Public Member Functions
LoadDataStmt (TableName tableName, HdfsUri sourceDataPath, boolean overwrite, PartitionSpec partitionSpec)
String getTbl ()
String getDb ()
String toSql ()
void analyze (Analyzer analyzer) throws AnalysisException
TLoadDataReq toThrift ()
void setIsExplain ()
boolean isExplain ()
Protected Attributes
boolean isExplain_ = false
Private Member Functions
void analyzePaths (Analyzer analyzer, HdfsTable hdfsTable) throws AnalysisException
Private Attributes
final TableName tableName_
final HdfsUri sourceDataPath_
final PartitionSpec partitionSpec_
final boolean overwrite_
String dbName_
Detailed Description
Definition at line 53 of file LoadDataStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.LoadDataStmt.LoadDataStmt (TableName tableName, HdfsUri sourceDataPath, boolean overwrite, PartitionSpec partitionSpec) inline
Definition at line 62 of file LoadDataStmt.java.
Member Function Documentation
void com.cloudera.impala.analysis.LoadDataStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 96 of file LoadDataStmt.java.
References com.cloudera.impala.analysis.LoadDataStmt.analyzePaths(), com.cloudera.impala.analysis.LoadDataStmt.dbName_, com.cloudera.impala.analysis.LoadDataStmt.getTbl(), com.cloudera.impala.authorization.Privilege.INSERT, com.cloudera.impala.analysis.LoadDataStmt.partitionSpec_, and com.cloudera.impala.analysis.LoadDataStmt.tableName_.
void com.cloudera.impala.analysis.LoadDataStmt.analyzePaths (Analyzer analyzer, HdfsTable hdfsTable) throws AnalysisException inline private
Check to see if Impala has the necessary permissions to access the source and dest paths for this LOAD statement (which maps onto a sequence of file move operations, with the requisite permission requirements), and check to see if all files to be moved are in format that Impala understands. Errors are raised as AnalysisExceptions.
Definition at line 125 of file LoadDataStmt.java.
References com.cloudera.impala.authorization.Privilege.ALL, com.cloudera.impala.common.FileSystemUtil.containsSubdirectory(), com.cloudera.impala.catalog.HdfsPartition.getAccessLevel(), com.cloudera.impala.catalog.HdfsPartition.getLocation(), com.cloudera.impala.util.FsPermissionChecker.getPermissions(), com.cloudera.impala.common.FileSystemUtil.getTotalNumVisibleFiles(), com.cloudera.impala.util.TAccessLevelUtil.impliesWriteAccess(), com.cloudera.impala.catalog.HdfsFileFormat.isFileCompressionTypeSupported(), com.cloudera.impala.common.FileSystemUtil.isHiddenFile(), com.cloudera.impala.common.FileSystemUtil.isPathOnFileSystem(), com.cloudera.impala.analysis.LoadDataStmt.partitionSpec_, and com.cloudera.impala.analysis.LoadDataStmt.sourceDataPath_.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyze().
String com.cloudera.impala.analysis.LoadDataStmt.getDb () inline
Definition at line 76 of file LoadDataStmt.java.
References com.cloudera.impala.analysis.LoadDataStmt.dbName_.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.toThrift().
String com.cloudera.impala.analysis.LoadDataStmt.getTbl () inline
Definition at line 72 of file LoadDataStmt.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyze(), and com.cloudera.impala.analysis.LoadDataStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.LoadDataStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 86 of file LoadDataStmt.java.
References com.cloudera.impala.analysis.LoadDataStmt.overwrite_, com.cloudera.impala.analysis.LoadDataStmt.partitionSpec_, and com.cloudera.impala.analysis.LoadDataStmt.sourceDataPath_.
TLoadDataReq com.cloudera.impala.analysis.LoadDataStmt.toThrift () inline
Definition at line 234 of file LoadDataStmt.java.
References com.cloudera.impala.analysis.LoadDataStmt.getDb(), com.cloudera.impala.analysis.LoadDataStmt.getTbl(), com.cloudera.impala.analysis.LoadDataStmt.overwrite_, and com.cloudera.impala.analysis.LoadDataStmt.partitionSpec_.
Member Data Documentation
String com.cloudera.impala.analysis.LoadDataStmt.dbName_ private
Definition at line 60 of file LoadDataStmt.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyze(), and com.cloudera.impala.analysis.LoadDataStmt.getDb().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final boolean com.cloudera.impala.analysis.LoadDataStmt.overwrite_ private
Definition at line 57 of file LoadDataStmt.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.toSql(), and com.cloudera.impala.analysis.LoadDataStmt.toThrift().
final PartitionSpec com.cloudera.impala.analysis.LoadDataStmt.partitionSpec_ private
Definition at line 56 of file LoadDataStmt.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyze(), com.cloudera.impala.analysis.LoadDataStmt.analyzePaths(), com.cloudera.impala.analysis.LoadDataStmt.toSql(), and com.cloudera.impala.analysis.LoadDataStmt.toThrift().
final HdfsUri com.cloudera.impala.analysis.LoadDataStmt.sourceDataPath_ private
Definition at line 55 of file LoadDataStmt.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyzePaths(), and com.cloudera.impala.analysis.LoadDataStmt.toSql().
final TableName com.cloudera.impala.analysis.LoadDataStmt.tableName_ private
Definition at line 54 of file LoadDataStmt.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyze().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/LoadDataStmt.java