Impala: com.cloudera.impala.analysis.HdfsUri Class Reference
com.cloudera.impala.analysis.HdfsUri Class Reference
Public Member Functions
HdfsUri (String location)
Path getPath ()
void analyze (Analyzer analyzer, Privilege privilege) throws AnalysisException
void analyze (Analyzer analyzer, Privilege privilege, FsAction perm) throws AnalysisException
void analyze (Analyzer analyzer, Privilege privilege, boolean registerPrivReq) throws AnalysisException
void analyze (Analyzer analyzer, Privilege privilege, FsAction perm, boolean registerPrivReq) throws AnalysisException
String toString ()
String getLocation ()
Private Attributes
final String location_
Path uriPath_
Detailed Description
Definition at line 34 of file HdfsUri.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.HdfsUri.HdfsUri (String location) inline
Definition at line 40 of file HdfsUri.java.
Member Function Documentation
void com.cloudera.impala.analysis.HdfsUri.analyze (Analyzer analyzer, Privilege privilege) throws AnalysisException inline
Definition at line 50 of file HdfsUri.java.
Referenced by com.cloudera.impala.analysis.HdfsUri.analyze().
void com.cloudera.impala.analysis.HdfsUri.analyze (Analyzer analyzer, Privilege privilege, FsAction perm) throws AnalysisException inline
Definition at line 55 of file HdfsUri.java.
References com.cloudera.impala.analysis.HdfsUri.analyze().
void com.cloudera.impala.analysis.HdfsUri.analyze (Analyzer analyzer, Privilege privilege, boolean registerPrivReq) throws AnalysisException inline
Definition at line 60 of file HdfsUri.java.
References com.cloudera.impala.analysis.HdfsUri.analyze().
void com.cloudera.impala.analysis.HdfsUri.analyze (Analyzer analyzer, Privilege privilege, FsAction perm, boolean registerPrivReq) throws AnalysisException inline
Analyzes the URI. Optionally check location path permission, issue warning if impala user doesn't have sufficient access rights. Optionally register a privilege request. Used by GRANT/REVOKE privilege statements.
Definition at line 71 of file HdfsUri.java.
References com.cloudera.impala.util.FsPermissionChecker.getPermissions(), com.cloudera.impala.common.FileSystemUtil.isPathReachable(), com.cloudera.impala.analysis.HdfsUri.location_, com.cloudera.impala.analysis.Path.toString(), and com.cloudera.impala.analysis.HdfsUri.uriPath_.
String com.cloudera.impala.analysis.HdfsUri.getLocation () inline
Definition at line 117 of file HdfsUri.java.
References com.cloudera.impala.analysis.HdfsUri.location_.
Referenced by com.cloudera.impala.catalog.Function.lookupSymbol().
Path com.cloudera.impala.analysis.HdfsUri.getPath () inline
Definition at line 45 of file HdfsUri.java.
References com.cloudera.impala.analysis.HdfsUri.uriPath_.
String com.cloudera.impala.analysis.HdfsUri.toString () inline
Definition at line 111 of file HdfsUri.java.
References com.cloudera.impala.analysis.HdfsUri.location_, and com.cloudera.impala.analysis.HdfsUri.uriPath_.
Referenced by com.cloudera.impala.analysis.AlterTableSetLocationStmt.toThrift(), and com.cloudera.impala.analysis.CreateDataSrcStmt.toThrift().
Member Data Documentation
final String com.cloudera.impala.analysis.HdfsUri.location_ private
Definition at line 35 of file HdfsUri.java.
Referenced by com.cloudera.impala.analysis.HdfsUri.analyze(), com.cloudera.impala.analysis.HdfsUri.getLocation(), and com.cloudera.impala.analysis.HdfsUri.toString().
Path com.cloudera.impala.analysis.HdfsUri.uriPath_ private
Definition at line 38 of file HdfsUri.java.
Referenced by com.cloudera.impala.analysis.HdfsUri.analyze(), com.cloudera.impala.analysis.HdfsUri.getPath(), and com.cloudera.impala.analysis.HdfsUri.toString().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/HdfsUri.java