Impala: com.cloudera.impala.planner.Planner Class Reference
com.cloudera.impala.planner.Planner Class Reference
Public Member Functions
Planner (AnalysisContext.AnalysisResult analysisResult, TQueryCtx queryCtx)
ArrayList< PlanFragment > createPlan () throws ImpalaException
String getExplainString (ArrayList< PlanFragment > fragments, TQueryExecRequest request, TExplainLevel explainLevel)
void computeResourceReqs (List< PlanFragment > fragments, boolean excludeUnpartitionedFragments, TQueryExecRequest request)
Private Attributes
final PlannerContext ctx_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(Planner.class)
Detailed Description
Creates an executable plan from an analyzed parse tree and query options.
Definition at line 31 of file Planner.java.
Constructor & Destructor Documentation
com.cloudera.impala.planner.Planner.Planner (AnalysisContext.AnalysisResult analysisResult, TQueryCtx queryCtx) inline
Definition at line 36 of file Planner.java.
References com.cloudera.impala.planner.Planner.ctx_.
Member Function Documentation
void com.cloudera.impala.planner.Planner.computeResourceReqs (List< PlanFragment > fragments, boolean excludeUnpartitionedFragments, TQueryExecRequest request) inline
Estimates the per-host memory and CPU requirements for the given plan fragments, and sets the results in request. Optionally excludes the requirements for unpartitioned fragments. TODO: The LOG.warn() messages should eventually become Preconditions checks once resource estimation is more robust.
Definition at line 196 of file Planner.java.
References com.cloudera.impala.planner.Planner.ctx_, and com.cloudera.impala.planner.PlannerContext.getQueryOptions().
ArrayList<PlanFragment> com.cloudera.impala.planner.Planner.createPlan () throws ImpalaException inline
Returns a list of plan fragments for executing an analyzed parse tree. May return a single-node or distributed executable plan.
Definition at line 44 of file Planner.java.
References com.cloudera.impala.common.RuntimeEnv.computeLineage(), com.cloudera.impala.planner.Planner.ctx_, com.cloudera.impala.util.MaxRowsProcessedVisitor.get(), com.cloudera.impala.planner.PlannerContext.getNextFragmentId(), com.cloudera.impala.planner.PlannerContext.getQueryOptions(), com.cloudera.impala.common.RuntimeEnv.INSTANCE, com.cloudera.impala.planner.PlannerContext.isInsertOrCtas(), com.cloudera.impala.planner.PlannerContext.isSingleNodeExec(), and com.cloudera.impala.planner.DataPartition.UNPARTITIONED.
String com.cloudera.impala.planner.Planner.getExplainString (ArrayList< PlanFragment > fragments, TQueryExecRequest request, TExplainLevel explainLevel) inline
Return combined explain string for all plan fragments. Includes the estimated resource requirements from the request if set.
Definition at line 141 of file Planner.java.
Member Data Documentation
final PlannerContext com.cloudera.impala.planner.Planner.ctx_ private
Definition at line 34 of file Planner.java.
Referenced by com.cloudera.impala.planner.Planner.computeResourceReqs(), com.cloudera.impala.planner.Planner.createPlan(), and com.cloudera.impala.planner.Planner.Planner().
final Logger com.cloudera.impala.planner.Planner.LOG = LoggerFactory.getLogger(Planner.class) static private
Definition at line 32 of file Planner.java.
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/planner/Planner.java