Impala: com.cloudera.impala.analysis.HdfsCachingOp Class Reference
com.cloudera.impala.analysis.HdfsCachingOp Class Reference
Public Member Functions
HdfsCachingOp ()
HdfsCachingOp (String cachePoolName, BigDecimal replication)
void analyze (Analyzer analyzer) throws AnalysisException
String toSql ()
THdfsCachingOp toThrift ()
boolean shouldCache ()
String getCachePoolName ()
Private Attributes
final THdfsCachingOp cacheOp_
final BigDecimal parsedReplication_
Detailed Description
Represents the partial SQL statement of specifying whether a table/partition should or should not be marked as cached.
Definition at line 28 of file HdfsCachingOp.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.HdfsCachingOp.HdfsCachingOp () inline
Creates an HdfsCachingOp that specifies the target should be uncached
Definition at line 35 of file HdfsCachingOp.java.
References com.cloudera.impala.analysis.HdfsCachingOp.cacheOp_, and com.cloudera.impala.analysis.HdfsCachingOp.parsedReplication_.
com.cloudera.impala.analysis.HdfsCachingOp.HdfsCachingOp (String cachePoolName, BigDecimal replication) inline
Creates an HdfsCachingOp that specifies the target should be cached in cachePoolName with an optional replication factor
Definition at line 44 of file HdfsCachingOp.java.
References com.cloudera.impala.analysis.HdfsCachingOp.cacheOp_, and com.cloudera.impala.analysis.HdfsCachingOp.parsedReplication_.
Member Function Documentation
void com.cloudera.impala.analysis.HdfsCachingOp.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 51 of file HdfsCachingOp.java.
References com.cloudera.impala.analysis.HdfsCachingOp.cacheOp_, and com.cloudera.impala.analysis.HdfsCachingOp.parsedReplication_.
String com.cloudera.impala.analysis.HdfsCachingOp.getCachePoolName () inline
Definition at line 87 of file HdfsCachingOp.java.
References com.cloudera.impala.analysis.HdfsCachingOp.shouldCache().
Referenced by com.cloudera.impala.analysis.HdfsCachingOp.toSql().
boolean com.cloudera.impala.analysis.HdfsCachingOp.shouldCache () inline
Definition at line 85 of file HdfsCachingOp.java.
Referenced by com.cloudera.impala.analysis.HdfsCachingOp.getCachePoolName(), and com.cloudera.impala.analysis.HdfsCachingOp.toSql().
String com.cloudera.impala.analysis.HdfsCachingOp.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 78 of file HdfsCachingOp.java.
References com.cloudera.impala.analysis.HdfsCachingOp.getCachePoolName(), and com.cloudera.impala.analysis.HdfsCachingOp.shouldCache().
THdfsCachingOp com.cloudera.impala.analysis.HdfsCachingOp.toThrift () inline
Definition at line 83 of file HdfsCachingOp.java.
References com.cloudera.impala.analysis.HdfsCachingOp.cacheOp_.
Member Data Documentation
final THdfsCachingOp com.cloudera.impala.analysis.HdfsCachingOp.cacheOp_ private
Definition at line 29 of file HdfsCachingOp.java.
Referenced by com.cloudera.impala.analysis.HdfsCachingOp.analyze(), com.cloudera.impala.analysis.HdfsCachingOp.HdfsCachingOp(), and com.cloudera.impala.analysis.HdfsCachingOp.toThrift().
final BigDecimal com.cloudera.impala.analysis.HdfsCachingOp.parsedReplication_ private
Definition at line 30 of file HdfsCachingOp.java.
Referenced by com.cloudera.impala.analysis.HdfsCachingOp.analyze(), and com.cloudera.impala.analysis.HdfsCachingOp.HdfsCachingOp().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/HdfsCachingOp.java