Impala: com.cloudera.impala.analysis.AnalyticInfo Class Reference
com.cloudera.impala.analysis.AnalyticInfo Class Reference
Public Member Functions
ArrayList< Expr > getAnalyticExprs ()
ExprSubstitutionMap getSmap ()
List< Expr > getCommonPartitionExprs ()
void getRefdSlots (List< SlotId > ids)
void materializeRequiredSlots (Analyzer analyzer, ExprSubstitutionMap smap)
void checkConsistency ()
String debugString ()
ArrayList< Expr > getGroupingExprs ()
ArrayList< FunctionCallExpr > getAggregateExprs ()
TupleDescriptor getOutputTupleDesc ()
TupleDescriptor getIntermediateTupleDesc ()
TupleId getIntermediateTupleId ()
TupleId getOutputTupleId ()
boolean requiresIntermediateTuple ()
Static Public Member Functions
static AnalyticInfo create (ArrayList< Expr > analyticExprs, Analyzer analyzer)
static< TextendsExpr > boolean requiresIntermediateTuple (List< T > aggExprs)
Protected Member Functions
String tupleDebugName ()
void createTupleDescs (Analyzer analyzer)
Protected Attributes
ArrayList< Expr > groupingExprs_
ArrayList< FunctionCallExpr > aggregateExprs_
TupleDescriptor intermediateTupleDesc_
TupleDescriptor outputTupleDesc_
ArrayList< Integer > materializedSlots_ = Lists.newArrayList()
Private Member Functions
AnalyticInfo (ArrayList< Expr > analyticExprs)
void computeCommonPartitionExprs ()
Private Attributes
final ArrayList< Expr > analyticExprs_
final List< Expr > commonPartitionExprs_ = Lists.newArrayList()
final ExprSubstitutionMap analyticTupleSmap_ = new ExprSubstitutionMap()
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(AnalyticInfo.class)
Detailed Description
Encapsulates the analytic functions found in a single select block plus the corresponding analytic result tuple and its substitution map.
Definition at line 32 of file AnalyticInfo.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AnalyticInfo.AnalyticInfo (ArrayList< Expr > analyticExprs) inline private
Definition at line 46 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.analyticExprs_, and com.cloudera.impala.analysis.AnalyticInfo.computeCommonPartitionExprs().
Referenced by com.cloudera.impala.analysis.AnalyticInfo.create().
Member Function Documentation
void com.cloudera.impala.analysis.AnalyticInfo.checkConsistency () inline
Validates internal state: Checks that the number of materialized slots of the analytic tuple corresponds to the number of materialized analytic functions. Also checks that the return types of the analytic exprs correspond to the slots in the analytic tuple.
Definition at line 143 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.Expr.getType().
void com.cloudera.impala.analysis.AnalyticInfo.computeCommonPartitionExprs () inline private
Computes the intersection of the partition exprs of all the analytic functions.
Definition at line 95 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.analyticExprs_, and com.cloudera.impala.analysis.AnalyticInfo.commonPartitionExprs_.
Referenced by com.cloudera.impala.analysis.AnalyticInfo.AnalyticInfo().
static AnalyticInfo com.cloudera.impala.analysis.AnalyticInfo.create (ArrayList< Expr > analyticExprs, Analyzer analyzer) inline static
Creates complete AnalyticInfo for analyticExprs, including tuple descriptors and smaps.
Definition at line 64 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.AnalyticInfo().
void com.cloudera.impala.analysis.AggregateInfoBase.createTupleDescs (Analyzer analyzer) inline protected inherited
Creates the intermediate and output tuple descriptors. If no agg expr has an intermediate type different from its output type, then only the output tuple descriptor is created and the intermediate tuple is set to the output tuple.
Definition at line 70 of file AggregateInfoBase.java.
References com.cloudera.impala.analysis.AggregateInfoBase.aggregateExprs_, com.cloudera.impala.analysis.AggregateInfoBase.createTupleDesc(), com.cloudera.impala.analysis.AggregateInfoBase.intermediateTupleDesc_, com.cloudera.impala.analysis.AggregateInfoBase.outputTupleDesc_, and com.cloudera.impala.analysis.AggregateInfoBase.requiresIntermediateTuple().
Referenced by com.cloudera.impala.analysis.AggregateInfo.createDistinctAggInfo().
String com.cloudera.impala.analysis.AnalyticInfo.debugString () inline
Definition at line 168 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.analyticExprs_, com.cloudera.impala.analysis.AnalyticInfo.analyticTupleSmap_, com.cloudera.impala.analysis.ExprSubstitutionMap.debugString(), and com.cloudera.impala.analysis.Expr.debugString().
ArrayList<FunctionCallExpr> com.cloudera.impala.analysis.AggregateInfoBase.getAggregateExprs () inline inherited
Definition at line 157 of file AggregateInfoBase.java.
References com.cloudera.impala.analysis.AggregateInfoBase.aggregateExprs_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), com.cloudera.impala.analysis.AnalyzerTest.checkSelectToThrift(), com.cloudera.impala.analysis.AggregateInfo.createMergeAggInfo(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), and com.cloudera.impala.analysis.AggregateInfo.hasAggregateExprs().
ArrayList<Expr> com.cloudera.impala.analysis.AnalyticInfo.getAnalyticExprs () inline
Definition at line 56 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.analyticExprs_.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.collectWindowGroups().
List<Expr> com.cloudera.impala.analysis.AnalyticInfo.getCommonPartitionExprs () inline
Definition at line 58 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.commonPartitionExprs_.
ArrayList<Expr> com.cloudera.impala.analysis.AggregateInfoBase.getGroupingExprs () inline inherited
Definition at line 156 of file AggregateInfoBase.java.
References com.cloudera.impala.analysis.AggregateInfoBase.groupingExprs_.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.checkSelectToThrift(), com.cloudera.impala.analysis.AggregateInfo.createMergeAggInfo(), com.cloudera.impala.analysis.AggregateInfo.createSecondPhaseAggInfo(), and com.cloudera.impala.planner.AggregationNode.getNodeExplainString().
TupleDescriptor com.cloudera.impala.analysis.AggregateInfoBase.getIntermediateTupleDesc () inline inherited
Definition at line 159 of file AggregateInfoBase.java.
References com.cloudera.impala.analysis.AggregateInfoBase.intermediateTupleDesc_.
TupleId com.cloudera.impala.analysis.AggregateInfoBase.getIntermediateTupleId () inline inherited
Definition at line 160 of file AggregateInfoBase.java.
Referenced by com.cloudera.impala.planner.AggregationNode.toThrift().
TupleDescriptor com.cloudera.impala.analysis.AggregateInfoBase.getOutputTupleDesc () inline inherited
Definition at line 158 of file AggregateInfoBase.java.
References com.cloudera.impala.analysis.AggregateInfoBase.outputTupleDesc_.
Referenced by com.cloudera.impala.planner.AnalyticPlanner.collectWindowGroups().
TupleId com.cloudera.impala.analysis.AggregateInfoBase.getOutputTupleId () inline inherited
Definition at line 161 of file AggregateInfoBase.java.
Referenced by com.cloudera.impala.planner.AggregationNode.AggregationNode(), com.cloudera.impala.planner.AnalyticPlanner.AnalyticPlanner(), com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.analysis.AggregateInfo.getResultTupleId(), com.cloudera.impala.planner.AggregationNode.setIntermediateTuple(), and com.cloudera.impala.planner.AggregationNode.toThrift().
void com.cloudera.impala.analysis.AnalyticInfo.getRefdSlots (List< SlotId > ids) inline
Append ids of all slots that are being referenced in the process of performing the analytic computation described by this AnalyticInfo.
Definition at line 113 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.analyticExprs_, com.cloudera.impala.analysis.TupleDescriptor.getSlots(), and com.cloudera.impala.analysis.AggregateInfoBase.intermediateTupleDesc_.
ExprSubstitutionMap com.cloudera.impala.analysis.AnalyticInfo.getSmap () inline
Definition at line 57 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.AnalyticInfo.analyticTupleSmap_.
void com.cloudera.impala.analysis.AnalyticInfo.materializeRequiredSlots (Analyzer analyzer, ExprSubstitutionMap smap) inline
Definition at line 123 of file AnalyticInfo.java.
References com.cloudera.impala.analysis.SlotDescriptor.isMaterialized().
boolean com.cloudera.impala.analysis.AggregateInfoBase.requiresIntermediateTuple () inline inherited
Definition at line 162 of file AggregateInfoBase.java.
References com.cloudera.impala.analysis.AggregateInfoBase.intermediateTupleDesc_, and com.cloudera.impala.analysis.AggregateInfoBase.outputTupleDesc_.
Referenced by com.cloudera.impala.analysis.AggregateInfo.createSmaps(), and com.cloudera.impala.analysis.AggregateInfoBase.createTupleDescs().
static <TextendsExpr> boolean com.cloudera.impala.analysis.AggregateInfoBase.requiresIntermediateTuple (List< T > aggExprs) inline static inherited
Returns true if evaluating the given aggregate exprs requires an intermediate tuple, i.e., whether one of the aggregate functions has an intermediate type different from its output type.
Definition at line 173 of file AggregateInfoBase.java.
String com.cloudera.impala.analysis.AnalyticInfo.tupleDebugName () inline protected
Definition at line 177 of file AnalyticInfo.java.
Member Data Documentation
ArrayList<FunctionCallExpr> com.cloudera.impala.analysis.AggregateInfoBase.aggregateExprs_ protected inherited
Definition at line 31 of file AggregateInfoBase.java.
Referenced by com.cloudera.impala.analysis.AggregateInfoBase.AggregateInfoBase(), com.cloudera.impala.analysis.AggregateInfo.createSecondPhaseAggInfo(), com.cloudera.impala.analysis.AggregateInfo.createSmaps(), com.cloudera.impala.analysis.AggregateInfoBase.createTupleDesc(), com.cloudera.impala.analysis.AggregateInfoBase.createTupleDescs(), com.cloudera.impala.analysis.AggregateInfoBase.debugString(), com.cloudera.impala.analysis.AggregateInfoBase.getAggregateExprs(), com.cloudera.impala.analysis.AggregateInfo.getRefdSlots(), and com.cloudera.impala.analysis.AggregateInfo.substitute().
final ArrayList<Expr> com.cloudera.impala.analysis.AnalyticInfo.analyticExprs_ private
Definition at line 38 of file AnalyticInfo.java.
Referenced by com.cloudera.impala.analysis.AnalyticInfo.AnalyticInfo(), com.cloudera.impala.analysis.AnalyticInfo.computeCommonPartitionExprs(), com.cloudera.impala.analysis.AnalyticInfo.debugString(), com.cloudera.impala.analysis.AnalyticInfo.getAnalyticExprs(), and com.cloudera.impala.analysis.AnalyticInfo.getRefdSlots().
final ExprSubstitutionMap com.cloudera.impala.analysis.AnalyticInfo.analyticTupleSmap_ = new ExprSubstitutionMap() private
Definition at line 44 of file AnalyticInfo.java.
Referenced by com.cloudera.impala.analysis.AnalyticInfo.debugString(), and com.cloudera.impala.analysis.AnalyticInfo.getSmap().
final List<Expr> com.cloudera.impala.analysis.AnalyticInfo.commonPartitionExprs_ = Lists.newArrayList() private
Definition at line 41 of file AnalyticInfo.java.
Referenced by com.cloudera.impala.analysis.AnalyticInfo.computeCommonPartitionExprs(), and com.cloudera.impala.analysis.AnalyticInfo.getCommonPartitionExprs().
ArrayList<Expr> com.cloudera.impala.analysis.AggregateInfoBase.groupingExprs_ protected inherited
Definition at line 26 of file AggregateInfoBase.java.
Referenced by com.cloudera.impala.analysis.AggregateInfoBase.AggregateInfoBase(), com.cloudera.impala.analysis.AggregateInfo.checkConsistency(), com.cloudera.impala.analysis.AggregateInfo.createSmaps(), com.cloudera.impala.analysis.AggregateInfoBase.createTupleDesc(), com.cloudera.impala.analysis.AggregateInfoBase.debugString(), com.cloudera.impala.analysis.AggregateInfoBase.getGroupingExprs(), com.cloudera.impala.analysis.AggregateInfo.getPartition(), com.cloudera.impala.analysis.AggregateInfo.getRefdSlots(), com.cloudera.impala.analysis.AggregateInfo.materializeRequiredSlots(), and com.cloudera.impala.analysis.AggregateInfo.substitute().
TupleDescriptor com.cloudera.impala.analysis.AggregateInfoBase.intermediateTupleDesc_ protected inherited
Definition at line 40 of file AggregateInfoBase.java.
Referenced by com.cloudera.impala.analysis.AggregateInfo.createMergeAggInfo(), com.cloudera.impala.analysis.AggregateInfo.createSecondPhaseAggInfo(), com.cloudera.impala.analysis.AggregateInfo.createSmaps(), com.cloudera.impala.analysis.AggregateInfoBase.createTupleDescs(), com.cloudera.impala.analysis.AggregateInfoBase.debugString(), com.cloudera.impala.analysis.AggregateInfoBase.getIntermediateTupleDesc(), com.cloudera.impala.analysis.AnalyticInfo.getRefdSlots(), and com.cloudera.impala.analysis.AggregateInfoBase.requiresIntermediateTuple().
final Logger com.cloudera.impala.analysis.AnalyticInfo.LOG = LoggerFactory.getLogger(AnalyticInfo.class) static private
Definition at line 33 of file AnalyticInfo.java.
ArrayList<Integer> com.cloudera.impala.analysis.AggregateInfoBase.materializedSlots_ = Lists.newArrayList() protected inherited
Definition at line 53 of file AggregateInfoBase.java.
Referenced by com.cloudera.impala.analysis.AggregateInfo.createMergeAggInfo(), and com.cloudera.impala.analysis.AggregateInfo.getMaterializedAggregateExprs().
TupleDescriptor com.cloudera.impala.analysis.AggregateInfoBase.outputTupleDesc_ protected inherited
Definition at line 47 of file AggregateInfoBase.java.
Referenced by com.cloudera.impala.analysis.AggregateInfo.createMergeAggInfo(), com.cloudera.impala.analysis.AggregateInfo.createSmaps(), com.cloudera.impala.analysis.AggregateInfoBase.createTupleDescs(), com.cloudera.impala.analysis.AggregateInfoBase.debugString(), com.cloudera.impala.analysis.AggregateInfoBase.getOutputTupleDesc(), com.cloudera.impala.analysis.AggregateInfo.getRefdSlots(), and com.cloudera.impala.analysis.AggregateInfoBase.requiresIntermediateTuple().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AnalyticInfo.java