Impala: impala::StateStore2Test Class Reference
impala::StateStore2Test Class Reference
Classes
class Callbacks
class TopicCallbacks
Protected Member Functions
StateStore2Test ()
virtual void SetUp ()
virtual void TearDown ()
shared_ptr< StateStoreSubscriber2 > StartStateStoreSubscriber (Callbacks *cb)
void UnregisterAllSubscribers ()
Protected Attributes
scoped_ptr< InProcessStateStore > state_store_
vector< shared_ptr
< StateStoreSubscriber2 > > subscribers_
vector< TopicCallbacks * > callbacks_
Static Protected Attributes
static int next_port_ = 27000
static const char * ipaddress_
Detailed Description
Definition at line 48 of file state-store-2.0-test.cc.
Constructor & Destructor Documentation
impala::StateStore2Test::StateStore2Test () inline protected
Definition at line 100 of file state-store-2.0-test.cc.
Member Function Documentation
virtual void impala::StateStore2Test::SetUp () inline protected virtual
Definition at line 104 of file state-store-2.0-test.cc.
References impala::Status::ok().
shared_ptr<StateStoreSubscriber2> impala::StateStore2Test::StartStateStoreSubscriber (Callbacks * cb) inline protected
Definition at line 117 of file state-store-2.0-test.cc.
References impala::MakeNetworkAddress(), impala::Status::ok(), and impala::WaitForServer().
virtual void impala::StateStore2Test::TearDown () inline protected virtual
Definition at line 112 of file state-store-2.0-test.cc.
void impala::StateStore2Test::UnregisterAllSubscribers () inline protected
Definition at line 134 of file state-store-2.0-test.cc.
Member Data Documentation
vector<TopicCallbacks*> impala::StateStore2Test::callbacks_ protected
Definition at line 98 of file state-store-2.0-test.cc.
const char* impala::StateStore2Test::ipaddress_ static protected
Definition at line 94 of file state-store-2.0-test.cc.
int impala::StateStore2Test::next_port_ = 27000 static protected
Definition at line 92 of file state-store-2.0-test.cc.
scoped_ptr<InProcessStateStore> impala::StateStore2Test::state_store_ protected
Definition at line 93 of file state-store-2.0-test.cc.
vector<shared_ptr<StateStoreSubscriber2> > impala::StateStore2Test::subscribers_ protected
Definition at line 97 of file state-store-2.0-test.cc.
The documentation for this class was generated from the following file:
be/src/statestore/state-store-2.0-test.cc