Impala: com.cloudera.impala.analysis.InsertStmt Class Reference
com.cloudera.impala.analysis.InsertStmt Class Reference
Public Member Functions
InsertStmt (WithClause withClause, TableName targetTable, boolean overwrite, List< PartitionKeyValue > partitionKeyValues, List< String > planHints, QueryStmt queryStmt, List< String > columnPermutation)
InsertStmt (InsertStmt other)
InsertStmt clone ()
void analyze (Analyzer analyzer) throws AnalysisException
List< String > getPlanHints ()
TableName getTargetTableName ()
Table getTargetTable ()
void setTargetTable (Table table)
boolean isOverwrite ()
QueryStmt getQueryStmt ()
void setQueryStmt (QueryStmt stmt)
List< Expr > getPartitionKeyExprs ()
Boolean isRepartition ()
ArrayList< Expr > getResultExprs ()
DataSink createDataSink ()
String toSql ()
void setIsExplain ()
boolean isExplain ()
Protected Attributes
boolean isExplain_ = false
Private Member Functions
void setTargetTable (Analyzer analyzer) throws AnalysisException
void checkColumnCoverage (ArrayList< Column > selectExprTargetColumns, Set< String > mentionedColumnNames, int numSelectListExprs, int numStaticPartitionExprs) throws AnalysisException
void prepareExpressions (List< Column > selectExprTargetColumns, List< Expr > selectListExprs, Table tbl, Analyzer analyzer) throws AnalysisException
Expr checkTypeCompatibility (Column column, Expr expr) throws AnalysisException
void analyzePlanHints (Analyzer analyzer) throws AnalysisException
Private Attributes
final WithClause withClause_
final TableName originalTableName_
TableName targetTableName_
final boolean overwrite_
final List< PartitionKeyValue > partitionKeyValues_
final List< String > planHints_
QueryStmt queryStmt_
final boolean needsGeneratedQueryStatement_
Table table_
final List< Expr > partitionKeyExprs_ = new ArrayList<Expr>()
Boolean isRepartition_ = null
final ArrayList< Expr > resultExprs_ = new ArrayList<Expr>()
final List< String > columnPermutation_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(InsertStmt.class)
Detailed Description
Representation of a single insert statement, including the select statement whose results are to be inserted.
Definition at line 46 of file InsertStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.InsertStmt.InsertStmt (WithClause withClause, TableName targetTable, boolean overwrite, List< PartitionKeyValue > partitionKeyValues, List< String > planHints, QueryStmt queryStmt, List< String > columnPermutation) inline
Definition at line 113 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.columnPermutation_, com.cloudera.impala.analysis.InsertStmt.needsGeneratedQueryStatement_, com.cloudera.impala.analysis.InsertStmt.originalTableName_, com.cloudera.impala.analysis.InsertStmt.overwrite_, com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, com.cloudera.impala.analysis.InsertStmt.planHints_, com.cloudera.impala.analysis.InsertStmt.queryStmt_, com.cloudera.impala.analysis.InsertStmt.table_, com.cloudera.impala.analysis.InsertStmt.targetTableName_, and com.cloudera.impala.analysis.InsertStmt.withClause_.
Referenced by com.cloudera.impala.analysis.InsertStmt.clone().
com.cloudera.impala.analysis.InsertStmt.InsertStmt (InsertStmt other) inline
C'tor used in clone().
Definition at line 131 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.columnPermutation_, com.cloudera.impala.analysis.InsertStmt.needsGeneratedQueryStatement_, com.cloudera.impala.analysis.InsertStmt.originalTableName_, com.cloudera.impala.analysis.InsertStmt.overwrite_, com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, com.cloudera.impala.analysis.InsertStmt.planHints_, com.cloudera.impala.analysis.InsertStmt.queryStmt_, com.cloudera.impala.analysis.InsertStmt.table_, com.cloudera.impala.analysis.InsertStmt.targetTableName_, and com.cloudera.impala.analysis.InsertStmt.withClause_.
Member Function Documentation
void com.cloudera.impala.analysis.InsertStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 148 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.analyzePlanHints(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.analysis.InsertStmt.columnPermutation_, com.cloudera.impala.catalog.Column.getPosition(), com.cloudera.impala.analysis.StatementBase.isExplain_, com.cloudera.impala.analysis.InsertStmt.needsGeneratedQueryStatement_, com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, com.cloudera.impala.analysis.InsertStmt.prepareExpressions(), com.cloudera.impala.analysis.InsertStmt.queryStmt_, com.cloudera.impala.analysis.InsertStmt.setTargetTable(), com.cloudera.impala.analysis.InsertStmt.table_, and com.cloudera.impala.analysis.InsertStmt.withClause_.
void com.cloudera.impala.analysis.InsertStmt.analyzePlanHints (Analyzer analyzer) throws AnalysisException inline private
Definition at line 592 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.isRepartition_, com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, com.cloudera.impala.analysis.InsertStmt.planHints_, and com.cloudera.impala.analysis.InsertStmt.table_.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze().
void com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage (ArrayList< Column > selectExprTargetColumns, Set< String > mentionedColumnNames, int numSelectListExprs, int numStaticPartitionExprs) throws AnalysisException inline private
Checks that the column permutation + select list + static partition exprs + dynamic partition exprs collectively cover exactly all columns in the target table (not more of fewer).
Definition at line 387 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.columnPermutation_, com.cloudera.impala.catalog.Table.getColumns(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, and com.cloudera.impala.analysis.InsertStmt.table_.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze().
Expr com.cloudera.impala.analysis.InsertStmt.checkTypeCompatibility (Column column, Expr expr) throws AnalysisException inline private
Checks for type compatibility of column and expr. Returns compatible (possibly cast) expr.
Definition at line 559 of file InsertStmt.java.
References com.cloudera.impala.catalog.Type.isValid(), com.cloudera.impala.analysis.InsertStmt.targetTableName_, and com.cloudera.impala.analysis.TableName.toSql().
Referenced by com.cloudera.impala.analysis.InsertStmt.prepareExpressions().
InsertStmt com.cloudera.impala.analysis.InsertStmt.clone () inline
Definition at line 145 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.InsertStmt().
DataSink com.cloudera.impala.analysis.InsertStmt.createDataSink () inline
Definition at line 633 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.overwrite_, com.cloudera.impala.analysis.InsertStmt.partitionKeyExprs_, and com.cloudera.impala.analysis.InsertStmt.table_.
List<Expr> com.cloudera.impala.analysis.InsertStmt.getPartitionKeyExprs () inline
Definition at line 629 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.partitionKeyExprs_.
List<String> com.cloudera.impala.analysis.InsertStmt.getPlanHints () inline
Definition at line 618 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.planHints_.
QueryStmt com.cloudera.impala.analysis.InsertStmt.getQueryStmt () inline
Only valid after analysis
Definition at line 627 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.queryStmt_.
ArrayList<Expr> com.cloudera.impala.analysis.InsertStmt.getResultExprs () inline
Definition at line 631 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.resultExprs_.
Table com.cloudera.impala.analysis.InsertStmt.getTargetTable () inline
Definition at line 620 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.table_.
TableName com.cloudera.impala.analysis.InsertStmt.getTargetTableName () inline
Definition at line 619 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.targetTableName_.
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
boolean com.cloudera.impala.analysis.InsertStmt.isOverwrite () inline
Definition at line 622 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.overwrite_.
Boolean com.cloudera.impala.analysis.InsertStmt.isRepartition () inline
Definition at line 630 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.isRepartition_.
void com.cloudera.impala.analysis.InsertStmt.prepareExpressions (List< Column > selectExprTargetColumns, List< Expr > selectListExprs, Table tbl, Analyzer analyzer) throws AnalysisException inline private
Performs three final parts of the analysis:
Checks type compatibility between all expressions and their targets
Populates partitionKeyExprs with type-compatible expressions, in Hive partition-column order, for all partition columns
Populates resultExprs_ with type-compatible expressions, in Hive column order, for all expressions in the select-list. Unmentioned columns are assigned NULL literal expressions.
If necessary, adds casts to the expressions to make them compatible with the type of the corresponding column.
Exceptions
AnalysisException If an expression is not compatible with its target column
Definition at line 467 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.checkTypeCompatibility(), com.cloudera.impala.catalog.Table.getColumns(), com.cloudera.impala.catalog.Table.getColumnsInHiveOrder(), com.cloudera.impala.catalog.Column.getPosition(), com.cloudera.impala.analysis.InsertStmt.needsGeneratedQueryStatement_, com.cloudera.impala.analysis.InsertStmt.partitionKeyExprs_, com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, com.cloudera.impala.analysis.InsertStmt.queryStmt_, com.cloudera.impala.analysis.InsertStmt.resultExprs_, and com.cloudera.impala.analysis.InsertStmt.table_.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze().
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.InsertStmt.setQueryStmt (QueryStmt stmt) inline
Definition at line 628 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.queryStmt_.
void com.cloudera.impala.analysis.InsertStmt.setTargetTable (Analyzer analyzer) throws AnalysisException inline private
Sets table_ based on targetTableName_ and performs table-type specific analysis:
Partition clause is invalid for unpartitioned Hdfs tables and HBase tables
Overwrite is invalid for HBase tables
Check INSERT privileges as well as write access to Hdfs paths
Cannot insert into a view Adds table_ to the analyzer's descriptor table if analysis succeeds.
Definition at line 298 of file InsertStmt.java.
References com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.Table.getDb(), com.cloudera.impala.catalog.HdfsTable.getFirstLocationWithoutWriteAccess(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.HdfsTable.getLocation(), com.cloudera.impala.catalog.Column.getName(), com.cloudera.impala.catalog.Table.getName(), com.cloudera.impala.catalog.Column.getType(), com.cloudera.impala.catalog.HdfsTable.hasWriteAccess(), com.cloudera.impala.authorization.Privilege.INSERT, com.cloudera.impala.common.FileSystemUtil.isDistributedFileSystem(), com.cloudera.impala.analysis.TableName.isFullyQualified(), com.cloudera.impala.analysis.InsertStmt.overwrite_, com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, com.cloudera.impala.catalog.HdfsTable.spansMultipleFileSystems(), com.cloudera.impala.analysis.InsertStmt.table_, and com.cloudera.impala.analysis.InsertStmt.targetTableName_.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze().
void com.cloudera.impala.analysis.InsertStmt.setTargetTable (Table table) inline
Definition at line 621 of file InsertStmt.java.
String com.cloudera.impala.analysis.InsertStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 640 of file InsertStmt.java.
References com.cloudera.impala.analysis.InsertStmt.columnPermutation_, com.cloudera.impala.analysis.InsertStmt.needsGeneratedQueryStatement_, com.cloudera.impala.analysis.InsertStmt.originalTableName_, com.cloudera.impala.analysis.InsertStmt.overwrite_, com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_, com.cloudera.impala.analysis.InsertStmt.planHints_, and com.cloudera.impala.analysis.InsertStmt.withClause_.
Member Data Documentation
final List<String> com.cloudera.impala.analysis.InsertStmt.columnPermutation_ private
Definition at line 111 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), and com.cloudera.impala.analysis.InsertStmt.toSql().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
Boolean com.cloudera.impala.analysis.InsertStmt.isRepartition_ = null private
Definition at line 85 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyzePlanHints(), and com.cloudera.impala.analysis.InsertStmt.isRepartition().
final Logger com.cloudera.impala.analysis.InsertStmt.LOG = LoggerFactory.getLogger(InsertStmt.class) static private
Definition at line 47 of file InsertStmt.java.
final boolean com.cloudera.impala.analysis.InsertStmt.needsGeneratedQueryStatement_ private
Definition at line 74 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), com.cloudera.impala.analysis.InsertStmt.prepareExpressions(), and com.cloudera.impala.analysis.InsertStmt.toSql().
final TableName com.cloudera.impala.analysis.InsertStmt.originalTableName_ private
Definition at line 53 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.InsertStmt(), and com.cloudera.impala.analysis.InsertStmt.toSql().
final boolean com.cloudera.impala.analysis.InsertStmt.overwrite_ private
Definition at line 59 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.createDataSink(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), com.cloudera.impala.analysis.InsertStmt.isOverwrite(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), and com.cloudera.impala.analysis.InsertStmt.toSql().
final List<Expr> com.cloudera.impala.analysis.InsertStmt.partitionKeyExprs_ = new ArrayList<Expr>() private
Definition at line 80 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.createDataSink(), com.cloudera.impala.analysis.InsertStmt.getPartitionKeyExprs(), and com.cloudera.impala.analysis.InsertStmt.prepareExpressions().
final List<PartitionKeyValue> com.cloudera.impala.analysis.InsertStmt.partitionKeyValues_ private
Definition at line 63 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.InsertStmt.analyzePlanHints(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), com.cloudera.impala.analysis.InsertStmt.prepareExpressions(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), and com.cloudera.impala.analysis.InsertStmt.toSql().
final List<String> com.cloudera.impala.analysis.InsertStmt.planHints_ private
Definition at line 66 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyzePlanHints(), com.cloudera.impala.analysis.InsertStmt.getPlanHints(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), and com.cloudera.impala.analysis.InsertStmt.toSql().
QueryStmt com.cloudera.impala.analysis.InsertStmt.queryStmt_ private
Definition at line 70 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.InsertStmt.getQueryStmt(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), com.cloudera.impala.analysis.InsertStmt.prepareExpressions(), and com.cloudera.impala.analysis.InsertStmt.setQueryStmt().
final ArrayList<Expr> com.cloudera.impala.analysis.InsertStmt.resultExprs_ = new ArrayList<Expr>() private
Definition at line 91 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.getResultExprs(), and com.cloudera.impala.analysis.InsertStmt.prepareExpressions().
Table com.cloudera.impala.analysis.InsertStmt.table_ private
Definition at line 77 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.InsertStmt.analyzePlanHints(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.analysis.InsertStmt.createDataSink(), com.cloudera.impala.analysis.InsertStmt.getTargetTable(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), com.cloudera.impala.analysis.InsertStmt.prepareExpressions(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
TableName com.cloudera.impala.analysis.InsertStmt.targetTableName_ private
Definition at line 56 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.checkTypeCompatibility(), com.cloudera.impala.analysis.InsertStmt.getTargetTableName(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
final WithClause com.cloudera.impala.analysis.InsertStmt.withClause_ private
Definition at line 50 of file InsertStmt.java.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.InsertStmt.InsertStmt(), and com.cloudera.impala.analysis.InsertStmt.toSql().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/InsertStmt.java