Impala: com.cloudera.impala.analysis.FunctionName Class Reference
com.cloudera.impala.analysis.FunctionName Class Reference
Public Member Functions
FunctionName (ArrayList< String > fnNamePath)
FunctionName (String dbName, String fn)
FunctionName (String fn)
boolean equals (Object obj)
String getDb ()
String getFunction ()
boolean isFullyQualified ()
boolean isBuiltin ()
ArrayList< String > getFnNamePath ()
String toString ()
void analyze (Analyzer analyzer) throws AnalysisException
TFunctionName toThrift ()
Static Public Member Functions
static FunctionName fromThrift (TFunctionName fnName)
Private Member Functions
void analyzeFnNamePath () throws AnalysisException
boolean isValidCharacter (char c)
Private Attributes
final ArrayList< String > fnNamePath_
String db_
String fn_
boolean isBuiltin_ = false
boolean isAnalyzed_ = false
Detailed Description
Class to represent a function name. Function names are specified as db.function_name.
Definition at line 30 of file FunctionName.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.FunctionName.FunctionName (ArrayList< String > fnNamePath) inline
C'tor for parsed function names. The function names could be invalid. The validity is checked during analysis.
Definition at line 44 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.fnNamePath_.
Referenced by com.cloudera.impala.analysis.FunctionName.equals(), and com.cloudera.impala.analysis.FunctionName.fromThrift().
com.cloudera.impala.analysis.FunctionName.FunctionName (String dbName, String fn) inline
Definition at line 48 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.db_, com.cloudera.impala.analysis.FunctionName.fn_, and com.cloudera.impala.analysis.FunctionName.fnNamePath_.
com.cloudera.impala.analysis.FunctionName.FunctionName (String fn) inline
Definition at line 54 of file FunctionName.java.
Member Function Documentation
void com.cloudera.impala.analysis.FunctionName.analyze (Analyzer analyzer) throws AnalysisException inline
Definition at line 84 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.analyzeFnNamePath(), com.cloudera.impala.catalog.Catalog.BUILTINS_DB, com.cloudera.impala.catalog.Db.containsFunction(), com.cloudera.impala.analysis.FunctionName.db_, com.cloudera.impala.analysis.FunctionName.fn_, com.cloudera.impala.analysis.FunctionName.isAnalyzed_, com.cloudera.impala.analysis.FunctionName.isBuiltin_, com.cloudera.impala.analysis.FunctionName.isFullyQualified(), and com.cloudera.impala.analysis.FunctionName.isValidCharacter().
void com.cloudera.impala.analysis.FunctionName.analyzeFnNamePath () throws AnalysisException inline private
Definition at line 117 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.db_, com.cloudera.impala.analysis.FunctionName.fn_, and com.cloudera.impala.analysis.FunctionName.fnNamePath_.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze().
boolean com.cloudera.impala.analysis.FunctionName.equals (Object obj) inline
Definition at line 59 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.db_, and com.cloudera.impala.analysis.FunctionName.FunctionName().
Referenced by com.cloudera.impala.catalog.Function.isIdentical(), com.cloudera.impala.catalog.Function.isIndistinguishable(), and com.cloudera.impala.catalog.Function.isSuperTypeOf().
static FunctionName com.cloudera.impala.analysis.FunctionName.fromThrift (TFunctionName fnName) inline static
Definition at line 142 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.FunctionName().
Referenced by com.cloudera.impala.service.CatalogOpExecutor.dropFunction(), and com.cloudera.impala.catalog.Function.fromThrift().
String com.cloudera.impala.analysis.FunctionName.getDb () inline
Definition at line 70 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.db_.
Referenced by com.cloudera.impala.catalog.Catalog.containsFunction(), and com.cloudera.impala.analysis.Analyzer.getTargetDbName().
ArrayList<String> com.cloudera.impala.analysis.FunctionName.getFnNamePath () inline
Definition at line 74 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.fnNamePath_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.createExpr().
String com.cloudera.impala.analysis.FunctionName.getFunction () inline
Definition at line 71 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.fn_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.getFunctionNotFoundError(), com.cloudera.impala.analysis.FunctionCallExpr.resolveDecimalReturnType(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
boolean com.cloudera.impala.analysis.FunctionName.isBuiltin () inline
Definition at line 73 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.isBuiltin_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.getFunctionNotFoundError().
boolean com.cloudera.impala.analysis.FunctionName.isFullyQualified () inline
Definition at line 72 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.db_.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze().
boolean com.cloudera.impala.analysis.FunctionName.isValidCharacter (char c) inline private
Definition at line 132 of file FunctionName.java.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze().
String com.cloudera.impala.analysis.FunctionName.toString () inline
Definition at line 77 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.db_, com.cloudera.impala.analysis.FunctionName.fn_, com.cloudera.impala.analysis.FunctionName.fnNamePath_, com.cloudera.impala.analysis.FunctionName.isAnalyzed_, and com.cloudera.impala.analysis.FunctionName.isBuiltin_.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.createMergeAggCall().
TFunctionName com.cloudera.impala.analysis.FunctionName.toThrift () inline
Definition at line 136 of file FunctionName.java.
References com.cloudera.impala.analysis.FunctionName.db_, com.cloudera.impala.analysis.FunctionName.fn_, and impala.name.
Member Data Documentation
String com.cloudera.impala.analysis.FunctionName.db_ private
Definition at line 35 of file FunctionName.java.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze(), com.cloudera.impala.analysis.FunctionName.analyzeFnNamePath(), com.cloudera.impala.analysis.FunctionName.equals(), com.cloudera.impala.analysis.FunctionName.FunctionName(), com.cloudera.impala.analysis.FunctionName.getDb(), com.cloudera.impala.analysis.FunctionName.isFullyQualified(), com.cloudera.impala.analysis.FunctionName.toString(), and com.cloudera.impala.analysis.FunctionName.toThrift().
String com.cloudera.impala.analysis.FunctionName.fn_ private
Definition at line 36 of file FunctionName.java.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze(), com.cloudera.impala.analysis.FunctionName.analyzeFnNamePath(), com.cloudera.impala.analysis.FunctionName.FunctionName(), com.cloudera.impala.analysis.FunctionName.getFunction(), com.cloudera.impala.analysis.FunctionName.toString(), and com.cloudera.impala.analysis.FunctionName.toThrift().
final ArrayList<String> com.cloudera.impala.analysis.FunctionName.fnNamePath_ private
Definition at line 32 of file FunctionName.java.
Referenced by com.cloudera.impala.analysis.FunctionName.analyzeFnNamePath(), com.cloudera.impala.analysis.FunctionName.FunctionName(), com.cloudera.impala.analysis.FunctionName.getFnNamePath(), and com.cloudera.impala.analysis.FunctionName.toString().
boolean com.cloudera.impala.analysis.FunctionName.isAnalyzed_ = false private
Definition at line 38 of file FunctionName.java.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze(), and com.cloudera.impala.analysis.FunctionName.toString().
boolean com.cloudera.impala.analysis.FunctionName.isBuiltin_ = false private
Definition at line 37 of file FunctionName.java.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze(), com.cloudera.impala.analysis.FunctionName.isBuiltin(), and com.cloudera.impala.analysis.FunctionName.toString().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/FunctionName.java