Impala: com.cloudera.impala.planner.HashJoinNode Class Reference
com.cloudera.impala.planner.HashJoinNode Class Reference
Classes
enum DistributionMode
Public Member Functions
HashJoinNode (PlanNode outer, PlanNode inner, TableRef tblRef, List< BinaryPredicate > eqJoinConjuncts, List< Expr > otherJoinConjuncts)
List< BinaryPredicate > getEqJoinConjuncts ()
JoinOperator getJoinOp ()
TableRef getTableRef ()
DistributionMode getDistributionMode ()
void setDistributionMode (DistributionMode distrMode)
void setAddProbeFilters (boolean b)
void init (Analyzer analyzer) throws InternalException
void computeStats (Analyzer analyzer)
void computeCosts (TQueryOptions queryOptions)
PlanNodeId getId ()
void setId (PlanNodeId id)
long getLimit ()
boolean hasLimit ()
long getPerHostMemCost ()
long getCardinality ()
int getNumNodes ()
float getAvgRowSize ()
void setFragment (PlanFragment fragment)
PlanFragment getFragment ()
List< Expr > getConjuncts ()
ExprSubstitutionMap getOutputSmap ()
void setOutputSmap (ExprSubstitutionMap smap)
Set< ExprId > getAssignedConjuncts ()
void setAssignedConjuncts (Set< ExprId > conjuncts)
void setLimit (long limit)
void unsetLimit ()
ArrayList< TupleId > getTupleIds ()
ArrayList< TupleId > getTblRefIds ()
void setTblRefIds (ArrayList< TupleId > ids)
Set< TupleId > getNullableTupleIds ()
void addConjuncts (List< Expr > conjuncts)
void transferConjuncts (PlanNode recipient)
String getExplainString ()
TPlan treeToThrift ()
boolean isBlockingNode ()
long getInputCardinality ()
Static Public Member Functions
static long addCardinalities (long a, long b)
static long multiplyCardinalities (long a, long b)
Protected Member Functions
String debugString ()
void toThrift (TPlanNode msg)
String getDisplayLabelDetail ()
String getNodeExplainString (String prefix, String detailPrefix, TExplainLevel detailLevel)
final String getExplainString (String rootPrefix, String prefix, TExplainLevel detailLevel)
String getExplainString (List<?extends Expr > exprs)
void setDisplayName (String s)
final String getDisplayLabel ()
String getOffsetExplainString (String prefix)
void assignConjuncts (Analyzer analyzer)
ExprSubstitutionMap getCombinedChildSmap ()
void createDefaultSmap (Analyzer analyzer)
long capAtLimit (long cardinality)
void markSlotsMaterialized (Analyzer analyzer, List< Expr > exprs)
void computeMemLayout (Analyzer analyzer)
double computeSelectivity ()
boolean hasValidStats ()
Protected Attributes
String displayName_
PlanNodeId id_
long limit_
ArrayList< TupleId > tupleIds_
ArrayList< TupleId > tblRefIds_
Set< TupleId > nullableTupleIds_ = Sets.newHashSet()
List< Expr > conjuncts_ = Lists.newArrayList()
PlanFragment fragment_
ExprSubstitutionMap outputSmap_
Set< ExprId > assignedConjuncts_
long cardinality_
int numNodes_
float avgRowSize_
long perHostMemCost_ = -1
Static Protected Attributes
static final int DEFAULT_BATCH_SIZE = 1024
Private Member Functions
long getJoinCardinality (Analyzer analyzer)
long getSemiJoinCardinality ()
long getNdv (Expr expr)
String eqJoinConjunctsDebugString ()
Private Attributes
final TableRef tblRef_
final JoinOperator joinOp_
DistributionMode distrMode_
List< BinaryPredicate > eqJoinConjuncts_
List< Expr > otherJoinConjuncts_
boolean addProbeFilters_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(HashJoinNode.class)
static final long DEFAULT_PER_HOST_MEM = 2L * 1024L * 1024L * 1024L
Detailed Description
Hash join between left child (outer) and right child (inner). One child must be the plan generated for a table ref. Typically, that is the right child, but due to join inversion (for outer/semi/cross joins) it could also be the left child.
Definition at line 50 of file HashJoinNode.java.
Constructor & Destructor Documentation
com.cloudera.impala.planner.HashJoinNode.HashJoinNode (PlanNode outer, PlanNode inner, TableRef tblRef, List< BinaryPredicate > eqJoinConjuncts, List< Expr > otherJoinConjuncts) inline
Definition at line 90 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.distrMode_, com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_, com.cloudera.impala.analysis.JoinOperator.FULL_OUTER_JOIN, com.cloudera.impala.planner.HashJoinNode.joinOp_, com.cloudera.impala.analysis.JoinOperator.LEFT_OUTER_JOIN, com.cloudera.impala.planner.HashJoinNode.DistributionMode.NONE, com.cloudera.impala.planner.HashJoinNode.otherJoinConjuncts_, com.cloudera.impala.analysis.JoinOperator.RIGHT_OUTER_JOIN, and com.cloudera.impala.planner.HashJoinNode.tblRef_.
Member Function Documentation
static long com.cloudera.impala.planner.PlanNode.addCardinalities (long a, long b) inline static inherited
Computes and returns the sum of two cardinalities. If an overflow occurs, the maximum Long value is returned (Long.MAX_VALUE).
Definition at line 528 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), and com.cloudera.impala.planner.PlanNode.getInputCardinality().
void com.cloudera.impala.planner.PlanNode.addConjuncts (List< Expr > conjuncts) inline inherited
Definition at line 209 of file PlanNode.java.
void com.cloudera.impala.planner.PlanNode.assignConjuncts (Analyzer analyzer) inline protected inherited
Assign remaining unassigned conjuncts.
Definition at line 401 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.init().
long com.cloudera.impala.planner.PlanNode.capAtLimit (long cardinality) inline protected inherited
Definition at line 450 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.hasLimit(), and com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.SortNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), and com.cloudera.impala.planner.HdfsScanNode.computeStats().
void com.cloudera.impala.planner.HashJoinNode.computeCosts (TQueryOptions queryOptions) inline
Definition at line 490 of file HashJoinNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_, com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.planner.HashJoinNode.DEFAULT_PER_HOST_MEM, com.cloudera.impala.planner.HashJoinNode.distrMode_, com.cloudera.impala.planner.PlanNode.getAvgRowSize(), com.cloudera.impala.planner.PlanNode.getCardinality(), com.cloudera.impala.planner.PlannerContext.HASH_TBL_SPACE_OVERHEAD, com.cloudera.impala.planner.PlanNode.numNodes_, com.cloudera.impala.planner.HashJoinNode.DistributionMode.PARTITIONED, and com.cloudera.impala.planner.PlanNode.perHostMemCost_.
void com.cloudera.impala.planner.PlanNode.computeMemLayout (Analyzer analyzer) inline protected inherited
Call computeMemLayout() for all materialized tuples.
Definition at line 475 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tupleIds_.
Referenced by com.cloudera.impala.planner.EmptySetNode.init(), com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), and com.cloudera.impala.planner.UnionNode.init().
double com.cloudera.impala.planner.PlanNode.computeSelectivity () inline protected inherited
Compute the product of the selectivies of all conjuncts.
Definition at line 484 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
Referenced by com.cloudera.impala.planner.SelectNode.computeStats(), com.cloudera.impala.planner.CrossJoinNode.computeStats(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), and com.cloudera.impala.planner.HdfsScanNode.computeStats().
void com.cloudera.impala.planner.HashJoinNode.computeStats (Analyzer analyzer) inline
Definition at line 360 of file HashJoinNode.java.
References com.cloudera.impala.planner.PlanNode.addCardinalities(), com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.planner.HashJoinNode.getJoinCardinality(), com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality(), com.cloudera.impala.planner.PlanNode.hasValidStats(), com.cloudera.impala.analysis.JoinOperator.isSemiJoin(), and com.cloudera.impala.planner.HashJoinNode.joinOp_.
Referenced by com.cloudera.impala.planner.HashJoinNode.init().
void com.cloudera.impala.planner.PlanNode.createDefaultSmap (Analyzer analyzer) inline protected inherited
Sets outputSmap_ to compose(existing smap, combined child smap). Also substitutes conjuncts_ using the combined child smap.
Definition at line 425 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_, com.cloudera.impala.planner.PlanNode.getCombinedChildSmap(), and com.cloudera.impala.planner.PlanNode.outputSmap_.
Referenced by com.cloudera.impala.planner.SelectNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.init().
String com.cloudera.impala.planner.HashJoinNode.debugString () inline protected
Definition at line 423 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.eqJoinConjunctsDebugString().
String com.cloudera.impala.planner.HashJoinNode.eqJoinConjunctsDebugString () inline private
Definition at line 430 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_.
Referenced by com.cloudera.impala.planner.HashJoinNode.debugString().
Set<ExprId> com.cloudera.impala.planner.PlanNode.getAssignedConjuncts () inline inherited
Definition at line 180 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.assignedConjuncts_.
float com.cloudera.impala.planner.PlanNode.getAvgRowSize () inline inherited
Definition at line 174 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), and com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan().
long com.cloudera.impala.planner.PlanNode.getCardinality () inline inherited
Definition at line 172 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan(), and com.cloudera.impala.planner.SingleNodePlanner.createJoinPlan().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.getCombinedChildSmap () inline protected inherited
Returns an smap that combines the childrens' smaps.
Definition at line 410 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.HashJoinNode.init().
List<Expr> com.cloudera.impala.planner.PlanNode.getConjuncts () inline inherited
Definition at line 177 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
Referenced by com.cloudera.impala.planner.ScanNode.getInputCardinality().
final String com.cloudera.impala.planner.PlanNode.getDisplayLabel () inline protected inherited
Definition at line 225 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.displayName_.
Referenced by com.cloudera.impala.planner.ExchangeNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
String com.cloudera.impala.planner.HashJoinNode.getDisplayLabelDetail () inline protected
Definition at line 456 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.distrMode_, com.cloudera.impala.planner.HashJoinNode.joinOp_, com.cloudera.impala.planner.HashJoinNode.DistributionMode.NONE, and com.cloudera.impala.analysis.JoinOperator.toString().
Referenced by com.cloudera.impala.planner.HashJoinNode.getNodeExplainString().
DistributionMode com.cloudera.impala.planner.HashJoinNode.getDistributionMode () inline
Definition at line 144 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.distrMode_.
Referenced by com.cloudera.impala.planner.PlanFragment.computeCanAddSlotFilters().
List<BinaryPredicate> com.cloudera.impala.planner.HashJoinNode.getEqJoinConjuncts () inline
Definition at line 141 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_.
String com.cloudera.impala.planner.PlanNode.getExplainString () inline inherited
Definition at line 219 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.getDisplayLabelDetail(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), and com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString().
final String com.cloudera.impala.planner.PlanNode.getExplainString (String rootPrefix, String prefix, TExplainLevel detailLevel) inline protected inherited
Generate the explain plan tree. The plan will be in the form of:
root | |-—child 3 | limit:1 | |-—child 2 | limit:2 | child 1
The root node header line will be prefixed by rootPrefix and the remaining plan output will be prefixed by prefix.
Definition at line 252 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_, com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getNodeExplainString(), com.cloudera.impala.planner.PlanNode.getOffsetExplainString(), com.cloudera.impala.planner.PlanNode.limit_, com.cloudera.impala.planner.PlanNode.numNodes_, com.cloudera.impala.planner.PlanNode.perHostMemCost_, and com.cloudera.impala.planner.PlanNode.tupleIds_.
String com.cloudera.impala.planner.PlanNode.getExplainString (List<?extends Expr > exprs) inline protected inherited
Definition at line 506 of file PlanNode.java.
PlanFragment com.cloudera.impala.planner.PlanNode.getFragment () inline inherited
Definition at line 176 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.fragment_.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), and com.cloudera.impala.planner.PipelinedPlanNodeSet.computePlanNodeSets().
PlanNodeId com.cloudera.impala.planner.PlanNode.getId () inline inherited
Definition at line 164 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.id_.
Referenced by com.cloudera.impala.planner.DataStreamSink.getExplainString(), com.cloudera.impala.planner.AggregationNode.init(), and com.cloudera.impala.planner.DataStreamSink.toThrift().
long com.cloudera.impala.planner.PlanNode.getInputCardinality () inline inherited
The input cardinality is the sum of output cardinalities of its children. For scan nodes the input cardinality is the expected number of rows scanned.
Definition at line 570 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.addCardinalities().
long com.cloudera.impala.planner.HashJoinNode.getJoinCardinality (Analyzer analyzer) inline private
Returns the estimated cardinality of an inner or outer join. For a join between child(0) and child(1), we look for join conditions "L.c = R.d" (with L being from child(0) and R from child(1)) and use as the cardinality estimate the maximum of |child(0)| * |R| / NDV(R.d) * |child(1)| / |R| across all suitable join conditions, which simplifies to |child(0)| * |child(1)| / NDV(R.d) The reasoning is that
each row in child(0) joins with |R| / NDV(R.d) rows in R
each row in R is 'present' in |child(1)| / |R| rows in child(1)
This handles the very frequent case of a fact table/dimension table join (aka foreign key/primary key join) if the primary key is a single column, with possible additional predicates against the dimension table. An example: FROM FactTbl F JOIN Customers C D ON (F.cust_id = C.id) ... WHERE C.region = 'US'
if there are 5 regions, the selectivity of "C.region = 'US'" would be 0.2 and the output cardinality of the Customers scan would be 0.2 * # rows in Customers
# rows in Customers == # of distinct values for Customers.id
the output cardinality of the join would be F.cardinality * 0.2
Definition at line 222 of file HashJoinNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_, com.cloudera.impala.catalog.ColumnStats.hasNumDistinctValues(), com.cloudera.impala.planner.HashJoinNode.joinOp_, and com.cloudera.impala.planner.PlanNode.multiplyCardinalities().
Referenced by com.cloudera.impala.planner.HashJoinNode.computeStats().
JoinOperator com.cloudera.impala.planner.HashJoinNode.getJoinOp () inline
Definition at line 142 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.joinOp_.
Referenced by com.cloudera.impala.planner.PlanFragment.computeCanAddSlotFilters().
long com.cloudera.impala.planner.PlanNode.getLimit () inline inherited
Definition at line 169 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.ScanNode.getInputCardinality().
long com.cloudera.impala.planner.HashJoinNode.getNdv (Expr expr) inline private
Unwraps the SlotRef in expr and returns the NDVs of it. Returns -1 if the NDVs are unknown or if expr is not a SlotRef.
Definition at line 349 of file HashJoinNode.java.
References com.cloudera.impala.catalog.ColumnStats.hasNumDistinctValues().
Referenced by com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality().
String com.cloudera.impala.planner.HashJoinNode.getNodeExplainString (String prefix, String detailPrefix, TExplainLevel detailLevel) inline protected
Definition at line 463 of file HashJoinNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_, com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_, com.cloudera.impala.planner.PlanNode.getDisplayLabel(), com.cloudera.impala.planner.HashJoinNode.getDisplayLabelDetail(), com.cloudera.impala.planner.PlanNode.getExplainString(), and com.cloudera.impala.planner.HashJoinNode.otherJoinConjuncts_.
Set<TupleId> com.cloudera.impala.planner.PlanNode.getNullableTupleIds () inline inherited
Definition at line 204 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.nullableTupleIds_.
int com.cloudera.impala.planner.PlanNode.getNumNodes () inline inherited
Definition at line 173 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.numNodes_.
Referenced by com.cloudera.impala.planner.PipelinedPlanNodeSet.computeResourceEstimates(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), and com.cloudera.impala.planner.DataSourceScanNode.computeStats().
String com.cloudera.impala.planner.PlanNode.getOffsetExplainString (String prefix) inline protected inherited
Return the offset_ details, if applicable. This is available separately from 'getNodeExplainString' because we want to output 'limit: ...' (which can be printed from PlanNode) before 'offset: ...', which is only printed from SortNodes right now.
Definition at line 336 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getExplainString().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.getOutputSmap () inline inherited
Definition at line 178 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.outputSmap_.
long com.cloudera.impala.planner.PlanNode.getPerHostMemCost () inline inherited
Definition at line 171 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.perHostMemCost_.
Referenced by com.cloudera.impala.planner.PipelinedPlanNodeSet.computeResourceEstimates().
long com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality () inline private
Returns the estimated cardinality of a semi join node. For a left semi join between child(0) and child(1), we look for equality join conditions "L.c = R.d" (with L being from child(0) and R from child(1)) and use as the cardinality estimate the minimum of |child(0)| * Min(NDV(L.c), NDV(R.d)) / NDV(L.c) over all suitable join conditions. The reasoning is that:
each row in child(0) is returned at most once
the probability of a row in child(0) having a match in R is Min(NDV(L.c), NDV(R.d)) / NDV(L.c)
For a left anti join we estimate the cardinality as the minimum of: |L| * Max(NDV(L.c) - NDV(R.d), NDV(L.c)) / NDV(L.c) over all suitable join conditions. The reasoning is that:
each row in child(0) is returned at most once
if NDV(L.c) > NDV(R.d) then the probability of row in L having a match in child(1) is (NDV(L.c) - NDV(R.d)) / NDV(L.c)
otherwise, we conservatively use |L| to avoid underestimation
We analogously estimate the cardinality for right semi/anti joins, and treat the null-aware anti join like a regular anti join
TODO: In order to take into account additional conjuncts in the child child subtrees adjust NDV(L.c) by |child(0)| / |L| and the NDV(R.d) by |child(1)| / |R|. The adjustment is currently too dangerous due to the other planner bugs compounding to bad plans causing perf regressions (IMPALA-976).
Definition at line 294 of file HashJoinNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_, com.cloudera.impala.planner.HashJoinNode.getNdv(), com.cloudera.impala.planner.HashJoinNode.joinOp_, com.cloudera.impala.analysis.JoinOperator.RIGHT_ANTI_JOIN, and com.cloudera.impala.analysis.JoinOperator.RIGHT_SEMI_JOIN.
Referenced by com.cloudera.impala.planner.HashJoinNode.computeStats().
TableRef com.cloudera.impala.planner.HashJoinNode.getTableRef () inline
Definition at line 143 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.tblRef_.
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.getTblRefIds () inline inherited
Definition at line 201 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tblRefIds_.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.getTupleIds () inline inherited
Definition at line 196 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tupleIds_.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.SingleNodePlanner.createInlineViewPlan(), com.cloudera.impala.planner.AnalyticPlanner.createSortInfo(), and com.cloudera.impala.planner.SelectNode.SelectNode().
boolean com.cloudera.impala.planner.PlanNode.hasLimit () inline inherited
Definition at line 170 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.PlanNode.capAtLimit(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.ScanNode.getInputCardinality(), and com.cloudera.impala.planner.SortNode.getNodeExplainDetail().
boolean com.cloudera.impala.planner.PlanNode.hasValidStats () inline protected inherited
Returns true if stats-related variables are valid.
Definition at line 519 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_, and com.cloudera.impala.planner.PlanNode.numNodes_.
Referenced by com.cloudera.impala.planner.SortNode.computeCosts(), and com.cloudera.impala.planner.HashJoinNode.computeStats().
void com.cloudera.impala.planner.HashJoinNode.init (Analyzer analyzer) throws InternalException inline
Definition at line 149 of file HashJoinNode.java.
References com.cloudera.impala.planner.PlanNode.assignConjuncts(), com.cloudera.impala.planner.PlanNode.assignedConjuncts_, com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_, com.cloudera.impala.planner.PlanNode.getCombinedChildSmap(), com.cloudera.impala.analysis.BinaryPredicate.getOp(), com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isStringType(), com.cloudera.impala.catalog.Type.matchesType(), com.cloudera.impala.planner.HashJoinNode.otherJoinConjuncts_, com.cloudera.impala.analysis.Expr.substitute(), and com.cloudera.impala.catalog.Type.toSql().
boolean com.cloudera.impala.planner.PlanNode.isBlockingNode () inline inherited
Returns true if this plan node can output its first row only after consuming all rows of all its children. This method is used to group plan nodes into pipelined units for resource estimation.
Definition at line 555 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PipelinedPlanNodeSet.computePlanNodeSets().
void com.cloudera.impala.planner.PlanNode.markSlotsMaterialized (Analyzer analyzer, List< Expr > exprs) inline protected inherited
Marks all slots referenced in exprs as materialized.
Definition at line 464 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.init().
static long com.cloudera.impala.planner.PlanNode.multiplyCardinalities (long a, long b) inline static inherited
Computes and returns the product of two cardinalities. If an overflow occurs, the maximum Long value is returned (Long.MAX_VALUE).
Definition at line 541 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeStats(), and com.cloudera.impala.planner.HashJoinNode.getJoinCardinality().
void com.cloudera.impala.planner.HashJoinNode.setAddProbeFilters (boolean b) inline
Definition at line 146 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.addProbeFilters_.
void com.cloudera.impala.planner.PlanNode.setAssignedConjuncts (Set< ExprId > conjuncts) inline inherited
Definition at line 181 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.assignedConjuncts_.
void com.cloudera.impala.planner.PlanNode.setDisplayName (String s) inline protected inherited
Definition at line 223 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.displayName_.
void com.cloudera.impala.planner.HashJoinNode.setDistributionMode (DistributionMode distrMode) inline
Definition at line 145 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.distrMode_.
void com.cloudera.impala.planner.PlanNode.setFragment (PlanFragment fragment) inline inherited
Definition at line 175 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.fragment_.
void com.cloudera.impala.planner.PlanNode.setId (PlanNodeId id) inline inherited
Definition at line 165 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.id_.
void com.cloudera.impala.planner.PlanNode.setLimit (long limit) inline inherited
Set the limit_ to the given limit_ only if the limit_ hasn't been set, or the new limit_ is lower.
Parameters
limit_
Definition at line 190 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
void com.cloudera.impala.planner.PlanNode.setOutputSmap (ExprSubstitutionMap smap) inline inherited
Definition at line 179 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.outputSmap_.
void com.cloudera.impala.planner.PlanNode.setTblRefIds (ArrayList< TupleId > ids) inline inherited
Definition at line 202 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tblRefIds_.
void com.cloudera.impala.planner.HashJoinNode.toThrift (TPlanNode msg) inline protected
Definition at line 439 of file HashJoinNode.java.
References com.cloudera.impala.planner.HashJoinNode.addProbeFilters_, com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_, and com.cloudera.impala.planner.HashJoinNode.otherJoinConjuncts_.
void com.cloudera.impala.planner.PlanNode.transferConjuncts (PlanNode recipient) inline inherited
Definition at line 214 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
TPlan com.cloudera.impala.planner.PlanNode.treeToThrift () inline inherited
Definition at line 341 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
void com.cloudera.impala.planner.PlanNode.unsetLimit () inline inherited
Definition at line 194 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Member Data Documentation
boolean com.cloudera.impala.planner.HashJoinNode.addProbeFilters_ private
Definition at line 88 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.setAddProbeFilters(), and com.cloudera.impala.planner.HashJoinNode.toThrift().
Set<ExprId> com.cloudera.impala.planner.PlanNode.assignedConjuncts_ protected inherited
Definition at line 99 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getAssignedConjuncts(), com.cloudera.impala.planner.CrossJoinNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.setAssignedConjuncts().
float com.cloudera.impala.planner.PlanNode.avgRowSize_ protected inherited
Definition at line 110 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getAvgRowSize(), and com.cloudera.impala.planner.PlanNode.getExplainString().
long com.cloudera.impala.planner.PlanNode.cardinality_ protected inherited
Definition at line 103 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.SelectNode.computeStats(), com.cloudera.impala.planner.CrossJoinNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.SortNode.computeStats(), com.cloudera.impala.planner.AnalyticEvalNode.computeStats(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getCardinality(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.HashJoinNode.getJoinCardinality(), com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality(), com.cloudera.impala.planner.PlanNode.hasValidStats(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
List<Expr> com.cloudera.impala.planner.PlanNode.conjuncts_ = Lists.newArrayList() protected inherited
Definition at line 86 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.computeSelectivity(), com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.HBaseScanNode.createHBaseFilters(), com.cloudera.impala.planner.PlanNode.debugString(), com.cloudera.impala.planner.PlanNode.getConjuncts(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.planner.SelectNode.init(), com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.transferConjuncts(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
final int com.cloudera.impala.planner.PlanNode.DEFAULT_BATCH_SIZE = 1024 static protected inherited
Definition at line 63 of file PlanNode.java.
final long com.cloudera.impala.planner.HashJoinNode.DEFAULT_PER_HOST_MEM = 2L * 1024L * 1024L * 1024L static private
Definition at line 55 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.computeCosts().
String com.cloudera.impala.planner.PlanNode.displayName_ protected inherited
Definition at line 66 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getDisplayLabel(), com.cloudera.impala.planner.EmptySetNode.getNodeExplainString(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.SortNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.setDisplayName(), and com.cloudera.impala.planner.ExchangeNode.setMergeInfo().
DistributionMode com.cloudera.impala.planner.HashJoinNode.distrMode_ private
Definition at line 77 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.getDisplayLabelDetail(), com.cloudera.impala.planner.HashJoinNode.getDistributionMode(), com.cloudera.impala.planner.HashJoinNode.HashJoinNode(), and com.cloudera.impala.planner.HashJoinNode.setDistributionMode().
List<BinaryPredicate> com.cloudera.impala.planner.HashJoinNode.eqJoinConjuncts_ private
Definition at line 80 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.eqJoinConjunctsDebugString(), com.cloudera.impala.planner.HashJoinNode.getEqJoinConjuncts(), com.cloudera.impala.planner.HashJoinNode.getJoinCardinality(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality(), com.cloudera.impala.planner.HashJoinNode.HashJoinNode(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.HashJoinNode.toThrift().
PlanFragment com.cloudera.impala.planner.PlanNode.fragment_ protected inherited
Definition at line 90 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.ExchangeNode.getDisplayLabelDetail(), com.cloudera.impala.planner.PlanNode.getFragment(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.reorderOperands(), and com.cloudera.impala.planner.PlanNode.setFragment().
PlanNodeId com.cloudera.impala.planner.PlanNode.id_ protected inherited
Definition at line 69 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getId(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.setId().
final JoinOperator com.cloudera.impala.planner.HashJoinNode.joinOp_ private
Definition at line 60 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.HashJoinNode.getDisplayLabelDetail(), com.cloudera.impala.planner.HashJoinNode.getJoinCardinality(), com.cloudera.impala.planner.HashJoinNode.getJoinOp(), com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality(), and com.cloudera.impala.planner.HashJoinNode.HashJoinNode().
long com.cloudera.impala.planner.PlanNode.limit_ protected inherited
Definition at line 71 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.PlanNode.capAtLimit(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.PlanNode.debugString(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getLimit(), com.cloudera.impala.planner.SortNode.getNodeExplainDetail(), com.cloudera.impala.planner.PlanNode.hasLimit(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.setLimit(), com.cloudera.impala.planner.PlanNode.treeToThriftHelper(), and com.cloudera.impala.planner.PlanNode.unsetLimit().
final Logger com.cloudera.impala.planner.HashJoinNode.LOG = LoggerFactory.getLogger(HashJoinNode.class) static private
Definition at line 51 of file HashJoinNode.java.
Set<TupleId> com.cloudera.impala.planner.PlanNode.nullableTupleIds_ = Sets.newHashSet() protected inherited
Definition at line 84 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.PlanNode.getNullableTupleIds(), and com.cloudera.impala.planner.PlanNode.PlanNode().
int com.cloudera.impala.planner.PlanNode.numNodes_ protected inherited
Definition at line 107 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.HdfsScanNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getNumNodes(), com.cloudera.impala.planner.PlanNode.hasValidStats(), and com.cloudera.impala.planner.PlanNode.PlanNode().
List<Expr> com.cloudera.impala.planner.HashJoinNode.otherJoinConjuncts_ private
Definition at line 83 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.HashJoinNode(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.HashJoinNode.toThrift().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.outputSmap_ protected inherited
Definition at line 93 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.PlanNode.getOutputSmap(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.PlanNode.setOutputSmap().
long com.cloudera.impala.planner.PlanNode.perHostMemCost_ = -1 protected inherited
Definition at line 114 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AnalyticEvalNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.DataSourceScanNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.HBaseScanNode.computeCosts(), com.cloudera.impala.planner.PlanNode.computeCosts(), com.cloudera.impala.planner.HdfsScanNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getPerHostMemCost(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
final TableRef com.cloudera.impala.planner.HashJoinNode.tblRef_ private
Definition at line 59 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.getTableRef(), and com.cloudera.impala.planner.HashJoinNode.HashJoinNode().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.tblRefIds_ protected inherited
Definition at line 79 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getTblRefIds(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.setTblRefIds().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.tupleIds_ protected inherited
Definition at line 74 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.UnionNode.addChild(), com.cloudera.impala.planner.PlanNode.computeMemLayout(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getTupleIds(), com.cloudera.impala.planner.EmptySetNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.HdfsScanNode.prunePartitions(), com.cloudera.impala.planner.ExchangeNode.toThrift(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/planner/HashJoinNode.java