Impala: impala::SortedRunMerger::BatchedRowSupplier Class Reference
impala::SortedRunMerger::BatchedRowSupplier Class Reference
Public Member Functions
BatchedRowSupplier (SortedRunMerger *parent, const RunBatchSupplier &sorted_run)
Status Init (bool *done)
Status Next (RowBatch *transfer_batch, bool *done)
TupleRow * current_row () const
Private Attributes
RunBatchSupplier sorted_run_
RowBatch * input_row_batch_
int input_row_batch_index_
SortedRunMerger * parent_
Friends
class SortedRunMerger
Detailed Description
Definition at line 33 of file sorted-run-merger.cc.
Constructor & Destructor Documentation
impala::SortedRunMerger::BatchedRowSupplier::BatchedRowSupplier (SortedRunMerger * parent, const RunBatchSupplier & sorted_run) inline
Definition at line 36 of file sorted-run-merger.cc.
Member Function Documentation
TupleRow* impala::SortedRunMerger::BatchedRowSupplier::current_row () const inline
Definition at line 75 of file sorted-run-merger.cc.
References impala::RowBatch::GetRow(), input_row_batch_, and input_row_batch_index_.
Referenced by impala::SortedRunMerger::GetNext().
Status impala::SortedRunMerger::BatchedRowSupplier::Init (bool * done) inline
Definition at line 44 of file sorted-run-merger.cc.
References input_row_batch_, Next(), impala::Status::OK, RETURN_IF_ERROR, and sorted_run_.
Referenced by impala::SortedRunMerger::Prepare().
Status impala::SortedRunMerger::BatchedRowSupplier::Next (RowBatch * transfer_batch, bool * done) inline
Definition at line 56 of file sorted-run-merger.cc.
References impala::SortedRunMerger::get_next_batch_timer_, input_row_batch_, input_row_batch_index_, impala::RowBatch::num_rows(), impala::Status::OK, parent_, RETURN_IF_ERROR, sorted_run_, and impala::RowBatch::TransferResourceOwnership().
Referenced by impala::SortedRunMerger::GetNext(), and Init().
Friends And Related Function Documentation
friend class SortedRunMerger friend
Definition at line 80 of file sorted-run-merger.cc.
Member Data Documentation
RowBatch* impala::SortedRunMerger::BatchedRowSupplier::input_row_batch_ private
Definition at line 86 of file sorted-run-merger.cc.
Referenced by current_row(), Init(), and Next().
int impala::SortedRunMerger::BatchedRowSupplier::input_row_batch_index_ private
Definition at line 89 of file sorted-run-merger.cc.
Referenced by current_row(), and Next().
SortedRunMerger* impala::SortedRunMerger::BatchedRowSupplier::parent_ private
Definition at line 92 of file sorted-run-merger.cc.
Referenced by Next().
RunBatchSupplier impala::SortedRunMerger::BatchedRowSupplier::sorted_run_ private
Definition at line 83 of file sorted-run-merger.cc.
Referenced by Init(), and Next().
The documentation for this class was generated from the following file:
be/src/runtime/sorted-run-merger.cc