Impala: com.cloudera.impala.catalog.HdfsPartition.FileDescriptor Class Reference
com.cloudera.impala.catalog.HdfsPartition.FileDescriptor Class Reference
Public Member Functions
String getFileName ()
long getFileLength ()
THdfsCompression getFileCompression ()
long getModificationTime ()
List< THdfsFileBlock > getFileBlocks ()
THdfsFileDesc toThrift ()
FileDescriptor (String fileName, long fileLength, long modificationTime)
void addFileBlock (FileBlock blockMd)
String toString ()
Static Public Member Functions
static FileDescriptor fromThrift (THdfsFileDesc desc)
Private Member Functions
FileDescriptor (THdfsFileDesc fileDesc)
Private Attributes
final THdfsFileDesc fileDescriptor_
Detailed Description
Metadata for a single file in this partition. TODO: Do we even need this class? Just get rid of it and use the Thrift version?
Definition at line 65 of file HdfsPartition.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.FileDescriptor (String fileName, long fileLength, long modificationTime) inline
Definition at line 82 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.fileDescriptor_, and com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.toThrift().
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.fromThrift().
com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.FileDescriptor (THdfsFileDesc fileDesc) inline private
Definition at line 95 of file HdfsPartition.java.
Member Function Documentation
void com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.addFileBlock (FileBlock blockMd) inline
Definition at line 102 of file HdfsPartition.java.
static FileDescriptor com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.fromThrift (THdfsFileDesc desc) inline static
Definition at line 106 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.FileDescriptor().
List<THdfsFileBlock> com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.getFileBlocks () inline
Definition at line 76 of file HdfsPartition.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.loadBlockMetadata().
THdfsCompression com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.getFileCompression () inline
Definition at line 70 of file HdfsPartition.java.
long com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.getFileLength () inline
Definition at line 69 of file HdfsPartition.java.
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.toString().
String com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.getFileName () inline
Definition at line 68 of file HdfsPartition.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.synthesizeBlockMetadata(), and com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.toString().
long com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.getModificationTime () inline
Definition at line 73 of file HdfsPartition.java.
String com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.toString () inline
Definition at line 111 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.getFileLength(), and com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.getFileName().
THdfsFileDesc com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.toThrift () inline
Definition at line 80 of file HdfsPartition.java.
References com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.fileDescriptor_.
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.FileDescriptor().
Member Data Documentation
final THdfsFileDesc com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.fileDescriptor_ private
Definition at line 66 of file HdfsPartition.java.
Referenced by com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.FileDescriptor(), and com.cloudera.impala.catalog.HdfsPartition.FileDescriptor.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HdfsPartition.java