Impala: impala::ThriftServer::ThriftServerEventProcessor Class Reference
impala::ThriftServer::ThriftServerEventProcessor Class Reference
Public Member Functions
ThriftServerEventProcessor (ThriftServer *thrift_server)
virtual void preServe ()
virtual void * createContext (shared_ptr< TProtocol > input, shared_ptr< TProtocol > output)
virtual void processContext (void *context, shared_ptr< TTransport > output)
virtual void deleteContext (void *serverContext, shared_ptr< TProtocol > input, shared_ptr< TProtocol > output)
Status StartAndWaitForServer ()
Private Member Functions
void Supervise ()
Private Attributes
boost::mutex signal_lock_
boost::condition_variable signal_cond_
ThriftServer * thrift_server_
bool signal_fired_
Static Private Attributes
static const int TIMEOUT_MS = 2500
Detailed Description
Definition at line 65 of file thrift-server.cc.
Constructor & Destructor Documentation
impala::ThriftServer::ThriftServerEventProcessor::ThriftServerEventProcessor (ThriftServer * thrift_server) inline
Definition at line 67 of file thrift-server.cc.
Member Function Documentation
void * impala::ThriftServer::ThriftServerEventProcessor::createContext (shared_ptr< TProtocol > input, shared_ptr< TProtocol > output) virtual
Definition at line 205 of file thrift-server.cc.
References impala::__connection_context__, apache::thrift::transport::TSaslTransport::getUnderlyingTransport(), apache::thrift::transport::TSaslTransport::getUsername(), impala::MakeNetworkAddress(), and impala::UUIDToTUniqueId().
void impala::ThriftServer::ThriftServerEventProcessor::deleteContext (void * serverContext, shared_ptr< TProtocol > input, shared_ptr< TProtocol > output) virtual
Definition at line 258 of file thrift-server.cc.
References impala::__connection_context__.
void impala::ThriftServer::ThriftServerEventProcessor::preServe () virtual
Definition at line 177 of file thrift-server.cc.
void impala::ThriftServer::ThriftServerEventProcessor::processContext (void * context, shared_ptr< TTransport > output) virtual
Definition at line 253 of file thrift-server.cc.
References impala::__connection_context__.
Status impala::ThriftServer::ThriftServerEventProcessor::StartAndWaitForServer ()
Definition at line 115 of file thrift-server.cc.
References impala::name, and impala::OK.
void impala::ThriftServer::ThriftServerEventProcessor::Supervise () private
Definition at line 155 of file thrift-server.cc.
Member Data Documentation
boost::condition_variable impala::ThriftServer::ThriftServerEventProcessor::signal_cond_ private
Definition at line 99 of file thrift-server.cc.
bool impala::ThriftServer::ThriftServerEventProcessor::signal_fired_ private
Definition at line 106 of file thrift-server.cc.
boost::mutex impala::ThriftServer::ThriftServerEventProcessor::signal_lock_ private
Definition at line 95 of file thrift-server.cc.
ThriftServer* impala::ThriftServer::ThriftServerEventProcessor::thrift_server_ private
Definition at line 103 of file thrift-server.cc.
const int impala::ThriftServer::ThriftServerEventProcessor::TIMEOUT_MS = 2500 static private
Definition at line 109 of file thrift-server.cc.
The documentation for this class was generated from the following file:
be/src/rpc/thrift-server.cc