Impala: impala::AuthProvider Class Reference
impala::AuthProvider Class Reference abstract
#include <auth-provider.h>
Public Member Functions
virtual Status Start ()=0
Initialises any state required to perform authentication using this provider.
virtual Status GetServerTransportFactory (boost::shared_ptr< apache::thrift::transport::TTransportFactory > *factory)=0
virtual Status WrapClientTransport (const std::string &hostname, boost::shared_ptr< apache::thrift::transport::TTransport > raw_transport, const std::string &service_name, boost::shared_ptr< apache::thrift::transport::TTransport > *wrapped_transport)=0
virtual bool is_sasl ()=0
Returns true if this provider uses Sasl at the transport layer.
Detailed Description
An AuthProvider creates Thrift transports that are set up to authenticate themselves using a protocol such as Kerberos or PLAIN/SASL. Both server and client transports are provided by this class, using slightly different mechanisms (servers use a factory, clients wrap a pre-provided transport)
Definition at line 36 of file auth-provider.h.
Member Function Documentation
virtual Status impala::AuthProvider::GetServerTransportFactory (boost::shared_ptr< apache::thrift::transport::TTransportFactory > * factory) pure virtual
Creates a new Thrift transport factory in the out parameter that performs authorisation per this provider's protocol.
Implemented in impala::NoAuthProvider, and impala::SaslAuthProvider.
Referenced by impala::ThriftServer::Start().
virtual bool impala::AuthProvider::is_sasl () pure virtual
Returns true if this provider uses Sasl at the transport layer.
Implemented in impala::NoAuthProvider, and impala::SaslAuthProvider.
Referenced by impala::TEST().
virtual Status impala::AuthProvider::Start () pure virtual
Initialises any state required to perform authentication using this provider.
Implemented in impala::NoAuthProvider, and impala::SaslAuthProvider.
Referenced by main().
virtual Status impala::AuthProvider::WrapClientTransport (const std::string & hostname, boost::shared_ptr< apache::thrift::transport::TTransport > raw_transport, const std::string & service_name, boost::shared_ptr< apache::thrift::transport::TTransport > * wrapped_transport) pure virtual
Called by Thrift clients to wrap a raw transport with any intermediate transport that an auth protocol requires.
Implemented in impala::NoAuthProvider, and impala::SaslAuthProvider.
Referenced by impala::ThriftClient< InterfaceType >::ThriftClient().
The documentation for this class was generated from the following file:
be/src/rpc/auth-provider.h