Impala: com.cloudera.impala.catalog.ScalarType Class Reference
com.cloudera.impala.catalog.ScalarType Class Reference
Public Member Functions
String toString ()
String toSql ()
void toThrift (TColumnType container)
int decimalPrecision ()
int decimalScale ()
PrimitiveType getPrimitiveType ()
int ordinal ()
int getLength ()
boolean isWildcardDecimal ()
boolean isWildcardVarchar ()
boolean isWildcardChar ()
boolean isFullySpecifiedDecimal ()
boolean isFixedLengthType ()
boolean isSupported ()
boolean supportsTablePartitioning ()
int getSlotSize ()
boolean matchesType (Type t)
boolean equals (Object o)
Type getMaxResolutionType ()
ScalarType getNextResolutionType ()
ScalarType getMinResolutionDecimal ()
boolean isSupertypeOf (ScalarType o)
boolean isInvalid ()
boolean isValid ()
boolean isNull ()
boolean isBoolean ()
boolean isTimestamp ()
boolean isDecimal ()
boolean isDecimalOrNull ()
boolean isStringType ()
boolean isScalarType ()
boolean isScalarType (PrimitiveType t)
boolean isFixedPointType ()
boolean isFloatingPointType ()
boolean isIntegerType ()
boolean isNumericType ()
boolean isDateType ()
boolean isComplexType ()
boolean isCollectionType ()
boolean isMapType ()
boolean isArrayType ()
boolean isStructType ()
TColumnType toThrift ()
TPrimitiveType getTPrimitiveType (TColumnType ttype)
Integer getColumnSize ()
Integer getPrecision ()
Integer getDecimalDigits ()
Integer getNumPrecRadix ()
int getJavaSqlType ()
Static Public Member Functions
static ScalarType createType (PrimitiveType type)
static ScalarType createCharType (int len)
static ScalarType createDecimalType ()
static ScalarType createDecimalType (int precision)
static ScalarType createDecimalType (int precision, int scale)
static ScalarType createDecimalTypeInternal (int precision, int scale)
static ScalarType createVarcharType (int len)
static ScalarType createVarcharType ()
static Type[] toColumnType (PrimitiveType[] types)
static ScalarType getAssignmentCompatibleType (ScalarType t1, ScalarType t2)
static boolean isImplicitlyCastable (ScalarType t1, ScalarType t2)
static ArrayList< ScalarType > getIntegerTypes ()
static ArrayList< ScalarType > getNumericTypes ()
static ArrayList< ScalarType > getSupportedTypes ()
static List< TColumnType > toThrift (Type[] types)
static List< TColumnType > toThrift (ArrayList< Type > types)
static Type parseColumnType (FieldSchema fs)
static boolean isImplicitlyCastable (Type t1, Type t2)
static Type getAssignmentCompatibleType (Type t1, Type t2)
static Type fromThrift (TColumnType thrift)
Static Public Attributes
static final int DEFAULT_PRECISION = 9
static final int DEFAULT_SCALE = 0
static final int MAX_VARCHAR_LENGTH = 65355
static final int MAX_CHAR_LENGTH = 255
static final int CHAR_INLINE_LENGTH = 128
static final int MAX_PRECISION = 38
static final int MAX_SCALE = MAX_PRECISION
static final ScalarType INVALID = new ScalarType(PrimitiveType.INVALID_TYPE)
static final ScalarType NULL = new ScalarType(PrimitiveType.NULL_TYPE)
static final ScalarType BOOLEAN = new ScalarType(PrimitiveType.BOOLEAN)
static final ScalarType TINYINT = new ScalarType(PrimitiveType.TINYINT)
static final ScalarType SMALLINT = new ScalarType(PrimitiveType.SMALLINT)
static final ScalarType INT = new ScalarType(PrimitiveType.INT)
static final ScalarType BIGINT = new ScalarType(PrimitiveType.BIGINT)
static final ScalarType FLOAT = new ScalarType(PrimitiveType.FLOAT)
static final ScalarType DOUBLE = new ScalarType(PrimitiveType.DOUBLE)
static final ScalarType STRING = new ScalarType(PrimitiveType.STRING)
static final ScalarType BINARY = new ScalarType(PrimitiveType.BINARY)
static final ScalarType TIMESTAMP = new ScalarType(PrimitiveType.TIMESTAMP)
static final ScalarType DATE = new ScalarType(PrimitiveType.DATE)
static final ScalarType DATETIME = new ScalarType(PrimitiveType.DATETIME)
static final ScalarType DEFAULT_DECIMAL
static final ScalarType DECIMAL
static final ScalarType DEFAULT_VARCHAR = ScalarType.createVarcharType(-1)
static final ScalarType VARCHAR = ScalarType.createVarcharType(-1)
static final ScalarType CHAR = (ScalarType) ScalarType.createCharType(-1)
Protected Member Functions
ScalarType (PrimitiveType type)
Static Protected Member Functions
static Pair< Type, Integer > fromThrift (TColumnType col, int nodeIdx)
Static Protected Attributes
static PrimitiveType[][] compatibilityMatrix
Static Package Functions
[static initializer]
[static initializer]
Private Attributes
final PrimitiveType type_
int len_
int precision_
int scale_
Detailed Description
Describes a scalar type. For most types this class just wraps a PrimitiveType enum, but for types like CHAR and DECIMAL, this class contain additional information.
Scalar types have a few ways they can be compared to other scalar types. They can be:
completely identical,
implicitly castable (convertible without loss of precision)
subtype. For example, in the case of decimal, a type can be decimal(*, *) indicating that any decimal type is a subtype of the decimal type.
Definition at line 34 of file ScalarType.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.ScalarType.ScalarType (PrimitiveType type) inline protected
Definition at line 65 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.catalog.ScalarType.createCharType(), com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.ScalarType.createDecimalTypeInternal(), com.cloudera.impala.catalog.ScalarType.createVarcharType(), com.cloudera.impala.catalog.ScalarType.equals(), and com.cloudera.impala.catalog.ScalarType.matchesType().
Member Function Documentation
com.cloudera.impala.catalog.Type.[static initializer] () inline static package inherited
com.cloudera.impala.catalog.Type.[static initializer] () inline static package inherited
static ScalarType com.cloudera.impala.catalog.ScalarType.createCharType (int len) inline static
Definition at line 93 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, and com.cloudera.impala.catalog.ScalarType.ScalarType().
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts().
static ScalarType com.cloudera.impala.catalog.ScalarType.createDecimalType () inline static
Definition at line 99 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.DEFAULT_DECIMAL.
Referenced by com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalArithmetic(), com.cloudera.impala.analysis.TypesUtilTest.TestDecimalAssignementType(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalFunctions(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution().
static ScalarType com.cloudera.impala.catalog.ScalarType.createDecimalType (int precision) inline static
Definition at line 101 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.createDecimalType(), and com.cloudera.impala.catalog.ScalarType.DEFAULT_SCALE.
static ScalarType com.cloudera.impala.catalog.ScalarType.createDecimalType (int precision, int scale) inline static
Definition at line 105 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.DECIMAL, and com.cloudera.impala.catalog.ScalarType.ScalarType().
static ScalarType com.cloudera.impala.catalog.ScalarType.createDecimalTypeInternal (int precision, int scale) inline static
Definition at line 117 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, and com.cloudera.impala.catalog.ScalarType.ScalarType().
Referenced by com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), and com.cloudera.impala.catalog.ScalarType.getNextResolutionType().
static ScalarType com.cloudera.impala.catalog.ScalarType.createType (PrimitiveType type) inline static
Definition at line 69 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BINARY, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.ScalarType.createVarcharType(), com.cloudera.impala.catalog.Type.DATE, com.cloudera.impala.catalog.Type.DATETIME, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.INVALID, impala.INVALID_TYPE, com.cloudera.impala.catalog.Type.NULL, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.Type.TIMESTAMP, com.cloudera.impala.catalog.Type.TINYINT, and com.cloudera.impala.catalog.Type.VARCHAR.
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), and com.cloudera.impala.catalog.ScalarType.toColumnType().
static ScalarType com.cloudera.impala.catalog.ScalarType.createVarcharType (int len) inline static
Definition at line 124 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.ScalarType(), and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
Referenced by com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts().
static ScalarType com.cloudera.impala.catalog.ScalarType.createVarcharType () inline static
Definition at line 131 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.DEFAULT_VARCHAR.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), and com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType().
int com.cloudera.impala.catalog.ScalarType.decimalPrecision () inline
Definition at line 204 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.ScalarType.precision_, and com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.analysis.TypesUtil.getDecimalSlotSize(), and com.cloudera.impala.analysis.NumericLiteral.uncheckedCastTo().
int com.cloudera.impala.catalog.ScalarType.decimalScale () inline
Definition at line 209 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.ScalarType.scale_, and com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.resolveDecimalReturnType(), and com.cloudera.impala.analysis.NumericLiteral.uncheckedCastTo().
boolean com.cloudera.impala.catalog.ScalarType.equals (Object o) inline
Definition at line 314 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.ScalarType.len_, com.cloudera.impala.catalog.ScalarType.precision_, com.cloudera.impala.catalog.ScalarType.ScalarType(), com.cloudera.impala.catalog.ScalarType.scale_, com.cloudera.impala.catalog.ScalarType.type_, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), and com.cloudera.impala.catalog.ScalarType.matchesType().
static Type com.cloudera.impala.catalog.Type.fromThrift (TColumnType thrift) inline static inherited
Definition at line 293 of file Type.java.
Referenced by com.cloudera.impala.catalog.Column.fromThrift(), com.cloudera.impala.catalog.Type.fromThrift(), and com.cloudera.impala.catalog.Function.fromThrift().
static Pair<Type, Integer> com.cloudera.impala.catalog.Type.fromThrift (TColumnType col, int nodeIdx) inline static protected inherited
Constructs a ColumnType rooted at the TTypeNode at nodeIdx in TColumnType. Returned pair: The resulting ColumnType and the next nodeIdx that is not a child type of the result.
Definition at line 305 of file Type.java.
References com.cloudera.impala.catalog.Type.fromThrift(), and impala.name.
static Type com.cloudera.impala.catalog.Type.getAssignmentCompatibleType (Type t1, Type t2) inline static inherited
Return type t such that values from both t1 and t2 can be assigned to t without loss of precision. Returns INVALID_TYPE if there is no such type or if any of t1 and t2 is INVALID_TYPE. TODO: Support non-scalar types.
Definition at line 273 of file Type.java.
References com.cloudera.impala.catalog.Type.INVALID, and com.cloudera.impala.catalog.Type.isScalarType().
static ScalarType com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType (ScalarType t1, ScalarType t2) inline static
Return type t such that values from both t1 and t2 can be assigned to t without loss of precision. Returns INVALID_TYPE if there is no such type or if any of t1 and t2 is INVALID_TYPE.
Definition at line 387 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.Type.compatibilityMatrix, com.cloudera.impala.catalog.ScalarType.createCharType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.createVarcharType(), com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.Type.INVALID, com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isFloatingPointType(), com.cloudera.impala.catalog.Type.isInvalid(), com.cloudera.impala.catalog.Type.isNull(), com.cloudera.impala.catalog.ScalarType.isSupertypeOf(), com.cloudera.impala.catalog.Type.isValid(), com.cloudera.impala.catalog.ScalarType.len_, com.cloudera.impala.catalog.PrimitiveType.STRING, com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.ScalarType.type_, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
Referenced by com.cloudera.impala.catalog.ScalarType.isImplicitlyCastable().
Integer com.cloudera.impala.catalog.Type.getColumnSize () inline inherited
JDBC data type description Returns the column size for this type. For numeric data this is the maximum precision. For character data this is the length in characters. For datetime types this is the length in characters of the String representation (assuming the maximum allowed precision of the fractional seconds component). For binary data this is the length in bytes. Null is returned for for data types where the column size is not applicable.
Definition at line 385 of file Type.java.
References com.cloudera.impala.catalog.Type.CHAR, com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.isNumericType(), com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.Type.TIMESTAMP, and com.cloudera.impala.catalog.Type.VARCHAR.
Integer com.cloudera.impala.catalog.Type.getDecimalDigits () inline inherited
JDBC data type description Returns the number of fractional digits for this type, or null if not applicable. For timestamp/time types, returns the number of digits in the fractional seconds component.
Definition at line 436 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.TIMESTAMP, and com.cloudera.impala.catalog.Type.TINYINT.
static ArrayList<ScalarType> com.cloudera.impala.catalog.Type.getIntegerTypes () inline static inherited
Definition at line 103 of file Type.java.
References com.cloudera.impala.catalog.Type.integerTypes.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins().
int com.cloudera.impala.catalog.Type.getJavaSqlType () inline inherited
JDBC data type description Returns the java SQL type enum
Definition at line 493 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BINARY, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.Type.CHAR, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), impala.name, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.Type.TIMESTAMP, com.cloudera.impala.catalog.Type.TINYINT, com.cloudera.impala.catalog.Type.toSql(), and com.cloudera.impala.catalog.Type.VARCHAR.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults().
int com.cloudera.impala.catalog.ScalarType.getLength () inline
Definition at line 217 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.len_.
Type com.cloudera.impala.catalog.ScalarType.getMaxResolutionType () inline
Definition at line 326 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.ScalarType.createDecimalTypeInternal(), com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.INVALID, com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isFloatingPointType(), com.cloudera.impala.catalog.Type.isIntegerType(), com.cloudera.impala.catalog.Type.isNull(), com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, com.cloudera.impala.catalog.Type.NULL, com.cloudera.impala.catalog.ScalarType.scale_, com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP, and com.cloudera.impala.catalog.ScalarType.type_.
ScalarType com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal () inline
Returns the smallest decimal type that can safely store this type. Returns INVALID if this type cannot be stored as a decimal.
Definition at line 355 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.ScalarType.createDecimalTypeInternal(), com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.INVALID, com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, com.cloudera.impala.catalog.Type.NULL, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.TINYINT, and com.cloudera.impala.catalog.ScalarType.type_.
ScalarType com.cloudera.impala.catalog.ScalarType.getNextResolutionType () inline
Definition at line 341 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.BIGINT, com.cloudera.impala.catalog.ScalarType.createDecimalTypeInternal(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.PrimitiveType.DOUBLE, com.cloudera.impala.catalog.Type.isNull(), com.cloudera.impala.catalog.Type.isNumericType(), com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, com.cloudera.impala.catalog.ScalarType.scale_, and com.cloudera.impala.catalog.ScalarType.type_.
static ArrayList<ScalarType> com.cloudera.impala.catalog.Type.getNumericTypes () inline static inherited
Definition at line 106 of file Type.java.
References com.cloudera.impala.catalog.Type.numericTypes.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins().
Integer com.cloudera.impala.catalog.Type.getNumPrecRadix () inline inherited
JDBC data type description For numeric data types, either 10 or 2. If it is 10, the values in COLUMN_SIZE and DECIMAL_DIGITS give the number of decimal digits allowed for the column. For example, a DECIMAL(12,5) column would return a NUM_PREC_RADIX of 10, a COLUMN_SIZE of 12, and a DECIMAL_DIGITS of 5; a FLOAT column could return a NUM_PREC_RADIX of 10, a COLUMN_SIZE of 15, and a DECIMAL_DIGITS of NULL. If it is 2, the values in COLUMN_SIZE and DECIMAL_DIGITS give the number of bits allowed in the column. For example, a FLOAT column could return a RADIX of 2, a COLUMN_SIZE of 53, and a DECIMAL_DIGITS of NULL. NULL is returned for data types where NUM_PREC_RADIX is not applicable.
Definition at line 471 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.SMALLINT, and com.cloudera.impala.catalog.Type.TINYINT.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults().
Integer com.cloudera.impala.catalog.Type.getPrecision () inline inherited
JDBC data type description For numeric types, returns the maximum precision for this type. For non-numeric types, returns null.
Definition at line 407 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.SMALLINT, and com.cloudera.impala.catalog.Type.TINYINT.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), and com.cloudera.impala.catalog.Type.getColumnSize().
PrimitiveType com.cloudera.impala.catalog.ScalarType.getPrimitiveType () inline
Definition at line 215 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), and com.cloudera.impala.catalog.Type.getPrecision().
int com.cloudera.impala.catalog.ScalarType.getSlotSize () inline
Definition at line 277 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.CHAR, com.cloudera.impala.catalog.ScalarType.CHAR_INLINE_LENGTH, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.ScalarType.len_, and com.cloudera.impala.catalog.ScalarType.type_.
static ArrayList<ScalarType> com.cloudera.impala.catalog.Type.getSupportedTypes () inline static inherited
Definition at line 109 of file Type.java.
References com.cloudera.impala.catalog.Type.supportedTypes.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.InPredicate.initBuiltins(), com.cloudera.impala.analysis.IsNullPredicate.initBuiltins(), com.cloudera.impala.analysis.BinaryPredicate.initBuiltins(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.analysis.CaseExpr.initBuiltins(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCasts(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts().
TPrimitiveType com.cloudera.impala.catalog.Type.getTPrimitiveType (TColumnType ttype) inline inherited
Utility function to get the primitive type of a thrift type that is known to be scalar.
Definition at line 369 of file Type.java.
boolean com.cloudera.impala.catalog.Type.isArrayType () inline inherited
Definition at line 173 of file Type.java.
Referenced by com.cloudera.impala.analysis.Path.getTypeAsStruct(), and com.cloudera.impala.catalog.Type.isCollectionType().
boolean com.cloudera.impala.catalog.Type.isBoolean () inline inherited
Definition at line 124 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.BOOLEAN, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.analysis.Expr.checkReturnsBool().
boolean com.cloudera.impala.catalog.Type.isCollectionType () inline inherited
Definition at line 171 of file Type.java.
References com.cloudera.impala.catalog.Type.isArrayType(), and com.cloudera.impala.catalog.Type.isMapType().
Referenced by com.cloudera.impala.catalog.Type.getSlotSize(), and com.cloudera.impala.catalog.Type.isComplexType().
boolean com.cloudera.impala.catalog.Type.isComplexType () inline inherited
Definition at line 170 of file Type.java.
References com.cloudera.impala.catalog.Type.isCollectionType(), and com.cloudera.impala.catalog.Type.isStructType().
Referenced by com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.catalog.ScalarType.supportsTablePartitioning(), and com.cloudera.impala.analysis.AnalyzeDDLTest.TypeDefsAnalyzeOk().
boolean com.cloudera.impala.catalog.Type.isDateType () inline inherited
Definition at line 165 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.DATE, com.cloudera.impala.catalog.PrimitiveType.DATETIME, com.cloudera.impala.catalog.Type.isScalarType(), and com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP.
boolean com.cloudera.impala.catalog.Type.isDecimal () inline inherited
Definition at line 126 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.DECIMAL, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.Expr.convertNumericLiteralsFromDecimal(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.planner.HashJoinNode.init(), com.cloudera.impala.catalog.Type.isDecimalOrNull(), com.cloudera.impala.catalog.ScalarType.isFullySpecifiedDecimal(), com.cloudera.impala.catalog.Type.isNumericType(), com.cloudera.impala.catalog.ScalarType.isSupertypeOf(), com.cloudera.impala.catalog.ScalarType.matchesType(), and com.cloudera.impala.analysis.NumericLiteral.NumericLiteral().
boolean com.cloudera.impala.catalog.Type.isDecimalOrNull () inline inherited
Definition at line 127 of file Type.java.
References com.cloudera.impala.catalog.Type.isDecimal(), and com.cloudera.impala.catalog.Type.isNull().
boolean com.cloudera.impala.catalog.ScalarType.isFixedLengthType () inline
Definition at line 247 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.DECIMAL, and com.cloudera.impala.catalog.ScalarType.type_.
boolean com.cloudera.impala.catalog.Type.isFixedPointType () inline inherited
Definition at line 143 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.BIGINT, com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.PrimitiveType.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.PrimitiveType.SMALLINT, and com.cloudera.impala.catalog.PrimitiveType.TINYINT.
Referenced by com.cloudera.impala.catalog.Type.isNumericType().
boolean com.cloudera.impala.catalog.Type.isFloatingPointType () inline inherited
Definition at line 149 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.DOUBLE, com.cloudera.impala.catalog.PrimitiveType.FLOAT, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), and com.cloudera.impala.catalog.Type.isNumericType().
boolean com.cloudera.impala.catalog.ScalarType.isFullySpecifiedDecimal () inline
Returns true if this type is a fully specified (not wild card) decimal.
Definition at line 238 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.ScalarType.isWildcardDecimal(), com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, and com.cloudera.impala.catalog.ScalarType.precision_.
static boolean com.cloudera.impala.catalog.Type.isImplicitlyCastable (Type t1, Type t2) inline static inherited
Returns true if casting t1 to t2 results in no loss of precision, false otherwise. TODO: Support casting of non-scalar types.
Definition at line 259 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.checkRangeOffsetBoundaryExpr(), and com.cloudera.impala.catalog.Function.isSuperTypeOf().
static boolean com.cloudera.impala.catalog.ScalarType.isImplicitlyCastable (ScalarType t1, ScalarType t2) inline static
Returns if it is compatible to implicitly cast from t1 to t2 (casting from t1 to t2 results in no loss of precision).
Definition at line 469 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType().
boolean com.cloudera.impala.catalog.Type.isIntegerType () inline inherited
Definition at line 153 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.BIGINT, com.cloudera.impala.catalog.PrimitiveType.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.PrimitiveType.SMALLINT, and com.cloudera.impala.catalog.PrimitiveType.TINYINT.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), and com.cloudera.impala.catalog.HBaseTable.supportsBinaryEncoding().
boolean com.cloudera.impala.catalog.Type.isInvalid () inline inherited
Definition at line 121 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.INVALID_TYPE, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), and com.cloudera.impala.catalog.Type.isValid().
boolean com.cloudera.impala.catalog.Type.isMapType () inline inherited
Definition at line 172 of file Type.java.
Referenced by com.cloudera.impala.catalog.Type.isCollectionType().
boolean com.cloudera.impala.catalog.Type.isNull () inline inherited
Definition at line 123 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType(), and com.cloudera.impala.catalog.PrimitiveType.NULL_TYPE.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.analysis.Expr.getResolvedWildCardType(), com.cloudera.impala.catalog.Type.isDecimalOrNull(), com.cloudera.impala.catalog.Function.isIndistinguishable(), com.cloudera.impala.analysis.Expr.treeToThrift(), com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest(), and com.cloudera.impala.analysis.SlotRef.uncheckedCastTo().
boolean com.cloudera.impala.catalog.Type.isNumericType () inline inherited
Definition at line 161 of file Type.java.
References com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isFixedPointType(), and com.cloudera.impala.catalog.Type.isFloatingPointType().
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.catalog.Type.getColumnSize(), and com.cloudera.impala.catalog.ScalarType.getNextResolutionType().
boolean com.cloudera.impala.catalog.Type.isScalarType () inline inherited
Definition at line 138 of file Type.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.catalog.Type.getAssignmentCompatibleType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.Type.isBoolean(), com.cloudera.impala.catalog.Type.isDateType(), com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isFixedPointType(), com.cloudera.impala.catalog.Type.isFloatingPointType(), com.cloudera.impala.catalog.Type.isImplicitlyCastable(), com.cloudera.impala.catalog.Type.isIntegerType(), com.cloudera.impala.catalog.Type.isInvalid(), com.cloudera.impala.catalog.Type.isNull(), com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.isStringType(), com.cloudera.impala.catalog.ColumnStats.isSupportedColType(), com.cloudera.impala.catalog.Type.isTimestamp(), com.cloudera.impala.catalog.ScalarType.matchesType(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts().
boolean com.cloudera.impala.catalog.Type.isScalarType (PrimitiveType t) inline inherited
Definition at line 139 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType().
boolean com.cloudera.impala.catalog.Type.isStringType () inline inherited
Definition at line 133 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.PrimitiveType.STRING, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.analysis.ComputeStatsStmt.getBaseColumnStatsQuerySelectList(), and com.cloudera.impala.planner.HashJoinNode.init().
boolean com.cloudera.impala.catalog.Type.isStructType () inline inherited
Definition at line 174 of file Type.java.
Referenced by com.cloudera.impala.analysis.Path.getTypeAsStruct(), and com.cloudera.impala.catalog.Type.isComplexType().
boolean com.cloudera.impala.catalog.ScalarType.isSupertypeOf (ScalarType o) inline
Returns true if this decimal type is a supertype of the other decimal type. e.g. (10,3) is a super type of (3,3) but (5,4) is not a supertype of (3,0). To be a super type of another decimal, the number of digits before and after the decimal point must be greater or equal.
Definition at line 375 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.ScalarType.isWildcardDecimal(), com.cloudera.impala.catalog.ScalarType.precision_, and com.cloudera.impala.catalog.ScalarType.scale_.
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), and com.cloudera.impala.analysis.NumericLiteral.NumericLiteral().
boolean com.cloudera.impala.catalog.ScalarType.isSupported () inline
Definition at line 257 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.BINARY, com.cloudera.impala.catalog.Type.DATE, com.cloudera.impala.catalog.Type.DATETIME, and com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.catalog.ScalarType.supportsTablePartitioning().
boolean com.cloudera.impala.catalog.Type.isTimestamp () inline inherited
Definition at line 125 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType(), and com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP.
boolean com.cloudera.impala.catalog.Type.isValid () inline inherited
Definition at line 122 of file Type.java.
References com.cloudera.impala.catalog.Type.isInvalid().
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze(), com.cloudera.impala.analysis.InsertStmt.checkTypeCompatibility(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.analysis.ComputeStatsStmt.getBaseColumnStatsQuerySelectList(), and com.cloudera.impala.analysis.Analyzer.getCompatibleType().
boolean com.cloudera.impala.catalog.ScalarType.isWildcardChar () inline
Definition at line 230 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.len_, and com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.catalog.ScalarType.matchesType(), and com.cloudera.impala.catalog.ScalarType.toString().
boolean com.cloudera.impala.catalog.ScalarType.isWildcardDecimal () inline
Definition at line 220 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.precision_, com.cloudera.impala.catalog.ScalarType.scale_, and com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.analysis.TypesUtil.getDecimalAssignmentCompatibleType(), com.cloudera.impala.analysis.TypesUtil.getDecimalSlotSize(), com.cloudera.impala.catalog.ScalarType.isFullySpecifiedDecimal(), com.cloudera.impala.catalog.ScalarType.isSupertypeOf(), com.cloudera.impala.catalog.ScalarType.matchesType(), and com.cloudera.impala.catalog.ScalarType.toString().
boolean com.cloudera.impala.catalog.ScalarType.isWildcardVarchar () inline
Definition at line 225 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.len_, and com.cloudera.impala.catalog.ScalarType.type_.
Referenced by com.cloudera.impala.catalog.ScalarType.matchesType(), and com.cloudera.impala.catalog.ScalarType.toString().
boolean com.cloudera.impala.catalog.ScalarType.matchesType (Type t) inline
Returns true if this object is of type t. Handles wildcard types. That is, if t is the wildcard type variant of 'this', returns true.
Definition at line 294 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.ScalarType.isWildcardChar(), com.cloudera.impala.catalog.ScalarType.isWildcardDecimal(), com.cloudera.impala.catalog.ScalarType.isWildcardVarchar(), com.cloudera.impala.catalog.ScalarType.ScalarType(), com.cloudera.impala.catalog.ScalarType.type_, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
int com.cloudera.impala.catalog.ScalarType.ordinal () inline
Definition at line 216 of file ScalarType.java.
static Type com.cloudera.impala.catalog.Type.parseColumnType (FieldSchema fs) inline static inherited
Gets the ColumnType from the given FieldSchema by using Impala's SqlParser. Returns null if the FieldSchema could not be parsed. The type can either be:
Supported by Impala, in which case the type is returned.
A type Impala understands but is not yet implemented (e.g. date), the type is returned but type.IsSupported() returns false.
A type Impala can't understand at all in which case null is returned.
Definition at line 229 of file Type.java.
References com.cloudera.impala.analysis.CreateTableStmt.getColumnDefs(), and gen_ir_descriptions.parser.
boolean com.cloudera.impala.catalog.ScalarType.supportsTablePartitioning () inline
Definition at line 269 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.isComplexType(), com.cloudera.impala.catalog.ScalarType.isSupported(), com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP, and com.cloudera.impala.catalog.ScalarType.type_.
static Type [] com.cloudera.impala.catalog.ScalarType.toColumnType (PrimitiveType[] types) inline static
Definition at line 196 of file ScalarType.java.
References com.cloudera.impala.catalog.ScalarType.createType().
String com.cloudera.impala.catalog.ScalarType.toSql () inline
Definition at line 151 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.BINARY, com.cloudera.impala.catalog.Type.CHAR, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.ScalarType.len_, com.cloudera.impala.catalog.ScalarType.precision_, com.cloudera.impala.catalog.ScalarType.scale_, com.cloudera.impala.catalog.ScalarType.type_, and com.cloudera.impala.catalog.Type.VARCHAR.
String com.cloudera.impala.catalog.ScalarType.toString () inline
Definition at line 136 of file ScalarType.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.ScalarType.isWildcardChar(), com.cloudera.impala.catalog.ScalarType.isWildcardDecimal(), com.cloudera.impala.catalog.ScalarType.isWildcardVarchar(), com.cloudera.impala.catalog.ScalarType.len_, com.cloudera.impala.catalog.ScalarType.precision_, com.cloudera.impala.catalog.ScalarType.scale_, com.cloudera.impala.catalog.ScalarType.type_, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
void com.cloudera.impala.catalog.ScalarType.toThrift (TColumnType container) inline
Definition at line 164 of file ScalarType.java.
References com.cloudera.impala.catalog.Type.CHAR, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.ScalarType.len_, com.cloudera.impala.catalog.ScalarType.precision_, com.cloudera.impala.catalog.ScalarType.scale_, com.cloudera.impala.catalog.ScalarType.type_, and com.cloudera.impala.catalog.Type.VARCHAR.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableUpdateStats(), com.cloudera.impala.service.Frontend.createCatalogOpRequest(), com.cloudera.impala.service.Frontend.createExecRequest(), com.cloudera.impala.service.Frontend.createExplainRequest(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.catalog.HdfsTable.getFiles(), com.cloudera.impala.catalog.AuthorizationPolicy.getRolePrivileges(), com.cloudera.impala.catalog.DataSourceTable.getTableStats(), com.cloudera.impala.catalog.HBaseTable.getTableStats(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), and com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas().
TColumnType com.cloudera.impala.catalog.Type.toThrift () inline inherited
Definition at line 201 of file Type.java.
Referenced by com.cloudera.impala.catalog.HBaseColumn.toThrift(), com.cloudera.impala.analysis.ColumnDef.toThrift(), com.cloudera.impala.catalog.Column.toThrift(), and com.cloudera.impala.catalog.Type.toThrift().
static List<TColumnType> com.cloudera.impala.catalog.Type.toThrift (Type[] types) inline static inherited
Definition at line 281 of file Type.java.
References com.cloudera.impala.catalog.Type.toThrift().
static List<TColumnType> com.cloudera.impala.catalog.Type.toThrift (ArrayList< Type > types) inline static inherited
Definition at line 285 of file Type.java.
Member Data Documentation
final ScalarType com.cloudera.impala.catalog.Type.BIGINT = new ScalarType(PrimitiveType.BIGINT) static inherited
Definition at line 50 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.analysis.CollectionStructType.createArrayStructType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.DataSourceTable.getTableStats(), com.cloudera.impala.catalog.HBaseTable.getTableStats(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.HdfsPartitionTest.HdfsPartitionTest(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.QueryStmt.setLimit(), com.cloudera.impala.analysis.AnalyticExpr.standardize(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestAggregateSubqueries(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.catalog.HdfsPartitionTest.testCompare(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution().
final ScalarType com.cloudera.impala.catalog.Type.BINARY = new ScalarType(PrimitiveType.BINARY) static inherited
Definition at line 54 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.isSupported(), and com.cloudera.impala.catalog.ScalarType.toSql().
final ScalarType com.cloudera.impala.catalog.Type.BOOLEAN = new ScalarType(PrimitiveType.BOOLEAN) static inherited
Definition at line 46 of file Type.java.
Referenced by com.cloudera.impala.analysis.Predicate< com.cloudera.impala.analysis.Expr >.analyze(), com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.BoolLiteral.BoolLiteral(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.AuthorizationPolicy.getRolePrivileges(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.analysis.InPredicate.initBuiltins(), com.cloudera.impala.analysis.LikePredicate.initBuiltins(), com.cloudera.impala.analysis.CompoundPredicate.initBuiltins(), com.cloudera.impala.analysis.IsNullPredicate.initBuiltins(), com.cloudera.impala.analysis.BinaryPredicate.initBuiltins(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.Expr.treeToThrift(), and com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest().
final ScalarType com.cloudera.impala.catalog.Type.CHAR = (ScalarType) ScalarType.createCharType(-1) static inherited
Definition at line 65 of file Type.java.
Referenced by com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getSlotSize(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.catalog.ScalarType.toSql(), and com.cloudera.impala.catalog.ScalarType.toThrift().
final int com.cloudera.impala.catalog.ScalarType.CHAR_INLINE_LENGTH = 128 static
Definition at line 59 of file ScalarType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.getSlotSize().
PrimitiveType [][] com.cloudera.impala.catalog.Type.compatibilityMatrix static protected inherited
Matrix that records "smallest" assignment-compatible type of two types (INVALID_TYPE if no such type exists, ie, if the input types are fundamentally incompatible). A value of any of the two types could be assigned to a slot of the assignment-compatible type without loss of precision.
We chose not to follow MySQL's type casting behavior as described here: http://dev.mysql.com/doc/refman/5.0/en/type-conversion.html for the following reasons: conservative casting in arithmetic exprs: TINYINT + TINYINT -> BIGINT comparison of many types as double: INT < FLOAT -> comparison as DOUBLE special cases when dealing with dates and timestamps
Definition at line 534 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType().
final ScalarType com.cloudera.impala.catalog.Type.DATE = new ScalarType(PrimitiveType.DATE) static inherited
Definition at line 56 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.isSupported(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.DATETIME = new ScalarType(PrimitiveType.DATETIME) static inherited
Definition at line 57 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.isSupported(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.DECIMAL static inherited
Initial value:
=
      (ScalarType) ScalarType.createDecimalTypeInternal(-1, -1)
Definition at line 61 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.ScalarType.getSlotSize(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins(), com.cloudera.impala.analysis.TypesUtilTest.TestDecimalAssignementType(), com.cloudera.impala.catalog.ScalarType.toSql(), and com.cloudera.impala.catalog.ScalarType.toThrift().
final ScalarType com.cloudera.impala.catalog.Type.DEFAULT_DECIMAL static inherited
Initial value:
= (ScalarType)
      ScalarType.createDecimalType(ScalarType.DEFAULT_PRECISION,
          ScalarType.DEFAULT_SCALE)
Definition at line 58 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.analysis.TypesUtilTest.TestDecimalAssignementType(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts().
final int com.cloudera.impala.catalog.ScalarType.DEFAULT_PRECISION = 9 static
Definition at line 50 of file ScalarType.java.
final int com.cloudera.impala.catalog.ScalarType.DEFAULT_SCALE = 0 static
Definition at line 51 of file ScalarType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createDecimalType().
final ScalarType com.cloudera.impala.catalog.Type.DEFAULT_VARCHAR = ScalarType.createVarcharType(-1) static inherited
Definition at line 63 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createVarcharType().
final ScalarType com.cloudera.impala.catalog.Type.DOUBLE = new ScalarType(PrimitiveType.DOUBLE) static inherited
Definition at line 52 of file Type.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.Expr.convertNumericLiteralsToFloat(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.catalog.CatalogObjectToFromThriftTest.TestHBaseTables(), com.cloudera.impala.catalog.CatalogObjectToFromThriftTest.TestHBaseTableWithBinaryEncodedCols(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs().
final ScalarType com.cloudera.impala.catalog.Type.FLOAT = new ScalarType(PrimitiveType.FLOAT) static inherited
Definition at line 51 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.INT = new ScalarType(PrimitiveType.INT) static inherited
Definition at line 49 of file Type.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.addTestFunction(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.ExtractFromExpr.ExtractFromExpr(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprDepthLimit(), com.cloudera.impala.analysis.AuthorizationTest.TestFunction(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.catalog.CatalogTest.TestUdf(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs().
final ScalarType com.cloudera.impala.catalog.Type.INVALID = new ScalarType(PrimitiveType.INVALID_TYPE) static inherited
Definition at line 44 of file Type.java.
Referenced by com.cloudera.impala.analysis.DropFunctionStmt.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.catalog.ScalarFunction.createBuiltinSearchDesc(), com.cloudera.impala.analysis.AnalyzerTest.createFunction(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.service.CatalogOpExecutor.dropFunction(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.catalog.Type.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.analysis.Expr.getBuiltinFunction(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.Function.getVarArgsType(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), and com.cloudera.impala.catalog.CatalogTest.TestUdf().
int com.cloudera.impala.catalog.ScalarType.len_ private
Definition at line 38 of file ScalarType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getLength(), com.cloudera.impala.catalog.ScalarType.getSlotSize(), com.cloudera.impala.catalog.ScalarType.isWildcardChar(), com.cloudera.impala.catalog.ScalarType.isWildcardVarchar(), com.cloudera.impala.catalog.ScalarType.toSql(), com.cloudera.impala.catalog.ScalarType.toString(), and com.cloudera.impala.catalog.ScalarType.toThrift().
final int com.cloudera.impala.catalog.ScalarType.MAX_CHAR_LENGTH = 255 static
Definition at line 55 of file ScalarType.java.
Referenced by com.cloudera.impala.analysis.TypeDef.analyzeScalarType().
final int com.cloudera.impala.catalog.ScalarType.MAX_PRECISION = 38 static
Definition at line 62 of file ScalarType.java.
Referenced by com.cloudera.impala.analysis.TypeDef.analyzeScalarType(), com.cloudera.impala.analysis.TypesUtil.computeDecimalType(), com.cloudera.impala.catalog.ScalarType.createDecimalTypeInternal(), com.cloudera.impala.analysis.TypesUtil.getDecimalArithmeticResultType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.catalog.ScalarType.isFullySpecifiedDecimal(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCasts().
final int com.cloudera.impala.catalog.ScalarType.MAX_SCALE = MAX_PRECISION static
Definition at line 63 of file ScalarType.java.
Referenced by com.cloudera.impala.analysis.TypesUtil.computeDecimalType(), and com.cloudera.impala.analysis.FunctionCallExpr.resolveDecimalReturnType().
final int com.cloudera.impala.catalog.ScalarType.MAX_VARCHAR_LENGTH = 65355 static
Definition at line 54 of file ScalarType.java.
Referenced by com.cloudera.impala.analysis.TypeDef.analyzeScalarType().
final ScalarType com.cloudera.impala.catalog.Type.NULL = new ScalarType(PrimitiveType.NULL_TYPE) static inherited
Definition at line 45 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.analysis.NullLiteral.NullLiteral(), com.cloudera.impala.analysis.NullLiteral.resetAnalysisState(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts().
int com.cloudera.impala.catalog.ScalarType.precision_ private
Definition at line 45 of file ScalarType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.decimalPrecision(), com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.ScalarType.isFullySpecifiedDecimal(), com.cloudera.impala.catalog.ScalarType.isSupertypeOf(), com.cloudera.impala.catalog.ScalarType.isWildcardDecimal(), com.cloudera.impala.catalog.ScalarType.toSql(), com.cloudera.impala.catalog.ScalarType.toString(), and com.cloudera.impala.catalog.ScalarType.toThrift().
int com.cloudera.impala.catalog.ScalarType.scale_ private
Definition at line 46 of file ScalarType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.decimalScale(), com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.catalog.ScalarType.isSupertypeOf(), com.cloudera.impala.catalog.ScalarType.isWildcardDecimal(), com.cloudera.impala.catalog.ScalarType.toSql(), com.cloudera.impala.catalog.ScalarType.toString(), and com.cloudera.impala.catalog.ScalarType.toThrift().
final ScalarType com.cloudera.impala.catalog.Type.SMALLINT = new ScalarType(PrimitiveType.SMALLINT) static inherited
Definition at line 48 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues().
final ScalarType com.cloudera.impala.catalog.Type.STRING = new ScalarType(PrimitiveType.STRING) static inherited
Definition at line 53 of file Type.java.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableUpdateStats(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.Expr.castChildCharsToStrings(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertLogicalParquetType(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.service.Frontend.createCatalogOpRequest(), com.cloudera.impala.service.Frontend.createExecRequest(), com.cloudera.impala.service.Frontend.createExplainRequest(), com.cloudera.impala.planner.SingleNodePlanner.createHBaseValueRange(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.catalog.HdfsTable.getFiles(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.AuthorizationPolicy.getRolePrivileges(), com.cloudera.impala.catalog.HBaseTable.getTableStats(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.HdfsPartitionTest.HdfsPartitionTest(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.LikePredicate.initBuiltins(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.catalog.Function.promoteCharsToStrings(), com.cloudera.impala.planner.HBaseScanNode.setStartStopKey(), com.cloudera.impala.analysis.StringLiteral.StringLiteral(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs().
final ScalarType com.cloudera.impala.catalog.Type.TIMESTAMP = new ScalarType(PrimitiveType.TIMESTAMP) static inherited
Definition at line 55 of file Type.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.TINYINT = new ScalarType(PrimitiveType.TINYINT) static inherited
Definition at line 47 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution(), and com.cloudera.impala.catalog.CatalogTest.TestUdf().
final PrimitiveType com.cloudera.impala.catalog.ScalarType.type_ private
Definition at line 35 of file ScalarType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.decimalPrecision(), com.cloudera.impala.catalog.ScalarType.decimalScale(), com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.ScalarType.getSlotSize(), com.cloudera.impala.catalog.ScalarType.isFixedLengthType(), com.cloudera.impala.catalog.ScalarType.isSupported(), com.cloudera.impala.catalog.ScalarType.isWildcardChar(), com.cloudera.impala.catalog.ScalarType.isWildcardDecimal(), com.cloudera.impala.catalog.ScalarType.isWildcardVarchar(), com.cloudera.impala.catalog.ScalarType.matchesType(), com.cloudera.impala.analysis.FunctionCallExpr.resolveDecimalReturnType(), com.cloudera.impala.catalog.ScalarType.ScalarType(), com.cloudera.impala.catalog.ScalarType.supportsTablePartitioning(), com.cloudera.impala.catalog.ScalarType.toSql(), com.cloudera.impala.catalog.ScalarType.toString(), and com.cloudera.impala.catalog.ScalarType.toThrift().
final ScalarType com.cloudera.impala.catalog.Type.VARCHAR = ScalarType.createVarcharType(-1) static inherited
Definition at line 64 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.catalog.ScalarType.toSql(), and com.cloudera.impala.catalog.ScalarType.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/ScalarType.java