Impala: com.cloudera.impala.analysis.AlterTableAddPartitionStmt Class Reference
com.cloudera.impala.analysis.AlterTableAddPartitionStmt Class Reference
Public Member Functions
AlterTableAddPartitionStmt (TableName tableName, PartitionSpec partitionSpec, HdfsUri location, boolean ifNotExists, HdfsCachingOp cacheOp)
boolean getIfNotExists ()
HdfsUri getLocation ()
String toSql ()
TAlterTableParams toThrift ()
void analyze (Analyzer analyzer) throws AnalysisException
String getTbl ()
String getDb ()
void setIsExplain ()
boolean isExplain ()
Protected Member Functions
Table getTargetTable ()
Protected Attributes
final TableName tableName_
Table table_
boolean isExplain_ = false
Private Attributes
final HdfsUri location_
final boolean ifNotExists_
final PartitionSpec partitionSpec_
final HdfsCachingOp cacheOp_
Detailed Description
Represents an ALTER TABLE ADD PARTITION statement.
Definition at line 28 of file AlterTableAddPartitionStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AlterTableAddPartitionStmt.AlterTableAddPartitionStmt (TableName tableName, PartitionSpec partitionSpec, HdfsUri location, boolean ifNotExists, HdfsCachingOp cacheOp) inline
Definition at line 34 of file AlterTableAddPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableAddPartitionStmt.cacheOp_, com.cloudera.impala.analysis.AlterTableAddPartitionStmt.ifNotExists_, com.cloudera.impala.analysis.AlterTableAddPartitionStmt.location_, and com.cloudera.impala.analysis.AlterTableAddPartitionStmt.partitionSpec_.
Member Function Documentation
void com.cloudera.impala.analysis.AlterTableAddPartitionStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 78 of file AlterTableAddPartitionStmt.java.
References com.cloudera.impala.authorization.Privilege.ALL, com.cloudera.impala.authorization.Privilege.ALTER, com.cloudera.impala.analysis.AlterTableAddPartitionStmt.cacheOp_, com.cloudera.impala.analysis.AlterTableAddPartitionStmt.ifNotExists_, and com.cloudera.impala.analysis.AlterTableAddPartitionStmt.location_.
String com.cloudera.impala.analysis.AlterTableStmt.getDb () inline inherited
Can only be called after analysis, returns the parent database name of the target table for this ALTER TABLE statement.
Definition at line 47 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
boolean com.cloudera.impala.analysis.AlterTableAddPartitionStmt.getIfNotExists () inline
Definition at line 46 of file AlterTableAddPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableAddPartitionStmt.ifNotExists_.
HdfsUri com.cloudera.impala.analysis.AlterTableAddPartitionStmt.getLocation () inline
Definition at line 47 of file AlterTableAddPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableAddPartitionStmt.location_.
Table com.cloudera.impala.analysis.AlterTableStmt.getTargetTable () inline protected inherited
Can only be called after analysis, returns the Table object of the target of this ALTER TABLE statement.
Definition at line 55 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.table_.
Referenced by com.cloudera.impala.analysis.AlterTableSetStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetCachedStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetLocationStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getDb().
String com.cloudera.impala.analysis.AlterTableStmt.getTbl () inline inherited
Definition at line 41 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toSql(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 50 of file AlterTableAddPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableAddPartitionStmt.cacheOp_, com.cloudera.impala.analysis.AlterTableStmt.getTbl(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.ifNotExists_, and com.cloudera.impala.analysis.AlterTableAddPartitionStmt.location_.
TAlterTableParams com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toThrift () inline
Definition at line 65 of file AlterTableAddPartitionStmt.java.
References com.cloudera.impala.analysis.AlterTableAddPartitionStmt.cacheOp_, com.cloudera.impala.analysis.AlterTableAddPartitionStmt.ifNotExists_, and com.cloudera.impala.analysis.AlterTableAddPartitionStmt.location_.
Member Data Documentation
final HdfsCachingOp com.cloudera.impala.analysis.AlterTableAddPartitionStmt.cacheOp_ private
Definition at line 32 of file AlterTableAddPartitionStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableAddPartitionStmt.AlterTableAddPartitionStmt(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toThrift().
final boolean com.cloudera.impala.analysis.AlterTableAddPartitionStmt.ifNotExists_ private
Definition at line 30 of file AlterTableAddPartitionStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableAddPartitionStmt.AlterTableAddPartitionStmt(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.getIfNotExists(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toThrift().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final HdfsUri com.cloudera.impala.analysis.AlterTableAddPartitionStmt.location_ private
Definition at line 29 of file AlterTableAddPartitionStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableAddPartitionStmt.AlterTableAddPartitionStmt(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.getLocation(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toThrift().
final PartitionSpec com.cloudera.impala.analysis.AlterTableAddPartitionStmt.partitionSpec_ private
Definition at line 31 of file AlterTableAddPartitionStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableAddPartitionStmt.AlterTableAddPartitionStmt().
Table com.cloudera.impala.analysis.AlterTableStmt.table_ protected inherited
Definition at line 33 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
final TableName com.cloudera.impala.analysis.AlterTableStmt.tableName_ protected inherited
Definition at line 30 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), and com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AlterTableAddPartitionStmt.java