Impala: com.cloudera.impala.util.TestRequestPoolService Class Reference
com.cloudera.impala.util.TestRequestPoolService Class Reference
Public Member Functions
void cleanUp () throws Exception
void testPoolResolution () throws Exception
void testResolvePrincipalName () throws Exception
void testUserNoGroupsError () throws Exception
void testPoolAcls () throws Exception
void testPoolLimitConfigs () throws Exception
void testDefaultConfigs () throws Exception
void testUpdatingConfigs () throws Exception
void testModifiedConfigs () throws Exception
void testNullLlamaSite () throws Exception
Public Attributes
TemporaryFolder tempFolder = new TemporaryFolder()
Package Functions
void createPoolService (String allocationFile, String llamaConfFile) throws Exception
Private Member Functions
File getClasspathFile (String filename) throws URISyntaxException
void checkModifiedConfigResults () throws IOException
void checkPoolConfigResult (String pool, long expectedMaxRequests, long expectedMaxQueued, long expectedMaxMemUsage)
Private Attributes
RequestPoolService poolService_
File allocationConfFile_
File llamaConfFile_
Static Private Attributes
static final String ALLOCATION_FILE = "fair-scheduler-test.xml"
static final String ALLOCATION_FILE_MODIFIED = "fair-scheduler-test2.xml"
static final String ALLOCATION_FILE_EMPTY = "fair-scheduler-empty.xml"
static final String ALLOCATION_FILE_GROUP_RULE = "fair-scheduler-group-rule.xml"
static final String LLAMA_CONFIG_FILE = "llama-site-test.xml"
static final String LLAMA_CONFIG_FILE_MODIFIED = "llama-site-test2.xml"
static final String LLAMA_CONFIG_FILE_EMPTY = "llama-site-empty.xml"
static final long CHECK_INTERVAL_MS = 100L
Detailed Description
Unit tests for the user to pool resolution, authorization, and getting configuration parameters via RequestPoolService. Sets a configuration file and ensures the appropriate user to pool resolution, authentication, and pool configs are returned. This also tests that updating the files after startup causes them to be reloaded and the updated values are returned. TODO: Move tests to C++ to test the API that's actually used.
Definition at line 45 of file TestRequestPoolService.java.
Member Function Documentation
void com.cloudera.impala.util.TestRequestPoolService.checkModifiedConfigResults () throws IOException inline private
Definition at line 235 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.checkPoolConfigResult(), and com.cloudera.impala.common.ByteUnits.MEGABYTE.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testModifiedConfigs(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
void com.cloudera.impala.util.TestRequestPoolService.checkPoolConfigResult (String pool, long expectedMaxRequests, long expectedMaxQueued, long expectedMaxMemUsage) inline private
Helper method to verify the per-pool limits.
Definition at line 258 of file TestRequestPoolService.java.
References pool.
Referenced by com.cloudera.impala.util.TestRequestPoolService.checkModifiedConfigResults(), com.cloudera.impala.util.TestRequestPoolService.testDefaultConfigs(), com.cloudera.impala.util.TestRequestPoolService.testNullLlamaSite(), and com.cloudera.impala.util.TestRequestPoolService.testPoolLimitConfigs().
void com.cloudera.impala.util.TestRequestPoolService.cleanUp () throws Exception inline
Definition at line 108 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.poolService_.
void com.cloudera.impala.util.TestRequestPoolService.createPoolService (String allocationFile, String llamaConfFile) throws Exception inline package
Creates the poolService_ with the specified configuration.
Parameters
allocationFile The file on the classpath of the allocation conf.
llamaConfFile The file on the classpath of the Llama conf. May be null to create a RequestPoolService with no llama-conf.xml as it is not required.
Definition at line 82 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.allocationConfFile_, com.cloudera.impala.util.TestRequestPoolService.CHECK_INTERVAL_MS, com.cloudera.impala.util.TestRequestPoolService.getClasspathFile(), com.cloudera.impala.util.TestRequestPoolService.llamaConfFile_, and com.cloudera.impala.util.TestRequestPoolService.poolService_.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testDefaultConfigs(), com.cloudera.impala.util.TestRequestPoolService.testModifiedConfigs(), com.cloudera.impala.util.TestRequestPoolService.testNullLlamaSite(), com.cloudera.impala.util.TestRequestPoolService.testPoolAcls(), com.cloudera.impala.util.TestRequestPoolService.testPoolLimitConfigs(), com.cloudera.impala.util.TestRequestPoolService.testPoolResolution(), com.cloudera.impala.util.TestRequestPoolService.testResolvePrincipalName(), com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs(), and com.cloudera.impala.util.TestRequestPoolService.testUserNoGroupsError().
File com.cloudera.impala.util.TestRequestPoolService.getClasspathFile (String filename) throws URISyntaxException inline private
Returns a File for the file on the classpath.
Definition at line 115 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
void com.cloudera.impala.util.TestRequestPoolService.testDefaultConfigs () throws Exception inline
Definition at line 177 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_EMPTY, com.cloudera.impala.util.TestRequestPoolService.checkPoolConfigResult(), com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE_EMPTY.
void com.cloudera.impala.util.TestRequestPoolService.testModifiedConfigs () throws Exception inline
Definition at line 205 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_MODIFIED, com.cloudera.impala.util.TestRequestPoolService.checkModifiedConfigResults(), com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE_MODIFIED.
void com.cloudera.impala.util.TestRequestPoolService.testNullLlamaSite () throws Exception inline
Definition at line 213 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_MODIFIED, com.cloudera.impala.util.TestRequestPoolService.checkPoolConfigResult(), com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.common.ByteUnits.MEGABYTE.
void com.cloudera.impala.util.TestRequestPoolService.testPoolAcls () throws Exception inline
Definition at line 160 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE, com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE.
void com.cloudera.impala.util.TestRequestPoolService.testPoolLimitConfigs () throws Exception inline
Definition at line 169 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE, com.cloudera.impala.util.TestRequestPoolService.checkPoolConfigResult(), com.cloudera.impala.util.TestRequestPoolService.createPoolService(), com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE, and com.cloudera.impala.common.ByteUnits.MEGABYTE.
void com.cloudera.impala.util.TestRequestPoolService.testPoolResolution () throws Exception inline
Definition at line 120 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE, com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE.
void com.cloudera.impala.util.TestRequestPoolService.testResolvePrincipalName () throws Exception inline
Definition at line 127 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE, com.cloudera.impala.util.TestRequestPoolService.createPoolService(), com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE, and impala.OK.
void com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs () throws Exception inline
Definition at line 185 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE, com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_MODIFIED, com.cloudera.impala.util.TestRequestPoolService.allocationConfFile_, com.cloudera.impala.util.TestRequestPoolService.CHECK_INTERVAL_MS, com.cloudera.impala.util.TestRequestPoolService.checkModifiedConfigResults(), com.cloudera.impala.util.TestRequestPoolService.createPoolService(), com.cloudera.impala.util.TestRequestPoolService.getClasspathFile(), com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE, com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE_MODIFIED, and com.cloudera.impala.util.TestRequestPoolService.llamaConfFile_.
void com.cloudera.impala.util.TestRequestPoolService.testUserNoGroupsError () throws Exception inline
Definition at line 142 of file TestRequestPoolService.java.
References com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_GROUP_RULE, com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE.
Member Data Documentation
final String com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE = "fair-scheduler-test.xml" static private
Definition at line 47 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testPoolAcls(), com.cloudera.impala.util.TestRequestPoolService.testPoolLimitConfigs(), com.cloudera.impala.util.TestRequestPoolService.testPoolResolution(), com.cloudera.impala.util.TestRequestPoolService.testResolvePrincipalName(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
final String com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_EMPTY = "fair-scheduler-empty.xml" static private
Definition at line 51 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testDefaultConfigs().
final String com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_GROUP_RULE = "fair-scheduler-group-rule.xml" static private
Definition at line 52 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testUserNoGroupsError().
final String com.cloudera.impala.util.TestRequestPoolService.ALLOCATION_FILE_MODIFIED = "fair-scheduler-test2.xml" static private
Definition at line 50 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testModifiedConfigs(), com.cloudera.impala.util.TestRequestPoolService.testNullLlamaSite(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
File com.cloudera.impala.util.TestRequestPoolService.allocationConfFile_ private
Definition at line 72 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
final long com.cloudera.impala.util.TestRequestPoolService.CHECK_INTERVAL_MS = 100L static private
Definition at line 64 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
final String com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE = "llama-site-test.xml" static private
Definition at line 56 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testPoolAcls(), com.cloudera.impala.util.TestRequestPoolService.testPoolLimitConfigs(), com.cloudera.impala.util.TestRequestPoolService.testPoolResolution(), com.cloudera.impala.util.TestRequestPoolService.testResolvePrincipalName(), com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs(), and com.cloudera.impala.util.TestRequestPoolService.testUserNoGroupsError().
final String com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE_EMPTY = "llama-site-empty.xml" static private
Definition at line 60 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testDefaultConfigs().
final String com.cloudera.impala.util.TestRequestPoolService.LLAMA_CONFIG_FILE_MODIFIED = "llama-site-test2.xml" static private
Definition at line 59 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.testModifiedConfigs(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
File com.cloudera.impala.util.TestRequestPoolService.llamaConfFile_ private
Definition at line 73 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.createPoolService(), and com.cloudera.impala.util.TestRequestPoolService.testUpdatingConfigs().
RequestPoolService com.cloudera.impala.util.TestRequestPoolService.poolService_ private
Definition at line 71 of file TestRequestPoolService.java.
Referenced by com.cloudera.impala.util.TestRequestPoolService.cleanUp(), and com.cloudera.impala.util.TestRequestPoolService.createPoolService().
TemporaryFolder com.cloudera.impala.util.TestRequestPoolService.tempFolder = new TemporaryFolder()
Definition at line 69 of file TestRequestPoolService.java.
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/util/TestRequestPoolService.java