Impala: com.cloudera.impala.analysis.CreateDbStmt Class Reference
com.cloudera.impala.analysis.CreateDbStmt Class Reference
Public Member Functions
CreateDbStmt (String dbName)
CreateDbStmt (String dbName, String comment, HdfsUri location, boolean ifNotExists)
String getComment ()
String getDb ()
boolean getIfNotExists ()
HdfsUri getLocation ()
String toSql ()
TCreateDbParams toThrift ()
void analyze (Analyzer analyzer) throws AnalysisException
void setIsExplain ()
boolean isExplain ()
Protected Attributes
boolean isExplain_ = false
Private Attributes
final String dbName_
final HdfsUri location_
final String comment_
final boolean ifNotExists_
Detailed Description
Represents a CREATE DATABASE statement
Definition at line 28 of file CreateDbStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.CreateDbStmt.CreateDbStmt (String dbName) inline
Creates a database with the given name.
Definition at line 37 of file CreateDbStmt.java.
com.cloudera.impala.analysis.CreateDbStmt.CreateDbStmt (String dbName, String comment, HdfsUri location, boolean ifNotExists) inline
Creates a database with the given name, comment, and HDFS table storage location. New tables created in the database inherit the location property for their default storage location. Create database will throw an error if the database already exists unless the ifNotExists is true.
Definition at line 47 of file CreateDbStmt.java.
Member Function Documentation
void com.cloudera.impala.analysis.CreateDbStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 80 of file CreateDbStmt.java.
References com.cloudera.impala.authorization.Privilege.ALL, com.cloudera.impala.authorization.Privilege.CREATE, com.cloudera.impala.analysis.Analyzer.DB_ALREADY_EXISTS_ERROR_MSG, com.cloudera.impala.analysis.CreateDbStmt.dbName_, com.cloudera.impala.analysis.CreateDbStmt.getDb(), com.cloudera.impala.analysis.CreateDbStmt.ifNotExists_, and com.cloudera.impala.analysis.CreateDbStmt.location_.
String com.cloudera.impala.analysis.CreateDbStmt.getComment () inline
Definition at line 55 of file CreateDbStmt.java.
References com.cloudera.impala.analysis.CreateDbStmt.comment_.
Referenced by com.cloudera.impala.analysis.CreateDbStmt.toThrift().
String com.cloudera.impala.analysis.CreateDbStmt.getDb () inline
Definition at line 56 of file CreateDbStmt.java.
References com.cloudera.impala.analysis.CreateDbStmt.dbName_.
Referenced by com.cloudera.impala.analysis.CreateDbStmt.analyze(), and com.cloudera.impala.analysis.CreateDbStmt.toThrift().
boolean com.cloudera.impala.analysis.CreateDbStmt.getIfNotExists () inline
Definition at line 57 of file CreateDbStmt.java.
References com.cloudera.impala.analysis.CreateDbStmt.ifNotExists_.
Referenced by com.cloudera.impala.analysis.CreateDbStmt.toThrift().
HdfsUri com.cloudera.impala.analysis.CreateDbStmt.getLocation () inline
Definition at line 58 of file CreateDbStmt.java.
References com.cloudera.impala.analysis.CreateDbStmt.location_.
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.CreateDbStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 61 of file CreateDbStmt.java.
References com.cloudera.impala.analysis.CreateDbStmt.comment_, com.cloudera.impala.analysis.CreateDbStmt.dbName_, com.cloudera.impala.analysis.CreateDbStmt.ifNotExists_, and com.cloudera.impala.analysis.CreateDbStmt.location_.
TCreateDbParams com.cloudera.impala.analysis.CreateDbStmt.toThrift () inline
Definition at line 70 of file CreateDbStmt.java.
References com.cloudera.impala.analysis.CreateDbStmt.getComment(), com.cloudera.impala.analysis.CreateDbStmt.getDb(), com.cloudera.impala.analysis.CreateDbStmt.getIfNotExists(), and com.cloudera.impala.analysis.CreateDbStmt.location_.
Member Data Documentation
final String com.cloudera.impala.analysis.CreateDbStmt.comment_ private
Definition at line 31 of file CreateDbStmt.java.
Referenced by com.cloudera.impala.analysis.CreateDbStmt.getComment(), and com.cloudera.impala.analysis.CreateDbStmt.toSql().
final String com.cloudera.impala.analysis.CreateDbStmt.dbName_ private
Definition at line 29 of file CreateDbStmt.java.
Referenced by com.cloudera.impala.analysis.CreateDbStmt.analyze(), com.cloudera.impala.analysis.CreateDbStmt.getDb(), and com.cloudera.impala.analysis.CreateDbStmt.toSql().
final boolean com.cloudera.impala.analysis.CreateDbStmt.ifNotExists_ private
Definition at line 32 of file CreateDbStmt.java.
Referenced by com.cloudera.impala.analysis.CreateDbStmt.analyze(), com.cloudera.impala.analysis.CreateDbStmt.getIfNotExists(), and com.cloudera.impala.analysis.CreateDbStmt.toSql().
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final HdfsUri com.cloudera.impala.analysis.CreateDbStmt.location_ private
Definition at line 30 of file CreateDbStmt.java.
Referenced by com.cloudera.impala.analysis.CreateDbStmt.analyze(), com.cloudera.impala.analysis.CreateDbStmt.getLocation(), com.cloudera.impala.analysis.CreateDbStmt.toSql(), and com.cloudera.impala.analysis.CreateDbStmt.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/CreateDbStmt.java