Impala: com.cloudera.impala.analysis.SelectListItem Class Reference
com.cloudera.impala.analysis.SelectListItem Class Reference
Public Member Functions
SelectListItem (Expr expr, String alias)
Expr getExpr ()
boolean isStar ()
String getAlias ()
void setAlias (String alias)
List< String > getRawPath ()
String toString ()
String toSql ()
String toColumnLabel (int selectListPos, boolean useHiveColLabels)
SelectListItem clone ()
Static Public Member Functions
static SelectListItem createStarItem (List< String > rawPath)
Private Member Functions
SelectListItem (List< String > path)
Private Attributes
final Expr expr_
String alias_
final List< String > rawPath_
final boolean isStar_
Detailed Description
Definition at line 22 of file SelectListItem.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.SelectListItem.SelectListItem (Expr expr, String alias) inline
Definition at line 30 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.alias_, com.cloudera.impala.analysis.SelectListItem.expr_, com.cloudera.impala.analysis.SelectListItem.isStar_, and com.cloudera.impala.analysis.SelectListItem.rawPath_.
Referenced by com.cloudera.impala.analysis.SelectListItem.clone(), and com.cloudera.impala.analysis.SelectListItem.createStarItem().
com.cloudera.impala.analysis.SelectListItem.SelectListItem (List< String > path) inline private
Definition at line 44 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.expr_, com.cloudera.impala.analysis.SelectListItem.isStar_, path(), and com.cloudera.impala.analysis.SelectListItem.rawPath_.
Member Function Documentation
SelectListItem com.cloudera.impala.analysis.SelectListItem.clone () inline
Definition at line 121 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.alias_, com.cloudera.impala.analysis.Expr.clone(), com.cloudera.impala.analysis.SelectListItem.createStarItem(), com.cloudera.impala.analysis.SelectListItem.expr_, com.cloudera.impala.analysis.SelectListItem.isStar_, com.cloudera.impala.analysis.SelectListItem.rawPath_, and com.cloudera.impala.analysis.SelectListItem.SelectListItem().
static SelectListItem com.cloudera.impala.analysis.SelectListItem.createStarItem (List< String > rawPath) inline static
Definition at line 40 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.SelectListItem().
Referenced by com.cloudera.impala.analysis.SelectListItem.clone().
String com.cloudera.impala.analysis.SelectListItem.getAlias () inline
Definition at line 53 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.alias_.
Expr com.cloudera.impala.analysis.SelectListItem.getExpr () inline
Definition at line 51 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.expr_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), and com.cloudera.impala.analysis.StmtRewriter.createJoinConjunct().
List<String> com.cloudera.impala.analysis.SelectListItem.getRawPath () inline
Definition at line 55 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.rawPath_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze().
boolean com.cloudera.impala.analysis.SelectListItem.isStar () inline
Definition at line 52 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.isStar_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyze(), and com.cloudera.impala.analysis.StmtRewriter.replaceUnqualifiedStarItems().
void com.cloudera.impala.analysis.SelectListItem.setAlias (String alias) inline
Definition at line 54 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.alias_.
String com.cloudera.impala.analysis.SelectListItem.toColumnLabel (int selectListPos, boolean useHiveColLabels) inline
Returns a column label for this select list item. If an alias was given, then the column label is the lower case alias. If expr is a SlotRef then directly use its lower case column name. Otherwise, the label is the lower case toSql() of expr or a Hive auto-generated column name (depending on useHiveColLabels). Hive's auto-generated column labels have a "_c" prefix and a select-list pos suffix, e.g., "_c0", "_c1", "_c2", etc.
Using auto-generated columns that are consistent with Hive is important for view compatibility between Impala and Hive.
Definition at line 104 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.alias_, com.cloudera.impala.analysis.SelectListItem.expr_, com.cloudera.impala.analysis.SlotRef.getResolvedPath(), and com.cloudera.impala.analysis.SelectListItem.toSql().
String com.cloudera.impala.analysis.SelectListItem.toSql () inline
Definition at line 70 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.alias_, com.cloudera.impala.analysis.SelectListItem.expr_, com.cloudera.impala.analysis.SelectListItem.isStar_, and com.cloudera.impala.analysis.SelectListItem.rawPath_.
Referenced by com.cloudera.impala.analysis.SelectListItem.toColumnLabel().
String com.cloudera.impala.analysis.SelectListItem.toString () inline
Definition at line 58 of file SelectListItem.java.
References com.cloudera.impala.analysis.SelectListItem.alias_, com.cloudera.impala.analysis.SelectListItem.expr_, com.cloudera.impala.analysis.SelectListItem.isStar_, and com.cloudera.impala.analysis.SelectListItem.rawPath_.
Member Data Documentation
String com.cloudera.impala.analysis.SelectListItem.alias_ private
Definition at line 24 of file SelectListItem.java.
Referenced by com.cloudera.impala.analysis.SelectListItem.clone(), com.cloudera.impala.analysis.SelectListItem.getAlias(), com.cloudera.impala.analysis.SelectListItem.SelectListItem(), com.cloudera.impala.analysis.SelectListItem.setAlias(), com.cloudera.impala.analysis.SelectListItem.toColumnLabel(), com.cloudera.impala.analysis.SelectListItem.toSql(), and com.cloudera.impala.analysis.SelectListItem.toString().
final Expr com.cloudera.impala.analysis.SelectListItem.expr_ private
Definition at line 23 of file SelectListItem.java.
Referenced by com.cloudera.impala.analysis.SelectListItem.clone(), com.cloudera.impala.analysis.SelectListItem.getExpr(), com.cloudera.impala.analysis.SelectListItem.SelectListItem(), com.cloudera.impala.analysis.SelectListItem.toColumnLabel(), com.cloudera.impala.analysis.SelectListItem.toSql(), and com.cloudera.impala.analysis.SelectListItem.toString().
final boolean com.cloudera.impala.analysis.SelectListItem.isStar_ private
Definition at line 28 of file SelectListItem.java.
Referenced by com.cloudera.impala.analysis.SelectListItem.clone(), com.cloudera.impala.analysis.SelectListItem.isStar(), com.cloudera.impala.analysis.SelectListItem.SelectListItem(), com.cloudera.impala.analysis.SelectListItem.toSql(), and com.cloudera.impala.analysis.SelectListItem.toString().
final List<String> com.cloudera.impala.analysis.SelectListItem.rawPath_ private
Definition at line 27 of file SelectListItem.java.
Referenced by com.cloudera.impala.analysis.SelectListItem.clone(), com.cloudera.impala.analysis.SelectListItem.getRawPath(), com.cloudera.impala.analysis.SelectListItem.SelectListItem(), com.cloudera.impala.analysis.SelectListItem.toSql(), and com.cloudera.impala.analysis.SelectListItem.toString().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/SelectListItem.java