Impala: com.cloudera.impala.util.FsPermissionChecker Class Reference
com.cloudera.impala.util.FsPermissionChecker Class Reference
Classes
class Permissions
Public Member Functions
Permissions getPermissions (FileSystem fs, Path path) throws IOException
Static Public Member Functions
static FsPermissionChecker getInstance ()
Protected Attributes
final String user_
Static Package Functions
[static initializer]
Private Member Functions
FsPermissionChecker () throws IOException
Private Attributes
final Set< String > groups_ = new HashSet<String>()
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(FsPermissionChecker.class)
static final FsPermissionChecker instance_
static List< AclEntryType > ACL_TYPE_PRIORITY
Detailed Description
Singleton class that can check whether the current user has permission to access paths in a FileSystem.
Definition at line 50 of file FsPermissionChecker.java.
Constructor & Destructor Documentation
com.cloudera.impala.util.FsPermissionChecker.FsPermissionChecker () throws IOException inline private
Definition at line 65 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.user_.
Member Function Documentation
com.cloudera.impala.util.FsPermissionChecker.[static initializer] () inline static package
static FsPermissionChecker com.cloudera.impala.util.FsPermissionChecker.getInstance () inline static
Returns the FsPermissionChecker singleton.
Definition at line 290 of file FsPermissionChecker.java.
References com.cloudera.impala.util.FsPermissionChecker.instance_.
Permissions com.cloudera.impala.util.FsPermissionChecker.getPermissions (FileSystem fs, Path path) throws IOException inline
Returns a Permissions object that can answer all access permission queries for the given path.
Definition at line 273 of file FsPermissionChecker.java.
References path().
Referenced by com.cloudera.impala.analysis.HdfsUri.analyze(), and com.cloudera.impala.analysis.LoadDataStmt.analyzePaths().
Member Data Documentation
List<AclEntryType> com.cloudera.impala.util.FsPermissionChecker.ACL_TYPE_PRIORITY static private
Initial value:
=
      ImmutableList.of(AclEntryType.USER, AclEntryType.GROUP, AclEntryType.OTHER)
Definition at line 73 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkAcls(), and com.cloudera.impala.util.FsPermissionChecker.Permissions.Permissions().
final Set<String> com.cloudera.impala.util.FsPermissionChecker.groups_ = new HashSet<String>() private
Definition at line 54 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkPermissions().
final FsPermissionChecker com.cloudera.impala.util.FsPermissionChecker.instance_ static private
Definition at line 52 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.getInstance().
final Logger com.cloudera.impala.util.FsPermissionChecker.LOG = LoggerFactory.getLogger(FsPermissionChecker.class) static private
Definition at line 51 of file FsPermissionChecker.java.
final String com.cloudera.impala.util.FsPermissionChecker.user_ protected
Definition at line 53 of file FsPermissionChecker.java.
Referenced by com.cloudera.impala.util.FsPermissionChecker.Permissions.checkPermissions(), and com.cloudera.impala.util.FsPermissionChecker.FsPermissionChecker().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/util/FsPermissionChecker.java