Impala: impala::PathBuilder Class Reference
impala::PathBuilder Class Reference
Utility class to construct full paths relative to the impala_home path.
#include <path-builder.h>
Static Public Member Functions
static void GetFullPath (const std::string &path, std::string *full_path)
Sets full_path to <IMPALA_HOME>/path.
static void GetFullBuildPath (const std::string &path, std::string *full_path)
Sets full_path to <IMPALA_HOME>/<build><debug or="" release>="">/path.
Static Private Member Functions
static void LoadImpalaHome ()
Load impala_home_ if it is not already loaded.
Static Private Attributes
static const char * impala_home_
Cache of env['IMPALA_HOME'].
Detailed Description
Utility class to construct full paths relative to the impala_home path.
Definition at line 24 of file path-builder.h.
Member Function Documentation
void PathBuilder::GetFullBuildPath (const std::string & path, std::string * full_path) static
Sets full_path to <IMPALA_HOME>/<build><debug or="" release>="">/path.
Definition at line 38 of file path-builder.cc.
References impala_home_, LoadImpalaHome(), and path().
Referenced by impala::LibCache::InitInternal().
void PathBuilder::GetFullPath (const std::string & path, std::string * full_path) static
Sets full_path to <IMPALA_HOME>/path.
Definition at line 31 of file path-builder.cc.
References impala_home_, LoadImpalaHome(), and path().
Referenced by impala::LlvmCodeGen::LoadImpalaIR().
void PathBuilder::LoadImpalaHome () static private
Load impala_home_ if it is not already loaded.
Definition at line 26 of file path-builder.cc.
References impala_home_.
Referenced by GetFullBuildPath(), and GetFullPath().
Member Data Documentation
const char * PathBuilder::impala_home_ static private
Cache of env['IMPALA_HOME'].
Definition at line 34 of file path-builder.h.
Referenced by GetFullBuildPath(), GetFullPath(), and LoadImpalaHome().
The documentation for this class was generated from the following files:
be/src/util/path-builder.h
be/src/util/path-builder.cc