Impala: impala::TimerMetric Class Reference
impala::TimerMetric Class Reference
#include <timer-metric.h>
Public Member Functions
virtual void ToJson (rapidjson::Document *document, rapidjson::Value *val)
name, value, human_readable, description
virtual void ToLegacyJson (rapidjson::Document *document)
This method is kept for backwards-compatibility with CM5.0.
virtual std::string ToHumanReadable ()
const std::string & key () const
const std::string & description () const
Protected Member Functions
void AddStandardFields (rapidjson::Document *document, rapidjson::Value *val)
Protected Attributes
const std::string key_
Unique key identifying this metric.
const std::string description_
Detailed Description
Definition at line 8 of file timer-metric.h.
Member Function Documentation
void Metric::AddStandardFields (rapidjson::Document * document, rapidjson::Value * val) protected inherited
Convenience method to add standard fields (name, description, human readable string) to 'val'.
Definition at line 46 of file metrics.cc.
References impala::name.
Referenced by impala::SetMetric< std::string >::ToJson(), impala::StatsMetric< double >::ToJson(), and impala::SimpleMetric< T, metric_kind >::ToJson().
const std::string& impala::Metric::description () const inline inherited
Definition at line 72 of file metrics.h.
References impala::Metric::description_.
const std::string& impala::Metric::key () const inline inherited
Definition at line 71 of file metrics.h.
References impala::Metric::key_.
Referenced by impala::SimpleMetric< T, metric_kind >::Increment().
virtual std::string impala::TimerMetric::ToHumanReadable () inline virtual
Writes a human-readable representation of this metric to 'out'. This is the representation that is often displayed in webpages etc.
Implements impala::Metric.
Definition at line 13 of file timer-metric.h.
virtual void impala::TimerMetric::ToJson (rapidjson::Document * document, rapidjson::Value * val) inline virtual
name, value, human_readable, description
Builds a new Value into 'val', using (if required) the allocator from 'document'. Should set the following fields where appropriate:
Implements impala::Metric.
Definition at line 10 of file timer-metric.h.
virtual void impala::TimerMetric::ToLegacyJson (rapidjson::Document * document) inline virtual
This method is kept for backwards-compatibility with CM5.0.
Adds a new json value directly to 'document' of the form: "name" : "human-readable-string"
Implements impala::Metric.
Definition at line 11 of file timer-metric.h.
Member Data Documentation
const std::string impala::Metric::description_ protected inherited
Description of this metric. TODO: share one copy amongst metrics with the same description.
Definition at line 80 of file metrics.h.
Referenced by impala::Metric::description().
const std::string impala::Metric::key_ protected inherited
Unique key identifying this metric.
Definition at line 76 of file metrics.h.
Referenced by impala::Metric::key(), impala::SetMetric< std::string >::ToLegacyJson(), impala::StatsMetric< double >::ToLegacyJson(), and impala::SimpleMetric< T, metric_kind >::ToLegacyJson().
The documentation for this class was generated from the following file:
be/src/util/timer-metric.h