Impala: impala::OldHashTableTest Class Reference
impala::OldHashTableTest Class Reference
Classes
struct ProbeTestData
Public Member Functions
OldHashTableTest ()
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
TupleRow * CreateTupleRow (int32_t val)
void ResizeTable (OldHashTable *table, int64_t new_size)
void FullScan (OldHashTable *table, int min, int max, bool all_unique, TupleRow **results, TupleRow **expected)
void ValidateMatch (TupleRow *probe_row, TupleRow *build_row)
void ProbeTest (OldHashTable *table, ProbeTestData *data, int num_data, bool scan)
Protected Attributes
ObjectPool pool_
MemTracker tracker_
MemPool mem_pool_
vector< ExprContext * > build_expr_ctxs_
vector< ExprContext * > probe_expr_ctxs_
Detailed Description
Definition at line 38 of file old-hash-table-test.cc.
Constructor & Destructor Documentation
impala::OldHashTableTest::OldHashTableTest () inline
Definition at line 40 of file old-hash-table-test.cc.
Member Function Documentation
TupleRow* impala::OldHashTableTest::CreateTupleRow (int32_t val) inline protected
Definition at line 76 of file old-hash-table-test.cc.
References impala::MemPool::Allocate(), impala::Tuple::Create(), mem_pool_, and impala::TupleRow::SetTuple().
void impala::OldHashTableTest::FullScan (OldHashTable * table, int min, int max, bool all_unique, TupleRow ** results, TupleRow ** expected) inline protected
Definition at line 95 of file old-hash-table-test.cc.
References impala::OldHashTable::Begin(), build_expr_ctxs_, impala::OldHashTable::End(), impala::OldHashTable::Iterator::GetRow(), impala::TupleRow::GetTuple(), and impala::OldHashTable::Iterator::Next().
void impala::OldHashTableTest::ProbeTest (OldHashTable * table, ProbeTestData * data, int num_data, bool scan) inline protected
Definition at line 126 of file old-hash-table-test.cc.
References impala::OldHashTable::End(), impala::OldHashTableTest::ProbeTestData::expected_build_rows, impala::OldHashTable::Find(), impala::OldHashTable::Iterator::GetRow(), impala::TupleRow::GetTuple(), impala::OldHashTable::Iterator::Next(), impala::OldHashTableTest::ProbeTestData::probe_row, and ValidateMatch().
void impala::OldHashTableTest::ResizeTable (OldHashTable * table, int64_t new_size) inline protected
Definition at line 87 of file old-hash-table-test.cc.
References impala::OldHashTable::ResizeBuckets().
virtual void impala::OldHashTableTest::SetUp () inline protected virtual
Definition at line 49 of file old-hash-table-test.cc.
References impala::ObjectPool::Add(), build_expr_ctxs_, impala::Status::ok(), impala::Expr::Open(), pool_, impala::Expr::Prepare(), probe_expr_ctxs_, tracker_, and impala::TYPE_INT.
virtual void impala::OldHashTableTest::TearDown () inline protected virtual
Definition at line 71 of file old-hash-table-test.cc.
References build_expr_ctxs_, impala::Expr::Close(), and probe_expr_ctxs_.
void impala::OldHashTableTest::ValidateMatch (TupleRow * probe_row, TupleRow * build_row) inline protected
Definition at line 112 of file old-hash-table-test.cc.
References build_expr_ctxs_, and probe_expr_ctxs_.
Referenced by ProbeTest().
Member Data Documentation
vector<ExprContext*> impala::OldHashTableTest::build_expr_ctxs_ protected
Definition at line 46 of file old-hash-table-test.cc.
Referenced by FullScan(), SetUp(), TearDown(), and ValidateMatch().
MemPool impala::OldHashTableTest::mem_pool_ protected
Definition at line 45 of file old-hash-table-test.cc.
Referenced by CreateTupleRow().
ObjectPool impala::OldHashTableTest::pool_ protected
Definition at line 43 of file old-hash-table-test.cc.
Referenced by SetUp().
vector<ExprContext*> impala::OldHashTableTest::probe_expr_ctxs_ protected
Definition at line 47 of file old-hash-table-test.cc.
Referenced by SetUp(), TearDown(), and ValidateMatch().
MemTracker impala::OldHashTableTest::tracker_ protected
Definition at line 44 of file old-hash-table-test.cc.
Referenced by SetUp().
The documentation for this class was generated from the following file:
be/src/exec/old-hash-table-test.cc