Impala: impala::TempRulesFile Class Reference
impala::TempRulesFile Class Reference
#include <redactor-test-utils.h>
Public Member Functions
TempRulesFile (const std::string &contents)
~TempRulesFile ()
void Delete ()
void OverwriteContents (const std::string &contents)
const char * name () const
Returns the absolute path to the file.
Private Attributes
string name_
bool deleted_
Detailed Description
Utility class for creating a redaction config file that will be automatically deleted upon test completion.
Definition at line 29 of file redactor-test-utils.h.
Constructor & Destructor Documentation
impala::TempRulesFile::TempRulesFile (const std::string & contents) inline
Definition at line 31 of file redactor-test-utils.h.
References name_, and OverwriteContents().
impala::TempRulesFile::~TempRulesFile () inline
Definition at line 46 of file redactor-test-utils.h.
References Delete().
Member Function Documentation
void impala::TempRulesFile::Delete () inline
Definition at line 48 of file redactor-test-utils.h.
References deleted_, and name().
Referenced by impala::TEST(), and ~TempRulesFile().
const char* impala::TempRulesFile::name () const inline
Returns the absolute path to the file.
Definition at line 76 of file redactor-test-utils.h.
References name_.
Referenced by Delete(), OverwriteContents(), and impala::TEST().
void impala::TempRulesFile::OverwriteContents (const std::string & contents) inline
Definition at line 57 of file redactor-test-utils.h.
References name().
Referenced by TempRulesFile(), and impala::TEST().
Member Data Documentation
bool impala::TempRulesFile::deleted_ private
Definition at line 80 of file redactor-test-utils.h.
Referenced by Delete().
string impala::TempRulesFile::name_ private
Definition at line 79 of file redactor-test-utils.h.
Referenced by name(), and TempRulesFile().
The documentation for this class was generated from the following file:
be/src/util/redactor-test-utils.h