Impala: com.cloudera.impala.analysis.PartitionSpec Class Reference
com.cloudera.impala.analysis.PartitionSpec Class Reference
Public Member Functions
PartitionSpec (List< PartitionKeyValue > partitionSpec)
List< PartitionKeyValue > getPartitionSpecKeyValues ()
String getTbl ()
void setTableName (TableName tableName)
boolean partitionExists ()
String getNullPartitionKeyValue ()
void setPartitionShouldExist ()
void setPartitionShouldNotExist ()
void setPrivilegeRequirement (Privilege privilege)
void analyze (Analyzer analyzer) throws AnalysisException
List< TPartitionKeyValue > toThrift ()
String toSql ()
Private Attributes
final ImmutableList
< PartitionKeyValue > partitionSpec_
TableName tableName_
Boolean partitionShouldExist_
Privilege privilegeRequirement_
Boolean partitionExists_
String nullPartitionKeyValue_
Detailed Description
Definition at line 24 of file PartitionSpec.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.PartitionSpec.PartitionSpec (List< PartitionKeyValue > partitionSpec) inline
Definition at line 38 of file PartitionSpec.java.
Member Function Documentation
void com.cloudera.impala.analysis.PartitionSpec.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 75 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.getTbl(), com.cloudera.impala.catalog.Type.isValid(), com.cloudera.impala.analysis.PartitionSpec.nullPartitionKeyValue_, com.cloudera.impala.analysis.PartitionSpec.partitionExists_, com.cloudera.impala.analysis.PartitionSpec.partitionShouldExist_, com.cloudera.impala.analysis.PartitionSpec.partitionSpec_, com.cloudera.impala.analysis.PartitionSpec.privilegeRequirement_, and com.cloudera.impala.analysis.PartitionSpec.tableName_.
String com.cloudera.impala.analysis.PartitionSpec.getNullPartitionKeyValue () inline
Definition at line 55 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.nullPartitionKeyValue_.
Referenced by com.cloudera.impala.analysis.PartitionSpec.toThrift().
List<PartitionKeyValue> com.cloudera.impala.analysis.PartitionSpec.getPartitionSpecKeyValues () inline
Definition at line 42 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.partitionSpec_.
Referenced by com.cloudera.impala.analysis.ComputeStatsStmt.analyze().
String com.cloudera.impala.analysis.PartitionSpec.getTbl () inline
Definition at line 46 of file PartitionSpec.java.
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze().
boolean com.cloudera.impala.analysis.PartitionSpec.partitionExists () inline
Definition at line 48 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.partitionExists_.
void com.cloudera.impala.analysis.PartitionSpec.setPartitionShouldExist () inline
Definition at line 62 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.partitionShouldExist_.
void com.cloudera.impala.analysis.PartitionSpec.setPartitionShouldNotExist () inline
Definition at line 66 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.partitionShouldExist_.
void com.cloudera.impala.analysis.PartitionSpec.setPrivilegeRequirement (Privilege privilege) inline
Definition at line 70 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.privilegeRequirement_.
void com.cloudera.impala.analysis.PartitionSpec.setTableName (TableName tableName) inline
Definition at line 47 of file PartitionSpec.java.
String com.cloudera.impala.analysis.PartitionSpec.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 177 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.partitionSpec_.
Referenced by com.cloudera.impala.analysis.ComputeStatsStmt.toSql().
List<TPartitionKeyValue> com.cloudera.impala.analysis.PartitionSpec.toThrift () inline
Definition at line 166 of file PartitionSpec.java.
References com.cloudera.impala.analysis.PartitionSpec.getNullPartitionKeyValue(), and com.cloudera.impala.analysis.PartitionSpec.partitionSpec_.
Member Data Documentation
String com.cloudera.impala.analysis.PartitionSpec.nullPartitionKeyValue_ private
Definition at line 36 of file PartitionSpec.java.
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze(), and com.cloudera.impala.analysis.PartitionSpec.getNullPartitionKeyValue().
Boolean com.cloudera.impala.analysis.PartitionSpec.partitionExists_ private
Definition at line 32 of file PartitionSpec.java.
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze(), and com.cloudera.impala.analysis.PartitionSpec.partitionExists().
Boolean com.cloudera.impala.analysis.PartitionSpec.partitionShouldExist_ private
Definition at line 27 of file PartitionSpec.java.
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze(), com.cloudera.impala.analysis.PartitionSpec.setPartitionShouldExist(), and com.cloudera.impala.analysis.PartitionSpec.setPartitionShouldNotExist().
final ImmutableList<PartitionKeyValue> com.cloudera.impala.analysis.PartitionSpec.partitionSpec_ private
Definition at line 25 of file PartitionSpec.java.
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze(), com.cloudera.impala.analysis.PartitionSpec.getPartitionSpecKeyValues(), com.cloudera.impala.analysis.PartitionSpec.toSql(), and com.cloudera.impala.analysis.PartitionSpec.toThrift().
Privilege com.cloudera.impala.analysis.PartitionSpec.privilegeRequirement_ private
Definition at line 28 of file PartitionSpec.java.
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze(), and com.cloudera.impala.analysis.PartitionSpec.setPrivilegeRequirement().
TableName com.cloudera.impala.analysis.PartitionSpec.tableName_ private
Definition at line 26 of file PartitionSpec.java.
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/PartitionSpec.java