Impala: com.cloudera.impala.authorization.PrivilegeRequest Class Reference
com.cloudera.impala.authorization.PrivilegeRequest Class Reference
Public Member Functions
PrivilegeRequest (Authorizeable authorizeable, Privilege privilege)
PrivilegeRequest (Privilege privilege)
String getName ()
Privilege getPrivilege ()
Authorizeable getAuthorizeable ()
Private Attributes
final Authorizeable authorizeable_
final Privilege privilege_
Detailed Description
Definition at line 24 of file PrivilegeRequest.java.
Constructor & Destructor Documentation
com.cloudera.impala.authorization.PrivilegeRequest.PrivilegeRequest (Authorizeable authorizeable, Privilege privilege) inline
Definition at line 28 of file PrivilegeRequest.java.
References com.cloudera.impala.authorization.PrivilegeRequest.authorizeable_, and com.cloudera.impala.authorization.PrivilegeRequest.privilege_.
com.cloudera.impala.authorization.PrivilegeRequest.PrivilegeRequest (Privilege privilege) inline
Definition at line 35 of file PrivilegeRequest.java.
References com.cloudera.impala.authorization.PrivilegeRequest.authorizeable_, and com.cloudera.impala.authorization.PrivilegeRequest.privilege_.
Member Function Documentation
Authorizeable com.cloudera.impala.authorization.PrivilegeRequest.getAuthorizeable () inline
Definition at line 57 of file PrivilegeRequest.java.
References com.cloudera.impala.authorization.PrivilegeRequest.authorizeable_.
Referenced by com.cloudera.impala.analysis.Analyzer.authorize(), and com.cloudera.impala.authorization.AuthorizationChecker.hasAccess().
String com.cloudera.impala.authorization.PrivilegeRequest.getName () inline
Definition at line 44 of file PrivilegeRequest.java.
References com.cloudera.impala.authorization.PrivilegeRequest.authorizeable_.
Privilege com.cloudera.impala.authorization.PrivilegeRequest.getPrivilege () inline
Definition at line 51 of file PrivilegeRequest.java.
References com.cloudera.impala.authorization.PrivilegeRequest.privilege_.
Referenced by com.cloudera.impala.analysis.Analyzer.authorize(), and com.cloudera.impala.authorization.AuthorizationChecker.hasAccess().
Member Data Documentation
final Authorizeable com.cloudera.impala.authorization.PrivilegeRequest.authorizeable_ private
Definition at line 25 of file PrivilegeRequest.java.
Referenced by com.cloudera.impala.authorization.PrivilegeRequest.getAuthorizeable(), com.cloudera.impala.authorization.PrivilegeRequest.getName(), and com.cloudera.impala.authorization.PrivilegeRequest.PrivilegeRequest().
final Privilege com.cloudera.impala.authorization.PrivilegeRequest.privilege_ private
Definition at line 26 of file PrivilegeRequest.java.
Referenced by com.cloudera.impala.authorization.PrivilegeRequest.getPrivilege(), and com.cloudera.impala.authorization.PrivilegeRequest.PrivilegeRequest().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/authorization/PrivilegeRequest.java