Impala: com.cloudera.impala.analysis.ShowStatsStmt Class Reference
com.cloudera.impala.analysis.ShowStatsStmt Class Reference
Public Member Functions
ShowStatsStmt (TableName tableName, boolean isShowColStats)
String toSql ()
void analyze (Analyzer analyzer) throws AnalysisException
TShowStatsParams toThrift ()
void setIsExplain ()
boolean isExplain ()
Protected Member Functions
String getSqlPrefix ()
Protected Attributes
final boolean isShowColStats_
final TableName tableName_
Table table_
boolean isExplain_ = false
Detailed Description
Representation of a SHOW TABLE/COLUMN STATS statement for displaying column and table/partition statistics for a given table.
Definition at line 27 of file ShowStatsStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.ShowStatsStmt.ShowStatsStmt (TableName tableName, boolean isShowColStats) inline
Definition at line 34 of file ShowStatsStmt.java.
Member Function Documentation
void com.cloudera.impala.analysis.ShowStatsStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 49 of file ShowStatsStmt.java.
References com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.analysis.ShowStatsStmt.getSqlPrefix(), com.cloudera.impala.analysis.ShowStatsStmt.table_, com.cloudera.impala.analysis.ShowStatsStmt.tableName_, and com.cloudera.impala.authorization.Privilege.VIEW_METADATA.
String com.cloudera.impala.analysis.ShowStatsStmt.getSqlPrefix () inline protected
Definition at line 44 of file ShowStatsStmt.java.
References com.cloudera.impala.analysis.ShowStatsStmt.isShowColStats_.
Referenced by com.cloudera.impala.analysis.ShowStatsStmt.analyze(), and com.cloudera.impala.analysis.ShowStatsStmt.toSql().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.ShowStatsStmt.toSql () inline
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 40 of file ShowStatsStmt.java.
References com.cloudera.impala.analysis.ShowStatsStmt.getSqlPrefix().
TShowStatsParams com.cloudera.impala.analysis.ShowStatsStmt.toThrift () inline
Definition at line 57 of file ShowStatsStmt.java.
References com.cloudera.impala.catalog.Table.getDb(), com.cloudera.impala.catalog.Table.getName(), com.cloudera.impala.analysis.ShowStatsStmt.isShowColStats_, and com.cloudera.impala.analysis.ShowStatsStmt.table_.
Member Data Documentation
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final boolean com.cloudera.impala.analysis.ShowStatsStmt.isShowColStats_ protected
Definition at line 28 of file ShowStatsStmt.java.
Referenced by com.cloudera.impala.analysis.ShowStatsStmt.getSqlPrefix(), and com.cloudera.impala.analysis.ShowStatsStmt.toThrift().
Table com.cloudera.impala.analysis.ShowStatsStmt.table_ protected
Definition at line 32 of file ShowStatsStmt.java.
Referenced by com.cloudera.impala.analysis.ShowPartitionsStmt.analyze(), com.cloudera.impala.analysis.ShowStatsStmt.analyze(), and com.cloudera.impala.analysis.ShowStatsStmt.toThrift().
final TableName com.cloudera.impala.analysis.ShowStatsStmt.tableName_ protected
Definition at line 29 of file ShowStatsStmt.java.
Referenced by com.cloudera.impala.analysis.ShowStatsStmt.analyze().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/ShowStatsStmt.java