Impala: com.cloudera.impala.analysis.AuthorizationTest Class Reference
com.cloudera.impala.analysis.AuthorizationTest Class Reference
Public Member Functions
AuthorizationTest (String policyFile) throws Exception
void TestFix () throws AnalysisException
void TestSentryService () throws ImpalaException
void TestTPCHCleanup () throws AuthorizationException, AnalysisException
void TestSelect () throws AuthorizationException, AnalysisException
void TestUnion () throws AuthorizationException, AnalysisException
void TestInsert () throws AuthorizationException, AnalysisException
void TestWithClause () throws AuthorizationException, AnalysisException
void TestExplain () throws AuthorizationException, AnalysisException
void TestUseDb () throws AnalysisException, AuthorizationException
void TestResetMetadata () throws ImpalaException
void TestCreateTable () throws AnalysisException, AuthorizationException
void TestCreateView () throws AuthorizationException, AnalysisException
void TestCreateDatabase () throws ImpalaException
void TestDropDatabase () throws AnalysisException, AuthorizationException
void TestDropTable () throws AnalysisException, AuthorizationException
void TestDropView () throws AnalysisException, AuthorizationException
void TestAlterTable () throws AnalysisException, AuthorizationException
void TestAlterView () throws AnalysisException, AuthorizationException
void TestComputeStatsTable () throws AnalysisException, AuthorizationException
void TestDropStats () throws AnalysisException, AuthorizationException
void TestDescribe () throws AuthorizationException, AnalysisException
void TestLoad () throws AuthorizationException, AnalysisException
void TestShowPermissions () throws AuthorizationException, AnalysisException
void TestShowDbResultsFiltered () throws ImpalaException
void TestShowTableResultsFiltered () throws ImpalaException
void TestShowCreateTable () throws ImpalaException
void TestHs2GetTables () throws ImpalaException
void TestHs2GetSchema () throws ImpalaException
void TestHs2GetColumns () throws ImpalaException
void TestShortUsernameUsed () throws AnalysisException, AuthorizationException
void TestFunction () throws ImpalaException
void TestServerNameAuthorized () throws AnalysisException
void TestNoPermissionsWhenPolicyFileDoesNotExist () throws AnalysisException
void TestConfigValidation () throws InternalException
void TestLocalGroupPolicyProvider () throws AnalysisException, AuthorizationException
Static Public Member Functions
static Collection testVectors ()
Static Protected Attributes
static final String SERVER_HOST = "localhost"
Private Member Functions
void setup () throws Exception
void TestWithIncorrectConfig (AuthorizationConfig authzConfig, User user) throws AnalysisException
void AuthzOk (String stmt) throws AuthorizationException, AnalysisException
void AuthzOk (AnalysisContext context, String stmt) throws AuthorizationException, AnalysisException
void AuthzError (String stmt, String expectedErrorString) throws AnalysisException
void AuthzError (AnalysisContext analysisContext, String stmt, String expectedErrorString, User user) throws AnalysisException
SentryPolicyService createSentryService ()
Static Private Member Functions
static void AuthzOk (Frontend fe, AnalysisContext context, String stmt) throws AuthorizationException, AnalysisException
static void AuthzError (Frontend fe, AnalysisContext analysisContext, String stmt, String expectedErrorString, User user) throws AnalysisException
static TSessionState createSessionState (String defaultDb, User user)
Private Attributes
final AuthorizationConfig authzConfig_
final ImpaladCatalog catalog_
final TQueryCtx queryCtx_
final AnalysisContext analysisContext_
final Frontend fe_
Static Private Attributes
static final Logger LOG
static final String AUTHZ_POLICY_FILE = "/test-warehouse/authz-policy.ini"
static final User USER = new User(System.getProperty("user.name"))
static final User ADMIN_USER = new User("admin_user")
static boolean isSetup_ = false
Detailed Description
Definition at line 70 of file AuthorizationTest.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AuthorizationTest.AuthorizationTest (String policyFile) throws Exception inline
Definition at line 106 of file AuthorizationTest.java.
References com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
Member Function Documentation
void com.cloudera.impala.analysis.AuthorizationTest.AuthzError (String stmt, String expectedErrorString) throws AnalysisException inline private
Verifies that a given statement fails authorization and the expected error string matches.
Definition at line 1562 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.AuthzError (AnalysisContext analysisContext, String stmt, String expectedErrorString, User user) throws AnalysisException inline private
Definition at line 1567 of file AuthorizationTest.java.
static void com.cloudera.impala.analysis.AuthorizationTest.AuthzError (Frontend fe, AnalysisContext analysisContext, String stmt, String expectedErrorString, User user) throws AnalysisException inline static private
Definition at line 1572 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.AuthzOk (String stmt) throws AuthorizationException, AnalysisException inline private
Definition at line 1542 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.AuthzOk (AnalysisContext context, String stmt) throws AuthorizationException, AnalysisException inline private
Definition at line 1547 of file AuthorizationTest.java.
static void com.cloudera.impala.analysis.AuthorizationTest.AuthzOk (Frontend fe, AnalysisContext context, String stmt) throws AuthorizationException, AnalysisException inline static private
Definition at line 1552 of file AuthorizationTest.java.
SentryPolicyService com.cloudera.impala.analysis.AuthorizationTest.createSentryService () inline private
Definition at line 1598 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig().
static TSessionState com.cloudera.impala.analysis.AuthorizationTest.createSessionState (String defaultDb, User user) inline static private
Definition at line 1593 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.User.getName().
void com.cloudera.impala.analysis.AuthorizationTest.setup () throws Exception inline private
Definition at line 120 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.AuthorizeableTable.ANY_TABLE_NAME, and com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig().
void com.cloudera.impala.analysis.AuthorizationTest.TestAlterTable () throws AnalysisException, AuthorizationException inline
Definition at line 834 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestAlterView () throws AnalysisException, AuthorizationException inline
Definition at line 949 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestComputeStatsTable () throws AnalysisException, AuthorizationException inline
Definition at line 1005 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestConfigValidation () throws InternalException inline
Definition at line 1389 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestCreateDatabase () throws ImpalaException inline
Definition at line 699 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig(), and com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
void com.cloudera.impala.analysis.AuthorizationTest.TestCreateTable () throws AnalysisException, AuthorizationException inline
Definition at line 577 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestCreateView () throws AuthorizationException, AnalysisException inline
Definition at line 648 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestDescribe () throws AuthorizationException, AnalysisException inline
Definition at line 1027 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestDropDatabase () throws AnalysisException, AuthorizationException inline
Definition at line 738 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestDropStats () throws AnalysisException, AuthorizationException inline
Definition at line 1016 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestDropTable () throws AnalysisException, AuthorizationException inline
Definition at line 768 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestDropView () throws AnalysisException, AuthorizationException inline
Definition at line 801 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestExplain () throws AuthorizationException, AnalysisException inline
Definition at line 434 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestFix () throws AnalysisException inline
Definition at line 249 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestFunction () throws ImpalaException inline
Definition at line 1283 of file AuthorizationTest.java.
References com.cloudera.impala.testutil.TestUtils.createQueryContext(), com.cloudera.impala.catalog.Catalog.DEFAULT_DB, com.cloudera.impala.authorization.User.getName(), com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig(), com.cloudera.impala.catalog.Type.INT, and com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
void com.cloudera.impala.analysis.AuthorizationTest.TestHs2GetColumns () throws ImpalaException inline
Definition at line 1230 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestHs2GetSchema () throws ImpalaException inline
Definition at line 1212 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestHs2GetTables () throws ImpalaException inline
Definition at line 1191 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestInsert () throws AuthorizationException, AnalysisException inline
Definition at line 373 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestLoad () throws AuthorizationException, AnalysisException inline
Definition at line 1050 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestLocalGroupPolicyProvider () throws AnalysisException, AuthorizationException inline
Definition at line 1489 of file AuthorizationTest.java.
References com.cloudera.impala.testutil.TestUtils.createQueryContext(), com.cloudera.impala.catalog.Catalog.DEFAULT_DB, com.cloudera.impala.authorization.User.getName(), and com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
void com.cloudera.impala.analysis.AuthorizationTest.TestNoPermissionsWhenPolicyFileDoesNotExist () throws AnalysisException inline
Definition at line 1376 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.AuthorizationConfig.createHadoopGroupAuthConfig(), and com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
void com.cloudera.impala.analysis.AuthorizationTest.TestResetMetadata () throws ImpalaException inline
Definition at line 536 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
void com.cloudera.impala.analysis.AuthorizationTest.TestSelect () throws AuthorizationException, AnalysisException inline
Definition at line 293 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestSentryService () throws ImpalaException inline
Definition at line 256 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.AuthorizationConfig.getSentryConfig().
void com.cloudera.impala.analysis.AuthorizationTest.TestServerNameAuthorized () throws AnalysisException inline
Definition at line 1366 of file AuthorizationTest.java.
References com.cloudera.impala.authorization.AuthorizationConfig.createHadoopGroupAuthConfig(), and com.cloudera.impala.authorization.AuthorizationConfig.isFileBasedPolicy().
void com.cloudera.impala.analysis.AuthorizationTest.TestShortUsernameUsed () throws AnalysisException, AuthorizationException inline
Definition at line 1256 of file AuthorizationTest.java.
References com.cloudera.impala.testutil.TestUtils.createQueryContext(), com.cloudera.impala.catalog.Catalog.DEFAULT_DB, and com.cloudera.impala.authorization.User.getName().
void com.cloudera.impala.analysis.AuthorizationTest.TestShowCreateTable () throws ImpalaException inline
Definition at line 1172 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestShowDbResultsFiltered () throws ImpalaException inline
Definition at line 1145 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestShowPermissions () throws AuthorizationException, AnalysisException inline
Definition at line 1091 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestShowTableResultsFiltered () throws ImpalaException inline
Definition at line 1159 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestTPCHCleanup () throws AuthorizationException, AnalysisException inline
Definition at line 283 of file AuthorizationTest.java.
References com.cloudera.impala.catalog.Catalog.getDb().
void com.cloudera.impala.analysis.AuthorizationTest.TestUnion () throws AuthorizationException, AnalysisException inline
Definition at line 362 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestUseDb () throws AnalysisException, AuthorizationException inline
Definition at line 506 of file AuthorizationTest.java.
static Collection com.cloudera.impala.analysis.AuthorizationTest.testVectors () inline static
Definition at line 102 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestWithClause () throws AuthorizationException, AnalysisException inline
Definition at line 408 of file AuthorizationTest.java.
void com.cloudera.impala.analysis.AuthorizationTest.TestWithIncorrectConfig (AuthorizationConfig authzConfig, User user) throws AnalysisException inline private
Definition at line 1524 of file AuthorizationTest.java.
References com.cloudera.impala.testutil.TestUtils.createQueryContext(), and com.cloudera.impala.catalog.Catalog.DEFAULT_DB.
Member Data Documentation
final User com.cloudera.impala.analysis.AuthorizationTest.ADMIN_USER = new User("admin_user") static private
Definition at line 88 of file AuthorizationTest.java.
final AnalysisContext com.cloudera.impala.analysis.AuthorizationTest.analysisContext_ private
Definition at line 93 of file AuthorizationTest.java.
final String com.cloudera.impala.analysis.AuthorizationTest.AUTHZ_POLICY_FILE = "/test-warehouse/authz-policy.ini" static private
Definition at line 84 of file AuthorizationTest.java.
final AuthorizationConfig com.cloudera.impala.analysis.AuthorizationTest.authzConfig_ private
Definition at line 90 of file AuthorizationTest.java.
final ImpaladCatalog com.cloudera.impala.analysis.AuthorizationTest.catalog_ private
Definition at line 91 of file AuthorizationTest.java.
final Frontend com.cloudera.impala.analysis.AuthorizationTest.fe_ private
Definition at line 94 of file AuthorizationTest.java.
boolean com.cloudera.impala.analysis.AuthorizationTest.isSetup_ = false static private
Definition at line 96 of file AuthorizationTest.java.
final Logger com.cloudera.impala.analysis.AuthorizationTest.LOG static private
Initial value:
=
      LoggerFactory.getLogger(AuthorizationTest.class)
Definition at line 71 of file AuthorizationTest.java.
final TQueryCtx com.cloudera.impala.analysis.AuthorizationTest.queryCtx_ private
Definition at line 92 of file AuthorizationTest.java.
final String com.cloudera.impala.analysis.AuthorizationTest.SERVER_HOST = "localhost" static protected
Definition at line 95 of file AuthorizationTest.java.
final User com.cloudera.impala.analysis.AuthorizationTest.USER = new User(System.getProperty("user.name")) static private
Definition at line 85 of file AuthorizationTest.java.
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/analysis/AuthorizationTest.java