Impala: com.cloudera.impala.planner.PlannerTest Class Reference
com.cloudera.impala.planner.PlannerTest Class Reference
Public Member Functions
void testPredicatePropagation ()
void testConstant ()
void testEmpty ()
void testDistinct ()
void testAggregation ()
void testAnalyticFns ()
void testHbase ()
void testInsert ()
void testHdfs ()
void testNestedCollections ()
void testJoins ()
void testJoinOrder ()
void testOuterJoins ()
void testImplicitJoins ()
void testOrder ()
void testTopN ()
void testInlineView ()
void testInlineViewLimit ()
void testSubqueryRewrite ()
void testUnion ()
void testValues ()
void testViews ()
void testWithClause ()
void testDistinctEstimate ()
void testDataSourceTables ()
void testLineage ()
void testDdl ()
void testTpch ()
void testTpcds ()
void testSmallQueryOptimization ()
Static Public Member Functions
static void setUp () throws Exception
static void cleanUp ()
Protected Member Functions
Path cleanseFilePath (Path path)
void runPlannerTestFile (String testFile, TQueryOptions options)
void runPlannerTestFile (String testFile)
void runPlannerTestFile (String testFile, String dbName)
Detailed Description
Definition at line 22 of file PlannerTest.java.
Member Function Documentation
Path com.cloudera.impala.planner.PlannerTestBase.cleanseFilePath (Path path) inline protected inherited
Normalize components of the given file path, removing any environment- or test-run dependent components. For example, substitutes the unique id portion of Impala generated file names with a fixed literal. Subclasses should override to do filesystem specific cleansing.
Definition at line 264 of file PlannerTestBase.java.
Referenced by com.cloudera.impala.planner.PlannerTestBase.PrintScanRangeLocations().
static void com.cloudera.impala.planner.PlannerTestBase.cleanUp () inline static inherited
Definition at line 99 of file PlannerTestBase.java.
void com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile (String testFile, TQueryOptions options) inline protected inherited
Definition at line 606 of file PlannerTestBase.java.
Referenced by com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile(), com.cloudera.impala.planner.PlannerTest.testAggregation(), com.cloudera.impala.planner.PlannerTest.testAnalyticFns(), com.cloudera.impala.planner.PlannerTest.testConstant(), com.cloudera.impala.planner.PlannerTest.testDataSourceTables(), com.cloudera.impala.planner.PlannerTest.testDdl(), com.cloudera.impala.planner.PlannerTest.testDistinct(), com.cloudera.impala.planner.PlannerTest.testDistinctEstimate(), com.cloudera.impala.planner.PlannerTest.testEmpty(), com.cloudera.impala.planner.PlannerTest.testHbase(), com.cloudera.impala.planner.PlannerTest.testHdfs(), com.cloudera.impala.planner.PlannerTest.testImplicitJoins(), com.cloudera.impala.planner.PlannerTest.testInlineView(), com.cloudera.impala.planner.PlannerTest.testInlineViewLimit(), com.cloudera.impala.planner.PlannerTest.testInsert(), com.cloudera.impala.planner.PlannerTest.testJoinOrder(), com.cloudera.impala.planner.PlannerTest.testJoins(), com.cloudera.impala.planner.PlannerTest.testLineage(), com.cloudera.impala.planner.PlannerTest.testNestedCollections(), com.cloudera.impala.planner.PlannerTest.testOrder(), com.cloudera.impala.planner.PlannerTest.testOuterJoins(), com.cloudera.impala.planner.PlannerTest.testPredicatePropagation(), com.cloudera.impala.planner.S3PlannerTest.testS3ScanRanges(), com.cloudera.impala.planner.PlannerTest.testSmallQueryOptimization(), com.cloudera.impala.planner.PlannerTest.testSubqueryRewrite(), com.cloudera.impala.planner.PlannerTest.testTopN(), com.cloudera.impala.planner.PlannerTest.testTpcds(), com.cloudera.impala.planner.PlannerTest.testTpch(), com.cloudera.impala.planner.PlannerTest.testUnion(), com.cloudera.impala.planner.PlannerTest.testValues(), com.cloudera.impala.planner.PlannerTest.testViews(), and com.cloudera.impala.planner.PlannerTest.testWithClause().
void com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile (String testFile) inline protected inherited
Definition at line 647 of file PlannerTestBase.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile (String testFile, String dbName) inline protected inherited
Definition at line 651 of file PlannerTestBase.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
static void com.cloudera.impala.planner.PlannerTestBase.setUp () throws Exception inline static inherited
Definition at line 91 of file PlannerTestBase.java.
void com.cloudera.impala.planner.PlannerTest.testAggregation () inline
Definition at line 45 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testAnalyticFns () inline
Definition at line 50 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testConstant () inline
Definition at line 30 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testDataSourceTables () inline
Definition at line 145 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testDdl () inline
Definition at line 155 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testDistinct () inline
Definition at line 40 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testDistinctEstimate () inline
Definition at line 140 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testEmpty () inline
Definition at line 35 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testHbase () inline
Definition at line 55 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testHdfs () inline
Definition at line 65 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testImplicitJoins () inline
Definition at line 90 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testInlineView () inline
Definition at line 105 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testInlineViewLimit () inline
Definition at line 110 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testInsert () inline
Definition at line 60 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testJoinOrder () inline
Definition at line 80 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testJoins () inline
Definition at line 75 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testLineage () inline
Definition at line 150 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testNestedCollections () inline
Definition at line 70 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testOrder () inline
Definition at line 95 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testOuterJoins () inline
Definition at line 85 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testPredicatePropagation () inline
Definition at line 25 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testSmallQueryOptimization () inline
Definition at line 173 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testSubqueryRewrite () inline
Definition at line 115 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testTopN () inline
Definition at line 100 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testTpcds () inline
Definition at line 165 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testTpch () inline
Definition at line 160 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testUnion () inline
Definition at line 120 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testValues () inline
Definition at line 125 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testViews () inline
Definition at line 130 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
void com.cloudera.impala.planner.PlannerTest.testWithClause () inline
Definition at line 135 of file PlannerTest.java.
References com.cloudera.impala.planner.PlannerTestBase.runPlannerTestFile().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/planner/PlannerTest.java