Impala: impala::InPredicate Class Reference
impala::InPredicate Class Reference abstract
Predicate for evaluating expressions of the form "val [NOT] IN (x1, x2, x3...)".
#include <in-predicate.h>
Classes
struct SetLookupState
Public Member Functions
template<typename T , typename SetType , bool not_in, InPredicate::Strategy strategy>
BooleanVal TemplatedIn (FunctionContext *ctx, const T &val, int num_args, const T *args)
virtual BooleanVal GetBooleanVal (ExprContext *context, TupleRow *)
virtual TinyIntVal GetTinyIntVal (ExprContext *context, TupleRow *)
virtual SmallIntVal GetSmallIntVal (ExprContext *context, TupleRow *)
virtual IntVal GetIntVal (ExprContext *context, TupleRow *)
virtual BigIntVal GetBigIntVal (ExprContext *context, TupleRow *)
virtual FloatVal GetFloatVal (ExprContext *context, TupleRow *)
virtual DoubleVal GetDoubleVal (ExprContext *context, TupleRow *)
virtual StringVal GetStringVal (ExprContext *context, TupleRow *)
virtual TimestampVal GetTimestampVal (ExprContext *context, TupleRow *)
virtual DecimalVal GetDecimalVal (ExprContext *context, TupleRow *)
int output_scale () const
void AddChild (Expr *expr)
Expr * GetChild (int i) const
int GetNumChildren () const
const ColumnType & type () const
bool is_slotref () const
const std::vector< Expr * > & children () const
virtual bool IsConstant () const
virtual int GetSlotIds (std::vector< SlotId > *slot_ids) const
virtual Status GetCodegendComputeFn (RuntimeState *state, llvm::Function **fn)=0
virtual AnyVal * GetConstVal (ExprContext *context)
virtual std::string DebugString () const
Static Public Member Functions
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::BooleanVal &val, int num_args, const impala_udf::BooleanVal *args)
Functions for every type.
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::BooleanVal &val, int num_args, const impala_udf::BooleanVal *args)
static void SetLookupPrepare_boolean (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_boolean (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::BooleanVal &val, int num_args, const impala_udf::BooleanVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::BooleanVal &val, int num_args, const impala_udf::BooleanVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::TinyIntVal &val, int num_args, const impala_udf::TinyIntVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::TinyIntVal &val, int num_args, const impala_udf::TinyIntVal *args)
static void SetLookupPrepare_tinyint (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_tinyint (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::TinyIntVal &val, int num_args, const impala_udf::TinyIntVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::TinyIntVal &val, int num_args, const impala_udf::TinyIntVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::SmallIntVal &val, int num_args, const impala_udf::SmallIntVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::SmallIntVal &val, int num_args, const impala_udf::SmallIntVal *args)
static void SetLookupPrepare_smallint (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_smallint (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::SmallIntVal &val, int num_args, const impala_udf::SmallIntVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::SmallIntVal &val, int num_args, const impala_udf::SmallIntVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::IntVal &val, int num_args, const impala_udf::IntVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::IntVal &val, int num_args, const impala_udf::IntVal *args)
static void SetLookupPrepare_int (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_int (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::IntVal &val, int num_args, const impala_udf::IntVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::IntVal &val, int num_args, const impala_udf::IntVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::BigIntVal &val, int num_args, const impala_udf::BigIntVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::BigIntVal &val, int num_args, const impala_udf::BigIntVal *args)
static void SetLookupPrepare_bigint (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_bigint (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::BigIntVal &val, int num_args, const impala_udf::BigIntVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::BigIntVal &val, int num_args, const impala_udf::BigIntVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::FloatVal &val, int num_args, const impala_udf::FloatVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::FloatVal &val, int num_args, const impala_udf::FloatVal *args)
static void SetLookupPrepare_float (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_float (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::FloatVal &val, int num_args, const impala_udf::FloatVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::FloatVal &val, int num_args, const impala_udf::FloatVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::DoubleVal &val, int num_args, const impala_udf::DoubleVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::DoubleVal &val, int num_args, const impala_udf::DoubleVal *args)
static void SetLookupPrepare_double (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_double (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::DoubleVal &val, int num_args, const impala_udf::DoubleVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::DoubleVal &val, int num_args, const impala_udf::DoubleVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::StringVal &val, int num_args, const impala_udf::StringVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::StringVal &val, int num_args, const impala_udf::StringVal *args)
static void SetLookupPrepare_string (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_string (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::StringVal &val, int num_args, const impala_udf::StringVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::StringVal &val, int num_args, const impala_udf::StringVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::TimestampVal &val, int num_args, const impala_udf::TimestampVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::TimestampVal &val, int num_args, const impala_udf::TimestampVal *args)
static void SetLookupPrepare_timestamp (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_timestamp (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::TimestampVal &val, int num_args, const impala_udf::TimestampVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::TimestampVal &val, int num_args, const impala_udf::TimestampVal *args)
static impala_udf::BooleanVal InIterate (impala_udf::FunctionContext *context, const impala_udf::DecimalVal &val, int num_args, const impala_udf::DecimalVal *args)
static impala_udf::BooleanVal NotInIterate (impala_udf::FunctionContext *context, const impala_udf::DecimalVal &val, int num_args, const impala_udf::DecimalVal *args)
static void SetLookupPrepare_decimal (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static void SetLookupClose_decimal (impala_udf::FunctionContext *ctx, impala_udf::FunctionContext::FunctionStateScope scope)
static impala_udf::BooleanVal InSetLookup (impala_udf::FunctionContext *context, const impala_udf::DecimalVal &val, int num_args, const impala_udf::DecimalVal *args)
static impala_udf::BooleanVal NotInSetLookup (impala_udf::FunctionContext *context, const impala_udf::DecimalVal &val, int num_args, const impala_udf::DecimalVal *args)
static Status CreateExprTree (ObjectPool *pool, const TExpr &texpr, ExprContext **ctx)
static Status CreateExprTrees (ObjectPool *pool, const std::vector< TExpr > &texprs, std::vector< ExprContext * > *ctxs)
static Status Prepare (const std::vector< ExprContext * > &ctxs, RuntimeState *state, const RowDescriptor &row_desc, MemTracker *tracker)
static Status Open (const std::vector< ExprContext * > &ctxs, RuntimeState *state)
Convenience function for opening multiple expr trees.
static Status Clone (const std::vector< ExprContext * > &ctxs, RuntimeState *state, std::vector< ExprContext * > *new_ctxs)
static void Close (const std::vector< ExprContext * > &ctxs, RuntimeState *state)
Convenience function for closing multiple expr trees.
static Expr * CreateLiteral (ObjectPool *pool, const ColumnType &type, void *data)
static Expr * CreateLiteral (ObjectPool *pool, const ColumnType &type, const std::string &)
static int ComputeResultsLayout (const std::vector< Expr * > &exprs, std::vector< int > *offsets, int *var_result_begin)
static int ComputeResultsLayout (const std::vector< ExprContext * > &ctxs, std::vector< int > *offsets, int *var_result_begin)
static std::string DebugString (const std::vector< Expr * > &exprs)
static std::string DebugString (const std::vector< ExprContext * > &ctxs)
static void InitBuiltinsDummy ()
Static Public Attributes
static const char * LLVM_CLASS_NAME = "class.impala::Expr"
Protected Member Functions
virtual Status Prepare (RuntimeState *state, const RowDescriptor &row_desc, ExprContext *context)
virtual Status Open (RuntimeState *state, ExprContext *context, FunctionContext::FunctionStateScope scope=FunctionContext::FRAGMENT_LOCAL)
virtual void Close (RuntimeState *state, ExprContext *context, FunctionContext::FunctionStateScope scope=FunctionContext::FRAGMENT_LOCAL)
Subclasses overriding this function should call Expr::Close().
std::string DebugString (const std::string &expr_name) const
Simple debug string that provides no expr subclass-specific information.
FunctionContext * RegisterFunctionContext (ExprContext *ctx, RuntimeState *state, int varargs_buffer_size=0)
llvm::Function * CreateIrFunctionPrototype (LlvmCodeGen *codegen, const std::string &name, llvm::Value *(*args)[2])
Status GetCodegendComputeFnWrapper (RuntimeState *state, llvm::Function **fn)
llvm::Function * GetStaticGetValWrapper (ColumnType type, LlvmCodeGen *codegen)
Protected Attributes
LibCache::LibCacheEntry * cache_entry_
Cache entry for the library implementing this function.
TFunction fn_
Function description.
const bool is_slotref_
recognize if this node is a slotref in order to speed up GetValue()
const ColumnType type_
analysis is done, types are fixed at this point
std::vector< Expr * > children_
int output_scale_
int context_index_
llvm::Function * ir_compute_fn_
Cached codegened compute function. Exprs should set this in GetCodegendComputeFn().
boost::scoped_ptr< AnyVal > constant_val_
Private Types
enum Strategy { SET_LOOKUP, ITERATE }
Static Private Member Functions
template<typename T , typename SetType , bool not_in, Strategy strategy>
static impala_udf::BooleanVal TemplatedIn (impala_udf::FunctionContext *context, const T &val, int num_args, const T *args)
template<typename T , typename SetType >
static void SetLookupPrepare (FunctionContext *ctx, FunctionContext::FunctionStateScope scope)
Initializes an SetLookupState in ctx.
template<typename SetType >
static void SetLookupClose (FunctionContext *ctx, FunctionContext::FunctionStateScope scope)
template<typename T , typename SetType >
static BooleanVal SetLookup (SetLookupState< SetType > *state, const T &v)
Looks up v in state->val_set.
template<typename T >
static BooleanVal Iterate (const FunctionContext::TypeDesc *type, const T &val, int num_args, const T *args)
Iterates through each vararg looking for val. 'type' is the type of 'val' and 'args'.
Friends
class InPredicateBenchmark
Detailed Description
Predicate for evaluating expressions of the form "val [NOT] IN (x1, x2, x3...)".
There are two strategies for evaluating the IN predicate: 1) SET_LOOKUP: This strategy is for when all the values in the IN list are constant. In the prepare function, we create a set of the constant values from the IN list, and use this set to lookup a given 'val'. 2) ITERATE: This is the fallback strategy for when their are non-constant IN list values, or very few values in the IN list. We simply iterate through every expression and compare it to val. This strategy has no prepare function. The FE chooses which strategy we should use by choosing the appropriate function (e.g., InIterate() or InSetLookup()). If it chooses SET_LOOKUP, it also sets the appropriate SetLookupPrepare and SetLookupClose functions. TODO: the set lookup logic is not yet implemented for TimestampVals or DecimalVals
Definition at line 42 of file in-predicate.h.
Member Enumeration Documentation
enum impala::InPredicate::Strategy private
Enumerator
SET_LOOKUP
Indicates we should use SetLookUp().
ITERATE
Indicates we should use Iterate().
Definition at line 268 of file in-predicate.h.
Member Function Documentation
void impala::Expr::AddChild (Expr * expr) inline inherited
Definition at line 141 of file expr.h.
Referenced by impala::Expr::CreateTreeFromThrift().
const std::vector<Expr*>& impala::Expr::children () const inline inherited
Definition at line 148 of file expr.h.
Referenced by impala::CaseExpr::GetChildVal(), and impala::CaseExpr::GetCodegendComputeFn().
Status Expr::Clone (const std::vector< ExprContext * > & ctxs, RuntimeState * state, std::vector< ExprContext * > * new_ctxs) static inherited
Clones each ExprContext for multiple expr trees. 'new_ctxs' should be an empty vector, and a clone of each context in 'ctxs' will be added to it. The new ExprContexts are created in state->obj_pool().
Definition at line 374 of file expr.cc.
References impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::HdfsScanNode::GetConjunctCtxs(), and impala::SortExecExprs::Open().
static void impala::Expr::Close (const std::vector< ExprContext * > & ctxs, RuntimeState * state) static inherited
Convenience function for closing multiple expr trees.
Referenced by impala::UnionNode::Close(), impala::SortExecExprs::Close(), impala::CaseExpr::Close(), impala::HashJoinNode::Close(), impala::AggregationNode::Close(), impala::ScalarFnCall::Close(), impala::ExprContext::Close(), impala::HiveUdfCall::Close(), impala::PartitionedHashJoinNode::Close(), impala::DataStreamSender::Close(), impala::PartitionedAggregationNode::Close(), impala::AggFnEvaluator::Close(), impala::HdfsScanner::Close(), impala::ExecNode::Close(), impala::HdfsScanNode::Close(), impala::HdfsTableSink::Close(), impala::HdfsPartitionDescriptor::CloseExprs(), impala::ImpalaServer::QueryExecState::Done(), impala::OldHashTableTest::TearDown(), and impala::HashTableTest::TearDown().
void Expr::Close (RuntimeState * state, ExprContext * context, FunctionContext::FunctionStateScope scope = FunctionContext::FRAGMENT_LOCAL) protected virtual inherited
Subclasses overriding this function should call Expr::Close().
If scope if FRAGMENT_LOCAL, both fragment- and thread-local state should be torn down. Otherwise, if scope is THREAD_LOCAL, only thread-local state should be torn down.
Reimplemented in impala::HiveUdfCall, impala::ScalarFnCall, and impala::CaseExpr.
Definition at line 114 of file expr.cc.
References impala::Expr::cache_entry_, impala::Expr::children_, impala::LibCache::DecrementUseCount(), and impala::LibCache::instance().
static int impala::Expr::ComputeResultsLayout (const std::vector< Expr * > & exprs, std::vector< int > * offsets, int * var_result_begin) static inherited
Computes a memory efficient layout for storing the results of evaluating 'exprs' Returns the number of bytes necessary to store all the results and offsets where the result for each expr should be stored. Variable length types are guaranteed to be at the end and 'var_result_begin' will be set the beginning byte offset where variable length results begin. 'var_result_begin' will be set to -1 if there are no variable len types.
Referenced by impala::HashTableCtx::HashTableCtx(), and impala::OldHashTable::OldHashTable().
static int impala::Expr::ComputeResultsLayout (const std::vector< ExprContext * > & ctxs, std::vector< int > * offsets, int * var_result_begin) static inherited
Status Expr::CreateExprTree (ObjectPool * pool, const TExpr & texpr, ExprContext ** ctx) static inherited
Create expression tree from the list of nodes contained in texpr within 'pool'. Returns the root of expression tree in 'expr' and the corresponding ExprContext in 'ctx'.
Definition at line 129 of file expr.cc.
References impala::Expr::CreateTreeFromThrift(), impala::Status::GetDetail(), impala::Status::OK, and impala::Status::ok().
Referenced by impala::Expr::CreateExprTrees(), impala::HdfsPartitionDescriptor::HdfsPartitionDescriptor(), impala::HashJoinNode::Init(), impala::AnalyticEvalNode::Init(), impala::PartitionedHashJoinNode::Init(), and Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs().
Status Expr::CreateExprTrees (ObjectPool * pool, const std::vector< TExpr > & texprs, std::vector< ExprContext * > * ctxs) static inherited
Creates vector of ExprContexts containing exprs from the given vector of TExprs within 'pool'. Returns an error if any of the individual conversions caused an error, otherwise OK.
Definition at line 149 of file expr.cc.
References impala::Expr::CreateExprTree(), impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::DataStreamSender::DataStreamSender(), impala::UnionNode::Init(), impala::HashJoinNode::Init(), impala::AggregationNode::Init(), impala::ExecNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::PartitionedAggregationNode::Init(), impala::HdfsScanNode::Prepare(), and impala::HdfsTableSink::Prepare().
Function * Expr::CreateIrFunctionPrototype (LlvmCodeGen * codegen, const std::string & name, llvm::Value *(*) args[2]) protected inherited
Helper function to create an empty Function* with the appropriate signature to be returned by GetCodegendComputeFn(). 'name' is the name of the returned Function*. The arguments to the function are returned in 'args'.
Definition at line 456 of file expr.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::LlvmCodeGen::FnPrototype::GeneratePrototype(), impala::CodegenAnyVal::GetLoweredType(), impala::LlvmCodeGen::GetPtrType(), impala::TupleRow::LLVM_CLASS_NAME, impala::ExprContext::LLVM_CLASS_NAME, and impala::Expr::type().
Referenced by impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
static Expr* impala::Expr::CreateLiteral (ObjectPool * pool, const ColumnType & type, void * data) static inherited
Create a new literal expr of 'type' with initial 'data'. data should match the ColumnType (i.e. type == TYPE_INT, data is a int*) The new Expr will be allocated from the pool.
static Expr* impala::Expr::CreateLiteral (ObjectPool * pool, const ColumnType & type, const std::string &) static inherited
Create a new literal expr of 'type' by parsing the string. NULL will be returned if the string and type are not compatible. The new Expr will be allocated from the pool.
string Expr::DebugString () const virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::IsNullExpr, impala::OrPredicate, impala::Literal, impala::CaseExpr, impala::AndPredicate, impala::ScalarFnCall, impala::NullLiteral, impala::TupleIsNullPredicate, and impala::SlotRef.
Definition at line 385 of file expr.cc.
References impala::Expr::children_, impala::ColumnType::DebugString(), and impala::Expr::type_.
Referenced by impala::HashJoinNode::AddToDebugString(), impala::PartitionedHashJoinNode::AddToDebugString(), impala::SlotRef::DebugString(), impala::SortNode::DebugString(), impala::TopNNode::DebugString(), impala::ScalarFnCall::DebugString(), impala::CaseExpr::DebugString(), impala::Literal::DebugString(), impala::AggregationNode::DebugString(), impala::AnalyticEvalNode::DebugString(), impala::HiveUdfCall::DebugString(), impala::PartitionedAggregationNode::DebugString(), impala::HdfsTableSink::DebugString(), impala::Expr::GetBigIntVal(), impala::Expr::GetBooleanVal(), impala::Expr::GetDecimalVal(), impala::Expr::GetDoubleVal(), impala::Expr::GetFloatVal(), impala::Expr::GetIntVal(), impala::Expr::GetSmallIntVal(), impala::Expr::GetStringVal(), impala::Expr::GetTimestampVal(), and impala::Expr::GetTinyIntVal().
static std::string impala::Expr::DebugString (const std::vector< Expr * > & exprs) static inherited
static std::string impala::Expr::DebugString (const std::vector< ExprContext * > & ctxs) static inherited
std::string impala::Expr::DebugString (const std::string & expr_name) const inline protected inherited
Simple debug string that provides no expr subclass-specific information.
Definition at line 332 of file expr.h.
References impala_udf::DebugString().
BigIntVal Expr::GetBigIntVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 589 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::ExprContext::GetBigIntVal(), impala::Expr::GetBigIntVal(), impala::Expr::GetConstVal(), and impala::ExprContext::GetValue().
BooleanVal Expr::GetBooleanVal (ExprContext * context, TupleRow * row) virtual inherited
Virtual compute functions for each *Val type. Each Expr subclass should implement the functions for the return type(s) it supports. For example, a boolean function will only implement GetBooleanVal(). Some Exprs, like Literal, have many possible return types and will implement multiple Get*Val() functions.
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::OrPredicate, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::TupleIsNullPredicate, impala::AndPredicate, impala::CaseExpr, and impala::NullLiteral.
Definition at line 573 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::ExprContext::GetBooleanVal(), impala::Expr::GetBooleanVal(), impala::Expr::GetConstVal(), and impala::ExprContext::GetValue().
Expr* impala::Expr::GetChild (int i) const inline inherited
Definition at line 142 of file expr.h.
Referenced by impala::HiveUdfCall::Evaluate(), and impala::HiveUdfCall::Prepare().
virtual Status impala::Expr::GetCodegendComputeFn (RuntimeState * state, llvm::Function ** fn) pure virtual inherited
Returns an llvm::Function* with signature: <subclass of="" anyval>=""> ComputeFn(ExprContext* context, TupleRow* row) The function should evaluate this expr over 'row' and return the result as the appropriate type of AnyVal.
Implemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::IsNullExpr, impala::OrPredicate, impala::ScalarFnCall, impala::Literal, impala::AndPredicate, impala::SlotRef, impala::TupleIsNullPredicate, impala::CaseExpr, and impala::NullLiteral.
Referenced by impala::AggregationNode::CodegenUpdateSlot(), and impala::PartitionedAggregationNode::CodegenUpdateSlot().
Status Expr::GetCodegendComputeFnWrapper (RuntimeState * state, llvm::Function ** fn) protected inherited
Generates an IR compute function that calls the appropriate interpreted Get*Val() compute function. This is useful for builtins that can't be implemented with the UDF interface (e.g. functions that need short-circuiting) and that don't have custom codegen functions that use the IRBuilder. It doesn't provide any performance benefit over the interpreted path. TODO: this should be replaced with fancier xcompiling infrastructure
Definition at line 546 of file expr.cc.
References impala::LlvmCodeGen::CastPtrToLlvmPtr(), impala::LlvmCodeGen::context(), impala::CodegenAnyVal::CreateCall(), impala::Expr::CreateIrFunctionPrototype(), impala::LlvmCodeGen::FinalizeFunction(), impala::RuntimeState::GetCodegen(), impala::LlvmCodeGen::GetPtrType(), impala::Expr::GetStaticGetValWrapper(), impala::Expr::ir_compute_fn_, impala::Expr::LLVM_CLASS_NAME, impala::Status::OK, RETURN_IF_ERROR, and impala::Expr::type().
Referenced by impala::TupleIsNullPredicate::GetCodegendComputeFn(), and impala::HiveUdfCall::GetCodegendComputeFn().
AnyVal * Expr::GetConstVal (ExprContext * context) virtual inherited
If this expr is constant, evaluates the expr with no input row argument and returns the output. Returns NULL if the argument is not constant. The returned AnyVal* is owned by this expr. This should only be called after Open() has been called on this expr.
Definition at line 491 of file expr.cc.
References impala::Expr::constant_val_, impala::Expr::GetBigIntVal(), impala::Expr::GetBooleanVal(), impala::Expr::GetDecimalVal(), impala::Expr::GetDoubleVal(), impala::Expr::GetFloatVal(), impala::Expr::GetIntVal(), impala::Expr::GetSmallIntVal(), impala::Expr::GetStringVal(), impala::Expr::GetTimestampVal(), impala::Expr::GetTinyIntVal(), impala::Expr::IsConstant(), impala::ExprContext::opened_, impala::ColumnType::type, impala::Expr::type(), impala::Expr::type_, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_CHAR, impala::TYPE_DECIMAL, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::ScalarFnCall::Open().
DecimalVal Expr::GetDecimalVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 609 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetDecimalVal(), impala::Expr::GetDecimalVal(), and impala::ExprContext::GetValue().
DoubleVal Expr::GetDoubleVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 597 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetDoubleVal(), impala::Expr::GetDoubleVal(), and impala::ExprContext::GetValue().
FloatVal Expr::GetFloatVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 593 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetFloatVal(), impala::Expr::GetFloatVal(), and impala::ExprContext::GetValue().
IntVal Expr::GetIntVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 585 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetIntVal(), impala::Expr::GetIntVal(), and impala::ExprContext::GetValue().
int impala::Expr::GetNumChildren () const inline inherited
Definition at line 143 of file expr.h.
Referenced by impala::HiveUdfCall::Evaluate(), impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), and impala::HiveUdfCall::Prepare().
int Expr::GetSlotIds (std::vector< SlotId > * slot_ids) const virtual inherited
Returns the slots that are referenced by this expr tree in 'slot_ids'. Returns the number of slots added to the vector
Reimplemented in impala::SlotRef.
Definition at line 418 of file expr.cc.
References impala::Expr::children_.
SmallIntVal Expr::GetSmallIntVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 581 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetSmallIntVal(), impala::Expr::GetSmallIntVal(), and impala::ExprContext::GetValue().
Function * Expr::GetStaticGetValWrapper (ColumnType type, LlvmCodeGen * codegen) protected inherited
Returns the IR version of the static Get*Val() wrapper function corresponding to 'type'. This is used for calling interpreted Get*Val() functions from codegen'd functions (e.g. in ScalarFnCall() when codegen is disabled).
Definition at line 426 of file expr.cc.
References impala::ColumnType::DebugString(), impala::LlvmCodeGen::GetFunction(), impala::ColumnType::type, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_CHAR, impala::TYPE_DECIMAL, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
StringVal Expr::GetStringVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 601 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetStringVal(), impala::Expr::GetStringVal(), and impala::ExprContext::GetValue().
TimestampVal Expr::GetTimestampVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 605 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetTimestampVal(), impala::Expr::GetTimestampVal(), and impala::ExprContext::GetValue().
TinyIntVal Expr::GetTinyIntVal (ExprContext * context, TupleRow * row) virtual inherited
Reimplemented in impala::CoalesceExpr, impala::IfExpr, impala::NullIfExpr, impala::HiveUdfCall, impala::ScalarFnCall, impala::IsNullExpr, impala::Literal, impala::SlotRef, impala::CaseExpr, and impala::NullLiteral.
Definition at line 577 of file expr.cc.
References impala::Expr::DebugString().
Referenced by impala::Expr::GetConstVal(), impala::ExprContext::GetTinyIntVal(), impala::Expr::GetTinyIntVal(), and impala::ExprContext::GetValue().
void Expr::InitBuiltinsDummy () static inherited
The builtin functions are not called from anywhere in the code and the symbols are therefore not included in the binary. We call these functions by using dlsym. The compiler must think this function is callable to not strip these symbols.
Definition at line 470 of file expr.cc.
References impala::Operators::Add_IntVal_IntVal(), impala::CastFunctions::CastToBooleanVal(), impala::DecimalOperators::CastToDecimalVal(), InIterate(), impala::AggregateFunctions::InitNull(), impala::IsNullPredicate::IsNull(), impala::StringFunctions::Length(), impala::LikePredicate::Like(), impala::CompoundPredicate::Not(), impala::ConditionalFunctions::NullIfZero(), impala::UdfBuiltins::Pi(), impala::MathFunctions::Pi(), impala::UtilityFunctions::Pid(), impala::DecimalFunctions::Precision(), and impala::TimestampFunctions::Year().
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::BooleanVal & val, int num_args, const impala_udf::BooleanVal * args) static
Functions for every type.
Referenced by impala::Expr::InitBuiltinsDummy().
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::TinyIntVal & val, int num_args, const impala_udf::TinyIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::SmallIntVal & val, int num_args, const impala_udf::SmallIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::IntVal & val, int num_args, const impala_udf::IntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::BigIntVal & val, int num_args, const impala_udf::BigIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::FloatVal & val, int num_args, const impala_udf::FloatVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::DoubleVal & val, int num_args, const impala_udf::DoubleVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::StringVal & val, int num_args, const impala_udf::StringVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::TimestampVal & val, int num_args, const impala_udf::TimestampVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InIterate (impala_udf::FunctionContext * context, const impala_udf::DecimalVal & val, int num_args, const impala_udf::DecimalVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::BooleanVal & val, int num_args, const impala_udf::BooleanVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::TinyIntVal & val, int num_args, const impala_udf::TinyIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::SmallIntVal & val, int num_args, const impala_udf::SmallIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::IntVal & val, int num_args, const impala_udf::IntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::BigIntVal & val, int num_args, const impala_udf::BigIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::FloatVal & val, int num_args, const impala_udf::FloatVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::DoubleVal & val, int num_args, const impala_udf::DoubleVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::StringVal & val, int num_args, const impala_udf::StringVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::TimestampVal & val, int num_args, const impala_udf::TimestampVal * args) static
static impala_udf::BooleanVal impala::InPredicate::InSetLookup (impala_udf::FunctionContext * context, const impala_udf::DecimalVal & val, int num_args, const impala_udf::DecimalVal * args) static
bool impala::Expr::is_slotref () const inline inherited
Definition at line 146 of file expr.h.
bool Expr::IsConstant () const virtual inherited
Returns true if GetValue(NULL) can be called on this expr and always returns the same result (e.g., exprs that don't contain slotrefs). The default implementation returns true if all children are constant.
Reimplemented in impala::ScalarFnCall, impala::TupleIsNullPredicate, and impala::SlotRef.
Definition at line 411 of file expr.cc.
References impala::Expr::children_.
Referenced by impala::Expr::GetConstVal(), and impala::ScalarFnCall::IsConstant().
template<typename T > template BooleanVal impala::InPredicate::Iterate< IntVal > (const FunctionContext::TypeDesc * type, const T & val, int num_args, const T * args) static private
Iterates through each vararg looking for val. 'type' is the type of 'val' and 'args'.
Definition at line 116 of file in-predicate-ir.cc.
References impala_udf::BooleanVal::null().
Referenced by impala::InPredicateBenchmark::TestIterate().
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::BooleanVal & val, int num_args, const impala_udf::BooleanVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::TinyIntVal & val, int num_args, const impala_udf::TinyIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::SmallIntVal & val, int num_args, const impala_udf::SmallIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::IntVal & val, int num_args, const impala_udf::IntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::BigIntVal & val, int num_args, const impala_udf::BigIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::FloatVal & val, int num_args, const impala_udf::FloatVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::DoubleVal & val, int num_args, const impala_udf::DoubleVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::StringVal & val, int num_args, const impala_udf::StringVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::TimestampVal & val, int num_args, const impala_udf::TimestampVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInIterate (impala_udf::FunctionContext * context, const impala_udf::DecimalVal & val, int num_args, const impala_udf::DecimalVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::BooleanVal & val, int num_args, const impala_udf::BooleanVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::TinyIntVal & val, int num_args, const impala_udf::TinyIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::SmallIntVal & val, int num_args, const impala_udf::SmallIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::IntVal & val, int num_args, const impala_udf::IntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::BigIntVal & val, int num_args, const impala_udf::BigIntVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::FloatVal & val, int num_args, const impala_udf::FloatVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::DoubleVal & val, int num_args, const impala_udf::DoubleVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::StringVal & val, int num_args, const impala_udf::StringVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::TimestampVal & val, int num_args, const impala_udf::TimestampVal * args) static
static impala_udf::BooleanVal impala::InPredicate::NotInSetLookup (impala_udf::FunctionContext * context, const impala_udf::DecimalVal & val, int num_args, const impala_udf::DecimalVal * args) static
static Status impala::Expr::Open (const std::vector< ExprContext * > & ctxs, RuntimeState * state) static inherited
Convenience function for opening multiple expr trees.
Referenced by impala::ExprContext::Clone(), impala::HashJoinNode::ConstructBuildSide(), impala::PartitionedHashJoinNode::ConstructBuildSide(), impala::UnionNode::Open(), impala::SortExecExprs::Open(), impala::ExprContext::Open(), impala::CaseExpr::Open(), impala::AggregationNode::Open(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::DataStreamSender::Open(), impala::ExecNode::Open(), impala::PartitionedAggregationNode::Open(), impala::AggFnEvaluator::Open(), impala::HdfsScanNode::Open(), impala::HdfsTableSink::Open(), impala::Expr::Open(), impala::HdfsPartitionDescriptor::OpenExprs(), impala::OldHashTableTest::SetUp(), impala::HashTableTest::SetUp(), and impala::ImpalaServer::QueryExecState::WaitInternal().
Status Expr::Open (RuntimeState * state, ExprContext * context, FunctionContext::FunctionStateScope scope = FunctionContext::FRAGMENT_LOCAL) protected virtual inherited
Initializes 'context' for execution. If scope if FRAGMENT_LOCAL, both fragment- and thread-local state should be initialized. Otherwise, if scope is THREAD_LOCAL, only thread-local state should be initialized. Subclasses overriding this function should call Expr::Open() to recursively call Open() on the expr tree.
Reimplemented in impala::HiveUdfCall, impala::ScalarFnCall, and impala::CaseExpr.
Definition at line 366 of file expr.cc.
References impala::Expr::children_, impala::Status::OK, impala::Expr::Open(), and RETURN_IF_ERROR.
int impala::Expr::output_scale () const inline inherited
Get the number of digits after the decimal that should be displayed for this value. Returns -1 if no scale has been specified (currently the scale is only set for doubles set by RoundUpTo). GetValue() must have already been called. TODO: is this still necessary?
Definition at line 139 of file expr.h.
static Status impala::Expr::Prepare (const std::vector< ExprContext * > & ctxs, RuntimeState * state, const RowDescriptor & row_desc, MemTracker * tracker) static inherited
Convenience function for preparing multiple expr trees. Allocations from 'ctxs' will be counted against 'tracker'.
Referenced by impala::TupleIsNullPredicate::Prepare(), impala::UnionNode::Prepare(), impala::SortExecExprs::Prepare(), impala::ExprContext::Prepare(), impala::CaseExpr::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::ScalarFnCall::Prepare(), impala::HiveUdfCall::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::DataStreamSender::Prepare(), impala::ExecNode::Prepare(), impala::AggFnEvaluator::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::Expr::Prepare(), impala::HdfsTableSink::PrepareExprs(), impala::HdfsPartitionDescriptor::PrepareExprs(), impala::HashTableTest::SetUp(), and impala::OldHashTableTest::SetUp().
Status Expr::Prepare (RuntimeState * state, const RowDescriptor & row_desc, ExprContext * context) protected virtual inherited
Initializes this expr instance for execution. This does not include initializing state in the ExprContext; 'context' should only be used to register a FunctionContext via RegisterFunctionContext(). Any IR functions must be generated here. Subclasses overriding this function should call Expr::Prepare() to recursively call Prepare() on the expr tree.
Reimplemented in impala::HiveUdfCall, impala::ScalarFnCall, impala::CaseExpr, impala::TupleIsNullPredicate, and impala::SlotRef.
Definition at line 350 of file expr.cc.
References impala::Expr::children_, impala::INVALID_TYPE, impala::Status::OK, impala::Expr::Prepare(), RETURN_IF_ERROR, impala::ColumnType::type, and impala::Expr::type_.
FunctionContext * Expr::RegisterFunctionContext (ExprContext * ctx, RuntimeState * state, int varargs_buffer_size = 0) protected inherited
Helper function that calls ctx->Register(), sets context_index_, and returns the registered FunctionContext.
Definition at line 80 of file expr.cc.
References impala::AnyValUtil::ColumnTypeToTypeDesc(), impala::ExprContext::fn_context(), and impala::ExprContext::Register().
Referenced by impala::CaseExpr::Prepare(), and impala::HiveUdfCall::Prepare().
template<typename T , typename SetType > BooleanVal impala::InPredicate::SetLookup (SetLookupState< SetType > * state, const T & v) static private
Looks up v in state->val_set.
Definition at line 105 of file in-predicate-ir.cc.
References impala::InPredicate::SetLookupState< SetType >::contains_null, impala_udf::BooleanVal::null(), impala::InPredicate::SetLookupState< SetType >::type, and impala::InPredicate::SetLookupState< SetType >::val_set.
Referenced by impala::InPredicateBenchmark::TestSetLookup().
template<typename SetType > void impala::InPredicate::SetLookupClose (FunctionContext * ctx, FunctionContext::FunctionStateScope scope) static private
Definition at line 77 of file in-predicate-ir.cc.
References impala_udf::FunctionContext::FRAGMENT_LOCAL, and impala_udf::FunctionContext::GetFunctionState().
static void impala::InPredicate::SetLookupClose_bigint (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_boolean (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_decimal (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_double (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_float (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_int (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_smallint (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_string (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_timestamp (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupClose_tinyint (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
template<typename T , typename SetType > void impala::InPredicate::SetLookupPrepare (FunctionContext * ctx, FunctionContext::FunctionStateScope scope) static private
Initializes an SetLookupState in ctx.
Definition at line 57 of file in-predicate-ir.cc.
References impala::InPredicate::SetLookupState< SetType >::contains_null, impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetArgType(), impala_udf::FunctionContext::GetConstantArg(), impala_udf::FunctionContext::GetNumArgs(), impala_udf::FunctionContext::IsArgConstant(), impala_udf::FunctionContext::SetFunctionState(), impala::InPredicate::SetLookupState< SetType >::type, and impala::InPredicate::SetLookupState< SetType >::val_set.
static void impala::InPredicate::SetLookupPrepare_bigint (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_boolean (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_decimal (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_double (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_float (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_int (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_smallint (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_string (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_timestamp (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
static void impala::InPredicate::SetLookupPrepare_tinyint (impala_udf::FunctionContext * ctx, impala_udf::FunctionContext::FunctionStateScope scope) static
template<typename T , typename SetType , bool not_in, InPredicate::Strategy strategy> BooleanVal impala::InPredicate::TemplatedIn (FunctionContext * ctx, const T & val, int num_args, const T * args)
Definition at line 86 of file in-predicate-ir.cc.
References impala_udf::FunctionContext::FRAGMENT_LOCAL, impala_udf::FunctionContext::GetArgType(), impala_udf::FunctionContext::GetFunctionState(), impala_udf::AnyVal::is_null, impala_udf::BooleanVal::null(), and impala_udf::BooleanVal::val.
template<typename T , typename SetType , bool not_in, Strategy strategy> static impala_udf::BooleanVal impala::InPredicate::TemplatedIn (impala_udf::FunctionContext * context, const T & val, int num_args, const T * args) inline static private
The templated function that provides the implementation for all the In() and NotIn() functions.
const ColumnType& impala::Expr::type () const inline inherited
Definition at line 145 of file expr.h.
Referenced by impala::CaseExpr::AnyValEq(), impala::HdfsParquetTableWriter::BoolColumnWriter::BoolColumnWriter(), impala::AggregationNode::CodegenUpdateSlot(), impala::PartitionedAggregationNode::CodegenUpdateSlot(), impala::HdfsParquetTableWriter::ColumnWriter< T >::ColumnWriter(), impala::Expr::CreateIrFunctionPrototype(), impala::Literal::DebugString(), impala::HiveUdfCall::Evaluate(), impala::ScalarFnCall::EvaluateChildren(), impala::CaseExpr::GetChildVal(), impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::Expr::GetCodegendComputeFnWrapper(), impala::Expr::GetConstVal(), impala::Literal::GetDecimalVal(), impala::ScalarFnCall::GetUdf(), impala::Literal::Literal(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), impala::HiveUdfCall::Prepare(), and impala::DataStreamSender::Send().
Friends And Related Function Documentation
friend class InPredicateBenchmark friend
Definition at line 266 of file in-predicate.h.
Member Data Documentation
LibCache::LibCacheEntry* impala::Expr::cache_entry_ protected inherited
Cache entry for the library implementing this function.
Definition at line 281 of file expr.h.
Referenced by impala::Expr::Close(), impala::ScalarFnCall::GetFunction(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::Prepare(), and impala::Expr::~Expr().
std::vector<Expr*> impala::Expr::children_ protected inherited
Definition at line 290 of file expr.h.
Referenced by impala::Expr::Close(), impala::Expr::DebugString(), impala::ScalarFnCall::EvaluateChildren(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::Expr::GetSlotIds(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::InterpretEval(), impala::Expr::IsConstant(), impala::CaseExpr::Open(), impala::ScalarFnCall::Open(), impala::Expr::Open(), impala::SlotRef::Prepare(), impala::TupleIsNullPredicate::Prepare(), impala::ScalarFnCall::Prepare(), and impala::Expr::Prepare().
boost::scoped_ptr<AnyVal> impala::Expr::constant_val_ protected inherited
If this expr is constant, this will store and cache the value generated by GetConstVal().
Definition at line 303 of file expr.h.
Referenced by impala::Expr::GetConstVal().
int impala::Expr::context_index_ protected inherited
Index to pass to ExprContext::fn_context() to retrieve this expr's FunctionContext. Set in RegisterFunctionContext(). -1 if this expr does not need a FunctionContext and doesn't call RegisterFunctionContext().
Definition at line 296 of file expr.h.
Referenced by impala::CaseExpr::Close(), impala::ScalarFnCall::Close(), impala::HiveUdfCall::Close(), impala::HiveUdfCall::Evaluate(), impala::ScalarFnCall::EvaluateChildren(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::ScalarFnCall::InterpretEval(), impala::CaseExpr::Open(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), and impala::ScalarFnCall::Prepare().
TFunction impala::Expr::fn_ protected inherited
Function description.
Definition at line 284 of file expr.h.
Referenced by impala::ScalarFnCall::DebugString(), impala::HiveUdfCall::DebugString(), impala::HiveUdfCall::Evaluate(), impala::Expr::Expr(), impala::ScalarFnCall::GetFunction(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::IsConstant(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), impala::HiveUdfCall::Prepare(), and impala::ScalarFnCall::ScalarFnCall().
llvm::Function* impala::Expr::ir_compute_fn_ protected inherited
Cached codegened compute function. Exprs should set this in GetCodegendComputeFn().
Definition at line 299 of file expr.h.
Referenced by impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
const bool impala::Expr::is_slotref_ protected inherited
recognize if this node is a slotref in order to speed up GetValue()
Definition at line 287 of file expr.h.
const char * Expr::LLVM_CLASS_NAME = "class.impala::Expr" static inherited
Definition at line 232 of file expr.h.
Referenced by impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
int impala::Expr::output_scale_ protected inherited
Definition at line 291 of file expr.h.
Referenced by impala::ExprContext::GetValue(), and impala::ScalarFnCall::Open().
const ColumnType impala::Expr::type_ protected inherited
analysis is done, types are fixed at this point
Definition at line 289 of file expr.h.
Referenced by impala::Literal::DebugString(), impala::Expr::DebugString(), impala::SlotRef::GetBigIntVal(), impala::Literal::GetBigIntVal(), impala::ScalarFnCall::GetBigIntVal(), impala::HiveUdfCall::GetBigIntVal(), impala::SlotRef::GetBooleanVal(), impala::Literal::GetBooleanVal(), impala::HiveUdfCall::GetBooleanVal(), impala::ScalarFnCall::GetBooleanVal(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::Expr::GetConstVal(), impala::SlotRef::GetDecimalVal(), impala::Literal::GetDecimalVal(), impala::ScalarFnCall::GetDecimalVal(), impala::HiveUdfCall::GetDecimalVal(), impala::SlotRef::GetDoubleVal(), impala::Literal::GetDoubleVal(), impala::ScalarFnCall::GetDoubleVal(), impala::HiveUdfCall::GetDoubleVal(), impala::SlotRef::GetFloatVal(), impala::Literal::GetFloatVal(), impala::ScalarFnCall::GetFloatVal(), impala::HiveUdfCall::GetFloatVal(), impala::SlotRef::GetIntVal(), impala::Literal::GetIntVal(), impala::ScalarFnCall::GetIntVal(), impala::HiveUdfCall::GetIntVal(), impala::SlotRef::GetSmallIntVal(), impala::Literal::GetSmallIntVal(), impala::ScalarFnCall::GetSmallIntVal(), impala::HiveUdfCall::GetSmallIntVal(), impala::SlotRef::GetStringVal(), impala::Literal::GetStringVal(), impala::HiveUdfCall::GetStringVal(), impala::ScalarFnCall::GetStringVal(), impala::SlotRef::GetTimestampVal(), impala::ScalarFnCall::GetTimestampVal(), impala::HiveUdfCall::GetTimestampVal(), impala::SlotRef::GetTinyIntVal(), impala::Literal::GetTinyIntVal(), impala::HiveUdfCall::GetTinyIntVal(), impala::ScalarFnCall::GetTinyIntVal(), impala::ExprContext::GetValue(), impala::Literal::Literal(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), and impala::Expr::Prepare().
The documentation for this class was generated from the following files:
be/src/exprs/in-predicate.h
be/src/exprs/in-predicate-ir.cc