Impala: TestServer Class Reference
TestServer Class Reference
Public Member Functions
TestServer ()
virtual ~TestServer ()
virtual void Send (ThriftDataResult &result, const ThriftDataParams &params)
void Server (ThriftServer *server)
Detailed Description
Definition at line 68 of file network-perf-benchmark.cc.
Constructor & Destructor Documentation
TestServer::TestServer () inline
Definition at line 70 of file network-perf-benchmark.cc.
virtual TestServer::~TestServer () inline virtual
Definition at line 73 of file network-perf-benchmark.cc.
Member Function Documentation
virtual void TestServer::Send (ThriftDataResult & result, const ThriftDataParams & params) inline virtual
Definition at line 76 of file network-perf-benchmark.cc.
void TestServer::Server (ThriftServer * server) inline
Definition at line 80 of file network-perf-benchmark.cc.
References impala::ThriftServer::Join(), and impala::ThriftServer::Start().
Referenced by main().
The documentation for this class was generated from the following file:
be/src/util/network-perf-benchmark.cc