Impala: com.cloudera.impala.analysis.AlterTableSetTblProperties Class Reference
com.cloudera.impala.analysis.AlterTableSetTblProperties Class Reference
Public Member Functions
AlterTableSetTblProperties (TableName tableName, PartitionSpec partitionSpec, TTablePropertyType targetProperty, HashMap< String, String > tblProperties)
HashMap< String, String > getTblProperties ()
TAlterTableParams toThrift ()
PartitionSpec getPartitionSpec ()
void analyze (Analyzer analyzer) throws AnalysisException
String getTbl ()
String getDb ()
String toSql ()
void setIsExplain ()
boolean isExplain ()
Protected Member Functions
Table getTargetTable ()
Protected Attributes
final PartitionSpec partitionSpec_
final TableName tableName_
Table table_
boolean isExplain_ = false
Private Attributes
final TTablePropertyType targetProperty_
final HashMap< String, String > tblProperties_
Detailed Description
Represents an ALTER TABLE SET [PARTITION ('k1'='a', 'k2'='b'...)] TBLPROPERTIES|SERDEPROPERTIES ('p1'='v1', ...) statement.
Definition at line 29 of file AlterTableSetTblProperties.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AlterTableSetTblProperties.AlterTableSetTblProperties (TableName tableName, PartitionSpec partitionSpec, TTablePropertyType targetProperty, HashMap< String, String > tblProperties) inline
Definition at line 33 of file AlterTableSetTblProperties.java.
References com.cloudera.impala.analysis.AlterTableSetTblProperties.targetProperty_, and com.cloudera.impala.analysis.AlterTableSetTblProperties.tblProperties_.
Member Function Documentation
void com.cloudera.impala.analysis.AlterTableSetStmt.analyze (Analyzer analyzer) throws AnalysisException inline inherited
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 37 of file AlterTableSetStmt.java.
References com.cloudera.impala.authorization.Privilege.ALTER, com.cloudera.impala.analysis.AlterTableStmt.getTargetTable(), and com.cloudera.impala.analysis.AlterTableSetStmt.partitionSpec_.
String com.cloudera.impala.analysis.AlterTableStmt.getDb () inline inherited
Can only be called after analysis, returns the parent database name of the target table for this ALTER TABLE statement.
Definition at line 47 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
PartitionSpec com.cloudera.impala.analysis.AlterTableSetStmt.getPartitionSpec () inline inherited
Definition at line 34 of file AlterTableSetStmt.java.
References com.cloudera.impala.analysis.AlterTableSetStmt.partitionSpec_.
Referenced by com.cloudera.impala.analysis.AlterTableSetLocationStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetFileFormatStmt.toThrift(), com.cloudera.impala.analysis.AlterTableSetCachedStmt.toThrift(), and com.cloudera.impala.analysis.AlterTableSetLocationStmt.toThrift().
Table com.cloudera.impala.analysis.AlterTableStmt.getTargetTable () inline protected inherited
Can only be called after analysis, returns the Table object of the target of this ALTER TABLE statement.
Definition at line 55 of file AlterTableStmt.java.
References com.cloudera.impala.analysis.AlterTableStmt.table_.
Referenced by com.cloudera.impala.analysis.AlterTableSetStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetCachedStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetLocationStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddReplaceColsStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getDb().
String com.cloudera.impala.analysis.AlterTableStmt.getTbl () inline inherited
Definition at line 41 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableDropColStmt.analyze(), com.cloudera.impala.analysis.AlterTableChangeColStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.toSql(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.toSql(), and com.cloudera.impala.analysis.AlterTableStmt.toThrift().
HashMap<String, String> com.cloudera.impala.analysis.AlterTableSetTblProperties.getTblProperties () inline
Definition at line 43 of file AlterTableSetTblProperties.java.
References com.cloudera.impala.analysis.AlterTableSetTblProperties.tblProperties_.
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
String com.cloudera.impala.analysis.StatementBase.toSql () inline inherited
Print SQL syntax corresponding to this node.
See Also
com.cloudera.impala.parser.ParseNode::toSql()
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 41 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.CreateUdaStmt.analyze(), and com.cloudera.impala.analysis.QueryStmt.createSortInfo().
TAlterTableParams com.cloudera.impala.analysis.AlterTableSetTblProperties.toThrift () inline
Definition at line 46 of file AlterTableSetTblProperties.java.
References com.cloudera.impala.analysis.AlterTableSetStmt.partitionSpec_, com.cloudera.impala.analysis.AlterTableSetTblProperties.targetProperty_, and com.cloudera.impala.analysis.AlterTableSetTblProperties.tblProperties_.
Member Data Documentation
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
final PartitionSpec com.cloudera.impala.analysis.AlterTableSetStmt.partitionSpec_ protected inherited
Definition at line 26 of file AlterTableSetStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableSetStmt.AlterTableSetStmt(), com.cloudera.impala.analysis.AlterTableSetStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetStmt.getPartitionSpec(), and com.cloudera.impala.analysis.AlterTableSetTblProperties.toThrift().
Table com.cloudera.impala.analysis.AlterTableStmt.table_ protected inherited
Definition at line 33 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze(), and com.cloudera.impala.analysis.AlterTableStmt.getTargetTable().
final TableName com.cloudera.impala.analysis.AlterTableStmt.tableName_ protected inherited
Definition at line 30 of file AlterTableStmt.java.
Referenced by com.cloudera.impala.analysis.AlterTableStmt.AlterTableStmt(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), and com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze().
final TTablePropertyType com.cloudera.impala.analysis.AlterTableSetTblProperties.targetProperty_ private
Definition at line 30 of file AlterTableSetTblProperties.java.
Referenced by com.cloudera.impala.analysis.AlterTableSetTblProperties.AlterTableSetTblProperties(), and com.cloudera.impala.analysis.AlterTableSetTblProperties.toThrift().
final HashMap<String, String> com.cloudera.impala.analysis.AlterTableSetTblProperties.tblProperties_ private
Definition at line 31 of file AlterTableSetTblProperties.java.
Referenced by com.cloudera.impala.analysis.AlterTableSetTblProperties.AlterTableSetTblProperties(), com.cloudera.impala.analysis.AlterTableSetTblProperties.getTblProperties(), and com.cloudera.impala.analysis.AlterTableSetTblProperties.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AlterTableSetTblProperties.java