Impala: impala::ImpalaServer::ScopedSessionState Class Reference
impala::ImpalaServer::ScopedSessionState Class Reference
Public Member Functions
ScopedSessionState (ImpalaServer *impala)
Status WithSession (const TUniqueId &session_id, boost::shared_ptr< SessionState > *session=NULL)
~ScopedSessionState ()
Decrements the reference count so the session can be expired correctly.
Private Attributes
boost::shared_ptr< SessionState > session_
Reference-counted pointer to the session state object.
ImpalaServer * impala_
Saved so that we can access ImpalaServer methods to get / return session state.
Detailed Description
Class that allows users of SessionState to mark a session as in-use, and therefore immune to expiration. The marking is done in WithSession() and undone in the destructor, so this class can be used to 'check-out' a session for the duration of a scope.
Definition at line 842 of file impala-server.h.
Constructor & Destructor Documentation
impala::ImpalaServer::ScopedSessionState::ScopedSessionState (ImpalaServer * impala) inline
Definition at line 844 of file impala-server.h.
impala::ImpalaServer::ScopedSessionState::~ScopedSessionState () inline
Decrements the reference count so the session can be expired correctly.
Definition at line 858 of file impala-server.h.
References impala_, impala::ImpalaServer::MarkSessionInactive(), and session_.
Member Function Documentation
Status impala::ImpalaServer::ScopedSessionState::WithSession (const TUniqueId & session_id, boost::shared_ptr< SessionState > * session = NULL) inline
Marks a session as in-use, and saves it so that it can be unmarked when this object goes out of scope. Returns OK unless there is an error in GetSessionState. Must only be called once per ScopedSessionState.
Definition at line 849 of file impala-server.h.
References impala::ImpalaServer::GetSessionState(), impala_, impala::Status::OK, RETURN_IF_ERROR, and session_.
Referenced by impala::ImpalaServer::Cancel(), impala::ImpalaServer::CancelOperation(), impala::ImpalaServer::close(), impala::ImpalaServer::CloseInsert(), impala::ImpalaServer::CloseOperation(), impala::ImpalaServer::dump_config(), impala::ImpalaServer::echo(), impala::ImpalaServer::executeAndWait(), impala::ImpalaServer::ExecuteMetadataOp(), impala::ImpalaServer::ExecuteStatement(), impala::ImpalaServer::explain(), impala::ImpalaServer::fetch(), impala::ImpalaServer::get_default_configuration(), impala::ImpalaServer::get_log(), impala::ImpalaServer::get_results_metadata(), impala::ImpalaServer::get_state(), impala::ImpalaServer::GetExecSummary(), impala::ImpalaServer::GetInfo(), impala::ImpalaServer::GetLog(), impala::ImpalaServer::GetResultSetMetadata(), impala::ImpalaServer::GetRuntimeProfile(), impala::ImpalaServer::PingImpalaService(), and impala::ImpalaServer::query().
Member Data Documentation
ImpalaServer* impala::ImpalaServer::ScopedSessionState::impala_ private
Saved so that we can access ImpalaServer methods to get / return session state.
Definition at line 869 of file impala-server.h.
Referenced by WithSession(), and ~ScopedSessionState().
boost::shared_ptr<SessionState> impala::ImpalaServer::ScopedSessionState::session_ private
Reference-counted pointer to the session state object.
Definition at line 866 of file impala-server.h.
Referenced by WithSession(), and ~ScopedSessionState().
The documentation for this class was generated from the following file:
be/src/service/impala-server.h