Impala: com.cloudera.impala.planner.AnalyticEvalNode Class Reference
com.cloudera.impala.planner.AnalyticEvalNode Class Reference
Public Member Functions
AnalyticEvalNode (PlanNodeId id, PlanNode input, List< TupleId > stmtTupleIds, List< Expr > analyticFnCalls, List< Expr > partitionExprs, List< OrderByElement > orderByElements, AnalyticWindow analyticWindow, TupleDescriptor logicalTupleDesc, TupleDescriptor intermediateTupleDesc, TupleDescriptor outputTupleDesc, ExprSubstitutionMap logicalToPhysicalSmap, Expr partitionByEq, Expr orderByEq, TupleDescriptor bufferedTupleDesc)
boolean isBlockingNode ()
List< Expr > getPartitionExprs ()
List< OrderByElement > getOrderByElements ()
void init (Analyzer analyzer) throws InternalException
void computeCosts (TQueryOptions queryOptions)
PlanNodeId getId ()
void setId (PlanNodeId id)
long getLimit ()
boolean hasLimit ()
long getPerHostMemCost ()
long getCardinality ()
int getNumNodes ()
float getAvgRowSize ()
void setFragment (PlanFragment fragment)
PlanFragment getFragment ()
List< Expr > getConjuncts ()
ExprSubstitutionMap getOutputSmap ()
void setOutputSmap (ExprSubstitutionMap smap)
Set< ExprId > getAssignedConjuncts ()
void setAssignedConjuncts (Set< ExprId > conjuncts)
void setLimit (long limit)
void unsetLimit ()
ArrayList< TupleId > getTupleIds ()
ArrayList< TupleId > getTblRefIds ()
void setTblRefIds (ArrayList< TupleId > ids)
Set< TupleId > getNullableTupleIds ()
void addConjuncts (List< Expr > conjuncts)
void transferConjuncts (PlanNode recipient)
String getExplainString ()
TPlan treeToThrift ()
long getInputCardinality ()
Static Public Member Functions
static long addCardinalities (long a, long b)
static long multiplyCardinalities (long a, long b)
Protected Member Functions
void computeStats (Analyzer analyzer)
String debugString ()
void toThrift (TPlanNode msg)
String getNodeExplainString (String prefix, String detailPrefix, TExplainLevel detailLevel)
final String getExplainString (String rootPrefix, String prefix, TExplainLevel detailLevel)
String getExplainString (List<?extends Expr > exprs)
void setDisplayName (String s)
final String getDisplayLabel ()
String getDisplayLabelDetail ()
String getOffsetExplainString (String prefix)
void assignConjuncts (Analyzer analyzer)
ExprSubstitutionMap getCombinedChildSmap ()
void createDefaultSmap (Analyzer analyzer)
long capAtLimit (long cardinality)
void markSlotsMaterialized (Analyzer analyzer, List< Expr > exprs)
void computeMemLayout (Analyzer analyzer)
double computeSelectivity ()
boolean hasValidStats ()
Protected Attributes
String displayName_
PlanNodeId id_
long limit_
ArrayList< TupleId > tupleIds_
ArrayList< TupleId > tblRefIds_
Set< TupleId > nullableTupleIds_ = Sets.newHashSet()
List< Expr > conjuncts_ = Lists.newArrayList()
PlanFragment fragment_
ExprSubstitutionMap outputSmap_
Set< ExprId > assignedConjuncts_
long cardinality_
int numNodes_
float avgRowSize_
long perHostMemCost_ = -1
Static Protected Attributes
static final int DEFAULT_BATCH_SIZE = 1024
Private Attributes
final List< TupleId > stmtTupleIds_
List< Expr > analyticFnCalls_
final List< Expr > partitionExprs_
List< Expr > substitutedPartitionExprs_
List< OrderByElement > orderByElements_
final AnalyticWindow analyticWindow_
final TupleDescriptor logicalTupleDesc_
final TupleDescriptor intermediateTupleDesc_
final TupleDescriptor outputTupleDesc_
final ExprSubstitutionMap logicalToPhysicalSmap_
final Expr partitionByEq_
final Expr orderByEq_
final TupleDescriptor bufferedTupleDesc_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(AnalyticEvalNode.class)
Detailed Description
Computation of analytic exprs.
Definition at line 43 of file AnalyticEvalNode.java.
Constructor & Destructor Documentation
com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode (PlanNodeId id, PlanNode input, List< TupleId > stmtTupleIds, List< Expr > analyticFnCalls, List< Expr > partitionExprs, List< OrderByElement > orderByElements, AnalyticWindow analyticWindow, TupleDescriptor logicalTupleDesc, TupleDescriptor intermediateTupleDesc, TupleDescriptor outputTupleDesc, ExprSubstitutionMap logicalToPhysicalSmap, Expr partitionByEq, Expr orderByEq, TupleDescriptor bufferedTupleDesc) inline
Definition at line 78 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.AnalyticEvalNode.analyticFnCalls_, com.cloudera.impala.planner.AnalyticEvalNode.analyticWindow_, com.cloudera.impala.planner.AnalyticEvalNode.bufferedTupleDesc_, com.cloudera.impala.planner.PlanNode.getTupleIds(), com.cloudera.impala.planner.AnalyticEvalNode.intermediateTupleDesc_, com.cloudera.impala.planner.AnalyticEvalNode.logicalToPhysicalSmap_, com.cloudera.impala.planner.AnalyticEvalNode.logicalTupleDesc_, com.cloudera.impala.planner.AnalyticEvalNode.orderByElements_, com.cloudera.impala.planner.AnalyticEvalNode.orderByEq_, com.cloudera.impala.planner.AnalyticEvalNode.outputTupleDesc_, com.cloudera.impala.planner.AnalyticEvalNode.partitionByEq_, com.cloudera.impala.planner.AnalyticEvalNode.partitionExprs_, and com.cloudera.impala.planner.AnalyticEvalNode.stmtTupleIds_.
Member Function Documentation
static long com.cloudera.impala.planner.PlanNode.addCardinalities (long a, long b) inline static inherited
Computes and returns the sum of two cardinalities. If an overflow occurs, the maximum Long value is returned (Long.MAX_VALUE).
Definition at line 528 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), and com.cloudera.impala.planner.PlanNode.getInputCardinality().
void com.cloudera.impala.planner.PlanNode.addConjuncts (List< Expr > conjuncts) inline inherited
Definition at line 209 of file PlanNode.java.
void com.cloudera.impala.planner.PlanNode.assignConjuncts (Analyzer analyzer) inline protected inherited
Assign remaining unassigned conjuncts.
Definition at line 401 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.init().
long com.cloudera.impala.planner.PlanNode.capAtLimit (long cardinality) inline protected inherited
Definition at line 450 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.hasLimit(), and com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.SortNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), and com.cloudera.impala.planner.HdfsScanNode.computeStats().
void com.cloudera.impala.planner.AnalyticEvalNode.computeCosts (TQueryOptions queryOptions) inline
Definition at line 244 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.PlanNode.fragment_, and com.cloudera.impala.planner.PlanNode.perHostMemCost_.
void com.cloudera.impala.planner.PlanNode.computeMemLayout (Analyzer analyzer) inline protected inherited
Call computeMemLayout() for all materialized tuples.
Definition at line 475 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tupleIds_.
Referenced by com.cloudera.impala.planner.EmptySetNode.init(), com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), and com.cloudera.impala.planner.UnionNode.init().
double com.cloudera.impala.planner.PlanNode.computeSelectivity () inline protected inherited
Compute the product of the selectivies of all conjuncts.
Definition at line 484 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
Referenced by com.cloudera.impala.planner.SelectNode.computeStats(), com.cloudera.impala.planner.CrossJoinNode.computeStats(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), and com.cloudera.impala.planner.HdfsScanNode.computeStats().
void com.cloudera.impala.planner.AnalyticEvalNode.computeStats (Analyzer analyzer) inline protected
Definition at line 138 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.init().
void com.cloudera.impala.planner.PlanNode.createDefaultSmap (Analyzer analyzer) inline protected inherited
Sets outputSmap_ to compose(existing smap, combined child smap). Also substitutes conjuncts_ using the combined child smap.
Definition at line 425 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_, com.cloudera.impala.planner.PlanNode.getCombinedChildSmap(), and com.cloudera.impala.planner.PlanNode.outputSmap_.
Referenced by com.cloudera.impala.planner.SelectNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.init().
String com.cloudera.impala.planner.AnalyticEvalNode.debugString () inline protected
Definition at line 144 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.AnalyticEvalNode.analyticFnCalls_, com.cloudera.impala.planner.AnalyticEvalNode.analyticWindow_, com.cloudera.impala.analysis.Expr.debugString(), com.cloudera.impala.analysis.TupleDescriptor.getId(), com.cloudera.impala.planner.AnalyticEvalNode.intermediateTupleDesc_, com.cloudera.impala.planner.AnalyticEvalNode.orderByElements_, com.cloudera.impala.planner.AnalyticEvalNode.orderByEq_, com.cloudera.impala.planner.AnalyticEvalNode.outputTupleDesc_, com.cloudera.impala.planner.AnalyticEvalNode.partitionByEq_, com.cloudera.impala.planner.AnalyticEvalNode.partitionExprs_, and com.cloudera.impala.planner.AnalyticEvalNode.substitutedPartitionExprs_.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.init().
Set<ExprId> com.cloudera.impala.planner.PlanNode.getAssignedConjuncts () inline inherited
Definition at line 180 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.assignedConjuncts_.
float com.cloudera.impala.planner.PlanNode.getAvgRowSize () inline inherited
Definition at line 174 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), and com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan().
long com.cloudera.impala.planner.PlanNode.getCardinality () inline inherited
Definition at line 172 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan(), and com.cloudera.impala.planner.SingleNodePlanner.createJoinPlan().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.getCombinedChildSmap () inline protected inherited
Returns an smap that combines the childrens' smaps.
Definition at line 410 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.HashJoinNode.init().
List<Expr> com.cloudera.impala.planner.PlanNode.getConjuncts () inline inherited
Definition at line 177 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
Referenced by com.cloudera.impala.planner.ScanNode.getInputCardinality().
final String com.cloudera.impala.planner.PlanNode.getDisplayLabel () inline protected inherited
Definition at line 225 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.displayName_.
Referenced by com.cloudera.impala.planner.ExchangeNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
String com.cloudera.impala.planner.PlanNode.getDisplayLabelDetail () inline protected inherited
Subclasses can override to provide a node specific detail string that is displayed to the user. e.g. scan can return the table name.
Definition at line 234 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
String com.cloudera.impala.planner.PlanNode.getExplainString () inline inherited
Definition at line 219 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.getDisplayLabelDetail(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), and com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString().
final String com.cloudera.impala.planner.PlanNode.getExplainString (String rootPrefix, String prefix, TExplainLevel detailLevel) inline protected inherited
Generate the explain plan tree. The plan will be in the form of:
root | |-—child 3 | limit:1 | |-—child 2 | limit:2 | child 1
The root node header line will be prefixed by rootPrefix and the remaining plan output will be prefixed by prefix.
Definition at line 252 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.avgRowSize_, com.cloudera.impala.planner.PlanNode.cardinality_, com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getNodeExplainString(), com.cloudera.impala.planner.PlanNode.getOffsetExplainString(), com.cloudera.impala.planner.PlanNode.limit_, com.cloudera.impala.planner.PlanNode.numNodes_, com.cloudera.impala.planner.PlanNode.perHostMemCost_, and com.cloudera.impala.planner.PlanNode.tupleIds_.
String com.cloudera.impala.planner.PlanNode.getExplainString (List<?extends Expr > exprs) inline protected inherited
Definition at line 506 of file PlanNode.java.
PlanFragment com.cloudera.impala.planner.PlanNode.getFragment () inline inherited
Definition at line 176 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.fragment_.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), and com.cloudera.impala.planner.PipelinedPlanNodeSet.computePlanNodeSets().
PlanNodeId com.cloudera.impala.planner.PlanNode.getId () inline inherited
Definition at line 164 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.id_.
Referenced by com.cloudera.impala.planner.DataStreamSink.getExplainString(), com.cloudera.impala.planner.AggregationNode.init(), and com.cloudera.impala.planner.DataStreamSink.toThrift().
long com.cloudera.impala.planner.PlanNode.getInputCardinality () inline inherited
The input cardinality is the sum of output cardinalities of its children. For scan nodes the input cardinality is the expected number of rows scanned.
Definition at line 570 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.addCardinalities().
long com.cloudera.impala.planner.PlanNode.getLimit () inline inherited
Definition at line 169 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.ScanNode.getInputCardinality().
String com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString (String prefix, String detailPrefix, TExplainLevel detailLevel) inline protected
Definition at line 195 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.AnalyticEvalNode.analyticFnCalls_, com.cloudera.impala.planner.AnalyticEvalNode.analyticWindow_, com.cloudera.impala.planner.PlanNode.conjuncts_, com.cloudera.impala.planner.PlanNode.getDisplayLabel(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.orderByElements_, and com.cloudera.impala.planner.AnalyticEvalNode.partitionExprs_.
Set<TupleId> com.cloudera.impala.planner.PlanNode.getNullableTupleIds () inline inherited
Definition at line 204 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.nullableTupleIds_.
int com.cloudera.impala.planner.PlanNode.getNumNodes () inline inherited
Definition at line 173 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.numNodes_.
Referenced by com.cloudera.impala.planner.PipelinedPlanNodeSet.computeResourceEstimates(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), and com.cloudera.impala.planner.DataSourceScanNode.computeStats().
String com.cloudera.impala.planner.PlanNode.getOffsetExplainString (String prefix) inline protected inherited
Return the offset_ details, if applicable. This is available separately from 'getNodeExplainString' because we want to output 'limit: ...' (which can be printed from PlanNode) before 'offset: ...', which is only printed from SortNodes right now.
Definition at line 336 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getExplainString().
List<OrderByElement> com.cloudera.impala.planner.AnalyticEvalNode.getOrderByElements () inline
Definition at line 108 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.AnalyticEvalNode.orderByElements_.
Referenced by com.cloudera.impala.planner.DistributedPlanner.createAnalyticFragment().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.getOutputSmap () inline inherited
Definition at line 178 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.outputSmap_.
List<Expr> com.cloudera.impala.planner.AnalyticEvalNode.getPartitionExprs () inline
Definition at line 107 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.AnalyticEvalNode.partitionExprs_.
Referenced by com.cloudera.impala.planner.DistributedPlanner.createAnalyticFragment().
long com.cloudera.impala.planner.PlanNode.getPerHostMemCost () inline inherited
Definition at line 171 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.perHostMemCost_.
Referenced by com.cloudera.impala.planner.PipelinedPlanNodeSet.computeResourceEstimates().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.getTblRefIds () inline inherited
Definition at line 201 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tblRefIds_.
Referenced by com.cloudera.impala.analysis.Analyzer.canEvalPredicate().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.getTupleIds () inline inherited
Definition at line 196 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tupleIds_.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.SingleNodePlanner.createInlineViewPlan(), com.cloudera.impala.planner.AnalyticPlanner.createSortInfo(), and com.cloudera.impala.planner.SelectNode.SelectNode().
boolean com.cloudera.impala.planner.PlanNode.hasLimit () inline inherited
Definition at line 170 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Referenced by com.cloudera.impala.planner.PlanNode.capAtLimit(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.ScanNode.getInputCardinality(), and com.cloudera.impala.planner.SortNode.getNodeExplainDetail().
boolean com.cloudera.impala.planner.PlanNode.hasValidStats () inline protected inherited
Returns true if stats-related variables are valid.
Definition at line 519 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.cardinality_, and com.cloudera.impala.planner.PlanNode.numNodes_.
Referenced by com.cloudera.impala.planner.SortNode.computeCosts(), and com.cloudera.impala.planner.HashJoinNode.computeStats().
void com.cloudera.impala.planner.AnalyticEvalNode.init (Analyzer analyzer) throws InternalException inline
Definition at line 111 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.AnalyticEvalNode.analyticFnCalls_, com.cloudera.impala.planner.PlanNode.computeMemLayout(), com.cloudera.impala.planner.AnalyticEvalNode.computeStats(), com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.AnalyticEvalNode.debugString(), com.cloudera.impala.planner.PlanNode.getCombinedChildSmap(), com.cloudera.impala.planner.AnalyticEvalNode.logicalToPhysicalSmap_, com.cloudera.impala.planner.AnalyticEvalNode.orderByElements_, com.cloudera.impala.planner.PlanNode.outputSmap_, com.cloudera.impala.planner.AnalyticEvalNode.partitionExprs_, and com.cloudera.impala.planner.AnalyticEvalNode.substitutedPartitionExprs_.
boolean com.cloudera.impala.planner.AnalyticEvalNode.isBlockingNode () inline
Definition at line 106 of file AnalyticEvalNode.java.
void com.cloudera.impala.planner.PlanNode.markSlotsMaterialized (Analyzer analyzer, List< Expr > exprs) inline protected inherited
Marks all slots referenced in exprs as materialized.
Definition at line 464 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.init().
static long com.cloudera.impala.planner.PlanNode.multiplyCardinalities (long a, long b) inline static inherited
Computes and returns the product of two cardinalities. If an overflow occurs, the maximum Long value is returned (Long.MAX_VALUE).
Definition at line 541 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeStats(), and com.cloudera.impala.planner.HashJoinNode.getJoinCardinality().
void com.cloudera.impala.planner.PlanNode.setAssignedConjuncts (Set< ExprId > conjuncts) inline inherited
Definition at line 181 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.assignedConjuncts_.
void com.cloudera.impala.planner.PlanNode.setDisplayName (String s) inline protected inherited
Definition at line 223 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.displayName_.
void com.cloudera.impala.planner.PlanNode.setFragment (PlanFragment fragment) inline inherited
Definition at line 175 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.fragment_.
void com.cloudera.impala.planner.PlanNode.setId (PlanNodeId id) inline inherited
Definition at line 165 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.id_.
void com.cloudera.impala.planner.PlanNode.setLimit (long limit) inline inherited
Set the limit_ to the given limit_ only if the limit_ hasn't been set, or the new limit_ is lower.
Parameters
limit_
Definition at line 190 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
void com.cloudera.impala.planner.PlanNode.setOutputSmap (ExprSubstitutionMap smap) inline inherited
Definition at line 179 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.outputSmap_.
void com.cloudera.impala.planner.PlanNode.setTblRefIds (ArrayList< TupleId > ids) inline inherited
Definition at line 202 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.tblRefIds_.
void com.cloudera.impala.planner.AnalyticEvalNode.toThrift (TPlanNode msg) inline protected
Definition at line 166 of file AnalyticEvalNode.java.
References com.cloudera.impala.planner.AnalyticEvalNode.analyticFnCalls_, com.cloudera.impala.planner.AnalyticEvalNode.analyticWindow_, com.cloudera.impala.planner.AnalyticEvalNode.bufferedTupleDesc_, com.cloudera.impala.planner.AnalyticEvalNode.orderByElements_, com.cloudera.impala.planner.AnalyticEvalNode.orderByEq_, com.cloudera.impala.planner.AnalyticEvalNode.partitionByEq_, and com.cloudera.impala.planner.AnalyticEvalNode.substitutedPartitionExprs_.
void com.cloudera.impala.planner.PlanNode.transferConjuncts (PlanNode recipient) inline inherited
Definition at line 214 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.conjuncts_.
TPlan com.cloudera.impala.planner.PlanNode.treeToThrift () inline inherited
Definition at line 341 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
void com.cloudera.impala.planner.PlanNode.unsetLimit () inline inherited
Definition at line 194 of file PlanNode.java.
References com.cloudera.impala.planner.PlanNode.limit_.
Member Data Documentation
List<Expr> com.cloudera.impala.planner.AnalyticEvalNode.analyticFnCalls_ private
Definition at line 51 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.AnalyticEvalNode.debugString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.AnalyticEvalNode.toThrift().
final AnalyticWindow com.cloudera.impala.planner.AnalyticEvalNode.analyticWindow_ private
Definition at line 59 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.AnalyticEvalNode.debugString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), and com.cloudera.impala.planner.AnalyticEvalNode.toThrift().
Set<ExprId> com.cloudera.impala.planner.PlanNode.assignedConjuncts_ protected inherited
Definition at line 99 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getAssignedConjuncts(), com.cloudera.impala.planner.CrossJoinNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.HashJoinNode.init(), and com.cloudera.impala.planner.PlanNode.setAssignedConjuncts().
float com.cloudera.impala.planner.PlanNode.avgRowSize_ protected inherited
Definition at line 110 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getAvgRowSize(), and com.cloudera.impala.planner.PlanNode.getExplainString().
final TupleDescriptor com.cloudera.impala.planner.AnalyticEvalNode.bufferedTupleDesc_ private
Definition at line 76 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), and com.cloudera.impala.planner.AnalyticEvalNode.toThrift().
long com.cloudera.impala.planner.PlanNode.cardinality_ protected inherited
Definition at line 103 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.SelectNode.computeStats(), com.cloudera.impala.planner.CrossJoinNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.SortNode.computeStats(), com.cloudera.impala.planner.AnalyticEvalNode.computeStats(), com.cloudera.impala.planner.AggregationNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), com.cloudera.impala.planner.HashJoinNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getCardinality(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.HashJoinNode.getJoinCardinality(), com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality(), com.cloudera.impala.planner.PlanNode.hasValidStats(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
List<Expr> com.cloudera.impala.planner.PlanNode.conjuncts_ = Lists.newArrayList() protected inherited
Definition at line 86 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.computeSelectivity(), com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.HBaseScanNode.createHBaseFilters(), com.cloudera.impala.planner.PlanNode.debugString(), com.cloudera.impala.planner.PlanNode.getConjuncts(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.AggregationNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.HashJoinNode.getNodeExplainString(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.planner.SelectNode.init(), com.cloudera.impala.planner.DataSourceScanNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.HBaseScanNode.init(), com.cloudera.impala.planner.HdfsScanNode.init(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.transferConjuncts(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
final int com.cloudera.impala.planner.PlanNode.DEFAULT_BATCH_SIZE = 1024 static protected inherited
Definition at line 63 of file PlanNode.java.
String com.cloudera.impala.planner.PlanNode.displayName_ protected inherited
Definition at line 66 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getDisplayLabel(), com.cloudera.impala.planner.EmptySetNode.getNodeExplainString(), com.cloudera.impala.planner.SelectNode.getNodeExplainString(), com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString(), com.cloudera.impala.planner.SortNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.getNodeExplainString(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.setDisplayName(), and com.cloudera.impala.planner.ExchangeNode.setMergeInfo().
PlanFragment com.cloudera.impala.planner.PlanNode.fragment_ protected inherited
Definition at line 90 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.ExchangeNode.getDisplayLabelDetail(), com.cloudera.impala.planner.PlanNode.getFragment(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.planner.UnionNode.reorderOperands(), and com.cloudera.impala.planner.PlanNode.setFragment().
PlanNodeId com.cloudera.impala.planner.PlanNode.id_ protected inherited
Definition at line 69 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getId(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.setId().
final TupleDescriptor com.cloudera.impala.planner.AnalyticEvalNode.intermediateTupleDesc_ private
Definition at line 65 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), and com.cloudera.impala.planner.AnalyticEvalNode.debugString().
long com.cloudera.impala.planner.PlanNode.limit_ protected inherited
Definition at line 71 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.PlanNode.capAtLimit(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.PlanNode.debugString(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getLimit(), com.cloudera.impala.planner.SortNode.getNodeExplainDetail(), com.cloudera.impala.planner.PlanNode.hasLimit(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.PlanNode.setLimit(), com.cloudera.impala.planner.PlanNode.treeToThriftHelper(), and com.cloudera.impala.planner.PlanNode.unsetLimit().
final Logger com.cloudera.impala.planner.AnalyticEvalNode.LOG = LoggerFactory.getLogger(AnalyticEvalNode.class) static private
Definition at line 44 of file AnalyticEvalNode.java.
final ExprSubstitutionMap com.cloudera.impala.planner.AnalyticEvalNode.logicalToPhysicalSmap_ private
Definition at line 70 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), and com.cloudera.impala.planner.AnalyticEvalNode.init().
final TupleDescriptor com.cloudera.impala.planner.AnalyticEvalNode.logicalTupleDesc_ private
Definition at line 62 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode().
Set<TupleId> com.cloudera.impala.planner.PlanNode.nullableTupleIds_ = Sets.newHashSet() protected inherited
Definition at line 84 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.PlanNode.getNullableTupleIds(), and com.cloudera.impala.planner.PlanNode.PlanNode().
int com.cloudera.impala.planner.PlanNode.numNodes_ protected inherited
Definition at line 107 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.HdfsScanNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.ExchangeNode.computeStats(), com.cloudera.impala.planner.UnionNode.computeStats(), com.cloudera.impala.planner.HBaseScanNode.computeStats(), com.cloudera.impala.planner.DataSourceScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.HdfsScanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getNumNodes(), com.cloudera.impala.planner.PlanNode.hasValidStats(), and com.cloudera.impala.planner.PlanNode.PlanNode().
List<OrderByElement> com.cloudera.impala.planner.AnalyticEvalNode.orderByElements_ private
Definition at line 58 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.AnalyticEvalNode.debugString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getOrderByElements(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.AnalyticEvalNode.toThrift().
final Expr com.cloudera.impala.planner.AnalyticEvalNode.orderByEq_ private
Definition at line 75 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.AnalyticEvalNode.debugString(), and com.cloudera.impala.planner.AnalyticEvalNode.toThrift().
ExprSubstitutionMap com.cloudera.impala.planner.PlanNode.outputSmap_ protected inherited
Definition at line 93 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.createDefaultSmap(), com.cloudera.impala.planner.PlanNode.getOutputSmap(), com.cloudera.impala.planner.SortNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.PlanNode.setOutputSmap().
final TupleDescriptor com.cloudera.impala.planner.AnalyticEvalNode.outputTupleDesc_ private
Definition at line 66 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), and com.cloudera.impala.planner.AnalyticEvalNode.debugString().
final Expr com.cloudera.impala.planner.AnalyticEvalNode.partitionByEq_ private
Definition at line 74 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.AnalyticEvalNode.debugString(), and com.cloudera.impala.planner.AnalyticEvalNode.toThrift().
final List<Expr> com.cloudera.impala.planner.AnalyticEvalNode.partitionExprs_ private
Definition at line 54 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode(), com.cloudera.impala.planner.AnalyticEvalNode.debugString(), com.cloudera.impala.planner.AnalyticEvalNode.getNodeExplainString(), com.cloudera.impala.planner.AnalyticEvalNode.getPartitionExprs(), and com.cloudera.impala.planner.AnalyticEvalNode.init().
long com.cloudera.impala.planner.PlanNode.perHostMemCost_ = -1 protected inherited
Definition at line 114 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.computeCosts(), com.cloudera.impala.planner.SortNode.computeCosts(), com.cloudera.impala.planner.AnalyticEvalNode.computeCosts(), com.cloudera.impala.planner.AggregationNode.computeCosts(), com.cloudera.impala.planner.DataSourceScanNode.computeCosts(), com.cloudera.impala.planner.HashJoinNode.computeCosts(), com.cloudera.impala.planner.HBaseScanNode.computeCosts(), com.cloudera.impala.planner.PlanNode.computeCosts(), com.cloudera.impala.planner.HdfsScanNode.computeCosts(), com.cloudera.impala.planner.EmptySetNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getPerHostMemCost(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
final List<TupleId> com.cloudera.impala.planner.AnalyticEvalNode.stmtTupleIds_ private
Definition at line 49 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.AnalyticEvalNode().
List<Expr> com.cloudera.impala.planner.AnalyticEvalNode.substitutedPartitionExprs_ private
Definition at line 57 of file AnalyticEvalNode.java.
Referenced by com.cloudera.impala.planner.AnalyticEvalNode.debugString(), com.cloudera.impala.planner.AnalyticEvalNode.init(), and com.cloudera.impala.planner.AnalyticEvalNode.toThrift().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.tblRefIds_ protected inherited
Definition at line 79 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.PlanNode.getTblRefIds(), com.cloudera.impala.planner.PlanNode.PlanNode(), and com.cloudera.impala.planner.PlanNode.setTblRefIds().
ArrayList<TupleId> com.cloudera.impala.planner.PlanNode.tupleIds_ protected inherited
Definition at line 74 of file PlanNode.java.
Referenced by com.cloudera.impala.planner.ExchangeNode.addChild(), com.cloudera.impala.planner.UnionNode.addChild(), com.cloudera.impala.planner.PlanNode.computeMemLayout(), com.cloudera.impala.planner.PlanNode.computeStats(), com.cloudera.impala.planner.PlanNode.getExplainString(), com.cloudera.impala.planner.PlanNode.getTupleIds(), com.cloudera.impala.planner.EmptySetNode.init(), com.cloudera.impala.planner.AggregationNode.init(), com.cloudera.impala.planner.PlanNode.PlanNode(), com.cloudera.impala.planner.HdfsScanNode.prunePartitions(), com.cloudera.impala.planner.ExchangeNode.toThrift(), and com.cloudera.impala.planner.PlanNode.treeToThriftHelper().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/planner/AnalyticEvalNode.java