Impala: com.cloudera.impala.catalog.RolePrivilege Class Reference
com.cloudera.impala.catalog.RolePrivilege Class Reference
Public Member Functions
TPrivilege toThrift ()
TCatalogObjectType getCatalogObjectType ()
String getName ()
int getRoleId ()
synchronized long getCatalogVersion ()
synchronized void setCatalogVersion (long newVersion)
boolean isLoaded ()
long getCreateTimeMs ()
TPrivilegeScope getScope ()
Static Public Member Functions
static RolePrivilege fromThrift (TPrivilege privilege)
static String buildRolePrivilegeName (TPrivilege privilege)
Private Member Functions
RolePrivilege (TPrivilege privilege)
Private Attributes
final TPrivilege privilege_
long catalogVersion_ = Catalog.INITIAL_CATALOG_VERSION
Static Private Attributes
static final Logger LOG = Logger.getLogger(AuthorizationPolicy.class)
static final Joiner AUTHORIZABLE_JOINER = Joiner.on("->")
static final Joiner KV_JOINER = Joiner.on("=")
Detailed Description
Represents a privilege that has been granted to a role in an authorization policy. This class is thread safe.
Definition at line 33 of file RolePrivilege.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.RolePrivilege.RolePrivilege (TPrivilege privilege) inline private
Definition at line 44 of file RolePrivilege.java.
References com.cloudera.impala.catalog.RolePrivilege.privilege_.
Referenced by com.cloudera.impala.catalog.RolePrivilege.fromThrift().
Member Function Documentation
static String com.cloudera.impala.catalog.RolePrivilege.buildRolePrivilegeName (TPrivilege privilege) inline static
Builds a privilege name for the given TPrivilege object. For simplicity, this name is generated in a format that can be sent to the Sentry client to perform authorization checks.
Definition at line 58 of file RolePrivilege.java.
References impala_udf.ALL.
static RolePrivilege com.cloudera.impala.catalog.RolePrivilege.fromThrift (TPrivilege privilege) inline static
Definition at line 49 of file RolePrivilege.java.
References com.cloudera.impala.catalog.RolePrivilege.RolePrivilege().
TCatalogObjectType com.cloudera.impala.catalog.RolePrivilege.getCatalogObjectType () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 106 of file RolePrivilege.java.
synchronized long com.cloudera.impala.catalog.RolePrivilege.getCatalogVersion () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 113 of file RolePrivilege.java.
References com.cloudera.impala.catalog.RolePrivilege.catalogVersion_.
Referenced by com.cloudera.impala.catalog.ImpaladCatalog.removePrivilege().
long com.cloudera.impala.catalog.RolePrivilege.getCreateTimeMs () inline
Definition at line 124 of file RolePrivilege.java.
References com.cloudera.impala.catalog.RolePrivilege.privilege_.
String com.cloudera.impala.catalog.RolePrivilege.getName () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 110 of file RolePrivilege.java.
int com.cloudera.impala.catalog.RolePrivilege.getRoleId () inline
Definition at line 111 of file RolePrivilege.java.
TPrivilegeScope com.cloudera.impala.catalog.RolePrivilege.getScope () inline
Definition at line 127 of file RolePrivilege.java.
boolean com.cloudera.impala.catalog.RolePrivilege.isLoaded () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 119 of file RolePrivilege.java.
synchronized void com.cloudera.impala.catalog.RolePrivilege.setCatalogVersion (long newVersion) inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 115 of file RolePrivilege.java.
References com.cloudera.impala.catalog.RolePrivilege.catalogVersion_.
TPrivilege com.cloudera.impala.catalog.RolePrivilege.toThrift () inline
Definition at line 48 of file RolePrivilege.java.
References com.cloudera.impala.catalog.RolePrivilege.privilege_.
Referenced by com.cloudera.impala.util.SentryProxy.revokeRolePrivilege().
Member Data Documentation
final Joiner com.cloudera.impala.catalog.RolePrivilege.AUTHORIZABLE_JOINER = Joiner.on("->") static private
Definition at line 38 of file RolePrivilege.java.
long com.cloudera.impala.catalog.RolePrivilege.catalogVersion_ = Catalog.INITIAL_CATALOG_VERSION private
Definition at line 42 of file RolePrivilege.java.
Referenced by com.cloudera.impala.catalog.RolePrivilege.getCatalogVersion(), and com.cloudera.impala.catalog.RolePrivilege.setCatalogVersion().
final Joiner com.cloudera.impala.catalog.RolePrivilege.KV_JOINER = Joiner.on("=") static private
Definition at line 39 of file RolePrivilege.java.
final Logger com.cloudera.impala.catalog.RolePrivilege.LOG = Logger.getLogger(AuthorizationPolicy.class) static private
Definition at line 34 of file RolePrivilege.java.
final TPrivilege com.cloudera.impala.catalog.RolePrivilege.privilege_ private
Definition at line 41 of file RolePrivilege.java.
Referenced by com.cloudera.impala.catalog.RolePrivilege.getCreateTimeMs(), com.cloudera.impala.catalog.RolePrivilege.RolePrivilege(), and com.cloudera.impala.catalog.RolePrivilege.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/RolePrivilege.java