Impala: com.cloudera.impala.catalog.HBaseColumn Class Reference
com.cloudera.impala.catalog.HBaseColumn Class Reference
Public Member Functions
HBaseColumn (String name, String columnFamily, String columnQualifier, boolean binaryEncoded, Type type, String comment, int position)
String getColumnFamily ()
String getColumnQualifier ()
boolean isBinaryEncoded ()
int compareTo (HBaseColumn o)
TColumn toThrift ()
String getComment ()
String getName ()
Type getType ()
int getPosition ()
void setPosition (int position)
ColumnStats getStats ()
boolean updateStats (ColumnStatisticsData statsData)
void updateStats (TColumnStats statsData)
String toString ()
Static Public Member Functions
static Column fromThrift (TColumn columnDesc)
Protected Attributes
final String name_
final Type type_
final String comment_
int position_
final ColumnStats stats_
Private Attributes
final String columnFamily_
final String columnQualifier_
final boolean binaryEncoded_
Detailed Description
Definition at line 23 of file HBaseColumn.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.HBaseColumn.HBaseColumn (String name, String columnFamily, String columnQualifier, boolean binaryEncoded, Type type, String comment, int position) inline
Definition at line 28 of file HBaseColumn.java.
References com.cloudera.impala.catalog.HBaseColumn.binaryEncoded_, com.cloudera.impala.catalog.HBaseColumn.columnFamily_, and com.cloudera.impala.catalog.HBaseColumn.columnQualifier_.
Member Function Documentation
int com.cloudera.impala.catalog.HBaseColumn.compareTo (HBaseColumn o) inline
Definition at line 43 of file HBaseColumn.java.
static Column com.cloudera.impala.catalog.Column.fromThrift (TColumn columnDesc) inline static inherited
Definition at line 79 of file Column.java.
References com.cloudera.impala.catalog.Column.Column(), com.cloudera.impala.catalog.Type.fromThrift(), and com.cloudera.impala.catalog.Column.getComment().
String com.cloudera.impala.catalog.HBaseColumn.getColumnFamily () inline
Definition at line 36 of file HBaseColumn.java.
References com.cloudera.impala.catalog.HBaseColumn.columnFamily_.
Referenced by com.cloudera.impala.catalog.CatalogTest.checkHBaseTableCols(), com.cloudera.impala.planner.HBaseScanNode.createHBaseFilters(), and com.cloudera.impala.catalog.HBaseTable.load().
String com.cloudera.impala.catalog.HBaseColumn.getColumnQualifier () inline
Definition at line 37 of file HBaseColumn.java.
References com.cloudera.impala.catalog.HBaseColumn.columnQualifier_.
Referenced by com.cloudera.impala.catalog.CatalogTest.checkHBaseTableCols(), and com.cloudera.impala.catalog.HBaseTable.getTHBaseTable().
String com.cloudera.impala.catalog.Column.getComment () inline inherited
Definition at line 52 of file Column.java.
References com.cloudera.impala.catalog.Column.comment_.
Referenced by com.cloudera.impala.analysis.ToSqlUtils.columnToSql(), com.cloudera.impala.catalog.Column.fromThrift(), and com.cloudera.impala.catalog.Table.loadFromThrift().
String com.cloudera.impala.catalog.Column.getName () inline inherited
Definition at line 53 of file Column.java.
References com.cloudera.impala.catalog.Column.name_.
Referenced by com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.analysis.ToSqlUtils.columnToSql(), com.cloudera.impala.service.MetadataOp.getColumns(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.Table.loadFromThrift(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
int com.cloudera.impala.catalog.Column.getPosition () inline inherited
Definition at line 55 of file Column.java.
References com.cloudera.impala.catalog.Column.position_.
Referenced by com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.service.MetadataOp.getColumns(), and com.cloudera.impala.analysis.InsertStmt.prepareExpressions().
ColumnStats com.cloudera.impala.catalog.Column.getStats () inline inherited
Definition at line 57 of file Column.java.
References com.cloudera.impala.catalog.Column.stats_.
Referenced by com.cloudera.impala.catalog.CatalogTest.assertStatsUnknown(), com.cloudera.impala.catalog.CatalogTest.testStats(), com.cloudera.impala.catalog.HBaseColumn.toThrift(), and com.cloudera.impala.catalog.Column.toThrift().
Type com.cloudera.impala.catalog.Column.getType () inline inherited
Definition at line 54 of file Column.java.
References com.cloudera.impala.catalog.Column.type_.
Referenced by com.cloudera.impala.analysis.ComputeStatsStmt.checkIncompleteAvroSchema(), com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.analysis.ToSqlUtils.columnToSql(), com.cloudera.impala.analysis.ComputeStatsStmt.getBaseColumnStatsQuerySelectList(), com.cloudera.impala.catalog.Table.loadAllColumnStats(), com.cloudera.impala.catalog.DataSourceTable.loadColumns(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
boolean com.cloudera.impala.catalog.HBaseColumn.isBinaryEncoded () inline
Definition at line 38 of file HBaseColumn.java.
References com.cloudera.impala.catalog.HBaseColumn.binaryEncoded_.
void com.cloudera.impala.catalog.Column.setPosition (int position) inline inherited
Definition at line 56 of file Column.java.
String com.cloudera.impala.catalog.Column.toString () inline inherited
Definition at line 70 of file Column.java.
References com.cloudera.impala.catalog.Column.comment_, com.cloudera.impala.catalog.Column.name_, com.cloudera.impala.catalog.Column.position_, com.cloudera.impala.catalog.Column.stats_, and com.cloudera.impala.catalog.Column.type_.
TColumn com.cloudera.impala.catalog.HBaseColumn.toThrift () inline
Definition at line 53 of file HBaseColumn.java.
References com.cloudera.impala.catalog.HBaseColumn.binaryEncoded_, com.cloudera.impala.catalog.HBaseColumn.columnFamily_, com.cloudera.impala.catalog.HBaseColumn.columnQualifier_, com.cloudera.impala.catalog.Column.comment_, com.cloudera.impala.catalog.Column.getStats(), com.cloudera.impala.catalog.Column.name_, com.cloudera.impala.catalog.Column.position_, com.cloudera.impala.catalog.Type.toThrift(), and com.cloudera.impala.catalog.Column.type_.
boolean com.cloudera.impala.catalog.Column.updateStats (ColumnStatisticsData statsData) inline inherited
Definition at line 59 of file Column.java.
References com.cloudera.impala.catalog.Column.name_, and com.cloudera.impala.catalog.Column.type_.
Referenced by com.cloudera.impala.catalog.Table.loadAllColumnStats().
void com.cloudera.impala.catalog.Column.updateStats (TColumnStats statsData) inline inherited
Definition at line 65 of file Column.java.
References com.cloudera.impala.catalog.Column.type_.
Member Data Documentation
final boolean com.cloudera.impala.catalog.HBaseColumn.binaryEncoded_ private
Definition at line 26 of file HBaseColumn.java.
Referenced by com.cloudera.impala.catalog.HBaseColumn.HBaseColumn(), com.cloudera.impala.catalog.HBaseColumn.isBinaryEncoded(), and com.cloudera.impala.catalog.HBaseColumn.toThrift().
final String com.cloudera.impala.catalog.HBaseColumn.columnFamily_ private
Definition at line 24 of file HBaseColumn.java.
Referenced by com.cloudera.impala.catalog.HBaseColumn.getColumnFamily(), com.cloudera.impala.catalog.HBaseColumn.HBaseColumn(), and com.cloudera.impala.catalog.HBaseColumn.toThrift().
final String com.cloudera.impala.catalog.HBaseColumn.columnQualifier_ private
Definition at line 25 of file HBaseColumn.java.
Referenced by com.cloudera.impala.catalog.HBaseColumn.getColumnQualifier(), com.cloudera.impala.catalog.HBaseColumn.HBaseColumn(), and com.cloudera.impala.catalog.HBaseColumn.toThrift().
final String com.cloudera.impala.catalog.Column.comment_ protected inherited
Definition at line 35 of file Column.java.
Referenced by com.cloudera.impala.catalog.Column.Column(), com.cloudera.impala.catalog.Column.getComment(), com.cloudera.impala.catalog.Column.toString(), com.cloudera.impala.catalog.HBaseColumn.toThrift(), and com.cloudera.impala.catalog.Column.toThrift().
final String com.cloudera.impala.catalog.Column.name_ protected inherited
Definition at line 33 of file Column.java.
Referenced by com.cloudera.impala.catalog.Column.Column(), com.cloudera.impala.catalog.Column.getName(), com.cloudera.impala.catalog.Column.toString(), com.cloudera.impala.catalog.HBaseColumn.toThrift(), com.cloudera.impala.catalog.Column.toThrift(), and com.cloudera.impala.catalog.Column.updateStats().
int com.cloudera.impala.catalog.Column.position_ protected inherited
Definition at line 36 of file Column.java.
Referenced by com.cloudera.impala.catalog.Column.Column(), com.cloudera.impala.catalog.Column.getPosition(), com.cloudera.impala.catalog.Column.toString(), com.cloudera.impala.catalog.HBaseColumn.toThrift(), and com.cloudera.impala.catalog.Column.toThrift().
final ColumnStats com.cloudera.impala.catalog.Column.stats_ protected inherited
Definition at line 38 of file Column.java.
Referenced by com.cloudera.impala.catalog.Column.Column(), com.cloudera.impala.catalog.Column.getStats(), and com.cloudera.impala.catalog.Column.toString().
final Type com.cloudera.impala.catalog.Column.type_ protected inherited
Definition at line 34 of file Column.java.
Referenced by com.cloudera.impala.catalog.Column.Column(), com.cloudera.impala.catalog.Column.getType(), com.cloudera.impala.catalog.Column.toString(), com.cloudera.impala.catalog.HBaseColumn.toThrift(), com.cloudera.impala.catalog.Column.toThrift(), and com.cloudera.impala.catalog.Column.updateStats().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HBaseColumn.java