Impala: impala::RowBatchListTest Class Reference
impala::RowBatchListTest Class Reference
Public Member Functions
RowBatchListTest ()
Protected Member Functions
virtual void SetUp ()
RowBatch * CreateRowBatch (int start, int end)
void ValidateMatch (TupleRow *row, int32_t expected)
void FullScan (RowBatchList *list, int start, int end)
Protected Attributes
MemTracker tracker_
ObjectPool pool_
RowDescriptor * desc_
Detailed Description
Definition at line 36 of file row-batch-list-test.cc.
Constructor & Destructor Documentation
impala::RowBatchListTest::RowBatchListTest () inline
Definition at line 38 of file row-batch-list-test.cc.
Member Function Documentation
RowBatch* impala::RowBatchListTest::CreateRowBatch (int start, int end) inline protected
Definition at line 54 of file row-batch-list-test.cc.
References impala::ObjectPool::Add(), impala::RowBatch::AddRow(), impala::MemPool::Allocate(), impala::RowBatch::CommitLastRow(), desc_, impala::RowBatch::GetRow(), gen_ir_descriptions::idx, pool_, impala::TupleRow::SetTuple(), tracker_, and impala::RowBatch::tuple_data_pool().
void impala::RowBatchListTest::FullScan (RowBatchList * list, int start, int end) inline protected
Definition at line 77 of file row-batch-list-test.cc.
References impala::RowBatchList::TupleRowIterator::AtEnd(), impala::RowBatchList::TupleRowIterator::GetRow(), impala::RowBatchList::Iterator(), impala::RowBatchList::TupleRowIterator::Next(), and ValidateMatch().
virtual void impala::RowBatchListTest::SetUp () inline protected virtual
Definition at line 45 of file row-batch-list-test.cc.
References impala::ObjectPool::Add(), impala::DescriptorTblBuilder::Build(), impala::DescriptorTblBuilder::DeclareTuple(), desc_, pool_, and impala::TYPE_INT.
void impala::RowBatchListTest::ValidateMatch (TupleRow * row, int32_t expected) inline protected
Definition at line 73 of file row-batch-list-test.cc.
References impala::TupleRow::GetTuple().
Referenced by FullScan().
Member Data Documentation
RowDescriptor* impala::RowBatchListTest::desc_ protected
Definition at line 43 of file row-batch-list-test.cc.
Referenced by CreateRowBatch(), and SetUp().
ObjectPool impala::RowBatchListTest::pool_ protected
Definition at line 42 of file row-batch-list-test.cc.
Referenced by CreateRowBatch(), and SetUp().
MemTracker impala::RowBatchListTest::tracker_ protected
Definition at line 41 of file row-batch-list-test.cc.
Referenced by CreateRowBatch().
The documentation for this class was generated from the following file:
be/src/exec/row-batch-list-test.cc