Impala: com.cloudera.impala.catalog.HdfsStorageDescriptor Class Reference
com.cloudera.impala.catalog.HdfsStorageDescriptor Class Reference
Classes
class InvalidStorageDescriptorException
Public Member Functions
void setFileFormat (HdfsFileFormat fileFormat)
HdfsStorageDescriptor (String tblName, HdfsFileFormat fileFormat, byte lineDelim, byte fieldDelim, byte collectionDelim, byte mapKeyDelim, byte escapeChar, byte quoteChar, int blockSize)
byte getLineDelim ()
byte getFieldDelim ()
byte getCollectionDelim ()
byte getMapKeyDelim ()
byte getEscapeChar ()
byte getQuoteChar ()
HdfsFileFormat getFileFormat ()
int getBlockSize ()
Static Public Member Functions
static Byte parseDelim (String delimVal)
static HdfsStorageDescriptor fromStorageDescriptor (String tblName, StorageDescriptor sd) throws InvalidStorageDescriptorException
Static Public Attributes
static final char DEFAULT_ESCAPE_CHAR = '\u0000'
Static Package Attributes
static final List< String > DELIMITER_KEYS
static final List< String > COMPATIBLE_SERDES
Static Private Member Functions
static Map< String, Byte > extractDelimiters (SerDeInfo serdeInfo) throws InvalidStorageDescriptorException
Private Attributes
HdfsFileFormat fileFormat_
final byte lineDelim_
final byte fieldDelim_
final byte collectionDelim_
final byte mapKeyDelim_
final byte escapeChar_
final byte quoteChar_
final int blockSize_
Static Private Attributes
static final char DEFAULT_LINE_DELIM = '\n'
static final char DEFAULT_FIELD_DELIM = '\u0001'
static final String BLOCK_SIZE = "blocksize"
static final String COMPRESSION = "compression"
static final Logger LOG = LoggerFactory.getLogger(HdfsStorageDescriptor.class)
Detailed Description
Represents the file format metadata for files stored in a table or partition.
Definition at line 33 of file HdfsStorageDescriptor.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.HdfsStorageDescriptor.HdfsStorageDescriptor (String tblName, HdfsFileFormat fileFormat, byte lineDelim, byte fieldDelim, byte collectionDelim, byte mapKeyDelim, byte escapeChar, byte quoteChar, int blockSize) inline
Definition at line 146 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_ESCAPE_CHAR.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.fromStorageDescriptor().
Member Function Documentation
static Map<String, Byte> com.cloudera.impala.catalog.HdfsStorageDescriptor.extractDelimiters (SerDeInfo serdeInfo) throws InvalidStorageDescriptorException inline static private
Returns a map from delimiter key to a single delimiter character, filling in defaults if explicit values are not found in the supplied serde descriptor.
Exceptions
InvalidStorageDescriptorException - if an invalid delimiter is found
Definition at line 85 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_ESCAPE_CHAR, com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_FIELD_DELIM, com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_LINE_DELIM, com.cloudera.impala.catalog.HdfsStorageDescriptor.DELIMITER_KEYS, and com.cloudera.impala.catalog.HdfsStorageDescriptor.parseDelim().
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.fromStorageDescriptor().
static HdfsStorageDescriptor com.cloudera.impala.catalog.HdfsStorageDescriptor.fromStorageDescriptor (String tblName, StorageDescriptor sd) throws InvalidStorageDescriptorException inline static
Constructs a new HdfsStorageDescriptor from a StorageDescriptor retrieved from the metastore.
Exceptions
InvalidStorageDescriptorException - if the storage descriptor has invalid delimiters, an unsupported SerDe, or an unknown file format.
Definition at line 195 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.BLOCK_SIZE, com.cloudera.impala.catalog.HdfsStorageDescriptor.COMPATIBLE_SERDES, com.cloudera.impala.catalog.HdfsStorageDescriptor.extractDelimiters(), com.cloudera.impala.catalog.HdfsFileFormat.fromJavaClassName(), and com.cloudera.impala.catalog.HdfsStorageDescriptor.HdfsStorageDescriptor().
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptorTest.testDelimiters(), and com.cloudera.impala.catalog.HdfsStorageDescriptorTest.testParquetFileFormat().
int com.cloudera.impala.catalog.HdfsStorageDescriptor.getBlockSize () inline
Definition at line 236 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.blockSize_.
byte com.cloudera.impala.catalog.HdfsStorageDescriptor.getCollectionDelim () inline
Definition at line 231 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.collectionDelim_.
Referenced by com.cloudera.impala.catalog.HdfsPartition.toThrift().
byte com.cloudera.impala.catalog.HdfsStorageDescriptor.getEscapeChar () inline
Definition at line 233 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.escapeChar_.
Referenced by com.cloudera.impala.catalog.CatalogTest.TestTableWithBadEscapeChar(), and com.cloudera.impala.catalog.HdfsPartition.toThrift().
byte com.cloudera.impala.catalog.HdfsStorageDescriptor.getFieldDelim () inline
Definition at line 230 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.fieldDelim_.
HdfsFileFormat com.cloudera.impala.catalog.HdfsStorageDescriptor.getFileFormat () inline
Definition at line 235 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.fileFormat_.
Referenced by com.cloudera.impala.catalog.HdfsTable.createPartition(), and com.cloudera.impala.catalog.HdfsPartition.toHmsPartition().
byte com.cloudera.impala.catalog.HdfsStorageDescriptor.getLineDelim () inline
Definition at line 229 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.lineDelim_.
Referenced by com.cloudera.impala.catalog.HdfsPartition.toThrift().
byte com.cloudera.impala.catalog.HdfsStorageDescriptor.getMapKeyDelim () inline
Definition at line 232 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.mapKeyDelim_.
byte com.cloudera.impala.catalog.HdfsStorageDescriptor.getQuoteChar () inline
Definition at line 234 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.quoteChar_.
static Byte com.cloudera.impala.catalog.HdfsStorageDescriptor.parseDelim (String delimVal) inline static
Parses a delimiter in a similar way as Hive, with some additional error checking. A delimiter must fit in a single byte and can be specified in the following formats, as far as I can tell (there isn't documentation):
A single ASCII or unicode character (ex. '|')
An escape character in octal format (ex. \001. Stored in the metastore as a unicode character:).
A signed decimal integer in the range [-128:127]. Used to support delimiters for ASCII character values between 128-255 (-2 maps to ASCII 254).
The delimiter is first parsed as a decimal number. If the parsing succeeds AND the resulting value fits in a signed byte, the byte value of the parsed int is returned. Otherwise, if the string has a single char, the byte value of this char is returned. If the delimiter is invalid, null will be returned.
Definition at line 134 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.analyzeRowFormatValue(), and com.cloudera.impala.catalog.HdfsStorageDescriptor.extractDelimiters().
void com.cloudera.impala.catalog.HdfsStorageDescriptor.setFileFormat (HdfsFileFormat fileFormat) inline
Definition at line 74 of file HdfsStorageDescriptor.java.
References com.cloudera.impala.catalog.HdfsStorageDescriptor.fileFormat_.
Member Data Documentation
final String com.cloudera.impala.catalog.HdfsStorageDescriptor.BLOCK_SIZE = "blocksize" static private
Definition at line 41 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.fromStorageDescriptor().
final int com.cloudera.impala.catalog.HdfsStorageDescriptor.blockSize_ private
Definition at line 72 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getBlockSize().
final byte com.cloudera.impala.catalog.HdfsStorageDescriptor.collectionDelim_ private
Definition at line 68 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getCollectionDelim().
final List<String> com.cloudera.impala.catalog.HdfsStorageDescriptor.COMPATIBLE_SERDES static package
Initial value:
= ImmutableList.of(
      "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe",
      "org.apache.hadoop.hive.serde2.avro.AvroSerDe",
      "org.apache.hadoop.hive.serde2.columnar.ColumnarSerDe",
      "parquet.hive.serde.ParquetHiveSerDe",
      "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe")
Definition at line 54 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.fromStorageDescriptor().
final String com.cloudera.impala.catalog.HdfsStorageDescriptor.COMPRESSION = "compression" static private
Definition at line 42 of file HdfsStorageDescriptor.java.
final char com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_ESCAPE_CHAR = '\u0000' static
Definition at line 38 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.extractDelimiters(), com.cloudera.impala.catalog.HdfsStorageDescriptor.HdfsStorageDescriptor(), and com.cloudera.impala.catalog.CatalogTest.TestTableWithBadEscapeChar().
final char com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_FIELD_DELIM = '\u0001' static private
Definition at line 36 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.extractDelimiters().
final char com.cloudera.impala.catalog.HdfsStorageDescriptor.DEFAULT_LINE_DELIM = '\n' static private
Definition at line 34 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.extractDelimiters().
final List<String> com.cloudera.impala.catalog.HdfsStorageDescriptor.DELIMITER_KEYS static package
Initial value:
= ImmutableList.of(
      serdeConstants.LINE_DELIM, serdeConstants.FIELD_DELIM,
      serdeConstants.COLLECTION_DELIM, serdeConstants.MAPKEY_DELIM,
      serdeConstants.ESCAPE_CHAR, serdeConstants.QUOTE_CHAR)
Definition at line 47 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptorTest.delimitersInCorrectOrder(), and com.cloudera.impala.catalog.HdfsStorageDescriptor.extractDelimiters().
final byte com.cloudera.impala.catalog.HdfsStorageDescriptor.escapeChar_ private
Definition at line 70 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getEscapeChar().
final byte com.cloudera.impala.catalog.HdfsStorageDescriptor.fieldDelim_ private
Definition at line 67 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getFieldDelim().
HdfsFileFormat com.cloudera.impala.catalog.HdfsStorageDescriptor.fileFormat_ private
Definition at line 65 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getFileFormat(), and com.cloudera.impala.catalog.HdfsStorageDescriptor.setFileFormat().
final byte com.cloudera.impala.catalog.HdfsStorageDescriptor.lineDelim_ private
Definition at line 66 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getLineDelim().
final Logger com.cloudera.impala.catalog.HdfsStorageDescriptor.LOG = LoggerFactory.getLogger(HdfsStorageDescriptor.class) static private
Definition at line 63 of file HdfsStorageDescriptor.java.
final byte com.cloudera.impala.catalog.HdfsStorageDescriptor.mapKeyDelim_ private
Definition at line 69 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getMapKeyDelim().
final byte com.cloudera.impala.catalog.HdfsStorageDescriptor.quoteChar_ private
Definition at line 71 of file HdfsStorageDescriptor.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.getQuoteChar().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HdfsStorageDescriptor.java