Impala: impala::HBaseTableScanner::ScanRange Class Reference
impala::HBaseTableScanner::ScanRange Class Reference
HBase scan range; "" means unbounded.
#include <hbase-table-scanner.h>
Public Member Functions
ScanRange ()
const std::string & start_key () const
const std::string & stop_key () const
void set_start_key (const std::string &key)
void set_stop_key (const std::string &key)
void DebugString (int indentation_level, std::stringstream *out)
Write debug string of this ScanRange into out.
Private Attributes
std::string start_key_
std::string stop_key_
Detailed Description
HBase scan range; "" means unbounded.
Definition at line 81 of file hbase-table-scanner.h.
Constructor & Destructor Documentation
impala::HBaseTableScanner::ScanRange::ScanRange () inline
Definition at line 83 of file hbase-table-scanner.h.
Member Function Documentation
void HBaseTableScanner::ScanRange::DebugString (int indentation_level, std::stringstream * out)
Write debug string of this ScanRange into out.
Definition at line 73 of file hbase-table-scanner.cc.
References start_key_, and stop_key_.
Referenced by impala::HBaseScanNode::DebugString().
void impala::HBaseTableScanner::ScanRange::set_start_key (const std::string & key) inline
Definition at line 90 of file hbase-table-scanner.h.
References start_key_.
Referenced by impala::HBaseScanNode::Prepare().
void impala::HBaseTableScanner::ScanRange::set_stop_key (const std::string & key) inline
Definition at line 91 of file hbase-table-scanner.h.
References stop_key_.
Referenced by impala::HBaseScanNode::Prepare().
const std::string& impala::HBaseTableScanner::ScanRange::start_key () const inline
Definition at line 88 of file hbase-table-scanner.h.
References start_key_.
Referenced by impala::HBaseTableScanner::InitScanRange().
const std::string& impala::HBaseTableScanner::ScanRange::stop_key () const inline
Definition at line 89 of file hbase-table-scanner.h.
References stop_key_.
Referenced by impala::HBaseTableScanner::HandleResultScannerTimeout(), and impala::HBaseTableScanner::InitScanRange().
Member Data Documentation
std::string impala::HBaseTableScanner::ScanRange::start_key_ private
Definition at line 97 of file hbase-table-scanner.h.
Referenced by DebugString(), set_start_key(), and start_key().
std::string impala::HBaseTableScanner::ScanRange::stop_key_ private
Definition at line 98 of file hbase-table-scanner.h.
Referenced by DebugString(), set_stop_key(), and stop_key().
The documentation for this class was generated from the following files:
be/src/exec/hbase-table-scanner.h
be/src/exec/hbase-table-scanner.cc