Impala: com.cloudera.impala.analysis.AnalysisContext.AnalysisResult Class Reference
com.cloudera.impala.analysis.AnalysisContext.AnalysisResult Class Reference
Public Member Functions
boolean isAlterTableStmt ()
boolean isAlterViewStmt ()
boolean isComputeStatsStmt ()
boolean isQueryStmt ()
boolean isInsertStmt ()
boolean isDropDbStmt ()
boolean isDropTableOrViewStmt ()
boolean isDropFunctionStmt ()
boolean isDropDataSrcStmt ()
boolean isDropStatsStmt ()
boolean isCreateTableLikeStmt ()
boolean isCreateViewStmt ()
boolean isCreateTableAsSelectStmt ()
boolean isCreateTableStmt ()
boolean isCreateDbStmt ()
boolean isCreateUdfStmt ()
boolean isCreateUdaStmt ()
boolean isCreateDataSrcStmt ()
boolean isLoadDataStmt ()
boolean isUseStmt ()
boolean isSetStmt ()
boolean isShowTablesStmt ()
boolean isShowDbsStmt ()
boolean isShowDataSrcsStmt ()
boolean isShowStatsStmt ()
boolean isShowFunctionsStmt ()
boolean isShowCreateTableStmt ()
boolean isShowFilesStmt ()
boolean isDescribeStmt ()
boolean isResetMetadataStmt ()
boolean isExplainStmt ()
boolean isShowRolesStmt ()
boolean isShowGrantRoleStmt ()
boolean isCreateDropRoleStmt ()
boolean isGrantRevokeRoleStmt ()
boolean isGrantRevokePrivStmt ()
boolean isCatalogOp ()
boolean isDmlStmt ()
AlterTableStmt getAlterTableStmt ()
AlterViewStmt getAlterViewStmt ()
ComputeStatsStmt getComputeStatsStmt ()
CreateTableLikeStmt getCreateTableLikeStmt ()
CreateViewStmt getCreateViewStmt ()
CreateTableAsSelectStmt getCreateTableAsSelectStmt ()
CreateTableStmt getCreateTableStmt ()
CreateTableStmt getTmpCreateTableStmt ()
CreateDbStmt getCreateDbStmt ()
CreateUdfStmt getCreateUdfStmt ()
CreateUdaStmt getCreateUdaStmt ()
DropDbStmt getDropDbStmt ()
DropTableOrViewStmt getDropTableOrViewStmt ()
DropFunctionStmt getDropFunctionStmt ()
LoadDataStmt getLoadDataStmt ()
QueryStmt getQueryStmt ()
InsertStmt getInsertStmt ()
UseStmt getUseStmt ()
SetStmt getSetStmt ()
ShowTablesStmt getShowTablesStmt ()
ShowDbsStmt getShowDbsStmt ()
ShowDataSrcsStmt getShowDataSrcsStmt ()
ShowStatsStmt getShowStatsStmt ()
ShowFunctionsStmt getShowFunctionsStmt ()
ShowFilesStmt getShowFilesStmt ()
DescribeStmt getDescribeStmt ()
ShowCreateTableStmt getShowCreateTableStmt ()
StatementBase getStmt ()
Analyzer getAnalyzer ()
Set< TAccessEvent > getAccessEvents ()
boolean requiresRewrite ()
String getJsonLineageGraph ()
Private Member Functions
boolean isDdlStmt ()
boolean isViewMetadataStmt ()
boolean isGrantRevokeStmt ()
Private Attributes
StatementBase stmt_
Analyzer analyzer_
CreateTableStmt tmpCreateTableStmt_
Detailed Description
Definition at line 50 of file AnalysisContext.java.
Member Function Documentation
Set<TAccessEvent> com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAccessEvents () inline
Definition at line 272 of file AnalysisContext.java.
AlterTableStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAlterTableStmt () inline
Definition at line 132 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterTableStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
AlterViewStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAlterViewStmt () inline
Definition at line 137 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterViewStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Analyzer com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAnalyzer () inline
Definition at line 271 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.analyzer_.
ComputeStatsStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getComputeStatsStmt () inline
Definition at line 142 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isComputeStatsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
CreateDbStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateDbStmt () inline
Definition at line 171 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDbStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
CreateTableAsSelectStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableAsSelectStmt () inline
Definition at line 157 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableAsSelectStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getInsertStmt().
CreateTableLikeStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableLikeStmt () inline
Definition at line 147 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableLikeStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
CreateTableStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableStmt () inline
Definition at line 162 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
CreateUdaStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateUdaStmt () inline
Definition at line 181 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdfStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
CreateUdfStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateUdfStmt () inline
Definition at line 176 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdfStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
CreateViewStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateViewStmt () inline
Definition at line 152 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateViewStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
DescribeStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDescribeStmt () inline
Definition at line 260 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDescribeStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
DropDbStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropDbStmt () inline
Definition at line 186 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropDbStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
DropFunctionStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropFunctionStmt () inline
Definition at line 196 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropFunctionStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
DropTableOrViewStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropTableOrViewStmt () inline
Definition at line 191 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropTableOrViewStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
InsertStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getInsertStmt () inline
Definition at line 211 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableAsSelectStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableAsSelectStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isInsertStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
String com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getJsonLineageGraph () inline
Definition at line 277 of file AnalysisContext.java.
LoadDataStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getLoadDataStmt () inline
Definition at line 201 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isLoadDataStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
QueryStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getQueryStmt () inline
Definition at line 206 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isQueryStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
SetStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getSetStmt () inline
Definition at line 225 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isSetStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
ShowCreateTableStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowCreateTableStmt () inline
Definition at line 265 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowCreateTableStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
ShowDataSrcsStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowDataSrcsStmt () inline
Definition at line 240 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDataSrcsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
ShowDbsStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowDbsStmt () inline
Definition at line 235 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDbsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
ShowFilesStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowFilesStmt () inline
Definition at line 255 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFilesStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
ShowFunctionsStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowFunctionsStmt () inline
Definition at line 250 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFunctionsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
ShowStatsStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowStatsStmt () inline
Definition at line 245 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowStatsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
ShowTablesStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowTablesStmt () inline
Definition at line 230 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowTablesStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
StatementBase com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getStmt () inline
Definition at line 270 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
CreateTableStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getTmpCreateTableStmt () inline
Definition at line 167 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.tmpCreateTableStmt_.
UseStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getUseStmt () inline
Definition at line 220 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isUseStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterTableStmt () inline
Definition at line 55 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAlterTableStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterViewStmt () inline
Definition at line 56 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAlterViewStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCatalogOp () inline
Definition at line 104 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isUseStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isComputeStatsStmt () inline
Definition at line 57 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getComputeStatsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDataSrcStmt () inline
Definition at line 78 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDbStmt () inline
Definition at line 75 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateDbStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDropRoleStmt () inline
Definition at line 96 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableAsSelectStmt () inline
Definition at line 71 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableAsSelectStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getInsertStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableLikeStmt () inline
Definition at line 67 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableLikeStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableStmt () inline
Definition at line 74 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdaStmt () inline
Definition at line 77 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdfStmt () inline
Definition at line 76 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateUdaStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateUdfStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateViewStmt () inline
Definition at line 70 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateViewStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt () inline private
Definition at line 108 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isComputeStatsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDataSrcStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDbStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDropRoleStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableAsSelectStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableLikeStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdaStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdfStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropDataSrcStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropDbStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropFunctionStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropStatsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropTableOrViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokeStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isResetMetadataStmt().
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCatalogOp().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDescribeStmt () inline
Definition at line 91 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDescribeStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDmlStmt () inline
Definition at line 128 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isInsertStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropDataSrcStmt () inline
Definition at line 65 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropDbStmt () inline
Definition at line 60 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropDbStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropFunctionStmt () inline
Definition at line 64 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropFunctionStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropStatsStmt () inline
Definition at line 66 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropTableOrViewStmt () inline
Definition at line 61 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropTableOrViewStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isExplainStmt () inline
Definition at line 93 of file AnalysisContext.java.
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokePrivStmt () inline
Definition at line 100 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokeStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokeRoleStmt () inline
Definition at line 97 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokeStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokeStmt () inline private
Definition at line 124 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokePrivStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokeRoleStmt().
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isInsertStmt () inline
Definition at line 59 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getInsertStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDmlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isLoadDataStmt () inline
Definition at line 79 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getLoadDataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isQueryStmt () inline
Definition at line 58 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getQueryStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isResetMetadataStmt () inline
Definition at line 92 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDdlStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isSetStmt () inline
Definition at line 81 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getSetStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowCreateTableStmt () inline
Definition at line 87 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowCreateTableStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDataSrcsStmt () inline
Definition at line 84 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowDataSrcsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDbsStmt () inline
Definition at line 83 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowDbsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFilesStmt () inline
Definition at line 90 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowFilesStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFunctionsStmt () inline
Definition at line 86 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowFunctionsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowGrantRoleStmt () inline
Definition at line 95 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowRolesStmt () inline
Definition at line 94 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowStatsStmt () inline
Definition at line 85 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowStatsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowTablesStmt () inline
Definition at line 82 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowTablesStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isUseStmt () inline
Definition at line 80 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getUseStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCatalogOp().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isViewMetadataStmt () inline private
Definition at line 118 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDescribeStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowCreateTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDataSrcsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDbsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFilesStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFunctionsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowGrantRoleStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowRolesStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowStatsStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowTablesStmt().
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCatalogOp().
boolean com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.requiresRewrite () inline
Definition at line 273 of file AnalysisContext.java.
References com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_.
Referenced by com.cloudera.impala.analysis.AnalysisContext.analyze().
Member Data Documentation
Analyzer com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.analyzer_ private
Definition at line 52 of file AnalysisContext.java.
Referenced by com.cloudera.impala.analysis.AnalysisContext.analyze(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAnalyzer().
StatementBase com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.stmt_ private
Definition at line 51 of file AnalysisContext.java.
Referenced by com.cloudera.impala.analysis.AnalysisContext.analyze(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAlterTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getAlterViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getComputeStatsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateDbStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableAsSelectStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableLikeStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateUdaStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateUdfStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getCreateViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDescribeStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropDbStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropFunctionStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getDropTableOrViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getInsertStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getLoadDataStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getQueryStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getSetStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowCreateTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowDataSrcsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowDbsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowFilesStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowFunctionsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowStatsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getShowTablesStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getUseStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isAlterViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isComputeStatsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDataSrcStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDbStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateDropRoleStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableAsSelectStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableLikeStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdaStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateUdfStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isCreateViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDescribeStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropDataSrcStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropDbStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropFunctionStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropStatsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isDropTableOrViewStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokePrivStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isGrantRevokeRoleStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isInsertStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isLoadDataStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isQueryStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isResetMetadataStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isSetStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowCreateTableStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDataSrcsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowDbsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFilesStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowFunctionsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowGrantRoleStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowRolesStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowStatsStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isShowTablesStmt(), com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.isUseStmt(), and com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.requiresRewrite().
CreateTableStmt com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.tmpCreateTableStmt_ private
Definition at line 53 of file AnalysisContext.java.
Referenced by com.cloudera.impala.analysis.AnalysisContext.AnalysisResult.getTmpCreateTableStmt().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AnalysisContext.java