Impala: impala::HdfsOp Class Reference
impala::HdfsOp Class Reference
#include <hdfs-bulk-ops.h>
Public Member Functions
HdfsOp (HdfsOpType op, const std::string &src, HdfsOperationSet *op_set)
HdfsOp (HdfsOpType op, const std::string &src, const std::string &dst, HdfsOperationSet *op_set)
HdfsOp (HdfsOpType op, const std::string &src, short permissions, HdfsOperationSet *op_set)
HdfsOp ()
Required for ThreadPool.
HdfsOpType op () const
const std::string & src () const
const std::string & dst () const
void Execute () const
Private Attributes
HdfsOpType op_
The kind of operation to execute.
std::string src_
First operand.
std::string dst_
Second string operand, ignored except for RENAME.
short permissions_
Permission operand, ignored except for CHMOD.
HdfsOperationSet * op_set_
Containing operation set, used to record errors and to signal completion.
Detailed Description
Container class that encapsulates a single HDFS operation. Used only internally by HdfsOperationSet, but visible because it parameterises HdfsOpThreadPool.
Definition at line 40 of file hdfs-bulk-ops.h.
Constructor & Destructor Documentation
HdfsOp::HdfsOp (HdfsOpType op, const std::string & src, HdfsOperationSet * op_set)
Definition at line 28 of file hdfs-bulk-ops.cc.
References impala::RENAME, and src_.
HdfsOp::HdfsOp (HdfsOpType op, const std::string & src, const std::string & dst, HdfsOperationSet * op_set)
Definition at line 34 of file hdfs-bulk-ops.cc.
References dst_, impala::RENAME, and src_.
impala::HdfsOp::HdfsOp (HdfsOpType op, const std::string & src, short permissions, HdfsOperationSet * op_set)
HdfsOp::HdfsOp ()
Required for ThreadPool.
Definition at line 49 of file hdfs-bulk-ops.cc.
Member Function Documentation
const std::string& impala::HdfsOp::dst () const inline
Definition at line 55 of file hdfs-bulk-ops.h.
References dst_.
void HdfsOp::Execute () const
Actually performs the corresponding HDFS operation, and signals completion to HdfsOperationSet via MarkOneOpDone.
Definition at line 51 of file hdfs-bulk-ops.cc.
References impala::HdfsOperationSet::AddError(), impala::CHMOD, impala::CREATE_DIR, impala::DELETE, impala::DELETE_THEN_CREATE, dst_, impala::GetStrErrMsg(), impala::HdfsOperationSet::hdfs_connection(), impala::HdfsOperationSet::MarkOneOpDone(), op_, op_set_, permissions_, impala::RENAME, impala::HdfsOperationSet::ShouldAbort(), src_, and VLOG_FILE.
Referenced by HdfsThreadPoolHelper().
HdfsOpType impala::HdfsOp::op () const inline
Definition at line 53 of file hdfs-bulk-ops.h.
References op_.
const std::string& impala::HdfsOp::src () const inline
Definition at line 54 of file hdfs-bulk-ops.h.
References src_.
Member Data Documentation
std::string impala::HdfsOp::dst_ private
Second string operand, ignored except for RENAME.
Definition at line 69 of file hdfs-bulk-ops.h.
Referenced by dst(), Execute(), and HdfsOp().
HdfsOpType impala::HdfsOp::op_ private
The kind of operation to execute.
Definition at line 63 of file hdfs-bulk-ops.h.
Referenced by Execute(), and op().
HdfsOperationSet* impala::HdfsOp::op_set_ private
Containing operation set, used to record errors and to signal completion.
Definition at line 75 of file hdfs-bulk-ops.h.
Referenced by Execute().
short impala::HdfsOp::permissions_ private
Permission operand, ignored except for CHMOD.
Definition at line 72 of file hdfs-bulk-ops.h.
Referenced by Execute().
std::string impala::HdfsOp::src_ private
First operand.
Definition at line 66 of file hdfs-bulk-ops.h.
Referenced by Execute(), HdfsOp(), and src().
The documentation for this class was generated from the following files:
be/src/util/hdfs-bulk-ops.h
be/src/util/hdfs-bulk-ops.cc