Impala: com.cloudera.impala.analysis.SortInfo Class Reference
com.cloudera.impala.analysis.SortInfo Class Reference
Public Member Functions
SortInfo (List< Expr > orderingExprs, List< Boolean > isAscOrder, List< Boolean > nullsFirstParams)
void setMaterializedTupleInfo (TupleDescriptor tupleDesc, List< Expr > tupleSlotExprs)
List< Expr > getOrderingExprs ()
List< Boolean > getIsAscOrder ()
List< Boolean > getNullsFirstParams ()
List< Expr > getSortTupleSlotExprs ()
TupleDescriptor getSortTupleDescriptor ()
List< Boolean > getNullsFirst ()
void materializeRequiredSlots (Analyzer analyzer, ExprSubstitutionMap smap)
void substituteOrderingExprs (ExprSubstitutionMap smap, Analyzer analyzer)
void checkConsistency ()
Private Attributes
List< Expr > orderingExprs_
final List< Boolean > isAscOrder_
final List< Boolean > nullsFirstParams_
TupleDescriptor sortTupleDesc_
List< Expr > sortTupleSlotExprs_
Detailed Description
Encapsulates all the information needed to compute ORDER BY This doesn't contain aliases or positional exprs. TODO: reorganize this completely, this doesn't really encapsulate anything; this should move into planner/ and encapsulate the implementation of the sort of a particular input row (materialize all row slots)
Definition at line 29 of file SortInfo.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.SortInfo.SortInfo (List< Expr > orderingExprs, List< Boolean > isAscOrder, List< Boolean > nullsFirstParams) inline
Definition at line 41 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.isAscOrder_, com.cloudera.impala.analysis.SortInfo.nullsFirstParams_, and com.cloudera.impala.analysis.SortInfo.orderingExprs_.
Member Function Documentation
void com.cloudera.impala.analysis.SortInfo.checkConsistency () inline
Asserts that all ordering exprs are bound by the sort tuple.
Definition at line 107 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.orderingExprs_.
List<Boolean> com.cloudera.impala.analysis.SortInfo.getIsAscOrder () inline
Definition at line 60 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.isAscOrder_.
Referenced by com.cloudera.impala.planner.SortNode.debugString(), com.cloudera.impala.planner.SortNode.toThrift(), and com.cloudera.impala.planner.ExchangeNode.toThrift().
List<Boolean> com.cloudera.impala.analysis.SortInfo.getNullsFirst () inline
Gets the list of booleans indicating whether nulls come first or last, independent of asc/desc.
Definition at line 69 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.isAscOrder_.
List<Boolean> com.cloudera.impala.analysis.SortInfo.getNullsFirstParams () inline
Definition at line 61 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.nullsFirstParams_.
List<Expr> com.cloudera.impala.analysis.SortInfo.getOrderingExprs () inline
Definition at line 59 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.orderingExprs_.
Referenced by com.cloudera.impala.analysis.SelectStmt.analyzeAggregation(), com.cloudera.impala.planner.SortNode.debugString(), com.cloudera.impala.planner.SortNode.toThrift(), and com.cloudera.impala.planner.ExchangeNode.toThrift().
TupleDescriptor com.cloudera.impala.analysis.SortInfo.getSortTupleDescriptor () inline
Definition at line 63 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.sortTupleDesc_.
Referenced by com.cloudera.impala.planner.SortNode.computeCosts(), and com.cloudera.impala.planner.SortNode.SortNode().
List<Expr> com.cloudera.impala.analysis.SortInfo.getSortTupleSlotExprs () inline
Definition at line 62 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.sortTupleSlotExprs_.
void com.cloudera.impala.analysis.SortInfo.materializeRequiredSlots (Analyzer analyzer, ExprSubstitutionMap smap) inline
Materializes the slots in sortTupleDesc_ referenced in the ordering exprs. Materializes the slots referenced by the corresponding sortTupleSlotExpr after applying the 'smap'.
Definition at line 83 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.orderingExprs_, com.cloudera.impala.analysis.SortInfo.sortTupleDesc_, and com.cloudera.impala.analysis.SortInfo.sortTupleSlotExprs_.
void com.cloudera.impala.analysis.SortInfo.setMaterializedTupleInfo (TupleDescriptor tupleDesc, List< Expr > tupleSlotExprs) inline
Definition at line 50 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.sortTupleDesc_, and com.cloudera.impala.analysis.SortInfo.sortTupleSlotExprs_.
void com.cloudera.impala.analysis.SortInfo.substituteOrderingExprs (ExprSubstitutionMap smap, Analyzer analyzer) inline
Definition at line 100 of file SortInfo.java.
References com.cloudera.impala.analysis.SortInfo.orderingExprs_.
Member Data Documentation
final List<Boolean> com.cloudera.impala.analysis.SortInfo.isAscOrder_ private
Definition at line 31 of file SortInfo.java.
Referenced by com.cloudera.impala.analysis.SortInfo.getIsAscOrder(), com.cloudera.impala.analysis.SortInfo.getNullsFirst(), and com.cloudera.impala.analysis.SortInfo.SortInfo().
final List<Boolean> com.cloudera.impala.analysis.SortInfo.nullsFirstParams_ private
Definition at line 33 of file SortInfo.java.
Referenced by com.cloudera.impala.analysis.SortInfo.getNullsFirstParams(), and com.cloudera.impala.analysis.SortInfo.SortInfo().
List<Expr> com.cloudera.impala.analysis.SortInfo.orderingExprs_ private
Definition at line 30 of file SortInfo.java.
Referenced by com.cloudera.impala.analysis.SortInfo.checkConsistency(), com.cloudera.impala.analysis.SortInfo.getOrderingExprs(), com.cloudera.impala.analysis.SortInfo.materializeRequiredSlots(), com.cloudera.impala.analysis.SortInfo.SortInfo(), and com.cloudera.impala.analysis.SortInfo.substituteOrderingExprs().
TupleDescriptor com.cloudera.impala.analysis.SortInfo.sortTupleDesc_ private
Definition at line 36 of file SortInfo.java.
Referenced by com.cloudera.impala.analysis.SortInfo.getSortTupleDescriptor(), com.cloudera.impala.analysis.SortInfo.materializeRequiredSlots(), and com.cloudera.impala.analysis.SortInfo.setMaterializedTupleInfo().
List<Expr> com.cloudera.impala.analysis.SortInfo.sortTupleSlotExprs_ private
Definition at line 39 of file SortInfo.java.
Referenced by com.cloudera.impala.analysis.SortInfo.getSortTupleSlotExprs(), com.cloudera.impala.analysis.SortInfo.materializeRequiredSlots(), and com.cloudera.impala.analysis.SortInfo.setMaterializedTupleInfo().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/SortInfo.java