Impala: com.cloudera.impala.catalog.HdfsPartitionTest Class Reference
com.cloudera.impala.catalog.HdfsPartitionTest Class Reference
Public Member Functions
HdfsPartitionTest ()
void testCompare ()
Private Member Functions
void verifySymmetric (List< LiteralExpr > o1, List< LiteralExpr > o2)
void verifyTransitive (List< LiteralExpr > o1, List< LiteralExpr > o2, List< LiteralExpr > o3)
void verifyReflexive (List< LiteralExpr > o1)
void verifyAntiSymmetric (List< LiteralExpr > o1, List< LiteralExpr > o2, List< LiteralExpr > o3)
Private Attributes
List< LiteralExpr > valuesNull_ = Lists.newArrayList()
List< LiteralExpr > valuesDecimal_ = Lists.newArrayList()
List< LiteralExpr > valuesDecimal1_ = Lists.newArrayList()
List< LiteralExpr > valuesDecimal2_ = Lists.newArrayList()
List< LiteralExpr > valuesMixed_ = Lists.newArrayList()
List< LiteralExpr > valuesMixed1_ = Lists.newArrayList()
List< LiteralExpr > valuesMixed2_ = Lists.newArrayList()
Detailed Description
Definition at line 29 of file HdfsPartitionTest.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.HdfsPartitionTest.HdfsPartitionTest () inline
Definition at line 39 of file HdfsPartitionTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, and com.cloudera.impala.catalog.Type.STRING.
Member Function Documentation
void com.cloudera.impala.catalog.HdfsPartitionTest.testCompare () inline
Definition at line 59 of file HdfsPartitionTest.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.HdfsPartitionTest.valuesDecimal1_, com.cloudera.impala.catalog.HdfsPartitionTest.valuesDecimal2_, com.cloudera.impala.catalog.HdfsPartitionTest.valuesDecimal_, com.cloudera.impala.catalog.HdfsPartitionTest.valuesMixed1_, com.cloudera.impala.catalog.HdfsPartitionTest.valuesMixed2_, com.cloudera.impala.catalog.HdfsPartitionTest.valuesMixed_, com.cloudera.impala.catalog.HdfsPartitionTest.valuesNull_, com.cloudera.impala.catalog.HdfsPartitionTest.verifyAntiSymmetric(), com.cloudera.impala.catalog.HdfsPartitionTest.verifyReflexive(), com.cloudera.impala.catalog.HdfsPartitionTest.verifySymmetric(), and com.cloudera.impala.catalog.HdfsPartitionTest.verifyTransitive().
void com.cloudera.impala.catalog.HdfsPartitionTest.verifyAntiSymmetric (List< LiteralExpr > o1, List< LiteralExpr > o2, List< LiteralExpr > o3) inline private
Definition at line 104 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
void com.cloudera.impala.catalog.HdfsPartitionTest.verifyReflexive (List< LiteralExpr > o1) inline private
Definition at line 100 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
void com.cloudera.impala.catalog.HdfsPartitionTest.verifySymmetric (List< LiteralExpr > o1, List< LiteralExpr > o2) inline private
Definition at line 86 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
void com.cloudera.impala.catalog.HdfsPartitionTest.verifyTransitive (List< LiteralExpr > o1, List< LiteralExpr > o2, List< LiteralExpr > o3) inline private
Definition at line 92 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
Member Data Documentation
List<LiteralExpr> com.cloudera.impala.catalog.HdfsPartitionTest.valuesDecimal1_ = Lists.newArrayList() private
Definition at line 33 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
List<LiteralExpr> com.cloudera.impala.catalog.HdfsPartitionTest.valuesDecimal2_ = Lists.newArrayList() private
Definition at line 34 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
List<LiteralExpr> com.cloudera.impala.catalog.HdfsPartitionTest.valuesDecimal_ = Lists.newArrayList() private
Definition at line 32 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
List<LiteralExpr> com.cloudera.impala.catalog.HdfsPartitionTest.valuesMixed1_ = Lists.newArrayList() private
Definition at line 36 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
List<LiteralExpr> com.cloudera.impala.catalog.HdfsPartitionTest.valuesMixed2_ = Lists.newArrayList() private
Definition at line 37 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
List<LiteralExpr> com.cloudera.impala.catalog.HdfsPartitionTest.valuesMixed_ = Lists.newArrayList() private
Definition at line 35 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
List<LiteralExpr> com.cloudera.impala.catalog.HdfsPartitionTest.valuesNull_ = Lists.newArrayList() private
Definition at line 31 of file HdfsPartitionTest.java.
Referenced by com.cloudera.impala.catalog.HdfsPartitionTest.testCompare().
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/catalog/HdfsPartitionTest.java