Impala: com.cloudera.impala.catalog.View Class Reference
com.cloudera.impala.catalog.View Class Reference
Public Member Functions
View (TableId id, org.apache.hadoop.hive.metastore.api.Table msTable, Db db, String name, String owner)
View (String alias, QueryStmt queryStmt)
void load (Table oldValue, HiveMetaStoreClient client, org.apache.hadoop.hive.metastore.api.Table msTbl) throws TableLoadingException
TCatalogObjectType getCatalogObjectType ()
QueryStmt getQueryStmt ()
String getOriginalViewDef ()
String getInlineViewDef ()
int getNumNodes ()
boolean isLocalView ()
TTableDescriptor toThriftDescriptor (Set< Long > referencedPartitions)
TTable toThrift ()
void addColumn (Column col)
void clearColumns ()
void updateLastDdlTime (long ddlTime)
void validate () throws TableLoadingException
TCatalogObject toTCatalogObject ()
Db getDb ()
String getName ()
String getFullName ()
TableName getTableName ()
String getOwner ()
ArrayList< Column > getColumns ()
List< String > getColumnNames ()
String getStorageHandlerClassName ()
ArrayList< Column > getColumnsInHiveOrder ()
List< Column > getNonClusteringColumns ()
Column getColumn (String name)
org.apache.hadoop.hive.metastore.api.Table getMetaStoreTable ()
int getNumClusteringCols ()
TableId getId ()
long getNumRows ()
ArrayType getType ()
long getCatalogVersion ()
void setCatalogVersion (long catalogVersion)
boolean isLoaded ()
Static Public Member Functions
static Table fromMetastoreTable (TableId id, Db db, org.apache.hadoop.hive.metastore.api.Table msTbl)
static Table fromThrift (Db parentDb, TTable thriftTable) throws TableLoadingException
Protected Member Functions
void loadFromThrift (TTable t) throws TableLoadingException
List< String > getColumnNamesWithHmsStats ()
void loadAllColumnStats (HiveMetaStoreClient client)
Type parseColumnType (FieldSchema fs) throws TableLoadingException
Static Protected Member Functions
static long getRowCount (Map< String, String > parameters)
Protected Attributes
final
org.apache.hadoop.hive.metastore.api.Table msTable_
final TableId id_
final Db db_
final String name_
final String owner_
TTableDescriptor tableDesc_
List< FieldSchema > fields_
TAccessLevel accessLevel_ = TAccessLevel.READ_WRITE
int numClusteringCols_
long numRows_ = -1
final ArrayType type_ = new ArrayType(new StructType())
long lastDdlTime_
Static Protected Attributes
static EnumSet< TableType > SUPPORTED_TABLE_TYPES
Private Member Functions
void init () throws TableLoadingException
Private Attributes
String originalViewDef_
String inlineViewDef_
QueryStmt queryStmt_
final boolean isLocalView_
Detailed Description
Table metadata representing a catalog view or a local view from a WITH clause. Most methods inherited from Table are not supposed to be called on this class because views are substituted with their underlying definition during analysis of a statement.
Refreshing or invalidating a view will reload the view's definition but will not affect the metadata of the underlying tables (if any).
Definition at line 41 of file View.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.View.View (TableId id, org.apache.hadoop.hive.metastore.api.Table msTable, Db db, String name, String owner) inline
Definition at line 67 of file View.java.
References com.cloudera.impala.catalog.View.isLocalView_.
com.cloudera.impala.catalog.View.View (String alias, QueryStmt queryStmt) inline
C'tor for WITH-clause views that already have a parsed QueryStmt.
Definition at line 76 of file View.java.
References com.cloudera.impala.catalog.View.isLocalView_, and com.cloudera.impala.catalog.View.queryStmt_.
Member Function Documentation
void com.cloudera.impala.catalog.Table.addColumn (Column col) inline inherited
Definition at line 114 of file Table.java.
References com.cloudera.impala.catalog.ArrayType.getItemType(), and com.cloudera.impala.catalog.Table.type_.
Referenced by com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.DataSourceTable.loadColumns(), and com.cloudera.impala.catalog.HdfsTable.loadColumns().
void com.cloudera.impala.catalog.Table.clearColumns () inline inherited
Definition at line 121 of file Table.java.
References com.cloudera.impala.catalog.ArrayType.getItemType(), and com.cloudera.impala.catalog.Table.type_.
Referenced by com.cloudera.impala.catalog.HBaseTable.load().
static Table com.cloudera.impala.catalog.Table.fromMetastoreTable (TableId id, Db db, org.apache.hadoop.hive.metastore.api.Table msTbl) inline static inherited
Creates a table of the appropriate type based on the given hive.metastore.api.Table object.
Definition at line 207 of file Table.java.
References com.cloudera.impala.catalog.DataSourceTable.isDataSourceTable(), com.cloudera.impala.catalog.HBaseTable.isHBaseTable(), and com.cloudera.impala.catalog.HdfsFileFormat.isHdfsFormatClass().
static Table com.cloudera.impala.catalog.Table.fromThrift (Db parentDb, TTable thriftTable) throws TableLoadingException inline static inherited
Factory method that creates a new Table from its Thrift representation. Determines the type of table to create based on the Thrift table provided.
Definition at line 231 of file Table.java.
TCatalogObjectType com.cloudera.impala.catalog.View.getCatalogObjectType () inline
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 144 of file View.java.
long com.cloudera.impala.catalog.Table.getCatalogVersion () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 408 of file Table.java.
References com.cloudera.impala.catalog.Table.catalogVersion_.
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.dropPartition(), com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects(), com.cloudera.impala.catalog.ImpaladCatalog.removeTable(), com.cloudera.impala.catalog.CatalogServiceCatalog.replaceTableIfUnchanged(), and com.cloudera.impala.catalog.Table.toTCatalogObject().
Column com.cloudera.impala.catalog.Table.getColumn (String name) inline inherited
Case-insensitive lookup.
Definition at line 392 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.loadAllColumnStats(), and com.cloudera.impala.catalog.CatalogTest.testColStatsColTypeMismatch().
List<String> com.cloudera.impala.catalog.Table.getColumnNames () inline inherited
Returns a list of the column names ordered by position.
Definition at line 354 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByPos_.
Referenced by com.cloudera.impala.analysis.ColumnLineageGraph.addTargetColumnLabels(), com.cloudera.impala.catalog.HdfsTable.getTHdfsTable(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
List<String> com.cloudera.impala.catalog.Table.getColumnNamesWithHmsStats () inline protected inherited
Definition at line 144 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByName_, and impala.name.
Referenced by com.cloudera.impala.catalog.Table.loadAllColumnStats().
ArrayList<Column> com.cloudera.impala.catalog.Table.getColumns () inline inherited
Definition at line 349 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByPos_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableOrViewRename(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.catalog.HdfsTable.createPartition(), com.cloudera.impala.catalog.HdfsTable.dropPartition(), com.cloudera.impala.catalog.HdfsTable.getColumnNamesWithHmsStats(), com.cloudera.impala.catalog.HBaseTable.getColumnsInHiveOrder(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.HBaseTable.getTHBaseTable(), com.cloudera.impala.analysis.InsertStmt.prepareExpressions(), com.cloudera.impala.catalog.HdfsTable.resetPartitionMd(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.updatePartitionMdAndColStats().
ArrayList<Column> com.cloudera.impala.catalog.Table.getColumnsInHiveOrder () inline inherited
Returns the list of all columns, but with partition columns at the end of the list rather than the beginning. This is equivalent to the order in which Hive enumerates columns.
Definition at line 373 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByPos_, com.cloudera.impala.catalog.Table.getNonClusteringColumns(), and com.cloudera.impala.catalog.Table.numClusteringCols_.
Referenced by com.cloudera.impala.service.DescribeResultFactory.describeTableMinimal(), com.cloudera.impala.service.Frontend.getColumnStats(), and com.cloudera.impala.analysis.InsertStmt.prepareExpressions().
Db com.cloudera.impala.catalog.Table.getDb () inline inherited
Definition at line 341 of file Table.java.
References com.cloudera.impala.catalog.Table.db_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableUpdateStats(), com.cloudera.impala.service.CatalogOpExecutor.createHiveColStats(), com.cloudera.impala.analysis.Analyzer.getTable(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), com.cloudera.impala.analysis.ShowStatsStmt.toThrift(), com.cloudera.impala.analysis.ComputeStatsStmt.toThrift(), and com.cloudera.impala.service.CatalogOpExecutor.updateCatalog().
String com.cloudera.impala.catalog.Table.getFullName () inline inherited
Definition at line 343 of file Table.java.
References com.cloudera.impala.catalog.Table.db_, com.cloudera.impala.catalog.Db.getName(), and com.cloudera.impala.catalog.Table.name_.
Referenced by com.cloudera.impala.analysis.ShowPartitionsStmt.analyze(), com.cloudera.impala.analysis.ShowStatsStmt.analyze(), com.cloudera.impala.analysis.ShowFilesStmt.analyze(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), com.cloudera.impala.analysis.TableRef.analyze(), com.cloudera.impala.analysis.InsertStmt.checkColumnCoverage(), com.cloudera.impala.planner.DataSourceScanNode.getNodeExplainString(), com.cloudera.impala.planner.HBaseScanNode.getNodeExplainString(), com.cloudera.impala.analysis.Analyzer.getTable(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.loadAllColumnStats(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), com.cloudera.impala.catalog.HdfsTable.loadDiskIds(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
TableId com.cloudera.impala.catalog.Table.getId () inline inherited
Definition at line 403 of file Table.java.
References com.cloudera.impala.catalog.Table.id_.
Referenced by com.cloudera.impala.planner.HBaseTableSink.toThrift(), and com.cloudera.impala.planner.HdfsTableSink.toThrift().
String com.cloudera.impala.catalog.View.getInlineViewDef () inline
Definition at line 147 of file View.java.
References com.cloudera.impala.catalog.View.inlineViewDef_.
org.apache.hadoop.hive.metastore.api.Table com.cloudera.impala.catalog.Table.getMetaStoreTable () inline inherited
Returns the metastore.api.Table object this Table was created from. Returns null if the derived Table object was not created from a metastore Table (ex. InlineViews).
Definition at line 398 of file Table.java.
References com.cloudera.impala.catalog.Table.msTable_.
Referenced by com.cloudera.impala.catalog.HdfsTable.getFirstLocationWithoutWriteAccess(), com.cloudera.impala.catalog.HdfsTable.getPartitionFromThriftPartitionSpec(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.HBaseTable.loadFromThrift(), com.cloudera.impala.catalog.HdfsTable.loadFromThrift(), and com.cloudera.impala.catalog.Table.toThrift().
String com.cloudera.impala.catalog.Table.getName () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 342 of file Table.java.
References com.cloudera.impala.catalog.Table.name_.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableUpdateStats(), com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.service.CatalogOpExecutor.createHiveColStats(), com.cloudera.impala.catalog.HdfsTable.createPartition(), com.cloudera.impala.catalog.HdfsPartition.fromThrift(), com.cloudera.impala.analysis.Analyzer.getTable(), com.cloudera.impala.analysis.InlineViewRef.InlineViewRef(), com.cloudera.impala.catalog.Table.parseColumnType(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), com.cloudera.impala.analysis.ShowStatsStmt.toThrift(), com.cloudera.impala.analysis.ComputeStatsStmt.toThrift(), com.cloudera.impala.service.CatalogOpExecutor.updateCatalog(), and com.cloudera.impala.analysis.WithClause.WithClause().
List<Column> com.cloudera.impala.catalog.Table.getNonClusteringColumns () inline inherited
Returns the list of all columns excluding any partition columns.
Definition at line 385 of file Table.java.
References com.cloudera.impala.catalog.Table.numClusteringCols_.
Referenced by com.cloudera.impala.analysis.ComputeStatsStmt.analyze(), and com.cloudera.impala.catalog.Table.getColumnsInHiveOrder().
int com.cloudera.impala.catalog.Table.getNumClusteringCols () inline inherited
Definition at line 402 of file Table.java.
References com.cloudera.impala.catalog.Table.numClusteringCols_.
Referenced by com.cloudera.impala.analysis.ShowPartitionsStmt.analyze(), com.cloudera.impala.analysis.ComputeStatsStmt.analyze(), com.cloudera.impala.catalog.CatalogTest.checkTableCols(), com.cloudera.impala.service.CatalogOpExecutor.dropTableOrView(), com.cloudera.impala.analysis.ComputeStatsStmt.getBaseColumnStatsQuerySelectList(), com.cloudera.impala.planner.HdfsScanNode.getNodeExplainString(), com.cloudera.impala.catalog.HdfsTable.getNonPartitionFieldSchemas(), com.cloudera.impala.planner.HdfsScanNode.prunePartitions(), and com.cloudera.impala.service.CatalogOpExecutor.updateCatalog().
int com.cloudera.impala.catalog.View.getNumNodes () inline
Definition at line 150 of file View.java.
long com.cloudera.impala.catalog.Table.getNumRows () inline inherited
Definition at line 404 of file Table.java.
References com.cloudera.impala.catalog.Table.numRows_.
Referenced by com.cloudera.impala.analysis.IsNullPredicate.analyze().
String com.cloudera.impala.catalog.View.getOriginalViewDef () inline
Definition at line 146 of file View.java.
References com.cloudera.impala.catalog.View.originalViewDef_.
String com.cloudera.impala.catalog.Table.getOwner () inline inherited
Definition at line 348 of file Table.java.
References com.cloudera.impala.catalog.Table.owner_.
QueryStmt com.cloudera.impala.catalog.View.getQueryStmt () inline
Definition at line 145 of file View.java.
References com.cloudera.impala.catalog.View.queryStmt_.
static long com.cloudera.impala.catalog.Table.getRowCount (Map< String, String > parameters) inline static protected inherited
Returns the value of the ROW_COUNT constant, or -1 if not found.
Definition at line 191 of file Table.java.
Referenced by com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), and com.cloudera.impala.catalog.HdfsTable.loadPartitions().
String com.cloudera.impala.catalog.Table.getStorageHandlerClassName () inline inherited
Subclasses should override this if they provide a storage handler class. Currently only HBase tables need to provide a storage handler.
Definition at line 366 of file Table.java.
TableName com.cloudera.impala.catalog.Table.getTableName () inline inherited
Definition at line 344 of file Table.java.
References com.cloudera.impala.catalog.Table.db_, com.cloudera.impala.catalog.Db.getName(), and com.cloudera.impala.catalog.Table.name_.
Referenced by com.cloudera.impala.analysis.ComputeStatsStmt.analyze(), com.cloudera.impala.service.CatalogOpExecutor.dropStats(), and com.cloudera.impala.analysis.InlineViewRef.InlineViewRef().
ArrayType com.cloudera.impala.catalog.Table.getType () inline inherited
Definition at line 405 of file Table.java.
References com.cloudera.impala.catalog.Table.type_.
Referenced by com.cloudera.impala.catalog.HdfsTable.load().
void com.cloudera.impala.catalog.View.init () throws TableLoadingException inline private
Initializes the originalViewDef_, inlineViewDef_, and queryStmt_ members by parsing the expanded view definition SQL-string. Throws a TableLoadingException if there was any error parsing the the SQL or if the view definition did not parse into a QueryStmt.
Definition at line 117 of file View.java.
References com.cloudera.impala.catalog.Table.db_, com.cloudera.impala.catalog.Table.getMetaStoreTable(), com.cloudera.impala.catalog.Db.getName(), com.cloudera.impala.catalog.View.inlineViewDef_, com.cloudera.impala.catalog.Table.name_, com.cloudera.impala.catalog.View.originalViewDef_, gen_ir_descriptions.parser, and com.cloudera.impala.catalog.View.queryStmt_.
Referenced by com.cloudera.impala.catalog.View.load(), and com.cloudera.impala.catalog.View.loadFromThrift().
boolean com.cloudera.impala.catalog.Table.isLoaded () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 416 of file Table.java.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.getExistingTable(), com.cloudera.impala.service.Frontend.getMissingTbls(), com.cloudera.impala.catalog.CatalogServiceCatalog.getOrLoadTable(), com.cloudera.impala.testutil.ImpaladTestCatalog.getTable(), com.cloudera.impala.catalog.ImpaladCatalog.getTable(), and com.cloudera.impala.analysis.Analyzer.getTable().
boolean com.cloudera.impala.catalog.View.isLocalView () inline
Definition at line 154 of file View.java.
References com.cloudera.impala.catalog.View.isLocalView_.
Referenced by com.cloudera.impala.analysis.TableRef.analyze().
void com.cloudera.impala.catalog.View.load (Table oldValue, HiveMetaStoreClient client, org.apache.hadoop.hive.metastore.api.Table msTbl) throws TableLoadingException inline
Definition at line 83 of file View.java.
References com.cloudera.impala.catalog.Table.addColumn(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.Table.name_, com.cloudera.impala.catalog.Table.numClusteringCols_, com.cloudera.impala.catalog.Table.numRows_, and com.cloudera.impala.catalog.Table.parseColumnType().
void com.cloudera.impala.catalog.Table.loadAllColumnStats (HiveMetaStoreClient client) inline protected inherited
Loads column statistics for all columns in this table from the Hive metastore. Any errors are logged and ignored, since the absence of column stats is not critical to the correctness of the system.
Definition at line 155 of file Table.java.
References com.cloudera.impala.catalog.Table.getColumn(), com.cloudera.impala.catalog.Table.getColumnNamesWithHmsStats(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Column.getType(), com.cloudera.impala.catalog.ColumnStats.isSupportedColType(), com.cloudera.impala.catalog.Table.name_, and com.cloudera.impala.catalog.Column.updateStats().
Referenced by com.cloudera.impala.catalog.HBaseTable.load(), and com.cloudera.impala.catalog.HdfsTable.loadColumns().
void com.cloudera.impala.catalog.View.loadFromThrift (TTable t) throws TableLoadingException inline protected
Definition at line 106 of file View.java.
References com.cloudera.impala.catalog.View.init().
Type com.cloudera.impala.catalog.Table.parseColumnType (FieldSchema fs) throws TableLoadingException inline protected inherited
Gets the ColumnType from the given FieldSchema by using Impala's SqlParser. Throws a TableLoadingException if the FieldSchema could not be parsed. The type can either be:
Supported by Impala, in which case the type is returned.
A type Impala understands but is not yet implemented (e.g. date), the type is returned but type.IsSupported() returns false.
A type Impala can't understand at all, and a TableLoadingException is thrown.
Definition at line 331 of file Table.java.
References com.cloudera.impala.catalog.Table.getName().
Referenced by com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.DataSourceTable.loadColumns(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), and com.cloudera.impala.catalog.HBaseTable.supportsBinaryEncoding().
void com.cloudera.impala.catalog.Table.setCatalogVersion (long catalogVersion) inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 411 of file Table.java.
References com.cloudera.impala.catalog.Table.catalogVersion_.
TCatalogObject com.cloudera.impala.catalog.Table.toTCatalogObject () inline inherited
Definition at line 314 of file Table.java.
References com.cloudera.impala.catalog.Table.getCatalogObjectType(), com.cloudera.impala.catalog.Table.getCatalogVersion(), and com.cloudera.impala.catalog.Table.toThrift().
TTable com.cloudera.impala.catalog.View.toThrift () inline
Definition at line 162 of file View.java.
TTableDescriptor com.cloudera.impala.catalog.View.toThriftDescriptor (Set< Long > referencedPartitions) inline
Definition at line 157 of file View.java.
void com.cloudera.impala.catalog.Table.updateLastDdlTime (long ddlTime) inline inherited
Updates the lastDdlTime for this Table, if the new value is greater than the existing value. Does nothing if the new value is less than or equal to the existing value.
Definition at line 132 of file Table.java.
References com.cloudera.impala.catalog.Table.lastDdlTime_.
void com.cloudera.impala.catalog.Table.validate () throws TableLoadingException inline inherited
Checks preconditions for this table to function as expected. Currently only checks that all entries in colsByName_ use lower case keys.
Definition at line 279 of file Table.java.
References com.cloudera.impala.catalog.Table.colsByName_.
Member Data Documentation
TAccessLevel com.cloudera.impala.catalog.Table.accessLevel_ = TAccessLevel.READ_WRITE protected inherited
Definition at line 66 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.getFirstLocationWithoutWriteAccess(), com.cloudera.impala.catalog.HdfsTable.hasWriteAccess(), com.cloudera.impala.catalog.Table.loadFromThrift(), com.cloudera.impala.catalog.HdfsTable.loadPartitions(), and com.cloudera.impala.catalog.Table.toThrift().
final Db com.cloudera.impala.catalog.Table.db_ protected inherited
Definition at line 61 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getDb(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Table.getTableName(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.Table(), com.cloudera.impala.catalog.IncompleteTable.toThrift(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
List<FieldSchema> com.cloudera.impala.catalog.Table.fields_ protected inherited
Definition at line 65 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.getFieldSchemas(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), and com.cloudera.impala.catalog.Table.loadFromThrift().
final TableId com.cloudera.impala.catalog.Table.id_ protected inherited
Definition at line 60 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getId(), com.cloudera.impala.catalog.Table.Table(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
String com.cloudera.impala.catalog.View.inlineViewDef_ private
Definition at line 59 of file View.java.
Referenced by com.cloudera.impala.catalog.View.getInlineViewDef(), and com.cloudera.impala.catalog.View.init().
final boolean com.cloudera.impala.catalog.View.isLocalView_ private
Definition at line 65 of file View.java.
Referenced by com.cloudera.impala.catalog.View.isLocalView(), and com.cloudera.impala.catalog.View.View().
long com.cloudera.impala.catalog.Table.lastDdlTime_ protected inherited
Definition at line 85 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.Table(), and com.cloudera.impala.catalog.Table.updateLastDdlTime().
final org.apache.hadoop.hive.metastore.api.Table com.cloudera.impala.catalog.Table.msTable_ protected inherited
Definition at line 58 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getMetaStoreTable(), and com.cloudera.impala.catalog.Table.Table().
final String com.cloudera.impala.catalog.Table.name_ protected inherited
Definition at line 62 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Table.getName(), com.cloudera.impala.catalog.DataSourceTable.getRequiredTableProperty(), com.cloudera.impala.catalog.Table.getTableName(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.loadAllColumnStats(), com.cloudera.impala.catalog.HdfsTable.loadBlockMetadata(), com.cloudera.impala.catalog.HBaseTable.loadFromThrift(), com.cloudera.impala.catalog.Table.Table(), com.cloudera.impala.catalog.IncompleteTable.toThrift(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
int com.cloudera.impala.catalog.Table.numClusteringCols_ protected inherited
Definition at line 69 of file Table.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.dropPartition(), com.cloudera.impala.catalog.HdfsTable.getColumnNamesWithHmsStats(), com.cloudera.impala.catalog.Table.getColumnsInHiveOrder(), com.cloudera.impala.catalog.Table.getNonClusteringColumns(), com.cloudera.impala.catalog.Table.getNumClusteringCols(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.HdfsTable.loadColumns(), com.cloudera.impala.catalog.Table.loadFromThrift(), com.cloudera.impala.catalog.HdfsTable.resetPartitionMd(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.updatePartitionMdAndColStats().
long com.cloudera.impala.catalog.Table.numRows_ = -1 protected inherited
Definition at line 72 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getNumRows(), com.cloudera.impala.catalog.DataSourceTable.getTableStats(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.catalog.View.load(), com.cloudera.impala.catalog.DataSourceTable.load(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.Table.loadFromThrift(), com.cloudera.impala.catalog.CatalogObjectToFromThriftTest.TestPartitionedTable(), and com.cloudera.impala.catalog.Table.toThrift().
String com.cloudera.impala.catalog.View.originalViewDef_ private
Definition at line 45 of file View.java.
Referenced by com.cloudera.impala.catalog.View.getOriginalViewDef(), and com.cloudera.impala.catalog.View.init().
final String com.cloudera.impala.catalog.Table.owner_ protected inherited
Definition at line 63 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.getOwner(), and com.cloudera.impala.catalog.Table.Table().
QueryStmt com.cloudera.impala.catalog.View.queryStmt_ private
Definition at line 62 of file View.java.
Referenced by com.cloudera.impala.catalog.View.getQueryStmt(), com.cloudera.impala.catalog.View.init(), and com.cloudera.impala.catalog.View.View().
EnumSet<TableType> com.cloudera.impala.catalog.Table.SUPPORTED_TABLE_TYPES static protected inherited
Initial value:
= EnumSet.of(
      TableType.EXTERNAL_TABLE, TableType.MANAGED_TABLE, TableType.VIRTUAL_VIEW)
Definition at line 88 of file Table.java.
TTableDescriptor com.cloudera.impala.catalog.Table.tableDesc_ protected inherited
Definition at line 64 of file Table.java.
final ArrayType com.cloudera.impala.catalog.Table.type_ = new ArrayType(new StructType()) protected inherited
Definition at line 82 of file Table.java.
Referenced by com.cloudera.impala.catalog.Table.addColumn(), com.cloudera.impala.catalog.Table.clearColumns(), com.cloudera.impala.catalog.Table.getType(), and com.cloudera.impala.catalog.Table.loadFromThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/View.java