Impala: com.cloudera.impala.service.FrontendTest Class Reference
com.cloudera.impala.service.FrontendTest Class Reference
Public Member Functions
void TestCatalogNotReady () throws ImpalaException
void TestGetTypeInfo () throws ImpalaException
void TestGetSchema () throws ImpalaException
void TestGetTables () throws ImpalaException
void TestGetColumns () throws ImpalaException
void TestGetCatalogs () throws ImpalaException
void TestGetTableTypes () throws ImpalaException
void TestGetFunctions () throws ImpalaException
Private Member Functions
TResultSet execMetadataOp (TMetadataOpRequest req) throws ImpalaException
Static Private Attributes
static Frontend fe_
Detailed Description
Unit test for Frontend.execHiveServer2MetadataOp, which executes a HiveServer2 metadata operation and returns a TMetadataOpResponse (which contains a result set and the schema of the result set). HiveServer2 API specifies the result set schema for each of the operation. Each test will validate the result set schema and the expected result set.
Definition at line 42 of file FrontendTest.java.
Member Function Documentation
TResultSet com.cloudera.impala.service.FrontendTest.execMetadataOp (TMetadataOpRequest req) throws ImpalaException inline private
Definition at line 191 of file FrontendTest.java.
Referenced by com.cloudera.impala.service.FrontendTest.TestGetCatalogs(), com.cloudera.impala.service.FrontendTest.TestGetColumns(), com.cloudera.impala.service.FrontendTest.TestGetFunctions(), com.cloudera.impala.service.FrontendTest.TestGetSchema(), com.cloudera.impala.service.FrontendTest.TestGetTables(), com.cloudera.impala.service.FrontendTest.TestGetTableTypes(), and com.cloudera.impala.service.FrontendTest.TestGetTypeInfo().
void com.cloudera.impala.service.FrontendTest.TestCatalogNotReady () throws ImpalaException inline
Definition at line 47 of file FrontendTest.java.
References com.cloudera.impala.authorization.AuthorizationConfig.createAuthDisabledConfig().
void com.cloudera.impala.service.FrontendTest.TestGetCatalogs () throws ImpalaException inline
Definition at line 137 of file FrontendTest.java.
References com.cloudera.impala.service.FrontendTest.execMetadataOp().
void com.cloudera.impala.service.FrontendTest.TestGetColumns () throws ImpalaException inline
Definition at line 114 of file FrontendTest.java.
References com.cloudera.impala.service.FrontendTest.execMetadataOp().
void com.cloudera.impala.service.FrontendTest.TestGetFunctions () throws ImpalaException inline
Definition at line 163 of file FrontendTest.java.
References com.cloudera.impala.service.FrontendTest.execMetadataOp().
void com.cloudera.impala.service.FrontendTest.TestGetSchema () throws ImpalaException inline
Definition at line 83 of file FrontendTest.java.
References com.cloudera.impala.service.FrontendTest.execMetadataOp().
void com.cloudera.impala.service.FrontendTest.TestGetTables () throws ImpalaException inline
Definition at line 98 of file FrontendTest.java.
References com.cloudera.impala.service.FrontendTest.execMetadataOp().
void com.cloudera.impala.service.FrontendTest.TestGetTableTypes () throws ImpalaException inline
Definition at line 150 of file FrontendTest.java.
References com.cloudera.impala.service.FrontendTest.execMetadataOp().
void com.cloudera.impala.service.FrontendTest.TestGetTypeInfo () throws ImpalaException inline
Definition at line 67 of file FrontendTest.java.
References com.cloudera.impala.service.FrontendTest.execMetadataOp().
Member Data Documentation
Frontend com.cloudera.impala.service.FrontendTest.fe_ static private
Initial value:
= new Frontend(
      AuthorizationConfig.createAuthDisabledConfig(), new ImpaladTestCatalog())
Definition at line 43 of file FrontendTest.java.
The documentation for this class was generated from the following file:
fe/src/test/java/com/cloudera/impala/service/FrontendTest.java