Impala: com.cloudera.impala.analysis.CreateTableDataSrcStmt Class Reference
com.cloudera.impala.analysis.CreateTableDataSrcStmt Class Reference
Public Member Functions
CreateTableDataSrcStmt (TableName tableName, List< ColumnDef > columnDefs, String dataSourceName, String initString, String comment, boolean ifNotExists)
void analyze (Analyzer analyzer) throws AnalysisException
CreateTableStmt clone ()
String getTbl ()
TableName getTblName ()
List< ColumnDef > getColumnDefs ()
List< ColumnDef > getPartitionColumnDefs ()
String getComment ()
boolean isExternal ()
boolean getIfNotExists ()
HdfsUri getLocation ()
void setLocation (HdfsUri location)
THdfsFileFormat getFileFormat ()
RowFormat getRowFormat ()
Map< String, String > getTblProperties ()
Map< String, String > getSerdeProperties ()
String getOwner ()
String getDb ()
String toSql ()
TCreateTableParams toThrift ()
void setIsExplain ()
boolean isExplain ()
Static Public Member Functions
static void unescapeProperties (Map< String, String > propertyMap)
Protected Attributes
boolean isExplain_ = false
Static Private Member Functions
static Map< String, String > createInitialTableProperties (String dataSourceName, String initString)
Detailed Description
Represents a CREATE TABLE statement for external data sources. Such tables reference an external data source (created with a CREATE DATA SOURCE statement) and the properties of that source are stored in the table properties because the metastore does not store the data sources themselves.
Definition at line 44 of file CreateTableDataSrcStmt.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.CreateTableDataSrcStmt.CreateTableDataSrcStmt (TableName tableName, List< ColumnDef > columnDefs, String dataSourceName, String initString, String comment, boolean ifNotExists) inline
Definition at line 46 of file CreateTableDataSrcStmt.java.
References com.cloudera.impala.analysis.CreateTableDataSrcStmt.createInitialTableProperties(), and com.cloudera.impala.catalog.RowFormat.DEFAULT_ROW_FORMAT.
Member Function Documentation
void com.cloudera.impala.analysis.CreateTableDataSrcStmt.analyze (Analyzer analyzer) throws AnalysisException inline
Perform semantic analysis of node and all of its children. Throws exception if any errors found.
Parameters
analyzer
Exceptions
AnalysisException
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 68 of file CreateTableDataSrcStmt.java.
References com.cloudera.impala.authorization.Privilege.ALL, com.cloudera.impala.analysis.CreateTableStmt.getColumnDefs(), com.cloudera.impala.analysis.CreateTableStmt.getTblProperties(), and com.cloudera.impala.catalog.DataSourceTable.isSupportedColumnType().
CreateTableStmt com.cloudera.impala.analysis.CreateTableStmt.clone () inline inherited
Definition at line 126 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.CreateTableStmt().
static Map<String, String> com.cloudera.impala.analysis.CreateTableDataSrcStmt.createInitialTableProperties (String dataSourceName, String initString) inline static private
Creates the initial map of table properties containing the name of the data source and the table init string.
Definition at line 58 of file CreateTableDataSrcStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableDataSrcStmt.CreateTableDataSrcStmt().
List<ColumnDef> com.cloudera.impala.analysis.CreateTableStmt.getColumnDefs () inline inherited
Definition at line 130 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.columnDefs_.
Referenced by com.cloudera.impala.analysis.CreateTableDataSrcStmt.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.analyze(), com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), com.cloudera.impala.catalog.Type.parseColumnType(), and com.cloudera.impala.analysis.CreateTableStmt.toThrift().
String com.cloudera.impala.analysis.CreateTableStmt.getComment () inline inherited
Definition at line 132 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.comment_.
Referenced by com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql().
String com.cloudera.impala.analysis.CreateTableStmt.getDb () inline inherited
Can only be called after analysis, returns the name of the database the table will be created within.
Definition at line 155 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.dbName_.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.analyze(), com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql(), and com.cloudera.impala.analysis.CreateTableStmt.toThrift().
THdfsFileFormat com.cloudera.impala.analysis.CreateTableStmt.getFileFormat () inline inherited
Definition at line 137 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.fileFormat_.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.analyze(), com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql().
boolean com.cloudera.impala.analysis.CreateTableStmt.getIfNotExists () inline inherited
Definition at line 134 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.ifNotExists_.
Referenced by com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql(), and com.cloudera.impala.analysis.CreateTableStmt.toThrift().
HdfsUri com.cloudera.impala.analysis.CreateTableStmt.getLocation () inline inherited
Definition at line 135 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.location_.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.analyze(), com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql().
String com.cloudera.impala.analysis.CreateTableStmt.getOwner () inline inherited
Can only be called after analysis, returns the owner of this table (the user from the current session).
Definition at line 146 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.owner_.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.toThrift().
List<ColumnDef> com.cloudera.impala.analysis.CreateTableStmt.getPartitionColumnDefs () inline inherited
Definition at line 131 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.partitionColDefs_.
Referenced by com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.analysis.CreateTableStmt.toThrift().
RowFormat com.cloudera.impala.analysis.CreateTableStmt.getRowFormat () inline inherited
Definition at line 138 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.rowFormat_.
Referenced by com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql().
Map<String, String> com.cloudera.impala.analysis.CreateTableStmt.getSerdeProperties () inline inherited
Definition at line 140 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.serdeProperties_.
Referenced by com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql(), and com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql().
String com.cloudera.impala.analysis.CreateTableStmt.getTbl () inline inherited
Definition at line 128 of file CreateTableStmt.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.addTestTable(), com.cloudera.impala.analysis.CreateTableStmt.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql(), and com.cloudera.impala.analysis.CreateTableStmt.toThrift().
TableName com.cloudera.impala.analysis.CreateTableStmt.getTblName () inline inherited
Definition at line 129 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.tableName_.
Referenced by com.cloudera.impala.analysis.CreateTableAsSelectStmt.CreateTableAsSelectStmt().
Map<String, String> com.cloudera.impala.analysis.CreateTableStmt.getTblProperties () inline inherited
Definition at line 139 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.tblProperties_.
Referenced by com.cloudera.impala.analysis.CreateTableDataSrcStmt.analyze(), and com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql().
boolean com.cloudera.impala.analysis.StatementBase.isExplain () inline inherited
Definition at line 43 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
boolean com.cloudera.impala.analysis.CreateTableStmt.isExternal () inline inherited
Definition at line 133 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.isExternal_.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.CreateTableStmt(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.toSql(), and com.cloudera.impala.analysis.CreateTableStmt.toThrift().
void com.cloudera.impala.analysis.StatementBase.setIsExplain () inline inherited
Definition at line 42 of file StatementBase.java.
References com.cloudera.impala.analysis.StatementBase.isExplain_.
void com.cloudera.impala.analysis.CreateTableStmt.setLocation (HdfsUri location) inline inherited
Definition at line 136 of file CreateTableStmt.java.
String com.cloudera.impala.analysis.CreateTableStmt.toSql () inline inherited
Returns
SQL syntax corresponding to this node.
Implements com.cloudera.impala.analysis.ParseNode.
Definition at line 161 of file CreateTableStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.analyzeAvroSchema().
TCreateTableParams com.cloudera.impala.analysis.CreateTableStmt.toThrift () inline inherited
Definition at line 165 of file CreateTableStmt.java.
References com.cloudera.impala.analysis.CreateTableStmt.cachingOp_, com.cloudera.impala.analysis.CreateTableStmt.comment_, com.cloudera.impala.analysis.CreateTableStmt.fileFormat_, com.cloudera.impala.analysis.CreateTableStmt.getColumnDefs(), com.cloudera.impala.analysis.CreateTableStmt.getDb(), com.cloudera.impala.analysis.CreateTableStmt.getIfNotExists(), com.cloudera.impala.analysis.CreateTableStmt.getOwner(), com.cloudera.impala.analysis.CreateTableStmt.getPartitionColumnDefs(), com.cloudera.impala.analysis.CreateTableStmt.getTbl(), com.cloudera.impala.analysis.CreateTableStmt.isExternal(), com.cloudera.impala.analysis.CreateTableStmt.location_, com.cloudera.impala.analysis.CreateTableStmt.serdeProperties_, and com.cloudera.impala.analysis.CreateTableStmt.tblProperties_.
static void com.cloudera.impala.analysis.CreateTableStmt.unescapeProperties (Map< String, String > propertyMap) inline static inherited
Unescapes all values in the property map.
Definition at line 361 of file CreateTableStmt.java.
Referenced by com.cloudera.impala.analysis.CreateTableStmt.CreateTableStmt().
Member Data Documentation
boolean com.cloudera.impala.analysis.StatementBase.isExplain_ = false protected inherited
Definition at line 24 of file StatementBase.java.
Referenced by com.cloudera.impala.analysis.StatementBase.analyze(), com.cloudera.impala.analysis.InsertStmt.analyze(), com.cloudera.impala.analysis.StatementBase.isExplain(), and com.cloudera.impala.analysis.StatementBase.setIsExplain().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/CreateTableDataSrcStmt.java