Impala: com.cloudera.impala.analysis.TypesUtil Class Reference
com.cloudera.impala.analysis.TypesUtil Class Reference
Static Public Member Functions
static int getDecimalSlotSize (ScalarType type)
static ScalarType getContainingIntType (ScalarType decType)
static ScalarType getDecimalAssignmentCompatibleType (ScalarType t1, ScalarType t2)
static Type getArithmeticResultType (Type t1, Type t2, ArithmeticExpr.Operator op) throws AnalysisException
static ScalarType getDecimalArithmeticResultType (Type t1, Type t2, ArithmeticExpr.Operator op) throws AnalysisException
static Type computeDecimalType (BigDecimal v)
Static Package Attributes
static final int DECIMAL_DIVISION_SCALE_INCREMENT = 4
Detailed Description
Definition at line 25 of file TypesUtil.java.
Member Function Documentation
static Type com.cloudera.impala.analysis.TypesUtil.computeDecimalType (BigDecimal v) inline static
Computes the ColumnType that can represent 'v' with no loss of resolution. The scale/precision in BigDecimal is not compatible with SQL decimal semantics (much more like significant figures and exponent). Returns null if the value cannot be represented.
Definition at line 196 of file TypesUtil.java.
References com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, and com.cloudera.impala.catalog.ScalarType.MAX_SCALE.
static Type com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType (Type t1, Type t2, ArithmeticExpr.Operator op) throws AnalysisException inline static
Returns the necessary result type for t1 op t2. Throws an analysis exception if the operation does not make sense for the types.
Definition at line 95 of file TypesUtil.java.
References impala.ADD, impala.DIVIDE, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.analysis.TypesUtil.getDecimalArithmeticResultType(), com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isNull(), impala.MOD, impala.MULTIPLY, com.cloudera.impala.catalog.Type.NULL, and impala.SUBTRACT.
static ScalarType com.cloudera.impala.analysis.TypesUtil.getContainingIntType (ScalarType decType) inline static
Returns the smallest integer type that can store decType without loss of precision. decType must have scale == 0. In the case where the decimal can be bigger than BIGINT, we return BIGINT (and the execution will report it as overflows).
Definition at line 52 of file TypesUtil.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.ScalarType.decimalPrecision(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.SMALLINT, and com.cloudera.impala.catalog.Type.TINYINT.
static ScalarType com.cloudera.impala.analysis.TypesUtil.getDecimalArithmeticResultType (Type t1, Type t2, ArithmeticExpr.Operator op) throws AnalysisException inline static
Returns the resulting typical type from (t1 op t2) These rules are mostly taken from the hive/sql server rules with some changes. http://blogs.msdn.com/b/sqlprogrammability/archive/2006/03/29/564110.aspx
Changes:
Multiply does not need +1 for the result precision.
Divide scale truncation is different.
Definition at line 148 of file TypesUtil.java.
References impala.ADD, com.cloudera.impala.analysis.TypesUtil.DECIMAL_DIVISION_SCALE_INCREMENT, impala.DIVIDE, com.cloudera.impala.catalog.ScalarType.MAX_PRECISION, impala.MOD, impala.MULTIPLY, and impala.SUBTRACT.
Referenced by com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType().
static ScalarType com.cloudera.impala.analysis.TypesUtil.getDecimalAssignmentCompatibleType (ScalarType t1, ScalarType t2) inline static
Returns the decimal type that can hold t1 and t2 without loss of precision. decimal(10, 2) && decimal(12, 2) -> decimal(12, 2) decimal (10, 5) && decimal(12, 3) -> decimal(14, 5) Either t1 or t2 can be a wildcard decimal (but not both).
Definition at line 70 of file TypesUtil.java.
References com.cloudera.impala.catalog.ScalarType.isWildcardDecimal().
Referenced by com.cloudera.impala.analysis.TypesUtilTest.TestDecimalAssignementType().
static int com.cloudera.impala.analysis.TypesUtil.getDecimalSlotSize (ScalarType type) inline static
[1-9] precision -> 4 bytes [10-18] precision -> 8 bytes [19-38] precision -> 16 bytes TODO: Support 12 byte decimal? For precision [20-28], we could support a 12 byte decimal but currently a 12 byte decimal in the BE is not implemented.
Definition at line 39 of file TypesUtil.java.
References com.cloudera.impala.catalog.ScalarType.decimalPrecision(), and com.cloudera.impala.catalog.ScalarType.isWildcardDecimal().
Member Data Documentation
final int com.cloudera.impala.analysis.TypesUtil.DECIMAL_DIVISION_SCALE_INCREMENT = 4 static package
Definition at line 29 of file TypesUtil.java.
Referenced by com.cloudera.impala.analysis.TypesUtil.getDecimalArithmeticResultType().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/TypesUtil.java