Impala: com.cloudera.impala.extdatasource.ExternalDataSourceExecutor Class Reference
com.cloudera.impala.extdatasource.ExternalDataSourceExecutor Class Reference
Public Member Functions
ExternalDataSourceExecutor (String jarPath, String className, String apiVersionStr) throws ImpalaException
byte[] prepare (byte[] thriftParams) throws ImpalaException
byte[] open (byte[] thriftParams) throws ImpalaException
byte[] getNext (byte[] thriftParams) throws ImpalaException
byte[] close (byte[] thriftParams) throws ImpalaException
TPrepareResult prepare (TPrepareParams params)
TOpenResult open (TOpenParams params)
TGetNextResult getNext (TGetNextParams params)
TCloseResult close (TCloseParams params)
Private Member Functions
TStatus logAndMakeErrorStatus (String opName, Exception e)
Private Attributes
final ApiVersion apiVersion_
final ExternalDataSource dataSource_
final String jarPath_
final String className_
Static Private Attributes
static final Logger LOG
static final
TBinaryProtocol.Factory protocolFactory_
Detailed Description
Wraps and executes an ExternalDataSource specified in an external jar. Used in planning to call prepare() and in the backend to fetch results. The executor takes the API version and abstracts the versioning from the caller, e.g. calling the correct API interface and massaging any parameters that can be handled here. There are thrift structures for all param and return types representing the necessary structures. If future versions of the API are added, the executor should be updated to call the appropriate API and handle any differences. It is assumed that the API is updated in a way that backwards compatibility is possible.
Definition at line 58 of file ExternalDataSourceExecutor.java.
Constructor & Destructor Documentation
com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.ExternalDataSourceExecutor (String jarPath, String className, String apiVersionStr) throws ImpalaException inline
Parameters
jarPath The local path to the jar containing the ExternalDataSource.
className The name of the class implementing the ExternalDataSource.
apiVersionStr The API version the ExternalDataSource implements. Must be a valid value of ApiVersion.
Definition at line 75 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.apiVersion_, com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.className_, com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.dataSource_, and com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.jarPath_.
Member Function Documentation
byte [] com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.close (byte[] thriftParams) throws ImpalaException inline
Definition at line 138 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.protocolFactory_.
TCloseResult com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.close (TCloseParams params) inline
Definition at line 194 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.logAndMakeErrorStatus().
byte [] com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.getNext (byte[] thriftParams) throws ImpalaException inline
Definition at line 127 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.protocolFactory_.
TGetNextResult com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.getNext (TGetNextParams params) inline
Definition at line 184 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.logAndMakeErrorStatus().
TStatus com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.logAndMakeErrorStatus (String opName, Exception e) inline private
Definition at line 150 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.className_, and com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.jarPath_.
Referenced by com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.close(), com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.getNext(), com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.open(), and com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.prepare().
byte [] com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.open (byte[] thriftParams) throws ImpalaException inline
Definition at line 116 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.protocolFactory_.
TOpenResult com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.open (TOpenParams params) inline
Definition at line 174 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.logAndMakeErrorStatus().
byte [] com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.prepare (byte[] thriftParams) throws ImpalaException inline
Definition at line 105 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.protocolFactory_.
TPrepareResult com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.prepare (TPrepareParams params) inline
Definition at line 164 of file ExternalDataSourceExecutor.java.
References com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.logAndMakeErrorStatus().
Member Data Documentation
final ApiVersion com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.apiVersion_ private
Definition at line 64 of file ExternalDataSourceExecutor.java.
Referenced by com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.ExternalDataSourceExecutor().
final String com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.className_ private
Definition at line 67 of file ExternalDataSourceExecutor.java.
Referenced by com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.ExternalDataSourceExecutor(), and com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.logAndMakeErrorStatus().
final ExternalDataSource com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.dataSource_ private
Definition at line 65 of file ExternalDataSourceExecutor.java.
Referenced by com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.ExternalDataSourceExecutor().
final String com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.jarPath_ private
Definition at line 66 of file ExternalDataSourceExecutor.java.
Referenced by com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.ExternalDataSourceExecutor(), and com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.logAndMakeErrorStatus().
final Logger com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.LOG static private
Initial value:
= LoggerFactory.getLogger(
      ExternalDataSourceExecutor.class)
Definition at line 59 of file ExternalDataSourceExecutor.java.
final TBinaryProtocol.Factory com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.protocolFactory_ static private
Initial value:
=
      new TBinaryProtocol.Factory()
Definition at line 61 of file ExternalDataSourceExecutor.java.
Referenced by com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.close(), com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.getNext(), com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.open(), and com.cloudera.impala.extdatasource.ExternalDataSourceExecutor.prepare().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/extdatasource/ExternalDataSourceExecutor.java