Impala: impala::HiveUdfCall Class Reference
impala::HiveUdfCall Class Reference
If the UDF ran into an error, the FE throws an exception.
#include <hive-udf-call.h>
Public Member Functions
virtual Status Prepare (RuntimeState *state, const RowDescriptor &row_desc, ExprContext *ctx)
virtual Status Open (RuntimeState *state, ExprContext *context, FunctionContext::FunctionStateScope scope=FunctionContext::FRAGMENT_LOCAL)
virtual void Close (RuntimeState *state, ExprContext *context, FunctionContext::FunctionStateScope scope=FunctionContext::FRAGMENT_LOCAL)
Subclasses overriding this function should call Expr::Close().
virtual BooleanVal GetBooleanVal (ExprContext *ctx, TupleRow *)
virtual TinyIntVal GetTinyIntVal (ExprContext *ctx, TupleRow *)
virtual SmallIntVal GetSmallIntVal (ExprContext *ctx, TupleRow *)
virtual IntVal GetIntVal (ExprContext *ctx, TupleRow *)
virtual BigIntVal GetBigIntVal (ExprContext *ctx, TupleRow *)
virtual FloatVal GetFloatVal (ExprContext *ctx, TupleRow *)
virtual DoubleVal GetDoubleVal (ExprContext *ctx, TupleRow *)
virtual StringVal GetStringVal (ExprContext *ctx, TupleRow *)
virtual TimestampVal GetTimestampVal (ExprContext *ctx, TupleRow *)
virtual DecimalVal GetDecimalVal (ExprContext *ctx, TupleRow *)
virtual Status GetCodegendComputeFn (RuntimeState *state, llvm::Function **fn)
int output_scale () const
void AddChild (Expr *expr)
Expr * GetChild (int i) const
int GetNumChildren () const
const ColumnType & type () const
bool is_slotref () const
const std::vector< Expr * > & children () const
virtual bool IsConstant () const
virtual int GetSlotIds (std::vector< SlotId > *slot_ids) const
virtual AnyVal * GetConstVal (ExprContext *context)
Static Public Member Functions
static Status CreateExprTree (ObjectPool *pool, const TExpr &texpr, ExprContext **ctx)
static Status CreateExprTrees (ObjectPool *pool, const std::vector< TExpr > &texprs, std::vector< ExprContext * > *ctxs)
static Status Prepare (const std::vector< ExprContext * > &ctxs, RuntimeState *state, const RowDescriptor &row_desc, MemTracker *tracker)
static Status Open (const std::vector< ExprContext * > &ctxs, RuntimeState *state)
Convenience function for opening multiple expr trees.
static Status Clone (const std::vector< ExprContext * > &ctxs, RuntimeState *state, std::vector< ExprContext * > *new_ctxs)
static void Close (const std::vector< ExprContext * > &ctxs, RuntimeState *state)
Convenience function for closing multiple expr trees.
static Expr * CreateLiteral (ObjectPool *pool, const ColumnType &type, void *data)
static Expr * CreateLiteral (ObjectPool *pool, const ColumnType &type, const std::string &)
static int ComputeResultsLayout (const std::vector< Expr * > &exprs, std::vector< int > *offsets, int *var_result_begin)
static int ComputeResultsLayout (const std::vector< ExprContext * > &ctxs, std::vector< int > *offsets, int *var_result_begin)
static std::string DebugString (const std::vector< Expr * > &exprs)
static std::string DebugString (const std::vector< ExprContext * > &ctxs)
static void InitBuiltinsDummy ()
Static Public Attributes
static const char * LLVM_CLASS_NAME = "class.impala::Expr"
Protected Member Functions
HiveUdfCall (const TExprNode &node)
virtual std::string DebugString () const
std::string DebugString (const std::string &expr_name) const
Simple debug string that provides no expr subclass-specific information.
FunctionContext * RegisterFunctionContext (ExprContext *ctx, RuntimeState *state, int varargs_buffer_size=0)
llvm::Function * CreateIrFunctionPrototype (LlvmCodeGen *codegen, const std::string &name, llvm::Value *(*args)[2])
Status GetCodegendComputeFnWrapper (RuntimeState *state, llvm::Function **fn)
llvm::Function * GetStaticGetValWrapper (ColumnType type, LlvmCodeGen *codegen)
Protected Attributes
LibCache::LibCacheEntry * cache_entry_
Cache entry for the library implementing this function.
TFunction fn_
Function description.
const bool is_slotref_
recognize if this node is a slotref in order to speed up GetValue()
const ColumnType type_
analysis is done, types are fixed at this point
std::vector< Expr * > children_
int output_scale_
int context_index_
llvm::Function * ir_compute_fn_
Cached codegened compute function. Exprs should set this in GetCodegendComputeFn().
boost::scoped_ptr< AnyVal > constant_val_
Private Member Functions
AnyVal * Evaluate (ExprContext *ctx, TupleRow *row)
Private Attributes
std::string local_location_
The path on the local FS to the UDF's jar.
std::vector< int > input_byte_offsets_
int input_buffer_size_
The size of the buffer for passing in input arguments.
Friends
class Expr
class StringFunctions
Detailed Description
If the UDF ran into an error, the FE throws an exception.
Executor for hive udfs using JNI. This works with the UdfExecutor on the java side which calls into the actual UDF. To minimize the JNI overhead, we eliminate as many copies as possible and share memory between the native side and java side. Memory in the native heap can be read with no issues from java but not vice versa (ptrs in the java heap move). Also, JNI calls are cheaper for function calls with no arguments and no return value (void). During Prepare(), we allocate an input buffer that is big enough to store all of the inputs (i.e. the slot size). This buffer is passed to the UdfExecutor in the constructor. During Evaluate(), the input buffer is populated and the UdfExecutor.evaluate() method is called via JNI. For input arguments, strings don't need to be treated any differently. The java side can parse the ptr and length from the StringValue and then read the ptr directly. For return values that are fixed size (i.e. not strings), we allocate an output buffer in Prepare(). This is also passed to the UdfExecutor in the constructor. The UdfExecutor writes to it directly during evaluate(). For strings, we pass a StringValue sized output buffer to the FE. The address of the StringValue does not change. When the FE writes the string result, it populates the StringValue with the buffer it allocated from its native heap. The BE reads the StringValue as normal.
Definition at line 57 of file hive-udf-call.h.
Constructor & Destructor Documentation
impala::HiveUdfCall::HiveUdfCall (const TExprNode & node) protected
Definition at line 67 of file hive-udf-call.cc.
Member Function Documentation
void impala::Expr::AddChild (Expr * expr) inline inherited
Definition at line 141 of file expr.h.
Referenced by impala::Expr::CreateTreeFromThrift().
const std::vector<Expr*>& impala::Expr::children () const inline inherited
Definition at line 148 of file expr.h.
Referenced by impala::CaseExpr::GetChildVal(), and impala::CaseExpr::GetCodegendComputeFn().
Status Expr::Clone (const std::vector< ExprContext * > & ctxs, RuntimeState * state, std::vector< ExprContext * > * new_ctxs) static inherited
Clones each ExprContext for multiple expr trees. 'new_ctxs' should be an empty vector, and a clone of each context in 'ctxs' will be added to it. The new ExprContexts are created in state->obj_pool().
Definition at line 374 of file expr.cc.
References impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::HdfsScanNode::GetConjunctCtxs(), and impala::SortExecExprs::Open().
void impala::HiveUdfCall::Close (RuntimeState * state, ExprContext * context, FunctionContext::FunctionStateScope scope = FunctionContext::FRAGMENT_LOCAL) virtual
Subclasses overriding this function should call Expr::Close().
If scope if FRAGMENT_LOCAL, both fragment- and thread-local state should be torn down. Otherwise, if scope is THREAD_LOCAL, only thread-local state should be torn down.
Reimplemented from impala::Expr.
Definition at line 232 of file hive-udf-call.cc.
References impala::JniContext::cl, impala::Expr::Close(), impala::JniContext::close_id, impala::Expr::context_index_, impala::JniContext::executor, impala::ExprContext::fn_context(), impala::Status::GetDetail(), impala_udf::FunctionContext::GetFunctionState(), getJNIEnv(), impala::JniUtil::GetJniExceptionMsg(), impala::JniContext::input_nulls_buffer, impala::JniContext::input_values_buffer, impala::Status::ok(), impala::ExprContext::opened_, impala::JniContext::output_anyval, impala::JniContext::output_value_buffer, and VLOG_QUERY.
static void impala::Expr::Close (const std::vector< ExprContext * > & ctxs, RuntimeState * state) static inherited
Convenience function for closing multiple expr trees.
Referenced by impala::UnionNode::Close(), impala::SortExecExprs::Close(), impala::CaseExpr::Close(), impala::HashJoinNode::Close(), impala::AggregationNode::Close(), impala::ScalarFnCall::Close(), impala::ExprContext::Close(), Close(), impala::PartitionedHashJoinNode::Close(), impala::DataStreamSender::Close(), impala::PartitionedAggregationNode::Close(), impala::AggFnEvaluator::Close(), impala::HdfsScanner::Close(), impala::ExecNode::Close(), impala::HdfsScanNode::Close(), impala::HdfsTableSink::Close(), impala::HdfsPartitionDescriptor::CloseExprs(), impala::ImpalaServer::QueryExecState::Done(), impala::OldHashTableTest::TearDown(), and impala::HashTableTest::TearDown().
static int impala::Expr::ComputeResultsLayout (const std::vector< Expr * > & exprs, std::vector< int > * offsets, int * var_result_begin) static inherited
Computes a memory efficient layout for storing the results of evaluating 'exprs' Returns the number of bytes necessary to store all the results and offsets where the result for each expr should be stored. Variable length types are guaranteed to be at the end and 'var_result_begin' will be set the beginning byte offset where variable length results begin. 'var_result_begin' will be set to -1 if there are no variable len types.
Referenced by impala::HashTableCtx::HashTableCtx(), and impala::OldHashTable::OldHashTable().
static int impala::Expr::ComputeResultsLayout (const std::vector< ExprContext * > & ctxs, std::vector< int > * offsets, int * var_result_begin) static inherited
Status Expr::CreateExprTree (ObjectPool * pool, const TExpr & texpr, ExprContext ** ctx) static inherited
Create expression tree from the list of nodes contained in texpr within 'pool'. Returns the root of expression tree in 'expr' and the corresponding ExprContext in 'ctx'.
Definition at line 129 of file expr.cc.
References impala::Expr::CreateTreeFromThrift(), impala::Status::GetDetail(), impala::Status::OK, and impala::Status::ok().
Referenced by impala::Expr::CreateExprTrees(), impala::HdfsPartitionDescriptor::HdfsPartitionDescriptor(), impala::HashJoinNode::Init(), impala::AnalyticEvalNode::Init(), impala::PartitionedHashJoinNode::Init(), and Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs().
Status Expr::CreateExprTrees (ObjectPool * pool, const std::vector< TExpr > & texprs, std::vector< ExprContext * > * ctxs) static inherited
Creates vector of ExprContexts containing exprs from the given vector of TExprs within 'pool'. Returns an error if any of the individual conversions caused an error, otherwise OK.
Definition at line 149 of file expr.cc.
References impala::Expr::CreateExprTree(), impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::DataStreamSender::DataStreamSender(), impala::UnionNode::Init(), impala::HashJoinNode::Init(), impala::AggregationNode::Init(), impala::ExecNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::PartitionedAggregationNode::Init(), impala::HdfsScanNode::Prepare(), and impala::HdfsTableSink::Prepare().
Function * Expr::CreateIrFunctionPrototype (LlvmCodeGen * codegen, const std::string & name, llvm::Value *(*) args[2]) protected inherited
Helper function to create an empty Function* with the appropriate signature to be returned by GetCodegendComputeFn(). 'name' is the name of the returned Function*. The arguments to the function are returned in 'args'.
Definition at line 456 of file expr.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::LlvmCodeGen::FnPrototype::GeneratePrototype(), impala::CodegenAnyVal::GetLoweredType(), impala::LlvmCodeGen::GetPtrType(), impala::TupleRow::LLVM_CLASS_NAME, impala::ExprContext::LLVM_CLASS_NAME, and impala::Expr::type().
Referenced by impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
static Expr* impala::Expr::CreateLiteral (ObjectPool * pool, const ColumnType & type, void * data) static inherited
Create a new literal expr of 'type' with initial 'data'. data should match the ColumnType (i.e. type == TYPE_INT, data is a int*) The new Expr will be allocated from the pool.
static Expr* impala::Expr::CreateLiteral (ObjectPool * pool, const ColumnType & type, const std::string &) static inherited
Create a new literal expr of 'type' by parsing the string. NULL will be returned if the string and type are not compatible. The new Expr will be allocated from the pool.
string impala::HiveUdfCall::DebugString () const protected virtual
Reimplemented from impala::Expr.
Definition at line 275 of file hive-udf-call.cc.
References impala::Expr::DebugString(), and impala::Expr::fn_.
static std::string impala::Expr::DebugString (const std::vector< Expr * > & exprs) static inherited
static std::string impala::Expr::DebugString (const std::vector< ExprContext * > & ctxs) static inherited
std::string impala::Expr::DebugString (const std::string & expr_name) const inline protected inherited
Simple debug string that provides no expr subclass-specific information.
Definition at line 332 of file expr.h.
References impala_udf::DebugString().
AnyVal * impala::HiveUdfCall::Evaluate (ExprContext * ctx, TupleRow * row) private
Evalutes the UDF over row. Returns the result as an AnyVal. This function never returns NULL but rather an AnyVal object with is_null set to true on error.
Definition at line 74 of file hive-udf-call.cc.
References impala_udf::FunctionContext::AddWarning(), impala::JniContext::cl, impala::Expr::context_index_, impala::JniContext::evalute_id, impala::JniContext::executor, impala::Expr::fn_, impala::ExprContext::fn_context(), impala::Expr::GetChild(), impala::Status::GetDetail(), impala_udf::FunctionContext::GetFunctionState(), getJNIEnv(), impala::JniUtil::GetJniExceptionMsg(), impala::Expr::GetNumChildren(), impala::ExprContext::GetValue(), input_byte_offsets_, impala::JniContext::input_nulls_buffer, impala::JniContext::input_values_buffer, impala_udf::AnyVal::is_null, impala::Status::ok(), impala::JniContext::output_anyval, impala::JniContext::output_null_value, impala::JniContext::output_value_buffer, impala::AnyValUtil::SetAnyVal(), impala_udf::FunctionContext::SetError(), impala::Expr::type(), impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, impala::TYPE_VARCHAR, and impala::JniContext::warning_logged.
Referenced by GetBigIntVal(), GetBooleanVal(), GetDecimalVal(), GetDoubleVal(), GetFloatVal(), GetIntVal(), GetSmallIntVal(), GetStringVal(), GetTimestampVal(), and GetTinyIntVal().
BigIntVal impala::HiveUdfCall::GetBigIntVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 303 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_BIGINT.
BooleanVal impala::HiveUdfCall::GetBooleanVal (ExprContext * context, TupleRow * row) virtual
Virtual compute functions for each *Val type. Each Expr subclass should implement the functions for the return type(s) it supports. For example, a boolean function will only implement GetBooleanVal(). Some Exprs, like Literal, have many possible return types and will implement multiple Get*Val() functions.
Reimplemented from impala::Expr.
Definition at line 283 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_BOOLEAN.
Expr* impala::Expr::GetChild (int i) const inline inherited
Definition at line 142 of file expr.h.
Referenced by Evaluate(), and Prepare().
Status impala::HiveUdfCall::GetCodegendComputeFn (RuntimeState * state, llvm::Function ** fn) virtual
Returns an llvm::Function* with signature: <subclass of="" anyval>=""> ComputeFn(ExprContext* context, TupleRow* row) The function should evaluate this expr over 'row' and return the result as the appropriate type of AnyVal.
Implements impala::Expr.
Definition at line 271 of file hive-udf-call.cc.
References impala::Expr::GetCodegendComputeFnWrapper().
Status Expr::GetCodegendComputeFnWrapper (RuntimeState * state, llvm::Function ** fn) protected inherited
Generates an IR compute function that calls the appropriate interpreted Get*Val() compute function. This is useful for builtins that can't be implemented with the UDF interface (e.g. functions that need short-circuiting) and that don't have custom codegen functions that use the IRBuilder. It doesn't provide any performance benefit over the interpreted path. TODO: this should be replaced with fancier xcompiling infrastructure
Definition at line 546 of file expr.cc.
References impala::LlvmCodeGen::CastPtrToLlvmPtr(), impala::LlvmCodeGen::context(), impala::CodegenAnyVal::CreateCall(), impala::Expr::CreateIrFunctionPrototype(), impala::LlvmCodeGen::FinalizeFunction(), impala::RuntimeState::GetCodegen(), impala::LlvmCodeGen::GetPtrType(), impala::Expr::GetStaticGetValWrapper(), impala::Expr::ir_compute_fn_, impala::Expr::LLVM_CLASS_NAME, impala::Status::OK, RETURN_IF_ERROR, and impala::Expr::type().
Referenced by impala::TupleIsNullPredicate::GetCodegendComputeFn(), and GetCodegendComputeFn().
AnyVal * Expr::GetConstVal (ExprContext * context) virtual inherited
If this expr is constant, evaluates the expr with no input row argument and returns the output. Returns NULL if the argument is not constant. The returned AnyVal* is owned by this expr. This should only be called after Open() has been called on this expr.
Definition at line 491 of file expr.cc.
References impala::Expr::constant_val_, impala::Expr::GetBigIntVal(), impala::Expr::GetBooleanVal(), impala::Expr::GetDecimalVal(), impala::Expr::GetDoubleVal(), impala::Expr::GetFloatVal(), impala::Expr::GetIntVal(), impala::Expr::GetSmallIntVal(), impala::Expr::GetStringVal(), impala::Expr::GetTimestampVal(), impala::Expr::GetTinyIntVal(), impala::Expr::IsConstant(), impala::ExprContext::opened_, impala::ColumnType::type, impala::Expr::type(), impala::Expr::type_, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_CHAR, impala::TYPE_DECIMAL, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::ScalarFnCall::Open().
DecimalVal impala::HiveUdfCall::GetDecimalVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 328 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_DECIMAL.
DoubleVal impala::HiveUdfCall::GetDoubleVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 313 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_DOUBLE.
FloatVal impala::HiveUdfCall::GetFloatVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 308 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_FLOAT.
IntVal impala::HiveUdfCall::GetIntVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 298 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_INT.
int impala::Expr::GetNumChildren () const inline inherited
Definition at line 143 of file expr.h.
Referenced by Evaluate(), impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), Open(), impala::ScalarFnCall::Prepare(), and Prepare().
int Expr::GetSlotIds (std::vector< SlotId > * slot_ids) const virtual inherited
Returns the slots that are referenced by this expr tree in 'slot_ids'. Returns the number of slots added to the vector
Reimplemented in impala::SlotRef.
Definition at line 418 of file expr.cc.
References impala::Expr::children_.
SmallIntVal impala::HiveUdfCall::GetSmallIntVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 293 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_SMALLINT.
Function * Expr::GetStaticGetValWrapper (ColumnType type, LlvmCodeGen * codegen) protected inherited
Returns the IR version of the static Get*Val() wrapper function corresponding to 'type'. This is used for calling interpreted Get*Val() functions from codegen'd functions (e.g. in ScalarFnCall() when codegen is disabled).
Definition at line 426 of file expr.cc.
References impala::ColumnType::DebugString(), impala::LlvmCodeGen::GetFunction(), impala::ColumnType::type, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_CHAR, impala::TYPE_DECIMAL, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
StringVal impala::HiveUdfCall::GetStringVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 318 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_STRING.
TimestampVal impala::HiveUdfCall::GetTimestampVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 323 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_TIMESTAMP.
TinyIntVal impala::HiveUdfCall::GetTinyIntVal (ExprContext * ctx, TupleRow * row) virtual
Reimplemented from impala::Expr.
Definition at line 288 of file hive-udf-call.cc.
References Evaluate(), impala::ColumnType::type, impala::Expr::type_, and impala::TYPE_TINYINT.
void Expr::InitBuiltinsDummy () static inherited
The builtin functions are not called from anywhere in the code and the symbols are therefore not included in the binary. We call these functions by using dlsym. The compiler must think this function is callable to not strip these symbols.
Definition at line 470 of file expr.cc.
References impala::Operators::Add_IntVal_IntVal(), impala::CastFunctions::CastToBooleanVal(), impala::DecimalOperators::CastToDecimalVal(), impala::InPredicate::InIterate(), impala::AggregateFunctions::InitNull(), impala::IsNullPredicate::IsNull(), impala::StringFunctions::Length(), impala::LikePredicate::Like(), impala::CompoundPredicate::Not(), impala::ConditionalFunctions::NullIfZero(), impala::UdfBuiltins::Pi(), impala::MathFunctions::Pi(), impala::UtilityFunctions::Pid(), impala::DecimalFunctions::Precision(), and impala::TimestampFunctions::Year().
bool impala::Expr::is_slotref () const inline inherited
Definition at line 146 of file expr.h.
bool Expr::IsConstant () const virtual inherited
Returns true if GetValue(NULL) can be called on this expr and always returns the same result (e.g., exprs that don't contain slotrefs). The default implementation returns true if all children are constant.
Reimplemented in impala::ScalarFnCall, impala::TupleIsNullPredicate, and impala::SlotRef.
Definition at line 411 of file expr.cc.
References impala::Expr::children_.
Referenced by impala::Expr::GetConstVal(), and impala::ScalarFnCall::IsConstant().
Status impala::HiveUdfCall::Open (RuntimeState * state, ExprContext * context, FunctionContext::FunctionStateScope scope = FunctionContext::FRAGMENT_LOCAL) virtual
Initializes 'context' for execution. If scope if FRAGMENT_LOCAL, both fragment- and thread-local state should be initialized. Otherwise, if scope is THREAD_LOCAL, only thread-local state should be initialized. Subclasses overriding this function should call Expr::Open() to recursively call Open() on the expr tree.
Reimplemented from impala::Expr.
Definition at line 176 of file hive-udf-call.cc.
References impala::JniContext::cl, impala::JniContext::close_id, impala::Expr::context_index_, impala::CreateAnyVal(), impala::JniContext::evalute_id, impala::JniContext::executor, EXECUTOR_CLASS, EXECUTOR_CLOSE_SIGNATURE, EXECUTOR_CTOR_SIGNATURE, EXECUTOR_EVALUATE_SIGNATURE, impala::Expr::fn_, impala::ExprContext::fn_context(), impala::JniUtil::GetGlobalClassRef(), getJNIEnv(), impala::Expr::GetNumChildren(), impala::ColumnType::GetSlotSize(), input_buffer_size_, input_byte_offsets_, impala::JniContext::input_nulls_buffer, impala::JniContext::input_values_buffer, local_location_, impala::Status::OK, impala::Expr::Open(), impala::JniContext::output_anyval, impala::JniContext::output_null_value, impala::JniContext::output_value_buffer, impala::JniLocalFrame::push(), RETURN_ERROR_IF_EXC, RETURN_IF_ERROR, impala::SerializeThriftMsg(), impala_udf::FunctionContext::SetFunctionState(), impala::Expr::type(), and impala::Expr::type_.
static Status impala::Expr::Open (const std::vector< ExprContext * > & ctxs, RuntimeState * state) static inherited
Convenience function for opening multiple expr trees.
Referenced by impala::ExprContext::Clone(), impala::HashJoinNode::ConstructBuildSide(), impala::PartitionedHashJoinNode::ConstructBuildSide(), impala::UnionNode::Open(), impala::SortExecExprs::Open(), impala::ExprContext::Open(), impala::CaseExpr::Open(), impala::AggregationNode::Open(), impala::ScalarFnCall::Open(), Open(), impala::DataStreamSender::Open(), impala::ExecNode::Open(), impala::PartitionedAggregationNode::Open(), impala::AggFnEvaluator::Open(), impala::HdfsScanNode::Open(), impala::HdfsTableSink::Open(), impala::Expr::Open(), impala::HdfsPartitionDescriptor::OpenExprs(), impala::HashTableTest::SetUp(), impala::OldHashTableTest::SetUp(), and impala::ImpalaServer::QueryExecState::WaitInternal().
int impala::Expr::output_scale () const inline inherited
Get the number of digits after the decimal that should be displayed for this value. Returns -1 if no scale has been specified (currently the scale is only set for doubles set by RoundUpTo). GetValue() must have already been called. TODO: is this still necessary?
Definition at line 139 of file expr.h.
Status impala::HiveUdfCall::Prepare (RuntimeState * state, const RowDescriptor & row_desc, ExprContext * context) virtual
Initializes this expr instance for execution. This does not include initializing state in the ExprContext; 'context' should only be used to register a FunctionContext via RegisterFunctionContext(). Any IR functions must be generated here. Subclasses overriding this function should call Expr::Prepare() to recursively call Prepare() on the expr tree.
Reimplemented from impala::Expr.
Definition at line 153 of file hive-udf-call.cc.
References impala::Expr::fn_, impala::Expr::GetChild(), impala::Expr::GetNumChildren(), impala::ColumnType::GetSlotSize(), input_buffer_size_, input_byte_offsets_, impala::LibCache::instance(), local_location_, impala::Status::OK, impala::Expr::Prepare(), impala::Expr::RegisterFunctionContext(), RETURN_IF_ERROR, impala::BitUtil::RoundUpNumBytes(), impala::Expr::type(), and impala::LibCache::TYPE_JAR.
static Status impala::Expr::Prepare (const std::vector< ExprContext * > & ctxs, RuntimeState * state, const RowDescriptor & row_desc, MemTracker * tracker) static inherited
Convenience function for preparing multiple expr trees. Allocations from 'ctxs' will be counted against 'tracker'.
Referenced by impala::TupleIsNullPredicate::Prepare(), impala::UnionNode::Prepare(), impala::SortExecExprs::Prepare(), impala::ExprContext::Prepare(), impala::CaseExpr::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::ScalarFnCall::Prepare(), Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::DataStreamSender::Prepare(), impala::ExecNode::Prepare(), impala::AggFnEvaluator::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::Expr::Prepare(), impala::HdfsTableSink::PrepareExprs(), impala::HdfsPartitionDescriptor::PrepareExprs(), impala::HashTableTest::SetUp(), and impala::OldHashTableTest::SetUp().
FunctionContext * Expr::RegisterFunctionContext (ExprContext * ctx, RuntimeState * state, int varargs_buffer_size = 0) protected inherited
Helper function that calls ctx->Register(), sets context_index_, and returns the registered FunctionContext.
Definition at line 80 of file expr.cc.
References impala::AnyValUtil::ColumnTypeToTypeDesc(), impala::ExprContext::fn_context(), and impala::ExprContext::Register().
Referenced by impala::CaseExpr::Prepare(), and Prepare().
const ColumnType& impala::Expr::type () const inline inherited
Definition at line 145 of file expr.h.
Referenced by impala::CaseExpr::AnyValEq(), impala::HdfsParquetTableWriter::BoolColumnWriter::BoolColumnWriter(), impala::AggregationNode::CodegenUpdateSlot(), impala::PartitionedAggregationNode::CodegenUpdateSlot(), impala::HdfsParquetTableWriter::ColumnWriter< T >::ColumnWriter(), impala::Expr::CreateIrFunctionPrototype(), impala::Literal::DebugString(), Evaluate(), impala::ScalarFnCall::EvaluateChildren(), impala::CaseExpr::GetChildVal(), impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::Expr::GetCodegendComputeFnWrapper(), impala::Expr::GetConstVal(), impala::Literal::GetDecimalVal(), impala::ScalarFnCall::GetUdf(), impala::Literal::Literal(), impala::ScalarFnCall::Open(), Open(), impala::ScalarFnCall::Prepare(), Prepare(), and impala::DataStreamSender::Send().
Friends And Related Function Documentation
friend class Expr friend
Definition at line 80 of file hive-udf-call.h.
friend class StringFunctions friend
Definition at line 81 of file hive-udf-call.h.
Member Data Documentation
LibCache::LibCacheEntry* impala::Expr::cache_entry_ protected inherited
Cache entry for the library implementing this function.
Definition at line 281 of file expr.h.
Referenced by impala::Expr::Close(), impala::ScalarFnCall::GetFunction(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::Prepare(), and impala::Expr::~Expr().
std::vector<Expr*> impala::Expr::children_ protected inherited
Definition at line 290 of file expr.h.
Referenced by impala::Expr::Close(), impala::Expr::DebugString(), impala::ScalarFnCall::EvaluateChildren(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::Expr::GetSlotIds(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::InterpretEval(), impala::Expr::IsConstant(), impala::CaseExpr::Open(), impala::ScalarFnCall::Open(), impala::Expr::Open(), impala::SlotRef::Prepare(), impala::TupleIsNullPredicate::Prepare(), impala::ScalarFnCall::Prepare(), and impala::Expr::Prepare().
boost::scoped_ptr<AnyVal> impala::Expr::constant_val_ protected inherited
If this expr is constant, this will store and cache the value generated by GetConstVal().
Definition at line 303 of file expr.h.
Referenced by impala::Expr::GetConstVal().
int impala::Expr::context_index_ protected inherited
Index to pass to ExprContext::fn_context() to retrieve this expr's FunctionContext. Set in RegisterFunctionContext(). -1 if this expr does not need a FunctionContext and doesn't call RegisterFunctionContext().
Definition at line 296 of file expr.h.
Referenced by impala::CaseExpr::Close(), impala::ScalarFnCall::Close(), Close(), Evaluate(), impala::ScalarFnCall::EvaluateChildren(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::ScalarFnCall::InterpretEval(), impala::CaseExpr::Open(), impala::ScalarFnCall::Open(), Open(), and impala::ScalarFnCall::Prepare().
TFunction impala::Expr::fn_ protected inherited
Function description.
Definition at line 284 of file expr.h.
Referenced by impala::ScalarFnCall::DebugString(), DebugString(), Evaluate(), impala::Expr::Expr(), impala::ScalarFnCall::GetFunction(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::IsConstant(), impala::ScalarFnCall::Open(), Open(), impala::ScalarFnCall::Prepare(), Prepare(), and impala::ScalarFnCall::ScalarFnCall().
int impala::HiveUdfCall::input_buffer_size_ private
The size of the buffer for passing in input arguments.
Definition at line 100 of file hive-udf-call.h.
Referenced by Open(), and Prepare().
std::vector<int> impala::HiveUdfCall::input_byte_offsets_ private
input_byte_offsets_[i] is the byte offset child ith's input argument should be written to.
Definition at line 97 of file hive-udf-call.h.
Referenced by Evaluate(), Open(), and Prepare().
llvm::Function* impala::Expr::ir_compute_fn_ protected inherited
Cached codegened compute function. Exprs should set this in GetCodegendComputeFn().
Definition at line 299 of file expr.h.
Referenced by impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
const bool impala::Expr::is_slotref_ protected inherited
recognize if this node is a slotref in order to speed up GetValue()
Definition at line 287 of file expr.h.
const char * Expr::LLVM_CLASS_NAME = "class.impala::Expr" static inherited
Definition at line 232 of file expr.h.
Referenced by impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
std::string impala::HiveUdfCall::local_location_ private
The path on the local FS to the UDF's jar.
Definition at line 93 of file hive-udf-call.h.
Referenced by Open(), and Prepare().
int impala::Expr::output_scale_ protected inherited
Definition at line 291 of file expr.h.
Referenced by impala::ExprContext::GetValue(), and impala::ScalarFnCall::Open().
const ColumnType impala::Expr::type_ protected inherited
analysis is done, types are fixed at this point
Definition at line 289 of file expr.h.
Referenced by impala::Literal::DebugString(), impala::Expr::DebugString(), impala::SlotRef::GetBigIntVal(), impala::Literal::GetBigIntVal(), impala::ScalarFnCall::GetBigIntVal(), GetBigIntVal(), impala::SlotRef::GetBooleanVal(), impala::Literal::GetBooleanVal(), GetBooleanVal(), impala::ScalarFnCall::GetBooleanVal(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::Expr::GetConstVal(), impala::SlotRef::GetDecimalVal(), impala::Literal::GetDecimalVal(), impala::ScalarFnCall::GetDecimalVal(), GetDecimalVal(), impala::SlotRef::GetDoubleVal(), impala::Literal::GetDoubleVal(), impala::ScalarFnCall::GetDoubleVal(), GetDoubleVal(), impala::SlotRef::GetFloatVal(), impala::Literal::GetFloatVal(), impala::ScalarFnCall::GetFloatVal(), GetFloatVal(), impala::SlotRef::GetIntVal(), impala::Literal::GetIntVal(), impala::ScalarFnCall::GetIntVal(), GetIntVal(), impala::SlotRef::GetSmallIntVal(), impala::Literal::GetSmallIntVal(), impala::ScalarFnCall::GetSmallIntVal(), GetSmallIntVal(), impala::SlotRef::GetStringVal(), impala::Literal::GetStringVal(), GetStringVal(), impala::ScalarFnCall::GetStringVal(), impala::SlotRef::GetTimestampVal(), GetTimestampVal(), impala::ScalarFnCall::GetTimestampVal(), impala::SlotRef::GetTinyIntVal(), impala::Literal::GetTinyIntVal(), impala::ScalarFnCall::GetTinyIntVal(), GetTinyIntVal(), impala::ExprContext::GetValue(), impala::Literal::Literal(), impala::ScalarFnCall::Open(), Open(), impala::ScalarFnCall::Prepare(), and impala::Expr::Prepare().
The documentation for this class was generated from the following files:
be/src/exprs/hive-udf-call.h
be/src/exprs/hive-udf-call.cc