Impala: impala::RuntimeProfile::Counter Class Reference
impala::RuntimeProfile::Counter Class Reference
#include <runtime-profile.h>
Public Member Functions
Counter (TUnit::type unit, int64_t value=0)
virtual ~Counter ()
virtual void Add (int64_t delta)
void BitOr (int64_t delta)
Use this to update if the counter is a bitmap.
virtual void Set (int64_t value)
virtual void Set (double value)
virtual int64_t value () const
virtual double double_value () const
TUnit::type unit () const
Protected Attributes
AtomicInt< int64_t > value_
TUnit::type unit_
Friends
class RuntimeProfile
Detailed Description
Definition at line 85 of file runtime-profile.h.
Constructor & Destructor Documentation
impala::RuntimeProfile::Counter::Counter (TUnit::type unit, int64_t value = 0) inline
Definition at line 87 of file runtime-profile.h.
virtual impala::RuntimeProfile::Counter::~Counter () inline virtual
Definition at line 91 of file runtime-profile.h.
Member Function Documentation
virtual void impala::RuntimeProfile::Counter::Add (int64_t delta) inline virtual
Reimplemented in impala::RuntimeProfile::AveragedCounter, and impala::RuntimeProfile::HighWaterMarkCounter.
Definition at line 93 of file runtime-profile.h.
References value_.
Referenced by impala::Sorter::CreateMerger(), impala::BufferedBlockMgr::FindBufferForBlock(), impala::BufferedBlockMgr::GetUnusedBlock(), impala::DiskIoMgr::ReadRange(), impala::ScopedCounter::ScopedCounter(), impala::Sorter::SortRun(), impala::ThreadCounterMeasurement::Stop(), impala::TEST(), impala::ScopedTimer< impala::MonotonicStopWatch >::UpdateCounter(), impala::BufferedBlockMgr::WriteComplete(), impala::BufferedBlockMgr::WriteUnpinnedBlock(), and impala::ScopedCounter::~ScopedCounter().
void impala::RuntimeProfile::Counter::BitOr (int64_t delta) inline
Use this to update if the counter is a bitmap.
Definition at line 98 of file runtime-profile.h.
References value_.
Referenced by impala::DiskIoMgr::ReadRange().
virtual double impala::RuntimeProfile::Counter::double_value () const inline virtual
Definition at line 110 of file runtime-profile.h.
References value_.
Referenced by impala::TEST(), and impala::RuntimeProfile::AveragedCounter::UpdateCounter().
virtual void impala::RuntimeProfile::Counter::Set (int64_t value) inline virtual
Reimplemented in impala::RuntimeProfile::AveragedCounter, and impala::RuntimeProfile::HighWaterMarkCounter.
Definition at line 102 of file runtime-profile.h.
References value(), and value_.
Referenced by impala::BufferedBlockMgr::Init(), impala::PlanFragmentExecutor::SendReport(), impala::HdfsScanNode::StopAndFinalizeCounters(), impala::PeriodicCounterUpdater::StopBucketingCounters(), and impala::TEST().
virtual void impala::RuntimeProfile::Counter::Set (double value) inline virtual
Reimplemented in impala::RuntimeProfile::AveragedCounter.
Definition at line 104 of file runtime-profile.h.
References value(), and value_.
TUnit::type impala::RuntimeProfile::Counter::unit () const inline
Definition at line 114 of file runtime-profile.h.
References unit_.
Referenced by impala::ScopedTimer< impala::MonotonicStopWatch >::ScopedTimer(), impala::TEST(), and impala::RuntimeProfile::UnitsPerSecond().
virtual int64_t impala::RuntimeProfile::Counter::value () const inline virtual
Reimplemented in impala::RuntimeProfile::DerivedCounter.
Definition at line 108 of file runtime-profile.h.
References value_.
Referenced by impala::HdfsScanNode::Close(), impala::RuntimeProfile::ComputeTimeInProfile(), impala::BufferedBlockMgr::DebugInternal(), impala::HdfsScanNode::EnoughMemoryForScannerThread(), impala::Coordinator::BackendExecState::GetNodeThroughput(), impala::Coordinator::BackendExecState::GetNumScanRangesCompleted(), impala::MemTracker::peak_consumption(), impala::HdfsScanNode::ScannerThread(), Set(), impala::HdfsScanNode::StopAndFinalizeCounters(), impala::PeriodicCounterUpdater::StopBucketingCounters(), impala::TEST(), impala::TEST_F(), impala::HdfsScanNode::ThreadTokenAvailableCb(), impala::RuntimeProfile::UnitsPerSecond(), impala::RuntimeProfile::AveragedCounter::UpdateCounter(), and impala::ValidateCounter().
Friends And Related Function Documentation
friend class RuntimeProfile friend
Definition at line 117 of file runtime-profile.h.
Member Data Documentation
TUnit::type impala::RuntimeProfile::Counter::unit_ protected
Definition at line 120 of file runtime-profile.h.
Referenced by unit(), and impala::RuntimeProfile::AveragedCounter::UpdateCounter().
AtomicInt<int64_t> impala::RuntimeProfile::Counter::value_ protected
Definition at line 119 of file runtime-profile.h.
Referenced by Add(), impala::RuntimeProfile::HighWaterMarkCounter::Add(), BitOr(), double_value(), Set(), impala::RuntimeProfile::HighWaterMarkCounter::Set(), impala::RuntimeProfile::HighWaterMarkCounter::TryAdd(), impala::RuntimeProfile::AveragedCounter::UpdateCounter(), and value().
The documentation for this class was generated from the following file:
be/src/util/runtime-profile.h