Impala: impala::HdfsTableDescriptor Class Reference
impala::HdfsTableDescriptor Class Reference
#include <descriptors.h>
Public Types
typedef std::map< int64_t,
HdfsPartitionDescriptor * > PartitionIdToDescriptorMap
Public Member Functions
HdfsTableDescriptor (const TTableDescriptor &tdesc, ObjectPool *pool)
const std::string & hdfs_base_dir () const
const std::string & null_partition_key_value () const
const std::string & null_column_value () const
const std::string & avro_schema () const
HdfsPartitionDescriptor * GetPartition (int64_t partition_id) const
const PartitionIdToDescriptorMap & partition_descriptors () const
virtual std::string DebugString () const
int num_cols () const
int num_clustering_cols () const
bool IsClusteringCol (const SlotDescriptor *slot_desc) const
const std::string & name () const
const std::string & database () const
const std::vector< std::string > & col_names () const
Protected Attributes
std::string hdfs_base_dir_
std::string null_partition_key_value_
std::string null_column_value_
Special string to indicate NULL values in text-encoded columns.
PartitionIdToDescriptorMap partition_descriptors_
std::string avro_schema_
Set to the table's Avro schema if this is an Avro table, empty string otherwise.
ObjectPool * object_pool_
Owned by DescriptorTbl.
std::string name_
std::string database_
TableId id_
int num_cols_
int num_clustering_cols_
std::vector< std::string > col_names_
Detailed Description
Definition at line 226 of file descriptors.h.
Member Typedef Documentation
typedef std::map<int64_t, HdfsPartitionDescriptor*> impala::HdfsTableDescriptor::PartitionIdToDescriptorMap
Definition at line 236 of file descriptors.h.
Constructor & Destructor Documentation
impala::HdfsTableDescriptor::HdfsTableDescriptor (const TTableDescriptor & tdesc, ObjectPool * pool)
Definition at line 173 of file descriptors.cc.
References impala::ObjectPool::Add(), avro_schema_, object_pool_, and partition_descriptors_.
Member Function Documentation
const std::string& impala::HdfsTableDescriptor::avro_schema () const inline
Definition at line 234 of file descriptors.h.
References avro_schema_.
Referenced by impala::HdfsAvroScanner::CodegenMaterializeTuple(), impala::HdfsAvroScanner::ParseMetadata(), and impala::HdfsAvroTableWriter::WriteFileHeader().
const std::vector<std::string>& impala::TableDescriptor::col_names () const inline inherited
Definition at line 165 of file descriptors.h.
References impala::TableDescriptor::col_names_.
Referenced by impala::HdfsParquetTableWriter::AddRowGroup(), impala::HdfsParquetTableWriter::CreateSchema(), impala::HdfsParquetTableWriter::FlushCurrentRowGroup(), impala::HdfsTableSink::InitOutputPartition(), impala::DataSourceScanNode::Open(), impala::HdfsTableSink::PrepareExprs(), and impala::HdfsAvroScanner::VerifyTypesMatch().
const std::string& impala::TableDescriptor::database () const inline inherited
Definition at line 164 of file descriptors.h.
References impala::TableDescriptor::database_.
Referenced by impala::HdfsScanNode::StopAndFinalizeCounters().
string impala::HdfsTableDescriptor::DebugString () const virtual
Reimplemented from impala::TableDescriptor.
Definition at line 190 of file descriptors.cc.
References impala::TableDescriptor::DebugString(), hdfs_base_dir_, null_column_value_, null_partition_key_value_, and partition_descriptors_.
Referenced by impala::HdfsTableSink::DebugString().
HdfsPartitionDescriptor* impala::HdfsTableDescriptor::GetPartition (int64_t partition_id) const inline
Definition at line 238 of file descriptors.h.
References partition_descriptors_.
Referenced by impala::HdfsScanNode::Close(), impala::HdfsScanNode::Open(), and impala::HdfsScanNode::ScannerThread().
const std::string& impala::HdfsTableDescriptor::hdfs_base_dir () const inline
Definition at line 229 of file descriptors.h.
References hdfs_base_dir_.
Referenced by impala::HdfsTableSink::BuildHdfsFileNames(), and impala::HdfsTableSink::Prepare().
bool impala::TableDescriptor::IsClusteringCol (const SlotDescriptor * slot_desc) const inline inherited
The first num_clustering_cols_ columns by position are clustering columns.
Definition at line 158 of file descriptors.h.
References impala::SlotDescriptor::col_path(), and impala::TableDescriptor::num_clustering_cols_.
const std::string& impala::TableDescriptor::name () const inline inherited
Definition at line 163 of file descriptors.h.
References impala::TableDescriptor::name_.
Referenced by impala::HBaseTableWriter::Init(), impala::DataSourceScanNode::Open(), and impala::HdfsScanNode::StopAndFinalizeCounters().
const std::string& impala::HdfsTableDescriptor::null_column_value () const inline
Definition at line 233 of file descriptors.h.
References null_column_value_.
Referenced by impala::HdfsTextTableWriter::AppendRowBatch(), impala::HdfsScanner::CodegenWriteCompleteTuple(), impala::HdfsSequenceTableWriter::EncodeRow(), impala::HdfsTextScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), and impala::HdfsRCFileScanner::Prepare().
const std::string& impala::HdfsTableDescriptor::null_partition_key_value () const inline
Definition at line 230 of file descriptors.h.
References null_partition_key_value_.
Referenced by impala::HdfsTableSink::InitOutputPartition().
int impala::TableDescriptor::num_clustering_cols () const inline inherited
Definition at line 153 of file descriptors.h.
References impala::TableDescriptor::num_clustering_cols_.
Referenced by impala::HdfsParquetTableWriter::AddRowGroup(), impala::HdfsSequenceTableWriter::AppendRowBatch(), impala::HdfsTextTableWriter::AppendRowBatch(), impala::HdfsAvroTableWriter::ConsumeRow(), impala::HdfsParquetTableWriter::CreateSchema(), impala::HdfsSequenceTableWriter::EncodeRow(), impala::HdfsParquetTableWriter::FlushCurrentRowGroup(), impala::HdfsTableWriter::HdfsTableWriter(), impala::HdfsParquetTableWriter::Init(), impala::HdfsScanNode::num_partition_keys(), and impala::HdfsTableSink::PrepareExprs().
int impala::TableDescriptor::num_cols () const inline inherited
Definition at line 152 of file descriptors.h.
References impala::TableDescriptor::num_cols_.
Referenced by impala::HBaseTableWriter::AppendRowBatch(), impala::HdfsSequenceTableWriter::AppendRowBatch(), impala::HdfsTextTableWriter::AppendRowBatch(), impala::HdfsAvroTableWriter::ConsumeRow(), impala::HdfsSequenceTableWriter::EncodeRow(), impala::HdfsTableWriter::HdfsTableWriter(), impala::HBaseTableWriter::Init(), impala::HdfsParquetTableWriter::Init(), impala::HdfsTextScanner::InitNewRange(), impala::HdfsSequenceScanner::InitNewRange(), impala::HdfsRCFileScanner::InitNewRange(), impala::HdfsTableSink::PrepareExprs(), and impala::HdfsAvroScanner::ResolveSchemas().
const PartitionIdToDescriptorMap& impala::HdfsTableDescriptor::partition_descriptors () const inline
Definition at line 245 of file descriptors.h.
References partition_descriptors_.
Referenced by impala::HdfsTableSink::Close(), impala::HdfsTableSink::Open(), and impala::HdfsTableSink::PrepareExprs().
Member Data Documentation
std::string impala::HdfsTableDescriptor::avro_schema_ protected
Set to the table's Avro schema if this is an Avro table, empty string otherwise.
Definition at line 258 of file descriptors.h.
Referenced by avro_schema(), and HdfsTableDescriptor().
std::vector<std::string> impala::TableDescriptor::col_names_ protected inherited
Definition at line 173 of file descriptors.h.
Referenced by impala::TableDescriptor::col_names(), and impala::TableDescriptor::DebugString().
std::string impala::TableDescriptor::database_ protected inherited
Definition at line 169 of file descriptors.h.
Referenced by impala::TableDescriptor::database().
std::string impala::HdfsTableDescriptor::hdfs_base_dir_ protected
Definition at line 252 of file descriptors.h.
Referenced by DebugString(), and hdfs_base_dir().
TableId impala::TableDescriptor::id_ protected inherited
Definition at line 170 of file descriptors.h.
std::string impala::TableDescriptor::name_ protected inherited
Definition at line 168 of file descriptors.h.
Referenced by impala::TableDescriptor::name().
std::string impala::HdfsTableDescriptor::null_column_value_ protected
Special string to indicate NULL values in text-encoded columns.
Definition at line 255 of file descriptors.h.
Referenced by DebugString(), and null_column_value().
std::string impala::HdfsTableDescriptor::null_partition_key_value_ protected
Definition at line 253 of file descriptors.h.
Referenced by DebugString(), and null_partition_key_value().
int impala::TableDescriptor::num_clustering_cols_ protected inherited
Definition at line 172 of file descriptors.h.
Referenced by impala::TableDescriptor::DebugString(), impala::TableDescriptor::IsClusteringCol(), and impala::TableDescriptor::num_clustering_cols().
int impala::TableDescriptor::num_cols_ protected inherited
Definition at line 171 of file descriptors.h.
Referenced by impala::TableDescriptor::DebugString(), and impala::TableDescriptor::num_cols().
ObjectPool* impala::HdfsTableDescriptor::object_pool_ protected
Owned by DescriptorTbl.
Definition at line 260 of file descriptors.h.
Referenced by HdfsTableDescriptor().
PartitionIdToDescriptorMap impala::HdfsTableDescriptor::partition_descriptors_ protected
Definition at line 256 of file descriptors.h.
Referenced by DebugString(), GetPartition(), HdfsTableDescriptor(), and partition_descriptors().
The documentation for this class was generated from the following files:
be/src/runtime/descriptors.h
be/src/runtime/descriptors.cc