Impala: com.cloudera.impala.service.FeSupport Class Reference
com.cloudera.impala.service.FeSupport Class Reference
Static Public Member Functions
static native void NativeFeTestInit ()
static native byte[] NativeEvalConstExprs (byte[] thriftExprBatch, byte[] thriftQueryGlobals)
static native byte[] NativeLookupSymbol (byte[] thriftSymbolLookup)
static native byte[] NativeCacheJar (byte[] thriftCacheJar)
static native byte[] NativePrioritizeLoad (byte[] thriftReq)
static native byte[] NativeGetStartupOptions ()
static TCacheJarResult CacheJar (String hdfsLocation) throws InternalException
static TColumnValue EvalConstExpr (Expr expr, TQueryCtx queryCtx) throws InternalException
static TSymbolLookupResult LookupSymbol (TSymbolLookupParams params) throws InternalException
static boolean EvalPredicate (Expr pred, TQueryCtx queryCtx) throws InternalException
static TResultRow EvalPredicateBatch (ArrayList< Expr > exprs, TQueryCtx queryCtx) throws InternalException
static TStatus PrioritizeLoad (Set< TableName > tableNames) throws InternalException
static TStartupOptions GetStartupOptions () throws InternalException
Static Private Member Functions
static byte[] CacheJar (byte[] thriftParams)
static byte[] LookupSymbol (byte[] thriftParams)
static byte[] EvalConstExprs (byte[] thriftExprBatch, byte[] thriftQueryContext)
static byte[] PrioritizeLoad (byte[] thriftReq)
static synchronized void loadLibrary ()
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(FeSupport.class)
static boolean loaded_ = false
Detailed Description
This class provides the Impala executor functionality to the FE. fe-support.cc implements all the native calls. If the planner is executed inside Impalad, Impalad would have registered all the JNI native functions already. There's no need to load the shared library. For unit test (mvn test), load the shared library because the native function has not been loaded yet.
Definition at line 60 of file FeSupport.java.
Member Function Documentation
static TCacheJarResult com.cloudera.impala.service.FeSupport.CacheJar (String hdfsLocation) throws InternalException inline static
Locally caches the jar at the specified HDFS location.
Parameters
hdfsLocation The path to the jar in HDFS
Returns
The result of the call to cache the jar, includes a status and the local path of the cached jar if the operation was successful.
Definition at line 94 of file FeSupport.java.
static byte [] com.cloudera.impala.service.FeSupport.CacheJar (byte[] thriftParams) inline static private
Definition at line 113 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.loadLibrary(), and com.cloudera.impala.service.FeSupport.NativeCacheJar().
static TColumnValue com.cloudera.impala.service.FeSupport.EvalConstExpr (Expr expr, TQueryCtx queryCtx) throws InternalException inline static
Definition at line 122 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.EvalConstExprs().
Referenced by com.cloudera.impala.service.FeSupport.EvalPredicate().
static byte [] com.cloudera.impala.service.FeSupport.EvalConstExprs (byte[] thriftExprBatch, byte[] thriftQueryContext) inline static private
Definition at line 169 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.loadLibrary(), and com.cloudera.impala.service.FeSupport.NativeEvalConstExprs().
Referenced by com.cloudera.impala.service.FeSupport.EvalConstExpr(), and com.cloudera.impala.service.FeSupport.EvalPredicateBatch().
static boolean com.cloudera.impala.service.FeSupport.EvalPredicate (Expr pred, TQueryCtx queryCtx) throws InternalException inline static
Definition at line 179 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.EvalConstExpr().
Referenced by com.cloudera.impala.analysis.Analyzer.markConstantConjunct().
static TResultRow com.cloudera.impala.service.FeSupport.EvalPredicateBatch (ArrayList< Expr > exprs, TQueryCtx queryCtx) throws InternalException inline static
Evaluate a batch of predicates in the BE. The results are stored in a TResultRow object, where each TColumnValue in it stores the result of a predicate evaluation.
TODO: This function is currently used for improving the performance of partition pruning (see IMPALA-887), hence it only supports boolean exprs. In the future, we can extend it to support arbitrary constant exprs.
Definition at line 199 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.EvalConstExprs().
static TStartupOptions com.cloudera.impala.service.FeSupport.GetStartupOptions () throws InternalException inline static
Definition at line 263 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.NativeGetStartupOptions().
static synchronized void com.cloudera.impala.service.FeSupport.loadLibrary () inline static private
This function should only be called explicitly by the FeSupport to ensure that native functions are loaded.
Definition at line 281 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.loaded_, and com.cloudera.impala.service.FeSupport.NativeFeTestInit().
Referenced by com.cloudera.impala.service.FeSupport.CacheJar(), com.cloudera.impala.service.FeSupport.EvalConstExprs(), com.cloudera.impala.service.FeSupport.LookupSymbol(), and com.cloudera.impala.service.FeSupport.PrioritizeLoad().
static byte [] com.cloudera.impala.service.FeSupport.LookupSymbol (byte[] thriftParams) inline static private
Definition at line 144 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.loadLibrary(), and com.cloudera.impala.service.FeSupport.NativeLookupSymbol().
Referenced by com.cloudera.impala.service.FeSupport.LookupSymbol().
static TSymbolLookupResult com.cloudera.impala.service.FeSupport.LookupSymbol (TSymbolLookupParams params) throws InternalException inline static
Definition at line 153 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.LookupSymbol().
static native byte [] com.cloudera.impala.service.FeSupport.NativeCacheJar (byte[] thriftCacheJar) static
Referenced by com.cloudera.impala.service.FeSupport.CacheJar().
static native byte [] com.cloudera.impala.service.FeSupport.NativeEvalConstExprs (byte[] thriftExprBatch, byte[] thriftQueryGlobals) static
Referenced by com.cloudera.impala.service.FeSupport.EvalConstExprs().
static native void com.cloudera.impala.service.FeSupport.NativeFeTestInit () static
Referenced by com.cloudera.impala.service.FeSupport.loadLibrary().
static native byte [] com.cloudera.impala.service.FeSupport.NativeGetStartupOptions () static
Referenced by com.cloudera.impala.service.FeSupport.GetStartupOptions().
static native byte [] com.cloudera.impala.service.FeSupport.NativeLookupSymbol (byte[] thriftSymbolLookup) static
Referenced by com.cloudera.impala.service.FeSupport.LookupSymbol().
static native byte [] com.cloudera.impala.service.FeSupport.NativePrioritizeLoad (byte[] thriftReq) static
Referenced by com.cloudera.impala.service.FeSupport.PrioritizeLoad().
static byte [] com.cloudera.impala.service.FeSupport.PrioritizeLoad (byte[] thriftReq) inline static private
Definition at line 224 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.loadLibrary(), and com.cloudera.impala.service.FeSupport.NativePrioritizeLoad().
Referenced by com.cloudera.impala.service.FeSupport.PrioritizeLoad().
static TStatus com.cloudera.impala.service.FeSupport.PrioritizeLoad (Set< TableName > tableNames) throws InternalException inline static
Definition at line 233 of file FeSupport.java.
References com.cloudera.impala.service.FeSupport.PrioritizeLoad().
Member Data Documentation
boolean com.cloudera.impala.service.FeSupport.loaded_ = false static private
Definition at line 62 of file FeSupport.java.
Referenced by com.cloudera.impala.service.FeSupport.loadLibrary().
final Logger com.cloudera.impala.service.FeSupport.LOG = LoggerFactory.getLogger(FeSupport.class) static private
Definition at line 61 of file FeSupport.java.
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/service/FeSupport.java