Impala: com.cloudera.impala.catalog.StructType Class Reference
com.cloudera.impala.catalog.StructType Class Reference
Public Member Functions
StructType (ArrayList< StructField > fields)
StructType ()
String toSql ()
void addField (StructField field)
ArrayList< StructField > getFields ()
StructField getField (String fieldName)
void clearFields ()
boolean equals (Object other)
void toThrift (TColumnType container)
boolean isInvalid ()
boolean isValid ()
boolean isNull ()
boolean isBoolean ()
boolean isTimestamp ()
boolean isDecimal ()
boolean isDecimalOrNull ()
boolean isFullySpecifiedDecimal ()
boolean isWildcardDecimal ()
boolean isWildcardVarchar ()
boolean isWildcardChar ()
boolean isStringType ()
boolean isScalarType ()
boolean isScalarType (PrimitiveType t)
boolean isFixedPointType ()
boolean isFloatingPointType ()
boolean isIntegerType ()
boolean isFixedLengthType ()
boolean isNumericType ()
boolean isDateType ()
boolean isComplexType ()
boolean isCollectionType ()
boolean isMapType ()
boolean isArrayType ()
boolean isStructType ()
boolean isSupported ()
boolean supportsTablePartitioning ()
PrimitiveType getPrimitiveType ()
int getSlotSize ()
TColumnType toThrift ()
boolean matchesType (Type t)
TPrimitiveType getTPrimitiveType (TColumnType ttype)
Integer getColumnSize ()
Integer getPrecision ()
Integer getDecimalDigits ()
Integer getNumPrecRadix ()
int getJavaSqlType ()
Static Public Member Functions
static ArrayList< ScalarType > getIntegerTypes ()
static ArrayList< ScalarType > getNumericTypes ()
static ArrayList< ScalarType > getSupportedTypes ()
static List< TColumnType > toThrift (Type[] types)
static List< TColumnType > toThrift (ArrayList< Type > types)
static Type parseColumnType (FieldSchema fs)
static boolean isImplicitlyCastable (Type t1, Type t2)
static Type getAssignmentCompatibleType (Type t1, Type t2)
static Type fromThrift (TColumnType thrift)
Static Public Attributes
static final ScalarType INVALID = new ScalarType(PrimitiveType.INVALID_TYPE)
static final ScalarType NULL = new ScalarType(PrimitiveType.NULL_TYPE)
static final ScalarType BOOLEAN = new ScalarType(PrimitiveType.BOOLEAN)
static final ScalarType TINYINT = new ScalarType(PrimitiveType.TINYINT)
static final ScalarType SMALLINT = new ScalarType(PrimitiveType.SMALLINT)
static final ScalarType INT = new ScalarType(PrimitiveType.INT)
static final ScalarType BIGINT = new ScalarType(PrimitiveType.BIGINT)
static final ScalarType FLOAT = new ScalarType(PrimitiveType.FLOAT)
static final ScalarType DOUBLE = new ScalarType(PrimitiveType.DOUBLE)
static final ScalarType STRING = new ScalarType(PrimitiveType.STRING)
static final ScalarType BINARY = new ScalarType(PrimitiveType.BINARY)
static final ScalarType TIMESTAMP = new ScalarType(PrimitiveType.TIMESTAMP)
static final ScalarType DATE = new ScalarType(PrimitiveType.DATE)
static final ScalarType DATETIME = new ScalarType(PrimitiveType.DATETIME)
static final ScalarType DEFAULT_DECIMAL
static final ScalarType DECIMAL
static final ScalarType DEFAULT_VARCHAR = ScalarType.createVarcharType(-1)
static final ScalarType VARCHAR = ScalarType.createVarcharType(-1)
static final ScalarType CHAR = (ScalarType) ScalarType.createCharType(-1)
Static Protected Member Functions
static Pair< Type, Integer > fromThrift (TColumnType col, int nodeIdx)
Static Protected Attributes
static PrimitiveType[][] compatibilityMatrix
Static Package Functions
[static initializer]
[static initializer]
Private Attributes
final HashMap< String,
StructField > fieldMap_ = Maps.newHashMap()
final ArrayList< StructField > fields_
Detailed Description
Describes a STRUCT type. STRUCT types have a list of named struct fields.
Definition at line 18 of file StructType.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.StructType.StructType (ArrayList< StructField > fields) inline
Definition at line 22 of file StructType.java.
References com.cloudera.impala.catalog.StructType.fields_.
com.cloudera.impala.catalog.StructType.StructType () inline
Definition at line 31 of file StructType.java.
References com.cloudera.impala.catalog.StructType.fields_.
Referenced by com.cloudera.impala.catalog.StructType.equals().
Member Function Documentation
com.cloudera.impala.catalog.Type.[static initializer] () inline static package inherited
com.cloudera.impala.catalog.Type.[static initializer] () inline static package inherited
void com.cloudera.impala.catalog.StructType.addField (StructField field) inline
Definition at line 44 of file StructType.java.
void com.cloudera.impala.catalog.StructType.clearFields () inline
Definition at line 56 of file StructType.java.
boolean com.cloudera.impala.catalog.StructType.equals (Object other) inline
Definition at line 62 of file StructType.java.
References com.cloudera.impala.catalog.StructType.fields_, and com.cloudera.impala.catalog.StructType.StructType().
static Type com.cloudera.impala.catalog.Type.fromThrift (TColumnType thrift) inline static inherited
Definition at line 293 of file Type.java.
Referenced by com.cloudera.impala.catalog.Column.fromThrift(), com.cloudera.impala.catalog.Type.fromThrift(), and com.cloudera.impala.catalog.Function.fromThrift().
static Pair<Type, Integer> com.cloudera.impala.catalog.Type.fromThrift (TColumnType col, int nodeIdx) inline static protected inherited
Constructs a ColumnType rooted at the TTypeNode at nodeIdx in TColumnType. Returned pair: The resulting ColumnType and the next nodeIdx that is not a child type of the result.
Definition at line 305 of file Type.java.
References com.cloudera.impala.catalog.Type.fromThrift(), and impala.name.
static Type com.cloudera.impala.catalog.Type.getAssignmentCompatibleType (Type t1, Type t2) inline static inherited
Return type t such that values from both t1 and t2 can be assigned to t without loss of precision. Returns INVALID_TYPE if there is no such type or if any of t1 and t2 is INVALID_TYPE. TODO: Support non-scalar types.
Definition at line 273 of file Type.java.
References com.cloudera.impala.catalog.Type.INVALID, and com.cloudera.impala.catalog.Type.isScalarType().
Integer com.cloudera.impala.catalog.Type.getColumnSize () inline inherited
JDBC data type description Returns the column size for this type. For numeric data this is the maximum precision. For character data this is the length in characters. For datetime types this is the length in characters of the String representation (assuming the maximum allowed precision of the fractional seconds component). For binary data this is the length in bytes. Null is returned for for data types where the column size is not applicable.
Definition at line 385 of file Type.java.
References com.cloudera.impala.catalog.Type.CHAR, com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.isNumericType(), com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.Type.TIMESTAMP, and com.cloudera.impala.catalog.Type.VARCHAR.
Integer com.cloudera.impala.catalog.Type.getDecimalDigits () inline inherited
JDBC data type description Returns the number of fractional digits for this type, or null if not applicable. For timestamp/time types, returns the number of digits in the fractional seconds component.
Definition at line 436 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.TIMESTAMP, and com.cloudera.impala.catalog.Type.TINYINT.
StructField com.cloudera.impala.catalog.StructType.getField (String fieldName) inline
Definition at line 52 of file StructType.java.
Referenced by com.cloudera.impala.analysis.CollectionStructType.CollectionStructType().
ArrayList<StructField> com.cloudera.impala.catalog.StructType.getFields () inline
Definition at line 50 of file StructType.java.
References com.cloudera.impala.catalog.StructType.fields_.
static ArrayList<ScalarType> com.cloudera.impala.catalog.Type.getIntegerTypes () inline static inherited
Definition at line 103 of file Type.java.
References com.cloudera.impala.catalog.Type.integerTypes.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins().
int com.cloudera.impala.catalog.Type.getJavaSqlType () inline inherited
JDBC data type description Returns the java SQL type enum
Definition at line 493 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.BINARY, com.cloudera.impala.catalog.Type.BOOLEAN, com.cloudera.impala.catalog.Type.CHAR, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), impala.name, com.cloudera.impala.catalog.Type.SMALLINT, com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.Type.TIMESTAMP, com.cloudera.impala.catalog.Type.TINYINT, com.cloudera.impala.catalog.Type.toSql(), and com.cloudera.impala.catalog.Type.VARCHAR.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults().
static ArrayList<ScalarType> com.cloudera.impala.catalog.Type.getNumericTypes () inline static inherited
Definition at line 106 of file Type.java.
References com.cloudera.impala.catalog.Type.numericTypes.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins().
Integer com.cloudera.impala.catalog.Type.getNumPrecRadix () inline inherited
JDBC data type description For numeric data types, either 10 or 2. If it is 10, the values in COLUMN_SIZE and DECIMAL_DIGITS give the number of decimal digits allowed for the column. For example, a DECIMAL(12,5) column would return a NUM_PREC_RADIX of 10, a COLUMN_SIZE of 12, and a DECIMAL_DIGITS of 5; a FLOAT column could return a NUM_PREC_RADIX of 10, a COLUMN_SIZE of 15, and a DECIMAL_DIGITS of NULL. If it is 2, the values in COLUMN_SIZE and DECIMAL_DIGITS give the number of bits allowed in the column. For example, a FLOAT column could return a RADIX of 2, a COLUMN_SIZE of 53, and a DECIMAL_DIGITS of NULL. NULL is returned for data types where NUM_PREC_RADIX is not applicable.
Definition at line 471 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.SMALLINT, and com.cloudera.impala.catalog.Type.TINYINT.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults().
Integer com.cloudera.impala.catalog.Type.getPrecision () inline inherited
JDBC data type description For numeric types, returns the maximum precision for this type. For non-numeric types, returns null.
Definition at line 407 of file Type.java.
References com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.FLOAT, com.cloudera.impala.catalog.ScalarType.getPrimitiveType(), com.cloudera.impala.catalog.Type.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.SMALLINT, and com.cloudera.impala.catalog.Type.TINYINT.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), and com.cloudera.impala.catalog.Type.getColumnSize().
PrimitiveType com.cloudera.impala.catalog.Type.getPrimitiveType () inline inherited
Definition at line 188 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.INVALID_TYPE.
Referenced by com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.service.CatalogOpExecutor.createHiveColStatsData(), com.cloudera.impala.catalog.Function.getUdfType(), com.cloudera.impala.catalog.DataSourceTable.isSupportedColumnType(), com.cloudera.impala.hive.executor.UdfExecutor.storeUdfResult(), com.cloudera.impala.hive.executor.UdfExecutorTest.TestUdfImpl(), com.cloudera.impala.analysis.NumericLiteral.toThrift(), com.cloudera.impala.catalog.ColumnStats.update(), and com.cloudera.impala.analysis.TypesUtilTest.verifyDecimalType().
int com.cloudera.impala.catalog.Type.getSlotSize () inline inherited
Returns the size in bytes of the fixed-length portion that a slot of this type occupies in a tuple.
Definition at line 194 of file Type.java.
References com.cloudera.impala.catalog.Type.isCollectionType(), and com.cloudera.impala.catalog.Type.toSql().
static ArrayList<ScalarType> com.cloudera.impala.catalog.Type.getSupportedTypes () inline static inherited
Definition at line 109 of file Type.java.
References com.cloudera.impala.catalog.Type.supportedTypes.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.InPredicate.initBuiltins(), com.cloudera.impala.analysis.IsNullPredicate.initBuiltins(), com.cloudera.impala.analysis.BinaryPredicate.initBuiltins(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.analysis.CaseExpr.initBuiltins(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCasts(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts().
TPrimitiveType com.cloudera.impala.catalog.Type.getTPrimitiveType (TColumnType ttype) inline inherited
Utility function to get the primitive type of a thrift type that is known to be scalar.
Definition at line 369 of file Type.java.
boolean com.cloudera.impala.catalog.Type.isArrayType () inline inherited
Definition at line 173 of file Type.java.
Referenced by com.cloudera.impala.analysis.Path.getTypeAsStruct(), and com.cloudera.impala.catalog.Type.isCollectionType().
boolean com.cloudera.impala.catalog.Type.isBoolean () inline inherited
Definition at line 124 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.BOOLEAN, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.analysis.Expr.checkReturnsBool().
boolean com.cloudera.impala.catalog.Type.isCollectionType () inline inherited
Definition at line 171 of file Type.java.
References com.cloudera.impala.catalog.Type.isArrayType(), and com.cloudera.impala.catalog.Type.isMapType().
Referenced by com.cloudera.impala.catalog.Type.getSlotSize(), and com.cloudera.impala.catalog.Type.isComplexType().
boolean com.cloudera.impala.catalog.Type.isComplexType () inline inherited
Definition at line 170 of file Type.java.
References com.cloudera.impala.catalog.Type.isCollectionType(), and com.cloudera.impala.catalog.Type.isStructType().
Referenced by com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.catalog.ScalarType.supportsTablePartitioning(), and com.cloudera.impala.analysis.AnalyzeDDLTest.TypeDefsAnalyzeOk().
boolean com.cloudera.impala.catalog.Type.isDateType () inline inherited
Definition at line 165 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.DATE, com.cloudera.impala.catalog.PrimitiveType.DATETIME, com.cloudera.impala.catalog.Type.isScalarType(), and com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP.
boolean com.cloudera.impala.catalog.Type.isDecimal () inline inherited
Definition at line 126 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.DECIMAL, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.Expr.convertNumericLiteralsFromDecimal(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.planner.HashJoinNode.init(), com.cloudera.impala.catalog.Type.isDecimalOrNull(), com.cloudera.impala.catalog.ScalarType.isFullySpecifiedDecimal(), com.cloudera.impala.catalog.Type.isNumericType(), com.cloudera.impala.catalog.ScalarType.isSupertypeOf(), com.cloudera.impala.catalog.ScalarType.matchesType(), and com.cloudera.impala.analysis.NumericLiteral.NumericLiteral().
boolean com.cloudera.impala.catalog.Type.isDecimalOrNull () inline inherited
Definition at line 127 of file Type.java.
References com.cloudera.impala.catalog.Type.isDecimal(), and com.cloudera.impala.catalog.Type.isNull().
boolean com.cloudera.impala.catalog.Type.isFixedLengthType () inline inherited
Definition at line 159 of file Type.java.
Referenced by com.cloudera.impala.catalog.ColumnStats.initColStats().
boolean com.cloudera.impala.catalog.Type.isFixedPointType () inline inherited
Definition at line 143 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.BIGINT, com.cloudera.impala.catalog.PrimitiveType.DECIMAL, com.cloudera.impala.catalog.PrimitiveType.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.PrimitiveType.SMALLINT, and com.cloudera.impala.catalog.PrimitiveType.TINYINT.
Referenced by com.cloudera.impala.catalog.Type.isNumericType().
boolean com.cloudera.impala.catalog.Type.isFloatingPointType () inline inherited
Definition at line 149 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.DOUBLE, com.cloudera.impala.catalog.PrimitiveType.FLOAT, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), and com.cloudera.impala.catalog.Type.isNumericType().
boolean com.cloudera.impala.catalog.Type.isFullySpecifiedDecimal () inline inherited
Definition at line 128 of file Type.java.
static boolean com.cloudera.impala.catalog.Type.isImplicitlyCastable (Type t1, Type t2) inline static inherited
Returns true if casting t1 to t2 results in no loss of precision, false otherwise. TODO: Support casting of non-scalar types.
Definition at line 259 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.AnalyticExpr.checkRangeOffsetBoundaryExpr(), and com.cloudera.impala.catalog.Function.isSuperTypeOf().
boolean com.cloudera.impala.catalog.Type.isIntegerType () inline inherited
Definition at line 153 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.BIGINT, com.cloudera.impala.catalog.PrimitiveType.INT, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.PrimitiveType.SMALLINT, and com.cloudera.impala.catalog.PrimitiveType.TINYINT.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), and com.cloudera.impala.catalog.HBaseTable.supportsBinaryEncoding().
boolean com.cloudera.impala.catalog.Type.isInvalid () inline inherited
Definition at line 121 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.INVALID_TYPE, and com.cloudera.impala.catalog.Type.isScalarType().
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), and com.cloudera.impala.catalog.Type.isValid().
boolean com.cloudera.impala.catalog.Type.isMapType () inline inherited
Definition at line 172 of file Type.java.
Referenced by com.cloudera.impala.catalog.Type.isCollectionType().
boolean com.cloudera.impala.catalog.Type.isNull () inline inherited
Definition at line 123 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType(), and com.cloudera.impala.catalog.PrimitiveType.NULL_TYPE.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.analysis.Expr.getResolvedWildCardType(), com.cloudera.impala.catalog.Type.isDecimalOrNull(), com.cloudera.impala.catalog.Function.isIndistinguishable(), com.cloudera.impala.analysis.Expr.treeToThrift(), com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest(), and com.cloudera.impala.analysis.SlotRef.uncheckedCastTo().
boolean com.cloudera.impala.catalog.Type.isNumericType () inline inherited
Definition at line 161 of file Type.java.
References com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isFixedPointType(), and com.cloudera.impala.catalog.Type.isFloatingPointType().
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.catalog.Type.getColumnSize(), and com.cloudera.impala.catalog.ScalarType.getNextResolutionType().
boolean com.cloudera.impala.catalog.Type.isScalarType () inline inherited
Definition at line 138 of file Type.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.catalog.Type.getAssignmentCompatibleType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.Type.isBoolean(), com.cloudera.impala.catalog.Type.isDateType(), com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.Type.isFixedPointType(), com.cloudera.impala.catalog.Type.isFloatingPointType(), com.cloudera.impala.catalog.Type.isImplicitlyCastable(), com.cloudera.impala.catalog.Type.isIntegerType(), com.cloudera.impala.catalog.Type.isInvalid(), com.cloudera.impala.catalog.Type.isNull(), com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.Type.isStringType(), com.cloudera.impala.catalog.ColumnStats.isSupportedColType(), com.cloudera.impala.catalog.Type.isTimestamp(), com.cloudera.impala.catalog.ScalarType.matchesType(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts().
boolean com.cloudera.impala.catalog.Type.isScalarType (PrimitiveType t) inline inherited
Definition at line 139 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType().
boolean com.cloudera.impala.catalog.Type.isStringType () inline inherited
Definition at line 133 of file Type.java.
References com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.Type.isScalarType(), com.cloudera.impala.catalog.PrimitiveType.STRING, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.analysis.ComputeStatsStmt.getBaseColumnStatsQuerySelectList(), and com.cloudera.impala.planner.HashJoinNode.init().
boolean com.cloudera.impala.catalog.Type.isStructType () inline inherited
Definition at line 174 of file Type.java.
Referenced by com.cloudera.impala.analysis.Path.getTypeAsStruct(), and com.cloudera.impala.catalog.Type.isComplexType().
boolean com.cloudera.impala.catalog.Type.isSupported () inline inherited
Returns true if Impala supports this type in the metdata. It does not mean we can manipulate data of this type. For tables that contain columns with these types, we can safely skip over them.
Definition at line 181 of file Type.java.
boolean com.cloudera.impala.catalog.Type.isTimestamp () inline inherited
Definition at line 125 of file Type.java.
References com.cloudera.impala.catalog.Type.isScalarType(), and com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP.
boolean com.cloudera.impala.catalog.Type.isValid () inline inherited
Definition at line 122 of file Type.java.
References com.cloudera.impala.catalog.Type.isInvalid().
Referenced by com.cloudera.impala.analysis.PartitionSpec.analyze(), com.cloudera.impala.analysis.InsertStmt.checkTypeCompatibility(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.analysis.ComputeStatsStmt.getBaseColumnStatsQuerySelectList(), and com.cloudera.impala.analysis.Analyzer.getCompatibleType().
boolean com.cloudera.impala.catalog.Type.isWildcardChar () inline inherited
Definition at line 131 of file Type.java.
Referenced by com.cloudera.impala.analysis.FunctionCallExpr.analyze().
boolean com.cloudera.impala.catalog.Type.isWildcardDecimal () inline inherited
Definition at line 129 of file Type.java.
Referenced by com.cloudera.impala.analysis.AggregateInfoBase.createTupleDesc(), com.cloudera.impala.analysis.Expr.getResolvedWildCardType(), and com.cloudera.impala.analysis.FunctionCallExpr.resolveDecimalReturnType().
boolean com.cloudera.impala.catalog.Type.isWildcardVarchar () inline inherited
Definition at line 130 of file Type.java.
boolean com.cloudera.impala.catalog.Type.matchesType (Type t) inline inherited
Returns true if this type is equal to t, or if t is a wildcard variant of this type. Subclasses should override this as appropriate. The default implementation here is to avoid special-casing logic in callers for concrete types.
Definition at line 218 of file Type.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.castChild(), com.cloudera.impala.planner.HashJoinNode.init(), com.cloudera.impala.catalog.Function.isIdentical(), com.cloudera.impala.catalog.Function.isIndistinguishable(), and com.cloudera.impala.catalog.Function.isSuperTypeOf().
static Type com.cloudera.impala.catalog.Type.parseColumnType (FieldSchema fs) inline static inherited
Gets the ColumnType from the given FieldSchema by using Impala's SqlParser. Returns null if the FieldSchema could not be parsed. The type can either be:
Supported by Impala, in which case the type is returned.
A type Impala understands but is not yet implemented (e.g. date), the type is returned but type.IsSupported() returns false.
A type Impala can't understand at all in which case null is returned.
Definition at line 229 of file Type.java.
References com.cloudera.impala.analysis.CreateTableStmt.getColumnDefs(), and gen_ir_descriptions.parser.
boolean com.cloudera.impala.catalog.Type.supportsTablePartitioning () inline inherited
Indicates whether we support partitioning tables on columns of this type.
Definition at line 186 of file Type.java.
Referenced by com.cloudera.impala.catalog.HdfsTable.loadColumns().
String com.cloudera.impala.catalog.StructType.toSql () inline
Definition at line 36 of file StructType.java.
References com.cloudera.impala.catalog.StructType.fields_.
void com.cloudera.impala.catalog.StructType.toThrift (TColumnType container) inline
Definition at line 69 of file StructType.java.
References com.cloudera.impala.catalog.StructType.fields_.
TColumnType com.cloudera.impala.catalog.Type.toThrift () inline inherited
Definition at line 201 of file Type.java.
Referenced by com.cloudera.impala.catalog.HBaseColumn.toThrift(), com.cloudera.impala.analysis.ColumnDef.toThrift(), com.cloudera.impala.catalog.Column.toThrift(), and com.cloudera.impala.catalog.Type.toThrift().
static List<TColumnType> com.cloudera.impala.catalog.Type.toThrift (Type[] types) inline static inherited
Definition at line 281 of file Type.java.
References com.cloudera.impala.catalog.Type.toThrift().
static List<TColumnType> com.cloudera.impala.catalog.Type.toThrift (ArrayList< Type > types) inline static inherited
Definition at line 285 of file Type.java.
Member Data Documentation
final ScalarType com.cloudera.impala.catalog.Type.BIGINT = new ScalarType(PrimitiveType.BIGINT) static inherited
Definition at line 50 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.analysis.CollectionStructType.createArrayStructType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.DataSourceTable.getTableStats(), com.cloudera.impala.catalog.HBaseTable.getTableStats(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.HdfsPartitionTest.HdfsPartitionTest(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.QueryStmt.setLimit(), com.cloudera.impala.analysis.AnalyticExpr.standardize(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeSubqueriesTest.TestAggregateSubqueries(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.catalog.HdfsPartitionTest.testCompare(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution().
final ScalarType com.cloudera.impala.catalog.Type.BINARY = new ScalarType(PrimitiveType.BINARY) static inherited
Definition at line 54 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.isSupported(), and com.cloudera.impala.catalog.ScalarType.toSql().
final ScalarType com.cloudera.impala.catalog.Type.BOOLEAN = new ScalarType(PrimitiveType.BOOLEAN) static inherited
Definition at line 46 of file Type.java.
Referenced by com.cloudera.impala.analysis.Predicate< com.cloudera.impala.analysis.Expr >.analyze(), com.cloudera.impala.analysis.IsNullPredicate.analyze(), com.cloudera.impala.analysis.InPredicate.analyze(), com.cloudera.impala.analysis.CaseExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.BoolLiteral.BoolLiteral(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.AuthorizationPolicy.getRolePrivileges(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.analysis.InPredicate.initBuiltins(), com.cloudera.impala.analysis.LikePredicate.initBuiltins(), com.cloudera.impala.analysis.CompoundPredicate.initBuiltins(), com.cloudera.impala.analysis.IsNullPredicate.initBuiltins(), com.cloudera.impala.analysis.BinaryPredicate.initBuiltins(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.analysis.InsertStmt.setTargetTable(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.Expr.treeToThrift(), and com.cloudera.impala.analysis.AnalyzeExprsTest.typeCastTest().
final ScalarType com.cloudera.impala.catalog.Type.CHAR = (ScalarType) ScalarType.createCharType(-1) static inherited
Definition at line 65 of file Type.java.
Referenced by com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getSlotSize(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.catalog.ScalarType.toSql(), and com.cloudera.impala.catalog.ScalarType.toThrift().
PrimitiveType [][] com.cloudera.impala.catalog.Type.compatibilityMatrix static protected inherited
Matrix that records "smallest" assignment-compatible type of two types (INVALID_TYPE if no such type exists, ie, if the input types are fundamentally incompatible). A value of any of the two types could be assigned to a slot of the assignment-compatible type without loss of precision.
We chose not to follow MySQL's type casting behavior as described here: http://dev.mysql.com/doc/refman/5.0/en/type-conversion.html for the following reasons: conservative casting in arithmetic exprs: TINYINT + TINYINT -> BIGINT comparison of many types as double: INT < FLOAT -> comparison as DOUBLE special cases when dealing with dates and timestamps
Definition at line 534 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType().
final ScalarType com.cloudera.impala.catalog.Type.DATE = new ScalarType(PrimitiveType.DATE) static inherited
Definition at line 56 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.isSupported(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.DATETIME = new ScalarType(PrimitiveType.DATETIME) static inherited
Definition at line 57 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.isSupported(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.DECIMAL static inherited
Initial value:
=
      (ScalarType) ScalarType.createDecimalTypeInternal(-1, -1)
Definition at line 61 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.catalog.ScalarType.getSlotSize(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins(), com.cloudera.impala.analysis.TypesUtilTest.TestDecimalAssignementType(), com.cloudera.impala.catalog.ScalarType.toSql(), and com.cloudera.impala.catalog.ScalarType.toThrift().
final ScalarType com.cloudera.impala.catalog.Type.DEFAULT_DECIMAL static inherited
Initial value:
= (ScalarType)
      ScalarType.createDecimalType(ScalarType.DEFAULT_PRECISION,
          ScalarType.DEFAULT_SCALE)
Definition at line 58 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.analysis.TypesUtilTest.TestDecimalAssignementType(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts().
final ScalarType com.cloudera.impala.catalog.Type.DEFAULT_VARCHAR = ScalarType.createVarcharType(-1) static inherited
Definition at line 63 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createVarcharType().
final ScalarType com.cloudera.impala.catalog.Type.DOUBLE = new ScalarType(PrimitiveType.DOUBLE) static inherited
Definition at line 52 of file Type.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.Expr.convertNumericLiteralsToFloat(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.ArithmeticExpr.initBuiltins(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.catalog.CatalogObjectToFromThriftTest.TestHBaseTables(), com.cloudera.impala.catalog.CatalogObjectToFromThriftTest.TestHBaseTableWithBinaryEncodedCols(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs().
final HashMap<String, StructField> com.cloudera.impala.catalog.StructType.fieldMap_ = Maps.newHashMap() private
Definition at line 19 of file StructType.java.
final ArrayList<StructField> com.cloudera.impala.catalog.StructType.fields_ private
Definition at line 20 of file StructType.java.
Referenced by com.cloudera.impala.catalog.StructType.equals(), com.cloudera.impala.catalog.StructType.getFields(), com.cloudera.impala.catalog.StructType.StructType(), com.cloudera.impala.catalog.StructType.toSql(), and com.cloudera.impala.catalog.StructType.toThrift().
final ScalarType com.cloudera.impala.catalog.Type.FLOAT = new ScalarType(PrimitiveType.FLOAT) static inherited
Definition at line 51 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.INT = new ScalarType(PrimitiveType.INT) static inherited
Definition at line 49 of file Type.java.
Referenced by com.cloudera.impala.analysis.AnalyzerTest.addTestFunction(), com.cloudera.impala.analysis.ArithmeticExpr.analyze(), com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.ExtractFromExpr.ExtractFromExpr(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestExprDepthLimit(), com.cloudera.impala.analysis.AuthorizationTest.TestFunction(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.catalog.CatalogTest.TestUdf(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs().
final ScalarType com.cloudera.impala.catalog.Type.INVALID = new ScalarType(PrimitiveType.INVALID_TYPE) static inherited
Definition at line 44 of file Type.java.
Referenced by com.cloudera.impala.analysis.DropFunctionStmt.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.catalog.ScalarFunction.createBuiltinSearchDesc(), com.cloudera.impala.analysis.AnalyzerTest.createFunction(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.service.CatalogOpExecutor.dropFunction(), com.cloudera.impala.analysis.Expr.Expr(), com.cloudera.impala.catalog.Type.getAssignmentCompatibleType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.analysis.Expr.getBuiltinFunction(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.Function.getVarArgsType(), com.cloudera.impala.catalog.HBaseTable.load(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), and com.cloudera.impala.catalog.CatalogTest.TestUdf().
final ScalarType com.cloudera.impala.catalog.Type.NULL = new ScalarType(PrimitiveType.NULL_TYPE) static inherited
Definition at line 45 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getArithmeticResultType(), com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.analysis.NullLiteral.NullLiteral(), com.cloudera.impala.analysis.NullLiteral.resetAnalysisState(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts().
final ScalarType com.cloudera.impala.catalog.Type.SMALLINT = new ScalarType(PrimitiveType.SMALLINT) static inherited
Definition at line 48 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues().
final ScalarType com.cloudera.impala.catalog.Type.STRING = new ScalarType(PrimitiveType.STRING) static inherited
Definition at line 53 of file Type.java.
Referenced by com.cloudera.impala.service.CatalogOpExecutor.alterTableUpdateStats(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), com.cloudera.impala.analysis.Expr.castChildCharsToStrings(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertLogicalParquetType(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.service.Frontend.createCatalogOpRequest(), com.cloudera.impala.service.Frontend.createExecRequest(), com.cloudera.impala.service.Frontend.createExplainRequest(), com.cloudera.impala.planner.SingleNodePlanner.createHBaseValueRange(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.service.Frontend.getColumnStats(), com.cloudera.impala.catalog.HdfsTable.getFiles(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.AuthorizationPolicy.getRolePrivileges(), com.cloudera.impala.catalog.HBaseTable.getTableStats(), com.cloudera.impala.catalog.HdfsTable.getTableStats(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.catalog.HdfsPartitionTest.HdfsPartitionTest(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.LikePredicate.initBuiltins(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.service.MetadataOp.initialzeResultSetSchemas(), com.cloudera.impala.catalog.Function.promoteCharsToStrings(), com.cloudera.impala.planner.HBaseScanNode.setStartStopKey(), com.cloudera.impala.analysis.StringLiteral.StringLiteral(), com.cloudera.impala.analysis.AnalyzeStmtsTest.TestAggregates(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestStringCasts(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestUdf(), and com.cloudera.impala.analysis.AnalyzeExprsTest.TestUdfs().
final ScalarType com.cloudera.impala.catalog.Type.TIMESTAMP = new ScalarType(PrimitiveType.TIMESTAMP) static inherited
Definition at line 55 of file Type.java.
Referenced by com.cloudera.impala.analysis.CreateTableLikeFileStmt.convertPrimitiveParquetType(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), and com.cloudera.impala.analysis.ExprTest.TestLiteralExpr().
final ScalarType com.cloudera.impala.catalog.Type.TINYINT = new ScalarType(PrimitiveType.TINYINT) static inherited
Definition at line 47 of file Type.java.
Referenced by com.cloudera.impala.analysis.NumericLiteral.analyze(), com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.analysis.TypesUtil.getContainingIntType(), com.cloudera.impala.catalog.Type.getDecimalDigits(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.catalog.ScalarType.getMinResolutionDecimal(), com.cloudera.impala.catalog.Type.getNumPrecRadix(), com.cloudera.impala.catalog.Type.getPrecision(), com.cloudera.impala.hive.executor.UdfExecutorTest.getType(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestArithmeticTypeCasts(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestComparisonTypeCasts(), com.cloudera.impala.analysis.AnalyzerTest.TestFunctionMatching(), com.cloudera.impala.analysis.ExprTest.TestLiteralExpr(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralMinMaxValues(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNumericLiteralTypeResolution(), and com.cloudera.impala.catalog.CatalogTest.TestUdf().
final ScalarType com.cloudera.impala.catalog.Type.VARCHAR = ScalarType.createVarcharType(-1) static inherited
Definition at line 64 of file Type.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createType(), com.cloudera.impala.catalog.Type.getColumnSize(), com.cloudera.impala.catalog.Type.getJavaSqlType(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.catalog.ScalarType.toSql(), and com.cloudera.impala.catalog.ScalarType.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/StructType.java