Impala: impala::HdfsParquetScanner::BaseColumnReader Class Reference
impala::HdfsParquetScanner::BaseColumnReader Class Reference abstract
Public Member Functions
virtual ~BaseColumnReader ()
Status Reset (const parquet::ColumnMetaData *metadata, ScannerContext::Stream *stream)
void Close ()
int64_t total_len () const
const SlotDescriptor * slot_desc () const
const parquet::SchemaElement & schema_element () const
int col_idx () const
int max_def_level () const
THdfsCompression::type codec () const
bool ReadValue (MemPool *pool, Tuple *tuple, bool *conjuncts_failed)
Protected Member Functions
BaseColumnReader (HdfsParquetScanner *parent, const SchemaNode &node)
Status ReadDataPage ()
int ReadDefinitionLevel ()
virtual void CreateDictionaryDecoder (uint8_t *values, int size)=0
virtual Status InitDataPage (uint8_t *data, int size)=0
virtual bool ReadSlot (void *slot, MemPool *pool, bool *conjuncts_failed)=0
Protected Attributes
HdfsParquetScanner * parent_
const SchemaNode & node_
const parquet::ColumnMetaData * metadata_
scoped_ptr< Codec > decompressor_
ScannerContext::Stream * stream_
boost::scoped_ptr< MemPool > decompressed_data_pool_
parquet::PageHeader current_page_header_
int num_buffered_values_
uint8_t * data_
RleDecoder rle_def_levels_
BitReader bit_packed_def_levels_
DictDecoderBase * dict_decoder_base_
int64_t num_values_read_
const Bitmap * bitmap_filter_
uint32_t hash_seed_
int64_t rows_returned_
int64_t bitmap_filter_rows_rejected_
Friends
class HdfsParquetScanner
Detailed Description
Definition at line 140 of file hdfs-parquet-scanner.cc.
Constructor & Destructor Documentation
virtual impala::HdfsParquetScanner::BaseColumnReader::~BaseColumnReader () inline virtual
Definition at line 142 of file hdfs-parquet-scanner.cc.
impala::HdfsParquetScanner::BaseColumnReader::BaseColumnReader (HdfsParquetScanner * parent, const SchemaNode & node) inline protected
Definition at line 240 of file hdfs-parquet-scanner.cc.
References bitmap_filter_, bitmap_filter_rows_rejected_, impala::HdfsParquetScanner::SchemaNode::col_idx, impala::RuntimeState::fragment_hash_seed(), impala::RuntimeState::GetBitmapFilter(), hash_seed_, impala::HdfsParquetScanner::SchemaNode::max_def_level, parent_, rows_returned_, impala::HdfsScanNode::runtime_state(), impala::HdfsScanner::scan_node_, impala::HdfsParquetScanner::SchemaNode::slot_desc, and slot_desc().
Member Function Documentation
void impala::HdfsParquetScanner::BaseColumnReader::Close () inline
Definition at line 163 of file hdfs-parquet-scanner.cc.
References decompressor_.
THdfsCompression::type impala::HdfsParquetScanner::BaseColumnReader::codec () const inline
Definition at line 172 of file hdfs-parquet-scanner.cc.
References metadata_, and impala::PARQUET_TO_IMPALA_CODEC.
int impala::HdfsParquetScanner::BaseColumnReader::col_idx () const inline
Definition at line 170 of file hdfs-parquet-scanner.cc.
References impala::HdfsParquetScanner::SchemaNode::col_idx, and node_.
Referenced by impala::HdfsParquetScanner::ValidateColumn().
virtual void impala::HdfsParquetScanner::BaseColumnReader::CreateDictionaryDecoder (uint8_t * values, int size) protected pure virtual
Implemented in impala::HdfsParquetScanner::BoolColumnReader, and impala::HdfsParquetScanner::ColumnReader< T >.
Referenced by ReadDataPage().
virtual Status impala::HdfsParquetScanner::BaseColumnReader::InitDataPage (uint8_t * data, int size) protected pure virtual
Implemented in impala::HdfsParquetScanner::BoolColumnReader, and impala::HdfsParquetScanner::ColumnReader< T >.
Referenced by ReadDataPage().
int impala::HdfsParquetScanner::BaseColumnReader::max_def_level () const inline
Definition at line 171 of file hdfs-parquet-scanner.cc.
References impala::HdfsParquetScanner::SchemaNode::max_def_level, and node_.
Referenced by ReadDataPage().
Status HdfsParquetScanner::BaseColumnReader::ReadDataPage () protected
Definition at line 532 of file hdfs-parquet-scanner.cc.
References impala::Status::AddDetail(), impala::HdfsScanner::AttachPool(), bit_packed_def_levels_, impala::BitUtil::Ceil(), CreateDictionaryDecoder(), current_page_header_, data_, impala::HdfsScanner::decompress_timer_, decompressed_data_pool_, decompressor_, impala::DeserializeThriftMsg(), dict_decoder_base_, impala::HdfsParquetScanner::dictionary_pool_, impala::ScannerContext::Stream::eosr(), impala::HdfsParquetScanner::file_version_, impala::ScannerContext::Stream::GetBuffer(), impala::ScannerContext::Stream::GetBytes(), InitDataPage(), impala::BitUtil::Log2(), LOG_OR_ABORT, max_def_level(), MAX_PAGE_HEADER_SIZE, metadata_, num_buffered_values_, impala::DictDecoderBase::num_entries(), impala::HdfsScanNode::num_partition_keys(), num_values_read_, impala::Status::OK, impala::Status::ok(), parent_, impala::PLAIN, impala::PrettyPrinter::Print(), impala::ReadWriteUtil::Read(), impala::ScannerContext::Stream::ReadBytes(), RequiresSkippedDictionaryHeaderCheck(), RETURN_IF_ERROR, rle_def_levels_, impala::HdfsScanNode::runtime_state(), impala::HdfsScanner::scan_node_, SCOPED_TIMER, impala::ScannerContext::Stream::SkipBytes(), slot_desc(), stream_, impala::TYPE_BOOLEAN, and VLOG_FILE.
int HdfsParquetScanner::BaseColumnReader::ReadDefinitionLevel () inline protected
Definition at line 720 of file hdfs-parquet-scanner.cc.
virtual bool impala::HdfsParquetScanner::BaseColumnReader::ReadSlot (void * slot, MemPool * pool, bool * conjuncts_failed) protected pure virtual
Implemented in impala::HdfsParquetScanner::BoolColumnReader, and impala::HdfsParquetScanner::ColumnReader< T >.
bool HdfsParquetScanner::BaseColumnReader::ReadValue (MemPool * pool, Tuple * tuple, bool * conjuncts_failed) inline
Definition at line 744 of file hdfs-parquet-scanner.cc.
References impala::Tuple::GetSlot(), pool, and impala::Tuple::SetNull().
Status impala::HdfsParquetScanner::BaseColumnReader::Reset (const parquet::ColumnMetaData * metadata, ScannerContext::Stream * stream) inline
Definition at line 145 of file hdfs-parquet-scanner.cc.
References impala::Codec::CreateDecompressor(), data_, decompressor_, dict_decoder_base_, metadata_, num_buffered_values_, num_values_read_, impala::Status::OK, impala::PARQUET_TO_IMPALA_CODEC, RETURN_IF_ERROR, and stream_.
const parquet::SchemaElement& impala::HdfsParquetScanner::BaseColumnReader::schema_element () const inline
Definition at line 169 of file hdfs-parquet-scanner.cc.
References impala::HdfsParquetScanner::SchemaNode::element, and node_.
Referenced by impala::HdfsParquetScanner::ValidateColumn().
const SlotDescriptor* impala::HdfsParquetScanner::BaseColumnReader::slot_desc () const inline
Definition at line 168 of file hdfs-parquet-scanner.cc.
References node_, and impala::HdfsParquetScanner::SchemaNode::slot_desc.
Referenced by BaseColumnReader(), impala::HdfsParquetScanner::BoolColumnReader::BoolColumnReader(), impala::HdfsParquetScanner::ColumnReader< T >::ColumnReader(), ReadDataPage(), impala::HdfsParquetScanner::ColumnReader< T >::ReadSlot(), and impala::HdfsParquetScanner::ValidateColumn().
int64_t impala::HdfsParquetScanner::BaseColumnReader::total_len () const inline
Definition at line 167 of file hdfs-parquet-scanner.cc.
References metadata_.
Friends And Related Function Documentation
friend class HdfsParquetScanner friend
Definition at line 195 of file hdfs-parquet-scanner.cc.
Member Data Documentation
BitReader impala::HdfsParquetScanner::BaseColumnReader::bit_packed_def_levels_ protected
Definition at line 219 of file hdfs-parquet-scanner.cc.
Referenced by ReadDataPage().
const Bitmap* impala::HdfsParquetScanner::BaseColumnReader::bitmap_filter_ protected
Definition at line 228 of file hdfs-parquet-scanner.cc.
Referenced by BaseColumnReader(), impala::HdfsParquetScanner::ColumnReader< T >::InitDataPage(), and impala::HdfsParquetScanner::ColumnReader< T >::ReadSlot().
int64_t impala::HdfsParquetScanner::BaseColumnReader::bitmap_filter_rows_rejected_ protected
Definition at line 238 of file hdfs-parquet-scanner.cc.
Referenced by BaseColumnReader(), impala::HdfsParquetScanner::ColumnReader< T >::InitDataPage(), and impala::HdfsParquetScanner::ColumnReader< T >::ReadSlot().
parquet::PageHeader impala::HdfsParquetScanner::BaseColumnReader::current_page_header_ protected
Definition at line 208 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::ColumnReader< T >::InitDataPage(), ReadDataPage(), and impala::HdfsParquetScanner::ColumnReader< T >::ReadSlot().
uint8_t* impala::HdfsParquetScanner::BaseColumnReader::data_ protected
Definition at line 214 of file hdfs-parquet-scanner.cc.
Referenced by ReadDataPage(), impala::HdfsParquetScanner::ColumnReader< T >::ReadSlot(), and Reset().
boost::scoped_ptr<MemPool> impala::HdfsParquetScanner::BaseColumnReader::decompressed_data_pool_ protected
Definition at line 205 of file hdfs-parquet-scanner.cc.
Referenced by ReadDataPage().
scoped_ptr<Codec> impala::HdfsParquetScanner::BaseColumnReader::decompressor_ protected
Definition at line 201 of file hdfs-parquet-scanner.cc.
Referenced by Close(), ReadDataPage(), and Reset().
DictDecoderBase* impala::HdfsParquetScanner::BaseColumnReader::dict_decoder_base_ protected
Definition at line 222 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::ColumnReader< T >::CreateDictionaryDecoder(), ReadDataPage(), and Reset().
uint32_t impala::HdfsParquetScanner::BaseColumnReader::hash_seed_ protected
Definition at line 230 of file hdfs-parquet-scanner.cc.
Referenced by BaseColumnReader(), and impala::HdfsParquetScanner::ColumnReader< T >::ReadSlot().
const parquet::ColumnMetaData* impala::HdfsParquetScanner::BaseColumnReader::metadata_ protected
Definition at line 200 of file hdfs-parquet-scanner.cc.
Referenced by codec(), ReadDataPage(), Reset(), and total_len().
const SchemaNode& impala::HdfsParquetScanner::BaseColumnReader::node_ protected
Definition at line 198 of file hdfs-parquet-scanner.cc.
Referenced by col_idx(), max_def_level(), schema_element(), and slot_desc().
int impala::HdfsParquetScanner::BaseColumnReader::num_buffered_values_ protected
Definition at line 211 of file hdfs-parquet-scanner.cc.
Referenced by ReadDataPage(), and Reset().
int64_t impala::HdfsParquetScanner::BaseColumnReader::num_values_read_ protected
Definition at line 225 of file hdfs-parquet-scanner.cc.
Referenced by ReadDataPage(), and Reset().
HdfsParquetScanner* impala::HdfsParquetScanner::BaseColumnReader::parent_ protected
Definition at line 197 of file hdfs-parquet-scanner.cc.
Referenced by BaseColumnReader(), ReadDataPage(), and impala::HdfsParquetScanner::BoolColumnReader::ReadSlot().
RleDecoder impala::HdfsParquetScanner::BaseColumnReader::rle_def_levels_ protected
Definition at line 218 of file hdfs-parquet-scanner.cc.
Referenced by ReadDataPage().
int64_t impala::HdfsParquetScanner::BaseColumnReader::rows_returned_ protected
Definition at line 237 of file hdfs-parquet-scanner.cc.
Referenced by BaseColumnReader(), impala::HdfsParquetScanner::ColumnReader< T >::InitDataPage(), and impala::HdfsParquetScanner::ColumnReader< T >::ReadSlot().
ScannerContext::Stream* impala::HdfsParquetScanner::BaseColumnReader::stream_ protected
Definition at line 202 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::AssembleRows(), ReadDataPage(), and Reset().
The documentation for this class was generated from the following file:
be/src/exec/hdfs-parquet-scanner.cc