Impala: com.cloudera.impala.hive.executor.ImpalaBytesWritable Class Reference
com.cloudera.impala.hive.executor.ImpalaBytesWritable Class Reference
Public Member Functions
ImpalaBytesWritable (long ptr)
byte[] copyBytes ()
byte[] get ()
byte[] getBytes ()
int getCapacity ()
int getLength ()
ImpalaStringWritable getStringWritable ()
void set (byte[] v, int offset, int len)
void setCapacity (int newCap)
void setSize (int size)
Private Attributes
final ImpalaStringWritable string_
Detailed Description
Impala writable type that implements the BytesWritable interface. The data marshalling is handled by the underlying ImpalaStringWritable object.
Definition at line 23 of file ImpalaBytesWritable.java.
Constructor & Destructor Documentation
com.cloudera.impala.hive.executor.ImpalaBytesWritable.ImpalaBytesWritable (long ptr) inline
Definition at line 26 of file ImpalaBytesWritable.java.
References com.cloudera.impala.hive.executor.ImpalaBytesWritable.string_.
Member Function Documentation
byte [] com.cloudera.impala.hive.executor.ImpalaBytesWritable.copyBytes () inline
Definition at line 31 of file ImpalaBytesWritable.java.
References com.cloudera.impala.hive.executor.ImpalaBytesWritable.getBytes().
byte [] com.cloudera.impala.hive.executor.ImpalaBytesWritable.get () inline
Definition at line 37 of file ImpalaBytesWritable.java.
References com.cloudera.impala.hive.executor.ImpalaBytesWritable.getBytes().
byte [] com.cloudera.impala.hive.executor.ImpalaBytesWritable.getBytes () inline
Definition at line 39 of file ImpalaBytesWritable.java.
Referenced by com.cloudera.impala.hive.executor.ImpalaBytesWritable.copyBytes(), and com.cloudera.impala.hive.executor.ImpalaBytesWritable.get().
int com.cloudera.impala.hive.executor.ImpalaBytesWritable.getCapacity () inline
Definition at line 41 of file ImpalaBytesWritable.java.
int com.cloudera.impala.hive.executor.ImpalaBytesWritable.getLength () inline
Definition at line 43 of file ImpalaBytesWritable.java.
ImpalaStringWritable com.cloudera.impala.hive.executor.ImpalaBytesWritable.getStringWritable () inline
Definition at line 45 of file ImpalaBytesWritable.java.
References com.cloudera.impala.hive.executor.ImpalaBytesWritable.string_.
void com.cloudera.impala.hive.executor.ImpalaBytesWritable.set (byte[] v, int offset, int len) inline
Definition at line 48 of file ImpalaBytesWritable.java.
References offset.
void com.cloudera.impala.hive.executor.ImpalaBytesWritable.setCapacity (int newCap) inline
Definition at line 50 of file ImpalaBytesWritable.java.
void com.cloudera.impala.hive.executor.ImpalaBytesWritable.setSize (int size) inline
Definition at line 52 of file ImpalaBytesWritable.java.
Member Data Documentation
final ImpalaStringWritable com.cloudera.impala.hive.executor.ImpalaBytesWritable.string_ private
Definition at line 24 of file ImpalaBytesWritable.java.
Referenced by com.cloudera.impala.hive.executor.ImpalaBytesWritable.getStringWritable(), and com.cloudera.impala.hive.executor.ImpalaBytesWritable.ImpalaBytesWritable().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/hive/executor/ImpalaBytesWritable.java