Impala: impala::IsNullExpr Class Reference
impala::IsNullExpr Class Reference
#include <conditional-functions.h>
Public Member Functions
virtual BooleanVal GetBooleanVal (ExprContext *context, TupleRow *row)
virtual TinyIntVal GetTinyIntVal (ExprContext *context, TupleRow *row)
virtual SmallIntVal GetSmallIntVal (ExprContext *context, TupleRow *row)
virtual IntVal GetIntVal (ExprContext *context, TupleRow *row)
virtual BigIntVal GetBigIntVal (ExprContext *context, TupleRow *row)
virtual FloatVal GetFloatVal (ExprContext *context, TupleRow *row)
virtual DoubleVal GetDoubleVal (ExprContext *context, TupleRow *row)
virtual StringVal GetStringVal (ExprContext *context, TupleRow *row)
virtual TimestampVal GetTimestampVal (ExprContext *context, TupleRow *row)
virtual DecimalVal GetDecimalVal (ExprContext *context, TupleRow *row)
virtual Status GetCodegendComputeFn (RuntimeState *state, llvm::Function **fn)
virtual std::string DebugString () const
int output_scale () const
void AddChild (Expr *expr)
Expr * GetChild (int i) const
int GetNumChildren () const
const ColumnType & type () const
bool is_slotref () const
const std::vector< Expr * > & children () const
virtual bool IsConstant () const
virtual int GetSlotIds (std::vector< SlotId > *slot_ids) const
virtual AnyVal * GetConstVal (ExprContext *context)
Static Public Member Functions
static Status CreateExprTree (ObjectPool *pool, const TExpr &texpr, ExprContext **ctx)
static Status CreateExprTrees (ObjectPool *pool, const std::vector< TExpr > &texprs, std::vector< ExprContext * > *ctxs)
static Status Prepare (const std::vector< ExprContext * > &ctxs, RuntimeState *state, const RowDescriptor &row_desc, MemTracker *tracker)
static Status Open (const std::vector< ExprContext * > &ctxs, RuntimeState *state)
Convenience function for opening multiple expr trees.
static Status Clone (const std::vector< ExprContext * > &ctxs, RuntimeState *state, std::vector< ExprContext * > *new_ctxs)
static void Close (const std::vector< ExprContext * > &ctxs, RuntimeState *state)
Convenience function for closing multiple expr trees.
static Expr * CreateLiteral (ObjectPool *pool, const ColumnType &type, void *data)
static Expr * CreateLiteral (ObjectPool *pool, const ColumnType &type, const std::string &)
static int ComputeResultsLayout (const std::vector< Expr * > &exprs, std::vector< int > *offsets, int *var_result_begin)
static int ComputeResultsLayout (const std::vector< ExprContext * > &ctxs, std::vector< int > *offsets, int *var_result_begin)
static std::string DebugString (const std::vector< Expr * > &exprs)
static std::string DebugString (const std::vector< ExprContext * > &ctxs)
static void InitBuiltinsDummy ()
Static Public Attributes
static const char * LLVM_CLASS_NAME = "class.impala::Expr"
Protected Member Functions
IsNullExpr (const TExprNode &node)
virtual Status Prepare (RuntimeState *state, const RowDescriptor &row_desc, ExprContext *context)
virtual Status Open (RuntimeState *state, ExprContext *context, FunctionContext::FunctionStateScope scope=FunctionContext::FRAGMENT_LOCAL)
virtual void Close (RuntimeState *state, ExprContext *context, FunctionContext::FunctionStateScope scope=FunctionContext::FRAGMENT_LOCAL)
Subclasses overriding this function should call Expr::Close().
std::string DebugString (const std::string &expr_name) const
Simple debug string that provides no expr subclass-specific information.
FunctionContext * RegisterFunctionContext (ExprContext *ctx, RuntimeState *state, int varargs_buffer_size=0)
llvm::Function * CreateIrFunctionPrototype (LlvmCodeGen *codegen, const std::string &name, llvm::Value *(*args)[2])
Status GetCodegendComputeFnWrapper (RuntimeState *state, llvm::Function **fn)
llvm::Function * GetStaticGetValWrapper (ColumnType type, LlvmCodeGen *codegen)
Protected Attributes
LibCache::LibCacheEntry * cache_entry_
Cache entry for the library implementing this function.
TFunction fn_
Function description.
const bool is_slotref_
recognize if this node is a slotref in order to speed up GetValue()
const ColumnType type_
analysis is done, types are fixed at this point
std::vector< Expr * > children_
int output_scale_
int context_index_
llvm::Function * ir_compute_fn_
Cached codegened compute function. Exprs should set this in GetCodegendComputeFn().
boost::scoped_ptr< AnyVal > constant_val_
Friends
class Expr
Detailed Description
The following conditional functions require separate Expr classes to take advantage of short circuiting
Definition at line 60 of file conditional-functions.h.
Constructor & Destructor Documentation
impala::IsNullExpr::IsNullExpr (const TExprNode & node) inline protected
Definition at line 78 of file conditional-functions.h.
Member Function Documentation
void impala::Expr::AddChild (Expr * expr) inline inherited
Definition at line 141 of file expr.h.
Referenced by impala::Expr::CreateTreeFromThrift().
const std::vector<Expr*>& impala::Expr::children () const inline inherited
Definition at line 148 of file expr.h.
Referenced by impala::CaseExpr::GetChildVal(), and impala::CaseExpr::GetCodegendComputeFn().
Status Expr::Clone (const std::vector< ExprContext * > & ctxs, RuntimeState * state, std::vector< ExprContext * > * new_ctxs) static inherited
Clones each ExprContext for multiple expr trees. 'new_ctxs' should be an empty vector, and a clone of each context in 'ctxs' will be added to it. The new ExprContexts are created in state->obj_pool().
Definition at line 374 of file expr.cc.
References impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::HdfsScanNode::GetConjunctCtxs(), and impala::SortExecExprs::Open().
static void impala::Expr::Close (const std::vector< ExprContext * > & ctxs, RuntimeState * state) static inherited
Convenience function for closing multiple expr trees.
Referenced by impala::UnionNode::Close(), impala::SortExecExprs::Close(), impala::CaseExpr::Close(), impala::HashJoinNode::Close(), impala::AggregationNode::Close(), impala::ScalarFnCall::Close(), impala::ExprContext::Close(), impala::HiveUdfCall::Close(), impala::PartitionedHashJoinNode::Close(), impala::DataStreamSender::Close(), impala::PartitionedAggregationNode::Close(), impala::AggFnEvaluator::Close(), impala::HdfsScanner::Close(), impala::ExecNode::Close(), impala::HdfsScanNode::Close(), impala::HdfsTableSink::Close(), impala::HdfsPartitionDescriptor::CloseExprs(), impala::ImpalaServer::QueryExecState::Done(), impala::OldHashTableTest::TearDown(), and impala::HashTableTest::TearDown().
void Expr::Close (RuntimeState * state, ExprContext * context, FunctionContext::FunctionStateScope scope = FunctionContext::FRAGMENT_LOCAL) protected virtual inherited
Subclasses overriding this function should call Expr::Close().
If scope if FRAGMENT_LOCAL, both fragment- and thread-local state should be torn down. Otherwise, if scope is THREAD_LOCAL, only thread-local state should be torn down.
Reimplemented in impala::HiveUdfCall, impala::ScalarFnCall, and impala::CaseExpr.
Definition at line 114 of file expr.cc.
References impala::Expr::cache_entry_, impala::Expr::children_, impala::LibCache::DecrementUseCount(), and impala::LibCache::instance().
static int impala::Expr::ComputeResultsLayout (const std::vector< Expr * > & exprs, std::vector< int > * offsets, int * var_result_begin) static inherited
Computes a memory efficient layout for storing the results of evaluating 'exprs' Returns the number of bytes necessary to store all the results and offsets where the result for each expr should be stored. Variable length types are guaranteed to be at the end and 'var_result_begin' will be set the beginning byte offset where variable length results begin. 'var_result_begin' will be set to -1 if there are no variable len types.
Referenced by impala::HashTableCtx::HashTableCtx(), and impala::OldHashTable::OldHashTable().
static int impala::Expr::ComputeResultsLayout (const std::vector< ExprContext * > & ctxs, std::vector< int > * offsets, int * var_result_begin) static inherited
Status Expr::CreateExprTree (ObjectPool * pool, const TExpr & texpr, ExprContext ** ctx) static inherited
Create expression tree from the list of nodes contained in texpr within 'pool'. Returns the root of expression tree in 'expr' and the corresponding ExprContext in 'ctx'.
Definition at line 129 of file expr.cc.
References impala::Expr::CreateTreeFromThrift(), impala::Status::GetDetail(), impala::Status::OK, and impala::Status::ok().
Referenced by impala::Expr::CreateExprTrees(), impala::HdfsPartitionDescriptor::HdfsPartitionDescriptor(), impala::HashJoinNode::Init(), impala::AnalyticEvalNode::Init(), impala::PartitionedHashJoinNode::Init(), and Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs().
Status Expr::CreateExprTrees (ObjectPool * pool, const std::vector< TExpr > & texprs, std::vector< ExprContext * > * ctxs) static inherited
Creates vector of ExprContexts containing exprs from the given vector of TExprs within 'pool'. Returns an error if any of the individual conversions caused an error, otherwise OK.
Definition at line 149 of file expr.cc.
References impala::Expr::CreateExprTree(), impala::Status::OK, and RETURN_IF_ERROR.
Referenced by impala::DataStreamSender::DataStreamSender(), impala::UnionNode::Init(), impala::HashJoinNode::Init(), impala::AggregationNode::Init(), impala::ExecNode::Init(), impala::PartitionedHashJoinNode::Init(), impala::PartitionedAggregationNode::Init(), impala::HdfsScanNode::Prepare(), and impala::HdfsTableSink::Prepare().
Function * Expr::CreateIrFunctionPrototype (LlvmCodeGen * codegen, const std::string & name, llvm::Value *(*) args[2]) protected inherited
Helper function to create an empty Function* with the appropriate signature to be returned by GetCodegendComputeFn(). 'name' is the name of the returned Function*. The arguments to the function are returned in 'args'.
Definition at line 456 of file expr.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::LlvmCodeGen::FnPrototype::GeneratePrototype(), impala::CodegenAnyVal::GetLoweredType(), impala::LlvmCodeGen::GetPtrType(), impala::TupleRow::LLVM_CLASS_NAME, impala::ExprContext::LLVM_CLASS_NAME, and impala::Expr::type().
Referenced by impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
static Expr* impala::Expr::CreateLiteral (ObjectPool * pool, const ColumnType & type, void * data) static inherited
Create a new literal expr of 'type' with initial 'data'. data should match the ColumnType (i.e. type == TYPE_INT, data is a int*) The new Expr will be allocated from the pool.
static Expr* impala::Expr::CreateLiteral (ObjectPool * pool, const ColumnType & type, const std::string &) static inherited
Create a new literal expr of 'type' by parsing the string. NULL will be returned if the string and type are not compatible. The new Expr will be allocated from the pool.
virtual std::string impala::IsNullExpr::DebugString () const inline virtual
Reimplemented from impala::Expr.
Definition at line 74 of file conditional-functions.h.
References impala_udf::DebugString().
static std::string impala::Expr::DebugString (const std::vector< Expr * > & exprs) static inherited
static std::string impala::Expr::DebugString (const std::vector< ExprContext * > & ctxs) static inherited
std::string impala::Expr::DebugString (const std::string & expr_name) const inline protected inherited
Simple debug string that provides no expr subclass-specific information.
Definition at line 332 of file expr.h.
References impala_udf::DebugString().
virtual BigIntVal impala::IsNullExpr::GetBigIntVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
virtual BooleanVal impala::IsNullExpr::GetBooleanVal (ExprContext * context, TupleRow * row) virtual
Virtual compute functions for each *Val type. Each Expr subclass should implement the functions for the return type(s) it supports. For example, a boolean function will only implement GetBooleanVal(). Some Exprs, like Literal, have many possible return types and will implement multiple Get*Val() functions.
Reimplemented from impala::Expr.
Expr* impala::Expr::GetChild (int i) const inline inherited
Definition at line 142 of file expr.h.
Referenced by impala::HiveUdfCall::Evaluate(), and impala::HiveUdfCall::Prepare().
virtual Status impala::IsNullExpr::GetCodegendComputeFn (RuntimeState * state, llvm::Function ** fn) virtual
Returns an llvm::Function* with signature: <subclass of="" anyval>=""> ComputeFn(ExprContext* context, TupleRow* row) The function should evaluate this expr over 'row' and return the result as the appropriate type of AnyVal.
Implements impala::Expr.
Status Expr::GetCodegendComputeFnWrapper (RuntimeState * state, llvm::Function ** fn) protected inherited
Generates an IR compute function that calls the appropriate interpreted Get*Val() compute function. This is useful for builtins that can't be implemented with the UDF interface (e.g. functions that need short-circuiting) and that don't have custom codegen functions that use the IRBuilder. It doesn't provide any performance benefit over the interpreted path. TODO: this should be replaced with fancier xcompiling infrastructure
Definition at line 546 of file expr.cc.
References impala::LlvmCodeGen::CastPtrToLlvmPtr(), impala::LlvmCodeGen::context(), impala::CodegenAnyVal::CreateCall(), impala::Expr::CreateIrFunctionPrototype(), impala::LlvmCodeGen::FinalizeFunction(), impala::RuntimeState::GetCodegen(), impala::LlvmCodeGen::GetPtrType(), impala::Expr::GetStaticGetValWrapper(), impala::Expr::ir_compute_fn_, impala::Expr::LLVM_CLASS_NAME, impala::Status::OK, RETURN_IF_ERROR, and impala::Expr::type().
Referenced by impala::TupleIsNullPredicate::GetCodegendComputeFn(), and impala::HiveUdfCall::GetCodegendComputeFn().
AnyVal * Expr::GetConstVal (ExprContext * context) virtual inherited
If this expr is constant, evaluates the expr with no input row argument and returns the output. Returns NULL if the argument is not constant. The returned AnyVal* is owned by this expr. This should only be called after Open() has been called on this expr.
Definition at line 491 of file expr.cc.
References impala::Expr::constant_val_, impala::Expr::GetBigIntVal(), impala::Expr::GetBooleanVal(), impala::Expr::GetDecimalVal(), impala::Expr::GetDoubleVal(), impala::Expr::GetFloatVal(), impala::Expr::GetIntVal(), impala::Expr::GetSmallIntVal(), impala::Expr::GetStringVal(), impala::Expr::GetTimestampVal(), impala::Expr::GetTinyIntVal(), impala::Expr::IsConstant(), impala::ExprContext::opened_, impala::ColumnType::type, impala::Expr::type(), impala::Expr::type_, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_CHAR, impala::TYPE_DECIMAL, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::ScalarFnCall::Open().
virtual DecimalVal impala::IsNullExpr::GetDecimalVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
virtual DoubleVal impala::IsNullExpr::GetDoubleVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
virtual FloatVal impala::IsNullExpr::GetFloatVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
virtual IntVal impala::IsNullExpr::GetIntVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
int impala::Expr::GetNumChildren () const inline inherited
Definition at line 143 of file expr.h.
Referenced by impala::HiveUdfCall::Evaluate(), impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), and impala::HiveUdfCall::Prepare().
int Expr::GetSlotIds (std::vector< SlotId > * slot_ids) const virtual inherited
Returns the slots that are referenced by this expr tree in 'slot_ids'. Returns the number of slots added to the vector
Reimplemented in impala::SlotRef.
Definition at line 418 of file expr.cc.
References impala::Expr::children_.
virtual SmallIntVal impala::IsNullExpr::GetSmallIntVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
Function * Expr::GetStaticGetValWrapper (ColumnType type, LlvmCodeGen * codegen) protected inherited
Returns the IR version of the static Get*Val() wrapper function corresponding to 'type'. This is used for calling interpreted Get*Val() functions from codegen'd functions (e.g. in ScalarFnCall() when codegen is disabled).
Definition at line 426 of file expr.cc.
References impala::ColumnType::DebugString(), impala::LlvmCodeGen::GetFunction(), impala::ColumnType::type, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_CHAR, impala::TYPE_DECIMAL, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
virtual StringVal impala::IsNullExpr::GetStringVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
virtual TimestampVal impala::IsNullExpr::GetTimestampVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
virtual TinyIntVal impala::IsNullExpr::GetTinyIntVal (ExprContext * context, TupleRow * row) virtual
Reimplemented from impala::Expr.
void Expr::InitBuiltinsDummy () static inherited
The builtin functions are not called from anywhere in the code and the symbols are therefore not included in the binary. We call these functions by using dlsym. The compiler must think this function is callable to not strip these symbols.
Definition at line 470 of file expr.cc.
References impala::Operators::Add_IntVal_IntVal(), impala::CastFunctions::CastToBooleanVal(), impala::DecimalOperators::CastToDecimalVal(), impala::InPredicate::InIterate(), impala::AggregateFunctions::InitNull(), impala::IsNullPredicate::IsNull(), impala::StringFunctions::Length(), impala::LikePredicate::Like(), impala::CompoundPredicate::Not(), impala::ConditionalFunctions::NullIfZero(), impala::UdfBuiltins::Pi(), impala::MathFunctions::Pi(), impala::UtilityFunctions::Pid(), impala::DecimalFunctions::Precision(), and impala::TimestampFunctions::Year().
bool impala::Expr::is_slotref () const inline inherited
Definition at line 146 of file expr.h.
bool Expr::IsConstant () const virtual inherited
Returns true if GetValue(NULL) can be called on this expr and always returns the same result (e.g., exprs that don't contain slotrefs). The default implementation returns true if all children are constant.
Reimplemented in impala::ScalarFnCall, impala::TupleIsNullPredicate, and impala::SlotRef.
Definition at line 411 of file expr.cc.
References impala::Expr::children_.
Referenced by impala::Expr::GetConstVal(), and impala::ScalarFnCall::IsConstant().
static Status impala::Expr::Open (const std::vector< ExprContext * > & ctxs, RuntimeState * state) static inherited
Convenience function for opening multiple expr trees.
Referenced by impala::ExprContext::Clone(), impala::HashJoinNode::ConstructBuildSide(), impala::PartitionedHashJoinNode::ConstructBuildSide(), impala::UnionNode::Open(), impala::SortExecExprs::Open(), impala::ExprContext::Open(), impala::CaseExpr::Open(), impala::AggregationNode::Open(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::DataStreamSender::Open(), impala::ExecNode::Open(), impala::PartitionedAggregationNode::Open(), impala::AggFnEvaluator::Open(), impala::HdfsScanNode::Open(), impala::HdfsTableSink::Open(), impala::Expr::Open(), impala::HdfsPartitionDescriptor::OpenExprs(), impala::OldHashTableTest::SetUp(), impala::HashTableTest::SetUp(), and impala::ImpalaServer::QueryExecState::WaitInternal().
Status Expr::Open (RuntimeState * state, ExprContext * context, FunctionContext::FunctionStateScope scope = FunctionContext::FRAGMENT_LOCAL) protected virtual inherited
Initializes 'context' for execution. If scope if FRAGMENT_LOCAL, both fragment- and thread-local state should be initialized. Otherwise, if scope is THREAD_LOCAL, only thread-local state should be initialized. Subclasses overriding this function should call Expr::Open() to recursively call Open() on the expr tree.
Reimplemented in impala::HiveUdfCall, impala::ScalarFnCall, and impala::CaseExpr.
Definition at line 366 of file expr.cc.
References impala::Expr::children_, impala::Status::OK, impala::Expr::Open(), and RETURN_IF_ERROR.
int impala::Expr::output_scale () const inline inherited
Get the number of digits after the decimal that should be displayed for this value. Returns -1 if no scale has been specified (currently the scale is only set for doubles set by RoundUpTo). GetValue() must have already been called. TODO: is this still necessary?
Definition at line 139 of file expr.h.
static Status impala::Expr::Prepare (const std::vector< ExprContext * > & ctxs, RuntimeState * state, const RowDescriptor & row_desc, MemTracker * tracker) static inherited
Convenience function for preparing multiple expr trees. Allocations from 'ctxs' will be counted against 'tracker'.
Referenced by impala::TupleIsNullPredicate::Prepare(), impala::UnionNode::Prepare(), impala::SortExecExprs::Prepare(), impala::ExprContext::Prepare(), impala::CaseExpr::Prepare(), impala::HashJoinNode::Prepare(), impala::AggregationNode::Prepare(), impala::ScalarFnCall::Prepare(), impala::HiveUdfCall::Prepare(), impala::PartitionedHashJoinNode::Prepare(), impala::DataStreamSender::Prepare(), impala::ExecNode::Prepare(), impala::AggFnEvaluator::Prepare(), impala::PartitionedAggregationNode::Prepare(), impala::HdfsScanNode::Prepare(), impala::Expr::Prepare(), impala::HdfsTableSink::PrepareExprs(), impala::HdfsPartitionDescriptor::PrepareExprs(), impala::HashTableTest::SetUp(), and impala::OldHashTableTest::SetUp().
Status Expr::Prepare (RuntimeState * state, const RowDescriptor & row_desc, ExprContext * context) protected virtual inherited
Initializes this expr instance for execution. This does not include initializing state in the ExprContext; 'context' should only be used to register a FunctionContext via RegisterFunctionContext(). Any IR functions must be generated here. Subclasses overriding this function should call Expr::Prepare() to recursively call Prepare() on the expr tree.
Reimplemented in impala::HiveUdfCall, impala::ScalarFnCall, impala::CaseExpr, impala::TupleIsNullPredicate, and impala::SlotRef.
Definition at line 350 of file expr.cc.
References impala::Expr::children_, impala::INVALID_TYPE, impala::Status::OK, impala::Expr::Prepare(), RETURN_IF_ERROR, impala::ColumnType::type, and impala::Expr::type_.
FunctionContext * Expr::RegisterFunctionContext (ExprContext * ctx, RuntimeState * state, int varargs_buffer_size = 0) protected inherited
Helper function that calls ctx->Register(), sets context_index_, and returns the registered FunctionContext.
Definition at line 80 of file expr.cc.
References impala::AnyValUtil::ColumnTypeToTypeDesc(), impala::ExprContext::fn_context(), and impala::ExprContext::Register().
Referenced by impala::CaseExpr::Prepare(), and impala::HiveUdfCall::Prepare().
const ColumnType& impala::Expr::type () const inline inherited
Definition at line 145 of file expr.h.
Referenced by impala::CaseExpr::AnyValEq(), impala::HdfsParquetTableWriter::BoolColumnWriter::BoolColumnWriter(), impala::AggregationNode::CodegenUpdateSlot(), impala::PartitionedAggregationNode::CodegenUpdateSlot(), impala::HdfsParquetTableWriter::ColumnWriter< T >::ColumnWriter(), impala::Expr::CreateIrFunctionPrototype(), impala::Literal::DebugString(), impala::HiveUdfCall::Evaluate(), impala::ScalarFnCall::EvaluateChildren(), impala::CaseExpr::GetChildVal(), impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::Expr::GetCodegendComputeFnWrapper(), impala::Expr::GetConstVal(), impala::Literal::GetDecimalVal(), impala::ScalarFnCall::GetUdf(), impala::Literal::Literal(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), impala::HiveUdfCall::Prepare(), and impala::DataStreamSender::Send().
Friends And Related Function Documentation
friend class Expr friend
Definition at line 77 of file conditional-functions.h.
Member Data Documentation
LibCache::LibCacheEntry* impala::Expr::cache_entry_ protected inherited
Cache entry for the library implementing this function.
Definition at line 281 of file expr.h.
Referenced by impala::Expr::Close(), impala::ScalarFnCall::GetFunction(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::Prepare(), and impala::Expr::~Expr().
std::vector<Expr*> impala::Expr::children_ protected inherited
Definition at line 290 of file expr.h.
Referenced by impala::Expr::Close(), impala::Expr::DebugString(), impala::ScalarFnCall::EvaluateChildren(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::Expr::GetSlotIds(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::InterpretEval(), impala::Expr::IsConstant(), impala::CaseExpr::Open(), impala::ScalarFnCall::Open(), impala::Expr::Open(), impala::SlotRef::Prepare(), impala::TupleIsNullPredicate::Prepare(), impala::ScalarFnCall::Prepare(), and impala::Expr::Prepare().
boost::scoped_ptr<AnyVal> impala::Expr::constant_val_ protected inherited
If this expr is constant, this will store and cache the value generated by GetConstVal().
Definition at line 303 of file expr.h.
Referenced by impala::Expr::GetConstVal().
int impala::Expr::context_index_ protected inherited
Index to pass to ExprContext::fn_context() to retrieve this expr's FunctionContext. Set in RegisterFunctionContext(). -1 if this expr does not need a FunctionContext and doesn't call RegisterFunctionContext().
Definition at line 296 of file expr.h.
Referenced by impala::CaseExpr::Close(), impala::ScalarFnCall::Close(), impala::HiveUdfCall::Close(), impala::HiveUdfCall::Evaluate(), impala::ScalarFnCall::EvaluateChildren(), impala::ScalarFnCall::GetCodegendComputeFn(), impala::ScalarFnCall::InterpretEval(), impala::CaseExpr::Open(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), and impala::ScalarFnCall::Prepare().
TFunction impala::Expr::fn_ protected inherited
Function description.
Definition at line 284 of file expr.h.
Referenced by impala::ScalarFnCall::DebugString(), impala::HiveUdfCall::DebugString(), impala::HiveUdfCall::Evaluate(), impala::Expr::Expr(), impala::ScalarFnCall::GetFunction(), impala::ScalarFnCall::GetUdf(), impala::ScalarFnCall::IsConstant(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), impala::HiveUdfCall::Prepare(), and impala::ScalarFnCall::ScalarFnCall().
llvm::Function* impala::Expr::ir_compute_fn_ protected inherited
Cached codegened compute function. Exprs should set this in GetCodegendComputeFn().
Definition at line 299 of file expr.h.
Referenced by impala::CaseExpr::GetCodegendComputeFn(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
const bool impala::Expr::is_slotref_ protected inherited
recognize if this node is a slotref in order to speed up GetValue()
Definition at line 287 of file expr.h.
const char * Expr::LLVM_CLASS_NAME = "class.impala::Expr" static inherited
Definition at line 232 of file expr.h.
Referenced by impala::ScalarFnCall::GetCodegendComputeFn(), and impala::Expr::GetCodegendComputeFnWrapper().
int impala::Expr::output_scale_ protected inherited
Definition at line 291 of file expr.h.
Referenced by impala::ExprContext::GetValue(), and impala::ScalarFnCall::Open().
const ColumnType impala::Expr::type_ protected inherited
analysis is done, types are fixed at this point
Definition at line 289 of file expr.h.
Referenced by impala::Literal::DebugString(), impala::Expr::DebugString(), impala::SlotRef::GetBigIntVal(), impala::Literal::GetBigIntVal(), impala::ScalarFnCall::GetBigIntVal(), impala::HiveUdfCall::GetBigIntVal(), impala::SlotRef::GetBooleanVal(), impala::Literal::GetBooleanVal(), impala::HiveUdfCall::GetBooleanVal(), impala::ScalarFnCall::GetBooleanVal(), impala::SlotRef::GetCodegendComputeFn(), impala::Literal::GetCodegendComputeFn(), impala::Expr::GetConstVal(), impala::SlotRef::GetDecimalVal(), impala::Literal::GetDecimalVal(), impala::ScalarFnCall::GetDecimalVal(), impala::HiveUdfCall::GetDecimalVal(), impala::SlotRef::GetDoubleVal(), impala::Literal::GetDoubleVal(), impala::ScalarFnCall::GetDoubleVal(), impala::HiveUdfCall::GetDoubleVal(), impala::SlotRef::GetFloatVal(), impala::Literal::GetFloatVal(), impala::ScalarFnCall::GetFloatVal(), impala::HiveUdfCall::GetFloatVal(), impala::SlotRef::GetIntVal(), impala::Literal::GetIntVal(), impala::ScalarFnCall::GetIntVal(), impala::HiveUdfCall::GetIntVal(), impala::SlotRef::GetSmallIntVal(), impala::Literal::GetSmallIntVal(), impala::ScalarFnCall::GetSmallIntVal(), impala::HiveUdfCall::GetSmallIntVal(), impala::SlotRef::GetStringVal(), impala::Literal::GetStringVal(), impala::HiveUdfCall::GetStringVal(), impala::ScalarFnCall::GetStringVal(), impala::SlotRef::GetTimestampVal(), impala::ScalarFnCall::GetTimestampVal(), impala::HiveUdfCall::GetTimestampVal(), impala::SlotRef::GetTinyIntVal(), impala::Literal::GetTinyIntVal(), impala::HiveUdfCall::GetTinyIntVal(), impala::ScalarFnCall::GetTinyIntVal(), impala::ExprContext::GetValue(), impala::Literal::Literal(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), impala::ScalarFnCall::Prepare(), and impala::Expr::Prepare().
The documentation for this class was generated from the following file:
be/src/exprs/conditional-functions.h