Impala: impala::DataStreamTest Class Reference
impala::DataStreamTest Class Reference
Classes
struct ReceiverInfo
struct SenderInfo
Protected Member Functions
DataStreamTest ()
virtual void SetUp ()
const TDataStreamSink & GetSink (TPartitionType::type partition_type)
virtual void TearDown ()
void Reset ()
void GetNextInstanceId (TUniqueId *instance_id)
void CreateRowDesc ()
void CreateTupleComparator ()
RowBatch * CreateRowBatch ()
void GetNextBatch (RowBatch *batch, int *next_val)
void StartReceiver (TPartitionType::type stream_type, int num_senders, int receiver_num, int buffer_size, bool is_merging, TUniqueId *out_id=NULL)
void JoinReceivers ()
void ReadStream (ReceiverInfo *info)
void ReadStreamMerging (ReceiverInfo *info, RuntimeProfile *profile)
void CheckReceivers (TPartitionType::type stream_type, int num_senders)
void CheckSenders ()
void StartBackend ()
void StopBackend ()
void StartSender (TPartitionType::type partition_type=TPartitionType::UNPARTITIONED, int channel_buffer_size=1024)
void JoinSenders ()
void Sender (int sender_num, int channel_buffer_size, TPartitionType::type partition_type)
void TestStream (TPartitionType::type stream_type, int num_senders, int num_receivers, int buffer_size, bool is_merging)
Protected Attributes
ObjectPool obj_pool_
MemTracker tracker_
DescriptorTbl * desc_tbl_
const RowDescriptor * row_desc_
TupleRowComparator * less_than_
MemTracker dummy_mem_tracker_
ExecEnv exec_env_
RuntimeState runtime_state_
TUniqueId next_instance_id_
string stmt_
scoped_ptr< RowBatch > batch_
int next_val_
int64_t * tuple_mem_
DataStreamMgr * stream_mgr_
ThriftServer * server_
TDataStreamSink broadcast_sink_
TDataStreamSink random_sink_
TDataStreamSink hash_sink_
vector< TPlanFragmentDestination > dest_
vector< SenderInfo > sender_info_
vector< ReceiverInfo > receiver_info_
Static Protected Attributes
static const int MAX_SENDERS = 16
static const int MAX_RECEIVERS = 16
static const PlanNodeId DEST_NODE_ID = 1
static const int BATCH_CAPACITY = 100
static const int PER_ROW_DATA = 8
static const int TOTAL_DATA_SIZE = 8 * 1024
static const int NUM_BATCHES = TOTAL_DATA_SIZE / BATCH_CAPACITY / PER_ROW_DATA
Private Attributes
ExprContext * lhs_slot_ctx_
ExprContext * rhs_slot_ctx_
Detailed Description
Definition at line 90 of file data-stream-test.cc.
Constructor & Destructor Documentation
impala::DataStreamTest::DataStreamTest () inline protected
Definition at line 92 of file data-stream-test.cc.
References impala::exec_env_, and impala::ExecEnv::InitForFeTests().
Member Function Documentation
void impala::DataStreamTest::CheckReceivers (TPartitionType::type stream_type, int num_senders) inline protected
Definition at line 383 of file data-stream-test.cc.
References impala::DataStreamTest::ReceiverInfo::data_values, impala::HashUtil::FNV_SEED, impala::RawValue::GetHashValueFnv(), impala::DataStreamTest::ReceiverInfo::num_senders, impala::Status::ok(), impala::DataStreamTest::ReceiverInfo::receiver_num, impala::DataStreamTest::ReceiverInfo::status, impala::DataStreamTest::ReceiverInfo::stream_type, and impala::TYPE_BIGINT.
void impala::DataStreamTest::CheckSenders () inline protected
Definition at line 428 of file data-stream-test.cc.
RowBatch* impala::DataStreamTest::CreateRowBatch () inline protected
Definition at line 292 of file data-stream-test.cc.
References impala::RowBatch::AddRow(), impala::MemPool::Allocate(), impala::RowBatch::CommitLastRow(), impala::RowBatch::GetRow(), gen_ir_descriptions::idx, impala::row_desc_, impala::TupleRow::SetTuple(), and impala::RowBatch::tuple_data_pool().
void impala::DataStreamTest::CreateRowDesc () inline protected
Definition at line 245 of file data-stream-test.cc.
References impala::DescriptorTbl::Create(), impala::desc_tbl_, impala::obj_pool_, impala::row_desc_, impala::ColumnType::ToThrift(), and impala::TYPE_BIGINT.
void impala::DataStreamTest::CreateTupleComparator () inline protected
Definition at line 276 of file data-stream-test.cc.
References impala::obj_pool_, impala::row_desc_, and impala::TYPE_BIGINT.
void impala::DataStreamTest::GetNextBatch (RowBatch * batch, int * next_val) inline protected
Definition at line 306 of file data-stream-test.cc.
References impala::RowBatch::GetRow(), impala::Tuple::GetSlot(), and impala::TupleRow::GetTuple().
void impala::DataStreamTest::GetNextInstanceId (TUniqueId * instance_id) inline protected
Definition at line 233 of file data-stream-test.cc.
const TDataStreamSink& impala::DataStreamTest::GetSink (TPartitionType::type partition_type) inline protected
Definition at line 138 of file data-stream-test.cc.
void impala::DataStreamTest::JoinReceivers () inline protected
Definition at line 337 of file data-stream-test.cc.
References VLOG_QUERY.
void impala::DataStreamTest::JoinSenders () inline protected
Definition at line 461 of file data-stream-test.cc.
References VLOG_QUERY.
void impala::DataStreamTest::ReadStream (ReceiverInfo * info) inline protected
Definition at line 346 of file data-stream-test.cc.
References impala::DataStreamTest::ReceiverInfo::data_values, impala::RowBatch::GetRow(), impala::Tuple::GetSlot(), impala::TupleRow::GetTuple(), impala::Status::IsCancelled(), impala::RowBatch::num_rows(), impala::SleepForMs(), impala::DataStreamTest::ReceiverInfo::status, impala::DataStreamTest::ReceiverInfo::stream_recvr, and VLOG_QUERY.
Referenced by StartReceiver().
void impala::DataStreamTest::ReadStreamMerging (ReceiverInfo * info, RuntimeProfile * profile) inline protected
Definition at line 362 of file data-stream-test.cc.
References impala::DataStreamTest::ReceiverInfo::data_values, impala::RowBatch::GetRow(), impala::Tuple::GetSlot(), impala::TupleRow::GetTuple(), impala::Status::IsCancelled(), impala::RowBatch::num_rows(), impala::RowBatch::Reset(), impala::row_desc_, impala::SleepForMs(), impala::DataStreamTest::ReceiverInfo::status, impala::DataStreamTest::ReceiverInfo::stream_recvr, and VLOG_QUERY.
Referenced by StartReceiver().
void impala::DataStreamTest::Reset () inline protected
Definition at line 156 of file data-stream-test.cc.
void impala::DataStreamTest::Sender (int sender_num, int channel_buffer_size, TPartitionType::type partition_type) inline protected
Definition at line 468 of file data-stream-test.cc.
References impala::DataStreamSender::Close(), impala::desc_tbl_, impala::exec_env_, impala::DataStreamSender::GetNumDataBytesSent(), impala::RuntimeState::InitMemTrackers(), impala::DataStreamTest::SenderInfo::num_bytes_sent, impala::obj_pool_, impala::Status::ok(), impala::DataStreamSender::Open(), impala::DataStreamSender::Prepare(), impala::row_desc_, impala::DataStreamSender::Send(), impala::RuntimeState::set_desc_tbl(), impala::DataStreamTest::SenderInfo::status, and VLOG_QUERY.
Referenced by StartSender().
virtual void impala::DataStreamTest::SetUp () inline protected virtual
Definition at line 100 of file data-stream-test.cc.
void impala::DataStreamTest::StartBackend () inline protected
Definition at line 436 of file data-stream-test.cc.
void impala::DataStreamTest::StartReceiver (TPartitionType::type stream_type, int num_senders, int receiver_num, int buffer_size, bool is_merging, TUniqueId * out_id = NULL) inline protected
Definition at line 315 of file data-stream-test.cc.
References impala::obj_pool_, ReadStream(), ReadStreamMerging(), impala::row_desc_, impala::DataStreamTest::ReceiverInfo::stream_recvr, impala::DataStreamTest::ReceiverInfo::thread_handle, and VLOG_QUERY.
void impala::DataStreamTest::StartSender (TPartitionType::type partition_type = TPartitionType::UNPARTITIONED, int channel_buffer_size = 1024) inline protected
Definition at line 449 of file data-stream-test.cc.
References Sender(), impala::DataStreamTest::SenderInfo::thread_handle, and VLOG_QUERY.
void impala::DataStreamTest::StopBackend () inline protected
Definition at line 443 of file data-stream-test.cc.
References VLOG_QUERY.
virtual void impala::DataStreamTest::TearDown () inline protected virtual
Definition at line 149 of file data-stream-test.cc.
References impala::exec_env_, impala::ExecEnv::impalad_client_cache(), and impala::ClientCache< T >::TestShutdown().
void impala::DataStreamTest::TestStream (TPartitionType::type stream_type, int num_senders, int num_receivers, int buffer_size, bool is_merging) inline protected
Definition at line 495 of file data-stream-test.cc.
References VLOG_QUERY.
Member Data Documentation
scoped_ptr<RowBatch> impala::DataStreamTest::batch_ protected
Definition at line 184 of file data-stream-test.cc.
const int impala::DataStreamTest::BATCH_CAPACITY = 100 static protected
Definition at line 167 of file data-stream-test.cc.
TDataStreamSink impala::DataStreamTest::broadcast_sink_ protected
Definition at line 193 of file data-stream-test.cc.
DescriptorTbl* impala::DataStreamTest::desc_tbl_ protected
Definition at line 174 of file data-stream-test.cc.
vector<TPlanFragmentDestination> impala::DataStreamTest::dest_ protected
Definition at line 196 of file data-stream-test.cc.
const PlanNodeId impala::DataStreamTest::DEST_NODE_ID = 1 static protected
Definition at line 166 of file data-stream-test.cc.
MemTracker impala::DataStreamTest::dummy_mem_tracker_ protected
Definition at line 177 of file data-stream-test.cc.
ExecEnv impala::DataStreamTest::exec_env_ protected
Definition at line 178 of file data-stream-test.cc.
TDataStreamSink impala::DataStreamTest::hash_sink_ protected
Definition at line 195 of file data-stream-test.cc.
TupleRowComparator* impala::DataStreamTest::less_than_ protected
Definition at line 176 of file data-stream-test.cc.
ExprContext* impala::DataStreamTest::lhs_slot_ctx_ private
Definition at line 514 of file data-stream-test.cc.
const int impala::DataStreamTest::MAX_RECEIVERS = 16 static protected
Definition at line 165 of file data-stream-test.cc.
const int impala::DataStreamTest::MAX_SENDERS = 16 static protected
Definition at line 164 of file data-stream-test.cc.
TUniqueId impala::DataStreamTest::next_instance_id_ protected
Definition at line 180 of file data-stream-test.cc.
int impala::DataStreamTest::next_val_ protected
Definition at line 185 of file data-stream-test.cc.
const int impala::DataStreamTest::NUM_BATCHES = TOTAL_DATA_SIZE / BATCH_CAPACITY / PER_ROW_DATA static protected
Definition at line 170 of file data-stream-test.cc.
ObjectPool impala::DataStreamTest::obj_pool_ protected
Definition at line 172 of file data-stream-test.cc.
const int impala::DataStreamTest::PER_ROW_DATA = 8 static protected
Definition at line 168 of file data-stream-test.cc.
TDataStreamSink impala::DataStreamTest::random_sink_ protected
Definition at line 194 of file data-stream-test.cc.
vector<ReceiverInfo> impala::DataStreamTest::receiver_info_ protected
Definition at line 230 of file data-stream-test.cc.
ExprContext* impala::DataStreamTest::rhs_slot_ctx_ private
Definition at line 515 of file data-stream-test.cc.
const RowDescriptor* impala::DataStreamTest::row_desc_ protected
Definition at line 175 of file data-stream-test.cc.
RuntimeState impala::DataStreamTest::runtime_state_ protected
Definition at line 179 of file data-stream-test.cc.
vector<SenderInfo> impala::DataStreamTest::sender_info_ protected
Definition at line 205 of file data-stream-test.cc.
ThriftServer* impala::DataStreamTest::server_ protected
Definition at line 190 of file data-stream-test.cc.
string impala::DataStreamTest::stmt_ protected
Definition at line 181 of file data-stream-test.cc.
DataStreamMgr* impala::DataStreamTest::stream_mgr_ protected
Definition at line 189 of file data-stream-test.cc.
const int impala::DataStreamTest::TOTAL_DATA_SIZE = 8 * 1024 static protected
Definition at line 169 of file data-stream-test.cc.
MemTracker impala::DataStreamTest::tracker_ protected
Definition at line 173 of file data-stream-test.cc.
int64_t* impala::DataStreamTest::tuple_mem_ protected
Definition at line 186 of file data-stream-test.cc.
The documentation for this class was generated from the following file:
be/src/runtime/data-stream-test.cc