Impala: impala::DataStreamRecvr::SenderQueue Class Reference
impala::DataStreamRecvr::SenderQueue Class Reference
Public Member Functions
SenderQueue (DataStreamRecvr *parent_recvr, int num_senders, RuntimeProfile *profile)
Status GetBatch (RowBatch **next_batch)
void AddBatch (const TRowBatch &batch)
void DecrementSenders ()
void Cancel ()
void Close ()
RowBatch * current_batch () const
Private Types
typedef list< pair< int,
RowBatch * > > RowBatchQueue
Private Attributes
DataStreamRecvr * recvr_
mutex lock_
bool is_cancelled_
int num_remaining_senders_
condition_variable data_arrival_cv_
condition_variable data_removal__cv_
RowBatchQueue batch_queue_
scoped_ptr< RowBatch > current_batch_
bool received_first_batch_
Detailed Description
Definition at line 34 of file data-stream-recvr.cc.
Member Typedef Documentation
typedef list<pair<int, RowBatch*> > impala::DataStreamRecvr::SenderQueue::RowBatchQueue private
Definition at line 89 of file data-stream-recvr.cc.
Constructor & Destructor Documentation
impala::DataStreamRecvr::SenderQueue::SenderQueue (DataStreamRecvr * parent_recvr, int num_senders, RuntimeProfile * profile)
Definition at line 101 of file data-stream-recvr.cc.
Member Function Documentation
void impala::DataStreamRecvr::SenderQueue::AddBatch (const TRowBatch & batch)
Definition at line 144 of file data-stream-recvr.cc.
References COUNTER_ADD, impala::RowBatch::GetBatchSize(), impala::lock_, SCOPED_TIMER, and VLOG_ROW.
void impala::DataStreamRecvr::SenderQueue::Cancel ()
Definition at line 226 of file data-stream-recvr.cc.
References impala::lock_, impala::PeriodicCounterUpdater::StopTimeSeriesCounter(), and VLOG_QUERY.
void impala::DataStreamRecvr::SenderQueue::Close ()
Definition at line 243 of file data-stream-recvr.cc.
RowBatch* impala::DataStreamRecvr::SenderQueue::current_batch () const inline
Definition at line 65 of file data-stream-recvr.cc.
References current_batch_.
Referenced by impala::DataStreamRecvr::TransferAllResources().
void impala::DataStreamRecvr::SenderQueue::DecrementSenders ()
Definition at line 215 of file data-stream-recvr.cc.
References data_arrival_cv_, impala::DataStreamRecvr::dest_node_id(), impala::DataStreamRecvr::fragment_instance_id(), lock_, num_remaining_senders_, recvr_, and VLOG_FILE.
Status impala::DataStreamRecvr::SenderQueue::GetBatch (RowBatch ** next_batch)
Definition at line 109 of file data-stream-recvr.cc.
References impala::Status::CANCELLED, impala::lock_, impala::Status::OK, SCOPED_TIMER, and VLOG_ROW.
Referenced by impala::DataStreamRecvr::CreateMerger().
Member Data Documentation
RowBatchQueue impala::DataStreamRecvr::SenderQueue::batch_queue_ private
Definition at line 90 of file data-stream-recvr.cc.
scoped_ptr<RowBatch> impala::DataStreamRecvr::SenderQueue::current_batch_ private
Definition at line 95 of file data-stream-recvr.cc.
Referenced by current_batch().
condition_variable impala::DataStreamRecvr::SenderQueue::data_arrival_cv_ private
Definition at line 82 of file data-stream-recvr.cc.
Referenced by DecrementSenders().
condition_variable impala::DataStreamRecvr::SenderQueue::data_removal__cv_ private
Definition at line 85 of file data-stream-recvr.cc.
bool impala::DataStreamRecvr::SenderQueue::is_cancelled_ private
Definition at line 75 of file data-stream-recvr.cc.
mutex impala::DataStreamRecvr::SenderQueue::lock_ private
Definition at line 72 of file data-stream-recvr.cc.
Referenced by DecrementSenders().
int impala::DataStreamRecvr::SenderQueue::num_remaining_senders_ private
Definition at line 79 of file data-stream-recvr.cc.
Referenced by DecrementSenders().
bool impala::DataStreamRecvr::SenderQueue::received_first_batch_ private
Definition at line 98 of file data-stream-recvr.cc.
DataStreamRecvr* impala::DataStreamRecvr::SenderQueue::recvr_ private
Definition at line 69 of file data-stream-recvr.cc.
Referenced by DecrementSenders().
The documentation for this class was generated from the following file:
be/src/runtime/data-stream-recvr.cc