Impala: com.cloudera.impala.analysis.AnalyticWindow.Boundary Class Reference
com.cloudera.impala.analysis.AnalyticWindow.Boundary Class Reference
Public Member Functions
BoundaryType getType ()
Expr getExpr ()
BigDecimal getOffsetValue ()
Boundary (BoundaryType type, Expr e)
String toSql ()
TAnalyticWindowBoundary toThrift (Type windowType)
boolean equals (Object obj)
Boundary converse ()
Boundary clone ()
void analyze (Analyzer analyzer) throws AnalysisException
Private Member Functions
Boundary (BoundaryType type, Expr e, BigDecimal offsetValue)
Private Attributes
final BoundaryType type_
final Expr expr_
BigDecimal offsetValue_
Detailed Description
Definition at line 112 of file AnalyticWindow.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary (BoundaryType type, Expr e) inline
Definition at line 126 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.Boundary.clone(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.converse(), and com.cloudera.impala.analysis.AnalyticWindow.Boundary.equals().
com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary (BoundaryType type, Expr e, BigDecimal offsetValue) inline private
Definition at line 131 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_, com.cloudera.impala.analysis.AnalyticWindow.Boundary.offsetValue_, and com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_.
Member Function Documentation
void com.cloudera.impala.analysis.AnalyticWindow.Boundary.analyze (Analyzer analyzer) throws AnalysisException inline
Definition at line 178 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_.
Boundary com.cloudera.impala.analysis.AnalyticWindow.Boundary.clone () inline
Definition at line 174 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary(), com.cloudera.impala.analysis.Expr.clone(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_, com.cloudera.impala.analysis.AnalyticWindow.Boundary.offsetValue_, and com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_.
Boundary com.cloudera.impala.analysis.AnalyticWindow.Boundary.converse () inline
Definition at line 166 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary(), com.cloudera.impala.analysis.Expr.clone(), com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.converse(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_, com.cloudera.impala.analysis.AnalyticWindow.Boundary.offsetValue_, and com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_.
boolean com.cloudera.impala.analysis.AnalyticWindow.Boundary.equals (Object obj) inline
Definition at line 157 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_, and com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_.
Expr com.cloudera.impala.analysis.AnalyticWindow.Boundary.getExpr () inline
Definition at line 123 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_.
BigDecimal com.cloudera.impala.analysis.AnalyticWindow.Boundary.getOffsetValue () inline
Definition at line 124 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.offsetValue_.
BoundaryType com.cloudera.impala.analysis.AnalyticWindow.Boundary.getType () inline
Definition at line 122 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), com.cloudera.impala.analysis.AnalyticWindow.reverse(), and com.cloudera.impala.analysis.AnalyticWindow.toThrift().
String com.cloudera.impala.analysis.AnalyticWindow.Boundary.toSql () inline
Definition at line 140 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.toSql().
TAnalyticWindowBoundary com.cloudera.impala.analysis.AnalyticWindow.Boundary.toThrift (Type windowType) inline
Definition at line 147 of file AnalyticWindow.java.
References com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.isOffset(), com.cloudera.impala.analysis.AnalyticWindow.Type.ROWS, com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.toThrift(), and com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_.
Member Data Documentation
final Expr com.cloudera.impala.analysis.AnalyticWindow.Boundary.expr_ private
Definition at line 116 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.Boundary.analyze(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.clone(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.converse(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.equals(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.getExpr(), and com.cloudera.impala.analysis.AnalyticWindow.Boundary.toSql().
BigDecimal com.cloudera.impala.analysis.AnalyticWindow.Boundary.offsetValue_ private
Definition at line 120 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.clone(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.converse(), and com.cloudera.impala.analysis.AnalyticWindow.Boundary.getOffsetValue().
final BoundaryType com.cloudera.impala.analysis.AnalyticWindow.Boundary.type_ private
Definition at line 113 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.Boundary(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.clone(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.converse(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.equals(), com.cloudera.impala.analysis.AnalyticWindow.Boundary.getType(), and com.cloudera.impala.analysis.AnalyticWindow.Boundary.toThrift().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AnalyticWindow.java