Impala: com.cloudera.impala.catalog.BuiltinsDb Class Reference
com.cloudera.impala.catalog.BuiltinsDb Class Reference
Public Member Functions
BuiltinsDb (String name, Catalog catalog)
void setIsSystemDb (boolean b)
boolean isSystemDb ()
TDatabase toThrift ()
String getName ()
TCatalogObjectType getCatalogObjectType ()
void addTable (Table table)
List< String > getAllTableNames ()
boolean containsTable (String tableName)
Table getTable (String tblName)
Table removeTable (String tableName)
int numFunctions ()
boolean containsFunction (String name)
Function getFunction (Function desc, Function.CompareMode mode)
Function getFunction (String signatureString)
boolean addFunction (Function fn)
Function removeFunction (Function desc)
Function removeFunction (String signatureStr)
void addScalarBuiltin (String fnName, String symbol, boolean varArgs, Type retType, Type...args)
void addScalarBuiltin (String fnName, String symbol, String prepareFnSymbol, String closeFnSymbol, boolean varArgs, Type retType, Type...args)
void addBuiltin (Function fn)
List< Function > getFunctions (TFunctionCategory category, PatternMatcher fnPattern)
long getCatalogVersion ()
void setCatalogVersion (long newVersion)
Catalog getParentCatalog ()
boolean isLoaded ()
Static Public Member Functions
static Db fromTDatabase (TDatabase db, Catalog parentCatalog)
Protected Member Functions
HashMap< String, List< Function > > getAllFunctions ()
Private Member Functions
void initBuiltins ()
void initAggregateBuiltins ()
Static Private Attributes
static final Map< Type, String > SAMPLE_INIT_SYMBOL
static final Map< Type, String > SAMPLE_SERIALIZE_SYMBOL
static final Map< Type, String > SAMPLE_MERGE_SYMBOL
static final Map< Type, String > SAMPLE_UPDATE_SYMBOL
static final Map< Type, String > SAMPLE_FINALIZE_SYMBOL
static final Map< Type, String > APPX_MEDIAN_FINALIZE_SYMBOL
static final Map< Type, String > HISTOGRAM_FINALIZE_SYMBOL
static final Map< Type, String > HLL_UPDATE_SYMBOL
static final Map< Type, String > PC_UPDATE_SYMBOL
static final Map< Type, String > PCSA_UPDATE_SYMBOL
static final Map< Type, String > MIN_UPDATE_SYMBOL
static final Map< Type, String > MAX_UPDATE_SYMBOL
static final Map< Type, String > STDDEV_UPDATE_SYMBOL
static final Map< Type, String > OFFSET_FN_INIT_SYMBOL
static final Map< Type, String > OFFSET_FN_UPDATE_SYMBOL
static final Map< Type, String > LAST_VALUE_UPDATE_SYMBOL
static final Map< Type, String > FIRST_VALUE_REWRITE_UPDATE_SYMBOL
static final Map< Type, String > LAST_VALUE_REMOVE_SYMBOL
static final Map< Type, String > FIRST_VALUE_UPDATE_SYMBOL
Detailed Description
Definition at line 32 of file BuiltinsDb.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.BuiltinsDb.BuiltinsDb (String name, Catalog catalog) inline
Definition at line 33 of file BuiltinsDb.java.
References com.cloudera.impala.catalog.BuiltinsDb.initBuiltins(), and com.cloudera.impala.catalog.Db.setIsSystemDb().
Member Function Documentation
void com.cloudera.impala.catalog.Db.addBuiltin (Function fn) inline inherited
Adds a builtin to this database. The function must not already exist.
Definition at line 247 of file Db.java.
References com.cloudera.impala.catalog.Db.addFunction(), com.cloudera.impala.catalog.Db.getFunction(), com.cloudera.impala.catalog.Function.CompareMode.IS_IDENTICAL, and com.cloudera.impala.catalog.Db.isSystemDb().
Referenced by com.cloudera.impala.catalog.Db.addScalarBuiltin().
boolean com.cloudera.impala.catalog.Db.addFunction (Function fn) inline inherited
See comment in Catalog.
Definition at line 179 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, com.cloudera.impala.catalog.Db.getFunction(), and com.cloudera.impala.catalog.Db.getName().
Referenced by com.cloudera.impala.catalog.Db.addBuiltin(), and com.cloudera.impala.catalog.CatalogServiceCatalog.addFunction().
void com.cloudera.impala.catalog.Db.addScalarBuiltin (String fnName, String symbol, boolean varArgs, Type retType, Type... args) inline inherited
Add a builtin with the specified name and signatures to this db. This defaults to not using a Prepare/Close function.
Definition at line 228 of file Db.java.
void com.cloudera.impala.catalog.Db.addScalarBuiltin (String fnName, String symbol, String prepareFnSymbol, String closeFnSymbol, boolean varArgs, Type retType, Type... args) inline inherited
Add a builtin with the specified name and signatures to this db.
Definition at line 236 of file Db.java.
References com.cloudera.impala.catalog.Db.addBuiltin(), com.cloudera.impala.catalog.ScalarFunction.createBuiltin(), and com.cloudera.impala.catalog.Db.isSystemDb().
void com.cloudera.impala.catalog.Db.addTable (Table table) inline inherited
Adds a table to the table cache.
Definition at line 89 of file Db.java.
boolean com.cloudera.impala.catalog.Db.containsFunction (String name) inline inherited
See comment in Catalog.
Definition at line 131 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, and impala.name.
Referenced by com.cloudera.impala.analysis.FunctionName.analyze(), and com.cloudera.impala.analysis.FunctionCallExpr.analyze().
boolean com.cloudera.impala.catalog.Db.containsTable (String tableName) inline inherited
Definition at line 100 of file Db.java.
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.invalidateTable().
static Db com.cloudera.impala.catalog.Db.fromTDatabase (TDatabase db, Catalog parentCatalog) inline static inherited
Creates a Db object with no tables based on the given TDatabase thrift struct.
Definition at line 75 of file Db.java.
References com.cloudera.impala.catalog.Db.Db().
HashMap<String, List<Function> > com.cloudera.impala.catalog.Db.getAllFunctions () inline protected inherited
Returns a map of functionNames to list of (overloaded) functions with that name. This is not thread safe so a higher level lock must be taken while iterating over the returned functions.
Definition at line 259 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
List<String> com.cloudera.impala.catalog.Db.getAllTableNames () inline inherited
Gets all table names in the table cache.
Definition at line 96 of file Db.java.
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects(), and com.cloudera.impala.testutil.BlockIdGenerator.main().
TCatalogObjectType com.cloudera.impala.catalog.Db.getCatalogObjectType () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 82 of file Db.java.
long com.cloudera.impala.catalog.Db.getCatalogVersion () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 292 of file Db.java.
References com.cloudera.impala.catalog.Db.catalogVersion_.
Referenced by com.cloudera.impala.catalog.ImpaladCatalog.addDb(), com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects(), and com.cloudera.impala.catalog.ImpaladCatalog.removeDb().
Function com.cloudera.impala.catalog.Db.getFunction (Function desc, Function.CompareMode mode) inline inherited
Definition at line 140 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
Referenced by com.cloudera.impala.catalog.Db.addBuiltin(), com.cloudera.impala.catalog.Db.addFunction(), and com.cloudera.impala.catalog.Db.removeFunction().
Function com.cloudera.impala.catalog.Db.getFunction (String signatureString) inline inherited
Definition at line 165 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
List<Function> com.cloudera.impala.catalog.Db.getFunctions (TFunctionCategory category, PatternMatcher fnPattern) inline inherited
Returns all functions that match 'fnPattern'.
Definition at line 266 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, and com.cloudera.impala.util.PatternMatcher.matches().
Referenced by com.cloudera.impala.catalog.CatalogServiceCatalog.getCatalogObjects().
String com.cloudera.impala.catalog.Db.getName () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 81 of file Db.java.
Referenced by com.cloudera.impala.catalog.Catalog.addDb(), com.cloudera.impala.catalog.Db.addFunction(), com.cloudera.impala.catalog.AggregateFunction.createAnalyticBuiltin(), com.cloudera.impala.catalog.AggregateFunction.createBuiltin(), com.cloudera.impala.service.CatalogOpExecutor.dropDatabase(), com.cloudera.impala.service.MetadataOp.getDbsMetadata(), com.cloudera.impala.catalog.Table.getFullName(), com.cloudera.impala.catalog.Table.getTableName(), com.cloudera.impala.catalog.View.init(), com.cloudera.impala.catalog.TableLoader.load(), com.cloudera.impala.catalog.HdfsTable.load(), com.cloudera.impala.catalog.ImpaladCatalog.removeDb(), com.cloudera.impala.catalog.CatalogTest.TestColSchema(), com.cloudera.impala.catalog.IncompleteTable.toThrift(), com.cloudera.impala.catalog.Table.toThrift(), com.cloudera.impala.catalog.DataSourceTable.toThriftDescriptor(), com.cloudera.impala.catalog.HBaseTable.toThriftDescriptor(), and com.cloudera.impala.catalog.HdfsTable.toThriftDescriptor().
Catalog com.cloudera.impala.catalog.Db.getParentCatalog () inline inherited
Definition at line 295 of file Db.java.
References com.cloudera.impala.catalog.Db.parentCatalog_.
Table com.cloudera.impala.catalog.Db.getTable (String tblName) inline inherited
Returns the Table with the given name if present in the table cache or null if the table does not exist in the cache.
Definition at line 108 of file Db.java.
void com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins () inline private
Definition at line 509 of file BuiltinsDb.java.
References com.cloudera.impala.catalog.BuiltinsDb.APPX_MEDIAN_FINALIZE_SYMBOL, com.cloudera.impala.catalog.Type.BIGINT, com.cloudera.impala.catalog.PrimitiveType.CHAR, com.cloudera.impala.catalog.ScalarType.createCharType(), com.cloudera.impala.catalog.Type.DECIMAL, com.cloudera.impala.catalog.Type.DOUBLE, com.cloudera.impala.catalog.Type.getSupportedTypes(), com.cloudera.impala.catalog.BuiltinsDb.HISTOGRAM_FINALIZE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.HLL_UPDATE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.LAST_VALUE_REMOVE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.MAX_UPDATE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.MIN_UPDATE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.OFFSET_FN_INIT_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.PC_UPDATE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.PCSA_UPDATE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_FINALIZE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_INIT_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_MERGE_SYMBOL, com.cloudera.impala.catalog.BuiltinsDb.STDDEV_UPDATE_SYMBOL, com.cloudera.impala.catalog.Type.STRING, com.cloudera.impala.catalog.Type.TIMESTAMP, and com.cloudera.impala.catalog.PrimitiveType.VARCHAR.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initBuiltins().
void com.cloudera.impala.catalog.BuiltinsDb.initBuiltins () inline private
Initializes all the builtins.
Definition at line 42 of file BuiltinsDb.java.
References com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
Referenced by com.cloudera.impala.catalog.BuiltinsDb.BuiltinsDb().
boolean com.cloudera.impala.catalog.Db.isLoaded () inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 298 of file Db.java.
boolean com.cloudera.impala.catalog.Db.isSystemDb () inline inherited
Definition at line 79 of file Db.java.
References com.cloudera.impala.catalog.Db.isSystemDb_.
Referenced by com.cloudera.impala.catalog.Db.addBuiltin(), com.cloudera.impala.catalog.Db.addScalarBuiltin(), and com.cloudera.impala.analysis.Analyzer.checkSystemDbAccess().
int com.cloudera.impala.catalog.Db.numFunctions () inline inherited
Returns the number of functions in this database.
Definition at line 122 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_.
Referenced by com.cloudera.impala.analysis.DropDbStmt.analyze(), and com.cloudera.impala.service.CatalogOpExecutor.dropDatabase().
Function com.cloudera.impala.catalog.Db.removeFunction (Function desc) inline inherited
See comment in Catalog.
Definition at line 198 of file Db.java.
References com.cloudera.impala.catalog.Function.functionName(), com.cloudera.impala.catalog.Db.functions_, and com.cloudera.impala.catalog.Db.getFunction().
Referenced by com.cloudera.impala.catalog.Db.removeFunction().
Function com.cloudera.impala.catalog.Db.removeFunction (String signatureStr) inline inherited
Removes a Function with the matching signature string. Returns the removed Function if a Function was removed as a result of this call, null otherwise. TODO: Move away from using signature strings and instead use Function IDs.
Definition at line 216 of file Db.java.
References com.cloudera.impala.catalog.Db.functions_, com.cloudera.impala.catalog.Db.getFunction(), and com.cloudera.impala.catalog.Db.removeFunction().
Table com.cloudera.impala.catalog.Db.removeTable (String tableName) inline inherited
Removes the table name and any cached metadata from the Table cache.
Definition at line 115 of file Db.java.
void com.cloudera.impala.catalog.Db.setCatalogVersion (long newVersion) inline inherited
Implements com.cloudera.impala.catalog.CatalogObject.
Definition at line 294 of file Db.java.
References com.cloudera.impala.catalog.Db.catalogVersion_.
void com.cloudera.impala.catalog.Db.setIsSystemDb (boolean b) inline inherited
Definition at line 70 of file Db.java.
References com.cloudera.impala.catalog.Db.isSystemDb_.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.BuiltinsDb().
TDatabase com.cloudera.impala.catalog.Db.toThrift () inline inherited
Definition at line 80 of file Db.java.
References com.cloudera.impala.catalog.Db.thriftDb_.
Member Data Documentation
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.APPX_MEDIAN_FINALIZE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "18AppxMedianFinalizeIN10impala_udf10BooleanValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.DECIMAL,
            "18AppxMedianFinalizeIN10impala_udf10DecimalValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.TINYINT,
            "18AppxMedianFinalizeIN10impala_udf10TinyIntValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.SMALLINT,
            "18AppxMedianFinalizeIN10impala_udf11SmallIntValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.TIMESTAMP,
            "18AppxMedianFinalizeIN10impala_udf12TimestampValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.INT,
            "18AppxMedianFinalizeIN10impala_udf6IntValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.FLOAT,
            "18AppxMedianFinalizeIN10impala_udf8FloatValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.BIGINT,
            "18AppxMedianFinalizeIN10impala_udf9BigIntValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.DOUBLE,
            "18AppxMedianFinalizeIN10impala_udf9DoubleValEEET_PNS2_15FunctionContextERKNS2_9StringValE")
        .put(Type.STRING,
            "18AppxMedianFinalizeIN10impala_udf9StringValEEET_PNS2_15FunctionContextERKS3_")
        .build()
Definition at line 178 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.FIRST_VALUE_REWRITE_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "21FirstValRewriteUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.DECIMAL,
             "21FirstValRewriteUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.TINYINT,
             "21FirstValRewriteUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.SMALLINT,
             "21FirstValRewriteUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.TIMESTAMP,
             "21FirstValRewriteUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.INT,
             "21FirstValRewriteUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.FLOAT,
             "21FirstValRewriteUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.BIGINT,
             "21FirstValRewriteUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_RKS3_PS6_")
        .put(Type.DOUBLE,
             "21FirstValRewriteUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .put(Type.STRING,
             "21FirstValRewriteUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValEPS6_")
        .build()
Definition at line 433 of file BuiltinsDb.java.
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.FIRST_VALUE_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "14FirstValUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DECIMAL,
             "14FirstValUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TINYINT,
             "14FirstValUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.SMALLINT,
             "14FirstValUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TIMESTAMP,
             "14FirstValUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.INT,
             "14FirstValUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.FLOAT,
             "14FirstValUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.BIGINT,
             "14FirstValUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DOUBLE,
             "14FirstValUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.STRING,
             "14FirstValUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS6_")
        .build()
Definition at line 481 of file BuiltinsDb.java.
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.HISTOGRAM_FINALIZE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "17HistogramFinalizeIN10impala_udf10BooleanValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.TINYINT,
             "17HistogramFinalizeIN10impala_udf10TinyIntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.SMALLINT,
             "17HistogramFinalizeIN10impala_udf11SmallIntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.INT,
             "17HistogramFinalizeIN10impala_udf6IntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.BIGINT,
             "17HistogramFinalizeIN10impala_udf9BigIntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.FLOAT,
             "17HistogramFinalizeIN10impala_udf8FloatValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.DOUBLE,
             "17HistogramFinalizeIN10impala_udf9DoubleValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.STRING,
             "17HistogramFinalizeIN10impala_udf9StringValEEES3_PNS2_15FunctionContextERKS3_")
        .put(Type.TIMESTAMP,
             "17HistogramFinalizeIN10impala_udf12TimestampValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.DECIMAL,
             "17HistogramFinalizeIN10impala_udf10DecimalValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .build()
Definition at line 202 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.HLL_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "9HllUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.TINYINT,
            "9HllUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.SMALLINT,
            "9HllUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.INT,
            "9HllUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.BIGINT,
            "9HllUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.FLOAT,
            "9HllUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.DOUBLE,
            "9HllUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.STRING,
            "9HllUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS3_")
        .put(Type.TIMESTAMP,
            "9HllUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.DECIMAL,
            "9HllUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .build()
Definition at line 226 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.LAST_VALUE_REMOVE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "13LastValRemoveIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DECIMAL,
             "13LastValRemoveIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TINYINT,
             "13LastValRemoveIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.SMALLINT,
             "13LastValRemoveIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TIMESTAMP,
             "13LastValRemoveIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.INT,
             "13LastValRemoveIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.FLOAT,
             "13LastValRemoveIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.BIGINT,
             "13LastValRemoveIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DOUBLE,
             "13LastValRemoveIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.STRING,
             "13LastValRemoveIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS6_")
        .build()
Definition at line 457 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.LAST_VALUE_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "13LastValUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DECIMAL,
             "13LastValUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TINYINT,
             "13LastValUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.SMALLINT,
             "13LastValUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TIMESTAMP,
             "13LastValUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.INT,
             "13LastValUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.FLOAT,
             "13LastValUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.BIGINT,
             "13LastValUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DOUBLE,
             "13LastValUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.STRING,
             "13LastValUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS6_")
        .build()
Definition at line 409 of file BuiltinsDb.java.
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.MAX_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "3MaxIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TINYINT,
            "3MaxIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.SMALLINT,
            "3MaxIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.INT,
            "3MaxIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.BIGINT,
            "3MaxIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.FLOAT,
            "3MaxIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DOUBLE,
            "3MaxIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.STRING,
            "3MaxIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TIMESTAMP,
            "3MaxIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DECIMAL,
            "3MaxIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PS6_")
        .build()
Definition at line 322 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.MIN_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "3MinIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TINYINT,
            "3MinIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.SMALLINT,
            "3MinIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.INT,
            "3MinIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.BIGINT,
            "3MinIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.FLOAT,
            "3MinIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DOUBLE,
            "3MinIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.STRING,
            "3MinIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.TIMESTAMP,
            "3MinIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PS6_")
        .put(Type.DECIMAL,
            "3MinIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PS6_")
        .build()
Definition at line 298 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.OFFSET_FN_INIT_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "12OffsetFnInitIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.DECIMAL,
             "12OffsetFnInitIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.TINYINT,
             "12OffsetFnInitIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.SMALLINT,
             "12OffsetFnInitIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.TIMESTAMP,
             "12OffsetFnInitIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.INT,
             "12OffsetFnInitIN10impala_udf6IntValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.FLOAT,
             "12OffsetFnInitIN10impala_udf8FloatValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.BIGINT,
             "12OffsetFnInitIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.DOUBLE,
             "12OffsetFnInitIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextEPT_")
        .put(Type.STRING,
             "12OffsetFnInitIN10impala_udf9StringValEEEvPNS2_15FunctionContextEPT_")
        .build()
Definition at line 361 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.OFFSET_FN_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "14OffsetFnUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.DECIMAL,
             "14OffsetFnUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.TINYINT,
             "14OffsetFnUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.SMALLINT,
             "14OffsetFnUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.TIMESTAMP,
             "14OffsetFnUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.INT,
             "14OffsetFnUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.FLOAT,
             "14OffsetFnUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.BIGINT,
             "14OffsetFnUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_RKS3_S8_PS6_")
        .put(Type.DOUBLE,
             "14OffsetFnUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .put(Type.STRING,
             "14OffsetFnUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_RKNS2_9BigIntValES8_PS6_")
        .build()
Definition at line 385 of file BuiltinsDb.java.
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.PC_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "8PcUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.TINYINT,
            "8PcUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.SMALLINT,
            "8PcUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.INT,
            "8PcUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.BIGINT,
            "8PcUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.FLOAT,
            "8PcUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.DOUBLE,
            "8PcUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.STRING,
            "8PcUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS3_")
        .put(Type.TIMESTAMP,
            "8PcUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
         .put(Type.DECIMAL,
            "8PcUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .build()
Definition at line 250 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.PCSA_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
          .put(Type.BOOLEAN,
              "10PcsaUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.TINYINT,
              "10PcsaUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.SMALLINT,
              "10PcsaUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.INT,
              "10PcsaUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.BIGINT,
              "10PcsaUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.FLOAT,
              "10PcsaUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.DOUBLE,
              "10PcsaUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.STRING,
              "10PcsaUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS3_")
          .put(Type.TIMESTAMP,
              "10PcsaUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .put(Type.DECIMAL,
              "10PcsaUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
          .build()
Definition at line 274 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_FINALIZE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "23ReservoirSampleFinalizeIN10impala_udf10BooleanValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.TINYINT,
             "23ReservoirSampleFinalizeIN10impala_udf10TinyIntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.SMALLINT,
             "23ReservoirSampleFinalizeIN10impala_udf11SmallIntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.INT,
             "23ReservoirSampleFinalizeIN10impala_udf6IntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.BIGINT,
             "23ReservoirSampleFinalizeIN10impala_udf9BigIntValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.FLOAT,
             "23ReservoirSampleFinalizeIN10impala_udf8FloatValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.DOUBLE,
             "23ReservoirSampleFinalizeIN10impala_udf9DoubleValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.STRING,
             "23ReservoirSampleFinalizeIN10impala_udf9StringValEEES3_PNS2_15FunctionContextERKS3_")
        .put(Type.TIMESTAMP,
             "23ReservoirSampleFinalizeIN10impala_udf12TimestampValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .put(Type.DECIMAL,
             "23ReservoirSampleFinalizeIN10impala_udf10DecimalValEEENS2_9StringValEPNS2_15FunctionContextERKS4_")
        .build()
Definition at line 154 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_INIT_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "19ReservoirSampleInitIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.TINYINT,
            "19ReservoirSampleInitIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.SMALLINT,
            "19ReservoirSampleInitIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.INT,
            "19ReservoirSampleInitIN10impala_udf6IntValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.BIGINT,
            "19ReservoirSampleInitIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.FLOAT,
            "19ReservoirSampleInitIN10impala_udf8FloatValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.DOUBLE,
            "19ReservoirSampleInitIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.STRING,
            "19ReservoirSampleInitIN10impala_udf9StringValEEEvPNS2_15FunctionContextEPS3_")
        .put(Type.TIMESTAMP,
            "19ReservoirSampleInitIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .put(Type.DECIMAL,
            "19ReservoirSampleInitIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextEPNS2_9StringValE")
        .build()
Definition at line 58 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_MERGE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "20ReservoirSampleMergeIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.TINYINT,
            "20ReservoirSampleMergeIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.SMALLINT,
            "20ReservoirSampleMergeIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.INT,
            "20ReservoirSampleMergeIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.BIGINT,
            "20ReservoirSampleMergeIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.FLOAT,
            "20ReservoirSampleMergeIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.DOUBLE,
            "20ReservoirSampleMergeIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.STRING,
            "20ReservoirSampleMergeIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKS3_PS3_")
        .put(Type.TIMESTAMP,
            "20ReservoirSampleMergeIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .put(Type.DECIMAL,
            "20ReservoirSampleMergeIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKNS2_9StringValEPS6_")
        .build()
Definition at line 106 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_SERIALIZE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
             "24ReservoirSampleSerializeIN10impala_udf10BooleanValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.TINYINT,
             "24ReservoirSampleSerializeIN10impala_udf10TinyIntValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.SMALLINT,
             "24ReservoirSampleSerializeIN10impala_udf11SmallIntValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.INT,
             "24ReservoirSampleSerializeIN10impala_udf6IntValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.BIGINT,
             "24ReservoirSampleSerializeIN10impala_udf9BigIntValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.FLOAT,
             "24ReservoirSampleSerializeIN10impala_udf8FloatValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.DOUBLE,
             "24ReservoirSampleSerializeIN10impala_udf9DoubleValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.STRING,
             "24ReservoirSampleSerializeIN10impala_udf9StringValEEEKS3_PNS2_15FunctionContextERS4_")
        .put(Type.TIMESTAMP,
             "24ReservoirSampleSerializeIN10impala_udf12TimestampValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .put(Type.DECIMAL,
             "24ReservoirSampleSerializeIN10impala_udf10DecimalValEEEKNS2_9StringValEPNS2_15FunctionContextERS5_")
        .build()
Definition at line 82 of file BuiltinsDb.java.
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.SAMPLE_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.BOOLEAN,
            "21ReservoirSampleUpdateIN10impala_udf10BooleanValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.TINYINT,
            "21ReservoirSampleUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.SMALLINT,
            "21ReservoirSampleUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.INT,
            "21ReservoirSampleUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.BIGINT,
            "21ReservoirSampleUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.FLOAT,
            "21ReservoirSampleUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.DOUBLE,
            "21ReservoirSampleUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.STRING,
            "21ReservoirSampleUpdateIN10impala_udf9StringValEEEvPNS2_15FunctionContextERKT_PS3_")
        .put(Type.TIMESTAMP,
            "21ReservoirSampleUpdateIN10impala_udf12TimestampValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.DECIMAL,
            "21ReservoirSampleUpdateIN10impala_udf10DecimalValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .build()
Definition at line 130 of file BuiltinsDb.java.
final Map<Type, String> com.cloudera.impala.catalog.BuiltinsDb.STDDEV_UPDATE_SYMBOL static private
Initial value:
=
      ImmutableMap.<Type, String>builder()
        .put(Type.TINYINT,
            "14KnuthVarUpdateIN10impala_udf10TinyIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.SMALLINT,
            "14KnuthVarUpdateIN10impala_udf11SmallIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.INT,
            "14KnuthVarUpdateIN10impala_udf6IntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.BIGINT,
            "14KnuthVarUpdateIN10impala_udf9BigIntValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.FLOAT,
            "14KnuthVarUpdateIN10impala_udf8FloatValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .put(Type.DOUBLE,
            "14KnuthVarUpdateIN10impala_udf9DoubleValEEEvPNS2_15FunctionContextERKT_PNS2_9StringValE")
        .build()
Definition at line 346 of file BuiltinsDb.java.
Referenced by com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/BuiltinsDb.java