Impala: com.cloudera.impala.common.RuntimeEnv Class Reference
com.cloudera.impala.common.RuntimeEnv Class Reference
Public Member Functions
RuntimeEnv ()
void reset ()
int getNumCores ()
void setNumCores (int numCores)
void setTestEnv (boolean v)
boolean isTestEnv ()
boolean computeLineage ()
Static Public Attributes
static RuntimeEnv INSTANCE = new RuntimeEnv()
Private Attributes
int numCores_
boolean computeLineage_
boolean isTestEnv_
Static Private Attributes
static final Logger LOG = LoggerFactory.getLogger(RuntimeEnv.class)
Detailed Description
Contains runtime-specific parameters such as the number of CPU cores. Currently only used in Plan cost estimation. The static RuntimeEnv members can be set so that tests can rely on a machine-independent RuntimeEnv.
Definition at line 30 of file RuntimeEnv.java.
Constructor & Destructor Documentation
com.cloudera.impala.common.RuntimeEnv.RuntimeEnv () inline
Definition at line 43 of file RuntimeEnv.java.
References com.cloudera.impala.common.RuntimeEnv.computeLineage_, and com.cloudera.impala.common.RuntimeEnv.reset().
Member Function Documentation
boolean com.cloudera.impala.common.RuntimeEnv.computeLineage () inline
Definition at line 65 of file RuntimeEnv.java.
References com.cloudera.impala.common.RuntimeEnv.computeLineage_.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), com.cloudera.impala.analysis.CreateViewStmt.analyze(), and com.cloudera.impala.planner.Planner.createPlan().
int com.cloudera.impala.common.RuntimeEnv.getNumCores () inline
Definition at line 61 of file RuntimeEnv.java.
References com.cloudera.impala.common.RuntimeEnv.numCores_.
boolean com.cloudera.impala.common.RuntimeEnv.isTestEnv () inline
Definition at line 64 of file RuntimeEnv.java.
References com.cloudera.impala.common.RuntimeEnv.isTestEnv_.
void com.cloudera.impala.common.RuntimeEnv.reset () inline
Resets this RuntimeEnv back to its machine-dependent state.
Definition at line 57 of file RuntimeEnv.java.
References com.cloudera.impala.common.RuntimeEnv.numCores_.
Referenced by com.cloudera.impala.common.RuntimeEnv.RuntimeEnv().
void com.cloudera.impala.common.RuntimeEnv.setNumCores (int numCores) inline
Definition at line 62 of file RuntimeEnv.java.
void com.cloudera.impala.common.RuntimeEnv.setTestEnv (boolean v) inline
Definition at line 63 of file RuntimeEnv.java.
References com.cloudera.impala.common.RuntimeEnv.isTestEnv_.
Member Data Documentation
boolean com.cloudera.impala.common.RuntimeEnv.computeLineage_ private
Definition at line 38 of file RuntimeEnv.java.
Referenced by com.cloudera.impala.common.RuntimeEnv.computeLineage(), and com.cloudera.impala.common.RuntimeEnv.RuntimeEnv().
RuntimeEnv com.cloudera.impala.common.RuntimeEnv.INSTANCE = new RuntimeEnv() static
Definition at line 33 of file RuntimeEnv.java.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), com.cloudera.impala.analysis.CreateViewStmt.analyze(), and com.cloudera.impala.planner.Planner.createPlan().
boolean com.cloudera.impala.common.RuntimeEnv.isTestEnv_ private
Definition at line 41 of file RuntimeEnv.java.
Referenced by com.cloudera.impala.common.RuntimeEnv.isTestEnv(), and com.cloudera.impala.common.RuntimeEnv.setTestEnv().
final Logger com.cloudera.impala.common.RuntimeEnv.LOG = LoggerFactory.getLogger(RuntimeEnv.class) static private
Definition at line 31 of file RuntimeEnv.java.
int com.cloudera.impala.common.RuntimeEnv.numCores_ private
Definition at line 35 of file RuntimeEnv.java.
Referenced by com.cloudera.impala.common.RuntimeEnv.getNumCores(), and com.cloudera.impala.common.RuntimeEnv.reset().
The documentation for this class was generated from the following file:
fe/src/main/java/com/cloudera/impala/common/RuntimeEnv.java