Impala: be/src/runtime/data-stream-test.cc File Reference
data-stream-test.cc File Reference
#include <boost/thread/thread.hpp>
#include <gtest/gtest.h>
#include "common/init.h"
#include "common/logging.h"
#include "common/status.h"
#include "codegen/llvm-codegen.h"
#include "exprs/slot-ref.h"
#include "rpc/auth-provider.h"
#include "rpc/thrift-server.h"
#include "runtime/row-batch.h"
#include "runtime/runtime-state.h"
#include "runtime/data-stream-mgr.h"
#include "runtime/data-stream-sender.h"
#include "runtime/data-stream-recvr.h"
#include "runtime/descriptors.h"
#include "runtime/client-cache.h"
#include "runtime/raw-value.h"
#include "service/fe-support.h"
#include "util/cpu-info.h"
#include "util/disk-info.h"
#include "util/debug-util.h"
#include "util/thread.h"
#include "util/time.h"
#include "util/mem-info.h"
#include "util/test-info.h"
#include "util/tuple-row-compare.h"
#include "gen-cpp/ImpalaInternalService.h"
#include "gen-cpp/ImpalaInternalService_types.h"
#include "gen-cpp/Types_types.h"
#include "gen-cpp/Descriptors_types.h"
#include <iostream>
#include "common/names.h"
Classes
class impala::ImpalaTestBackend
class impala::DataStreamTest
struct impala::DataStreamTest::SenderInfo
struct impala::DataStreamTest::ReceiverInfo
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Functions
DEFINE_int32 (port, 20001,"port on which to run Impala test backend")
DECLARE_string (principal)
impala::TEST_F (DataStreamTest, UnknownSenderSmallResult)
impala::TEST_F (DataStreamTest, UnknownSenderLargeResult)
impala::TEST_F (DataStreamTest, Cancel)
impala::TEST_F (DataStreamTest, BasicTest)
int main (int argc, char **argv)
Function Documentation
DECLARE_string (principal)
DEFINE_int32 (port , 20001 , "port on which to run Impala test backend")
int main (int argc, char ** argv)
Definition at line 581 of file data-stream-test.cc.
References impala::TestInfo::BE_TEST, impala::InitCommonRuntime(), impala::InitFeSupport(), and impala::LlvmCodeGen::InitializeLlvm().