Impala: be/src/util/default-path-handlers.cc File Reference
default-path-handlers.cc File Reference
#include "util/default-path-handlers.h"
#include <sstream>
#include <fstream>
#include <sys/stat.h>
#include <boost/algorithm/string.hpp>
#include <boost/bind.hpp>
#include <google/malloc_extension.h>
#include <gutil/strings/substitute.h>
#include "common/logging.h"
#include "runtime/mem-tracker.h"
#include "util/debug-util.h"
#include "util/pprof-path-handlers.h"
#include "util/webserver.h"
#include "common/names.h"
Functions
DECLARE_bool (enable_process_lifetime_heap_profiling)
DEFINE_int64 (web_log_bytes, 1024 *1024,"The maximum number of bytes to display on the debug webserver's log page")
void LogsHandler (const Webserver::ArgumentMap &args, Document *document)
void FlagsHandler (const Webserver::ArgumentMap &args, Document *document)
void MemUsageHandler (MemTracker *mem_tracker, const Webserver::ArgumentMap &args, Document *document)
Function Documentation
DECLARE_bool (enable_process_lifetime_heap_profiling)
DEFINE_int64 (web_log_bytes , 1024 * 1024, "The maximum number of bytes to display on the debug webserver's log page")
void FlagsHandler (const Webserver::ArgumentMap & args, Document * document)
Definition at line 73 of file default-path-handlers.cc.
Referenced by impala::AddDefaultUrlCallbacks().
void LogsHandler (const Webserver::ArgumentMap & args, Document * document)
Definition at line 44 of file default-path-handlers.cc.
References impala::GetFullLogFilename().
Referenced by impala::AddDefaultUrlCallbacks().
void MemUsageHandler (MemTracker * mem_tracker, const Webserver::ArgumentMap & args, Document * document)
Definition at line 81 of file default-path-handlers.cc.
References impala::MemTracker::consumption(), impala::MemTracker::limit(), and impala::MemTracker::LogUsage().
Referenced by impala::AddDefaultUrlCallbacks().