Impala: be/src/runtime/disk-io-mgr-test.cc File Reference
disk-io-mgr-test.cc File Reference
#include <sched.h>
#include <boost/bind.hpp>
#include <boost/thread/thread.hpp>
#include <sys/stat.h>
#include <gtest/gtest.h>
#include "codegen/llvm-codegen.h"
#include "runtime/disk-io-mgr.h"
#include "runtime/disk-io-mgr-stress.h"
#include "runtime/mem-tracker.h"
#include "runtime/thread-resource-mgr.h"
#include "util/cpu-info.h"
#include "util/disk-info.h"
#include "util/thread.h"
#include "common/names.h"
Classes
class impala::DiskIoMgrTest
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Functions
impala::TEST_F (DiskIoMgrTest, SingleWriter)
impala::TEST_F (DiskIoMgrTest, InvalidWrite)
impala::TEST_F (DiskIoMgrTest, SingleWriterCancel)
impala::TEST_F (DiskIoMgrTest, SingleReader)
impala::TEST_F (DiskIoMgrTest, AddScanRangeTest)
impala::TEST_F (DiskIoMgrTest, SyncReadTest)
impala::TEST_F (DiskIoMgrTest, SingleReaderCancel)
impala::TEST_F (DiskIoMgrTest, MemLimits)
impala::TEST_F (DiskIoMgrTest, CachedReads)
impala::TEST_F (DiskIoMgrTest, MultipleReaderWriter)
impala::TEST_F (DiskIoMgrTest, MultipleReader)
impala::TEST_F (DiskIoMgrTest, StressTest)
impala::TEST_F (DiskIoMgrTest, Buffers)
int main (int argc, char **argv)
Variables
const int MIN_BUFFER_SIZE = 512
const int MAX_BUFFER_SIZE = 1024
const int LARGE_MEM_LIMIT = 1024 * 1024 * 1024
Function Documentation
int main (int argc, char ** argv)
Definition at line 1021 of file disk-io-mgr-test.cc.
References impala::DiskInfo::Init(), impala::CpuInfo::Init(), and impala::InitThreading().
Variable Documentation
const int LARGE_MEM_LIMIT = 1024 * 1024 * 1024
Definition at line 37 of file disk-io-mgr-test.cc.
Referenced by impala::TEST_F().
const int MAX_BUFFER_SIZE = 1024
Definition at line 36 of file disk-io-mgr-test.cc.
Referenced by impala::TEST_F().
const int MIN_BUFFER_SIZE = 512
Definition at line 35 of file disk-io-mgr-test.cc.
Referenced by impala::TEST_F().