Impala: com.cloudera.impala.analysis.BinaryPredicate.Operator Enum Reference
com.cloudera.impala.analysis.BinaryPredicate.Operator Enum Reference
Public Member Functions
String toString ()
String getName ()
TComparisonOp getThriftOp ()
Operator converse ()
Public Attributes
EQ =("=", "eq", TComparisonOp.EQ)
NE =("!=", "ne", TComparisonOp.NE)
LE =("<=", "le", TComparisonOp.LE)
GE =(">=", "ge", TComparisonOp.GE)
LT =("<", "lt", TComparisonOp.LT)
GT =(">", "gt", TComparisonOp.GT)
NULL_MATCHING_EQ =("=", "null_matching_eq", TComparisonOp.EQ)
Private Member Functions
Operator (String description, String name, TComparisonOp thriftOp)
Private Attributes
final String description_
final String name_
final TComparisonOp thriftOp_
Detailed Description
Definition at line 45 of file BinaryPredicate.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.BinaryPredicate.Operator.Operator (String description, String name, TComparisonOp thriftOp) inline private
Definition at line 61 of file BinaryPredicate.java.
References impala.name.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.createHBaseValueRange(), and com.cloudera.impala.analysis.Analyzer.registerConjunct().
Member Function Documentation
Operator com.cloudera.impala.analysis.BinaryPredicate.Operator.converse () inline
Definition at line 72 of file BinaryPredicate.java.
String com.cloudera.impala.analysis.BinaryPredicate.Operator.getName () inline
Definition at line 69 of file BinaryPredicate.java.
TComparisonOp com.cloudera.impala.analysis.BinaryPredicate.Operator.getThriftOp () inline
Definition at line 70 of file BinaryPredicate.java.
String com.cloudera.impala.analysis.BinaryPredicate.Operator.toString () inline
Definition at line 68 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.analysis.BinaryPredicate.toSqlImpl().
Member Data Documentation
final String com.cloudera.impala.analysis.BinaryPredicate.Operator.description_ private
Definition at line 57 of file BinaryPredicate.java.
com.cloudera.impala.analysis.BinaryPredicate.Operator.EQ =("=", "eq", TComparisonOp.EQ)
Definition at line 46 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.analysis.BinaryPredicate.analyze(), com.cloudera.impala.planner.HdfsScanNode.evalBinaryPredicate(), com.cloudera.impala.analysis.BinaryPredicate.getEqSlots(), and com.cloudera.impala.analysis.BinaryPredicate.negate().
com.cloudera.impala.analysis.BinaryPredicate.Operator.GE =(">=", "ge", TComparisonOp.GE)
Definition at line 49 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.evalBinaryPredicate(), and com.cloudera.impala.analysis.BinaryPredicate.negate().
com.cloudera.impala.analysis.BinaryPredicate.Operator.GT =(">", "gt", TComparisonOp.GT)
Definition at line 51 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.evalBinaryPredicate(), and com.cloudera.impala.analysis.BinaryPredicate.negate().
com.cloudera.impala.analysis.BinaryPredicate.Operator.LE =("<=", "le", TComparisonOp.LE)
Definition at line 48 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.evalBinaryPredicate(), and com.cloudera.impala.analysis.BinaryPredicate.negate().
com.cloudera.impala.analysis.BinaryPredicate.Operator.LT =("<", "lt", TComparisonOp.LT)
Definition at line 50 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.evalBinaryPredicate(), and com.cloudera.impala.analysis.BinaryPredicate.negate().
final String com.cloudera.impala.analysis.BinaryPredicate.Operator.name_ private
Definition at line 58 of file BinaryPredicate.java.
com.cloudera.impala.analysis.BinaryPredicate.Operator.NE =("!=", "ne", TComparisonOp.NE)
Definition at line 47 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.planner.HdfsScanNode.evalBinaryPredicate(), and com.cloudera.impala.analysis.BinaryPredicate.negate().
com.cloudera.impala.analysis.BinaryPredicate.Operator.NULL_MATCHING_EQ =("=", "null_matching_eq", TComparisonOp.EQ)
Definition at line 55 of file BinaryPredicate.java.
Referenced by com.cloudera.impala.analysis.BinaryPredicate.isNullMatchingEq().
final TComparisonOp com.cloudera.impala.analysis.BinaryPredicate.Operator.thriftOp_ private
Definition at line 59 of file BinaryPredicate.java.
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/BinaryPredicate.java