Impala: com.cloudera.impala.analysis.AnalyticWindow.Type Enum Reference
com.cloudera.impala.analysis.AnalyticWindow.Type Enum Reference
Public Member Functions
String toString ()
TAnalyticWindowType toThrift ()
Public Attributes
ROWS =("ROWS")
RANGE =("RANGE")
Private Member Functions
Type (String d)
Private Attributes
final String description_
Detailed Description
Definition at line 41 of file AnalyticWindow.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AnalyticWindow.Type.Type (String d) inline private
Definition at line 47 of file AnalyticWindow.java.
Member Function Documentation
String com.cloudera.impala.analysis.AnalyticWindow.Type.toString () inline
Definition at line 52 of file AnalyticWindow.java.
TAnalyticWindowType com.cloudera.impala.analysis.AnalyticWindow.Type.toThrift () inline
Definition at line 53 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.toThrift().
Member Data Documentation
final String com.cloudera.impala.analysis.AnalyticWindow.Type.description_ private
Definition at line 45 of file AnalyticWindow.java.
com.cloudera.impala.analysis.AnalyticWindow.Type.RANGE =("RANGE")
Definition at line 43 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze().
com.cloudera.impala.analysis.AnalyticWindow.Type.ROWS =("ROWS")
Definition at line 42 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.checkOffsetExpr(), and com.cloudera.impala.analysis.AnalyticWindow.Boundary.toThrift().
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AnalyticWindow.java