Impala: com.cloudera.impala.planner.HashJoinNode.DistributionMode Enum Reference
com.cloudera.impala.planner.HashJoinNode.DistributionMode Enum Reference
Public Member Functions
String toString ()
Public Attributes
NONE =("NONE")
BROADCAST =("BROADCAST")
PARTITIONED =("PARTITIONED")
Private Member Functions
DistributionMode (String descr)
Private Attributes
final String description
Detailed Description
Definition at line 62 of file HashJoinNode.java.
Constructor & Destructor Documentation
com.cloudera.impala.planner.HashJoinNode.DistributionMode.DistributionMode (String descr) inline private
Definition at line 69 of file HashJoinNode.java.
Member Function Documentation
String com.cloudera.impala.planner.HashJoinNode.DistributionMode.toString () inline
Definition at line 74 of file HashJoinNode.java.
Member Data Documentation
com.cloudera.impala.planner.HashJoinNode.DistributionMode.BROADCAST =("BROADCAST")
Definition at line 64 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.CrossJoinNode.getNodeExplainString().
final String com.cloudera.impala.planner.HashJoinNode.DistributionMode.description private
Definition at line 67 of file HashJoinNode.java.
com.cloudera.impala.planner.HashJoinNode.DistributionMode.NONE =("NONE")
Definition at line 63 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.HashJoinNode.getDisplayLabelDetail(), and com.cloudera.impala.planner.HashJoinNode.HashJoinNode().
com.cloudera.impala.planner.HashJoinNode.DistributionMode.PARTITIONED =("PARTITIONED")
Definition at line 65 of file HashJoinNode.java.
Referenced by com.cloudera.impala.planner.PlanFragment.computeCanAddSlotFilters(), and com.cloudera.impala.planner.HashJoinNode.computeCosts().
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/planner/HashJoinNode.java