Impala: com.cloudera.impala.analysis.AnalyticWindow.BoundaryType Enum Reference
com.cloudera.impala.analysis.AnalyticWindow.BoundaryType Enum Reference
Public Member Functions
String toString ()
TAnalyticWindowBoundaryType toThrift ()
boolean isAbsolutePos ()
boolean isOffset ()
boolean isPreceding ()
boolean isFollowing ()
BoundaryType converse ()
Public Attributes
UNBOUNDED_PRECEDING =("UNBOUNDED PRECEDING")
UNBOUNDED_FOLLOWING =("UNBOUNDED FOLLOWING")
CURRENT_ROW =("CURRENT ROW")
PRECEDING =("PRECEDING")
FOLLOWING =("FOLLOWING")
Private Member Functions
BoundaryType (String d)
Private Attributes
final String description_
Detailed Description
Definition at line 58 of file AnalyticWindow.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.BoundaryType (String d) inline private
Definition at line 67 of file AnalyticWindow.java.
Member Function Documentation
BoundaryType com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.converse () inline
Definition at line 101 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.Boundary.converse().
boolean com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.isAbsolutePos () inline
Definition at line 85 of file AnalyticWindow.java.
boolean com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.isFollowing () inline
Definition at line 97 of file AnalyticWindow.java.
boolean com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.isOffset () inline
Definition at line 89 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), and com.cloudera.impala.analysis.AnalyticWindow.Boundary.toThrift().
boolean com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.isPreceding () inline
Definition at line 93 of file AnalyticWindow.java.
String com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.toString () inline
Definition at line 72 of file AnalyticWindow.java.
TAnalyticWindowBoundaryType com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.toThrift () inline
Definition at line 73 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.Boundary.toThrift().
Member Data Documentation
com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.CURRENT_ROW =("CURRENT ROW")
Definition at line 61 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
final String com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.description_ private
Definition at line 65 of file AnalyticWindow.java.
com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.FOLLOWING =("FOLLOWING")
Definition at line 63 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.PRECEDING =("PRECEDING")
Definition at line 62 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), and com.cloudera.impala.analysis.AnalyticExpr.standardize().
com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_FOLLOWING =("UNBOUNDED FOLLOWING")
Definition at line 60 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticWindow.analyze(), com.cloudera.impala.analysis.AnalyticExpr.standardize(), and com.cloudera.impala.analysis.AnalyticWindow.toThrift().
com.cloudera.impala.analysis.AnalyticWindow.BoundaryType.UNBOUNDED_PRECEDING =("UNBOUNDED PRECEDING")
Definition at line 59 of file AnalyticWindow.java.
Referenced by com.cloudera.impala.analysis.AnalyticExpr.analyze(), com.cloudera.impala.analysis.AnalyticWindow.analyze(), com.cloudera.impala.analysis.AnalyticExpr.standardize(), and com.cloudera.impala.analysis.AnalyticWindow.toThrift().
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/AnalyticWindow.java