Impala: com.cloudera.impala.analysis.LikePredicate.Operator Enum Reference
com.cloudera.impala.analysis.LikePredicate.Operator Enum Reference
Public Member Functions
String toString ()
Public Attributes
LIKE =("LIKE")
RLIKE =("RLIKE")
REGEXP =("REGEXP")
Private Member Functions
Operator (String description)
Private Attributes
final String description_
Detailed Description
Definition at line 31 of file LikePredicate.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.LikePredicate.Operator.Operator (String description) inline private
Definition at line 38 of file LikePredicate.java.
Member Function Documentation
String com.cloudera.impala.analysis.LikePredicate.Operator.toString () inline
Definition at line 43 of file LikePredicate.java.
Referenced by com.cloudera.impala.analysis.LikePredicate.analyze(), and com.cloudera.impala.analysis.LikePredicate.toSqlImpl().
Member Data Documentation
final String com.cloudera.impala.analysis.LikePredicate.Operator.description_ private
Definition at line 36 of file LikePredicate.java.
com.cloudera.impala.analysis.LikePredicate.Operator.LIKE =("LIKE")
Definition at line 32 of file LikePredicate.java.
com.cloudera.impala.analysis.LikePredicate.Operator.REGEXP =("REGEXP")
Definition at line 34 of file LikePredicate.java.
Referenced by com.cloudera.impala.analysis.LikePredicate.analyze().
com.cloudera.impala.analysis.LikePredicate.Operator.RLIKE =("RLIKE")
Definition at line 33 of file LikePredicate.java.
Referenced by com.cloudera.impala.analysis.LikePredicate.analyze().
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/LikePredicate.java