Impala: com.cloudera.impala.catalog.PrimitiveType Enum Reference
com.cloudera.impala.catalog.PrimitiveType Enum Reference
Public Member Functions
String toString ()
TPrimitiveType toThrift ()
int getSlotSize ()
Static Public Member Functions
static PrimitiveType fromThrift (TPrimitiveType t)
static List< TPrimitiveType > toThrift (PrimitiveType[] types)
static int getMaxSlotSize ()
Public Attributes
INVALID_TYPE =("INVALID_TYPE", -1, TPrimitiveType.INVALID_TYPE)
NULL_TYPE =("NULL_TYPE", 1, TPrimitiveType.NULL_TYPE)
BOOLEAN =("BOOLEAN", 1, TPrimitiveType.BOOLEAN)
TINYINT =("TINYINT", 1, TPrimitiveType.TINYINT)
SMALLINT =("SMALLINT", 2, TPrimitiveType.SMALLINT)
INT =("INT", 4, TPrimitiveType.INT)
BIGINT =("BIGINT", 8, TPrimitiveType.BIGINT)
FLOAT =("FLOAT", 4, TPrimitiveType.FLOAT)
DOUBLE =("DOUBLE", 8, TPrimitiveType.DOUBLE)
DATE =("DATE", 4, TPrimitiveType.DATE)
DATETIME =("DATETIME", 8, TPrimitiveType.DATETIME)
TIMESTAMP =("TIMESTAMP", 16, TPrimitiveType.TIMESTAMP)
STRING =("STRING", 16, TPrimitiveType.STRING)
VARCHAR =("VARCHAR", 16, TPrimitiveType.VARCHAR)
BINARY =("BINARY", -1, TPrimitiveType.BINARY)
DECIMAL =("DECIMAL", 16, TPrimitiveType.DECIMAL)
CHAR =("CHAR", -1, TPrimitiveType.CHAR)
Private Member Functions
PrimitiveType (String description, int slotSize, TPrimitiveType thriftType)
Private Attributes
final String description_
final int slotSize_
final TPrimitiveType thriftType_
Detailed Description
Definition at line 22 of file PrimitiveType.java.
Constructor & Destructor Documentation
com.cloudera.impala.catalog.PrimitiveType.PrimitiveType (String description, int slotSize, TPrimitiveType thriftType) inline private
Definition at line 56 of file PrimitiveType.java.
Member Function Documentation
static PrimitiveType com.cloudera.impala.catalog.PrimitiveType.fromThrift (TPrimitiveType t) inline static
Definition at line 67 of file PrimitiveType.java.
References impala.INVALID_TYPE.
static int com.cloudera.impala.catalog.PrimitiveType.getMaxSlotSize () inline static
Definition at line 99 of file PrimitiveType.java.
int com.cloudera.impala.catalog.PrimitiveType.getSlotSize () inline
Definition at line 98 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createObject().
String com.cloudera.impala.catalog.PrimitiveType.toString () inline
Definition at line 63 of file PrimitiveType.java.
TPrimitiveType com.cloudera.impala.catalog.PrimitiveType.toThrift () inline
Definition at line 88 of file PrimitiveType.java.
static List<TPrimitiveType> com.cloudera.impala.catalog.PrimitiveType.toThrift (PrimitiveType[] types) inline static
Definition at line 90 of file PrimitiveType.java.
Member Data Documentation
com.cloudera.impala.catalog.PrimitiveType.BIGINT =("BIGINT", 8, TPrimitiveType.BIGINT)
Definition at line 31 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createBigInt(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isFixedPointType(), com.cloudera.impala.catalog.Type.isIntegerType(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.BINARY =("BINARY", -1, TPrimitiveType.BINARY)
Definition at line 44 of file PrimitiveType.java.
Referenced by com.cloudera.impala.catalog.ColumnStats.update().
com.cloudera.impala.catalog.PrimitiveType.BOOLEAN =("BOOLEAN", 1, TPrimitiveType.BOOLEAN)
Definition at line 27 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createBoolean(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isBoolean(), com.cloudera.impala.analysis.Expr.negate(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.CHAR =("CHAR", -1, TPrimitiveType.CHAR)
Definition at line 50 of file PrimitiveType.java.
Referenced by com.cloudera.impala.analysis.CreateUdfStmt.analyze(), com.cloudera.impala.analysis.CreateUdaStmt.analyze(), com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.analysis.TypeDef.analyzeScalarType(), com.cloudera.impala.analysis.Expr.castChildCharsToStrings(), com.cloudera.impala.catalog.ScalarType.createCharType(), com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.InPredicate.initBuiltins(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.analysis.CaseExpr.initBuiltins(), com.cloudera.impala.catalog.Type.isStringType(), com.cloudera.impala.catalog.ScalarType.matchesType(), com.cloudera.impala.catalog.Function.promoteCharsToStrings(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestDecimalCasts(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts(), and com.cloudera.impala.catalog.ScalarType.toString().
com.cloudera.impala.catalog.PrimitiveType.DATE =("DATE", 4, TPrimitiveType.DATE)
Definition at line 34 of file PrimitiveType.java.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), and com.cloudera.impala.catalog.Type.isDateType().
com.cloudera.impala.catalog.PrimitiveType.DATETIME =("DATETIME", 8, TPrimitiveType.DATETIME)
Definition at line 35 of file PrimitiveType.java.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), and com.cloudera.impala.catalog.Type.isDateType().
com.cloudera.impala.catalog.PrimitiveType.DECIMAL =("DECIMAL", 16, TPrimitiveType.DECIMAL)
Definition at line 47 of file PrimitiveType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.createDecimalType(), com.cloudera.impala.catalog.ScalarType.createDecimalTypeInternal(), com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.catalog.ScalarType.decimalPrecision(), com.cloudera.impala.catalog.ScalarType.decimalScale(), com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.catalog.Type.isDecimal(), com.cloudera.impala.catalog.ScalarType.isFixedLengthType(), com.cloudera.impala.catalog.Type.isFixedPointType(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable(), com.cloudera.impala.catalog.ScalarType.toString(), and com.cloudera.impala.analysis.TypesUtilTest.verifyDecimalType().
final String com.cloudera.impala.catalog.PrimitiveType.description_ private
Definition at line 52 of file PrimitiveType.java.
com.cloudera.impala.catalog.PrimitiveType.DOUBLE =("DOUBLE", 8, TPrimitiveType.DOUBLE)
Definition at line 33 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createDouble(), com.cloudera.impala.catalog.ScalarType.getNextResolutionType(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isFloatingPointType(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.FLOAT =("FLOAT", 4, TPrimitiveType.FLOAT)
Definition at line 32 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createFloat(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isFloatingPointType(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.INT =("INT", 4, TPrimitiveType.INT)
Definition at line 30 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createInt(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isFixedPointType(), com.cloudera.impala.catalog.Type.isIntegerType(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.INVALID_TYPE =("INVALID_TYPE", -1, TPrimitiveType.INVALID_TYPE)
Definition at line 23 of file PrimitiveType.java.
Referenced by com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.catalog.Type.getPrimitiveType(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), and com.cloudera.impala.catalog.Type.isInvalid().
com.cloudera.impala.catalog.PrimitiveType.NULL_TYPE =("NULL_TYPE", 1, TPrimitiveType.NULL_TYPE)
Definition at line 26 of file PrimitiveType.java.
Referenced by com.cloudera.impala.catalog.Type.isNull().
final int com.cloudera.impala.catalog.PrimitiveType.slotSize_ private
Definition at line 53 of file PrimitiveType.java.
com.cloudera.impala.catalog.PrimitiveType.SMALLINT =("SMALLINT", 2, TPrimitiveType.SMALLINT)
Definition at line 29 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createSmallInt(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isFixedPointType(), com.cloudera.impala.catalog.Type.isIntegerType(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.STRING =("STRING", 16, TPrimitiveType.STRING)
Definition at line 40 of file PrimitiveType.java.
Referenced by com.cloudera.impala.analysis.CastExpr.analyze(), com.cloudera.impala.planner.HBaseScanNode.createHBaseFilters(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isStringType(), and com.cloudera.impala.catalog.CatalogTest.testStats().
final TPrimitiveType com.cloudera.impala.catalog.PrimitiveType.thriftType_ private
Definition at line 54 of file PrimitiveType.java.
com.cloudera.impala.catalog.PrimitiveType.TIMESTAMP =("TIMESTAMP", 16, TPrimitiveType.TIMESTAMP)
Definition at line 37 of file PrimitiveType.java.
Referenced by com.cloudera.impala.catalog.ScalarType.getMaxResolutionType(), com.cloudera.impala.catalog.Type.isDateType(), com.cloudera.impala.catalog.Type.isTimestamp(), com.cloudera.impala.catalog.ScalarType.supportsTablePartitioning(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.TINYINT =("TINYINT", 1, TPrimitiveType.TINYINT)
Definition at line 28 of file PrimitiveType.java.
Referenced by com.cloudera.impala.hive.executor.UdfExecutorTest.createTinyInt(), com.cloudera.impala.hive.executor.UdfExecutor.getPrimitiveType(), com.cloudera.impala.catalog.Type.isFixedPointType(), com.cloudera.impala.catalog.Type.isIntegerType(), and com.cloudera.impala.catalog.CatalogTest.testStats().
com.cloudera.impala.catalog.PrimitiveType.VARCHAR =("VARCHAR", 16, TPrimitiveType.VARCHAR)
Definition at line 41 of file PrimitiveType.java.
Referenced by com.cloudera.impala.analysis.CreateUdfStmt.analyze(), com.cloudera.impala.analysis.CreateUdaStmt.analyze(), com.cloudera.impala.analysis.TypeDef.analyzeScalarType(), com.cloudera.impala.service.MetadataOp.createGetTypeInfoResults(), com.cloudera.impala.catalog.ScalarType.createVarcharType(), com.cloudera.impala.catalog.ScalarType.equals(), com.cloudera.impala.catalog.ScalarType.getAssignmentCompatibleType(), com.cloudera.impala.catalog.BuiltinsDb.initAggregateBuiltins(), com.cloudera.impala.analysis.InPredicate.initBuiltins(), com.cloudera.impala.analysis.CastExpr.initBuiltins(), com.cloudera.impala.catalog.Type.isStringType(), com.cloudera.impala.catalog.ScalarType.matchesType(), com.cloudera.impala.analysis.AnalyzeDDLTest.TestCreateTable(), com.cloudera.impala.analysis.AnalyzeExprsTest.TestNullCasts(), and com.cloudera.impala.catalog.ScalarType.toString().
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/PrimitiveType.java