Impala: com.cloudera.impala.analysis.JoinOperator Enum Reference
com.cloudera.impala.analysis.JoinOperator Enum Reference
Public Member Functions
String toString ()
TJoinOp toThrift ()
boolean isInnerJoin ()
boolean isOuterJoin ()
boolean isSemiJoin ()
boolean isLeftSemiJoin ()
boolean isRightSemiJoin ()
boolean isCrossJoin ()
boolean isFullOuterJoin ()
boolean isNullAwareLeftAntiJoin ()
boolean isAntiJoin ()
JoinOperator invert ()
Public Attributes
INNER_JOIN =("INNER JOIN", TJoinOp.INNER_JOIN)
LEFT_OUTER_JOIN =("LEFT OUTER JOIN", TJoinOp.LEFT_OUTER_JOIN)
LEFT_SEMI_JOIN =("LEFT SEMI JOIN", TJoinOp.LEFT_SEMI_JOIN)
LEFT_ANTI_JOIN =("LEFT ANTI JOIN", TJoinOp.LEFT_ANTI_JOIN)
RIGHT_OUTER_JOIN =("RIGHT OUTER JOIN", TJoinOp.RIGHT_OUTER_JOIN)
RIGHT_SEMI_JOIN =("RIGHT SEMI JOIN", TJoinOp.RIGHT_SEMI_JOIN)
RIGHT_ANTI_JOIN =("RIGHT ANTI JOIN", TJoinOp.RIGHT_ANTI_JOIN)
FULL_OUTER_JOIN =("FULL OUTER JOIN", TJoinOp.FULL_OUTER_JOIN)
CROSS_JOIN =("CROSS JOIN", TJoinOp.CROSS_JOIN)
NULL_AWARE_LEFT_ANTI_JOIN
Private Member Functions
JoinOperator (String description, TJoinOp thriftJoinOp)
Private Attributes
final String description_
final TJoinOp thriftJoinOp_
Detailed Description
Definition at line 19 of file JoinOperator.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.JoinOperator.JoinOperator (String description, TJoinOp thriftJoinOp) inline private
Definition at line 38 of file JoinOperator.java.
Member Function Documentation
JoinOperator com.cloudera.impala.analysis.JoinOperator.invert () inline
Definition at line 94 of file JoinOperator.java.
boolean com.cloudera.impala.analysis.JoinOperator.isAntiJoin () inline
Definition at line 89 of file JoinOperator.java.
References com.cloudera.impala.analysis.JoinOperator.NULL_AWARE_LEFT_ANTI_JOIN.
boolean com.cloudera.impala.analysis.JoinOperator.isCrossJoin () inline
Definition at line 77 of file JoinOperator.java.
References com.cloudera.impala.analysis.JoinOperator.CROSS_JOIN.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan().
boolean com.cloudera.impala.analysis.JoinOperator.isFullOuterJoin () inline
Definition at line 81 of file JoinOperator.java.
References com.cloudera.impala.analysis.JoinOperator.FULL_OUTER_JOIN.
boolean com.cloudera.impala.analysis.JoinOperator.isInnerJoin () inline
Definition at line 52 of file JoinOperator.java.
boolean com.cloudera.impala.analysis.JoinOperator.isLeftSemiJoin () inline
Definition at line 68 of file JoinOperator.java.
References com.cloudera.impala.analysis.JoinOperator.NULL_AWARE_LEFT_ANTI_JOIN.
boolean com.cloudera.impala.analysis.JoinOperator.isNullAwareLeftAntiJoin () inline
Definition at line 85 of file JoinOperator.java.
References com.cloudera.impala.analysis.JoinOperator.NULL_AWARE_LEFT_ANTI_JOIN.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan().
boolean com.cloudera.impala.analysis.JoinOperator.isOuterJoin () inline
Definition at line 56 of file JoinOperator.java.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.createCheapestJoinPlan(), and com.cloudera.impala.analysis.TableRef.invertJoin().
boolean com.cloudera.impala.analysis.JoinOperator.isRightSemiJoin () inline
Definition at line 73 of file JoinOperator.java.
References com.cloudera.impala.analysis.JoinOperator.RIGHT_ANTI_JOIN.
boolean com.cloudera.impala.analysis.JoinOperator.isSemiJoin () inline
Definition at line 62 of file JoinOperator.java.
References com.cloudera.impala.analysis.JoinOperator.NULL_AWARE_LEFT_ANTI_JOIN.
Referenced by com.cloudera.impala.planner.HashJoinNode.computeStats().
String com.cloudera.impala.analysis.JoinOperator.toString () inline
Definition at line 44 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), com.cloudera.impala.planner.HashJoinNode.getDisplayLabelDetail(), and com.cloudera.impala.analysis.TableRef.toSql().
TJoinOp com.cloudera.impala.analysis.JoinOperator.toThrift () inline
Definition at line 48 of file JoinOperator.java.
Member Data Documentation
com.cloudera.impala.analysis.JoinOperator.CROSS_JOIN =("CROSS JOIN", TJoinOp.CROSS_JOIN)
Definition at line 28 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), com.cloudera.impala.planner.SingleNodePlanner.createJoinNode(), com.cloudera.impala.analysis.StmtRewriter.extractCorrelatedPredicates(), com.cloudera.impala.analysis.JoinOperator.isCrossJoin(), and com.cloudera.impala.analysis.StmtRewriter.mergeExpr().
final String com.cloudera.impala.analysis.JoinOperator.description_ private
Definition at line 35 of file JoinOperator.java.
com.cloudera.impala.analysis.JoinOperator.FULL_OUTER_JOIN =("FULL OUTER JOIN", TJoinOp.FULL_OUTER_JOIN)
Definition at line 27 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), com.cloudera.impala.planner.PlanFragment.computeCanAddSlotFilters(), com.cloudera.impala.planner.DistributedPlanner.createHashJoinFragment(), com.cloudera.impala.planner.HashJoinNode.HashJoinNode(), com.cloudera.impala.analysis.JoinOperator.isFullOuterJoin(), and com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.partitionValueTransfers().
com.cloudera.impala.analysis.JoinOperator.INNER_JOIN =("INNER JOIN", TJoinOp.INNER_JOIN)
Definition at line 20 of file JoinOperator.java.
Referenced by com.cloudera.impala.planner.SingleNodePlanner.createJoinNode(), and com.cloudera.impala.analysis.TableRef.getJoinOp().
com.cloudera.impala.analysis.JoinOperator.LEFT_ANTI_JOIN =("LEFT ANTI JOIN", TJoinOp.LEFT_ANTI_JOIN)
Definition at line 23 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.planner.PlanFragment.computeCanAddSlotFilters(), com.cloudera.impala.analysis.StmtRewriter.mergeExpr(), com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.partitionValueTransfers(), and com.cloudera.impala.analysis.StmtRewriter.replaceUnqualifiedStarItems().
com.cloudera.impala.analysis.JoinOperator.LEFT_OUTER_JOIN =("LEFT OUTER JOIN", TJoinOp.LEFT_OUTER_JOIN)
Definition at line 21 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.planner.PlanFragment.computeCanAddSlotFilters(), com.cloudera.impala.planner.HashJoinNode.HashJoinNode(), and com.cloudera.impala.analysis.StmtRewriter.mergeExpr().
com.cloudera.impala.analysis.JoinOperator.LEFT_SEMI_JOIN =("LEFT SEMI JOIN", TJoinOp.LEFT_SEMI_JOIN)
Definition at line 22 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), and com.cloudera.impala.analysis.StmtRewriter.mergeExpr().
com.cloudera.impala.analysis.JoinOperator.NULL_AWARE_LEFT_ANTI_JOIN
Initial value:
=("NULL AWARE LEFT ANTI JOIN",
      TJoinOp.NULL_AWARE_LEFT_ANTI_JOIN)
Definition at line 32 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.planner.PlanFragment.computeCanAddSlotFilters(), com.cloudera.impala.analysis.JoinOperator.isAntiJoin(), com.cloudera.impala.analysis.JoinOperator.isLeftSemiJoin(), com.cloudera.impala.analysis.JoinOperator.isNullAwareLeftAntiJoin(), com.cloudera.impala.analysis.JoinOperator.isSemiJoin(), com.cloudera.impala.analysis.StmtRewriter.mergeExpr(), and com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.partitionValueTransfers().
com.cloudera.impala.analysis.JoinOperator.RIGHT_ANTI_JOIN =("RIGHT ANTI JOIN", TJoinOp.RIGHT_ANTI_JOIN)
Definition at line 26 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), com.cloudera.impala.planner.DistributedPlanner.createHashJoinFragment(), com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality(), com.cloudera.impala.analysis.JoinOperator.isRightSemiJoin(), and com.cloudera.impala.analysis.Analyzer.ValueTransferGraph.partitionValueTransfers().
com.cloudera.impala.analysis.JoinOperator.RIGHT_OUTER_JOIN =("RIGHT OUTER JOIN", TJoinOp.RIGHT_OUTER_JOIN)
Definition at line 24 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), and com.cloudera.impala.planner.HashJoinNode.HashJoinNode().
com.cloudera.impala.analysis.JoinOperator.RIGHT_SEMI_JOIN =("RIGHT SEMI JOIN", TJoinOp.RIGHT_SEMI_JOIN)
Definition at line 25 of file JoinOperator.java.
Referenced by com.cloudera.impala.analysis.TableRef.analyzeJoin(), com.cloudera.impala.analysis.TableRef.analyzeJoinHints(), and com.cloudera.impala.planner.HashJoinNode.getSemiJoinCardinality().
final TJoinOp com.cloudera.impala.analysis.JoinOperator.thriftJoinOp_ private
Definition at line 36 of file JoinOperator.java.
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/JoinOperator.java