Impala: com.cloudera.impala.analysis.ArithmeticExpr.Operator Enum Reference
com.cloudera.impala.analysis.ArithmeticExpr.Operator Enum Reference
Public Member Functions
String toString ()
String getName ()
Public Attributes
MULTIPLY =("*", "multiply")
DIVIDE =("/", "divide")
MOD =("%", "mod")
INT_DIVIDE =("DIV", "int_divide")
ADD =("+", "add")
SUBTRACT =("-", "subtract")
BITAND =("&", "bitand")
BITOR =("|", "bitor")
BITXOR =("^", "bitxor")
BITNOT =("~", "bitnot")
Private Member Functions
Operator (String description, String name)
Private Attributes
final String description_
final String name_
Detailed Description
Definition at line 30 of file ArithmeticExpr.java.
Constructor & Destructor Documentation
com.cloudera.impala.analysis.ArithmeticExpr.Operator.Operator (String description, String name) inline private
Definition at line 45 of file ArithmeticExpr.java.
References impala.name.
Member Function Documentation
String com.cloudera.impala.analysis.ArithmeticExpr.Operator.getName () inline
Definition at line 52 of file ArithmeticExpr.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze().
String com.cloudera.impala.analysis.ArithmeticExpr.Operator.toString () inline
Definition at line 51 of file ArithmeticExpr.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze(), and com.cloudera.impala.analysis.ArithmeticExpr.toSqlImpl().
Member Data Documentation
com.cloudera.impala.analysis.ArithmeticExpr.Operator.ADD =("+", "add")
Definition at line 35 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.BITAND =("&", "bitand")
Definition at line 37 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.BITNOT =("~", "bitnot")
Definition at line 40 of file ArithmeticExpr.java.
Referenced by com.cloudera.impala.analysis.ArithmeticExpr.analyze().
com.cloudera.impala.analysis.ArithmeticExpr.Operator.BITOR =("|", "bitor")
Definition at line 38 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.BITXOR =("^", "bitxor")
Definition at line 39 of file ArithmeticExpr.java.
final String com.cloudera.impala.analysis.ArithmeticExpr.Operator.description_ private
Definition at line 42 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.DIVIDE =("/", "divide")
Definition at line 32 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.INT_DIVIDE =("DIV", "int_divide")
Definition at line 34 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.MOD =("%", "mod")
Definition at line 33 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.MULTIPLY =("*", "multiply")
Definition at line 31 of file ArithmeticExpr.java.
final String com.cloudera.impala.analysis.ArithmeticExpr.Operator.name_ private
Definition at line 43 of file ArithmeticExpr.java.
com.cloudera.impala.analysis.ArithmeticExpr.Operator.SUBTRACT =("-", "subtract")
Definition at line 36 of file ArithmeticExpr.java.
Referenced by com.cloudera.impala.analysis.TimestampArithmeticExpr.TimestampArithmeticExpr().
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/analysis/ArithmeticExpr.java