Impala: com.cloudera.impala.catalog.HdfsFileFormat Enum Reference
com.cloudera.impala.catalog.HdfsFileFormat Enum Reference
Public Member Functions
String toJavaClassName ()
THdfsFileFormat toThrift ()
String toSql (HdfsCompression compressionType)
boolean isFileCompressionTypeSupported (String fileName, StringBuilder errorMsg)
boolean isSplittable (HdfsCompression compression)
Static Public Member Functions
static boolean isHdfsFormatClass (String formatClass)
static HdfsFileFormat fromHdfsInputFormatClass (String inputFormatClass)
static HdfsFileFormat fromJavaClassName (String className)
static HdfsFileFormat fromThrift (THdfsFileFormat thriftFormat)
Public Attributes
RC_FILE
TEXT
SEQUENCE_FILE
AVRO
Static Public Attributes
staticfinal String LZO_TEXT_INPUT_FORMAT
staticfinal String LZO_TEXT_OUTPUT_FORMAT
Static Private Attributes
staticfinal String RCFILE_INPUT_FORMAT
staticfinal String TEXT_INPUT_FORMAT
staticfinal String SEQUENCE_INPUT_FORMAT
staticfinal String[] PARQUET_INPUT_FORMATS
staticfinal String AVRO_INPUT_FORMAT
staticfinal Map< String,
HdfsFileFormat > VALID_FORMATS
Detailed Description
Supported HDFS file formats
Definition at line 26 of file HdfsFileFormat.java.
Member Function Documentation
static HdfsFileFormat com.cloudera.impala.catalog.HdfsFileFormat.fromHdfsInputFormatClass (String inputFormatClass) inline static
Returns the file format associated with the input format class, or null if the input format class is not supported.
Definition at line 91 of file HdfsFileFormat.java.
static HdfsFileFormat com.cloudera.impala.catalog.HdfsFileFormat.fromJavaClassName (String className) inline static
Returns the corresponding enum for a SerDe class name. If classname is not one of our supported formats, throws an IllegalArgumentException like Enum.valueOf
Definition at line 100 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.catalog.HdfsStorageDescriptor.fromStorageDescriptor(), and com.cloudera.impala.catalog.HdfsTable.load().
static HdfsFileFormat com.cloudera.impala.catalog.HdfsFileFormat.fromThrift (THdfsFileFormat thriftFormat) inline static
Definition at line 116 of file HdfsFileFormat.java.
References com.cloudera.impala.catalog.HdfsFileFormat.AVRO, com.cloudera.impala.catalog.HdfsFileFormat.PARQUET, com.cloudera.impala.catalog.HdfsFileFormat.RC_FILE, com.cloudera.impala.catalog.HdfsFileFormat.SEQUENCE_FILE, and com.cloudera.impala.catalog.HdfsFileFormat.TEXT.
Referenced by com.cloudera.impala.analysis.ToSqlUtils.getCreateTableSql().
boolean com.cloudera.impala.catalog.HdfsFileFormat.isFileCompressionTypeSupported (String fileName, StringBuilder errorMsg) inline
Definition at line 175 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyzePaths().
static boolean com.cloudera.impala.catalog.HdfsFileFormat.isHdfsFormatClass (String formatClass) inline static
Returns true if the string describes an input format class that we support.
Definition at line 83 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.catalog.Table.fromMetastoreTable().
boolean com.cloudera.impala.catalog.HdfsFileFormat.isSplittable (HdfsCompression compression) inline
Returns true if this file format with the given compression format is splittable.
Definition at line 207 of file HdfsFileFormat.java.
References com.cloudera.impala.catalog.HdfsCompression.NONE.
Referenced by com.cloudera.impala.catalog.HdfsTable.synthesizeBlockMetadata().
String com.cloudera.impala.catalog.HdfsFileFormat.toJavaClassName () inline
Definition at line 108 of file HdfsFileFormat.java.
String com.cloudera.impala.catalog.HdfsFileFormat.toSql (HdfsCompression compressionType) inline
Definition at line 142 of file HdfsFileFormat.java.
References com.cloudera.impala.catalog.HdfsCompression.LZO, and com.cloudera.impala.catalog.HdfsCompression.LZO_INDEX.
THdfsFileFormat com.cloudera.impala.catalog.HdfsFileFormat.toThrift () inline
Definition at line 129 of file HdfsFileFormat.java.
Member Data Documentation
com.cloudera.impala.catalog.HdfsFileFormat.AVRO
Definition at line 30 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.catalog.HdfsFileFormat.fromThrift(), and com.cloudera.impala.catalog.HdfsTable.load().
static final String com.cloudera.impala.catalog.HdfsFileFormat.AVRO_INPUT_FORMAT static private
Initial value:
=
      "org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat"
Definition at line 65 of file HdfsFileFormat.java.
static final String com.cloudera.impala.catalog.HdfsFileFormat.LZO_TEXT_INPUT_FORMAT static
Initial value:
=
      "com.hadoop.mapred.DeprecatedLzoTextInputFormat"
Definition at line 42 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.catalog.HdfsCompression.fromHdfsInputFormatClass().
static final String com.cloudera.impala.catalog.HdfsFileFormat.LZO_TEXT_OUTPUT_FORMAT static
Initial value:
=
      "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
Definition at line 46 of file HdfsFileFormat.java.
static final String [] com.cloudera.impala.catalog.HdfsFileFormat.PARQUET_INPUT_FORMATS static private
Initial value:
= {
      "com.cloudera.impala.hive.serde.ParquetInputFormat",
      "parquet.hive.DeprecatedParquetInputFormat",
      "parquet.hive.MapredParquetInputFormat",
      "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat",
  }
Definition at line 57 of file HdfsFileFormat.java.
com.cloudera.impala.catalog.HdfsFileFormat.RC_FILE
Definition at line 27 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.catalog.HdfsFileFormat.fromThrift().
static final String com.cloudera.impala.catalog.HdfsFileFormat.RCFILE_INPUT_FORMAT static private
Initial value:
=
      "org.apache.hadoop.hive.ql.io.RCFileInputFormat"
Definition at line 34 of file HdfsFileFormat.java.
com.cloudera.impala.catalog.HdfsFileFormat.SEQUENCE_FILE
Definition at line 29 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.catalog.HdfsFileFormat.fromThrift().
static final String com.cloudera.impala.catalog.HdfsFileFormat.SEQUENCE_INPUT_FORMAT static private
Initial value:
=
      "org.apache.hadoop.mapred.SequenceFileInputFormat"
Definition at line 50 of file HdfsFileFormat.java.
com.cloudera.impala.catalog.HdfsFileFormat.TEXT
Definition at line 28 of file HdfsFileFormat.java.
Referenced by com.cloudera.impala.catalog.HdfsFileFormat.fromThrift().
static final String com.cloudera.impala.catalog.HdfsFileFormat.TEXT_INPUT_FORMAT static private
Initial value:
=
      "org.apache.hadoop.mapred.TextInputFormat"
Definition at line 38 of file HdfsFileFormat.java.
static final Map<String, HdfsFileFormat> com.cloudera.impala.catalog.HdfsFileFormat.VALID_FORMATS static private
Initial value:
=
      ImmutableMap.<String, HdfsFileFormat>builder()
          .put(RCFILE_INPUT_FORMAT, RC_FILE)
          .put(TEXT_INPUT_FORMAT, TEXT)
          .put(LZO_TEXT_INPUT_FORMAT, TEXT)
          .put(SEQUENCE_INPUT_FORMAT, SEQUENCE_FILE)
          .put(AVRO_INPUT_FORMAT, AVRO)
          .put(PARQUET_INPUT_FORMATS[0], PARQUET)
          .put(PARQUET_INPUT_FORMATS[1], PARQUET)
          .put(PARQUET_INPUT_FORMATS[2], PARQUET)
          .put(PARQUET_INPUT_FORMATS[3], PARQUET)
          .build()
Definition at line 68 of file HdfsFileFormat.java.
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/catalog/HdfsFileFormat.java