Impala: com.cloudera.impala.authorization.Privilege Enum Reference
com.cloudera.impala.authorization.Privilege Enum Reference
Public Member Functions
EnumSet< DBModelAction > getHiveActions ()
boolean getAnyOf ()
Public Attributes
ALL =(DBModelAction.ALL, false)
ALTER =(DBModelAction.ALL, false)
DROP =(DBModelAction.ALL, false)
CREATE =(DBModelAction.ALL, false)
INSERT =(DBModelAction.INSERT, false)
SELECT =(DBModelAction.SELECT, false)
VIEW_METADATA =(EnumSet.of(DBModelAction.INSERT, DBModelAction.SELECT), true)
ANY =(EnumSet.allOf(DBModelAction.class), true)
Private Member Functions
Privilege (EnumSet< DBModelAction > actions, boolean anyOf)
Privilege (DBModelAction action, boolean anyOf)
Private Attributes
final EnumSet< DBModelAction > actions
final boolean anyOf_
Detailed Description
Definition at line 24 of file Privilege.java.
Constructor & Destructor Documentation
com.cloudera.impala.authorization.Privilege.Privilege (EnumSet< DBModelAction > actions, boolean anyOf) inline private
Definition at line 45 of file Privilege.java.
com.cloudera.impala.authorization.Privilege.Privilege (DBModelAction action, boolean anyOf) inline private
Definition at line 50 of file Privilege.java.
Member Function Documentation
boolean com.cloudera.impala.authorization.Privilege.getAnyOf () inline
Definition at line 66 of file Privilege.java.
EnumSet<DBModelAction> com.cloudera.impala.authorization.Privilege.getHiveActions () inline
Definition at line 57 of file Privilege.java.
Member Data Documentation
final EnumSet<DBModelAction> com.cloudera.impala.authorization.Privilege.actions private
Definition at line 38 of file Privilege.java.
com.cloudera.impala.authorization.Privilege.ALL =(DBModelAction.ALL, false)
Definition at line 25 of file Privilege.java.
Referenced by com.cloudera.impala.authorization.PrivilegeRequestBuilder.all(), com.cloudera.impala.analysis.ResetMetadataStmt.analyze(), com.cloudera.impala.analysis.CreateDataSrcStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetLocationStmt.analyze(), com.cloudera.impala.analysis.CreateTableDataSrcStmt.analyze(), com.cloudera.impala.analysis.DropFunctionStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.analyze(), com.cloudera.impala.analysis.CreateDbStmt.analyze(), com.cloudera.impala.analysis.PrivilegeSpec.analyze(), com.cloudera.impala.analysis.CreateFunctionStmtBase.analyze(), com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), com.cloudera.impala.analysis.CreateTableStmt.analyze(), com.cloudera.impala.analysis.CreateTableLikeFileStmt.analyze(), com.cloudera.impala.analysis.LoadDataStmt.analyzePaths(), and com.cloudera.impala.authorization.AuthorizationChecker.checkAccess().
com.cloudera.impala.authorization.Privilege.ALTER =(DBModelAction.ALL, false)
Definition at line 26 of file Privilege.java.
Referenced by com.cloudera.impala.analysis.AlterViewStmt.analyze(), com.cloudera.impala.analysis.AlterTableSetStmt.analyze(), com.cloudera.impala.analysis.AlterTableDropPartitionStmt.analyze(), com.cloudera.impala.analysis.AlterTableStmt.analyze(), com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze(), com.cloudera.impala.analysis.AlterTableAddPartitionStmt.analyze(), com.cloudera.impala.analysis.DropStatsStmt.analyze(), com.cloudera.impala.analysis.ComputeStatsStmt.analyze(), and com.cloudera.impala.analysis.ComputeStatsStmt.ComputeStatsStmt().
com.cloudera.impala.authorization.Privilege.ANY =(EnumSet.allOf(DBModelAction.class), true)
Definition at line 35 of file Privilege.java.
Referenced by com.cloudera.impala.analysis.UseStmt.analyze(), com.cloudera.impala.analysis.ResetMetadataStmt.analyze(), com.cloudera.impala.analysis.CreateTableAsSelectStmt.analyze(), com.cloudera.impala.analysis.ShowTablesStmt.analyze(), com.cloudera.impala.authorization.PrivilegeRequestBuilder.any(), com.cloudera.impala.authorization.AuthorizationChecker.checkAccess(), com.cloudera.impala.analysis.Analyzer.getDb(), and com.cloudera.impala.service.Frontend.getTableNames().
final boolean com.cloudera.impala.authorization.Privilege.anyOf_ private
Definition at line 43 of file Privilege.java.
com.cloudera.impala.authorization.Privilege.CREATE =(DBModelAction.ALL, false)
Definition at line 28 of file Privilege.java.
Referenced by com.cloudera.impala.analysis.CreateViewStmt.analyze(), com.cloudera.impala.analysis.AlterTableOrViewRenameStmt.analyze(), com.cloudera.impala.analysis.CreateDbStmt.analyze(), com.cloudera.impala.analysis.CreateFunctionStmtBase.analyze(), com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), and com.cloudera.impala.analysis.CreateTableStmt.analyze().
com.cloudera.impala.authorization.Privilege.DROP =(DBModelAction.ALL, false)
Definition at line 27 of file Privilege.java.
Referenced by com.cloudera.impala.analysis.DropDbStmt.analyze(), com.cloudera.impala.analysis.DropFunctionStmt.analyze(), and com.cloudera.impala.analysis.DropTableOrViewStmt.analyze().
com.cloudera.impala.authorization.Privilege.INSERT =(DBModelAction.INSERT, false)
Definition at line 29 of file Privilege.java.
Referenced by com.cloudera.impala.analysis.LoadDataStmt.analyze(), and com.cloudera.impala.analysis.InsertStmt.setTargetTable().
com.cloudera.impala.authorization.Privilege.SELECT =(DBModelAction.SELECT, false)
Definition at line 30 of file Privilege.java.
Referenced by com.cloudera.impala.analysis.TableRef.getPrivilegeRequirement().
com.cloudera.impala.authorization.Privilege.VIEW_METADATA =(EnumSet.of(DBModelAction.INSERT, DBModelAction.SELECT), true)
Definition at line 32 of file Privilege.java.
Referenced by com.cloudera.impala.analysis.ShowCreateTableStmt.analyze(), com.cloudera.impala.analysis.ShowStatsStmt.analyze(), com.cloudera.impala.analysis.DescribeStmt.analyze(), com.cloudera.impala.analysis.ShowFilesStmt.analyze(), com.cloudera.impala.analysis.ShowFunctionsStmt.analyze(), com.cloudera.impala.analysis.CreateTableLikeStmt.analyze(), com.cloudera.impala.analysis.FunctionCallExpr.analyze(), and com.cloudera.impala.authorization.AuthorizationChecker.checkAccess().
The documentation for this enum was generated from the following file:
fe/src/main/java/com/cloudera/impala/authorization/Privilege.java