Impala: be/src/exprs/expr-test.cc File Reference
expr-test.cc File Reference
#include <map>
#include <math.h>
#include <string>
#include <time.h>
#include <boost/assign/list_of.hpp>
#include <boost/date_time/c_local_time_adjustor.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/random/mersenne_twister.hpp>
#include <boost/unordered_map.hpp>
#include <gtest/gtest.h>
#include "codegen/llvm-codegen.h"
#include "common/init.h"
#include "common/object-pool.h"
#include "exprs/expr-context.h"
#include "exprs/is-null-predicate.h"
#include "exprs/like-predicate.h"
#include "exprs/literal.h"
#include "exprs/null-literal.h"
#include "gen-cpp/Exprs_types.h"
#include "gen-cpp/hive_metastore_types.h"
#include "rpc/thrift-client.h"
#include "rpc/thrift-server.h"
#include "runtime/raw-value.h"
#include "runtime/string-value.h"
#include "runtime/timestamp-value.h"
#include "service/fe-support.h"
#include "service/impala-server.h"
#include "testutil/impalad-query-executor.h"
#include "testutil/in-process-servers.h"
#include "util/debug-util.h"
#include "util/string-parser.h"
#include "util/test-info.h"
#include "common/names.h"
Classes
class impala::ScopedTimeZoneOverride
class impala::ScopedLocalUnixTimestampConversionOverride
class impala::ExprTest
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Functions
DECLARE_int32 (be_port)
DECLARE_int32 (beeswax_port)
DECLARE_string (impalad)
DECLARE_bool (abort_on_config_error)
DECLARE_bool (disable_optimization_passes)
DECLARE_bool (use_utc_for_unix_timestamp_conversions)
template<typename ORIGINAL_TYPE , typename VAL_TYPE >
string impala::LiteralToString (VAL_TYPE val)
template<>
string impala::LiteralToString< float, float > (float val)
template<>
string impala::LiteralToString< float, double > (double val)
template<>
string impala::LiteralToString< double, double > (double val)
template<typename T >
void impala::TestSingleLiteralConstruction (const ColumnType &type, const T &value, const string &string_val)
impala::TEST_F (ExprTest, NullLiteral)
impala::TEST_F (ExprTest, LiteralConstruction)
impala::TEST_F (ExprTest, LiteralExprs)
impala::TEST_F (ExprTest, ArithmeticExprs)
impala::TEST_F (ExprTest, DecimalArithmeticExprs)
impala::TEST_F (ExprTest, BinaryPredicates)
impala::TEST_F (ExprTest, CastExprs)
impala::TEST_F (ExprTest, CompoundPredicates)
impala::TEST_F (ExprTest, IsNullPredicate)
impala::TEST_F (ExprTest, LikePredicate)
impala::TEST_F (ExprTest, BetweenPredicate)
impala::TEST_F (ExprTest, InPredicate)
impala::TEST_F (ExprTest, StringFunctions)
impala::TEST_F (ExprTest, StringRegexpFunctions)
impala::TEST_F (ExprTest, StringParseUrlFunction)
impala::TEST_F (ExprTest, UtilityFunctions)
impala::TEST_F (ExprTest, NonFiniteFloats)
impala::TEST_F (ExprTest, MathTrigonometricFunctions)
impala::TEST_F (ExprTest, MathConversionFunctions)
impala::TEST_F (ExprTest, MathFunctions)
impala::TEST_F (ExprTest, MathRoundingFunctions)
impala::TEST_F (ExprTest, UnaryOperators)
impala::TEST_F (ExprTest, TimestampFunctions)
impala::TEST_F (ExprTest, ConditionalFunctions)
impala::TEST_F (ExprTest, ConditionalFunctionIsTrue)
impala::TEST_F (ExprTest, ConditionalFunctionIsFalse)
impala::TEST_F (ExprTest, ConditionalFunctionIsNotTrue)
impala::TEST_F (ExprTest, ConditionalFunctionIsNotFalse)
void impala::ValidateLayout (const vector< Expr * > &exprs, int expected_byte_size, int expected_var_begin, const map< int, set< int > > &expected_offsets)
impala::TEST_F (ExprTest, ResultsLayoutTest)
impala::TEST_F (ExprTest, DecimalFunctions)
impala::TEST_F (ExprTest, DecimalOverflowCasts)
impala::TEST_F (ExprTest, NullValueFunction)
impala::TEST_F (ExprTest, NonNullValueFunction)
impala::TEST_F (ExprTest, UdfInterfaceBuiltins)
impala::TEST_F (ExprTest, MADlib)
int main (int argc, char **argv)
Variables
ImpaladQueryExecutor * impala::executor_
execution state of coordinator fragment
bool impala::disable_codegen_
Function Documentation
DECLARE_bool (abort_on_config_error)
DECLARE_bool (disable_optimization_passes)
DECLARE_bool (use_utc_for_unix_timestamp_conversions)
DECLARE_int32 (be_port)
DECLARE_int32 (beeswax_port)
DECLARE_string (impalad)
int main (int argc, char ** argv)
Definition at line 4834 of file expr-test.cc.
References impala::disable_codegen_, impala::executor_, EXIT_IF_ERROR, impala::InitCommonRuntime(), impala::InitFeSupport(), impala::LlvmCodeGen::InitializeLlvm(), impala::InProcessImpalaServer::SetCatalogInitialized(), impala::ImpaladQueryExecutor::setExecOptions(), impala::ImpaladQueryExecutor::Setup(), impala::InProcessImpalaServer::StartWithClientServers(), and VLOG_CONNECTION.