Impala: be/src/service/fe-support.cc File Reference
fe-support.cc File Reference
#include "service/fe-support.h"
#include <boost/scoped_ptr.hpp>
#include "codegen/llvm-codegen.h"
#include "common/init.h"
#include "common/logging.h"
#include "common/status.h"
#include "exec/catalog-op-executor.h"
#include "exprs/expr.h"
#include "exprs/expr-context.h"
#include "runtime/exec-env.h"
#include "runtime/runtime-state.h"
#include "runtime/hdfs-fs-cache.h"
#include "runtime/lib-cache.h"
#include "runtime/client-cache.h"
#include "service/impala-server.h"
#include "util/cpu-info.h"
#include "util/disk-info.h"
#include "util/dynamic-util.h"
#include "util/jni-util.h"
#include "util/mem-info.h"
#include "util/symbols-util.h"
#include "rpc/jni-thrift-util.h"
#include "rpc/thrift-server.h"
#include "util/debug-util.h"
#include "gen-cpp/Data_types.h"
#include "gen-cpp/Frontend_types.h"
#include "common/names.h"
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Functions
JNIEXPORT void JNICALL Java_com_cloudera_impala_service_FeSupport_NativeFeTestInit (JNIEnv *env, jclass caller_class)
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs (JNIEnv *env, jclass caller_class, jbyteArray thrift_expr_batch, jbyteArray thrift_query_ctx_bytes)
static void ResolveSymbolLookup (const TSymbolLookupParams params, const vector< ColumnType > &arg_types, TSymbolLookupResult *result)
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeCacheJar (JNIEnv *env, jclass caller_class, jbyteArray thrift_struct)
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeLookupSymbol (JNIEnv *env, jclass caller_class, jbyteArray thrift_struct)
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad (JNIEnv *env, jclass caller_class, jbyteArray thrift_struct)
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeGetStartupOptions (JNIEnv *env, jclass caller_class)
void impala::InitFeSupport ()
Variables
static JNINativeMethod impala::native_methods []
Function Documentation
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeCacheJar (JNIEnv * env, jclass caller_class, jbyteArray thrift_struct)
Definition at line 238 of file fe-support.cc.
References impala::DeserializeThriftMsg(), impala::LibCache::GetLocalLibPath(), impala::LibCache::instance(), impala::JniUtil::internal_exc_class(), impala::Status::ok(), impala::SerializeThriftMsg(), THROW_IF_ERROR_RET, impala::Status::ToThrift(), and impala::LibCache::TYPE_JAR.
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs (JNIEnv * env, jclass caller_class, jbyteArray thrift_expr_batch, jbyteArray thrift_query_ctx_bytes)
Definition at line 72 of file fe-support.cc.
References impala::RuntimeState::codegen_created(), impala::Expr::CreateExprTree(), impala::DeserializeThriftMsg(), impala::LlvmCodeGen::EnableOptimizations(), impala::LlvmCodeGen::FinalizeModule(), impala::RuntimeState::GetCodegen(), impala::RuntimeState::InitMemTrackers(), impala::JniUtil::internal_exc_class(), impala::obj_pool(), impala::ExprContext::Prepare(), impala::JniLocalFrame::push(), impala::RuntimeState::query_mem_tracker(), impala::SerializeThriftMsg(), and THROW_IF_ERROR_RET.
JNIEXPORT void JNICALL Java_com_cloudera_impala_service_FeSupport_NativeFeTestInit (JNIEnv * env, jclass caller_class)
Definition at line 56 of file fe-support.cc.
References impala::TestInfo::FE_TEST, impala::ExecEnv::GetInstance(), impala::InitCommonRuntime(), impala::ExecEnv::InitForFeTests(), impala::LlvmCodeGen::InitializeLlvm(), and impala::name.
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeGetStartupOptions (JNIEnv * env, jclass caller_class)
Definition at line 305 of file fe-support.cc.
References impala::ExecEnv::GetInstance(), impala::ExecEnv::impala_server(), impala::JniUtil::internal_exc_class(), impala::ImpalaServer::IsLineageLoggingEnabled(), impala::SerializeThriftMsg(), and THROW_IF_ERROR_RET.
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativeLookupSymbol (JNIEnv * env, jclass caller_class, jbyteArray thrift_struct)
Definition at line 258 of file fe-support.cc.
References impala::DeserializeThriftMsg(), impala::JniUtil::internal_exc_class(), ResolveSymbolLookup(), impala::SerializeThriftMsg(), and THROW_IF_ERROR_RET.
JNIEXPORT jbyteArray JNICALL Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad (JNIEnv * env, jclass caller_class, jbyteArray thrift_struct)
Definition at line 281 of file fe-support.cc.
References impala::DeserializeThriftMsg(), impala::Status::GetDetail(), impala::ExecEnv::GetInstance(), impala::JniUtil::internal_exc_class(), impala::Status::MergeStatus(), impala::Status::ok(), impala::CatalogOpExecutor::PrioritizeLoad(), impala::SerializeThriftMsg(), THROW_IF_ERROR_RET, and impala::Status::ToThrift().
static void ResolveSymbolLookup (const TSymbolLookupParams params, const vector< ColumnType > & arg_types, TSymbolLookupResult * result) static
Definition at line 131 of file fe-support.cc.
References impala::LibCache::CheckSymbolExists(), impala::ColumnType::DebugString(), impala::Status::GetDetail(), impala::LibCache::GetLocalLibPath(), impala::LibCache::instance(), impala::INVALID_TYPE, impala::SymbolsUtil::IsMangled(), impala::SymbolsUtil::ManglePrepareOrCloseFunction(), impala::SymbolsUtil::MangleUserFunction(), impala::Status::ok(), impala::LibCache::SetNeedsRefresh(), impala::LibCache::TYPE_IR, impala::LibCache::TYPE_JAR, and impala::LibCache::TYPE_SO.
Referenced by Java_com_cloudera_impala_service_FeSupport_NativeLookupSymbol().