Impala: be/src/exec/hash-table.cc File Reference
hash-table.cc File Reference
#include "exec/hash-table.inline.h"
#include "codegen/codegen-anyval.h"
#include "codegen/llvm-codegen.h"
#include "exprs/expr.h"
#include "exprs/expr-context.h"
#include "exprs/slot-ref.h"
#include "runtime/buffered-block-mgr.h"
#include "runtime/mem-tracker.h"
#include "runtime/raw-value.h"
#include "runtime/runtime-state.h"
#include "runtime/string-value.inline.h"
#include "util/debug-util.h"
#include "util/impalad-metrics.h"
#include "common/names.h"
Functions
DEFINE_bool (enable_quadratic_probing, false,"Enable quadratic probing hash table")
static void CodegenAssignNullValue (LlvmCodeGen *codegen, LlvmCodeGen::LlvmBuilder *builder, Value *dst, const ColumnType &type)
Variables
static const int64_t TEST_PAGE_SIZE = 8 * 1024 * 1024
static uint32_t SEED_PRIMES []
static int64_t NULL_VALUE []
static const int64_t INITIAL_DATA_PAGE_SIZES [] = { 64 * 1024, 512 * 1024 }
static const int NUM_SMALL_DATA_PAGES = sizeof(INITIAL_DATA_PAGE_SIZES) / sizeof(int64_t)
Function Documentation
static void CodegenAssignNullValue (LlvmCodeGen * codegen, LlvmCodeGen::LlvmBuilder * builder, Value * dst, const ColumnType & type) static
Definition at line 444 of file hash-table.cc.
References impala::LlvmCodeGen::context(), impala::HashUtil::FNV_SEED, impala::LlvmCodeGen::GetIntConstant(), impala::LlvmCodeGen::ptr_type(), impala::ColumnType::type, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::HashTableCtx::CodegenEvalRow().
DEFINE_bool (enable_quadratic_probing , false , "Enable quadratic probing hash table")
Variable Documentation
const int64_t INITIAL_DATA_PAGE_SIZES[] = { 64 * 1024, 512 * 1024 } static
Definition at line 80 of file hash-table.cc.
Referenced by impala::HashTable::GrowNodeArray().
int64_t NULL_VALUE[] static
Initial value:
= { HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED }
Definition at line 68 of file hash-table.cc.
Referenced by impala::Statestore::Topic::DeleteIfVersionsMatch(), impala::HashTableCtx::EvalRow(), and impala::Statestore::TopicEntry::SetValue().
const int NUM_SMALL_DATA_PAGES = sizeof(INITIAL_DATA_PAGE_SIZES) / sizeof(int64_t) static
Definition at line 81 of file hash-table.cc.
Referenced by impala::HashTable::GrowNodeArray().
uint32_t SEED_PRIMES[] static
Initial value:
= {
  1,
  1431655781,
  1183186591,
  622729787,
  472882027,
  338294347,
  275604541,
  41161739,
  29999999,
  27475109,
  611603,
  16313357,
  11380003,
  21261403,
  33393119,
  101,
  71043403
}
Definition at line 43 of file hash-table.cc.
Referenced by impala::HashTableCtx::HashTableCtx().
const int64_t TEST_PAGE_SIZE = 8 * 1024 * 1024 static
Definition at line 40 of file hash-table.cc.
Referenced by impala::HashTable::GrowNodeArray().