Impala: be/src/exec/hdfs-parquet-scanner.cc File Reference
hdfs-parquet-scanner.cc File Reference
#include "exec/hdfs-parquet-scanner.h"
#include <limits>
#include <boost/algorithm/string.hpp>
#include <gflags/gflags.h>
#include <gutil/strings/substitute.h>
#include "common/object-pool.h"
#include "common/logging.h"
#include "exec/hdfs-scan-node.h"
#include "exec/scanner-context.inline.h"
#include "exec/read-write-util.h"
#include "exprs/expr.h"
#include "runtime/descriptors.h"
#include "runtime/runtime-state.h"
#include "runtime/mem-pool.h"
#include "runtime/raw-value.h"
#include "runtime/row-batch.h"
#include "runtime/tuple-row.h"
#include "runtime/tuple.h"
#include "runtime/string-value.h"
#include "util/bitmap.h"
#include "util/bit-util.h"
#include "util/decompress.h"
#include "util/debug-util.h"
#include "util/error-util.h"
#include "util/dict-encoding.h"
#include "util/rle-encoding.h"
#include "util/runtime-profile.h"
#include "rpc/thrift-util.h"
#include "common/names.h"
Classes
class impala::HdfsParquetScanner::BaseColumnReader
class impala::HdfsParquetScanner::ColumnReader< T >
class impala::HdfsParquetScanner::BoolColumnReader
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Macros
#define LOG_OR_ABORT(error_msg, runtime_state)
#define LOG_OR_RETURN_ON_ERROR(error_msg, runtime_state)
Functions
DEFINE_bool (convert_legacy_hive_parquet_utc_timestamps, false,"When true, TIMESTAMPs read from files written by Parquet-MR (used by Hive) will ""be converted from UTC to local time. Writes are unaffected.")
static bool RequiresSkippedDictionaryHeaderCheck (const HdfsParquetScanner::FileVersion &v)
bool IsEncodingSupported (parquet::Encoding::type e)
string PrintRepetitionType (const parquet::FieldRepetitionType::type &t)
string PrintParquetType (const parquet::Type::type &t)
Variables
const int MAX_PAGE_HEADER_SIZE = 8 * 1024 * 1024
const int MAX_DICT_HEADER_SIZE = 100
Macro Definition Documentation
#define LOG_OR_ABORT (error_msg, runtime_state)
Value:
if (runtime_state->abort_on_error()) {                                \
    return Status(error_msg);                                           \
  } else {                                                              \
    runtime_state->LogError(error_msg);                                 \
    return Status::OK;                                                  \
  }
Definition at line 69 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage().
#define LOG_OR_RETURN_ON_ERROR (error_msg, runtime_state)
Value:
if (runtime_state->abort_on_error()) {                                \
    return Status(error_msg.msg());                                     \
  }                                                                     \
  runtime_state->LogError(error_msg);
Definition at line 77 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::AssembleRows(), and impala::HdfsParquetScanner::ValidateColumn().
Function Documentation
DEFINE_bool (convert_legacy_hive_parquet_utc_timestamps , false , "When true, TIMESTAMPs read from files written by Parquet-MR(used by Hive) will""be converted from UTC to local time.Writes are unaffected.")
bool IsEncodingSupported (parquet::Encoding::type e)
Definition at line 1278 of file hdfs-parquet-scanner.cc.
References impala::PLAIN.
Referenced by impala::HdfsParquetScanner::ValidateColumn().
string PrintParquetType (const parquet::Type::type & t)
Definition at line 1429 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::SchemaNode::DebugString().
string PrintRepetitionType (const parquet::FieldRepetitionType::type & t)
Definition at line 1420 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::SchemaNode::DebugString().
static bool RequiresSkippedDictionaryHeaderCheck (const HdfsParquetScanner::FileVersion & v) static
Definition at line 526 of file hdfs-parquet-scanner.cc.
References impala::HdfsParquetScanner::FileVersion::application, impala::HdfsParquetScanner::FileVersion::is_impala_internal, and impala::HdfsParquetScanner::FileVersion::VersionEq().
Referenced by impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage().
Variable Documentation
const int MAX_DICT_HEADER_SIZE = 100
Definition at line 67 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::InitColumns().
const int MAX_PAGE_HEADER_SIZE = 8 * 1024 * 1024
Definition at line 63 of file hdfs-parquet-scanner.cc.
Referenced by impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage().