Impala: be/src/service/hs2-util-test.cc File Reference
hs2-util-test.cc File Reference
#include "common/init.h"
#include <string>
#include <gtest/gtest.h>
#include "service/hs2-util.h"
#include "common/names.h"
Functions
TEST (StitchNullsTest, OneByteStitch)
TEST (StitchNullsTest, MultiByteStitch)
TEST (StitchNullsTest, StitchOverlapping)
TEST (StitchNullsTest, StitchWithOffset)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 109 of file hs2-util-test.cc.
TEST (StitchNullsTest , OneByteStitch)
Definition at line 27 of file hs2-util-test.cc.
References impala::StitchNulls().
TEST (StitchNullsTest , MultiByteStitch)
Definition at line 39 of file hs2-util-test.cc.
References impala::StitchNulls().
TEST (StitchNullsTest , StitchOverlapping)
Definition at line 61 of file hs2-util-test.cc.
References impala::StitchNulls().
TEST (StitchNullsTest , StitchWithOffset)
Definition at line 82 of file hs2-util-test.cc.
References impala::StitchNulls().