Impala: be/src/exec/incr-stats-util.cc File Reference
incr-stats-util.cc File Reference
#include "incr-stats-util.h"
#include <boost/foreach.hpp>
#include <boost/unordered_set.hpp>
#include <gutil/strings/substitute.h>
#include <cmath>
#include <sstream>
#include "common/logging.h"
#include "service/hs2-util.h"
#include "udf/udf.h"
#include "gen-cpp/CatalogService_types.h"
#include "gen-cpp/CatalogObjects_types.h"
#include "exprs/aggregate-functions.h"
#include "common/names.h"
Classes
struct PerColumnStats
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Functions
StringVal IncrementNdvFinalize (FunctionContext *ctx, const StringVal &src)
string EncodeNdv (const string &ndv, bool *is_encoded)
string DecodeNdv (const string &ndv, bool is_encoded)
void impala::FinalizePartitionedColumnStats (const TTableSchema &col_stats_schema, const vector< TPartitionStats > &existing_part_stats, const vector< vector< string > > &expected_partitions, const TRowSet &rowset, int32_t num_partition_cols, TAlterTableUpdateStatsParams *params)
Function Documentation
string DecodeNdv (const string & ndv, bool is_encoded)
Definition at line 97 of file incr-stats-util.cc.
References HLL_LEN, and gen_ir_descriptions::idx.
Referenced by impala::FinalizePartitionedColumnStats(), and TEST().
string EncodeNdv (const string & ndv, bool * is_encoded)
Definition at line 58 of file incr-stats-util.cc.
References count, HLL_LEN, and gen_ir_descriptions::idx.
Referenced by impala::FinalizePartitionedColumnStats(), and TEST().
StringVal IncrementNdvFinalize (FunctionContext * ctx, const StringVal & src)
Definition at line 39 of file incr-stats-util.cc.
References impala_udf::FunctionContext::Free(), HLL_LEN, impala_udf::AnyVal::is_null, impala_udf::StringVal::len, and impala_udf::StringVal::ptr.