Impala: be/src/common/init.cc File Reference
init.cc File Reference
#include "common/init.h"
#include <google/heap-profiler.h>
#include <google/malloc_extension.h>
#include "common/logging.h"
#include "common/status.h"
#include "exprs/expr.h"
#include "util/cpu-info.h"
#include "util/debug-util.h"
#include "util/disk-info.h"
#include "util/logging-support.h"
#include "util/mem-info.h"
#include "util/network-util.h"
#include "util/os-info.h"
#include "util/redactor.h"
#include "util/test-info.h"
#include "runtime/decimal-value.h"
#include "runtime/exec-env.h"
#include "runtime/hdfs-fs-cache.h"
#include "runtime/lib-cache.h"
#include "runtime/mem-tracker.h"
#include "runtime/timestamp-parse-util.h"
#include "rpc/authentication.h"
#include "rpc/thrift-util.h"
#include "util/thread.h"
#include "common/names.h"
Functions
DECLARE_string (hostname)
DECLARE_string (redaction_rules_file)
DECLARE_int32 (logbufsecs)
DECLARE_string (heap_profile_dir)
DECLARE_bool (enable_process_lifetime_heap_profiling)
DEFINE_int32 (max_log_files, 10,"Maximum number of log files to retain per severity ""level. The most recent log files are retained. If set to 0, all log files are ""retained.")
DECLARE_string (vmodule)
static void MaintenanceThread ()
Variables
static const float TCMALLOC_RELEASE_FREE_MEMORY_FRACTION = 0.5f
shared_ptr< impala::Thread > maintenance_thread
Function Documentation
DECLARE_bool (enable_process_lifetime_heap_profiling)
DECLARE_int32 (logbufsecs)
DECLARE_string (hostname)
DECLARE_string (redaction_rules_file)
DECLARE_string (heap_profile_dir)
DECLARE_string (vmodule)
DEFINE_int32 (max_log_files , 10 , "Maximum number of log files to retain per severity ""level. The most recent log files are retained. If set to 0, all log files are""retained.")
static void MaintenanceThread () static
Definition at line 74 of file init.cc.
References impala::CheckAndRotateLogFiles(), impala::ExecEnv::GetInstance(), impala::TestInfo::is_test(), impala::ExecEnv::process_mem_tracker(), impala::MemTracker::Release(), and TCMALLOC_RELEASE_FREE_MEMORY_FRACTION.
Referenced by impala::InitCommonRuntime().
Variable Documentation
shared_ptr<impala::Thread> maintenance_thread
Definition at line 73 of file init.cc.
Referenced by impala::InitCommonRuntime().
const float TCMALLOC_RELEASE_FREE_MEMORY_FRACTION = 0.5f static
Definition at line 64 of file init.cc.
Referenced by MaintenanceThread().