Impala: be/src/util/jni-util.h File Reference
jni-util.h File Reference
#include <jni.h>
#include <string>
#include <vector>
#include "common/status.h"
#include "gen-cpp/Frontend_types.h"
Classes
class impala::JniLocalFrame
struct impala::JniMethodDescriptor
Describes one method to look up in a Java object.
class impala::JniUtil
Namespaces
impala
This file contains type definitions that are used throughout the code base.
Macros
#define THROW_IF_ERROR_WITH_LOGGING(stmt, env, adaptor)
#define THROW_IF_ERROR(stmt, env, impala_exc_cl)
#define THROW_IF_ERROR_RET(stmt, env, impala_exc_cl, ret)
#define THROW_IF_EXC(env, exc_class)
#define RETURN_IF_EXC(env)
#define EXIT_IF_EXC(env)
#define RETURN_ERROR_IF_EXC(env)
#define EXIT_IF_JNIERROR(stmt)
#define RETURN_IF_JNIERROR(stmt)
Functions
JNIEnv * getJNIEnv (void)
C linkage for helper functions in hdfsJniHelper.h.
Macro Definition Documentation
#define EXIT_IF_EXC (env)
Value:
do { \
    jthrowable exc = (env)->ExceptionOccurred(); \
    if (exc != NULL) { \
      jstring stack = (jstring) env->CallStaticObjectMethod(JniUtil::jni_util_class(), \
          (JniUtil::throwable_to_stack_trace_id()), exc); \
      jboolean is_copy; \
      const char* c_stack = \
          reinterpret_cast<const char*>((env)->GetStringUTFChars(stack, &is_copy)); \
      LOG(ERROR) << string(c_stack); \
     exit(1); \
    } \
  } while (false)
Definition at line 85 of file jni-util.h.
Referenced by impala::Catalog::Catalog(), impala::Frontend::Frontend(), impala::InitFeSupport(), impala::InitJvmLoggingSupport(), Planner::Planner(), and impala::RequestPoolService::RequestPoolService().
#define EXIT_IF_JNIERROR (stmt)
Value:
do { \
    if ((stmt) != JNI_OK) { \
      cerr << #stmt << " resulted in a jni error"; \
      exit(1); \
    } \
  } while (false)
Definition at line 105 of file jni-util.h.
#define RETURN_ERROR_IF_EXC (env)
Value:
do { \
    jthrowable exc = (env)->ExceptionOccurred(); \
    if (exc != NULL) return JniUtil::GetJniExceptionMsg(env);\
  } while (false)
Definition at line 99 of file jni-util.h.
Referenced by impala::HBaseTableWriter::AppendRowBatch(), CallJniMethod(), impala::JniUtil::CallJniMethod(), impala::HBaseTableWriter::CleanUpJni(), impala::HBaseTableWriter::CreateByteArray(), impala::HBaseTableWriter::CreatePut(), impala::HBaseTableWriter::CreatePutList(), Planner::GeneratePlan(), impala::Catalog::GetAllCatalogObjects(), impala::JniUtil::GetGlobalClassRef(), impala::HBaseTable::GetResultScanner(), impala::HBaseTableScanner::GetRowKey(), impala::HBaseTable::Init(), impala::HBaseTableFactory::Init(), impala::ExternalDataSourceExecutor::Init(), impala::HBaseTableScanner::Init(), impala::HBaseTable::InitJNI(), impala::HBaseTableWriter::InitJNI(), impala::HBaseTableScanner::InitScanRange(), impala::JniUtil::LoadJniMethod(), impala::JniUtil::LocalToGlobalRef(), impala::HBaseTableScanner::Next(), impala::HiveUdfCall::Open(), impala::HBaseTable::Put(), impala::HBaseTableScanner::ScanSetup(), impala::SerializeThriftMsg(), impala::Frontend::SetCatalogInitialized(), and impala::Frontend::ValidateSettings().
#define RETURN_IF_EXC (env)
Value:
do { \
    jthrowable exc = (env)->ExceptionOccurred(); \
    if (exc != NULL) { \
      jstring stack = (jstring) env->CallStaticObjectMethod(JniUtil::jni_util_class(), \
          (JniUtil::throwable_to_stack_trace_id()), exc); \
      jboolean is_copy; \
      const char* c_stack = \
          reinterpret_cast<const char*>((env)->GetStringUTFChars(stack, &is_copy)); \
      VLOG(1) << string(c_stack); \
     return; \
    } \
  } while (false)
Definition at line 71 of file jni-util.h.
#define RETURN_IF_JNIERROR (stmt)
Value:
do { \
    if ((stmt) != JNI_OK) { \
      stringstream out; \
      out << #stmt << " resulted in a jni error";      \
      return Status(out.str()); \
    } \
  } while (false)
Definition at line 113 of file jni-util.h.
#define THROW_IF_ERROR (stmt, env, impala_exc_cl)
Value:
do { \
    Status status = (stmt); \
    if (!status.ok()) { \
      (env)->ThrowNew((impala_exc_cl), status.GetDetail().c_str()); \
      return; \
    } \
  } while (false)
Definition at line 37 of file jni-util.h.
#define THROW_IF_ERROR_RET (stmt, env, impala_exc_cl, ret)
Value:
do { \
    Status status = (stmt); \
    if (!status.ok()) { \
      (env)->ThrowNew((impala_exc_cl), status.GetDetail().c_str()); \
      return (ret); \
    } \
  } while (false)
Definition at line 46 of file jni-util.h.
Referenced by Java_com_cloudera_impala_service_FeSupport_NativeCacheJar(), Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs(), Java_com_cloudera_impala_service_FeSupport_NativeGetStartupOptions(), Java_com_cloudera_impala_service_FeSupport_NativeLookupSymbol(), and Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad().
#define THROW_IF_ERROR_WITH_LOGGING (stmt, env, adaptor)
Value:
do { \
    Status status = (stmt); \
    if (!status.ok()) { \
      (adaptor)->WriteErrorLog(); \
      (adaptor)->WriteFileErrors(); \
      (env)->ThrowNew((adaptor)->impala_exc_cl(), status.GetDetail().c_str()); \
      return; \
    } \
  } while (false)
Definition at line 26 of file jni-util.h.
#define THROW_IF_EXC (env, exc_class)
Value:
do { \
    jthrowable exc = (env)->ExceptionOccurred(); \
    if (exc != NULL) { \
      DCHECK((throwable_to_string_id_) != NULL); \
      jstring stack = (jstring) env->CallStaticObjectMethod(JniUtil::jni_util_class(), \
          (JniUtil::throwable_to_stack_trace_id()), exc); \
      jboolean is_copy; \
      const char* c_stack = \
          reinterpret_cast<const char*>((env)->GetStringUTFChars(stack, &is_copy)); \
      (env)->ExceptionClear(); \
      (env)->ThrowNew((exc_class), c_stack); \
      return; \
    } \
  } while (false)
Definition at line 55 of file jni-util.h.
Function Documentation
JNIEnv* getJNIEnv (void)
C linkage for helper functions in hdfsJniHelper.h.
Referenced by impala::HBaseTableWriter::AppendRowBatch(), CallJniMethod(), impala::JniUtil::CallJniMethod(), impala::Catalog::Catalog(), impala::JniUtil::Cleanup(), impala::HBaseTableWriter::CleanUpJni(), impala::HBaseTable::Close(), impala::HBaseScanNode::Close(), impala::ExternalDataSourceExecutor::Close(), impala::HiveUdfCall::Close(), impala::HiveUdfCall::Evaluate(), impala::Frontend::Frontend(), Planner::GeneratePlan(), impala::Catalog::GetAllCatalogObjects(), impala::Catalog::GetCatalogVersion(), impala::HBaseScanNode::GetNext(), impala::HBaseTable::GetResultScanner(), impala::HBaseTable::Init(), impala::HBaseTableFactory::Init(), impala::ExternalDataSourceExecutor::Init(), impala::HBaseTableWriter::Init(), impala::HBaseTableScanner::Init(), impala::JniUtil::Init(), impala::InitFeSupport(), impala::HBaseTable::InitJNI(), impala::HBaseTableWriter::InitJNI(), impala::InitJvmLoggingSupport(), impala::HBaseScanNode::Open(), impala::HiveUdfCall::Open(), Planner::Planner(), impala::HBaseTable::Put(), impala::RequestPoolService::RequestPoolService(), impala::Frontend::SetCatalogInitialized(), impala::Frontend::ValidateSettings(), and impala::HBaseTableFactory::~HBaseTableFactory().