Impala: be/src/util/lru-cache-test.cc File Reference
lru-cache-test.cc File Reference
#include "lru-cache.h"
#include <boost/thread.hpp>
#include <glog/logging.h>
#include <gtest/gtest.h>
#include "common/init.h"
#include "common/logging.h"
#include "util/test-info.h"
#include "common/names.h"
Functions
TEST (FifoMultimap, Basic)
TEST (FifoMultimap, Evict)
TEST (FifoMultimap, Large)
void TestDeleter (int *v)
TEST (FifoMultimap, Deleter)
void TestCountDeleter (int *v)
void ParallelPut (const int start, const int end, FifoMultimap< int, int > *shelf)
TEST (FifoMultimap, ParallelEviction)
TEST (FifoMultimap, PopShouldPopMostRecent)
int main (int argc, char **argv)
Variables
static int del_sum = 0
static int del_count = 0
Function Documentation
int main (int argc, char ** argv)
Definition at line 141 of file lru-cache-test.cc.
void ParallelPut (const int start, const int end, FifoMultimap< int, int > * shelf)
Definition at line 91 of file lru-cache-test.cc.
References impala::FifoMultimap< Key, Value >::Pop(), and impala::FifoMultimap< Key, Value >::Put().
Referenced by TEST().
TEST (FifoMultimap , Basic)
Definition at line 32 of file lru-cache-test.cc.
References impala::FifoMultimap< Key, Value >::capacity(), impala::FifoMultimap< Key, Value >::Pop(), impala::FifoMultimap< Key, Value >::Put(), and impala::FifoMultimap< Key, Value >::size().
TEST (FifoMultimap , Evict)
Definition at line 45 of file lru-cache-test.cc.
References impala::FifoMultimap< Key, Value >::Pop(), impala::FifoMultimap< Key, Value >::Put(), and impala::FifoMultimap< Key, Value >::size().
TEST (FifoMultimap , Large)
Definition at line 61 of file lru-cache-test.cc.
References impala::FifoMultimap< Key, Value >::Pop(), impala::FifoMultimap< Key, Value >::Put(), and impala::FifoMultimap< Key, Value >::size().
TEST (FifoMultimap , Deleter)
Definition at line 78 of file lru-cache-test.cc.
References impala::FifoMultimap< Key, Value >::capacity(), del_sum, impala::FifoMultimap< Key, Value >::Put(), and TestDeleter().
TEST (FifoMultimap , ParallelEviction)
Definition at line 103 of file lru-cache-test.cc.
References impala::FifoMultimap< Key, Value >::capacity(), count, del_count, del_sum, ParallelPut(), impala::FifoMultimap< Key, Value >::size(), and TestCountDeleter().
TEST (FifoMultimap , PopShouldPopMostRecent)
Definition at line 119 of file lru-cache-test.cc.
References impala::FifoMultimap< Key, Value >::Pop(), impala::FifoMultimap< Key, Value >::Put(), and impala::FifoMultimap< Key, Value >::size().
void TestCountDeleter (int * v)
Definition at line 89 of file lru-cache-test.cc.
References del_count.
Referenced by TEST().
void TestDeleter (int * v)
Definition at line 76 of file lru-cache-test.cc.
References del_sum.
Referenced by TEST().
Variable Documentation
int del_count = 0 static
Definition at line 88 of file lru-cache-test.cc.
Referenced by TEST(), and TestCountDeleter().
int del_sum = 0 static
Definition at line 75 of file lru-cache-test.cc.
Referenced by TEST(), and TestDeleter().