Impala: impala Namespace Reference
impala Namespace Reference
This file contains type definitions that are used throughout the code base.
Namespaces
Coordinator
SSEUtil
This class contains constants useful for text processing with SSE4.2 intrinsics.
Classes
class CatalogServer
class Catalog
class CodegenAnyVal
class InstructionCounterTest
class InstructionCounter
class LlvmCodeGenTest
class LlvmCodeGen
LLVM code generator. This is the top level object to generate jitted code.
class SubExprElimination
class AtomicUtil
class AtomicInt
class ObjectPool
class Status
class AggregationNode
class AnalyticEvalNode
class BaseSequenceScanner
class BlockingJoinNode
class CatalogOpExecutor
class CrossJoinNode
class DataSink
Superclass of all data sinks.
class DataSourceScanNode
class DelimitedTextParser
class EmptySetNode
class ExchangeNode
class ExecNode
class ExternalDataSourceExecutor
class HashJoinNode
class HashTableTest
class HashTableCtx
class HashTable
class HBaseScanNode
class HBaseTableScanner
class HBaseTableSink
class HBaseTableWriter
class HdfsAvroScanner
class HdfsAvroTableWriter
class HdfsLzoTextScanner
class HdfsParquetScanner
class HdfsParquetTableWriter
class HdfsRCFileScanner
A scanner for reading RCFiles into tuples.
struct HdfsFileDesc
struct ScanRangeMetadata
class HdfsScanNode
struct FieldLocation
class HdfsScanner
class HdfsSequenceScanner
class HdfsSequenceTableWriter
struct OutputPartition
class HdfsTableSink
class HdfsTableWriter
class HdfsTextScanner
class HdfsTextTableWriter
class OldHashTableTest
class OldHashTable
The hash table does not support removes. The hash table is not thread safe.
class ParquetPlainEncoder
class PartitionedAggregationNode
class PartitionedHashJoinNode
class ReadWriteUtil
class RowBatchListTest
class RowBatchList
class ScanNode
Abstract base class of all scan nodes; introduces SetScanRange().
class ScannerContext
class SelectNode
class SortExecExprs
class SortNode
class TextConverter
class TopNNode
class UnionNode
class WriteStream
class BitWriter_8byte
class BitReader_8byte
class GrowingTest
class PartitioningThroughputTest
class StringSearchSSE
class AggFnEvaluator
struct AvgState
struct DecimalAvgState
struct ReservoirSample
struct ReservoirSample< StringVal >
struct ReservoirSampleState
struct KnuthVarianceState
struct RankState
class AggregateFunctions
class AnyValUtil
Utilities for AnyVals.
struct CaseExprState
class CaseExpr
class CastFunctions
class CompoundPredicate
class AndPredicate
Expr for evaluating and (&&) operators.
class OrPredicate
Expr for evaluating or (||) operators.
class ConditionalFunctions
Conditional functions that can be expressed as UDFs.
class IsNullExpr
class NullIfExpr
class IfExpr
class CoalesceExpr
class DecimalFunctions
class DecimalOperators
class ExprContext
class ScopedTimeZoneOverride
class ScopedLocalUnixTimestampConversionOverride
class ExprTest
struct ExprValue
The materialized value returned by ExprContext::GetValue().
class Expr
This is the superclass of all expr evaluation nodes.
struct JniContext
class HiveUdfCall
If the UDF ran into an error, the FE throws an exception.
class InPredicateBenchmark
class InPredicate
Predicate for evaluating expressions of the form "val [NOT] IN (x1, x2, x3...)".
class IsNullPredicate
class LikePredicate
This class handles the Like, Regexp, and Rlike predicates and uses the udf interface.
class Literal
class MathFunctions
class NullLiteral
class Operators
Operators written against the UDF interface.
class Predicate
class ScalarFnCall
class SlotRef
Reference to a single slot of a tuple.
class StringFunctions
class TimestampFunctions
TODO: Reconsider whether this class needs to exist.
class TimezoneDatabase
Functions to load and access the timestamp database.
class TupleIsNullPredicate
class UdfBuiltins
class UtilityFunctions
class LlamaNotificationThriftIf
class ResourceBroker
class AuthProvider
class SaslAuthProvider
class NoAuthProvider
class AuthManager
class RpcEventHandler
class ThriftClientImpl
Super class for templatized thrift clients.
class ThriftClient
class ThriftServer
class ThriftThreadFactory
class ThriftThread
class ThriftSerializer
class ThriftDeserializer
class BufferedBlockMgrTest
class BufferedBlockMgr
class SimpleTupleStreamTest
class SimpleNullStreamTest
class MultiTupleStreamTest
class MultiNullableTupleStreamTest
class BufferedTupleStream
The underlying memory management is done by the BufferedBlockMgr.
class ClientCacheHelper
This class is thread-safe.
class ClientCache
class ClientConnection
struct DebugOptions
struct InstanceComparator
struct FragmentInstanceCounters
Struct for per fragment instance counters that will be aggregated by the coordinator.
struct PerFragmentProfileData
Per fragment profile information.
class DataStreamMgr
class DataStreamRecvr
class DataStreamSender
class ImpalaTestBackend
class DataStreamTest
class DecimalValue
struct LlvmTupleStruct
struct NullIndicatorOffset
class SlotDescriptor
class TableDescriptor
Base class for table descriptors.
class HdfsPartitionDescriptor
Metadata for a single partition inside an Hdfs table.
class HdfsTableDescriptor
class HBaseTableDescriptor
class DataSourceTableDescriptor
Descriptor for a DataSourceTable.
class TupleDescriptor
class DescriptorTbl
class RowDescriptor
class DiskIoMgrStress
class DiskIoMgrTest
class DiskIoMgr
class ExecEnv
class FreePool
class HBaseTableFactory
class HBaseTable
Class to wrap JNI calls into HTable.
class HdfsFsCache
class LibCache
class MemPoolTest
class MemPool
class GcFunctionHelper
class MemTracker
This class is thread-safe.
class ParallelExecutorTest
class ParallelExecutor
class PlanFragmentExecutor
class RawValueTest
class RawValue
Useful utility functions for runtime values (which are passed around as void*).
class RowBatch
class RuntimeState
class SortedRunMerger
class Sorter
Note that Init() must be called right after the constructor.
class StringBuffer
class StringSearch
struct StringValue
class NotifiedCounter
class ThreadResourceMgr
struct DateTimeFormatToken
Used to store metadata about a token group within a date/time format.
struct DateTimeFormatContext
struct DateTimeParseResult
Stores the results of parsing a date/time string.
class TimestampParser
Used for parsing both default and custom formatted timestamp values.
struct TimestampTC
struct TimestampFormatTC
struct TimestampToken
class TimestampValue
class TmpFileMgr
class TupleRow
class Tuple
A tuple with 0 materialised slots is represented as NULL.
struct ColumnType
class AdmissionController
class RequestPoolService
class ChildQuery
class FragmentMgr
class Frontend
class ImpalaInternalService
class ImapalaServiceWebHandlers
class CancellationWork
class ImpalaServer
class LdapTestServer
class FailureDetector
class TimeoutFailureDetector
class MissedHeartbeatFailureDetector
class ResourceResolver
class QueryResourceMgr
Only CPU-heavy threads need be managed using this class.
struct FragmentExecParams
class QuerySchedule
class Scheduler
class SimpleSchedulerTest
class SimpleScheduler
class StateStore2Test
class TestRegistrationCb
class TestReceiveTopicCb
class StatestoreSubscriberThriftIf
class StatestoreSubscriber
class Statestore
class DescriptorTblBuilder
class TupleDescBuilder
class ImpaladQueryExecutor
Query execution against running impalad process.
class InProcessImpalaServer
class InProcessStatestore
An in-process statestore, with webserver and metrics.
class FunctionContextImpl
struct MemcpyData
class BenchmarkTest
class Benchmark
class BitWriter
class BitReader
class BitUtil
class Bitmap
class MultiThreadTest
class BlockingQueue
class BufferBuilder
Utility class to build an in-memory buffer.
class CgroupsMgr
class Codec
class SetMetric
Metric whose value is a set of items.
class StatsMetric
class GzipCompressor
class BzipCompressor
class SnappyBlockCompressor
class SnappyCompressor
class Lz4Compressor
struct HashTNetworkAddressPtr
struct TNetworkAddressPtrEquals
class CpuInfo
class DebugRuntimeProfile
class DecimalUtil
class DecompressorTest
class GzipDecompressor
class BzipDecompressor
class SnappyDecompressor
class Lz4Decompressor
class SnappyBlockDecompressor
class DictEncoderBase
class DictEncoder
class DictDecoderBase
class DictDecoder
class DiskInfo
class ErrorMsg
class FileSystemUtil
class HashUtil
Utility class to compute hash values.
class HdfsOp
class HdfsOperationSet
class ImpaladMetricKeys
Contains the keys (strings) for impala metrics.
class ImpaladMetrics
struct IntNode
class InternalQueue
T must be a subclass of InternalQueue::Node.
class JniLocalFrame
struct JniMethodDescriptor
Describes one method to look up in a Java object.
class JniUtil
class KeyNormalizer
Finally, we pad any remaining bytes of the key with zeroes.
class FifoMultimap
class MemInfo
class TcmallocMetric
Specialised metric which exposes numeric properties from tcmalloc.
class JvmMetric
class Metric
TODO: Add ToThrift() for conversion to an RPC-friendly format.
class SimpleMetric
class MetricGroup
MetricGroups may be organised hierarchically as a tree.
class OsInfo
Provides information about the OS we're running on.
struct ThreadStats
Container struct for statistics read from the /proc filesystem for a thread.
class ParseUtil
Utility class for parsing information from strings.
class PathBuilder
Utility class to construct full paths relative to the impala_home path.
class PerfCounters
class PeriodicCounterUpdater
class PrettyPrinter
class ProcessStateInfo
class ProgressUpdater
struct ScopedLimitResetter
class Promise
class TempRulesFile
struct Rule
class RulesParser
class RleDecoder
Decoder class for RLE encoded data.
class RleEncoder
class RuntimeProfile
class ScopedEvent
Utility class to mark an event when the object is destroyed.
class ScopedCounter
class ScopedTimer
class ThreadCounterMeasurement
class SimpleLogger
class SpinLock
Lightweight spinlock.
class StatUtil
class UnusedClass
class StopWatch
class MonotonicStopWatch
class StreamingSampler
class StringParser
class SymbolsUtil
Utility class to manipulate c++/IR symbols, mangling and demangling names.
class TablePrinter
class TestInfo
class ThreadPool
class ThreadMgr
class Thread
TODO: Consider allowing fragment IDs as category parameters.
class ThreadGroup
class TimerMetric
class TupleRowComparator
struct TupleEqualityChecker
Compares the equality of two Tuples, going slot by slot.
struct RowEqualityChecker
Compares the equality of two TupleRows, going tuple by tuple.
class UrlParser
class Webserver
Typedefs
typedef function< void(int64_t,
int64_t, AtomicInt< int > *)> Fn
typedef int TupleId
typedef int SlotId
typedef int TableId
typedef int PlanNodeId
typedef int StringConcatHeader
typedef void * ClientKey
typedef ClientCache
< ImpalaInternalServiceClient > ImpalaInternalServiceClientCache
typedef ClientConnection
< ImpalaInternalServiceClient > ImpalaInternalServiceConnection
typedef ClientCache
< CatalogServiceClient > CatalogServiceClientCache
typedef ClientConnection
< CatalogServiceClient > CatalogServiceConnection
typedef
boost::accumulators::accumulator_set
< int64_t,
boost::accumulators::features
< boost::accumulators::tag::min,
boost::accumulators::tag::max,
boost::accumulators::tag::mean,
boost::accumulators::tag::variance > > SummaryStats
typedef std::map< PlanNodeId,
RuntimeProfile::Counter * > CounterMap
map from id of a scan node to a specific counter in the node's profile
typedef boost::unordered_map
< TUniqueId, BackendExecState * > BackendExecStateMap
typedef boost::unordered_map
< std::string, std::pair< bool,
short > > PermissionCache
typedef DecimalValue< int32_t > Decimal4Value
typedef DecimalValue< int64_t > Decimal8Value
typedef DecimalValue< int128_t > Decimal16Value
typedef __int128_t int128_t
We use the c++ int128_t type. This is stored using 16 bytes and very performant.
typedef
boost::multiprecision::number
< boost::multiprecision::cpp_int_backend
< 256, 256, boost::multiprecision::signed_magnitude,
boost::multiprecision::unchecked,
void > > int256_t
Define 256 bit int type.
typedef std::map< std::string,
TInsertPartitionStatus > PartitionStatusMap
typedef std::map< std::string,
TInsertStats > PartitionInsertStats
Stats per partition for insert queries. They key is the same as for PartitionRowCount.
typedef std::map< std::string,
std::string > FileMoveMap
typedef std::map< TPlanNodeId,
std::vector< TScanRangeParams > > PerNodeScanRanges
map from scan node id to a list of scan ranges
typedef boost::unordered_map
< TNetworkAddress,
PerNodeScanRanges > FragmentScanRangeAssignment
typedef ClientConnection
< StatestoreServiceClient > StatestoreConnection
typedef ClientCache
< StatestoreServiceClient > StatestoreClientCache
typedef std::map
< TErrorCode::type,
TErrorLogEntry > ErrorLogMap
Tracks log messages per error code.
typedef ThreadPool< HdfsOp > HdfsOpThreadPool
typedef class SimpleMetric
< int64_t, TMetricKind::GAUGE > IntGauge
We write 'Int' as a placeholder for all integer types.
typedef class SimpleMetric
< uint64_t, TMetricKind::GAUGE > UIntGauge
typedef class SimpleMetric
< double, TMetricKind::GAUGE > DoubleGauge
typedef class SimpleMetric
< int64_t,
TMetricKind::COUNTER > IntCounter
typedef class SimpleMetric
< bool, TMetricKind::PROPERTY > BooleanProperty
typedef class SimpleMetric
< std::string,
TMetricKind::PROPERTY > StringProperty
typedef re2::RE2 Regex
typedef vector< Rule > Rules
Enumerations
enum Op {
ADD, SUBTRACT, MULTIPLY, DIVIDE,
MOD
}
enum DateTimeFormatTokenType {
UNKNOWN = 0, SEPARATOR, YEAR, MONTH_IN_YEAR,
MONTH_IN_YEAR_SLT, DAY_IN_MONTH, HOUR_IN_DAY, MINUTE_IN_HOUR,
SECOND_IN_MINUTE, FRACTION
}
Used to indicate the type of a date/time format token group.
enum PrimitiveType {
INVALID_TYPE = 0, TYPE_NULL, TYPE_BOOLEAN, TYPE_TINYINT,
TYPE_SMALLINT, TYPE_INT, TYPE_BIGINT, TYPE_FLOAT,
TYPE_DOUBLE, TYPE_TIMESTAMP, TYPE_STRING, TYPE_DATE,
TYPE_DATETIME, TYPE_BINARY, TYPE_DECIMAL, TYPE_CHAR,
TYPE_VARCHAR
}
enum HdfsOpType {
DELETE, CREATE_DIR, RENAME, DELETE_THEN_CREATE,
CHMOD
}
enum PERF_IO_IDX {
PROC_IO_READ = 0, PROC_IO_WRITE, PROC_IO_SYS_RREAD, PROC_IO_SYS_WRITE,
PROC_IO_DISK_READ, PROC_IO_DISK_WRITE, PROC_IO_CANCELLED_WRITE, PROC_IO_LAST_COUNTER
}
enum ResponseCode { OK = 200, NOT_FOUND = 404 }
enum ContentType { HTML, PLAIN }
Functions
TCatalogObjectType::type TCatalogObjectTypeFromName (const string &name)
Status TCatalogObjectFromEntryKey (const string &key, TCatalogObject *catalog_object)
Status TCatalogObjectFromObjectName (const TCatalogObjectType::type &object_type, const string &object_name, TCatalogObject *catalog_object)
string TCatalogObjectToEntryKey (const TCatalogObject &catalog_object)
TCatalogObjectType::type TCatalogObjectTypeFromName (const std::string &name)
Status TCatalogObjectFromEntryKey (const std::string &key, TCatalogObject *catalog_object)
Status TCatalogObjectFromObjectName (const TCatalogObjectType::type &object_type, const std::string &object_name, TCatalogObject *catalog_object)
Module * CodegenMulAdd (LLVMContext *context)
TEST_F (InstructionCounterTest, Count)
Module * CodegenGcd (LLVMContext *context)
TEST_F (InstructionCounterTest, TestMemInstrCount)
TEST_F (LlvmCodeGenTest, BasicLifetime)
TEST_F (LlvmCodeGenTest, MultithreadedLifetime)
TEST_F (LlvmCodeGenTest, BadIRFile)
Function * CodegenInnerLoop (LlvmCodeGen *codegen, int64_t *jitted_counter, int delta)
TEST_F (LlvmCodeGenTest, ReplaceFnCall)
Function * CodegenStringTest (LlvmCodeGen *codegen)
TEST_F (LlvmCodeGenTest, StringValue)
TEST_F (LlvmCodeGenTest, MemcpyTest)
TEST_F (LlvmCodeGenTest, HashTest)
void DebugTrace (const char *str)
static Function * GetLenOptimizedHashFn (LlvmCodeGen *codegen, IRFunction::Type f, int len)
TEST (AtomicTest, Basic)
TEST (AtomicTest, TestAndSet)
void IncrementThread (int64_t id, int64_t n, AtomicInt< int > *ai)
void DecrementThread (int64_t id, int64_t n, AtomicInt< int > *ai)
TEST (AtomicTest, MultipleThreadsIncDec)
void CASIncrementThread (int64_t id, int64_t n, AtomicInt< int > *ai)
void CASDecrementThread (int64_t id, int64_t n, AtomicInt< int > *ai)
TEST (AtomicTest, MultipleThreadsCASIncDec)
void InitCommonRuntime (int argc, char **argv, bool init_jvm, TestInfo::Mode m=TestInfo::NON_TEST)
void InitGoogleLoggingSafe (const char *arg)
void GetFullLogFilename (google::LogSeverity severity, std::string *filename)
void ShutdownLogging ()
void LogCommandLineFlags ()
Writes all command-line flags to the log at level INFO.
void CheckAndRotateLogFiles (int max_log_files)
IRFunction::Type GetHllUpdateFunction2 (const ColumnType &type)
string DebugWindowBoundString (const TAnalyticWindowBoundary &b)
Status SetDecimalVal (const ColumnType &type, char *bytes, int len, void *slot)
void Validate (DelimitedTextParser *parser, const string &data, int expected_offset, char tuple_delim, int expected_num_tuples, int expected_num_fields)
TEST (DelimitedTextParser, Basic)
TEST (DelimitedTextParser, Fields)
void ProcessEscapeMask (uint16_t escape_mask, bool *last_char_is_escape, uint16_t *delim_mask)
TEST_F (HashTableTest, LinearSetupTest)
TEST_F (HashTableTest, QuadraticSetupTest)
TEST_F (HashTableTest, LinearBasicTest)
TEST_F (HashTableTest, QuadraticBasicTest)
TEST_F (HashTableTest, LinearScanTest)
TEST_F (HashTableTest, QuadraticScanTest)
TEST_F (HashTableTest, LinearGrowTableTest)
TEST_F (HashTableTest, QuadraticGrowTableTest)
TEST_F (HashTableTest, LinearInsertFullTest)
TEST_F (HashTableTest, QuadraticInsertFullTest)
void FinalizePartitionedColumnStats (const TTableSchema &col_stats_schema, const vector< TPartitionStats > &existing_part_stats, const vector< vector< string > > &expected_partitions, const TRowSet &rowset, int32_t num_partition_cols, TAlterTableUpdateStatsParams *params)
void FinalizePartitionedColumnStats (const apache::hive::service::cli::thrift::TTableSchema &col_stats_schema, const std::vector< TPartitionStats > &existing_part_stats, const std::vector< std::vector< std::string > > &expected_partitions, const apache::hive::service::cli::thrift::TRowSet &rowset, int32_t num_partition_cols, TAlterTableUpdateStatsParams *params)
TEST_F (OldHashTableTest, SetupTest)
TEST_F (OldHashTableTest, BasicTest)
TEST_F (OldHashTableTest, ScanTest)
TEST_F (OldHashTableTest, GrowTableTest)
template<typename T >
void TestType (const T &v, int expected_byte_size)
TEST (PlainEncoding, Basic)
TEST (PlainEncoding, DecimalBigEndian)
void CheckVersionParse (const string &s, const string &expected_application, int expected_major, int expected_minor, int expected_patch, bool expected_is_internal)
TEST (ParquetVersionTest, Parsing)
TEST (ParquetVersionTest, Comparisons)
template<typename T >
void TestBigEndian (T value)
TEST (ReadWriteUtil, BigEndian)
TEST_F (RowBatchListTest, BasicTest)
TEST_F (RowBatchListTest, EmptyBatchTest)
TEST_F (RowBatchListTest, MultipleRowBatchesTest)
void TestZInt (int32_t value)
void TestZLong (int64_t value)
TEST (ZigzagTest, Basic)
void TestCompression (int num, int min_len, int max_len, THdfsCompression::type codec)
void TestSearch (const char *haystack_orig, const char *needle_orig, int haystack_len=-1, int needle_len=-1)
TEST (StringSearchTest, Basic)
template<typename T >
StringVal ToStringVal (FunctionContext *context, T val)
static void SetDistinctEstimateBit (uint8_t *bitmap, uint32_t row_index, uint32_t bit_index)
static bool GetDistinctEstimateBit (uint8_t *bitmap, uint32_t row_index, uint32_t bit_index)
string DistinctEstimateBitMapToString (uint8_t *v)
double DistinceEstimateFinalize (const StringVal &src)
template<typename T >
bool SampleValLess (const ReservoirSample< T > &i, const ReservoirSample< T > &j)
template<>
bool SampleValLess (const ReservoirSample< StringVal > &i, const ReservoirSample< StringVal > &j)
template<>
bool SampleValLess (const ReservoirSample< DecimalVal > &i, const ReservoirSample< DecimalVal > &j)
template<>
bool SampleValLess (const ReservoirSample< TimestampVal > &i, const ReservoirSample< TimestampVal > &j)
template<typename T >
bool SampleKeyGreater (const ReservoirSample< T > &i, const ReservoirSample< T > &j)
template<typename T >
void PrintSample (const ReservoirSample< T > &v, ostream *os)
template<>
void PrintSample (const ReservoirSample< TinyIntVal > &v, ostream *os)
template<>
void PrintSample (const ReservoirSample< StringVal > &v, ostream *os)
template<>
void PrintSample (const ReservoirSample< DecimalVal > &v, ostream *os)
template<>
void PrintSample (const ReservoirSample< TimestampVal > &v, ostream *os)
double ComputeKnuthVariance (const KnuthVarianceState &state, bool pop)
AnyVal * CreateAnyVal (ObjectPool *pool, const ColumnType &type)
Creates the corresponding AnyVal subclass for type. The object is added to the pool.
AnyVal * CreateAnyVal (const ColumnType &type)
Creates the corresponding AnyVal subclass for type. The object is owned by the caller.
static Decimal4Value GetDecimal4Value (const DecimalVal &val, const ColumnType &type, bool *overflow)
static Decimal8Value GetDecimal8Value (const DecimalVal &val, const ColumnType &type, bool *overflow)
static Decimal16Value GetDecimal16Value (const DecimalVal &val, const ColumnType &type, bool *overflow)
template<typename ORIGINAL_TYPE , typename VAL_TYPE >
string LiteralToString (VAL_TYPE val)
template<>
string LiteralToString< float, float > (float val)
template<>
string LiteralToString< float, double > (double val)
template<>
string LiteralToString< double, double > (double val)
template<typename T >
void TestSingleLiteralConstruction (const ColumnType &type, const T &value, const string &string_val)
TEST_F (ExprTest, NullLiteral)
TEST_F (ExprTest, LiteralConstruction)
TEST_F (ExprTest, LiteralExprs)
TEST_F (ExprTest, ArithmeticExprs)
TEST_F (ExprTest, DecimalArithmeticExprs)
TEST_F (ExprTest, BinaryPredicates)
TEST_F (ExprTest, CastExprs)
TEST_F (ExprTest, CompoundPredicates)
TEST_F (ExprTest, IsNullPredicate)
TEST_F (ExprTest, LikePredicate)
TEST_F (ExprTest, BetweenPredicate)
TEST_F (ExprTest, InPredicate)
TEST_F (ExprTest, StringFunctions)
TEST_F (ExprTest, StringRegexpFunctions)
TEST_F (ExprTest, StringParseUrlFunction)
TEST_F (ExprTest, UtilityFunctions)
TEST_F (ExprTest, NonFiniteFloats)
TEST_F (ExprTest, MathTrigonometricFunctions)
TEST_F (ExprTest, MathConversionFunctions)
TEST_F (ExprTest, MathFunctions)
TEST_F (ExprTest, MathRoundingFunctions)
TEST_F (ExprTest, UnaryOperators)
TEST_F (ExprTest, TimestampFunctions)
TEST_F (ExprTest, ConditionalFunctions)
TEST_F (ExprTest, ConditionalFunctionIsTrue)
TEST_F (ExprTest, ConditionalFunctionIsFalse)
TEST_F (ExprTest, ConditionalFunctionIsNotTrue)
TEST_F (ExprTest, ConditionalFunctionIsNotFalse)
void ValidateLayout (const vector< Expr * > &exprs, int expected_byte_size, int expected_var_begin, const map< int, set< int > > &expected_offsets)
TEST_F (ExprTest, ResultsLayoutTest)
TEST_F (ExprTest, DecimalFunctions)
TEST_F (ExprTest, DecimalOverflowCasts)
TEST_F (ExprTest, NullValueFunction)
TEST_F (ExprTest, NonNullValueFunction)
TEST_F (ExprTest, UdfInterfaceBuiltins)
TEST_F (ExprTest, MADlib)
template<typename T >
T MakeAnyVal (int v)
template<>
StringVal MakeAnyVal (int v)
template<typename T , typename SetType >
SetType GetVal (const FunctionContext::TypeDesc *type, const T &x)
template<>
StringValue GetVal (const FunctionContext::TypeDesc *type, const StringVal &x)
template<>
TimestampValue GetVal (const FunctionContext::TypeDesc *type, const TimestampVal &x)
template<>
Decimal16Value GetVal (const FunctionContext::TypeDesc *type, const DecimalVal &x)
static const RE2 SUBSTRING_RE ("(?:\\.\\*)*([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)(?:\\.\\*)*")
static const RE2 ENDS_WITH_RE ("(?:\\.\\*)*([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)\\$")
static const RE2 STARTS_WITH_RE ("\\^([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)(?:\\.\\*)*")
static const RE2 EQUALS_RE ("\\^([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)\\$")
template<class T >
bool ParseString (const string &str, T *val)
ONE_ARG_MATH_FN (Abs, BigIntVal, BigIntVal, llabs)
ONE_ARG_MATH_FN (Abs, DoubleVal, DoubleVal, fabs)
ONE_ARG_MATH_FN (Abs, FloatVal, FloatVal, fabs)
ONE_ARG_MATH_FN (Abs, IntVal, IntVal, abs)
ONE_ARG_MATH_FN (Abs, SmallIntVal, SmallIntVal, abs)
ONE_ARG_MATH_FN (Abs, TinyIntVal, TinyIntVal, abs)
ONE_ARG_MATH_FN (Sin, DoubleVal, DoubleVal, sin)
ONE_ARG_MATH_FN (Asin, DoubleVal, DoubleVal, asin)
ONE_ARG_MATH_FN (Cos, DoubleVal, DoubleVal, cos)
ONE_ARG_MATH_FN (Acos, DoubleVal, DoubleVal, acos)
ONE_ARG_MATH_FN (Tan, DoubleVal, DoubleVal, tan)
ONE_ARG_MATH_FN (Atan, DoubleVal, DoubleVal, atan)
ONE_ARG_MATH_FN (Sqrt, DoubleVal, DoubleVal, sqrt)
ONE_ARG_MATH_FN (Ceil, BigIntVal, DoubleVal, ceil)
ONE_ARG_MATH_FN (Floor, BigIntVal, DoubleVal, floor)
ONE_ARG_MATH_FN (Ln, DoubleVal, DoubleVal, log)
ONE_ARG_MATH_FN (Log10, DoubleVal, DoubleVal, log10)
ONE_ARG_MATH_FN (Exp, DoubleVal, DoubleVal, exp)
BINARY_OP_NUMERIC_TYPES (Add,+)
BINARY_OP_NUMERIC_TYPES (Subtract,-)
BINARY_OP_NUMERIC_TYPES (Multiply,*)
BINARY_OP_FN (Divide, DoubleVal,/)
BINARY_OP_CHECK_ZERO_INT_TYPES (Int_divide,/)
BINARY_OP_CHECK_ZERO_INT_TYPES (Mod,%)
BINARY_OP_INT_TYPES (Bitand,&)
BINARY_OP_INT_TYPES (Bitxor,^)
BINARY_OP_INT_TYPES (Bitor,|)
BITNOT_FN (TinyIntVal)
BITNOT_FN (SmallIntVal)
BITNOT_FN (IntVal)
BITNOT_FN (BigIntVal)
BINARY_PREDICATE_ALL_TYPES (Eq,==)
BINARY_PREDICATE_ALL_TYPES (Ne,!=)
BINARY_PREDICATE_ALL_TYPES (Gt, >)
BINARY_PREDICATE_ALL_TYPES (Lt,<)
BINARY_PREDICATE_ALL_TYPES (Ge, >=)
BINARY_PREDICATE_ALL_TYPES (Le,<=)
re2::RE2 * CompileRegex (const StringVal &pattern, string *error_str)
ostream & operator<< (ostream &os, const map< TNetworkAddress, llama::TAllocatedResource > &resources)
ostream & operator<< (ostream &os, const TResourceBrokerReservationRequest &request)
ostream & operator<< (ostream &os, const TResourceBrokerReservationResponse &reservation)
ostream & operator<< (ostream &os, const TResourceBrokerExpansionRequest &request)
ostream & operator<< (ostream &os, const TResourceBrokerExpansionResponse &expansion)
std::ostream & operator<< (std::ostream &os, const TResourceBrokerReservationRequest &request)
std::ostream & operator<< (std::ostream &os, const TResourceBrokerReservationResponse &reservation)
std::ostream & operator<< (std::ostream &os, const TResourceBrokerExpansionRequest &request)
std::ostream & operator<< (std::ostream &os, const TResourceBrokerExpansionResponse &expansion)
Status InitAuth (const std::string &appname)
TEST (Auth, PrincipalSubstitution)
TEST (Auth, ValidAuthProviders)
TEST (Auth, LdapAuth)
TEST (Auth, LdapKerbAuth)
static int SaslLogCallback (void *context, int level, const char *message)
int SaslLdapCheckPass (sasl_conn_t *conn, void *context, const char *user, const char *pass, unsigned passlen, struct propctx *propctx)
static int SaslGetOption (void *context, const char *plugin_name, const char *option, const char **result, unsigned *len)
static void ImpalaAuxpropLookup (void *glob_context, sasl_server_params_t *sparams, unsigned int flags, const char *user, unsigned ulen)
int ImpalaAuxpropInit (const sasl_utils_t *utils, int max_version, int *out_version, sasl_auxprop_plug_t **plug, const char *plugname)
static int SaslVerifyFile (void *context, const char *file, sasl_verify_type_t type)
static int SaslAuthorizeInternal (sasl_conn_t *conn, void *context, const char *requested_user, unsigned rlen, const char *auth_identity, unsigned alen, const char *def_realm, unsigned urlen, struct propctx *propctx)
static int SaslAuthorizeExternal (sasl_conn_t *conn, void *context, const char *requested_user, unsigned rlen, const char *auth_identity, unsigned alen, const char *def_realm, unsigned urlen, struct propctx *propctx)
static int SaslGetPath (void *context, const char **path)
Status InitAuth (const string &appname)
Status CheckReplayCacheDirPermissions ()
static Status EnvAppend (const string &attr, const string &thing, const string &thingval)
template<class T >
Status SerializeThriftMsg (JNIEnv *env, T *msg, jbyteArray *serialized_msg)
template<class T >
Status DeserializeThriftMsg (JNIEnv *env, jbyteArray serialized_msg, T *deserialized_msg)
void InitRpcEventTracing (Webserver *webserver)
Initialises rpc event tracing, must be called before any RpcEventHandlers are created.
TEST (ThriftUtil, SimpleSerializeDeserialize)
TEST (ThriftUtil, TNetworkAddressComparator)
shared_ptr< TProtocol > CreateDeserializeProtocol (shared_ptr< TMemoryBuffer > mem, bool compact)
static void ThriftOutputFunction (const char *output)
void InitThriftLogging ()
Redirects all Thrift logging to VLOG(1)
Status WaitForLocalServer (const ThriftServer &server, int num_retries, int retry_interval_ms)
Status WaitForServer (const string &host, int port, int num_retries, int retry_interval_ms)
std::ostream & operator<< (std::ostream &out, const TColumnValue &colval)
Print a TColumnValue. If null, print "NULL".
bool TNetworkAddressComparator (const TNetworkAddress &a, const TNetworkAddress &b)
bool IsTimeoutTException (const TException &e)
boost::shared_ptr
< apache::thrift::protocol::TProtocol > CreateDeserializeProtocol (boost::shared_ptr< apache::thrift::transport::TMemoryBuffer > mem, bool compact)
Utility to create a protocol (deserialization) object for 'mem'.
template<class T >
Status DeserializeThriftMsg (const uint8_t *buf, uint32_t *len, bool compact, T *deserialized_msg)
Status WaitForServer (const std::string &host, int port, int num_retries, int retry_interval_ms)
Wait for a server to start accepting connections, up to a maximum timeout.
bool IsTimeoutTException (const apache::thrift::TException &e)
Returns true if the TException corresponds to a TCP socket recv or send timeout.
TEST_F (BufferedBlockMgrTest, GetNewBlock)
TEST_F (BufferedBlockMgrTest, GetNewBlockSmallBlocks)
TEST_F (BufferedBlockMgrTest, Pin)
TEST_F (BufferedBlockMgrTest, Eviction)
TEST_F (BufferedBlockMgrTest, Deletion)
TEST_F (BufferedBlockMgrTest, Close)
TEST_F (BufferedBlockMgrTest, WriteError)
TEST_F (BufferedBlockMgrTest, MultipleClients)
TEST_F (BufferedBlockMgrTest, MultipleClientsExtraBuffers)
TEST_F (BufferedBlockMgrTest, ClientOversubscription)
TEST_F (BufferedBlockMgrTest, SingleRandom_plain)
TEST_F (BufferedBlockMgrTest, Multi2Random_plain)
TEST_F (BufferedBlockMgrTest, Multi4Random_plain)
TEST_F (BufferedBlockMgrTest, SingleRandom_encryption)
TEST_F (BufferedBlockMgrTest, Multi2Random_encryption)
TEST_F (BufferedBlockMgrTest, Multi4Random_encryption)
static int OpenSSLErrCallback (const char *buf, size_t len, void *ctx)
static Status OpenSSLErr (const string &msg)
TEST_F (SimpleTupleStreamTest, Basic)
TEST_F (SimpleTupleStreamTest, OneBufferSpill)
TEST_F (SimpleTupleStreamTest, ManyBufferSpill)
TEST_F (SimpleTupleStreamTest, UnpinPin)
TEST_F (SimpleTupleStreamTest, SmallBuffers)
TEST_F (SimpleNullStreamTest, Basic)
TEST_F (MultiTupleStreamTest, MultiTupleOneBufferSpill)
TEST_F (MultiTupleStreamTest, MultiTupleManyBufferSpill)
TEST_F (MultiNullableTupleStreamTest, MultiNullableTupleOneBufferSpill)
TEST_F (MultiNullableTupleStreamTest, MultiNullableTupleManyBufferSpill)
TExecNodePhase::type GetExecNodePhase (const string &key)
TDebugAction::type GetDebugAction (const string &key)
static void ProcessQueryOptions (const TQueryOptions &query_options, DebugOptions *debug_options)
~Coordinator ()
Status Exec (QuerySchedule &schedule, std::vector< ExprContext * > *output_expr_ctxs)
Status Wait ()
Status GetNext (RowBatch **batch, RuntimeState *state)
void Cancel (const Status *cause=NULL)
Status UpdateFragmentExecStatus (const TReportExecStatusParams &params)
RuntimeState * runtime_state ()
only valid after calling Exec(), and may return NULL if there is no executor
const RowDescriptor & row_desc () const
MemTracker * query_mem_tracker ()
RuntimeProfile * query_profile () const
const TUniqueId & query_id () const
const PartitionStatusMap & per_partition_status ()
This is safe to call only after Wait()
bool PrepareCatalogUpdate (TUpdateCatalogRequest *catalog_update)
std::string GetErrorLog ()
const ProgressUpdater & progress ()
Status GetStatus ()
Returns query_status_.
const TExecSummary & exec_summary () const
SpinLock & GetExecSummaryLock () const
ObjectPool * obj_pool ()
Returns a local object pool.
void SetExecPlanFragmentParams (QuerySchedule &schedule, int backend_num, const TPlanFragment &fragment, int fragment_idx, const FragmentExecParams &params, int instance_idx, const TNetworkAddress &coord, TExecPlanFragmentParams *rpc_params)
Fill in rpc_params based on parameters.
Status ExecRemoteFragment (void *exec_state)
int GetFragmentNum (const TUniqueId &fragment_id)
Determine fragment number, given fragment id.
void PrintBackendInfo ()
void CreateAggregateCounters (const std::vector< TPlanFragment > &fragments)
Create aggregate counters for all scan nodes in any of the fragments.
void CollectScanNodeCounters (RuntimeProfile *, FragmentInstanceCounters *result)
int64_t ComputeTotalThroughput (int node_id)
int64_t ComputeTotalScanRangesComplete (int node_id)
void CancelInternal ()
Runs cancel logic. Assumes that lock_ is held.
void CancelRemoteFragments ()
Status UpdateStatus (const Status &status, const TUniqueId *failed_fragment)
Status WaitForAllBackends ()
Status FinalizeQuery ()
Status FinalizeSuccessfulInsert ()
Moves all temporary staging files to their final destinations.
void InitExecProfile (const TQueryExecRequest &request)
void UpdateAverageProfile (BackendExecState *backend_exec_state)
void ComputeFragmentSummaryStats (BackendExecState *backend_exec_state)
void ReportQuerySummary ()
void UpdateExecSummary (int fragment_idx, int instance_idx, RuntimeProfile *profile)
void PopulatePathPermissionCache (hdfsFS fs, const std::string &path_str, PermissionCache *permissions_cache)
TEST_F (DataStreamTest, UnknownSenderSmallResult)
TEST_F (DataStreamTest, UnknownSenderLargeResult)
TEST_F (DataStreamTest, Cancel)
TEST_F (DataStreamTest, BasicTest)
template<typename T >
void VerifyEquals (const DecimalValue< T > &t1, const DecimalValue< T > &t2)
template<typename T >
void VerifyParse (const string &s, const ColumnType &t, const DecimalValue< T > &expected_val, StringParser::ParseResult expected_result)
template<typename T >
void VerifyToString (const T &decimal, const ColumnType &t, const string &expected)
void StringToAllDecimals (const string &s, const ColumnType &t, int32_t val, StringParser::ParseResult result)
TEST (IntToDecimal, Basic)
TEST (DoubleToDecimal, Basic)
TEST (StringToDecimal, Basic)
TEST (StringToDecimal, LargeDecimals)
TEST (DecimalTest, Overflow)
TEST (DecimalTest, MultiplyScaleOverflow)
ColumnType GetResultType (const ColumnType &t1, const ColumnType &t2, Op op)
template<typename T >
void VerifyFuzzyEquals (const T &actual, const ColumnType &t, double expected, bool overflow)
TEST (DecimalArithmetic, Basic)
TEST (DecimalArithmetic, Divide)
TEST (DecimalArithmetic, DivideLargeScales)
template<typename T >
DecimalValue< T > RandDecimal (int max_precision)
int DoubleCompare (double x, double y)
TEST (DecimalArithmetic, RandTesting)
Decimal4Value ToDecimal4 (const Decimal4Value &v, bool *overflow)
Decimal8Value ToDecimal8 (const Decimal4Value &v, bool *overflow)
Decimal16Value ToDecimal16 (const Decimal4Value &v, bool *overflow)
Decimal4Value ToDecimal4 (const Decimal8Value &v, bool *overflow)
Decimal8Value ToDecimal8 (const Decimal8Value &v, bool *overflow)
Decimal16Value ToDecimal16 (const Decimal8Value &v, bool *overflow)
Decimal4Value ToDecimal4 (const Decimal16Value &v, bool *overflow)
Decimal8Value ToDecimal8 (const Decimal16Value &v, bool *overflow)
Decimal16Value ToDecimal16 (const Decimal16Value &v, bool *overflow)
std::ostream & operator<< (std::ostream &os, const Decimal4Value &d)
std::ostream & operator<< (std::ostream &os, const Decimal8Value &d)
std::ostream & operator<< (std::ostream &os, const Decimal16Value &d)
std::size_t hash_value (const Decimal4Value &v)
This function must be called 'hash_value' to be picked up by boost.
std::size_t hash_value (const Decimal8Value &v)
std::size_t hash_value (const Decimal16Value &v)
ostream & operator<< (ostream &os, const NullIndicatorOffset &null_indicator)
std::ostream & operator<< (std::ostream &os, const NullIndicatorOffset &null_indicator)
TEST_F (DiskIoMgrTest, SingleWriter)
TEST_F (DiskIoMgrTest, InvalidWrite)
TEST_F (DiskIoMgrTest, SingleWriterCancel)
TEST_F (DiskIoMgrTest, SingleReader)
TEST_F (DiskIoMgrTest, AddScanRangeTest)
TEST_F (DiskIoMgrTest, SyncReadTest)
TEST_F (DiskIoMgrTest, SingleReaderCancel)
TEST_F (DiskIoMgrTest, MemLimits)
TEST_F (DiskIoMgrTest, CachedReads)
TEST_F (DiskIoMgrTest, MultipleReaderWriter)
TEST_F (DiskIoMgrTest, MultipleReader)
TEST_F (DiskIoMgrTest, StressTest)
TEST_F (DiskIoMgrTest, Buffers)
TEST (FreePoolTest, Basic)
TEST (FreePoolTest, Loop)
TEST (FreePoolTest, ReAlloc)
void ValidateNameNode (const string &path, const string &expected_namenode, const string &expected_error)
TEST (HdfsFsCacheTest, Basic)
TEST (MemPoolTest, Basic)
TEST (MemPoolTest, Offsets)
TEST (MemPoolTest, Keep)
TEST (MemPoolTest, ReturnPartial)
TEST (MemPoolTest, Limits)
TEST (MemTestTest, SingleTrackerNoLimit)
TEST (MemTestTest, SingleTrackerWithLimit)
TEST (MemTestTest, ConsumptionMetric)
TEST (MemTestTest, TrackerHierarchy)
TEST (MemTestTest, GcFunctions)
TEST (MultiPrecisionIntTest, Conversion)
TEST (MultiPrecisionIntTest, HighLowBits)
TEST (MultiPrecisionIntTest, Example)
template<typename T >
T area_of_a_circle (T r)
TEST (MultiPrecisionFloatTest, Example)
ostream & operator<< (ostream &os, const int128_t &val)
int256_t ConvertToInt256 (const int128_t &x)
int128_t ConvertToInt128 (int256_t x, int128_t max_value, bool *overflow)
int128_t abs (const int128_t &x)
uint64_t HighBits (int128_t x)
Get the high and low bits of an int128_t.
uint64_t LowBits (int128_t x)
std::ostream & operator<< (std::ostream &os, const int128_t &val)
Prints v in base 10.
TEST (ParallelExecutorTest, Basic)
TEST_F (RawValueTest, Compare)
TEST_F (RawValueTest, TypeChar)
void ValidateString (const string &std_str, const StringBuffer &str)
TEST (StringBufferTest, Basic)
StringValue FromStdString (const string &str)
TEST (StringValueTest, TestCompare)
ostream & operator<< (ostream &os, const StringValue &string_value)
std::size_t hash_value (const StringValue &v)
This function must be called 'hash_value' to be picked up by boost.
std::ostream & operator<< (std::ostream &os, const StringValue &string_value)
static int StringCompare (const char *s1, int n1, const char *s2, int n2, int len)
TEST (ThreadResourceMgr, BasicTest)
void ValidateTimestamp (TimestampValue &tv, string &fmt, string &val, string &fmt_val, int year, int month, int day, int hours, int mins, int secs, int frac)
void TestTimestampTokens (vector< TimestampToken > *toks, int year, int month, int day, int hours, int mins, int secs, int frac)
TEST (TimestampTest, Basic)
ostream & operator<< (ostream &os, const TimestampValue &timestamp_value)
std::size_t hash_value (const TimestampValue &v)
This function must be called 'hash_value' to be picked up by boost.
std::ostream & operator<< (std::ostream &os, const TimestampValue &timestamp_value)
PrimitiveType ThriftToType (TPrimitiveType::type ttype)
TPrimitiveType::type ToThrift (PrimitiveType ptype)
string TypeToString (PrimitiveType t)
string TypeToOdbcString (PrimitiveType t)
ostream & operator<< (ostream &os, const ColumnType &type)
std::ostream & operator<< (std::ostream &os, const ColumnType &type)
static bool ParsePoolTopicKey (const string &topic_key, string *pool_name, string *backend_id)
static string MakePoolTopicKey (const string &pool_name, const string &backend_id)
static string DebugPoolStats (const string &pool_name, const TPoolStats *total_stats, const TPoolStats *local_stats)
template<typename T >
void SetQueryOption (TImpalaQueryOptions::type opt, const T &opt_val, TExecuteStatementReq *exec_stmt_req)
void InitFeSupport ()
void TColumnValueToHS2TColumn (const TColumnValue &col_val, const TColumnType &type, uint32_t row_idx, apache::hive::service::cli::thrift::TColumn *column)
For V6->
void ExprValueToHS2TColumn (const void *value, const TColumnType &type, uint32_t row_idx, apache::hive::service::cli::thrift::TColumn *column)
For V6->
void TColumnValueToHS2TColumnValue (const TColumnValue &col_val, const TColumnType &type, apache::hive::service::cli::thrift::TColumnValue *hs2_col_val)
For V1->V5.
void ExprValueToHS2TColumnValue (const void *value, const TColumnType &type, apache::hive::service::cli::thrift::TColumnValue *hs2_col_val)
For V1->V5.
void StitchNulls (uint32_t num_rows_before, uint32_t num_rows_added, uint32_t start_idx, const std::string &from, std::string *to)
void PrintTColumnValue (const apache::hive::service::cli::thrift::TColumnValue &colval, std::stringstream *out)
static int64_t ByteSize (const thrift::TColumnValue &val)
static int64_t ByteSize (const thrift::TRow &row)
static uint32_t TColumnByteSize (const thrift::TColumn &col, uint32_t start_idx, uint32_t end_idx)
static TOperationState::type QueryStateToTOperationState (const beeswax::QueryState::type &query_state)
TOperationState::type QueryStateToTOperationState (const QueryState::type &query_state)
Status CreateImpalaServer (ExecEnv *exec_env, int beeswax_port, int hs2_port, int be_port, ThriftServer **beeswax_server, ThriftServer **hs2_server, ThriftServer **be_server, ImpalaServer **impala_server)
void TQueryOptionsToMap (const TQueryOptions &query_options, std::map< std::string, std::string > *configuration)
Converts a TQueryOptions struct into a map of key, value pairs.
Status SetQueryOption (const std::string &key, const std::string &value, TQueryOptions *query_options)
Status ParseQueryOptions (const std::string &options, TQueryOptions *query_options)
TEST_F (SimpleSchedulerTest, LocalMatches)
TEST_F (SimpleSchedulerTest, HostnameTest)
TEST_F (SimpleSchedulerTest, NonLocalHost)
static const string LOCAL_ASSIGNMENTS_KEY ("simple-scheduler.local-assignments.total")
static const string ASSIGNMENTS_KEY ("simple-scheduler.assignments.total")
static const string SCHEDULER_INIT_KEY ("simple-scheduler.initialized")
static const string NUM_BACKENDS_KEY ("simple-scheduler.num-backends")
static const string DEFAULT_USER ("default")
static const string ERROR_USER_TO_POOL_MAPPING_NOT_FOUND ("No mapping found for request from user '$0' with requested pool '$1'")
static const string ERROR_USER_NOT_ALLOWED_IN_POOL ("Request from user '$0' with ""requested pool '$1' denied access to assigned pool '$2'")
static const string ERROR_USER_NOT_SPECIFIED ("User must be specified because ""-require_username=true.")
bool TBackendDescriptorComparator (const TBackendDescriptor &a, const TBackendDescriptor &b)
Status WaitForCV (unique_lock< mutex > *lock, condition_variable *cv)
TEST_F (StateStore2Test, TestRegistration)
TEST_F (StateStore2Test, TestReceiveUpdates)
TEST (StatestoreTest, SmokeTest)
static TSlotDescriptor MakeSlotDescriptor (int id, int parent_id, const ColumnType &type, int slot_idx, int byte_offset)
static TTupleDescriptor MakeTupleDescriptor (int id, int byte_size, int num_null_bytes)
void TestFunction (int batch_size, void *d)
TEST (BenchmarkTest, Basic)
TEST (BitUtil, Ceil)
TEST (BitUtil, Popcount)
TEST (BitUtil, TrailingBits)
TEST (BitUtil, ByteSwap)
TEST (BitUtil, Log2)
TEST (BitUtil, RoundUpToPowerOf2)
TEST (BitUtil, RoundDownToPowerOf2)
TEST (BitUtil, RoundUpDown)
TEST (BlockingQueueTest, TestBasic)
TEST (BlockingQueueTest, TestGetFromShutdownQueue)
TEST (BlockingQueueTest, TestMultipleThreads)
std::size_t hash_value (const TNetworkAddress &host_port)
template<typename K , typename V >
V * FindOrInsert (std::map< K, V > *m, const K &key, const V &default_val)
template<typename K , typename V >
V * FindOrInsert (boost::unordered_map< K, V > *m, const K &key, const V &default_val)
template<typename K , typename V >
const V & FindWithDefault (const std::map< K, V > &m, const K &key, const V &default_val)
template<typename K , typename V >
const V & FindWithDefault (const boost::unordered_map< K, V > &m, const K &key, const V &default_val)
template<typename K , typename V >
void MergeMapValues (const std::map< K, V > &src, std::map< K, V > *dst)
int64_t ParseCPUFlags (const string &values)
string RecursionStack (int level)
TEST (DebugUtil, StackDump)
TEST (DebugUtil, QueryIdParsing)
TEST (DebugUtil, PreCDH5QueryIdParsing)
THRIFT_ENUM_OUTPUT_FN (TFunctionBinaryType)
THRIFT_ENUM_OUTPUT_FN (TCatalogObjectType)
THRIFT_ENUM_OUTPUT_FN (TDdlType)
THRIFT_ENUM_OUTPUT_FN (TCatalogOpType)
THRIFT_ENUM_OUTPUT_FN (THdfsFileFormat)
THRIFT_ENUM_OUTPUT_FN (THdfsCompression)
THRIFT_ENUM_OUTPUT_FN (TSessionType)
THRIFT_ENUM_OUTPUT_FN (TStmtType)
THRIFT_ENUM_OUTPUT_FN (QueryState)
THRIFT_ENUM_OUTPUT_FN (Encoding)
THRIFT_ENUM_OUTPUT_FN (CompressionCodec)
THRIFT_ENUM_OUTPUT_FN (Type)
THRIFT_ENUM_OUTPUT_FN (TMetricKind)
THRIFT_ENUM_OUTPUT_FN (TUnit)
THRIFT_ENUM_PRINT_FN (TCatalogObjectType)
THRIFT_ENUM_PRINT_FN (TDdlType)
THRIFT_ENUM_PRINT_FN (TCatalogOpType)
THRIFT_ENUM_PRINT_FN (TSessionType)
THRIFT_ENUM_PRINT_FN (TStmtType)
THRIFT_ENUM_PRINT_FN (QueryState)
THRIFT_ENUM_PRINT_FN (Encoding)
THRIFT_ENUM_PRINT_FN (TMetricKind)
THRIFT_ENUM_PRINT_FN (TUnit)
ostream & operator<< (ostream &os, const TUniqueId &id)
string PrintId (const TUniqueId &id, const string &separator)
string PrintAsHex (const char *bytes, int64_t len)
bool ParseId (const string &s, TUniqueId *id)
string PrintPlanNodeType (const TPlanNodeType::type &type)
string PrintTuple (const Tuple *t, const TupleDescriptor &d)
string PrintRow (TupleRow *row, const RowDescriptor &d)
string PrintBatch (RowBatch *batch)
string PrintPath (const vector< int > &path)
string GetBuildVersion (bool compact)
string GetVersionString (bool compact=false)
Returns "<program short name> version <GetBuildVersion(compact)>".
string GetStackTrace ()
std::ostream & operator<< (std::ostream &os, const TFunctionBinaryType::type &op)
std::ostream & operator<< (std::ostream &os, const TUniqueId &id)
std::ostream & operator<< (std::ostream &os, const THdfsFileFormat::type &type)
std::ostream & operator<< (std::ostream &os, const THdfsCompression::type &type)
std::ostream & operator<< (std::ostream &os, const TStmtType::type &type)
std::ostream & operator<< (std::ostream &os, const TUnit::type &type)
std::ostream & operator<< (std::ostream &os, const TMetricKind::type &type)
std::ostream & operator<< (std::ostream &os, const beeswax::QueryState::type &type)
std::ostream & operator<< (std::ostream &os, const parquet::Encoding::type &type)
std::ostream & operator<< (std::ostream &os, const parquet::CompressionCodec::type &type)
std::ostream & operator<< (std::ostream &os, const parquet::Type::type &type)
std::string PrintId (const TUniqueId &id, const std::string &separator=":")
std::string PrintTCatalogObjectType (const TCatalogObjectType::type &type)
std::string PrintTDdlType (const TDdlType::type &type)
std::string PrintTCatalogOpType (const TCatalogOpType::type &type)
std::string PrintTSessionType (const TSessionType::type &type)
std::string PrintTStmtType (const TStmtType::type &type)
std::string PrintQueryState (const beeswax::QueryState::type &type)
std::string PrintEncoding (const parquet::Encoding::type &type)
std::string PrintTMetricKind (const TMetricKind::type &type)
std::string PrintTUnit (const TUnit::type &type)
std::string PrintPath (const std::vector< int > &path)
bool ParseId (const std::string &s, TUniqueId *id)
TEST_F (DecompressorTest, Default)
TEST_F (DecompressorTest, Snappy)
TEST_F (DecompressorTest, LZ4)
TEST_F (DecompressorTest, Gzip)
TEST_F (DecompressorTest, Deflate)
TEST_F (DecompressorTest, Bzip)
TEST_F (DecompressorTest, SnappyBlocked)
TEST_F (DecompressorTest, Impala1506)
void AddDefaultUrlCallbacks (Webserver *webserver, MemTracker *process_mem_tracker=NULL)
template<typename T >
void ValidateDict (const vector< T > &values, int fixed_buffer_byte_size)
TEST (DictTest, TestStrings)
TEST (DictTest, TestTimestamps)
template<typename T >
void IncrementValue (T *t)
template<>
void IncrementValue (Decimal4Value *t)
template<>
void IncrementValue (Decimal8Value *t)
template<>
void IncrementValue (Decimal16Value *t)
template<typename T >
void TestNumbers (int max_value, int repeat, int value_byte_size)
template<typename T >
void TestNumbers (int value_byte_size)
TEST (DictTest, TestNumbers)
Status DynamicLookup (void *handle, const char *symbol, void **fn_ptr, bool quiet)
Status DynamicOpen (const char *library, void **handle)
void DynamicClose (void *handle)
Closes the handle.
TEST (ErrorMsg, GenericFormatting)
TEST (ErrorMsg, MergeMap)
TEST (ErrorMsg, CountErrors)
TEST (ErrorMsg, AppendError)
TEST (ErrorMsg, PrintMap)
string GetStrErrMsg ()
string GetTablesMissingStatsWarning (const vector< TTableName > &tables_missing_stats)
void PrintErrorMap (ostream *stream, const ErrorLogMap &errors)
string PrintErrorMapToString (const ErrorLogMap &errors)
void MergeErrorMaps (ErrorLogMap *left, const ErrorLogMap &right)
void AppendError (ErrorLogMap *map, const ErrorMsg &e)
size_t ErrorCount (const ErrorLogMap &errors)
std::string GetTablesMissingStatsWarning (const std::vector< TTableName > &tables_missing_stats)
void PrintErrorMap (std::ostream *stream, const ErrorLogMap &errors)
Helper method to print the contents of an ErrorMap to a stream.
HdfsOpThreadPool * CreateHdfsOpThreadPool (const std::string &name, uint32_t num_threads, uint32_t max_queue_length)
Creates a new HdfsOp-processing thread pool.
string GetHdfsErrorMsg (const string &prefix, const string &file)
Status GetFileSize (const hdfsFS &connection, const char *filename, int64_t *filesize)
Return the size, in bytes, of a file from the hdfs connection.
Status GetLastModificationTime (const hdfsFS &connection, const char *filename, time_t *last_mod_time)
bool IsHiddenFile (const string &filename)
Status CopyHdfsFile (const hdfsFS &src_conn, const string &src_path, const hdfsFS &dst_conn, const string &dst_path)
bool IsDfsPath (const char *path)
Returns true iff the path refers to a location on an HDFS filesystem.
bool IsS3APath (const char *path)
Returns true iff the path refers to a location on an S3A filesystem.
std::string GetHdfsErrorMsg (const std::string &prefix, const std::string &file="")
bool IsHiddenFile (const std::string &filename)
Status CopyHdfsFile (const hdfsFS &src_conn, const std::string &src_path, const hdfsFS &dst_conn, const std::string &dst_path)
Copy the file at 'src_path' from 'src_conn' to 'dst_path' in 'dst_conn'.
TEST (InternalQueue, TestBasic)
TEST (InternalQueue, TestRemove)
void ProducerThread (InternalQueue< IntNode > *queue, int num_inserts, vector< IntNode > *nodes, AtomicInt< int32_t > *counter, bool *failed)
void ConsumerThread (InternalQueue< IntNode > *queue, int num_consumes, int delta, vector< int > *results, bool *failed)
TEST (InternalQueue, TestClear)
TEST (InternalQueue, TestSingleProducerSingleConsumer)
TEST (InternalQueue, TestMultiProducerMultiConsumer)
template<typename T >
ToJsonValue (const T &value, const TUnit::type unit, rapidjson::Document *document, rapidjson::Value *out_val)
template<>
void ToJsonValue< std::string > (const std::string &value, const TUnit::type unit, rapidjson::Document *document, rapidjson::Value *out_val)
void InitJvmLoggingSupport ()
TLogLevel::type FlagToTLogLevel (int flag)
int64_t ParseMemString (const char *val, size_t len)
Status RegisterMemoryMetrics (MetricGroup *metrics, bool register_jvm_metrics)
template<typename M , typename T >
void AssertValue (M *metric, const T &value, const string &human_readable)
TEST (MetricsTest, CounterMetrics)
TEST (MetricsTest, GaugeMetrics)
TEST (MetricsTest, PropertyMetrics)
TEST (MetricsTest, NonFiniteValues)
TEST (MetricsTest, SetMetrics)
TEST (MetricsTest, StatsMetrics)
TEST (MetricsTest, MemMetric)
TEST (MetricsTest, JvmMetrics)
void AssertJson (const Value &val, const string &name, const string &value, const string &description, const string &kind="", const string &units="")
TEST (MetricsJsonTest, Counters)
TEST (MetricsJsonTest, Gauges)
TEST (MetricsJsonTest, Properties)
TEST (MetricsJsonTest, SetMetrics)
TEST (MetricsJsonTest, StatsMetrics)
TEST (MetricsJsonTest, UnitsAndDescription)
TEST (MetricGroupTest, JsonTest)
template<>
void ToJsonValue< string > (const string &value, const TUnit::type unit, Document *document, Value *out_val)
static const string LOCALHOST ("127.0.0.1")
Status GetHostname (string *hostname)
Status HostnameToIpAddrs (const string &name, vector< string > *addresses)
bool FindFirstNonLocalhost (const vector< string > &addresses, string *addr)
TNetworkAddress MakeNetworkAddress (const string &hostname, int port)
TNetworkAddress MakeNetworkAddress (const string &address)
bool IsWildcardAddress (const string &ipaddress)
string TNetworkAddressToString (const TNetworkAddress &address)
Utility method to print address as address:port.
ostream & operator<< (ostream &out, const TNetworkAddress &hostport)
Status HostnameToIpAddrs (const std::string &name, std::vector< std::string > *addresses)
bool FindFirstNonLocalhost (const std::vector< std::string > &addresses, std::string *addr)
Status GetHostname (std::string *hostname)
TNetworkAddress MakeNetworkAddress (const std::string &hostname, int port)
Utility method because Thrift does not supply useful constructors.
TNetworkAddress MakeNetworkAddress (const std::string &address)
bool IsWildcardAddress (const std::string &ipaddress)
Returns true if the ip address parameter is the wildcard interface (0.0.0.0)
std::ostream & operator<< (std::ostream &out, const TNetworkAddress &hostport)
Prints a hostport as ipaddress:port.
Status GetThreadStats (int64_t tid, ThreadStats *stats)
bool RunShellProcess (const std::string &cmd, std::string *msg)
TEST (ParseMemSpecs, Basic)
TEST (PerfCounterTest, Basic)
TEST (CpuInfoTest, Basic)
TEST (DiskInfoTest, Basic)
static int sys_perf_event_open (struct perf_event_attr *attr, pid_t pid, int cpu, int group_fd, unsigned long flags)
static bool InitEventAttr (perf_event_attr *attr, PerfCounters::Counter counter)
static string GetCounterName (PerfCounters::Counter counter)
DEFINE_int32 (periodic_counter_update_period_ms, 500,"Period to update rate counters and"" sampling counters in ms")
void AddPprofUrlCallbacks (Webserver *webserver)
Adds set of path handlers to support pprof profiling of a remote server.
TEST (PrettyPrinterTest, Unit)
TEST (PrettyPrinterTest, UnitPerSecond)
TEST (PrettyPrinterTest, CpuTicks)
TEST (PrettyPrinterTest, Bytes)
TEST (PrettyPrinterTest, BytesPerSecond)
TEST (PrettyPrinterTest, Seconds)
TEST (PrettyPrinterTest, NanoSeconds)
TEST (PrettyPrinterTest, DoubleValue)
TEST (PrettyPrinterTest, StringList)
TEST (MemInfo, Basic)
TEST (ProcessStateInfo, Basic)
void RunThread (Promise< int64_t > *promise)
TEST (PromiseTest, BasicTest)
TEST (PromiseTest, TimeoutTest)
TEST (PromiseDeathTest, RepeatedSetTest)
TEST (ParserTest, FileNotFound)
TEST (ParserTest, EmptyFile)
TEST (ParserTest, DescriptionPropertyIgnored)
TEST (ParserTest, InvalidJson)
TEST (ParserTest, BadVersion)
TEST (ParserTest, BadRegex)
TEST (ParserTest, BadCaseSensitivtyValue)
TEST (ParserTest, RuleNumberInErrorMessage)
unsigned int RandSeed ()
void RandomlyFillString (char *string, const int length)
Randomly fills the contents of 'string' up to the given length.
void AssertErrorMessageContains (const std::string &message, const char *expected)
void AssertRedactedEquals (const char *message, const char *expected)
void AssertUnredacted (const char *message)
void * MultiThreadWorkload (void *unused)
TEST (RedactorTest, NoTrigger)
TEST (RedactorTest, Trigger)
TEST (RedactorTest, MultiTrigger)
TEST (RedactorTest, CaseSensitivityProperty)
TEST (RedactorTest, SingleTriggerMultiRule)
TEST (RedactorTest, RuleOrder)
TEST (RedactorTest, InputSize)
TEST (RedactorTest, ChangeInputSize)
TEST (RedactorTest, MultiThreaded)
TEST (RedactorTest, Unconfigured)
string NameOfTypeOfJsonValue (const Value &value)
string SetRedactionRulesFromFile (const string &rules_file_path)
void Redact (string *value, bool *changed)
std::string SetRedactionRulesFromFile (const std::string &rules_file_path)
void Redact (std::string *string, bool *changed=NULL)
std::string RedactCopy (const std::string &original)
Utility function to redacted a string without modifying the original.
TEST (BitArray, TestBool)
void TestBitArrayValues (int bit_width, int num_vals)
TEST (BitArray, TestValues)
TEST (BitArray, TestMixed)
void ValidateRle (const vector< int > &values, int bit_width, uint8_t *expected_encoding, int expected_len)
TEST (Rle, SpecificSequences)
void TestRleValues (int bit_width, int num_vals, int value=-1)
TEST (Rle, TestValues)
TEST (Rle, BitWidthZeroRepeated)
TEST (Rle, BitWidthZeroLiteral)
TEST (BitRle, Flush)
TEST (BitRle, Random)
TEST (BitRle, RepeatedPattern)
TEST (BitRle, Overflow)
TEST (CountersTest, Basic)
void ValidateCounter (RuntimeProfile *profile, const string &name, int64_t value)
TEST (CountersTest, MergeAndUpdate)
TEST (CountersTest, DerivedCounters)
TEST (CountersTest, AverageSetCounters)
TEST (CountersTest, InfoStringTest)
TEST (CountersTest, RateCounters)
TEST (CountersTest, BucketCounters)
TEST (CountersTest, EventSequences)
void ValidateSampler (const StreamingSampler< int, 10 > &sampler, int expected_num, int expected_period, int expected_delta)
TEST (CountersTest, StreamingSampler)
ADD_COUNTER_IMPL (AddCounter, Counter)
ADD_COUNTER_IMPL (AddHighWaterMarkCounter, HighWaterMarkCounter)
static SSE_ALWAYS_INLINE __m128i SSE4_cmpestrm (__m128i str1, int len1, __m128i str2, int len2, const int mode)
static SSE_ALWAYS_INLINE int SSE4_cmpestri (__m128i str1, int len1, __m128i str2, int len2, const int mode)
static uint32_t SSE4_crc32_u8 (uint32_t crc, uint8_t v)
static uint32_t SSE4_crc32_u32 (uint32_t crc, uint32_t v)
static int64_t POPCNT_popcnt_u64 (uint64_t a)
template<typename T >
void TestIntValue (const char *s, T exp_val, StringParser::ParseResult exp_result)
template<typename T >
void TestIntValue (const char *s, int base, T exp_val, StringParser::ParseResult exp_result)
void TestBoolValue (const char *s, bool exp_val, StringParser::ParseResult exp_result)
template<typename T >
void TestFloatValue (const string &s, StringParser::ParseResult exp_result)
template<typename T >
void TestFloatValueIsNan (const string &s, StringParser::ParseResult exp_result)
void TestAllFloatVariants (const string &s, StringParser::ParseResult exp_result)
template<typename T >
void TestFloatBruteForce ()
TEST (StringToInt, Basic)
TEST (StringToInt, InvalidLeadingTrailing)
TEST (StringToInt, Limit)
TEST (StringToInt, Overflow)
TEST (StringToInt, Int8_Exhaustive)
TEST (StringToIntWithBase, Basic)
TEST (StringToIntWithBase, NonNumericCharacters)
TEST (StringToIntWithBase, Limit)
TEST (StringToIntWithBase, Overflow)
TEST (StringToIntWithBase, Int8_Exhaustive)
TEST (StringToFloat, Basic)
TEST (StringToFloat, InvalidLeadingTrailing)
TEST (StringToFloat, BruteForce)
TEST (StringToBool, Basic)
std::string PrintExecSummary (const TExecSummary &exec_summary)
Print the exec summary as a formatted table.
void TestDemangling (const string &mangled, const string &expected_demangled)
void TestDemanglingNameOnly (const string &mangled, const string &expected_demangled)
void TestMangling (const string &name, bool var_args, const vector< ColumnType > args, ColumnType *ret_arg_type, const string &expected_mangled, const string &expected_demangled)
void TestManglingPrepareOrClose (const string &name, const string &expected_mangled, const string &expected_demangled)
TEST (SymbolsUtil, Demangling)
TEST (SymbolsUtil, DemanglingNameOnly)
TEST (SymbolsUtil, Mangling)
TEST (SymbolsUtil, ManglingPrepareOrClose)
void Count (int thread_id, const int &i)
TEST (ThreadPoolTest, BasicTest)
void InitThreading ()
Initialises the threading subsystem. Must be called before a Thread is created.
Status StartThreadInstrumentation (MetricGroup *metrics, Webserver *webserver)
int64_t MonotonicMicros ()
int64_t MonotonicMillis ()
int64_t MonotonicSeconds ()
int64_t UnixMillis ()
void SleepForMs (const int64_t duration_ms)
Sleeps the current thread for at least duration_ms milliseconds.
std::size_t hash_value (const impala::TUniqueId &id)
This function must be called 'hash_value' to be picked up by boost.
template<typename T >
void UUIDToTUniqueId (const boost::uuids::uuid &uuid, T *unique_id)
template<typename F , typename T >
T CastTUniqueId (const F &from)
string GenerateUUIDString ()
generates a 16 byte UUID
TUniqueId GenerateUUID ()
generates a 16 byte UUID
void TestUrl (const string &input, const string &expected_encoded, bool hive_compat)
void TestBase64 (const string &input, const string &expected_encoded)
TEST (UrlCodingTest, Basic)
TEST (UrlCodingTest, HiveExceptions)
TEST (UrlCodingTest, BlankString)
TEST (UrlCodingTest, PathSeparators)
TEST (Base64Test, Basic)
TEST (HtmlEscapingTest, Basic)
static void UrlEncode (const char *in, int in_len, string *out, bool hive_compat)
void UrlEncode (const vector< uint8_t > &in, string *out, bool hive_compat)
void UrlEncode (const string &in, string *out, bool hive_compat)
bool UrlDecode (const string &in, string *out, bool hive_compat)
static void Base64Encode (const char *in, int in_len, stringstream *out)
void Base64Encode (const vector< uint8_t > &in, string *out)
void Base64Encode (const vector< uint8_t > &in, stringstream *out)
void Base64Encode (const string &in, string *out)
void Base64Encode (const string &in, stringstream *out)
bool Base64Decode (const string &in, string *out)
void EscapeForHtml (const string &in, stringstream *out)
void UrlEncode (const std::string &in, std::string *out, bool hive_compat=false)
void UrlEncode (const std::vector< uint8_t > &in, std::string *out, bool hive_compat=false)
bool UrlDecode (const std::string &in, std::string *out, bool hive_compat=false)
void Base64Encode (const std::vector< uint8_t > &in, std::string *out)
void Base64Encode (const std::vector< uint8_t > &in, std::stringstream *out)
void Base64Encode (const std::string &in, std::string *out)
void Base64Encode (const std::string &in, std::stringstream *out)
bool Base64Decode (const std::string &in, std::string *out)
void EscapeForHtml (const std::string &in, std::stringstream *out)
string BuildHeaderString (ResponseCode response, ContentType content_type)
Variables
static mutex llvm_initialization_lock
static bool llvm_initialized = false
const string ERROR_NUM_COLUMNS
const string ERROR_MISMATCHED_COL_SIZES
const string ERROR_INVALID_COL_DATA
const string ERROR_INVALID_TIMESTAMP
const string ERROR_INVALID_DECIMAL
const size_t TIMESTAMP_SIZE = sizeof(int64_t) + sizeof(int32_t)
static const string & ROOT_PARTITION_KEY
const char *(* GetImpalaBuildVersion)()
static const string & ROOT_PARTITION_KEY
const uint8_t PARQUET_VERSION_NUMBER [4] = {'P', 'A', 'R', '1'}
const uint32_t PARQUET_CURRENT_VERSION = 1
const parquet::Type::type IMPALA_TO_PARQUET_TYPES []
const THdfsCompression::type PARQUET_TO_IMPALA_CODEC []
Mapping of Parquet codec enums to Impala enums.
const
parquet::CompressionCodec::type IMPALA_TO_PARQUET_CODEC []
Mapping of Impala codec enums to Parquet enums.
impala::GrowingTest __attribute__
static const StringVal DEFAULT_STRING_CONCAT_DELIM ((uint8_t *)", ", 2)
static const int NUM_PC_BITMAPS = 64
static const int PC_BITMAP_LENGTH = 32
static const float PC_THETA = 0.77351f
static const int NUM_BUCKETS = 100
static const int NUM_SAMPLES_PER_BUCKET = 200
static const int NUM_SAMPLES = NUM_BUCKETS * NUM_SAMPLES_PER_BUCKET
static const int MAX_STRING_SAMPLE_LEN = 10
ImpaladQueryExecutor * executor_
execution state of coordinator fragment
bool disable_codegen_
const string LLAMA_RESTART_SEARCH_STRING = "unknown handle"
static sasl_callback_t GENERAL_CALLBACKS [5]
static vector< sasl_callback_t > KERB_INT_CALLBACKS
static vector< sasl_callback_t > KERB_EXT_CALLBACKS
static vector< sasl_callback_t > LDAP_EXT_CALLBACKS
static const string HOSTNAME_PATTERN = "_HOST"
static const string KERBEROS_MECHANISM = "GSSAPI"
static const string PLAIN_MECHANISM = "PLAIN"
static const string LDAP_URI_PREFIX = "ldap://"
static const string LDAPS_URI_PREFIX = "ldaps://"
static const string IMPALA_AUXPROP_PLUGIN = "impala-auxprop"
static sasl_auxprop_plug_t impala_auxprop_plugin
__thread
ThriftServer::ConnectionContext * __connection_context__
static const StringValue STRINGS []
static const int NUM_STRINGS = sizeof(STRINGS) / sizeof(StringValue)
client __pad0__
client
RuntimeProfile::EventSequence * events
ExecEnv * exec_env_
TUniqueId query_id_
TDescriptorTable desc_tbl_
copied from TQueryExecRequest; constant across all fragments
TQueryCtx query_ctx_
TStmtType::type stmt_type_
copied from TQueryExecRequest, governs when to call ReportQuerySummary
std::vector< BackendExecState * > backend_exec_states_
BackendExecStates owned by obj_pool()
bool needs_finalization_
True if the query needs a post-execution step to tidy up.
TFinalizeParams finalize_params_
Only valid if needs_finalization is true.
boost::mutex wait_lock_
ensures single-threaded execution of Wait(); must not hold lock_ when acquiring this
bool has_called_wait_
ProgressUpdater progress_
Keeps track of number of completed ranges and total scan ranges.
boost::mutex lock_
protects all fields below
Status query_status_
bool returned_all_results_
boost::shared_ptr< MemTracker > query_mem_tracker_
const RowDescriptor * row_desc_
owned by plan root, which resides in runtime_state_'s pool
BackendExecStateMap backend_exec_state_map_
bool execution_completed_
True if execution has completed, false otherwise.
int num_remote_fragements_complete_
Number of remote fragments that have completed.
boost::condition_variable backend_completion_cv_
int num_remaining_backends_
PartitionStatusMap per_partition_status_
FileMoveMap files_to_move_
boost::scoped_ptr< ObjectPool > obj_pool_
Object pool owned by the coordinator. Any executor will have its own pool.
SpinLock exec_summary_lock_
Execution summary for this query.
TExecSummary exec_summary_
boost::unordered_map
< TPlanNodeId, int > plan_node_id_to_summary_map_
A mapping of plan node ids to index into exec_summary_.nodes.
boost::scoped_ptr< RuntimeProfile > query_profile_
Aggregate counters for the entire query.
RuntimeProfile::EventSequence * query_events_
Event timeline for this query. Unowned.
std::vector
< PerFragmentProfileData > fragment_profiles_
FragmentInstanceCounters coordinator_counters_
Throughput counters for the coordinator fragment.
boost::unordered_set
< TNetworkAddress > unique_hosts_
The set of hosts that the query will run on. Populated in Exec.
RuntimeProfile::Counter * finalization_timer_
Total time spent in finalization (typically 0 except for INSERT into hdfs tables)
static const double MAX_ERROR = 0.0001
const string REQUEST_POOL_MEM_TRACKER_LABEL_FORMAT = "RequestPool=$0"
static const uint32_t ONE_BILLION = 1000000000
const int BLOCKS_REQUIRED_FOR_MERGE = 3
const string PIN_FAILED_ERROR_MSG
const string TMP_SUB_DIR_NAME = "impala-scratch"
const uint64_t AVAILABLE_SPACE_THRESHOLD_MB = 1024
const char TOPIC_KEY_DELIMITER = '!'
const string LOCAL_ADMITTED_METRIC_KEY_FORMAT
const string LOCAL_QUEUED_METRIC_KEY_FORMAT
const string LOCAL_DEQUEUED_METRIC_KEY_FORMAT
const string LOCAL_REJECTED_METRIC_KEY_FORMAT
const string LOCAL_TIMED_OUT_METRIC_KEY_FORMAT
const string LOCAL_COMPLETED_METRIC_KEY_FORMAT
const string LOCAL_TIME_IN_QUEUE_METRIC_KEY_FORMAT
const string CLUSTER_NUM_RUNNING_METRIC_KEY_FORMAT
const string CLUSTER_IN_QUEUE_METRIC_KEY_FORMAT
const string CLUSTER_MEM_USAGE_METRIC_KEY_FORMAT
const string CLUSTER_MEM_ESTIMATE_METRIC_KEY_FORMAT
const string LOCAL_NUM_RUNNING_METRIC_KEY_FORMAT
const string LOCAL_IN_QUEUE_METRIC_KEY_FORMAT
const string LOCAL_MEM_USAGE_METRIC_KEY_FORMAT
const string LOCAL_MEM_ESTIMATE_METRIC_KEY_FORMAT
const string QUERY_EVENT_SUBMIT_FOR_ADMISSION = "Submit for admission"
const string QUERY_EVENT_COMPLETED_ADMISSION = "Completed admission"
const string PROFILE_INFO_KEY_ADMISSION_RESULT = "Admission result"
const string PROFILE_INFO_VAL_ADMIT_IMMEDIATELY = "Admitted immediately"
const string PROFILE_INFO_VAL_ADMIT_QUEUED = "Admitted (queued)"
const string PROFILE_INFO_VAL_REJECTED = "Rejected"
const string PROFILE_INFO_VAL_TIME_OUT = "Timed out (queued)"
const string STATUS_REJECTED = "Rejected query from pool $0 : $1"
const string REASON_DISABLED_MEM_LIMIT = "disabled by mem limit set to 0"
const string REASON_DISABLED_REQUESTS_LIMIT = "disabled by requests limit set to 0"
const string REASON_QUEUE_FULL = "queue full, limit=$0, num_queued=$1"
const string REASON_REQ_OVER_MEM_LIMIT
const string QUEUED_NUM_RUNNING = "number of running queries $0 is over limit $1"
const string QUEUED_MEM_LIMIT
const string QUEUED_QUEUE_NOT_EMPTY
const string STATUS_TIME_OUT
static JNINativeMethod native_methods []
const string IMPALA_RESULT_CACHING_OPT = "impala.resultset.cache.size"
const string PROFILE_LOG_FILE_PREFIX = "impala_profile_log_1.1-"
const string AUDIT_EVENT_LOG_FILE_PREFIX = "impala_audit_event_log_1.0-"
const string LINEAGE_LOG_FILE_PREFIX = "impala_lineage_log_1.0-"
const uint32_t MAX_CANCELLATION_QUEUE_SIZE = 65536
const string BEESWAX_SERVER_NAME = "beeswax-frontend"
const string HS2_SERVER_NAME = "hiveserver2-frontend"
const int MAX_NM_MISSED_HEARTBEATS = 5
static const string PER_HOST_MEM_KEY = "Estimated Per-Host Mem"
static const string PER_HOST_VCORES_KEY = "Estimated Per-Host VCores"
static const string TABLES_MISSING_STATS_KEY = "Tables Missing Stats"
const int64_t DEFAULT_REQUEST_TIMEOUT_MS = 5 * 60 * 1000
static const string BACKENDS_WEB_PAGE = "/backends"
static const string BACKENDS_TEMPLATE = "backends.tmpl"
const string STATESTORE_ID = "STATESTORE"
const string CALLBACK_METRIC_PATTERN = "statestore-subscriber.topic-$0.processing-time-s"
const int32_t SLEEP_INTERVAL_MS = 5000
const std::string IMPALA_CGROUP_SUFFIX = "_impala"
const int32_t CPU_DEFAULT_WEIGHT = 1024
struct {
string impala::name
int64_t impala::flag
} flag_mappings []
static const long num_flags = sizeof(flag_mappings) / sizeof(flag_mappings[0])
const int VALIDATE_INTERVAL = 10000
static Rules * g_rules
const int MAX_WIDTH = 32
static const string THREAD_TOTAL_TIME = "TotalWallClockTime"
static const string THREAD_USER_TIME = "UserTime"
static const string THREAD_SYS_TIME = "SysTime"
static const string THREAD_VOLUNTARY_CONTEXT_SWITCHES = "VoluntaryContextSwitches"
static const string THREAD_INVOLUNTARY_CONTEXT_SWITCHES = "InvoluntaryContextSwitches"
static const string ROOT_COUNTER = ""
string space [] = {"", " ", "\t\t\t", "\n\n\n", "\v\v\v", "\f\f\f", "\r\r\r"}
int space_len = 7
const int NUM_THREADS = 5
int thread_counters [NUM_THREADS]
mutex thread_mutexes [NUM_THREADS]
static const string THREADS_WEB_PAGE = "/threadz"
static const string THREADS_TEMPLATE = "threadz.tmpl"
shared_ptr< ThreadMgr > thread_manager
static function< bool(char)> HiveShouldEscape = is_any_of("\"#%\\*/:=?\u00FF")
static function< bool(char)> ShouldNotEscape = is_any_of("-_.~")
const StringSearch
UrlParser::protocol_search & protocol
const StringSearch
UrlParser::at_search & at
const StringSearch
UrlParser::slash_search & slash
const StringSearch
UrlParser::colon_search & colon
const StringSearch
UrlParser::question_search & question
const StringSearch
UrlParser::hash_search & hash
Detailed Description
This file contains type definitions that are used throughout the code base.
Utilities for collecting timings.
We need zlib.h here to declare stream_ below.
Utility methods to process per-query options.
Finally include the boost library.
This file contains common elements between the parquet Writer and Scanner.
needed for scoped_ptr to work on ObjectPool
file-version-header ::= Byte[4] {'S', 'E', 'Q', 6}
file-is-compressed ::= Byte[1]
IR modules don't use these methods, and can't see the google namespace used in GetFullLogFilename()'s prototype.
org.apache.hadoop.hive.ql.io.RCFile is the original RCFile implementation and should be viewed as the canonical definition of this format. If anything is unclear in this file you should consult the code in org.apache.hadoop.hive.ql.io.RCFile. The following is a pseudo-BNF grammar for RCFile. Comments are prefixed with dashes: rcfile ::= <file-header> <rcfile-rowgroup>+ file-header ::= <file-version-header> <file-key-class-name> (only exists if version is seq6) <file-value-class-name> (only exists if version is seq6) <file-is-compressed> <file-is-block-compressed> (only exists if version is seq6) [<file-compression-codec-class>] <file-header-metadata> <file-sync-field> – The normative RCFile implementation included with Hive is actually – based on a modified version of Hadoop's SequenceFile code. Some – things which should have been modified were not, including the code – that writes out the file version header. Consequently, RCFile and – SequenceFile originally shared the same version header. A newer – release has created a unique version string. file-version-header ::= Byte[4] {'S', 'E', 'Q', 6} | Byte[4] {'R', 'C', 'F', 1} – The name of the Java class responsible for reading the key buffer – component of the rowgroup. file-key-class-name ::= Text {"org.apache.hadoop.hive.ql.io.RCFile$KeyBuffer"} – The name of the Java class responsible for reading the value buffer – component of the rowgroup. file-value-class-name ::= Text {"org.apache.hadoop.hive.ql.io.RCFile$ValueBuffer"} – Boolean variable indicating whether or not the file uses compression – for the key and column buffer sections.– A boolean field indicating whether or not the file is block compressed. – This field is always false. According to comments in the original – RCFile implementation this field was retained for backwards – compatability with the SequenceFile format. file-is-block-compressed ::= Byte[1] {false} – The Java class name of the compression codec iff <file-is-compressed> – is true. The named class must implement – org.apache.hadoop.io.compress.CompressionCodec. – The expected value is org.apache.hadoop.io.compress.GzipCodec. file-compression-codec-class ::= Text – A collection of key-value pairs defining metadata values for the – file. The Map is serialized using standard JDK serialization, i.e. – an Int corresponding to the number of key-value pairs, followed by – Text key and value pairs. The following metadata properties are
– mandatory for all RCFiles:
– hive.io.rcfile.column.number: the number of columns in the RCFile file-header-metadata ::= Map<Text, Text> – A 16 byte marker that is generated by the writer. This marker appears – at regular intervals at the beginning of rowgroup-headers, and is – intended to enable readers to skip over corrupted rowgroups. file-sync-hash ::= Byte[16] – Each row group is split into three sections: a header, a set of – key buffers, and a set of column buffers. The header section includes – an optional sync hash, information about the size of the row group, and – the total number of rows in the row group. Each key buffer – consists of run-length encoding data which is used to decode – the length and offsets of individual fields in the corresponding column – buffer. rcfile-rowgroup ::= <rowgroup-header> <rowgroup-key-data> <rowgroup-column-buffers> rowgroup-header ::= [<rowgroup-sync-marker>, <rowgroup-sync-hash>] <rowgroup-record-length> <rowgroup-key-length> <rowgroup-compressed-key-length> – rowgroup-key-data is compressed if the column data is compressed. rowgroup-key-data ::= <rowgroup-num-rows> <rowgroup-key-buffers> – An integer (always -1) signaling the beginning of a sync-hash – field. rowgroup-sync-marker ::= Int – A 16 byte sync field. This must match the <file-sync-hash> value read – in the file header. rowgroup-sync-hash ::= Byte[16] – The record-length is the sum of the number of bytes used to store – the key and column parts, i.e. it is the total length of the current – rowgroup. rowgroup-record-length ::= Int – Total length in bytes of the rowgroup's key sections. rowgroup-key-length ::= Int – Total compressed length in bytes of the rowgroup's key sections. rowgroup-compressed-key-length ::= Int – Number of rows in the current rowgroup. rowgroup-num-rows ::= VInt – One or more column key buffers corresponding to each column – in the RCFile. rowgroup-key-buffers ::= <rowgroup-key-buffer>+ – Data in each column buffer is stored using a run-length – encoding scheme that is intended to reduce the cost of – repeated column field values. This mechanism is described – in more detail in the following entries. rowgroup-key-buffer ::= <column-buffer-length> <column-buffer-uncompressed-length> <column-key-buffer-length> <column-key-buffer> – The serialized length on disk of the corresponding column buffer. column-buffer-length ::= VInt – The uncompressed length of the corresponding column buffer. This – is equivalent to column-buffer-length if the RCFile is not compressed. column-buffer-uncompressed-length ::= VInt – The length in bytes of the current column key buffer column-key-buffer-length ::= VInt – The column-key-buffer contains a sequence of serialized VInt values – corresponding to the byte lengths of the serialized column fields – in the corresponding rowgroup-column-buffer. For example, consider – an integer column that contains the consecutive values 1, 2, 3, 44. – The RCFile format stores these values as strings in the column buffer, – e.g. "12344". The length of each column field is recorded in – the column-key-buffer as a sequence of VInts: 1,1,1,2. However, – if the same length occurs repeatedly, then we replace repeated – run lengths with the complement (i.e. negative) of the number of – repetitions, so 1,1,1,2 becomes 1,~2,2. column-key-buffer ::= Byte[column-key-buffer-length] rowgroup-column-buffers ::= <rowgroup-value-buffer>+ – RCFile stores all column data as strings regardless of the – underlying column type. The strings are neither length-prefixed or – null-terminated, and decoding them into individual fields requires – the use of the run-length information contained in the corresponding – column-key-buffer. rowgroup-column-buffer ::= Byte[column-buffer-length] Byte ::= An eight-bit byte VInt ::= Variable length integer. The high-order bit of each byte indicates whether more bytes remain to be read. The low-order seven bits are appended as increasingly more significant bits in the resulting integer value. Int ::= A four-byte integer in big-endian format. Text ::= VInt, Chars (Length prefixed UTF-8 characters) The above file format is read in chunks. The "key" buffer is read. The "keys" are really the lengths of the column data blocks and the lengths of the values within those blocks. Using this information the column "buffers" (data) that are needed by the query are read into a single buffer. Column data that is not used by the query is skipped and not read from the file. The key data and the column data may be compressed. The key data is compressed in a single block while the column data is compressed separately by column.
This scanner parses Sequence file located in HDFS, and writes the content as tuples in the Impala in-memory representation of data, e.g. (tuples, rows, row batches). TODO: Make the various sequence file formats behave more similarly. They should all have a structure similar to block compressed operating in batches rather than row at a time. org.apache.hadoop.io.SequenceFile is the original SequenceFile implementation and should be viewed as the canonical definition of this format. If anything is unclear in this file you should consult the code in org.apache.hadoop.io.SequenceFile. The following is a pseudo-BNF grammar for SequenceFile. Comments are prefixed with dashes: seqfile ::= <file-header> <record-block>+ record-block ::= <record>+ <file-sync-hash> file-header ::= <file-version-header> <file-key-class-name> <file-value-class-name> <file-is-compressed> <file-is-block-compressed> [<file-compression-codec-class>] <file-header-metadata> <file-sync-field>– The name of the Java class responsible for reading the key buffer file-key-class-name ::= Text {"org.apache.hadoop.io.BytesWritable"} – The name of the Java class responsible for reading the value buffer – We don't care what this is. file-value-class-name ::= – Boolean variable indicating whether or not the file uses compression – for key/values in this file file-is-compressed ::= Byte[1] – A boolean field indicating whether or not the file is block compressed. file-is-block-compressed ::= Byte[1] {false} – The Java class name of the compression codec iff <file-is-compressed> – is true. The named class must implement – org.apache.hadoop.io.compress.CompressionCodec. – The expected value is org.apache.hadoop.io.compress.GzipCodec. file-compression-codec-class ::= Text – A collection of key-value pairs defining metadata values for the – file. The Map is serialized using standard JDK serialization, i.e. – an Int corresponding to the number of key-value pairs, followed by – Text key and value pairs. file-header-metadata ::= Map<Text, Text> – A 16 byte marker that is generated by the writer. This marker appears – at regular intervals at the beginning of records or record blocks – intended to enable readers to skip to a random part of the file – the sync hash is preceeded by a length of -1, refered to as the sync marker file-sync-hash ::= Byte[16] – Records are all of one type as determined by the compression bits in the header record ::= <uncompressed-record> | <block-compressed-record> | <record-compressed-record> uncompressed-record ::= <record-length> <key-length> <key>
record-compressed-record ::= <record-length> <key-length> <key> <compressed-value> block-compressed-record ::= <file-sync-field> <key-lengths-block-size> <key-lengths-block> <keys-block-size> <keys-block> <value-lengths-block-size> <value-lengths-block> <values-block-size> <values-block> record-length := Int key-length := Int keys-lengths-block-size> := Int value-lengths-block-size> := Int keys-block :: = Byte[keys-block-size] values-block :: = Byte[values-block-size] – The key-lengths and value-lengths blocks are are a sequence of lengths encoded – in ZeroCompressedInteger (VInt) format. key-lengths-block :: = Byte[key-lengths-block-size] value-lengths-block :: = Byte[value-lengths-block-size] Byte ::= An eight-bit byte VInt ::= Variable length integer. The high-order bit of each byte indicates whether more bytes remain to be read. The low-order seven bits are appended as increasingly more significant bits in the resulting integer value. Int ::= A four-byte integer in big-endian format. Text ::= VInt, Chars (Length prefixed UTF-8 characters)
Utility functions that depend on both JNI and Thrift, kept separate to reduce unnecessary dependencies where we just want to use one or the other.
This file adds an implementation of Thrift's ThreadFactory and Thread that uses Impala's Thread wrapper class, so that all threads are accounted for by Impala's ThreadManager.
This file contains internal structures to the IoMgr. Users of the IoMgr do not need to include this file.
stringstream is a typedef, so can't forward declare it.
Copyright 2012 Cloudera Inc.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http:///www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Be very careful when adding Impala includes in this file. We don't want to pull in unnecessary dependencies for the development libs.
This is the only Impala header required to develop UDFs and UDAs. This header contains the types that need to be used and the FunctionContext object. The context object serves as the interface object between the UDF/UDA and the impala process.
This is a utility class that aggregates counters from the kernel. These counters come from different sources.
perf counter syscall (/usr/include/linux/perf_event.h")
/proc/self/io: io stats
/proc/self/status: memory stats The complexity here is that all these sources have data in a different and not easy to get at format. A typical usage pattern would be: PerfCounters counters; counters.AddDefaultCounters(); counters.Snapshot("After Init"); <do your="" work>=""> counters.Snapshot("After Work"); counters.PrettyPrint(cout);
"Redaction" is about preventing sensitive data from showing up in undesired locations, such as log files or a web ui. For example, this library could be used to log credit card numbers as XXXX-...-XXXX instead of actual numbers. The java original is http://github.mtv.cloudera.com/CDH/logredactor. TODO: Replace the above link with the public version once it is available.
Typedef Documentation
typedef boost::unordered_map<TUniqueId, BackendExecState*> impala::BackendExecStateMap
map from fragment instance id to corresponding exec state stored in backend_exec_states_
Definition at line 259 of file coordinator.h.
typedef class SimpleMetric< bool, TMetricKind::PROPERTY > impala::BooleanProperty
Definition at line 322 of file metrics.h.
typedef ClientCache<CatalogServiceClient> impala::CatalogServiceClientCache
Definition at line 348 of file client-cache.h.
typedef ClientConnection<CatalogServiceClient> impala::CatalogServiceConnection
Definition at line 350 of file client-cache.h.
typedef void* impala::ClientKey
Opaque pointer type which allows users of ClientCache to refer to particular client instances without requiring that we parameterise ClientCacheHelper by type.
Definition at line 35 of file client-cache.h.
typedef std::map<PlanNodeId, RuntimeProfile::Counter*> impala::CounterMap
map from id of a scan node to a specific counter in the node's profile
Definition at line 204 of file coordinator.h.
typedef DecimalValue<int128_t> impala::Decimal16Value
TODO: should we support Decimal12Value? We pad it to 16 bytes in the tuple anyway.
Definition at line 350 of file decimal-value.h.
typedef DecimalValue<int32_t> impala::Decimal4Value
Definition at line 346 of file decimal-value.h.
typedef DecimalValue<int64_t> impala::Decimal8Value
Definition at line 347 of file decimal-value.h.
typedef class SimpleMetric< double, TMetricKind::GAUGE > impala::DoubleGauge
Definition at line 319 of file metrics.h.
typedef std::map<TErrorCode::type, TErrorLogEntry> impala::ErrorLogMap
Tracks log messages per error code.
Definition at line 144 of file error-util.h.
typedef std::map<std::string, std::string> impala::FileMoveMap
Tracks files to move from a temporary (key) to a final destination (value) as part of query finalization. If the destination is empty, the file is to be deleted.
Definition at line 65 of file runtime-state.h.
typedef function<void (int64_t, int64_t , AtomicInt<int>*)> impala::Fn
Definition at line 104 of file atomic-test.cc.
typedef boost::unordered_map<TNetworkAddress, PerNodeScanRanges> impala::FragmentScanRangeAssignment
map from an impalad host address to the per-node assigned scan ranges; records scan range assignment for a single fragment
Definition at line 42 of file query-schedule.h.
typedef ThreadPool<HdfsOp> impala::HdfsOpThreadPool
Definition at line 78 of file hdfs-bulk-ops.h.
typedef ClientCache<ImpalaInternalServiceClient> impala::ImpalaInternalServiceClientCache
Definition at line 344 of file client-cache.h.
typedef ClientConnection<ImpalaInternalServiceClient> impala::ImpalaInternalServiceConnection
Definition at line 346 of file client-cache.h.
typedef __int128_t impala::int128_t
We use the c++ int128_t type. This is stored using 16 bytes and very performant.
Definition at line 51 of file multi-precision.h.
typedef boost::multiprecision::number< boost::multiprecision::cpp_int_backend<256, 256, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, void> > impala::int256_t
Define 256 bit int type.
Definition at line 57 of file multi-precision.h.
typedef class SimpleMetric< int64_t, TMetricKind::COUNTER > impala::IntCounter
Definition at line 320 of file metrics.h.
typedef class SimpleMetric< int64_t, TMetricKind::GAUGE > impala::IntGauge
We write 'Int' as a placeholder for all integer types.
Definition at line 317 of file metrics.h.
typedef std::map<std::string, TInsertStats> impala::PartitionInsertStats
Stats per partition for insert queries. They key is the same as for PartitionRowCount.
Definition at line 60 of file runtime-state.h.
typedef std::map<std::string, TInsertPartitionStatus> impala::PartitionStatusMap
Counts how many rows an INSERT query has added to a particular partition (partitions are identified by their partition keys: k1=v1/k2=v2 etc. Unpartitioned tables have a single 'default' partition which is identified by ROOT_PARTITION_KEY.
Definition at line 51 of file runtime-state.h.
typedef boost::unordered_map<std::string, std::pair<bool, short> > impala::PermissionCache
Determines what the permissions of directories created by INSERT statements should be if permission inheritance is enabled. Populates a map from all prefixes of path_str (including the full path itself) which is a path in Hdfs, to pairs (does_not_exist, permissions), where does_not_exist is true if the path does not exist in Hdfs. If does_not_exist is true, permissions is set to the permissions of the most immediate ancestor of the path that does exist, i.e. the permissions that the path should inherit when created. Otherwise permissions is set to the actual permissions of the path. The PermissionCache argument is also used to cache the output across repeated calls, to avoid repeatedly calling hdfsGetPathInfo() on the same path.
Definition at line 450 of file coordinator.h.
typedef std::map<TPlanNodeId, std::vector<TScanRangeParams> > impala::PerNodeScanRanges
map from scan node id to a list of scan ranges
Definition at line 35 of file query-schedule.h.
typedef int impala::PlanNodeId
Definition at line 26 of file global-types.h.
typedef re2::RE2 impala::Regex
Definition at line 46 of file redactor.cc.
typedef vector<Rule> impala::Rules
Definition at line 90 of file redactor.cc.
typedef int impala::SlotId
Definition at line 24 of file global-types.h.
typedef ClientCache<StatestoreServiceClient> impala::StatestoreClientCache
Definition at line 40 of file statestore-subscriber.h.
typedef ClientConnection<StatestoreServiceClient> impala::StatestoreConnection
Definition at line 60 of file statestore-subscriber.cc.
typedef int impala::StringConcatHeader
Definition at line 488 of file aggregate-functions.cc.
typedef class SimpleMetric< std::string, TMetricKind::PROPERTY > impala::StringProperty
Definition at line 323 of file metrics.h.
typedef boost::accumulators::accumulator_set<int64_t, boost::accumulators::features< boost::accumulators::tag::min, boost::accumulators::tag::max, boost::accumulators::tag::mean, boost::accumulators::tag::variance> > impala::SummaryStats
Typedef for boost utility to compute averaged stats TODO: including the median doesn't compile, looks like some includes are missing
Definition at line 181 of file coordinator.h.
typedef int impala::TableId
Definition at line 25 of file global-types.h.
typedef int impala::TupleId
for now, these are simply ints; if we find we need to generate ids in the backend, we can also introduce separate classes for these to make them assignment-incompatible
Definition at line 23 of file global-types.h.
typedef class SimpleMetric< uint64_t, TMetricKind::GAUGE > impala::UIntGauge
Definition at line 318 of file metrics.h.
Enumeration Type Documentation
enum impala::ContentType
Enumerator
HTML
PLAIN
Definition at line 120 of file webserver.cc.
enum impala::DateTimeFormatTokenType
Used to indicate the type of a date/time format token group.
Enumerator
UNKNOWN
SEPARATOR
YEAR
MONTH_IN_YEAR
MONTH_IN_YEAR_SLT
Indicates a short literal month e.g. MMM (Aug). Note that the month name is case insensitive for an input scenario and printed in camel case for an output scenario.
DAY_IN_MONTH
HOUR_IN_DAY
MINUTE_IN_HOUR
SECOND_IN_MINUTE
FRACTION
Indicates fractional seconds e.g.14:52:36.2334. By default this provides nanosecond resolution.
Definition at line 29 of file timestamp-parse-util.h.
enum impala::HdfsOpType
Enumerator
DELETE
CREATE_DIR
RENAME
DELETE_THEN_CREATE
CHMOD
Definition at line 28 of file hdfs-bulk-ops.h.
enum impala::Op
Enumerator
ADD
SUBTRACT
MULTIPLY
DIVIDE
MOD
Definition at line 574 of file decimal-test.cc.
enum impala::PERF_IO_IDX
Enumerator
PROC_IO_READ
PROC_IO_WRITE
PROC_IO_SYS_RREAD
PROC_IO_SYS_WRITE
PROC_IO_DISK_READ
PROC_IO_DISK_WRITE
PROC_IO_CANCELLED_WRITE
PROC_IO_LAST_COUNTER
Definition at line 42 of file perf-counters.cc.
enum impala::PrimitiveType
Enumerator
INVALID_TYPE
TYPE_NULL
TYPE_BOOLEAN
TYPE_TINYINT
TYPE_SMALLINT
TYPE_INT
TYPE_BIGINT
TYPE_FLOAT
TYPE_DOUBLE
TYPE_TIMESTAMP
TYPE_STRING
TYPE_DATE
TYPE_DATETIME
TYPE_BINARY
TYPE_DECIMAL
TYPE_CHAR
This is minimally supported currently. It can't be returned to the user or parsed from scan nodes. It can be returned from exprs and must be consumable by exprs.
TYPE_VARCHAR
Definition at line 27 of file types.h.
enum impala::ResponseCode
Enumerator
OK
NOT_FOUND
Definition at line 114 of file webserver.cc.
Function Documentation
int128_t impala::abs (const int128_t & x) inline
abs() is not defined for int128_t. Name it abs() so it can be compatible with native int types in templates.
Definition at line 113 of file multi-precision.h.
Referenced by impala::DecimalFunctions::Abs(), impala::DecimalValue< int128_t >::Abs(), impala::DecimalValue< int128_t >::Add(), impala::DecimalValue< int128_t >::AdjustToSameScale(), impala::MathFunctions::ConvInt(), impala::MathFunctions::ConvString(), impala::MathFunctions::DecimalInBaseToDecimal(), impala::MathFunctions::DecimalToBase(), impala::Statestore::DoSubscriberUpdate(), impala::DecimalValue< int128_t >::fractional_part(), impala::DecimalValue< int128_t >::FromDouble(), impala::DecimalValue< int128_t >::FromInt(), FuzzyCompare(), impala::DecimalValue< int128_t >::Multiply(), impala::DecimalOperators::RoundDecimalNegativeScale(), impala::DecimalOperators::RoundDelta(), impala::DecimalValue< int128_t >::ScaleTo(), impala::ExprTest::TestTimestampValue(), ToDecimal4(), and ToDecimal8().
impala::ADD_COUNTER_IMPL (AddCounter , Counter)
impala::ADD_COUNTER_IMPL (AddHighWaterMarkCounter , HighWaterMarkCounter)
void impala::AddDefaultUrlCallbacks (Webserver * webserver, MemTracker * process_mem_tracker = NULL)
Adds a set of default path handlers to the webserver to display logs and configuration flags
Definition at line 111 of file default-path-handlers.cc.
References AddPprofUrlCallbacks(), FlagsHandler(), LogsHandler(), MemUsageHandler(), and impala::Webserver::RegisterUrlCallback().
Referenced by impala::InProcessStatestore::InProcessStatestore(), main(), and impala::ExecEnv::StartServices().
void impala::AddPprofUrlCallbacks (Webserver * webserver)
Adds set of path handlers to support pprof profiling of a remote server.
Definition at line 150 of file pprof-path-handlers.cc.
References PprofCmdLineHandler(), PprofCpuProfileHandler(), PprofGrowthHandler(), PprofHeapHandler(), PprofJsonHandler(), PprofSymbolHandler(), and impala::Webserver::RegisterUrlCallback().
Referenced by AddDefaultUrlCallbacks().
void impala::AppendError (ErrorLogMap * map, const ErrorMsg & e)
Append an error to the error map. Performs the aggregation as follows: GENERAL errors are appended to the list of GENERAL errors, to keep one item each in the map, while for all other error codes only the count is incremented and only the first message is kept as a sample.
Definition at line 177 of file error-util.cc.
References impala::ErrorMsg::error(), and impala::ErrorMsg::msg().
Referenced by impala::RuntimeState::LogError(), and TEST().
template<typename T > T impala::area_of_a_circle (T r) inline
Definition at line 104 of file multi-precision-test.cc.
Referenced by TEST().
void impala::AssertErrorMessageContains (const std::string & message, const char * expected)
Definition at line 100 of file redactor-test-utils.h.
void impala::AssertJson (const Value & val, const string & name, const string & value, const string & description, const string & kind = "", const string & units = "")
Definition at line 188 of file metrics-test.cc.
Referenced by TEST().
void impala::AssertRedactedEquals (const char * message, const char * expected)
Test the signature with the 'changed' argument.
Definition at line 105 of file redactor-test-utils.h.
References Redact().
Referenced by AssertUnredacted().
void impala::AssertUnredacted (const char * message)
Definition at line 118 of file redactor-test-utils.h.
References AssertRedactedEquals().
template<typename M , typename T > void impala::AssertValue (M * metric, const T & value, const string & human_readable)
Definition at line 33 of file metrics-test.cc.
Referenced by TEST().
static const string impala::ASSIGNMENTS_KEY ("simple-scheduler.assignments.total") static
Referenced by impala::SimpleScheduler::Init().
bool impala::Base64Decode (const std::string & in, std::string * out)
Utility method to decode base64 encoded strings. Also not extremely performant. Returns true unless the string could not be correctly decoded.
bool impala::Base64Decode (const string & in, string * out)
Definition at line 155 of file url-coding.cc.
Referenced by TestBase64().
void impala::Base64Encode (const std::vector< uint8_t > & in, std::string * out)
Utility method to encode input as base-64 encoded. This is not very performant (multiple string copies) and should not be used in a hot path.
void impala::Base64Encode (const std::vector< uint8_t > & in, std::stringstream * out)
void impala::Base64Encode (const std::string & in, std::string * out)
void impala::Base64Encode (const std::string & in, std::stringstream * out)
static void impala::Base64Encode (const char * in, int in_len, stringstream * out) inline static
Definition at line 110 of file url-coding.cc.
Referenced by Base64Encode(), and TestBase64().
void impala::Base64Encode (const vector< uint8_t > & in, string * out)
Definition at line 127 of file url-coding.cc.
References Base64Encode().
void impala::Base64Encode (const vector< uint8_t > & in, stringstream * out)
Definition at line 137 of file url-coding.cc.
References Base64Encode().
void impala::Base64Encode (const string & in, string * out)
Definition at line 145 of file url-coding.cc.
References Base64Encode().
void impala::Base64Encode (const string & in, stringstream * out)
Definition at line 151 of file url-coding.cc.
References Base64Encode().
impala::BINARY_OP_CHECK_ZERO_INT_TYPES (Int_divide , /)
impala::BINARY_OP_CHECK_ZERO_INT_TYPES (Mod , %)
impala::BINARY_OP_FN (Divide , DoubleVal , /)
impala::BINARY_OP_INT_TYPES (Bitand , &)
impala::BINARY_OP_INT_TYPES (Bitxor , ^)
impala::BINARY_OP_INT_TYPES (Bitor , |)
impala::BINARY_OP_NUMERIC_TYPES (Add , +)
impala::BINARY_OP_NUMERIC_TYPES (Subtract , -)
impala::BINARY_OP_NUMERIC_TYPES (Multiply , *)
impala::BINARY_PREDICATE_ALL_TYPES (Eq)
impala::BINARY_PREDICATE_ALL_TYPES (Ne , !)
impala::BINARY_PREDICATE_ALL_TYPES (Gt)
impala::BINARY_PREDICATE_ALL_TYPES (Lt)
impala::BINARY_PREDICATE_ALL_TYPES (Ge , >=)
impala::BINARY_PREDICATE_ALL_TYPES (Le , <=)
impala::BITNOT_FN (TinyIntVal)
impala::BITNOT_FN (SmallIntVal)
impala::BITNOT_FN (IntVal)
impala::BITNOT_FN (BigIntVal)
string impala::BuildHeaderString (ResponseCode response, ContentType content_type)
Definition at line 126 of file webserver.cc.
References HTML, and OK.
Referenced by impala::Webserver::BeginRequestCallback().
static int64_t impala::ByteSize (const thrift::TColumnValue & val) inline static
Definition at line 80 of file impala-hs2-server.cc.
Referenced by impala::ImpalaServer::HS2RowOrientedResultSet::ByteSize().
static int64_t impala::ByteSize (const thrift::TRow & row) static
Definition at line 84 of file impala-hs2-server.cc.
void impala::Cancel (const Status * cause = NULL)
Cancel execution of query. This includes the execution of the local plan fragment, if any, as well as all plan fragments on remote nodes. Sets query_status_ to the given cause if non-NULL. Otherwise, sets query_status_ to Status::CANCELLED. Idempotent.
Referenced by impala::DiskIoMgr::ScanRange::GetNext().
void impala::CancelInternal () private
Runs cancel logic. Assumes that lock_ is held.
Referenced by impala::ImpalaServer::Cancel(), and impala::ImpalaServer::CancelOperation().
void impala::CancelRemoteFragments () private
Cancels remote fragments. Assumes that lock_ is held. This can be called when the query is not being cancelled in the case where the query limit is reached.
void impala::CASDecrementThread (int64_t id, int64_t n, AtomicInt< int > * ai)
Definition at line 157 of file atomic-test.cc.
References impala::AtomicInt< T >::CompareAndSwap(), and impala::AtomicInt< T >::Read().
Referenced by TEST().
void impala::CASIncrementThread (int64_t id, int64_t n, AtomicInt< int > * ai)
Definition at line 143 of file atomic-test.cc.
References impala::AtomicInt< T >::CompareAndSwap(), and impala::AtomicInt< T >::Read().
Referenced by TEST().
template<typename F , typename T > T impala::CastTUniqueId (const F & from) inline
Definition at line 44 of file uid-util.h.
void impala::CheckAndRotateLogFiles (int max_log_files)
Helper function that checks for the number of logfiles in the log directory and removes the oldest ones given an upper bound of number of logfiles to keep.
Definition at line 159 of file logging.cc.
Referenced by MaintenanceThread().
Status impala::CheckReplayCacheDirPermissions ()
Definition at line 608 of file authentication.cc.
References GetStrErrMsg(), and OK.
Referenced by impala::SaslAuthProvider::InitKerberos().
void impala::CheckVersionParse (const string & s, const string & expected_application, int expected_major, int expected_minor, int expected_patch, bool expected_is_internal)
Definition at line 26 of file parquet-version-test.cc.
References impala::HdfsParquetScanner::FileVersion::application, impala::HdfsParquetScanner::FileVersion::is_impala_internal, impala::HdfsParquetScanner::FileVersion::major, impala::HdfsParquetScanner::FileVersion::minor, impala::HdfsParquetScanner::FileVersion::patch, and impala::HdfsParquetScanner::FileVersion::version.
Referenced by TEST().
Module* impala::CodegenGcd (LLVMContext * context)
Definition at line 110 of file instruction-counter-test.cc.
Referenced by TEST_F().
Function* impala::CodegenInnerLoop (LlvmCodeGen * codegen, int64_t * jitted_counter, int delta)
Definition at line 113 of file llvm-codegen-test.cc.
References impala::LlvmCodeGen::CastPtrToLlvmPtr(), impala::LlvmCodeGen::CodegenDebugTrace(), impala::LlvmCodeGen::context(), impala::LlvmCodeGen::FnPrototype::GeneratePrototype(), impala::LlvmCodeGen::GetPtrType(), TYPE_BIGINT, and impala::LlvmCodeGen::void_type().
Referenced by TEST_F().
Module* impala::CodegenMulAdd (LLVMContext * context)
Definition at line 47 of file instruction-counter-test.cc.
Referenced by TEST_F().
Function* impala::CodegenStringTest (LlvmCodeGen * codegen)
Definition at line 247 of file llvm-codegen-test.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::LlvmCodeGen::context(), impala::LlvmCodeGen::GetIntConstant(), impala::LlvmCodeGen::GetPtrType(), impala::LlvmCodeGen::GetType(), TYPE_INT, TYPE_STRING, and TYPE_TINYINT.
Referenced by TEST_F().
void impala::CollectScanNodeCounters (RuntimeProfile * , FragmentInstanceCounters * result) private
Collect scan node counters from the profile. Assumes lock protecting profile and result is held.
re2::RE2* impala::CompileRegex (const StringVal & pattern, string * error_str)
Definition at line 308 of file string-functions.cc.
References impala_udf::StringVal::len, and impala_udf::StringVal::ptr.
Referenced by impala::StringFunctions::RegexpExtract(), impala::StringFunctions::RegexpPrepare(), and impala::StringFunctions::RegexpReplace().
void impala::ComputeFragmentSummaryStats (BackendExecState * backend_exec_state) private
Compute the summary stats (completion_time and rates) for an individual fragment_profile_ based on the specified backed_exec_state. Called only from ReportQuerySummary() below.
double impala::ComputeKnuthVariance (const KnuthVarianceState & state, bool pop)
Definition at line 1086 of file aggregate-functions.cc.
References impala::KnuthVarianceState::count, and impala::KnuthVarianceState::m2.
Referenced by impala::AggregateFunctions::KnuthStddevFinalize(), impala::AggregateFunctions::KnuthStddevPopFinalize(), impala::AggregateFunctions::KnuthVarFinalize(), and impala::AggregateFunctions::KnuthVarPopFinalize().
int64_t impala::ComputeTotalScanRangesComplete (int node_id) private
Derived counter function: aggregates total completed scan ranges for node_id across all backends(id needs to be for a ScanNode)
int64_t impala::ComputeTotalThroughput (int node_id) private
Derived counter function: aggregates throughput for node_id across all backends (id needs to be for a ScanNode)
void impala::ConsumerThread (InternalQueue< IntNode > * queue, int num_consumes, int delta, vector< int > * results, bool * failed)
Definition at line 164 of file internal-queue-test.cc.
References impala::InternalQueue< T >::Dequeue(), impala::InternalQueue< T >::Validate(), VALIDATE_INTERVAL, and impala::IntNode::value.
Referenced by TEST().
int128_t impala::ConvertToInt128 (int256_t x, int128_t max_value, bool * overflow) inline
Converts an int256_t to an int128_t. int256_t does support convert_to<int128_t>() but that produces an approximate int128_t which makes it unusable. Instead, we'll construct it using convert_to<int64_t> which is exact. *overflow is set to true if the value cannot be converted. The return value is undefined in this case.
Extract the values in base int64_t::max() and reconstruct the new value as an int128_t.
Definition at line 87 of file multi-precision.h.
Referenced by impala::DecimalValue< int128_t >::Divide(), and TEST().
int256_t impala::ConvertToInt256 (const int128_t & x) inline
There is no implicit assignment from int128_t to int256_t (or in general, the boost multi precision types and __int128_t). TODO: look into the perf of this. I think the boost library is very slow with bitwise ops but reasonably fast with arithmetic ops so different implementations of this could have big perf differences.
Definition at line 64 of file multi-precision.h.
Referenced by impala::DecimalValue< int128_t >::Divide(), and TEST().
Status impala::CopyHdfsFile (const hdfsFS & src_conn, const std::string & src_path, const hdfsFS & dst_conn, const std::string & dst_path)
Copy the file at 'src_path' from 'src_conn' to 'dst_path' in 'dst_conn'.
Status impala::CopyHdfsFile (const hdfsFS & src_conn, const string & src_path, const hdfsFS & dst_conn, const string & dst_path)
Definition at line 54 of file hdfs-util.cc.
References GetHdfsErrorMsg(), and impala::Status::OK.
Referenced by impala::LibCache::GetCacheEntryInternal().
void impala::Count (int thread_id, const int & i)
Definition at line 34 of file thread-pool-test.cc.
References thread_counters, and thread_mutexes.
Referenced by TEST().
void impala::CreateAggregateCounters (const std::vector< TPlanFragment > & fragments) private
Create aggregate counters for all scan nodes in any of the fragments.
impala_udf::AnyVal * impala::CreateAnyVal (ObjectPool * pool, const ColumnType & type)
Creates the corresponding AnyVal subclass for type. The object is added to the pool.
Definition at line 26 of file anyval-util.cc.
References impala::ObjectPool::Add(), and CreateAnyVal().
Referenced by impala::CaseExpr::Open(), impala::ScalarFnCall::Open(), impala::HiveUdfCall::Open(), and impala::AggFnEvaluator::Prepare().
impala_udf::AnyVal * impala::CreateAnyVal (const ColumnType & type)
Creates the corresponding AnyVal subclass for type. The object is owned by the caller.
Definition at line 30 of file anyval-util.cc.
References impala::ColumnType::type, TYPE_BIGINT, TYPE_BOOLEAN, TYPE_CHAR, TYPE_DECIMAL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_NULL, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, TYPE_TINYINT, and TYPE_VARCHAR.
Referenced by CreateAnyVal().
shared_ptr<TProtocol> impala::CreateDeserializeProtocol (shared_ptr< TMemoryBuffer > mem, bool compact)
Definition at line 77 of file thrift-util.cc.
Referenced by DeserializeThriftMsg().
boost::shared_ptr<apache::thrift::protocol::TProtocol> impala::CreateDeserializeProtocol (boost::shared_ptr< apache::thrift::transport::TMemoryBuffer > mem, bool compact)
Utility to create a protocol (deserialization) object for 'mem'.
HdfsOpThreadPool* impala::CreateHdfsOpThreadPool (const std::string & name, uint32_t num_threads, uint32_t max_queue_length)
Creates a new HdfsOp-processing thread pool.
Status impala::CreateImpalaServer (ExecEnv * exec_env, int beeswax_port, int hs2_port, int be_port, ThriftServer ** beeswax_server, ThriftServer ** hs2_server, ThriftServer ** be_server, ImpalaServer ** impala_server)
Create an ImpalaServer and Thrift servers. If beeswax_port != 0 (and fe_server != NULL), creates a ThriftServer exporting ImpalaService (Beeswax) on beeswax_port (returned via beeswax_server). If hs2_port != 0 (and hs2_server != NULL), creates a ThriftServer exporting ImpalaHiveServer2Service on hs2_port (returned via hs2_server). If be_port != 0 (and be_server != NULL), create a ThriftServer exporting ImpalaInternalService on be_port (returned via be_server). Returns created ImpalaServer. The caller owns fe_server and be_server. The returned ImpalaServer is referenced by both of these via shared_ptrs and will be deleted automatically. Returns OK unless there was some error creating the servers, in which case none of the output parameters can be assumed to be valid.
Definition at line 1641 of file impala-server.cc.
References BEESWAX_SERVER_NAME, impala::AuthManager::GetInstance(), HS2_SERVER_NAME, impala::ImpalaServer::ImpalaServer(), impala::ExecEnv::metrics(), impala::Status::OK, RETURN_IF_ERROR, impala::ThriftServer::SetConnectionHandler(), and impala::ThriftServer::ThreadPool.
Referenced by main(), impala::InProcessImpalaServer::StartAsBackendOnly(), and impala::InProcessImpalaServer::StartWithClientServers().
static string impala::DebugPoolStats (const string & pool_name, const TPoolStats * total_stats, const TPoolStats * local_stats) static
Definition at line 148 of file admission-controller.cc.
Referenced by impala::AdmissionController::AddPoolUpdates(), impala::AdmissionController::AdmitQuery(), impala::AdmissionController::HandleTopicDeletions(), impala::AdmissionController::HandleTopicUpdates(), impala::AdmissionController::ReleaseQuery(), and impala::AdmissionController::UpdateClusterAggregates().
void impala::DebugTrace (const char * str)
Definition at line 761 of file llvm-codegen.cc.
Referenced by impala::LlvmCodeGen::CodegenDebugTrace().
string impala::DebugWindowBoundString (const TAnalyticWindowBoundary & b)
Definition at line 216 of file analytic-eval-node.cc.
Referenced by impala::AnalyticEvalNode::DebugWindowString().
void impala::DecrementThread (int64_t id, int64_t n, AtomicInt< int > * ai)
Definition at line 112 of file atomic-test.cc.
Referenced by TEST().
static const string impala::DEFAULT_USER ("default") static
Referenced by impala::SimpleScheduler::Schedule().
impala::DEFINE_int32 (periodic_counter_update_period_ms , 500 , "Period to update rate counters and"" sampling counters in ms")
template<class T > Status impala::DeserializeThriftMsg (JNIEnv * env, jbyteArray serialized_msg, T * deserialized_msg)
Return buffer back. JNI_ABORT indicates to not copy contents back to java side.
Definition at line 45 of file jni-thrift-util.h.
References impala::Status::OK, and RETURN_IF_ERROR.
Referenced by CallJniMethod(), impala::JniUtil::CallJniMethod(), impala::ImpalaServer::CatalogUpdateCallback(), impala::Catalog::GetAllCatalogObjects(), impala::AdmissionController::HandleTopicUpdates(), Java_com_cloudera_impala_service_FeSupport_NativeCacheJar(), Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs(), Java_com_cloudera_impala_service_FeSupport_NativeLookupSymbol(), Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad(), impala::ImpalaServer::MembershipCallback(), impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsParquetScanner::BaseColumnReader::ReadDataPage(), TEST(), and TestDeserialize().
template<class T > Status impala::DeserializeThriftMsg (const uint8_t * buf, uint32_t * len, bool compact, T * deserialized_msg)
Deserialize a thrift message from buf/len. buf/len must at least contain all the bytes needed to store the thrift message. On return, len will be set to the actual length of the header.
Deserialize msg bytes into c++ thrift msg using memory transport. TMemoryBuffer is not const-safe, although we use it in a const-safe way, so we have to explicitly cast away the const.
TODO: Find the right exception for 0 bytes
Definition at line 111 of file thrift-util.h.
References CreateDeserializeProtocol(), and impala::Status::OK.
double impala::DistinceEstimateFinalize (const StringVal & src)
Definition at line 671 of file aggregate-functions.cc.
References DistinctEstimateBitMapToString(), GetDistinctEstimateBit(), impala_udf::AnyVal::is_null, impala_udf::StringVal::len, NUM_PC_BITMAPS, PC_BITMAP_LENGTH, PC_THETA, impala_udf::StringVal::ptr, and VLOG_ROW.
Referenced by impala::AggregateFunctions::PcFinalize(), and impala::AggregateFunctions::PcsaFinalize().
string impala::DistinctEstimateBitMapToString (uint8_t * v)
Definition at line 639 of file aggregate-functions.cc.
References GetDistinctEstimateBit(), NUM_PC_BITMAPS, and PC_BITMAP_LENGTH.
Referenced by DistinceEstimateFinalize(), and impala::AggregateFunctions::PcMerge().
int impala::DoubleCompare (double x, double y)
Definition at line 734 of file decimal-test.cc.
Referenced by TEST().
void impala::DynamicClose (void * handle)
Closes the handle.
Definition at line 58 of file dynamic-util.cc.
Referenced by impala::LibCache::~LibCache(), and impala::LibCache::LibCacheEntry::~LibCacheEntry().
Status impala::DynamicLookup (void * handle, const char * symbol, void ** fn_ptr, bool quiet = false)
Look up symbols in a dynamically linked library. handle – handle to the library. NULL if loading from the current process. symbol – symbol to lookup. fn_ptr – pointer tor retun addres of function. quiet – silence the error
Definition at line 26 of file dynamic-util.cc.
References impala::Status::Expected(), and impala::Status::OK.
Referenced by impala::LibCache::GetSoFunctionPtr(), and impala::HdfsLzoTextScanner::LoadLzoLibrary().
Status impala::DynamicOpen (const char * library, void ** handle)
Open a dynamicly loaded library. library – name of the library. The default paths will be searched. library can be NULL to get the handle for the current process. handle – returned handle to the library.
Definition at line 37 of file dynamic-util.cc.
References impala::TestInfo::is_fe_test(), and impala::Status::OK.
Referenced by impala::LibCache::GetCacheEntryInternal(), impala::LibCache::InitInternal(), and impala::HdfsLzoTextScanner::LoadLzoLibrary().
static const RE2 impala::ENDS_WITH_RE ("(?:\\.\\*)*([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)\\$") static
Referenced by impala::LikePredicate::RegexPrepare().
static Status impala::EnvAppend (const string & attr, const string & thing, const string & thingval) static
Definition at line 668 of file authentication.cc.
References GetStrErrMsg(), and OK.
Referenced by impala::SaslAuthProvider::InitKerberosEnv().
static const RE2 impala::EQUALS_RE ("\\^([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)\\$") static
Referenced by impala::LikePredicate::RegexPrepare().
static const string impala::ERROR_USER_NOT_ALLOWED_IN_POOL ("Request from user '$0' with ""requested pool '$1' denied access to assigned pool '$2'") static
Referenced by impala::SimpleScheduler::GetRequestPool().
static const string impala::ERROR_USER_NOT_SPECIFIED () static
Referenced by impala::SimpleScheduler::Schedule().
static const string impala::ERROR_USER_TO_POOL_MAPPING_NOT_FOUND ("No mapping found for request from user '$0' with requested pool '$1'") static
Referenced by impala::SimpleScheduler::GetRequestPool().
size_t impala::ErrorCount (const ErrorLogMap & errors)
Returns the number of errors within this error maps. General errors are counted individually, while specific errors are counted once per distinct occurrence.
Definition at line 191 of file error-util.cc.
Referenced by impala::RuntimeState::LogError(), and TEST().
void impala::EscapeForHtml (const std::string & in, std::stringstream * out)
Replaces &, < and > with &, < and > respectively. This is not the full set of required encodings, but one that should be added to on a case-by-case basis. Slow, since it necessarily inspects each character in turn, and copies them all to *out; use judiciously.
void impala::EscapeForHtml (const string & in, stringstream * out)
Definition at line 178 of file url-coding.cc.
Referenced by TEST().
Status impala::Exec (QuerySchedule & schedule, std::vector< ExprContext * > * output_expr_ctxs)
Initiate asynchronous execution of a query with the given schedule. Returns as soon as all plan fragments have started executing at their respective backends. 'schedule' must contain at least a coordinator plan fragment (ie, can't be for a query like 'SELECT 1'). Populates and prepares output_expr_ctxs from the coordinator's fragment if there is one, and LLVM optimizes them together with the fragment's other exprs. A call to Exec() must precede all other member function calls.
Referenced by impala::CatalogOpExecutor::ExecComputeStats().
const TExecSummary& impala::exec_summary () const
Returns the exec summary. The exec summary lock must already have been taken. The caller must not block while holding the lock.
Definition at line 173 of file coordinator.h.
References impala::SpinLock::DCheckLocked(), exec_summary_, and exec_summary_lock_.
Referenced by impala::ImpalaServer::UnregisterQuery().
Status impala::ExecRemoteFragment (void * exec_state) private
Wrapper for ExecPlanFragment() rpc. This function will be called in parallel from multiple threads. Obtains exec_state->lock prior to making rpc, so that it serializes correctly with UpdateFragmentExecStatus(). exec_state contains all information needed to issue the rpc. 'coordinator' will always be an instance to this class and 'exec_state' will always be an instance of BackendExecState.
void impala::ExprValueToHS2TColumn (const void * value, const TColumnType & type, uint32_t row_idx, apache::hive::service::cli::thrift::TColumn * column)
For V6->
Referenced by impala::ImpalaServer::HS2ColumnarResultSet::AddOneRow().
void impala::ExprValueToHS2TColumnValue (const void * value, const TColumnType & type, apache::hive::service::cli::thrift::TColumnValue * hs2_col_val)
For V1->V5.
Referenced by impala::ImpalaServer::HS2RowOrientedResultSet::AddOneRow().
void impala::FinalizePartitionedColumnStats (const apache::hive::service::cli::thrift::TTableSchema & col_stats_schema, const std::vector< TPartitionStats > & existing_part_stats, const std::vector< std::vector< std::string > > & expected_partitions, const apache::hive::service::cli::thrift::TRowSet & rowset, int32_t num_partition_cols, TAlterTableUpdateStatsParams * params)
Populates the supplied TAlterTableUpdateStatsParams argument with per-column statistics that are computed by aggregating the per-partition results from the COMPUTE STATS child queries, contained in the 'rowset', and any pre-existing per-partition measurements, contained in 'existing_part_stats'. The schema for 'rowset' is in 'col_stats_schema'.
void impala::FinalizePartitionedColumnStats (const TTableSchema & col_stats_schema, const vector< TPartitionStats > & existing_part_stats, const vector< vector< string > > & expected_partitions, const TRowSet & rowset, int32_t num_partition_cols, TAlterTableUpdateStatsParams * params)
Definition at line 188 of file incr-stats-util.cc.
References DecodeNdv(), EncodeNdv(), HLL_LEN, PrintTColumnValue(), and PerColumnStats::Update().
Referenced by impala::CatalogOpExecutor::ExecComputeStats().
Status impala::FinalizeQuery () private
Perform any post-query cleanup required. Called by Wait() only after all backends have returned, or if the query has failed, in which case it only cleans up temporary data rather than finishing the INSERT in flight.
Status impala::FinalizeSuccessfulInsert () private
Moves all temporary staging files to their final destinations.
bool impala::FindFirstNonLocalhost (const std::vector< std::string > & addresses, std::string * addr)
Finds the first non-localhost IP address in the given list. Returns true if such an address was found, false otherwise.
bool impala::FindFirstNonLocalhost (const vector< string > & addresses, string * addr)
Definition at line 85 of file network-util.cc.
References LOCALHOST().
Referenced by impala::SimpleScheduler::Init().
template<typename K , typename V > V* impala::FindOrInsert (std::map< K, V > * m, const K & key, const V & default_val)
FindOrInsert(): if the key is present, return the value; if the key is not present, create a new entry (key, default_val) and return default_val.
Definition at line 51 of file container-util.h.
Referenced by impala::RuntimeProfile::AddDerivedCounter(), impala::RuntimeProfile::UpdateAverage(), and impala::HdfsScanNode::UpdateHdfsSplitStats().
template<typename K , typename V > V* impala::FindOrInsert (boost::unordered_map< K, V > * m, const K & key, const V & default_val)
Definition at line 60 of file container-util.h.
template<typename K , typename V > const V& impala::FindWithDefault (const std::map< K, V > & m, const K & key, const V & default_val)
FindWithDefault: if the key is present, return the corresponding value; if the key is not present, return the supplied default value
Definition at line 73 of file container-util.h.
Referenced by impala::PlanFragmentExecutor::Prepare().
template<typename K , typename V > const V& impala::FindWithDefault (const boost::unordered_map< K, V > & m, const K & key, const V & default_val)
Definition at line 80 of file container-util.h.
TLogLevel::type impala::FlagToTLogLevel (int flag)
Helper function to convert a command line logging flag value (input as an int) to the matching TLogLevel enum value.
Definition at line 84 of file logging-support.cc.
Referenced by impala::Catalog::Catalog(), and impala::Frontend::Frontend().
StringValue impala::FromStdString (const string & str)
Definition at line 25 of file string-value-test.cc.
Referenced by TEST().
TUniqueId impala::GenerateUUID () inline
generates a 16 byte UUID
Definition at line 60 of file uid-util.h.
References GenerateUUIDString().
string impala::GenerateUUIDString () inline
generates a 16 byte UUID
Definition at line 52 of file uid-util.h.
Referenced by GenerateUUID(), impala::HdfsSequenceTableWriter::Init(), and impala::HdfsAvroTableWriter::Init().
std::string impala::GetBuildVersion (bool compact = false)
Returns a string "<product version number> (build <build hash>)" If compact == false, this string is appended: "\nBuilt on <build time>" This is used to set gflags build version
Definition at line 223 of file debug-util.cc.
References IMPALA_BUILD_HASH, IMPALA_BUILD_TIME, and IMPALA_BUILD_VERSION.
Referenced by GetVersionString(), and InitCommonRuntime().
static string impala::GetCounterName (PerfCounters::Counter counter) static
Definition at line 119 of file perf-counters.cc.
References impala::PerfCounters::PERF_COUNTER_BYTES_READ, impala::PerfCounters::PERF_COUNTER_BYTES_WRITE, impala::PerfCounters::PERF_COUNTER_DISK_READ, impala::PerfCounters::PERF_COUNTER_DISK_WRITE, impala::PerfCounters::PERF_COUNTER_HW_BRANCH_MISSES, impala::PerfCounters::PERF_COUNTER_HW_BRANCHES, impala::PerfCounters::PERF_COUNTER_HW_BUS_CYCLES, impala::PerfCounters::PERF_COUNTER_HW_CACHE_HIT, impala::PerfCounters::PERF_COUNTER_HW_CACHE_MISSES, impala::PerfCounters::PERF_COUNTER_HW_CPU_CYCLES, impala::PerfCounters::PERF_COUNTER_HW_INSTRUCTIONS, impala::PerfCounters::PERF_COUNTER_RESIDENT_SET_SIZE, impala::PerfCounters::PERF_COUNTER_SW_CONTEXT_SWITCHES, impala::PerfCounters::PERF_COUNTER_SW_CPU_CLOCK, impala::PerfCounters::PERF_COUNTER_SW_CPU_MIGRATIONS, impala::PerfCounters::PERF_COUNTER_SW_PAGE_FAULTS, impala::PerfCounters::PERF_COUNTER_VM_PEAK_USAGE, and impala::PerfCounters::PERF_COUNTER_VM_USAGE.
Referenced by impala::PerfCounters::AddCounter().
TDebugAction::type impala::GetDebugAction (const string & key)
Definition at line 267 of file coordinator.cc.
Referenced by ProcessQueryOptions().
static Decimal16Value impala::GetDecimal16Value (const DecimalVal & val, const ColumnType & type, bool * overflow) inline static
Definition at line 215 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), ToDecimal16(), impala::ColumnType::type, TYPE_DECIMAL, impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
static Decimal4Value impala::GetDecimal4Value (const DecimalVal & val, const ColumnType & type, bool * overflow) inline static
Definition at line 189 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), ToDecimal4(), impala::ColumnType::type, TYPE_DECIMAL, impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
static Decimal8Value impala::GetDecimal8Value (const DecimalVal & val, const ColumnType & type, bool * overflow) inline static
Definition at line 202 of file decimal-operators.cc.
References impala::ColumnType::GetByteSize(), ToDecimal8(), impala::ColumnType::type, TYPE_DECIMAL, impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
static bool impala::GetDistinctEstimateBit (uint8_t * bitmap, uint32_t row_index, uint32_t bit_index) inline static
Definition at line 597 of file aggregate-functions.cc.
Referenced by DistinceEstimateFinalize(), and DistinctEstimateBitMapToString().
std::string impala::GetErrorLog ()
Return error log for coord and all the fragments. The error messages from the individual backends are merged into a single output to retain readability.
TExecNodePhase::type impala::GetExecNodePhase (const string & key)
Definition at line 255 of file coordinator.cc.
Referenced by ProcessQueryOptions().
SpinLock& impala::GetExecSummaryLock () const
Definition at line 178 of file coordinator.h.
References exec_summary_lock_.
Status impala::GetFileSize (const hdfsFS & connection, const char * filename, int64_t * filesize)
Return the size, in bytes, of a file from the hdfs connection.
Definition at line 33 of file hdfs-util.cc.
References GetHdfsErrorMsg(), and impala::Status::OK.
int impala::GetFragmentNum (const TUniqueId & fragment_id) private
Determine fragment number, given fragment id.
void impala::GetFullLogFilename (google::LogSeverity severity, std::string * filename)
Returns the full pathname of the symlink to the most recent log file corresponding to this severity
Referenced by InitGoogleLoggingSafe(), and LogsHandler().
string impala::GetHdfsErrorMsg (const string & prefix, const string & file)
Definition at line 26 of file hdfs-util.cc.
References GetStrErrMsg().
Referenced by impala::HdfsTableSink::ClosePartitionFile(), CopyHdfsFile(), impala::HdfsTableSink::CreateNewTmpFile(), impala::HdfsFsCache::GetConnection(), impala::HdfsTableSink::GetFileBlockSize(), GetFileSize(), GetLastModificationTime(), impala::DiskIoMgr::ScanRange::Open(), impala::DiskIoMgr::ScanRange::Read(), and impala::HdfsTableWriter::Write().
std::string impala::GetHdfsErrorMsg (const std::string & prefix, const std::string & file = "")
Utility function to get error messages from HDFS. This function takes prefix/file and appends errno to it. Note: any stdlib function can reset errno, this should be called immediately following the failed call into libhdfs.
IRFunction::Type impala::GetHllUpdateFunction2 (const ColumnType & type)
Definition at line 413 of file aggregation-node.cc.
References impala::ColumnType::type, TYPE_BIGINT, TYPE_BOOLEAN, TYPE_DECIMAL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, TYPE_STRING, and TYPE_TINYINT.
Referenced by impala::AggregationNode::CodegenUpdateSlot().
Status impala::GetHostname (std::string * hostname)
Sets the output argument to the system defined hostname. Returns OK if a hostname can be found, false otherwise.
Status impala::GetHostname (string * hostname)
Definition at line 40 of file network-util.cc.
References GetStrErrMsg(), name, and impala::Status::OK.
Referenced by InitCommonRuntime(), impala::SaslAuthProvider::InitKerberos(), impala::SaslAuthProvider::Start(), and TEST().
Status impala::GetLastModificationTime (const hdfsFS & connection, const char * filename, time_t * last_mod_time)
Returns the last modification time of 'filename' in seconds. This should not be called in a fast path (e.g., running a UDF).
Definition at line 41 of file hdfs-util.cc.
References GetHdfsErrorMsg(), and impala::Status::OK.
Referenced by impala::LibCache::GetCacheEntryInternal().
static Function* impala::GetLenOptimizedHashFn (LlvmCodeGen * codegen, IRFunction::Type f, int len) static
Definition at line 1078 of file llvm-codegen.cc.
References impala::LlvmCodeGen::CloneFunction(), impala::LlvmCodeGen::FinalizeFunction(), impala::LlvmCodeGen::GetArgument(), impala::LlvmCodeGen::GetFunction(), impala::LlvmCodeGen::GetIntConstant(), and TYPE_INT.
Referenced by impala::LlvmCodeGen::GetFnvHashFunction(), and impala::LlvmCodeGen::GetMurmurHashFunction().
Status impala::GetNext (RowBatch ** batch, RuntimeState * state)
Returns tuples from the coordinator fragment. Any returned tuples are valid until the next GetNext() call. If *batch is NULL, execution has completed and GetNext() must not be called again. GetNext() will not set *batch=NULL until all backends have either completed or have failed. It is safe to call GetNext() even in the case where there is no coordinator fragment (distributed INSERT). '*batch' is owned by the underlying PlanFragmentExecutor and must not be deleted. *state is owned by the caller, and must not be deleted. Returns an error status if an error was encountered either locally or by any of the remote fragments or if the query was cancelled. GetNext() is not thread-safe: multiple threads must not make concurrent GetNext() calls (but may call any of the other member functions concurrently with GetNext()).
ColumnType impala::GetResultType (const ColumnType & t1, const ColumnType & t2, Op op)
Definition at line 584 of file decimal-test.cc.
References ADD, impala::ColumnType::CreateDecimalType(), DIVIDE, MOD, MULTIPLY, impala::ColumnType::precision, impala::ColumnType::scale, and SUBTRACT.
Referenced by TEST().
std::string impala::GetStackTrace ()
Returns the stack trace as a string from the current location. Note: there is a libc bug that causes this not to work on 64 bit machines for recursive calls.
Definition at line 246 of file debug-util.cc.
References google::glog_internal_namespace_::DumpStackTraceToString().
Referenced by impala::BufferedBlockMgr::FindBufferForBlock(), impala::MemTracker::LogUpdate(), impala::BufferedBlockMgr::MemLimitTooLowError(), RecursionStack(), impala::Status::Status(), and TEST().
Status impala::GetStatus ()
Returns query_status_.
std::string impala::GetStrErrMsg ()
Returns the error message for errno. We should not use strerror directly as that is not thread safe. Returns empty string if errno is 0.
Definition at line 30 of file error-util.cc.
Referenced by CheckReplayCacheDirPermissions(), impala::FileSystemUtil::CreateFile(), impala::ImpalaServer::DetectNmFailures(), EnvAppend(), impala::HdfsOp::Execute(), GetHdfsErrorMsg(), GetHostname(), InitGoogleLoggingSafe(), impala::SaslAuthProvider::InitKerberosEnv(), impala::DiskIoMgr::ScanRange::Open(), impala::DiskIoMgr::ScanRange::Read(), impala::FileSystemUtil::ResizeFile(), impala::Thread::SuperviseThread(), impala::DiskIoMgr::Write(), and impala::DiskIoMgr::WriteRangeHelper().
string impala::GetTablesMissingStatsWarning (const vector< TTableName > & tables_missing_stats)
Definition at line 40 of file error-util.cc.
Referenced by impala::SimpleScheduler::Schedule(), and impala::RuntimeState::SetMemLimitExceeded().
std::string impala::GetTablesMissingStatsWarning (const std::vector< TTableName > & tables_missing_stats)
Returns an error message warning that the given table names are missing relevant table/and or column statistics.
Status impala::GetThreadStats (int64_t tid, ThreadStats * stats)
Populates ThreadStats object for a given thread by reading from /proc/<pid>/task/<tid>/stats. Returns OK unless the file cannot be read or is in an unrecognised format, or if the kernel version is not modern enough.
Definition at line 52 of file os-util.cc.
References IO_WAIT, impala::ThreadStats::iowait_ns, impala::ThreadStats::kernel_ns, KERNEL_TICKS, MAX_OFFSET, impala::Status::OK, impala::StringParser::PARSE_SUCCESS, TICKS_PER_SEC, impala::ThreadStats::user_ns, and USER_TICKS.
Referenced by impala::ThreadMgr::ThreadGroupUrlCallback().
template<typename T , typename SetType > SetType impala::GetVal (const FunctionContext::TypeDesc * type, const T & x)
Definition at line 30 of file in-predicate-ir.cc.
template<> StringValue impala::GetVal (const FunctionContext::TypeDesc * type, const StringVal & x)
Definition at line 35 of file in-predicate-ir.cc.
References impala_udf::AnyVal::is_null.
template<> TimestampValue impala::GetVal (const FunctionContext::TypeDesc * type, const TimestampVal & x)
Definition at line 40 of file in-predicate-ir.cc.
template<> Decimal16Value impala::GetVal (const FunctionContext::TypeDesc * type, const DecimalVal & x)
Definition at line 45 of file in-predicate-ir.cc.
References impala_udf::FunctionContext::TypeDesc::precision, impala_udf::DecimalVal::val16, impala_udf::DecimalVal::val4, and impala_udf::DecimalVal::val8.
std::string impala::GetVersionString (bool compact)
Returns "<program short name> version <GetBuildVersion(compact)>".
Definition at line 239 of file debug-util.cc.
References GetBuildVersion().
Referenced by impala::ImpaladMetrics::CreateMetrics(), InitCommonRuntime(), main(), impala::ImpalaServer::PingImpalaService(), impala::ImpalaServer::QueryExecState::QueryExecState(), impala::Webserver::RootHandler(), TEST_F(), and impala::UtilityFunctions::Version().
std::size_t impala::hash_value (const impala::TUniqueId & id) inline
This function must be called 'hash_value' to be picked up by boost.
Definition at line 28 of file uid-util.h.
std::size_t impala::hash_value (const TNetworkAddress & host_port) inline
Hash function for TNetworkAddress. This function must be called hash_value to be picked up properly by boost.
Definition at line 29 of file container-util.h.
References hash, and impala::HashUtil::Hash().
std::size_t impala::hash_value (const StringValue & v) inline
This function must be called 'hash_value' to be picked up by boost.
Definition at line 125 of file string-value.h.
References impala::HashUtil::Hash(), impala::StringValue::len, and impala::StringValue::ptr.
std::size_t impala::hash_value (const TimestampValue & v) inline
This function must be called 'hash_value' to be picked up by boost.
Definition at line 275 of file timestamp-value.h.
References impala::TimestampValue::Hash().
std::size_t impala::hash_value (const Decimal4Value & v) inline
This function must be called 'hash_value' to be picked up by boost.
Definition at line 397 of file decimal-value.h.
References impala::DecimalValue< T >::Hash().
Referenced by impala::DataStreamMgr::CreateRecvr(), impala::DataStreamMgr::DeregisterRecvr(), impala::DataStreamMgr::FindRecvr(), HllUpdate(), impala::AggregateFunctions::HllUpdate(), impala::HashTNetworkAddressPtr::operator()(), impala::AggregateFunctions::PcsaUpdate(), impala::AggregateFunctions::PcUpdate(), TestBoostIntHash(), and TestBoostMixedHash().
std::size_t impala::hash_value (const Decimal8Value & v) inline
Definition at line 400 of file decimal-value.h.
References impala::DecimalValue< T >::Hash().
std::size_t impala::hash_value (const Decimal16Value & v) inline
Definition at line 403 of file decimal-value.h.
References impala::DecimalValue< T >::Hash().
uint64_t impala::HighBits (int128_t x) inline
Get the high and low bits of an int128_t.
Definition at line 116 of file multi-precision.h.
Referenced by impala::CodegenAnyVal::SetVal(), and TEST().
Status impala::HostnameToIpAddrs (const std::string & name, std::vector< std::string > * addresses)
Looks up all IP addresses associated with a given hostname. Returns an error status if any system call failed, otherwise OK. Even if OK is returned, addresses may still be of zero length.
Status impala::HostnameToIpAddrs (const string & name, vector< string > * addresses)
Definition at line 53 of file network-util.cc.
References name, and impala::Status::OK.
Referenced by impala::SimpleScheduler::Init(), and main().
int impala::ImpalaAuxpropInit (const sasl_utils_t * utils, int max_version, int * out_version, sasl_auxprop_plug_t ** plug, const char * plugname)
Definition at line 331 of file authentication.cc.
References impala_auxprop_plugin.
Referenced by InitAuth().
static void impala::ImpalaAuxpropLookup (void * glob_context, sasl_server_params_t * sparams, unsigned int flags, const char * user, unsigned ulen) static
Definition at line 306 of file authentication.cc.
void impala::IncrementThread (int64_t id, int64_t n, AtomicInt< int > * ai)
Definition at line 106 of file atomic-test.cc.
Referenced by TEST().
template<typename T > void impala::IncrementValue (T * t)
Definition at line 103 of file dict-test.cc.
Referenced by TestNumbers().
template<> void impala::IncrementValue (Decimal4Value * t)
Definition at line 105 of file dict-test.cc.
References impala::DecimalValue< T >::value().
template<> void impala::IncrementValue (Decimal8Value * t)
Definition at line 106 of file dict-test.cc.
References impala::DecimalValue< T >::value().
template<> void impala::IncrementValue (Decimal16Value * t)
Definition at line 107 of file dict-test.cc.
References impala::DecimalValue< T >::value().
Status impala::InitAuth (const std::string & appname)
The first entry point to the authentication subsystem. Performs initialization of Sasl, the global AuthManager, and the two authentication providers. Appname should generally be argv[0].
Referenced by InitCommonRuntime(), and main().
Status impala::InitAuth (const string & appname)
Definition at line 506 of file authentication.cc.
References GENERAL_CALLBACKS, IMPALA_AUXPROP_PLUGIN, ImpalaAuxpropInit(), KERB_EXT_CALLBACKS, KERB_INT_CALLBACKS, LDAP_EXT_CALLBACKS, OK, RETURN_IF_ERROR, SaslAuthorizeExternal(), SaslAuthorizeInternal(), SaslGetOption(), SaslGetPath(), sasl::TSaslClient::SaslInit(), sasl::TSaslServer::SaslInit(), SaslLdapCheckPass(), SaslLogCallback(), and SaslVerifyFile().
void impala::InitCommonRuntime (int argc, char ** argv, bool init_jvm, TestInfo::Mode m = TestInfo::NON_TEST)
Initialises logging, flags, and, if init_jvm is true, an embedded JVM. Tests can initialize indicating if they are a FE or BE test if they require different behavior (most BE tests don't.). Callers that want to override default gflags variables should do so before calling this method. No logging should be performed until after this method returns.
Definition at line 122 of file init.cc.
References impala_udf::DebugString(), EXIT_IF_ERROR, EXIT_WITH_ERROR, GetBuildVersion(), GetHostname(), GetVersionString(), impala::HdfsFsCache::Init(), impala::LibCache::Init(), impala::TimestampParser::Init(), InitAuth(), InitGoogleLoggingSafe(), InitJvmLoggingSupport(), InitThreading(), InitThriftLogging(), LogCommandLineFlags(), maintenance_thread, MaintenanceThread(), SetRedactionRulesFromFile(), and VLOG_ROW_IS_ON.
Referenced by Java_com_cloudera_impala_service_FeSupport_NativeFeTestInit(), and main().
static bool impala::InitEventAttr (perf_event_attr * attr, PerfCounters::Counter counter) static
Definition at line 64 of file perf-counters.cc.
References impala::PerfCounters::PERF_COUNTER_HW_BRANCH_MISSES, impala::PerfCounters::PERF_COUNTER_HW_BRANCHES, impala::PerfCounters::PERF_COUNTER_HW_BUS_CYCLES, impala::PerfCounters::PERF_COUNTER_HW_CACHE_HIT, impala::PerfCounters::PERF_COUNTER_HW_CACHE_MISSES, impala::PerfCounters::PERF_COUNTER_HW_CPU_CYCLES, impala::PerfCounters::PERF_COUNTER_HW_INSTRUCTIONS, impala::PerfCounters::PERF_COUNTER_SW_CONTEXT_SWITCHES, impala::PerfCounters::PERF_COUNTER_SW_CPU_CLOCK, impala::PerfCounters::PERF_COUNTER_SW_CPU_MIGRATIONS, and impala::PerfCounters::PERF_COUNTER_SW_PAGE_FAULTS.
Referenced by impala::PerfCounters::InitSysCounter().
void impala::InitExecProfile (const TQueryExecRequest & request) private
Initializes the structures in runtime profile and exec_summary_. Must be called before RPCs to start remote fragments.
void impala::InitFeSupport ()
InitFeSupport registers native functions with JNI. When the java function FeSupport.EvalPredicate is called within Impalad, the native implementation FeSupport_EvalPredicateImpl already exists in Impalad binary. In order to expose JNI functions from Impalad binary, we need to "register native functions". See this link: http://java.sun.com/docs/books/jni/html/other.html#29535 for details.
Definition at line 346 of file fe-support.cc.
References EXIT_IF_EXC, getJNIEnv(), and native_methods.
Referenced by main().
void impala::InitGoogleLoggingSafe (const char * arg)
glog doesn't allow multiple invocations of InitGoogleLogging(). This method conditionally calls InitGoogleLogging() only if it hasn't been called before.
Definition at line 55 of file logging.cc.
References GetFullLogFilename(), GetStrErrMsg(), logging_mutex, and Redact().
Referenced by InitCommonRuntime(), and main().
void impala::InitJvmLoggingSupport ()
InitLoggingSupport registers the native logging functions with JNI. This allows the Java log4j log messages to be forwarded to Glog.
Definition at line 73 of file logging-support.cc.
References EXIT_IF_EXC, getJNIEnv(), and Java_com_cloudera_impala_util_NativeLogger_Log().
Referenced by InitCommonRuntime().
void impala::InitRpcEventTracing (Webserver * webserver)
Initialises rpc event tracing, must be called before any RpcEventHandlers are created.
Definition at line 67 of file rpc-trace.cc.
References handler_manager, RpcEventHandlerManager::JsonCallback(), impala::Webserver::RegisterUrlCallback(), and RpcEventHandlerManager::ResetCallback().
Referenced by main().
void impala::InitThreading ()
Initialises the threading subsystem. Must be called before a Thread is created.
Definition at line 261 of file thread.cc.
References thread_manager.
Referenced by InitCommonRuntime(), and main().
void impala::InitThriftLogging ()
Redirects all Thrift logging to VLOG(1)
Definition at line 112 of file thrift-util.cc.
References ThriftOutputFunction().
Referenced by InitCommonRuntime().
bool impala::IsDfsPath (const char * path)
Returns true iff the path refers to a location on an HDFS filesystem.
Definition at line 66 of file hdfs-util.cc.
Referenced by impala::DiskIoMgr::ScanRange::Close().
bool impala::IsHiddenFile (const std::string & filename)
bool impala::IsHiddenFile (const string & filename)
Definition at line 50 of file hdfs-util.cc.
bool impala::IsS3APath (const char * path)
Returns true iff the path refers to a location on an S3A filesystem.
Definition at line 72 of file hdfs-util.cc.
Referenced by impala::DiskIoMgr::AssignQueue(), and impala::DiskIoMgr::ScanRange::MaxReadChunkSize().
bool impala::IsTimeoutTException (const apache::thrift::TException & e)
Returns true if the TException corresponds to a TCP socket recv or send timeout.
bool impala::IsTimeoutTException (const TException & e)
Definition at line 175 of file thrift-util.cc.
Referenced by impala::ClientConnection< T >::DoRpc().
bool impala::IsWildcardAddress (const std::string & ipaddress)
Returns true if the ip address parameter is the wildcard interface (0.0.0.0)
bool impala::IsWildcardAddress (const string & ipaddress)
Definition at line 122 of file network-util.cc.
Referenced by impala::SimpleScheduler::Init().
template<typename ORIGINAL_TYPE , typename VAL_TYPE > string impala::LiteralToString (VAL_TYPE val)
Definition at line 75 of file expr-test.cc.
template<> string impala::LiteralToString< double, double > (double val)
Definition at line 98 of file expr-test.cc.
template<> string impala::LiteralToString< float, double > (double val)
Definition at line 89 of file expr-test.cc.
template<> string impala::LiteralToString< float, float > (float val)
Definition at line 80 of file expr-test.cc.
static const string impala::LOCAL_ASSIGNMENTS_KEY ("simple-scheduler.local-assignments.total") static
Referenced by impala::SimpleScheduler::Init().
static const string impala::LOCALHOST ("127.0.0.1") static
Referenced by FindFirstNonLocalhost().
void impala::LogCommandLineFlags ()
Writes all command-line flags to the log at level INFO.
Definition at line 154 of file logging.cc.
Referenced by InitCommonRuntime().
uint64_t impala::LowBits (int128_t x) inline
Definition at line 119 of file multi-precision.h.
Referenced by impala::CodegenAnyVal::SetVal(), and TEST().
template<typename T > T impala::MakeAnyVal (int v)
Definition at line 175 of file in-predicate-benchmark.cc.
template<> StringVal impala::MakeAnyVal (int v)
Definition at line 179 of file in-predicate-benchmark.cc.
TNetworkAddress impala::MakeNetworkAddress (const std::string & hostname, int port)
Utility method because Thrift does not supply useful constructors.
TNetworkAddress impala::MakeNetworkAddress (const std::string & address)
Utility method to parse the given string into a network address. Accepted format: "host:port" or "host". For the latter format the port is set to zero. If the given string address is malformed, returns a network address with an empty hostname and a port of 0.
TNetworkAddress impala::MakeNetworkAddress (const string & hostname, int port)
Definition at line 96 of file network-util.cc.
Referenced by impala::SimpleScheduler::ComputeFragmentHosts(), impala::ThriftServer::ThriftServerEventProcessor::createContext(), impala::ResourceResolver::CreateLocalLlamaNodeMapping(), impala::ImpalaServer::DetectNmFailures(), impala::CatalogOpExecutor::Exec(), impala::ExecEnv::ExecEnv(), impala::CatalogOpExecutor::GetCatalogObject(), impala::ResourceBroker::PendingRequest::GetResources(), impala::SimpleScheduler::GetScanHosts(), impala::SimpleScheduler::Init(), impala::ExecEnv::InitRm(), impala::ImpalaServer::PrepareQueryContext(), impala::CatalogOpExecutor::PrioritizeLoad(), impala::CatalogOpExecutor::SentryAdminCheck(), impala::CatalogServer::Start(), impala::StateStore2Test::StartStateStoreSubscriber(), TEST(), impala::ImpalaServer::QueryExecState::UpdateCatalog(), and impala::Webserver::Webserver().
TNetworkAddress impala::MakeNetworkAddress (const string & address)
Definition at line 103 of file network-util.cc.
References impala::StringParser::PARSE_SUCCESS.
static string impala::MakePoolTopicKey (const string & pool_name, const string & backend_id) inline static
Definition at line 138 of file admission-controller.cc.
References TOPIC_KEY_DELIMITER.
Referenced by impala::AdmissionController::AddPoolUpdates().
static TSlotDescriptor impala::MakeSlotDescriptor (int id, int parent_id, const ColumnType & type, int slot_idx, int byte_offset) static
Definition at line 34 of file desc-tbl-builder.cc.
References impala::ColumnType::ToThrift().
Referenced by impala::DescriptorTblBuilder::Build().
static TTupleDescriptor impala::MakeTupleDescriptor (int id, int byte_size, int num_null_bytes) static
Definition at line 51 of file desc-tbl-builder.cc.
Referenced by impala::DescriptorTblBuilder::Build().
void impala::MergeErrorMaps (ErrorLogMap * left, const ErrorLogMap & right)
Merge error maps. Merging of error maps occurs, when the errors from multiple backends are merged into a single error map. General log messages are simply appended, specific errors are deduplicated by either appending a new instance or incrementing the count of an existing one.
Definition at line 159 of file error-util.cc.
Referenced by TEST().
template<typename K , typename V > void impala::MergeMapValues (const std::map< K, V > & src, std::map< K, V > * dst)
Merges (by summing) the values from two maps of values. The values must be native types or support operator +=.
Definition at line 90 of file container-util.h.
int64_t impala::MonotonicMicros () inline
Returns a value representing a point in time with microsecond accuracy that is unaffected by daylight savings or manual adjustments to the system clock. This should not be assumed to be a Unix time. Typically the value corresponds to elapsed time since the system booted. See UnixMillis() below if you need to send a time to a different host.
Definition at line 29 of file time.h.
Referenced by impala::Promise< bool >::Get().
int64_t impala::MonotonicMillis () inline
Definition at line 35 of file time.h.
Referenced by impala::AdmissionController::AdmitQuery(), impala::RpcEventHandler::getContext(), impala::RpcEventHandler::postWrite(), impala::RequestPoolService::ResolveRequestPool(), and TEST().
int64_t impala::MonotonicSeconds () inline
Definition at line 41 of file time.h.
Referenced by impala::ResourceBroker::RegisterWithLlama().
void* impala::MultiThreadWorkload (void * unused)
Definition at line 30 of file redactor-test.cc.
References RandomlyFillString(), RandSeed(), and Redact().
Referenced by TEST().
string impala::NameOfTypeOfJsonValue (const Value & value)
Definition at line 95 of file redactor.cc.
Referenced by impala::RulesParser::ParseRules(), and SetRedactionRulesFromFile().
static const string impala::NUM_BACKENDS_KEY ("simple-scheduler.num-backends") static
Referenced by impala::SimpleScheduler::Init().
ObjectPool* impala::obj_pool () private
Returns a local object pool.
Definition at line 263 of file coordinator.h.
References obj_pool_.
Referenced by Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs(), main(), impala::ScalarFnCall::Open(), and impala::AggFnEvaluator::Prepare().
impala::ONE_ARG_MATH_FN (Abs , BigIntVal , BigIntVal , llabs)
impala::ONE_ARG_MATH_FN (Abs , DoubleVal , DoubleVal , fabs)
impala::ONE_ARG_MATH_FN (Abs , FloatVal , FloatVal , fabs)
impala::ONE_ARG_MATH_FN (Abs , IntVal , IntVal , abs)
impala::ONE_ARG_MATH_FN (Abs , SmallIntVal , SmallIntVal , abs)
impala::ONE_ARG_MATH_FN (Abs , TinyIntVal , TinyIntVal , abs)
impala::ONE_ARG_MATH_FN (Sin , DoubleVal , DoubleVal , sin)
impala::ONE_ARG_MATH_FN (Asin , DoubleVal , DoubleVal , asin)
impala::ONE_ARG_MATH_FN (Cos , DoubleVal , DoubleVal , cos)
impala::ONE_ARG_MATH_FN (Acos , DoubleVal , DoubleVal , acos)
impala::ONE_ARG_MATH_FN (Tan , DoubleVal , DoubleVal , tan)
impala::ONE_ARG_MATH_FN (Atan , DoubleVal , DoubleVal , atan)
impala::ONE_ARG_MATH_FN (Sqrt , DoubleVal , DoubleVal , sqrt)
impala::ONE_ARG_MATH_FN (Ceil , BigIntVal , DoubleVal , ceil)
impala::ONE_ARG_MATH_FN (Floor , BigIntVal , DoubleVal , floor)
impala::ONE_ARG_MATH_FN (Ln , DoubleVal , DoubleVal , log)
impala::ONE_ARG_MATH_FN (Log10 , DoubleVal , DoubleVal , log10)
impala::ONE_ARG_MATH_FN (Exp , DoubleVal , DoubleVal , exp)
static Status impala::OpenSSLErr (const string & msg) static
Definition at line 1176 of file buffered-block-mgr.cc.
References OpenSSLErrCallback().
Referenced by impala::BufferedBlockMgr::Decrypt(), and impala::BufferedBlockMgr::Encrypt().
static int impala::OpenSSLErrCallback (const char * buf, size_t len, void * ctx) static
Definition at line 1169 of file buffered-block-mgr.cc.
Referenced by OpenSSLErr().
ostream& impala::operator<< (ostream & os, const int128_t & val)
Definition at line 27 of file multi-precision.cc.
References ONE_BILLION.
ostream& impala::operator<< (ostream & os, const StringValue & string_value)
Definition at line 28 of file string-value.cc.
References impala::StringValue::DebugString().
std::ostream& impala::operator<< (std::ostream & os, const TFunctionBinaryType::type & op)
std::ostream& impala::operator<< (std::ostream & os, const TUniqueId & id)
std::ostream& impala::operator<< (std::ostream & os, const THdfsFileFormat::type & type)
std::ostream& impala::operator<< (std::ostream & os, const THdfsCompression::type & type)
std::ostream& impala::operator<< (std::ostream & os, const TStmtType::type & type)
std::ostream& impala::operator<< (std::ostream & os, const TUnit::type & type)
ostream& impala::operator<< (ostream & os, const NullIndicatorOffset & null_indicator)
Definition at line 45 of file descriptors.cc.
References impala::NullIndicatorOffset::DebugString().
std::ostream& impala::operator<< (std::ostream & os, const TMetricKind::type & type)
std::ostream& impala::operator<< (std::ostream & os, const beeswax::QueryState::type & type)
std::ostream& impala::operator<< (std::ostream & os, const parquet::Encoding::type & type)
std::ostream& impala::operator<< (std::ostream & os, const parquet::CompressionCodec::type & type)
std::ostream& impala::operator<< (std::ostream & os, const parquet::Type::type & type)
std::ostream& impala::operator<< (std::ostream & out, const TNetworkAddress & hostport)
Prints a hostport as ipaddress:port.
ostream& impala::operator<< (ostream & os, const TimestampValue & timestamp_value)
Definition at line 69 of file timestamp-value.cc.
References impala::TimestampValue::DebugString().
std::ostream& impala::operator<< (std::ostream & os, const NullIndicatorOffset & null_indicator)
ostream& impala::operator<< (ostream & os, const TUniqueId & id)
Definition at line 92 of file debug-util.cc.
References PrintId().
std::ostream& impala::operator<< (std::ostream & os, const int128_t & val)
Prints v in base 10.
std::ostream& impala::operator<< (std::ostream & os, const StringValue & string_value)
ostream& impala::operator<< (ostream & out, const TNetworkAddress & hostport)
Definition at line 132 of file network-util.cc.
std::ostream & impala::operator<< (std::ostream & out, const TColumnValue & colval)
Print a TColumnValue. If null, print "NULL".
Definition at line 145 of file thrift-util.cc.
ostream& impala::operator<< (ostream & os, const ColumnType & type)
Definition at line 208 of file types.cc.
References impala::ColumnType::DebugString().
std::ostream& impala::operator<< (std::ostream & os, const ColumnType & type)
std::ostream& impala::operator<< (std::ostream & os, const TimestampValue & timestamp_value)
std::ostream& impala::operator<< (std::ostream & os, const Decimal4Value & d) inline
Definition at line 386 of file decimal-value.h.
References impala::DecimalValue< T >::value().
std::ostream& impala::operator<< (std::ostream & os, const Decimal8Value & d) inline
Definition at line 389 of file decimal-value.h.
References impala::DecimalValue< T >::value().
std::ostream& impala::operator<< (std::ostream & os, const TResourceBrokerReservationRequest & request)
std::ostream& impala::operator<< (std::ostream & os, const Decimal16Value & d) inline
Definition at line 392 of file decimal-value.h.
References impala::DecimalValue< T >::value().
std::ostream& impala::operator<< (std::ostream & os, const TResourceBrokerReservationResponse & reservation)
std::ostream& impala::operator<< (std::ostream & os, const TResourceBrokerExpansionRequest & request)
std::ostream& impala::operator<< (std::ostream & os, const TResourceBrokerExpansionResponse & expansion)
ostream& impala::operator<< (ostream & os, const map< TNetworkAddress, llama::TAllocatedResource > & resources)
Definition at line 805 of file resource-broker.cc.
References count.
ostream& impala::operator<< (ostream & os, const TResourceBrokerReservationRequest & request)
Definition at line 816 of file resource-broker.cc.
ostream& impala::operator<< (ostream & os, const TResourceBrokerReservationResponse & reservation)
Definition at line 831 of file resource-broker.cc.
ostream& impala::operator<< (ostream & os, const TResourceBrokerExpansionRequest & request)
Definition at line 838 of file resource-broker.cc.
ostream& impala::operator<< (ostream & os, const TResourceBrokerExpansionResponse & expansion)
Definition at line 846 of file resource-broker.cc.
int64_t impala::ParseCPUFlags (const string & values)
Definition at line 65 of file cpu-info.cc.
References flag_mappings, name, and num_flags.
Referenced by impala::CpuInfo::Init().
bool impala::ParseId (const std::string & s, TUniqueId * id)
Parse 's' into a TUniqueId object. The format of s needs to be the output format from PrintId. (<hi_part>:<low_part>) Returns true if parse succeeded.
bool impala::ParseId (const string & s, TUniqueId * id)
Definition at line 112 of file debug-util.cc.
Referenced by ParseQueryId(), impala::ImpalaServer::QueryHandleToTUniqueId(), TEST(), and impala::ImpalaServer::TExecuteStatementReqToTQueryContext().
int64_t impala::ParseMemString (const char * val, size_t len)
Definition at line 45 of file mem-info.cc.
References impala::StringParser::PARSE_SUCCESS.
Referenced by impala::MemInfo::Init().
static bool impala::ParsePoolTopicKey (const string & topic_key, string * pool_name, string * backend_id) inline static
Definition at line 124 of file admission-controller.cc.
References TOPIC_KEY_DELIMITER, and VLOG_QUERY.
Referenced by impala::AdmissionController::HandleTopicDeletions(), and impala::AdmissionController::HandleTopicUpdates().
Status impala::ParseQueryOptions (const std::string & options, TQueryOptions * query_options)
Parse a "," separated key=value pair of query options and set it in 'query_options'. If the same query option is specified more than once, the last one wins. Return an error if the input is invalid (bad format or invalid query option).
Referenced by impala::ImpalaServer::InitializeConfigVariables(), and impala::ImpalaServer::QueryToTQueryContext().
template<class T > bool impala::ParseString (const string & str, T * val)
Definition at line 184 of file literal.cc.
const PartitionStatusMap& impala::per_partition_status ()
This is safe to call only after Wait()
Definition at line 155 of file coordinator.h.
References per_partition_status_.
static int64_t impala::POPCNT_popcnt_u64 (uint64_t a) inline static
Definition at line 117 of file sse-util.h.
Referenced by impala::BitUtil::Popcount().
void impala::PopulatePathPermissionCache (hdfsFS fs, const std::string & path_str, PermissionCache * permissions_cache) private
bool impala::PrepareCatalogUpdate (TUpdateCatalogRequest * catalog_update)
Gathers all updates to the catalog required once this query has completed execution. Returns true if a catalog update is required, false otherwise. Must only be called after Wait()
Referenced by impala::ImpalaServer::QueryExecState::UpdateCatalog().
std::string impala::PrintAsHex (const char * bytes, int64_t len)
Definition at line 103 of file debug-util.cc.
void impala::PrintBackendInfo () private
Print hdfs split size stats to VLOG_QUERY and details to VLOG_FILE Attaches split size summary to the appropriate runtime profile
std::string impala::PrintBatch (RowBatch * batch)
Definition at line 203 of file debug-util.cc.
References impala::RowBatch::GetRow(), impala::RowBatch::num_rows(), PrintRow(), and impala::RowBatch::row_desc().
std::string impala::PrintEncoding (const parquet::Encoding::type & type)
Referenced by impala::HdfsParquetScanner::ValidateColumn().
void impala::PrintErrorMap (ostream * stream, const ErrorLogMap & errors)
Definition at line 136 of file error-util.cc.
Referenced by PrintErrorMapToString().
void impala::PrintErrorMap (std::ostream * stream, const ErrorLogMap & errors)
Helper method to print the contents of an ErrorMap to a stream.
std::string impala::PrintErrorMapToString (const ErrorLogMap & errors)
Generates a string representation of the error map. Produces the same output as PrintErrorMap, but returns a string instead of using a stream.
Definition at line 153 of file error-util.cc.
References PrintErrorMap().
Referenced by impala::RuntimeState::ErrorLog(), and TEST().
string impala::PrintExecSummary (const TExecSummary & exec_summary)
Print the exec summary as a formatted table.
Definition at line 108 of file summary-util.cc.
References impala::TablePrinter::AddColumn(), impala::TablePrinter::AddRow(), impala::TablePrinter::set_max_output_width(), and impala::TablePrinter::ToString().
Referenced by PrintExecSummary(), and impala::ImpalaServer::UnregisterQuery().
std::string impala::PrintId (const TUniqueId & id, const std::string & separator = ":")
string impala::PrintId (const TUniqueId & id, const string & separator)
Definition at line 97 of file debug-util.cc.
Referenced by impala::QueryResourceMgr::AcquireVcoreResources(), impala::Coordinator::BackendExecState::BackendExecState(), impala::ImpalaServer::CancelInternal(), impala::ImpalaServer::CancelOperation(), impala::StatestoreSubscriber::CheckRegistrationId(), impala::ImpalaServer::close(), impala::ImpalaServer::CloseInsert(), impala::ImpalaServer::CloseOperation(), impala::RuntimeState::CreateCodegen(), impala::Statestore::DoSubscriberUpdate(), impala::ChildQuery::ExecAndFetch(), impala::ImpalaServer::ExpireQueries(), impala::ImpalaServer::fetch(), impala::ImpalaServer::FetchResults(), impala::ImpalaServer::get_results_metadata(), impala::ImpalaServer::get_state(), impala::ImpalaServer::GetExecSummary(), impala::TmpFileMgr::GetFile(), impala::PlanFragmentExecutor::GetNext(), impala::ImpalaServer::GetOperationStatus(), impala::ImpalaServer::GetResultSetMetadata(), impala::ImpalaServer::GetRuntimeProfileStr(), impala::QueryResourceMgr::InitVcoreAcquisition(), impala::ImpalaServer::LogAuditRecord(), operator<<(), impala::PlanFragmentExecutor::Prepare(), impala::HdfsTableSink::Prepare(), impala::ImpalaServer::QueryExecState::QueryExecState(), impala::ImpalaServer::QueryStateToJson(), impala::ImpalaServer::QuerySummaryCallback(), impala::StatestoreSubscriber::Register(), impala::CgroupsMgr::RegisterFragment(), impala::ImpalaServer::RegisterQuery(), impala::Statestore::RegisterSubscriber(), impala::ImpalaServer::ReportExecStatus(), impala::ImpalaServer::SessionsUrlCallback(), impala::ImpalaServer::SetQueryInflight(), impala::Statestore::SubscribersHandler(), impala::ImpalaServer::TUniqueIdToQueryHandle(), impala::CgroupsMgr::UnregisterFragment(), and impala::Statestore::UnregisterSubscriber().
std::string impala::PrintPath (const std::vector< int > & path)
string impala::PrintPath (const vector< int > & path)
Definition at line 211 of file debug-util.cc.
Referenced by impala::HdfsParquetScanner::CreateColumnReaders().
std::string impala::PrintPlanNodeType (const TPlanNodeType::type & type)
Definition at line 157 of file debug-util.cc.
Referenced by impala::ExecNode::ExecNode().
std::string impala::PrintQueryState (const beeswax::QueryState::type & type)
Referenced by impala::ImpalaServer::QueryExecState::Done(), impala::ImpalaServer::QueryExecState::Exec(), and impala::ImpalaServer::QueryExecState::QueryExecState().
std::string impala::PrintRow (TupleRow * row, const RowDescriptor & d)
Definition at line 192 of file debug-util.cc.
References impala::TupleRow::GetTuple(), PrintTuple(), and impala::RowDescriptor::tuple_descriptors().
Referenced by impala::RowBatchList::DebugString(), impala::OldHashTable::DebugString(), impala::HashTable::DebugStringTuple(), impala::HashJoinNode::GetNext(), impala::AggregationNode::GetNext(), impala::AggregationNode::Open(), impala::PartitionedAggregationNode::Open(), impala::PlanFragmentExecutor::OpenInternal(), and PrintBatch().
template<typename T > void impala::PrintSample (const ReservoirSample< T > & v, ostream * os)
Definition at line 914 of file aggregate-functions.cc.
References impala::ReservoirSample< T >::val.
template<> void impala::PrintSample (const ReservoirSample< TinyIntVal > & v, ostream * os)
Definition at line 917 of file aggregate-functions.cc.
References impala_udf::TinyIntVal::val, and impala::ReservoirSample< T >::val.
template<> void impala::PrintSample (const ReservoirSample< StringVal > & v, ostream * os)
Definition at line 922 of file aggregate-functions.cc.
References impala::ReservoirSample< StringVal >::len, and impala::ReservoirSample< StringVal >::val.
template<> void impala::PrintSample (const ReservoirSample< DecimalVal > & v, ostream * os)
Definition at line 928 of file aggregate-functions.cc.
References impala::ReservoirSample< T >::val, and impala_udf::DecimalVal::val16.
template<> void impala::PrintSample (const ReservoirSample< TimestampVal > & v, ostream * os)
Definition at line 933 of file aggregate-functions.cc.
References impala::TimestampValue::DebugString(), impala::TimestampValue::FromTimestampVal(), and impala::ReservoirSample< T >::val.
std::string impala::PrintTCatalogObjectType (const TCatalogObjectType::type & type)
Referenced by impala::ImpalaServer::LogAuditRecord(), and TCatalogObjectToEntryKey().
std::string impala::PrintTCatalogOpType (const TCatalogOpType::type & type)
Referenced by impala::ImpalaServer::QueryExecState::ExecDdlRequest(), and impala::ImpalaServer::LogAuditRecord().
void impala::PrintTColumnValue (const apache::hive::service::cli::thrift::TColumnValue & colval, std::stringstream * out)
Referenced by FinalizePartitionedColumnStats(), and impala::CatalogOpExecutor::SetTableStats().
std::string impala::PrintTDdlType (const TDdlType::type & type)
Referenced by impala::ImpalaServer::QueryExecState::ExecDdlRequest(), and impala::ImpalaServer::LogAuditRecord().
std::string impala::PrintTMetricKind (const TMetricKind::type & type)
Referenced by impala::SimpleMetric< T, metric_kind >::ToJson().
std::string impala::PrintTSessionType (const TSessionType::type & type)
Referenced by impala::ImpalaServer::QueryExecState::QueryExecState(), and impala::ImpalaServer::SessionsUrlCallback().
std::string impala::PrintTStmtType (const TStmtType::type & type)
Referenced by impala::ImpalaServer::QueryExecState::Exec(), and impala::ImpalaServer::LogAuditRecord().
std::string impala::PrintTUnit (const TUnit::type & type)
Referenced by impala::StatsMetric< double >::ToJson(), and impala::SimpleMetric< T, metric_kind >::ToJson().
std::string impala::PrintTuple (const Tuple * t, const TupleDescriptor & d)
Definition at line 166 of file debug-util.cc.
References impala::Tuple::GetSlot(), impala::SlotDescriptor::is_materialized(), impala::Tuple::IsNull(), impala::SlotDescriptor::null_indicator_offset(), impala::TupleDescriptor::slots(), impala::SlotDescriptor::tuple_offset(), and impala::SlotDescriptor::type().
Referenced by impala::BlockingJoinNode::GetLeftChildRowString(), and PrintRow().
void impala::ProcessEscapeMask (uint16_t escape_mask, bool * last_char_is_escape, uint16_t * delim_mask) inline
Updates the values in the field and tuple masks, escaping them if necessary. If the character at n is an escape character, then delimiters(tuple/field/escape characters) at n+1 don't count.
Definition at line 28 of file delimited-text-parser.inline.h.
References impala::SSEUtil::CHARS_PER_128_BIT_REGISTER, and impala::SSEUtil::SSE_BITMASK.
Referenced by impala::DelimitedTextParser::ParseSingleTuple(), and impala::DelimitedTextParser::ParseSse().
static void impala::ProcessQueryOptions (const TQueryOptions & query_options, DebugOptions * debug_options) static
Definition at line 278 of file coordinator.cc.
References impala::DebugOptions::action, impala::DebugOptions::backend_num, GetDebugAction(), GetExecNodePhase(), impala::DebugOptions::node_id, and impala::DebugOptions::phase.
void impala::ProducerThread (InternalQueue< IntNode > * queue, int num_inserts, vector< IntNode > * nodes, AtomicInt< int32_t > * counter, bool * failed)
Definition at line 151 of file internal-queue-test.cc.
References impala::InternalQueue< T >::Enqueue(), impala::InternalQueue< T >::Validate(), and VALIDATE_INTERVAL.
Referenced by TEST().
const ProgressUpdater& impala::progress ()
Definition at line 166 of file coordinator.h.
References progress_.
Referenced by impala::ImpalaServer::QueryStateToJson().
const TUniqueId& impala::query_id () const
Definition at line 152 of file coordinator.h.
References query_id_.
Referenced by impala::ImpalaServer::Cancel(), impala::ImpalaServer::CancelOperation(), impala::ImpalaServer::close(), impala::ImpalaServer::CloseInsert(), impala::ImpalaServer::CloseOperation(), impala::ImpalaServer::CloseSessionInternal(), impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest(), impala::ImpalaServer::ExpireQueries(), impala::ImpalaServer::ExpireSessions(), impala::ImpalaServer::fetch(), impala::ImpalaServer::FetchResults(), impala::ImpalaServer::get_log(), impala::ImpalaServer::get_results_metadata(), impala::ImpalaServer::get_state(), impala::ImpalaServer::GetExecSummary(), impala::ImpalaServer::GetLog(), impala::ImpalaServer::GetOperationStatus(), impala::ResourceBroker::GetQueryResourceMgr(), impala::ImpalaServer::GetResultSetMetadata(), impala::ImpalaServer::GetRuntimeProfile(), impala::ImpalaServer::MembershipCallback(), impala::ImpalaServer::QueryStateToJson(), impala::ImpalaServer::QuerySummaryCallback(), impala::ImpalaServer::RegisterQuery(), impala::ImpalaServer::SetQueryInflight(), impala::ImpalaServer::UnregisterQuery(), and impala::ImpalaServer::QueryExecState::UpdateCatalog().
MemTracker* impala::query_mem_tracker ()
Only valid after Exec(). Returns runtime_state()->query_mem_tracker() if there is a coordinator fragment, or query_mem_tracker_ (initialized in Exec()) otherwise.
Referenced by impala::ImpalaServer::QueryExecState::FetchRowsInternal(), and impala::PlanFragmentExecutor::SendReport().
RuntimeProfile* impala::query_profile () const
Get cumulative profile aggregated over all fragments of the query. This is a snapshot of the current state of execution and will change in the future if not all fragments have finished execution.
Definition at line 150 of file coordinator.h.
References query_profile_.
static TOperationState::type impala::QueryStateToTOperationState (const beeswax::QueryState::type & query_state) static
TOperationState::type impala::QueryStateToTOperationState (const QueryState::type & query_state)
Definition at line 1145 of file impala-hs2-server.cc.
Referenced by impala::ImpalaServer::GetOperationStatus().
template<typename T > DecimalValue<T> impala::RandDecimal (int max_precision)
Definition at line 724 of file decimal-test.cc.
void impala::RandomlyFillString (char * string, const int length)
Randomly fills the contents of 'string' up to the given length.
Definition at line 90 of file redactor-test-utils.h.
References RandSeed().
Referenced by MultiThreadWorkload(), and TEST().
unsigned int impala::RandSeed ()
Definition at line 83 of file redactor-test-utils.h.
Referenced by MultiThreadWorkload(), and RandomlyFillString().
string impala::RecursionStack (int level)
Definition at line 26 of file debug-util-test.cc.
References GetStackTrace().
Referenced by TEST().
void impala::Redact (std::string * string, bool * changed = NULL)
Applies the redaction rules to the given string in-place. If no redaction rules are set, nothing will be done. This is thread-safe as long as multiple calls are not made with the same input string. If the 'changed' argument is not null, it will be set to true if redaction modified 'string'.
void impala::Redact (string * value, bool * changed)
Definition at line 309 of file redactor.cc.
References g_rules.
Referenced by AssertRedactedEquals(), impala::ImpalaServer::Execute(), InitGoogleLoggingSafe(), impala::ImpalaServer::LogAuditRecord(), MultiThreadWorkload(), RedactCopy(), and TEST().
std::string impala::RedactCopy (const std::string & original) inline
Utility function to redacted a string without modifying the original.
Definition at line 63 of file redactor.h.
References Redact().
Referenced by impala::RuntimeProfile::AddInfoString(), PlanToJsonHelper(), PrintExecSummary(), impala::ImpalaServer::QueryStateToJson(), and impala::ImpalaServer::QuerySummaryCallback().
Status impala::RegisterMemoryMetrics (MetricGroup * metrics, bool register_jvm_metrics)
Registers common tcmalloc memory metrics. If register_jvm_metrics is true, the JVM memory metrics are also registered.
Definition at line 34 of file memory-metrics.cc.
References impala::TcmallocMetric::BYTES_IN_USE, impala::MetricGroup::GetChildGroup(), impala::JvmMetric::InitMetrics(), impala::Status::OK, impala::TcmallocMetric::PAGEHEAP_FREE_BYTES, impala::TcmallocMetric::PAGEHEAP_UNMAPPED_BYTES, impala::TcmallocMetric::PHYSICAL_BYTES_RESERVED, impala::MetricGroup::RegisterMetric(), RETURN_IF_ERROR, and impala::TcmallocMetric::TOTAL_BYTES_RESERVED.
Referenced by main(), impala::ExecEnv::StartServices(), and TEST().
void impala::ReportQuerySummary () private
Outputs aggregate query profile summary. This is assumed to be called at the end of a query – remote fragments' profiles must not be updated while this is running.
const RowDescriptor& impala::row_desc () const
Referenced by impala::DataStreamMgr::CreateRecvr().
bool impala::RunShellProcess (const std::string & cmd, std::string * msg)
Runs a shell command. Returns false if there was any error (either failure to launch or non-0 exit code), and true otherwise. *msg is set to an error message including the OS error string, if any, and the first 1k of output if there was any error, or just the first 1k of output otherwise.
Referenced by impala::SaslAuthProvider::RunKinit().
void impala::RunThread (Promise< int64_t > * promise)
Definition at line 44 of file promise-test.cc.
References impala::Promise< T >::Set().
Referenced by TEST().
RuntimeState* impala::runtime_state ()
only valid after calling Exec(), and may return NULL if there is no executor
Referenced by impala::FragmentMgr::FragmentExecState::ReportStatusCb().
template<typename T > bool impala::SampleKeyGreater (const ReservoirSample< T > & i, const ReservoirSample< T > & j)
Definition at line 875 of file aggregate-functions.cc.
References impala::ReservoirSample< T >::key.
template<typename T > bool impala::SampleValLess (const ReservoirSample< T > & i, const ReservoirSample< T > & j)
Definition at line 848 of file aggregate-functions.cc.
References impala::ReservoirSample< T >::val.
template<> bool impala::SampleValLess (const ReservoirSample< StringVal > & i, const ReservoirSample< StringVal > & j)
Definition at line 853 of file aggregate-functions.cc.
References impala::ReservoirSample< StringVal >::len, and impala::ReservoirSample< StringVal >::val.
template<> bool impala::SampleValLess (const ReservoirSample< DecimalVal > & i, const ReservoirSample< DecimalVal > & j)
Definition at line 862 of file aggregate-functions.cc.
References impala::ReservoirSample< T >::val, and impala_udf::DecimalVal::val16.
template<> bool impala::SampleValLess (const ReservoirSample< TimestampVal > & i, const ReservoirSample< TimestampVal > & j)
Definition at line 868 of file aggregate-functions.cc.
References impala_udf::TimestampVal::date, impala_udf::TimestampVal::time_of_day, and impala::ReservoirSample< T >::val.
static int impala::SaslAuthorizeExternal (sasl_conn_t * conn, void * context, const char * requested_user, unsigned rlen, const char * auth_identity, unsigned alen, const char * def_realm, unsigned urlen, struct propctx * propctx) static
Definition at line 406 of file authentication.cc.
Referenced by InitAuth().
static int impala::SaslAuthorizeInternal (sasl_conn_t * conn, void * context, const char * requested_user, unsigned rlen, const char * auth_identity, unsigned alen, const char * def_realm, unsigned urlen, struct propctx * propctx) static
Definition at line 380 of file authentication.cc.
Referenced by InitAuth().
static int impala::SaslGetOption (void * context, const char * plugin_name, const char * option, const char ** result, unsigned * len) static
Definition at line 272 of file authentication.cc.
References IMPALA_AUXPROP_PLUGIN, VLOG_CONNECTION_IS_ON, and VLOG_ROW_IS_ON.
static int impala::SaslGetPath (void * context, const char ** path) static
Definition at line 428 of file authentication.cc.
Referenced by InitAuth().
int impala::SaslLdapCheckPass (sasl_conn_t * conn, void * context, const char * user, const char * pass, unsigned passlen, struct propctx * propctx)
Definition at line 190 of file authentication.cc.
References LDAP_URI_PREFIX, and VLOG_QUERY.
Referenced by InitAuth().
static int impala::SaslLogCallback (void * context, int level, const char * message) static
Definition at line 141 of file authentication.cc.
Referenced by InitAuth().
static int impala::SaslVerifyFile (void * context, const char * file, sasl_verify_type_t type) static
Definition at line 347 of file authentication.cc.
Referenced by InitAuth().
static const string impala::SCHEDULER_INIT_KEY ("simple-scheduler.initialized") static
Referenced by impala::SimpleScheduler::Init().
template<class T > Status impala::SerializeThriftMsg (JNIEnv * env, T * msg, jbyteArray * serialized_msg)
create jbyteArray given buffer
Definition at line 27 of file jni-thrift-util.h.
References impala::Status::OK, RETURN_ERROR_IF_EXC, RETURN_IF_ERROR, and impala::ThriftSerializer::Serialize().
Referenced by CallJniMethod(), impala::JniUtil::CallJniMethod(), Planner::GeneratePlan(), Java_com_cloudera_impala_service_FeSupport_NativeCacheJar(), Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs(), Java_com_cloudera_impala_service_FeSupport_NativeGetStartupOptions(), Java_com_cloudera_impala_service_FeSupport_NativeLookupSymbol(), Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad(), and impala::HiveUdfCall::Open().
Status impala::SetDecimalVal (const ColumnType & type, char * bytes, int len, void * slot) inline
Definition at line 166 of file data-source-scan-node.cc.
References impala::ParquetPlainEncoder::Decode(), ERROR_INVALID_DECIMAL, impala::ColumnType::GetByteSize(), and impala::Status::OK.
Referenced by impala::DataSourceScanNode::MaterializeNextRow().
static void impala::SetDistinctEstimateBit (uint8_t * bitmap, uint32_t row_index, uint32_t bit_index) inline static
Definition at line 588 of file aggregate-functions.cc.
Referenced by impala::AggregateFunctions::PcsaUpdate(), and impala::AggregateFunctions::PcUpdate().
void impala::SetExecPlanFragmentParams (QuerySchedule & schedule, int backend_num, const TPlanFragment & fragment, int fragment_idx, const FragmentExecParams & params, int instance_idx, const TNetworkAddress & coord, TExecPlanFragmentParams * rpc_params) private
Fill in rpc_params based on parameters.
Status impala::SetQueryOption (const std::string & key, const std::string & value, TQueryOptions * query_options)
Set the key/value pair in TQueryOptions. It will override existing setting in query_options.
template<typename T > void impala::SetQueryOption (TImpalaQueryOptions::type opt, const T & opt_val, TExecuteStatementReq * exec_stmt_req)
Definition at line 102 of file child-query.cc.
Referenced by impala::ImpalaServer::QueryExecState::Exec(), impala::ImpalaServer::OpenSession(), and impala::ImpalaServer::TExecuteStatementReqToTQueryContext().
std::string impala::SetRedactionRulesFromFile (const std::string & rules_file_path)
Load redaction rules stored in a file. Returns an error message if problems were encountered while constructing the redaction rules. If no rules were given the message will be empty. This is not thread-safe and should not be called with concurrent calls to Redact(). The rule format is JSON with the following structure: { "version": 1, # required int "rules": [ # required array, rules are executed in order { "description": "", # optional, completely ignored "caseSensitive": true, # optional boolean, default = true, applies to both the
'trigger' and 'search'.
"trigger": "find", # optional string, default = "", rule only goes into
effect if the string to be redacted contains this
value. An empty string matches everything.
"search": "\\d", # required string, regex to search for "replace": "#" # required string, the replacement value for 'search' }, ... ] } Rules are set globally. Having multiple sets of rules in effect at the same time is not supported.
string impala::SetRedactionRulesFromFile (const string & rules_file_path)
Definition at line 260 of file redactor.cc.
References g_rules, NameOfTypeOfJsonValue(), and impala::RulesParser::Parse().
Referenced by InitCommonRuntime(), and TEST().
void impala::ShutdownLogging ()
Shuts down the google logging library. Call before exit to ensure that log files are flushed. May only be called once.
Definition at line 146 of file logging.cc.
References logging_mutex.
Referenced by main().
void impala::SleepForMs (const int64_t duration_ms)
Sleeps the current thread for at least duration_ms milliseconds.
Definition at line 21 of file time.cc.
Referenced by impala::QueryResourceMgr::AcquireVcoreResources(), impala::ImpalaServer::DetectNmFailures(), impala::Statestore::DoSubscriberUpdate(), impala::ImpalaServer::ExpireQueries(), impala::ImpalaServer::ExpireSessions(), impala::ThriftClientImpl::OpenWithRetry(), impala::DataStreamTest::ReadStream(), impala::DataStreamTest::ReadStreamMerging(), impala::StatestoreSubscriber::RecoveryModeChecker(), impala::ResourceBroker::RegisterWithLlama(), impala::DiskIoMgrStress::Run(), impala::SaslAuthProvider::RunKinit(), impala::UtilityFunctions::Sleep(), TEST(), TEST_F(), impala::PeriodicCounterUpdater::UpdateLoop(), and WaitForServer().
static SSE_ALWAYS_INLINE int impala::SSE4_cmpestri (__m128i str1, int len1, __m128i str2, int len2, const int mode) static
Definition at line 99 of file sse-util.h.
Referenced by StringCompare(), StringCompare1(), StringCompare2(), and StringCompare3().
static SSE_ALWAYS_INLINE __m128i impala::SSE4_cmpestrm (__m128i str1, int len1, __m128i str2, int len2, const int mode) static
Use asm reg rather than Yz output constraint to workaround LLVM bug 13199 - clang doesn't support Y-prefixed asm constraints.
Definition at line 89 of file sse-util.h.
Referenced by impala::DelimitedTextParser::FindFirstInstance(), impala::DelimitedTextParser::ParseSingleTuple(), and impala::DelimitedTextParser::ParseSse().
static uint32_t impala::SSE4_crc32_u32 (uint32_t crc, uint32_t v) inline static
Definition at line 112 of file sse-util.h.
Referenced by impala::HashUtil::CrcHash().
static uint32_t impala::SSE4_crc32_u8 (uint32_t crc, uint8_t v) inline static
Definition at line 107 of file sse-util.h.
Referenced by impala::HashUtil::CrcHash().
static const RE2 impala::STARTS_WITH_RE ("\\^([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)(?:\\.\\*)*") static
Referenced by impala::LikePredicate::RegexPrepare().
Status impala::StartThreadInstrumentation (MetricGroup * metrics, Webserver * webserver)
Registers /threadsz with the debug webserver, and creates thread-tracking metrics under the "thread-manager." prefix
Definition at line 266 of file thread.cc.
References thread_manager.
Referenced by main().
void impala::StitchNulls (uint32_t num_rows_before, uint32_t num_rows_added, uint32_t start_idx, const std::string & from, std::string * to)
Combine two null columns by appending 'from' to 'to', starting at 'num_rows_before' in 'from', 'start_idx' in 'to', and proceeding for 'num_rows_added' rows.
Referenced by impala::ImpalaServer::HS2ColumnarResultSet::AddRows(), and TEST().
static int impala::StringCompare (const char * s1, int n1, const char * s2, int n2, int len) inline static
Compare two strings using sse4.2 intrinsics if they are available. This code assumes that the trivial cases are already handled (i.e. one string is empty). Returns: < 0 if s1 < s2 0 if s1 == s2
0 if s1 > s2
The SSE code path is just under 2x faster than the non-sse code path.
s1/n1: ptr/len for the first string
s2/n2: ptr/len for the second string
len: min(n1, n2) - this can be more cheaply passed in by the caller
Definition at line 37 of file string-value.inline.h.
References impala::SSEUtil::CHARS_PER_128_BIT_REGISTER, impala::CpuInfo::IsSupported(), impala::CpuInfo::SSE4_2, SSE4_cmpestri(), and impala::SSEUtil::STRCMP_MODE.
Referenced by impala::StringValue::Compare(), impala::RawValue::Compare(), impala::StringValue::Eq(), impala::RawValue::Eq(), and impala::TextConverter::WriteSlot().
void impala::StringToAllDecimals (const string & s, const ColumnType & t, int32_t val, StringParser::ParseResult result)
Definition at line 61 of file decimal-test.cc.
References VerifyParse().
Referenced by TEST().
static const RE2 impala::SUBSTRING_RE ("(?:\\.\\*)*([^\\.\\^\\{\\[\\(\\|\\)\\]\\}\\+\\*\\?\\$\\\\]*)(?:\\.\\*)*") static
Referenced by impala::LikePredicate::RegexPrepare().
static int impala::sys_perf_event_open (struct perf_event_attr * attr, pid_t pid, int cpu, int group_fd, unsigned long flags) inline static
Definition at line 55 of file perf-counters.cc.
Referenced by impala::PerfCounters::InitSysCounter().
bool impala::TBackendDescriptorComparator (const TBackendDescriptor & a, const TBackendDescriptor & b)
Definition at line 247 of file simple-scheduler.cc.
References TNetworkAddressComparator().
Status impala::TCatalogObjectFromEntryKey (const std::string & key, TCatalogObject * catalog_object)
Parses the given IMPALA_CATALOG_TOPIC topic entry key to determine the TCatalogObjectType and unique object name. Populates catalog_object with the result. This is used to reconstruct type information when an item is deleted from the topic. At that time the only context available about the object being deleted is its its topic entry key which contains only the type and object name. The resulting TCatalogObject can then be used to removing a matching item from the catalog.
Status impala::TCatalogObjectFromEntryKey (const string & key, TCatalogObject * catalog_object)
Definition at line 53 of file catalog-util.cc.
References TCatalogObjectFromObjectName(), and TCatalogObjectTypeFromName().
Referenced by impala::ImpalaServer::CatalogUpdateCallback().
Status impala::TCatalogObjectFromObjectName (const TCatalogObjectType::type & object_type, const std::string & object_name, TCatalogObject * catalog_object)
Populates a TCatalogObject based on the given object type (TABLE, DATABASE, etc) and object name string.
Status impala::TCatalogObjectFromObjectName (const TCatalogObjectType::type & object_type, const string & object_name, TCatalogObject * catalog_object)
Definition at line 68 of file catalog-util.cc.
References impala::Status::OK, and UNKNOWN.
Referenced by impala::CatalogServer::CatalogObjectsUrlCallback(), impala::ImpalaServer::CatalogObjectsUrlCallback(), and TCatalogObjectFromEntryKey().
std::string impala::TCatalogObjectToEntryKey (const TCatalogObject & catalog_object)
Builds and returns the topic entry key string for the given TCatalogObject. The key format is: "TCatalogObjectType:<fully qualified object name>". So a table named "foo" in a database named "bar" would have a key of: "TABLE:bar.foo" Returns an empty string if there were any problem building the key.
Definition at line 149 of file catalog-util.cc.
References PrintTCatalogObjectType().
Referenced by impala::CatalogServer::BuildTopicUpdates().
TCatalogObjectType::type impala::TCatalogObjectTypeFromName (const string & name)
Definition at line 29 of file catalog-util.cc.
References UNKNOWN.
Referenced by impala::CatalogServer::CatalogObjectsUrlCallback(), impala::ImpalaServer::CatalogObjectsUrlCallback(), and TCatalogObjectFromEntryKey().
TCatalogObjectType::type impala::TCatalogObjectTypeFromName (const std::string & name)
Converts a string to the matching TCatalogObjectType enum type. Returns TCatalogObjectType::UNKNOWN if no match was found.
static uint32_t impala::TColumnByteSize (const thrift::TColumn & col, uint32_t start_idx, uint32_t end_idx) static
Definition at line 94 of file impala-hs2-server.cc.
Referenced by impala::ImpalaServer::HS2ColumnarResultSet::ByteSize().
void impala::TColumnValueToHS2TColumn (const TColumnValue & col_val, const TColumnType & type, uint32_t row_idx, apache::hive::service::cli::thrift::TColumn * column)
For V6->
Utility methods for converting from Impala (either an Expr result or a TColumnValue) to Hive types (either a thrift::TColumnValue (V1->V5) or a TColumn (V6->).
Referenced by impala::ImpalaServer::HS2ColumnarResultSet::AddOneRow().
void impala::TColumnValueToHS2TColumnValue (const TColumnValue & col_val, const TColumnType & type, apache::hive::service::cli::thrift::TColumnValue * hs2_col_val)
For V1->V5.
Referenced by impala::ImpalaServer::HS2RowOrientedResultSet::AddOneRow().
impala::TEST (ErrorMsg , GenericFormatting)
Definition at line 24 of file error-util-test.cc.
References impala::ErrorMsg::AddDetail(), impala::ErrorMsg::GetFullMessageDetails(), and impala::ErrorMsg::msg().
impala::TEST (RedactorTest , Unconfigured)
Definition at line 24 of file redactor-unconfigured-test.cc.
References ASSERT_UNREDACTED, and g_rules.
impala::TEST (ParserTest , FileNotFound)
Definition at line 25 of file redactor-config-parser-test.cc.
References ASSERT_ERROR_MESSAGE_CONTAINS, impala::TempRulesFile::Delete(), impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (MemPoolTest , Basic)
Definition at line 25 of file mem-pool-test.cc.
References impala::MemPool::AcquireData(), impala::MemPool::Allocate(), impala::MemPool::Clear(), impala::MemPool::FreeAll(), impala::MemPool::GetTotalChunkSizes(), impala::MemPool::peak_allocated_bytes(), impala::MemPool::total_allocated_bytes(), and tracker.
impala::TEST (MemTestTest , SingleTrackerNoLimit)
Definition at line 25 of file mem-tracker-test.cc.
References impala::MemTracker::Consume(), impala::MemTracker::consumption(), impala::MemTracker::has_limit(), impala::MemTracker::LimitExceeded(), and impala::MemTracker::Release().
impala::TEST (PrettyPrinterTest , Unit)
Definition at line 26 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (FreePoolTest , Basic)
Definition at line 26 of file free-pool-test.cc.
References impala::FreePool::Allocate(), impala::FreePool::Free(), impala::MemPool::FreeAll(), pool, impala::MemPool::total_allocated_bytes(), and tracker.
impala::TEST (PerfCounterTest , Basic)
Definition at line 27 of file perf-counters-test.cc.
References impala::PerfCounters::AddDefaultCounters(), impala::PerfCounters::PrettyPrint(), and impala::PerfCounters::Snapshot().
impala::TEST (AtomicTest , Basic)
Definition at line 28 of file atomic-test.cc.
References impala::AtomicInt< T >::CompareAndSwap(), impala::AtomicInt< T >::CompareAndSwapVal(), impala::AtomicInt< T >::Swap(), impala::AtomicInt< T >::UpdateMax(), and impala::AtomicInt< T >::UpdateMin().
impala::TEST (BlockingQueueTest , TestBasic)
Definition at line 28 of file blocking-queue-test.cc.
References impala::BlockingQueue< T >::BlockingGet(), and impala::BlockingQueue< T >::BlockingPut().
impala::TEST (ThriftUtil , SimpleSerializeDeserialize)
Definition at line 29 of file thrift-util-test.cc.
References DeserializeThriftMsg(), impala::Status::ok(), and impala::ThriftSerializer::Serialize().
impala::TEST (BitUtil , Ceil)
Definition at line 29 of file bit-util-test.cc.
References impala::BitUtil::Ceil().
impala::TEST (ParseMemSpecs , Basic)
Definition at line 30 of file parse-util-test.cc.
References impala::ParseUtil::ParseMemSpec(), and impala::MemInfo::physical_mem().
impala::TEST (StringValueTest , TestCompare)
Definition at line 31 of file string-value-test.cc.
References FromStdString(), NUM_STRINGS, impala::StringValue::PadWithSpaces(), and impala::StringValue::UnpaddedCharLength().
impala::TEST (MultiPrecisionIntTest , Conversion)
Definition at line 31 of file multi-precision-test.cc.
References ConvertToInt128(), and ConvertToInt256().
impala::TEST (StatestoreTest , SmokeTest)
Definition at line 31 of file statestore-test.cc.
References MakeNetworkAddress(), impala::Status::ok(), and impala::InProcessStatestore::Start().
impala::TEST (DebugUtil , StackDump)
Definition at line 31 of file debug-util-test.cc.
References GetStackTrace(), and RecursionStack().
impala::TEST (ParserTest , EmptyFile)
Definition at line 32 of file redactor-config-parser-test.cc.
References ASSERT_ERROR_MESSAGE_CONTAINS, ASSERT_UNREDACTED, g_rules, impala::TempRulesFile::name(), impala::TempRulesFile::OverwriteContents(), and SetRedactionRulesFromFile().
impala::TEST (MemInfo , Basic)
Definition at line 32 of file proc-info-test.cc.
References impala::MemInfo::commit_limit(), impala::MemInfo::physical_mem(), and impala::MemInfo::vm_overcommit().
impala::TEST (CountersTest , Basic)
Definition at line 32 of file runtime-profile-test.cc.
References impala::RuntimeProfile::Counter::Add(), impala::RuntimeProfile::AddChild(), impala::RuntimeProfile::AddCounter(), impala::RuntimeProfile::CreateFromThrift(), impala::RuntimeProfile::GetCounter(), pool, impala::RuntimeProfile::Counter::Set(), impala::RuntimeProfile::ToThrift(), and impala::RuntimeProfile::Counter::value().
impala::TEST (BitArray , TestBool)
Definition at line 33 of file rle-test.cc.
References impala::BitWriter::Flush(), impala::BitReader::GetValue(), and impala::BitWriter::PutValue().
impala::TEST (InternalQueue , TestBasic)
Definition at line 34 of file internal-queue-test.cc.
References impala::InternalQueue< T >::Dequeue(), impala::InternalQueue< T >::empty(), impala::InternalQueue< T >::Enqueue(), impala::InternalQueue< T >::head(), impala::InternalQueue< T >::Node::Next(), impala::InternalQueue< T >::PopBack(), impala::InternalQueue< T >::Node::Prev(), impala::InternalQueue< T >::size(), impala::InternalQueue< T >::tail(), impala::InternalQueue< T >::Validate(), and impala::IntNode::value.
impala::TEST (StringBufferTest , Basic)
Definition at line 34 of file string-buffer-test.cc.
References impala::StringBuffer::Append(), impala::StringBuffer::Assign(), impala::StringBuffer::buffer_size(), impala::StringBuffer::Clear(), impala::MemPool::FreeAll(), pool, tracker, and ValidateString().
impala::TEST (ReadWriteUtil , BigEndian)
Definition at line 35 of file read-write-util-test.cc.
impala::TEST (HdfsFsCacheTest , Basic)
Definition at line 36 of file hdfs-fs-cache-test.cc.
References path(), and ValidateNameNode().
impala::TEST (Auth , PrincipalSubstitution)
Definition at line 36 of file authentication-test.cc.
References GetHostname(), impala::SaslAuthProvider::hostname(), impala::SaslAuthProvider::InitKerberos(), impala::Status::ok(), impala::SaslAuthProvider::principal(), impala::SaslAuthProvider::realm(), impala::SaslAuthProvider::service_name(), and impala::SaslAuthProvider::Start().
impala::TEST (DebugUtil , QueryIdParsing)
Definition at line 36 of file debug-util-test.cc.
References ParseId().
impala::TEST (ParquetVersionTest , Parsing)
Definition at line 37 of file parquet-version-test.cc.
References CheckVersionParse().
impala::TEST (PrettyPrinterTest , UnitPerSecond)
Definition at line 37 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (MemTestTest , SingleTrackerWithLimit)
Definition at line 37 of file mem-tracker-test.cc.
References impala::MemTracker::Consume(), impala::MemTracker::consumption(), impala::MemTracker::has_limit(), impala::MemTracker::LimitExceeded(), and impala::MemTracker::Release().
impala::TEST (ErrorMsg , MergeMap)
Definition at line 38 of file error-util-test.cc.
References count, and MergeErrorMaps().
impala::TEST (ProcessStateInfo , Basic)
Definition at line 39 of file proc-info-test.cc.
References impala::ProcessStateInfo::GetBytes(), and impala::ProcessStateInfo::GetInt().
impala::TEST (ThreadPoolTest , BasicTest)
Definition at line 39 of file thread-pool-test.cc.
References Count(), count, impala::ThreadPool< T >::DrainAndShutdown(), impala::ThreadPool< T >::GetQueueSize(), NUM_THREADS, impala::ThreadPool< T >::Offer(), thread_counters, and thread_mutexes.
impala::TEST (BitUtil , Popcount)
Definition at line 39 of file bit-util-test.cc.
References impala::BitUtil::Popcount(), and impala::BitUtil::PopcountNoHw().
impala::TEST (MetricsTest , CounterMetrics)
Definition at line 41 of file metrics-test.cc.
References impala::MetricGroup::AddCounter(), and AssertValue().
impala::TEST (PlainEncoding , Basic)
Definition at line 41 of file parquet-plain-test.cc.
References impala::StringValue::len, and TestType().
impala::TEST (BlockingQueueTest , TestGetFromShutdownQueue)
Definition at line 42 of file blocking-queue-test.cc.
References impala::BlockingQueue< T >::BlockingGet(), impala::BlockingQueue< T >::BlockingPut(), and impala::BlockingQueue< T >::Shutdown().
impala::TEST (ThreadResourceMgr , BasicTest)
Definition at line 43 of file thread-resource-mgr-test.cc.
References impala::ThreadResourceMgr::ResourcePool::AcquireThreadToken(), impala::NotifiedCounter::counter(), impala::NotifiedCounter::Notify(), impala::ThreadResourceMgr::ResourcePool::num_optional_threads(), impala::ThreadResourceMgr::ResourcePool::num_required_threads(), impala::ThreadResourceMgr::ResourcePool::num_threads(), impala::ThreadResourceMgr::RegisterPool(), impala::ThreadResourceMgr::ResourcePool::ReleaseThreadToken(), impala::ThreadResourceMgr::ResourcePool::ReserveOptionalTokens(), impala::ThreadResourceMgr::ResourcePool::SetThreadAvailableCb(), impala::ThreadResourceMgr::ResourcePool::TryAcquireThreadToken(), and impala::ThreadResourceMgr::UnregisterPool().
impala::TEST (ParserTest , DescriptionPropertyIgnored)
Definition at line 44 of file redactor-config-parser-test.cc.
References ASSERT_REDACTED_EQ, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (PromiseTest , BasicTest)
Definition at line 48 of file promise-test.cc.
References impala::Promise< T >::Get(), and RunThread().
impala::TEST (PrettyPrinterTest , CpuTicks)
Definition at line 49 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (CpuInfoTest , Basic)
Definition at line 49 of file perf-counters-test.cc.
References impala::CpuInfo::DebugString().
impala::TEST (Auth , ValidAuthProviders)
Definition at line 49 of file authentication-test.cc.
References impala::AuthManager::GetInstance().
impala::TEST (BitUtil , TrailingBits)
Definition at line 50 of file bit-util-test.cc.
References impala::BitUtil::TrailingBits().
impala::TEST (MemTestTest , ConsumptionMetric)
Definition at line 51 of file mem-tracker-test.cc.
impala::TEST (BenchmarkTest , Basic)
Definition at line 51 of file benchmark-test.cc.
References impala::MemcpyData::dst, impala::BenchmarkTest::Measure(), impala::MemcpyData::size, impala::MemcpyData::src, and TestFunction().
impala::TEST (DiskInfoTest , Basic)
Definition at line 53 of file perf-counters-test.cc.
References impala::DiskInfo::DebugString(), impala::DiskInfo::device_name(), and impala::DiskInfo::disk_id().
impala::TEST (PrettyPrinterTest , Bytes)
Definition at line 55 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (PromiseTest , TimeoutTest)
Definition at line 55 of file promise-test.cc.
References impala::Promise< T >::Get(), MonotonicMillis(), and RunThread().
impala::TEST (DelimitedTextParser , Basic)
Definition at line 55 of file delimited-text-parser-test.cc.
References Validate().
impala::TEST (ZigzagTest , Basic)
Definition at line 56 of file zigzag-test.cc.
References impala::HashUtil::Hash(), TestZInt(), and TestZLong().
impala::TEST (Auth , LdapAuth)
Definition at line 56 of file authentication-test.cc.
References impala::AuthManager::GetExternalAuthProvider(), impala::AuthManager::GetInstance(), impala::AuthManager::GetInternalAuthProvider(), and impala::AuthProvider::is_sasl().
impala::TEST (ParserTest , InvalidJson)
Definition at line 57 of file redactor-config-parser-test.cc.
References ASSERT_ERROR_MESSAGE_CONTAINS, impala::TempRulesFile::name(), impala::TempRulesFile::OverwriteContents(), and SetRedactionRulesFromFile().
impala::TEST (MetricsTest , GaugeMetrics)
Definition at line 57 of file metrics-test.cc.
References impala::MetricGroup::AddGauge(), and AssertValue().
impala::TEST (ErrorMsg , CountErrors)
Definition at line 60 of file error-util-test.cc.
References ErrorCount().
impala::TEST (RedactorTest , NoTrigger)
Definition at line 61 of file redactor-test.cc.
References ASSERT_REDACTED_EQ, ASSERT_UNREDACTED, g_rules, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (ParallelExecutorTest , Basic)
Definition at line 61 of file parallel-executor-test.cc.
References impala::ParallelExecutor::Exec(), impala::Status::ok(), impala::ParallelExecutorTest::UpdateFunction(), and impala::ParallelExecutorTest::Validate().
impala::TEST (DebugUtil , PreCDH5QueryIdParsing)
Definition at line 61 of file debug-util-test.cc.
References ParseId().
impala::TEST (ParquetVersionTest , Comparisons)
Definition at line 64 of file parquet-version-test.cc.
References impala::HdfsParquetScanner::FileVersion::VersionEq(), and impala::HdfsParquetScanner::FileVersion::VersionLt().
impala::TEST (DictTest , TestStrings)
Definition at line 64 of file dict-test.cc.
References ValidateDict().
impala::TEST (BitUtil , ByteSwap)
Definition at line 64 of file bit-util-test.cc.
References impala::BitUtil::ByteSwap().
impala::TEST (SymbolsUtil , Demangling)
Definition at line 64 of file symbols-util-test.cc.
References TestDemangling().
impala::TEST (StringSearchTest , Basic)
Definition at line 68 of file string-search-test.cc.
References TestSearch().
impala::TEST (IntToDecimal , Basic)
Definition at line 68 of file decimal-test.cc.
References impala::ColumnType::CreateDecimalType(), impala::DecimalValue< int128_t >::FromInt(), and VerifyToString().
impala::TEST (UrlCodingTest , Basic)
Definition at line 69 of file url-coding-test.cc.
References TestUrl().
impala::TEST (PrettyPrinterTest , BytesPerSecond)
Definition at line 70 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (ErrorMsg , AppendError)
Definition at line 71 of file error-util-test.cc.
References AppendError(), and ErrorCount().
impala::TEST (ThriftUtil , TNetworkAddressComparator)
Definition at line 71 of file thrift-util-test.cc.
References MakeNetworkAddress(), and TNetworkAddressComparator().
impala::TEST (MetricsTest , PropertyMetrics)
Definition at line 73 of file metrics-test.cc.
References impala::MetricGroup::AddProperty(), and AssertValue().
impala::TEST (PromiseDeathTest , RepeatedSetTest)
Definition at line 74 of file promise-test.cc.
References impala::Promise< T >::Set().
impala::TEST (UrlCodingTest , HiveExceptions)
Definition at line 75 of file url-coding-test.cc.
References TestUrl().
impala::TEST (MultiPrecisionIntTest , HighLowBits)
Definition at line 77 of file multi-precision-test.cc.
References HighBits(), and LowBits().
impala::TEST (UrlCodingTest , BlankString)
Definition at line 79 of file url-coding-test.cc.
References TestUrl().
impala::TEST (Auth , LdapKerbAuth)
Definition at line 79 of file authentication-test.cc.
References env_keytab, env_princ, impala::AuthManager::GetExternalAuthProvider(), impala::AuthManager::GetInstance(), impala::AuthManager::GetInternalAuthProvider(), and impala::AuthProvider::is_sasl().
impala::TEST (RedactorTest , Trigger)
Definition at line 81 of file redactor-test.cc.
References ASSERT_REDACTED_EQ, ASSERT_UNREDACTED, g_rules, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (ErrorMsg , PrintMap)
Definition at line 83 of file error-util-test.cc.
References PrintErrorMapToString().
impala::TEST (SymbolsUtil , DemanglingNameOnly)
Definition at line 83 of file symbols-util-test.cc.
References TestDemangling(), and TestDemanglingNameOnly().
impala::TEST (UrlCodingTest , PathSeparators)
Definition at line 84 of file url-coding-test.cc.
References TestUrl().
impala::TEST (PrettyPrinterTest , Seconds)
Definition at line 85 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (DictTest , TestTimestamps)
Definition at line 86 of file dict-test.cc.
References impala::ParquetPlainEncoder::ByteSize(), TYPE_TIMESTAMP, and ValidateDict().
impala::TEST (BitUtil , Log2)
Definition at line 86 of file bit-util-test.cc.
References impala::BitUtil::Log2().
impala::TEST (MetricsTest , NonFiniteValues)
Definition at line 87 of file metrics-test.cc.
References impala::MetricGroup::AddGauge(), and AssertValue().
impala::TEST (DoubleToDecimal , Basic)
Definition at line 88 of file decimal-test.cc.
References impala::ColumnType::CreateDecimalType(), impala::DecimalValue< int32_t >::FromDouble(), impala::DecimalValue< int64_t >::FromDouble(), impala::DecimalValue< int128_t >::FromDouble(), impala::DecimalValue< T >::value(), and VerifyToString().
impala::TEST (MultiPrecisionIntTest , Example)
Definition at line 89 of file multi-precision-test.cc.
impala::TEST (Base64Test , Basic)
Definition at line 89 of file url-coding-test.cc.
References TestBase64().
impala::TEST (AtomicTest , TestAndSet)
Definition at line 90 of file atomic-test.cc.
References impala::AtomicInt< T >::FetchAndUpdate(), and impala::AtomicInt< T >::UpdateAndFetch().
impala::TEST (PlainEncoding , DecimalBigEndian)
Definition at line 90 of file parquet-plain-test.cc.
References impala::ParquetPlainEncoder::Encode().
impala::TEST (MemTestTest , TrackerHierarchy)
Definition at line 92 of file mem-tracker-test.cc.
References impala::MemTracker::AnyLimitExceeded(), impala::MemTracker::Consume(), impala::MemTracker::consumption(), impala::MemTracker::LimitExceeded(), and impala::MemTracker::Release().
impala::TEST (FreePoolTest , Loop)
Definition at line 94 of file free-pool-test.cc.
References impala::FreePool::Allocate(), impala::FreePool::Free(), impala::MemPool::FreeAll(), pool, impala::MemPool::total_allocated_bytes(), and tracker.
impala::TEST (RedactorTest , MultiTrigger)
Definition at line 97 of file redactor-test.cc.
References ASSERT_REDACTED_EQ, g_rules, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (BitUtil , RoundUpToPowerOf2)
Definition at line 97 of file bit-util-test.cc.
References impala::BitUtil::RoundUpToPowerOf2().
impala::TEST (HtmlEscapingTest , Basic)
Definition at line 98 of file url-coding-test.cc.
References EscapeForHtml().
impala::TEST (SymbolsUtil , Mangling)
Definition at line 98 of file symbols-util-test.cc.
References impala::ColumnType::CreateCharType(), TestMangling(), TYPE_BIGINT, TYPE_BOOLEAN, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, and TYPE_TINYINT.
impala::TEST (MetricsTest , SetMetrics)
Definition at line 98 of file metrics-test.cc.
References impala::SetMetric< T >::Add(), impala::MetricGroup::RegisterMetric(), impala::SetMetric< T >::Remove(), and impala::SetMetric< T >::ToHumanReadable().
impala::TEST (PrettyPrinterTest , NanoSeconds)
Definition at line 99 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (ParserTest , BadVersion)
Definition at line 101 of file redactor-config-parser-test.cc.
References ASSERT_ERROR_MESSAGE_CONTAINS, impala::TempRulesFile::name(), impala::TempRulesFile::OverwriteContents(), and SetRedactionRulesFromFile().
impala::TEST (BitUtil , RoundDownToPowerOf2)
Definition at line 103 of file bit-util-test.cc.
References impala::BitUtil::RoundDownToPowerOf2().
impala::TEST (CountersTest , MergeAndUpdate)
Definition at line 104 of file runtime-profile-test.cc.
References impala::RuntimeProfile::Counter::Add(), impala::RuntimeProfile::AddChild(), impala::RuntimeProfile::AddCounter(), impala::RuntimeProfile::GetChildren(), impala::RuntimeProfile::name(), impala::RuntimeProfile::num_counters(), pool, impala::RuntimeProfile::PrettyPrint(), impala::RuntimeProfile::ToThrift(), impala::RuntimeProfile::Update(), impala::RuntimeProfile::UpdateAverage(), and ValidateCounter().
impala::TEST (PrettyPrinterTest , DoubleValue)
Definition at line 105 of file pretty-printer-test.cc.
References impala::PrettyPrinter::Print().
impala::TEST (BitUtil , RoundUpDown)
Definition at line 109 of file bit-util-test.cc.
References impala::BitUtil::RoundDownNumBytes(), impala::BitUtil::RoundDownNumi32(), impala::BitUtil::RoundDownNumi64(), impala::BitUtil::RoundUpNumBytes(), impala::BitUtil::RoundUpNumi32(), and impala::BitUtil::RoundUpNumi64().
impala::TEST (MultiPrecisionFloatTest , Example)
Definition at line 109 of file multi-precision-test.cc.
References area_of_a_circle().
impala::TEST (PrettyPrinterTest , StringList)
Definition at line 109 of file pretty-printer-test.cc.
impala::TEST (DelimitedTextParser , Fields)
Definition at line 111 of file delimited-text-parser-test.cc.
References Validate().
impala::TEST (RedactorTest , CaseSensitivityProperty)
Definition at line 113 of file redactor-test.cc.
References ASSERT_REDACTED_EQ, ASSERT_UNREDACTED, impala::TempRulesFile::name(), impala::TempRulesFile::OverwriteContents(), and SetRedactionRulesFromFile().
impala::TEST (MetricsTest , StatsMetrics)
Definition at line 114 of file metrics-test.cc.
References impala::MetricGroup::RegisterMetric(), impala::StatsMetric< T >::ToHumanReadable(), and impala::StatsMetric< T >::Update().
impala::TEST (MemPoolTest , Offsets)
Definition at line 115 of file mem-pool-test.cc.
References impala::MemPool::Allocate(), impala::MemPool::FreeAll(), impala::MemPool::GetCurrentOffset(), impala::MemPool::GetDataPtr(), impala::MemPool::GetOffset(), offset, and tracker.
impala::TEST (InternalQueue , TestRemove)
Definition at line 116 of file internal-queue-test.cc.
References impala::InternalQueue< T >::Dequeue(), impala::InternalQueue< T >::Enqueue(), impala::InternalQueue< T >::Remove(), impala::InternalQueue< T >::size(), impala::InternalQueue< T >::Validate(), and impala::IntNode::value.
impala::TEST (AtomicTest , MultipleThreadsIncDec)
Definition at line 118 of file atomic-test.cc.
References DecrementThread(), and IncrementThread().
impala::TEST (BitArray , TestValues)
Definition at line 120 of file rle-test.cc.
References MAX_WIDTH, and TestBitArrayValues().
impala::TEST (DictTest , TestNumbers)
Definition at line 128 of file dict-test.cc.
References impala::ParquetPlainEncoder::ByteSize(), TYPE_BIGINT, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, and TYPE_TINYINT.
impala::TEST (BitArray , TestMixed)
Definition at line 131 of file rle-test.cc.
References impala::BitWriter::Flush(), impala::BitReader::GetValue(), and impala::BitWriter::PutValue().
impala::TEST (BlockingQueueTest , TestMultipleThreads)
Definition at line 133 of file blocking-queue-test.cc.
References impala::MultiThreadTest::Run().
impala::TEST (ParserTest , BadRegex)
Definition at line 139 of file redactor-config-parser-test.cc.
References ASSERT_ERROR_MESSAGE_CONTAINS, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (MetricsTest , MemMetric)
Definition at line 140 of file metrics-test.cc.
References impala::MetricGroup::FindMetricForTesting(), and RegisterMemoryMetrics().
impala::TEST (StringToInt , Basic)
Definition at line 141 of file string-parser-test.cc.
References impala::StringParser::PARSE_SUCCESS.
impala::TEST (FreePoolTest , ReAlloc)
Definition at line 143 of file free-pool-test.cc.
References impala::FreePool::Allocate(), impala::MemPool::FreeAll(), pool, impala::FreePool::Reallocate(), impala::MemPool::total_allocated_bytes(), and tracker.
impala::TEST (MemTestTest , GcFunctions)
Definition at line 145 of file mem-tracker-test.cc.
References impala::MemTracker::AddGcFunction(), impala::MemTracker::Consume(), impala::MemTracker::consumption(), impala::GcFunctionHelper::GcFunc(), impala::MemTracker::has_limit(), impala::MemTracker::LimitExceeded(), and impala::MemTracker::TryConsume().
impala::TEST (MemPoolTest , Keep)
Definition at line 147 of file mem-pool-test.cc.
References impala::MemPool::AcquireData(), impala::MemPool::Allocate(), impala::MemPool::Clear(), impala::MemPool::FreeAll(), impala::MemPool::GetTotalChunkSizes(), impala::MemPool::total_allocated_bytes(), and tracker.
impala::TEST (ParserTest , BadCaseSensitivtyValue)
Definition at line 151 of file redactor-config-parser-test.cc.
References ASSERT_ERROR_MESSAGE_CONTAINS, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (ParserTest , RuleNumberInErrorMessage)
Definition at line 163 of file redactor-config-parser-test.cc.
References ASSERT_ERROR_MESSAGE_CONTAINS, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (StringToInt , InvalidLeadingTrailing)
Definition at line 168 of file string-parser-test.cc.
References impala::StringParser::PARSE_FAILURE.
impala::TEST (AtomicTest , MultipleThreadsCASIncDec)
Definition at line 171 of file atomic-test.cc.
References CASDecrementThread(), and CASIncrementThread().
impala::TEST (MetricsTest , JvmMetrics)
Definition at line 173 of file metrics-test.cc.
References impala::MetricGroup::FindMetricForTesting(), impala::MetricGroup::GetChildGroup(), and RegisterMemoryMetrics().
impala::TEST (MemPoolTest , ReturnPartial)
Definition at line 174 of file mem-pool-test.cc.
References impala::MemPool::Allocate(), impala::MemPool::FreeAll(), impala::MemPool::ReturnPartialAllocation(), impala::MemPool::total_allocated_bytes(), and tracker.
impala::TEST (InternalQueue , TestClear)
Definition at line 185 of file internal-queue-test.cc.
References impala::InternalQueue< T >::Clear(), impala::InternalQueue< T >::empty(), impala::InternalQueue< T >::Enqueue(), impala::InternalQueue< T >::size(), and impala::InternalQueue< T >::Validate().
impala::TEST (StringToDecimal , Basic)
Definition at line 186 of file decimal-test.cc.
References impala::ColumnType::CreateDecimalType(), impala::StringParser::PARSE_FAILURE, impala::StringParser::PARSE_OVERFLOW, impala::StringParser::PARSE_SUCCESS, impala::StringParser::PARSE_UNDERFLOW, and StringToAllDecimals().
impala::TEST (StringToInt , Limit)
Definition at line 188 of file string-parser-test.cc.
References impala::StringParser::PARSE_SUCCESS.
impala::TEST (MetricsJsonTest , Counters)
Definition at line 197 of file metrics-test.cc.
References impala::MetricGroup::AddCounter(), AssertJson(), and impala::MetricGroup::ToJson().
impala::TEST (Rle , SpecificSequences)
Definition at line 201 of file rle-test.cc.
References impala::BitUtil::Ceil(), MAX_WIDTH, and ValidateRle().
impala::TEST (StringToInt , Overflow)
Definition at line 201 of file string-parser-test.cc.
References impala::StringParser::PARSE_OVERFLOW.
impala::TEST (InternalQueue , TestSingleProducerSingleConsumer)
Definition at line 204 of file internal-queue-test.cc.
References ConsumerThread(), impala::InternalQueue< T >::empty(), ProducerThread(), and impala::InternalQueue< T >::size().
impala::TEST (MetricsJsonTest , Gauges)
Definition at line 208 of file metrics-test.cc.
References impala::MetricGroup::AddGauge(), AssertJson(), and impala::MetricGroup::ToJson().
impala::TEST (RedactorTest , SingleTriggerMultiRule)
Definition at line 209 of file redactor-test.cc.
References ASSERT_REDACTED_EQ, ASSERT_UNREDACTED, g_rules, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (StringToInt , Int8_Exhaustive)
Definition at line 214 of file string-parser-test.cc.
References impala::StringParser::PARSE_OVERFLOW, and impala::StringParser::PARSE_SUCCESS.
impala::TEST (MetricsJsonTest , Properties)
Definition at line 218 of file metrics-test.cc.
References impala::MetricGroup::AddProperty(), AssertJson(), and impala::MetricGroup::ToJson().
impala::TEST (MemPoolTest , Limits)
Definition at line 219 of file mem-pool-test.cc.
References impala::MemPool::Allocate(), impala::MemTracker::AnyLimitExceeded(), impala::MemPoolTest::CheckIntegrity(), impala::MemTracker::consumption(), impala::MemPool::FreeAll(), and impala::MemTracker::LimitExceeded().
impala::TEST (CountersTest , DerivedCounters)
Definition at line 225 of file runtime-profile-test.cc.
References impala::RuntimeProfile::AddCounter(), impala::RuntimeProfile::AddDerivedCounter(), pool, impala::RuntimeProfile::Counter::Set(), impala::RuntimeProfile::UnitsPerSecond(), impala::RuntimeProfile::Counter::value(), and impala::RuntimeProfile::DerivedCounter::value().
impala::TEST (RedactorTest , RuleOrder)
Definition at line 225 of file redactor-test.cc.
References ASSERT_REDACTED_EQ, ASSERT_UNREDACTED, g_rules, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (TimestampTest , Basic)
Definition at line 225 of file timestamp-test.cc.
References impala::TimestampValue::date(), impala_udf::DebugString(), impala::TimestampTC::expected_day, impala::TimestampTC::expected_fraction, impala::TimestampTC::expected_hours, impala::TimestampTC::expected_minutes, impala::TimestampTC::expected_month, impala::TimestampTC::expected_seconds, impala::TimestampTC::expected_year, impala::TimestampTC::fmt, impala::TimestampFormatTC::fmt, impala::TimestampTC::fmt_has_date_toks, impala::TimestampTC::fmt_has_time_toks, impala::DateTimeFormatContext::fmt_len, impala::DateTimeFormatContext::fmt_out_len, impala::TimestampTC::fmt_should_fail, impala::TimestampValue::Format(), impala::RawValue::GetHashValue(), impala::TimestampValue::HasDate(), impala::TimestampValue::HasTime(), impala::StringParser::PARSE_SUCCESS, impala::TimestampParser::ParseFormatTokens(), impala::TimestampTC::should_format, impala::TimestampTC::str, impala::TimestampFormatTC::str, impala::TimestampTC::str_should_fail, TestTimestampTokens(), impala::TimestampValue::time(), impala::TimestampValue::ToUnixTime(), impala::TimestampFormatTC::ts, TYPE_TIMESTAMP, and YEAR.
impala::TEST (InternalQueue , TestMultiProducerMultiConsumer)
Definition at line 229 of file internal-queue-test.cc.
References ConsumerThread(), impala::InternalQueue< T >::empty(), and ProducerThread().
impala::TEST (MetricsJsonTest , SetMetrics)
Definition at line 229 of file metrics-test.cc.
References AssertJson(), impala::MetricGroup::RegisterMetric(), and impala::MetricGroup::ToJson().
impala::TEST (StringToIntWithBase , Basic)
Definition at line 229 of file string-parser-test.cc.
References impala::StringParser::PARSE_SUCCESS.
impala::TEST (CountersTest , AverageSetCounters)
Definition at line 247 of file runtime-profile-test.cc.
References impala::RuntimeProfile::AddCounter(), impala::RuntimeProfile::Counter::double_value(), pool, impala::RuntimeProfile::Counter::Set(), impala::RuntimeProfile::AveragedCounter::UpdateCounter(), and impala::RuntimeProfile::Counter::value().
impala::TEST (MetricsJsonTest , StatsMetrics)
Definition at line 248 of file metrics-test.cc.
References AssertJson(), impala::MetricGroup::RegisterMetric(), impala::MetricGroup::ToJson(), and impala::StatsMetric< T >::Update().
impala::TEST (RedactorTest , InputSize)
Definition at line 253 of file redactor-test.cc.
References ASSERT_UNREDACTED, impala::TempRulesFile::name(), RandomlyFillString(), Redact(), and SetRedactionRulesFromFile().
impala::TEST (StringToDecimal , LargeDecimals)
Definition at line 258 of file decimal-test.cc.
References impala::ColumnType::CreateDecimalType(), impala::DecimalUtil::MAX_UNSCALED_DECIMAL, impala::StringParser::PARSE_OVERFLOW, impala::StringParser::PARSE_SUCCESS, impala::StringParser::PARSE_UNDERFLOW, StringToAllDecimals(), and VerifyParse().
impala::TEST (Rle , TestValues)
Definition at line 259 of file rle-test.cc.
References MAX_WIDTH, and TestRleValues().
impala::TEST (StringToIntWithBase , NonNumericCharacters)
Definition at line 265 of file string-parser-test.cc.
References impala::StringParser::PARSE_FAILURE, and impala::StringParser::PARSE_SUCCESS.
impala::TEST (Rle , BitWidthZeroRepeated)
Definition at line 268 of file rle-test.cc.
References impala::RleDecoder::Get().
impala::TEST (MetricsJsonTest , UnitsAndDescription)
Definition at line 269 of file metrics-test.cc.
References impala::MetricGroup::AddCounter(), AssertJson(), and impala::MetricGroup::ToJson().
impala::TEST (RedactorTest , ChangeInputSize)
Definition at line 276 of file redactor-test.cc.
References ASSERT_REDACTED_EQ, impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (MetricGroupTest , JsonTest)
Definition at line 280 of file metrics-test.cc.
References impala::MetricGroup::AddCounter(), impala::MetricGroup::FindMetricForTesting(), impala::MetricGroup::GetChildGroup(), and impala::MetricGroup::ToJson().
impala::TEST (Rle , BitWidthZeroLiteral)
Definition at line 282 of file rle-test.cc.
References impala::RleDecoder::Get().
impala::TEST (SymbolsUtil , ManglingPrepareOrClose)
Definition at line 284 of file symbols-util-test.cc.
References TestManglingPrepareOrClose().
impala::TEST (StringToIntWithBase , Limit)
Definition at line 289 of file string-parser-test.cc.
References impala::StringParser::PARSE_SUCCESS.
impala::TEST (RedactorTest , MultiThreaded)
Definition at line 293 of file redactor-test.cc.
References MultiThreadWorkload(), impala::TempRulesFile::name(), and SetRedactionRulesFromFile().
impala::TEST (CountersTest , InfoStringTest)
Definition at line 296 of file runtime-profile-test.cc.
References impala::RuntimeProfile::AddInfoString(), impala::RuntimeProfile::CreateFromThrift(), impala::RuntimeProfile::GetInfoString(), pool, impala::RuntimeProfile::ToThrift(), and impala::RuntimeProfile::Update().
impala::TEST (BitRle , Flush)
Definition at line 299 of file rle-test.cc.
References ValidateRle().
impala::TEST (StringToIntWithBase , Overflow)
Definition at line 302 of file string-parser-test.cc.
References impala::StringParser::PARSE_OVERFLOW.
impala::TEST (BitRle , Random)
Definition at line 313 of file rle-test.cc.
References MAX_WIDTH, and ValidateRle().
impala::TEST (StringToIntWithBase , Int8_Exhaustive)
Definition at line 315 of file string-parser-test.cc.
References impala::StringParser::PARSE_OVERFLOW, and impala::StringParser::PARSE_SUCCESS.
impala::TEST (StringToFloat , Basic)
Definition at line 330 of file string-parser-test.cc.
References impala::StringParser::PARSE_FAILURE, impala::StringParser::PARSE_OVERFLOW, impala::StringParser::PARSE_SUCCESS, and TestAllFloatVariants().
impala::TEST (BitRle , RepeatedPattern)
Definition at line 336 of file rle-test.cc.
References ValidateRle().
impala::TEST (CountersTest , RateCounters)
Definition at line 337 of file runtime-profile-test.cc.
References impala::RuntimeProfile::AddCounter(), impala::RuntimeProfile::AddRateCounter(), pool, impala::RuntimeProfile::Counter::Set(), impala::PeriodicCounterUpdater::StopRateCounter(), impala::RuntimeProfile::Counter::unit(), and impala::RuntimeProfile::Counter::value().
impala::TEST (BitRle , Overflow)
Definition at line 359 of file rle-test.cc.
References impala::RleEncoder::Flush(), impala::RleDecoder::Get(), impala::RleEncoder::MinBufferSize(), and impala::RleEncoder::Put().
impala::TEST (CountersTest , BucketCounters)
Definition at line 374 of file runtime-profile-test.cc.
References impala::ObjectPool::Add(), impala::RuntimeProfile::AddCounter(), pool, impala::RuntimeProfile::RegisterBucketingCounters(), impala::RuntimeProfile::Counter::Set(), and impala::PeriodicCounterUpdater::StopBucketingCounters().
impala::TEST (DecimalTest , Overflow)
Definition at line 382 of file decimal-test.cc.
References impala::DecimalValue< T >::Add(), impala::ColumnType::CreateDecimalType(), impala::DecimalUtil::MAX_UNSCALED_DECIMAL, impala::DecimalValue< T >::Mod(), impala::DecimalValue< T >::Subtract(), and impala::DecimalValue< T >::value().
impala::TEST (CountersTest , EventSequences)
Definition at line 410 of file runtime-profile-test.cc.
References impala::RuntimeProfile::AddEventSequence(), impala::RuntimeProfile::CreateFromThrift(), events, impala::RuntimeProfile::EventSequence::GetEvents(), impala::RuntimeProfile::EventSequence::MarkEvent(), pool, and impala::RuntimeProfile::ToThrift().
impala::TEST (StringToFloat , InvalidLeadingTrailing)
Definition at line 430 of file string-parser-test.cc.
References impala::StringParser::PARSE_FAILURE.
impala::TEST (StringToFloat , BruteForce)
Definition at line 450 of file string-parser-test.cc.
impala::TEST (StringToBool , Basic)
Definition at line 455 of file string-parser-test.cc.
References impala::StringParser::PARSE_FAILURE, impala::StringParser::PARSE_SUCCESS, and TestBoolValue().
impala::TEST (CountersTest , StreamingSampler)
Definition at line 470 of file runtime-profile-test.cc.
References impala::StreamingSampler< T, MAX_SAMPLES >::AddSample(), gen_ir_descriptions::idx, and ValidateSampler().
impala::TEST (DecimalTest , MultiplyScaleOverflow)
Definition at line 552 of file decimal-test.cc.
References impala::ColumnType::CreateDecimalType(), impala::DecimalValue< T >::Multiply(), and impala::DecimalValue< T >::value().
impala::TEST (DecimalArithmetic , Basic)
Definition at line 619 of file decimal-test.cc.
References impala::DecimalValue< T >::Add(), ADD, impala::ColumnType::CreateDecimalType(), GetResultType(), impala::DecimalValue< T >::Multiply(), MULTIPLY, impala::ColumnType::scale, impala::DecimalValue< T >::Subtract(), impala::DecimalValue< T >::ToDouble(), and VerifyFuzzyEquals().
impala::TEST (DecimalArithmetic , Divide)
Definition at line 648 of file decimal-test.cc.
References impala::ColumnType::CreateDecimalType(), impala::DecimalValue< T >::Divide(), DIVIDE, GetResultType(), MAX_ERROR, impala::ColumnType::scale, impala::DecimalValue< T >::ToDouble(), and impala::DecimalValue< T >::ToString().
impala::TEST (DecimalArithmetic , DivideLargeScales)
Definition at line 700 of file decimal-test.cc.
References impala::ColumnType::CreateDecimalType(), impala::DecimalValue< T >::Divide(), DIVIDE, GetResultType(), impala::ColumnType::scale, and VerifyToString().
impala::TEST (DecimalArithmetic , RandTesting)
Definition at line 741 of file decimal-test.cc.
References impala::DecimalValue< T >::Add(), ADD, impala::DecimalValue< T >::Compare(), impala::ColumnType::CreateDecimalType(), impala::DecimalValue< T >::Divide(), DIVIDE, DoubleCompare(), GetResultType(), impala::DecimalValue< T >::Multiply(), MULTIPLY, impala::ColumnType::scale, impala::DecimalValue< T >::Subtract(), impala::DecimalValue< T >::ToDouble(), and VerifyFuzzyEquals().
impala::TEST_F (RawValueTest , Compare)
Definition at line 28 of file raw-value-test.cc.
References impala::RawValue::Compare(), TYPE_BIGINT, TYPE_INT, and TYPE_SMALLINT.
impala::TEST_F (RawValueTest , TypeChar)
Definition at line 48 of file raw-value-test.cc.
References impala::RawValue::Compare(), impala::ColumnType::CreateCharType(), and impala::RawValue::PrintValue().
impala::TEST_F (InstructionCounterTest , Count)
Definition at line 69 of file instruction-counter-test.cc.
References CodegenMulAdd(), impala::InstructionCounter::GetCount(), impala::InstructionCounter::PrintCounters(), impala::InstructionCounter::ResetCount(), and impala::InstructionCounter::visit().
impala::TEST_F (SimpleSchedulerTest , LocalMatches)
Definition at line 76 of file simple-scheduler-test.cc.
References backends.
impala::TEST_F (LlvmCodeGenTest , BasicLifetime)
Definition at line 80 of file llvm-codegen-test.cc.
impala::TEST_F (LlvmCodeGenTest , MultithreadedLifetime)
Definition at line 85 of file llvm-codegen-test.cc.
References NUM_THREADS.
impala::TEST_F (RowBatchListTest , BasicTest)
Definition at line 92 of file row-batch-list-test.cc.
References impala::RowBatchList::AddRowBatch(), and impala::RowBatchList::total_num_rows().
impala::TEST_F (LlvmCodeGenTest , BadIRFile)
Definition at line 95 of file llvm-codegen-test.cc.
References impala::Status::ok(), and pool.
impala::TEST_F (SimpleSchedulerTest , HostnameTest)
Definition at line 96 of file simple-scheduler-test.cc.
References backends.
impala::TEST_F (RowBatchListTest , EmptyBatchTest)
Definition at line 103 of file row-batch-list-test.cc.
References impala::RowBatchList::AddRowBatch(), impala::RowBatchList::Iterator(), and impala::RowBatchList::total_num_rows().
impala::TEST_F (RowBatchListTest , MultipleRowBatchesTest)
Definition at line 114 of file row-batch-list-test.cc.
References impala::RowBatchList::AddRowBatch(), BATCH_SIZE, and impala::RowBatchList::total_num_rows().
impala::TEST_F (SimpleSchedulerTest , NonLocalHost)
Definition at line 118 of file simple-scheduler-test.cc.
References backends.
impala::TEST_F (InstructionCounterTest , TestMemInstrCount)
Definition at line 145 of file instruction-counter-test.cc.
References CodegenGcd(), impala::InstructionCounter::GetCount(), impala::InstructionCounter::PrintCounters(), impala::InstructionCounter::ResetCount(), and impala::InstructionCounter::visit().
impala::TEST_F (LlvmCodeGenTest , ReplaceFnCall)
Definition at line 147 of file llvm-codegen-test.cc.
References CodegenInnerLoop(), impala::Status::ok(), and pool.
impala::TEST_F (OldHashTableTest , SetupTest)
Definition at line 158 of file old-hash-table-test.cc.
impala::TEST_F (StateStore2Test , TestRegistration)
Definition at line 169 of file state-store-2.0-test.cc.
References impala::TestRegistrationCb::cv1(), impala::TestRegistrationCb::lock1(), and WaitForCV().
impala::TEST_F (DiskIoMgrTest , SingleWriter)
Definition at line 172 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddWriteRange(), CreateTempFile(), impala::DiskIoMgr::Init(), LARGE_MEM_LIMIT, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), impala::DiskIoMgr::WriteRange::SetData(), impala::DiskIoMgr::UnregisterContext(), and impala::DiskIoMgrTest::WriteValidateCallback().
impala::TEST_F (OldHashTableTest , BasicTest)
Definition at line 184 of file old-hash-table-test.cc.
References impala::OldHashTable::Close(), impala::OldHashTable::Insert(), impala::OldHashTable::num_buckets(), impala::OldHashTable::size(), and tracker.
impala::TEST_F (StateStore2Test , TestReceiveUpdates)
Definition at line 199 of file state-store-2.0-test.cc.
References impala::TestRegistrationCb::cv1(), impala::TestRegistrationCb::lock1(), and WaitForCV().
impala::TEST_F (DecompressorTest , Default)
Definition at line 204 of file decompress-test.cc.
impala::TEST_F (DecompressorTest , Snappy)
Definition at line 208 of file decompress-test.cc.
impala::TEST_F (DecompressorTest , LZ4)
Definition at line 212 of file decompress-test.cc.
impala::TEST_F (DecompressorTest , Gzip)
Definition at line 216 of file decompress-test.cc.
impala::TEST_F (DecompressorTest , Deflate)
Definition at line 221 of file decompress-test.cc.
impala::TEST_F (DecompressorTest , Bzip)
Definition at line 226 of file decompress-test.cc.
impala::TEST_F (DecompressorTest , SnappyBlocked)
Definition at line 230 of file decompress-test.cc.
impala::TEST_F (DiskIoMgrTest , InvalidWrite)
Definition at line 230 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddWriteRange(), CreateTempFile(), impala::DiskIoMgr::Init(), LARGE_MEM_LIMIT, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), impala::DiskIoMgr::WriteRange::SetData(), impala::DiskIoMgr::UnregisterContext(), and impala::DiskIoMgrTest::WriteValidateCallback().
impala::TEST_F (DecompressorTest , Impala1506)
Definition at line 234 of file decompress-test.cc.
References impala::Codec::CreateCompressor(), impala::MemPool::FreeAll(), and pool.
impala::TEST_F (OldHashTableTest , ScanTest)
Definition at line 241 of file old-hash-table-test.cc.
References impala::OldHashTable::Close(), impala::OldHashTable::Insert(), impala::OldHashTable::num_buckets(), and tracker.
impala::TEST_F (LlvmCodeGenTest , StringValue)
Definition at line 277 of file llvm-codegen-test.cc.
References CodegenStringTest(), impala::StringValue::len, impala::Status::ok(), pool, and impala::StringValue::ptr.
impala::TEST_F (DiskIoMgrTest , SingleWriterCancel)
Definition at line 284 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddWriteRange(), impala::DiskIoMgr::CancelContext(), impala::Status::CANCELLED, impala::Status::code(), CreateTempFile(), impala::DiskIoMgr::Init(), LARGE_MEM_LIMIT, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), impala::DiskIoMgr::WriteRange::SetData(), impala::DiskIoMgr::UnregisterContext(), and impala::DiskIoMgrTest::WriteValidateCallback().
impala::TEST_F (OldHashTableTest , GrowTableTest)
Definition at line 285 of file old-hash-table-test.cc.
References impala::OldHashTable::Close(), impala::OldHashTable::End(), impala::OldHashTable::Find(), impala::OldHashTable::Iterator::GetRow(), impala::OldHashTable::Insert(), impala::MemTracker::LimitExceeded(), impala::OldHashTable::mem_limit_exceeded(), impala::OldHashTable::size(), and tracker.
impala::TEST_F (BufferedBlockMgrTest , GetNewBlock)
Definition at line 297 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Block::buffer(), impala::BufferedBlockMgr::Block::is_pinned(), and impala::Status::ok().
impala::TEST_F (LlvmCodeGenTest , MemcpyTest)
Definition at line 319 of file llvm-codegen-test.cc.
References impala::LlvmCodeGen::FnPrototype::AddArgument(), impala::Status::ok(), pool, and TYPE_INT.
impala::TEST_F (BufferedBlockMgrTest , GetNewBlockSmallBlocks)
Definition at line 339 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Block::buffer(), impala::BufferedBlockMgr::Block::BytesRemaining(), impala::MemTracker::consumption(), impala::BufferedBlockMgr::Block::is_pinned(), impala::Status::ok(), and tracker.
impala::TEST_F (DiskIoMgrTest , SingleReader)
Definition at line 349 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddScanRanges(), impala::MemTracker::consumption(), CreateTempFile(), impala::DiskIoMgr::Init(), LARGE_MEM_LIMIT, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), and impala::DiskIoMgr::UnregisterContext().
impala::TEST_F (LlvmCodeGenTest , HashTest)
Definition at line 357 of file llvm-codegen-test.cc.
References Hash(), impala::Status::ok(), pool, and TYPE_INT.
impala::TEST_F (HashTableTest , LinearSetupTest)
Definition at line 392 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , QuadraticSetupTest)
Definition at line 398 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , LinearBasicTest)
Definition at line 404 of file hash-table-test.cc.
impala::TEST_F (BufferedBlockMgrTest , Pin)
Definition at line 404 of file buffered-block-mgr-test.cc.
References impala::Status::ok().
impala::TEST_F (DiskIoMgrTest , AddScanRangeTest)
Definition at line 408 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddScanRanges(), impala::Status::CANCELLED, impala::MemTracker::consumption(), CreateTempFile(), impala::DiskIoMgr::Init(), LARGE_MEM_LIMIT, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), and impala::DiskIoMgr::UnregisterContext().
impala::TEST_F (HashTableTest , QuadraticBasicTest)
Definition at line 410 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , LinearScanTest)
Definition at line 417 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , QuadraticScanTest)
Definition at line 423 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , LinearGrowTableTest)
Definition at line 429 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , QuadraticGrowTableTest)
Definition at line 433 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , LinearInsertFullTest)
Definition at line 437 of file hash-table-test.cc.
impala::TEST_F (HashTableTest , QuadraticInsertFullTest)
Definition at line 445 of file hash-table-test.cc.
impala::TEST_F (BufferedBlockMgrTest , Eviction)
Definition at line 454 of file buffered-block-mgr-test.cc.
References impala::RuntimeProfile::GetCounter(), impala::Status::ok(), impala::BufferedBlockMgr::Block::Unpin(), and impala::RuntimeProfile::Counter::value().
impala::TEST_F (SimpleTupleStreamTest , Basic)
Definition at line 482 of file buffered-tuple-stream-test.cc.
impala::TEST_F (DiskIoMgrTest , SyncReadTest)
Definition at line 484 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddScanRanges(), impala::MemTracker::consumption(), CreateTempFile(), impala::DiskIoMgr::Init(), LARGE_MEM_LIMIT, MAX_BUFFER_SIZE, MIN_BUFFER_SIZE, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), and impala::DiskIoMgr::UnregisterContext().
impala::TEST_F (SimpleTupleStreamTest , OneBufferSpill)
Definition at line 498 of file buffered-tuple-stream-test.cc.
impala::TEST_F (BufferedBlockMgrTest , Deletion)
Definition at line 507 of file buffered-block-mgr-test.cc.
References impala::BufferedBlockMgr::Block::Delete(), impala::RuntimeProfile::GetCounter(), impala::Status::ok(), and impala::RuntimeProfile::Counter::value().
impala::TEST_F (SimpleTupleStreamTest , ManyBufferSpill)
Definition at line 510 of file buffered-tuple-stream-test.cc.
impala::TEST_F (DataStreamTest , UnknownSenderSmallResult)
Definition at line 518 of file data-stream-test.cc.
impala::TEST_F (SimpleTupleStreamTest , UnpinPin)
Definition at line 526 of file buffered-tuple-stream-test.cc.
References BATCH_SIZE, impala::RowBatch::GetRow(), impala::RowBatch::num_rows(), and offset.
impala::TEST_F (DataStreamTest , UnknownSenderLargeResult)
Definition at line 531 of file data-stream-test.cc.
impala::TEST_F (BufferedBlockMgrTest , Close)
Definition at line 536 of file buffered-block-mgr-test.cc.
References impala::Status::IsCancelled(), and impala::Status::ok().
impala::TEST_F (DataStreamTest , Cancel)
Definition at line 541 of file data-stream-test.cc.
impala::TEST_F (DataStreamTest , BasicTest)
Definition at line 552 of file data-stream-test.cc.
impala::TEST_F (DiskIoMgrTest , SingleReaderCancel)
Definition at line 558 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddScanRanges(), impala::DiskIoMgr::CancelContext(), impala::Status::CANCELLED, impala::MemTracker::consumption(), impala::DiskIoMgr::context_status(), CreateTempFile(), impala::DiskIoMgr::Init(), impala::Status::IsCancelled(), LARGE_MEM_LIMIT, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), and impala::DiskIoMgr::UnregisterContext().
impala::TEST_F (SimpleTupleStreamTest , SmallBuffers)
Definition at line 568 of file buffered-tuple-stream-test.cc.
impala::TEST_F (BufferedBlockMgrTest , WriteError)
Definition at line 568 of file buffered-block-mgr-test.cc.
References impala::RuntimeProfile::GetCounter(), impala::Status::ok(), SCRATCH_DIR, SleepForMs(), and impala::RuntimeProfile::Counter::value().
impala::TEST_F (SimpleNullStreamTest , Basic)
Definition at line 607 of file buffered-tuple-stream-test.cc.
impala::TEST_F (BufferedBlockMgrTest , MultipleClients)
Definition at line 617 of file buffered-block-mgr-test.cc.
References impala::Status::ok().
impala::TEST_F (DiskIoMgrTest , MemLimits)
Definition at line 626 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddScanRanges(), impala::DiskIoMgr::BufferDescriptor::buffer(), impala::DiskIoMgr::context_status(), CreateTempFile(), impala::DiskIoMgr::ScanRange::GetNext(), impala::DiskIoMgr::GetNextRange(), impala::DiskIoMgr::Init(), impala::Status::IsMemLimitExceeded(), impala::DiskIoMgr::BufferDescriptor::len(), MAX_BUFFER_SIZE, impala::Status::MEM_LIMIT_EXCEEDED, MIN_BUFFER_SIZE, impala::DiskIoMgr::RequestRange::offset(), impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), impala::DiskIoMgr::BufferDescriptor::scan_range_offset(), and impala::DiskIoMgr::UnregisterContext().
impala::TEST_F (MultiTupleStreamTest , MultiTupleOneBufferSpill)
Definition at line 629 of file buffered-tuple-stream-test.cc.
impala::TEST_F (MultiTupleStreamTest , MultiTupleManyBufferSpill)
Definition at line 641 of file buffered-tuple-stream-test.cc.
impala::TEST_F (MultiNullableTupleStreamTest , MultiNullableTupleOneBufferSpill)
Definition at line 659 of file buffered-tuple-stream-test.cc.
impala::TEST_F (MultiNullableTupleStreamTest , MultiNullableTupleManyBufferSpill)
Definition at line 675 of file buffered-tuple-stream-test.cc.
impala::TEST_F (DiskIoMgrTest , CachedReads)
Definition at line 706 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddScanRanges(), impala::MemTracker::consumption(), CreateTempFile(), impala::DiskIoMgr::Init(), LARGE_MEM_LIMIT, MAX_BUFFER_SIZE, MIN_BUFFER_SIZE, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), and impala::DiskIoMgr::UnregisterContext().
impala::TEST_F (BufferedBlockMgrTest , MultipleClientsExtraBuffers)
Definition at line 730 of file buffered-block-mgr-test.cc.
References impala::Status::ok().
impala::TEST_F (DiskIoMgrTest , MultipleReaderWriter)
Definition at line 774 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddWriteRange(), CreateTempFile(), impala::DiskIoMgr::Init(), ITERATIONS, LARGE_MEM_LIMIT, MAX_BUFFER_SIZE, MIN_BUFFER_SIZE, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), impala::DiskIoMgr::WriteRange::SetData(), impala::DiskIoMgr::UnregisterContext(), and impala::DiskIoMgrTest::WriteCompleteCallback().
impala::TEST_F (BufferedBlockMgrTest , ClientOversubscription)
Definition at line 779 of file buffered-block-mgr-test.cc.
References impala::Status::IsMemLimitExceeded(), and impala::Status::ok().
impala::TEST_F (BufferedBlockMgrTest , SingleRandom_plain)
Definition at line 824 of file buffered-block-mgr-test.cc.
impala::TEST_F (BufferedBlockMgrTest , Multi2Random_plain)
Definition at line 829 of file buffered-block-mgr-test.cc.
impala::TEST_F (BufferedBlockMgrTest , Multi4Random_plain)
Definition at line 834 of file buffered-block-mgr-test.cc.
impala::TEST_F (ExprTest , NullLiteral)
Definition at line 838 of file expr-test.cc.
References impala::ExprContext::Close(), impala::ExprContext::GetValue(), impala::Status::ok(), impala::ExprContext::Open(), impala::ExprContext::Prepare(), tracker, TYPE_BOOLEAN, and TYPE_DATE.
impala::TEST_F (BufferedBlockMgrTest , SingleRandom_encryption)
Definition at line 845 of file buffered-block-mgr-test.cc.
impala::TEST_F (BufferedBlockMgrTest , Multi2Random_encryption)
Definition at line 850 of file buffered-block-mgr-test.cc.
impala::TEST_F (ExprTest , LiteralConstruction)
Definition at line 853 of file expr-test.cc.
References TestSingleLiteralConstruction(), TYPE_BIGINT, TYPE_BOOLEAN, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, TYPE_STRING, and TYPE_TINYINT.
impala::TEST_F (BufferedBlockMgrTest , Multi4Random_encryption)
Definition at line 855 of file buffered-block-mgr-test.cc.
impala::TEST_F (DiskIoMgrTest , MultipleReader)
Definition at line 861 of file disk-io-mgr-test.cc.
References impala::DiskIoMgr::AddScanRanges(), impala::MemTracker::consumption(), CreateTempFile(), impala::DiskIoMgr::Init(), ITERATIONS, LARGE_MEM_LIMIT, MAX_BUFFER_SIZE, MIN_BUFFER_SIZE, impala::Status::OK, impala::Status::ok(), impala::DiskIoMgr::RegisterContext(), and impala::DiskIoMgr::UnregisterContext().
impala::TEST_F (ExprTest , LiteralExprs)
Definition at line 908 of file expr-test.cc.
References TYPE_BIGINT, TYPE_BOOLEAN, TYPE_DOUBLE, TYPE_INT, TYPE_NULL, TYPE_SMALLINT, and TYPE_TINYINT.
impala::TEST_F (ExprTest , ArithmeticExprs)
Definition at line 924 of file expr-test.cc.
References TYPE_BIGINT, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, and TYPE_TINYINT.
impala::TEST_F (DiskIoMgrTest , StressTest)
Definition at line 958 of file disk-io-mgr-test.cc.
References impala::DiskIoMgrStress::Run().
impala::TEST_F (DiskIoMgrTest , Buffers)
Definition at line 964 of file disk-io-mgr-test.cc.
References impala::MemTracker::consumption(), impala::DiskIoMgr::GcIoBuffers(), impala::DiskIoMgr::GetFreeBuffer(), impala::DiskIoMgr::Init(), impala::DiskIoMgr::num_allocated_buffers_, impala::Status::ok(), and impala::DiskIoMgr::ReturnFreeBuffer().
impala::TEST_F (ExprTest , DecimalArithmeticExprs)
Definition at line 1060 of file expr-test.cc.
impala::TEST_F (ExprTest , BinaryPredicates)
Definition at line 1117 of file expr-test.cc.
impala::TEST_F (ExprTest , CastExprs)
Definition at line 1133 of file expr-test.cc.
References TYPE_BIGINT, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, TYPE_TIMESTAMP, and TYPE_TINYINT.
impala::TEST_F (ExprTest , CompoundPredicates)
Definition at line 1254 of file expr-test.cc.
References TYPE_BOOLEAN.
impala::TEST_F (ExprTest , IsNullPredicate)
Definition at line 1305 of file expr-test.cc.
References TYPE_BOOLEAN.
impala::TEST_F (ExprTest , LikePredicate)
Definition at line 1312 of file expr-test.cc.
References TYPE_BOOLEAN.
impala::TEST_F (ExprTest , BetweenPredicate)
Definition at line 1412 of file expr-test.cc.
References TYPE_BOOLEAN.
impala::TEST_F (ExprTest , InPredicate)
Definition at line 1451 of file expr-test.cc.
References TYPE_BOOLEAN.
impala::TEST_F (ExprTest , StringFunctions)
Definition at line 1551 of file expr-test.cc.
References TYPE_BOOLEAN, TYPE_INT, and TYPE_STRING.
impala::TEST_F (ExprTest , StringRegexpFunctions)
Definition at line 1858 of file expr-test.cc.
References TestError(), and TYPE_STRING.
impala::TEST_F (ExprTest , StringParseUrlFunction)
Definition at line 1929 of file expr-test.cc.
References TestError(), and TYPE_STRING.
impala::TEST_F (ExprTest , UtilityFunctions)
Definition at line 2210 of file expr-test.cc.
References impala::ColumnType::GetByteSize(), GetVersionString(), TYPE_BIGINT, and TYPE_BOOLEAN.
impala::TEST_F (ExprTest , NonFiniteFloats)
Definition at line 2287 of file expr-test.cc.
References TYPE_BOOLEAN, TYPE_DOUBLE, and TYPE_FLOAT.
impala::TEST_F (ExprTest , MathTrigonometricFunctions)
Definition at line 2319 of file expr-test.cc.
References TYPE_DOUBLE.
impala::TEST_F (ExprTest , MathConversionFunctions)
Definition at line 2353 of file expr-test.cc.
References TYPE_STRING.
impala::TEST_F (ExprTest , MathFunctions)
Definition at line 2454 of file expr-test.cc.
References TYPE_BIGINT, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, TYPE_TIMESTAMP, and TYPE_TINYINT.
impala::TEST_F (ExprTest , MathRoundingFunctions)
Definition at line 2772 of file expr-test.cc.
References TYPE_BIGINT, and TYPE_DOUBLE.
impala::TEST_F (ExprTest , UnaryOperators)
Definition at line 2810 of file expr-test.cc.
References TYPE_DOUBLE, TYPE_FLOAT, TYPE_SMALLINT, and TYPE_TINYINT.
impala::TEST_F (ExprTest , TimestampFunctions)
Definition at line 2825 of file expr-test.cc.
References TestError(), TYPE_BIGINT, TYPE_BOOLEAN, TYPE_DOUBLE, TYPE_INT, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, and TYPE_TINYINT.
impala::TEST_F (ExprTest , ConditionalFunctions)
Definition at line 3593 of file expr-test.cc.
References TYPE_BIGINT, TYPE_BOOLEAN, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, and TYPE_TINYINT.
impala::TEST_F (ExprTest , ConditionalFunctionIsTrue)
Definition at line 3843 of file expr-test.cc.
References TestError(), and TYPE_BOOLEAN.
impala::TEST_F (ExprTest , ConditionalFunctionIsFalse)
Definition at line 3870 of file expr-test.cc.
References TestError(), and TYPE_BOOLEAN.
impala::TEST_F (ExprTest , ConditionalFunctionIsNotTrue)
Definition at line 3899 of file expr-test.cc.
References TestError(), and TYPE_BOOLEAN.
impala::TEST_F (ExprTest , ConditionalFunctionIsNotFalse)
Definition at line 3928 of file expr-test.cc.
References TestError(), and TYPE_BOOLEAN.
impala::TEST_F (ExprTest , ResultsLayoutTest)
Definition at line 3989 of file expr-test.cc.
References impala::ObjectPool::Add(), impala::ColumnType::GetByteSize(), pool, impala::ColumnType::type, TYPE_BIGINT, TYPE_BOOLEAN, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, TYPE_TINYINT, and ValidateLayout().
impala::TEST_F (ExprTest , DecimalFunctions)
Definition at line 4079 of file expr-test.cc.
References disable_codegen_, TYPE_BIGINT, TYPE_INT, and TYPE_TINYINT.
impala::TEST_F (ExprTest , DecimalOverflowCasts)
Definition at line 4586 of file expr-test.cc.
impala::TEST_F (ExprTest , NullValueFunction)
Definition at line 4657 of file expr-test.cc.
References TYPE_BOOLEAN.
impala::TEST_F (ExprTest , NonNullValueFunction)
Definition at line 4727 of file expr-test.cc.
References TYPE_BOOLEAN.
impala::TEST_F (ExprTest , UdfInterfaceBuiltins)
Definition at line 4797 of file expr-test.cc.
References TYPE_BIGINT, TYPE_DOUBLE, TYPE_INT, TYPE_SMALLINT, and TYPE_TINYINT.
impala::TEST_F (ExprTest , MADlib)
Definition at line 4813 of file expr-test.cc.
References TYPE_DOUBLE.
void impala::TestAllFloatVariants (const string & s, StringParser::ParseResult exp_result)
Definition at line 105 of file string-parser-test.cc.
References space, and space_len.
Referenced by TEST().
void impala::TestBase64 (const string & input, const string & expected_encoded)
Definition at line 48 of file url-coding-test.cc.
References Base64Decode(), and Base64Encode().
Referenced by TEST().
template<typename T > void impala::TestBigEndian (T value)
Definition at line 28 of file read-write-util-test.cc.
References impala::ReadWriteUtil::PutInt().
void impala::TestBitArrayValues (int bit_width, int num_vals)
Definition at line 97 of file rle-test.cc.
References impala::BitWriter::bytes_written(), impala::BitUtil::Ceil(), impala::BitWriter::Flush(), and impala::BitWriter::PutValue().
Referenced by TEST().
void impala::TestBoolValue (const char * s, bool exp_val, StringParser::ParseResult exp_result)
Definition at line 66 of file string-parser-test.cc.
References space, space_len, and impala::StringParser::StringToBool().
Referenced by TEST().
void impala::TestCompression (int num, int min_len, int max_len, THdfsCompression::type codec)
Definition at line 32 of file compression-test.cc.
References impala::Codec::CreateCompressor(), and offset.
Referenced by main().
void impala::TestDemangling (const string & mangled, const string & expected_demangled)
Definition at line 27 of file symbols-util-test.cc.
References impala::SymbolsUtil::Demangle().
Referenced by TEST().
void impala::TestDemanglingNameOnly (const string & mangled, const string & expected_demangled)
Definition at line 32 of file symbols-util-test.cc.
References impala::SymbolsUtil::DemangleNameOnly().
Referenced by TEST().
template<typename T > void impala::TestFloatBruteForce ()
Definition at line 120 of file string-parser-test.cc.
References impala::StringParser::PARSE_SUCCESS.
template<typename T > void impala::TestFloatValue (const string & s, StringParser::ParseResult exp_result)
Definition at line 81 of file string-parser-test.cc.
References impala::StringParser::PARSE_SUCCESS.
template<typename T > void impala::TestFloatValueIsNan (const string & s, StringParser::ParseResult exp_result)
Definition at line 93 of file string-parser-test.cc.
References impala::StringParser::PARSE_SUCCESS.
void impala::TestFunction (int batch_size, void * d)
Definition at line 44 of file benchmark-test.cc.
References impala::MemcpyData::dst, impala::MemcpyData::size, and impala::MemcpyData::src.
Referenced by TEST().
template<typename T > void impala::TestIntValue (const char * s, T exp_val, StringParser::ParseResult exp_result)
Definition at line 36 of file string-parser-test.cc.
References space, and space_len.
template<typename T > void impala::TestIntValue (const char * s, int base, T exp_val, StringParser::ParseResult exp_result)
Definition at line 52 of file string-parser-test.cc.
References space, and space_len.
void impala::TestMangling (const string & name, bool var_args, const vector< ColumnType > args, ColumnType * ret_arg_type, const string & expected_mangled, const string & expected_demangled)
Definition at line 39 of file symbols-util-test.cc.
References impala::SymbolsUtil::Demangle(), and impala::SymbolsUtil::MangleUserFunction().
Referenced by TEST().
void impala::TestManglingPrepareOrClose (const string & name, const string & expected_mangled, const string & expected_demangled)
Definition at line 51 of file symbols-util-test.cc.
References impala::SymbolsUtil::Demangle(), and impala::SymbolsUtil::ManglePrepareOrCloseFunction().
Referenced by TEST().
template<typename T > void impala::TestNumbers (int max_value, int repeat, int value_byte_size)
Definition at line 110 of file dict-test.cc.
References IncrementValue(), and ValidateDict().
template<typename T > void impala::TestNumbers (int value_byte_size)
Definition at line 121 of file dict-test.cc.
void impala::TestRleValues (int bit_width, int num_vals, int value = -1)
Definition at line 250 of file rle-test.cc.
References ValidateRle().
Referenced by TEST().
void impala::TestSearch (const char * haystack_orig, const char * needle_orig, int haystack_len = -1, int needle_len = -1)
Definition at line 15 of file string-search-test.cc.
References impala::StringSearchSSE::Search().
Referenced by TEST().
template<typename T > void impala::TestSingleLiteralConstruction (const ColumnType & type, const T & value, const string & string_val)
Definition at line 821 of file expr-test.cc.
References impala::ObjectPool::Add(), impala::ExprContext::Close(), impala::ExprContext::GetValue(), impala::Status::ok(), impala::ExprContext::Open(), pool, impala::ExprContext::Prepare(), and tracker.
Referenced by TEST_F().
void impala::TestTimestampTokens (vector< TimestampToken > * toks, int year, int month, int day, int hours, int mins, int secs, int frac)
Definition at line 157 of file timestamp-test.cc.
References impala::TimestampParser::ParseFormatTokens(), and ValidateTimestamp().
Referenced by TEST().
template<typename T > void impala::TestType (const T & v, int expected_byte_size)
Definition at line 30 of file parquet-plain-test.cc.
References impala::ParquetPlainEncoder::Decode(), and impala::ParquetPlainEncoder::Encode().
Referenced by TEST().
void impala::TestUrl (const string & input, const string & expected_encoded, bool hive_compat)
Definition at line 29 of file url-coding-test.cc.
References UrlDecode(), and UrlEncode().
Referenced by TEST().
void impala::TestZInt (int32_t value)
Definition at line 29 of file zigzag-test.cc.
References impala::ReadWriteUtil::MAX_ZINT_LEN, impala::ReadWriteUtil::PutZInt(), and impala::ReadWriteUtil::ReadZInt().
Referenced by TEST().
void impala::TestZLong (int64_t value)
Definition at line 42 of file zigzag-test.cc.
References impala::ReadWriteUtil::MAX_ZLONG_LEN, impala::ReadWriteUtil::PutZLong(), and impala::ReadWriteUtil::ReadZLong().
Referenced by TEST().
impala::THRIFT_ENUM_OUTPUT_FN (TFunctionBinaryType)
impala::THRIFT_ENUM_OUTPUT_FN (TCatalogObjectType)
impala::THRIFT_ENUM_OUTPUT_FN (TDdlType)
impala::THRIFT_ENUM_OUTPUT_FN (TCatalogOpType)
impala::THRIFT_ENUM_OUTPUT_FN (THdfsFileFormat)
impala::THRIFT_ENUM_OUTPUT_FN (THdfsCompression)
impala::THRIFT_ENUM_OUTPUT_FN (TSessionType)
impala::THRIFT_ENUM_OUTPUT_FN (TStmtType)
impala::THRIFT_ENUM_OUTPUT_FN (QueryState)
impala::THRIFT_ENUM_OUTPUT_FN (Encoding)
impala::THRIFT_ENUM_OUTPUT_FN (CompressionCodec)
impala::THRIFT_ENUM_OUTPUT_FN (Type)
impala::THRIFT_ENUM_OUTPUT_FN (TMetricKind)
impala::THRIFT_ENUM_OUTPUT_FN (TUnit)
impala::THRIFT_ENUM_PRINT_FN (TCatalogObjectType)
impala::THRIFT_ENUM_PRINT_FN (TDdlType)
impala::THRIFT_ENUM_PRINT_FN (TCatalogOpType)
impala::THRIFT_ENUM_PRINT_FN (TSessionType)
impala::THRIFT_ENUM_PRINT_FN (TStmtType)
impala::THRIFT_ENUM_PRINT_FN (QueryState)
impala::THRIFT_ENUM_PRINT_FN (Encoding)
impala::THRIFT_ENUM_PRINT_FN (TMetricKind)
impala::THRIFT_ENUM_PRINT_FN (TUnit)
static void impala::ThriftOutputFunction (const char * output) static
Definition at line 108 of file thrift-util.cc.
References VLOG_QUERY.
Referenced by InitThriftLogging().
PrimitiveType impala::ThriftToType (TPrimitiveType::type ttype)
Definition at line 27 of file types.cc.
References INVALID_TYPE, TYPE_BIGINT, TYPE_BINARY, TYPE_BOOLEAN, TYPE_CHAR, TYPE_DATE, TYPE_DATETIME, TYPE_DECIMAL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_NULL, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, TYPE_TINYINT, and TYPE_VARCHAR.
Referenced by impala::ImpalaServer::HS2ColumnarResultSet::AddRows(), impala::ColumnType::ColumnType(), impala::ImpalaServer::FetchInternal(), impala::ImpalaServer::get_results_metadata(), and impala::ImpalaServer::HS2ColumnarResultSet::InitColumns().
bool impala::TNetworkAddressComparator (const TNetworkAddress & a, const TNetworkAddress & b)
Compares two TNetworkAddresses alphanumerically by their host:port string representation
Definition at line 168 of file thrift-util.cc.
Referenced by TBackendDescriptorComparator(), and TEST().
std::string impala::TNetworkAddressToString (const TNetworkAddress & address)
Utility method to print address as address:port.
Definition at line 126 of file network-util.cc.
Referenced by impala::SimpleScheduler::BackendsUrlCallback(), impala::QueryResourceMgr::CreateExpansionRequest(), impala::ExecEnv::ExecEnv(), impala::ImpalaServer::QueryExecState::QueryExecState(), and impala::CatalogServer::Start().
Decimal16Value impala::ToDecimal16 (const Decimal4Value & v, bool * overflow) inline
Definition at line 361 of file decimal-value.h.
References impala::DecimalValue< T >::value().
Referenced by GetDecimal16Value(), and impala::DecimalOperators::ScaleDecimalValue().
Decimal16Value impala::ToDecimal16 (const Decimal8Value & v, bool * overflow) inline
Definition at line 371 of file decimal-value.h.
References impala::DecimalValue< T >::value().
Decimal16Value impala::ToDecimal16 (const Decimal16Value & v, bool * overflow) inline
Definition at line 382 of file decimal-value.h.
Decimal4Value impala::ToDecimal4 (const Decimal4Value & v, bool * overflow) inline
Conversions from different decimal types to one another. This does not alter the scale. Checks for overflow. Although in some cases (going from Decimal4Value to Decimal8Value) cannot overflow, the signature is the same to allow for templating.
Definition at line 355 of file decimal-value.h.
Referenced by GetDecimal4Value(), and impala::DecimalOperators::ScaleDecimalValue().
Decimal4Value impala::ToDecimal4 (const Decimal8Value & v, bool * overflow) inline
Definition at line 364 of file decimal-value.h.
References abs(), and impala::DecimalValue< T >::value().
Decimal4Value impala::ToDecimal4 (const Decimal16Value & v, bool * overflow) inline
Definition at line 374 of file decimal-value.h.
References abs(), and impala::DecimalValue< T >::value().
Decimal8Value impala::ToDecimal8 (const Decimal4Value & v, bool * overflow) inline
Definition at line 358 of file decimal-value.h.
References impala::DecimalValue< T >::value().
Referenced by GetDecimal8Value(), and impala::DecimalOperators::ScaleDecimalValue().
Decimal8Value impala::ToDecimal8 (const Decimal8Value & v, bool * overflow) inline
Definition at line 368 of file decimal-value.h.
Decimal8Value impala::ToDecimal8 (const Decimal16Value & v, bool * overflow) inline
Definition at line 378 of file decimal-value.h.
References abs(), and impala::DecimalValue< T >::value().
template<typename T > impala::ToJsonValue (const T & value, const TUnit::type unit, rapidjson::Document * document, rapidjson::Value * out_val)
ToJsonValue() converts 'value' into a rapidjson::Value in 'out_val'. The type of 'out_val' depends on the value of 'type'. If type != TUnit::NONE and 'value' is numeric, 'value' will be set to a string which is the pretty-printed representation of 'value' (e.g. conversion to MB etc). Otherwise the value is directly copied into 'out_val'.
Does pretty-printing if 'value' is numeric, and type is not NONE, otherwise constructs a json object containing 'value' as a literal.
Definition at line 33 of file json-util.h.
Referenced by impala::SetMetric< std::string >::ToJson(), impala::SimpleMetric< T, metric_kind >::ToJson(), impala::SetMetric< std::string >::ToLegacyJson(), and impala::SimpleMetric< T, metric_kind >::ToLegacyJson().
template<> void impala::ToJsonValue< std::string > (const std::string & value, const TUnit::type unit, rapidjson::Document * document, rapidjson::Value * out_val)
Specialisation for std::string which requires explicit use of 'document's allocator to copy into out_val.
Definition at line 9 of file json-util.cc.
template<> void impala::ToJsonValue< string > (const string & value, const TUnit::type unit, Document * document, Value * out_val)
Definition at line 38 of file metrics.cc.
template<typename T > StringVal impala::ToStringVal (FunctionContext * context, T val)
Definition at line 45 of file aggregate-functions.cc.
Referenced by impala::AnyValUtil::SetAnyVal().
TPrimitiveType::type impala::ToThrift (PrimitiveType ptype)
Definition at line 50 of file types.cc.
References INVALID_TYPE, TYPE_BIGINT, TYPE_BINARY, TYPE_BOOLEAN, TYPE_CHAR, TYPE_DATE, TYPE_DATETIME, TYPE_DECIMAL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_NULL, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, TYPE_TINYINT, and TYPE_VARCHAR.
Referenced by impala::ColumnType::ToThrift().
void impala::TQueryOptionsToMap (const TQueryOptions & query_options, std::map< std::string, std::string > * configuration)
Converts a TQueryOptions struct into a map of key, value pairs.
Referenced by impala::ImpalaServer::QueryExecState::Exec(), impala::ImpalaServer::InitializeConfigVariables(), and impala::ImpalaServer::OpenSession().
std::string impala::TypeToOdbcString (PrimitiveType t)
Definition at line 96 of file types.cc.
References INVALID_TYPE, TYPE_BIGINT, TYPE_BINARY, TYPE_BOOLEAN, TYPE_CHAR, TYPE_DATE, TYPE_DATETIME, TYPE_DECIMAL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_NULL, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, TYPE_TINYINT, and TYPE_VARCHAR.
Referenced by impala::ImpalaServer::FetchInternal(), impala::ImpalaServer::get_results_metadata(), and impala::ExprTest::GetValue().
std::string impala::TypeToString (PrimitiveType t)
Definition at line 73 of file types.cc.
References INVALID_TYPE, TYPE_BIGINT, TYPE_BINARY, TYPE_BOOLEAN, TYPE_CHAR, TYPE_DATE, TYPE_DATETIME, TYPE_DECIMAL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT, TYPE_NULL, TYPE_SMALLINT, TYPE_STRING, TYPE_TIMESTAMP, TYPE_TINYINT, and TYPE_VARCHAR.
Referenced by impala::ImpalaServer::HS2ColumnarResultSet::AddRows(), impala::ColumnType::DebugString(), impala::ImpalaServer::HS2ColumnarResultSet::InitColumns(), impala::Literal::Literal(), and impala::UtilityFunctions::TypeOf().
int64_t impala::UnixMillis () inline
Returns the number of milliseconds that have passed since the Unix epoch. This is affected by manual changes to the system clock but is more suitable for use across a cluster. For more accurate timings on the local host use the monotonic functions above.
Definition at line 51 of file time.h.
Referenced by impala::ImpalaServer::ArchiveQuery(), impala::ImpalaServer::ConnectionStart(), impala::Statestore::DoSubscriberUpdate(), impala::ImpalaServer::ExpireQueries(), impala::ImpalaServer::ExpireSessions(), impala::ImpalaServer::LogAuditRecord(), impala::ImpalaServer::QueryExecState::MarkActive(), impala::ImpalaServer::QueryExecState::MarkInactive(), impala::ImpalaServer::MarkSessionInactive(), impala::ImpalaServer::OpenSession(), impala::ImpalaServer::SetQueryInflight(), and TEST().
void impala::UpdateAverageProfile (BackendExecState * backend_exec_state) private
Update fragment profile information from a backend exec state. This is called repeatedly from UpdateFragmentExecStatus(), and also at the end of the query from ReportQuerySummary(). This method calls UpdateAverage() and AddChild(), which obtain their own locks on the backend state.
void impala::UpdateExecSummary (int fragment_idx, int instance_idx, RuntimeProfile * profile) private
Populates the summary execution stats from the profile. Can only be called when the query is done.
Status impala::UpdateFragmentExecStatus (const TReportExecStatusParams & params)
Updates status and query execution metadata of a particular fragment; if 'status' is an error status or if 'done' is true, considers the plan fragment to have finished execution. Assumes that calls to UpdateFragmentExecStatus() won't happen concurrently for the same backend. If 'status' is an error status, also cancel execution of the query via a call to CancelInternal().
Status impala::UpdateStatus (const Status & status, const TUniqueId * failed_fragment) private
Acquires lock_ and updates query_status_ with 'status' if it's not already an error status, and returns the current query_status_. Calls CancelInternal() when switching to an error status. If failed_fragment is non-null, it is the fragment_id that has failed, used for error reporting.
Referenced by impala::FragmentMgr::FragmentExecState::ReportStatusCb().
bool impala::UrlDecode (const std::string & in, std::string * out, bool hive_compat = false)
Utility method to decode a string that was URL-encoded. Returns true unless the string could not be correctly decoded. The optional parameter hive_compat controls whether or not we treat the strings as encoded by Hive, which means selectively ignoring certain characters like ' '.
bool impala::UrlDecode (const string & in, string * out, bool hive_compat)
Definition at line 84 of file url-coding.cc.
Referenced by impala::Webserver::BuildArgumentMap(), and TestUrl().
void impala::UrlEncode (const std::string & in, std::string * out, bool hive_compat = false)
Utility method to URL-encode a string (that is, replace special characters with %<hex value="" in="" ascii>="">). The optional parameter hive_compat controls whether we mimic Hive's behaviour when encoding a string, which is only to encode certain characters (excluding, e.g., ' ')
void impala::UrlEncode (const std::vector< uint8_t > & in, std::string * out, bool hive_compat = false)
static void impala::UrlEncode (const char * in, int in_len, string * out, bool hive_compat) inline static
Definition at line 48 of file url-coding.cc.
References HiveShouldEscape, and ShouldNotEscape.
Referenced by impala::HdfsTableSink::InitOutputPartition(), TestUrl(), and UrlEncode().
void impala::UrlEncode (const vector< uint8_t > & in, string * out, bool hive_compat)
Definition at line 68 of file url-coding.cc.
References UrlEncode().
void impala::UrlEncode (const string & in, string * out, bool hive_compat)
Definition at line 76 of file url-coding.cc.
References UrlEncode().
template<typename T > void impala::UUIDToTUniqueId (const boost::uuids::uuid & uuid, T * unique_id) inline
Templated so that this method is not namespace-specific (since we also call this on llama::TUniqueId)
Definition at line 38 of file uid-util.h.
Referenced by impala::ThriftServer::ThriftServerEventProcessor::createContext(), impala::ResourceBroker::CreateLlamaReservationRequest(), impala::ResourceBroker::Expand(), impala::ImpalaServer::OpenSession(), impala::ImpalaServer::PrepareQueryContext(), impala::Statestore::RegisterSubscriber(), and impala::ResourceBroker::RegisterWithLlama().
void impala::Validate (DelimitedTextParser * parser, const string & data, int expected_offset, char tuple_delim, int expected_num_tuples, int expected_num_fields)
Definition at line 25 of file delimited-text-parser-test.cc.
References impala::DelimitedTextParser::FindFirstInstance(), offset, impala::DelimitedTextParser::ParseFieldLocations(), and impala::DelimitedTextParser::ParserReset().
Referenced by TEST().
void impala::ValidateCounter (RuntimeProfile * profile, const string & name, int64_t value)
Definition at line 98 of file runtime-profile-test.cc.
References impala::RuntimeProfile::GetCounter(), and impala::RuntimeProfile::Counter::value().
Referenced by TEST().
template<typename T > void impala::ValidateDict (const vector< T > & values, int fixed_buffer_byte_size)
Definition at line 33 of file dict-test.cc.
References impala::DictEncoderBase::ClearIndices(), impala::DictEncoderBase::dict_encoded_size(), impala::DictEncoderBase::EstimatedDataEncodedSize(), impala::MemPool::FreeAll(), impala::DictEncoder< T >::num_entries(), pool, impala::DictEncoder< T >::Put(), impala::DictDecoderBase::SetData(), tracker, impala::DictEncoderBase::WriteData(), and impala::DictEncoder< T >::WriteDict().
Referenced by TEST(), and TestNumbers().
void impala::ValidateLayout (const vector< Expr * > & exprs, int expected_byte_size, int expected_var_begin, const map< int, set< int > > & expected_offsets)
Definition at line 3960 of file expr-test.cc.
Referenced by TEST_F().
void impala::ValidateNameNode (const string & path, const string & expected_namenode, const string & expected_error)
Definition at line 25 of file hdfs-fs-cache-test.cc.
Referenced by TEST().
void impala::ValidateRle (const vector< int > & values, int bit_width, uint8_t * expected_encoding, int expected_len)
Definition at line 171 of file rle-test.cc.
References impala::RleEncoder::Flush(), impala::RleDecoder::Get(), and impala::RleEncoder::Put().
Referenced by TEST(), and TestRleValues().
void impala::ValidateSampler (const StreamingSampler< int, 10 > & sampler, int expected_num, int expected_period, int expected_delta)
Definition at line 454 of file runtime-profile-test.cc.
References impala::StreamingSampler< T, MAX_SAMPLES >::GetSamples().
Referenced by TEST().
void impala::ValidateString (const string & std_str, const StringBuffer & str)
Definition at line 26 of file string-buffer-test.cc.
References impala::StringBuffer::Empty(), impala::StringValue::ptr, impala::StringBuffer::Size(), and impala::StringBuffer::str().
Referenced by TEST().
void impala::ValidateTimestamp (TimestampValue & tv, string & fmt, string & val, string & fmt_val, int year, int month, int day, int hours, int mins, int secs, int frac) inline
Definition at line 136 of file timestamp-test.cc.
References impala::TimestampValue::date(), and impala::TimestampValue::time().
Referenced by TestTimestampTokens().
template<typename T > void impala::VerifyEquals (const DecimalValue< T > & t1, const DecimalValue< T > & t2)
Definition at line 36 of file decimal-test.cc.
Referenced by VerifyParse().
template<typename T > void impala::VerifyFuzzyEquals (const T & actual, const ColumnType & t, double expected, bool overflow)
Definition at line 611 of file decimal-test.cc.
References MAX_ERROR.
Referenced by TEST().
template<typename T > void impala::VerifyParse (const string & s, const ColumnType & t, const DecimalValue< T > & expected_val, StringParser::ParseResult expected_result)
Definition at line 44 of file decimal-test.cc.
References impala::StringParser::PARSE_SUCCESS, impala::StringParser::PARSE_UNDERFLOW, and VerifyEquals().
Referenced by StringToAllDecimals(), and TEST().
template<typename T > void impala::VerifyToString (const T & decimal, const ColumnType & t, const string & expected)
Definition at line 57 of file decimal-test.cc.
Referenced by TEST().
Status impala::Wait ()
Blocks until result rows are ready to be retrieved via GetNext(), or, if the query doesn't return rows, until the query finishes or is cancelled. A call to Wait() must precede all calls to GetNext(). Multiple calls to Wait() are idempotent and it is okay to issue multiple Wait() calls concurrently.
Status impala::WaitForAllBackends () private
Returns only when either all backends have reported success or the query is in error. Returns the status of the query. It is safe to call this concurrently, but any calls must be made only after Exec(). WaitForAllBackends may be called before Wait(), but note that Wait() guarantees that any coordinator fragment has finished, which this method does not.
Status impala::WaitForCV (unique_lock< mutex > * lock, condition_variable * cv)
Definition at line 141 of file state-store-2.0-test.cc.
References OK.
Referenced by TEST_F().
Status impala::WaitForLocalServer (const ThriftServer & server, int num_retries, int retry_interval_ms)
Wait for a server that is running locally to start accepting connections, up to a maximum timeout
Definition at line 116 of file thrift-util.cc.
References impala::ThriftServer::port(), and WaitForServer().
Status impala::WaitForServer (const string & host, int port, int num_retries, int retry_interval_ms)
Definition at line 121 of file thrift-util.cc.
References impala::Status::OK, SleepForMs(), and VLOG_QUERY.
Referenced by impala::ImpaladQueryExecutor::Setup(), impala::InProcessStatestore::Start(), impala::StateStore2Test::StartStateStoreSubscriber(), impala::InProcessImpalaServer::StartWithClientServers(), and WaitForLocalServer().
Status impala::WaitForServer (const std::string & host, int port, int num_retries, int retry_interval_ms)
Wait for a server to start accepting connections, up to a maximum timeout.
impala::~Coordinator ()
Variable Documentation
impala::GrowingTest impala::__attribute__
Referenced by main().
__thread ThriftServer::ConnectionContext* impala::__connection_context__
Definition at line 194 of file thrift-server.cc.
Referenced by impala::ThriftServer::ThriftServerEventProcessor::createContext(), impala::ThriftServer::ThriftServerEventProcessor::deleteContext(), impala::ThriftServer::GetThreadConnectionContext(), impala::ThriftServer::GetThreadConnectionId(), and impala::ThriftServer::ThriftServerEventProcessor::processContext().
client impala::__pad0__
Query coordinator: handles execution of plan fragments on remote nodes, given a TQueryExecRequest. As part of that, it handles all interactions with the executing backends; it is also responsible for implementing all client requests regarding the query, including cancellation. The coordinator fragment is executed locally in the calling thread, all other fragments are sent to remote nodes. The coordinator also monitors the execution status of the remote fragments and aborts the entire query if an error occurs, either in any of the remote fragments or in the local fragment. Once a query has finished executing and all results have been returned either to the caller of GetNext() or a data sink, execution_completed() will return true. If the query is aborted, execution_completed should also be set to true. Coordinator is thread-safe, with the exception of GetNext(). A typical sequence of calls for a single query (calls under the same numbered item can happen concurrently):
client: Exec()
client: Wait()/client: Cancel()/backend: UpdateFragmentExecStatus()
client: GetNext()
Definition at line 64 of file coordinator.h.
const StringSearch UrlParser::at_search& impala::at
Definition at line 37 of file url-parser.cc.
const string impala::AUDIT_EVENT_LOG_FILE_PREFIX = "impala_audit_event_log_1.0-"
Definition at line 176 of file impala-server.cc.
Referenced by impala::ImpalaServer::InitAuditEventLogging().
const uint64_t impala::AVAILABLE_SPACE_THRESHOLD_MB = 1024
Definition at line 43 of file tmp-file-mgr.cc.
Referenced by impala::TmpFileMgr::Init().
boost::condition_variable impala::backend_completion_cv_
If there is no coordinator fragment, Wait simply waits until all backends report completion by notifying on backend_completion_cv_. Tied to lock_.
Definition at line 274 of file coordinator.h.
BackendExecStateMap impala::backend_exec_state_map_
Definition at line 260 of file coordinator.h.
std::vector<BackendExecState*> impala::backend_exec_states_
BackendExecStates owned by obj_pool()
Definition at line 216 of file coordinator.h.
const string impala::BACKENDS_TEMPLATE = "backends.tmpl" static
Definition at line 75 of file simple-scheduler.cc.
Referenced by impala::SimpleScheduler::Init().
const string impala::BACKENDS_WEB_PAGE = "/backends" static
Definition at line 74 of file simple-scheduler.cc.
Referenced by impala::SimpleScheduler::Init().
const string impala::BEESWAX_SERVER_NAME = "beeswax-frontend"
Definition at line 181 of file impala-server.cc.
Referenced by impala::ImpalaServer::ConnectionStart(), and CreateImpalaServer().
const int impala::BLOCKS_REQUIRED_FOR_MERGE = 3
Definition at line 31 of file sorter.cc.
Referenced by impala::Sorter::Init().
const string impala::CALLBACK_METRIC_PATTERN = "statestore-subscriber.topic-$0.processing-time-s"
Definition at line 54 of file statestore-subscriber.cc.
Referenced by impala::StatestoreSubscriber::AddTopic().
const string impala::CLUSTER_IN_QUEUE_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.cluster-in-queue"
Definition at line 66 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::CLUSTER_MEM_ESTIMATE_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.cluster-mem-estimate"
Definition at line 70 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::CLUSTER_MEM_USAGE_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.cluster-mem-usage"
Definition at line 68 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::CLUSTER_NUM_RUNNING_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.cluster-num-running"
Definition at line 64 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const StringSearch UrlParser::colon_search& impala::colon
Definition at line 39 of file url-parser.cc.
Referenced by impala::PerfCounters::GetProcSelfIOCounters(), impala::PerfCounters::GetProcSelfStatusCounters(), and impala::CpuInfo::Init().
FragmentInstanceCounters impala::coordinator_counters_
Throughput counters for the coordinator fragment.
Definition at line 342 of file coordinator.h.
const int32_t impala::CPU_DEFAULT_WEIGHT = 1024
Definition at line 38 of file cgroups-mgr.cc.
Referenced by impala::CgroupsMgr::VirtualCoresToCpuShares().
const int64_t impala::DEFAULT_REQUEST_TIMEOUT_MS = 5 * 60 * 1000
Definition at line 57 of file query-schedule.cc.
Referenced by impala::QuerySchedule::PrepareReservationRequest().
const StringVal impala::DEFAULT_STRING_CONCAT_DELIM((uint8_t *)", ", 2) static
Referenced by impala::AggregateFunctions::StringConcatUpdate().
TDescriptorTable impala::desc_tbl_
copied from TQueryExecRequest; constant across all fragments
Definition at line 197 of file coordinator.h.
Referenced by impala::DataStreamTest::CreateRowDesc(), and impala::DataStreamTest::Sender().
bool impala::disable_codegen_
Definition at line 72 of file expr-test.cc.
Referenced by main(), and TEST_F().
const string impala::ERROR_INVALID_COL_DATA
Initial value:
= "Data source returned inconsistent column data. "
    "Expected value of type $0 based on column metadata. This likely indicates a "
    "problem with the data source library."
Definition at line 51 of file data-source-scan-node.cc.
Referenced by impala::DataSourceScanNode::MaterializeNextRow().
const string impala::ERROR_INVALID_DECIMAL
Initial value:
= "Data source returned invalid decimal data. "
    "This likely indicates a problem with the data source library."
Definition at line 56 of file data-source-scan-node.cc.
Referenced by SetDecimalVal().
const string impala::ERROR_INVALID_TIMESTAMP
Initial value:
= "Data source returned invalid timestamp data. "
    "This likely indicates a problem with the data source library."
Definition at line 54 of file data-source-scan-node.cc.
Referenced by impala::DataSourceScanNode::MaterializeNextRow().
const string impala::ERROR_MISMATCHED_COL_SIZES
Initial value:
= "Data source returned columns containing "
    "different numbers of rows. This likely indicates a problem with the data source "
    "library."
Definition at line 47 of file data-source-scan-node.cc.
Referenced by impala::DataSourceScanNode::ValidateRowBatchSize().
const string impala::ERROR_NUM_COLUMNS
Initial value:
= "Data source returned unexpected number of columns. "
    "Expected $0 but received $1. This likely indicates a problem with the data source "
    "library."
Definition at line 44 of file data-source-scan-node.cc.
Referenced by impala::DataSourceScanNode::ValidateRowBatchSize().
client RuntimeProfile::EventSequence* impala::events
Definition at line 64 of file coordinator.h.
Referenced by impala::RuntimeProfile::PrettyPrint(), and TEST().
ExecEnv* impala::exec_env_
Definition at line 193 of file coordinator.h.
Referenced by impala::ImpalaServer::CatalogObjectsUrlCallback(), impala::ImpalaServer::CatalogUrlCallback(), impala::DataStreamTest::DataStreamTest(), impala::ImpalaServer::ExecuteMetadataOp(), impala::ImpalaServer::explain(), impala::ImpalaServer::HadoopVarzUrlCallback(), impala::DataStreamTest::Sender(), and impala::DataStreamTest::TearDown().
TExecSummary impala::exec_summary_
Definition at line 300 of file coordinator.h.
Referenced by exec_summary().
SpinLock impala::exec_summary_lock_ mutable
Execution summary for this query.
Definition at line 299 of file coordinator.h.
Referenced by exec_summary(), and GetExecSummaryLock().
bool impala::execution_completed_
True if execution has completed, false otherwise.
Definition at line 266 of file coordinator.h.
boost::scoped_ptr< PlanFragmentExecutor > impala::executor_
execution state of coordinator fragment
Definition at line 71 of file expr-test.cc.
Referenced by impala::FragmentMgr::FragmentExecState::Cancel(), impala::ExternalDataSourceExecutor::Close(), impala::FragmentMgr::FragmentExecState::Exec(), impala::ExternalDataSourceExecutor::GetNext(), impala::ExprTest::GetValue(), impala::ExternalDataSourceExecutor::Init(), main(), impala::ExternalDataSourceExecutor::Open(), impala::FragmentMgr::FragmentExecState::Prepare(), impala::FragmentMgr::FragmentExecState::ReportStatusCb(), and impala::ExprTest::TestNonOkStatus().
FileMoveMap impala::files_to_move_
The set of files to move after an INSERT query has run, in (src, dest) form. An empty string for the destination means that a file is to be deleted.
Definition at line 293 of file coordinator.h.
RuntimeProfile::Counter* impala::finalization_timer_
Total time spent in finalization (typically 0 except for INSERT into hdfs tables)
Definition at line 348 of file coordinator.h.
TFinalizeParams impala::finalize_params_
Only valid if needs_finalization is true.
Definition at line 222 of file coordinator.h.
int64_t impala::flag
Definition at line 51 of file cpu-info.cc.
Referenced by impala::CpuInfo::DebugString(), and impala::CpuInfo::EnableFeature().
struct { ... } impala::flag_mappings[]
Initial value:
=
{
  { "ssse3",  CpuInfo::SSSE3 },
  { "sse4_1", CpuInfo::SSE4_1 },
  { "sse4_2", CpuInfo::SSE4_2 },
  { "popcnt", CpuInfo::POPCNT },
}
Referenced by impala::CpuInfo::DebugString(), and ParseCPUFlags().
std::vector<PerFragmentProfileData> impala::fragment_profiles_
This is indexed by fragment_idx. This array is only modified at coordinator startup and query completion and does not need locks.
Definition at line 339 of file coordinator.h.
Rules* impala::g_rules static
Definition at line 93 of file redactor.cc.
Referenced by Redact(), SetRedactionRulesFromFile(), and TEST().
sasl_callback_t impala::GENERAL_CALLBACKS[5] static
Definition at line 109 of file authentication.cc.
Referenced by InitAuth().
const char*(* impala::GetImpalaBuildVersion)()
Definition at line 42 of file hdfs-lzo-text-scanner.cc.
Referenced by impala::HdfsLzoTextScanner::LoadLzoLibrary().
bool impala::has_called_wait_
Definition at line 227 of file coordinator.h.
const StringSearch UrlParser::hash_search& impala::hash
Definition at line 41 of file url-parser.cc.
Referenced by DataPartitioner::AddData(), impala::HashTableTest::BasicTest(), impala::PartitionedHashJoinNode::Partition::BuildHashTableInternal(), impala::HashUtil::CrcHash(), com.cloudera.impala.analysis.ColumnLineageGraph::createFromJSON(), DistinctEstimatUpdate(), impala::OldHashTable::Find(), impala::HashTable::Find(), FnvHash(), impala::HashUtil::FnvHash64(), impala::HashTableTest::GrowTableTest(), impala::TimestampValue::Hash(), hash_value(), impala::HashTableCtx::HashVariableLenRow(), impala::OldHashTable::HashVariableLenRow(), impala::HashTable::Insert(), impala::HashTableTest::InsertFullTest(), impala::OldHashTable::InsertImpl(), main(), NumCollisions(), impala::HashTable::PrepareBucketForInsert(), impala::HashTable::Probe(), impala::HashTableTest::ProbeTest(), impala::PartitionedAggregationNode::ProcessBatch(), impala::PartitionedHashJoinNode::ProcessBuildBatch(), impala::PartitionedHashJoinNode::ProcessProbeBatch(), impala::BaseSequenceScanner::ReadSync(), impala::OldHashTable::ResizeBuckets(), impala::HashTableTest::ScanTest(), DataPartitioner::Split(), TestCrcIntHash(), TestCrcMixedHash(), TestFnvIntHash(), and TestFnvMixedHash().
function<bool (char)> impala::HiveShouldEscape = is_any_of("\"#%\\*/:=?\u00FF") static
Definition at line 42 of file url-coding.cc.
Referenced by UrlEncode().
const string impala::HOSTNAME_PATTERN = "_HOST" static
Definition at line 115 of file authentication.cc.
Referenced by impala::SaslAuthProvider::InitKerberos().
const string impala::HS2_SERVER_NAME = "hiveserver2-frontend"
Definition at line 182 of file impala-server.cc.
Referenced by CreateImpalaServer().
const string impala::IMPALA_AUXPROP_PLUGIN = "impala-auxprop" static
Definition at line 127 of file authentication.cc.
Referenced by InitAuth(), and SaslGetOption().
sasl_auxprop_plug_t impala::impala_auxprop_plugin static
Initial value:
= {
  0,
  0,
  NULL,
  NULL,
  &ImpalaAuxpropLookup,
  const_cast<char*>(IMPALA_AUXPROP_PLUGIN.c_str()),
  NULL
}
Definition at line 318 of file authentication.cc.
Referenced by ImpalaAuxpropInit().
const std::string impala::IMPALA_CGROUP_SUFFIX = "_impala"
Definition at line 34 of file cgroups-mgr.cc.
Referenced by impala::CgroupsMgr::UniqueIdToCgroup().
const string impala::IMPALA_RESULT_CACHING_OPT = "impala.resultset.cache.size"
Definition at line 76 of file impala-hs2-server.cc.
Referenced by impala::ImpalaServer::ExecuteStatement(), and impala::ImpalaServer::TExecuteStatementReqToTQueryContext().
const parquet::CompressionCodec::type impala::IMPALA_TO_PARQUET_CODEC[]
Initial value:
= {
  parquet::CompressionCodec::UNCOMPRESSED,
  parquet::CompressionCodec::SNAPPY,
  parquet::CompressionCodec::GZIP,
  parquet::CompressionCodec::GZIP,
  parquet::CompressionCodec::SNAPPY,
  parquet::CompressionCodec::SNAPPY,
  parquet::CompressionCodec::LZO,
}
Mapping of Impala codec enums to Parquet enums.
Definition at line 64 of file parquet-common.h.
Referenced by impala::HdfsParquetTableWriter::BaseColumnWriter::codec().
const parquet::Type::type impala::IMPALA_TO_PARQUET_TYPES[]
Initial value:
= {
  parquet::Type::BOOLEAN,
  parquet::Type::BOOLEAN,
  parquet::Type::BOOLEAN,
  parquet::Type::INT32,
  parquet::Type::INT32,
  parquet::Type::INT32,
  parquet::Type::INT64,
  parquet::Type::FLOAT,
  parquet::Type::DOUBLE,
  parquet::Type::INT96,
  parquet::Type::BYTE_ARRAY,
  parquet::Type::BYTE_ARRAY,
  parquet::Type::BYTE_ARRAY,
  parquet::Type::BYTE_ARRAY,
  parquet::Type::FIXED_LEN_BYTE_ARRAY,
  parquet::Type::BYTE_ARRAY,
  parquet::Type::BYTE_ARRAY,
}
Mapping of impala types to parquet storage types. This is indexed by PrimitiveType enum
Definition at line 35 of file parquet-common.h.
Referenced by impala::HdfsParquetTableWriter::AddRowGroup(), impala::HdfsParquetTableWriter::CreateSchema(), and impala::HdfsParquetScanner::ValidateColumn().
vector<sasl_callback_t> impala::KERB_EXT_CALLBACKS static
Definition at line 111 of file authentication.cc.
Referenced by impala::SaslAuthProvider::GetServerTransportFactory(), and InitAuth().
vector<sasl_callback_t> impala::KERB_INT_CALLBACKS static
Definition at line 110 of file authentication.cc.
Referenced by impala::SaslAuthProvider::GetServerTransportFactory(), InitAuth(), and impala::SaslAuthProvider::WrapClientTransport().
const string impala::KERBEROS_MECHANISM = "GSSAPI" static
Definition at line 118 of file authentication.cc.
Referenced by impala::SaslAuthProvider::GetServerTransportFactory(), and impala::SaslAuthProvider::WrapClientTransport().
vector<sasl_callback_t> impala::LDAP_EXT_CALLBACKS static
Definition at line 112 of file authentication.cc.
Referenced by impala::SaslAuthProvider::GetServerTransportFactory(), and InitAuth().
const string impala::LDAP_URI_PREFIX = "ldap://" static
Definition at line 122 of file authentication.cc.
Referenced by impala::AuthManager::Init(), and SaslLdapCheckPass().
const string impala::LDAPS_URI_PREFIX = "ldaps://" static
Definition at line 123 of file authentication.cc.
Referenced by impala::AuthManager::Init().
const string impala::LINEAGE_LOG_FILE_PREFIX = "impala_lineage_log_1.0-"
Definition at line 177 of file impala-server.cc.
Referenced by impala::ImpalaServer::InitLineageLogging().
const string impala::LLAMA_RESTART_SEARCH_STRING = "unknown handle"
Definition at line 65 of file resource-broker.cc.
Referenced by impala::ResourceBroker::LlamaHasRestarted().
mutex impala::llvm_initialization_lock static
Definition at line 75 of file llvm-codegen.cc.
Referenced by impala::LlvmCodeGen::InitializeLlvm().
bool impala::llvm_initialized = false static
Definition at line 76 of file llvm-codegen.cc.
Referenced by impala::LlvmCodeGen::InitializeLlvm(), and impala::LlvmCodeGen::LlvmCodeGen().
const string impala::LOCAL_ADMITTED_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-admitted"
Definition at line 50 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_COMPLETED_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-completed"
Definition at line 60 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_DEQUEUED_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-dequeued"
Definition at line 54 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_IN_QUEUE_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-in-queue"
Definition at line 74 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_MEM_ESTIMATE_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-mem-estimate"
Definition at line 78 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_MEM_USAGE_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-mem-usage"
Definition at line 76 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_NUM_RUNNING_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-num-running"
Definition at line 72 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_QUEUED_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-queued"
Definition at line 52 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_REJECTED_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-rejected"
Definition at line 56 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_TIME_IN_QUEUE_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-time-in-queue-ms"
Definition at line 62 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
const string impala::LOCAL_TIMED_OUT_METRIC_KEY_FORMAT
Initial value:
=
  "admission-controller.$0.local-timed-out"
Definition at line 58 of file admission-controller.cc.
Referenced by impala::AdmissionController::GetPoolMetrics().
boost::mutex impala::lock_
protects all fields below
Definition at line 233 of file coordinator.h.
Referenced by impala::DataStreamRecvr::SenderQueue::AddBatch(), impala::ExecNode::RowBatchQueue::AddBatch(), BoostConsumeThread(), BoostProduceThread(), impala::DataStreamRecvr::SenderQueue::Cancel(), impala::ChildQuery::Cancel(), impala::DiskIoMgr::ScanRange::Cancel(), impala::ExecNode::RowBatchQueue::Cleanup(), impala::DiskIoMgr::RequestContextCache::DebugString(), impala::ImpalaServer::QueryExecState::Done(), impala::ChildQuery::ExecAndFetch(), impala::ImpalaServer::QueryExecState::ExecDdlRequest(), impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest(), impala::ImpalaServer::QueryExecState::FetchNextBatch(), impala::DataStreamRecvr::SenderQueue::GetBatch(), impala::DiskIoMgr::RequestContextCache::GetNewContext(), impala::DiskIoMgr::ScanRange::GetNext(), impala::ChildQuery::IsCancelled(), RpcEventHandlerManager::JsonCallback(), impala::FifoMultimap< Key, Value >::Pop(), impala::FifoMultimap< Key, Value >::Put(), RpcEventHandlerManager::RegisterEventHandler(), RpcEventHandlerManager::ResetCallback(), impala::DiskIoMgr::RequestContextCache::ReturnContext(), impala::ImpalaServer::QueryExecState::SetResultCache(), impala::ImpalaServer::QueryExecState::UpdateQueryState(), impala::ImpalaServer::QueryExecState::UpdateTableAndColumnStats(), impala::ImpalaServer::QueryExecState::Wait(), and impala::ImpalaServer::QueryExecState::WaitForChildQueries().
const uint32_t impala::MAX_CANCELLATION_QUEUE_SIZE = 65536
Definition at line 179 of file impala-server.cc.
Referenced by impala::ImpalaServer::ImpalaServer(), and impala::ImpalaServer::MembershipCallback().
const double impala::MAX_ERROR = 0.0001 static
Definition at line 33 of file decimal-test.cc.
Referenced by TEST(), and VerifyFuzzyEquals().
const int impala::MAX_NM_MISSED_HEARTBEATS = 5
Definition at line 189 of file impala-server.cc.
Referenced by impala::ImpalaServer::DetectNmFailures().
const int impala::MAX_STRING_SAMPLE_LEN = 10 static
Definition at line 732 of file aggregate-functions.cc.
Referenced by impala::ReservoirSample< StringVal >::ReservoirSample().
const int impala::MAX_WIDTH = 32
Definition at line 31 of file rle-test.cc.
Referenced by TEST().
string impala::name
Definition at line 50 of file cpu-info.cc.
Referenced by impala::Benchmark::AddBenchmark(), impala::LlvmCodeGen::AddFunctionToJit(), impala::Metric::AddStandardFields(), com.cloudera.impala.analysis.TypeDef::analyzeScalarType(), com.cloudera.impala.analysis.Expr::checkReturnsBool(), CodegenCrcHash(), com.cloudera.impala.catalog.Column::Column(), com.cloudera.impala.catalog.CatalogObjectCache< T extends CatalogObject >::contains(), com.cloudera.impala.catalog.Db::containsFunction(), com.cloudera.impala.catalog.AggregateFunction::createAnalyticBuiltin(), com.cloudera.impala.catalog.AggregateFunction::createBuiltin(), com.cloudera.impala.analysis.LimitElement::evalIntegerExpr(), com.cloudera.impala.util.EventSequence::EventSequence(), com.cloudera.impala.catalog.Type::fromThrift(), com.cloudera.impala.catalog.Function::Function(), com.cloudera.impala.catalog.CatalogObjectCache< T extends CatalogObject >::get(), com.cloudera.impala.analysis.Expr::getBuiltinFunction(), com.cloudera.impala.catalog.Table::getColumnNamesWithHmsStats(), com.cloudera.impala.catalog.Catalog::getDataSources(), impala::DiskInfo::GetDeviceNames(), GetHostname(), impala::CodegenAnyVal::GetIsNull(), com.cloudera.impala.catalog.Type::getJavaSqlType(), impala::CodegenAnyVal::GetVal(), HostnameToIpAddrs(), impala::CpuInfo::Init(), impala::HdfsAvroTableWriter::Init(), impala::RuntimeState::InitMemTrackers(), impala::JvmMetric::InitMetrics(), Java_com_cloudera_impala_service_FeSupport_NativeFeTestInit(), main(), impala::ThriftThreadFactory::newThread(), com.cloudera.impala.analysis.ArithmeticExpr.Operator::Operator(), com.cloudera.impala.analysis.BinaryPredicate.Operator::Operator(), ParseCPUFlags(), impala::HdfsTableSink::Prepare(), com.cloudera.impala.catalog.CatalogObjectCache< T extends CatalogObject >::remove(), com.cloudera.impala.analysis.ResetMetadataStmt::ResetMetadataStmt(), com.cloudera.impala.catalog.Function::setName(), impala::PerfCounters::Snapshot(), impala::ThriftServer::ThriftServerEventProcessor::StartAndWaitForServer(), com.cloudera.impala.catalog.StructField::StructField(), impala::Thread::SuperviseThread(), impala::RpcEventHandler::ToJson(), com.cloudera.impala.analysis.FunctionName::toThrift(), and com.cloudera.impala.authorization.User::User().
JNINativeMethod impala::native_methods[] static
Initial value:
= {
  {
    (char*)"NativeFeTestInit", (char*)"()V",
    (void*)::Java_com_cloudera_impala_service_FeSupport_NativeFeTestInit
  },
  {
    (char*)"NativeEvalConstExprs", (char*)"([B[B)[B",
    (void*)::Java_com_cloudera_impala_service_FeSupport_NativeEvalConstExprs
  },
  {
    (char*)"NativeCacheJar", (char*)"([B)[B",
    (void*)::Java_com_cloudera_impala_service_FeSupport_NativeCacheJar
  },
  {
    (char*)"NativeLookupSymbol", (char*)"([B)[B",
    (void*)::Java_com_cloudera_impala_service_FeSupport_NativeLookupSymbol
  },
  {
    (char*)"NativePrioritizeLoad", (char*)"([B)[B",
    (void*)::Java_com_cloudera_impala_service_FeSupport_NativePrioritizeLoad
  },
  {
    (char*)"NativeGetStartupOptions", (char*)"()[B",
    (void*)::Java_com_cloudera_impala_service_FeSupport_NativeGetStartupOptions
  },
}
Definition at line 319 of file fe-support.cc.
Referenced by InitFeSupport().
bool impala::needs_finalization_
True if the query needs a post-execution step to tidy up.
Definition at line 219 of file coordinator.h.
const int impala::NUM_BUCKETS = 100 static
Definition at line 729 of file aggregate-functions.cc.
Referenced by impala::AggregateFunctions::HistogramFinalize(), and TEST().
const long impala::num_flags = sizeof(flag_mappings) / sizeof(flag_mappings[0]) static
Definition at line 59 of file cpu-info.cc.
Referenced by impala::CpuInfo::DebugString(), and ParseCPUFlags().
const int impala::NUM_PC_BITMAPS = 64 static
Definition at line 558 of file aggregate-functions.cc.
Referenced by DistinceEstimateFinalize(), DistinctEstimateBitMapToString(), impala::AggregateFunctions::PcInit(), impala::AggregateFunctions::PcMerge(), impala::AggregateFunctions::PcsaFinalize(), impala::AggregateFunctions::PcsaUpdate(), and impala::AggregateFunctions::PcUpdate().
int impala::num_remaining_backends_
Count of the number of backends for which done != true. When this hits 0, any Wait()'ing thread is notified
Definition at line 278 of file coordinator.h.
int impala::num_remote_fragements_complete_
Number of remote fragments that have completed.
Definition at line 269 of file coordinator.h.
const int impala::NUM_SAMPLES = NUM_BUCKETS * NUM_SAMPLES_PER_BUCKET static
Definition at line 731 of file aggregate-functions.cc.
Referenced by impala::AggregateFunctions::ReservoirSampleMerge(), and impala::AggregateFunctions::ReservoirSampleUpdate().
const int impala::NUM_SAMPLES_PER_BUCKET = 200 static
Definition at line 730 of file aggregate-functions.cc.
const int impala::NUM_STRINGS = sizeof(STRINGS) / sizeof(StringValue) static
Definition at line 55 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::CreateStringBatch(), TEST(), and impala::SimpleTupleStreamTest::VerifyResults().
const int impala::NUM_THREADS = 5
Definition at line 28 of file thread-pool-test.cc.
Referenced by TEST(), and TEST_F().
boost::scoped_ptr<ObjectPool> impala::obj_pool_
Object pool owned by the coordinator. Any executor will have its own pool.
Definition at line 296 of file coordinator.h.
Referenced by impala::DataStreamTest::CreateRowDesc(), impala::DataStreamTest::CreateTupleComparator(), obj_pool(), impala::DataStreamTest::Sender(), and impala::DataStreamTest::StartReceiver().
const uint32_t impala::ONE_BILLION = 1000000000 static
Definition at line 23 of file multi-precision.cc.
Referenced by operator<<().
const uint32_t impala::PARQUET_CURRENT_VERSION = 1
Definition at line 31 of file parquet-common.h.
Referenced by impala::HdfsParquetTableWriter::Init(), and impala::HdfsParquetScanner::ValidateFileMetadata().
const THdfsCompression::type impala::PARQUET_TO_IMPALA_CODEC[]
Initial value:
= {
  THdfsCompression::NONE,
  THdfsCompression::SNAPPY,
  THdfsCompression::GZIP,
  THdfsCompression::LZO
}
Mapping of Parquet codec enums to Impala enums.
Definition at line 56 of file parquet-common.h.
Referenced by impala::HdfsParquetScanner::BaseColumnReader::codec(), and impala::HdfsParquetScanner::BaseColumnReader::Reset().
const uint8_t impala::PARQUET_VERSION_NUMBER[4] = {'P', 'A', 'R', '1'}
Definition at line 30 of file parquet-common.h.
Referenced by impala::HdfsParquetScanner::ProcessFooter(), impala::HdfsParquetTableWriter::WriteFileFooter(), and impala::HdfsParquetTableWriter::WriteFileHeader().
const int impala::PC_BITMAP_LENGTH = 32 static
Definition at line 559 of file aggregate-functions.cc.
Referenced by DistinceEstimateFinalize(), DistinctEstimateBitMapToString(), impala::AggregateFunctions::PcInit(), impala::AggregateFunctions::PcMerge(), impala::AggregateFunctions::PcsaUpdate(), and impala::AggregateFunctions::PcUpdate().
const float impala::PC_THETA = 0.77351f static
Definition at line 560 of file aggregate-functions.cc.
Referenced by DistinceEstimateFinalize().
const string impala::PER_HOST_MEM_KEY = "Estimated Per-Host Mem" static
Definition at line 53 of file query-exec-state.cc.
Referenced by impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest().
const string impala::PER_HOST_VCORES_KEY = "Estimated Per-Host VCores" static
Definition at line 54 of file query-exec-state.cc.
Referenced by impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest().
PartitionStatusMap impala::per_partition_status_
The following two structures, partition_row_counts_ and files_to_move_ are filled in as the query completes, and track the results of INSERT queries that alter the structure of tables. They are either the union of the reports from all backends, or taken from the coordinator fragment: only one of the two can legitimately produce updates. The set of partitions that have been written to or updated by all backends, along with statistics such as the number of rows written (may be 0). For unpartitioned tables, the empty string denotes the entire table.
Definition at line 289 of file coordinator.h.
Referenced by per_partition_status().
const string impala::PIN_FAILED_ERROR_MSG
Initial value:
= "Failed to pin block for $0-length data needed "
    "for sorting. Reducing query concurrency or increasing the memory available to "
    "Impala may help running this query."
Definition at line 35 of file sorter.cc.
Referenced by impala::Sorter::Run::PrepareRead().
const string impala::PLAIN_MECHANISM = "PLAIN" static
Definition at line 119 of file authentication.cc.
Referenced by impala::SaslAuthProvider::GetServerTransportFactory().
boost::unordered_map<TPlanNodeId, int> impala::plan_node_id_to_summary_map_
A mapping of plan node ids to index into exec_summary_.nodes.
Definition at line 303 of file coordinator.h.
const string impala::PROFILE_INFO_KEY_ADMISSION_RESULT = "Admission result"
Definition at line 86 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
const string impala::PROFILE_INFO_VAL_ADMIT_IMMEDIATELY = "Admitted immediately"
Definition at line 87 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
const string impala::PROFILE_INFO_VAL_ADMIT_QUEUED = "Admitted (queued)"
Definition at line 88 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
const string impala::PROFILE_INFO_VAL_REJECTED = "Rejected"
Definition at line 89 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
const string impala::PROFILE_INFO_VAL_TIME_OUT = "Timed out (queued)"
Definition at line 90 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
const string impala::PROFILE_LOG_FILE_PREFIX = "impala_profile_log_1.1-"
Definition at line 175 of file impala-server.cc.
Referenced by impala::ImpalaServer::InitProfileLogging().
ProgressUpdater impala::progress_
Keeps track of number of completed ranges and total scan ranges.
Definition at line 230 of file coordinator.h.
Referenced by progress().
const StringSearch UrlParser::protocol_search& impala::protocol
Definition at line 36 of file url-parser.cc.
Referenced by ExecuteAndCancelOperationTest().
TQueryCtx impala::query_ctx_
Definition at line 198 of file coordinator.h.
Referenced by impala::ImpalaServer::QueryExecState::ExecLocalCatalogOp().
const string impala::QUERY_EVENT_COMPLETED_ADMISSION = "Completed admission"
Definition at line 83 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
const string impala::QUERY_EVENT_SUBMIT_FOR_ADMISSION = "Submit for admission"
Definition at line 82 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
RuntimeProfile::EventSequence* impala::query_events_
Event timeline for this query. Unowned.
Definition at line 309 of file coordinator.h.
Referenced by impala::ImpalaServer::QueryExecState::Cancel(), impala::ImpalaServer::QueryExecState::Done(), impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest(), impala::ImpalaServer::QueryExecState::UpdateCatalog(), impala::ImpalaServer::QueryExecState::UpdateTableAndColumnStats(), and impala::ImpalaServer::QueryExecState::WaitForChildQueries().
TUniqueId impala::query_id_
Definition at line 194 of file coordinator.h.
Referenced by impala::CancellationWork::operator<(), impala::CancellationWork::operator==(), query_id(), and impala::CancellationWork::query_id().
boost::shared_ptr<MemTracker> impala::query_mem_tracker_
Query mem tracker for this coordinator initialized in Exec(). Only valid if there is no coordinator fragment (i.e. executor_ == NULL). If executor_ is not NULL, this->runtime_state()->query_mem_tracker() returns the query mem tracker. (See this->query_mem_tracker())
Definition at line 252 of file coordinator.h.
boost::scoped_ptr<RuntimeProfile> impala::query_profile_
Aggregate counters for the entire query.
Definition at line 306 of file coordinator.h.
Referenced by query_profile().
Status impala::query_status_
Overall status of the entire query; set to the first reported fragment error status or to CANCELLED, if Cancel() is called.
Definition at line 237 of file coordinator.h.
Referenced by impala::ImpalaServer::QueryExecState::FetchNextBatch(), impala::ImpalaServer::QueryExecState::FetchRows(), impala::ImpalaServer::QueryExecState::UpdateQueryStatus(), and impala::ImpalaServer::QueryExecState::WaitForChildQueries().
const StringSearch UrlParser::question_search& impala::question
Definition at line 40 of file url-parser.cc.
const string impala::QUEUED_MEM_LIMIT
Initial value:
= "query memory estimate $0 plus current pool "
    "memory estimate $1 is over pool memory limit $2"
Definition at line 113 of file admission-controller.cc.
Referenced by impala::AdmissionController::CanAdmitRequest().
const string impala::QUEUED_NUM_RUNNING = "number of running queries $0 is over limit $1"
Definition at line 111 of file admission-controller.cc.
Referenced by impala::AdmissionController::CanAdmitRequest().
const string impala::QUEUED_QUEUE_NOT_EMPTY
Initial value:
= "queue is not empty (size $0); queued queries are "
    "executed first"
Definition at line 116 of file admission-controller.cc.
Referenced by impala::AdmissionController::CanAdmitRequest().
const string impala::REASON_DISABLED_MEM_LIMIT = "disabled by mem limit set to 0"
Definition at line 95 of file admission-controller.cc.
Referenced by impala::AdmissionController::RejectRequest().
const string impala::REASON_DISABLED_REQUESTS_LIMIT = "disabled by requests limit set to 0"
Definition at line 96 of file admission-controller.cc.
Referenced by impala::AdmissionController::RejectRequest().
const string impala::REASON_QUEUE_FULL = "queue full, limit=$0, num_queued=$1"
Definition at line 97 of file admission-controller.cc.
Referenced by impala::AdmissionController::RejectRequest().
const string impala::REASON_REQ_OVER_MEM_LIMIT
Initial value:
=
    "request memory estimate $0 is greater than pool limit $1.\n\n"
    "If the memory estimate appears to be too high, use the MEM_LIMIT query option to "
    "override the memory estimates in admission decisions. Check the explain plan for "
    "warnings about missing stats. Running COMPUTE STATS may help. You may also "
    "consider using query hints to manually improve the plan.\n\n"
    "See the Impala documentation for more details regarding the MEM_LIMIT query "
    "option, table stats, and query hints. If the memory estimate is still too high, "
    "consider modifying the query to reduce the memory impact or increasing the "
    "available memory."
Definition at line 98 of file admission-controller.cc.
Referenced by impala::AdmissionController::RejectRequest().
const string impala::REQUEST_POOL_MEM_TRACKER_LABEL_FORMAT = "RequestPool=$0"
Definition at line 44 of file mem-tracker.cc.
Referenced by impala::MemTracker::GetRequestPoolMemTracker().
bool impala::returned_all_results_
If true, the query is done returning all results. It is possible that the coordinator still needs to wait for cleanup on remote fragments (e.g. queries with limit) Once this is set to true, errors from remote fragments are ignored.
Definition at line 243 of file coordinator.h.
const string impala::ROOT_COUNTER = "" static
Definition at line 47 of file runtime-profile.cc.
Referenced by impala::RuntimeProfile::PrettyPrint().
const string& impala::ROOT_PARTITION_KEY static
Initial value:
=
    g_ImpalaInternalService_constants.ROOT_PARTITION_KEY
Definition at line 28 of file hbase-table-sink.cc.
Referenced by impala::HBaseTableSink::Prepare(), impala::HBaseTableSink::Send(), and impala::HdfsTableSink::Send().
const string& impala::ROOT_PARTITION_KEY static
Initial value:
=
    g_ImpalaInternalService_constants.ROOT_PARTITION_KEY
Definition at line 52 of file hdfs-table-sink.cc.
const RowDescriptor* impala::row_desc_
owned by plan root, which resides in runtime_state_'s pool
Definition at line 255 of file coordinator.h.
Referenced by impala::DataStreamSender::Channel::AddRow(), impala::DataStreamTest::CreateRowBatch(), impala::DataStreamTest::CreateRowDesc(), impala::DataStreamTest::CreateTupleComparator(), impala::DataStreamSender::Channel::Init(), impala::HBaseTableSink::PrepareExprs(), impala::DataStreamTest::ReadStreamMerging(), impala::DataStreamTest::Sender(), and impala::DataStreamTest::StartReceiver().
function<bool (char)> impala::ShouldNotEscape = is_any_of("-_.~") static
Definition at line 46 of file url-coding.cc.
Referenced by UrlEncode().
const StringSearch UrlParser::slash_search& impala::slash
Definition at line 38 of file url-parser.cc.
const int32_t impala::SLEEP_INTERVAL_MS = 5000
Definition at line 58 of file statestore-subscriber.cc.
Referenced by impala::StatestoreSubscriber::RecoveryModeChecker().
string impala::space[] = {"", " ", "\t\t\t", "\n\n\n", "\v\v\v", "\f\f\f", "\r\r\r"}
Definition at line 31 of file string-parser-test.cc.
Referenced by impala::FileSystemUtil::GetSpaceAvailable(), TestAllFloatVariants(), TestBoolValue(), and TestIntValue().
int impala::space_len = 7
Definition at line 32 of file string-parser-test.cc.
Referenced by TestAllFloatVariants(), TestBoolValue(), and TestIntValue().
const string impala::STATESTORE_ID = "STATESTORE"
Definition at line 51 of file statestore-subscriber.cc.
Referenced by impala::StatestoreSubscriber::Heartbeat(), and impala::StatestoreSubscriber::RecoveryModeChecker().
const string impala::STATUS_REJECTED = "Rejected query from pool $0 : $1"
Definition at line 94 of file admission-controller.cc.
Referenced by impala::AdmissionController::RejectRequest().
const string impala::STATUS_TIME_OUT
Initial value:
= "Admission for query exceeded timeout $0ms. Queued "
    "reason: $1"
Definition at line 119 of file admission-controller.cc.
Referenced by impala::AdmissionController::AdmitQuery().
TStmtType::type impala::stmt_type_
copied from TQueryExecRequest, governs when to call ReportQuerySummary
Definition at line 201 of file coordinator.h.
const StringValue impala::STRINGS[] static
Initial value:
= {
  StringValue("ABC"),
  StringValue("HELLO"),
  StringValue("123456789"),
  StringValue("FOOBAR"),
  StringValue("ONE"),
  StringValue("THREE"),
  StringValue("abcdefghijklmno"),
  StringValue("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
  StringValue("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
}
Definition at line 43 of file buffered-tuple-stream-test.cc.
Referenced by impala::SimpleTupleStreamTest::CreateStringBatch(), and impala::SimpleTupleStreamTest::VerifyResults().
const string impala::TABLES_MISSING_STATS_KEY = "Tables Missing Stats" static
Definition at line 55 of file query-exec-state.cc.
Referenced by impala::ImpalaServer::QueryExecState::ExecQueryOrDmlRequest().
int impala::thread_counters[NUM_THREADS]
Definition at line 29 of file thread-pool-test.cc.
Referenced by Count(), and TEST().
const string impala::THREAD_INVOLUNTARY_CONTEXT_SWITCHES = "InvoluntaryContextSwitches" static
Definition at line 44 of file runtime-profile.cc.
Referenced by impala::RuntimeProfile::AddThreadCounters().
shared_ptr<ThreadMgr> impala::thread_manager
Definition at line 43 of file thread.cc.
Referenced by InitThreading(), impala::Thread::StartThread(), StartThreadInstrumentation(), and impala::Thread::SuperviseThread().
mutex impala::thread_mutexes[NUM_THREADS]
Definition at line 32 of file thread-pool-test.cc.
Referenced by Count(), and TEST().
const string impala::THREAD_SYS_TIME = "SysTime" static
Definition at line 42 of file runtime-profile.cc.
Referenced by impala::RuntimeProfile::AddThreadCounters().
const string impala::THREAD_TOTAL_TIME = "TotalWallClockTime" static
Definition at line 40 of file runtime-profile.cc.
Referenced by impala::RuntimeProfile::AddThreadCounters().
const string impala::THREAD_USER_TIME = "UserTime" static
Definition at line 41 of file runtime-profile.cc.
Referenced by impala::RuntimeProfile::AddThreadCounters().
const string impala::THREAD_VOLUNTARY_CONTEXT_SWITCHES = "VoluntaryContextSwitches" static
Definition at line 43 of file runtime-profile.cc.
Referenced by impala::RuntimeProfile::AddThreadCounters().
const string impala::THREADS_TEMPLATE = "threadz.tmpl" static
Definition at line 41 of file thread.cc.
Referenced by impala::ThreadMgr::StartInstrumentation().
const string impala::THREADS_WEB_PAGE = "/threadz" static
Definition at line 40 of file thread.cc.
Referenced by impala::ThreadMgr::StartInstrumentation().
const size_t impala::TIMESTAMP_SIZE = sizeof(int64_t) + sizeof(int32_t)
Definition at line 60 of file data-source-scan-node.cc.
Referenced by impala::DataSourceScanNode::MaterializeNextRow().
const string impala::TMP_SUB_DIR_NAME = "impala-scratch"
Definition at line 42 of file tmp-file-mgr.cc.
Referenced by impala::TmpFileMgr::Init().
const char impala::TOPIC_KEY_DELIMITER = '!'
Definition at line 46 of file admission-controller.cc.
Referenced by MakePoolTopicKey(), and ParsePoolTopicKey().
boost::unordered_set<TNetworkAddress> impala::unique_hosts_
The set of hosts that the query will run on. Populated in Exec.
Definition at line 345 of file coordinator.h.
const int impala::VALIDATE_INTERVAL = 10000
Definition at line 148 of file internal-queue-test.cc.
Referenced by ConsumerThread(), and ProducerThread().
boost::mutex impala::wait_lock_
ensures single-threaded execution of Wait(); must not hold lock_ when acquiring this
Definition at line 225 of file coordinator.h.