Impala: llama Namespace Reference
llama Namespace Reference
Functions
ostream & operator<< (ostream &os, const TUniqueId &id)
ostream & operator<< (ostream &os, const TNetworkAddress &address)
ostream & operator<< (ostream &os, const TResource &resource)
ostream & operator<< (ostream &os, const TAllocatedResource &resource)
ostream & operator<< (ostream &os, const llama::TLlamaAMGetNodesRequest &request)
ostream & operator<< (ostream &os, const llama::TLlamaAMReservationRequest &request)
ostream & operator<< (ostream &os, const llama::TLlamaAMReservationExpansionRequest &request)
ostream & operator<< (ostream &os, const llama::TLlamaAMReleaseRequest &request)
llama::TUniqueId & operator<< (llama::TUniqueId &dest, const impala::TUniqueId &src)
'Assignment' operators to convert types between the llama and impala namespaces.
impala::TUniqueId & operator<< (impala::TUniqueId &dest, const llama::TUniqueId &src)
bool operator== (const impala::TUniqueId &impala_id, const llama::TUniqueId &llama_id)
llama::TNetworkAddress & operator<< (llama::TNetworkAddress &dest, const impala::TNetworkAddress &src)
impala::TNetworkAddress & operator<< (impala::TNetworkAddress &dest, const llama::TNetworkAddress &src)
impala::Status LlamaStatusToImpalaStatus (const TStatus &status, const string &err_prefix)
string GetShortName (const string &user)
std::ostream & operator<< (std::ostream &os, const llama::TUniqueId &id)
std::ostream & operator<< (std::ostream &os, const llama::TNetworkAddress &address)
std::ostream & operator<< (std::ostream &os, const llama::TResource &resource)
std::ostream & operator<< (std::ostream &os, const llama::TAllocatedResource &resource)
std::ostream & operator<< (std::ostream &os, const llama::TLlamaAMGetNodesRequest &request)
std::ostream & operator<< (std::ostream &os, const llama::TLlamaAMReservationRequest &request)
std::ostream & operator<< (std::ostream &os, const llama::TLlamaAMReservationExpansionRequest &request)
std::ostream & operator<< (std::ostream &os, const llama::TLlamaAMReleaseRequest &request)
impala::Status LlamaStatusToImpalaStatus (const llama::TStatus &status, const std::string &err_prefix="")
std::size_t hash_value (const llama::TUniqueId &id)
This function must be called 'hash_value' to be picked up by boost.
std::string GetShortName (const std::string &user)
Function Documentation
std::string llama::GetShortName (const std::string & user)
Get the short version of the user name (the user's name up to the first '/' or '@') If neither are found (or are found at the beginning of the user name) return username.
string llama::GetShortName (const string & user)
Definition at line 135 of file llama-util.cc.
Referenced by impala::QuerySchedule::PrepareReservationRequest().
std::size_t llama::hash_value (const llama::TUniqueId & id) inline
This function must be called 'hash_value' to be picked up by boost.
Definition at line 57 of file llama-util.h.
impala::Status llama::LlamaStatusToImpalaStatus (const llama::TStatus & status, const std::string & err_prefix = "")
impala::Status llama::LlamaStatusToImpalaStatus (const TStatus & status, const string & err_prefix)
Definition at line 127 of file llama-util.cc.
References impala::Status::OK, and impala::OK.
Referenced by impala::ResourceBroker::Expand(), impala::ResourceBroker::RefreshLlamaNodes(), impala::ResourceBroker::RegisterWithLlama(), impala::ResourceBroker::Release(), and impala::ResourceBroker::Reserve().
std::ostream& llama::operator<< (std::ostream & os, const llama::TUniqueId & id)
std::ostream& llama::operator<< (std::ostream & os, const llama::TNetworkAddress & address)
std::ostream& llama::operator<< (std::ostream & os, const llama::TResource & resource)
ostream& llama::operator<< (ostream & os, const TUniqueId & id)
Definition at line 30 of file llama-util.cc.
std::ostream& llama::operator<< (std::ostream & os, const llama::TAllocatedResource & resource)
std::ostream& llama::operator<< (std::ostream & os, const llama::TLlamaAMGetNodesRequest & request)
ostream& llama::operator<< (ostream & os, const TNetworkAddress & address)
Definition at line 35 of file llama-util.cc.
std::ostream& llama::operator<< (std::ostream & os, const llama::TLlamaAMReservationRequest & request)
std::ostream& llama::operator<< (std::ostream & os, const llama::TLlamaAMReservationExpansionRequest & request)
std::ostream& llama::operator<< (std::ostream & os, const llama::TLlamaAMReleaseRequest & request)
ostream& llama::operator<< (ostream & os, const TResource & resource)
Definition at line 40 of file llama-util.cc.
ostream& llama::operator<< (ostream & os, const TAllocatedResource & resource)
Definition at line 50 of file llama-util.cc.
ostream& llama::operator<< (ostream & os, const llama::TLlamaAMGetNodesRequest & request)
Definition at line 61 of file llama-util.cc.
ostream& llama::operator<< (ostream & os, const llama::TLlamaAMReservationRequest & request)
Definition at line 66 of file llama-util.cc.
ostream& llama::operator<< (ostream & os, const llama::TLlamaAMReservationExpansionRequest & request)
Definition at line 81 of file llama-util.cc.
ostream& llama::operator<< (ostream & os, const llama::TLlamaAMReleaseRequest & request)
Definition at line 90 of file llama-util.cc.
llama::TUniqueId & llama::operator<< (llama::TUniqueId & dest, const impala::TUniqueId & src)
'Assignment' operators to convert types between the llama and impala namespaces.
Definition at line 97 of file llama-util.cc.
impala::TUniqueId & llama::operator<< (impala::TUniqueId & dest, const llama::TUniqueId & src)
Definition at line 103 of file llama-util.cc.
llama::TNetworkAddress & llama::operator<< (llama::TNetworkAddress & dest, const impala::TNetworkAddress & src)
Definition at line 113 of file llama-util.cc.
impala::TNetworkAddress & llama::operator<< (impala::TNetworkAddress & dest, const llama::TNetworkAddress & src)
Definition at line 120 of file llama-util.cc.
bool llama::operator== (const impala::TUniqueId & impala_id, const llama::TUniqueId & llama_id)
Definition at line 109 of file llama-util.cc.