Impala: be/src/util/network-perf-benchmark.cc File Reference
network-perf-benchmark.cc File Reference
#include <iostream>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/protocol/TDebugProtocol.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportUtils.h>
#include <boost/algorithm/string.hpp>
#include <boost/thread/thread.hpp>
#include "gen-cpp/NetworkTest_types.h"
#include "gen-cpp/NetworkTestService.h"
#include "common/logging.h"
#include "util/cpu-info.h"
#include "util/stopwatch.h"
#include "rpc/thrift-client.h"
#include "rpc/thrift-server.h"
#include "rpc/thrift-thread.h"
#include "common/names.h"
Classes
class TestServer
Functions
DEFINE_int32 (port, 22222,"Port for NetworkTestService")
DEFINE_int64 (send_batch_size, 0,"Batch size (in bytes). Data is split up into batches")
double Send (ThriftClient< NetworkTestServiceClient > *client, int64_t bytes)
void HandleSend (const vector< string > &tokens)
void HandleBroadcast (const vector< string > &tokens)
void ConvertToLowerCase (vector< string > *tokens)
bool ProcessCommand (const vector< string > &tokens)
int main (int argc, char **argv)
Function Documentation
void ConvertToLowerCase (vector< string > * tokens)
Definition at line 178 of file network-perf-benchmark.cc.
Referenced by main().
DEFINE_int32 (port , 22222 , "Port for NetworkTestService")
DEFINE_int64 (send_batch_size , 0 , "Batch size (in bytes). Data is split up into batches")
void HandleBroadcast (const vector< string > & tokens)
Definition at line 142 of file network-perf-benchmark.cc.
References impala::MonotonicStopWatch::ElapsedTime(), impala::ThriftClientImpl::Open(), Send(), impala::MonotonicStopWatch::Start(), and impala::MonotonicStopWatch::Stop().
Referenced by ProcessCommand().
void HandleSend (const vector< string > & tokens)
Definition at line 116 of file network-perf-benchmark.cc.
References impala::Status::ok(), impala::ThriftClientImpl::Open(), and Send().
Referenced by ProcessCommand().
int main (int argc, char ** argv)
Definition at line 201 of file network-perf-benchmark.cc.
References ConvertToLowerCase(), ProcessCommand(), TestServer::Server(), and impala::ThriftServer::StopForTesting().
bool ProcessCommand (const vector< string > & tokens)
Definition at line 185 of file network-perf-benchmark.cc.
References HandleBroadcast(), and HandleSend().
Referenced by main().
double Send (ThriftClient< NetworkTestServiceClient > * client, int64_t bytes)
Definition at line 88 of file network-perf-benchmark.cc.
References impala::MonotonicStopWatch::ElapsedTime(), impala::ThriftClient< InterfaceType >::iface(), impala::MonotonicStopWatch::Start(), and impala::MonotonicStopWatch::Stop().
Referenced by HandleBroadcast(), and HandleSend().