Impala: be/src/exec/old-hash-table.cc File Reference
old-hash-table.cc File Reference
#include "exec/old-hash-table.inline.h"
#include "codegen/codegen-anyval.h"
#include "codegen/llvm-codegen.h"
#include "exprs/expr.h"
#include "exprs/expr-context.h"
#include "exprs/slot-ref.h"
#include "runtime/mem-tracker.h"
#include "runtime/raw-value.h"
#include "runtime/runtime-state.h"
#include "runtime/string-value.inline.h"
#include "util/debug-util.h"
#include "util/error-util.h"
#include "util/impalad-metrics.h"
#include "common/names.h"
Functions
static void CodegenAssignNullValue (LlvmCodeGen *codegen, LlvmCodeGen::LlvmBuilder *builder, Value *dst, const ColumnType &type)
Variables
static const int PAGE_SIZE = 8 * 1024 * 1024
static int64_t NULL_VALUE []
Function Documentation
static void CodegenAssignNullValue (LlvmCodeGen * codegen, LlvmCodeGen::LlvmBuilder * builder, Value * dst, const ColumnType & type) static
Definition at line 169 of file old-hash-table.cc.
References impala::LlvmCodeGen::context(), impala::HashUtil::FNV_SEED, impala::LlvmCodeGen::GetIntConstant(), impala::LlvmCodeGen::ptr_type(), impala::ColumnType::type, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::OldHashTable::CodegenEvalTupleRow().
Variable Documentation
int64_t NULL_VALUE[] static
Initial value:
= { HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED,
                                HashUtil::FNV_SEED, HashUtil::FNV_SEED }
Definition at line 45 of file old-hash-table.cc.
Referenced by impala::OldHashTable::EvalRow().
const int PAGE_SIZE = 8 * 1024 * 1024 static
Definition at line 38 of file old-hash-table.cc.
Referenced by impala::OldHashTable::Close(), and impala::OldHashTable::GrowNodeArray().