Impala: be/src/benchmarks/parse-timestamp-benchmark.cc File Reference
parse-timestamp-benchmark.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <vector>
#include <sstream>
#include "runtime/string-value.h"
#include "runtime/timestamp-value.h"
#include "util/benchmark.h"
#include "util/cpu-info.h"
#include "common/names.h"
Classes
struct TestData< Decimal >
Macros
#define VALIDATE 0
#define VALIDATE_RESULT(actual, expected, str)
Functions
void AddTestData (TestData *data, const string &input)
void AddTestDataDates (TestData *data, int n, const string &startstr)
void AddTestDataTimes (TestData *data, int n, const string &startstr)
void TestImpalaDate (int batch_size, void *d)
void TestBoostStringDate (int batch_size, void *d)
void TestBoostDate (int batch_size, void *d)
void TestBoostTime (int batch_size, void *d)
int main (int argc, char **argv)
Macro Definition Documentation
#define VALIDATE 0
Definition at line 48 of file parse-timestamp-benchmark.cc.
#define VALIDATE_RESULT (actual, expected, str)
Definition at line 59 of file parse-timestamp-benchmark.cc.
Function Documentation
void AddTestData (TestData * data, const string & input)
Definition at line 69 of file parse-timestamp-benchmark.cc.
References TestData< Decimal >::data, and TestData< Decimal >::memory.
Referenced by AddTestDataDates(), and AddTestDataTimes().
void AddTestDataDates (TestData * data, int n, const string & startstr)
Definition at line 75 of file parse-timestamp-benchmark.cc.
References AddTestData().
Referenced by main().
void AddTestDataTimes (TestData * data, int n, const string & startstr)
Definition at line 88 of file parse-timestamp-benchmark.cc.
References AddTestData().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 143 of file parse-timestamp-benchmark.cc.
References impala::Benchmark::AddBenchmark(), AddTestDataDates(), AddTestDataTimes(), TestData< Decimal >::data, impala::Benchmark::GetMachineInfo(), impala::CpuInfo::Init(), impala::Benchmark::Measure(), TestData< Decimal >::result, TestBoostDate(), TestBoostStringDate(), TestBoostTime(), and TestImpalaDate().
void TestBoostDate (int batch_size, void * d)
Definition at line 120 of file parse-timestamp-benchmark.cc.
References TestData< Decimal >::data, and TestData< Decimal >::result.
Referenced by main().
void TestBoostStringDate (int batch_size, void * d)
Definition at line 110 of file parse-timestamp-benchmark.cc.
References TestData< Decimal >::data, TestData< Decimal >::memory, and TestData< Decimal >::result.
Referenced by main().
void TestBoostTime (int batch_size, void * d)
Definition at line 131 of file parse-timestamp-benchmark.cc.
References TestData< Decimal >::data, and TestData< Decimal >::result.
Referenced by main().
void TestImpalaDate (int batch_size, void * d)
Definition at line 100 of file parse-timestamp-benchmark.cc.
References TestData< Decimal >::data, and TestData< Decimal >::result.
Referenced by main().