Impala: be/src/util/pprof-path-handlers.cc File Reference
pprof-path-handlers.cc File Reference
#include "util/pprof-path-handlers.h"
#include <boost/bind.hpp>
#include <fstream>
#include <sys/stat.h>
#include <google/profiler.h>
#include <google/heap-profiler.h>
#include <google/malloc_extension.h>
#include "common/logging.h"
#include "util/webserver.h"
#include "common/names.h"
Typedefs
typedef boost::function< void(const
Webserver::ArgumentMap &args,
std::stringstream *output)> PprofCallback
Functions
DECLARE_string (heap_profile_dir)
void PprofJsonHandler (const PprofCallback &callback, const Webserver::ArgumentMap &args, Document *document)
void PprofCmdLineHandler (const Webserver::ArgumentMap &args, stringstream *output)
void PprofHeapHandler (const Webserver::ArgumentMap &args, stringstream *output)
void PprofCpuProfileHandler (const Webserver::ArgumentMap &args, stringstream *output)
void PprofGrowthHandler (const Webserver::ArgumentMap &args, stringstream *output)
void PprofSymbolHandler (const Webserver::ArgumentMap &args, stringstream *output)
Variables
const int PPROF_DEFAULT_SAMPLE_SECS = 30
Typedef Documentation
typedef boost::function<void (const Webserver::ArgumentMap& args, std::stringstream* output)> PprofCallback
Definition at line 38 of file pprof-path-handlers.cc.
Function Documentation
DECLARE_string (heap_profile_dir)
void PprofCmdLineHandler (const Webserver::ArgumentMap & args, stringstream * output)
Definition at line 52 of file pprof-path-handlers.cc.
Referenced by impala::AddPprofUrlCallbacks().
void PprofCpuProfileHandler (const Webserver::ArgumentMap & args, stringstream * output)
Definition at line 89 of file pprof-path-handlers.cc.
References PPROF_DEFAULT_SAMPLE_SECS.
Referenced by impala::AddPprofUrlCallbacks().
void PprofGrowthHandler (const Webserver::ArgumentMap & args, stringstream * output)
Definition at line 117 of file pprof-path-handlers.cc.
Referenced by impala::AddPprofUrlCallbacks().
void PprofHeapHandler (const Webserver::ArgumentMap & args, stringstream * output)
Definition at line 66 of file pprof-path-handlers.cc.
References PPROF_DEFAULT_SAMPLE_SECS.
Referenced by impala::AddPprofUrlCallbacks().
void PprofJsonHandler (const PprofCallback & callback, const Webserver::ArgumentMap & args, Document * document)
Definition at line 42 of file pprof-path-handlers.cc.
Referenced by impala::AddPprofUrlCallbacks().
void PprofSymbolHandler (const Webserver::ArgumentMap & args, stringstream * output)
Definition at line 144 of file pprof-path-handlers.cc.
Referenced by impala::AddPprofUrlCallbacks().
Variable Documentation
const int PPROF_DEFAULT_SAMPLE_SECS = 30
Definition at line 35 of file pprof-path-handlers.cc.
Referenced by PprofCpuProfileHandler(), and PprofHeapHandler().