Impala: be/src/benchmarks/rle-benchmark.cc File Reference
rle-benchmark.cc File Reference
#include <iostream>
#include <sstream>
#include "runtime/mem-pool.h"
#include "runtime/mem-tracker.h"
#include "experiments/bit-stream-utils.8byte.inline.h"
#include "util/benchmark.h"
#include "util/bit-stream-utils.inline.h"
#include "util/cpu-info.h"
#include "common/names.h"
Classes
struct TestData< Decimal >
Functions
void TestBitWriterEncode (int batch_size, void *d)
void TestBitWriter8ByteEncode (int batch_size, void *d)
void TestBitWriterDecode (int batch_size, void *d)
void TestBitWriter8ByteDecode (int batch_size, void *d)
int main (int argc, char **argv)
Variables
const int BUFFER_LEN = 64 * 4096
Function Documentation
int main (int argc, char ** argv)
Definition at line 192 of file rle-benchmark.cc.
References impala::Benchmark::AddBenchmark(), TestData< Decimal >::buffer, BUFFER_LEN, impala::CpuInfo::Init(), TestData< Decimal >::max_value, impala::Benchmark::Measure(), impala::name, TestData< Decimal >::num_bits, TestData< Decimal >::num_values, pool, TestData< Decimal >::pool, TestBitWriter8ByteDecode(), TestBitWriter8ByteEncode(), TestBitWriterDecode(), TestBitWriterEncode(), and tracker.
void TestBitWriter8ByteDecode (int batch_size, void * d)
Definition at line 171 of file rle-benchmark.cc.
References TestData< Decimal >::buffer, BUFFER_LEN, impala::BitReader_8byte::GetValue(), TestData< Decimal >::num_bits, TestData< Decimal >::num_values, and TestData< Decimal >::result.
Referenced by main().
void TestBitWriter8ByteEncode (int batch_size, void * d)
Definition at line 133 of file rle-benchmark.cc.
References TestData< Decimal >::buffer, impala::BitUtil::Ceil(), TestData< Decimal >::num_bits, TestData< Decimal >::num_values, and impala::BitWriter_8byte::PutValue().
Referenced by main().
void TestBitWriterDecode (int batch_size, void * d)
Definition at line 152 of file rle-benchmark.cc.
References TestData< Decimal >::buffer, BUFFER_LEN, impala::BitReader::GetValue(), TestData< Decimal >::num_bits, and TestData< Decimal >::num_values.
Referenced by main().
void TestBitWriterEncode (int batch_size, void * d)
Definition at line 113 of file rle-benchmark.cc.
References TestData< Decimal >::buffer, impala::BitUtil::Ceil(), impala::BitWriter::Flush(), TestData< Decimal >::num_bits, TestData< Decimal >::num_values, and impala::BitWriter::PutValue().
Referenced by main().
Variable Documentation
const int BUFFER_LEN = 64 * 4096
Definition at line 101 of file rle-benchmark.cc.
Referenced by main(), TestBitWriter8ByteDecode(), and TestBitWriterDecode().