Impala: be/src/transport/sasl-test.cc File Reference
sasl-test.cc File Reference
#include <stdio.h>
#include <sasl/sasl.h>
#include <vector>
#include <string>
Functions
static int SaslGetOption (void *context, const char *plugin_name, const char *option, const char **result, unsigned *len)
string path ("/usr/lib/sasl2:/usr/lib64/sasl2:/usr/local/lib/sasl2:/usr/lib/x86_64-linux-gnu/sasl2")
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 16 of file sasl-test.cc.
References gen_ir_descriptions::idx, path(), and SaslGetOption().
string path ("/usr/lib/sasl2:/usr/lib64/sasl2:/usr/local/lib/sasl2:/usr/lib/x86_64-linux-gnu/sasl2")
Referenced by com.cloudera.impala.planner.S3PlannerTest::cleanseFilePath(), impala::HdfsParquetScanner::CreateColumnReaders(), impala::LlvmCodeGen::FinalizeModule(), com.cloudera.impala.catalog.HdfsTable::getAvroSchema(), impala::LibCache::GetCacheEntryInternal(), com.cloudera.impala.planner.HdfsScanNode::getDisplayLabelDetail(), com.cloudera.impala.common.FileSystemUtil::getDistributedFileSystem(), impala::TmpFileMgr::GetFile(), impala::PathBuilder::GetFullBuildPath(), impala::PathBuilder::GetFullPath(), com.cloudera.impala.util.FsPermissionChecker::getPermissions(), com.cloudera.impala.util.RequestPoolService::getURL(), impala::TmpFileMgr::Init(), impala::LlvmCodeGen::InitializeLlvm(), com.cloudera.impala.common.FileSystemUtil::isDistributedFileSystem(), com.cloudera.impala.common.FileSystemUtil::isPathOnFileSystem(), com.cloudera.impala.util.NativeLibUtil::loadLibrary(), main(), impala::LibCache::MakeLocalPath(), com.cloudera.impala.util.HdfsCachingUtil::modifyCacheDirective(), impala::HdfsScanNode::Prepare(), impala::ProcessStateInfo::ReadProcCgroup(), impala::ProcessStateInfo::ReadProcIO(), impala::ProcessStateInfo::ReadProcSched(), impala::ProcessStateInfo::ReadProcStatus(), com.cloudera.impala.analysis.SelectListItem::SelectListItem(), com.cloudera.impala.analysis.SlotDescriptor::setPath(), com.cloudera.impala.util.HdfsCachingUtil::submitDirective(), com.cloudera.impala.analysis.TableRef::TableRef(), com.cloudera.impala.analysis.TableRef::tableRefToSql(), and impala::TEST().
static int SaslGetOption (void * context, const char * plugin_name, const char * option, const char ** result, unsigned * len) static
Definition at line 9 of file sasl-test.cc.
Referenced by impala::InitAuth(), and main().