Impala: be/src/experiments/hashing/split-benchmarks/cache-hash-test.cc File Reference
cache-hash-test.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <glog/logging.h>
#include <vector>
#include "cache-hash-table.h"
#include "cache-hash-table.inline.h"
#include "standard-hash-table.h"
#include "standard-hash-table.inline.h"
#include "tuple-types.h"
#include "runtime/mem-pool.h"
#include "util/cpu-info.h"
#include "util/debug-util.h"
#include "util/hash-util.h"
#include "util/runtime-profile.h"
#include "util/stopwatch.h"
Functions
template<typename T >
void Process (T *ht, const ProbeTuple *probe)
template<typename T >
uint64_t Test (T *ht, const ProbeTuple *input, uint64_t num_tuples)
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 78 of file cache-hash-test.cc.
References impala::CpuInfo::Init(), NUM_TUPLES, and impala::PrettyPrinter::Print().
template<typename T > void Process (T * ht, const ProbeTuple * probe) inline
Definition at line 52 of file cache-hash-test.cc.
template<typename T > uint64_t Test (T * ht, const ProbeTuple * input, uint64_t num_tuples)
Definition at line 67 of file cache-hash-test.cc.
References impala::StopWatch::Start(), and impala::StopWatch::Stop().