Impala: be/src/util/ssl-test.cc File Reference
ssl-test.cc File Reference
#include "common/logging.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <netdb.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
Functions
int tcp_connect (char *host, int port)
bool check_cert (SSL *ssl, char *host)
static int password_cb (char *buf, int num, int rwflag, void *userdata)
bool install_certificates (SSL_CTX *ctx, char *keyfile)
int main (int argc, char **argv)
Function Documentation
bool check_cert (SSL * ssl, char * host)
Definition at line 39 of file ssl-test.cc.
Referenced by main().
bool install_certificates (SSL_CTX * ctx, char * keyfile)
Definition at line 74 of file ssl-test.cc.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 97 of file ssl-test.cc.
References check_cert(), install_certificates(), and tcp_connect().
static int password_cb (char * buf, int num, int rwflag, void * userdata) static
Definition at line 64 of file ssl-test.cc.
int tcp_connect (char * host, int port)
Definition at line 13 of file ssl-test.cc.
Referenced by main().