Impala: impala::HdfsAvroScanner::ScopedAvroSchemaT Struct Reference
impala::HdfsAvroScanner::ScopedAvroSchemaT Struct Reference
Wrapper for avro_schema_t's that handles decrementing the ref count.
Public Member Functions
ScopedAvroSchemaT (avro_schema_t s=NULL)
ScopedAvroSchemaT (const ScopedAvroSchemaT &)
~ScopedAvroSchemaT ()
ScopedAvroSchemaT & operator= (const ScopedAvroSchemaT &)
ScopedAvroSchemaT & operator= (const avro_schema_t &s)
avro_schema_t operator-> () const
avro_schema_t get () const
Private Attributes
avro_schema_t schema
If not NULL, this owns a reference to schema.
Detailed Description
Wrapper for avro_schema_t's that handles decrementing the ref count.
Definition at line 106 of file hdfs-avro-scanner.h.
Constructor & Destructor Documentation
impala::HdfsAvroScanner::ScopedAvroSchemaT::ScopedAvroSchemaT (avro_schema_t s = NULL) inline
Definition at line 107 of file hdfs-avro-scanner.h.
HdfsAvroScanner::ScopedAvroSchemaT::ScopedAvroSchemaT (const ScopedAvroSchemaT & other)
Definition at line 50 of file hdfs-avro-scanner.cc.
References schema.
HdfsAvroScanner::ScopedAvroSchemaT::~ScopedAvroSchemaT ()
Definition at line 55 of file hdfs-avro-scanner.cc.
Member Function Documentation
avro_schema_t impala::HdfsAvroScanner::ScopedAvroSchemaT::get () const inline
Definition at line 116 of file hdfs-avro-scanner.h.
References schema.
Referenced by impala::HdfsAvroScanner::ConvertSchema(), impala::HdfsAvroScanner::ParseMetadata(), and impala::HdfsAvroScanner::ResolveSchemas().
avro_schema_t impala::HdfsAvroScanner::ScopedAvroSchemaT::operator-> () const inline
Definition at line 115 of file hdfs-avro-scanner.h.
References schema.
HdfsAvroScanner::ScopedAvroSchemaT & HdfsAvroScanner::ScopedAvroSchemaT::operator= (const ScopedAvroSchemaT & other)
Definition at line 69 of file hdfs-avro-scanner.cc.
References schema.
HdfsAvroScanner::ScopedAvroSchemaT & HdfsAvroScanner::ScopedAvroSchemaT::operator= (const avro_schema_t & s)
Definition at line 60 of file hdfs-avro-scanner.cc.
References LIKELY.
Member Data Documentation
avro_schema_t impala::HdfsAvroScanner::ScopedAvroSchemaT::schema private
If not NULL, this owns a reference to schema.
Definition at line 120 of file hdfs-avro-scanner.h.
Referenced by get(), operator->(), operator=(), and ScopedAvroSchemaT().
The documentation for this struct was generated from the following files:
be/src/exec/hdfs-avro-scanner.h
be/src/exec/hdfs-avro-scanner.cc