Impala: impala::Rule Struct Reference
impala::Rule Struct Reference
Public Member Functions
Rule (const Rule &other)
bool case_sensitive () const
const Rule & operator= (const Rule &other)
Static Public Member Functions
static Rule Create (const string &trigger, const string &search_regex, const string &replacement, bool case_sensitive)
Public Attributes
const string trigger
const Regex search_pattern
const string replacement
Private Member Functions
Rule (const string &trigger, const Regex &search_pattern, const string &replacement)
Detailed Description
Definition at line 48 of file redactor.cc.
Constructor & Destructor Documentation
impala::Rule::Rule (const Rule & other) inline
Definition at line 64 of file redactor.cc.
Referenced by Create(), and operator=().
impala::Rule::Rule (const string & trigger, const Regex & search_pattern, const string & replacement) inline private
Definition at line 84 of file redactor.cc.
Member Function Documentation
bool impala::Rule::case_sensitive () const inline
Definition at line 73 of file redactor.cc.
References search_pattern.
static Rule impala::Rule::Create (const string & trigger, const string & search_regex, const string & replacement, bool case_sensitive) inline static
Definition at line 55 of file redactor.cc.
References Rule().
Referenced by impala::RulesParser::ParseRule().
const Rule& impala::Rule::operator= (const Rule & other) inline
Definition at line 76 of file redactor.cc.
References Rule().
Member Data Documentation
const string impala::Rule::replacement
Definition at line 71 of file redactor.cc.
const Regex impala::Rule::search_pattern
Definition at line 70 of file redactor.cc.
Referenced by case_sensitive(), and impala::RulesParser::ParseRule().
const string impala::Rule::trigger
Definition at line 69 of file redactor.cc.
The documentation for this struct was generated from the following file:
be/src/util/redactor.cc