Impala: impala::AdmissionController::QueueNode Struct Reference
impala::AdmissionController::QueueNode Struct Reference
Public Member Functions
QueueNode (const QuerySchedule &query_schedule)
T * Next () const
Returns the Next/Prev node or NULL if this is the end/front.
T * Prev () const
Public Attributes
Promise< bool > is_admitted
const QuerySchedule & schedule
Detailed Description
Structure stored in a QueryQueue representing a request. This struct lives only during the call to AdmitQuery().
Definition at line 109 of file admission-controller.h.
Constructor & Destructor Documentation
impala::AdmissionController::QueueNode::QueueNode (const QuerySchedule & query_schedule) inline
Definition at line 110 of file admission-controller.h.
Member Function Documentation
template<typename T> T* impala::InternalQueue< T >::Node::Next () const inline inherited
Returns the Next/Prev node or NULL if this is the end/front.
Definition at line 48 of file internal-queue.h.
References impala::InternalQueue< T >::lock_, impala::InternalQueue< T >::Node::next, and impala::InternalQueue< T >::Node::parent_queue.
Referenced by impala::TEST(), and impala::BufferedBlockMgr::Validate().
template<typename T> T* impala::InternalQueue< T >::Node::Prev () const inline inherited
Definition at line 52 of file internal-queue.h.
References impala::InternalQueue< T >::lock_, impala::InternalQueue< T >::Node::parent_queue, and impala::InternalQueue< T >::Node::prev.
Referenced by impala::TEST().
Member Data Documentation
Promise<bool> impala::AdmissionController::QueueNode::is_admitted
Set when the request is admitted or rejected by the dequeuing thread. Used by AdmitQuery() to wait for admission or until the timeout is reached. The admission_ctrl_lock_ is not held while waiting on this promise, but the lock should be held when checking the result because the dequeuing thread holds it to Set().
Definition at line 117 of file admission-controller.h.
Referenced by impala::AdmissionController::AdmitQuery(), and impala::AdmissionController::DequeueLoop().
const QuerySchedule& impala::AdmissionController::QueueNode::schedule
The query schedule of the queued request. The schedule lives longer than the duration of the the QueueNode, which only lives the duration of the call to AdmitQuery.
Definition at line 122 of file admission-controller.h.
Referenced by impala::AdmissionController::DequeueLoop().
The documentation for this struct was generated from the following file:
be/src/scheduling/admission-controller.h