Impala: CompactStringValue< STORAGE_SIZE > Struct Template Reference
CompactStringValue< STORAGE_SIZE > Struct Template Reference
Public Member Functions
CompactStringValue (const char *str)
const char * ptr () const
int len () const
Private Attributes
union {
char bytes_ [STORAGE_SIZE]
struct {
long is_inline_: 1
long inline_len_: 7
char inline_data_ [STORAGE_SIZE-1]
}
struct {
long dummy_: 1
long indirect_len_: 15
long indirect_ptr_: 48
}
};
Detailed Description
template<int STORAGE_SIZE>
struct CompactStringValue< STORAGE_SIZE >
Definition at line 47 of file string-benchmark.cc.
Constructor & Destructor Documentation
template<int STORAGE_SIZE> CompactStringValue< STORAGE_SIZE >::CompactStringValue (const char * str) inline
Definition at line 69 of file string-benchmark.cc.
Member Function Documentation
template<int STORAGE_SIZE> int CompactStringValue< STORAGE_SIZE >::len () const inline
Definition at line 87 of file string-benchmark.cc.
Referenced by TestCompactStringsRandom(), and TestCompactStringsSequential().
template<int STORAGE_SIZE> const char* CompactStringValue< STORAGE_SIZE >::ptr () const inline
Definition at line 82 of file string-benchmark.cc.
Referenced by TestCompactStringsRandom(), and TestCompactStringsSequential().
Member Data Documentation
union { ... }
template<int STORAGE_SIZE> char CompactStringValue< STORAGE_SIZE >::bytes_[STORAGE_SIZE]
Definition at line 50 of file string-benchmark.cc.
template<int STORAGE_SIZE> long CompactStringValue< STORAGE_SIZE >::dummy_
Definition at line 59 of file string-benchmark.cc.
template<int STORAGE_SIZE> long CompactStringValue< STORAGE_SIZE >::indirect_len_
Definition at line 60 of file string-benchmark.cc.
template<int STORAGE_SIZE> long CompactStringValue< STORAGE_SIZE >::indirect_ptr_
Definition at line 61 of file string-benchmark.cc.
template<int STORAGE_SIZE> char CompactStringValue< STORAGE_SIZE >::inline_data_[STORAGE_SIZE-1]
Definition at line 56 of file string-benchmark.cc.
template<int STORAGE_SIZE> long CompactStringValue< STORAGE_SIZE >::inline_len_
Definition at line 55 of file string-benchmark.cc.
template<int STORAGE_SIZE> long CompactStringValue< STORAGE_SIZE >::is_inline_
Definition at line 54 of file string-benchmark.cc.
The documentation for this struct was generated from the following file:
be/src/benchmarks/string-benchmark.cc