Impala: impala::TupleEqualityChecker Struct Reference
impala::TupleEqualityChecker Struct Reference
Compares the equality of two Tuples, going slot by slot.
#include <tuple-row-compare.h>
Public Member Functions
TupleEqualityChecker (TupleDescriptor *tuple_desc)
bool operator() (Tuple *x, Tuple *y)
Public Attributes
TupleDescriptor * tuple_desc_
Detailed Description
Compares the equality of two Tuples, going slot by slot.
Definition at line 107 of file tuple-row-compare.h.
Constructor & Destructor Documentation
impala::TupleEqualityChecker::TupleEqualityChecker (TupleDescriptor * tuple_desc) inline
Definition at line 110 of file tuple-row-compare.h.
Member Function Documentation
bool impala::TupleEqualityChecker::operator() (Tuple * x, Tuple * y) inline
Definition at line 113 of file tuple-row-compare.h.
References impala::RawValue::Eq(), impala::Tuple::GetSlot(), impala::SlotDescriptor::is_nullable(), impala::Tuple::IsNull(), impala::SlotDescriptor::null_indicator_offset(), impala::TupleDescriptor::slots(), tuple_desc_, impala::SlotDescriptor::tuple_offset(), and impala::SlotDescriptor::type().
Member Data Documentation
TupleDescriptor* impala::TupleEqualityChecker::tuple_desc_
Definition at line 108 of file tuple-row-compare.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
be/src/util/tuple-row-compare.h