Impala: be/src/util/summary-util.cc File Reference
summary-util.cc File Reference
#include "util/summary-util.h"
#include <vector>
#include <boost/lexical_cast.hpp>
#include "common/logging.h"
#include "util/pretty-printer.h"
#include "util/redactor.h"
#include "util/table-printer.h"
#include "common/names.h"
Macros
#define COMPUTE_MAX_SUM_STATS(NAME)
Functions
void PrintExecSummary (const TExecSummary &exec_summary, int indent_level, int new_indent_level, int *node_idx, vector< vector< string > > *result)
Macro Definition Documentation
#define COMPUTE_MAX_SUM_STATS (NAME)
Value:
agg_stats.NAME += node.exec_stats[i].NAME;\
  max_stats.NAME = std::max(max_stats.NAME, node.exec_stats[i].NAME)
Referenced by PrintExecSummary().
Function Documentation
void PrintExecSummary (const TExecSummary & exec_summary, int indent_level, int new_indent_level, int * node_idx, vector< vector< string > > * result)
Definition at line 34 of file summary-util.cc.
References COMPUTE_MAX_SUM_STATS, impala::PrettyPrinter::Print(), impala::PrintExecSummary(), and impala::RedactCopy().
Referenced by impala::ImpalaServer::QuerySummaryCallback().