Impala: be/src/util/symbols-util.cc File Reference
symbols-util.cc File Reference
#include "util/symbols-util.h"
#include <cxxabi.h>
#include <sstream>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/regex.hpp>
#include "common/names.h"
Functions
static void AppendMangledToken (const string &s, stringstream *out)
static void AppendSeqId (int seq_id, stringstream *out)
static void AppendAnyValType (int namespace_id, const ColumnType &type, stringstream *s)
Variables
const char * MANGLE_PREFIX = "_Z"
Function Documentation
static void AppendAnyValType (int namespace_id, const ColumnType & type, stringstream * s) static
Definition at line 109 of file symbols-util.cc.
References AppendMangledToken(), AppendSeqId(), impala::ColumnType::DebugString(), impala::ColumnType::type, impala::TYPE_BIGINT, impala::TYPE_BOOLEAN, impala::TYPE_CHAR, impala::TYPE_DECIMAL, impala::TYPE_DOUBLE, impala::TYPE_FLOAT, impala::TYPE_INT, impala::TYPE_SMALLINT, impala::TYPE_STRING, impala::TYPE_TIMESTAMP, impala::TYPE_TINYINT, and impala::TYPE_VARCHAR.
Referenced by impala::SymbolsUtil::MangleUserFunction().
static void AppendMangledToken (const string & s, stringstream * out) static
Definition at line 77 of file symbols-util.cc.
Referenced by AppendAnyValType(), impala::SymbolsUtil::ManglePrepareOrCloseFunction(), and impala::SymbolsUtil::MangleUserFunction().
static void AppendSeqId (int seq_id, stringstream * out) static
Definition at line 88 of file symbols-util.cc.
Referenced by AppendAnyValType(), and impala::SymbolsUtil::MangleUserFunction().
Variable Documentation
const char* MANGLE_PREFIX = "_Z"
Definition at line 51 of file symbols-util.cc.
Referenced by impala::SymbolsUtil::IsMangled(), impala::SymbolsUtil::ManglePrepareOrCloseFunction(), and impala::SymbolsUtil::MangleUserFunction().