Impala: be/src/testutil/test-udfs.cc File Reference
test-udfs.cc File Reference
#include <udf/udf.h>
Functions
BooleanVal Identity (FunctionContext *context, const BooleanVal &arg)
TinyIntVal Identity (FunctionContext *context, const TinyIntVal &arg)
SmallIntVal Identity (FunctionContext *context, const SmallIntVal &arg)
IntVal Identity (FunctionContext *context, const IntVal &arg)
BigIntVal Identity (FunctionContext *context, const BigIntVal &arg)
FloatVal Identity (FunctionContext *context, const FloatVal &arg)
DoubleVal Identity (FunctionContext *context, const DoubleVal &arg)
StringVal Identity (FunctionContext *context, const StringVal &arg)
TimestampVal Identity (FunctionContext *context, const TimestampVal &arg)
DecimalVal Identity (FunctionContext *context, const DecimalVal &arg)
IntVal AllTypes (FunctionContext *context, const StringVal &string, const BooleanVal &boolean, const TinyIntVal &tiny_int, const SmallIntVal &small_int, const IntVal &int_val, const BigIntVal &big_int, const FloatVal &float_val, const DoubleVal &double_val, const DecimalVal &decimal)
StringVal NoArgs (FunctionContext *context)
BooleanVal VarAnd (FunctionContext *context, int n, const BooleanVal *args)
IntVal VarSum (FunctionContext *context, int n, const IntVal *args)
DoubleVal VarSum (FunctionContext *context, int n, const DoubleVal *args)
IntVal VarSum (FunctionContext *context, int n, const StringVal *args)
DecimalVal VarSum (FunctionContext *context, int n, const DecimalVal *args)
DoubleVal VarSumMultiply (FunctionContext *context, const DoubleVal &d, int n, const IntVal *args)
BooleanVal TestError (FunctionContext *context)
BooleanVal TestWarnings (FunctionContext *context)
IntVal Fn (FunctionContext *)
IntVal Fn (FunctionContext *, const IntVal &)
IntVal Fn (FunctionContext *, const IntVal &, const StringVal &)
IntVal Fn (FunctionContext *, const StringVal &, const IntVal &)
IntVal Fn2 (FunctionContext *, const IntVal &)
IntVal Fn2 (FunctionContext *, const IntVal &, const StringVal &)
TimestampVal ConstantTimestamp (FunctionContext *context)
BooleanVal ValidateArgType (FunctionContext *context, const StringVal &dummy)
void CountPrepare (FunctionContext *context, FunctionContext::FunctionStateScope scope)
BigIntVal Count (FunctionContext *context)
void CountClose (FunctionContext *context, FunctionContext::FunctionStateScope scope)
void ConstantArgPrepare (FunctionContext *context, FunctionContext::FunctionStateScope scope)
IntVal ConstantArg (FunctionContext *context, const IntVal &const_val)
void ConstantArgClose (FunctionContext *context, FunctionContext::FunctionStateScope scope)
void ValidateOpenPrepare (FunctionContext *context, FunctionContext::FunctionStateScope scope)
BooleanVal ValidateOpen (FunctionContext *context, const IntVal &dummy)
void ValidateOpenClose (FunctionContext *context, FunctionContext::FunctionStateScope scope)
void MemTestPrepare (FunctionContext *context, FunctionContext::FunctionStateScope scope)
BigIntVal MemTest (FunctionContext *context, const BigIntVal &bytes)
void MemTestClose (FunctionContext *context, FunctionContext::FunctionStateScope scope)
BigIntVal DoubleFreeTest (FunctionContext *context, BigIntVal bytes)
BigIntVal UnmangledSymbol (FunctionContext *context)
IntVal FourArgs (FunctionContext *context, const IntVal &v1, const IntVal &v2, const IntVal &v3, const IntVal &v4)
IntVal FiveArgs (FunctionContext *context, const IntVal &v1, const IntVal &v2, const IntVal &v3, const IntVal &v4, const IntVal &v5)
IntVal SixArgs (FunctionContext *context, const IntVal &v1, const IntVal &v2, const IntVal &v3, const IntVal &v4, const IntVal &v5, const IntVal &v6)
IntVal SevenArgs (FunctionContext *context, const IntVal &v1, const IntVal &v2, const IntVal &v3, const IntVal &v4, const IntVal &v5, const IntVal &v6, const IntVal &v7)
IntVal EightArgs (FunctionContext *context, const IntVal &v1, const IntVal &v2, const IntVal &v3, const IntVal &v4, const IntVal &v5, const IntVal &v6, const IntVal &v7, const IntVal &v8)
Function Documentation
IntVal AllTypes (FunctionContext * context, const StringVal & string, const BooleanVal & boolean, const TinyIntVal & tiny_int, const SmallIntVal & small_int, const IntVal & int_val, const BigIntVal & big_int, const FloatVal & float_val, const DoubleVal & double_val, const DecimalVal & decimal)
Definition at line 42 of file test-udfs.cc.
References impala_udf::TinyIntVal::val, impala_udf::SmallIntVal::val, impala_udf::IntVal::val, impala_udf::BigIntVal::val, impala_udf::FloatVal::val, impala_udf::DoubleVal::val, and impala_udf::DecimalVal::val4.
IntVal ConstantArg (FunctionContext * context, const IntVal & const_val)
Definition at line 211 of file test-udfs.cc.
References impala_udf::FunctionContext::GetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
void ConstantArgClose (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 217 of file test-udfs.cc.
References impala_udf::FunctionContext::Free(), impala_udf::FunctionContext::GetFunctionState(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
void ConstantArgPrepare (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 198 of file test-udfs.cc.
References impala_udf::FunctionContext::Allocate(), impala_udf::FunctionContext::GetConstantArg(), impala_udf::FunctionContext::IsArgConstant(), impala_udf::IntVal::null(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
TimestampVal ConstantTimestamp (FunctionContext * context)
Definition at line 161 of file test-udfs.cc.
BigIntVal Count (FunctionContext * context)
Definition at line 183 of file test-udfs.cc.
References impala_udf::FunctionContext::GetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
void CountClose (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 189 of file test-udfs.cc.
References impala_udf::FunctionContext::Free(), impala_udf::FunctionContext::GetFunctionState(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
void CountPrepare (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 175 of file test-udfs.cc.
References impala_udf::FunctionContext::Allocate(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
BigIntVal DoubleFreeTest (FunctionContext * context, BigIntVal bytes)
Definition at line 278 of file test-udfs.cc.
References impala_udf::FunctionContext::Free(), impala_udf::FunctionContext::TrackAllocation(), and impala_udf::BigIntVal::val.
Referenced by TEST().
IntVal EightArgs (FunctionContext * context, const IntVal & v1, const IntVal & v2, const IntVal & v3, const IntVal & v4, const IntVal & v5, const IntVal & v6, const IntVal & v7, const IntVal & v8)
Definition at line 311 of file test-udfs.cc.
References impala_udf::IntVal::val.
IntVal FiveArgs (FunctionContext * context, const IntVal & v1, const IntVal & v2, const IntVal & v3, const IntVal & v4, const IntVal & v5)
Definition at line 295 of file test-udfs.cc.
References impala_udf::IntVal::val.
IntVal Fn (FunctionContext *)
Definition at line 154 of file test-udfs.cc.
References impala_udf::IntVal::null().
IntVal Fn (FunctionContext * , const IntVal &)
Definition at line 155 of file test-udfs.cc.
References impala_udf::IntVal::null().
IntVal Fn (FunctionContext * , const IntVal & , const StringVal &)
Definition at line 156 of file test-udfs.cc.
References impala_udf::IntVal::null().
IntVal Fn (FunctionContext * , const StringVal & , const IntVal &)
Definition at line 157 of file test-udfs.cc.
References impala_udf::IntVal::null().
IntVal Fn2 (FunctionContext * , const IntVal &)
Definition at line 158 of file test-udfs.cc.
References impala_udf::IntVal::null().
IntVal Fn2 (FunctionContext * , const IntVal & , const StringVal &)
Definition at line 159 of file test-udfs.cc.
References impala_udf::IntVal::null().
IntVal FourArgs (FunctionContext * context, const IntVal & v1, const IntVal & v2, const IntVal & v3, const IntVal & v4)
Definition at line 290 of file test-udfs.cc.
References impala_udf::IntVal::val.
BooleanVal Identity (FunctionContext * context, const BooleanVal & arg)
Definition at line 22 of file test-udfs.cc.
TinyIntVal Identity (FunctionContext * context, const TinyIntVal & arg)
Definition at line 24 of file test-udfs.cc.
SmallIntVal Identity (FunctionContext * context, const SmallIntVal & arg)
Definition at line 26 of file test-udfs.cc.
IntVal Identity (FunctionContext * context, const IntVal & arg)
Definition at line 28 of file test-udfs.cc.
BigIntVal Identity (FunctionContext * context, const BigIntVal & arg)
Definition at line 30 of file test-udfs.cc.
FloatVal Identity (FunctionContext * context, const FloatVal & arg)
Definition at line 32 of file test-udfs.cc.
DoubleVal Identity (FunctionContext * context, const DoubleVal & arg)
Definition at line 34 of file test-udfs.cc.
StringVal Identity (FunctionContext * context, const StringVal & arg)
Definition at line 36 of file test-udfs.cc.
TimestampVal Identity (FunctionContext * context, const TimestampVal & arg)
Definition at line 38 of file test-udfs.cc.
DecimalVal Identity (FunctionContext * context, const DecimalVal & arg)
Definition at line 40 of file test-udfs.cc.
BigIntVal MemTest (FunctionContext * context, const BigIntVal & bytes)
Definition at line 260 of file test-udfs.cc.
References impala_udf::FunctionContext::GetFunctionState(), impala_udf::FunctionContext::THREAD_LOCAL, impala_udf::FunctionContext::TrackAllocation(), and impala_udf::BigIntVal::val.
Referenced by TEST().
void MemTestClose (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 268 of file test-udfs.cc.
References impala_udf::FunctionContext::Free(), impala_udf::FunctionContext::GetFunctionState(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
Referenced by TEST().
void MemTestPrepare (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 251 of file test-udfs.cc.
References impala_udf::FunctionContext::Allocate(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
Referenced by TEST().
StringVal NoArgs (FunctionContext * context)
Definition at line 53 of file test-udfs.cc.
References impala_udf::StringVal::ptr.
IntVal SevenArgs (FunctionContext * context, const IntVal & v1, const IntVal & v2, const IntVal & v3, const IntVal & v4, const IntVal & v5, const IntVal & v6, const IntVal & v7)
Definition at line 305 of file test-udfs.cc.
References impala_udf::IntVal::val.
IntVal SixArgs (FunctionContext * context, const IntVal & v1, const IntVal & v2, const IntVal & v3, const IntVal & v4, const IntVal & v5, const IntVal & v6)
Definition at line 300 of file test-udfs.cc.
References impala_udf::IntVal::val.
BooleanVal TestError (FunctionContext * context)
Definition at line 141 of file test-udfs.cc.
References impala_udf::FunctionContext::SetError().
Referenced by impala::TEST_F().
BooleanVal TestWarnings (FunctionContext * context)
Definition at line 147 of file test-udfs.cc.
References impala_udf::FunctionContext::AddWarning().
BigIntVal UnmangledSymbol (FunctionContext * context)
Definition at line 285 of file test-udfs.cc.
BooleanVal ValidateArgType (FunctionContext * context, const StringVal & dummy)
Definition at line 165 of file test-udfs.cc.
References impala_udf::FunctionContext::GetArgType(), impala_udf::FunctionContext::TypeDesc::type, and impala_udf::FunctionContext::TYPE_STRING.
BooleanVal ValidateOpen (FunctionContext * context, const IntVal & dummy)
Definition at line 236 of file test-udfs.cc.
References impala_udf::FunctionContext::GetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
void ValidateOpenClose (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 241 of file test-udfs.cc.
References impala_udf::FunctionContext::Free(), impala_udf::FunctionContext::GetFunctionState(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
void ValidateOpenPrepare (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 228 of file test-udfs.cc.
References impala_udf::FunctionContext::Allocate(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
BooleanVal VarAnd (FunctionContext * context, int n, const BooleanVal * args)
Definition at line 64 of file test-udfs.cc.
References impala_udf::BooleanVal::val.
IntVal VarSum (FunctionContext * context, int n, const IntVal * args)
Definition at line 73 of file test-udfs.cc.
References impala_udf::IntVal::null(), and impala_udf::IntVal::val.
DoubleVal VarSum (FunctionContext * context, int n, const DoubleVal * args)
Definition at line 85 of file test-udfs.cc.
References impala_udf::DoubleVal::null(), and impala_udf::DoubleVal::val.
IntVal VarSum (FunctionContext * context, int n, const StringVal * args)
Definition at line 99 of file test-udfs.cc.
References impala_udf::StringVal::len.
DecimalVal VarSum (FunctionContext * context, int n, const DecimalVal * args)
Definition at line 109 of file test-udfs.cc.
References impala_udf::FunctionContext::GetArgType(), impala_udf::DecimalVal::null(), impala_udf::FunctionContext::TypeDesc::precision, impala_udf::FunctionContext::SetError(), impala_udf::FunctionContext::TypeDesc::type, impala_udf::FunctionContext::TYPE_DECIMAL, and impala_udf::DecimalVal::val4.
DoubleVal VarSumMultiply (FunctionContext * context, const DoubleVal & d, int n, const IntVal * args)
Definition at line 126 of file test-udfs.cc.
References impala_udf::AnyVal::is_null, impala_udf::DoubleVal::null(), impala_udf::IntVal::val, and impala_udf::DoubleVal::val.