Impala: be/src/testutil/test-udfs.h File Reference
test-udfs.h File Reference
#include "udf/udf.h"
Functions
void MemTestPrepare (FunctionContext *context, FunctionContext::FunctionStateScope scope)
BigIntVal MemTest (FunctionContext *context, const BigIntVal &bytes)
void MemTestClose (FunctionContext *context, FunctionContext::FunctionStateScope scope)
BigIntVal DoubleFreeTest (FunctionContext *context, BigIntVal bytes)
Function Documentation
BigIntVal DoubleFreeTest (FunctionContext * context, BigIntVal bytes)
Definition at line 278 of file test-udfs.cc.
References impala_udf::FunctionContext::Free(), impala_udf::FunctionContext::TrackAllocation(), and impala_udf::BigIntVal::val.
Referenced by TEST().
BigIntVal MemTest (FunctionContext * context, const BigIntVal & bytes)
Definition at line 260 of file test-udfs.cc.
References impala_udf::FunctionContext::GetFunctionState(), impala_udf::FunctionContext::THREAD_LOCAL, impala_udf::FunctionContext::TrackAllocation(), and impala_udf::BigIntVal::val.
Referenced by TEST().
void MemTestClose (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 268 of file test-udfs.cc.
References impala_udf::FunctionContext::Free(), impala_udf::FunctionContext::GetFunctionState(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
Referenced by TEST().
void MemTestPrepare (FunctionContext * context, FunctionContext::FunctionStateScope scope)
Definition at line 251 of file test-udfs.cc.
References impala_udf::FunctionContext::Allocate(), impala_udf::FunctionContext::SetFunctionState(), and impala_udf::FunctionContext::THREAD_LOCAL.
Referenced by TEST().