Impala: be/src/testutil/test-udas.cc File Reference
test-udas.cc File Reference
#include "testutil/test-udas.h"
#include <udf/udf.h>
Functions
void TwoArgInit (FunctionContext *, IntVal *)
void TwoArgUpdate (FunctionContext *, const IntVal &, const StringVal &, IntVal *)
void TwoArgMerge (FunctionContext *, const IntVal &, IntVal *)
void VarArgInit (FunctionContext *, IntVal *)
void VarArgUpdate (FunctionContext *, const DoubleVal &, int, const StringVal *, IntVal *)
void VarArgMerge (FunctionContext *, const IntVal &, IntVal *)
void AggUpdate (FunctionContext *, const IntVal &, IntVal *)
void AggUpdate (FunctionContext *, const IntVal &, const IntVal &, IntVal *)
void AggFn (FunctionContext *, const IntVal &, IntVal *)
void AggInit (FunctionContext *, IntVal *)
void AggMerge (FunctionContext *, const IntVal &, IntVal *)
IntVal AggSerialize (FunctionContext *, const IntVal &i)
IntVal AggFinalize (FunctionContext *, const IntVal &i)
void AggUpdate (FunctionContext *, const StringVal &, const DoubleVal &, StringVal *)
void Agg2Update (FunctionContext *, const StringVal &, const DoubleVal &, StringVal *)
void Agg (FunctionContext *, const StringVal &, const DoubleVal &, StringVal *)
void AggInit (FunctionContext *, StringVal *)
void AggMerge (FunctionContext *, const StringVal &, StringVal *)
StringVal AggSerialize (FunctionContext *, const StringVal &v)
StringVal AggFinalize (FunctionContext *, const StringVal &v)
void Agg (FunctionContext *, const IntVal &, BufferVal *)
void AggUpdate (FunctionContext *, const IntVal &, BufferVal *)
void AggInit (FunctionContext *, BufferVal *)
void AggMerge (FunctionContext *, const BufferVal &, BufferVal *)
BigIntVal AggFinalize (FunctionContext *, const BufferVal &)
void MemTestInit (FunctionContext *, BigIntVal *total)
void MemTestUpdate (FunctionContext *context, const BigIntVal &bytes, BigIntVal *total)
void MemTestMerge (FunctionContext *context, const BigIntVal &src, BigIntVal *dst)
const BigIntVal MemTestSerialize (FunctionContext *context, const BigIntVal &total)
BigIntVal MemTestFinalize (FunctionContext *context, const BigIntVal &total)
Function Documentation
void Agg (FunctionContext * , const StringVal & , const DoubleVal & , StringVal *)
Definition at line 43 of file test-udas.cc.
void Agg (FunctionContext * , const IntVal & , BufferVal *)
Definition at line 52 of file test-udas.cc.
void Agg2Update (FunctionContext * , const StringVal & , const DoubleVal & , StringVal *)
Definition at line 42 of file test-udas.cc.
IntVal AggFinalize (FunctionContext * , const IntVal & i)
Definition at line 37 of file test-udas.cc.
StringVal AggFinalize (FunctionContext * , const StringVal & v)
Definition at line 48 of file test-udas.cc.
BigIntVal AggFinalize (FunctionContext * , const BufferVal &)
Definition at line 56 of file test-udas.cc.
References impala_udf::BigIntVal::null().
void AggFn (FunctionContext * , const IntVal & , IntVal *)
Definition at line 33 of file test-udas.cc.
void AggInit (FunctionContext * , IntVal *)
Definition at line 34 of file test-udas.cc.
void AggInit (FunctionContext * , StringVal *)
Definition at line 45 of file test-udas.cc.
void AggInit (FunctionContext * , BufferVal *)
Definition at line 54 of file test-udas.cc.
void AggMerge (FunctionContext * , const IntVal & , IntVal *)
Definition at line 35 of file test-udas.cc.
void AggMerge (FunctionContext * , const StringVal & , StringVal *)
Definition at line 46 of file test-udas.cc.
void AggMerge (FunctionContext * , const BufferVal & , BufferVal *)
Definition at line 55 of file test-udas.cc.
IntVal AggSerialize (FunctionContext * , const IntVal & i)
Definition at line 36 of file test-udas.cc.
StringVal AggSerialize (FunctionContext * , const StringVal & v)
Definition at line 47 of file test-udas.cc.
void AggUpdate (FunctionContext * , const IntVal & , IntVal *)
Definition at line 30 of file test-udas.cc.
void AggUpdate (FunctionContext * , const IntVal & , const IntVal & , IntVal *)
Definition at line 31 of file test-udas.cc.
void AggUpdate (FunctionContext * , const StringVal & , const DoubleVal & , StringVal *)
Definition at line 41 of file test-udas.cc.
void AggUpdate (FunctionContext * , const IntVal & , BufferVal *)
Definition at line 53 of file test-udas.cc.
BigIntVal MemTestFinalize (FunctionContext * context, const BigIntVal & total)
Definition at line 89 of file test-udas.cc.
References impala_udf::FunctionContext::Free(), impala_udf::AnyVal::is_null, and impala_udf::BigIntVal::val.
Referenced by TEST().
void MemTestInit (FunctionContext * , BigIntVal * total)
Definition at line 63 of file test-udas.cc.
Referenced by TEST().
void MemTestMerge (FunctionContext * context, const BigIntVal & src, BigIntVal * dst)
Definition at line 73 of file test-udas.cc.
References impala_udf::AnyVal::is_null, impala_udf::FunctionContext::TrackAllocation(), and impala_udf::BigIntVal::val.
Referenced by TEST().
const BigIntVal MemTestSerialize (FunctionContext * context, const BigIntVal & total)
Definition at line 83 of file test-udas.cc.
References impala_udf::FunctionContext::Free(), impala_udf::AnyVal::is_null, and impala_udf::BigIntVal::val.
Referenced by TEST().
void MemTestUpdate (FunctionContext * context, const BigIntVal & bytes, BigIntVal * total)
Definition at line 67 of file test-udas.cc.
References impala_udf::AnyVal::is_null, impala_udf::FunctionContext::TrackAllocation(), and impala_udf::BigIntVal::val.
Referenced by TEST().
void TwoArgInit (FunctionContext * , IntVal *)
Definition at line 21 of file test-udas.cc.
void TwoArgMerge (FunctionContext * , const IntVal & , IntVal *)
Definition at line 23 of file test-udas.cc.
void TwoArgUpdate (FunctionContext * , const IntVal & , const StringVal & , IntVal *)
Definition at line 22 of file test-udas.cc.
void VarArgInit (FunctionContext * , IntVal *)
Definition at line 25 of file test-udas.cc.
void VarArgMerge (FunctionContext * , const IntVal & , IntVal *)
Definition at line 27 of file test-udas.cc.
void VarArgUpdate (FunctionContext * , const DoubleVal & , int , const StringVal * , IntVal *)
Definition at line 26 of file test-udas.cc.