Impala: be/src/benchmarks/thread-create-benchmark.cc File Reference
thread-create-benchmark.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include "util/cpu-info.h"
#include "util/debug-util.h"
#include "util/pretty-printer.h"
#include "util/thread.h"
#include "util/stopwatch.h"
#include <boost/thread/thread.hpp>
#include <boost/foreach.hpp>
#include <boost/bind.hpp>
#include "common/names.h"
Functions
void EmptyThread ()
void NativeThreadStarter (int num_threads, const function< void()> &f)
void ImpalaThreadStarter (int num_threads, const function< void()> &f)
void TimeParallelExecutors (int num_threads, int num_threads_per_executor, bool use_native_threads=true)
int main (int argc, char **argv)
Function Documentation
void EmptyThread ()
Definition at line 74 of file thread-create-benchmark.cc.
Referenced by TimeParallelExecutors().
void ImpalaThreadStarter (int num_threads, const function< void()> & f)
Definition at line 87 of file thread-create-benchmark.cc.
References impala::Thread::Join().
Referenced by TimeParallelExecutors().
int main (int argc, char ** argv)
Definition at line 122 of file thread-create-benchmark.cc.
References impala::StopWatch::ElapsedTime(), impala::CpuInfo::Init(), impala::InitThreading(), impala::PrettyPrinter::Print(), impala::StopWatch::Start(), impala::StopWatch::Stop(), and TimeParallelExecutors().
void NativeThreadStarter (int num_threads, const function< void()> & f)
Definition at line 78 of file thread-create-benchmark.cc.
Referenced by TimeParallelExecutors().
void TimeParallelExecutors (int num_threads, int num_threads_per_executor, bool use_native_threads = true)
Definition at line 102 of file thread-create-benchmark.cc.
References impala::StopWatch::ElapsedTime(), EmptyThread(), ImpalaThreadStarter(), NativeThreadStarter(), impala::PrettyPrinter::Print(), impala::StopWatch::Start(), and impala::StopWatch::Stop().
Referenced by main().