Impala: be/src/experiments/tuple-splitter-test.cc File Reference
tuple-splitter-test.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <vector>
#include "common/compiler-util.h"
#include "experiments/data-provider.h"
#include "runtime/mem-pool.h"
#include "runtime/mem-tracker.h"
#include "runtime/string-value.h"
#include "util/cpu-info.h"
#include "util/runtime-profile.h"
#include "common/names.h"
Classes
struct PointerValue
class DataPartitioner
struct DataPartitioner::Partition
struct DataPartitioner::BuildPartition
Macros
#define PRINT_RESULT 0
#define UNUSED_BITS 16
#define USED_BITS 48
#define UNUSED_UPPER_BITS_MASK 0xFFFF000000000000
#define POINTER_LOWER_BITS_MASK 0x0000FFFFFFFFFFFF
Functions
void Memcpy16 (uint8_t *dst, uint8_t *src)
template<class T >
T NextPowerOfTwo (T k)
int main (int argc, char **argv)
Macro Definition Documentation
#define POINTER_LOWER_BITS_MASK 0x0000FFFFFFFFFFFF
Definition at line 34 of file tuple-splitter-test.cc.
Referenced by PointerValue::Get(), and PointerValue::GetPointer().
#define PRINT_RESULT 0
Definition at line 29 of file tuple-splitter-test.cc.
#define UNUSED_BITS 16
Definition at line 31 of file tuple-splitter-test.cc.
Referenced by PointerValue::UpdateValue().
#define UNUSED_UPPER_BITS_MASK 0xFFFF000000000000
Definition at line 33 of file tuple-splitter-test.cc.
#define USED_BITS 48
Definition at line 32 of file tuple-splitter-test.cc.
Referenced by PointerValue::Get(), PointerValue::GetValue(), PointerValue::Update(), PointerValue::UpdatePointer(), and PointerValue::UpdateValue().
Function Documentation
int main (int argc, char ** argv)
Definition at line 365 of file tuple-splitter-test.cc.
References DataPartitioner::Partition::blocks, impala::hash, DataProvider::NextBatch(), impala::obj_pool(), pool, impala::RuntimeProfile::PrettyPrint(), DataProvider::Print(), DataProvider::Reset(), DataProvider::row_size(), DataProvider::total_rows(), tracker, and tuples.
void Memcpy16 (uint8_t * dst, uint8_t * src) inline
Definition at line 40 of file tuple-splitter-test.cc.
Referenced by DataPartitioner::AddData(), and DataPartitioner::Split().
template<class T > T NextPowerOfTwo (T k)
Definition at line 85 of file tuple-splitter-test.cc.
Referenced by DataPartitioner::DataPartitioner().