Impala: be/src/benchmarks/tuple-layout-benchmark.cc File Reference
tuple-layout-benchmark.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <algorithm>
#include "util/benchmark.h"
#include "util/cpu-info.h"
#include "runtime/string-search.h"
#include "common/names.h"
Classes
struct UnpaddedTupleStruct
struct PaddedTupleStruct
struct ImpalaTupleStruct
struct TestData< Decimal >
Macros
#define VALIDATE 0
Functions
void InitTestData (TestData *data)
void TestSequentialUnpadded (int batch_size, void *d)
void TestSequentialPadded (int batch_size, void *d)
void TestSequentialImpala (int batch_size, void *d)
void TestSequentialUnaligned (int batch_size, void *d)
void TestRandomPadded (int batch_size, void *d)
void TestRandomImpala (int batch_size, void *d)
void TestRandomUnaligned (int batch_size, void *d)
int main (int argc, char **argv)
Variables
const int NUM_TUPLES = 1024 * 500
const int MAX_ID = 10000
Macro Definition Documentation
#define VALIDATE 0
Definition at line 39 of file tuple-layout-benchmark.cc.
Function Documentation
void InitTestData (TestData * data)
Definition at line 78 of file tuple-layout-benchmark.cc.
References PaddedTupleStruct::a, PaddedTupleStruct::c, UnpaddedTupleStruct::id, PaddedTupleStruct::id, ImpalaTupleStruct::id, TestData< Decimal >::impala_data, MAX_ID, NUM_TUPLES, TestData< Decimal >::padded_data, TestData< Decimal >::rand_access_order, TestData< Decimal >::unaligned_data, TestData< Decimal >::unpadded_data, PaddedTupleStruct::UnpaddedSize, UnpaddedTupleStruct::val, PaddedTupleStruct::val, and ImpalaTupleStruct::val.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 211 of file tuple-layout-benchmark.cc.
References impala::Benchmark::AddBenchmark(), impala::Benchmark::GetMachineInfo(), impala::CpuInfo::Init(), InitTestData(), impala::Benchmark::Measure(), TestData< Decimal >::result, TestRandomImpala(), TestRandomPadded(), TestRandomUnaligned(), TestSequentialImpala(), TestSequentialPadded(), TestSequentialUnaligned(), and TestSequentialUnpadded().
void TestRandomImpala (int batch_size, void * d)
Definition at line 184 of file tuple-layout-benchmark.cc.
References ImpalaTupleStruct::id, TestData< Decimal >::impala_data, MAX_ID, NUM_TUPLES, TestData< Decimal >::rand_access_order, TestData< Decimal >::result, and ImpalaTupleStruct::val.
Referenced by main().
void TestRandomPadded (int batch_size, void * d)
Definition at line 172 of file tuple-layout-benchmark.cc.
References PaddedTupleStruct::id, MAX_ID, NUM_TUPLES, TestData< Decimal >::padded_data, TestData< Decimal >::rand_access_order, TestData< Decimal >::result, and PaddedTupleStruct::val.
Referenced by main().
void TestRandomUnaligned (int batch_size, void * d)
Definition at line 196 of file tuple-layout-benchmark.cc.
References MAX_ID, NUM_TUPLES, TestData< Decimal >::rand_access_order, TestData< Decimal >::result, TestData< Decimal >::unaligned_data, and PaddedTupleStruct::UnpaddedSize.
Referenced by main().
void TestSequentialImpala (int batch_size, void * d)
Definition at line 146 of file tuple-layout-benchmark.cc.
References ImpalaTupleStruct::id, TestData< Decimal >::impala_data, MAX_ID, NUM_TUPLES, TestData< Decimal >::result, and ImpalaTupleStruct::val.
Referenced by main().
void TestSequentialPadded (int batch_size, void * d)
Definition at line 135 of file tuple-layout-benchmark.cc.
References PaddedTupleStruct::id, MAX_ID, NUM_TUPLES, TestData< Decimal >::padded_data, TestData< Decimal >::result, and PaddedTupleStruct::val.
Referenced by main().
void TestSequentialUnaligned (int batch_size, void * d)
Definition at line 157 of file tuple-layout-benchmark.cc.
References MAX_ID, NUM_TUPLES, TestData< Decimal >::result, TestData< Decimal >::unaligned_data, and PaddedTupleStruct::UnpaddedSize.
Referenced by main().
void TestSequentialUnpadded (int batch_size, void * d)
Definition at line 124 of file tuple-layout-benchmark.cc.
References UnpaddedTupleStruct::id, MAX_ID, NUM_TUPLES, TestData< Decimal >::result, TestData< Decimal >::unpadded_data, and UnpaddedTupleStruct::val.
Referenced by main().
Variable Documentation
const int MAX_ID = 10000
Definition at line 42 of file tuple-layout-benchmark.cc.
Referenced by InitTestData(), TestRandomImpala(), TestRandomPadded(), TestRandomUnaligned(), TestSequentialImpala(), TestSequentialPadded(), TestSequentialUnaligned(), and TestSequentialUnpadded().
const int NUM_TUPLES = 1024 * 500
Definition at line 41 of file tuple-layout-benchmark.cc.
Referenced by InitTestData(), main(), TestRandomImpala(), TestRandomPadded(), TestRandomUnaligned(), TestSequentialImpala(), TestSequentialPadded(), TestSequentialUnaligned(), and TestSequentialUnpadded().