Impala: be/src/benchmarks/uuid-benchmark.cc File Reference
uuid-benchmark.cc File Reference
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <vector>
#include <sstream>
#include "runtime/string-value.h"
#include "util/benchmark.h"
#include "util/cpu-info.h"
#include "util/thrift-util.h"
#include "gen-cpp/Types_types.h"
#include <boost/shared_ptr.hpp>
#include <boost/thread/mutex.hpp>
#include <boost/thread.hpp>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/TApplicationException.h>
#include <thrift/transport/TBufferTransports.h>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>
Functions
void TestSharedGenerator (int n)
void TestOwnGenerator (int n)
void TestOwnThreaded (int size, void *d)
void TestSharedThreaded (int size, void *d)
int main (int argc, char **argv)
Variables
mutex global_mutex
static
boost::uuids::random_generator uuid_generator_
static int NUM_REPS = 100
Function Documentation
int main (int argc, char ** argv)
Definition at line 86 of file uuid-benchmark.cc.
References impala::Benchmark::AddBenchmark(), impala::CpuInfo::Init(), impala::Benchmark::Measure(), TestOwnThreaded(), and TestSharedThreaded().
void TestOwnGenerator (int n)
Definition at line 53 of file uuid-benchmark.cc.
Referenced by TestOwnThreaded(), and TestSharedThreaded().
void TestOwnThreaded (int size, void * d)
Definition at line 60 of file uuid-benchmark.cc.
References TestOwnGenerator().
Referenced by main().
void TestSharedGenerator (int n)
Definition at line 46 of file uuid-benchmark.cc.
References global_mutex, and uuid_generator_.
void TestSharedThreaded (int size, void * d)
Definition at line 73 of file uuid-benchmark.cc.
References TestOwnGenerator().
Referenced by main().
Variable Documentation
mutex global_mutex
Definition at line 41 of file uuid-benchmark.cc.
Referenced by TestSharedGenerator().
int NUM_REPS = 100 static
Definition at line 44 of file uuid-benchmark.cc.
boost::uuids::random_generator uuid_generator_ static
Definition at line 42 of file uuid-benchmark.cc.
Referenced by impala::ImpalaServer::OpenSession(), and TestSharedGenerator().