#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
### BEGIN INIT INFO
# Provides:          statestored
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Should-Start:      $time $network
# Should-Stop:       $time $network
# Short-Description: Apache Impala statestore service
### END INIT INFO

IMPALA_HOME=/opt/impala
IMPALA_SHELL_CMD=${IMPALA_HOME}/bin/impala.sh
IMPALA_SERVICE=statestored

main() {
  case ${1} in
    start|stop|restart|status) su impala -s /bin/bash -c "${IMPALA_SHELL_CMD} ${1} ${IMPALA_SERVICE}" ;;
    force-reload) su impala -s /bin/sh -c "${IMPALA_SHELL_CMD} restart ${IMPALA_SERVICE}" ;;
    *) exit 2 ;;
  esac
}

main ${@}
